Photon::Pun::UtilityScripts::OnJoinedInstantiate
SpawnSequence
Transform Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnPosition
SpawnSequence Photon.Pun.UtilityScripts.OnJoinedInstantiate.Sequence
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint.
List<Transform> Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnPoints
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint.
bool Photon.Pun.UtilityScripts.OnJoinedInstantiate.UseRandomOffset
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint.
float Photon.Pun.UtilityScripts.OnJoinedInstantiate.RandomOffset
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetRandomOffset.
bool Photon.Pun.UtilityScripts.OnJoinedInstantiate.ClampY
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetRandomOffset.
List<GameObject> Photon.Pun.UtilityScripts.OnJoinedInstantiate.PrefabsToInstantiate
bool Photon.Pun.UtilityScripts.OnJoinedInstantiate.AutoSpawnObjects
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinedRoom.
Stack<GameObject> Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnedObjects
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.DespawnObjects, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnObjects.
int Photon.Pun.UtilityScripts.OnJoinedInstantiate.spawnedAsActorId
int Photon.Pun.UtilityScripts.OnJoinedInstantiate.lastUsedSpawnPointIndex
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnEnable()
References Photon.Pun.PhotonNetwork.AddCallbackTarget.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnDisable()
References Photon.Pun.PhotonNetwork.RemoveCallbackTarget.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References Photon.Pun.UtilityScripts.OnJoinedInstantiate.AutoSpawnObjects, Photon.Realtime.Player.HasRejoined, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnObjects.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnObjects()
References Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint, Photon.Pun.PhotonNetwork.Instantiate, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnedObjects.
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinedRoom.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.DespawnObjects(bool localOnly)
Destroy all objects that have been spawned by this component for this client.
localOnly Use Object.Destroy rather than PhotonNetwork.Destroy.
References Photon.Pun.PhotonNetwork.Destroy, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnedObjects.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnFriendListUpdate(List< FriendInfo > friendList)
Called when the server sent the response to a FindFriends request.
After calling OpFindFriends, the Master Server will cache the friend list and send updates to the friend list. The friends includes the name, userId, online state and the room (if any) for each requested user/friend. Use the friendList to update your UI and store it, if the UI should highlight changes.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnCreatedRoom()
Called when this client created a room and entered it.
OnJoinedRoom() will be called as well. This callback is only called on the client which created a room (see OpCreateRoom). As any client might close (or drop connection) anytime, there is a chance that the creator of a room does not execute OnCreatedRoom. If you need specific room properties or a "start signal", implement OnMasterClientSwitched() and make each new MasterClient check the room's state.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
Creating a room may fail for various reasons. Most often, the room already exists (roomname in use) or the RoomOptions clash and it's impossible to create the room. When creating a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
Joining a room may fail for various reasons. Most often, the room is full or does not exist anymore (due to someone else being faster or closing the room). When joining a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinRandomFailed(short returnCode, string message)
Called when a previous OpJoinRandom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). This operation is only ever sent to the Master Server. Once a room is found by the Master Server, the client will head off to the designated Game Server and use the operation Join on the Game Server. When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms. returnCode Operation ReturnCode from the server. message Debug message for the error.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
virtual void Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint(out Vector3 spawnPos, out Quaternion spawnRot)
Gets the next SpawnPoint from the list using the SpawnSequence, and applies RandomOffset (if used) to the transform matrix.
Override this method with any custom code for coming up with a spawn location. This method is used by AutoSpawn.
References Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetRandomOffset, Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint, Photon.Pun.UtilityScripts.OnJoinedInstantiate.UseRandomOffset.
virtual Transform Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint()
Get the transform of the next SpawnPoint from the list, selected using the SpawnSequence setting.
RandomOffset is not applied, only the transform of the SpawnPoint is returned. Override this method to change how Spawn Point transform is selected. Return the transform you want to use as a spawn point.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.UtilityScripts.OnJoinedInstantiate.lastUsedSpawnPointIndex, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.UtilityScripts.OnJoinedInstantiate.Sequence, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnPoints.
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint, Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnObjects.
virtual Vector3 Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetRandomOffset()
When UseRandomeOffset is enabled, this method is called to produce a Vector3 offset.
The default implementation clamps the Y value to zero. You may override this with your own implementation.
References Photon.Pun.UtilityScripts.OnJoinedInstantiate.ClampY, Photon.Pun.UtilityScripts.OnJoinedInstantiate.RandomOffset.
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint.