SInt::Netcode::PhotonPUN::MenuManager
MenuManager SInt.Netcode.PhotonPUN.MenuManager.Instance
Referenced by Launcher.CheckAllPlayersReady, Launcher.CreateRoom, Launcher.JoinRoom, Launcher.LeaveRoom, Launcher.OnCreateRoomFailed, Launcher.OnJoinedLobby, Launcher.OnJoinedRoom, Launcher.OnJoinRoomFailed, Launcher.OnLeftRoom.
Menu [] SInt.Netcode.PhotonPUN.MenuManager.menus
bool SInt.Netcode.PhotonPUN.MenuManager.initMenusViaChildren
void SInt.Netcode.PhotonPUN.MenuManager.Awake()
void SInt.Netcode.PhotonPUN.MenuManager.OpenMenu(string menuName)
References SInt.Netcode.PhotonPUN.MenuManager.CloseMenu, SInt.Netcode.PhotonPUN.Menu.Open.
Referenced by Launcher.CheckAllPlayersReady, Launcher.CreateRoom, Launcher.JoinRoom, Launcher.LeaveRoom, Launcher.OnCreateRoomFailed, Launcher.OnJoinedLobby, Launcher.OnJoinedRoom, Launcher.OnJoinRoomFailed, Launcher.OnLeftRoom.
void SInt.Netcode.PhotonPUN.MenuManager.OpenMenu(Menu menu)
References SInt.Netcode.PhotonPUN.MenuManager.CloseMenu, SInt.Netcode.PhotonPUN.Menu.Open.
void SInt.Netcode.PhotonPUN.MenuManager.CloseMenu(Menu menu)
References SInt.Netcode.PhotonPUN.Menu.Close.
Referenced by SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.