Photon::Pun::Demo::Procedural::WorldGenerator
readonly string Photon.Pun.Demo.Procedural.WorldGenerator.SeedPropertiesKey
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate.
readonly string Photon.Pun.Demo.Procedural.WorldGenerator.WorldSizePropertiesKey
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate.
readonly string Photon.Pun.Demo.Procedural.WorldGenerator.ClusterSizePropertiesKey
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate.
readonly string Photon.Pun.Demo.Procedural.WorldGenerator.WorldTypePropertiesKey
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate.
Material [] Photon.Pun.Demo.Procedural.WorldGenerator.WorldMaterials
WorldGenerator Photon.Pun.Demo.Procedural.WorldGenerator.instance
WorldGenerator Photon.Pun.Demo.Procedural.WorldGenerator.Instance
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake, Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate, Photon.Pun.Demo.Procedural.ProceduralController.Update.
int Photon.Pun.Demo.Procedural.WorldGenerator.Seed
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake, Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties.
WorldSize Photon.Pun.Demo.Procedural.WorldGenerator.WorldSize
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake.
ClusterSize Photon.Pun.Demo.Procedural.WorldGenerator.ClusterSize
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake.
WorldType Photon.Pun.Demo.Procedural.WorldGenerator.WorldType
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake.
Dictionary<int, GameObject> Photon.Pun.Demo.Procedural.WorldGenerator.clusterList
void Photon.Pun.Demo.Procedural.WorldGenerator.Awake()
void Photon.Pun.Demo.Procedural.WorldGenerator.CreateWorld()
Called whenever a client receives a Custom Room Properties update containing all necessary information for creating a world.
If there is currently a world generation process running, it will be stopped automatically. Also if there is a world already existing, it will be destroyed before the new one gets created.
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.OnRoomPropertiesUpdate.
void Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties()
Whenever the 'Confirm' button on the Control Panel is clicked by the MasterClient, the Room Properties will be updated with the settings he defined.
References Photon.Pun.Demo.Procedural.WorldGenerator.ClusterSizePropertiesKey, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.Demo.Procedural.WorldGenerator.Seed, Photon.Pun.Demo.Procedural.WorldGenerator.SeedPropertiesKey, Photon.Realtime.Room.SetCustomProperties, Photon.Pun.Demo.Procedural.WorldGenerator.WorldSizePropertiesKey, Photon.Pun.Demo.Procedural.WorldGenerator.WorldTypePropertiesKey.
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake.
void Photon.Pun.Demo.Procedural.WorldGenerator.DecreaseBlockHeight(int clusterId, int blockId)
Decreases the height of a certain Block from a certain Cluster.
References Photon.Pun.Demo.Procedural.Cluster.DecreaseBlockHeight.
Referenced by Photon.Pun.Demo.Procedural.ProceduralController.Update.
void Photon.Pun.Demo.Procedural.WorldGenerator.IncreaseBlockHeight(int clusterId, int blockId)
Increases the height of a certain Block from a certain Cluster.
References Photon.Pun.Demo.Procedural.Cluster.IncreaseBlockHeight.
Referenced by Photon.Pun.Demo.Procedural.ProceduralController.Update.
void Photon.Pun.Demo.Procedural.WorldGenerator.DestroyWorld()
Destroys each Block from each Cluster before actually destroying the Cluster itself.
IEnumerator Photon.Pun.Demo.Procedural.WorldGenerator.GenerateWorld()
Generates a new world based on the settings made either by the MasterClient on the Ingame Control Panel or after receiving the new settings from the Custom Room Properties update.