Launcher
Launcher Launcher.Instance
Referenced by SInt.Netcode.PhotonPUN.RoomListItem.OnClick.
readonly string Launcher.StartGameSceneName
Referenced by StartGame.
TMP_InputField Launcher.CreateInput
TMP_InputField Launcher.JoinInput
TMP_Text Launcher.errorMainText
TMP_Text Launcher.errorText
TMP_Text Launcher.roomNameText
Transform Launcher.roomListContent
GameObject Launcher.roomListItemPrefab
Transform Launcher.playerListContent
GameObject Launcher.PlayerListItemPrefab
Button Launcher.hostReadyButton
Button Launcher.readyButton
GameObject Launcher.loadingP1
GameObject Launcher.loadingP2
GameObject Launcher.checkmarkP1
GameObject Launcher.checkmarkP2
bool Launcher.readyP1
bool Launcher.readyP2
ExitGames.Client.Photon.Hashtable Launcher.playerProperties
void Launcher.Awake()
void Launcher.Start()
void Launcher.UpdateUI(Player targetPlayer)
void Launcher.Update()
override void Launcher.OnConnectedToMaster()
Called when the client is connected to the Master Server and ready for matchmaking and other tasks.
The list of available rooms won't become available unless you join a lobby via LoadBalancingClient.OpJoinLobby. You can join rooms and create them even without being in a lobby. The default lobby is used in that case.
References Photon.Pun.PhotonNetwork.AutomaticallySyncScene, Photon.Pun.PhotonNetwork.JoinLobby.
override void Launcher.OnJoinedLobby()
Called on entering a lobby on the Master Server.
The actual room-list updates will call OnRoomListUpdate. While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud). The room list gets available via OnRoomListUpdate.
References SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
void Launcher.CreateRoom()
References Photon.Pun.PhotonNetwork.CreateRoom, SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
void Launcher.JoinRoom()
References SInt.Netcode.PhotonPUN.MenuManager.Instance, Photon.Pun.PhotonNetwork.JoinRoom, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
Referenced by SInt.Netcode.PhotonPUN.RoomListItem.OnClick.
override void Launcher.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References AssignRoleRandomly, Photon.Pun.PhotonNetwork.CurrentRoom, SInt.Netcode.PhotonPUN.MenuManager.Instance, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Realtime.Room.Name, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu, Photon.Pun.PhotonNetwork.PlayerList.
override void Launcher.OnMasterClientSwitched(Player newMasterClient)
Called after switching to a new MasterClient when the current one leaves.
This is not called when this client enters a room. The former MasterClient is still in the player list when this method get called.
References Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer.
override void Launcher.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
The most common cause to fail creating a room, is when a title relies on fixed room-names and the room already exists. returnCode Operation ReturnCode from the server. message Debug message for the error.
References SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
override void Launcher.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). returnCode Operation ReturnCode from the server. message Debug message for the error.
References SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
void Launcher.StartGame()
References Photon.Pun.PhotonNetwork.LoadLevel, StartGameSceneName.
Referenced by CheckAllPlayersReady.
void Launcher.BackToMenu()
void Launcher.LeaveRoom()
References SInt.Netcode.PhotonPUN.MenuManager.Instance, Photon.Pun.PhotonNetwork.LeaveRoom, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
void Launcher.JoinRoom(RoomInfo info)
References SInt.Netcode.PhotonPUN.MenuManager.Instance, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Realtime.RoomInfo.Name, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
override void Launcher.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
References SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu.
override void Launcher.OnRoomListUpdate(List< RoomInfo > roomList)
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server.
Each item is a RoomInfo which might include custom properties (provided you defined those as lobby-listed when creating a room). Not all types of lobbies provide a listing of rooms to the client. Some are silent and specialized for server-side matchmaking.
override void Launcher.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
void Launcher.OnClick_Ready()
References CheckAllPlayersReady, Photon.Realtime.Player.CustomProperties, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Realtime.Player.SetCustomProperties.
override void Launcher.OnPlayerPropertiesUpdate(Player targetPlayer, ExitGames.Client.Photon.Hashtable changedProps)
References CheckAllPlayersReady.
IEnumerator Launcher.CheckAllPlayersReady()
References Photon.Pun.PhotonNetwork.CurrentRoom, SInt.Netcode.PhotonPUN.MenuManager.Instance, SInt.Netcode.PhotonPUN.MenuManager.OpenMenu, Photon.Realtime.Room.PlayerCount, Photon.Pun.PhotonNetwork.PlayerList, StartGame.
Referenced by OnClick_Ready, OnPlayerPropertiesUpdate.
void Launcher.AssignRoleRandomly()
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.MasterClient, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties.
Referenced by OnJoinedRoom.