Photon::Pun::Demo::Shared::DocLinks
DocTypes
Products
Versions
Languages
Versions Photon.Pun.Demo.Shared.DocLinks.Version
The version to generate links for
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetApiLink, Photon.Pun.Demo.Shared.DocLinks.GetDocLink, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
Languages Photon.Pun.Demo.Shared.DocLinks.Language
The language to generate links with
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetApiLink, Photon.Pun.Demo.Shared.DocLinks.GetDocLink, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
Products Photon.Pun.Demo.Shared.DocLinks.Product
The product to generate links for
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetApiLink, Photon.Pun.Demo.Shared.DocLinks.GetDocLink, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
string Photon.Pun.Demo.Shared.DocLinks.ApiUrlRoot
The API URL format.
0 is the Language 1 is the Product 2 is the Version 3 is the custom part passed to generate the link with
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetApiLink.
string Photon.Pun.Demo.Shared.DocLinks.DocUrlFormat
The Doc URL format.
0 is the Language 1 is the Product 2 is the Version 3 is the custom part passed to generate the link with
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetDocLink.
Dictionary<Products,string> Photon.Pun.Demo.Shared.DocLinks.ProductsFolders
LookUp dictionnary for doc versions to avoid parsing this every link request
Dictionary<Languages,string> Photon.Pun.Demo.Shared.DocLinks.ApiLanguagesFolder
LookUp dictionnary for api languages to avoid parsing this every link request
Dictionary<Languages,string> Photon.Pun.Demo.Shared.DocLinks.DocLanguagesFolder
LookUp dictionnary for doc languages to avoid parsing this every link request
Dictionary<Versions,string> Photon.Pun.Demo.Shared.DocLinks.VersionsFolder
LookUp dictionnary for doc versions to avoid parsing this every link request
static string Photon.Pun.Demo.Shared.DocLinks.GetLink(DocTypes type, string reference)
Gets a documentation link given a reference
The link. type Type. reference Reference.
References Photon.Pun.Demo.Shared.DocLinks.GetApiLink, Photon.Pun.Demo.Shared.DocLinks.GetDocLink.
Referenced by Photon.Pun.Demo.Cockpit.DocLinkButton.OnPointerClick.
static string Photon.Pun.Demo.Shared.DocLinks.GetApiLink(string reference)
Gets the API link given a reference
The API link. reference Reference.
References Photon.Pun.Demo.Shared.DocLinks.ApiUrlRoot, Photon.Pun.Demo.Shared.DocLinks.Language, Photon.Pun.Demo.Shared.DocLinks.Product, Photon.Pun.Demo.Shared.DocLinks.Version.
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetLink.
static string Photon.Pun.Demo.Shared.DocLinks.GetDocLink(string reference)
Gets the Doc link given a reference
The document link. reference Reference.
References Photon.Pun.Demo.Shared.DocLinks.DocUrlFormat, Photon.Pun.Demo.Shared.DocLinks.Language, Photon.Pun.Demo.Shared.DocLinks.Product, Photon.Pun.Demo.Shared.DocLinks.Version.
Referenced by Photon.Pun.Demo.Shared.DocLinks.GetLink.