Photon::Pun::Simple::VitalUIBase
TargetField
VitalNameType Photon.Pun.Simple.VitalUIBase.targetVital
Referenced by Photon.Pun.Simple.VitalUIBase.ApplyVitalsSource.
TargetField Photon.Pun.Simple.VitalUIBase.targetField
Referenced by Photon.Pun.Simple.VitalUI.UpdateGraphics.
Vitals Photon.Pun.Simple.VitalUIBase.Vitals
Vital Photon.Pun.Simple.VitalUIBase.Vital
int Photon.Pun.Simple.VitalUIBase.vitalIndex
Referenced by Photon.Pun.Simple.VitalUIBase.ApplyVitalsSource, Photon.Pun.Simple.VitalUI.AutoAlign.
Vital Photon.Pun.Simple.VitalUIBase.vital
Referenced by Photon.Pun.Simple.VitalUIBase.OnDestroy, Photon.Pun.Simple.VitalUIBase.OnVitalValueChange, Photon.Pun.Simple.VitalUI.Recalculate, Photon.Pun.Simple.VitalUIBase.Start, Photon.Pun.Simple.VitalUI.UpdateGraphics.
override IVitalsSystem Photon.Pun.Simple.VitalUIBase.ApplyVitalsSource(Object vs)
References Photon.Pun.Simple.VitalUIBase.Recalculate, Photon.Pun.Simple.VitalUIBase.targetVital, Photon.Pun.Simple.VitalUIBase.vitalIndex.
Referenced by Photon.Pun.Simple.VitalUIBase.Awake.
abstract void Photon.Pun.Simple.VitalUIBase.Recalculate()
Referenced by Photon.Pun.Simple.VitalUIBase.ApplyVitalsSource.
override void Photon.Pun.Simple.VitalUIBase.OnChangeOwnedVitals(IVitalsSystem added, IVitalsSystem removed)
References Photon.Pun.Simple.Component, Photon.Pun.Simple.OwnedIVitals.LastItem, Photon.Pun.Simple.IVitalsSystem.Vitals, Photon.Pun.Simple.VitalsUISrcBase.vitals, Photon.Pun.Simple.VitalsUISrcBase.vitalsSource.
void Photon.Pun.Simple.VitalUIBase.OnVitalParamChange(Vital vital)
virtual void Photon.Pun.Simple.VitalUIBase.OnVitalValueChange(Vital vital)
References Photon.Pun.Simple.VitalUIBase.UpdateGraphics, Photon.Pun.Simple.VitalUIBase.vital.
abstract void Photon.Pun.Simple.VitalUIBase.UpdateGraphics(Vital vital)
Referenced by Photon.Pun.Simple.VitalUIBase.OnVitalValueChange, Photon.Pun.Simple.VitalUIBase.Start.
virtual void Photon.Pun.Simple.VitalUIBase.Awake()
References Photon.Pun.Simple.VitalUIBase.ApplyVitalsSource, Photon.Pun.Simple.OwnedIVitals.iOnChangeOwnedVitals, Photon.Pun.Simple.VitalsUISrcBase.monitor, Photon.Pun.Simple.VitalsUISrcBase.vitalsSource.
virtual void Photon.Pun.Simple.VitalUIBase.Start()
References Photon.Pun.Simple.VitalUIBase.UpdateGraphics, Photon.Pun.Simple.VitalUIBase.vital.
virtual void Photon.Pun.Simple.VitalUIBase.OnDestroy()
References Photon.Pun.Simple.OwnedIVitals.iOnChangeOwnedVitals, Photon.Pun.Simple.VitalsUISrcBase.monitor, Photon.Pun.Simple.Vital.RemoveIOnVitalChange, Photon.Pun.Simple.VitalUIBase.vital.