Photon::Compression::ArraySerializeExt
const string Photon.Compression.ArraySerializeExt.bufferOverrunMsg
static void Photon.Compression.ArraySerializeExt.Zero(this byte[] buffer, int startByte, int endByte)
Zero out all array values.
Start and End values are inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this byte[] buffer, int startByte)
Zero out all array values.
Start value is inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this byte[] buffer)
Zero out all array values.
static void Photon.Compression.ArraySerializeExt.Zero(this ushort[] buffer, int startByte, int endByte)
Zero out all array values.
Start and End values are inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this ushort[] buffer, int startByte)
Zero out all array values.
Start value is inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this ushort[] buffer)
Zero out all array values.
static void Photon.Compression.ArraySerializeExt.Zero(this uint[] buffer, int startByte, int endByte)
Zero out all array values.
Start and End values are inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this uint[] buffer, int startByte)
Zero out all array values.
Start value is inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this uint[] buffer)
Zero out all array values.
static void Photon.Compression.ArraySerializeExt.Zero(this ulong[] buffer, int startByte, int endByte)
Zero out all array values.
Start and End values are inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this ulong[] buffer, int startByte)
Zero out all array values.
Start value is inclusive.
static void Photon.Compression.ArraySerializeExt.Zero(this ulong[] buffer)
Zero out all array values.
static void Photon.Compression.ArraySerializeExt.WriteSigned(this byte[] buffer, int value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteSigned(this uint[] buffer, int value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteSigned(this ulong[] buffer, int value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteSigned(this byte[] buffer, long value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteSigned(this uint[] buffer, long value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteSigned(this ulong[] buffer, long value, ref int bitposition, int bits)
static int Photon.Compression.ArraySerializeExt.ReadSigned(this byte[] buffer, ref int bitposition, int bits)
static int Photon.Compression.ArraySerializeExt.ReadSigned(this uint[] buffer, ref int bitposition, int bits)
static int Photon.Compression.ArraySerializeExt.ReadSigned(this ulong[] buffer, ref int bitposition, int bits)
static long Photon.Compression.ArraySerializeExt.ReadSigned64(this byte[] buffer, ref int bitposition, int bits)
static long Photon.Compression.ArraySerializeExt.ReadSigned64(this uint[] buffer, ref int bitposition, int bits)
static long Photon.Compression.ArraySerializeExt.ReadSigned64(this ulong[] buffer, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteFloat(this byte[] buffer, float value, ref int bitposition)
Converts a float to a 32bit uint with ByteConverter, then writes those 32 bits to the buffer.
buffer The array we are reading from. value The float value to write. bitposition The bit position in the array we start the read at. Will be incremented by 32 bits.
References Photon.Compression.ArraySerializeExt.Write.
static float Photon.Compression.ArraySerializeExt.ReadFloat(this byte[] buffer, ref int bitposition)
Reads a uint32 from the buffer, and converts that back to a float with a ByteConverter cast.
If performance is a concern, you can call the primary (ByteConverter)byte[].Read()) buffer The array we are reading from. bitposition The bit position in the array we start the read at. Will be incremented by 32 bits.
References Photon.Compression.ArraySerializeExt.Read.
static void Photon.Compression.ArraySerializeExt.Append(this byte[] buffer, ulong value, ref int bitposition, int bits)
Faster Primary Write method specifically specifically for sequential writes.
Doesn't preserve existing data past the write point in exchnage for a faster write. buffer value bitposition bits
static void Photon.Compression.ArraySerializeExt.Append(this uint[] buffer, ulong value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.Append(this uint[] buffer, uint value, ref int bitposition, int bits)
Faster Primary Write method specifically specifically for sequential writes.
Doesn't preserve existing data past the write point in exchnage for a faster write.
static void Photon.Compression.ArraySerializeExt.Append(this ulong[] buffer, ulong value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.Write(this byte[] buffer, ulong value, ref int bitposition, int bits)
This is the primary byte[].Write() method.
All other byte[].Write methods lead to this one, so when performance matters, cast using (ByteConverter)value and use this method. buffer value bitposition bits
Referenced by Photon.Compression.ArraySerializeExt.Write, Photon.Compression.ArraySerializeExt.WriteFloat.
static void Photon.Compression.ArraySerializeExt.Write(this uint[] buffer, ulong value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.Write(this ulong[] buffer, ulong value, ref int bitposition, int bits)
static void Photon.Compression.ArraySerializeExt.WriteBool(this ulong[] buffer, bool b, ref int bitposition)
static void Photon.Compression.ArraySerializeExt.WriteBool(this uint[] buffer, bool b, ref int bitposition)
static void Photon.Compression.ArraySerializeExt.WriteBool(this byte[] buffer, bool b, ref int bitposition)
static ulong Photon.Compression.ArraySerializeExt.Read(this byte[] buffer, ref int bitposition, int bits)
This is the Primary byte[].Read() method.
All other byte[].ReadXXX() methods lead here. For maximum performance use this for all Read() calls and cast accordingly. buffer The array we are deserializing from. bitposition The position in the array (in bits) where we will begin reading. bits The number of bits to read. UInt64 read value. Cast this to the intended type.
Referenced by Photon.Compression.ArraySerializeExt.Read, Photon.Compression.ArraySerializeExt.ReadBool, Photon.Compression.ArraySerializeExt.ReadByte, Photon.Compression.ArraySerializeExt.ReadChar, Photon.Compression.ArraySerializeExt.ReadFloat, Photon.Compression.ArraySerializeExt.ReadUInt16, Photon.Compression.ArraySerializeExt.ReadUInt32, Photon.Compression.ArraySerializeExt.ReadUInt64, Photon.Compression.ArraySerializeExt.ReadUInt8.
static ulong Photon.Compression.ArraySerializeExt.Read(this uint[] buffer, ref int bitposition, int bits)
This is the Primary uint[].Read() method.
All other uint[].ReadXXX methods lead here. For maximum performance use this for all Read() calls and cast accordingly. buffer The array we are deserializing from. bitposition The position in the array (in bits) where we will begin reading. bits The number of bits to read. UInt64 read value. Cast this to the intended type.
static ulong Photon.Compression.ArraySerializeExt.Read(this ulong[] buffer, ref int bitposition, int bits)
This is the Primary ulong[].Read() method.
All other ulong[].ReadXXX methods lead here. For maximum performance use this for all Read() calls and cast accordingly. buffer The array we are deserializing from. bitposition The position in the array (in bits) where we will begin reading. bits The number of bits to read. UInt64 read value. Cast this to the intended type.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this byte[] buffer, ref int bitposition, int bits=64)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this uint[] buffer, ref int bitposition, int bits=64)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this ulong[] buffer, ref int bitposition, int bits=64)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this byte[] buffer, ref int bitposition, int bits=32)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this uint[] buffer, ref int bitposition, int bits=32)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this ulong[] buffer, ref int bitposition, int bits=32)
References Photon.Compression.ArraySerializeExt.Read.
static ushort Photon.Compression.ArraySerializeExt.ReadUInt16(this byte[] buffer, ref int bitposition, int bits=16)
References Photon.Compression.ArraySerializeExt.Read.
static ushort Photon.Compression.ArraySerializeExt.ReadUInt16(this uint[] buffer, ref int bitposition, int bits=16)
References Photon.Compression.ArraySerializeExt.Read.
static ushort Photon.Compression.ArraySerializeExt.ReadUInt16(this ulong[] buffer, ref int bitposition, int bits=16)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadByte(this byte[] buffer, ref int bitposition, int bits=8)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadByte(this uint[] buffer, ref int bitposition, int bits=32)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadByte(this ulong[] buffer, ref int bitposition, int bits)
References Photon.Compression.ArraySerializeExt.Read.
static bool Photon.Compression.ArraySerializeExt.ReadBool(this ulong[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static bool Photon.Compression.ArraySerializeExt.ReadBool(this uint[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static bool Photon.Compression.ArraySerializeExt.ReadBool(this byte[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static char Photon.Compression.ArraySerializeExt.ReadChar(this ulong[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static char Photon.Compression.ArraySerializeExt.ReadChar(this uint[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static char Photon.Compression.ArraySerializeExt.ReadChar(this byte[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static void Photon.Compression.ArraySerializeExt.ReadOutSafe(this ulong[] source, int srcStartPos, byte[] target, ref int bitposition, int bits)
Read the contents of one array buffer to another.
This safe version doesn't use Unsafe, and may be up to 3x slower than ReadArrayOutUnsafe(). source Source array to copy from. srcStartPos Bit position in source to start reading frome. target Target array bitposition Current write position for target. Will start writing at this bitposition. Value gets incremented. bits Number of bits to readout. Typically the current write position of the source buffer.
static void Photon.Compression.ArraySerializeExt.ReadOutSafe(this ulong[] source, int srcStartPos, ulong[] target, ref int bitposition, int bits)
Read the contents of one array buffer to another.
This safe version doesn't use Unsafe, and may be up to 3x slower than ReadArrayOutUnsafe(). source Source array to copy from. srcStartPos Bit position in source to start reading frome. target Target array bitposition Current write position for target. Will start writing at this bitposition. Value gets incremented. bits Number of bits to readout. Typically the current write position of the source buffer.
static void Photon.Compression.ArraySerializeExt.ReadOutSafe(this byte[] source, int srcStartPos, ulong[] target, ref int bitposition, int bits)
Read the contents of one array buffer to another.
This safe version doesn't use Unsafe, and may be up to 3x slower than ReadArrayOutUnsafe(). source Source array to copy from. srcStartPos Bit position in source to start reading frome. target Target array bitposition Current write position for target. Will start writing at this bitposition. Value gets incremented. bits Number of bits to readout. Typically the current write position of the source buffer.
static void Photon.Compression.ArraySerializeExt.ReadOutSafe(this byte[] source, int srcStartPos, byte[] target, ref int bitposition, int bits)
Read the contents of one array buffer to another.
This safe version doesn't use Unsafe, and may be up to 3x slower than ReadArrayOutUnsafe(). source Source array to copy from. srcStartPos Bit position in source to start reading frome. target Target array bitposition Current write position for target. Will start writing at this bitposition. Value gets incremented. bits Number of bits to readout. Typically the current write position of the source buffer.
static ulong Photon.Compression.ArraySerializeExt.IndexAsUInt64(this byte[] buffer, int index)
Treats buffer as ulong[] and returns the index value of that virtual ulong[]
index The index of the virtual ulong[]
static ulong Photon.Compression.ArraySerializeExt.IndexAsUInt64(this uint[] buffer, int index)
Treats buffer as ulong[] and returns the index value of that virtual ulong[]
index The index of the virtual ulong[]
static uint Photon.Compression.ArraySerializeExt.IndexAsUInt32(this byte[] buffer, int index)
Treats buffer as uint[] and returns the index value of that virtual uint[]
index The index of the virtual uint[]
static uint Photon.Compression.ArraySerializeExt.IndexAsUInt32(this ulong[] buffer, int index)
Treats buffer as uint[] and returns the index value of that virtual uint[]
index The index of the virtual uint[]
static byte Photon.Compression.ArraySerializeExt.IndexAsUInt8(this ulong[] buffer, int index)
Treats buffer as byte[] and returns the index value of that virtual byte[]
index The index of the virtual byte[]
static byte Photon.Compression.ArraySerializeExt.IndexAsUInt8(this uint[] buffer, int index)
Treats buffer as byte[] and returns the index value of that virtual byte[]
index The index of the virtual byte[]
static byte[] Photon.Compression.ArraySerializeExt.Write(this byte[] buffer, ulong value, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Write.
static uint[] Photon.Compression.ArraySerializeExt.Write(this uint[] buffer, ulong value, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Write.
static ulong[] Photon.Compression.ArraySerializeExt.Write(this ulong[] buffer, ulong value, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Write.
static byte[] Photon.Compression.ArraySerializeExt.Write(this byte[] buffer, float value, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Write.
static float Photon.Compression.ArraySerializeExt.Read(this byte[] buffer, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.Read(this byte[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.Read(this uint[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.Read(this ulong[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadUInt8(this ulong[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this ulong[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this ulong[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadUInt8(this uint[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this uint[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this uint[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static byte Photon.Compression.ArraySerializeExt.ReadUInt8(this byte[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static uint Photon.Compression.ArraySerializeExt.ReadUInt32(this byte[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static ulong Photon.Compression.ArraySerializeExt.ReadUInt64(this byte[] buffer, int bits, ref int bitposition)
References Photon.Compression.ArraySerializeExt.Read.
static byte[] Photon.Compression.ArraySerializeExt.Write(this byte[] buffer, byte[] srcbuffer, ref int readpos, ref int writepos, int bits)
static void Photon.Compression.ArraySerializeExt.ReadArrayOutSafe(this ulong[] source, int srcStartPos, byte[] target, ref int bitposition, int bits)