Photon::Pun::UtilityScripts::CellTreeNode
ENodeType
byte Photon.Pun.UtilityScripts.CellTreeNode.Id
Represents the unique ID of the cell.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells.
Vector3 Photon.Pun.UtilityScripts.CellTreeNode.Center
Represents the center, top-left or bottom-right position of the cell or the size of the cell.
Vector3 Photon.Pun.UtilityScripts.CellTreeNode.Size
Vector3 Photon.Pun.UtilityScripts.CellTreeNode.TopLeft
Vector3 Photon.Pun.UtilityScripts.CellTreeNode.BottomRight
ENodeType Photon.Pun.UtilityScripts.CellTreeNode.NodeType
Describes the current node type of the cell tree node.
CellTreeNode Photon.Pun.UtilityScripts.CellTreeNode.Parent
Reference to the parent node.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells.
List<CellTreeNode> Photon.Pun.UtilityScripts.CellTreeNode.Childs
A list containing all child nodes.
float Photon.Pun.UtilityScripts.CellTreeNode.maxDistance
The max distance the player can have to the center of the cell for being 'nearby'.
This is calculated once at runtime.
Photon.Pun.UtilityScripts.CellTreeNode.CellTreeNode()
Default constructor.
Photon.Pun.UtilityScripts.CellTreeNode.CellTreeNode(byte id, ENodeType nodeType, CellTreeNode parent)
Constructor to define the ID and the node type as well as setting a parent node.
id The ID of the cell is used as the interest group. nodeType The node type of the cell tree node. parent The parent node of the cell tree node.
void Photon.Pun.UtilityScripts.CellTreeNode.AddChild(CellTreeNode child)
Adds the given child to the node.
child The child which is added to the node.
void Photon.Pun.UtilityScripts.CellTreeNode.Draw()
Draws the cell in the editor.
References Photon.Pun.UtilityScripts.CellTreeNode.Draw.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.Draw.
void Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells(List< byte > activeCells, bool yIsUpAxis, Vector3 position)
Gathers all cell IDs the player is currently inside or nearby.
activeCells The list to add all cell IDs to the player is currently inside or nearby. yIsUpAxis Describes if the y-axis is used as up-axis. position The current position of the player.
References Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells, Photon.Pun.UtilityScripts.CellTreeNode.Id, Photon.Pun.UtilityScripts.CellTreeNode.IsPointInsideCell, Photon.Pun.UtilityScripts.CellTreeNode.IsPointNearCell, Photon.Pun.UtilityScripts.CellTreeNode.Parent.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells, Photon.Pun.UtilityScripts.CullArea.GetActiveCells.
bool Photon.Pun.UtilityScripts.CellTreeNode.IsPointInsideCell(bool yIsUpAxis, Vector3 point)
Checks if the given point is inside the cell.
yIsUpAxis Describes if the y-axis is used as up-axis. point The point to check. True if the point is inside the cell, false if the point is not inside the cell.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells.
bool Photon.Pun.UtilityScripts.CellTreeNode.IsPointNearCell(bool yIsUpAxis, Vector3 point)
Checks if the given point is near the cell.
yIsUpAxis Describes if the y-axis is used as up-axis. point The point to check. True if the point is near the cell, false if the point is too far away.
Referenced by Photon.Pun.UtilityScripts.CellTreeNode.GetActiveCells.