Photon::Pun::Simple::VitalsContactReactor
VitalNameType Photon.Pun.Simple.VitalsContactReactor.vitalNameType
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
double Photon.Pun.Simple.VitalsContactReactor.dischargePerSec
Referenced by Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.OnAwakeInitialize.
bool Photon.Pun.Simple.VitalsContactReactor.isPickup
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
double Photon.Pun.Simple.VitalsContactReactor.initialCharges
Referenced by Photon.Pun.Simple.VitalsContactReactor.ConsumeCharges, Photon.Pun.Simple.VitalsContactReactor.OnStateChange.
double Photon.Pun.Simple.VitalsContactReactor.valuePerFixed
Referenced by Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType, Photon.Pun.Simple.VitalsContactReactor.OnAwakeInitialize.
virtual VitalNameType Photon.Pun.Simple.VitalsContactReactor.VitalNameType
double Photon.Pun.Simple.VitalsContactReactor.DischargePerSec
virtual bool Photon.Pun.Simple.VitalsContactReactor.Propagate
virtual bool Photon.Pun.Simple.VitalsContactReactor.AllowOverload
override bool Photon.Pun.Simple.VitalsContactReactor.IsPickup
virtual double Photon.Pun.Simple.VitalsContactReactor.Charges
double Photon.Pun.Simple.VitalsContactReactor.dischargeOnEnter
Referenced by Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType.
double Photon.Pun.Simple.VitalsContactReactor.dischargeOnExit
Referenced by Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType.
double Photon.Pun.Simple.VitalsContactReactor.dischargeOnScan
Referenced by Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType.
bool Photon.Pun.Simple.VitalsContactReactor.propagate
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
bool Photon.Pun.Simple.VitalsContactReactor.allowOverload
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
bool Photon.Pun.Simple.VitalsContactReactor.useCharges
Referenced by Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
double Photon.Pun.Simple.VitalsContactReactor._charges
Referenced by Photon.Pun.Simple.VitalsContactReactor.ConsumeCharges, Photon.Pun.Simple.VitalsContactReactor.DischargeValue, Photon.Pun.Simple.VitalsContactReactor.OnStateChange.
Consumption Photon.Pun.Simple.VitalsContactReactor.consumeDespawn
Referenced by Photon.Pun.Simple.VitalsContactReactor.Consume.
virtual Consumption Photon.Pun.Simple.VitalsContactReactor.ConsumeCharges(double amount)
References Photon.Pun.Simple.VitalsContactReactor._charges, Photon.Pun.Simple.VitalsContactReactor.initialCharges.
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
override void Photon.Pun.Simple.VitalsContactReactor.OnAwakeInitialize(bool isNetObject)
Awake code that will run whether or not a NetObject Exists
Returns true if this is a NetObject
References Photon.Pun.Simple.VitalsContactReactor.dischargePerSec, Photon.Pun.Simple.VitalsContactReactor.valuePerFixed.
void Photon.Pun.Simple.VitalsContactReactor.OnStateChange(ObjState newState, ObjState previousState, Transform attachmentTransform, Mount attachTo=null, bool isReady=true)
References Photon.Pun.Simple.VitalsContactReactor._charges, Photon.Pun.Simple.VitalsContactReactor.initialCharges.
double Photon.Pun.Simple.VitalsContactReactor.DischargeValue(ContactType contactType=ContactType.Undefined)
References Photon.Pun.Simple.VitalsContactReactor._charges, Photon.Pun.Simple.VitalsContactReactor.dischargeOnEnter, Photon.Pun.Simple.VitalsContactReactor.dischargeOnExit, Photon.Pun.Simple.VitalsContactReactor.dischargeOnScan, Photon.Pun.Simple.VitalsContactReactor.dischargePerSec, Photon.Pun.Simple.VitalsContactReactor.useCharges.
virtual void Photon.Pun.Simple.VitalsContactReactor.Consume(Consumption consumed)
References Photon.Pun.Simple.VitalsContactReactor.consumeDespawn, Photon.Pun.Simple.SyncState.Despawn, Photon.Pun.Simple.ContactReactorBase< T >.syncState.
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
override Consumption Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent(ContactEvent contactEvent)
References Photon.Pun.Simple.VitalsContactReactor.allowOverload, Photon.Pun.Simple.VitalsContactReactor.Consume, Photon.Pun.Simple.VitalsContactReactor.ConsumeCharges, Photon.Pun.Simple.ContactEvent.contactSystem, Photon.Pun.Simple.ContactEvent.contactType, Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType, Photon.Pun.Simple.SyncState.HardMount, Photon.Pun.Simple.VitalsContactReactor.isPickup, Photon.Pun.Simple.VitalsContactReactor.propagate, Photon.Pun.Simple.ContactReactorBase< T >.syncState, Photon.Pun.Simple.VitalsContactReactor.useCharges, Photon.Pun.Simple.VitalsContactReactor.vitalNameType.
double Photon.Pun.Simple.VitalsContactReactor.GetValueForTriggerType(ContactType collideType)
References Photon.Pun.Simple.VitalsContactReactor.dischargeOnEnter, Photon.Pun.Simple.VitalsContactReactor.dischargeOnExit, Photon.Pun.Simple.VitalsContactReactor.dischargeOnScan, Photon.Pun.Simple.VitalsContactReactor.valuePerFixed.
Referenced by Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.