Photon::Compression::ElementCrusher
UniformAxes
StaticTRSType
Dictionary<int, ElementCrusher> Photon.Compression.ElementCrusher.staticElementCrushers
Experiemental collection of non-changing crushers, to avoid redundant crushers.
Referenced by Photon.Compression.ElementCrusher.CheckAgainstStatics.
ElementCrusher Photon.Compression.ElementCrusher.defaultUncompressedElementCrusher
ElementCrusher Photon.Compression.ElementCrusher.defaultUncompressedPosCrusher
ElementCrusher Photon.Compression.ElementCrusher.defaultUncompressedSclCrusher
ElementCrusher Photon.Compression.ElementCrusher.defaultHalfFloatElementCrusher
ElementCrusher Photon.Compression.ElementCrusher.defaultHalfFloatPosCrusher
ElementCrusher Photon.Compression.ElementCrusher.defaultHalfFloatSclCrusher
ulong [] Photon.Compression.ElementCrusher.reusableArray64
Referenced by Photon.Compression.ElementCrusher.Read.
readonly CompressedElement Photon.Compression.ElementCrusher.reusableCE
Temporary CompressedMatrix used internally when a non-alloc is not provided and no return CE required.
bool Photon.Compression.ElementCrusher.hideFieldName
Transform Photon.Compression.ElementCrusher.defaultTransform
Referenced by Photon.Compression.ElementCrusher.Equals.
UniformAxes Photon.Compression.ElementCrusher.uniformAxes
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.Clamp, Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.CopyFrom, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Equals, Photon.Compression.ElementCrusher.GetHashCode, Photon.Compression.ElementCrusher.TallyBits, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write.
bool Photon.Compression.ElementCrusher.local
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.CopyFrom, Photon.Compression.ElementCrusher.Equals, Photon.Compression.ElementCrusher.GetHashCode, Photon.Compression.Matrix.Matrix, Photon.Compression.ElementCrusher.Move, Photon.Compression.ElementCrusher.Set, Photon.Compression.ElementCrusher.Write.
bool Photon.Compression.ElementCrusher.enableTRSTypeSelector
Referenced by Photon.Compression.ElementCrusher.ElementCrusher.
bool Photon.Compression.ElementCrusher.enableLocalSelector
ReadOnlyCollection<int> Photon.Compression.ElementCrusher.Cached_TotalBits
Referenced by Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedElement.operator byte, Photon.Compression.CompressedElement.operator uint, Photon.Compression.CompressedElement.operator ulong, Photon.Compression.CompressedElement.operator ushort.
Bounds Photon.Compression.ElementCrusher.bounds
Referenced by Photon.Compression.ElementCrusher.GetStaticPositionCrusher.
TRSType Photon.Compression.ElementCrusher._trsType
FloatCrusher Photon.Compression.ElementCrusher._xcrusher
FloatCrusher Photon.Compression.ElementCrusher._ycrusher
FloatCrusher Photon.Compression.ElementCrusher._zcrusher
FloatCrusher Photon.Compression.ElementCrusher._ucrusher
QuatCrusher Photon.Compression.ElementCrusher._qcrusher
bool Photon.Compression.ElementCrusher.useWorldBounds
int Photon.Compression.ElementCrusher.boundsGroupId
bool Photon.Compression.ElementCrusher.cached
bool Photon.Compression.ElementCrusher.cache_xEnabled
bool Photon.Compression.ElementCrusher.cache_yEnabled
bool Photon.Compression.ElementCrusher.cache_zEnabled
bool Photon.Compression.ElementCrusher.cache_uEnabled
bool Photon.Compression.ElementCrusher.cache_qEnabled
bool Photon.Compression.ElementCrusher.cache_isUniformScale
readonly int [] Photon.Compression.ElementCrusher.cache_xBits
readonly int [] Photon.Compression.ElementCrusher.cache_yBits
readonly int [] Photon.Compression.ElementCrusher.cache_zBits
readonly int [] Photon.Compression.ElementCrusher.cache_uBits
readonly int [] Photon.Compression.ElementCrusher.cache_TotalBits
int Photon.Compression.ElementCrusher.cache_qBits
bool Photon.Compression.ElementCrusher.cache_mustCorrectRotationX
TRSType Photon.Compression.ElementCrusher.TRSType
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.Matrix.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.ElementCrusher.Clamp, Photon.Compression.ElementCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.ElementCrusher, Photon.Compression.ElementCrusher.FindBestBitCullLevel, Photon.Compression.CompressedElement.FindBestBitCullLevel, Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix, Photon.Compression.ElementCrusher.Move, Photon.Compression.CompressedElement.operator Quaternion, Photon.Compression.CompressedElement.operator Vector3, Photon.Compression.ElementCrusher.Read, Photon.Compression.ElementCrusher.Set, Photon.Compression.ElementCrusher.TallyBits, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write.
FloatCrusher Photon.Compression.ElementCrusher.xcrusher
FloatCrusher Photon.Compression.ElementCrusher.ycrusher
FloatCrusher Photon.Compression.ElementCrusher.zcrusher
FloatCrusher Photon.Compression.ElementCrusher.ucrusher
QuatCrusher Photon.Compression.ElementCrusher.qcrusher
FloatCrusher Photon.Compression.ElementCrusher.XCrusher
Referenced by Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.CompressedElementExt.GuessUpperBits, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.WorldBoundsGroup.RecalculateWorldCombinedBounds, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
FloatCrusher Photon.Compression.ElementCrusher.YCrusher
Referenced by Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.CompressedElementExt.GuessUpperBits, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.WorldBoundsGroup.RecalculateWorldCombinedBounds, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
FloatCrusher Photon.Compression.ElementCrusher.ZCrusher
Referenced by Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.CompressedElementExt.GuessUpperBits, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.WorldBoundsGroup.RecalculateWorldCombinedBounds, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
FloatCrusher Photon.Compression.ElementCrusher.UCrusher
Referenced by Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.CompressedElement.Set.
QuatCrusher Photon.Compression.ElementCrusher.QCrusher
Referenced by Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.GetStaticQuatCrusher, Photon.Compression.CompressedElement.Set.
bool Photon.Compression.ElementCrusher.UseWorldBounds
int Photon.Compression.ElementCrusher.BoundsGroupId
Bounds?????? Photon.Compression.ElementCrusher.Bounds
Get will return a Bounds struct with the ranges of the x/y/z crushers.
Set will set the x/y/z crusher to match those of the Bounds value.
Referenced by Photon.Compression.WorldBoundsGroup.RecalculateWorldCombinedBounds.
bool Photon.Compression.ElementCrusher.Enabled
Property that returns if this element crusher is effectively enabled (has any enabled float/quat crushers using bits > 0)
FloatCrusher Photon.Compression.ElementCrusher.this[int axis]
Indexer returns the component crushers.
axis
static ElementCrusher Photon.Compression.ElementCrusher.GetStaticPositionCrusher(Bounds bounds, int resolution)
References Photon.Compression.ElementCrusher.bounds, Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.ElementCrusher.ElementCrusher, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
static ElementCrusher Photon.Compression.ElementCrusher.GetStaticQuatCrusher(int minBits)
References Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.ElementCrusher.ElementCrusher, Photon.Compression.ElementCrusher.QCrusher.
static ElementCrusher Photon.Compression.ElementCrusher.CheckAgainstStatics(ElementCrusher ec, bool CheckAgainstFloatCrushersAsWell=true)
Checks to see if a crusher with the same settings has been registered with our dictionary.
If a crusher with the same value exists there, that crusher is returned. If no duplicate of of the supplied crusher exists, the supplied crusher is returned. ec
References Photon.Compression.ElementCrusher.GetHashCode, Photon.Compression.ElementCrusher.staticElementCrushers, Photon.Compression.ElementCrusher.UCrusher, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.TransformCrusher.CheckAgainstStatics, Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.ElementCrusher.GetStaticQuatCrusher.
static bool Photon.Compression.ElementCrusher.operator==(ElementCrusher crusher1, ElementCrusher crusher2)
static bool Photon.Compression.ElementCrusher.operator!=(ElementCrusher crusher1, ElementCrusher crusher2)
void Photon.Compression.ElementCrusher.OnCrusherChange(QuatCrusher crusher)
References Photon.Compression.ElementCrusher.CacheValues.
void Photon.Compression.ElementCrusher.OnCrusherChange(FloatCrusher crusher)
References Photon.Compression.ElementCrusher.CacheValues.
void Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings()
Initial crusher references to match the WorldBoundsGroup specified by the current settings.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Utilities.SettingsScriptableObject< T >.OnSingletonReady, Photon.Utilities.SettingsScriptableObject< T >.single, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.ElementCrusher.CacheValues.
void Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings(bool newUseBounds, int newBndsGrpId)
Swap the crusher references to match the WorldBoundsGroup specified by the current settings.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.local, Photon.Utilities.SettingsScriptableObject< T >.single, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
override void Photon.Compression.ElementCrusher.OnBeforeSerialize()
override void Photon.Compression.ElementCrusher.OnAfterDeserialize()
void Photon.Compression.ElementCrusher.CacheValues()
References Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.QuatCrusher.Bits, Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.QuatCrusher.Enabled, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.Clamp, Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Move, Photon.Compression.ElementCrusher.OnCrusherChange, Photon.Compression.ElementCrusher.Read, Photon.Compression.ElementCrusher.Set, Photon.Compression.ElementCrusher.Write.
Photon.Compression.ElementCrusher.ElementCrusher()
References Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Compression.ElementCrusher.GetStaticPositionCrusher, Photon.Compression.ElementCrusher.GetStaticQuatCrusher.
Photon.Compression.ElementCrusher.ElementCrusher(bool enableTRSTypeSelector=true)
References Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.enableTRSTypeSelector, Photon.Compression.ElementCrusher.TRSType.
Photon.Compression.ElementCrusher.ElementCrusher(TRSType trsType, bool enableTRSTypeSelector=true)
References Photon.Compression.ElementCrusher.Defaults, Photon.Compression.ElementCrusher.enableTRSTypeSelector.
void Photon.Compression.ElementCrusher.Defaults(TRSType trs)
References Photon.Compression.ElementCrusher.QCrusher, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.UCrusher, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.ElementCrusher.ApplyWorldCrusherSettings, Photon.Compression.ElementCrusher.ElementCrusher.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Transform trans, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Automatically use the correct transform TRS element based on the TRSType and local settings of each Crusher.
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.Write.
Referenced by Photon.Compression.CompressedElement.operator byte, Photon.Compression.CompressedElement.operator uint, Photon.Compression.CompressedElement.operator ulong, Photon.Compression.CompressedElement.operator ushort, Photon.Compression.CompressedElement.Serialize, Photon.Compression.ElementCrusher.Write, Photon.Compression.TransformCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(Transform trans, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement ce, byte[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serialize a CompressedElement into a byte[] buffer.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement ce, uint[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serialize a CompressedElement into a uint[] buffer.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement ce, ulong[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serialize a CompressedElement into a ulong[] buffer.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Vector3 v3, byte[] bytes, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(Vector3 v3, byte[] bytes, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Vector3 v3, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Compress and then write a vector3 value into a byte[] buffer.
nonalloc Overwrite this CompressedElement with the compressed value. v3 The uncompressed value to compress and serialize. bytes The target buffer. bitposition Write position of the target buffer. bcl
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes, Photon.Compression.QuatCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(Vector3 v3, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Quaternion quat, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.QuatCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(Quaternion quat, byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Transform trans, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Vector3 v3, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Quaternion quat, ulong[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, byte[] bytes, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Read CompressedElement from buffer.
References Photon.Compression.ElementCrusher.Read.
Referenced by Photon.Compression.ElementCrusher.Read, Photon.Compression.TransformCrusher.Read, Photon.Compression.ElementCrusher.ReadAndDecompress.
CompressedElement Photon.Compression.ElementCrusher.Read(byte[] buffer, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Read CompressedElement from buffer.
WARNING: Returned CompressedElement is a recycled class and values should be used immediately.
References Photon.Compression.ElementCrusher.Read, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, byte[] bytes, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Reads out the commpressed value for this vector/quaternion from a buffer.
Needs to be decompressed still to become vector3/quaterion.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType.
CompressedElement Photon.Compression.ElementCrusher.Read(byte[] bytes, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Deserialize a compressed Vector/Quaternion and return as a CompressedElement.
WARNING: The returned CompressedElement is recycled and its values need to be used immediately. Supply a pre-allocated CompressedElement as an argument if you intend to store these values.
References Photon.Compression.ElementCrusher.Read, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, ulong[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Reads out the commpressed value for this vector/quaternion from a buffer.
Needs to be decompressed still to become vector3/quaterion.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, uint[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Reads out the commpressed value for this vector/quaternion from a buffer.
Needs to be decompressed still to become vector3/quaterion.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType.
Element Photon.Compression.ElementCrusher.ReadAndDecompress(byte[] bytes, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Read.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Transform trans, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Automatically use the correct transform element based on the TRSType for this Crusher.
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(Transform trans, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Vector3 v3, ref ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(Vector3 v3, ref ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Vector3 v3, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set.
void Photon.Compression.ElementCrusher.Write(Vector3 v3, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Quaternion quat, ref ulong buffer)
References Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(Quaternion quat, ref ulong buffer)
References Photon.Compression.ElementCrusher.Write.
void Photon.Compression.ElementCrusher.Write(CompressedElement nonalloc, Quaternion quat, ref ulong buffer, ref int bitposition)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.QuatCrusher.Write.
void Photon.Compression.ElementCrusher.Write(Quaternion quat, ref ulong buffer, ref int bitposition)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(CompressedElement ce, ref ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Write.
CompressedElement Photon.Compression.ElementCrusher.Write(CompressedElement ce, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedQuat.cvalue, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Element Photon.Compression.ElementCrusher.Read(ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Decompress, Photon.Compression.ElementCrusher.TRSType.
Element Photon.Compression.ElementCrusher.Read(ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Deserialize a compressed element directly from the buffer stream into a vector3/quaternion.
This is the most efficient read, but it does not return any intermediary compressed values. buffer Serialized source. bitposition Current read position in source. bcl
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Decompress, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Read.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.ElementCrusher.Read(CompressedElement nonalloc, ulong frag0, ulong frag1=0, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.Read, Photon.Compression.ElementCrusher.reusableArray64.
CompressedElement Photon.Compression.ElementCrusher.Read(ulong frag0, ulong frag1=0, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.ElementCrusher.Read, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.Compress(CompressedElement nonalloc, Transform trans)
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Compression.TransformCrusher.Capture, Photon.Compression.ElementCrusher.Compress, Photon.Compression.TransformCrusher.Compress.
CompressedElement Photon.Compression.ElementCrusher.Compress(Transform trans)
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.CompressAndWrite(Transform trans, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.CompressAndWrite.
void Photon.Compression.ElementCrusher.Compress(CompressedElement nonalloc, Element e)
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
CompressedElement Photon.Compression.ElementCrusher.Compress(Element e)
Compress an Element (Vector/Quaternion wrapper) and return as a CompressedElement.
WARNING: The returned CompressedElement is recycled and its values need to be used immediately. Supply a pre-allocated CompressedElement as an argument if you intend to store these values.
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.Element.quat, Photon.Compression.CompressedElement.reusable, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.CompressAndWrite(Element e, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.Compress(CompressedElement nonalloc, Rigidbody rb, IncludedAxes ia=IncludedAxes.XYZ)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.Clear, Photon.Compression.QuatCrusher.Compress, Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.local, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.ElementCrusher.Compress(CompressedElement nonalloc, Vector3 v, IncludedAxes ia=IncludedAxes.XYZ)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Compress, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
CompressedElement Photon.Compression.ElementCrusher.Compress(Vector3 v)
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.CompressAndWrite(Vector3 v, byte[] buffer, ref int bitposition, IncludedAxes ia=IncludedAxes.XYZ)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Compress, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
void Photon.Compression.ElementCrusher.Compress(CompressedElement nonalloc, Quaternion quat)
Compress and bitpack the enabled vectors into a generic unsigned int.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Compress, Photon.Compression.CompressedElement.Set.
CompressedElement Photon.Compression.ElementCrusher.Compress(Quaternion quat)
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedElement.reusable.
void Photon.Compression.ElementCrusher.CompressAndWrite(Quaternion quat, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Compress.
Element Photon.Compression.ElementCrusher.Decompress(CompressedElement compressed)
Decode (decompresss) and restore an element that was compressed by this crusher.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.QuatCrusher.Decompress, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.CompressedElement.Decompress, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.ElementCrusher.Move, Photon.Compression.ElementCrusher.ReadAndDecompress, Photon.Compression.ElementCrusher.Set.
Element Photon.Compression.ElementCrusher.Decompress(ulong cval, IncludedAxes ia=IncludedAxes.XYZ)
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Decompress, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
void Photon.Compression.ElementCrusher.Apply(Rigidbody rb, CompressedElement ce, IncludedAxes ia=IncludedAxes.XYZ)
Applies only the enabled axes to the transform, leaving the disabled axes untouched.
ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.Decompress.
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.ElementCrusher.Apply(Rigidbody rb, Element e, IncludedAxes ia=IncludedAxes.XYZ)
Applies only the enabled axes to the rigidbody, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.Move(Rigidbody rb, CompressedElement ce, IncludedAxes ia=IncludedAxes.XYZ)
Rigidbody.MovePosition/MoveRotation only the enabled axes, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Move.
Referenced by Photon.Compression.ElementCrusher.Move, Photon.Compression.TransformCrusher.Move.
void Photon.Compression.ElementCrusher.Move(Rigidbody rb, Element e, IncludedAxes ia=IncludedAxes.XYZ)
Rigidbody.MovePosition/MoveRotation only the enabled axes, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.Set(Rigidbody rb, CompressedElement ce, IncludedAxes ia=IncludedAxes.XYZ)
Set RB pos/rot using only the enabled axes, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Set.
Referenced by Photon.Compression.ElementCrusher.Set, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.ElementCrusher.Set(Rigidbody2D rb, CompressedElement ce, IncludedAxes ia=IncludedAxes.XYZ)
Set RB pos/rot using only the enabled axes, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.Decompress, Photon.Compression.ElementCrusher.Set.
void Photon.Compression.ElementCrusher.Set(Rigidbody rb, Element e, IncludedAxes ia=IncludedAxes.XYZ)
Set RB pos/rot using only the enabled axes, leaving the disabled axes untouched.
rb e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.Set(Rigidbody2D rb2d, Element e, IncludedAxes ia=IncludedAxes.XYZ)
Set RB pos/rot using only the enabled axes, leaving the disabled axes untouched.
rb2d e ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
void Photon.Compression.ElementCrusher.Apply(Transform trans, CompressedElement ce, IncludedAxes ia=IncludedAxes.XYZ)
Applies only the enabled axes to the transform, leaving the disabled axes untouched.
ia The indicated axis will be used (assuming they are enabled for the crusher). For example if an object only moves up and down in place, IncludedAxes.Y would only apply the Y axis compression values, and would leave the X and Z values as they currently are.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.Decompress.
void Photon.Compression.ElementCrusher.Apply(Transform trans, Element e, IncludedAxes ia=IncludedAxes.XYZ)
Applies only the enabled axes to the transform, leaving the disabled axes untouched.
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.local, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes, Photon.Compression.Element.v.
Vector3 Photon.Compression.ElementCrusher.Clamp(Vector3 v3)
Return a value clamped to the Min/Max values defined for each axis by this Crusher.
v3
References Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.WorldBoundsGroup.GetUncompressedCrusher.
BitCullingLevel Photon.Compression.ElementCrusher.FindBestBitCullLevel(CompressedElement a, CompressedElement b, BitCullingLevel maxCulling)
Return the smallest bit culling level that will be able to communicate the changes between two compressed elements.
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.ElementCrusher.TRSType.
bool Photon.Compression.ElementCrusher.TestMatchingUpper(CompressedElement a, CompressedElement b, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
int Photon.Compression.ElementCrusher.TallyBits(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Get the total number of bits needed to serialize an element with this crusher.
References Photon.Compression.QuatCrusher.Bits, Photon.Compression.QuatCrusher.Enabled, Photon.Compression.WorldBoundsSettings.TallyBits, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.TransformCrusher.TallyBits.
void Photon.Compression.ElementCrusher.CopyFrom(ElementCrusher src)
References Photon.Compression.QuatCrusher.CopyFrom, Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.TransformCrusher.CopyFrom.
override string Photon.Compression.ElementCrusher.ToString()
override bool Photon.Compression.ElementCrusher.Equals(object obj)
References Photon.Compression.ElementCrusher.Equals.
Referenced by Photon.Compression.ElementCrusher.Equals, Photon.Compression.TransformCrusher.Equals.
bool Photon.Compression.ElementCrusher.Equals(ElementCrusher other)
References Photon.Compression.ElementCrusher.defaultTransform, Photon.Compression.QuatCrusher.Equals, Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.uniformAxes.
override int Photon.Compression.ElementCrusher.GetHashCode()
References Photon.Compression.ElementCrusher.local, Photon.Compression.ElementCrusher.uniformAxes.
Referenced by Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.TransformCrusher.GetHashCode.
void Photon.Compression.ElementCrusher.OnWorldBoundsReady()
Handle callback from WorldBoundsSO letting this crusher know that it can now use the WBSO crusher references
WorldBoundsGroup Photon.Compression.ElementCrusher.GetUsedWorldBounds()
void Photon.Compression.ElementCrusher.NullUnusedCrushers()
Called at startup of builds to clear any crushers that were stored for the editor, but are not used in builds.
Generates some startup GC, but the alternative is breaking unused crushers in SOs in the editor every time a build is made.
bool Photon.Compression.ElementCrusher.TestMatchingUpper(uint a, uint b, int lowerbits)
Photon.Compression.ElementCrusher.ElementCrusher(StaticTRSType staticTrsType)
Static crushers don't initialize unused crusher.
Using this constructor will leave unused crushers null, since these types are not meant to be shown in the inspector. staticTrsType