Photon::Pun::Demo::Cockpit::RoomListView
OnJoinRoomEvent Photon.Pun.Demo.Cockpit.RoomListView.OnJoinRoom
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.OnRoomCellJoinButtonClick.
RoomListCell Photon.Pun.Demo.Cockpit.RoomListView.CellPrototype
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.OnEnable, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate.
Text Photon.Pun.Demo.Cockpit.RoomListView.UpdateStatusText
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.OnEnable, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate.
Text Photon.Pun.Demo.Cockpit.RoomListView.ContentFeedback
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList, Photon.Pun.Demo.Cockpit.RoomListView.OnEnable, Photon.Pun.Demo.Cockpit.RoomListView.OnJoinedLobbyCallBack, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate.
InputField Photon.Pun.Demo.Cockpit.RoomListView.LobbyNameInputField
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate.
InputField Photon.Pun.Demo.Cockpit.RoomListView.SqlQueryInputField
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate.
bool Photon.Pun.Demo.Cockpit.RoomListView._firstUpdate
Dictionary<string, RoomListCell> Photon.Pun.Demo.Cockpit.RoomListView.roomCellList
override void Photon.Pun.Demo.Cockpit.RoomListView.OnEnable()
References Photon.Pun.Demo.Cockpit.RoomListView.CellPrototype, Photon.Pun.Demo.Cockpit.RoomListView.ContentFeedback, Photon.Pun.Demo.Cockpit.RoomListView.ResetList, Photon.Pun.Demo.Cockpit.RoomListView.UpdateStatusText.
void Photon.Pun.Demo.Cockpit.RoomListView.OnRoomCellJoinButtonClick(string roomName)
References Photon.Pun.Demo.Cockpit.RoomListView.OnJoinRoom.
Referenced by Photon.Pun.Demo.Cockpit.RoomListCell.OnJoinRoomButtonClick.
override void Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate(List< RoomInfo > roomList)
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server.
Each item is a RoomInfo which might include custom properties (provided you defined those as lobby-listed when creating a room). Not all types of lobbies provide a listing of rooms to the client. Some are silent and specialized for server-side matchmaking.
References Photon.Pun.Demo.Cockpit.RoomListView.CellPrototype, Photon.Pun.Demo.Cockpit.RoomListView.ContentFeedback, Photon.Pun.PhotonNetwork.InLobby, Photon.Pun.Demo.Cockpit.RoomListView.LobbyNameInputField, Photon.Realtime.RoomInfo.Name, Photon.Realtime.RoomInfo.RemovedFromList, Photon.Pun.Demo.Cockpit.RoomListView.SqlQueryInputField, Photon.Pun.Demo.Cockpit.RoomListView.UpdateStatusText.
void Photon.Pun.Demo.Cockpit.RoomListView.OnJoinedLobbyCallBack()
References Photon.Pun.Demo.Cockpit.RoomListView.ContentFeedback.
void Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList()
References Photon.Pun.Demo.Cockpit.RoomListView.ContentFeedback, Photon.Pun.PhotonNetwork.GetCustomRoomList, Photon.Pun.Demo.Cockpit.RoomListView.LobbyNameInputField, Photon.Pun.Demo.Cockpit.RoomListView.ResetList, Photon.Pun.Demo.Cockpit.RoomListView.SqlQueryInputField.
void Photon.Pun.Demo.Cockpit.RoomListView.ResetList()
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom, Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList, Photon.Pun.Demo.Cockpit.PunCockpit.JoinRoom, Photon.Pun.Demo.Cockpit.RoomListView.OnEnable, Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftLobby.
IEnumerator Photon.Pun.Demo.Cockpit.RoomListView.clearStatus()