Photon::Compression::TransformCrusher
const int Photon.Compression.TransformCrusher.VersionMajor
const int Photon.Compression.TransformCrusher.VersionMinor
const int Photon.Compression.TransformCrusher.VersionRevision
const int Photon.Compression.TransformCrusher.Build
Dictionary<int, TransformCrusher> Photon.Compression.TransformCrusher.staticTransformCrushers
Referenced by Photon.Compression.TransformCrusher.CheckAgainstStatics.
ulong [] Photon.Compression.TransformCrusher.reusableArray64
Referenced by Photon.Compression.TransformCrusher.Read.
Transform Photon.Compression.TransformCrusher.defaultTransform
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Compress.
ReadOnlyCollection<int> Photon.Compression.TransformCrusher.cached_total
Referenced by Photon.Compression.TransformCrusher.CacheValues.
ElementCrusher Photon.Compression.TransformCrusher.posCrusher
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Capture, Photon.Compression.TransformCrusher.CheckAgainstStatics, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.CopyFrom, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Equals, Photon.Compression.TransformCrusher.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
ElementCrusher Photon.Compression.TransformCrusher.rotCrusher
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Capture, Photon.Compression.TransformCrusher.CheckAgainstStatics, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.CopyFrom, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Equals, Photon.Compression.TransformCrusher.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
ElementCrusher Photon.Compression.TransformCrusher.sclCrusher
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Capture, Photon.Compression.TransformCrusher.CheckAgainstStatics, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.CopyFrom, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Equals, Photon.Compression.TransformCrusher.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
readonly int [] Photon.Compression.TransformCrusher.cached_pBits
Temporary CompressedMatrix used internally when a non-alloc is not provided and no return CM or M is required.
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
readonly int [] Photon.Compression.TransformCrusher.cached_rBits
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
readonly int [] Photon.Compression.TransformCrusher.cached_sBits
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
readonly int [] Photon.Compression.TransformCrusher._cached_total
Referenced by Photon.Compression.TransformCrusher.CacheValues.
bool Photon.Compression.TransformCrusher.cached
Referenced by Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Write.
ElementCrusher Photon.Compression.TransformCrusher.PosCrusher
Sets the position crusher to the assigned reference, and reruns CacheValues().
Referenced by Photon.Compression.TransformCrusher.ConstructDefault, Photon.Compression.Matrix.Matrix.
ElementCrusher Photon.Compression.TransformCrusher.RotCrusher
Sets the scale crusher to the assigned reference, and reruns CacheValues().
Referenced by Photon.Compression.Matrix.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.TransformCrusher.ConstructDefault, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix.
ElementCrusher Photon.Compression.TransformCrusher.SclCrusher
Sets the scale crusher to the assigned reference, and reruns CacheValues().
Referenced by Photon.Compression.TransformCrusher.ConstructDefault, Photon.Compression.Matrix.Matrix.
const string Photon.Compression.TransformCrusher.transformMissingError
static TransformCrusher Photon.Compression.TransformCrusher.CheckAgainstStatics(TransformCrusher tc, bool CheckElementCrusherAsWell=true)
See if a crusher with these exact settings exists in the static crushers list.
If so, return that already cataloged crusher. You may allow the crusher given as an argument be garbage collected. NOTE: Any changes to static crushers will break things. Currently there are no safeguards against this. tc
References Photon.Compression.ElementCrusher.CheckAgainstStatics, Photon.Compression.TransformCrusher.GetHashCode, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.TransformCrusher.staticTransformCrushers.
static bool Photon.Compression.TransformCrusher.operator==(TransformCrusher crusher1, TransformCrusher crusher2)
static bool Photon.Compression.TransformCrusher.operator!=(TransformCrusher crusher1, TransformCrusher crusher2)
void Photon.Compression.TransformCrusher.OnCrusherChange(ElementCrusher crusher)
Callback fired whenever a component ElementCrusher is changed.
crusher
References Photon.Compression.TransformCrusher.CacheValues.
Photon.Compression.TransformCrusher.TransformCrusher()
References Photon.Compression.TransformCrusher.ConstructDefault.
Photon.Compression.TransformCrusher.TransformCrusher(bool isStatic=false)
Default constructor for TransformCrusher.
isStatic Set this as true if this crusher is not meant to be serialized. Static crushers are created in code, and are not meant to be modified after creation. This allows them to be indexed by their hashcodes and reused.
References Photon.Compression.TransformCrusher.ConstructDefault.
override void Photon.Compression.TransformCrusher.OnBeforeSerialize()
override void Photon.Compression.TransformCrusher.OnAfterDeserialize()
References Photon.Compression.TransformCrusher.CacheValues.
virtual void Photon.Compression.TransformCrusher.CacheValues()
References Photon.Compression.TransformCrusher._cached_total, Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.cached_total, Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
Referenced by Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.CopyFrom, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.OnAfterDeserialize, Photon.Compression.TransformCrusher.OnCrusherChange, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix cm, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
Referenced by Photon.Compression.CompressedMatrix.AsArray32, Photon.Compression.CompressedMatrix.AsArray64, Photon.Compression.CompressedMatrix.AsArray8, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Compression.CompressedMatrix.operator byte, Photon.Compression.CompressedMatrix.operator uint, Photon.Compression.CompressedMatrix.operator ulong, Photon.Compression.CompressedMatrix.operator ushort, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix cm, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix cm, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix nonalloc, Transform transform, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(Transform transform, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.CompressedMatrix.reusable, Photon.Compression.TransformCrusher.Write.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(ulong[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress.
Referenced by Photon.Compression.TransformCrusher.ReadAndDecompress.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(uint[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(byte[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, ulong[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, uint[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, byte[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(ulong[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress, Photon.Compression.Matrix.reusable.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(uint[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress, Photon.Compression.Matrix.reusable.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(byte[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress, Photon.Compression.Matrix.reusable.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, byte[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.ElementCrusher.Read, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Move, Photon.Pun.Simple.SyncTransform.OnNetDeserialize, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.ReadAndApply, Photon.Compression.TransformCrusher.ReadAndDecompress, Photon.Compression.TransformCrusher.Set.
CompressedMatrix Photon.Compression.TransformCrusher.Read(ulong[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(uint[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(byte[] array, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(ulong[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(uint[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(byte[] array, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.ElementCrusher.Read, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.ElementCrusher.Read, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix nonalloc, Transform transform, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Compress a transform using this crusher, store the compressed results in a supplied CompressedMatrix, and serialize the compressed values to the buffer.
nonalloc Populate this CompressedMatrix with the results of the cmopression operation. transform The transform to compress. buffer The write target. bitposition The write position for the buffer. bcl
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(Transform transform, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Compress and write all of the components of transform, without creating any intermediary CompressedMatrix or Bitstream.
This is the most efficient way to compress and write a transform, but it will not return any compresed values for you to store or compare. transform The transform to compress. buffer The write target. bitposition The write position for the buffer. bcl
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix cm, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serialize a CompressedMatrix to a bitstream.
cm Results of a previously compressed Transform Matrix. buffer The write target. bcl
References Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.Write(CompressedMatrix nonalloc, Transform transform, ref ulong bitstream, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Compress a transform using this crusher, store the compressed results in a supplied CompressedMatrix, and serialize the compressed values to the bitstream.
nonalloc Populate this CompressedMatrix with the results of the cmopression operation. transform The transform to compress. bitstream The write target. bcl
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Write.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.ReadAndDecompress.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
Matrix Photon.Compression.TransformCrusher.ReadAndDecompress(ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.ReadAndApply(Transform target, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Read the compressed value from a buffer, decompress it, and apply it to the target transform.
target bitstream bcl
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, ulong frag4=0, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Reconstruct a CompressedMatrix from fragments.
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.reusableArray64.
void Photon.Compression.TransformCrusher.ReadAndDecompress(Matrix nonalloc, ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, ulong frag4=0, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Read(ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, uint frag4=0, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, ulong buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Extract a CompressedMatrix from a primitive buffer.
Results will overwrite the supplied CompressedMatrix non-alloc. nonalloc Target of the Read. buffer Serialized source. bcl
References Photon.Compression.TransformCrusher.Read.
void Photon.Compression.TransformCrusher.Read(CompressedMatrix nonalloc, ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Extract a CompressedMatrix from a primitive buffer.
Results will overwrite the supplied CompressedMatrix non-alloc. nonalloc Target of the Read. buffer Serialized source. bitposition The read start position of the buffer. This value will be incremented by the number of bits read. bcl
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.ElementCrusher.Read, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
CompressedMatrix Photon.Compression.TransformCrusher.Read(ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Compress(CompressedMatrix nonalloc)
Compress the transform of the default gameobject.
(Only avavilable if this crusher is serialized in the editor).
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.defaultTransform.
Referenced by Photon.Compression.Matrix.Compress, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.InterpolateFrame.
CompressedMatrix Photon.Compression.TransformCrusher.Compress()
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.defaultTransform.
Referenced by Photon.Compression.TransformCrusher.Capture, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.TransformCrusher.Compress(CompressedMatrix nonalloc, Matrix matrix)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedElement.Clear, Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Compress(CompressedMatrix nonalloc, Transform transform)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedElement.Clear, Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
CompressedMatrix Photon.Compression.TransformCrusher.Compress(Transform transform)
Compressed to an internally reused CompressedMatrix.
WARNING: Be sure to use the contents of this CompressedMatrix immediately, as its values will be overwritten often. If you need to hold these values, use the nonalloc overload and supply a CompressedMatrix.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.reusable.
CompressedMatrix Photon.Compression.TransformCrusher.Compress(Rigidbody rb)
Compress Rigodbody to an internally reused CompressedMatrix.
WARNING: Be sure to use the contents of this CompressedMatrix immediately, as its values will be overwritten often. If you need to hold these values, use the nonalloc overload and supply a CompressedMatrix.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Compress(CompressedMatrix nonalloc, Rigidbody rb)
Compress to Rigidbody to supplied CompressedMatrix.
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
CompressedMatrix Photon.Compression.TransformCrusher.Compress(Rigidbody2D rb2d)
Compressed Rigidbody2D to an internally reused CompressedMatrix.
WARNING: Be sure to use the contents of this CompressedMatrix immediately, as its values will be overwritten often. If you need to hold these values, use the nonalloc overload and supply a CompressedMatrix.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Compress(CompressedMatrix nonalloc, Rigidbody2D rb2d)
Compress to Rigidbody2D to supplied CompressedMatrix.
NOT FULLY TEST (OR TESTED AT ALL EVEN)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.CompressAndWrite(Matrix matrix, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned. matrix bitstream
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.CompressAndWrite(Transform transform, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.CompressAndWrite(Rigidbody rb, byte[] buffer, ref int bitposition)
CompressAndWrite doesn't produce any temporary 40byte bitstream structs, but rather will compress and write directly to the supplied bitstream.
Use this rather than Write() and Compress() when you don't need the lossy or compressed value returned.
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.ElementCrusher.local, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.TransformCrusher.Decompress(Matrix nonalloc, ulong[] buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.CompressedMatrix.Decompress, Photon.Compression.TransformCrusher.Decompress, Photon.Pun.Simple.SyncTransform.OnNetDeserialize, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Compression.TransformCrusher.ReadAndDecompress.
void Photon.Compression.TransformCrusher.Decompress(Matrix nonalloc, uint[] buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Decompress(Matrix nonalloc, ulong compressed, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
Matrix Photon.Compression.TransformCrusher.Decompress(ulong[] buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.Matrix.reusable.
Matrix Photon.Compression.TransformCrusher.Decompress(uint[] buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.Matrix.reusable.
Matrix Photon.Compression.TransformCrusher.Decompress(byte[] buffer, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.Matrix.reusable.
Matrix Photon.Compression.TransformCrusher.Decompress(ulong compressed, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.Matrix.reusable.
void Photon.Compression.TransformCrusher.Decompress(Matrix nonalloc, CompressedMatrix compMatrix)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.Matrix.Set, Photon.Compression.ElementCrusher.TRSType.
Matrix Photon.Compression.TransformCrusher.Decompress(CompressedMatrix compMatrix)
References Photon.Compression.TransformCrusher.cached, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.TransformCrusher.Set(Rigidbody rb, CompressedMatrix cmatrix)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Set.
Referenced by Photon.Compression.CompressedMatrix.Set, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody rb, Matrix matrix)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody rb, ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, ulong frag4=0)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody rb, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody rb, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody2D rb2d, Matrix matrix)
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Set.
void Photon.Compression.TransformCrusher.Set(Rigidbody2D rb2d, CompressedMatrix cmatrix)
Set Rigidbody to values of CompressedMatrix using rb.position and rb.rotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.Set.
void Photon.Compression.TransformCrusher.Move(Rigidbody rb, CompressedMatrix cmatrix)
Move Rigidbody to values of CompressedMatrix using rb.MovePosition and rb.MoveRotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.CompressedMatrix.Decompress, Photon.Compression.ElementCrusher.Move, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
Referenced by Photon.Compression.CompressedMatrix.Move, Photon.Compression.TransformCrusher.Move.
void Photon.Compression.TransformCrusher.Move(Rigidbody rb, Matrix matrix)
Move Rigidbody to values of CompressedMatrix using rb.MovePosition and rb.MoveRotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.ElementCrusher.Move, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Move(Rigidbody rb, ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, ulong frag4=0)
Move Rigidbody to values of CompressedMatrix using rb.MovePosition and rb.MoveRotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Move(Rigidbody rb, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Move Rigidbody to values of CompressedMatrix using rb.MovePosition and rb.MoveRotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Move(Rigidbody rb, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Move Rigidbody to values of CompressedMatrix using rb.MovePosition and rb.MoveRotation.
Any axes not included in the Crusher are left as is. Scale uses rb.transform (rb doesn't handle scaling).
References Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Apply(Rigidbody rb, CompressedMatrix cmatrix)
Apply the CompressedMatrix to a Rigidbody.
Any axes not included in the Crusher are left as is.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
Referenced by Photon.Compression.CompressedMatrix.Apply, Photon.Compression.Matrix.Apply, Photon.Compression.TransformCrusher.Apply, Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnInterpolate, Photon.Compression.TransformCrusher.ReadAndApply.
void Photon.Compression.TransformCrusher.Apply(Rigidbody rb, Matrix matrix)
Apply the TRS matrix to a transform.
Any axes not included in the Crusher are left as is.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Apply(ulong cvalue)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.defaultTransform.
void Photon.Compression.TransformCrusher.Apply(Transform t, ulong cvalue)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.Matrix.reusable.
void Photon.Compression.TransformCrusher.Apply(ulong u0, ulong u1, ulong u2, ulong u3, uint u4)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.defaultTransform.
void Photon.Compression.TransformCrusher.Apply(Transform t, ulong frag0, ulong frag1=0, ulong frag2=0, ulong frag3=0, ulong frag4=0)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.reusable.
void Photon.Compression.TransformCrusher.Apply(CompressedMatrix cmatrix)
Apply the CompressedMatrix to a transform.
Any axes not included in the Crusher are left as is.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.defaultTransform.
void Photon.Compression.TransformCrusher.Apply(Transform t, CompressedMatrix cmatrix)
Apply the CompressedMatrix to a transform.
Any axes not included in the Crusher are left as is.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Apply(Matrix matrix)
Apply the TRS matrix to a transform.
Any axes not included in the Crusher are left as is.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.defaultTransform.
void Photon.Compression.TransformCrusher.Apply(Transform transform, Matrix matrix)
Apply the TRS matrix to a transform.
Any axes not included in the Crusher are left as is.
References Photon.Compression.ElementCrusher.Apply, Photon.Compression.TransformCrusher.cached_pBits, Photon.Compression.TransformCrusher.cached_rBits, Photon.Compression.TransformCrusher.cached_sBits, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
void Photon.Compression.TransformCrusher.Capture(Rigidbody rb, CompressedMatrix cm, Matrix m)
Capture the values of a Rigidbody.
Applies the lossy decompressed value to the Matrix. m Lossy decompressed value is stored.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.Decompress.
Referenced by Photon.Pun.Simple.SyncTransform.CaptureCurrent, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.Frame.Set.
void Photon.Compression.TransformCrusher.Capture(Rigidbody2D rb2d, CompressedMatrix cm, Matrix m)
Capture the values of a Rigidbody2d.
Applies the lossy decompressed value to the Matrix. m Lossy decompressed value is stored.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.Decompress.
void Photon.Compression.TransformCrusher.Capture(Transform tr, CompressedMatrix cm, Matrix m)
Capture the values of a Transform.
m Lossy decompressed value is stored.
References Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.TransformCrusher.sclCrusher.
int Photon.Compression.TransformCrusher.TallyBits(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Get the total number of bits this Transform is set to write.
References Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher, Photon.Compression.ElementCrusher.TallyBits.
Referenced by Photon.Compression.CompressedMatrix.operator byte, Photon.Compression.CompressedMatrix.operator uint, Photon.Compression.CompressedMatrix.operator ulong, Photon.Compression.CompressedMatrix.operator ushort.
void Photon.Compression.TransformCrusher.CopyFrom(TransformCrusher source)
References Photon.Compression.TransformCrusher.CacheValues, Photon.Compression.ElementCrusher.CopyFrom, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
override bool Photon.Compression.TransformCrusher.Equals(object obj)
References Photon.Compression.TransformCrusher.Equals.
Referenced by Photon.Compression.TransformCrusher.Equals.
bool Photon.Compression.TransformCrusher.Equals(TransformCrusher other)
References Photon.Compression.ElementCrusher.Equals, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
override int Photon.Compression.TransformCrusher.GetHashCode()
References Photon.Compression.ElementCrusher.GetHashCode, Photon.Compression.TransformCrusher.posCrusher, Photon.Compression.TransformCrusher.rotCrusher, Photon.Compression.TransformCrusher.sclCrusher.
Referenced by Photon.Compression.TransformCrusher.CheckAgainstStatics.
virtual void Photon.Compression.TransformCrusher.ConstructDefault(bool isStatic=false)
References Photon.Compression.TransformCrusher.PosCrusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.TransformCrusher.SclCrusher.
Referenced by Photon.Compression.TransformCrusher.TransformCrusher.