SoundGeneralDynamicsMultiplayerPhoton
SoundChain [] SoundGeneralDynamicsMultiplayerPhoton.soundChains
SoundChunk [] SoundGeneralDynamicsMultiplayerPhoton.soundChunks
SoundPiece [] SoundGeneralDynamicsMultiplayerPhoton.soundPieces
SoundCastDynamics [] SoundGeneralDynamicsMultiplayerPhoton.soundCasts
SoundVisualizer [] SoundGeneralDynamicsMultiplayerPhoton.soundVisualUI
PhotonView SoundGeneralDynamicsMultiplayerPhoton.photonView
GameObject SoundGeneralDynamicsMultiplayerPhoton.ears
void SoundGeneralDynamicsMultiplayerPhoton.soundVisualUIInitialization()
void SoundGeneralDynamicsMultiplayerPhoton.Awake()
void SoundGeneralDynamicsMultiplayerPhoton.Start()
void SoundGeneralDynamicsMultiplayerPhoton.UpdateCalculate()
void SoundGeneralDynamicsMultiplayerPhoton.CalculateSoundSourceCast(SoundPiece SoundPiece, float MaxVolume, float MaxPitch)
void SoundGeneralDynamicsMultiplayerPhoton.CalculateVisualPositioning(SoundVisualizer soundVisualizer, float fowardBack, float leftRight, float upDown)
void SoundGeneralDynamicsMultiplayerPhoton.Update()
void SoundGeneralDynamicsMultiplayerPhoton.OnDrawGizmosSelected()
IEnumerator SoundGeneralDynamicsMultiplayerPhoton.playSoundChain(int soundChainID)
IEnumerator SoundGeneralDynamicsMultiplayerPhoton.playSoundChunk(int soundChunkID)
IEnumerator SoundGeneralDynamicsMultiplayerPhoton.playSoundPiece(int soundPieceID)
void SoundGeneralDynamicsMultiplayerPhoton.Initialization()
References SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.Audio, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.AudioMixer, SoundCast.castName, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.delayAfter, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.delayAfterWait, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.delayBefore, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.delayBeforeWait, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.delayDuringWait, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.originalMaxVolume, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.originalPitch, SoundGeneralDynamicsMultiplayerPhoton.SoundChain.Pitch, SoundGeneralDynamicsMultiplayerPhoton.SoundChunk.Pitch, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.Pitch, PlayChain, PlayChunk, SoundGeneralDynamicsMultiplayerPhoton.SoundChain.playOnStart, SoundGeneralDynamicsMultiplayerPhoton.SoundChunk.playOnStart, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.playOnStart, PlayPiece, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.soundCastName, SoundCastDynamics.soundCasts, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.soundCastSource, SoundGeneralDynamicsMultiplayerPhoton.SoundChain.soundChunks, SoundGeneralDynamicsMultiplayerPhoton.SoundChunk.soundPieces, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.soundVisualizerName, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.soundVisualSource, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.source, SoundVisualizer.visualizerName, SoundGeneralDynamicsMultiplayerPhoton.SoundChain.Volume, SoundGeneralDynamicsMultiplayerPhoton.SoundChunk.Volume, SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.Volume.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundChain(int soundChainID)
References Photon.Pun.PhotonView.RPC.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundChunk(int soundChunkID)
References Photon.Pun.PhotonView.RPC.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundPiece(int soundPieceID)
References Photon.Pun.PhotonView.RPC.
Referenced by BreakableFurniture.SpawnBrokenVersion.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundChain(string soundChainName)
References Photon.Pun.PhotonView.RPC.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundChunk(string soundChunkName)
References Photon.Pun.PhotonView.RPC.
void SoundGeneralDynamicsMultiplayerPhoton.multiplayerSoundPiece(string soundPieceName)
References Photon.Pun.PhotonView.RPC.
void SoundGeneralDynamicsMultiplayerPhoton.PlayChain(int soundChainID)
Referenced by Initialization, SoundTesterKit.TestChain.
void SoundGeneralDynamicsMultiplayerPhoton.PlayChunk(int soundChunkID)
Referenced by Initialization, SoundTesterKit.TestChunk.
void SoundGeneralDynamicsMultiplayerPhoton.PlayPiece(int soundPieceID)
Referenced by Initialization, SoundTesterKit.TestPiece.
void SoundGeneralDynamicsMultiplayerPhoton.PlayChain(string soundChainName)
References SoundGeneralDynamicsMultiplayerPhoton.SoundChain.chainName.
void SoundGeneralDynamicsMultiplayerPhoton.PlayChunk(string soundChunkName)
References SoundGeneralDynamicsMultiplayerPhoton.SoundChunk.chunkName.
void SoundGeneralDynamicsMultiplayerPhoton.PlayPiece(string soundPieceName)
References SoundGeneralDynamicsMultiplayerPhoton.SoundPiece.pieceName.