Photon::Pun::PhotonStream
List<object> Photon.Pun.PhotonStream.writeData
object [] Photon.Pun.PhotonStream.readData
int Photon.Pun.PhotonStream.currentItem
bool Photon.Pun.PhotonStream.IsWriting
If true, this client should add data to the stream to send it.
Referenced by Photon.Pun.PhotonStream.CopyToListAndClear, TimerScript.OnPhotonSerializeView, BreakableFurniture.OnPhotonSerializeView, Photon.Pun.PhotonAnimatorView.OnPhotonSerializeView, Photon.Pun.PhotonRigidbody2DView.OnPhotonSerializeView, Photon.Pun.PhotonRigidbodyView.OnPhotonSerializeView, Photon.Pun.PhotonTransformView.OnPhotonSerializeView, Photon.Pun.Demo.PunBasics.PlayerManager.OnPhotonSerializeView, Photon.Pun.UtilityScripts.SmoothSyncMovement.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewRotationControl.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewPositionControl.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewScaleControl.OnPhotonSerializeView, Photon.Pun.PhotonStream.PeekNext, Photon.Pun.PhotonStream.PhotonStream, Photon.Pun.PhotonStream.ReceiveNext, Photon.Pun.PhotonStream.SendNext, Photon.Pun.PhotonStream.Serialize, Photon.Pun.PhotonStream.SetReadStream, Photon.Pun.PhotonStream.ToArray.
bool Photon.Pun.PhotonStream.IsReading
If true, this client should read data send by another client.
Referenced by Photon.Pun.PhotonTransformViewClassic.OnPhotonSerializeView.
int? Photon.Pun.PhotonStream.Count
Count of items in the stream.
Photon.Pun.PhotonStream.PhotonStream(bool write, object[] incomingData)
Creates a stream and initializes it.
Used by PUN internally.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.SetReadStream(object[] incomingData, int pos=0)
References Photon.Pun.PhotonStream.IsWriting.
object Photon.Pun.PhotonStream.ReceiveNext()
Read next piece of data from the stream when IsReading is true.
References Photon.Pun.PhotonStream.IsWriting.
Referenced by Photon.Pun.PhotonStreamQueue.Deserialize, TimerScript.OnPhotonSerializeView, BreakableFurniture.OnPhotonSerializeView, Photon.Pun.PhotonRigidbody2DView.OnPhotonSerializeView, Photon.Pun.PhotonRigidbodyView.OnPhotonSerializeView, Photon.Pun.PhotonTransformView.OnPhotonSerializeView, Photon.Pun.Demo.PunBasics.PlayerManager.OnPhotonSerializeView, Photon.Pun.UtilityScripts.SmoothSyncMovement.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewRotationControl.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewScaleControl.OnPhotonSerializeView.
object Photon.Pun.PhotonStream.PeekNext()
Read next piece of data from the stream without advancing the "current" item.
References Photon.Pun.PhotonStream.IsWriting.
Referenced by Photon.Pun.PhotonAnimatorView.OnPhotonSerializeView.
void Photon.Pun.PhotonStream.SendNext(object obj)
Add another piece of data to send it when IsWriting is true.
References Photon.Pun.PhotonStream.IsWriting.
Referenced by TimerScript.OnPhotonSerializeView, BreakableFurniture.OnPhotonSerializeView, Photon.Pun.PhotonRigidbody2DView.OnPhotonSerializeView, Photon.Pun.PhotonRigidbodyView.OnPhotonSerializeView, Photon.Pun.PhotonTransformView.OnPhotonSerializeView, Photon.Pun.Demo.PunBasics.PlayerManager.OnPhotonSerializeView, Photon.Pun.UtilityScripts.SmoothSyncMovement.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewRotationControl.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewScaleControl.OnPhotonSerializeView, Photon.Pun.PhotonStreamQueue.Serialize.
bool Photon.Pun.PhotonStream.CopyToListAndClear(List< object > target)
References Photon.Pun.PhotonStream.IsWriting.
object[] Photon.Pun.PhotonStream.ToArray()
Turns the stream into a new object[].
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref bool myBool)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref int myInt)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref string value)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref char value)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref short value)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref float obj)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref Player obj)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref Vector3 obj)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref Vector2 obj)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.Serialize(ref Quaternion obj)
Will read or write the value, depending on the stream's IsWriting value.
References Photon.Pun.PhotonStream.IsWriting.
void Photon.Pun.PhotonStream.SetWriteStream(List< object > newWriteData, int pos=0)
List< object > Photon.Pun.PhotonStream.GetWriteStream()
void Photon.Pun.PhotonStream.ResetWriteStream()