Photon::Realtime::ConnectionHandler
LoadBalancingClient Photon.Realtime.ConnectionHandler.Client
Photon client to log information and statistics from.
Referenced by Photon.Pun.PhotonHandler.OnEnable, Photon.Realtime.ConnectionHandler.RealtimeFallbackThread, Photon.Realtime.Demo.ConnectAndJoinRandomLb.Start.
int Photon.Realtime.ConnectionHandler.CountSendAcksOnly
Counts how often the Fallback Thread called SendAcksOnly, which is purely of interest to monitor if the game logic called SendOutgoingCommands as intended.
Referenced by Photon.Realtime.ConnectionHandler.RealtimeFallbackThread.
bool Photon.Realtime.ConnectionHandler.FallbackThreadRunning
True if a fallback thread is running. Will call the client's SendAcksOnly() method to keep the connection up.
Referenced by Photon.Realtime.ConnectionHandler.StartFallbackSendAckThread, Photon.Realtime.ConnectionHandler.StopFallbackSendAckThread.
bool Photon.Realtime.ConnectionHandler.DisconnectAfterKeepAlive
Option to let the fallback thread call Disconnect after the KeepAliveInBackground time.
Default: false. If set to true, the thread will disconnect the client regularly, should the client not call SendOutgoingCommands / Service. This may happen due to an app being in background (and not getting a lot of CPU time) or when loading assets. If false, a regular timeout time will have to pass (on top) to time out the client.
int Photon.Realtime.ConnectionHandler.KeepAliveInBackground
Defines for how long the Fallback Thread should keep the connection, before it may time out as usual.
We want to the Client to keep it's connection when an app is in the background (and doesn't call Update / Service Clients should not keep their connection indefinitely in the background, so after some milliseconds, the Fallback Thread should stop keeping it up.
bool Photon.Realtime.ConnectionHandler.ApplyDontDestroyOnLoad
Keeps the ConnectionHandler, even if a new scene gets loaded.
bool Photon.Realtime.ConnectionHandler.AppQuits
Indicates that the app is closing. Set in OnApplicationQuit().
Referenced by Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonNetwork.LoadLevel.
byte Photon.Realtime.ConnectionHandler.fallbackThreadId
bool Photon.Realtime.ConnectionHandler.didSendAcks
readonly Stopwatch Photon.Realtime.ConnectionHandler.backgroundStopwatch
void Photon.Realtime.ConnectionHandler.StartFallbackSendAckThread()
References Photon.Realtime.ConnectionHandler.FallbackThreadRunning, Photon.Realtime.ConnectionHandler.RealtimeFallbackThread.
Referenced by Photon.Pun.PhotonHandler.OnEnable, Photon.Realtime.Demo.ConnectAndJoinRandomLb.Start.
void Photon.Realtime.ConnectionHandler.StopFallbackSendAckThread()
References Photon.Realtime.ConnectionHandler.FallbackThreadRunning.
bool Photon.Realtime.ConnectionHandler.RealtimeFallbackThread()
A thread which runs independent from the Update() calls. Keeps connections online while loading or in background. See KeepAliveInBackground.
References Photon.Realtime.ConnectionHandler.Client, Photon.Realtime.ConnectionHandler.CountSendAcksOnly, Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Realtime.LoadBalancingClient.IsConnected, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Realtime.LoadBalancingPeer.LoadBalancingPeer.
Referenced by Photon.Realtime.ConnectionHandler.StartFallbackSendAckThread.