Photon::Pun::Simple::VitalUI
GameObject Photon.Pun.Simple.VitalUI.vitalBarDefaultPrefab
bool Photon.Pun.Simple.VitalUI.autoOffset
Referenced by Photon.Pun.Simple.VitalUI.AutoAlign.
Vector3 Photon.Pun.Simple.VitalUI.offset
Referenced by Photon.Pun.Simple.VitalUI.AutoAlign.
float Photon.Pun.Simple.VitalUI.widthMultiplier
Referenced by Photon.Pun.Simple.VitalUI.Recalculate, Photon.Pun.Simple.VitalUI.UpdateGraphics.
bool Photon.Pun.Simple.VitalUI.searchChildren
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements.
Text Photon.Pun.Simple.VitalUI.UIText
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements, Photon.Pun.Simple.VitalUI.UpdateGraphics.
Image Photon.Pun.Simple.VitalUI.UIImage
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements, Photon.Pun.Simple.VitalUI.UpdateGraphics.
TextMesh Photon.Pun.Simple.VitalUI.textMesh
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements, Photon.Pun.Simple.VitalUI.UpdateGraphics.
SpriteRenderer Photon.Pun.Simple.VitalUI.barSprite
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements, Photon.Pun.Simple.VitalUI.UpdateGraphics.
SpriteRenderer Photon.Pun.Simple.VitalUI.backSprite
Referenced by Photon.Pun.Simple.VitalUI.FindUIElements, Photon.Pun.Simple.VitalUI.Recalculate.
bool Photon.Pun.Simple.VitalUI.billboard
Referenced by Photon.Pun.Simple.VitalUI.Awake.
const string Photon.Pun.Simple.VitalUI.PLACEHOLDER_CANVAS_NAME
List<SpriteRenderer> Photon.Pun.Simple.VitalUI.resuableFindSpriteRend
override void Photon.Pun.Simple.VitalUI.Reset()
References Photon.Pun.Simple.VitalUI.FindUIElements.
override void Photon.Pun.Simple.VitalUI.Awake()
References Photon.Pun.Simple.VitalUI.billboard, Photon.Pun.Simple.VitalUI.FindUIElements.
virtual void Photon.Pun.Simple.VitalUI.AutoAlign()
References Photon.Pun.Simple.VitalUI.autoOffset, Photon.Pun.Simple.VitalUI.offset, Photon.Pun.Simple.VitalUIBase.vitalIndex.
Referenced by Photon.Pun.Simple.VitalUI.Recalculate.
override void Photon.Pun.Simple.VitalUI.Recalculate()
References Photon.Pun.Simple.VitalUI.AutoAlign, Photon.Pun.Simple.VitalUI.backSprite, Photon.Pun.Simple.VitalUI.UpdateGraphics, Photon.Pun.Simple.VitalUIBase.vital, Photon.Pun.Simple.VitalUI.widthMultiplier.
bool Photon.Pun.Simple.VitalUI.FindUIElements()
Finds UI Elements.
References Photon.Pun.Simple.VitalUI.backSprite, Photon.Pun.Simple.VitalUI.barSprite, Photon.Pun.Simple.VitalUI.searchChildren, Photon.Pun.Simple.VitalUI.textMesh, Photon.Pun.Simple.VitalUI.UIImage, Photon.Pun.Simple.VitalUI.UIText.
Referenced by Photon.Pun.Simple.VitalUI.Awake, Photon.Pun.Simple.VitalUI.Reset.
override void Photon.Pun.Simple.VitalUI.UpdateGraphics(Vital vital)
References Photon.Pun.Simple.VitalUI.barSprite, Photon.Pun.Simple.VitalUIBase.targetField, Photon.Pun.Simple.VitalUI.textMesh, Photon.Pun.Simple.VitalUI.UIImage, Photon.Pun.Simple.VitalUI.UIText, Photon.Pun.Simple.VitalData.Value, Photon.Pun.Simple.VitalUIBase.vital, Photon.Pun.Simple.Vital.VitalData, Photon.Pun.Simple.Vital.VitalDef, Photon.Pun.Simple.VitalUI.widthMultiplier.
Referenced by Photon.Pun.Simple.VitalUI.Recalculate.
void Photon.Pun.Simple.VitalUI.LateUpdate()