Photon::Realtime::RegionHandler
Type Photon.Realtime.RegionHandler.PingImplementation
The implementation of PhotonPing to use for region pinging (Best Region detection).
Defaults to null, which means the Type is set automatically.
List<Region> Photon.Realtime.RegionHandler.EnabledRegions
A list of region names for the Photon Cloud.
Set by the result of OpGetRegions(). Implement ILoadBalancingCallbacks and register for the callbacks to get OnRegionListReceived(RegionHandler regionHandler). You can also put a "case OperationCode.GetRegions:" into your OnOperationResponse method to notice when the result is available.
Referenced by Photon.Realtime.RegionHandler.PingMinimumOfRegions, Photon.Realtime.RegionHandler.SetRegions.
Region Photon.Realtime.RegionHandler.BestRegion
When PingMinimumOfRegions was called and completed, the BestRegion is identified by best ping.
Referenced by Photon.Realtime.RegionHandler.GetResults.
string Photon.Realtime.RegionHandler.SummaryToCache
This value summarizes the results of pinging currently available regions (after PingMinimumOfRegions finished).
This value should be stored in the client by the game logic. When connecting again, use it as previous summary to speed up pinging regions and to make the best region sticky for the client.
bool Photon.Realtime.RegionHandler.IsPinging
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.RegionHandler.PingMinimumOfRegions.
string Photon.Realtime.RegionHandler.availableRegionCodes
Region Photon.Realtime.RegionHandler.bestRegionCache
List<RegionPinger> Photon.Realtime.RegionHandler.pingerList
Action<RegionHandler> Photon.Realtime.RegionHandler.onCompleteCall
int Photon.Realtime.RegionHandler.previousPing
string Photon.Realtime.RegionHandler.previousSummaryProvided
ushort Photon.Realtime.RegionHandler.PortToPingOverride
string Photon.Realtime.RegionHandler.GetResults()
References Photon.Realtime.RegionHandler.BestRegion, Photon.Realtime.RegionPinger.GetResults, Photon.Realtime.Region.ToString.
void Photon.Realtime.RegionHandler.SetRegions(OperationResponse opGetRegions)
References Photon.Realtime.ParameterCode.Address, Photon.Realtime.Region.Code, Photon.Realtime.RegionHandler.EnabledRegions, Photon.Realtime.OperationCode.GetRegions, Photon.Realtime.ErrorCode.Ok, Photon.Realtime.ParameterCode.Region.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
Photon.Realtime.RegionHandler.RegionHandler(ushort masterServerPortOverride=0)
bool Photon.Realtime.RegionHandler.PingMinimumOfRegions(Action< RegionHandler > onCompleteCallback, string previousSummary)
References Photon.Realtime.RegionHandler.EnabledRegions, Photon.Realtime.RegionHandler.IsPinging, Photon.Realtime.RegionPinger.PingWhenFailed, Photon.Realtime.RegionPinger.Start.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.Demo.ConnectAndJoinRandomLb.OnRegionListReceived, Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionListReceived.
void Photon.Realtime.RegionHandler.OnPreferredRegionPinged(Region preferredRegion)
bool Photon.Realtime.RegionHandler.PingEnabledRegions()
void Photon.Realtime.RegionHandler.OnRegionDone(Region region)