Photon::Compression::Matrix
TransformCrusher Photon.Compression.Matrix.crusher
Referenced by Photon.Compression.Matrix.Apply, Photon.Compression.Matrix.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.Matrix.Compress, Photon.Compression.MatrixExtensions.CopyFrom, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix, Photon.Compression.Matrix.Set.
Vector3 Photon.Compression.Matrix.position
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.MatrixExtensions.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.FastCompareUncompressed, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Set, Photon.Compression.Matrix.Set, Photon.Compression.Matrix.ToString, Photon.Pun.Simple.SyncTransform.Frame.ToString.
Element Photon.Compression.Matrix.rotation
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.MatrixExtensions.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.FastCompareUncompressed, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Set, Photon.Compression.Matrix.Set, Photon.Compression.Matrix.ToString, Photon.Pun.Simple.SyncTransform.Frame.ToString.
Vector3 Photon.Compression.Matrix.scale
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.CompressAndWrite, Photon.Compression.MatrixExtensions.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.FastCompareUncompressed, Photon.Compression.Matrix.Lerp, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Matrix.Matrix, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Set, Photon.Compression.Matrix.Set, Photon.Compression.Matrix.ToString.
Matrix Photon.Compression.Matrix.reusable
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.CompressedMatrix.Decompress, Photon.Compression.TransformCrusher.Decompress, Photon.Pun.Simple.SyncTransform.OnInterpolate, Photon.Compression.TransformCrusher.ReadAndDecompress.
Photon.Compression.Matrix.Matrix()
Photon.Compression.Matrix.Matrix(TransformCrusher crusher)
References Photon.Compression.Matrix.crusher.
Photon.Compression.Matrix.Matrix(TransformCrusher crusher, Vector3 position, Element rotation, Vector3 scale)
References Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.Matrix.scale.
Photon.Compression.Matrix.Matrix(TransformCrusher crusher, Transform transform)
References Photon.Compression.Matrix.crusher, Photon.Compression.ElementCrusher.local, Photon.Compression.TransformCrusher.PosCrusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.TransformCrusher.SclCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.Matrix.Set(TransformCrusher crusher, Vector3 position, Element rotation, Vector3 scale)
References Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.Matrix.scale.
Referenced by Photon.Compression.TransformCrusher.Decompress.
void Photon.Compression.Matrix.Set(TransformCrusher crusher, Transform transform)
References Photon.Compression.Matrix.Capture, Photon.Compression.Matrix.crusher.
void Photon.Compression.Matrix.Capture(TransformCrusher crusher, Transform transform)
Set Matrix values to the current values of the supplied Rigidbody.
Also set the crusher ref.
References Photon.Compression.Matrix.crusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Compression.Matrix.Set.
void Photon.Compression.Matrix.Set(Transform transform)
References Photon.Compression.Matrix.Capture.
void Photon.Compression.Matrix.Capture(Transform transform)
Set Matrix values to the current values of the supplied Transform
References Photon.Compression.Matrix.crusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.Matrix.Set(TransformCrusher crusher, Rigidbody rb)
References Photon.Compression.Matrix.Capture, Photon.Compression.Matrix.crusher.
void Photon.Compression.Matrix.Capture(TransformCrusher crusher, Rigidbody rb)
Set Matrix values to the current values of the supplied Rigidbody.
Also set the crusher ref.
References Photon.Compression.Matrix.crusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.Matrix.Set(Rigidbody rb)
References Photon.Compression.Matrix.Capture.
void Photon.Compression.Matrix.Capture(Rigidbody rb)
Set Matrix values to the current values of the supplied Rigidbody
References Photon.Compression.Matrix.crusher, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.ElementCrusher.TRSType.
void Photon.Compression.Matrix.Clear()
Referenced by Photon.Compression.CompressedMatrix.Decompress.
void Photon.Compression.Matrix.Compress(CompressedMatrix nonalloc)
Compress this matrix using the crusher it was previously created with.
References Photon.Compression.TransformCrusher.Compress, Photon.Compression.Matrix.crusher.
void Photon.Compression.Matrix.Apply()
Apply this TRS Matrix to the default transform, using the crusher that created this TRS Matrix.
Unused Axes will be left unchanged.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.Matrix.crusher.
void Photon.Compression.Matrix.Apply(Transform t)
Apply this TRS Matrix to the supplied transform, using the crusher that created this TRS Matrix.
Unused Axes will be left unchanged.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.Matrix.crusher.
void Photon.Compression.Matrix.Apply(Rigidbody rb)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.Matrix.crusher.
override string Photon.Compression.Matrix.ToString()
References Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.Matrix.scale, Photon.Compression.Element.vectorType.
static Matrix Photon.Compression.Matrix.Lerp(Matrix target, Matrix start, Matrix end, float t)
Lerp the position, rotation and scale of two Matrix objects, writing the results to the target Matrix.
target Result target. start end t Returns a reference to the supplied target matrix.
References Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.Element.Slerp, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnInterpolate.
static Matrix Photon.Compression.Matrix.LerpUnclamped(Matrix target, Matrix start, Matrix end, float t)
Unclamped Lerp the position, rotation and scale of two Matrix objects, writing the results to the target Matrix.
target Result target. start end t Returns a reference to the supplied target matrix.
References Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.Element.SlerpUnclamped, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Pun.Simple.SyncTransform.ExtrapolateFrame.
static Matrix Photon.Compression.Matrix.CatmullRomLerpUnclamped(Matrix target, Matrix pre, Matrix start, Matrix end, Matrix post, float t)
References Photon.Utilities.CatmulRom.CatmullRomLerp, Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.Element.SlerpUnclamped, Photon.Compression.ElementCrusher.TRSType.
Referenced by Photon.Pun.Simple.SyncTransform.OnInterpolate.
static Matrix Photon.Compression.Matrix.CatmullRomLerpUnclamped(Matrix target, Matrix pre, Matrix start, Matrix end, float t)
References Photon.Utilities.CatmulRom.CatmullRomLerp, Photon.Compression.Matrix.crusher, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.TransformCrusher.RotCrusher, Photon.Compression.Matrix.scale, Photon.Compression.Element.SlerpUnclamped, Photon.Compression.ElementCrusher.TRSType.