Photon::Pun::Simple::SyncTransform
Interpolation Photon.Pun.Simple.SyncTransform.interpolation
Referenced by Photon.Pun.Simple.SyncTransform.OnInterpolate.
float Photon.Pun.Simple.SyncTransform.extrapolateRatio
Referenced by Photon.Pun.Simple.SyncTransform.ExtrapolateFrame.
float Photon.Pun.Simple.SyncTransform.teleportThreshold
Referenced by Photon.Pun.Simple.SyncTransform.OnAwake, Photon.Pun.Simple.SyncTransform.OnSnapshot.
bool Photon.Pun.Simple.SyncTransform.teleportReliable
Referenced by Photon.Pun.Simple.SyncTransform.OnNetSerialize.
Dictionary<int, TransformCrusher> Photon.Pun.Simple.SyncTransform.masterSharedCrushers
TransformCrusher Photon.Pun.Simple.SyncTransform.transformCrusher
Referenced by Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.CaptureCurrent, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnInterpolate, Photon.Pun.Simple.SyncTransform.OnNetDeserialize, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Pun.Simple.SyncTransform.Frame.Set.
Frame Photon.Pun.Simple.SyncTransform.prevSentFrame
Referenced by Photon.Pun.Simple.SyncTransform.OnNetSerialize.
int Photon.Pun.Simple.SyncTransform.extrapolationCount
bool Photon.Pun.Simple.SyncTransform.hasTeleported
When IsMine: OnTeleport sets this true to indicate the next outgoing serialization should be flagged as a teleport.
When !IsMine: Is set during Snapshot to indicate that interpolation should not occur.
Referenced by Photon.Pun.Simple.SyncTransform.FlagTeleport, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnNetSerialize.
int Photon.Pun.Simple.SyncTransform.teleNewParentId
Referenced by Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.OnSnapshot, Photon.Pun.Simple.SyncTransform.UpdateParent.
Matrix Photon.Pun.Simple.SyncTransform.preTeleportM
Referenced by Photon.Pun.Simple.SyncTransform.FlagTeleport, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState.
CompressedMatrix Photon.Pun.Simple.SyncTransform.preTeleportCM
Referenced by Photon.Pun.Simple.SyncTransform.FlagTeleport, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState.
bool Photon.Pun.Simple.SyncTransform.allowInterpolation
Referenced by Photon.Pun.Simple.SyncTransform.OnAwake.
bool Photon.Pun.Simple.SyncTransform.allowReconstructionOfEmpty
Referenced by Photon.Pun.Simple.SyncTransform.OnAwake.
bool Photon.Pun.Simple.SyncTransform.skipInterpolation
Referenced by Photon.Pun.Simple.SyncTransform.OnInterpolate, Photon.Pun.Simple.SyncTransform.OnSnapshot.
float Photon.Pun.Simple.SyncTransform.teleportThresholdSqrMag
Rigidbody Photon.Pun.Simple.SyncTransform.rb
Rigidbody2D Photon.Pun.Simple.SyncTransform.rb2d
List<ITransformController> Photon.Pun.Simple.SyncTransform.iTransformControllers
override bool Photon.Pun.Simple.SyncTransform.AllowInterpolation
override bool Photon.Pun.Simple.SyncTransform.AllowReconstructionOfEmpty
override int Photon.Pun.Simple.SyncTransform.ApplyOrder
Stack<Frame[]> Photon.Pun.Simple.SyncTransform.framePool
Referenced by Photon.Pun.Simple.SyncTransform.PopulateFrames.
void Photon.Pun.Simple.SyncTransform.FlagTeleport()
Be sure to call this in the Capture segment BEFORE you reparent the object.
Captures and holds the current transform prior to changes you are about to make. pos rot scl
References Photon.Pun.Simple.SyncTransform.CaptureCurrent, Photon.Pun.Simple.SyncTransform.hasTeleported, Photon.Pun.Simple.NetComponent.IsMine, Photon.Pun.Simple.SyncTransform.preTeleportCM, Photon.Pun.Simple.SyncTransform.preTeleportM.
void Photon.Pun.Simple.SyncTransform.UpdateParent(ObjState state, Transform newParent)
Internal.
StateSync uses this method to tell the SyncTransform what the parent object is. SyncTransform needs to know about parent changes to avoid interpolating/extrapolating across parent changes. state newParent
References Photon.Pun.Simple.SyncTransform.teleNewParentId.
Referenced by Photon.Pun.Simple.SyncState.ApplySnapshot.
override void Photon.Pun.Simple.SyncTransform.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
References Photon.Pun.Simple.SyncTransform.allowInterpolation, Photon.Pun.Simple.SyncTransform.allowReconstructionOfEmpty, Photon.Pun.Simple.SyncTransform.teleportThreshold.
virtual void Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState(int frameId)
References Photon.Compression.TransformCrusher.Apply, Photon.Pun.Simple.SyncTransform.CaptureCurrent, Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.CompressedMatrix.CopyFrom, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::frames, Photon.Pun.Simple.SyncTransform.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.preTeleportCM, Photon.Pun.Simple.SyncTransform.preTeleportM, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.Frame.telem, Photon.Pun.Simple.SyncTransform.transformCrusher.
SerializationFlags Photon.Pun.Simple.SyncTransform.OnNetSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.CompressedMatrix.Equals, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::frames, Photon.Pun.Simple.SyncTransform.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Pun.Simple.IUseKeyframes.IsKeyframe, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.prevSentFrame, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.teleportReliable, Photon.Pun.Simple.SyncTransform.transformCrusher, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::useDeltas, Photon.Compression.TransformCrusher.Write.
SerializationFlags Photon.Pun.Simple.SyncTransform.OnNetDeserialize(int originFrameId, byte[] buffer, ref int bitposition, FrameArrival arrival)
References Photon.Pun.Simple.FrameBase.content, Photon.Compression.TransformCrusher.Decompress, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::frames, Photon.Pun.PhotonView.IsMine, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::offtickFrame, Photon.Pun.Simple.NetComponent.photonView, Photon.Compression.TransformCrusher.Read, Photon.Pun.Simple.SyncTransform.transformCrusher.
override bool Photon.Pun.Simple.SyncTransform.OnSnapshot(int prevFrameId, int snapFrameId, int targFrameId, bool prevIsValid, bool snapIsValid, bool targIsValid)
References Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.skipInterpolation, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::snapFrame, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::targFrame, Photon.Pun.Simple.SyncTransform.teleNewParentId, Photon.Pun.Simple.SyncTransform.teleportThreshold.
override bool Photon.Pun.Simple.SyncTransform.OnInterpolate(int snapFrameId, int targFrameId, float t)
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Pun.Simple.SyncTransform.interpolation, Photon.Compression.Matrix.Lerp, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::prevFrame, Photon.Compression.Matrix.reusable, Photon.Pun.Simple.SyncTransform.skipInterpolation, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::snapFrame, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::targFrame, Photon.Pun.Simple.SyncTransform.transformCrusher.
void Photon.Pun.Simple.SyncTransform.ConnectSharedCaches()
void Photon.Pun.Simple.SyncTransform.OnDestroy()
override void Photon.Pun.Simple.SyncTransform.PopulateFrames()
We reuse frame buffers for Transforms.
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncTransform.framePool, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::frames.
void Photon.Pun.Simple.SyncTransform.CaptureCurrent(Matrix m, CompressedMatrix cm, bool forceUseTransform=false)
References Photon.Compression.TransformCrusher.Capture, Photon.Pun.Simple.SyncTransform.transformCrusher.
Referenced by Photon.Pun.Simple.SyncTransform.FlagTeleport, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState.
void Photon.Pun.Simple.SyncTransform.ApplyFrame(Frame frame)
References Photon.Compression.TransformCrusher.Apply, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.telem, Photon.Pun.Simple.SyncTransform.transformCrusher.
Referenced by Photon.Pun.Simple.SyncTransform.OnSnapshot.
override void Photon.Pun.Simple.SyncTransform.InterpolateFrame(Frame targframe, Frame startframe, Frame endframe, float t)
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.TransformCrusher.Compress, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Compression.Matrix.Lerp, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.parentHash, Photon.Pun.Simple.SyncObject< SyncTransform.Frame >::targFrame, Photon.Pun.Simple.SyncTransform.Frame.telem, Photon.Pun.Simple.SyncTransform.transformCrusher.
override void Photon.Pun.Simple.SyncTransform.ExtrapolateFrame(Frame prevframe, Frame snapframe, Frame targframe)
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.TransformCrusher.Compress, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.extrapolateRatio, Photon.Pun.Simple.FrameBase.frameId, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Compression.Matrix.LerpUnclamped, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.parentHash, Photon.Pun.Simple.SyncTransform.Frame.telem, Photon.Pun.Simple.SyncTransform.teleNewParentId, Photon.Pun.Simple.SyncTransform.transformCrusher.