Photon::Pun::PhotonStreamQueue
int Photon.Pun.PhotonStreamQueue.m_SampleRate
int Photon.Pun.PhotonStreamQueue.m_SampleCount
int Photon.Pun.PhotonStreamQueue.m_ObjectsPerSample
float Photon.Pun.PhotonStreamQueue.m_LastSampleTime
int Photon.Pun.PhotonStreamQueue.m_LastFrameCount
int Photon.Pun.PhotonStreamQueue.m_NextObjectIndex
List<object> Photon.Pun.PhotonStreamQueue.m_Objects
bool Photon.Pun.PhotonStreamQueue.m_IsWriting
Photon.Pun.PhotonStreamQueue.PhotonStreamQueue(int sampleRate)
Initializes a new instance of the PhotonStreamQueue class.
sampleRate How many times per second should the object states be sampled
void Photon.Pun.PhotonStreamQueue.Reset()
Resets the PhotonStreamQueue.
You need to do this whenever the amount of objects you are observing changes
Referenced by Photon.Pun.PhotonAnimatorView.OnPhotonSerializeView.
void Photon.Pun.PhotonStreamQueue.SendNext(object obj)
Adds the next object to the queue.
This works just like PhotonStream.SendNext obj The object you want to add to the queue
bool Photon.Pun.PhotonStreamQueue.HasQueuedObjects()
Determines whether the queue has stored any objects
object Photon.Pun.PhotonStreamQueue.ReceiveNext()
Receives the next object from the queue.
This works just like PhotonStream.ReceiveNext
void Photon.Pun.PhotonStreamQueue.Serialize(PhotonStream stream)
Serializes the specified stream.
Call this in your OnPhotonSerializeView method to send the whole recorded stream. stream The PhotonStream you receive as a parameter in OnPhotonSerializeView
References Photon.Pun.PhotonStream.SendNext.
Referenced by Photon.Pun.PhotonAnimatorView.OnPhotonSerializeView.
void Photon.Pun.PhotonStreamQueue.Deserialize(PhotonStream stream)
Deserializes the specified stream.
Call this in your OnPhotonSerializeView method to receive the whole recorded stream. stream The PhotonStream you receive as a parameter in OnPhotonSerializeView
References Photon.Pun.PhotonStream.ReceiveNext.
Referenced by Photon.Pun.PhotonAnimatorView.OnPhotonSerializeView.
void Photon.Pun.PhotonStreamQueue.BeginWritePackage()