Photon::Chat::ChatClient
const int Photon.Chat.ChatClient.FriendRequestListMax
const byte Photon.Chat.ChatClient.HttpForwardWebFlag
const string Photon.Chat.ChatClient.ChatAppName
const int Photon.Chat.ChatClient.DefaultMaxSubscribers
Default maximum value possible for ChatChannel.MaxSubscribers when ChatChannel.PublishSubscribers is enabled
Referenced by Photon.Chat.ChatClient.Subscribe.
bool Photon.Chat.ChatClient.EnableProtocolFallback
Enables a fallback to another protocol in case a connect to the Name Server fails.
When connecting to the Name Server fails for a first time, the client will select an alternative network protocol and re-try to connect. The fallback will use the default Name Server port as defined by ProtocolToNameServerPort. The fallback for TCP is UDP. All other protocols fallback to TCP.
Referenced by Photon.Chat.ChatClient.ConnectUsingSettings.
string Photon.Chat.ChatClient.NameServerAddress
The address of last connected Name Server.
Referenced by Photon.Chat.ChatClient.Connect.
string Photon.Chat.ChatClient.FrontendAddress
The address of the actual chat server assigned from NameServer. Public for read only.
string Photon.Chat.ChatClient.ChatRegion
Settable only before you connect! Defaults to "EU".
Referenced by Photon.Chat.ChatClient.ConnectUsingSettings.
ChatState Photon.Chat.ChatClient.State
Current state of the ChatClient. Also use CanChat.
Referenced by Photon.Chat.ChatClient.ChatClient, Photon.Chat.ChatClient.Connect, Photon.Chat.ChatClient.Disconnect.
ChatDisconnectCause Photon.Chat.ChatClient.DisconnectedCause
Disconnection cause. Check this inside IChatClientListener.OnDisconnected.
Referenced by Photon.Chat.ChatClient.Connect, Photon.Chat.ChatClient.Disconnect.
bool Photon.Chat.ChatClient.CanChat
Checks if this client is ready to send messages.
Referenced by Photon.Chat.ChatClient.AddFriends, Photon.Chat.ChatClient.CanChatInChannel, Photon.Chat.ChatClient.RemoveFriends, Photon.Chat.ChatClient.Subscribe, Photon.Chat.ChatClient.Unsubscribe.
bool Photon.Chat.ChatClient.HasPeer
string Photon.Chat.ChatClient.AppVersion
The version of your client. A new version also creates a new "virtual app" to separate players from older client versions.
Referenced by Photon.Chat.ChatClient.Connect.
string Photon.Chat.ChatClient.AppId
The AppID as assigned from the Photon Cloud.
Referenced by Photon.Chat.ChatClient.Connect.
AuthenticationValues Photon.Chat.ChatClient.AuthValues
Settable only before you connect!
Referenced by Photon.Chat.Demo.ChatGui.Connect, Photon.Chat.ChatClient.Connect.
string? Photon.Chat.ChatClient.UserId
The unique ID of a user/person, stored in AuthValues.UserId.
Set it before you connect. This value wraps AuthValues.UserId. It's not a nickname and we assume users with the same userID are the same person.
Referenced by Photon.Chat.ChatClient.GetPrivateChannelNameByUser.
bool Photon.Chat.ChatClient.UseBackgroundWorkerForSending
Defines if a background thread will call SendOutgoingCommands, while your code calls Service to dispatch received messages.
The benefit of using a background thread to call SendOutgoingCommands is this: Even if your game logic is being paused, the background thread will keep the connection to the server up. On a lower level, acknowledgements and pings will prevent a server-side timeout while (e.g.) Unity loads assets. Your game logic still has to call Service regularly, or else incoming messages are not dispatched. As this typically triggers UI updates, it's easier to call Service from the main/UI thread.
Referenced by Photon.Chat.Demo.ChatGui.Connect, Photon.Chat.ChatClient.Connect, Photon.Chat.ChatClient.Service.
ConnectionProtocol? Photon.Chat.ChatClient.TransportProtocol
Exposes the TransportProtocol of the used PhotonPeer. Settable while not connected.
Referenced by Photon.Chat.ChatClient.Connect, Photon.Chat.ChatClient.ConnectUsingSettings.
Dictionary<ConnectionProtocol, Type> Photon.Chat.ChatClient.SocketImplementationConfig
Defines which IPhotonSocket class to use per ConnectionProtocol.
Several platforms have special Socket implementations and slightly different APIs. To accomodate this, switching the socket implementation for a network protocol was made available. By default, UDP and TCP have socket implementations assigned. You only need to set the SocketImplementationConfig once, after creating a PhotonPeer and before connecting. If you switch the TransportProtocol, the correct implementation is being used.
DebugLevel Photon.Chat.ChatClient.DebugOut
Sets the level (and amount) of debug output provided by the library.
This affects the callbacks to IChatClientListener.DebugReturn. Default Level: Error.
Referenced by Photon.Chat.ChatClient.AddFriends, Photon.Chat.ChatClient.ConnectUsingSettings, Photon.Chat.ChatClient.RemoveFriends, Photon.Chat.ChatClient.Subscribe, Photon.Chat.ChatClient.Unsubscribe.
string Photon.Chat.ChatClient.chatRegion
Region used to connect to. Currently all chat is done in EU. It can make sense to use only one region for the whole game.
readonly HashSet<string> Photon.Chat.ChatClient.PublicChannelsUnsubscribing
readonly IChatClientListener Photon.Chat.ChatClient.listener
bool Photon.Chat.ChatClient.didAuthenticate
int? Photon.Chat.ChatClient.statusToSetWhenConnected
object Photon.Chat.ChatClient.messageToSetWhenConnected
int Photon.Chat.ChatClient.msDeltaForServiceCalls
int Photon.Chat.ChatClient.msTimestampOfLastServiceCall
int Photon.Chat.ChatClient.MessageLimit
If greater than 0, new channels will limit the number of messages they cache locally.
This can be useful to limit the amount of memory used by chats. You can set a MessageLimit per channel but this value gets applied to new ones. Note: Changing this value, does not affect ChatChannels that are already in use!
int Photon.Chat.ChatClient.PrivateChatHistoryLength
Limits the number of messages from private channel histories.
This is applied to all private channels on reconnect, as there is no explicit re-joining private channels. Default is -1, which gets available messages up to a maximum set by the server. A value of 0 gets you zero messages. The server's limit of messages may be lower. If so, the server's value will overrule this.
readonly Dictionary<string, ChatChannel> Photon.Chat.ChatClient.PublicChannels
Public channels this client is subscribed to.
Referenced by Photon.Chat.ChatClient.CanChatInChannel.
readonly Dictionary<string, ChatChannel> Photon.Chat.ChatClient.PrivateChannels
Private channels in which this client has exchanged messages.
ChatPeer Photon.Chat.ChatClient.chatPeer
The Chat Peer used by this client.
bool Photon.Chat.ChatClient.CanChatInChannel(string channelName)
Checks if this client is ready to publish messages inside a public channel.
channelName The channel to do the check with. Whether or not this client is ready to publish messages inside the public channel with the specified channelName.
References Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatClient.PublicChannels.
Photon.Chat.ChatClient.ChatClient(IChatClientListener listener, ConnectionProtocol protocol=ConnectionProtocol.Udp)
Chat client constructor.
listener The chat listener implementation. protocol Connection protocol to be used by this client. Default is ConnectionProtocol.Udp.
References Photon.Chat.ChatClient.State.
bool Photon.Chat.ChatClient.ConnectUsingSettings(ChatAppSettings appSettings)
References Photon.Chat.ChatAppSettings.AppIdChat, Photon.Chat.ChatAppSettings.AppVersion, Photon.Chat.ChatClient.ChatRegion, Photon.Chat.ChatClient.Connect, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatAppSettings.EnableProtocolFallback, Photon.Chat.ChatClient.EnableProtocolFallback, Photon.Chat.ChatAppSettings.FixedRegion, Photon.Chat.ChatAppSettings.IsDefaultNameServer, Photon.Chat.ChatPeer.NameServerHost, Photon.Chat.ChatPeer.NameServerPortOverride, Photon.Chat.ChatAppSettings.NetworkLogging, Photon.Chat.ChatAppSettings.Port, Photon.Chat.ChatAppSettings.Protocol, Photon.Chat.ChatAppSettings.Server, Photon.Chat.ChatClient.TransportProtocol.
Referenced by Photon.Chat.Demo.ChatGui.Connect.
bool Photon.Chat.ChatClient.Connect(string appId, string appVersion, AuthenticationValues authValues)
Connects this client to the Photon Chat Cloud service, which will also authenticate the user (and set a UserId).
appId Get your Photon Chat AppId from the Dashboard. appVersion Any version string you make up. Used to separate users and variants of your clients, which might be incompatible. authValues Values for authentication. You can leave this null, if you set a UserId before. If you set authValues, they will override any UserId set before.
References Photon.Chat.ChatClient.AppId, Photon.Chat.ChatClient.AppVersion, Photon.Chat.ChatClient.AuthValues, Photon.Chat.ChatPeer.Connect, Photon.Chat.ChatClient.DisconnectedCause, Photon.Chat.ChatClient.NameServerAddress, Photon.Chat.ChatPeer.NameServerAddress, Photon.Chat.ChatClient.State, Photon.Chat.ChatClient.TransportProtocol, Photon.Chat.ChatClient.UseBackgroundWorkerForSending.
Referenced by Photon.Chat.ChatClient.ConnectAndSetStatus, Photon.Chat.ChatClient.ConnectUsingSettings.
bool Photon.Chat.ChatClient.ConnectAndSetStatus(string appId, string appVersion, AuthenticationValues authValues, int status=ChatUserStatus.Online, object message=null)
Connects this client to the Photon Chat Cloud service, which will also authenticate the user (and set a UserId).
This also sets an online status once connected. By default it will set user status to ChatUserStatus.Online. See SetOnlineStatus(int,object) for more information. appId Get your Photon Chat AppId from the Dashboard. appVersion Any version string you make up. Used to separate users and variants of your clients, which might be incompatible. authValues Values for authentication. You can leave this null, if you set a UserId before. If you set authValues, they will override any UserId set before. status User status to set when connected. Predefined states are in class ChatUserStatus. Other values can be used at will. message Optional status Also sets a status-message which your friends can get. If the connection attempt could be sent at all.
References Photon.Chat.ChatClient.Connect.
void Photon.Chat.ChatClient.Service()
Must be called regularly to keep connection between client and server alive and to process incoming messages.
This method limits the effort it does automatically using the private variable msDeltaForServiceCalls. That value is lower for connect and multiplied by 4 when chat-server connection is ready.
References Photon.Chat.ChatClient.UseBackgroundWorkerForSending.
Referenced by Photon.Chat.Demo.ChatGui.Update.
void Photon.Chat.ChatClient.SendAcksOnly()
Obsolete: Better use UseBackgroundWorkerForSending and Service().
void Photon.Chat.ChatClient.Disconnect(ChatDisconnectCause cause=ChatDisconnectCause.DisconnectByClientLogic)
Disconnects from the Chat Server by sending a "disconnect command", which prevents a timeout server-side.
References Photon.Chat.ChatClient.DisconnectedCause, Photon.Chat.ChatClient.State.
Referenced by Photon.Chat.Demo.ChatGui.OnApplicationQuit, Photon.Chat.Demo.ChatGui.OnDestroy.
void Photon.Chat.ChatClient.StopThread()
Locally shuts down the connection to the Chat Server.
This resets states locally but the server will have to timeout this peer.
bool Photon.Chat.ChatClient.Subscribe(string[] channels)
Sends operation to subscribe to a list of channels by name.
channels List of channels to subscribe to. Avoid null or empty values. If the operation could be sent at all (Example: Fails if not connected to Chat Server).
References Photon.Chat.ChatClient.Subscribe.
Referenced by Photon.Chat.Demo.ChatGui.OnConnected, Photon.Chat.ChatClient.Subscribe.
bool Photon.Chat.ChatClient.Subscribe(string[] channels, int[] lastMsgIds)
Sends operation to subscribe to a list of channels by name and possibly retrieve messages we did not receive while unsubscribed.
channels List of channels to subscribe to. Avoid null or empty values. lastMsgIds ID of last message received per channel. Useful when re subscribing to receive only messages we missed. If the operation could be sent at all (Example: Fails if not connected to Chat Server).
References Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatParameterCode.Channels, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatParameterCode.HistoryLength, Photon.Chat.ChatParameterCode.MsgIds, Photon.Chat.ChatOperationCode.Subscribe.
bool Photon.Chat.ChatClient.Subscribe(string[] channels, int messagesFromHistory)
Sends operation to subscribe client to channels, optionally fetching a number of messages from the cache.
Subscribes channels will forward new messages to this user. Use PublishMessage to do so. The messages cache is limited but can be useful to get into ongoing conversations, if that's needed. channels List of channels to subscribe to. Avoid null or empty values. messagesFromHistory 0: no history. 1 and higher: number of messages in history. -1: all available history. If the operation could be sent at all (Example: Fails if not connected to Chat Server).
References Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatOperationCode.Subscribe.
bool Photon.Chat.ChatClient.Unsubscribe(string[] channels)
Unsubscribes from a list of channels, which stops getting messages from those.
The client will remove these channels from the PublicChannels dictionary once the server sent a response to this request. The request will be sent to the server and IChatClientListener.OnUnsubscribed gets called when the server actually removed the channel subscriptions. Unsubscribe will fail if you include null or empty channel names. channels Names of channels to unsubscribe. False, if not connected to a chat server.
References Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatOperationCode.Unsubscribe.
bool Photon.Chat.ChatClient.PublishMessage(string channelName, object message, bool forwardAsWebhook=false)
Sends a message to a public channel which this client subscribed to.
Before you publish to a channel, you have to subscribe it. Everyone in that channel will get the message. channelName Name of the channel to publish to. message Your message (string or any serializable data). forwardAsWebhook Optionally, public messages can be forwarded as webhooks. Configure webhooks for your Chat app to use this. False if the client is not yet ready to send messages.
Referenced by Photon.Chat.Demo.ChatGui.OnSubscribed.
bool Photon.Chat.ChatClient.SendPrivateMessage(string target, object message, bool forwardAsWebhook=false)
Sends a private message to a single target user.
Calls OnPrivateMessage on the receiving client. target Username to send this message to. message The message you want to send. Can be a simple string or anything serializable. forwardAsWebhook Optionally, private messages can be forwarded as webhooks. Configure webhooks for your Chat app to use this. True if this clients can send the message to the server.
References Photon.Chat.ChatClient.SendPrivateMessage.
Referenced by Photon.Chat.ChatClient.SendPrivateMessage.
bool Photon.Chat.ChatClient.SendPrivateMessage(string target, object message, bool encrypt, bool forwardAsWebhook)
Sends a private message to a single target user.
Calls OnPrivateMessage on the receiving client. target Username to send this message to. message The message you want to send. Can be a simple string or anything serializable. encrypt Optionally, private messages can be encrypted. Encryption is not end-to-end as the server decrypts the message. forwardAsWebhook Optionally, private messages can be forwarded as webhooks. Configure webhooks for your Chat app to use this. True if this clients can send the message to the server.
bool Photon.Chat.ChatClient.SetOnlineStatus(int status)
Sets the user's status without changing your status-message.
The predefined status values can be found in class ChatUserStatus. State ChatUserStatus.Invisible will make you offline for everyone and send no message. You can set custom values in the status integer. Aside from the pre-configured ones, all states will be considered visible and online. Else, no one would see the custom state. This overload does not change the set message. status Predefined states are in class ChatUserStatus. Other values can be used at will. True if the operation gets called on the server.
bool Photon.Chat.ChatClient.SetOnlineStatus(int status, object message)
Sets the user's status without changing your status-message.
The predefined status values can be found in class ChatUserStatus. State ChatUserStatus.Invisible will make you offline for everyone and send no message. You can set custom values in the status integer. Aside from the pre-configured ones, all states will be considered visible and online. Else, no one would see the custom state. The message object can be anything that Photon can serialize, including (but not limited to) Hashtable, object[] and string. This value is defined by your own conventions. status Predefined states are in class ChatUserStatus. Other values can be used at will. message Also sets a status-message which your friends can get. True if the operation gets called on the server.
bool Photon.Chat.ChatClient.AddFriends(string[] friends)
Adds friends to a list on the Chat Server which will send you status updates for those.
AddFriends and RemoveFriends enable clients to handle their friend list in the Photon Chat server. Having users on your friends list gives you access to their current online status (and whatever info your client sets in it). Each user can set an online status consisting of an integer and an arbitrary (serializable) object. The object can be null, Hashtable, object[] or anything else Photon can serialize. The status is published automatically to friends (anyone who set your user ID with AddFriends). Photon flushes friends-list when a chat client disconnects, so it has to be set each time. If your community API gives you access to online status already, you could filter and set online friends in AddFriends. Actual friend relations are not persistent and have to be stored outside of Photon. friends Array of friend userIds. If the operation could be sent.
References Photon.Chat.ChatOperationCode.AddFriends, Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatParameterCode.Friends.
Referenced by Photon.Chat.Demo.ChatGui.OnConnected.
bool Photon.Chat.ChatClient.RemoveFriends(string[] friends)
Removes the provided entries from the list on the Chat Server and stops their status updates.
Photon flushes friends-list when a chat client disconnects. Unless you want to remove individual entries, you don't have to RemoveFriends. AddFriends and RemoveFriends enable clients to handle their friend list in the Photon Chat server. Having users on your friends list gives you access to their current online status (and whatever info your client sets in it). Each user can set an online status consisting of an integer and an arbitratry (serializable) object. The object can be null, Hashtable, object[] or anything else Photon can serialize. The status is published automatically to friends (anyone who set your user ID with AddFriends). Photon flushes friends-list when a chat client disconnects, so it has to be set each time. If your community API gives you access to online status already, you could filter and set online friends in AddFriends. Actual friend relations are not persistent and have to be stored outside of Photon. AddFriends and RemoveFriends enable clients to handle their friend list in the Photon Chat server. Having users on your friends list gives you access to their current online status (and whatever info your client sets in it). Each user can set an online status consisting of an integer and an arbitratry (serializable) object. The object can be null, Hashtable, object[] or anything else Photon can serialize. The status is published automatically to friends (anyone who set your user ID with AddFriends). Actual friend relations are not persistent and have to be stored outside of Photon. friends Array of friend userIds. If the operation could be sent.
References Photon.Chat.ChatClient.CanChat, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChatParameterCode.Friends, Photon.Chat.ChatOperationCode.RemoveFriends.
string Photon.Chat.ChatClient.GetPrivateChannelNameByUser(string userName)
Get you the (locally used) channel name for the chat between this client and another user.
userName Remote user's name or UserId. The (locally used) channel name for a private channel. Do not subscribe to this channel. Private channels do not need to be explicitly subscribed to. Use this for debugging purposes mainly.
References Photon.Chat.ChatClient.UserId.
Referenced by Photon.Chat.ChatClient.TryGetPrivateChannelByUser.
bool Photon.Chat.ChatClient.TryGetChannel(string channelName, bool isPrivate, out ChatChannel channel)
Simplified access to either private or public channels by name.
channelName Name of the channel to get. For private channels, the channel-name is composed of both user's names. isPrivate Define if you expect a private or public channel. channel Out parameter gives you the found channel, if any. True if the channel was found. Public channels exist only when subscribed to them. Private channels exist only when at least one message is exchanged with the target user privately.
Referenced by Photon.Chat.Demo.ChatGui.AddMessageToSelectedChannel, Photon.Chat.Demo.ChatGui.ShowChannel, Photon.Chat.ChatClient.TryGetPrivateChannelByUser.
bool Photon.Chat.ChatClient.TryGetChannel(string channelName, out ChatChannel channel)
Simplified access to all channels by name.
Checks public channels first, then private ones. channelName Name of the channel to get. channel Out parameter gives you the found channel, if any. True if the channel was found. Public channels exist only when subscribed to them. Private channels exist only when at least one message is exchanged with the target user privately.
bool Photon.Chat.ChatClient.TryGetPrivateChannelByUser(string userId, out ChatChannel channel)
Simplified access to private channels by target user.
userId UserId of the target user in the private channel. channel Out parameter gives you the found channel, if any. True if the channel was found.
References Photon.Chat.ChatClient.GetPrivateChannelNameByUser, Photon.Chat.ChatClient.TryGetChannel.
bool Photon.Chat.ChatClient.Subscribe(string channel, int lastMsgId=0, int messagesFromHistory=-1, ChannelCreationOptions creationOptions=null)
Subscribe to a single channel and optionally sets its well-know channel properties in case the channel is created.
channel name of the channel to subscribe to lastMsgId ID of the last received message from this channel when re subscribing to receive only missed messages, default is 0 messagesFromHistory how many missed messages to receive from history, default is -1 (available history). 0 will get you no items. Positive values are capped by a server side limit. creationOptions options to be used in case the channel to subscribe to will be created.
References Photon.Chat.ChatParameterCode.Channels, Photon.Chat.ChatClient.DebugOut, Photon.Chat.ChannelCreationOptions.Default, Photon.Chat.ChatClient.DefaultMaxSubscribers, Photon.Chat.ChatParameterCode.HistoryLength, Photon.Chat.ChannelCreationOptions.MaxSubscribers, Photon.Chat.ChannelWellKnownProperties.MaxSubscribers, Photon.Chat.ChatParameterCode.MsgIds, Photon.Chat.ChatParameterCode.Properties, Photon.Chat.ChannelWellKnownProperties.PublishSubscribers, Photon.Chat.ChatOperationCode.Subscribe.
bool Photon.Chat.ChatClient.SendOutgoingInBackground()
Called by a separate thread, this sends outgoing commands of this peer, as long as it's connected.
True as long as the client is not disconnected.
bool Photon.Chat.ChatClient.publishMessage(string channelName, object message, bool reliable, bool forwardAsWebhook=false)
bool Photon.Chat.ChatClient.sendPrivateMessage(string target, object message, bool encrypt, bool reliable, bool forwardAsWebhook=false)
bool Photon.Chat.ChatClient.SetOnlineStatus(int status, object message, bool skipMessage)
Sets the user's status (pre-defined or custom) and an optional message.
The predefined status values can be found in class ChatUserStatus. State ChatUserStatus.Invisible will make you offline for everyone and send no message. You can set custom values in the status integer. Aside from the pre-configured ones, all states will be considered visible and online. Else, no one would see the custom state. The message object can be anything that Photon can serialize, including (but not limited to) Hashtable, object[] and string. This value is defined by your own conventions. status Predefined states are in class ChatUserStatus. Other values can be used at will. message Optional string message or null. skipMessage If true, the message gets ignored. It can be null but won't replace any current message. True if the operation gets called on the server.
void IPhotonPeerListener. Photon.Chat.ChatClient.DebugReturn(DebugLevel level, string message)
void IPhotonPeerListener. Photon.Chat.ChatClient.OnEvent(EventData eventData)
void IPhotonPeerListener. Photon.Chat.ChatClient.OnOperationResponse(OperationResponse operationResponse)
void IPhotonPeerListener. Photon.Chat.ChatClient.OnStatusChanged(StatusCode statusCode)
void Photon.Chat.ChatClient.TryAuthenticateOnNameServer()
bool Photon.Chat.ChatClient.SendChannelOperation(string[] channels, byte operation, int historyLength)
void Photon.Chat.ChatClient.HandlePrivateMessageEvent(EventData eventData)
void Photon.Chat.ChatClient.HandleChatMessagesEvent(EventData eventData)
void Photon.Chat.ChatClient.HandleSubscribeEvent(EventData eventData)
void Photon.Chat.ChatClient.HandleUnsubscribeEvent(EventData eventData)
void Photon.Chat.ChatClient.HandleAuthResponse(OperationResponse operationResponse)
void Photon.Chat.ChatClient.HandleStatusUpdate(EventData eventData)
bool Photon.Chat.ChatClient.ConnectToFrontEnd()
bool Photon.Chat.ChatClient.AuthenticateOnFrontEnd()
void Photon.Chat.ChatClient.HandleUserUnsubscribedEvent(EventData eventData)
void Photon.Chat.ChatClient.HandleUserSubscribedEvent(EventData eventData)
bool Photon.Chat.ChatClient.PublishMessageUnreliable(string channelName, object message, bool forwardAsWebhook=false)
bool Photon.Chat.ChatClient.SendPrivateMessageUnreliable(string target, object message, bool encrypt, bool forwardAsWebhook=false)