Photon::Compression::LiteIntCrusher
LiteIntCompressType Photon.Compression.LiteIntCrusher.compressType
Referenced by Photon.Compression.LiteIntCrusher.Decode, Photon.Compression.LiteIntCrusher.Encode, Photon.Compression.LiteIntCrusher.LiteIntCrusher, Photon.Compression.LiteIntCrusher.ReadCValue, Photon.Compression.LiteIntCrusher.ReadValue, Photon.Compression.LiteIntCrusher.WriteCValue, Photon.Compression.LiteIntCrusher.WriteValue.
int Photon.Compression.LiteIntCrusher.min
Referenced by Photon.Compression.LiteIntCrusher.LiteIntCrusher, Photon.Compression.LiteIntCrusher.Recalculate.
int Photon.Compression.LiteIntCrusher.max
Referenced by Photon.Compression.LiteIntCrusher.LiteIntCrusher, Photon.Compression.LiteIntCrusher.Recalculate.
int Photon.Compression.LiteIntCrusher.smallest
int Photon.Compression.LiteIntCrusher.biggest
Photon.Compression.LiteIntCrusher.LiteIntCrusher()
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType, Photon.Compression.LiteIntCrusher.max, Photon.Compression.LiteIntCrusher.min, Photon.Compression.LiteIntCrusher.Recalculate.
Photon.Compression.LiteIntCrusher.LiteIntCrusher(LiteIntCompressType compType=LiteIntCompressType.PackSigned, int min=sbyte.MinValue, int max=sbyte.MaxValue)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType, Photon.Compression.LiteIntCrusher.max, Photon.Compression.LiteIntCrusher.min, Photon.Compression.LiteIntCrusher.Recalculate.
override uint Photon.Compression.LiteIntCrusher.WriteValue(int val, byte[] buffer, ref int bitposition)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType, Photon.Compression.LiteIntCrusher.Encode.
override void Photon.Compression.LiteIntCrusher.WriteCValue(uint cval, byte[] buffer, ref int bitposition)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType.
override int Photon.Compression.LiteIntCrusher.ReadValue(byte[] buffer, ref int bitposition)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType, Photon.Compression.LiteIntCrusher.Decode.
override uint Photon.Compression.LiteIntCrusher.ReadCValue(byte[] buffer, ref int bitposition)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteIntCrusher.compressType.
override uint Photon.Compression.LiteIntCrusher.Encode(int value)
References Photon.Compression.LiteIntCrusher.compressType.
Referenced by Photon.Compression.LiteIntCrusher.WriteValue.
override int Photon.Compression.LiteIntCrusher.Decode(uint cvalue)
References Photon.Compression.LiteIntCrusher.compressType.
Referenced by Photon.Compression.LiteIntCrusher.ReadValue.
static void Photon.Compression.LiteIntCrusher.Recalculate(int min, int max, LiteIntCrusher crusher)
References Photon.Compression.LiteCrusher< TComp, T >.bits, Photon.Compression.LiteCrusher< uint, int >::GetBitsForMaxValue, Photon.Compression.LiteIntCrusher.max, Photon.Compression.LiteIntCrusher.min.
Referenced by Photon.Compression.LiteIntCrusher.LiteIntCrusher.
static void Photon.Compression.LiteIntCrusher.Recalculate(int min, int max, ref int smallest, ref int biggest, ref int bits)
References Photon.Compression.LiteCrusher< uint, int >::bits, Photon.Compression.LiteCrusher< uint, int >::GetBitsForMaxValue, Photon.Compression.LiteIntCrusher.max, Photon.Compression.LiteIntCrusher.min.