ScoreManager
ScoreManager ScoreManager.instance
Referenced by Chores.CleanToy, Chores.ClearTrash, CatTaskScript.DeliverFood, Chores.MakeBed, Chores.PutBack, Chores.PutDishesAway, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion.
const string ScoreManager.MainScore
Referenced by SetMainScore.
const string ScoreManager.BrokenFurnitureScore
Referenced by SetBrokenFurnitureScore, SetFixFurnitureScore.
const string ScoreManager.TotalTrapScore
Referenced by SetTrapScore.
int ScoreManager.mainScore
Referenced by Chores.CleanToy, Chores.ClearTrash, CatTaskScript.DeliverFood, Chores.MakeBed, Chores.PutBack, Chores.PutDishesAway.
int ScoreManager.trapScore
Referenced by SetTrapScore.
int ScoreManager.furniture1
Referenced by BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion.
int ScoreManager.furniture2
int ScoreManager.furniture3
int ScoreManager.totalFurnitureScore
TextMeshProUGUI ScoreManager.nameP1
TextMeshProUGUI ScoreManager.nameP2
TextMeshProUGUI ScoreManager.mainScoreP1
Referenced by Start.
TextMeshProUGUI ScoreManager.mainScoreP2
Referenced by Start.
TextMeshProUGUI ScoreManager.extraScoreP1
TextMeshProUGUI ScoreManager.extraScoreP2
TextMeshProUGUI ScoreManager.totalP1
TextMeshProUGUI ScoreManager.totalP2
TimerScript ScoreManager.timerScript
Referenced by Start.
ExitGames.Client.Photon.Hashtable ScoreManager.playerProperties
int ScoreManager.catMain
int ScoreManager.humanMain
int ScoreManager.catExtra
int ScoreManager.humanExtra
int ScoreManager.totalBrokenScore
int ScoreManager.totalTrapScore
void ScoreManager.Awake()
IEnumerator ScoreManager.ChangeScene(string sceneName)
void ScoreManager.UpdatePlayerPropertiesUI(Player targetPlayer)
void ScoreManager.SetMainScore(int score)
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.LocalPlayer, MainScore, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties.
Referenced by Chores.CleanToy, Chores.ClearTrash, CatTaskScript.DeliverFood, Chores.MakeBed, Chores.PutBack, Chores.PutDishesAway.
void ScoreManager.SetBrokenFurnitureScore(int score)
References BrokenFurnitureScore, Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.MasterClient, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties.
Referenced by BreakableFurniture.SpawnBrokenVersion.
void ScoreManager.SetFixFurnitureScore(int score)
References BrokenFurnitureScore, Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.MasterClient, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties.
Referenced by FixDestroyedFurniture.SpawnDefaultVersion.
void ScoreManager.SetTrapScore()
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties, TotalTrapScore, trapScore.
override void ScoreManager.OnPlayerPropertiesUpdate(Player targetPlayer, ExitGames.Client.Photon.Hashtable changedProps)
References Photon.Pun.PhotonNetwork.PlayerList.
void ScoreManager.Start()
References mainScoreP1, mainScoreP2, Photon.Pun.PhotonNetwork.PlayerList, timerScript.
void ScoreManager.BackToMenu()