Photon::Realtime::RegionPinger
int Photon.Realtime.RegionPinger.Attempts
Referenced by Photon.Realtime.RegionPinger.Start.
bool Photon.Realtime.RegionPinger.IgnoreInitialAttempt
int Photon.Realtime.RegionPinger.MaxMilliseconsPerPing
int Photon.Realtime.RegionPinger.PingWhenFailed
Referenced by Photon.Realtime.RegionHandler.PingMinimumOfRegions, Photon.Realtime.RegionPinger.RegionPinger.
Region Photon.Realtime.RegionPinger.region
string Photon.Realtime.RegionPinger.regionAddress
Action<Region> Photon.Realtime.RegionPinger.onDoneCall
PhotonPing Photon.Realtime.RegionPinger.ping
List<int> Photon.Realtime.RegionPinger.rttResults
int Photon.Realtime.RegionPinger.CurrentAttempt
bool Photon.Realtime.RegionPinger.Done
Referenced by Photon.Realtime.RegionPinger.RegionPinger, Photon.Realtime.RegionPinger.Start.
Photon.Realtime.RegionPinger.RegionPinger(Region region, Action< Region > onDoneCallback)
References Photon.Realtime.RegionPinger.Done, Photon.Realtime.Region.Ping, Photon.Realtime.RegionPinger.PingWhenFailed.
bool Photon.Realtime.RegionPinger.Start()
Starts the ping routine for the assigned region.
Pinging runs in a ThreadPool worker item or (if needed) in a Thread. WebGL runs pinging on the Main Thread as coroutine. Always true.
References Photon.Realtime.RegionPinger.Attempts, Photon.Realtime.Region.Code, Photon.Realtime.RegionPinger.Done, Photon.Realtime.Region.HostAndPort, Photon.Realtime.RegionPinger.ResolveHost.
Referenced by Photon.Realtime.RegionHandler.PingMinimumOfRegions.
string Photon.Realtime.RegionPinger.GetResults()
References Photon.Realtime.Region.Code.
Referenced by Photon.Realtime.RegionHandler.GetResults.
PhotonPing Photon.Realtime.RegionPinger.GetPingImplementation()
Selects the best fitting ping implementation or uses the one set in RegionHandler.PingImplementation.
PhotonPing instance to use.
void Photon.Realtime.RegionPinger.RegionPingPooled(object context)
bool Photon.Realtime.RegionPinger.RegionPingThreaded()
static string Photon.Realtime.RegionPinger.ResolveHost(string hostName)
Attempts to resolve a hostname into an IP string or returns empty string if that fails.
To be compatible with most platforms, the address family is checked like this: if (ipAddress.AddressFamily.ToString().Contains("6")) // ipv6... hostName Hostname to resolve. IP string or empty string if resolution fails
Referenced by Photon.Realtime.RegionPinger.Start.