Photon::Pun::Demo::SlotRacer::Utils::BezierSpline
Vector3 [] Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.points
float [] Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.lengths
float [] Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.lengthsTime
BezierControlPointMode [] Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.modes
bool Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.loop
float Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.TotalLength
bool Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.Loop
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSplineInspector.OnInspectorGUI.
int Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.ControlPointCount
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSplineInspector.OnInspectorGUI.
int Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.CurveCount
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPoint, Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetVelocity.
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.Awake()
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.EnforceMode(int index)
Vector3 Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetControlPoint(int index)
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.SetControlPoint(int index, Vector3 point)
BezierControlPointMode Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetControlPointMode(int index)
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.SetControlPointMode(int index, BezierControlPointMode mode)
Vector3 Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPoint(float t)
References Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.CurveCount, Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetPoint.
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.ComputeLengths, Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPositionAtDistance.
Vector3 Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetVelocity(float t)
References Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.CurveCount, Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetFirstDerivative.
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetDirection.
Vector3 Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetDirection(float t)
References Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetVelocity.
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.AddCurve()
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierSplineInspector.OnInspectorGUI.
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.Reset()
void Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.ComputeLengths()
References Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPoint.
Vector3 Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPositionAtDistance(float distance, bool reverse=false)
References Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPoint.
Referenced by Photon.Pun.Demo.SlotRacer.Utils.SplineWalker.ExecutePositioning.