Photon::Chat::ChatChannel
readonly string Photon.Chat.ChatChannel.Name
Name of the channel (used to subscribe and unsubscribe).
readonly List<string> Photon.Chat.ChatChannel.Senders
Senders of messages in chronological order. Senders and Messages refer to each other by index. Senders[x] is the sender of Messages[x].
readonly List<object> Photon.Chat.ChatChannel.Messages
Messages in chronological order. Senders and Messages refer to each other by index. Senders[x] is the sender of Messages[x].
int Photon.Chat.ChatChannel.MessageLimit
If greater than 0, this channel will limit the number of messages, that it caches locally.
Referenced by Photon.Chat.ChatChannel.TruncateMessages.
int Photon.Chat.ChatChannel.ChannelID
Unique channel ID.
readonly HashSet<string> Photon.Chat.ChatChannel.Subscribers
Subscribed users.
bool Photon.Chat.ChatChannel.IsPrivate
Is this a private 1:1 channel?
int Photon.Chat.ChatChannel.MessageCount
Count of messages this client still buffers/knows for this channel.
int Photon.Chat.ChatChannel.LastMsgId
ID of the last message received.
Referenced by Photon.Chat.ChatChannel.Add.
bool Photon.Chat.ChatChannel.PublishSubscribers
Whether or not this channel keeps track of the list of its subscribers.
int Photon.Chat.ChatChannel.MaxSubscribers
Maximum number of channel subscribers. 0 means infinite.
Dictionary<object, object> Photon.Chat.ChatChannel.properties
Photon.Chat.ChatChannel.ChatChannel(string name)
Used internally to create new channels. This does NOT create a channel on the server! Use ChatClient.Subscribe.
void Photon.Chat.ChatChannel.Add(string sender, object message, int msgId)
Used internally to add messages to this channel.
References Photon.Chat.ChatChannel.LastMsgId, Photon.Chat.ChatChannel.TruncateMessages.
Referenced by Photon.Chat.Demo.ChatGui.AddMessageToSelectedChannel.
void Photon.Chat.ChatChannel.Add(string[] senders, object[] messages, int lastMsgId)
Used internally to add messages to this channel.
References Photon.Chat.ChatChannel.LastMsgId, Photon.Chat.ChatChannel.TruncateMessages.
void Photon.Chat.ChatChannel.TruncateMessages()
Reduces the number of locally cached messages in this channel to the MessageLimit (if set).
References Photon.Chat.ChatChannel.MessageLimit.
Referenced by Photon.Chat.ChatChannel.Add.
void Photon.Chat.ChatChannel.ClearMessages()
Clear the local cache of messages currently stored. This frees memory but doesn't affect the server.
string Photon.Chat.ChatChannel.ToStringMessages()
Provides a string-representation of all messages in this channel.
All known messages in format "Sender: Message", line by line.
Referenced by Photon.Chat.Demo.ChatGui.ShowChannel.
void Photon.Chat.ChatChannel.ReadChannelProperties(Dictionary< object, object > newProperties)
void Photon.Chat.ChatChannel.AddSubscribers(string[] users)