Photon::Compression::LiteFloatCrusher
Normalization
Normalization Photon.Compression.LiteFloatCrusher.normalization
Referenced by Photon.Compression.LiteFloatCrusher.LiteFloatCrusher.
LiteFloatCompressType Photon.Compression.LiteFloatCrusher.compressType
Referenced by Photon.Compression.LiteFloatCrusher.Decode, Photon.Compression.LiteFloatCrusher.Encode, Photon.Compression.LiteFloatCrusher.LiteFloatCrusher, Photon.Compression.LiteFloatCrusher.ReadCValue, Photon.Compression.LiteFloatCrusher.ReadValue, Photon.Compression.LiteFloatCrusher.Recalculate, Photon.Compression.LiteFloatCrusher.WriteCValue, Photon.Compression.LiteFloatCrusher.WriteValue.
LiteOutOfBoundsHandling Photon.Compression.LiteFloatCrusher.outOfBoundsHandling
Referenced by Photon.Compression.LiteFloatCrusher.Encode, Photon.Compression.LiteFloatCrusher.LiteFloatCrusher.
float Photon.Compression.LiteFloatCrusher.min
Referenced by Photon.Compression.LiteFloatCrusher.Decode, Photon.Compression.LiteFloatCrusher.Encode, Photon.Compression.LiteFloatCrusher.LiteFloatCrusher, Photon.Compression.LiteFloatCrusher.Recalculate.
float Photon.Compression.LiteFloatCrusher.max
Referenced by Photon.Compression.LiteFloatCrusher.Decode, Photon.Compression.LiteFloatCrusher.LiteFloatCrusher, Photon.Compression.LiteFloatCrusher.Recalculate.
bool Photon.Compression.LiteFloatCrusher.accurateCenter
float Photon.Compression.LiteFloatCrusher.encoder
float Photon.Compression.LiteFloatCrusher.decoder
ulong Photon.Compression.LiteFloatCrusher.maxCVal
Photon.Compression.LiteFloatCrusher.LiteFloatCrusher()
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min, Photon.Compression.LiteFloatCrusher.Recalculate.
Photon.Compression.LiteFloatCrusher.LiteFloatCrusher(LiteFloatCompressType compressType, float min, float max, bool accurateCenter, LiteOutOfBoundsHandling outOfBoundsHandling=LiteOutOfBoundsHandling.Clamp)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min, Photon.Compression.LiteFloatCrusher.outOfBoundsHandling, Photon.Compression.LiteFloatCrusher.Recalculate.
Photon.Compression.LiteFloatCrusher.LiteFloatCrusher(LiteFloatCompressType compressType, Normalization normalization=Normalization.None, LiteOutOfBoundsHandling outOfBoundsHandling=LiteOutOfBoundsHandling.Clamp)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min, Photon.Compression.LiteFloatCrusher.normalization, Photon.Compression.LiteFloatCrusher.outOfBoundsHandling, Photon.Compression.LiteFloatCrusher.Recalculate.
override ulong Photon.Compression.LiteFloatCrusher.Encode(float val)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.min, Photon.Compression.LiteFloatCrusher.outOfBoundsHandling.
Referenced by Photon.Pun.Simple.SyncNodeMover.OnCaptureCurrentState, Photon.Compression.Internal.SyncRangedAttribute.Pack, Photon.Compression.LiteFloatCrusher.WriteValue.
override float Photon.Compression.LiteFloatCrusher.Decode(uint cval)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min.
Referenced by Photon.Pun.Simple.SyncNodeMover.OnNetDeserialize, Photon.Compression.LiteFloatCrusher.ReadValue.
override ulong Photon.Compression.LiteFloatCrusher.WriteValue(float val, byte[] buffer, ref int bitposition)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.Encode.
Referenced by Photon.Pun.Simple.SyncNodeMover.OnNetSerialize.
override void Photon.Compression.LiteFloatCrusher.WriteCValue(uint cval, byte[] buffer, ref int bitposition)
References Photon.Compression.LiteFloatCrusher.compressType.
Referenced by Photon.Compression.Internal.SyncRangedAttribute.Pack.
override float Photon.Compression.LiteFloatCrusher.ReadValue(byte[] buffer, ref int bitposition)
References Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.Decode, Photon.Compression.ByteConverter.float32.
Referenced by Photon.Compression.Internal.SyncRangedAttribute.Unpack.
override ulong Photon.Compression.LiteFloatCrusher.ReadCValue(byte[] buffer, ref int bitposition)
References Photon.Compression.LiteFloatCrusher.compressType.
Referenced by Photon.Pun.Simple.SyncNodeMover.OnNetDeserialize.
static void Photon.Compression.LiteFloatCrusher.Recalculate(LiteFloatCompressType compressType, float min, float max, bool accurateCenter, LiteFloatCrusher crusher)
References Photon.Compression.LiteCrusher< TComp, T >.bits, Photon.Compression.LiteCrusher< ulong, float >::bits, Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min.
Referenced by Photon.Compression.LiteFloatCrusher.LiteFloatCrusher, Photon.Compression.Internal.SyncRangedAttribute.SyncRangedAttribute.
static void Photon.Compression.LiteFloatCrusher.Recalculate(LiteFloatCompressType compressType, float min, float max, bool accurateCenter, ref int bits, ref float encoder, ref float decoder, ref ulong maxCVal)
References Photon.Compression.LiteCrusher< ulong, float >::bits, Photon.Compression.LiteFloatCrusher.compressType, Photon.Compression.LiteFloatCrusher.max, Photon.Compression.LiteFloatCrusher.min.