Photon::Compression::CompressedElement
CompressedElement Photon.Compression.CompressedElement.reusable
Referenced by Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.Read.
readonly CompressedElement Photon.Compression.CompressedElement.Empty
CompressedFloat Photon.Compression.CompressedElement.cx
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.AsArray32, Photon.Compression.CompressedElement.AsArray64, Photon.Compression.CompressedElement.AsArray8, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.CopyFrom, Photon.Compression.CompressedElement.CopyTo, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.CompressedElement.Equals, Photon.Compression.CompressedElement.Extrapolate, Photon.Compression.CompressedElement.GetGuessableBitCullLevel, Photon.Compression.CompressedElement.GetHashCode, Photon.Compression.CompressedElement.GetUInt, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TestMatchingUpper, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
CompressedFloat Photon.Compression.CompressedElement.cy
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.AsArray32, Photon.Compression.CompressedElement.AsArray64, Photon.Compression.CompressedElement.AsArray8, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.CopyFrom, Photon.Compression.CompressedElement.CopyTo, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.CompressedElement.Equals, Photon.Compression.CompressedElement.Extrapolate, Photon.Compression.CompressedElement.GetGuessableBitCullLevel, Photon.Compression.CompressedElement.GetHashCode, Photon.Compression.CompressedElement.GetUInt, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TestMatchingUpper, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
CompressedFloat Photon.Compression.CompressedElement.cz
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.AsArray32, Photon.Compression.CompressedElement.AsArray64, Photon.Compression.CompressedElement.AsArray8, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.CopyFrom, Photon.Compression.CompressedElement.CopyTo, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.CompressedElement.Equals, Photon.Compression.CompressedElement.Extrapolate, Photon.Compression.CompressedElement.GetGuessableBitCullLevel, Photon.Compression.CompressedElement.GetHashCode, Photon.Compression.CompressedElement.GetUInt, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.TestMatchingUpper, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
CompressedFloat Photon.Compression.CompressedElement.cUniform
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.CompressedElement.Equals, Photon.Compression.CompressedElement.GetHashCode, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write.
CompressedQuat Photon.Compression.CompressedElement.cQuat
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.CompressedElement.Equals, Photon.Compression.ElementCrusher.FindBestBitCullLevel, Photon.Compression.CompressedElement.FindBestBitCullLevel, Photon.Compression.CompressedElement.GetHashCode, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.ToString, Photon.Compression.ElementCrusher.Write.
ElementCrusher Photon.Compression.CompressedElement.crusher
Referenced by Photon.Compression.CompressedElementExt.AppendSB, Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.CopyFrom, Photon.Compression.CompressedElement.CopyTo, Photon.Compression.CompressedElement.Decompress, Photon.Compression.CompressedElement.Extrapolate, Photon.Compression.CompressedElement.FindBestBitCullLevel, Photon.Compression.CompressedElement.operator byte, Photon.Compression.CompressedElement.operator Quaternion, Photon.Compression.CompressedElement.operator uint, Photon.Compression.CompressedElement.operator ulong, Photon.Compression.CompressedElement.operator ushort, Photon.Compression.CompressedElement.operator Vector3, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.CompressedElement.Serialize, Photon.Compression.CompressedElement.Set, Photon.Compression.CompressedElement.TestMatchingUpper, Photon.Compression.CompressedElement.ToString, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
readonly ulong [] Photon.Compression.CompressedElement.reusableArray64
readonly uint [] Photon.Compression.CompressedElement.reusableArray32
readonly byte [] Photon.Compression.CompressedElement.reusableArray8
CompressedElement Photon.Compression.CompressedElement.uppers
CompressedElement Photon.Compression.CompressedElement.lowers
uint?? Photon.Compression.CompressedElement.this[int axis]
void Photon.Compression.CompressedElement.Clear()
Referenced by Photon.Compression.CompressedMatrix.Clear, Photon.Compression.ElementCrusher.Compress, Photon.Compression.TransformCrusher.Compress.
ulong[] Photon.Compression.CompressedElement.AsArray64(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
void Photon.Compression.CompressedElement.AsArray64(ulong[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
uint[] Photon.Compression.CompressedElement.AsArray32(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
void Photon.Compression.CompressedElement.AsArray32(uint[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
byte[] Photon.Compression.CompressedElement.AsArray8(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
void Photon.Compression.CompressedElement.AsArray8(byte[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedElement into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Photon.Compression.CompressedElement.CompressedElement()
Referenced by Photon.Compression.CompressedElement.Extrapolate.
Photon.Compression.CompressedElement.CompressedElement(ElementCrusher crusher, CompressedFloat cx, CompressedFloat cy, CompressedFloat cz)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Photon.Compression.CompressedElement.CompressedElement(ElementCrusher crusher, uint cx, uint cy, uint cz)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Photon.Compression.CompressedElement.CompressedElement(ElementCrusher crusher, uint cUniform)
A uint argument indicates compressed uniform scale.
A ulong argument indicates a compressed quaternion. Be sure to cast ulongs down to uint, or your scale we be treated as quaternion values for this constructor. crusher cUniform ubits
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cUniform, Photon.Compression.ElementCrusher.UCrusher.
Photon.Compression.CompressedElement.CompressedElement(ElementCrusher crusher, ulong cQuat)
A uint argument indicates compressed uniform scale.
A ulong argument indicates a compressed quaternion. crusher cQuat qbits
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.QCrusher.
void Photon.Compression.CompressedElement.Set(ElementCrusher crusher, CompressedFloat cx, CompressedFloat cy, CompressedFloat cz)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Referenced by Photon.Compression.ElementCrusher.Compress, Photon.Compression.CompressedElement.Extrapolate, Photon.Compression.CompressedElementExt.GuessUpperBits, Photon.Compression.CompressedElementExt.OverwriteUpperBits, Photon.Compression.ElementCrusher.Read, Photon.Compression.ElementCrusher.Write, Photon.Compression.CompressedElementExt.ZeroLowerBits, Photon.Compression.CompressedElementExt.ZeroUpperBits.
void Photon.Compression.CompressedElement.Set(ElementCrusher crusher, uint cx, uint cy, uint cz)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
void Photon.Compression.CompressedElement.Set(ElementCrusher crusher, uint cUniform)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cUniform, Photon.Compression.ElementCrusher.UCrusher.
void Photon.Compression.CompressedElement.Set(ElementCrusher crusher, ulong cQuat)
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.QCrusher.
void Photon.Compression.CompressedElement.CopyTo(CompressedElement copyTarget)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Referenced by Photon.Compression.CompressedMatrix.CopyTo.
void Photon.Compression.CompressedElement.CopyFrom(CompressedElement copySource)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Referenced by Photon.Compression.CompressedMatrix.CopyFrom.
uint Photon.Compression.CompressedElement.GetUInt(int axis)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Element Photon.Compression.CompressedElement.Decompress()
References Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Decompress.
Referenced by Photon.Compression.CompressedElement.operator Element, Photon.Compression.CompressedElement.operator Quaternion, Photon.Compression.CompressedElement.operator Vector3.
void Photon.Compression.CompressedElement.Serialize(byte[] buffer, ref int bitposition, IncludedAxes ia, BitCullingLevel bcl=BitCullingLevel.NoCulling)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Write.
override string Photon.Compression.CompressedElement.ToString()
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedQuat.cvalue, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.ElementCrusher.uniformAxes.
override bool Photon.Compression.CompressedElement.Equals(object obj)
References Photon.Compression.CompressedElement.Equals.
Referenced by Photon.Compression.CompressedElement.Compare, Photon.Compression.CompressedMatrix.Equals, Photon.Compression.CompressedElement.Equals, Photon.Compression.CompressedElement.operator!=, Photon.Compression.CompressedElement.operator==.
bool Photon.Compression.CompressedElement.Equals(CompressedElement other)
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedQuat.cvalue, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
override int Photon.Compression.CompressedElement.GetHashCode()
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
Referenced by Photon.Compression.CompressedMatrix.GetHashCode.
static Photon.Compression.CompressedElement.operator ulong(CompressedElement ce)
References Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Write.
static Photon.Compression.CompressedElement.operator uint(CompressedElement ce)
References Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Write.
static Photon.Compression.CompressedElement.operator ushort(CompressedElement ce)
References Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Write.
static Photon.Compression.CompressedElement.operator byte(CompressedElement ce)
References Photon.Compression.ElementCrusher.Cached_TotalBits, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.Write.
static Photon.Compression.CompressedElement.operator ulong[](CompressedElement ce)
static Photon.Compression.CompressedElement.operator uint[](CompressedElement ce)
static Photon.Compression.CompressedElement.operator byte[](CompressedElement ce)
static Photon.Compression.CompressedElement.operator Element(CompressedElement ce)
References Photon.Compression.CompressedElement.Decompress.
static Photon.Compression.CompressedElement.operator Vector3(CompressedElement ce)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.Decompress, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
static Photon.Compression.CompressedElement.operator Quaternion(CompressedElement ce)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.Decompress, Photon.Compression.Element.quat, Photon.Compression.ElementCrusher.TRSType, Photon.Compression.Element.v.
static bool Photon.Compression.CompressedElement.Compare(CompressedElement a, CompressedElement b)
Basic compare of the X, Y, Z, and W values.
True if they all match.
References Photon.Compression.CompressedElement.Equals.
static int Photon.Compression.CompressedElement.HighestDifferentBit(uint a, uint b)
Get the bit count of the highest bit that is different between two compressed positions.
This is the min number of bits that must be sent.
static void Photon.Compression.CompressedElement.Extrapolate(ElementCrusher crusher, CompressedElement target, CompressedElement curr, CompressedElement prev, int divisor=2)
It may preferable to use the overload that takes and int divisor value than a float, to avoid all float math to possibly reduce jitter.
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set.
static CompressedElement Photon.Compression.CompressedElement.Extrapolate(ElementCrusher crusher, CompressedElement curr, CompressedElement prev, int divisor=2)
summary> It may preferable to use the overload that takes and int divisor value than a float, to avoid all float math to possibly reduce jitter.
Uses curr.crusher.
References Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static void Photon.Compression.CompressedElement.Extrapolate(CompressedElement target, CompressedElement curr, CompressedElement prev, int divisor=2)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set.
static CompressedElement Photon.Compression.CompressedElement.Extrapolate(CompressedElement curr, CompressedElement prev, int divisor=2)
References Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static void Photon.Compression.CompressedElement.Extrapolate(ElementCrusher crusher, CompressedElement target, CompressedElement curr, CompressedElement prev, float amount=.5f)
It may preferable to use the overload that takes and int divisor value than a float, to avoid all float math to possibly reduce jitter.
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set.
static CompressedElement Photon.Compression.CompressedElement.Extrapolate(ElementCrusher crusher, CompressedElement curr, CompressedElement prev, float amount=.5f)
References Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static void Photon.Compression.CompressedElement.Extrapolate(CompressedElement target, CompressedElement curr, CompressedElement prev, float amount=.5f)
It may preferable to use the overload that takes and int divisor value than a float, to avoid all float math to possibly reduce jitter.
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set.
static CompressedElement Photon.Compression.CompressedElement.Extrapolate(CompressedElement curr, CompressedElement prev, float amount=.5f)
References Photon.Compression.CompressedElement.CompressedElement, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static BitCullingLevel Photon.Compression.CompressedElement.GetGuessableBitCullLevel(CompressedElement a, CompressedElement b, BitCullingLevel maxCullLvl)
Test changes between two compressed Vector3 elements and returns the ideal BitCullingLevel for that change, with the assumption that it will be recreated using best guess (process where the upperbits are incremented and deincremented until the closest position to compare positon is returned.
NOT FULLY TESTED a b maxCullLvl
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static BitCullingLevel Photon.Compression.CompressedElement.GetGuessableBitCullLevel(CompressedElement oldComp, CompressedElement newComp, ElementCrusher ec, BitCullingLevel maxCullLvl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static BitCullingLevel Photon.Compression.CompressedElement.FindBestBitCullLevel(CompressedElement a, CompressedElement b, BitCullingLevel maxCulling)
Return the smallest bit culling level that will be able to communicate the changes between two compressed elements.
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.crusher, Photon.Compression.ElementCrusher.TRSType.
static BitCullingLevel Photon.Compression.CompressedElement.FindBestBitCullLevel(CompressedElement a, CompressedElement b, ElementCrusher ec, BitCullingLevel maxCulling)
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.ElementCrusher.TRSType.
static BitCullingLevel Photon.Compression.CompressedElement.FindBestBitCullLevel(CompressedElement a, CompressedElement b, FloatCrusher[] ec, BitCullingLevel maxCulling)
static bool Photon.Compression.CompressedElement.TestMatchingUpper(CompressedElement a, CompressedElement b, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
static bool Photon.Compression.CompressedElement.TestMatchingUpper(CompressedElement a, CompressedElement b, ElementCrusher ec, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static bool Photon.Compression.CompressedElement.TestMatchingUpper(CompressedElement a, CompressedElement b, FloatCrusher[] ec, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static bool Photon.Compression.CompressedElement.operator==(CompressedElement a, CompressedElement b)
References Photon.Compression.CompressedElement.Equals.
static bool Photon.Compression.CompressedElement.operator!=(CompressedElement a, CompressedElement b)
References Photon.Compression.CompressedElement.Equals.
static bool Photon.Compression.CompressedElement.TestMatchingUpper(uint a, uint b, int lowerbits)