Photon::Compression::ArraySerializeUnsafe
const string Photon.Compression.ArraySerializeUnsafe.bufferOverrunMsg
static unsafe void Photon.Compression.ArraySerializeUnsafe.WriteSigned(ulong *buffer, int value, ref int bitposition, int bits)
Writes value to this unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AppendSigned(ulong *buffer, int value, ref int bitposition, int bits)
Appends value to this unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is NOT preserved. Only use for sequential writes. Use Write() or Inject() for non-linear writes.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddSigned(this int value, ulong *uPtr, ref int bitposition, int bits)
Appends this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is NOT preserved in exchange for a faster write.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddSigned(this short value, ulong *uPtr, ref int bitposition, int bits)
Appends this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is NOT preserved in exchange for a faster write.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddSigned(this sbyte value, ulong *uPtr, ref int bitposition, int bits)
Appends this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is NOT preserved in exchange for a faster write.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectSigned(this int value, ulong *uPtr, ref int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectSigned(this short value, ulong *uPtr, ref int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectSigned(this sbyte value, ulong *uPtr, ref int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.PokeSigned(this int value, ulong *uPtr, int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Unlike Inject, this does not increment the bitposition and is for one-off injections. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.PokeSigned(this short value, ulong *uPtr, int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Unlike Inject, this does not increment the bitposition and is for one-off injections. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.PokeSigned(this sbyte value, ulong *uPtr, int bitposition, int bits)
Overwrites this value to the unsafe buffer.
Uses zigzag encoding to retain the sign value. Unlike Inject, this does not increment the bitposition and is for one-off injections. Existing data past this inject is preserved.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe int Photon.Compression.ArraySerializeUnsafe.ReadSigned(ulong *uPtr, ref int bitposition, int bits)
Returns signed value read from the buffer.
References Photon.Compression.ArraySerializeUnsafe.Read.
static unsafe int Photon.Compression.ArraySerializeUnsafe.PeekSigned(ulong *uPtr, int bitposition, int bits)
Returns signed value read from the buffer.
Same as Read, only the bitposition is not incremented.
References Photon.Compression.ArraySerializeUnsafe.Read.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Append(ulong *uPtr, ulong value, ref int bitposition, int bits)
Primary Append writer.
Faster method for writing to byte[] or uint[] buffers. Uses unsafe to treat them as ulong[]. Append does not preserve existing buffer data past the write point in exchange for a faster write. WARNING: There is no bounds checking on this. If you write too far, you will crash. uPtr Cast your byte* or uint* to ulong* value bitposition bits
Referenced by Photon.Compression.ArraySerializeUnsafe.Add, Photon.Compression.ArraySerializeUnsafe.AddSigned, Photon.Compression.ArraySerializeUnsafe.AddUnsigned, Photon.Compression.ArraySerializeUnsafe.AppendSigned.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Write(ulong *uPtr, ulong value, ref int bitposition, int bits)
Primary Unsafe writer.
Faster method for writing to byte[] or uint[] buffers. Uses unsafe to treat them as ulong[]. WARNING: There is no bounds checking on this. If you write too far, you will crash. uPtr Cast your byte* or uint* to ulong* value bitposition bits
Referenced by Photon.Compression.ArraySerializeUnsafe.Inject, Photon.Compression.ArraySerializeUnsafe.InjectSigned, Photon.Compression.ArraySerializeUnsafe.InjectUnsigned, Photon.Compression.ArraySerializeUnsafe.Poke, Photon.Compression.ArraySerializeUnsafe.PokeSigned, Photon.Compression.ArraySerializeUnsafe.PokeUnsigned, Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe, Photon.Compression.ArrayPackBitsExt.WritePackedBits, Photon.Compression.ArrayPackBytesExt.WritePackedBytes, Photon.Compression.ArraySerializeUnsafe.WriteSigned.
static unsafe ulong Photon.Compression.ArraySerializeUnsafe.Read(ulong *uPtr, ref int bitposition, int bits)
Primary Unsafe Read.
Fast read for byte[] and unit[] by treating them as ulong[]. WARNING: There is no bounds checking on this method! uPtr Cast your byte* or uint* to ulong* bitposition bits Returns the read value.
Referenced by Photon.Compression.ArraySerializeUnsafe.PeekSigned, Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe, Photon.Compression.ArrayPackBitsExt.ReadPackedBits, Photon.Compression.ArrayPackBytesExt.ReadPackedBytes, Photon.Compression.ArraySerializeUnsafe.ReadSigned.
static unsafe ulong Photon.Compression.ArraySerializeUnsafe.Read(ulong *uPtr, int bitposition, int bits)
Primary Unsafe Peek.
Fast read for byte[] and unit[] by treating them as ulong[]. Reads value at position without incrementing the bitposition. WARNING: There is no bounds checking on this method! uPtr Cast your byte* or uint* to ulong* bitposition bits Returns the read value.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Add(this ulong value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Add(this uint value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Add(this ushort value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Add(this byte value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddUnsigned(this long value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddUnsigned(this int value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddUnsigned(this short value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.AddUnsigned(this sbyte value, ulong *uPtr, int bitposition, int bits)
Append this value to the unsafe uPtr array.
Use for altering previous writes. Does not preserve existing data past the write. Use for sequential writes only. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Append.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Inject(this ulong value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Inject(this uint value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Inject(this ushort value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Inject(this byte value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this long value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this int value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this short value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this sbyte value, ulong *uPtr, ref int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Poke(this ulong value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Poke(this uint value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Poke(this ushort value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.Poke(this byte value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this long value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.InjectUnsigned(this int value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.PokeUnsigned(this short value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.PokeUnsigned(this sbyte value, ulong *uPtr, int bitposition, int bits)
Write this value to the unsafe uPtr array.
Use for altering previous writes. Preserves existing data past the write. Sign is ignored and value is cast to ulong. Same as Inject, only the bitposition is not a ref and is not incremented. WARNING: There is no bounds checking on this. If you write too far, you will crash.
References Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(ulong *sourcePtr, int sourcePos, ulong *targetPtr, ref int targetPos, int bits)
Primary ReadOutUnsafe method.
WARNING: No bounds checking. Use with caution. Cast array pointers to ulong*. sourcePtr sourcePos targetPtr targetPos bits
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this ulong[] source, int sourcePos, byte[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this ulong[] source, int sourcePos, uint[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this ulong[] source, int sourcePos, ulong[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this uint[] source, int sourcePos, byte[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this uint[] source, int sourcePos, uint[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this uint[] source, int sourcePos, ulong[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this byte[] source, int sourcePos, ulong[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this byte[] source, int sourcePos, uint[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.
static unsafe void Photon.Compression.ArraySerializeUnsafe.ReadOutUnsafe(this byte[] source, int sourcePos, byte[] target, ref int targetPos, int bits)
Read the contents of one bitpacked array to another using Unsafe.
This generally requires arrays to have a total byte count divisible by 8, as they will be treated as ulong[] in unsafe. source sourcePos Bitpos of the source array to start read from. target targetPos The target bitposition (that will be incremented with this write). bits Number of bits to copy. This should be the current bitpos of the source.
References Photon.Compression.ArraySerializeUnsafe.Read, Photon.Compression.ArraySerializeUnsafe.Write.