StarterAssets::StarterAssetsInputs
Vector2 StarterAssets.StarterAssetsInputs.move
Referenced by StarterAssets.StarterAssetsInputs.MoveInput.
Vector2 StarterAssets.StarterAssetsInputs.look
Referenced by StarterAssets.StarterAssetsInputs.LookInput.
bool StarterAssets.StarterAssetsInputs.jump
Referenced by StarterAssets.StarterAssetsInputs.JumpInput.
bool StarterAssets.StarterAssetsInputs.sprint
Referenced by StarterAssets.StarterAssetsInputs.SprintInput.
bool StarterAssets.StarterAssetsInputs.analogMovement
bool StarterAssets.StarterAssetsInputs.cursorLocked
bool StarterAssets.StarterAssetsInputs.cursorInputForLook
void StarterAssets.StarterAssetsInputs.MoveInput(Vector2 newMoveDirection)
References StarterAssets.StarterAssetsInputs.move.
Referenced by StarterAssets.UICanvasControllerInput.VirtualMoveInput.
void StarterAssets.StarterAssetsInputs.LookInput(Vector2 newLookDirection)
References StarterAssets.StarterAssetsInputs.look.
Referenced by StarterAssets.UICanvasControllerInput.VirtualLookInput.
void StarterAssets.StarterAssetsInputs.JumpInput(bool newJumpState)
References StarterAssets.StarterAssetsInputs.jump.
Referenced by StarterAssets.UICanvasControllerInput.VirtualJumpInput.
void StarterAssets.StarterAssetsInputs.SprintInput(bool newSprintState)
References StarterAssets.StarterAssetsInputs.sprint.
Referenced by StarterAssets.UICanvasControllerInput.VirtualSprintInput.
void StarterAssets.StarterAssetsInputs.OnApplicationFocus(bool hasFocus)
void StarterAssets.StarterAssetsInputs.SetCursorState(bool newState)