Photon::Pun::Demo::Cockpit::PlayerListView
PlayerDetailsController Photon.Pun.Demo.Cockpit.PlayerListView.PlayerDetailManager
Referenced by Photon.Pun.Demo.Cockpit.PlayerListView.SelectPlayer.
PlayerListCell Photon.Pun.Demo.Cockpit.PlayerListView.CellPrototype
Referenced by Photon.Pun.Demo.Cockpit.PlayerListView.OnEnable, Photon.Pun.Demo.Cockpit.PlayerListView.OnPlayerEnteredRoom.
Text Photon.Pun.Demo.Cockpit.PlayerListView.PlayerCountsText
Text Photon.Pun.Demo.Cockpit.PlayerListView.UpdateStatusText
Referenced by Photon.Pun.Demo.Cockpit.PlayerListView.OnEnable.
Dictionary<int, PlayerListCell> Photon.Pun.Demo.Cockpit.PlayerListView.playerCellList
void Photon.Pun.Demo.Cockpit.PlayerListView.Awake()
void Photon.Pun.Demo.Cockpit.PlayerListView.RefreshCount()
IEnumerator Photon.Pun.Demo.Cockpit.PlayerListView.UpdateUIPing()
override void Photon.Pun.Demo.Cockpit.PlayerListView.OnEnable()
References Photon.Pun.Demo.Cockpit.PlayerListView.CellPrototype, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Room.Players, Photon.Pun.Demo.Cockpit.PlayerListView.UpdateStatusText.
void Photon.Pun.Demo.Cockpit.PlayerListView.SelectPlayer(Player player)
References Photon.Pun.Demo.Cockpit.PlayerListView.PlayerDetailManager, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.
Referenced by Photon.Pun.Demo.Cockpit.PlayerListCell.OnClick.
override void Photon.Pun.Demo.Cockpit.PlayerListView.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.Demo.Cockpit.PlayerListCell.AddToList, Photon.Pun.Demo.Cockpit.PlayerListView.CellPrototype.
override void Photon.Pun.Demo.Cockpit.PlayerListView.OnMasterClientSwitched(Player newMasterClient)
Called after switching to a new MasterClient when the current one leaves.
This is not called when this client enters a room. The former MasterClient is still in the player list when this method get called.
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Room.Players.
override void Photon.Pun.Demo.Cockpit.PlayerListView.OnPlayerPropertiesUpdate(Player target, ExitGames.Client.Photon.Hashtable changedProps)
References Photon.Realtime.Player.ActorNumber.
override void Photon.Pun.Demo.Cockpit.PlayerListView.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.PlayerListOthers.
void Photon.Pun.Demo.Cockpit.PlayerListView.ResetList()
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.LeaveRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom.