Photon::Pun::Simple::ContactTrigger
bool Photon.Pun.Simple.ContactTrigger.preventRepeats
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact, Photon.Pun.Simple.ContactTrigger.OnDisable, Photon.Pun.Simple.ContactTrigger.OnEnable, Photon.Pun.Simple.ContactTrigger.OnPreSimulate, Photon.Pun.Simple.ContactTrigger.OnStateChange.
int [] Photon.Pun.Simple.ContactTrigger._ignoredSystems
List<IOnContactEvent> Photon.Pun.Simple.ContactTrigger.OnContactEventCallbacks
Referenced by Photon.Pun.Simple.ContactTrigger.Awake.
IContactTrigger Photon.Pun.Simple.ContactTrigger._proxy
Referenced by Photon.Pun.Simple.ContactTrigger.Awake.
bool Photon.Pun.Simple.ContactTrigger.PreventRepeats
List<IContactSystem> Photon.Pun.Simple.ContactTrigger.ContactSystems
IContactTrigger Photon.Pun.Simple.ContactTrigger.Proxy
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact.
byte Photon.Pun.Simple.ContactTrigger.Index
NetObject Photon.Pun.Simple.ContactTrigger.NetObj
ISyncContact Photon.Pun.Simple.ContactTrigger.SyncContact
IContactGroupsAssign Photon.Pun.Simple.ContactTrigger.ContactGroupsAssign
List<Type> Photon.Pun.Simple.ContactTrigger.ignoredSystems
Referenced by Photon.Pun.Simple.ContactTrigger.PollInterfaces.
NetObject Photon.Pun.Simple.ContactTrigger.netObj
Referenced by Photon.Pun.Simple.ContactTrigger.Awake, Photon.Pun.Simple.ContactTrigger.OnContact.
ISyncContact Photon.Pun.Simple.ContactTrigger.syncContact
Referenced by Photon.Pun.Simple.ContactTrigger.Awake, Photon.Pun.Simple.ContactTrigger.OnContact.
IContactGroupsAssign Photon.Pun.Simple.ContactTrigger.contactGroupsAssign
Referenced by Photon.Pun.Simple.ContactTrigger.Awake.
HashSet<IContactSystem> Photon.Pun.Simple.ContactTrigger.triggeringHitscans
Hashsets used to make sure things only trigger once per tick, so multiple colliders can't cause multiple retriggers.
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact, Photon.Pun.Simple.ContactTrigger.OnEnable, Photon.Pun.Simple.ContactTrigger.OnPreSimulate.
HashSet<IContactSystem> Photon.Pun.Simple.ContactTrigger.triggeringEnters
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact, Photon.Pun.Simple.ContactTrigger.OnEnable.
HashSet<IContactSystem> Photon.Pun.Simple.ContactTrigger.triggeringStays
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact, Photon.Pun.Simple.ContactTrigger.OnEnable, Photon.Pun.Simple.ContactTrigger.OnPreSimulate.
List<IContactSystem> Photon.Pun.Simple.ContactTrigger._contactSystems
ContactType Photon.Pun.Simple.ContactTrigger.usedContactTypes
List<IContactSystem> Photon.Pun.Simple.ContactTrigger.tempFindSystems
Referenced by Photon.Pun.Simple.ContactTrigger.PollInterfaces.
List<Type> Photon.Pun.Simple.ContactTrigger.contactSystemTypes
static Photon.Pun.Simple.ContactTrigger.ContactTrigger()
virtual void Photon.Pun.Simple.ContactTrigger.PollInterfaces()
References Photon.Pun.Simple.ContactTrigger.ignoredSystems, Photon.Pun.Simple.ContactTrigger.tempFindSystems.
Referenced by Photon.Pun.Simple.ContactTrigger.Awake.
virtual void Photon.Pun.Simple.ContactTrigger.Awake()
References Photon.Pun.Simple.ContactTrigger._proxy, Photon.Pun.Simple.ContactTrigger.contactGroupsAssign, Photon.Pun.Simple.ContactTrigger.netObj, Photon.Pun.Simple.ContactTrigger.OnContactEventCallbacks, Photon.Pun.Simple.ContactTrigger.PollInterfaces, Photon.Pun.Simple.ContactTrigger.syncContact, Photon.Pun.Simple.IOnContactEvent.TriggerOn.
void Photon.Pun.Simple.ContactTrigger.OnStateChange(ObjState newState, ObjState previousState, Transform attachmentTransform, Mount attachTo=null, bool isReady=true)
References Photon.Pun.Simple.ContactTrigger.preventRepeats.
virtual void Photon.Pun.Simple.ContactTrigger.OnContact(IContactTrigger otherCT, ContactType contactType)
References Photon.Pun.Simple.NetObject.AllObjsAreReady, Photon.Pun.Simple.ContactTrigger.ContactCallbacks, Photon.Pun.Simple.IContactTrigger.ContactSystems, Photon.Pun.Simple.ContactTrigger.netObj, Photon.Pun.Simple.IContactTrigger.NetObj, Photon.Pun.Simple.ContactTrigger.preventRepeats, Photon.Pun.Simple.ContactTrigger.Proxy, Photon.Pun.Simple.IContactTrigger.Proxy, Photon.Pun.Simple.ContactTrigger.syncContact, Photon.Pun.Simple.IContactTrigger.SyncContact, Photon.Pun.Simple.ISyncContact.SyncContactEvent, Photon.Pun.Simple.ContactTrigger.triggeringEnters, Photon.Pun.Simple.ContactTrigger.triggeringHitscans, Photon.Pun.Simple.ContactTrigger.triggeringStays.
virtual Consumption Photon.Pun.Simple.ContactTrigger.ContactCallbacks(ContactEvent contactEvent)
Referenced by Photon.Pun.Simple.ContactTrigger.OnContact.
void Photon.Pun.Simple.ContactTrigger.OnPreSimulate(int frameId, int subFrameId)
This callback only is registered if preventRepeats is true.
References Photon.Pun.Simple.ContactTrigger.preventRepeats, Photon.Pun.Simple.ContactTrigger.triggeringHitscans, Photon.Pun.Simple.ContactTrigger.triggeringStays.
virtual void Photon.Pun.Simple.ContactTrigger.OnEnable()
References Photon.Pun.Simple.ContactTrigger.preventRepeats, Photon.Pun.Simple.NetMasterCallbacks.RegisterCallbackInterfaces, Photon.Pun.Simple.ContactTrigger.triggeringEnters, Photon.Pun.Simple.ContactTrigger.triggeringHitscans, Photon.Pun.Simple.ContactTrigger.triggeringStays.
virtual void Photon.Pun.Simple.ContactTrigger.OnDisable()
References Photon.Pun.Simple.ContactTrigger.preventRepeats, Photon.Pun.Simple.NetMasterCallbacks.RegisterCallbackInterfaces.
virtual void Photon.Pun.Simple.ContactTrigger.Contact(Component otherCollider, ContactType contactType)
Converts Unity Collision/Trigger events into OnContact calls on both ContactTriggers involved.
References Photon.Pun.Simple.ContactTrigger.CheckIsNested, Photon.Pun.Simple.IContactTrigger.NetObj, Photon.Pun.Simple.IContactTrigger.OnContact.
bool Photon.Pun.Simple.ContactTrigger.CheckIsNested(IContactTrigger first, IContactTrigger second)
References Photon.Pun.Simple.IContactTrigger.NetObj.
Referenced by Photon.Pun.Simple.ContactTrigger.Contact.
void Photon.Pun.Simple.ContactTrigger.OnTriggerEnter2D(Collider2D other)
void Photon.Pun.Simple.ContactTrigger.OnTriggerEnter(Collider other)
void Photon.Pun.Simple.ContactTrigger.OnCollisionEnter2D(Collision2D collision)
void Photon.Pun.Simple.ContactTrigger.OnCollisionEnter(Collision collision)
void Photon.Pun.Simple.ContactTrigger.OnTriggerStay2D(Collider2D other)
void Photon.Pun.Simple.ContactTrigger.OnTriggerStay(Collider other)
void Photon.Pun.Simple.ContactTrigger.OnCollisionStay2D(Collision2D collision)
void Photon.Pun.Simple.ContactTrigger.OnCollisionStay(Collision collision)
void Photon.Pun.Simple.ContactTrigger.OnTriggerExit2D(Collider2D other)
void Photon.Pun.Simple.ContactTrigger.OnTriggerExit(Collider other)
void Photon.Pun.Simple.ContactTrigger.OnCollisionExit2D(Collision2D collision)
void Photon.Pun.Simple.ContactTrigger.OnCollisionExit(Collision collision)
bool Photon.Pun.Simple.ContactTrigger.IsCompatibleSystem(IContactSystem system, IContactTrigger ct)
void Photon.Pun.Simple.ContactTrigger.GetAllowedTypesFromHashes()
static void Photon.Pun.Simple.ContactTrigger.FindDerivedTypesFromAssembly()
Find all IContactSystem derived interfaces that are not abstract.