Photon::Pun::UtilityScripts::PhotonTeamsManager
List<PhotonTeam> Photon.Pun.UtilityScripts.PhotonTeamsManager.teamsList
Dictionary<byte, PhotonTeam> Photon.Pun.UtilityScripts.PhotonTeamsManager.teamsByCode
Dictionary<string, PhotonTeam> Photon.Pun.UtilityScripts.PhotonTeamsManager.teamsByName
Dictionary<byte, HashSet<Player> > Photon.Pun.UtilityScripts.PhotonTeamsManager.playersPerTeam
The main list of teams with their player-lists. Automatically kept up to date.
const string Photon.Pun.UtilityScripts.PhotonTeamsManager.TeamPlayerProp
Defines the player custom property name to use for team affinity of "this" player.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamExtensions.GetPhotonTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.JoinTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.LeaveCurrentTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.SwitchTeam.
Action<Player, PhotonTeam> Photon.Pun.UtilityScripts.PhotonTeamsManager.PlayerJoinedTeam
Action<Player, PhotonTeam> Photon.Pun.UtilityScripts.PhotonTeamsManager.PlayerLeftTeam
PhotonTeamsManager Photon.Pun.UtilityScripts.PhotonTeamsManager.instance
PhotonTeamsManager Photon.Pun.UtilityScripts.PhotonTeamsManager.Instance
Referenced by Photon.Pun.UtilityScripts.PhotonTeamExtensions.GetPhotonTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.JoinTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.SwitchTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.TryGetTeamMates.
void Photon.Pun.UtilityScripts.PhotonTeamsManager.Awake()
void Photon.Pun.UtilityScripts.PhotonTeamsManager.OnEnable()
void Photon.Pun.UtilityScripts.PhotonTeamsManager.OnDisable()
void Photon.Pun.UtilityScripts.PhotonTeamsManager.Init()
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
void IInRoomCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnPlayerPropertiesUpdate(Player targetPlayer, Hashtable changedProps)
Called when custom player-properties are changed.
Player and the changed properties are passed as object[]. Changing properties must be done by Player.SetCustomProperties, which causes this callback locally, too. targetPlayer Contains Player that changed. changedProps Contains the properties that changed.
void IInRoomCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
void IInRoomCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
void Photon.Pun.UtilityScripts.PhotonTeamsManager.UpdateTeams()
void Photon.Pun.UtilityScripts.PhotonTeamsManager.ClearTeams()
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnFriendListUpdate(List< FriendInfo > friendList)
Called when the server sent the response to a FindFriends request.
After calling OpFindFriends, the Master Server will cache the friend list and send updates to the friend list. The friends includes the name, userId, online state and the room (if any) for each requested user/friend. Use the friendList to update your UI and store it, if the UI should highlight changes.
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnCreatedRoom()
Called when this client created a room and entered it.
OnJoinedRoom() will be called as well. This callback is only called on the client which created a room (see OpCreateRoom). As any client might close (or drop connection) anytime, there is a chance that the creator of a room does not execute OnCreatedRoom. If you need specific room properties or a "start signal", implement OnMasterClientSwitched() and make each new MasterClient check the room's state.
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
Creating a room may fail for various reasons. Most often, the room already exists (roomname in use) or the RoomOptions clash and it's impossible to create the room. When creating a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
Joining a room may fail for various reasons. Most often, the room is full or does not exist anymore (due to someone else being faster or closing the room). When joining a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void IMatchmakingCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnJoinRandomFailed(short returnCode, string message)
Called when a previous OpJoinRandom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). This operation is only ever sent to the Master Server. Once a room is found by the Master Server, the client will head off to the designated Game Server and use the operation Join on the Game Server. When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms. returnCode Operation ReturnCode from the server. message Debug message for the error.
void IInRoomCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnRoomPropertiesUpdate(Hashtable propertiesThatChanged)
Called when a room's custom properties changed.
The propertiesThatChanged contains all that was set via Room.SetCustomProperties. Since v1.25 this method has one parameter: Hashtable propertiesThatChanged. Changing properties must be done by Room.SetCustomProperties, which causes this callback locally, too. propertiesThatChanged
void IInRoomCallbacks. Photon.Pun.UtilityScripts.PhotonTeamsManager.OnMasterClientSwitched(Player newMasterClient)
Called after switching to a new MasterClient when the current one leaves.
This is not called when this client enters a room. The former MasterClient is still in the player list when this method get called.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamByCode(byte code, out PhotonTeam team)
Find a PhotonTeam using a team code.
code The team code. team The team to be assigned if found. If successful or not.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamExtensions.GetPhotonTeam, Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount, Photon.Pun.UtilityScripts.PhotonTeamExtensions.JoinTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.SwitchTeam.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamByName(string teamName, out PhotonTeam team)
Find a PhotonTeam using a team name.
teamName The team name. team The team to be assigned if found. If successful or not.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount, Photon.Pun.UtilityScripts.PhotonTeamExtensions.JoinTeam, Photon.Pun.UtilityScripts.PhotonTeamExtensions.SwitchTeam, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers.
PhotonTeam[] Photon.Pun.UtilityScripts.PhotonTeamsManager.GetAvailableTeams()
Gets all teams available.
Returns all teams available.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamsManagerEditor.OnInspectorGUI.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers(byte code, out Player[] members)
Gets all players joined to a team using a team code.
code The code of the team. members The array of players to be filled. If successful or not.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamsManagerEditor.OnInspectorGUI, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers(string teamName, out Player[] members)
Gets all players joined to a team using a team name.
teamName The name of the team. members The array of players to be filled. If successful or not.
References Photon.Pun.UtilityScripts.PhotonTeam.Code, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamByName, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers(PhotonTeam team, out Player[] members)
Gets all players joined to a team.
team The team which will be used to find players. members The array of players to be filled. If successful or not.
References Photon.Pun.UtilityScripts.PhotonTeam.Code, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMembers.
bool Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamMatesOfPlayer(Player player, out Player[] teamMates)
Gets all team mates of a player.
player The player whose team mates will be searched. teamMates The array of players to be filled. If successful or not.
References Photon.Pun.UtilityScripts.PhotonTeam.Code.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamExtensions.TryGetTeamMates.
int Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount(byte code)
Gets the number of players in a team by team code.
code Unique code of the team Number of players joined to the team.
References Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamByCode.
Referenced by Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount.
int Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount(string name)
Gets the number of players in a team by team name.
name Unique name of the team Number of players joined to the team.
References Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount, Photon.Pun.UtilityScripts.PhotonTeamsManager.TryGetTeamByName.
int Photon.Pun.UtilityScripts.PhotonTeamsManager.GetTeamMembersCount(PhotonTeam team)
Gets the number of players in a team.
team The team you want to know the size of Number of players joined to the team.
References Photon.Pun.UtilityScripts.PhotonTeam.Code.