Photon::Pun::Simple::SyncObject
int Photon.Pun.Simple.SyncObject< TFrame >._applyOrder
bool Photon.Pun.Simple.SyncObject< TFrame >._alwaysReady
bool Photon.Pun.Simple.SyncObject< TFrame >.serializeThis
System.Action<SyncObject, ReadyStateEnum> Photon.Pun.Simple.SyncObject< TFrame >.onReadyCallbacks
TFrame [] Photon.Pun.Simple.SyncObject< TFrame >.frames
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame, Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged, Photon.Pun.Simple.SyncObject< TFrame >.OnAwake, Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot, Photon.Pun.Simple.SyncObject< TFrame >.PopulateFrames.
virtual int Photon.Pun.Simple.SyncObject< TFrame >.ApplyOrder
bool Photon.Pun.Simple.SyncObject< TFrame >.UseDeltas
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.AlwaysReady
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.IncludeInSerialization
bool Photon.Pun.Simple.SyncObject< TFrame >.SkipWhenEmpty
int Photon.Pun.Simple.SyncObject< TFrame >.SyncObjIndex
Referenced by Photon.Pun.Simple.NetObject.OnSyncObjReadyChange.
ReadyStateEnum Photon.Pun.Simple.SyncObject< TFrame >.ReadyState
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged, Photon.Pun.Simple.SyncObject< TFrame >.OnPostDisable, Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.AllowInterpolation
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnInterpolate.
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.AllowReconstructionOfEmpty
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.AllowReconstructionOfPartial
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
int Photon.Pun.Simple.SyncObject< TFrame >.keyframeRate
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.IsKeyframe, Photon.Pun.Simple.SyncObject< TFrame >.OnAwake.
bool Photon.Pun.Simple.SyncObject< TFrame >.useDeltas
int Photon.Pun.Simple.SyncObject< TFrame >.syncObjIndex
ReadyStateEnum Photon.Pun.Simple.SyncObject< TFrame >._readyState
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged, Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
TFrame Photon.Pun.Simple.SyncObject< TFrame >.prevFrame
Runtime vars.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame, Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
TFrame Photon.Pun.Simple.SyncObject< TFrame >.snapFrame
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructEmptyFrame, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructIncompleteFrame.
TFrame Photon.Pun.Simple.SyncObject< TFrame >.targFrame
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructEmptyFrame, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructIncompleteFrame.
TFrame Photon.Pun.Simple.SyncObject< TFrame >.offtickFrame
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnAwake.
bool Photon.Pun.Simple.SyncObject< TFrame >.hadInitialSnapshot
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged, Photon.Pun.Simple.SyncObject< TFrame >.OnPostDisable.
const string Photon.Pun.Simple.SyncObject< TFrame >.ALWAYS_READY_TOOLTIP
const string Photon.Pun.Simple.SyncObject< TFrame >.INCLUDE_SERIALIZATION_TOOLTIP
bool Photon.Pun.Simple.SyncObject< TFrame >.IsKeyframe(int frameId)
Checks if the supplied frame is a keyframe.
frameId
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncObject< TFrame >.keyframeRate.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ResetBuffers()
override void Photon.Pun.Simple.SyncObject< TFrame >.OnPostEnable()
override void Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged(bool isMine, bool controllerChanged)
Updates authority values on authority changes.
controllerChanged
References Photon.Pun.Simple.SyncObject< TFrame >._readyState, Photon.Pun.Simple.SyncObject< TFrame >.ReadyState.
override void Photon.Pun.Simple.SyncObject< TFrame >.OnPostDisable()
References Photon.Pun.Simple.SyncObject< TFrame >.ReadyState.
override void Photon.Pun.Simple.SyncObject< TFrame >.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
override void Photon.Pun.Simple.SyncObject< TFrame >.OnAwake()
When overriding, but sure to keep base.Awake().
Also, frames are created and given indexes, but any other Initialization will still need to be explicitly called in the derived Awake().
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncObject< TFrame >.frames, Photon.Pun.Simple.SyncObject< TFrame >.keyframeRate, Photon.Pun.Simple.TickEngineSettings.MaxKeyframes, Photon.Pun.Simple.SyncObject< TFrame >.offtickFrame, Photon.Pun.Simple.SyncObject< TFrame >.PopulateFrames, Photon.Utilities.SettingsScriptableObject< T >.single.
override void Photon.Pun.Simple.SyncObject< TFrame >.OnPostDisable()
References Photon.Pun.Simple.SyncObject< TFrame >.hadInitialSnapshot.
override void Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged(bool isMine, bool controllerChanged)
Updates authority values on authority changes.
controllerChanged
References Photon.Pun.PhotonView.ControllerActorNr, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncObject< TFrame >.frames, Photon.Pun.Simple.SyncObject< TFrame >.hadInitialSnapshot, Photon.Pun.Simple.NetComponent.netObj, Photon.Pun.Simple.NetObject.originHistory, Photon.Pun.Simple.NetComponent.photonView.
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot(int prevFrameId, int snapFrameId, int targFrameId, bool prevIsValid, bool snapIsValid, bool targIsValid)
Called every simulation tick, right after the frameId has been incremented by NetMaster.
Base class advances/increments all of the frame references. targFrameId initialize Base will return false if snapshot is not ready.
References Photon.Pun.Simple.SyncObject< TFrame >._readyState, Photon.Pun.Simple.SyncObject< TFrame >.AllowReconstructionOfEmpty, Photon.Pun.Simple.SyncObject< TFrame >.AllowReconstructionOfPartial, Photon.Pun.Simple.SyncObject< TFrame >.ApplySnapshot, Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncObject< TFrame >.frames, Photon.Pun.Simple.TickEngineSettings.halfFrameCount, Photon.Pun.Simple.SyncObject< TFrame >.InitialCompleteSnapshot, Photon.Pun.Simple.SyncObject< TFrame >.prevFrame, Photon.Pun.Simple.SyncObject< TFrame >.ReadyState, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructEmptyFrame, Photon.Pun.Simple.SyncObject< TFrame >.ReconstructIncompleteFrame, Photon.Pun.Simple.SyncObject< TFrame >.snapFrame, Photon.Pun.Simple.SyncObject< TFrame >.targFrame.
virtual bool Photon.Pun.Simple.SyncObject< TFrame >.OnInterpolate(int snapFrameId, int targFrameId, float t)
Interpolate between SnapFrame and TargFrame.
t Base will return false if snapshot is not ready. Set to true if interpolation can be done.
References Photon.Pun.Simple.SyncObject< TFrame >.AllowInterpolation, Photon.Pun.Simple.NetComponent.IsMine.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.OnEnable()
This is here to ensure the enable checkbox visible for the Component.
int Photon.Pun.Simple.SyncObject< TFrame >.ConvertSecsToTicks(float seconds)
References Photon.Pun.Simple.TickEngineSettings.sendEveryXTick.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.PopulateFrames()
Override this with frame initialization code.
The default base just creates the frame instances and assigns them index values.
References Photon.Pun.Simple.SyncObject< TFrame >.frames.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnAwake.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.InitialCompleteSnapshot(TFrame frame)
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ApplySnapshot(TFrame snapframe, TFrame targframe, bool snapIsValid, bool targIsValid)
TODO: Make this abstract and use everywhere rather than OnSnapshot?
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ReconstructEmptyFrame()
Handling if a frame arrived, but the frame was flagged as FrameContents.Empty
References Photon.Pun.Simple.SyncObject< TFrame >.snapFrame, Photon.Pun.Simple.SyncObject< TFrame >.targFrame.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ReconstructIncompleteFrame()
Handling if a frame arrived, but the frame was flagged as hasConent = true and isComplete = false
References Photon.Pun.Simple.SyncObject< TFrame >.snapFrame, Photon.Pun.Simple.SyncObject< TFrame >.targFrame.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame(TFrame prevFrame, TFrame snapframe, TFrame targframe)
References Photon.Pun.Simple.NetComponent.ControllerActorNr, Photon.Pun.Simple.SyncObject< TFrame >.ExtrapolateFrame, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.SyncObject< TFrame >.frames, Photon.Pun.Simple.NetObject.frameValidMask, Photon.Pun.Simple.SyncObject< TFrame >.InterpolateFrame, Photon.Pun.Simple.NetComponent.netObj, Photon.Pun.Simple.Internal.TickManager.perConnOffsets, Photon.Pun.Simple.SyncObject< TFrame >.prevFrame.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.OnSnapshot.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.InterpolateFrame(TFrame targframe, TFrame startframe, TFrame endframe, float t)
Interpolate used to construct a new from from two existing frames.
Return true if this should flag that new frame now as having content.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame.
virtual void Photon.Pun.Simple.SyncObject< TFrame >.ExtrapolateFrame(TFrame prevframe, TFrame snapframe, TFrame targframe)
Interpolate a new TargFrame from previous frames.
Return true if this should flag that new frame now as having content.
Referenced by Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame.