Photon::Compression::Internal::SyncVarBaseAttribute
SyncAs Photon.Compression.Internal.SyncVarBaseAttribute.syncAs
Indicates how the Pack syncvar should be treated.
'State' maintains the value until changed. 'Trigger' resets the value to new() after capture/send.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize, Photon.Compression.Internal.SyncVarBaseAttribute.IsForced, Photon.Compression.Internal.SyncVarBaseAttribute.IsForced< T >, Photon.Compression.Internal.SyncVarBaseAttribute.IsForcedClass< T >.
KeyRate Photon.Compression.Internal.SyncVarBaseAttribute.keyRate
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize, Photon.Compression.Internal.SyncVarBaseAttribute.IsForced, Photon.Compression.Internal.SyncVarBaseAttribute.IsForced< T >, Photon.Compression.Internal.SyncVarBaseAttribute.IsForcedClass< T >, Photon.Compression.Internal.SyncVarBaseAttribute.IsKeyframe, Photon.Compression.SyncHalfFloatAttribute.SyncHalfFloatAttribute, Photon.Compression.SyncRangedIntAttribute.SyncRangedIntAttribute, Photon.Compression.SyncVarAttribute.SyncVarAttribute.
string Photon.Compression.Internal.SyncVarBaseAttribute.applyCallback
By default the callback is called After the value is changed.
This behavior can be changed by setting the CallbackSetValue.
string Photon.Compression.Internal.SyncVarBaseAttribute.snapshotCallback
Called every net tick before SyncObjects.OnSnapshot and before PackObjs.applyCallback is run.
Use this if you intend to handle your own interpolation/tween operations. Snap value is not be applied to the syncvar yet.
SetValueTiming Photon.Compression.Internal.SyncVarBaseAttribute.setValueTiming
Will automatically set the value where there is a callback defined.
Disable if you would like to set the local value manually in your callback.
bool Photon.Compression.Internal.SyncVarBaseAttribute.interpolate
Types that have interpolation methods defined for them, will automatically interpolate/Lerp/Tween to smooth movement in Update() between ticks.
int Photon.Compression.Internal.SyncVarBaseAttribute.bitCount
Referenced by Photon.Compression.SyncRangedIntAttribute.GetMaxBits, Photon.Compression.Internal.SyncVarBaseAttribute.Initialize, Photon.Compression.SyncVarAttribute.Pack, Photon.Compression.SyncListAttribute.Pack, Photon.Compression.SyncRangedIntAttribute.SyncRangedIntAttribute, Photon.Compression.SyncVarAttribute.Unpack, Photon.Compression.SyncListAttribute.Unpack.
virtual void Photon.Compression.Internal.SyncVarBaseAttribute.Initialize(Type primitiveType)
References Photon.Compression.Internal.SyncVarBaseAttribute.bitCount, Photon.Compression.Internal.SyncVarBaseAttribute.GetDefaultBitCount.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
virtual int Photon.Compression.Internal.SyncVarBaseAttribute.GetDefaultBitCount(Type fieldType)
References Photon.Compression.UInt16, Photon.Compression.UInt32, Photon.Compression.UInt64.
Referenced by Photon.Compression.Internal.SyncVarBaseAttribute.Initialize.
virtual int Photon.Compression.Internal.SyncVarBaseAttribute.GetMaxBits(Type fieldType)
Maximum possible bits that can be used during bitpacking.
These are used to determine the byte[] size for any PackObjects. Override this if the PackableAttribute will always use less than these values. Doing so will result in some memory savings. fieldType
References Photon.Compression.UInt16, Photon.Compression.UInt32, Photon.Compression.UInt64.
bool Photon.Compression.Internal.SyncVarBaseAttribute.IsKeyframe(int frameId)
References Photon.Compression.Internal.SyncVarBaseAttribute.keyRate.
Referenced by Photon.Compression.SyncListAttribute.Pack, Photon.Compression.SyncListAttribute.Unpack.
bool Photon.Compression.Internal.SyncVarBaseAttribute.IsForced(int frameId, SerializationFlags writeFlags)
References Photon.Compression.Internal.SyncVarBaseAttribute.keyRate, Photon.Compression.Internal.SyncVarBaseAttribute.syncAs.
Referenced by Photon.Compression.SyncVarAttribute.Pack, Photon.Compression.SyncRangedIntAttribute.Pack, Photon.Compression.Internal.SyncRangedAttribute.Pack, Photon.Compression.SyncHalfFloatAttribute.Pack.
bool Photon.Compression.Internal.SyncVarBaseAttribute.IsForcedClass< T >(int frameId, T value, T prevValue, SerializationFlags writeFlags)
References Photon.Compression.Internal.SyncVarBaseAttribute.keyRate, Photon.Compression.Internal.SyncVarBaseAttribute.syncAs.
bool Photon.Compression.Internal.SyncVarBaseAttribute.IsForced< T >(int frameId, T value, T prevValue, SerializationFlags writeFlags)
References Photon.Compression.Internal.SyncVarBaseAttribute.keyRate, Photon.Compression.Internal.SyncVarBaseAttribute.syncAs.