Photon::Chat::Demo::ChatGui
string [] Photon.Chat.Demo.ChatGui.ChannelsToJoinOnConnect
string [] Photon.Chat.Demo.ChatGui.FriendsList
int Photon.Chat.Demo.ChatGui.HistoryLengthToFetch
ChatClient Photon.Chat.Demo.ChatGui.chatClient
GameObject Photon.Chat.Demo.ChatGui.missingAppIdErrorPanel
GameObject Photon.Chat.Demo.ChatGui.ConnectingLabel
RectTransform Photon.Chat.Demo.ChatGui.ChatPanel
GameObject Photon.Chat.Demo.ChatGui.UserIdFormPanel
InputField Photon.Chat.Demo.ChatGui.InputFieldChat
Text Photon.Chat.Demo.ChatGui.CurrentChannelText
Toggle Photon.Chat.Demo.ChatGui.ChannelToggleToInstantiate
GameObject Photon.Chat.Demo.ChatGui.FriendListUiItemtoInstantiate
bool Photon.Chat.Demo.ChatGui.ShowState
GameObject Photon.Chat.Demo.ChatGui.Title
Text Photon.Chat.Demo.ChatGui.StateText
Text Photon.Chat.Demo.ChatGui.UserIdText
int Photon.Chat.Demo.ChatGui.TestLength
string Photon.Chat.Demo.ChatGui.UserName
Referenced by Photon.Chat.Demo.ChatGui.Connect, Photon.Chat.Demo.ChatGui.OnConnected, Photon.Chat.Demo.ChatGui.Start, Photon.Chat.Demo.NamePickGui.StartChat.
string Photon.Chat.Demo.ChatGui.selectedChannelName
readonly Dictionary<string, Toggle> Photon.Chat.Demo.ChatGui.channelToggles
readonly Dictionary<string,FriendItem> Photon.Chat.Demo.ChatGui.friendListItemLUT
byte [] Photon.Chat.Demo.ChatGui.testBytes
ChatAppSettings Photon.Chat.Demo.ChatGui.chatAppSettings
string Photon.Chat.Demo.ChatGui.HelpText
void Photon.Chat.Demo.ChatGui.Start()
References Photon.Chat.ChatAppSettings.AppIdChat, Photon.Chat.Demo.ChatGui.UserName.
void Photon.Chat.Demo.ChatGui.Connect()
References Photon.Chat.ChatClient.AuthValues, Photon.Chat.ChatClient.ConnectUsingSettings, Photon.Chat.ChatClient.UseBackgroundWorkerForSending, Photon.Chat.Demo.ChatGui.UserName.
Referenced by Photon.Chat.Demo.NamePickGui.StartChat.
void Photon.Chat.Demo.ChatGui.OnDestroy()
To avoid that the Editor becomes unresponsive, disconnect all Photon connections in OnDestroy.
References Photon.Chat.ChatClient.Disconnect.
void Photon.Chat.Demo.ChatGui.OnApplicationQuit()
To avoid that the Editor becomes unresponsive, disconnect all Photon connections in OnApplicationQuit.
References Photon.Chat.ChatClient.Disconnect.
void Photon.Chat.Demo.ChatGui.Update()
References Photon.Chat.ChatClient.Service.
void Photon.Chat.Demo.ChatGui.OnEnterSend()
void Photon.Chat.Demo.ChatGui.OnClickSend()
void Photon.Chat.Demo.ChatGui.PostHelpToCurrentChannel()
void Photon.Chat.Demo.ChatGui.DebugReturn(ExitGames.Client.Photon.DebugLevel level, string message)
void Photon.Chat.Demo.ChatGui.OnConnected()
Client is connected now.
Clients have to be connected before they can send their state, subscribe to channels and send any messages.
References Photon.Chat.ChatClient.AddFriends, Photon.Chat.ChatUserStatus.Online, Photon.Chat.ChatClient.Subscribe, Photon.Chat.Demo.ChatGui.UserName.
void Photon.Chat.Demo.ChatGui.OnDisconnected()
Disconnection happened.
void Photon.Chat.Demo.ChatGui.OnChatStateChange(ChatState state)
The ChatClient's state changed.
Usually, OnConnected and OnDisconnected are the callbacks to react to. state The new state.
void Photon.Chat.Demo.ChatGui.OnSubscribed(string[] channels, bool[] results)
Result of Subscribe operation.
Returns subscription result for every requested channel name. If multiple channels sent in Subscribe operation, OnSubscribed may be called several times, each call with part of sent array or with single channel in "channels" parameter. Calls order and order of channels in "channels" parameter may differ from order of channels in "channels" parameter of Subscribe operation. channels Array of channel names. results Per channel result if subscribed.
References Photon.Chat.ChatClient.PublishMessage, Photon.Chat.Demo.ChatGui.ShowChannel.
void Photon.Chat.Demo.ChatGui.OnSubscribed(string channel, string[] users, Dictionary< object, object > properties)
void Photon.Chat.Demo.ChatGui.OnUnsubscribed(string[] channels)
Result of Unsubscribe operation.
Returns for channel name if the channel is now unsubscribed. If multiple channels sent in Unsubscribe operation, OnUnsubscribed may be called several times, each call with part of sent array or with single channel in "channels" parameter. Calls order and order of channels in "channels" parameter may differ from order of channels in "channels" parameter of Unsubscribe operation. channels Array of channel names that are no longer subscribed.
References Photon.Chat.Demo.ChatGui.ShowChannel.
void Photon.Chat.Demo.ChatGui.OnGetMessages(string channelName, string[] senders, object[] messages)
Notifies app that client got new messages from server Number of senders is equal to number of messages in 'messages'.
Sender with number '0' corresponds to message with number '0', sender with number '1' corresponds to message with number '1' and so on channelName channel from where messages came senders list of users who sent messages messages list of messages it self
References Photon.Chat.Demo.ChatGui.ShowChannel.
void Photon.Chat.Demo.ChatGui.OnPrivateMessage(string sender, object message, string channelName)
Notifies client about private message
sender user who sent this message message message it self channelName channelName for private messages (messages you sent yourself get added to a channel per target username)
References Photon.Chat.Demo.ChatGui.ShowChannel.
void Photon.Chat.Demo.ChatGui.OnStatusUpdate(string user, int status, bool gotMessage, object message)
New status of another user (you get updates for users set in your friends list).
user Name of the user. status New status of that user. gotMessage True if the status contains a message you should cache locally. False: This status update does not include a message (keep any you have). message Message that user set.
References Photon.Chat.Demo.FriendItem.OnFriendStatusUpdate.
void Photon.Chat.Demo.ChatGui.OnUserSubscribed(string channel, string user)
A user has subscribed to a public chat channel
channel Name of the chat channel user UserId of the user who subscribed
void Photon.Chat.Demo.ChatGui.OnUserUnsubscribed(string channel, string user)
A user has unsubscribed from a public chat channel
channel Name of the chat channel user UserId of the user who unsubscribed
void Photon.Chat.Demo.ChatGui.OnChannelPropertiesChanged(string channel, string userId, Dictionary< object, object > properties)
References Photon.Realtime.Extensions.ToStringFull.
void Photon.Chat.Demo.ChatGui.OnUserPropertiesChanged(string channel, string targetUserId, string senderUserId, Dictionary< object, object > properties)
References Photon.Realtime.Extensions.ToStringFull.
void Photon.Chat.Demo.ChatGui.OnErrorInfo(string channel, string error, object data)
void Photon.Chat.Demo.ChatGui.AddMessageToSelectedChannel(string msg)
References Photon.Chat.ChatChannel.Add, Photon.Chat.ChatClient.TryGetChannel.
void Photon.Chat.Demo.ChatGui.ShowChannel(string channelName)
References Photon.Chat.ChatChannel.ToStringMessages, Photon.Chat.ChatClient.TryGetChannel.
Referenced by Photon.Chat.Demo.ChatGui.OnGetMessages, Photon.Chat.Demo.ChannelSelector.OnPointerClick, Photon.Chat.Demo.ChatGui.OnPrivateMessage, Photon.Chat.Demo.ChatGui.OnSubscribed, Photon.Chat.Demo.ChatGui.OnUnsubscribed.
void Photon.Chat.Demo.ChatGui.OpenDashboard()
void Photon.Chat.Demo.ChatGui.SendChatMessage(string inputLine)
void Photon.Chat.Demo.ChatGui.InstantiateChannelButton(string channelName)
void Photon.Chat.Demo.ChatGui.InstantiateFriendButton(string friendId)