Photon::Pun::Simple::Internal::NetMsgCallbacks
Dictionary<int, CallbackLists> Photon.Pun.Simple.Internal.NetMsgCallbacks.callbacks
const byte Photon.Pun.Simple.Internal.NetMsgCallbacks.DEF_MSG_ID
Referenced by Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback.
delegate void Photon.Pun.Simple.Internal.NetMsgCallbacks.ByteBufferCallback(object conn, int connId, byte[] buffer)
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterOnEventListener()
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.OnEvent(EventData photonEvent)
Capture incoming Photon messages here.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback(byte msgid, ByteBufferCallback callback, bool asServer)
Referenced by Photon.Pun.Simple.NetMaster.EnsureExistsInScene, Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback.
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback(ByteBufferCallback callback)
References Photon.Pun.Simple.Internal.NetMsgCallbacks.DEF_MSG_ID, Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback.
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.RegisterCallback(byte msgid, ByteBufferCallback callback)
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback(byte msgid, ByteBufferCallback callback, bool asServer)
Referenced by Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback.
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback(ByteBufferCallback callback)
References Photon.Pun.Simple.Internal.NetMsgCallbacks.DEF_MSG_ID, Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback.
static void Photon.Pun.Simple.Internal.NetMsgCallbacks.UnregisterCallback(byte msgid, ByteBufferCallback callback)