Photon::Pun::Simple::SyncState
override int Photon.Pun.Simple.SyncState.ApplyOrder
Mount Photon.Pun.Simple.SyncState.CurrentMount
Referenced by Photon.Pun.Simple.MountSwitcher.OnPreSimulate.
bool Photon.Pun.Simple.SyncState.IsThrowable
bool Photon.Pun.Simple.SyncState.IsDroppable
Rigidbody Photon.Pun.Simple.SyncState.Rb
Rigidbody2D Photon.Pun.Simple.SyncState.Rb2d
override bool Photon.Pun.Simple.SyncState.AllowReconstructionOfEmpty
ObjState Photon.Pun.Simple.SyncState.initialState
Referenced by Photon.Pun.Simple.SyncState.OnJoinedRoom, Photon.Pun.Simple.SyncState.OnStart.
ObjState Photon.Pun.Simple.SyncState.respawnState
Referenced by Photon.Pun.Simple.SyncState.OnStart.
ObjState Photon.Pun.Simple.SyncState.readyState
Referenced by Photon.Pun.Simple.SyncState.OnNetObjReadyChange.
ObjState Photon.Pun.Simple.SyncState.unreadyState
Referenced by Photon.Pun.Simple.SyncState.OnNetObjReadyChange.
MountMaskSelector Photon.Pun.Simple.SyncState.mountableTo
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.ContactReactorBase< T >.OnAwakeInitialize, Photon.Pun.Simple.ContactReactorBase< T >.OnContactEvent, Photon.Pun.Simple.SyncState.OnStart.
bool Photon.Pun.Simple.SyncState.autoReset
Referenced by Photon.Pun.Simple.SyncState.ChangeState.
bool Photon.Pun.Simple.SyncState.autoOwnerChange
Referenced by Photon.Pun.Simple.SyncState.ChangeState.
bool Photon.Pun.Simple.SyncState.mountReliable
Referenced by Photon.Pun.Simple.SyncState.OnNetSerialize.
List<IOnStateChange> Photon.Pun.Simple.SyncState.onStateChangeCallbacks
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.OnAwake.
List<IFlagTeleport> Photon.Pun.Simple.SyncState.flagTeleportCallbacks
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.OnAwake.
Frame Photon.Pun.Simple.SyncState.currentState
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.HardMount, Photon.Pun.Simple.SyncState.OnCaptureCurrentState, Photon.Pun.Simple.SyncState.SoftMount.
Mount Photon.Pun.Simple.SyncState.currentMount
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.OnNetObjReadyChange.
bool Photon.Pun.Simple.SyncState.netObjIsReady
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.OnNetObjReadyChange.
MountsManager Photon.Pun.Simple.SyncState.mountsLookup
Referenced by Photon.Pun.Simple.SyncState.OnAwake.
SyncTransform Photon.Pun.Simple.SyncState.syncTransform
Referenced by Photon.Pun.Simple.SyncState.ApplySnapshot, Photon.Pun.Simple.SyncState.OnAwake.
SyncOwner Photon.Pun.Simple.SyncState.syncOwner
Referenced by Photon.Pun.Simple.SyncState.OnAwake.
ISpawnController Photon.Pun.Simple.SyncState.iSpawnController
Referenced by Photon.Pun.Simple.SyncState.OnAwake, Photon.Pun.Simple.SyncState.OnJoinedRoom, Photon.Pun.Simple.SyncState.OnNetObjReadyChange.
Dictionary<int, int> Photon.Pun.Simple.SyncState.mountTypeIdToIndex
[mountTypeId, index]
Referenced by Photon.Pun.Simple.SyncState.OnNetSerialize, Photon.Pun.Simple.SyncState.OnStart.
int [] Photon.Pun.Simple.SyncState.indexToMountTypeId
Referenced by Photon.Pun.Simple.SyncState.OnNetDeserialize, Photon.Pun.Simple.SyncState.OnStart.
int Photon.Pun.Simple.SyncState.bitsForMountType
Referenced by Photon.Pun.Simple.SyncState.OnNetDeserialize, Photon.Pun.Simple.SyncState.OnNetSerialize, Photon.Pun.Simple.SyncState.OnStart.
StateChangeInfo Photon.Pun.Simple.SyncState.respawnStateInfo
The state to which this object will be set when Respawn is called.
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.OnStart, Photon.Pun.Simple.SyncState.Respawn.
Queue<StateChangeInfo> Photon.Pun.Simple.SyncState.stateChangeQueue
Referenced by Photon.Pun.Simple.SyncState.DequeueStateChanges, Photon.Pun.Simple.SyncState.Despawn, Photon.Pun.Simple.SyncState.Drop, Photon.Pun.Simple.SyncState.ImmediateUnmount, Photon.Pun.Simple.SyncState.OnAuthorityChanged, Photon.Pun.Simple.SyncState.QueueStateChange, Photon.Pun.Simple.SyncState.Respawn, Photon.Pun.Simple.SyncState.Throw, Photon.Pun.Simple.SyncState.ThrowLocal.
Frame Photon.Pun.Simple.SyncState.prevSerializedFrame
Referenced by Photon.Pun.Simple.SyncState.OnAuthorityChanged, Photon.Pun.Simple.SyncState.OnNetSerialize.
override void Photon.Pun.Simple.SyncState.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
References Photon.Pun.Simple.SyncState.flagTeleportCallbacks, Photon.Pun.Simple.SyncState.iSpawnController, Photon.Pun.Simple.SyncState.mountsLookup, Photon.Pun.Simple.NetComponent.netObj, Photon.Pun.Simple.SyncState.onStateChangeCallbacks, Photon.Pun.Simple.SyncState.syncOwner, Photon.Pun.Simple.SyncState.syncTransform.
override void Photon.Pun.Simple.SyncState.OnStart()
References Photon.Pun.Simple.SyncState.bitsForMountType, Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.indexToMountTypeId, Photon.Pun.Simple.SyncState.initialState, Photon.Pun.Simple.MountMaskSelector.mask, Photon.Pun.Simple.SyncState.mountableTo, Photon.Pun.Simple.MountSettings.mountTypeCount, Photon.Pun.Simple.SyncState.mountTypeIdToIndex, Photon.Pun.PhotonView.OwnerActorNr, Photon.Pun.Simple.NetComponent.photonView, Photon.Pun.Simple.SyncState.respawnState, Photon.Pun.Simple.SyncState.respawnStateInfo.
override void Photon.Pun.Simple.SyncState.OnJoinedRoom()
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.initialState, Photon.Pun.Simple.SyncState.iSpawnController.
override void Photon.Pun.Simple.SyncState.OnAuthorityChanged(bool isMine, bool controllerChanged)
Updates authority values on authority changes.
controllerChanged
References Photon.Pun.Simple.SyncState.prevSerializedFrame, Photon.Pun.Simple.SyncState.stateChangeQueue.
virtual void Photon.Pun.Simple.SyncState.OnNetObjReadyChange(bool ready)
Respond to NetObject changes in Ready here.
References Photon.Pun.Simple.ISpawnController.AllowNetObjectReadyCallback, Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.currentMount, Photon.Pun.Simple.NetComponent.IsMine, Photon.Pun.Simple.SyncState.iSpawnController, Photon.Pun.Simple.SyncState.netObjIsReady, Photon.Pun.Simple.SyncState.readyState, Photon.Pun.Simple.SyncState.unreadyState.
void Photon.Pun.Simple.SyncState.SoftMount(Mount attachTo)
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.currentState, Photon.Pun.Simple.SyncState.Frame.state.
Referenced by Photon.Pun.Simple.AutoMountHitscan.OnPreSimulate.
void Photon.Pun.Simple.SyncState.HardMount(Mount mountTo)
mountTo
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.currentState, Photon.Pun.Simple.SyncState.Frame.state.
Referenced by Photon.Pun.Simple.InventoryContactReactors< T >.ProcessContactEvent, Photon.Pun.Simple.VitalsContactReactor.ProcessContactEvent.
void Photon.Pun.Simple.SyncState.Spawn()
void Photon.Pun.Simple.SyncState.Respawn(bool immediate)
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.respawnStateInfo, Photon.Pun.Simple.SyncState.stateChangeQueue.
Referenced by Photon.Pun.Simple.SyncSpawnTimer.ApplySnapshot, Photon.Pun.Simple.SyncSpawnTimer.OnCaptureCurrentState.
void Photon.Pun.Simple.SyncState.Despawn(bool immediate)
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.stateChangeQueue.
Referenced by Photon.Pun.Simple.SyncSpawnTimer.ApplySnapshot, Photon.Pun.Simple.VitalsContactReactor.Consume, Photon.Pun.Simple.SyncSpawnTimer.OnCaptureCurrentState, Photon.Pun.Simple.SyncVitals.RootVitalBecameZero.
void Photon.Pun.Simple.SyncState.ImmediateUnmount()
Handler that unparents this object from any mount immediately (rather than on the next tick Capture).
Put in place for handling despawning of objects, so that mounts on NetObjects can unmount all objects before self-destructing.
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.stateChangeQueue.
void Photon.Pun.Simple.SyncState.Drop(Mount newMount, bool force=false)
References Photon.Pun.Simple.SyncState.stateChangeQueue.
void Photon.Pun.Simple.SyncState.Throw(Vector3 position, Quaternion rotation, Vector3 velocity)
References Photon.Pun.Simple.SyncState.stateChangeQueue.
void Photon.Pun.Simple.SyncState.ThrowLocal(Transform origin, Vector3 offset, Vector3 velocity)
References Photon.Pun.Simple.SyncState.stateChangeQueue.
virtual void Photon.Pun.Simple.SyncState.QueueStateChange(ObjState newState, Mount newMount, bool force)
References Photon.Pun.Simple.SyncState.stateChangeQueue.
virtual void Photon.Pun.Simple.SyncState.QueueStateChange(ObjState newState, Mount newMount, Vector3 offset, Vector3 velocity, bool force)
References Photon.Pun.Simple.SyncState.stateChangeQueue.
virtual bool Photon.Pun.Simple.SyncState.ChangeMount(int newMountId)
Attempt to change to a different Mount on the same object.
newMountId
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.currentMount, Photon.Pun.Simple.SyncState.currentState, Photon.Pun.Simple.MountSettings.GetName, Photon.Pun.Simple.SyncState.mountableTo, Photon.Pun.Simple.MountsManager.mountIdLookup, Photon.Pun.Simple.Mount.mountsLookup, Photon.Pun.Simple.SyncState.Frame.state.
Referenced by Photon.Pun.Simple.MountSwitcher.OnPreSimulate.
void Photon.Pun.Simple.SyncState.OnCaptureCurrentState(int frameId)
References Photon.Pun.Simple.SyncState.Frame.CopyFrom, Photon.Pun.Simple.SyncState.currentState, Photon.Pun.Simple.SyncState.DequeueStateChanges, Photon.Pun.Simple.SyncObject< SyncState.Frame >::frames.
SerializationFlags Photon.Pun.Simple.SyncState.OnNetSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
References Photon.Pun.Simple.SyncState.bitsForMountType, Photon.Pun.Simple.SyncObject< SyncState.Frame >::frames, Photon.Pun.Simple.IUseKeyframes.IsKeyframe, Photon.Pun.Simple.SyncObject< SyncState.Frame >::keyframeRate, Photon.Pun.Simple.SyncState.mountReliable, Photon.Pun.Simple.SyncState.Frame.mountToViewID, Photon.Pun.Simple.SyncState.Frame.mountTypeId, Photon.Pun.Simple.SyncState.mountTypeIdToIndex, Photon.Pun.Simple.SyncState.prevSerializedFrame, Photon.Pun.Simple.SyncState.Frame.state.
SerializationFlags Photon.Pun.Simple.SyncState.OnNetDeserialize(int originFrameId, byte[] buffer, ref int bitposition, FrameArrival arrival)
References Photon.Pun.Simple.SyncState.bitsForMountType, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncObject< SyncState.Frame >::frames, Photon.Pun.Simple.SyncState.indexToMountTypeId, Photon.Pun.Simple.IUseKeyframes.IsKeyframe, Photon.Pun.Simple.SyncState.Frame.mountToViewID, Photon.Pun.Simple.SyncState.Frame.mountTypeId, Photon.Pun.Simple.SyncState.Frame.state.
virtual void Photon.Pun.Simple.SyncState.DequeueStateChanges()
References Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.SyncState.stateChangeQueue.
Referenced by Photon.Pun.Simple.SyncState.OnCaptureCurrentState.
virtual void Photon.Pun.Simple.SyncState.ChangeState(StateChangeInfo stateChangeInfo)
Call this method to change the state of this object.
This state will be synced over the network, and callbacks will trigger locally and remotely. Typically it is preferred to call QueueStateChange(), which will defer the ChangeState application until the appropriate timing.
References Photon.Pun.Simple.SyncState.autoOwnerChange, Photon.Pun.Simple.SyncState.autoReset, Photon.Pun.Simple.Mount.ChangeMounting, Photon.Pun.Simple.SyncState.currentMount, Photon.Pun.Simple.SyncState.currentState, Photon.Pun.Simple.SyncState.flagTeleportCallbacks, Photon.Pun.Simple.StateChangeInfo.force, Photon.Pun.Simple.SyncState.InvalidMountHandler, Photon.Pun.Simple.NetComponent.IsMine, Photon.Pun.Simple.StateChangeInfo.mount, Photon.Pun.Simple.SyncState.Frame.mountToViewID, Photon.Pun.Simple.SyncState.Frame.mountTypeId, Photon.Pun.Simple.NetComponent.netObj, Photon.Pun.Simple.SyncState.netObjIsReady, Photon.Pun.Simple.StateChangeInfo.objState, Photon.Pun.Simple.StateChangeInfo.offsetPos, Photon.Pun.Simple.StateChangeInfo.offsetRot, Photon.Pun.Simple.SyncState.onStateChangeCallbacks, Photon.Pun.Simple.NetObject.Rb, Photon.Pun.Simple.NetObject.Rb2D, Photon.Pun.Simple.SyncState.respawnStateInfo, Photon.Pun.Simple.SyncState.Frame.state, Photon.Pun.Simple.StateChangeInfo.velocity.
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.SyncState.DequeueStateChanges, Photon.Pun.Simple.SyncState.Despawn, Photon.Pun.Simple.SyncState.HardMount, Photon.Pun.Simple.SyncState.ImmediateUnmount, Photon.Pun.Simple.SyncState.InvalidMountHandler, Photon.Pun.Simple.SyncState.OnJoinedRoom, Photon.Pun.Simple.SyncState.OnNetObjReadyChange, Photon.Pun.Simple.SyncState.OnStart, Photon.Pun.Simple.SyncState.Respawn, Photon.Pun.Simple.SyncState.SoftMount.
virtual void Photon.Pun.Simple.SyncState.InvalidMountHandler(ObjState newState, Mount newMount, bool force)
Modify StateChange call if the mount was invalid (Mount likely destroyed).
References Photon.Pun.Simple.SyncState.ChangeState.
Referenced by Photon.Pun.Simple.SyncState.ChangeState.
override void Photon.Pun.Simple.SyncState.ApplySnapshot(Frame snapframe, Frame targframe, bool snapIsValid, bool targIsValid)
References Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncState.GetMount, Photon.Pun.Simple.SyncState.Frame.mountToViewID, Photon.Pun.Simple.SyncState.Frame.mountTypeId, Photon.Pun.Simple.SyncState.Frame.state, Photon.Pun.Simple.SyncState.syncTransform, Photon.Pun.Simple.SyncTransform.UpdateParent.
void Photon.Pun.Simple.SyncState.ChangeOwnerToParentMountsOwner()
Deferred method that applies pending onwer changes.
This is used internally.
void Photon.Pun.Simple.SyncState.ApplyFrame(Frame frame)
static Mount Photon.Pun.Simple.SyncState.GetMount(int? viewID, int? mountId)
References Photon.Pun.PhotonNetwork.GetPhotonView, Photon.Pun.Simple.MountsManager.mountIdLookup.
Referenced by Photon.Pun.Simple.SyncState.ApplySnapshot.