Photon::Compression::Internal::PackFrame_TestPackObject
System.Single Photon.Compression.Internal.PackFrame_TestPackObject.rotation
Referenced by Photon.Compression.Internal.PackFrame_TestPackObject.Capture, Photon.Compression.Internal.PackFrame_TestPackObject.Copy.
System.Int32 Photon.Compression.Internal.PackFrame_TestPackObject.intoroboto
static void Photon.Compression.Internal.PackFrame_TestPackObject.Interpolate(PackFrame start, PackFrame end, PackFrame trg, float time, ref FastBitMask128 readyMask, ref int maskOffset)
References Photon.Compression.Internal.PackFrame.mask.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static void Photon.Compression.Internal.PackFrame_TestPackObject.Interpolate(PackFrame start, PackFrame end, System.Object trg, float time, ref FastBitMask128 readyMask, ref int maskOffset)
References Photon.Compression.Internal.PackFrame.mask.
static void Photon.Compression.Internal.PackFrame_TestPackObject.SnapshotCallback(PackFrame snapframe, PackFrame targframe, System.Object trg, ref FastBitMask128 readyMask, ref int maskOffset)
References Photon.Compression.Internal.PackFrame.mask.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static void Photon.Compression.Internal.PackFrame_TestPackObject.Capture(System.Object src, PackFrame trg)
References Photon.Compression.Internal.PackFrame_TestPackObject.rotation.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static void Photon.Compression.Internal.PackFrame_TestPackObject.Apply(PackFrame src, System.Object trg, ref FastBitMask128 mask, ref int maskOffset)
References Photon.Compression.Internal.PackFrame.mask, emotitron.TestPackObject.rotation.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static void Photon.Compression.Internal.PackFrame_TestPackObject.Copy(PackFrame src, PackFrame trg)
References Photon.Compression.Internal.PackFrame_TestPackObject.rotation.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static PackFrame Photon.Compression.Internal.PackFrame_TestPackObject.Factory()
References Photon.Compression.Internal.PackFrame.isCompleteMask, Photon.Compression.Internal.PackFrame.mask, Photon.Compression.Internal.Pack_TestPackObject.TOTAL_FIELDS.
Referenced by Photon.Compression.Internal.Pack_TestPackObject.Initialize.
static PackFrame[] Photon.Compression.Internal.PackFrame_TestPackObject.Factory(System.Object trg, int count)
References Photon.Compression.Internal.PackFrame.isCompleteMask, Photon.Compression.Internal.PackFrame.mask, Photon.Compression.Internal.Pack_TestPackObject.TOTAL_FIELDS.