Photon::Pun::PhotonNetwork
const string Photon.Pun.PhotonNetwork.PunVersion
Version number of PUN. Used in the AppVersion, which separates your playerbase in matchmaking.
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI, Photon.Pun.PhotonEditor.RegisterWithEmail.
LoadBalancingClient Photon.Pun.PhotonNetwork.NetworkingClient
The LoadBalancingClient is part of Photon Realtime and wraps up multiple servers and states for PUN.
Referenced by Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Pun.Simple.Internal.TickManager.Bootstrap, Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine, Photon.Pun.PhotonNetwork.CloseConnection, Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.Disconnect, Photon.Pun.PhotonHandler.Dispatch, Photon.Pun.PhotonNetwork.FetchServerTimestamp, Photon.Pun.PhotonNetwork.FindFriends, Photon.Pun.PhotonNetwork.GetCustomRoomList, Photon.Pun.PhotonNetwork.GetPing, Photon.Pun.PhotonNetwork.JoinLobby, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Pun.PhotonHandler.LateUpdate, Photon.Pun.PhotonNetwork.LeaveLobby, Photon.Pun.PhotonNetwork.LeaveRoom, Photon.Pun.PhotonNetwork.NetworkStatisticsReset, Photon.Pun.PhotonNetwork.NetworkStatisticsToString, Photon.Pun.PhotonHandler.OnEnable, Photon.Pun.Simple.Internal.NetMsgCallbacks.OnEvent, Photon.Pun.UtilityScripts.PhotonStatsGui.OnGUI, Photon.Pun.PhotonNetwork.RaiseEvent, Photon.Pun.PhotonNetwork.Reconnect, Photon.Pun.PhotonNetwork.ReconnectAndRejoin, Photon.Pun.PhotonNetwork.RejoinRoom, Photon.Pun.PhotonNetwork.RemoveCallbackTarget, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.PhotonNetwork.SendAllOutgoingCommands, Photon.Pun.PhotonNetwork.SetInterestGroups, Photon.Pun.UtilityScripts.PhotonLagSimulationGui.Start, Photon.Pun.UtilityScripts.PhotonStatsGui.TrafficStatsWindow, Photon.Pun.PhotonNetwork.WebRpc.
readonly int Photon.Pun.PhotonNetwork.MAX_VIEW_IDS
The maximum number of assigned PhotonViews per player (or scene).
See the General Documentation topic "Limitations" on how to raise this limitation.
Referenced by Photon.Pun.PhotonNetwork.AllocateViewID.
const string Photon.Pun.PhotonNetwork.ServerSettingsFileName
Name of the PhotonServerSettings file (used to load and by PhotonEditor to save new files).
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonNetwork.LoadOrCreateSettings.
ConnectMethod Photon.Pun.PhotonNetwork.ConnectMethod
Tracks, which Connect method was called last.
ConnectToMaster sets this to ConnectToMaster. ConnectToRegion sets this to ConnectToRegion. ConnectToBestCloudServer sets this to ConnectToBest. PhotonNetwork.ConnectUsingSettings will call either ConnectToMaster, ConnectToRegion or ConnectToBest, depending on the settings.
PunLogLevel Photon.Pun.PhotonNetwork.LogLevel
Controls how verbose PUN is.
Referenced by Photon.Pun.PhotonNetwork.RegisterPhotonView, Photon.Pun.PhotonView.RequestOwnership, Photon.Pun.PhotonNetwork.SetMasterClient, Photon.Pun.PhotonView.TransferOwnership.
bool Photon.Pun.PhotonNetwork.EnableCloseConnection
Used to enable reaction to CloseConnection events.
Default: false. Using CloseConnection is a security risk, as exploiters can send the event as Master Client. In best case, a game would implement this "disconnect others" independently from PUN in game-code with some security checks.
Referenced by Photon.Pun.PhotonNetwork.CloseConnection.
float Photon.Pun.PhotonNetwork.PrecisionForVectorSynchronization
The minimum difference that a Vector2 or Vector3(e.g.
a transforms rotation) needs to change before we send it via a PhotonView's OnSerialize/ObservingComponent. Note that this is the sqrMagnitude. E.g. to send only after a 0.01 change on the Y-axix, we use 0.01f*0.01f=0.0001f. As a remedy against float inaccuracy we use 0.000099f instead of 0.0001f.
float Photon.Pun.PhotonNetwork.PrecisionForQuaternionSynchronization
The minimum angle that a rotation needs to change before we send it via a PhotonView's OnSerialize/ObservingComponent.
float Photon.Pun.PhotonNetwork.PrecisionForFloatSynchronization
The minimum difference between floats before we send it via a PhotonView's OnSerialize/ObservingComponent.
float Photon.Pun.PhotonNetwork.MinimalTimeScaleToDispatchInFixedUpdate
Affects if the PhotonHandler dispatches incoming messages in LateUpdate or FixedUpdate (default).
By default the PhotonHandler component dispatches incoming messages in FixedUpdate. When the Time.timeScale is low, FixedUpdate is called less frequently up to a point where updates may get paused. PUN can automatically dispatch messages in LateUpdate for low timeScale values (when Time.timeScale is lower than this value). PUN will use either FixedUpdate or LateUpdate but not both (as of v2.23). When you use this value, be aware that Instantiates and RPCs execute with a changed timing within a frame. If Instantiate is called from FixedUpdate, the physics engine seems to run for instantiated objects before the engine calls Start() on them. By default, this value is -1f, so there is no fallback to LateUpdate.
Referenced by Photon.Pun.PhotonHandler.FixedUpdate, Photon.Pun.PhotonHandler.LateUpdate.
bool Photon.Pun.PhotonNetwork.UseRpcMonoBehaviourCache
While enabled, the MonoBehaviours on which we call RPCs are cached, avoiding costly GetComponents<MonoBehaviour>() calls.
RPCs are called on the MonoBehaviours of a target PhotonView. Those have to be found via GetComponents. When set this to true, the list of MonoBehaviours gets cached in each PhotonView. You can use photonView.RefreshRpcMonoBehaviourCache() to manually refresh a PhotonView's list of MonoBehaviours on demand (when a new MonoBehaviour gets added to a networked GameObject, e.g.).
bool Photon.Pun.PhotonNetwork.RunRpcCoroutines
If an RPC method is implemented as coroutine, it gets started, unless this value is false.
As starting coroutines causes a little memnory garbage, you may want to disable this option but it is also good enough to not return IEnumerable from methods with the attribite PunRPC.
int Photon.Pun.PhotonNetwork.ObjectsInOneUpdate
Defines how many updated produced by OnPhotonSerialize() are batched into one message.
A low number increases overhead, a high number might lead to fragmented messages.
const int Photon.Pun.PhotonNetwork.SyncViewId
const int Photon.Pun.PhotonNetwork.SyncCompressed
const int Photon.Pun.PhotonNetwork.SyncNullValues
const int Photon.Pun.PhotonNetwork.SyncFirstValue
string Photon.Pun.PhotonNetwork.GameVersion
Version number of your game.
Setting this updates the AppVersion, which separates your playerbase in matchmaking. In PUN, the GameVersion is only one component of the LoadBalancingClient.AppVersion. Setting the GameVersion will also set the LoadBalancingClient.AppVersion to: value+'_'+ PhotonNetwork.PunVersion. The AppVersion is used to split your playerbase as needed. One AppId may have various AppVersions and each is a separate set of users for matchmaking. The AppVersion gets sent in the "Authenticate" step. This means you can set the GameVersion right after calling ConnectUsingSettings (e.g.) and the new value will be used on the server. Once the client is connected, authentication is done and the value won't be sent to the server anymore.
Referenced by Photon.Pun.Demo.PunBasics.Launcher.Connect, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.ConnectNow, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings.
string Photon.Pun.PhotonNetwork.AppVersion
Sent to Photon Server to specify the "Virtual AppId".
Sent with the operation Authenticate. When using PUN, you should set the GameVersion or use ConnectUsingSettings().
ServerSettings Photon.Pun.PhotonNetwork.PhotonServerSettings
Serialized server settings, written by the Setup Wizard for use in ConnectUsingSettings.
Referenced by Photon.Pun.PhotonEditor.Awake, Photon.Pun.Demo.Procedural.IngameControlPanel.Awake, Photon.Pun.PhotonEditor.ClearRpcList, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonHandler.OnEnable, Photon.Pun.ServerSettingsInspector.OnInspectorGUI, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions, Photon.Pun.PhotonEditor.UiSetupApp, Photon.Pun.PhotonEditor.UpdateRpcList.
string? Photon.Pun.PhotonNetwork.ServerAddress
Currently used server address (no matter if master or game server).
string? Photon.Pun.PhotonNetwork.CloudRegion
Currently used Cloud Region (if any). As long as the client is not on a Master Server or Game Server, the region is not yet defined.
Referenced by Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnConnectedToMaster, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnJoinedLobby, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnJoinedRoom, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnJoinRandomFailed.
string? Photon.Pun.PhotonNetwork.CurrentCluster
The cluster name provided by the Name Server.
The value is provided by the OpResponse for OpAuthenticate/OpAuthenticateOnce. See ConnectToRegion. Null until set. Note that the Name Server may assign another cluster, if the requested one is not configured or available.
string Photon.Pun.PhotonNetwork.BestRegionSummaryInPreferences
Used to store and access the "Best Region Summary" in the Player Preferences.
Set this value to null before you connect, to discard the previously selected Best Region for the client.
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI, Photon.Pun.ServerSettings.ResetBestRegionCodeInPreferences.
bool Photon.Pun.PhotonNetwork.IsConnected
False until you connected to Photon initially.
True immediately after Connect-call, in offline mode, while connected to any server and even while switching servers. It is recommended to use the IConnectionCallbacks to establish a connection workflow. Also have a look at IsConnectedAndReady, which provides more info on when you can call operations at all.
Referenced by Photon.Pun.Demo.PunBasics.Launcher.Connect, Photon.Pun.PhotonNetwork.JoinLobby, Photon.Pun.PhotonNetwork.LeaveLobby, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
bool Photon.Pun.PhotonNetwork.IsConnectedAndReady
A refined version of connected which is true only if your connection to the server is ready to accept operations like join, leave, etc.
Referenced by Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.GetPlayerNumber, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Pun.PhotonNetwork.RejoinRoom, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.SetPlayerNumber, Photon.Pun.UtilityScripts.TeamExtensions.SetTeam.
ClientState? Photon.Pun.PhotonNetwork.NetworkClientState
Directly provides the network-level client state, unless in OfflineMode.
In context of PUN, you should usually use IsConnected or IsConnectedAndReady. This is the lower level connection state. Keep in mind that PUN uses more than one server, so the client may become Disconnected, even though it's just switching servers. While OfflineMode is true, this is ClientState.Joined (after create/join) or ConnectedToMasterServer in all other cases.
Referenced by Photon.Pun.PhotonNetwork.Instantiate, Photon.Pun.PhotonNetwork.LeaveRoom, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.SetPlayerNumber, Photon.Pun.UtilityScripts.TeamExtensions.SetTeam, Photon.Pun.Demo.Asteroids.LobbyTopPanel.Update.
ServerConnection?? Photon.Pun.PhotonNetwork.Server
The server (type) this client is currently connected or connecting to.
Photon uses 3 different roles of servers: Name Server, Master Server and Game Server.
Referenced by Photon.Pun.PhotonNetwork.JoinLobby, Photon.Pun.PhotonNetwork.LeaveLobby, Photon.Pun.Demo.WebRpcImplementationExample.OnWebRpcResponse, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
AuthenticationValues? Photon.Pun.PhotonNetwork.AuthValues
A user's authentication values used during connect.
Set these before calling Connect if you want custom authentication. These values set the userId, if and how that userId gets verified (server-side), etc.. If authentication fails for any values, PUN will call your implementation of OnCustomAuthenticationFailed(string debugMessage). See Photon.Realtime.IConnectionCallbacks.OnCustomAuthenticationFailed.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Connect, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.Demo.Cockpit.PunCockpit.ReConnect, Photon.Pun.Demo.Cockpit.PunCockpit.ReconnectAndRejoin.
TypedLobby Photon.Pun.PhotonNetwork.CurrentLobby
The lobby that will be used when PUN joins a lobby or creates a game.
This is defined when joining a lobby or creating rooms The default lobby uses an empty string as name. So when you connect or leave a room, PUN automatically gets you into a lobby again. Check PhotonNetwork.InLobby if the client is in a lobby. (masterServerAndLobby)
Room? Photon.Pun.PhotonNetwork.CurrentRoom
Get the room we're currently in (also when in OfflineMode).
Null if we aren't in any room. LoadBalancing Client is not aware of the Photon Offline Mode, so never use PhotonNetwork.NetworkingClient.CurrentRoom will be null if you are using OffLine Mode, while PhotonNetwork.CurrentRoom will be set when offlineMode is true
Referenced by Launcher.CheckAllPlayersReady, Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.Simple.SyncOwner.DeferredOwnerChange, Photon.Pun.UtilityScripts.TurnExtensions.GetFinishedTurn, Photon.Pun.PhotonNetwork.Instantiate, Photon.Pun.PhotonNetwork.InstantiateRoomObject, Photon.Pun.PhotonNetwork.LeaveRoom, Photon.Pun.Demo.Cockpit.PlayerListView.OnEnable, Launcher.OnJoinedRoom, Launcher_old.OnJoinedRoom, Photon.Pun.PhotonHandler.OnJoinedRoom, Photon.Pun.Demo.PunBasics.Launcher.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PlayerListView.OnMasterClientSwitched, Photon.Pun.PhotonHandler.OnPlayerLeftRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnStartGameButtonClicked, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.UtilityScripts.TurnExtensions.SetFinishedTurn, Photon.Pun.PhotonNetwork.SetMasterClient, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget, Photon.Pun.Demo.Cockpit.PunCockpit.SetRoomCustomProperty, Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime, Photon.Pun.Demo.Cockpit.CurrentRoomIsOpenToggle.ToggleValue, Photon.Pun.Demo.Cockpit.CurrentRoomIsVisibleToggle.ToggleValue, Photon.Pun.UtilityScripts.CountdownTimer.TryGetStartTime.
Player Photon.Pun.PhotonNetwork.LocalPlayer
This client's Player instance is always available, unless the app shuts down.
Useful (e.g.) to set the Custom Player Properties or the NickName for this client anytime. When the client joins a room, the Custom Properties and other values are synced.
Referenced by Photon.Pun.PhotonNetwork.AllocateViewID, Launcher.AssignRoleRandomly, SInt.Netcode.PhotonPUN.PlayerManager.CheckAllPlayersReady, Photon.Pun.PhotonNetwork.CloseConnection, Photon.Pun.PhotonNetwork.DestroyPlayerObjects, Photon.Pun.Demo.Asteroids.Spaceship.DestroySpaceship, Photon.Pun.UtilityScripts.OnJoinedInstantiate.GetSpawnPoint, SInt.MissionObjectives.MoOwner.Init, Photon.Pun.PhotonNetwork.Instantiate, Photon.Pun.PhotonNetwork.InstantiateRoomObject, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Launcher.OnClick_Ready, ReadyCheck.OnClick_Ready, Photon.Pun.UtilityScripts.PunTeamsInspector.OnInspectorGUI, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom, Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnJoinedRoom, Photon.Pun.UtilityScripts.PlayerNumbering.OnLeftRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnLoginButtonClicked, Launcher.OnMasterClientSwitched, Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnMasterClientSwitched, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnMasterClientSwitched, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, Photon.Pun.PhotonNetwork.RemovePlayerCustomProperties, SInt.Netcode.PhotonPUN.PlayerManager.RespawnLocalPlayerInstance, DestroyGameObject.SelfDestroy, Photon.Pun.UtilityScripts.PunTurnManager.SendMove, Photon.Pun.Demo.Cockpit.FriendListView.SetFriendDetails, ScoreManager.SetMainScore, CatBreakFurniture.SetOutlineVisibility, Photon.Pun.PhotonNetwork.SetPlayerCustomProperties, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget, ScoreManager.SetTrapScore, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion, Photon.Pun.Demo.Asteroids.AsteroidsGameManager.Start, Photon.Pun.Demo.Asteroids.PlayerListEntry.Start, Photon.Pun.Example.TakeOwnership.TransferOwner, CatTrappedScript.TrapDestroyself, TrapMechanicButtonScript.TrapInstantiate, Photon.Pun.Demo.Asteroids.Spaceship.Update.
string Photon.Pun.PhotonNetwork.NickName
Set to synchronize the player's nickname with everyone in the room(s) you enter.
This sets PhotonNetwork.player.NickName. The NickName is just a nickname and does not have to be unique or backed up with some account. Set the value any time (e.g. before you connect) and it will be available to everyone you play with. Access the names of players by: Player.NickName. PhotonNetwork.PlayerListOthers is a list of other players - each contains the NickName the remote player set.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnConnected, Launcher_old.OnJoinedLobby, PlayerNameManager.OnUsernameInputValueChanged, Photon.Pun.Demo.PunBasics.PlayerNameInputField.SetPlayerName, Photon.Pun.Demo.Cockpit.NickNameField.SubmitForm.
Player [] Photon.Pun.PhotonNetwork.PlayerList
A sorted copy of the players-list of the current room.
This is using Linq, so better cache this value. Update when players join / leave.
Referenced by Photon.Pun.Demo.Asteroids.PlayerOverviewPanel.Awake, SInt.Netcode.PhotonPUN.PlayerManager.CheckAllPlayersReady, Launcher.CheckAllPlayersReady, Launcher.OnJoinedRoom, Launcher_old.OnJoinedRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnJoinedRoom, ScoreManager.OnPlayerPropertiesUpdate, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, ScoreManager.Start, Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
Player [] Photon.Pun.PhotonNetwork.PlayerListOthers
A sorted copy of the players-list of the current room, excluding this client.
This is using Linq, so better cache this value. Update when players join / leave.
Referenced by Photon.Pun.Demo.Cockpit.PlayerListView.OnPlayerLeftRoom.
bool Photon.Pun.PhotonNetwork.OfflineMode
Offline mode can be set to re-use your multiplayer code in singleplayer game modes.
When this is on PhotonNetwork will not create any connections and there is near to no overhead. Mostly usefull for reusing RPC's and PhotonNetwork.Instantiate
Referenced by TransitionToLobby.CheckIfHappening, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectOffline, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.Disconnect, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.GetPlayerNumber, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Pun.PhotonNetwork.LeaveRoom, Photon.Pun.PhotonNetwork.NetworkStatisticsToString, Photon.Pun.Demo.Cockpit.PunCockpit.OnConnectedToMaster, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftRoom, Photon.Pun.PhotonNetwork.Reconnect, Photon.Pun.PhotonNetwork.ReconnectAndRejoin, Photon.Pun.PhotonNetwork.RejoinRoom, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.PhotonNetwork.SetMasterClient, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.SetPlayerNumber.
bool Photon.Pun.PhotonNetwork.AutomaticallySyncScene
Defines if all clients in a room should automatically load the same level as the Master Client.
When enabled, clients load the same scene that is active on the Master Client. When a client joins a room, the scene gets loaded even before the callback OnJoinedRoom gets called. To synchronize the loaded level, the Master Client should use PhotonNetwork.LoadLevel, which notifies the other clients before starting to load the scene. If the Master Client loads a level directly via Unity's API, PUN will notify the other players after the scene loading completed (using SceneManager.sceneLoaded). Internally, a Custom Room Property is set for the loaded scene. On change, clients use LoadLevel if they are not in the same scene. Note that this works only for a single active scene and that reloading the scene is not supported. The Master Client will actually reload a scene but other clients won't. To get everyone to reload, the game can send an RPC or event to trigger the loading.
Referenced by Photon.Pun.Demo.Asteroids.LobbyMainPanel.Awake, Photon.Pun.PhotonNetwork.LoadLevel, Launcher.OnConnectedToMaster, Launcher_old.OnConnectedToMaster, Photon.Pun.Demo.Cockpit.AutoSyncSceneToggle.ToggleValue.
bool Photon.Pun.PhotonNetwork.EnableLobbyStatistics
If enabled, the client will get a list of available lobbies from the Master Server.
Set this value before the client connects to the Master Server. While connected to the Master Server, a change has no effect. Implement OptionalInfoCallbacks.OnLobbyStatisticsUpdate, to get the list of used lobbies. The lobby statistics can be useful if your title dynamically uses lobbies, depending (e.g.) on current player activity or such. In this case, getting a list of available lobbies, their room-count and player-count can be useful info. ConnectUsingSettings sets this to the PhotonServerSettings value.
bool Photon.Pun.PhotonNetwork.InLobby
True while this client is in a lobby.
Implement IPunCallbacks.OnRoomListUpdate() for a notification when the list of rooms becomes available or updated. You are automatically leaving any lobby when you join a room! Lobbies only exist on the Master Server (whereas rooms are handled by Game Servers).
Referenced by Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnBackButtonClicked, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnRoomListButtonClicked, Photon.Pun.Demo.Cockpit.RoomListView.OnRoomListUpdate, Photon.Pun.Demo.Asteroids.RoomListEntry.Start, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
int Photon.Pun.PhotonNetwork.SendRate
Defines how many times per second the PhotonHandler should send data, if any is queued.
Default: 30. This value defines how often PUN will call the low level PhotonPeer to put queued outgoing messages into a datagram to be sent. This is implemented in the PhotonHandler component, which integrates PUN into the Unity game loop. The PhotonHandler.MaxDatagrams value defines how many datagrams can be sent in one iteration. This value does not affect how often updates are written by PhotonViews. That is controlled by the SerializationRate. To avoid send-delays for PhotonView updates, PUN will also send data at the end of frames that wrote data in OnPhotonSerializeView, so sending may actually be more frequent than the SendRate. Messages queued due to RPCs and RaiseEvent, will be sent with at least SendRate frequency. They are included, when OnPhotonSerialize wrote updates and triggers early sending. Setting this value does not adjust the SerializationRate anymore (as of PUN 2.24). Sending less often will aggregate messages in datagrams, which avoids overhead on the network. It is also important to not push too many datagrams per frame. Three to five seem to be the sweet spot. Keep your target platform in mind: mobile networks are usually slower. WiFi is slower with more variance and bursts of loss. A low framerate (as in Update calls) will affect sending of messages.
Referenced by Photon.Pun.PhotonHandler.OnEnable, Photon.Pun.Demo.Cockpit.SendRateField.SubmitForm.
int Photon.Pun.PhotonNetwork.SerializationRate
Defines how many times per second OnPhotonSerialize should be called on PhotonViews for controlled objects.
This value defines how often PUN will call OnPhotonSerialize on controlled network objects. This is implemented in the PhotonHandler component, which integrates PUN into the Unity game loop. The updates written in OnPhotonSerialize will be queued temporarily and sent in the next LateUpdate, so a high SerializationRate also causes more sends. The idea is to keep the delay short during which written updates are queued. Calling RPCs will not trigger a send. A low framerate will affect how frequent updates are written and how "on time" they are. A lower rate takes up less performance but the receiving side needs to interpolate longer times between updates.
Referenced by Photon.Pun.PhotonRigidbody2DView.FixedUpdate, Photon.Pun.PhotonRigidbodyView.FixedUpdate, Photon.Pun.PhotonTransformViewPositionControl.GetExtrapolatedPositionOffset, Photon.Pun.PhotonHandler.OnEnable, Photon.Pun.Demo.Cockpit.SendRateOnSerializeField.SubmitForm, Photon.Pun.PhotonTransformView.Update, Photon.Pun.PhotonTransformViewPositionControl.UpdatePosition.
bool Photon.Pun.PhotonNetwork.IsMessageQueueRunning
Can be used to pause dispatching of incoming events (RPCs, Instantiates and anything else incoming).
While IsMessageQueueRunning == false, the OnPhotonSerializeView calls are not done and nothing is sent by a client. Also, incoming messages will be queued until you re-activate the message queue. This can be useful if you first want to load a level, then go on receiving data of PhotonViews and RPCs. The client will go on receiving and sending acknowledgements for incoming packages and your RPCs/Events. This adds "lag" and can cause issues when the pause is longer, as all incoming messages are just queued.
Referenced by Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonHandler.Dispatch, Photon.Pun.PhotonHandler.LateUpdate, Photon.Pun.PhotonNetwork.LoadLevel, Photon.Pun.PhotonNetwork.Reconnect, Photon.Pun.PhotonNetwork.ReconnectAndRejoin.
double Photon.Pun.PhotonNetwork.Time
Photon network time, synched with the server.
v1.55 This time value depends on the server's Environment.TickCount. It is different per server but inside a Room, all clients should have the same value (Rooms are on one server only). This is not a DateTime! Use this value with care: It can start with any positive value. It will "wrap around" from 4294967.295 to 0!
Referenced by Photon.Pun.Demo.Asteroids.Spaceship.Fire, Photon.Pun.PhotonTransformViewPositionControl.GetExtrapolatedPositionOffset, Photon.Pun.PhotonRigidbody2DView.OnPhotonSerializeView, Photon.Pun.PhotonRigidbodyView.OnPhotonSerializeView, Photon.Pun.PhotonTransformView.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewPositionControl.OnPhotonSerializeView.
int Photon.Pun.PhotonNetwork.ServerTimestamp
The current server's millisecond timestamp.
This can be useful to sync actions and events on all clients in one room. The timestamp is based on the server's Environment.TickCount. It will overflow from a positive to a negative value every so often, so be careful to use only time-differences to check the Time delta when things happen. This is the basis for PhotonNetwork.Time.
Referenced by Photon.Pun.PhotonNetwork.Instantiate, Photon.Pun.PhotonNetwork.InstantiateRoomObject, Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime, Photon.Pun.UtilityScripts.TurnExtensions.SetTurn, Photon.Pun.UtilityScripts.CountdownTimer.TryGetStartTime.
float? Photon.Pun.PhotonNetwork.KeepAliveInBackground
Defines how many seconds PUN keeps the connection after Unity's OnApplicationPause(true) call.
Default: 60 seconds. It's best practice to disconnect inactive apps/connections after a while but to also allow users to take calls, etc.. We think a reasonable background timeout is 60 seconds. To handle the timeout, implement: OnDisconnected(), as usual. Your application will "notice" the background disconnect when it becomes active again (running the Update() loop). If you need to separate this case from others, you need to track if the app was in the background (there is no special callback by PUN). Info: PUN is running a "fallback thread" to send ACKs to the server, even when Unity is not calling Update() regularly. This helps keeping the connection while loading scenes and assets and when the app is in the background. Note: Some platforms (e.g. iOS) don't allow to keep a connection while the app is in background. In those cases, this value does not change anything, the app immediately loses connection in background. Unity's OnApplicationPause() callback is broken in some exports (Android) of some Unity versions. Make sure OnApplicationPause() gets the callbacks you expect on the platform you target! Check PhotonHandler.OnApplicationPause(bool pause) to see the implementation.
Referenced by Photon.Pun.Demo.Cockpit.BackgroundTimeOutField.SubmitForm.
bool Photon.Pun.PhotonNetwork.IsMasterClient
Are we the master client?
Referenced by Photon.Pun.PhotonNetwork.AllocateRoomViewID, Launcher.AssignRoleRandomly, Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.PhotonNetwork.DestroyAll, Photon.Pun.Demo.Procedural.Cluster.DestroyCluster, Photon.Pun.PhotonNetwork.DestroyPlayerObjects, Launcher.OnJoinedRoom, Launcher_old.OnJoinedRoom, Photon.Pun.PhotonHandler.OnJoinedRoom, Photon.Pun.Demo.Procedural.IngameControlPanel.OnJoinedRoom, Launcher.OnMasterClientSwitched, Launcher_old.OnMasterClientSwitched, Photon.Pun.PhotonHandler.OnPlayerEnteredRoom, Photon.Pun.Demo.PunBasics.GameManager.OnPlayerEnteredRoom, Photon.Pun.Demo.PunBasics.GameManager.OnPlayerLeftRoom, Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnPlayerPropertiesUpdate, Photon.Pun.PhotonNetwork.RemoveRPCs, Photon.Pun.Demo.Asteroids.PlayerListEntry.Start.
Player Photon.Pun.PhotonNetwork.MasterClient
The Master Client of the current room or null (outside of rooms).
Can be used as "authoritative" client/player to make descisions, run AI or other. If the current Master Client leaves the room (leave/disconnect), the server will quickly assign someone else. If the current Master Client times out (closed app, lost connection, etc), messages sent to this client are effectively lost for the others! A timeout can take 10 seconds in which no Master Client is active. Implement the method IPunCallbacks.OnMasterClientSwitched to be called when the Master Client switched. Use PhotonNetwork.SetMasterClient, to switch manually to some other player / client. With OfflineMode == true, this always returns the PhotonNetwork.player.
Referenced by Launcher.AssignRoleRandomly, Photon.Pun.PhotonHandler.OnPlayerLeftRoom, ScoreManager.SetBrokenFurnitureScore, ScoreManager.SetFixFurnitureScore.
bool Photon.Pun.PhotonNetwork.InRoom
Is true while being in a room (NetworkClientState == ClientState.Joined).
Aside from polling this value, game logic should implement IMatchmakingCallbacks in some class and react when that gets called. Many actions can only be executed in a room, like Instantiate or Leave, etc. A client can join a room in offline mode. In that case, don't use LoadBalancingClient.InRoom, which does not cover offline mode.
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake, Photon.Pun.PhotonNetwork.Destroy, Photon.Pun.UtilityScripts.PlayerNumberingInspector.OnInspectorGUI, Photon.Pun.PhotonNetwork.RaiseEvent, Photon.Pun.PhotonNetwork.SetMasterClient.
int Photon.Pun.PhotonNetwork.CountOfPlayersOnMaster
The count of players currently looking for a room (available on MasterServer in 5sec intervals).
int Photon.Pun.PhotonNetwork.CountOfPlayersInRooms
Count of users currently playing your app in some room (sent every 5sec by Master Server).
Use PhotonNetwork.PlayerList.Length or PhotonNetwork.CurrentRoom.PlayerCount to get the count of players in the room you're in!
int Photon.Pun.PhotonNetwork.CountOfPlayers
The count of players currently using this application (available on MasterServer in 5sec intervals).
int Photon.Pun.PhotonNetwork.CountOfRooms
The count of rooms currently in use (available on MasterServer in 5sec intervals).
bool Photon.Pun.PhotonNetwork.NetworkStatisticsEnabled
Enables or disables the collection of statistics about this client's traffic.
If you encounter issues with clients, the traffic stats are a good starting point to find solutions. Only with enabled stats, you can use GetVitalStats
int Photon.Pun.PhotonNetwork.ResentReliableCommands
Count of commands that got repeated (due to local repeat-timing before an ACK was received).
If this value increases a lot, there is a good chance that a timeout disconnect will happen due to bad conditions.
bool Photon.Pun.PhotonNetwork.CrcCheckEnabled
Crc checks can be useful to detect and avoid issues with broken datagrams. Can be enabled while not connected.
Referenced by Photon.Pun.Demo.Cockpit.CrcCheckToggle.ToggleValue.
int Photon.Pun.PhotonNetwork.PacketLossByCrcCheck
If CrcCheckEnabled, this counts the incoming packages that don't have a valid CRC checksum and got rejected.
int Photon.Pun.PhotonNetwork.MaxResendsBeforeDisconnect
Defines the number of times a reliable message can be resent before not getting an ACK for it will trigger a disconnect.
Default: 5. Less resends mean quicker disconnects, while more can lead to much more lag without helping. Min: 3. Max: 10.
int Photon.Pun.PhotonNetwork.QuickResends
In case of network loss, reliable messages can be repeated quickly up to 3 times.
When reliable messages get lost more than once, subsequent repeats are delayed a bit to allow the network to recover. With this option, the repeats 2 and 3 can be sped up. This can help avoid timeouts but also it increases the speed in which gaps are closed. When you set this, increase PhotonNetwork.MaxResendsBeforeDisconnect to 6 or 7.
bool Photon.Pun.PhotonNetwork.UseAlternativeUdpPorts
Replaced by ServerPortOverrides.
PhotonPortDefinition? Photon.Pun.PhotonNetwork.ServerPortOverrides
Defines overrides for server ports.
Used per server-type if > 0. Important: If you change the transport protocol, adjust the overrides, too. LoadBalancingClient.ServerPortOverrides
PhotonView [] Photon.Pun.PhotonNetwork.PhotonViews
Gets the photon views.
This is an expensive operation as it returns a copy of the internal list. The photon views.
NonAllocDictionary<int, PhotonView>.ValueIterator Photon.Pun.PhotonNetwork.PhotonViewCollection
Returns a new iterable collection of current photon views.
You can iterate over all PhotonViews in a simple foreach loop. To use this in a while-loop, assign the new iterator to a variable and then call MoveNext on that.
Referenced by Photon.Pun.PhotonHandler.OnJoinedRoom, Photon.Pun.PhotonHandler.OnMasterClientSwitched, Photon.Pun.PhotonHandler.OnPlayerEnteredRoom, Photon.Pun.PhotonHandler.OnPlayerLeftRoom.
int Photon.Pun.PhotonNetwork.ViewCount
Referenced by Photon.Pun.PhotonHandler.OnJoinedRoom.
IPunPrefabPool Photon.Pun.PhotonNetwork.PrefabPool
An Object Pool can be used to keep and reuse instantiated object instances.
Replaces Unity's default Instantiate and Destroy methods. Defaults to the DefaultPool type. To use a GameObject pool, implement IPunPrefabPool and assign it here. Prefabs are identified by name.
float Photon.Pun.PhotonNetwork.LevelLoadingProgress
Represents the scene loading progress when using LoadLevel().
The value is 0 if the app never loaded a scene with LoadLevel(). During async scene loading, the value is between 0 and 1. Once any scene completed loading, it stays at 1 (signaling "done"). The level loading progress. Ranges from 0 to 1.
string Photon.Pun.PhotonNetwork.gameVersion
ServerSettings Photon.Pun.PhotonNetwork.photonServerSettings
const string Photon.Pun.PhotonNetwork.PlayerPrefsKey
Key to save the "Best Region Summary" in the Player Preferences.
bool Photon.Pun.PhotonNetwork.offlineMode
Room Photon.Pun.PhotonNetwork.offlineModeRoom
bool Photon.Pun.PhotonNetwork.automaticallySyncScene
int Photon.Pun.PhotonNetwork.sendFrequency
int Photon.Pun.PhotonNetwork.serializationFrequency
bool Photon.Pun.PhotonNetwork.isMessageQueueRunning
Backup for property IsMessageQueueRunning.
double Photon.Pun.PhotonNetwork.frametime
int Photon.Pun.PhotonNetwork.frame
Stopwatch Photon.Pun.PhotonNetwork.StartupStopwatch
Used for Photon/PUN timing, as Time.time can't be called from Threads.
int Photon.Pun.PhotonNetwork.lastUsedViewSubId
int Photon.Pun.PhotonNetwork.lastUsedViewSubIdStatic
readonly HashSet<string> Photon.Pun.PhotonNetwork.PrefabsWithoutMagicCallback
readonly Hashtable Photon.Pun.PhotonNetwork.SendInstantiateEvHashtable
readonly RaiseEventOptions Photon.Pun.PhotonNetwork.SendInstantiateRaiseEventOptions
HashSet<byte> Photon.Pun.PhotonNetwork.allowedReceivingGroups
HashSet<byte> Photon.Pun.PhotonNetwork.blockedSendingGroups
HashSet<PhotonView> Photon.Pun.PhotonNetwork.reusablePVHashset
NonAllocDictionary<int, PhotonView> Photon.Pun.PhotonNetwork.photonViewList
The photon view list.
IPunPrefabPool Photon.Pun.PhotonNetwork.prefabPool
readonly Dictionary<Type, List<MethodInfo> > Photon.Pun.PhotonNetwork.monoRPCMethodsCache
Dictionary<string, int> Photon.Pun.PhotonNetwork.rpcShortcuts
AsyncOperation Photon.Pun.PhotonNetwork._AsyncLevelLoadingOperation
float Photon.Pun.PhotonNetwork._levelLoadingProgress
readonly Type Photon.Pun.PhotonNetwork.typePunRPC
readonly Type Photon.Pun.PhotonNetwork.typePhotonMessageInfo
readonly object Photon.Pun.PhotonNetwork.keyByteZero
readonly object Photon.Pun.PhotonNetwork.keyByteOne
readonly object Photon.Pun.PhotonNetwork.keyByteTwo
readonly object Photon.Pun.PhotonNetwork.keyByteThree
readonly object Photon.Pun.PhotonNetwork.keyByteFour
readonly object Photon.Pun.PhotonNetwork.keyByteFive
readonly object Photon.Pun.PhotonNetwork.keyByteSix
readonly object Photon.Pun.PhotonNetwork.keyByteSeven
readonly object Photon.Pun.PhotonNetwork.keyByteEight
readonly object [] Photon.Pun.PhotonNetwork.emptyObjectArray
readonly Type [] Photon.Pun.PhotonNetwork.emptyTypeArray
readonly ExitGames.Client.Photon.Hashtable Photon.Pun.PhotonNetwork.removeFilter
readonly ExitGames.Client.Photon.Hashtable Photon.Pun.PhotonNetwork.ServerCleanDestroyEvent
readonly RaiseEventOptions Photon.Pun.PhotonNetwork.ServerCleanOptions
readonly Hashtable Photon.Pun.PhotonNetwork.rpcFilterByViewId
readonly RaiseEventOptions Photon.Pun.PhotonNetwork.OpCleanRpcBufferOptions
ExitGames.Client.Photon.Hashtable Photon.Pun.PhotonNetwork.rpcEvent
RPC Hashtable Structure (byte)0 -> (int) ViewId (combined from actorNr and actor-unique-id) (byte)1 -> (short) prefix (level) (byte)2 -> (int) server timestamp (byte)3 -> (string) methodname (byte)4 -> (object[]) parameters (byte)5 -> (byte) method shortcut (alternative to name)
This is sent as event (code: 200) which will contain a sender (origin of this RPC).
RaiseEventOptions Photon.Pun.PhotonNetwork.RpcOptionsToAll
readonly PhotonStream Photon.Pun.PhotonNetwork.serializeStreamOut
readonly PhotonStream Photon.Pun.PhotonNetwork.serializeStreamIn
summary> cache the RaiseEventOptions to prevent redundant Memory Allocation
RaiseEventOptions Photon.Pun.PhotonNetwork.serializeRaiseEvOptions
readonly Dictionary<RaiseEventBatch, SerializeViewBatch> Photon.Pun.PhotonNetwork.serializeViewBatches
RegionHandler Photon.Pun.PhotonNetwork._cachedRegionHandler
Action<PhotonView, Player> Photon.Pun.PhotonNetwork.OnOwnershipRequestEv
Parameters: PhotonView for which ownership changed, previous owner of the view.
Action<PhotonView, Player> Photon.Pun.PhotonNetwork.OnOwnershipTransferedEv
Parameters: PhotonView for which ownership was requested, player who requests ownership.
Action<PhotonView, Player> Photon.Pun.PhotonNetwork.OnOwnershipTransferFailedEv
Parameters: PhotonView for which ownership was requested, player who requested (but didn't get) ownership.
byte Photon.Pun.PhotonNetwork.currentLevelPrefix
bool Photon.Pun.PhotonNetwork.loadingLevelAndPausedNetwork
Internally used to flag if the message queue was disabled by a "scene sync" situation (to re-enable it).
const string Photon.Pun.PhotonNetwork.CurrentSceneProperty
For automatic scene syncing, the loaded scene is put into a room property. This is the name of said prop.
const string Photon.Pun.PhotonNetwork.CurrentScenePropertyLoadAsync
List<PhotonView> Photon.Pun.PhotonNetwork.foundPVs
RaiseEventOptions Photon.Pun.PhotonNetwork.SendToAllOptions
RaiseEventOptions Photon.Pun.PhotonNetwork.SendToOthersOptions
RaiseEventOptions Photon.Pun.PhotonNetwork.SendToSingleOptions
static Photon.Pun.PhotonNetwork.PhotonNetwork()
Static constructor used for basic setup.
static void Photon.Pun.PhotonNetwork.StaticReset()
static bool Photon.Pun.PhotonNetwork.VerifyCanUseNetwork()
Helper function which is called inside this class to erify if certain functions can be used (e.g.
RPC when not connected)
static void Photon.Pun.PhotonNetwork.EnterOfflineRoom(string roomName, RoomOptions roomOptions, bool createdRoom)
Internally used helper-method to setup an offline room, the numbers for actor and master-client and to do the callbacks.
static bool Photon.Pun.PhotonNetwork.RaiseEventInternal(byte eventCode, object eventContent, RaiseEventOptions raiseEventOptions, SendOptions sendOptions)
Sends PUN-specific events to the server, unless in offlineMode.
eventCode A byte identifying the type of event. eventContent Serializable object or container. raiseEventOptions Allows more complex usage of events. If null, RaiseEventOptions. sendOptions Send options for reliable, encryption etc.. False if event could not be sent
static GameObject Photon.Pun.PhotonNetwork.NetworkInstantiate(Hashtable networkEvent, Player creator)
static GameObject Photon.Pun.PhotonNetwork.NetworkInstantiate(Pun.InstantiateParameters parameters, bool roomObject=false, bool instantiateEvent=false)
static void Photon.Pun.PhotonNetwork.SetupLogging()
Applies default log settings if they are not set up programmatically.
static void Photon.Pun.PhotonNetwork.LeftRoomCleanup()
Called when "this client" left a room to clean up.
if (Server == ServerConnection.GameServer && (state == ClientState.Disconnecting || state == ClientState.DisconnectingFromGameServer))
static void Photon.Pun.PhotonNetwork.ResetPhotonViewsOnSerialize()
Resets the PhotonView "lastOnSerializeDataSent" so that "OnReliable" synched PhotonViews send a complete state to new clients (if the state doesnt change, no messages would be send otherwise!).
Note that due to this reset, ALL other players will receive the full OnSerialize.
static bool Photon.Pun.PhotonNetwork.CheckTypeMatch(ParameterInfo[] methodParameters, Type[] callParameterTypes)
Check if all types match with parameters.
We can have more paramters then types (allow last RPC type to be different). methodParameters callParameterTypes If the types-array has matching parameters (of method) in the parameters array (which may be longer).
static void Photon.Pun.PhotonNetwork.ServerCleanInstantiateAndDestroy(PhotonView photonView)
Removes an instantiation event from the server's cache.
Needs id and actorNr of player who instantiated.
static void Photon.Pun.PhotonNetwork.SendDestroyOfPlayer(int actorNr)
static void Photon.Pun.PhotonNetwork.SendDestroyOfAll()
static void Photon.Pun.PhotonNetwork.OpRemoveFromServerInstantiationsOfPlayer(int actorNr)
static void Photon.Pun.PhotonNetwork.RemoveCacheOfLeftPlayers()
This clears the cache of any player/actor who's no longer in the room (making it a simple clean-up option for a new master)
static void Photon.Pun.PhotonNetwork.SendSerializeViewBatch(SerializeViewBatch batch)
static List< object > Photon.Pun.PhotonNetwork.OnSerializeWrite(PhotonView view)
static void Photon.Pun.PhotonNetwork.OnSerializeRead(object[] data, Player sender, int networkTime, short correctPrefix)
Reads updates created by OnSerializeWrite
static List< object > Photon.Pun.PhotonNetwork.DeltaCompressionWrite(List< object > previousContent, List< object > currentContent)
static object[] Photon.Pun.PhotonNetwork.DeltaCompressionRead(object[] lastOnSerializeDataReceived, object[] incomingData)
static bool Photon.Pun.PhotonNetwork.AlmostEquals(IList< object > lastData, IList< object > currentContent)
static bool Photon.Pun.PhotonNetwork.AlmostEquals(object one, object two)
Returns true if both objects are almost identical.
Used to check whether two objects are similar enough to skip an update.
static void Photon.Pun.PhotonNetwork.OnEvent(EventData photonEvent)
static void Photon.Pun.PhotonNetwork.OnOperation(OperationResponse opResponse)
static void Photon.Pun.PhotonNetwork.OnClientStateChanged(ClientState previousState, ClientState state)
static void Photon.Pun.PhotonNetwork.OnRegionsPinged(RegionHandler regionHandler)
static bool Photon.Pun.PhotonNetwork.ConnectUsingSettings()
Connect to Photon as configured in the PhotonServerSettings file.
Implement IConnectionCallbacks, to make your game logic aware of state changes. Especially, IConnectionCallbacks.ConnectedToMasterServer is useful to react when the client can do matchmaking. This method will disable OfflineMode (which won't destroy any instantiated GOs) and it will set IsMessageQueueRunning to true. Your Photon configuration is created by the PUN Wizard and contains the AppId, region for Photon Cloud games, the server address among other things. To ignore the settings file, set the relevant values and connect by calling ConnectToMaster, ConnectToRegion. To connect to the Photon Cloud, a valid AppId must be in the settings file (shown in the Photon Cloud Dashboard). Connecting to the Photon Cloud might fail due to: Invalid AppId Network issues Invalid region Subscription CCU limit reached etc. In general check out the DisconnectCause from the IConnectionCallbacks.OnDisconnected callback.
References Photon.Pun.ServerSettings.AppSettings, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.PhotonNetwork.ServerSettingsFileName, Photon.Pun.ServerSettings.StartInOfflineMode.
Referenced by Photon.Pun.Demo.PunBasics.Launcher.Connect, Photon.Pun.Demo.Cockpit.PunCockpit.Connect, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.ConnectNow, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnLoginButtonClicked.
static bool Photon.Pun.PhotonNetwork.ConnectUsingSettings(AppSettings appSettings, bool startInOfflineMode=false)
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.AppSettings.AppIdRealtime, Photon.Realtime.ConnectionHandler.AppQuits, Photon.Realtime.AppSettings.AppVersion, Photon.Realtime.AppSettings.AuthMode, Photon.Realtime.LoadBalancingClient.AuthMode, Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Realtime.AppSettings.EnableLobbyStatistics, Photon.Realtime.LoadBalancingClient.EnableLobbyStatistics, Photon.Realtime.AppSettings.EnableProtocolFallback, Photon.Realtime.LoadBalancingClient.EnableProtocolFallback, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.AppSettings.FixedRegion, Photon.Pun.PhotonNetwork.GameVersion, Photon.Realtime.AppSettings.IsBestRegion, Photon.Realtime.AppSettings.IsDefaultNameServer, Photon.Realtime.AppSettings.IsMasterServerAddress, Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Realtime.LoadBalancingClient.NameServerHost, Photon.Realtime.LoadBalancingClient.NameServerPortInAppSettings, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Realtime.AppSettings.Port, Photon.Realtime.AppSettings.Protocol, Photon.Realtime.AppSettings.ProxyServer, Photon.Realtime.LoadBalancingClient.ProxyServerAddress, Photon.Realtime.AppSettings.Server, Photon.Pun.PhotonNetwork.ServerSettingsFileName, Photon.Realtime.AuthenticationValues.UserId.
static bool Photon.Pun.PhotonNetwork.ConnectToMaster(string masterServerAddress, int port, string appID)
Connect to a Photon Master Server by address, port, appID.
To connect to the Photon Cloud, a valid AppId must be in the settings file (shown in the Photon Cloud Dashboard). https://dashboard.photonengine.com Connecting to the Photon Cloud might fail due to: Invalid AppId Network issues Invalid region Subscription CCU limit reached etc. In general check out the DisconnectCause from the IConnectionCallbacks.OnDisconnected callback. masterServerAddress The server's address (either your own or Photon Cloud address). port The server's port to connect to. appID Your application ID (Photon Cloud provides you with a GUID for your game).
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.ConnectionHandler.AppQuits, Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.IsUsingNameServer, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Realtime.LoadBalancingClient.MasterServerAddress, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode.
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
static bool Photon.Pun.PhotonNetwork.ConnectToBestCloudServer()
Connect to the Photon Cloud region with the lowest ping (on platforms that support Unity's Ping).
Will save the result of pinging all cloud servers in PlayerPrefs. Calling this the first time can take +-2 seconds. The ping result can be overridden via PhotonNetwork.OverrideBestCloudServer(..) This call can take up to 2 seconds if it is the first time you are using this, all cloud servers will be pinged to check for the best region. The PUN Setup Wizard stores your appID in a settings file and applies a server address/port. To connect to the Photon Cloud, a valid AppId must be in the settings file (shown in the Photon Cloud Dashboard). https://dashboard.photonengine.com Connecting to the Photon Cloud might fail due to: Invalid AppId Network issues Invalid region Subscription CCU limit reached etc. In general check out the DisconnectCause from the IConnectionCallbacks.OnDisconnected callback. If this client is going to connect to cloud server based on ping. Even if true, this does not guarantee a connection but the attempt is being made.
References Photon.Realtime.ConnectionHandler.AppQuits, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectUsingSettings.
static bool Photon.Pun.PhotonNetwork.ConnectToRegion(string region)
Connects to the Photon Cloud region of choice.
It's typically enough to define the region code ("eu", "us", etc). Connecting to a specific cluster may be necessary, when regions get sharded and you support friends / invites. In all other cases, you should not define a cluster as this allows the Name Server to distribute clients as needed. A random, load balanced cluster will be selected. The Name Server has the final say to assign a cluster as available. If the requested cluster is not available another will be assigned. Once connected, check the value of CurrentCluster.
References Photon.Realtime.ConnectionHandler.AppQuits, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.Server.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings.
static void Photon.Pun.PhotonNetwork.Disconnect()
Makes this client disconnect from the photon server, a process that leaves any room and calls OnDisconnected on completion.
When you disconnect, the client will send a "disconnecting" message to the server. This speeds up leave/disconnect messages for players in the same room as you (otherwise the server would timeout this client's connection). When used in OfflineMode, the state-change and event-call OnDisconnected are immediate. Offline mode is set to false as well. Once disconnected, the client can connect again. Use ConnectUsingSettings.
References Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.Demo.Hub.ToDemoHubButton.BackToHub, Photon.Pun.Demo.Cockpit.PunCockpit.Disconnect, Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnLeftRoom.
static bool Photon.Pun.PhotonNetwork.Reconnect()
Can be used to reconnect to the master server after a disconnect.
After losing connection, you can use this to connect a client to the region Master Server again. Cache the room name you're in and use RejoinRoom(roomname) to return to a game. Common use case: Press the Lock Button on a iOS device and you get disconnected immediately.
References Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.IsUsingNameServer, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Realtime.LoadBalancingClient.MasterServerAddress, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.ReconnectToMaster.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ReConnect.
static void Photon.Pun.PhotonNetwork.NetworkStatisticsReset()
Resets the traffic stats and re-enables them.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
static string Photon.Pun.PhotonNetwork.NetworkStatisticsToString()
Only available when NetworkStatisticsEnabled was used to gather some stats.
A string with vital networking statistics.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode.
static int Photon.Pun.PhotonNetwork.GetPing()
The current roundtrip time to the photon server.
Roundtrip time (to server and back).
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
Referenced by Photon.Pun.PhotonTransformViewPositionControl.GetExtrapolatedPositionOffset.
static void Photon.Pun.PhotonNetwork.FetchServerTimestamp()
Refreshes the server timestamp (async operation, takes a roundtrip).
Can be useful if a bad connection made the timestamp unusable or imprecise.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
static void Photon.Pun.PhotonNetwork.SendAllOutgoingCommands()
Can be used to immediately send the RPCs and Instantiates just called, so they are on their way to the other players.
This could be useful if you do a RPC to load a level and then load it yourself. While loading, no RPCs are sent to others, so this would delay the "load" RPC. You can send the RPC to "others", use this method, disable the message queue (by IsMessageQueueRunning) and then load.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
static bool Photon.Pun.PhotonNetwork.CloseConnection(Player kickPlayer)
Request a client to disconnect/kick, which happens if EnableCloseConnection is set to true.
Only the master client can do this. Only the target player gets this event. That player will disconnect if EnableCloseConnection = true. kickPlayer The Player to kick.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.EnableCloseConnection, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpRaiseEvent.
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.KickOutPlayer.
static bool Photon.Pun.PhotonNetwork.SetMasterClient(Player masterClientPlayer)
Asks the server to assign another player as Master Client of your current room.
RPCs and RaiseEvent have the option to send messages only to the Master Client of a room. SetMasterClient affects which client gets those messages. This method calls an operation on the server to set a new Master Client, which takes a roundtrip. In case of success, this client and the others get the new Master Client from the server. SetMasterClient tells the server which current Master Client should be replaced with the new one. It will fail, if anything switches the Master Client moments earlier. There is no callback for this error. All clients should get the new Master Client assigned by the server anyways. See also: PhotonNetwork.MasterClient On v3 servers: The ReceiverGroup.MasterClient (usable in RPCs) is not affected by this (still points to lowest player.ID in room). Avoid using this enum value (and send to a specific player instead). If the current Master Client leaves, PUN will detect a new one by "lowest player ID". Implement OnMasterClientSwitched to get a callback in this case. The PUN-selected Master Client might assign a new one. Make sure you don't create an endless loop of Master-assigning! When selecting a custom Master Client, all clients should point to the same player, no matter who actually assigns this player. Locally the Master Client is immediately switched, while remote clients get an event. This means the game is tempoarily without Master Client like when a current Master Client leaves. When switching the Master Client manually, keep in mind that this user might leave and not do it's work, just like any Master Client. masterClientPlayer The player to become the next Master Client. False when this operation couldn't be done. Must be in a room (not in OfflineMode).
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.PhotonNetwork.InRoom, Photon.Pun.PhotonNetwork.LogLevel, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.Room.SetMasterClient.
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetAsMaster.
static bool Photon.Pun.PhotonNetwork.JoinRandomRoom()
Joins a random room that matches the filter.
Will callback: OnJoinedRoom or OnJoinRandomFailed. Used for random matchmaking. You can join any room or one with specific properties defined in opJoinRandomRoomParams. This operation fails if no rooms are fitting or available (all full, closed, in another lobby or not visible). It may also fail when actually joining the room which was found. Rooms may close, become full or empty anytime. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby
References Photon.Pun.PhotonNetwork.JoinRandomRoom.
Referenced by Photon.Pun.Demo.PunBasics.Launcher.Connect, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.Demo.Cockpit.PunCockpit.JoinRandomRoom, Photon.Pun.Demo.PunBasics.Launcher.OnConnectedToMaster, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnConnectedToMaster, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnJoinedLobby, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnJoinRandomRoomButtonClicked.
static bool Photon.Pun.PhotonNetwork.JoinRandomRoom(Hashtable expectedCustomRoomProperties, byte expectedMaxPlayers)
Joins a random room that matches the filter.
Will callback: OnJoinedRoom or OnJoinRandomFailed. Used for random matchmaking. You can join any room or one with specific properties defined in opJoinRandomRoomParams. This operation fails if no rooms are fitting or available (all full, closed, in another lobby or not visible). It may also fail when actually joining the room which was found. Rooms may close, become full or empty anytime. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby expectedCustomRoomProperties Filters for rooms that match these custom properties (string keys and values). To ignore, pass null. expectedMaxPlayers Filters for a particular maxplayer setting. Use 0 to accept any maxPlayer value. If the operation got queued and will be sent.
References Photon.Pun.PhotonNetwork.JoinRandomRoom.
static bool Photon.Pun.PhotonNetwork.JoinRandomRoom(Hashtable expectedCustomRoomProperties, byte expectedMaxPlayers, MatchmakingMode matchingType, TypedLobby typedLobby, string sqlLobbyFilter, string[] expectedUsers=null)
Joins a random room that matches the filter.
Will callback: OnJoinedRoom or OnJoinRandomFailed. Used for random matchmaking. You can join any room or one with specific properties defined in opJoinRandomRoomParams. This operation fails if no rooms are fitting or available (all full, closed, in another lobby or not visible). It may also fail when actually joining the room which was found. Rooms may close, become full or empty anytime. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby expectedCustomRoomProperties Filters for rooms that match these custom properties (string keys and values). To ignore, pass null. expectedMaxPlayers Filters for a particular maxplayer setting. Use 0 to accept any maxPlayer value. matchingType Selects one of the available matchmaking algorithms. See MatchmakingMode enum for options. typedLobby The lobby in which you want to lookup a room. Pass null, to use the default lobby. This does not join that lobby and neither sets the lobby property. sqlLobbyFilter A filter-string for SQL-typed lobbies. expectedUsers Optional list of users (by UserId) who are expected to join this game and who you want to block a slot for. If the operation got queued and will be sent.
References Photon.Realtime.LoadBalancingClient.CurrentLobby, Photon.Realtime.OpJoinRandomRoomParams.ExpectedCustomRoomProperties, Photon.Realtime.OpJoinRandomRoomParams.ExpectedMaxPlayers, Photon.Realtime.OpJoinRandomRoomParams.ExpectedUsers, Photon.Realtime.LoadBalancingClient.InLobby, Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Realtime.OpJoinRandomRoomParams.MatchingType, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpJoinRandomRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.OpJoinRandomRoomParams.SqlLobbyFilter, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.OpJoinRandomRoomParams.TypedLobby.
static bool Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom(Hashtable expectedCustomRoomProperties=null, byte expectedMaxPlayers=0, MatchmakingMode matchingType=MatchmakingMode.FillRoom, TypedLobby typedLobby=null, string sqlLobbyFilter=null, string roomName=null, RoomOptions roomOptions=null, string[] expectedUsers=null)
Attempts to join a room that matches the specified filter and creates a room if none found.
This operation is a combination of filter-based random matchmaking with the option to create a new room, if no fitting room exists. The benefit of that is that the room creation is done by the same operation and the room can be found by the very next client, looking for similar rooms. There are separate parameters for joining and creating a room. This method can only be called while connected to a Master Server. This client's State is set to ClientState.Joining immediately. Either IMatchmakingCallbacks.OnJoinedRoom or IMatchmakingCallbacks.OnCreatedRoom gets called. Should the creation on the Master Server, IMatchmakingCallbacks.OnJoinRandomFailed gets called. Should the "join" on the Game Server fail, IMatchmakingCallbacks.OnJoinRoomFailed gets called. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. If the operation will be sent (requires connection to Master Server).
References Photon.Realtime.LoadBalancingClient.CurrentLobby, Photon.Realtime.OpJoinRandomRoomParams.ExpectedCustomRoomProperties, Photon.Realtime.OpJoinRandomRoomParams.ExpectedMaxPlayers, Photon.Realtime.OpJoinRandomRoomParams.ExpectedUsers, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.LoadBalancingClient.InLobby, Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Realtime.EnterRoomParams.Lobby, Photon.Realtime.OpJoinRandomRoomParams.MatchingType, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpJoinRandomOrCreateRoom, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.OpJoinRandomRoomParams.SqlLobbyFilter, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.OpJoinRandomRoomParams.TypedLobby.
static bool Photon.Pun.PhotonNetwork.CreateRoom(string roomName, RoomOptions roomOptions=null, TypedLobby typedLobby=null, string[] expectedUsers=null)
Creates a new room.
Will callback: OnCreatedRoom and OnJoinedRoom or OnCreateRoomFailed. When successful, this calls the callbacks OnCreatedRoom and OnJoinedRoom (the latter, cause you join as first player). In all error cases, OnCreateRoomFailed gets called. Creating a room will fail if the room name is already in use or when the RoomOptions clashing with one another. Check the EnterRoomParams reference for the various room creation options. If you don't want to create a unique room-name, pass null or "" as name and the server will assign a roomName (a GUID as string). This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby roomName Unique name of the room to create. Pass null or "" to make the server generate a name. roomOptions Common options for the room like MaxPlayers, initial custom room properties and similar. See RoomOptions type.. typedLobby If null, the room is automatically created in the currently used lobby (which is "default" when you didn't join one explicitly). expectedUsers Optional list of users (by UserId) who are expected to join this game and who you want to block a slot for. If the operation got queued and will be sent.
References Photon.Realtime.LoadBalancingClient.CurrentLobby, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.LoadBalancingClient.InLobby, Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Realtime.EnterRoomParams.Lobby, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpCreateRoom, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Launcher.CreateRoom, Launcher_old.CreateRoom, Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnCreateRoomButtonClicked, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnJoinRandomFailed, Photon.Pun.Demo.PunBasics.Launcher.OnJoinRandomFailed, Photon.Pun.UtilityScripts.ConnectAndJoinRandom.OnJoinRandomFailed.
static bool Photon.Pun.PhotonNetwork.JoinOrCreateRoom(string roomName, RoomOptions roomOptions, TypedLobby typedLobby, string[] expectedUsers=null)
Joins a specific room by name and creates it on demand.
Will callback: OnJoinedRoom or OnJoinRoomFailed. Useful when players make up a room name to meet in: All involved clients call the same method and whoever is first, also creates the room. When successful, the client will enter the specified room. The client which creates the room, will callback both OnCreatedRoom and OnJoinedRoom. Clients that join an existing room will only callback OnJoinedRoom. In all error cases, OnJoinRoomFailed gets called. Joining a room will fail, if the room is full, closed or when the user already is present in the room (checked by userId). To return to a room, use OpRejoinRoom. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. If you set room properties in roomOptions, they get ignored when the room is existing already. This avoids changing the room properties by late joining players. You can define an array of expectedUsers, to block player slots in the room for these users. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby roomName Name of the room to join. Must be non null. roomOptions Options for the room, in case it does not exist yet. Else these values are ignored. typedLobby Lobby you want a new room to be listed in. Ignored if the room was existing and got joined. expectedUsers Optional list of users (by UserId) who are expected to join this game and who you want to block a slot for. If the operation got queued and will be sent.
References Photon.Realtime.LoadBalancingClient.CurrentLobby, Photon.Realtime.Player.CustomProperties, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.LoadBalancingClient.InLobby, Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Realtime.EnterRoomParams.Lobby, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpJoinOrCreateRoom, Photon.Realtime.EnterRoomParams.PlayerProperties, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
static bool Photon.Pun.PhotonNetwork.JoinRoom(string roomName, string[] expectedUsers=null)
Joins a room by name.
Will callback: OnJoinedRoom or OnJoinRoomFailed. Useful when using lobbies or when players follow friends or invite each other. When successful, the client will enter the specified room and callback via OnJoinedRoom. In all error cases, OnJoinRoomFailed gets called. Joining a room will fail if the room is full, closed, not existing or when the user already is present in the room (checked by userId). To return to a room, use OpRejoinRoom. When players invite each other and it's unclear who's first to respond, use OpJoinOrCreateRoom instead. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. More about PUN matchmaking: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby OnJoinRoomFailed OnJoinedRoom roomName Unique name of the room to join. expectedUsers Optional list of users (by UserId) who are expected to join this game and who you want to block a slot for. If the operation got queued and will be sent.
References Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpJoinRoom, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Launcher.JoinRoom, Launcher_old.joinRoom, Photon.Pun.Demo.Cockpit.PunCockpit.JoinRoom, Photon.Pun.Demo.Asteroids.RoomListEntry.Start.
static bool Photon.Pun.PhotonNetwork.RejoinRoom(string roomName)
Rejoins a room by roomName (using the userID internally to return).
Will callback: OnJoinedRoom or OnJoinRoomFailed. After losing connection, you might be able to return to a room and continue playing, if the client is reconnecting fast enough. Use Reconnect() and this method. Cache the room name you're in and use RejoinRoom(roomname) to return to a game. Note: To be able to Rejoin any room, you need to use UserIDs! You also need to set RoomOptions.PlayerTtl. Important: Instantiate() and use of RPCs is not yet supported. The ownership rules of PhotonViews prevent a seamless return to a game, if you use PhotonViews. Use Custom Properties and RaiseEvent with event caching instead. Common use case: Press the Lock Button on a iOS device and you get disconnected immediately. Rejoining room will not send any player properties. Instead client will receive up-to-date ones from server. If you want to set new player properties, do it once rejoined.
References Photon.Pun.PhotonNetwork.IsConnectedAndReady, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.OpRejoinRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinRoomFailed.
static bool Photon.Pun.PhotonNetwork.ReconnectAndRejoin()
When the client lost connection during gameplay, this method attempts to reconnect and rejoin the room.
This method re-connects directly to the game server which was hosting the room PUN was in before. If the room was shut down in the meantime, PUN will call OnJoinRoomFailed and return this client to the Master Server. Check the return value, if this client will attempt a reconnect and rejoin (if the conditions are met). If ReconnectAndRejoin returns false, you can still attempt a Reconnect and Rejoin. Similar to PhotonNetwork.RejoinRoom, this requires you to use unique IDs per player (the UserID). Rejoining room will not send any player properties. Instead client will receive up-to-date ones from server. If you want to set new player properties, do it once rejoined. False, if there is no known room or game server to return to. Then, this client does not attempt the ReconnectAndRejoin.
References Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ReconnectAndRejoin.
static bool Photon.Pun.PhotonNetwork.LeaveRoom(bool becomeInactive=true)
Leave the current room and return to the Master Server where you can join or create rooms (see remarks).
This will clean up all (network) GameObjects with a PhotonView, unless you changed autoCleanUp to false. Returns to the Master Server. In OfflineMode, the local "fake" room gets cleaned up and OnLeftRoom gets called immediately. In a room with playerTTL < 0, LeaveRoom just turns a client inactive. The player stays in the room's player list and can return later on. Setting becomeInactive to false deliberately, means to "abandon" the room, despite the playerTTL allowing you to come back. In a room with playerTTL == 0, become inactive has no effect (clients are removed from the room right away). becomeInactive If this client becomes inactive in a room with playerTTL < 0. Defaults to true.
References Photon.Realtime.LoadBalancingClient.ConnectionCallbackTargets, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.LoadBalancingClient.MatchMakingCallbackTargets, Photon.Pun.PhotonNetwork.NetworkClientState, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Realtime.ConnectionCallbacksContainer.OnConnectedToMaster, Photon.Realtime.MatchMakingCallbacksContainer.OnLeftRoom, Photon.Realtime.LoadBalancingClient.OpLeaveRoom, Photon.Realtime.Room.PlayerTtl.
Referenced by Launcher.LeaveRoom, Launcher_old.LeaveRoom, Photon.Pun.Demo.PunBasics.GameManager.LeaveRoom, Photon.Pun.Demo.Cockpit.PunCockpit.LeaveRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnLeaveGameButtonClicked.
static bool Photon.Pun.PhotonNetwork.JoinLobby()
On MasterServer this joins the default lobby which list rooms currently in use.
The room list is sent and refreshed by the server using ILobbyCallbacks.OnRoomListUpdate. Per room you should check if it's full or not before joining. Photon also lists rooms that are full, unless you close and hide them (room.open = false and room.visible = false). In best case, you make your clients join random games, as described here: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby You can show your current players and room count without joining a lobby (but you must be on the master server). Use: CountOfPlayers, CountOfPlayersOnMaster, CountOfPlayersInRooms and CountOfRooms. You can use more than one lobby to keep the room lists shorter. See JoinLobby(TypedLobby lobby). When creating new rooms, they will be "attached" to the currently used lobby or the default lobby. You can use JoinRandomRoom without being in a lobby!
References Photon.Pun.PhotonNetwork.JoinLobby.
Referenced by Photon.Pun.PhotonNetwork.JoinLobby, Photon.Pun.Demo.Cockpit.PunCockpit.JoinLobby, Launcher.OnConnectedToMaster, Launcher_old.OnConnectedToMaster, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnRoomListButtonClicked.
static bool Photon.Pun.PhotonNetwork.JoinLobby(TypedLobby typedLobby)
On a Master Server you can join a lobby to get lists of available rooms.
The room list is sent and refreshed by the server using ILobbyCallbacks.OnRoomListUpdate. Any client can "make up" any lobby on the fly. Splitting rooms into multiple lobbies will keep each list shorter. However, having too many lists might ruin the matchmaking experience. In best case, you create a limited number of lobbies. For example, create a lobby per game-mode: "koth" for king of the hill and "ffa" for free for all, etc. There is no listing of lobbies at the moment. Sql-typed lobbies offer a different filtering model for random matchmaking. This might be more suited for skillbased-games. However, you will also need to follow the conventions for naming filterable properties in sql-lobbies! Both is explained in the matchmaking doc linked below. In best case, you make your clients join random games, as described here: https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby Per room you should check if it's full or not before joining. Photon does list rooms that are full, unless you close and hide them (room.open = false and room.visible = false). You can show your games current players and room count without joining a lobby (but you must be on the master server). Use: CountOfPlayers, CountOfPlayersOnMaster, CountOfPlayersInRooms and CountOfRooms. When creating new rooms, they will be "attached" to the currently used lobby or the default lobby. You can use JoinRandomRoom without being in a lobby! typedLobby A typed lobby to join (must have name and type).
References Photon.Pun.PhotonNetwork.IsConnected, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpJoinLobby, Photon.Pun.PhotonNetwork.Server.
static bool Photon.Pun.PhotonNetwork.LeaveLobby()
Leave a lobby to stop getting updates about available rooms.
This does not reset PhotonNetwork.lobby! This allows you to join this particular lobby later easily. The values CountOfPlayers, CountOfPlayersOnMaster, CountOfPlayersInRooms and CountOfRooms are received even without being in a lobby. You can use JoinRandomRoom without being in a lobby.
References Photon.Pun.PhotonNetwork.IsConnected, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpLeaveLobby, Photon.Pun.PhotonNetwork.Server.
Referenced by Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnBackButtonClicked.
static bool Photon.Pun.PhotonNetwork.FindFriends(string[] friendsToFind)
Requests the rooms and online status for a list of friends and saves the result in PhotonNetwork.Friends.
Works only on Master Server to find the rooms played by a selected list of users. The result will be stored in PhotonNetwork.Friends when available. That list is initialized on first use of OpFindFriends (before that, it is null). To refresh the list, call FindFriends again (in 5 seconds or 10 or 20). Users identify themselves by setting a unique userId in the PhotonNetwork.AuthValues. See remarks of AuthenticationValues for info about how this is set and used. The list of friends must be fetched from some other source (not provided by Photon). Internal: The server response includes 2 arrays of info (each index matching a friend from the request): ParameterCode.FindFriendsResponseOnlineList = bool[] of online states ParameterCode.FindFriendsResponseRoomIdList = string[] of room names (empty string if not in a room) friendsToFind Array of friend (make sure to use unique NickName or AuthValues). If the operation could be sent (requires connection, only one request is allowed at any time). Always false in offline mode.
References Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpFindFriends.
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.FindFriends, Photon.Pun.Demo.Cockpit.FriendListView.OnRoomListUpdateCallBack.
static bool Photon.Pun.PhotonNetwork.GetCustomRoomList(TypedLobby typedLobby, string sqlLobbyFilter)
Fetches a custom list of games from the server, matching a (non-empty) SQL-like filter.
Triggers OnRoomListUpdate callback. Operation is only available for lobbies of type SqlLobby and the filter can not be empty. It will check those conditions and fail locally, returning false. This is an async request. Note: You don't have to join a lobby to query it. Rooms need to be "attached" to a lobby, which can be done via the typedLobby parameter in CreateRoom, JoinOrCreateRoom, etc.. When done, OnRoomListUpdate gets called. https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby/::sql_lobby_type typedLobby The lobby to query. Has to be of type SqlLobby. sqlLobbyFilter The sql query statement. If the operation could be sent (has to be connected).
References Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpGetGameList.
Referenced by Photon.Pun.Demo.Cockpit.RoomListView.GetRoomList.
static bool Photon.Pun.PhotonNetwork.SetPlayerCustomProperties(Hashtable customProperties)
Sets this (local) player's properties and synchronizes them to the other players (don't modify them directly).
While in a room, your properties are synced with the other players. CreateRoom, JoinRoom and JoinRandomRoom will all apply your player's custom properties when you enter the room. The whole Hashtable will get sent. Minimize the traffic by setting only updated key/values. If the Hashtable is null, the custom properties will be cleared. Custom properties are never cleared automatically, so they carry over to the next room, if you don't change them. Don't set properties by modifying PhotonNetwork.player.customProperties! customProperties Only string-typed keys will be used from this hashtable. If null, custom properties are all deleted. False if customProperties is empty or have zero string keys. True in offline mode. True if not in a room and this is the local player (use this to cache properties to be sent when joining a room). Otherwise, returns if this operation could be sent to the server.
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Realtime.Player.SetCustomProperties.
Referenced by Launcher.AssignRoleRandomly, ReadyCheck.OnClick_Ready, ScoreManager.SetBrokenFurnitureScore, ScoreManager.SetFixFurnitureScore, ScoreManager.SetMainScore, ScoreManager.SetTrapScore.
static void Photon.Pun.PhotonNetwork.RemovePlayerCustomProperties(string[] customPropertiesToDelete)
Locally removes Custom Properties of "this" player.
Important: This does not synchronize the change! Useful when you switch rooms. Use this method with care. It can create inconsistencies of state between players! This only changes the player.customProperties locally. This can be useful to clear your Custom Properties between games (let's say they store which turn you made, kills, etc). SetPlayerCustomProperties() syncs and can be used to set values to null while in a room. That can be considered "removed" while in a room. If customPropertiesToDelete is null or has 0 entries, all Custom Properties are deleted (replaced with a new Hashtable). If you specify keys to remove, those will be removed from the Hashtable but other keys are unaffected. customPropertiesToDelete List of Custom Property keys to remove. See remarks.
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.LocalPlayer.
static bool Photon.Pun.PhotonNetwork.RaiseEvent(byte eventCode, object eventContent, RaiseEventOptions raiseEventOptions, SendOptions sendOptions)
Sends fully customizable events in a room.
Events consist of at least an EventCode (0..199) and can have content. To receive events, implement IOnEventCallback in any class and register it via PhotonNetwork.AddCallbackTarget. See IOnEventCallback.OnEvent. The eventContent is optional. If set, eventContent must be a "serializable type", something that the client can turn into a byte[] basically. Most basic types and arrays of them are supported, including Unity's Vector2, Vector3, Quaternion. Transforms are not supported. You can turn a class into a "serializable type" by following the example in CustomTypes.cs. The RaiseEventOptions have some (less intuitive) combination rules: If you set targetActors (an array of Player.ID values), the receivers parameter gets ignored. When using event caching, the targetActors, receivers and interestGroup can't be used. Buffered events go to all. When using cachingOption removeFromRoomCache, the eventCode and content are actually not sent but used as filter. eventCode A byte identifying the type of event. You might want to use a code per action or to signal which content can be expected. Allowed: 0..199. eventContent Some serializable object like string, byte, integer, float (etc) and arrays of those. Hashtables with byte keys are good to send variable content. raiseEventOptions Allows more complex usage of events. If null, RaiseEventOptions.Default will be used (which is fine). sendOptions Send options for reliable, encryption etc.. False if event could not be sent.
References Photon.Realtime.ParameterCode.ActorNr, Photon.Realtime.ParameterCode.Data, Photon.Pun.PhotonNetwork.InRoom, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OnEvent, Photon.Realtime.LoadBalancingClient.OpRaiseEvent, Photon.Realtime.RaiseEventOptions.Receivers.
Referenced by Photon.Pun.UtilityScripts.PunTurnManager.SendMove.
static bool Photon.Pun.PhotonNetwork.AllocateViewID(PhotonView view)
Allocates a viewID for the current/local player.
True if a viewId was assigned. False if the PhotonView already had a non-zero viewID.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.AllocateViewID, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonView.ToString, Photon.Pun.PhotonView.ViewID.
Referenced by Photon.Pun.PhotonNetwork.AllocateRoomViewID, Photon.Pun.PhotonNetwork.AllocateViewID.
static bool Photon.Pun.PhotonNetwork.AllocateSceneViewID(PhotonView view)
References Photon.Pun.PhotonNetwork.AllocateRoomViewID.
static bool Photon.Pun.PhotonNetwork.AllocateRoomViewID(PhotonView view)
Enables the Master Client to allocate a viewID for room objects.
True if a viewId was assigned. False if the PhotonView already had a non-zero viewID or if this client is not the Master Client.
References Photon.Pun.PhotonNetwork.AllocateViewID, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonView.ToString, Photon.Pun.PhotonView.ViewID.
Referenced by Photon.Pun.PhotonNetwork.AllocateSceneViewID.
static int Photon.Pun.PhotonNetwork.AllocateViewID(bool roomObject)
Allocates a viewID for the current/local player or the room.
roomObject Use true, to allocate a room viewID and false to allocate a viewID for the local player. Returns a viewID (combined owner and sequential number) that can be assigned as PhotonView.ViewID.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.AllocateViewID, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer.
static int Photon.Pun.PhotonNetwork.AllocateViewID(int ownerId)
Allocates a viewID for the current/local player or the room.
ownerId ActorNumber to allocate a viewID for. Returns a viewID (combined owner and sequential number) that can be assigned as PhotonView.ViewID.
References Photon.Pun.PhotonNetwork.MAX_VIEW_IDS.
static GameObject Photon.Pun.PhotonNetwork.Instantiate(string prefabName, Vector3 position, Quaternion rotation, byte group=0, object[] data=null)
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.NetworkClientState, Photon.Pun.PhotonNetwork.ServerTimestamp.
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.SpawnObjects.
static GameObject Photon.Pun.PhotonNetwork.InstantiateSceneObject(string prefabName, Vector3 position, Quaternion rotation, byte group=0, object[] data=null)
References Photon.Pun.PhotonNetwork.InstantiateRoomObject.
static GameObject Photon.Pun.PhotonNetwork.InstantiateRoomObject(string prefabName, Vector3 position, Quaternion rotation, byte group=0, object[] data=null)
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.ServerTimestamp.
Referenced by Photon.Pun.PhotonNetwork.InstantiateSceneObject, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion, NetcodeSpawnRoomObjs.SpawnObjects, TrapMechanicButtonScript.TrapInstantiate.
static void Photon.Pun.PhotonNetwork.Destroy(PhotonView targetView)
Network-Destroy the GameObject associated with the PhotonView, unless the PhotonView is static or not under this client's control.
Destroying a networked GameObject while in a Room includes: Removal of the Instantiate call from the server's room buffer. Removing RPCs buffered for PhotonViews that got created indirectly with the PhotonNetwork.Instantiate call. Sending a message to other clients to remove the GameObject also (affected by network lag). Usually, when you leave a room, the GOs get destroyed automatically. If you have to destroy a GO while not in a room, the Destroy is only done locally. Destroying networked objects works only if they got created with PhotonNetwork.Instantiate(). Objects loaded with a scene are ignored, no matter if they have PhotonView components. The GameObject must be under this client's control: Instantiated and owned by this client. Instantiated objects of players who left the room are controlled by the Master Client. Room-owned game objects are controlled by the Master Client. GameObject can be destroyed while client is not in a room. Nothing. Check error debug log for any issues.
References Photon.Pun.PhotonNetwork.InRoom.
Referenced by Photon.Pun.UtilityScripts.OnJoinedInstantiate.DespawnObjects, FoodBehaviourScript.PhotonSyncingTaskCompletion, SInt.Netcode.PhotonPUN.PlayerManager.RespawnLocalPlayerInstance, DestroyGameObject.SelfDestroy, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion, CatTrappedScript.TrapDestroyself, Photon.Pun.Demo.Asteroids.Asteroid.Update.
static void Photon.Pun.PhotonNetwork.Destroy(GameObject targetGo)
Network-Destroy the GameObject, unless it is static or not under this client's control.
Destroying a networked GameObject includes: Removal of the Instantiate call from the server's room buffer. Removing RPCs buffered for PhotonViews that got created indirectly with the PhotonNetwork.Instantiate call. Sending a message to other clients to remove the GameObject also (affected by network lag). Usually, when you leave a room, the GOs get destroyed automatically. If you have to destroy a GO while not in a room, the Destroy is only done locally. Destroying networked objects works only if they got created with PhotonNetwork.Instantiate(). Objects loaded with a scene are ignored, no matter if they have PhotonView components. The GameObject must be under this client's control: Instantiated and owned by this client. Instantiated objects of players who left the room are controlled by the Master Client. Room-owned game objects are controlled by the Master Client. GameObject can be destroyed while client is not in a room. Nothing. Check error debug log for any issues.
References Photon.Pun.PhotonNetwork.InRoom.
static void Photon.Pun.PhotonNetwork.DestroyPlayerObjects(Player targetPlayer)
Network-Destroy all GameObjects, PhotonViews and their RPCs of targetPlayer.
Can only be called on local player (for "self") or Master Client (for anyone). Destroying a networked GameObject includes: Removal of the Instantiate call from the server's room buffer. Removing RPCs buffered for PhotonViews that got created indirectly with the PhotonNetwork.Instantiate call. Sending a message to other clients to remove the GameObject also (affected by network lag). Destroying networked objects works only if they got created with PhotonNetwork.Instantiate(). Objects loaded with a scene are ignored, no matter if they have PhotonView components. Nothing. Check error debug log for any issues.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.DestroyPlayerObjects.
Referenced by Photon.Pun.PhotonNetwork.DestroyPlayerObjects.
static void Photon.Pun.PhotonNetwork.DestroyPlayerObjects(int targetPlayerId)
Network-Destroy all GameObjects, PhotonViews and their RPCs of this player (by ID).
Can only be called on local player (for "self") or Master Client (for anyone). Destroying a networked GameObject includes: Removal of the Instantiate call from the server's room buffer. Removing RPCs buffered for PhotonViews that got created indirectly with the PhotonNetwork.Instantiate call. Sending a message to other clients to remove the GameObject also (affected by network lag). Destroying networked objects works only if they got created with PhotonNetwork.Instantiate(). Objects loaded with a scene are ignored, no matter if they have PhotonView components. Nothing. Check error debug log for any issues.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.DestroyPlayerObjects, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer.
static void Photon.Pun.PhotonNetwork.DestroyAll()
Network-Destroy all GameObjects, PhotonViews and their RPCs in the room.
Removes anything buffered from the server. Can only be called by Master Client (for anyone). Can only be called by Master Client (for anyone). Unlike the Destroy methods, this will remove anything from the server's room buffer. If your game buffers anything beyond Instantiate and RPC calls, that will be cleaned as well from server. Destroying all includes: Remove anything from the server's room buffer (Instantiate, RPCs, anything buffered). Sending a message to other clients to destroy everything locally, too (affected by network lag). Destroying networked objects works only if they got created with PhotonNetwork.Instantiate(). Objects loaded with a scene are ignored, no matter if they have PhotonView components. Nothing. Check error debug log for any issues.
References Photon.Pun.PhotonNetwork.DestroyAll, Photon.Pun.PhotonNetwork.IsMasterClient.
Referenced by Photon.Pun.PhotonNetwork.DestroyAll.
static void Photon.Pun.PhotonNetwork.RemoveRPCs(Player targetPlayer)
Remove all buffered RPCs from server that were sent by targetPlayer.
Can only be called on local player (for "self") or Master Client (for anyone). This method requires either: This is the targetPlayer's client. This client is the Master Client (can remove any Player's RPCs). If the targetPlayer calls RPCs at the same time that this is called, network lag will determine if those get buffered or cleared like the rest. targetPlayer This player's buffered RPCs get removed from server buffer.
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.Player.IsLocal, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.OpCleanActorRpcBuffer.
static void Photon.Pun.PhotonNetwork.RemoveRPCs(PhotonView targetPhotonView)
Remove all buffered RPCs from server that were sent via targetPhotonView.
The Master Client and the owner of the targetPhotonView may call this. This method requires either: The targetPhotonView is owned by this client (Instantiated by it). This client is the Master Client (can remove any PhotonView's RPCs). targetPhotonView RPCs buffered for this PhotonView get removed from server buffer.
References Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine.
static HashSet< GameObject > Photon.Pun.PhotonNetwork.FindGameObjectsWithComponent(Type type)
Finds the GameObjects with Components of a specific type (using FindObjectsOfType).
type Type must be a Component HashSet with GameObjects that have a specific type of Component.
static void Photon.Pun.PhotonNetwork.SetInterestGroups(byte group, bool enabled)
Enable/disable receiving events from a given Interest Group.
A client can tell the server which Interest Groups it's interested in. The server will only forward events for those Interest Groups to that client (saving bandwidth and performance). See: https://doc.photonengine.com/en-us/pun/v2/gameplay/interestgroups See: https://doc.photonengine.com/en-us/pun/v2/demos-and-tutorials/package-demos/culling-demo group The interest group to affect. enabled Sets if receiving from group to enabled (or not).
References Photon.Pun.PhotonNetwork.SetInterestGroups.
Referenced by Photon.Pun.PhotonNetwork.SetInterestGroups.
static void Photon.Pun.PhotonNetwork.LoadLevel(int levelNumber)
This method wraps loading a level asynchronously and pausing network messages during the process.
While loading levels in a networked game, it makes sense to not dispatch messages received by other players. LoadLevel takes care of that by setting PhotonNetwork.IsMessageQueueRunning = false until the scene loaded. To sync the loaded level in a room, set PhotonNetwork.AutomaticallySyncScene to true. The Master Client of a room will then sync the loaded level with every other player in the room. Note that this works only for a single active scene and that reloading the scene is not supported. The Master Client will actually reload a scene but other clients won't. You should make sure you don't fire RPCs before you load another scene (which doesn't contain the same GameObjects and PhotonViews). LoadLevel uses SceneManager.LoadSceneAsync(). Check the progress of the LevelLoading using PhotonNetwork.LevelLoadingProgress. Calling LoadLevel before the previous scene finished loading is not recommended. If AutomaticallySyncScene is enabled, PUN cancels the previous load (and prevent that from becoming the active scene). If AutomaticallySyncScene is off, the previous scene loading can finish. In both cases, a new scene is loaded locally. levelNumber Build-index number of the level to load. When using level numbers, make sure they are identical on all clients.
References Photon.Realtime.ConnectionHandler.AppQuits, Photon.Pun.PhotonNetwork.AutomaticallySyncScene, Photon.Pun.PhotonNetwork.IsMessageQueueRunning.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.LoadLevel, Photon.Pun.Demo.PunBasics.Launcher.OnJoinedRoom, Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnStartGameButtonClicked, Launcher.StartGame, Launcher_old.StartGame.
static void Photon.Pun.PhotonNetwork.LoadLevel(string levelName)
This method wraps loading a level asynchronously and pausing network messages during the process.
While loading levels in a networked game, it makes sense to not dispatch messages received by other players. LoadLevel takes care of that by setting PhotonNetwork.IsMessageQueueRunning = false until the scene loaded. To sync the loaded level in a room, set PhotonNetwork.AutomaticallySyncScene to true. The Master Client of a room will then sync the loaded level with every other player in the room. Note that this works only for a single active scene and that reloading the scene is not supported. The Master Client will actually reload a scene but other clients won't. You should make sure you don't fire RPCs before you load another scene (which doesn't contain the same GameObjects and PhotonViews). LoadLevel uses SceneManager.LoadSceneAsync(). Check the progress of the LevelLoading using PhotonNetwork.LevelLoadingProgress. Calling LoadLevel before the previous scene finished loading is not recommended. If AutomaticallySyncScene is enabled, PUN cancels the previous load (and prevent that from becoming the active scene). If AutomaticallySyncScene is off, the previous scene loading can finish. In both cases, a new scene is loaded locally. levelName Name of the level to load. Make sure it's available to all clients in the same room.
References Photon.Realtime.ConnectionHandler.AppQuits, Photon.Pun.PhotonNetwork.AutomaticallySyncScene, Photon.Pun.PhotonNetwork.IsMessageQueueRunning.
static bool Photon.Pun.PhotonNetwork.WebRpc(string name, object parameters, bool sendAuthCookie=false)
This operation makes Photon call your custom web-service by name (path) with the given parameters.
This is a server-side feature which must be setup in the Photon Cloud Dashboard prior to use. https://doc.photonengine.com/en-us/pun/v2/gameplay/web-extensions/webrpc The Parameters will be converted into JSon format, so make sure your parameters are compatible. See Photon.Realtime.IWebRpcCallback.OnWebRpcResponse on how to get a response. It's important to understand that the OperationResponse only tells if the WebRPC could be called. The content of the response contains any values your web-service sent and the error/success code. In case the web-service failed, an error code and a debug message are usually inside the OperationResponse. The class WebRpcResponse is a helper-class that extracts the most valuable content from the WebRPC response. Example callback implementation: public void OnWebRpcResponse(OperationResponse response) { WebRpcResponse webResponse = new WebRpcResponse(operationResponse); if (webResponse.ReturnCode != 0) { //... } switch (webResponse.Name) { //... } // and so on }
References Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpWebRpc.
Referenced by Photon.Pun.Demo.WebRpcImplementationExample.WebRpcCall.
static void Photon.Pun.PhotonNetwork.LoadOrCreateSettings(bool reload=false)
References Photon.Pun.PhotonNetwork.ServerSettingsFileName.
static void Photon.Pun.PhotonNetwork.SetPlayerCustomProperties(System.Collections.Hashtable hash)
static void Photon.Pun.PhotonNetwork.AddCallbackTarget(object target)
Registers an object for callbacks for the implemented callback-interfaces.
The covered callback interfaces are: IConnectionCallbacks, IMatchmakingCallbacks, ILobbyCallbacks, IInRoomCallbacks, IOnEventCallback and IWebRpcCallback. See: .Net Callbacks target The object that registers to get callbacks from PUN's LoadBalancingClient.
References Photon.Realtime.LoadBalancingClient.AddCallbackTarget, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipRequest, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransfered, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransferFailed.
Referenced by Photon.Pun.PhotonHandler.OnEnable, Photon.Pun.MonoBehaviourPunCallbacks.OnEnable, Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnEnable.
static void Photon.Pun.PhotonNetwork.RemoveCallbackTarget(object target)
Removes the target object from callbacks for its implemented callback-interfaces.
The covered callback interfaces are: IConnectionCallbacks, IMatchmakingCallbacks, ILobbyCallbacks, IInRoomCallbacks, IOnEventCallback and IWebRpcCallback. See: .Net Callbacks target The object that unregisters from getting callbacks.
References Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipRequest, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransfered, Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransferFailed, Photon.Realtime.LoadBalancingClient.RemoveCallbackTarget.
Referenced by Photon.Pun.PhotonHandler.OnDisable, Photon.Pun.MonoBehaviourPunCallbacks.OnDisable, Photon.Pun.UtilityScripts.OnJoinedInstantiate.OnDisable.
static void Photon.Pun.PhotonNetwork.DestroyPlayerObjects(int playerId, bool localOnly)
Destroys all Instantiates and RPCs locally and (if not localOnly) sends EvDestroy(player) and clears related events in the server buffer.
References Photon.Pun.PhotonView.ControllerActorNr, Photon.Pun.PhotonView.CreatorActorNr, Photon.Pun.PhotonNetwork.OpCleanActorRpcBuffer, Photon.Pun.PhotonView.Owner, Photon.Pun.PhotonView.OwnerActorNr.
static void Photon.Pun.PhotonNetwork.DestroyAll(bool localOnly)
References Photon.Pun.PhotonNetwork.OpRemoveCompleteCache.
static bool Photon.Pun.PhotonNetwork.LocalCleanPhotonView(PhotonView view)
References Photon.Pun.PhotonView.ViewID.
static PhotonView Photon.Pun.PhotonNetwork.GetPhotonView(int viewID)
Referenced by Photon.Pun.Simple.SyncContact.ApplySnapshot, Photon.Pun.PhotonView.Find, Photon.Pun.Simple.SyncState.GetMount, Photon.Pun.Simple.NetMaster.ReceiveMessage.
static void Photon.Pun.PhotonNetwork.RegisterPhotonView(PhotonView netView)
References Photon.Pun.PhotonNetwork.LogLevel, Photon.Pun.PhotonView.ViewID.
static void Photon.Pun.PhotonNetwork.OpCleanActorRpcBuffer(int actorNumber)
Removes the RPCs of someone else (to be used as master).
This won't clean any local caches. It just tells the server to forget a player's RPCs and instantiates. actorNumber
Referenced by Photon.Pun.PhotonNetwork.DestroyPlayerObjects, Photon.Pun.PhotonNetwork.RemoveRPCs.
static void Photon.Pun.PhotonNetwork.OpRemoveCompleteCacheOfPlayer(int actorNumber)
Instead removing RPCs or Instantiates, this removed everything cached by the actor.
actorNumber
static void Photon.Pun.PhotonNetwork.OpRemoveCompleteCache()
Referenced by Photon.Pun.PhotonNetwork.DestroyAll.
static void Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine(PhotonView view)
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonView.IsRoomView, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.OpCleanRpcBuffer, Photon.Pun.PhotonView.Owner, Photon.Pun.PhotonView.OwnerActorNr.
Referenced by Photon.Pun.PhotonNetwork.RemoveRPCs, Photon.Pun.PhotonNetwork.RemoveRPCsInGroup.
static void Photon.Pun.PhotonNetwork.OpCleanRpcBuffer(PhotonView view)
Cleans server RPCs for PhotonView (without any further checks).
References Photon.Pun.PhotonView.ViewID.
Referenced by Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine.
static void Photon.Pun.PhotonNetwork.RemoveRPCsInGroup(int group)
Remove all buffered RPCs from server that were sent in the targetGroup, if this is the Master Client or if this controls the individual PhotonView.
This method requires either: This client is the Master Client (can remove any RPCs per group). Any other client: each PhotonView is checked if it is under this client's control. Only those RPCs are removed. group Interest group that gets all RPCs removed.
References Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine, Photon.Pun.PhotonView.Group.
static bool Photon.Pun.PhotonNetwork.RemoveBufferedRPCs(int viewId=0, string methodName=null, int[] callersActorNumbers=null)
Clear buffered RPCs based on filter parameters.
viewId The viewID of the PhotonView where the RPC has been called on. We actually need its ViewID. If 0 (default) is provided, all PhotonViews/ViewIDs are considered. methodName The RPC method name, if possible we will use its hash shortcut for efficiency. If none (null or empty string) is provided all RPC method names are considered. callersActorNumbers The actor numbers of the players who called/buffered the RPC. For example if two players buffered the same RPC you can clear the buffered RPC of one and keep the other. If none (null or empty array) is provided all senders are considered. If the operation could be sent to the server.
References Photon.Realtime.RaiseEventOptions.CachingOption, Photon.Realtime.RaiseEventOptions.TargetActors.
static void Photon.Pun.PhotonNetwork.SetLevelPrefix(byte prefix)
Sets level prefix for PhotonViews instantiated later on.
Don't set it if you need only one! Important: If you don't use multiple level prefixes, simply don't set this value. The default value is optimized out of the traffic. This won't affect existing PhotonViews (they can't be changed yet for existing PhotonViews). Messages sent with a different level prefix will be received but not executed. This affects RPCs, Instantiates and synchronization. Be aware that PUN never resets this value, you'll have to do so yourself. prefix Max value is short.MaxValue = 255
static void Photon.Pun.PhotonNetwork.SetInterestGroups(byte[] disableGroups, byte[] enableGroups)
Enable/disable receiving on given Interest Groups (applied to PhotonViews).
A client can tell the server which Interest Groups it's interested in. The server will only forward events for those Interest Groups to that client (saving bandwidth and performance). See: https://doc.photonengine.com/en-us/pun/v2/gameplay/interestgroups See: https://doc.photonengine.com/en-us/pun/v2/demos-and-tutorials/package-demos/culling-demo disableGroups The interest groups to disable (or null). enableGroups The interest groups to enable (or null).
References Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Realtime.LoadBalancingClient.OpChangeGroups.
static void Photon.Pun.PhotonNetwork.SetSendingEnabled(byte group, bool enabled)
Enable/disable sending on given group (applied to PhotonViews)
This does not interact with the Photon server-side. It's just a client-side setting to suppress updates, should they be sent to one of the blocked groups. This setting is not particularly useful, as it means that updates literally never reach the server or anyone else. Use with care. group The interest group to affect. enabled Sets if sending to group is enabled (or not).
static void Photon.Pun.PhotonNetwork.SetSendingEnabled(byte[] disableGroups, byte[] enableGroups)
Enable/disable sending on given groups (applied to PhotonViews)
This does not interact with the Photon server-side. It's just a client-side setting to suppress updates, should they be sent to one of the blocked groups. This setting is not particularly useful, as it means that updates literally never reach the server or anyone else. Use with care. enableGroups The interest groups to enable sending on (or null). disableGroups The interest groups to disable sending on (or null).
static bool Photon.Pun.PhotonNetwork.SendInstantiate(Pun.InstantiateParameters parameters, bool roomObject=false)
static void Photon.Pun.PhotonNetwork.RPC(PhotonView view, string methodName, RpcTarget target, bool encrypt, params object[] parameters)
Internal to send an RPC on given PhotonView.
Do not call this directly but use: PhotonView.RPC!
static void Photon.Pun.PhotonNetwork.RPC(PhotonView view, string methodName, Player targetPlayer, bool encrypt, params object[] parameters)
Internal to send an RPC on given PhotonView.
Do not call this directly but use: PhotonView.RPC!
static string Photon.Pun.PhotonNetwork.CallbacksToString()
static void Photon.Pun.PhotonNetwork.LocalCleanupAnythingInstantiated(bool destroyInstantiatedGameObjects)
Cleans up anything that was instantiated in-game (not loaded with the scene).
Resets views that are not destroyed.
static void Photon.Pun.PhotonNetwork.ExecuteRpc(Hashtable rpcData, Player sender)
Executes a received RPC event
static void Photon.Pun.PhotonNetwork.RemoveInstantiatedGO(GameObject go, bool localOnly)
Removes GameObject and the PhotonViews on it from local lists and optionally updates remotes.
GameObject gets destroyed at end. This method might fail and quit early due to several tests. go GameObject to cleanup. localOnly For localOnly, tests of control are skipped and the server is not updated.
static void Photon.Pun.PhotonNetwork.RequestOwnership(int viewID, int fromOwner)
static void Photon.Pun.PhotonNetwork.TransferOwnership(int viewID, int playerID)
static void Photon.Pun.PhotonNetwork.OwnershipUpdate(int[] viewOwnerPairs, int targetActor=-1)
Call this on the Master to reassert ownership on clients.
viewOwnerPairs are [viewId][viewOwnerActorNr] pairs. targetActor of -1 indicates send to all others.
static void Photon.Pun.PhotonNetwork.RPC(PhotonView view, string methodName, RpcTarget target, Player player, bool encrypt, params object[] parameters)
static void Photon.Pun.PhotonNetwork.NewSceneLoaded()
static void Photon.Pun.PhotonNetwork.RunViewUpdate()
Calls all locally controlled PhotonViews to write their updates in OnPhotonSerializeView. Called by a PhotonHandler.
static bool Photon.Pun.PhotonNetwork.GetMethod(MonoBehaviour monob, string methodType, out MethodInfo mi)
static void Photon.Pun.PhotonNetwork.LoadLevelIfSynced()
Internally used to detect the current scene and load it if PhotonNetwork.AutomaticallySyncScene is enabled.
static void Photon.Pun.PhotonNetwork.SetLevelInPropsIfSynced(object levelId)