Photon::Compression::PrimitiveSerializeExt
const string Photon.Compression.PrimitiveSerializeExt.overrunerror
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ByteConverter value, ref ulong buffer, ref int bitposition, int bits)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
Referenced by Photon.Compression.PrimitiveSerializeExt.Inject.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ByteConverter value, ref uint buffer, ref int bitposition, int bits)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ByteConverter value, ref ushort buffer, ref int bitposition, int bits)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ByteConverter value, ref byte buffer, ref int bitposition, int bits)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
static ulong Photon.Compression.PrimitiveSerializeExt.WriteSigned(this ulong buffer, int value, ref int bitposition, int bits)
Write a signed value into a buffer using zigzag.
Returns the modified buffer with the injected value.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this long value, ref ulong buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this int value, ref ulong buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this short value, ref ulong buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this sbyte value, ref ulong buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static int Photon.Compression.PrimitiveSerializeExt.ReadSigned(this ulong buffer, ref int bitposition, int bits)
Read a previously injected signed int back out of a buffer.
Returns the restored signed value.
static uint Photon.Compression.PrimitiveSerializeExt.WriteSigned(this uint buffer, int value, ref int bitposition, int bits)
Write a signed value into a buffer using zigzag.
Returns the modified buffer with the injected value.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this long value, ref uint buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this int value, ref uint buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this short value, ref uint buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this sbyte value, ref uint buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static int Photon.Compression.PrimitiveSerializeExt.ReadSigned(this uint buffer, ref int bitposition, int bits)
Read a previously injected signed int back out of a buffer.
Returns the restored signed value.
static ushort Photon.Compression.PrimitiveSerializeExt.WriteSigned(this ushort buffer, int value, ref int bitposition, int bits)
Write a signed value into a buffer using zigzag.
Returns the modified buffer with the injected value.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this long value, ref ushort buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this int value, ref ushort buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this short value, ref ushort buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this sbyte value, ref ushort buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static int Photon.Compression.PrimitiveSerializeExt.ReadSigned(this ushort buffer, ref int bitposition, int bits)
Read a previously injected signed int back out of a buffer.
Returns the restored signed value.
static byte Photon.Compression.PrimitiveSerializeExt.WriteSigned(this byte buffer, int value, ref int bitposition, int bits)
Write a signed value into a buffer using zigzag.
Returns the modified buffer with the injected value.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this long value, ref byte buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this int value, ref byte buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this short value, ref byte buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static void Photon.Compression.PrimitiveSerializeExt.InjectSigned(this sbyte value, ref byte buffer, ref int bitposition, int bits)
Inject (write) a signed value into a buffer using zigzag.
The buffer reference is modified.
static int Photon.Compression.PrimitiveSerializeExt.ReadSigned(this byte buffer, ref int bitposition, int bits)
Read a previously injected signed int back out of a buffer.
Returns the restored signed value.
static ulong Photon.Compression.PrimitiveSerializeExt.WritetBool(this ulong buffer, bool value, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Write.
static uint Photon.Compression.PrimitiveSerializeExt.WritetBool(this uint buffer, bool value, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Write.
static ushort Photon.Compression.PrimitiveSerializeExt.WritetBool(this ushort buffer, bool value, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Write.
static byte Photon.Compression.PrimitiveSerializeExt.WritetBool(this byte buffer, bool value, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this bool value, ref ulong buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Inject.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this bool value, ref uint buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Inject.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this bool value, ref ushort buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Inject.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this bool value, ref byte buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Inject.
static bool Photon.Compression.PrimitiveSerializeExt.ReadBool(this ulong buffer, ref int bitposition)
static bool Photon.Compression.PrimitiveSerializeExt.ReadtBool(this uint buffer, ref int bitposition)
static bool Photon.Compression.PrimitiveSerializeExt.ReadBool(this ushort buffer, ref int bitposition)
static bool Photon.Compression.PrimitiveSerializeExt.ReadBool(this byte buffer, ref int bitposition)
static ulong Photon.Compression.PrimitiveSerializeExt.Write(this ulong buffer, ulong value, ref int bitposition, int bits=64)
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition.
WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer. Returns the modified buffer.
Referenced by Photon.Compression.PrimitiveSerializeExt.Inject, Photon.Compression.PrimitiveSerializeExt.InjectAsHalfFloat, Photon.Compression.PrimitiveSerializeExt.InjectUnsigned, Photon.Compression.PrimitiveSerializeExt.WritetBool.
static uint Photon.Compression.PrimitiveSerializeExt.Write(this uint buffer, ulong value, ref int bitposition, int bits=64)
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition.
WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer. Returns the modified buffer.
static ushort Photon.Compression.PrimitiveSerializeExt.Write(this ushort buffer, ulong value, ref int bitposition, int bits=64)
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition.
WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer. Returns the modified buffer.
static byte Photon.Compression.PrimitiveSerializeExt.Write(this byte buffer, ulong value, ref int bitposition, int bits=64)
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition.
WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer. Returns the modified buffer.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref ulong buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref ulong buffer, int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref ulong buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref ulong buffer, int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref ulong buffer, ref int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref ulong buffer, int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref ulong buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref ulong buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this long value, ref ulong buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this int value, ref ulong buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this short value, ref ulong buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this sbyte value, ref ulong buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref uint buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref uint buffer, int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref uint buffer, ref int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref uint buffer, int bitposition, int bits=32)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref uint buffer, ref int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref uint buffer, int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref uint buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref uint buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this long value, ref uint buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this int value, ref uint buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this short value, ref uint buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.InjectUnsigned(this sbyte value, ref uint buffer, ref int bitposition, int bits=64)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
Negative numbers will not serialize properly. Use InjectUnsigned for signed values. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref ushort buffer, ref int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref ushort buffer, int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref ushort buffer, ref int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref ushort buffer, int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref ushort buffer, ref int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref ushort buffer, int bitposition, int bits=16)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref ushort buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref ushort buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref byte buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref byte buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref byte buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this uint value, ref byte buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref byte buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ushort value, ref byte buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref byte buffer, ref int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this byte value, ref byte buffer, int bitposition, int bits=8)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Write position. Writing will begin at this position in the buffer. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Write.
static ulong Photon.Compression.PrimitiveSerializeExt.Extract(this ulong value, int bits, ref int bitposition)
Extract (read/deserialize) a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value.
value Source primitive buffer to read from. bits Number of lower order bits to copy from source to return value. bitposition Auto-incremented reference to the value read bit pointer. Extraction starts at this point in value. Downcast this ulong return value to the desired type.
References Photon.Compression.PrimitiveSerializeExt.Extract.
Referenced by Photon.Compression.PrimitiveSerializeExt.Extract, Photon.Compression.PrimitiveSerializeExt.ExtractFloat, Photon.Compression.PrimitiveSerializeExt.ExtractHalfFloat.
static ulong Photon.Compression.PrimitiveSerializeExt.Read(this ulong value, ref int bitposition, int bits)
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value.
value Source primitive buffer to read from. bits Number of lower order bits to copy from source to return value. bitposition Auto-incremented reference to the value read bit pointer. Read starts at this point in value. Downcast this ulong return value to the desired type.
Referenced by Photon.Compression.PrimitiveSerializeExt.ReadFloat, Photon.Compression.PrimitiveSerializeExt.ReadHalfFloat.
static ulong Photon.Compression.PrimitiveSerializeExt.Extract(this ulong value, ref int bitposition, int bits)
static ulong Photon.Compression.PrimitiveSerializeExt.Extract(this ulong value, int bits)
Extract and return bits from value.
value Source primitive. bits How many lower order bits to read. Cast the return value to the desired type.
static uint Photon.Compression.PrimitiveSerializeExt.Read(this uint value, ref int bitposition, int bits)
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value.
value Source primitive buffer to read from. bits Number of lower order bits to copy from source to return value. bitposition Auto-incremented reference to the value read bit pointer. Read starts at this point in value. Cast this uint return value to the desired type.
static uint Photon.Compression.PrimitiveSerializeExt.Extract(this uint value, ref int bitposition, int bits)
static uint Photon.Compression.PrimitiveSerializeExt.Extract(this uint value, int bits)
Extract and return bits from value.
value Source primitive. bits How many lower order bits to read. Cast the return value to the desired type.
static uint Photon.Compression.PrimitiveSerializeExt.Read(this ushort value, ref int bitposition, int bits)
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value.
value Source primitive buffer to read from. bits Number of lower order bits to copy from source to return value. bitposition Auto-incremented reference to the value read bit pointer. Read starts at this point in value. Cast this ushort return value to the desired type.
static uint Photon.Compression.PrimitiveSerializeExt.Extract(this ushort value, ref int bitposition, int bits)
static uint Photon.Compression.PrimitiveSerializeExt.Read(this byte value, ref int bitposition, int bits)
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value.
value Source primitive buffer to read from. bits Number of lower order bits to copy from source to return value. bitposition Auto-incremented reference to the value read bit pointer. Read starts at this point in value. Downcast this uint return value to the desired type.
static uint Photon.Compression.PrimitiveSerializeExt.Extract(this byte value, ref int bitposition, int bits)
static byte Photon.Compression.PrimitiveSerializeExt.Extract(this byte value, int bits)
Extract and return bits from value.
value Source primitive. bits How many lower order bits to read. Cast the return value to the desired type.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this float f, ref ulong buffer, ref int bitposition)
Inject (serialize/write) a float into a primitive buffer at the bitposition.
No compression occurs, this is a full 32bit write. f Float to compress and write. buffer Target buffer for write. bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Write.
static float Photon.Compression.PrimitiveSerializeExt.ReadFloat(this ulong buffer, ref int bitposition)
REad a float from a bitpacked primitive(value) starting at bitposition.
buffer bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Read.
static float Photon.Compression.PrimitiveSerializeExt.ExtractFloat(this ulong buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Extract.
static ushort Photon.Compression.PrimitiveSerializeExt.InjectAsHalfFloat(this float f, ref ulong buffer, ref int bitposition)
Inject (serialize/write) a compressed float into a primitive buffer at the bitposition.
f Float to compress and write. buffer Target buffer for write. bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Write.
static ushort Photon.Compression.PrimitiveSerializeExt.InjectAsHalfFloat(this float f, ref uint buffer, ref int bitposition)
Inject (serialize/write) a compressed float into a primitive buffer at the bitposition.
f Float to compress and write. buffer Target buffer for write. bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Write.
static float Photon.Compression.PrimitiveSerializeExt.ReadHalfFloat(this ulong buffer, ref int bitposition)
Read a float from a bitpacked primitive(value) starting at bitposition.
buffer Source buffer to read from. bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Read.
static float Photon.Compression.PrimitiveSerializeExt.ExtractHalfFloat(this ulong buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Extract.
static float Photon.Compression.PrimitiveSerializeExt.ReadHalfFloat(this uint buffer, ref int bitposition)
Read a float from a bitpacked primitive(value) starting at bitposition.
buffer Source buffer to read from. bitposition Auto-incremented read position for the buffer (in bits)
References Photon.Compression.PrimitiveSerializeExt.Read.
static float Photon.Compression.PrimitiveSerializeExt.ExtractHalfFloat(this uint buffer, ref int bitposition)
References Photon.Compression.PrimitiveSerializeExt.Extract.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref uint buffer, int bits, ref int bitposition)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Inject.
static void Photon.Compression.PrimitiveSerializeExt.Inject(this ulong value, ref ulong buffer, int bits, ref int bitposition)
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition.
value Value to write. buffer Target of write. bitposition Auto-incremented write position. Writing will begin at this position in the buffer, and this value will have bits added to it. bits Number of lower order bits to copy from source to target buffer.
References Photon.Compression.PrimitiveSerializeExt.Inject.