Photon::Pun::Simple::ContactProjectile
IProjectileCannon Photon.Pun.Simple.ContactProjectile.owner
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
RespondTo Photon.Pun.Simple.ContactProjectile.terminateOn
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
RespondTo Photon.Pun.Simple.ContactProjectile.damageOn
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
Rigidbody Photon.Pun.Simple.ContactProjectile.rb
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize, Photon.Pun.Simple.ContactProjectile.LagCompensate.
Rigidbody2D Photon.Pun.Simple.ContactProjectile.rb2d
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize, Photon.Pun.Simple.ContactProjectile.LagCompensate, Photon.Pun.Simple.ContactProjectile.SimulateTime.
bool Photon.Pun.Simple.ContactProjectile._hasRigidBody
bool Photon.Pun.Simple.ContactProjectile.needsSnapshot
IContactTrigger Photon.Pun.Simple.ContactProjectile.localContactTrigger
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
bool Photon.Pun.Simple.ContactProjectile.useRbForces
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize, Photon.Pun.Simple.ContactProjectile.OnPreSimulate, Photon.Pun.Simple.ContactProjectile.OnPreUpdate.
bool Photon.Pun.Simple.ContactProjectile.useRb2dForces
Referenced by Photon.Pun.Simple.ContactProjectile.OnPreSimulate, Photon.Pun.Simple.ContactProjectile.OnPreUpdate, Photon.Pun.Simple.ContactProjectile.SimulateTime.
bool Photon.Pun.Simple.ContactProjectile.useRBGravity
IProjectileCannon Photon.Pun.Simple.ContactProjectile.Owner
bool Photon.Pun.Simple.ContactProjectile.HasRigidbody
VitalNameType Photon.Pun.Simple.ContactProjectile.VitalNameType
Vector3 Photon.Pun.Simple.ContactProjectile.velocity
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize, Photon.Pun.Simple.ContactProjectile.LagCompensate, Photon.Pun.Simple.ContactProjectile.SimulateTime.
int Photon.Pun.Simple.ContactProjectile.frameId
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
int Photon.Pun.Simple.ContactProjectile.subFrameId
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
List<IOnNetworkHit> Photon.Pun.Simple.ContactProjectile.onHit
Hit callbacks.
List<IOnTerminate> Photon.Pun.Simple.ContactProjectile.onTerminate
Referenced by Photon.Pun.Simple.ContactProjectile.Terminate.
Vector3 Photon.Pun.Simple.ContactProjectile.snapPos
Vector3 Photon.Pun.Simple.ContactProjectile.targPos
Quaternion Photon.Pun.Simple.ContactProjectile.snapRot
Quaternion Photon.Pun.Simple.ContactProjectile.targRot
List<NetObject> Photon.Pun.Simple.ContactProjectile.reusableNetObjects
void Photon.Pun.Simple.ContactProjectile.Reset()
void Photon.Pun.Simple.ContactProjectile.Awake()
void Photon.Pun.Simple.ContactProjectile.OnDestroy()
virtual void Photon.Pun.Simple.ContactProjectile.LagCompensate(float timeshift)
Override this method to implement more advanced initial lag compensated snap and velocity values.
Advance the position/rotation of the projectile here, and set the velocity to a value it should be at AFTER the timeshift is applied, so that it accounts for gravity and drag. timeshift
References Photon.Pun.Simple.ContactProjectile.rb, Photon.Pun.Simple.ContactProjectile.rb2d, Photon.Pun.Simple.ContactProjectile.velocity.
Referenced by Photon.Pun.Simple.ContactProjectile.Initialize.
void Photon.Pun.Simple.ContactProjectile.Initialize(IProjectileCannon owner, int frameId, int subFrameId, Vector3 localVelocity, RespondTo terminateOn, RespondTo damageOn, float timeshift=0)
References Photon.Pun.Simple.IProjectileCannon.ContactTrigger, Photon.Pun.Simple.ContactProjectile.damageOn, Photon.Pun.Simple.ContactProjectile.frameId, Photon.Pun.Simple.ContactProjectile.LagCompensate, Photon.Pun.Simple.ContactProjectile.localContactTrigger, Photon.Pun.Simple.ContactProjectile.owner, Photon.Pun.Simple.IContactTrigger.Proxy, Photon.Pun.Simple.ContactProjectile.rb, Photon.Pun.Simple.ContactProjectile.rb2d, Photon.Pun.Simple.ContactProjectile.subFrameId, Photon.Pun.Simple.ContactProjectile.terminateOn, Photon.Pun.Simple.ContactProjectile.useRbForces, Photon.Pun.Simple.ContactProjectile.velocity.
void Photon.Pun.Simple.ContactProjectile.OnPreSimulate(int frameId, int subFrameId)
Pre-Fixed.
References Photon.Pun.Simple.ContactProjectile.SimulateTime, Photon.Pun.Simple.ContactProjectile.useRb2dForces, Photon.Pun.Simple.ContactProjectile.useRbForces.
virtual void Photon.Pun.Simple.ContactProjectile.SimulateTime(float t)
References Photon.Pun.Simple.ContactProjectile.Interpolate, Photon.Pun.Simple.ContactProjectile.rb2d, Photon.Pun.Simple.ContactProjectile.useRb2dForces, Photon.Pun.Simple.ContactProjectile.velocity.
Referenced by Photon.Pun.Simple.ContactProjectile.OnPreSimulate.
virtual void Photon.Pun.Simple.ContactProjectile.OnPreUpdate()
Interpolation.
References Photon.Pun.Simple.ContactProjectile.Interpolate, Photon.Pun.Simple.NetMaster.NormTimeSinceFixed, Photon.Pun.Simple.ContactProjectile.useRb2dForces, Photon.Pun.Simple.ContactProjectile.useRbForces.
void Photon.Pun.Simple.ContactProjectile.Interpolate(float t)
Referenced by Photon.Pun.Simple.ContactProjectile.OnPreUpdate, Photon.Pun.Simple.ContactProjectile.SimulateTime.
virtual void Photon.Pun.Simple.ContactProjectile.Terminate()
Override this and extend the base with your own projectile termination code, or place a component on this GameObject with IOnTerminate to define a response.
References Photon.Pun.Simple.ContactProjectile.onTerminate.