Photon::Compression::CompressedElementExt
System.UInt32 [] Photon.Compression.CompressedElementExt.reusableInts
Referenced by Photon.Compression.CompressedElementExt.GetChangeAmount.
static StringBuilder Photon.Compression.CompressedElementExt.AppendSB(this StringBuilder strb, CompressedElement ce)
References Photon.Compression.CompressedElement.cQuat, Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cUniform, Photon.Compression.CompressedQuat.cvalue, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz.
static void Photon.Compression.CompressedElementExt.GetChangeAmount(uint[] results, CompressedElement a, CompressedElement b)
static uint[] Photon.Compression.CompressedElementExt.GetChangeAmount(CompressedElement a, CompressedElement b)
References Photon.Compression.CompressedElementExt.reusableInts.
static void Photon.Compression.CompressedElementExt.GuessUpperBits(this CompressedElement newcpos, ElementCrusher ec, CompressedElement oldcpos, BitCullingLevel bcl)
Alternative to OverwriteUpperBits that attempts to guess the upperbits by seeing if each axis of the new position would be closer to the old one if the upper bit is incremented by one, two, three etc.
Stops trying when it fails to get a better result. oldcpos Last best position test against. Returns a corrected CompressPos
References Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
static CompressedElement Photon.Compression.CompressedElementExt.GuessUpperBits(this CompressedElement newcpos, CompressedElement oldcpos, ElementCrusher ec, BitCullingLevel bcl)
References Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
static void Photon.Compression.CompressedElementExt.OverwriteUpperBits(this CompressedElement low, CompressedElement uppers, BitCullingLevel bcl)
Replace the upperbits of the first compressed element with the upper bits of the second, using BitCullingLevel as the separation point.
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.CompressedElementExt.OverwriteUpperBits.
static CompressedElement Photon.Compression.CompressedElementExt.OverwriteUpperBits(this CompressedElement low, CompressedElement up, ElementCrusher ec, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElementExt.OverwriteUpperBits.
static void Photon.Compression.CompressedElementExt.ZeroLowerBits(this CompressedElement fullpos, CompressedElement target, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.CompressedElementExt.ZeroLowerBits.
static CompressedElement Photon.Compression.CompressedElementExt.ZeroLowerBits(this CompressedElement fullpos, ElementCrusher ec, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElementExt.ZeroLowerBits.
static void Photon.Compression.CompressedElementExt.ZeroUpperBits(this CompressedElement fullpos, CompressedElement target, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.crusher, Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElement.Set, Photon.Compression.ElementCrusher.XCrusher, Photon.Compression.ElementCrusher.YCrusher, Photon.Compression.ElementCrusher.ZCrusher.
Referenced by Photon.Compression.CompressedElementExt.ZeroUpperBits.
static CompressedElement Photon.Compression.CompressedElementExt.ZeroUpperBits(this CompressedElement fullpos, ElementCrusher ec, BitCullingLevel bcl)
References Photon.Compression.CompressedElement.cx, Photon.Compression.CompressedElement.cy, Photon.Compression.CompressedElement.cz, Photon.Compression.CompressedElementExt.ZeroUpperBits.