Photon::Pun::UtilityScripts::PlayerNumbering
PlayerNumbering Photon.Pun.UtilityScripts.PlayerNumbering.instance
The instance.
EntryPoint to query about Room Indexing.
Referenced by Photon.Pun.UtilityScripts.PlayerNumbering.Awake.
Player [] Photon.Pun.UtilityScripts.PlayerNumbering.SortedPlayers
Referenced by Photon.Pun.UtilityScripts.PlayerNumberingInspector.OnInspectorGUI, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
const string Photon.Pun.UtilityScripts.PlayerNumbering.RoomPlayerIndexedProp
Defines the room custom property name to use for room player indexing tracking.
Referenced by Photon.Pun.UtilityScripts.PlayerNumberingExtensions.GetPlayerNumber, Photon.Pun.UtilityScripts.PlayerNumbering.OnLeftRoom, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerPropertiesUpdate, Photon.Pun.UtilityScripts.PlayerNumberingExtensions.SetPlayerNumber.
PlayerNumberingChanged Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerNumberingChanged
Called everytime the room Indexing was updated.
Use this for discrete updates. Always better than brute force calls every frame.
Referenced by Photon.Pun.Demo.Asteroids.PlayerListEntry.OnDisable, Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnDisable, Photon.Pun.Demo.Asteroids.PlayerListEntry.OnEnable, Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnEnable, Photon.Pun.UtilityScripts.PlayerNumberingInspector.OnInspectorGUI, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
bool Photon.Pun.UtilityScripts.PlayerNumbering.dontDestroyOnLoad
dont destroy on load flag for this Component's GameObject to survive Level Loading.
Referenced by Photon.Pun.UtilityScripts.PlayerNumbering.Awake.
delegate void Photon.Pun.UtilityScripts.PlayerNumbering.PlayerNumberingChanged()
OnPlayerNumberingChanged delegate.
Use
void Photon.Pun.UtilityScripts.PlayerNumbering.Awake()
References Photon.Pun.UtilityScripts.PlayerNumbering.dontDestroyOnLoad, Photon.Pun.UtilityScripts.PlayerNumbering.instance, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
override void Photon.Pun.UtilityScripts.PlayerNumbering.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
override void Photon.Pun.UtilityScripts.PlayerNumbering.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
References Photon.Realtime.Player.CustomProperties, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.UtilityScripts.PlayerNumbering.RoomPlayerIndexedProp.
override void Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
References Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
override void Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
References Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData.
override void Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerPropertiesUpdate(Player targetPlayer, Hashtable changedProps)
Called when custom player-properties are changed.
Player and the changed properties are passed as object[]. Changing properties must be done by Player.SetCustomProperties, which causes this callback locally, too. targetPlayer Contains Player that changed. changedProps Contains the properties that changed.
References Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, Photon.Pun.UtilityScripts.PlayerNumbering.RoomPlayerIndexedProp.
void Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData()
Internal call Refresh the cached data and call the OnPlayerNumberingChanged delegate.
References Photon.Realtime.Player.ActorNumber, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Player.IsLocal, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerNumberingChanged, Photon.Realtime.Room.PlayerCount, Photon.Pun.PhotonNetwork.PlayerList, Photon.Realtime.Room.Players, Photon.Pun.UtilityScripts.PlayerNumbering.SortedPlayers.
Referenced by Photon.Pun.UtilityScripts.PlayerNumbering.Awake, Photon.Pun.UtilityScripts.PlayerNumbering.OnJoinedRoom, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerEnteredRoom, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerLeftRoom, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerPropertiesUpdate.