TutoManager
List<Tutorial> TutoManager.tutorials
Referenced by TutoSequence.
Text TutoManager.dialogue
Referenced by NextTutorial, TutoComplete.
string TutoManager.endTutorialMessage
Referenced by TutoComplete.
TutoManager TutoManager.tuto
Tutorial TutoManager.current
TutoManager TutoManager.instance
Referenced by MouseClickTuto.CheckIfHappening, RemoveBGIntro.CheckIfHappening, RemoveRestrict.CheckIfHappening, SweepChoreTuto.CheckIfHappening, SwitchingPlayers.CheckIfHappening, TransitionToLobby.CheckIfHappening, HoldButtonTuto.HoldButtonTutorial, TriggerAreaTuto.OnTriggerEnter.
void TutoManager.Start()
void TutoManager.Update()
Tutorial TutoManager.TutoSequence(int order)
References tutorials.
Referenced by NextTutorial.
void TutoManager.NextTutorial(int onSequence)
References dialogue, TutoComplete, Tutorial.tutoDialogue, TutoSequence.
Referenced by EndTuto.
void TutoManager.TutoComplete()
References dialogue, endTutorialMessage.
Referenced by NextTutorial.
void TutoManager.EndTuto()
References NextTutorial, Tutorial.sequence.
Referenced by MouseClickTuto.CheckIfHappening, RemoveBGIntro.CheckIfHappening, RemoveRestrict.CheckIfHappening, SweepChoreTuto.CheckIfHappening, SwitchingPlayers.CheckIfHappening, TransitionToLobby.CheckIfHappening, HoldButtonTuto.HoldButtonTutorial, TriggerAreaTuto.OnTriggerEnter.