SInt::QuickTask::Gamekit3D::KitHelpers::GameCommands::GameCommandHandler
GameCommandType SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.interactionType
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.Awake.
bool SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.isOneShot
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.OnInteraction.
float SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.coolDown
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.OnInteraction.
float SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.startDelay
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.OnInteraction.
bool SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.isTriggered
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.OnInteraction, SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameplayCounter.PerformInteraction.
float SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.startTime
abstract void SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.PerformInteraction()
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameplayCounter.PerformInteraction.
virtual void SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.OnInteraction()
References SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.coolDown, SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.isOneShot, SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.isTriggered, SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.startDelay.
Referenced by SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandReceiver.Register, SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandReceiver.Remove.
void SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.ExecuteInteraction()
virtual void SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.Awake()
References SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler.interactionType.