Photon::Pun::Simple::VitalDefinition
List<IOnVitalValueChange> Photon.Pun.Simple.VitalDefinition.iOnVitalChange
Referenced by Photon.Pun.Simple.VitalDefinition.AddIOnVitalChange, Photon.Pun.Simple.VitalDefinition.RemoveIOnVitalChange.
double Photon.Pun.Simple.VitalDefinition.startValue
Referenced by Photon.Pun.Simple.VitalDefinition.GetDefaultData, Photon.Pun.Simple.VitalDefinition.VitalDefinition.
VitalNameType Photon.Pun.Simple.VitalDefinition.vitalName
double Photon.Pun.Simple.VitalDefinition._fullValue
uint Photon.Pun.Simple.VitalDefinition._maxValue
float Photon.Pun.Simple.VitalDefinition.regenDelay
double Photon.Pun.Simple.VitalDefinition.regenRate
float Photon.Pun.Simple.VitalDefinition.decayDelay
double Photon.Pun.Simple.VitalDefinition.decayRate
double Photon.Pun.Simple.VitalDefinition.absorption
int Photon.Pun.Simple.VitalDefinition._decayDelayInTicks
int Photon.Pun.Simple.VitalDefinition._regenDelayInTicks
double Photon.Pun.Simple.VitalDefinition._decayPerTick
double Photon.Pun.Simple.VitalDefinition._regenPerTick
int Photon.Pun.Simple.VitalDefinition.bitsForValue
int Photon.Pun.Simple.VitalDefinition.bitsForDecayDelay
int Photon.Pun.Simple.VitalDefinition.bitsForRegenDelay
VitalNameType Photon.Pun.Simple.VitalDefinition.VitalName
Referenced by Photon.Pun.Simple.Vitals.Initialize.
double Photon.Pun.Simple.VitalDefinition.FullValue
Referenced by Photon.Pun.Simple.Vital.ApplyChange, Photon.Pun.Simple.Vital.ApplyCharges, Photon.Pun.Simple.VitalDefinition.Extrapolate, Photon.Pun.Simple.Vital.IsFull, Photon.Pun.Simple.Vital.Simulate.
double Photon.Pun.Simple.VitalDefinition.MaxValue
Referenced by Photon.Pun.Simple.Vital.ApplyChange, Photon.Pun.Simple.Vital.IsFull, Photon.Pun.Simple.Vital.TestApplyChange.
double Photon.Pun.Simple.VitalDefinition.Absorbtion
Referenced by Photon.Pun.Simple.Vital.ApplyCharges.
int Photon.Pun.Simple.VitalDefinition.DecayDelayInTicks
Referenced by Photon.Pun.Simple.Vital.DisruptDecay.
int Photon.Pun.Simple.VitalDefinition.RegenDelayInTicks
Referenced by Photon.Pun.Simple.Vital.DisruptRegen.
double Photon.Pun.Simple.VitalDefinition.DecayPerTick
Referenced by Photon.Pun.Simple.Vital.Simulate.
double Photon.Pun.Simple.VitalDefinition.RegenPerTick
Referenced by Photon.Pun.Simple.Vital.Simulate.
void Photon.Pun.Simple.VitalDefinition.AddIOnVitalChange(IOnVitalValueChange cb)
References Photon.Pun.Simple.VitalDefinition.iOnVitalChange.
void Photon.Pun.Simple.VitalDefinition.RemoveIOnVitalChange(IOnVitalValueChange cb)
References Photon.Pun.Simple.VitalDefinition.iOnVitalChange.
Photon.Pun.Simple.VitalDefinition.VitalDefinition(double fullValue, uint maxValue, double startValue, double absorbtion, float regenDelay, double regenRate, float decayDelay, double decayRate, string name)
References Photon.Pun.Simple.VitalDefinition.startValue.
void Photon.Pun.Simple.VitalDefinition.Initialize(float tickDuration)
References Photon.Pun.Simple.VitalDefinition.SetTickInterval.
Referenced by Photon.Pun.Simple.Vital.Initialize.
void Photon.Pun.Simple.VitalDefinition.SetTickInterval(float tickInterval)
Referenced by Photon.Pun.Simple.VitalDefinition.Initialize.
VitalData Photon.Pun.Simple.VitalDefinition.GetDefaultData()
References Photon.Pun.Simple.VitalDefinition.startValue.
Referenced by Photon.Pun.Simple.Vital.ResetValues.
SerializationFlags Photon.Pun.Simple.VitalDefinition.Serialize(VitalData vitalData, VitalData prevVitalData, byte[] buffer, ref int bitposition, bool keyframe=true)
References Photon.Pun.Simple.VitalData.ticksUntilDecay, Photon.Pun.Simple.VitalData.ticksUntilRegen, Photon.Pun.Simple.VitalData.Value.
VitalData Photon.Pun.Simple.VitalDefinition.Deserialize(byte[] buffer, ref int bitposition, bool keyframe=true)
VitalData Photon.Pun.Simple.VitalDefinition.Extrapolate(VitalData prev)
References Photon.Pun.Simple.VitalDefinition.FullValue, Photon.Pun.Simple.VitalData.ticksUntilDecay, Photon.Pun.Simple.VitalData.ticksUntilRegen, Photon.Pun.Simple.VitalData.Value.