Photon::Compression::HalfFloat::HalfUtilities
readonly uint [] Photon.Compression.HalfFloat.HalfUtilities.HalfToFloatMantissaTable
readonly uint [] Photon.Compression.HalfFloat.HalfUtilities.HalfToFloatExponentTable
readonly uint [] Photon.Compression.HalfFloat.HalfUtilities.HalfToFloatOffsetTable
readonly ushort [] Photon.Compression.HalfFloat.HalfUtilities.FloatToHalfBaseTable
readonly byte [] Photon.Compression.HalfFloat.HalfUtilities.FloatToHalfShiftTable
static Photon.Compression.HalfFloat.HalfUtilities.HalfUtilities()
static float Photon.Compression.HalfFloat.HalfUtilities.Unpack(ushort value)
Referenced by Photon.Compression.HalfFloat.Half.ConvertToFloat, Photon.Compression.HalfFloat.Half.operator float.
static ushort Photon.Compression.HalfFloat.HalfUtilities.Pack(float value)
Referenced by Photon.Compression.HalfFloat.Half.Half.