Photon::Realtime::LoadBalancingClient
LoadBalancingPeer Photon.Realtime.LoadBalancingClient.LoadBalancingPeer
The client uses a LoadBalancingPeer as API to communicate with the server.
This is public for ease-of-use: Some methods like OpRaiseEvent are not relevant for the connection state and don't need a override.
Referenced by Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.PhotonHandler.Dispatch, Photon.Pun.PhotonNetwork.FetchServerTimestamp, Photon.Pun.PhotonNetwork.GetPing, Photon.Pun.PhotonHandler.LateUpdate, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Realtime.SupportLogger.LogStats, Photon.Pun.PhotonNetwork.NetworkStatisticsReset, Photon.Pun.PhotonNetwork.NetworkStatisticsToString, Photon.Realtime.SupportLogger.OnConnected, Photon.Pun.Simple.Internal.NetMsgCallbacks.OnEvent, Photon.Pun.UtilityScripts.PhotonStatsGui.OnGUI, Photon.Realtime.ConnectionHandler.RealtimeFallbackThread, Photon.Pun.PhotonNetwork.Reconnect, Photon.Pun.PhotonNetwork.ReconnectAndRejoin, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.PhotonNetwork.SendAllOutgoingCommands, Photon.Pun.UtilityScripts.PhotonLagSimulationGui.Start, Photon.Pun.UtilityScripts.PhotonStatsGui.TrafficStatsWindow.
SerializationProtocol Photon.Realtime.LoadBalancingClient.SerializationProtocol
Gets or sets the binary protocol version used by this client
Use this always instead of setting it via LoadBalancingClient.LoadBalancingPeer (PhotonPeer.SerializationProtocolType) directly, especially when WSS protocol is used.
Referenced by Photon.Realtime.LoadBalancingClient.LoadBalancingClient.
string Photon.Realtime.LoadBalancingClient.AppVersion
The version of your client. A new version also creates a new "virtual app" to separate players from older client versions.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.LoadBalancingClient.
string Photon.Realtime.LoadBalancingClient.AppId
The AppID as assigned from the Photon Cloud. If you host yourself, this is the "regular" Photon Server Application Name (most likely: "LoadBalancing").
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions.
ClientAppType Photon.Realtime.LoadBalancingClient.ClientType
The ClientAppType defines which sort of AppId should be expected. The LoadBalancingClient supports Realtime and Voice app types. Default: Realtime.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectUsingSettings.
AuthenticationValues Photon.Realtime.LoadBalancingClient.AuthValues
User authentication values to be sent to the Photon server right after connecting.
Set this property or pass AuthenticationValues by Connect(..., authValues).
Referenced by Photon.Realtime.LoadBalancingClient.OnEvent, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin, Photon.Realtime.LoadBalancingClient.ReconnectToMaster.
ConnectionProtocol? Photon.Realtime.LoadBalancingClient.ExpectedProtocol
Optionally contains a protocol which will be used on Master- and GameServer.
When using AuthMode = AuthModeOption.AuthOnceWss, the client uses a wss-connection on the NameServer but another protocol on the other servers. As the NameServer sends an address, which is different per protocol, it needs to know the expected protocol. This is nullable by design. In many cases, the protocol on the NameServer is not different from the other servers. If set, the operation AuthOnce will contain this value and the OpAuth response on the NameServer will execute a protocol switch. summary>Simplifies getting the token for connect/init requests, if this feature is enabled.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged.
object? Photon.Realtime.LoadBalancingClient.TokenForInit
bool Photon.Realtime.LoadBalancingClient.IsUsingNameServer
True if this client uses a NameServer to get the Master Server address.
This value is public, despite being an internal value, which should only be set by this client.
Referenced by Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.Reconnect.
string Photon.Realtime.LoadBalancingClient.NameServerAddress
Name Server Address for Photon Cloud (based on current protocol). You can use the default values and usually won't have to set this value.
bool Photon.Realtime.LoadBalancingClient.UseAlternativeUdpPorts
Replaced by ServerPortOverrides.
bool Photon.Realtime.LoadBalancingClient.EnableProtocolFallback
Enables a fallback to another protocol in case a connect to the Name Server fails.
When connecting to the Name Server fails for a first time, the client will select an alternative network protocol and re-try to connect. The fallback will use the default Name Server port as defined by ProtocolToNameServerPort. The fallback for TCP is UDP. All other protocols fallback to TCP.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.OnStatusChanged.
string Photon.Realtime.LoadBalancingClient.CurrentServerAddress
The currently used server address (if any). The type of server is define by Server property.
string Photon.Realtime.LoadBalancingClient.MasterServerAddress
Your Master Server address.
In PhotonCloud, call ConnectToRegionMaster() to find your Master Server. In the Photon Cloud, explicit definition of a Master Server Address is not best practice. The Photon Cloud has a "Name Server" which redirects clients to a specific Master Server (per Region and AppId).
Referenced by Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Pun.PhotonNetwork.Reconnect, Photon.Realtime.LoadBalancingClient.ReconnectToMaster.
string Photon.Realtime.LoadBalancingClient.GameServerAddress
The game server's address for a particular room. In use temporarily, as assigned by master.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.OpLeaveRoom, Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin.
ServerConnection Photon.Realtime.LoadBalancingClient.Server
The server this client is currently connected or connecting to.
Each server (NameServer, MasterServer, GameServer) allow some operations and reject others.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.OpCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinOrCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinRoom, Photon.Realtime.LoadBalancingClient.OpRejoinRoom, Photon.Pun.PhotonNetwork.RejoinRoom.
ClientState Photon.Realtime.LoadBalancingClient.State
Current state this client is in. Careful: several states are "transitions" that lead to other states.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.Disconnect, Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Pun.PhotonNetwork.JoinRoom, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Realtime.SupportLogger.LogStats, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.OpCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinLobby, Photon.Realtime.LoadBalancingClient.OpJoinOrCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinRandomOrCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinRandomRoom, Photon.Realtime.LoadBalancingClient.OpJoinRoom, Photon.Realtime.LoadBalancingClient.OpLeaveRoom, Photon.Realtime.LoadBalancingClient.OpRejoinRoom, Photon.Pun.PhotonNetwork.RejoinRoom, Photon.Realtime.Demo.ConnectAndJoinRandomLb.Update.
bool Photon.Realtime.LoadBalancingClient.IsConnected
Returns if this client is currently connected or connecting to some type of server.
This is even true while switching servers. Use IsConnectedAndReady to check only for those states that enable you to send Operations.
Referenced by Photon.Realtime.ConnectionHandler.RealtimeFallbackThread.
bool Photon.Realtime.LoadBalancingClient.IsConnectedAndReady
A refined version of IsConnected which is true only if your connection is ready to send operations.
Not all operations can be called on all types of servers. If an operation is unavailable on the currently connected server, this will result in a OperationResponse with ErrorCode != 0. Examples: The NameServer allows OpGetRegions which is not available anywhere else. The MasterServer does not allow you to send events (OpRaiseEvent) and on the GameServer you are unable to join a lobby (OpJoinLobby). To check which server you are on, use: Server.
DisconnectCause Photon.Realtime.LoadBalancingClient.DisconnectedCause
Summarizes (aggregates) the different causes for disconnects of a client.
A disconnect can be caused by: errors in the network connection or some vital operation failing (which is considered "high level"). While operations always trigger a call to OnOperationResponse, connection related changes are treated in OnStatusChanged. The DisconnectCause is set in either case and summarizes the causes for any disconnect in a single state value which can be used to display (or debug) the cause for disconnection.
Referenced by Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged.
bool Photon.Realtime.LoadBalancingClient.InLobby
Internal value if the client is in a lobby.
This is used to re-set this.State, when joining/creating a room fails.
Referenced by Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Realtime.LoadBalancingClient.OnOperationResponse.
TypedLobby Photon.Realtime.LoadBalancingClient.CurrentLobby
The lobby this client currently uses. Defined when joining a lobby or creating rooms
Referenced by Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.PhotonNetwork.JoinOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom, Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Realtime.SupportLogger.OnJoinedLobby, Photon.Realtime.LoadBalancingClient.OpJoinLobby.
Player Photon.Realtime.LoadBalancingClient.LocalPlayer
The local player is never null but not valid unless the client is in a room, too. The ID will be -1 outside of rooms.
Referenced by Photon.Realtime.LoadBalancingClient.ChangeLocalID, Photon.Pun.PhotonNetwork.CleanRpcBufferIfMine, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Realtime.LoadBalancingClient.OnEvent, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfActor.
string Photon.Realtime.LoadBalancingClient.NickName
The nickname of the player (synced with others).
Same as client.LocalPlayer.NickName.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
string Photon.Realtime.LoadBalancingClient.UserId
An ID for this user.
Sent in OpAuthenticate when you connect. If not set, the PlayerName is applied during connect. On connect, if the UserId is null or empty, the client will copy the PlayName to UserId. If PlayerName is not set either (before connect), the server applies a temporary ID which stays unknown to this client and other clients. The UserId is what's used in FindFriends and for fetching data for your account (with WebHooks e.g.). By convention, set this ID before you connect, not while being connected. There is no error but the ID won't change while being connected.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OpFindFriends.
Room Photon.Realtime.LoadBalancingClient.CurrentRoom
The current room this client is connected to (null if none available).
Referenced by Photon.Realtime.LoadBalancingClient.ChangeLocalID, Photon.Realtime.SupportLogger.OnCreatedRoom, Photon.Realtime.LoadBalancingClient.OnEvent, Photon.Realtime.SupportLogger.OnJoinedRoom, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfActor.
bool Photon.Realtime.LoadBalancingClient.InRoom
Is true while being in a room (this.state == ClientState.Joined).
Aside from polling this value, game logic should implement IMatchmakingCallbacks in some class and react when that gets called. OpRaiseEvent, OpLeave and some other operations can only be used (successfully) when the client is in a room..
int Photon.Realtime.LoadBalancingClient.PlayersOnMasterCount
Statistic value available on master server: Players on master (looking for games).
Referenced by Photon.Realtime.LoadBalancingClient.OnEvent.
int Photon.Realtime.LoadBalancingClient.PlayersInRoomsCount
Statistic value available on master server: Players in rooms (playing).
Referenced by Photon.Realtime.LoadBalancingClient.OnEvent.
int Photon.Realtime.LoadBalancingClient.RoomsCount
Statistic value available on master server: Rooms currently created.
bool Photon.Realtime.LoadBalancingClient.IsFetchingFriendList
Internal flag to know if the client currently fetches a friend list.
Referenced by Photon.Realtime.LoadBalancingClient.OpFindFriends.
string Photon.Realtime.LoadBalancingClient.CloudRegion
The cloud region this client connects to. Set by ConnectToRegionMaster(). Not set if you don't use a NameServer!
Referenced by Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.OnStatusChanged.
string Photon.Realtime.LoadBalancingClient.CurrentCluster
The cluster name provided by the Name Server.
The value is provided by the OpResponse for OpAuthenticate/OpAuthenticateOnce. Default: null. This value only ever updates from the Name Server authenticate response.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
AuthModeOption Photon.Realtime.LoadBalancingClient.AuthMode
Enables the new Authentication workflow.
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
EncryptionMode Photon.Realtime.LoadBalancingClient.EncryptionMode
Defines how the communication gets encrypted.
string Photon.Realtime.LoadBalancingClient.NameServerHost
Name Server Host Name for Photon Cloud. Without port and without any prefix.
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
PhotonPortDefinition Photon.Realtime.LoadBalancingClient.ServerPortOverrides
Defines overrides for server ports.
Used per server-type if > 0. Important: You must change these when the protocol changes! Typical ports are listed in PhotonPortDefinition. Instead of using the port provided from the servers, the specified port is used (independent of the protocol). If a value is 0 (default), the port is not being replaced. Different protocols have different typical ports per server-type. https://doc.photonengine.com/en-us/pun/current/reference/tcp-and-udp-port-numbers In case of using the AuthMode AutOnceWss, the name server's protocol is wss, while udp or tcp will be used on the master server and game server. Set the ports accordingly per protocol and server.
string Photon.Realtime.LoadBalancingClient.ProxyServerAddress
Defines a proxy URL for WebSocket connections.
Can be the proxy or point to a .pac file. This URL supports various definitions: "user:pass@proxyaddress:port" "proxyaddress:port" "system:" "pac:" "pac:http://host/path/pacfile.pac" Important: Don't define a protocol, except to point to a pac file. the proxy address should not begin with http:// or https://.
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
ConnectionCallbacksContainer Photon.Realtime.LoadBalancingClient.ConnectionCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
Referenced by Photon.Pun.PhotonNetwork.LeaveRoom.
MatchMakingCallbacksContainer Photon.Realtime.LoadBalancingClient.MatchMakingCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
Referenced by Photon.Pun.PhotonNetwork.LeaveRoom.
bool Photon.Realtime.LoadBalancingClient.EnableLobbyStatistics
If enabled, the client will get a list of available lobbies from the Master Server.
Set this value before the client connects to the Master Server. While connected to the Master Server, a change has no effect. Implement OptionalInfoCallbacks.OnLobbyStatisticsUpdate, to get the list of used lobbies. The lobby statistics can be useful if your title dynamically uses lobbies, depending (e.g.) on current player activity or such. In this case, getting a list of available lobbies, their room-count and player-count can be useful info. ConnectUsingSettings sets this to the PhotonServerSettings value.
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
RegionHandler Photon.Realtime.LoadBalancingClient.RegionHandler
Contains the list if enabled regions this client may use. Null, unless the client got a response to OpGetRegions.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
string Photon.Realtime.LoadBalancingClient.SummaryToCache
Set when the best region pinging is done.
int Photon.Realtime.LoadBalancingClient.NameServerPortInAppSettings
Referenced by Photon.Pun.PhotonNetwork.ConnectUsingSettings.
object Photon.Realtime.LoadBalancingClient.tokenCache
Internally used cache for the server's token. Identifies a user/session and can be used to rejoin.
ClientState Photon.Realtime.LoadBalancingClient.state
Backing field for property.
readonly List<TypedLobbyInfo> Photon.Realtime.LoadBalancingClient.lobbyStatistics
Internal lobby stats cache, used by LobbyStatistics.
JoinType Photon.Realtime.LoadBalancingClient.lastJoinType
Internally used to decide if a room must be created or joined on game server.
EnterRoomParams Photon.Realtime.LoadBalancingClient.enterRoomParamsCache
Used when the client arrives on the GS, to join the room with the correct values.
OperationResponse Photon.Realtime.LoadBalancingClient.failedRoomEntryOperation
Used to cache a failed "enter room" operation on the Game Server, to return to the Master Server before calling a fail-callback.
string [] Photon.Realtime.LoadBalancingClient.friendListRequested
Contains the list of names of friends to look up their state on the server.
string Photon.Realtime.LoadBalancingClient.bestRegionSummaryFromStorage
Stores the best region summary of a previous session to speed up connecting.
bool Photon.Realtime.LoadBalancingClient.connectToBestRegion
Internal connection setting/flag.
If the client should connect to the best region or not. It's set in the Connect...() methods. Only ConnectUsingSettings() sets it to true. If true, client will ping available regions and select the best. A bestRegionSummaryFromStorage can be used to cut the ping time short.
readonly Queue<CallbackTargetChange> Photon.Realtime.LoadBalancingClient.callbackTargetChanges
readonly HashSet<object> Photon.Realtime.LoadBalancingClient.callbackTargets
readonly Dictionary<ConnectionProtocol, int> Photon.Realtime.LoadBalancingClient.ProtocolToNameServerPort
Name Server port per protocol (the UDP port is different than TCP, etc).
const int Photon.Realtime.LoadBalancingClient.FriendRequestListMax
Maximum of userIDs that can be sent in one friend list request.
Action<ClientState, ClientState> Photon.Realtime.LoadBalancingClient.StateChanged
Register a method to be called when this client's ClientState gets set.
This can be useful to react to being connected, joined into a room, etc.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions.
Action<EventData> Photon.Realtime.LoadBalancingClient.EventReceived
Register a method to be called when an event got dispatched.
Gets called after the LoadBalancingClient handled the internal events first. This is an alternative to extending LoadBalancingClient to override OnEvent(). Note that OnEvent is calling EventReceived after it handled internal events first. That means for example: Joining players will already be in the player list but leaving players will already be removed from the room.
Referenced by Photon.Realtime.LoadBalancingClient.OnEvent.
Action<OperationResponse> Photon.Realtime.LoadBalancingClient.OpResponseReceived
Register a method to be called when an operation response is received.
This is an alternative to extending LoadBalancingClient to override OnOperationResponse(). Note that OnOperationResponse gets executed before your Action is called. That means for example: The OpJoinLobby response already set the state to "JoinedLobby" and the response to OpLeave already triggered the Disconnect before this is called.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
InRoomCallbacksContainer Photon.Realtime.LoadBalancingClient.InRoomCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
LobbyCallbacksContainer Photon.Realtime.LoadBalancingClient.LobbyCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
WebRpcCallbacksContainer Photon.Realtime.LoadBalancingClient.WebRpcCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
ErrorInfoCallbacksContainer Photon.Realtime.LoadBalancingClient.ErrorInfoCallbackTargets
Wraps up the target objects for a group of callbacks, so they can be called conveniently.
By using Add or Remove, objects can "subscribe" or "unsubscribe" for this group of callbacks.
Photon.Realtime.LoadBalancingClient.LoadBalancingClient(ConnectionProtocol protocol=ConnectionProtocol.Udp)
Creates a LoadBalancingClient with UDP protocol or the one specified.
protocol Specifies the network protocol to use for connections.
References Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Realtime.LoadBalancingPeer.LoadBalancingPeer, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Realtime.LoadBalancingClient.SerializationProtocol, Photon.Realtime.LoadBalancingClient.State.
Photon.Realtime.LoadBalancingClient.LoadBalancingClient(string masterAddress, string appId, string gameVersion, ConnectionProtocol protocol=ConnectionProtocol.Udp)
Creates a LoadBalancingClient, setting various values needed before connecting.
masterAddress The Master Server's address to connect to. Used in Connect. appId The AppId of this title. Needed for the Photon Cloud. Find it in the Dashboard. gameVersion A version for this client/build. In the Photon Cloud, players are separated by AppId, GameVersion and Region. protocol Specifies the network protocol to use for connections.
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.LoadBalancingClient.AppVersion, Photon.Realtime.LoadBalancingClient.MasterServerAddress.
virtual bool Photon.Realtime.LoadBalancingClient.ConnectUsingSettings(AppSettings appSettings)
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.AppSettings.AppIdFusion, Photon.Realtime.AppSettings.AppIdRealtime, Photon.Realtime.AppSettings.AppIdVoice, Photon.Realtime.AppSettings.AppVersion, Photon.Realtime.LoadBalancingClient.AppVersion, Photon.Realtime.AppSettings.AuthMode, Photon.Realtime.AppSettings.BestRegionSummaryFromStorage, Photon.Realtime.LoadBalancingClient.ClientType, Photon.Realtime.LoadBalancingClient.CloudRegion, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.AppSettings.EnableLobbyStatistics, Photon.Realtime.AppSettings.EnableProtocolFallback, Photon.Realtime.LoadBalancingClient.EnableProtocolFallback, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.AppSettings.FixedRegion, Photon.Realtime.AppSettings.IsDefaultNameServer, Photon.Realtime.AppSettings.IsDefaultPort, Photon.Realtime.LoadBalancingClient.IsUsingNameServer, Photon.Realtime.LoadBalancingClient.MasterServerAddress, Photon.Realtime.AppSettings.NetworkLogging, Photon.Realtime.AppSettings.Port, Photon.Realtime.AppSettings.Protocol, Photon.Realtime.AppSettings.ProxyServer, Photon.Realtime.AppSettings.Server, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.AppSettings.UseNameServer.
Referenced by Photon.Realtime.Demo.ConnectAndJoinRandomLb.Start.
bool Photon.Realtime.LoadBalancingClient.Connect()
References Photon.Realtime.LoadBalancingClient.ConnectToMasterServer.
Referenced by Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin, Photon.Realtime.LoadBalancingClient.ReconnectToMaster.
virtual bool Photon.Realtime.LoadBalancingClient.ConnectToMasterServer()
Starts the "process" to connect to a Master Server, using MasterServerAddress and AppId properties.
To connect to the Photon Cloud, use ConnectUsingSettings() or ConnectToRegionMaster(). The process to connect includes several steps: the actual connecting, establishing encryption, authentification (of app and optionally the user) and connecting to the MasterServer Users can connect either anonymously or use "Custom Authentication" to verify each individual player's login. Custom Authentication in Photon uses external services and communities to verify users. While the client provides a user's info, the service setup is done in the Photon Cloud Dashboard. The parameter authValues will set this.AuthValues and use them in the connect process. Connecting to the Photon Cloud might fail due to: Network issues (OnStatusChanged() StatusCode.ExceptionOnConnect) Region not available (OnOperationResponse() for OpAuthenticate with ReturnCode == ErrorCode.InvalidRegion) Subscription CCU limit reached (OnOperationResponse() for OpAuthenticate with ReturnCode == ErrorCode.MaxCcuReached)
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Realtime.LoadBalancingClient.Connect, Photon.Pun.PhotonNetwork.ConnectToMaster, Photon.Realtime.LoadBalancingClient.OnStatusChanged.
bool Photon.Realtime.LoadBalancingClient.ConnectToNameServer()
Connects to the NameServer for Photon Cloud, where a region and server list can be obtained.
OpGetRegions If the workflow was started or failed right away.
References Photon.Realtime.LoadBalancingClient.CloudRegion, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.LoadBalancingClient.IsUsingNameServer, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions.
bool Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster(string region)
Connects you to a specific region's Master Server, using the Name Server to find the IP.
If the region is null or empty, no connection will be made. If the region (code) provided is not available, the connection process will fail on the Name Server. This method connects only to the region defined. No "Best Region" pinging will be done. If the region string does not contain a "/", this means no specific cluster is requested. To support "Sharding", the region gets a "/*" postfix in this case, to select a random cluster. If the operation could be sent. If false, no operation was sent.
References Photon.Realtime.LoadBalancingClient.CloudRegion, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.LoadBalancingClient.IsUsingNameServer, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.ConnectToRegion.
bool Photon.Realtime.LoadBalancingClient.ReconnectToMaster()
Can be used to reconnect to the master server after a disconnect.
Common use case: Press the Lock Button on a iOS device and you get disconnected immediately.
References Photon.Realtime.LoadBalancingClient.AuthValues, Photon.Realtime.LoadBalancingClient.Connect, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.MasterServerAddress, Photon.Realtime.AuthenticationValues.Token.
Referenced by Photon.Pun.PhotonNetwork.Reconnect.
bool Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin()
Can be used to return to a room quickly by directly reconnecting to a game server to rejoin a room.
Rejoining room will not send any player properties. Instead client will receive up-to-date ones from server. If you want to set new player properties, do it once rejoined. False, if the conditions are not met. Then, this client does not attempt the ReconnectAndRejoin.
References Photon.Realtime.LoadBalancingClient.AuthValues, Photon.Realtime.LoadBalancingClient.Connect, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.GameServerAddress, Photon.Realtime.AuthenticationValues.Token.
Referenced by Photon.Pun.PhotonNetwork.ReconnectAndRejoin.
void Photon.Realtime.LoadBalancingClient.Disconnect(DisconnectCause cause=DisconnectCause.DisconnectByClientLogic)
Disconnects the peer from a server or stays disconnected.
If the client / peer was connected, a callback will be triggered. Disconnect will attempt to notify the server of the client closing the connection. Clients that are in a room, will leave the room. If the room's playerTTL > 0, the player will just become inactive (and may rejoin). This method will not change the current State, if this client State is PeerCreated, Disconnecting or Disconnected. In those cases, there is also no callback for the disconnect. The DisconnectedCause will only change if the client was connected.
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.CloseRegionListView, Photon.Pun.PhotonNetwork.Disconnect, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.ConnectionHandler.RealtimeFallbackThread.
void Photon.Realtime.LoadBalancingClient.SimulateConnectionLoss(bool simulateTimeout)
Useful to test loss of connection which will end in a client timeout.
This modifies LoadBalancingPeer.NetworkSimulationSettings. Read remarks. Use with care as this sets LoadBalancingPeer.IsSimulationEnabled. Read LoadBalancingPeer.IsSimulationEnabled to check if this is on or off, if needed. If simulateTimeout is true, LoadBalancingPeer.NetworkSimulationSettings.IncomingLossPercentage and LoadBalancingPeer.NetworkSimulationSettings.OutgoingLossPercentage will be set to 100. Obviously, this overrides any network simulation settings done before. If you want fine-grained network simulation control, use the NetworkSimulationSettings. The timeout will lead to a call to IConnectionCallbacks.OnDisconnected, as usual in a client timeout. You could modify this method (or use NetworkSimulationSettings) to deliberately run into a server timeout by just setting the OutgoingLossPercentage = 100 and the IncomingLossPercentage = 0. simulateTimeout If true, a connection loss is simulated. If false, the simulation ends.
References Photon.Realtime.LoadBalancingClient.DebugReturn.
void Photon.Realtime.LoadBalancingClient.Service()
This method dispatches all available incoming commands and then sends this client's outgoing commands.
It uses DispatchIncomingCommands and SendOutgoingCommands to do that. The Photon client libraries are designed to fit easily into a game or application. The application is in control of the context (thread) in which incoming events and responses are executed and has full control of the creation of UDP/TCP packages. Sending packages and dispatching received messages are two separate tasks. Service combines them into one method at the cost of control. It calls DispatchIncomingCommands and SendOutgoingCommands. Call this method regularly (10..50 times a second). This will Dispatch ANY received commands (unless a reliable command in-order is still missing) and events AND will send queued outgoing commands. Fewer calls might be more effective if a device cannot send many packets per second, as multiple operations might be combined into one package. You could replace Service by: while (DispatchIncomingCommands()); //Dispatch until everything is Dispatched... SendOutgoingCommands(); //Send a UDP/TCP package with outgoing messages PhotonPeer.DispatchIncomingCommands, PhotonPeer.SendOutgoingCommands
Referenced by Photon.Realtime.Demo.ConnectAndJoinRandomLb.Update.
bool Photon.Realtime.LoadBalancingClient.OpFindFriends(string[] friendsToFind, FindFriendsOptions options=null)
Request the rooms and online status for a list of friends.
All clients should set a unique UserId before connecting. The result is available in this.FriendList. Used on Master Server to find the rooms played by a selected list of users. The result will be stored in LoadBalancingClient.FriendList, which is null before the first server response. Users identify themselves by setting a UserId in the LoadBalancingClient instance. This will send the ID in OpAuthenticate during connect (to master and game servers). Note: Changing a player's name doesn't make sense when using a friend list. The list of usernames must be fetched from some other source (not provided by Photon). Internal: The server response includes 2 arrays of info (each index matching a friend from the request): ParameterCode.FindFriendsResponseOnlineList = bool[] of online states ParameterCode.FindFriendsResponseRoomIdList = string[] of room names (empty string if not in a room) The options may be used to define which state a room must match to be returned. friendsToFind Array of friend's names (make sure they are unique). options Options that affect the result of the FindFriends operation. If the operation could be sent (requires connection).
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.OperationCode.FindFriends, Photon.Realtime.LoadBalancingClient.IsFetchingFriendList, Photon.Realtime.LoadBalancingPeer.OpFindFriends, Photon.Realtime.LoadBalancingClient.UserId.
Referenced by Photon.Pun.PhotonNetwork.FindFriends.
bool Photon.Realtime.LoadBalancingClient.OpJoinLobby(TypedLobby lobby)
If already connected to a Master Server, this joins the specified lobby.
This request triggers an OnOperationResponse() call and the callback OnJoinedLobby(). lobby The lobby to join. Use null for default lobby. If the operation could be sent. False, if the client is not IsConnectedAndReady or when it's not connected to a Master Server.
References Photon.Realtime.LoadBalancingClient.CurrentLobby, Photon.Realtime.TypedLobby.Default, Photon.Realtime.OperationCode.JoinLobby, Photon.Realtime.LoadBalancingPeer.OpJoinLobby, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.JoinLobby.
bool Photon.Realtime.LoadBalancingClient.OpLeaveLobby()
Opposite of joining a lobby.
You don't have to explicitly leave a lobby to join another (client can be in one max, at any time). If the operation could be sent (has to be connected).
References Photon.Realtime.OperationCode.LeaveLobby, Photon.Realtime.LoadBalancingPeer.OpLeaveLobby.
Referenced by Photon.Pun.PhotonNetwork.LeaveLobby.
bool Photon.Realtime.LoadBalancingClient.OpJoinRandomRoom(OpJoinRandomRoomParams opJoinRandomRoomParams=null)
Joins a random room that matches the filter.
Will callback: OnJoinedRoom or OnJoinRandomFailed. Used for random matchmaking. You can join any room or one with specific properties defined in opJoinRandomRoomParams. You can use expectedCustomRoomProperties and expectedMaxPlayers as filters for accepting rooms. If you set expectedCustomRoomProperties, a room must have the exact same key values set at Custom Properties. You need to define which Custom Room Properties will be available for matchmaking when you create a room. See: OpCreateRoom(string roomName, RoomOptions roomOptions, TypedLobby lobby) This operation fails if no rooms are fitting or available (all full, closed or not visible). It may also fail when actually joining the room which was found. Rooms may close, become full or empty anytime. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. This client's State is set to ClientState.Joining immediately, when the operation could be called. In the background, the client will switch servers and call various related operations. When you're in the room, this client's State will become ClientState.Joined. When entering a room, this client's Player Custom Properties will be sent to the room. Use LocalPlayer.SetCustomProperties to set them, even while not yet in the room. Note that the player properties will be cached locally and are not wiped when leaving a room. More about matchmaking: https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby You can define an array of expectedUsers, to block player slots in the room for these users. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. opJoinRandomRoomParams Optional definition of properties to filter rooms in random matchmaking. If the operation could be sent currently (requires connection to Master Server).
References Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.OperationCode.JoinRandomGame, Photon.Realtime.EnterRoomParams.Lobby, Photon.Realtime.LoadBalancingPeer.OpJoinRandomRoom, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.JoinRandomRoom, Photon.Realtime.Demo.ConnectAndJoinRandomLb.OnConnectedToMaster.
bool Photon.Realtime.LoadBalancingClient.OpJoinRandomOrCreateRoom(OpJoinRandomRoomParams opJoinRandomRoomParams, EnterRoomParams createRoomParams)
Attempts to join a room that matches the specified filter and creates a room if none found.
This operation is a combination of filter-based random matchmaking with the option to create a new room, if no fitting room exists. The benefit of that is that the room creation is done by the same operation and the room can be found by the very next client, looking for similar rooms. There are separate parameters for joining and creating a room. This method can only be called while connected to a Master Server. This client's State is set to ClientState.Joining immediately. Either IMatchmakingCallbacks.OnJoinedRoom or IMatchmakingCallbacks.OnCreatedRoom get called. More about matchmaking: https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. If the operation will be sent (requires connection to Master Server).
References Photon.Realtime.OpJoinRandomRoomParams.ExpectedUsers, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.OperationCode.JoinRandomGame, Photon.Realtime.EnterRoomParams.Lobby, Photon.Realtime.LoadBalancingPeer.OpJoinRandomOrCreateRoom, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.OpJoinRandomRoomParams.TypedLobby.
Referenced by Photon.Pun.PhotonNetwork.JoinRandomOrCreateRoom.
bool Photon.Realtime.LoadBalancingClient.OpCreateRoom(EnterRoomParams enterRoomParams)
Creates a new room.
Will callback: OnCreatedRoom and OnJoinedRoom or OnCreateRoomFailed. When successful, the client will enter the specified room and callback both OnCreatedRoom and OnJoinedRoom. In all error cases, OnCreateRoomFailed gets called. Creating a room will fail if the room name is already in use or when the RoomOptions clashing with one another. Check the EnterRoomParams reference for the various room creation options. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. When you're in the room, this client's State will become ClientState.Joined. When entering a room, this client's Player Custom Properties will be sent to the room. Use LocalPlayer.SetCustomProperties to set them, even while not yet in the room. Note that the player properties will be cached locally and are not wiped when leaving a room. You can define an array of expectedUsers, to block player slots in the room for these users. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. enterRoomParams Definition of properties for the room to create. If the operation could be sent currently (requires connection to Master Server).
References Photon.Realtime.OperationCode.CreateGame, Photon.Realtime.LoadBalancingPeer.OpCreateRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.CreateRoom, Photon.Realtime.Demo.ConnectAndJoinRandomLb.OnJoinRandomFailed.
bool Photon.Realtime.LoadBalancingClient.OpJoinOrCreateRoom(EnterRoomParams enterRoomParams)
Joins a specific room by name and creates it on demand.
Will callback: OnJoinedRoom or OnJoinRoomFailed. Useful when players make up a room name to meet in: All involved clients call the same method and whoever is first, also creates the room. When successful, the client will enter the specified room. The client which creates the room, will callback both OnCreatedRoom and OnJoinedRoom. Clients that join an existing room will only callback OnJoinedRoom. In all error cases, OnJoinRoomFailed gets called. Joining a room will fail, if the room is full, closed or when the user already is present in the room (checked by userId). To return to a room, use OpRejoinRoom. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. This client's State is set to ClientState.Joining immediately, when the operation could be called. In the background, the client will switch servers and call various related operations. When you're in the room, this client's State will become ClientState.Joined. If you set room properties in roomOptions, they get ignored when the room is existing already. This avoids changing the room properties by late joining players. When entering a room, this client's Player Custom Properties will be sent to the room. Use LocalPlayer.SetCustomProperties to set them, even while not yet in the room. Note that the player properties will be cached locally and are not wiped when leaving a room. You can define an array of expectedUsers, to block player slots in the room for these users. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. enterRoomParams Definition of properties for the room to create or join. If the operation could be sent currently (requires connection to Master Server).
References Photon.Realtime.OperationCode.JoinGame, Photon.Realtime.LoadBalancingPeer.OpJoinRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.JoinOrCreateRoom.
bool Photon.Realtime.LoadBalancingClient.OpJoinRoom(EnterRoomParams enterRoomParams)
Joins a room by name.
Will callback: OnJoinedRoom or OnJoinRoomFailed. Useful when using lobbies or when players follow friends or invite each other. When successful, the client will enter the specified room and callback via OnJoinedRoom. In all error cases, OnJoinRoomFailed gets called. Joining a room will fail if the room is full, closed, not existing or when the user already is present in the room (checked by userId). To return to a room, use OpRejoinRoom. When players invite each other and it's unclear who's first to respond, use OpJoinOrCreateRoom instead. This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster. Check the return value to make sure the operation will be called on the server. Note: There will be no callbacks if this method returned false. A room's name has to be unique (per region, appid and gameversion). When your title uses a global matchmaking or invitations (e.g. an external solution), keep regions and the game versions in mind to join a room. This client's State is set to ClientState.Joining immediately, when the operation could be called. In the background, the client will switch servers and call various related operations. When you're in the room, this client's State will become ClientState.Joined. When entering a room, this client's Player Custom Properties will be sent to the room. Use LocalPlayer.SetCustomProperties to set them, even while not yet in the room. Note that the player properties will be cached locally and are not wiped when leaving a room. You can define an array of expectedUsers, to reserve player slots in the room for friends or party members. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. enterRoomParams Definition of properties for the room to join. If the operation could be sent currently (requires connection to Master Server).
References Photon.Realtime.OperationCode.JoinGame, Photon.Realtime.LoadBalancingPeer.OpJoinRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.JoinRoom.
bool Photon.Realtime.LoadBalancingClient.OpRejoinRoom(string roomName)
Rejoins a room by roomName (using the userID internally to return).
Will callback: OnJoinedRoom or OnJoinRoomFailed. Used to return to a room, before this user was removed from the players list. Internally, the userID will be checked by the server, to make sure this user is in the room (active or inactice). In contrast to join, this operation never adds a players to a room. It will attempt to retake an existing spot in the playerlist or fail. This makes sure the client doean't accidentally join a room when the game logic meant to re-activate an existing actor in an existing room. This method will fail on the server, when the room does not exist, can't be loaded (persistent rooms) or when the userId is not in the player list of this room. This will lead to a callback OnJoinRoomFailed. Rejoining room will not send any player properties. Instead client will receive up-to-date ones from server. If you want to set new player properties, do it once rejoined.
References Photon.Realtime.OperationCode.JoinGame, Photon.Realtime.LoadBalancingPeer.OpJoinRoom, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.RejoinRoom.
bool Photon.Realtime.LoadBalancingClient.OpLeaveRoom(bool becomeInactive, bool sendAuthCookie=false)
Leaves the current room, optionally telling the server that the user is just becoming inactive.
Will callback: OnLeftRoom. OpLeaveRoom skips execution when the room is null or the server is not GameServer or the client is disconnecting from GS already. OpLeaveRoom returns false in those cases and won't change the state, so check return of this method. In some cases, this method will skip the OpLeave call and just call Disconnect(), which not only leaves the room but also the server. Disconnect also triggers a leave and so that workflow is is quicker. becomeInactive If true, this player becomes inactive in the game and can return later (if PlayerTTL of the room is != 0). sendAuthCookie WebFlag: Securely transmit the encrypted object AuthCookie to the web service in PathLeave webhook when available If the current room could be left (impossible while not in a room).
References Photon.Realtime.LoadBalancingClient.GameServerAddress, Photon.Realtime.OperationCode.Leave, Photon.Realtime.LoadBalancingPeer.OpLeaveRoom, Photon.Realtime.LoadBalancingClient.State.
Referenced by Photon.Pun.PhotonNetwork.LeaveRoom.
bool Photon.Realtime.LoadBalancingClient.OpGetGameList(TypedLobby typedLobby, string sqlLobbyFilter)
Gets a list of rooms matching the (non empty) SQL filter for the given SQL-typed lobby.
Operation is only available for lobbies of type SqlLobby and the filter can not be empty. It will check those conditions and fail locally, returning false. This is an async request which triggers a OnOperationResponse() call. https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby::sql_lobby_type typedLobby The lobby to query. Has to be of type SqlLobby. sqlLobbyFilter The sql query statement. If the operation could be sent (has to be connected).
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.OperationCode.GetGameList, Photon.Realtime.LoadBalancingPeer.OpGetGameList, Photon.Realtime.TypedLobby.Type.
Referenced by Photon.Pun.PhotonNetwork.GetCustomRoomList.
bool Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfActor(int actorNr, Hashtable propertiesToSet, Hashtable expectedProperties=null, WebFlags webFlags=null)
Updates and synchronizes a Player's Custom Properties.
Optionally, expectedProperties can be provided as condition. Custom Properties are a set of string keys and arbitrary values which is synchronized for the players in a Room. They are available when the client enters the room, as they are in the response of OpJoin and OpCreate. Custom Properties either relate to the (current) Room or a Player (in that Room). Both classes locally cache the current key/values and make them available as property: CustomProperties. This is provided only to read them. You must use the method SetCustomProperties to set/modify them. Any client can set any Custom Properties anytime (when in a room). It's up to the game logic to organize how they are best used. You should call SetCustomProperties only with key/values that are new or changed. This reduces traffic and performance. Unless you define some expectedProperties, setting key/values is always permitted. In this case, the property-setting client will not receive the new values from the server but instead update its local cache in SetCustomProperties. If you define expectedProperties, the server will skip updates if the server property-cache does not contain all expectedProperties with the same values. In this case, the property-setting client will get an update from the server and update it's cached key/values at about the same time as everyone else. The benefit of using expectedProperties can be only one client successfully sets a key from one known value to another. As example: Store who owns an item in a Custom Property "ownedBy". It's 0 initally. When multiple players reach the item, they all attempt to change "ownedBy" from 0 to their actorNumber. If you use expectedProperties {"ownedBy", 0} as condition, the first player to take the item will have it (and the others fail to set the ownership). Properties get saved with the game state for Turnbased games (which use IsPersistent = true). actorNr Defines which player the Custom Properties belong to. ActorID of a player. propertiesToSet Hashtable of Custom Properties that changes. expectedProperties Provide some keys/values to use as condition for setting the new values. Client must be in room. webFlags Defines if the set properties should be forwarded to a WebHook. Client must be in room. False if propertiesToSet is null or empty or have zero string keys. If not in a room, returns true if local player and expectedProperties and webFlags are null. False if actorNr is lower than or equal to zero. Otherwise, returns if the operation could be sent to the server.
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.LoadBalancingClient.CurrentRoom, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Realtime.Player.SetCustomProperties.
bool Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfRoom(Hashtable propertiesToSet, Hashtable expectedProperties=null, WebFlags webFlags=null)
Updates and synchronizes this Room's Custom Properties.
Optionally, expectedProperties can be provided as condition. Custom Properties are a set of string keys and arbitrary values which is synchronized for the players in a Room. They are available when the client enters the room, as they are in the response of OpJoin and OpCreate. Custom Properties either relate to the (current) Room or a Player (in that Room). Both classes locally cache the current key/values and make them available as property: CustomProperties. This is provided only to read them. You must use the method SetCustomProperties to set/modify them. Any client can set any Custom Properties anytime (when in a room). It's up to the game logic to organize how they are best used. You should call SetCustomProperties only with key/values that are new or changed. This reduces traffic and performance. Unless you define some expectedProperties, setting key/values is always permitted. In this case, the property-setting client will not receive the new values from the server but instead update its local cache in SetCustomProperties. If you define expectedProperties, the server will skip updates if the server property-cache does not contain all expectedProperties with the same values. In this case, the property-setting client will get an update from the server and update it's cached key/values at about the same time as everyone else. The benefit of using expectedProperties can be only one client successfully sets a key from one known value to another. As example: Store who owns an item in a Custom Property "ownedBy". It's 0 initally. When multiple players reach the item, they all attempt to change "ownedBy" from 0 to their actorNumber. If you use expectedProperties {"ownedBy", 0} as condition, the first player to take the item will have it (and the others fail to set the ownership). Properties get saved with the game state for Turnbased games (which use IsPersistent = true). propertiesToSet Hashtable of Custom Properties that changes. expectedProperties Provide some keys/values to use as condition for setting the new values. webFlags Defines web flags for an optional PathProperties webhook. False if propertiesToSet is null or empty or have zero string keys. Otherwise, returns if the operation could be sent to the server.
References Photon.Realtime.LoadBalancingClient.DebugReturn.
virtual bool Photon.Realtime.LoadBalancingClient.OpRaiseEvent(byte eventCode, object customEventContent, RaiseEventOptions raiseEventOptions, SendOptions sendOptions)
Send an event with custom code/type and any content to the other players in the same room.
eventCode Identifies this type of event (and the content). Your game's event codes can start with 0. customEventContent Any serializable datatype (including Hashtable like the other OpRaiseEvent overloads). raiseEventOptions Contains used send options. If you pass null, the default options will be used. sendOptions Send options for reliable, encryption etc If operation could be enqueued for sending. Sent when calling: Service or SendOutgoingCommands.
References Photon.Realtime.LoadBalancingPeer.OpRaiseEvent, Photon.Realtime.OperationCode.RaiseEvent.
Referenced by Photon.Pun.PhotonNetwork.CloseConnection, Photon.Pun.PhotonNetwork.RaiseEvent.
virtual bool Photon.Realtime.LoadBalancingClient.OpChangeGroups(byte[] groupsToRemove, byte[] groupsToAdd)
Operation to handle this client's interest groups (for events in room).
Note the difference between passing null and byte[0]: null won't add/remove any groups. byte[0] will add/remove all (existing) groups. First, removing groups is executed. This way, you could leave all groups and join only the ones provided. Changes become active not immediately but when the server executes this operation (approximately RTT/2). groupsToRemove Groups to remove from interest. Null will not remove any. A byte[0] will remove all. groupsToAdd Groups to add to interest. Null will not add any. A byte[0] will add all current. If operation could be enqueued for sending. Sent when calling: Service or SendOutgoingCommands.
References Photon.Realtime.OperationCode.ChangeGroups, Photon.Realtime.LoadBalancingPeer.OpChangeGroups.
Referenced by Photon.Pun.PhotonNetwork.SetInterestGroups.
void Photon.Realtime.LoadBalancingClient.ChangeLocalID(int newID)
Internally used to set the LocalPlayer's ID (from -1 to the actual in-room ID).
newID New actor ID (a.k.a actorNr) assigned when joining a room.
References Photon.Realtime.LoadBalancingClient.CurrentRoom, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Realtime.Room.StorePlayer.
Referenced by Photon.Realtime.LoadBalancingClient.OnStatusChanged.
virtual void Photon.Realtime.LoadBalancingClient.DebugReturn(DebugLevel level, string message)
Debug output of low level api (and this client).
This method is not responsible to keep up the state of a LoadBalancingClient. Calling base.DebugReturn on overrides is optional.
References Photon.Realtime.LoadBalancingPeer.LoadBalancingPeer.
Referenced by Photon.Realtime.LoadBalancingClient.ChangeLocalID, Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Realtime.LoadBalancingClient.ConnectToRegionMaster, Photon.Realtime.LoadBalancingClient.ConnectUsingSettings, Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Realtime.LoadBalancingClient.OnMessage, Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OnStatusChanged, Photon.Realtime.LoadBalancingClient.OpFindFriends, Photon.Realtime.LoadBalancingClient.OpGetGameList, Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfActor, Photon.Realtime.LoadBalancingClient.OpSetCustomPropertiesOfRoom, Photon.Realtime.LoadBalancingClient.OpWebRpc, Photon.Realtime.LoadBalancingClient.ReconnectAndRejoin, Photon.Realtime.LoadBalancingClient.ReconnectToMaster, Photon.Realtime.Room.SetExpectedUsers, Photon.Realtime.LoadBalancingClient.SimulateConnectionLoss.
virtual void Photon.Realtime.LoadBalancingClient.OnOperationResponse(OperationResponse operationResponse)
Uses the OperationResponses provided by the server to advance the internal state and call ops as needed.
When this method finishes, it will call your OnOpResponseAction (if any). This way, you can get any operation response without overriding this class. To implement a more complex game/app logic, you should implement your own class that inherits the LoadBalancingClient. Override this method to use your own operation-responses easily. This method is essential to update the internal state of a LoadBalancingClient, so overriding methods must call base.OnOperationResponse(). operationResponse Contains the server's response for an operation called by this peer.
References Photon.Realtime.ParameterCode.Address, Photon.Realtime.OperationCode.Authenticate, Photon.Realtime.OperationCode.AuthenticateOnce, Photon.Realtime.ErrorCode.AuthenticationTicketExpired, Photon.Realtime.LoadBalancingClient.AuthValues, Photon.Realtime.ParameterCode.Cluster, Photon.Realtime.OperationCode.CreateGame, Photon.Realtime.LoadBalancingClient.CurrentCluster, Photon.Realtime.ErrorCode.CustomAuthenticationFailed, Photon.Realtime.Player.CustomProperties, Photon.Realtime.ParameterCode.Data, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.ParameterCode.EncryptionData, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.OperationCode.FindFriends, Photon.Realtime.ParameterCode.FindFriendsResponseOnlineList, Photon.Realtime.ParameterCode.FindFriendsResponseRoomIdList, Photon.Realtime.ParameterCode.GameList, Photon.Realtime.LoadBalancingClient.GameServerAddress, Photon.Realtime.PhotonPortDefinition.GameServerPort, Photon.Realtime.OperationCode.GetGameList, Photon.Realtime.OperationCode.GetRegions, Photon.Realtime.LoadBalancingClient.InLobby, Photon.Realtime.ErrorCode.InvalidAuthentication, Photon.Realtime.ErrorCode.InvalidOperation, Photon.Realtime.ErrorCode.InvalidRegion, Photon.Realtime.RegionHandler.IsPinging, Photon.Realtime.OperationCode.JoinGame, Photon.Realtime.OperationCode.JoinLobby, Photon.Realtime.OperationCode.JoinRandomGame, Photon.Realtime.OperationCode.Leave, Photon.Realtime.OperationCode.LeaveLobby, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Realtime.LoadBalancingClient.MasterServerAddress, Photon.Realtime.PhotonPortDefinition.MasterServerPort, Photon.Realtime.ErrorCode.MaxCcuReached, Photon.Realtime.LoadBalancingClient.NickName, Photon.Realtime.ParameterCode.NickName, Photon.Realtime.Player.NickName, Photon.Realtime.ErrorCode.Ok, Photon.Realtime.ConnectionCallbacksContainer.OnConnectedToMaster, Photon.Realtime.ConnectionCallbacksContainer.OnCustomAuthenticationFailed, Photon.Realtime.ConnectionCallbacksContainer.OnCustomAuthenticationResponse, Photon.Realtime.MatchMakingCallbacksContainer.OnFriendListUpdate, Photon.Realtime.ConnectionCallbacksContainer.OnRegionListReceived, Photon.Realtime.LoadBalancingPeer.OpCreateRoom, Photon.Realtime.ErrorCode.OperationLimitReached, Photon.Realtime.ErrorCode.OperationNotAllowedInCurrentState, Photon.Realtime.LoadBalancingPeer.OpJoinRoom, Photon.Realtime.LoadBalancingClient.OpResponseReceived, Photon.Realtime.LoadBalancingPeer.OpSettings, Photon.Realtime.RegionHandler.PingMinimumOfRegions, Photon.Realtime.ActorProperties.PlayerName, Photon.Realtime.EnterRoomParams.PlayerProperties, Photon.Realtime.LoadBalancingClient.RegionHandler, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.ParameterCode.RoomName, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.RegionHandler.SetRegions, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.ParameterCode.Token, Photon.Realtime.AuthenticationValues.Token, Photon.Realtime.LoadBalancingClient.UserId, Photon.Realtime.ParameterCode.UserId, Photon.Realtime.Player.UserId, Photon.Realtime.OperationCode.WebRpc.
virtual void Photon.Realtime.LoadBalancingClient.OnStatusChanged(StatusCode statusCode)
Uses the connection's statusCodes to advance the internal state and call operations as needed.
This method is essential to update the internal state of a LoadBalancingClient. Overriding methods must call base.OnStatusChanged.
References Photon.Realtime.LoadBalancingClient.AuthValues, Photon.Realtime.LoadBalancingClient.ChangeLocalID, Photon.Realtime.LoadBalancingClient.CloudRegion, Photon.Realtime.LoadBalancingClient.Connect, Photon.Realtime.LoadBalancingClient.ConnectToMasterServer, Photon.Realtime.LoadBalancingClient.CurrentRoom, Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.DisconnectedCause, Photon.Realtime.LoadBalancingClient.EnableProtocolFallback, Photon.Realtime.LoadBalancingClient.ExpectedProtocol, Photon.Realtime.LoadBalancingClient.GameServerAddress, Photon.Realtime.ConnectionCallbacksContainer.OnConnected, Photon.Realtime.ConnectionCallbacksContainer.OnDisconnected, Photon.Realtime.MatchMakingCallbacksContainer.OnLeftRoom, Photon.Realtime.LoadBalancingClient.Server, Photon.Realtime.LoadBalancingClient.State, Photon.Realtime.AuthenticationValues.Token.
Referenced by Photon.Pun.PhotonNetwork.Disconnect.
virtual void Photon.Realtime.LoadBalancingClient.OnEvent(EventData photonEvent)
Uses the photonEvent's provided by the server to advance the internal state and call ops as needed.
This method is essential to update the internal state of a LoadBalancingClient. Overriding methods must call base.OnEvent.
References Photon.Realtime.ParameterCode.ActorList, Photon.Realtime.Player.ActorNumber, Photon.Realtime.EventCode.AppStats, Photon.Realtime.EventCode.AuthEvent, Photon.Realtime.LoadBalancingClient.AuthValues, Photon.Realtime.LoadBalancingClient.CurrentRoom, Photon.Realtime.EventCode.ErrorInfo, Photon.Realtime.LoadBalancingClient.EventReceived, Photon.Realtime.ParameterCode.GameCount, Photon.Realtime.EventCode.GameList, Photon.Realtime.ParameterCode.GameList, Photon.Realtime.EventCode.GameListUpdate, Photon.Realtime.Room.GetPlayer, Photon.Realtime.Player.HasRejoined, Photon.Realtime.ParameterCode.IsInactive, Photon.Realtime.Player.IsInactive, Photon.Realtime.EventCode.Join, Photon.Realtime.EventCode.Leave, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.EventCode.LobbyStats, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.LoadBalancingClient.LocalPlayer, Photon.Realtime.ParameterCode.MasterClientId, Photon.Realtime.RoomInfo.masterClientId, Photon.Realtime.ParameterCode.MasterPeerCount, Photon.Realtime.TypedLobby.Name, Photon.Realtime.MatchMakingCallbacksContainer.OnCreatedRoom, Photon.Realtime.MatchMakingCallbacksContainer.OnJoinedRoom, Photon.Realtime.ParameterCode.PeerCount, Photon.Realtime.TypedLobbyInfo.PlayerCount, Photon.Realtime.ParameterCode.PlayerProperties, Photon.Realtime.LoadBalancingClient.PlayersInRoomsCount, Photon.Realtime.LoadBalancingClient.PlayersOnMasterCount, Photon.Realtime.ParameterCode.Properties, Photon.Realtime.EventCode.PropertiesChanged, Photon.Realtime.TypedLobbyInfo.RoomCount, Photon.Realtime.Room.StorePlayer, Photon.Realtime.ParameterCode.TargetActorNr, Photon.Realtime.ParameterCode.Token, Photon.Realtime.AuthenticationValues.Token, Photon.Realtime.TypedLobby.Type.
Referenced by Photon.Pun.PhotonNetwork.RaiseEvent.
virtual void Photon.Realtime.LoadBalancingClient.OnMessage(object message)
In Photon 4, "raw messages" will get their own callback method in the interface. Not used yet.
References Photon.Realtime.LoadBalancingClient.DebugReturn.
bool Photon.Realtime.LoadBalancingClient.OpWebRpc(string uriPath, object parameters, bool sendAuthCookie=false)
This operation makes Photon call your custom web-service by path/name with the given parameters (converted into Json).
Use IWebRpcCallback.OnWebRpcResponse as a callback. A WebRPC calls a custom, http-based function on a server you provide. The uriPath is relative to a "base path" which is configured server-side. The sent parameters get converted from C# types to Json. Vice versa, the response of the web-service will be converted to C# types and sent back as normal operation response. To use this feature, you have to setup your server: For a Photon Cloud application, visit the Dashboard and setup "WebHooks". The BaseUrl is used for WebRPCs as well. The class WebRpcResponse is a helper-class that extracts the most valuable content from the WebRPC response. uriPath The url path to call, relative to the baseUrl configured on Photon's server-side. parameters The parameters to send to the web-service method. sendAuthCookie Defines if the authentication cookie gets sent to a WebHook (if setup).
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.ParameterCode.EventForward, Photon.Realtime.WebFlags.SendAuthCookieConst, Photon.Realtime.ParameterCode.UriPath, Photon.Realtime.OperationCode.WebRpc, Photon.Realtime.ParameterCode.WebRpcParameters.
Referenced by Photon.Pun.PhotonNetwork.WebRpc.
void Photon.Realtime.LoadBalancingClient.AddCallbackTarget(object target)
Registers an object for callbacks for the implemented callback-interfaces.
Adding and removing callback targets is queued to not mess with callbacks in execution. Internally, this means that the addition/removal is done before the LoadBalancingClient calls the next callbacks. This detail should not affect a game's workflow. The covered callback interfaces are: IConnectionCallbacks, IMatchmakingCallbacks, ILobbyCallbacks, IInRoomCallbacks, IOnEventCallback and IWebRpcCallback. See: The object that registers to get callbacks from this client.
Referenced by Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Pun.Simple.Internal.TickManager.Bootstrap, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions, Photon.Realtime.Demo.ConnectAndJoinRandomLb.Start.
void Photon.Realtime.LoadBalancingClient.RemoveCallbackTarget(object target)
Unregisters an object from callbacks for the implemented callback-interfaces.
Adding and removing callback targets is queued to not mess with callbacks in execution. Internally, this means that the addition/removal is done before the LoadBalancingClient calls the next callbacks. This detail should not affect a game's workflow. The covered callback interfaces are: IConnectionCallbacks, IMatchmakingCallbacks, ILobbyCallbacks, IInRoomCallbacks, IOnEventCallback and IWebRpcCallback. See: target The object that unregisters from getting callbacks.
Referenced by Photon.Pun.PhotonNetwork.RemoveCallbackTarget.
string Photon.Realtime.LoadBalancingClient.GetNameServerAddress()
Gets the NameServer Address (with prefix and port), based on the set protocol (this.LoadBalancingPeer.UsedProtocol).
NameServer Address (with prefix and port).
void Photon.Realtime.LoadBalancingClient.CheckConnectSetupWebGl()
bool Photon.Realtime.LoadBalancingClient.Connect(string serverAddress, string proxyServerAddress, ServerConnection serverType)
Privately used only for reconnecting.
void Photon.Realtime.LoadBalancingClient.DisconnectToReconnect()
Private Disconnect variant that sets the state, too.
bool Photon.Realtime.LoadBalancingClient.CallAuthenticate()
bool Photon.Realtime.LoadBalancingClient.OpGetRegions()
While on the NameServer, this gets you the list of regional servers (short names and their IPs to ping them).
If the operation could be sent. If false, no operation was sent (e.g. while not connected to the NameServer).
void Photon.Realtime.LoadBalancingClient.ReadoutProperties(Hashtable gameProperties, Hashtable actorProperties, int targetActorNr)
Privately used to read-out properties coming from the server in events and operation responses (which might be a bit tricky).
Hashtable Photon.Realtime.LoadBalancingClient.ReadoutPropertiesForActorNr(Hashtable actorProperties, int actorNr)
Privately used only to read properties for a distinct actor (which might be the hashtable OR a key-pair value IN the actorProperties).
void Photon.Realtime.LoadBalancingClient.GameEnteredOnGameServer(OperationResponse operationResponse)
Called internally, when a game was joined or created on the game server successfully.
This reads the response, finds out the local player's actorNumber (a.k.a. Player.ID) and applies properties of the room and players. Errors for these operations are to be handled before this method is called. operationResponse Contains the server's response for an operation called by this peer.
void Photon.Realtime.LoadBalancingClient.UpdatedActorList(int[] actorsInGame)
bool Photon.Realtime.LoadBalancingClient.CheckIfOpAllowedOnServer(byte opCode, ServerConnection serverConnection)
bool Photon.Realtime.LoadBalancingClient.CheckIfOpCanBeSent(byte opCode, ServerConnection serverConnection, string opName)
bool Photon.Realtime.LoadBalancingClient.CheckIfClientIsReadyToCallOperation(byte opCode)
void Photon.Realtime.LoadBalancingClient.CallbackRoomEnterFailed(OperationResponse operationResponse)
void Photon.Realtime.LoadBalancingClient.OnDisconnectMessageReceived(DisconnectMessage obj)
void Photon.Realtime.LoadBalancingClient.OnRegionPingCompleted(RegionHandler regionHandler)
A callback of the RegionHandler, provided in OnRegionListReceived.
regionHandler The regionHandler wraps up best region and other region relevant info.
void Photon.Realtime.LoadBalancingClient.SetupEncryption(Dictionary< byte, object > encryptionData)
void Photon.Realtime.LoadBalancingClient.UpdateCallbackTarget< T >(CallbackTargetChange change, List< T > container)
Helper method to cast and apply a target per (interface) type.
T Either of the interfaces for callbacks. change The queued change to apply (add or remove) some target. container The container that calls callbacks on it's list of targets.
bool Photon.Realtime.LoadBalancingClient.OpSetPropertiesOfActor(int actorNr, Hashtable actorProperties, Hashtable expectedProperties=null, WebFlags webFlags=null)
Internally used to cache and set properties (including well known properties).
Requires being in a room (because this attempts to send an operation which will fail otherwise).
bool Photon.Realtime.LoadBalancingClient.OpSetPropertyOfRoom(byte propCode, object value)
bool Photon.Realtime.LoadBalancingClient.OpSetPropertiesOfRoom(Hashtable gameProperties, Hashtable expectedProperties=null, WebFlags webFlags=null)
Internally used to cache and set properties (including well known properties).
Requires being in a room (because this attempts to send an operation which will fail otherwise).
virtual Player Photon.Realtime.LoadBalancingClient.CreatePlayer(string actorName, int actorNumber, bool isLocal, Hashtable actorProperties)
Factory method to create a player instance - override to get your own player-type with custom features.
actorName The name of the player to be created. actorNumber The player ID (a.k.a. actorNumber) of the player to be created. isLocal Sets the distinction if the player to be created is your player or if its assigned to someone else. actorProperties The custom properties for this new player The newly created player
virtual Room Photon.Realtime.LoadBalancingClient.CreateRoom(string roomName, RoomOptions opt)
Internal "factory" method to create a room-instance.
void Photon.Realtime.LoadBalancingClient.UpdateCallbackTargets()
Applies queued callback cahnges from a queue to the actual containers.
Will cause exceptions if used while callbacks execute. There is no explicit check that this is not called during callbacks, however the implemented, private logic takes care of this.
static string Photon.Realtime.LoadBalancingClient.ReplacePortWithAlternative(string address, ushort replacementPort)