Photon::Pun::Simple::SyncContact
Frame Photon.Pun.Simple.SyncContact.currentState
IContactTrigger Photon.Pun.Simple.SyncContact.contactTrigger
Referenced by Photon.Pun.Simple.SyncContact.ApplySnapshot, Photon.Pun.Simple.SyncContact.Contact, Photon.Pun.Simple.SyncContact.OnAwake.
Rigidbody Photon.Pun.Simple.SyncContact.rb
Referenced by Photon.Pun.Simple.SyncContact.OnAwake.
Rigidbody2D Photon.Pun.Simple.SyncContact.rb2d
Referenced by Photon.Pun.Simple.SyncContact.OnAwake.
bool Photon.Pun.Simple.SyncContact._hasRigidbody
Referenced by Photon.Pun.Simple.SyncContact.OnAwake.
Queue<ContactEvent> Photon.Pun.Simple.SyncContact.queuedContactEvents
Referenced by Photon.Pun.Simple.SyncContact.EnqueueEvent, Photon.Pun.Simple.SyncContact.OnCaptureCurrentState.
bool Photon.Pun.Simple.SyncContact.HasRigidbody
GameObject Photon.Pun.Simple.SyncContact.VisiblePickupObj
override void Photon.Pun.Simple.SyncContact.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
References Photon.Pun.Simple.SyncContact._hasRigidbody, Photon.Pun.Simple.SyncContact.contactTrigger, Photon.Pun.Simple.SyncContact.rb, Photon.Pun.Simple.SyncContact.rb2d.
virtual void Photon.Pun.Simple.SyncContact.SyncContactEvent(ContactEvent contactEvent)
References Photon.Pun.Simple.SyncContact.EnqueueEvent, Photon.Pun.Simple.NetComponent.IsMine.
virtual void Photon.Pun.Simple.SyncContact.OnCaptureCurrentState(int frameId)
frameId amActingAuthority realm
References Photon.Pun.Simple.SyncContact.Contact, Photon.Pun.Simple.SyncContact.Frame.contactRecords, Photon.Pun.Simple.ContactEvent.contactSystem, Photon.Pun.Simple.ContactEvent.contactType, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncObject< SyncContact.Frame >::frames, Photon.Pun.Simple.SyncContact.queuedContactEvents, Photon.Pun.Simple.IContactSystem.SystemIndex, Photon.Pun.Simple.IContactSystem.ViewID.
virtual SerializationFlags Photon.Pun.Simple.SyncContact.OnNetSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
References Photon.Pun.Simple.SyncContact.Frame.contactRecords, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncObject< SyncContact.Frame >::frames.
SerializationFlags Photon.Pun.Simple.SyncContact.OnNetDeserialize(int originFrameId, byte[] buffer, ref int bitposition, FrameArrival arrival)
References Photon.Pun.Simple.SyncContact.Frame.contactRecords, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncObject< SyncContact.Frame >::frames.
virtual bool Photon.Pun.Simple.SyncContact.EnqueueEvent(ContactEvent contactEvent)
References Photon.Pun.Simple.SyncContact.queuedContactEvents.
Referenced by Photon.Pun.Simple.SyncContact.SyncContactEvent.
virtual Consumption Photon.Pun.Simple.SyncContact.Contact(ContactEvent contactEvent)
Attempt a trigger.
Returns true if a triggerEvent results in a valid collision.
References Photon.Pun.Simple.IContactTrigger.ContactCallbacks, Photon.Pun.Simple.SyncContact.contactTrigger.
Referenced by Photon.Pun.Simple.SyncContact.ApplySnapshot, Photon.Pun.Simple.SyncContact.OnCaptureCurrentState.
virtual void Photon.Pun.Simple.SyncContact.Consume(Frame frame, ContactEvent contactEvent, Consumption consumed)
Referenced by Photon.Pun.Simple.SyncContact.ApplySnapshot.
override void Photon.Pun.Simple.SyncContact.ApplySnapshot(Frame snapframe, Frame targframe, bool snapIsValid, bool targIsValid)
References Photon.Pun.Simple.SyncContact.Consume, Photon.Pun.Simple.SyncContact.Contact, Photon.Pun.Simple.SyncContact.Frame.contactRecords, Photon.Pun.Simple.SyncContact.ContactRecord.contactSystemIndex, Photon.Pun.Simple.SyncContact.ContactRecord.contactSystemViewID, Photon.Pun.Simple.SyncContact.contactTrigger, Photon.Pun.Simple.SyncContact.ContactRecord.contactType, Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.ContactManager.GetContacting, Photon.Pun.PhotonNetwork.GetPhotonView.
static int Photon.Pun.Simple.SyncContact.ConvertMaskToIndex(int mask)
static int Photon.Pun.Simple.SyncContact.ConvertIndexToMask(int index)