Photon::Pun::Demo::Cockpit::PunCockpit
PunCockpit Photon.Pun.Demo.Cockpit.PunCockpit.Instance
Referenced by Photon.Pun.Demo.Cockpit.PunCockpitEmbed.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionListReceived, Photon.Pun.Demo.Cockpit.PunCockpit.Start, Photon.Pun.Demo.Cockpit.GameVersionField.SubmitForm.
bool Photon.Pun.Demo.Cockpit.PunCockpit.Embedded
string Photon.Pun.Demo.Cockpit.PunCockpit.EmbeddedGameTitle
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
bool Photon.Pun.Demo.Cockpit.PunCockpit.debug
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectOffline, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom, Photon.Pun.Demo.Cockpit.PunCockpit.Disconnect, Photon.Pun.Demo.Cockpit.PunCockpit.JoinLobby, Photon.Pun.Demo.Cockpit.PunCockpit.LoadLevel, Photon.Pun.Demo.Cockpit.PunCockpit.OnConnected, Photon.Pun.Demo.Cockpit.PunCockpit.OnConnectedToMaster, Photon.Pun.Demo.Cockpit.PunCockpit.OnCreateRoomFailed, Photon.Pun.Demo.Cockpit.PunCockpit.OnDisconnected, Photon.Pun.Demo.Cockpit.PunCockpit.OnDropdownConnectAs, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedLobby, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinRandomFailed, Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftLobby, Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftRoom, Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionListReceived, Photon.Pun.Demo.Cockpit.PunCockpit.OnRoomPropertiesUpdate, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions, Photon.Pun.Demo.Cockpit.PunCockpit.SetCleanupCacheOnLeave, Photon.Pun.Demo.Cockpit.PunCockpit.SetDeleteNullProperties, Photon.Pun.Demo.Cockpit.PunCockpit.SetEmptyRoomTtlRoomOption, Photon.Pun.Demo.Cockpit.PunCockpit.SetIsOpen, Photon.Pun.Demo.Cockpit.PunCockpit.SetIsVisible, Photon.Pun.Demo.Cockpit.PunCockpit.SetMaxPlayersRoomOption, Photon.Pun.Demo.Cockpit.PunCockpit.SetPlayerTtlRoomOption, Photon.Pun.Demo.Cockpit.PunCockpit.SetPluginsRoomOption, Photon.Pun.Demo.Cockpit.PunCockpit.SetPublishUserId, Photon.Pun.Demo.Cockpit.PunCockpit.SetResetBestRegionCodeInPreferences, Photon.Pun.Demo.Cockpit.PunCockpit.SetRoomCustomProperty.
Text Photon.Pun.Demo.Cockpit.PunCockpit.Title
Text Photon.Pun.Demo.Cockpit.PunCockpit.StateText
Text Photon.Pun.Demo.Cockpit.PunCockpit.UserIdText
CanvasGroup Photon.Pun.Demo.Cockpit.PunCockpit.MinimalCanvasGroup
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMaximalPanel, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMinimalPanel.
CanvasGroup Photon.Pun.Demo.Cockpit.PunCockpit.MaximalCanvasGroup
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMaximalPanel, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMinimalPanel.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.MinimizeButton
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.MinimalUIEmbeddHelp
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMaximalPanel.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.ConnectingLabel
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.ConnectionPanel
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.AdvancedConnectionPanel
Dropdown Photon.Pun.Demo.Cockpit.PunCockpit.ConnectAsDropDown
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.InfosPanel
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.RequestInfosPanel.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.MinimalUiInfosPanel
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ToggleInfosInMinimalPanel.
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.LobbyPanel
Selectable Photon.Pun.Demo.Cockpit.PunCockpit.JoinLobbyButton
RoomListView Photon.Pun.Demo.Cockpit.PunCockpit.RoomListManager
FriendListView Photon.Pun.Demo.Cockpit.PunCockpit.FriendListManager
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.RoomListMatchMakingForm
GameObject Photon.Pun.Demo.Cockpit.PunCockpit.GamePanel
PlayerListView Photon.Pun.Demo.Cockpit.PunCockpit.PlayerListManager
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.LeaveRoom.
PlayerDetailsController Photon.Pun.Demo.Cockpit.PunCockpit.PlayerDetailsManager
InputField Photon.Pun.Demo.Cockpit.PunCockpit.RoomCustomPropertyInputfield
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnRoomPropertiesUpdate.
string Photon.Pun.Demo.Cockpit.PunCockpit.GameVersionOverride
The game version override.
This is one way to let the user define the gameversion, and set it properly right after we call connect to override the server settings Check ConnectAndJoinRandom.cs for another example of gameversion overriding
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.Demo.Cockpit.GameVersionField.SubmitForm.
bool Photon.Pun.Demo.Cockpit.PunCockpit.ResetBestRegionCodeInPreferences
The reset flag for best cloud ServerSettings.
This is one way to let the user define if bestcloud cache should be reseted when connecting.
int Photon.Pun.Demo.Cockpit.PunCockpit.MaxPlayers
int Photon.Pun.Demo.Cockpit.PunCockpit.PlayerTtl
int Photon.Pun.Demo.Cockpit.PunCockpit.EmptyRoomTtl
string Photon.Pun.Demo.Cockpit.PunCockpit.Plugins
bool Photon.Pun.Demo.Cockpit.PunCockpit.PublishUserId
bool Photon.Pun.Demo.Cockpit.PunCockpit.IsVisible
bool Photon.Pun.Demo.Cockpit.PunCockpit.IsOpen
bool Photon.Pun.Demo.Cockpit.PunCockpit.CleanupCacheOnLeave
bool Photon.Pun.Demo.Cockpit.PunCockpit.DeleteNullProperties
IntInputField Photon.Pun.Demo.Cockpit.PunCockpit.PlayerTtlField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
IntInputField Photon.Pun.Demo.Cockpit.PunCockpit.EmptyRoomTtlField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
IntInputField Photon.Pun.Demo.Cockpit.PunCockpit.MaxPlayersField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
StringInputField Photon.Pun.Demo.Cockpit.PunCockpit.PluginsField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
BoolInputField Photon.Pun.Demo.Cockpit.PunCockpit.PublishUserIdField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
BoolInputField Photon.Pun.Demo.Cockpit.PunCockpit.IsVisibleField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
BoolInputField Photon.Pun.Demo.Cockpit.PunCockpit.IsOpenField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
BoolInputField Photon.Pun.Demo.Cockpit.PunCockpit.CleanupCacheOnLeaveField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
BoolInputField Photon.Pun.Demo.Cockpit.PunCockpit.DeleteNullPropertiesField
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
FriendListView.FriendDetail [] Photon.Pun.Demo.Cockpit.PunCockpit.FriendsList
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnDropdownConnectAs, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
CanvasGroup Photon.Pun.Demo.Cockpit.PunCockpit.ModalWindow
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
RegionListView Photon.Pun.Demo.Cockpit.PunCockpit.RegionListView
Text Photon.Pun.Demo.Cockpit.PunCockpit.RegionListLoadingFeedback
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionListReceived, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions.
string Photon.Pun.Demo.Cockpit.PunCockpit.UserId
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Connect, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.Demo.Cockpit.PunCockpit.OnConnected, Photon.Pun.Demo.Cockpit.PunCockpit.OnDropdownConnectAs, Photon.Pun.Demo.Cockpit.PunCockpit.OnUserIdSubmited, Photon.Pun.Demo.Cockpit.PunCockpit.ReConnect, Photon.Pun.Demo.Cockpit.PunCockpit.ReconnectAndRejoin, Photon.Pun.Demo.Cockpit.PunCockpit.Start, Photon.Pun.Demo.Cockpit.UserIdField.SubmitForm.
LoadBalancingClient Photon.Pun.Demo.Cockpit.PunCockpit._lbc
bool Photon.Pun.Demo.Cockpit.PunCockpit._regionPingProcessActive
List<Region> Photon.Pun.Demo.Cockpit.PunCockpit.RegionsList
string Photon.Pun.Demo.Cockpit.PunCockpit.roomNameToEnter
void Photon.Pun.Demo.Cockpit.PunCockpit.Start()
References Photon.Pun.Demo.Cockpit.PunCockpit.CleanupCacheOnLeaveField, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectAsDropDown, Photon.Pun.Demo.Cockpit.PunCockpit.DeleteNullPropertiesField, Photon.Pun.Demo.Cockpit.PunCockpit.EmbeddedGameTitle, Photon.Pun.Demo.Cockpit.PunCockpit.EmptyRoomTtlField, Photon.Pun.Demo.Cockpit.PunCockpit.FriendsList, Photon.Pun.PhotonNetwork.InLobby, Photon.Pun.Demo.Cockpit.PunCockpit.Instance, Photon.Pun.PhotonNetwork.IsConnected, Photon.Pun.Demo.Cockpit.PunCockpit.IsOpenField, Photon.Pun.Demo.Cockpit.PunCockpit.IsVisibleField, Photon.Pun.Demo.Shared.DocLinks.Language, Photon.Pun.Demo.Cockpit.PunCockpit.MaximalCanvasGroup, Photon.Pun.Demo.Cockpit.PunCockpit.MaxPlayersField, Photon.Pun.Demo.Cockpit.PunCockpit.MinimizeButton, Photon.Pun.Demo.Cockpit.PunCockpit.ModalWindow, Photon.Pun.Demo.Cockpit.PunCockpit.OnConnectedToMaster, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedLobby, Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.PlayerTtlField, Photon.Pun.Demo.Cockpit.PunCockpit.PluginsField, Photon.Pun.Demo.Shared.DocLinks.Product, Photon.Pun.Demo.Cockpit.PunCockpit.PublishUserIdField, Photon.Pun.PhotonNetwork.Server, Photon.Pun.Demo.Cockpit.BoolInputField.SetValue, Photon.Pun.Demo.Cockpit.IntInputField.SetValue, Photon.Pun.Demo.Cockpit.StringInputField.SetValue, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMaximalPanel, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMinimalPanel, Photon.Pun.Demo.Cockpit.PunCockpit.SwitchToSimpleConnection, Photon.Pun.Demo.Cockpit.PunCockpit.UserId, Photon.Pun.Demo.Shared.DocLinks.Version.
void Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMinimalPanel()
References Photon.Pun.Demo.Cockpit.PunCockpit.MaximalCanvasGroup, Photon.Pun.Demo.Cockpit.PunCockpit.MinimalCanvasGroup.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpitEmbed.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PunCockpit.Start.
void Photon.Pun.Demo.Cockpit.PunCockpit.SwitchtoMaximalPanel()
References Photon.Pun.Demo.Cockpit.PunCockpit.MaximalCanvasGroup, Photon.Pun.Demo.Cockpit.PunCockpit.MinimalCanvasGroup, Photon.Pun.Demo.Cockpit.PunCockpit.MinimalUIEmbeddHelp.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
void Photon.Pun.Demo.Cockpit.PunCockpit.SwitchToAdvancedConnection()
void Photon.Pun.Demo.Cockpit.PunCockpit.SwitchToSimpleConnection()
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
void Photon.Pun.Demo.Cockpit.PunCockpit.ToggleInfosInMinimalPanel()
References Photon.Pun.Demo.Cockpit.PunCockpit.MinimalUiInfosPanel.
void Photon.Pun.Demo.Cockpit.PunCockpit.RequestInfosPanel(GameObject Parent)
References Photon.Pun.Demo.Cockpit.PunCockpit.InfosPanel.
void Photon.Pun.Demo.Cockpit.PunCockpit.OnUserIdSubmited(string userId)
References Photon.Pun.Demo.Cockpit.PunCockpit.Connect, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetPlayerTtlRoomOption(int value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetEmptyRoomTtlRoomOption(int value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetMaxPlayersRoomOption(int value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetPluginsRoomOption(string value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetPublishUserId(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetIsVisible(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetIsOpen(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetResetBestRegionCodeInPreferences(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetCleanupCacheOnLeave(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetDeleteNullProperties(bool value)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
void Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions()
in progress, not fully working
References Photon.Realtime.LoadBalancingClient.AddCallbackTarget, Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.AppSettings.AppIdRealtime, Photon.Pun.ServerSettings.AppSettings, Photon.Realtime.LoadBalancingClient.ConnectToNameServer, Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.PunCockpit.ModalWindow, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.Demo.Cockpit.PunCockpit.RegionListLoadingFeedback, Photon.Realtime.LoadBalancingClient.StateChanged.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionListReceived(RegionHandler regionHandler)
Called when the Name Server provided a list of regions for your title.
Check the RegionHandler class description, to make use of the provided values. regionHandler The currently used RegionHandler.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.PunCockpit.Instance, Photon.Realtime.RegionHandler.PingMinimumOfRegions, Photon.Pun.Demo.Cockpit.PunCockpit.RegionListLoadingFeedback.
void Photon.Pun.Demo.Cockpit.PunCockpit.CloseRegionListView()
References Photon.Realtime.LoadBalancingClient.Disconnect, Photon.Pun.Demo.Cockpit.RegionListView.ResetList.
void Photon.Pun.Demo.Cockpit.PunCockpit.LoadLevel(string level)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.LoadLevel.
void Photon.Pun.Demo.Cockpit.PunCockpit.SetRoomCustomProperty(string value)
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Realtime.Room.SetCustomProperties.
void Photon.Pun.Demo.Cockpit.PunCockpit.JoinRoom(string roomName)
References Photon.Pun.PhotonNetwork.JoinRoom, Photon.Pun.Demo.Cockpit.RoomListView.ResetList.
void Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom()
References Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom.
void Photon.Pun.Demo.Cockpit.PunCockpit.CreateRoom(string roomName, string lobbyName="MyLobby", LobbyType lobbyType=LobbyType.SqlLobby, string[] expectedUsers=null)
References Photon.Pun.PhotonNetwork.CreateRoom, Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.RoomListView.ResetList.
void Photon.Pun.Demo.Cockpit.PunCockpit.JoinRandomRoom()
References Photon.Pun.PhotonNetwork.JoinRandomRoom.
void Photon.Pun.Demo.Cockpit.PunCockpit.LeaveRoom()
References Photon.Pun.PhotonNetwork.LeaveRoom, Photon.Pun.Demo.Cockpit.PunCockpit.PlayerListManager, Photon.Pun.Demo.Cockpit.PlayerListView.ResetList.
void Photon.Pun.Demo.Cockpit.PunCockpit.Connect()
References Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Realtime.AuthenticationValues.UserId, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnUserIdSubmited.
void Photon.Pun.Demo.Cockpit.PunCockpit.ReConnect()
References Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.Reconnect, Photon.Realtime.AuthenticationValues.UserId, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
void Photon.Pun.Demo.Cockpit.PunCockpit.ReconnectAndRejoin()
References Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.ReconnectAndRejoin, Photon.Realtime.AuthenticationValues.UserId, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
void Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer()
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.AppSettings.AppIdRealtime, Photon.Pun.ServerSettings.AppSettings, Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.ConnectToBestCloudServer, Photon.Pun.PhotonNetwork.GameVersion, Photon.Pun.Demo.Cockpit.PunCockpit.GameVersionOverride, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.ServerSettings.ResetBestRegionCodeInPreferences, Photon.Realtime.AuthenticationValues.UserId, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
void Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion(string region)
References Photon.Realtime.LoadBalancingClient.AppId, Photon.Realtime.AppSettings.AppIdRealtime, Photon.Pun.ServerSettings.AppSettings, Photon.Pun.PhotonNetwork.AuthValues, Photon.Pun.PhotonNetwork.ConnectToRegion, Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.GameVersion, Photon.Pun.Demo.Cockpit.PunCockpit.GameVersionOverride, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Realtime.AuthenticationValues.UserId, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
void Photon.Pun.Demo.Cockpit.PunCockpit.ConnectOffline()
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.OfflineMode.
void Photon.Pun.Demo.Cockpit.PunCockpit.JoinLobby()
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.JoinLobby.
void Photon.Pun.Demo.Cockpit.PunCockpit.Disconnect()
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.Disconnect.
void Photon.Pun.Demo.Cockpit.PunCockpit.OpenDashboard()
void Photon.Pun.Demo.Cockpit.PunCockpit.OnDropdownConnectAs(int dropdownIndex)
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.PunCockpit.FriendsList, Photon.Pun.Demo.Cockpit.PunCockpit.UserId, Photon.Pun.Demo.Cockpit.Forms.UserIdUiForm.UserIdPlayerPref.
void Photon.Pun.Demo.Cockpit.PunCockpit.OnLobbyToolsViewTabChanged(string tabId)
void Photon.Pun.Demo.Cockpit.PunCockpit.OnSelectPlayer()
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnConnected()
Called to signal that the raw connection got established but before the client can call operation on the server.
After the (low level transport) connection is established, the client will automatically send the Authentication operation, which needs to get a response before the client can call other operations. Your logic should wait for either: OnRegionListReceived or OnConnectedToMaster. This callback is useful to detect if the server can be reached at all (technically). Most often, it's enough to implement OnDisconnected(). This is not called for transitions from the masterserver to game servers.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.NickName, Photon.Pun.Demo.Cockpit.PunCockpit.UserId.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnDisconnected(DisconnectCause cause)
Called after disconnecting from the Photon server.
It could be a failure or intentional The reason for this disconnect is provided as DisconnectCause.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnConnectedToMaster()
Called when the client is connected to the Master Server and ready for matchmaking and other tasks.
The list of available rooms won't become available unless you join a lobby via LoadBalancingClient.OpJoinLobby. You can join rooms and create them even without being in a lobby. The default lobby is used in that case.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.OfflineMode.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedLobby()
Called on entering a lobby on the Master Server.
The actual room-list updates will call OnRoomListUpdate. While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud). The room list gets available via OnRoomListUpdate.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnRoomPropertiesUpdate(Hashtable propertiesThatChanged)
Called when a room's custom properties changed.
The propertiesThatChanged contains all that was set via Room.SetCustomProperties. Since v1.25 this method has one parameter: Hashtable propertiesThatChanged. Changing properties must be done by Room.SetCustomProperties, which causes this callback locally, too. propertiesThatChanged
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.PunCockpit.RoomCustomPropertyInputfield.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftLobby()
Called after leaving a lobby.
When you leave a lobby, OpCreateRoom and OpJoinRandomRoom automatically refer to the default lobby.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.Demo.Cockpit.RoomListView.ResetList.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
The most common cause to fail creating a room, is when a title relies on fixed room-names and the room already exists. returnCode Operation ReturnCode from the server. message Debug message for the error.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinRandomFailed(short returnCode, string message)
Called when a previous OpJoinRandom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms. returnCode Operation ReturnCode from the server. message Debug message for the error.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.PhotonNetwork.OfflineMode, Photon.Pun.Demo.Cockpit.PlayerListView.ResetList, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.Start.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). returnCode Operation ReturnCode from the server. message Debug message for the error.
References Photon.Realtime.ErrorCode.JoinFailedFoundInactiveJoiner, Photon.Pun.PhotonNetwork.RejoinRoom.
override void Photon.Pun.Demo.Cockpit.PunCockpit.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
References Photon.Pun.Demo.Cockpit.PunCockpit.debug, Photon.Pun.PhotonNetwork.OfflineMode.
void Photon.Pun.Demo.Cockpit.PunCockpit.Update()
void Photon.Pun.Demo.Cockpit.PunCockpit.OnStateChanged(ClientState previousState, ClientState state)
void Photon.Pun.Demo.Cockpit.PunCockpit.OnRegionsPinged(RegionHandler regionHandler)
IEnumerator Photon.Pun.Demo.Cockpit.PunCockpit.OnDropdownConnectAs_CB()
void Photon.Pun.Demo.Cockpit.PunCockpit.SetUpLobbyGenericUI()
RoomOptions Photon.Pun.Demo.Cockpit.PunCockpit.GetRoomOptions()