Photon::Pun::Simple::NetObject
bool Photon.Pun.Simple.NetObject.skipWhenEmpty
Referenced by Photon.Pun.Simple.NetObject.OnNetSerialize.
bool Photon.Pun.Simple.NetObject.ignoreNonControllerUpdates
bool Photon.Pun.Simple.NetObject.resimulateLateArrivals
Referenced by Photon.Pun.Simple.NetObject.OnDeserialize.
Rigidbody Photon.Pun.Simple.NetObject._rigidbody
Referenced by Photon.Pun.Simple.NetObject.Awake.
Rigidbody2D Photon.Pun.Simple.NetObject._rigidbody2D
Referenced by Photon.Pun.Simple.NetObject.Awake.
int Photon.Pun.Simple.NetObject.viewID
Referenced by Photon.Pun.Simple.NetObject.OnNetSerialize.
bool Photon.Pun.Simple.NetObject.SkipWhenEmpty
Referenced by Photon.Pun.Simple.NetObject.OnNetSerialize.
bool Photon.Pun.Simple.NetObject.IgnoreNonControllerUpdates
bool Photon.Pun.Simple.NetObject.ResimulateLateArrivals
Rigidbody Photon.Pun.Simple.NetObject.Rb
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.NetComponent.EnsureComponentsDependenciesExist, Photon.Pun.Simple.OnStateChangeKinematic.OnAwake.
Rigidbody2D Photon.Pun.Simple.NetObject.Rb2D
Referenced by Photon.Pun.Simple.SyncState.ChangeState, Photon.Pun.Simple.NetComponent.EnsureComponentsDependenciesExist, Photon.Pun.Simple.OnStateChangeKinematic.OnAwake.
bool Photon.Pun.Simple.NetObject.NetObjDictsLocked
Prevent objects from being added or removed from the activeControlledNetObjs dictionary.
Any changes are queued and applied after unlock.
bool? Photon.Pun.Simple.NetObject.AllObjsAreReady
Referenced by Photon.Pun.Simple.NetObject.OnChangeAuthority, Photon.Pun.Simple.ContactTrigger.OnContact, Photon.Pun.Simple.NetObject.OnPackObjReadyChange, Photon.Pun.Simple.NetObject.OnSyncObjReadyChange.
int Photon.Pun.Simple.NetObject.ViewID
NonAllocDictionary<int, NetObject> Photon.Pun.Simple.NetObject.activeControlledNetObjs
NonAllocDictionary<int, NetObject> Photon.Pun.Simple.NetObject.activeUncontrolledNetObjs
Queue<NetObject> Photon.Pun.Simple.NetObject.pendingActiveNetObjDictChanges
bool Photon.Pun.Simple.NetObject.netObjDictsLocked
List<Component> Photon.Pun.Simple.NetObject.reusableComponents
readonly List<IOnJoinedRoom> Photon.Pun.Simple.NetObject.onJoinedRoomCallbacks
readonly List<IOnAwake> Photon.Pun.Simple.NetObject.onAwakeCallbacks
readonly List<IOnStart> Photon.Pun.Simple.NetObject.onStartCallbacks
Dictionary<Component, int> Photon.Pun.Simple.NetObject.colliderLookup
TODO: Pool these?
Referenced by Photon.Pun.Simple.Internal.NetObjColliderExt.IndexColliders.
List<Component> Photon.Pun.Simple.NetObject.indexedColliders
Referenced by Photon.Pun.Simple.Internal.NetObjColliderExt.IndexColliders.
int Photon.Pun.Simple.NetObject.bitsForColliderIndex
Referenced by Photon.Pun.Simple.Internal.NetObjColliderExt.IndexColliders.
FastBitMask128 Photon.Pun.Simple.NetObject.frameValidMask
Referenced by Photon.Pun.Simple.NetObject.Awake, Photon.Pun.Simple.SyncObject< TFrame >.ConstructMissingFrame, Photon.Pun.Simple.NetObject.OnDeserialize, Photon.Pun.Simple.NetObject.OnSnapshot.
int [] Photon.Pun.Simple.NetObject.originHistory
Record of the connection that produced the each deserialized frame.
Index is the frameId.
Referenced by Photon.Pun.Simple.NetObject.Awake, Photon.Pun.Simple.SyncObject< TFrame >.OnAuthorityChanged, Photon.Pun.Simple.NetObject.OnDeserialize.
FastBitMask128 Photon.Pun.Simple.NetObject.syncObjReadyMask
Referenced by Photon.Pun.Simple.NetObject.OnPackObjReadyChange, Photon.Pun.Simple.NetObject.OnSyncObjReadyChange.
FastBitMask128 Photon.Pun.Simple.NetObject.packObjReadyMask
Referenced by Photon.Pun.Simple.NetObject.OnPackObjReadyChange, Photon.Pun.Simple.NetObject.OnSyncObjReadyChange.
PhotonView Photon.Pun.Simple.NetObject.photonView
Referenced by Photon.Pun.Simple.NetObject.Awake, Photon.Pun.Simple.NetObject.OnControllerChange, Photon.Pun.Simple.NetObject.OnInterpolate, Photon.Pun.Simple.NetObject.OnJoinedRoom, Photon.Pun.Simple.NetObject.OnNetSerialize, Photon.Pun.Simple.NetObject.OnOwnerChange, Photon.Pun.Simple.NetObject.OnSnapshot.
readonly List<IOnPreUpdate> Photon.Pun.Simple.NetObject.onPreUpdateCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnPreUpdate.
readonly List<IOnAuthorityChanged> Photon.Pun.Simple.NetObject.onAuthorityChangedCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnChangeAuthority.
readonly List<IOnNetSerialize> Photon.Pun.Simple.NetObject.onNetSerializeCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnDeserialize, Photon.Pun.Simple.NetObject.OnSerialize.
readonly List<IOnCriticallyLateFrame> Photon.Pun.Simple.NetObject.onCriticallyLateFrameCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnDeserialize.
readonly List<IOnIncrementFrame> Photon.Pun.Simple.NetObject.onIncrementFramesCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnIncrementFrame.
readonly List<IOnSnapshot> Photon.Pun.Simple.NetObject.onSnapshotCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnDeserialize, Photon.Pun.Simple.NetObject.OnSnapshot.
readonly List<IOnQuantize> Photon.Pun.Simple.NetObject.onQuantizeCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnQuantize.
readonly List<IOnInterpolate> Photon.Pun.Simple.NetObject.onInterpolateCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnInterpolate.
readonly List<IOnCaptureState> Photon.Pun.Simple.NetObject.onCaptureCurrentStateCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnCaptureCurrentState.
readonly List<IOnPreSimulate> Photon.Pun.Simple.NetObject.onPreSimulateCallbacks
Referenced by Photon.Pun.Simple.AutoMountHitscan.OnAuthorityChanged, Photon.Pun.Simple.NetObject.OnPreSimulate.
readonly List<IOnPostSimulate> Photon.Pun.Simple.NetObject.onPostSimulateCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnPostSimulate.
readonly List<IOnPreQuit> Photon.Pun.Simple.NetObject.onPreQuitCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnPreQuit.
readonly List<IOnPreNetDestroy> Photon.Pun.Simple.NetObject.onPreNetDestroyCallbacks
Referenced by Photon.Pun.Simple.NetObject.OnPreNetDestroy.
readonly Dictionary<Component, int> Photon.Pun.Simple.NetObject.packObjIndexLookup
bool Photon.Pun.Simple.NetObject._allObjsAreReady
readonly List<IOnEnable> Photon.Pun.Simple.NetObject.onEnableCallbacks
readonly List<IOnDisable> Photon.Pun.Simple.NetObject.onDisableCallbacks
readonly List<IOnNetObjReady> Photon.Pun.Simple.NetObject.onNetObjReadyCallbacks
readonly List<SyncObject> Photon.Pun.Simple.NetObject.syncObjects
readonly List<PackObjRecord> Photon.Pun.Simple.NetObject.packObjects
bool Photon.Pun.Simple.NetObject.processedInitialBacklog
float Photon.Pun.Simple.NetObject.firstDeserializeTime
void Photon.Pun.Simple.NetObject.OnSyncObjReadyChange(SyncObject sobj, ReadyStateEnum readyState)
References Photon.Utilities.FastBitMask128.AllAreTrue, Photon.Pun.Simple.NetObject.AllObjsAreReady, Photon.Pun.Simple.NetObject.packObjReadyMask, Photon.Pun.Simple.SyncObject< TFrame >.SyncObjIndex, Photon.Pun.Simple.NetObject.syncObjReadyMask.
void Photon.Pun.Simple.NetObject.OnPackObjReadyChange(Component pobj, ReadyStateEnum readyState)
References Photon.Utilities.FastBitMask128.AllAreTrue, Photon.Pun.Simple.NetObject.AllObjsAreReady, Photon.Pun.Simple.NetObject.packObjReadyMask, Photon.Pun.Simple.NetObject.syncObjReadyMask.
void Photon.Pun.Simple.NetObject.OnPreQuit()
References Photon.Pun.Simple.NetObject.onPreQuitCallbacks.
void Photon.Pun.Simple.NetObject.OnPreNetDestroy(PhotonView rootView)
This method is called before Destroy() is initiated for a networked object.
rootView
References Photon.Pun.Simple.NetObject.onPreNetDestroyCallbacks.
virtual void Photon.Pun.Simple.NetObject.PrepareForDestroy()
TODO: likely not needed if moving UnmountAll to OnDisable.
Destroy an object in a way that respects Simple.
void Photon.Pun.Simple.NetObject.OnOwnerChange(Realtime.Player newOwner, Realtime.Player previousOwner)
References Photon.Pun.PhotonView.IsMine, Photon.Pun.Simple.NetObject.OnChangeAuthority, Photon.Pun.Simple.NetObject.photonView, Photon.Realtime.Realtime, Photon.Pun.PhotonView.ViewID.
void Photon.Pun.Simple.NetObject.OnControllerChange(Realtime.Player newController, Realtime.Player previousController)
References Photon.Pun.PhotonView.IsMine, Photon.Pun.Simple.NetObject.OnChangeAuthority, Photon.Pun.Simple.NetObject.photonView, Photon.Realtime.Realtime, Photon.Pun.PhotonView.ViewID.
void Photon.Pun.Simple.NetObject.OnFriendListUpdate(List< FriendInfo > friendList)
Called when the server sent the response to a FindFriends request.
After calling OpFindFriends, the Master Server will cache the friend list and send updates to the friend list. The friends includes the name, userId, online state and the room (if any) for each requested user/friend. Use the friendList to update your UI and store it, if the UI should highlight changes.
void Photon.Pun.Simple.NetObject.OnCreatedRoom()
Called when this client created a room and entered it.
OnJoinedRoom() will be called as well. This callback is only called on the client which created a room (see OpCreateRoom). As any client might close (or drop connection) anytime, there is a chance that the creator of a room does not execute OnCreatedRoom. If you need specific room properties or a "start signal", implement OnMasterClientSwitched() and make each new MasterClient check the room's state.
void Photon.Pun.Simple.NetObject.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
Creating a room may fail for various reasons. Most often, the room already exists (roomname in use) or the RoomOptions clash and it's impossible to create the room. When creating a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.Simple.NetObject.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References Photon.Pun.PhotonView.IsMine, Photon.Pun.Simple.NetObject.OnChangeAuthority, Photon.Pun.Simple.NetObject.OnJoinedRoom, Photon.Pun.Simple.NetObject.photonView.
Referenced by Photon.Pun.Simple.NetObject.OnJoinedRoom.
void Photon.Pun.Simple.NetObject.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
Joining a room may fail for various reasons. Most often, the room is full or does not exist anymore (due to someone else being faster or closing the room). When joining a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.Simple.NetObject.OnJoinRandomFailed(short returnCode, string message)
Called when a previous OpJoinRandom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). This operation is only ever sent to the Master Server. Once a room is found by the Master Server, the client will head off to the designated Game Server and use the operation Join on the Game Server. When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.Simple.NetObject.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
void Photon.Pun.Simple.NetObject.OnChangeAuthority(bool isMine, bool controllerHasChanged)
References Photon.Pun.Simple.NetObject.AllObjsAreReady, Photon.Pun.Simple.NetObject.onAuthorityChangedCallbacks.
Referenced by Photon.Pun.Simple.NetObject.OnControllerChange, Photon.Pun.Simple.NetObject.OnJoinedRoom, Photon.Pun.Simple.NetObject.OnOwnerChange.
void Photon.Pun.Simple.NetObject.RemoveInterfaces(Component comp)
Remove a component from all NetObj callback lists.
comp
Referenced by Photon.Pun.Simple.MountSwitcher.OnAwake.
void Photon.Pun.Simple.NetObject.OnPreUpdate()
References Photon.Pun.Simple.NetObject.onPreUpdateCallbacks.
SerializationFlags Photon.Pun.Simple.NetObject.GenerateMessage(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
Generate a state tick.
frameId
References Photon.Pun.Simple.NetObject.OnCaptureCurrentState, Photon.Pun.Simple.NetObject.OnQuantize, Photon.Pun.Simple.NetObject.OnSerialize.
Referenced by Photon.Pun.Simple.NetObject.OnNetSerialize.
SerializationFlags Photon.Pun.Simple.NetObject.OnSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
Serialize all SyncObjs on this NetObj
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.NetObject.onNetSerializeCallbacks.
Referenced by Photon.Pun.Simple.NetObject.GenerateMessage.
void Photon.Pun.Simple.NetObject.OnDeserialize(int connId, int originFrameId, byte[] buffer, ref int bitposition, bool hasData, FrameArrival arrival)
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.NetObject.frameValidMask, Photon.Pun.Simple.NetObject.onCriticallyLateFrameCallbacks, Photon.Pun.Simple.NetObject.onNetSerializeCallbacks, Photon.Pun.Simple.NetObject.onSnapshotCallbacks, Photon.Pun.Simple.NetObject.originHistory, Photon.Pun.Simple.NetObject.resimulateLateArrivals.
Referenced by Photon.Pun.Simple.NetMaster.ReceiveMessage.
void Photon.Pun.Simple.NetObject.OnPreSimulate(int frameId, int _currSubFrameId)
References Photon.Pun.Simple.NetObject.onPreSimulateCallbacks.
void Photon.Pun.Simple.NetObject.OnPostSimulate(int frameId, int subFrameId, bool isNetTick)
References Photon.Pun.Simple.NetObject.onPostSimulateCallbacks.
SerializationFlags Photon.Pun.Simple.NetObject.OnNetSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
References Photon.Pun.Simple.NetMaster.BITS_FOR_NETOBJ_SIZE, Photon.Pun.Simple.TickEngineSettings.frameCountBits, Photon.Pun.Simple.NetObject.GenerateMessage, Photon.Pun.PhotonView.Group, Photon.Pun.Simple.NetObject.photonView, Photon.Pun.Simple.Internal.NetMsgSends.reusableNetObjBuffer, Photon.Pun.Simple.Internal.NetMsgSends.Send, Photon.Pun.Simple.NetObject.skipWhenEmpty, Photon.Pun.Simple.NetObject.SkipWhenEmpty, Photon.Pun.Simple.NetObject.viewID.
void Photon.Pun.Simple.NetObject.OnCaptureCurrentState(int frameId)
References Photon.Pun.Simple.NetObject.onCaptureCurrentStateCallbacks.
Referenced by Photon.Pun.Simple.NetObject.GenerateMessage.
void Photon.Pun.Simple.NetObject.OnQuantize(int frameId)
References Photon.Pun.Simple.NetObject.onQuantizeCallbacks.
Referenced by Photon.Pun.Simple.NetObject.GenerateMessage.
void Photon.Pun.Simple.NetObject.OnIncrementFrame(int newFrameId, int newSubFrameId, int previousFrameId, int prevSubFrameId)
References Photon.Pun.Simple.NetObject.onIncrementFramesCallbacks.
bool Photon.Pun.Simple.NetObject.OnSnapshot(int localTargFrameId)
References Photon.Pun.Simple.ConnectionTickOffsets.advanceCount, Photon.Pun.PhotonView.ControllerActorNr, Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameLocalToOrigin, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.NetObject.frameValidMask, Photon.Pun.Simple.ConnectionTickOffsets.hadInitialSnapshot, Photon.Pun.Simple.TickEngineSettings.halfFrameCount, Photon.Pun.Simple.NetObject.onSnapshotCallbacks, Photon.Pun.Simple.Internal.TickManager.perConnOffsets, Photon.Pun.Simple.NetObject.photonView.
bool Photon.Pun.Simple.NetObject.OnInterpolate(int localSnapFrameId, int localTargFrameId, float t)
References Photon.Pun.PhotonView.ControllerActorNr, Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameLocalToOrigin, Photon.Pun.Simple.ConnectionTickOffsets.hadInitialSnapshot, Photon.Pun.Simple.NetObject.onInterpolateCallbacks, Photon.Pun.Simple.Internal.TickManager.perConnOffsets, Photon.Pun.Simple.NetObject.photonView, Photon.Pun.Simple.ConnectionTickOffsets.validFrameMask.
void Photon.Pun.Simple.NetObject.Awake()
References Photon.Pun.Simple.NetObject._rigidbody, Photon.Pun.Simple.NetObject._rigidbody2D, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.NetObject.frameValidMask, Photon.Pun.Simple.NetObject.originHistory, Photon.Pun.Simple.NetObject.photonView.
void Photon.Pun.Simple.NetObject.Start()
void Photon.Pun.Simple.NetObject.OnEnable()
void Photon.Pun.Simple.NetObject.OnDisable()
void Photon.Pun.Simple.NetObject.OnDestroy()
void Photon.Pun.Simple.NetObject.DetermineActiveAndControlled(bool amController)
Adds and Removes this NetObject from the active/owned list based on IsMine and ActiveAndEnabled.
Effectively caches which netObjects are part of serialization and such. Call this any time a change to enabled or owners change.
void Photon.Pun.Simple.NetObject.CollectAndReorderInterfaces()
Find all of the callback interfaces on children, and add them to the callback list, respecting the ApplyOrder value.
void Photon.Pun.Simple.NetObject.AddInterfaces(Component comp, bool remove=false)
void Photon.Pun.Simple.NetObject.AddInterfaceToList< T >(object comp, List< T > list, bool remove, bool checkSerializationOptional=false)
void Photon.Pun.Simple.NetObject.AddPackObjects(Component comp)
Check if passed Component has a PackObject attribute, if so add it to the callback list for this NetObj
void Photon.Pun.Simple.NetObject.BroadcastReadyMaskChange(PackObjRecord p)