ParrelSync::ClonesManager
const string ParrelSync.ClonesManager.CloneFileName
Name used for an identifying file created in the clone project directory.
(!) Do not change this after the clone was created, because then connection will be lost.
Referenced by ParrelSync.ClonesManager.IsClone.
const string ParrelSync.ClonesManager.CloneNameSuffix
Suffix added to the end of the project clone name when it is created.
(!) Do not change this after the clone was created, because then connection will be lost.
Referenced by ParrelSync.ClonesManager.CreateCloneFromPath, ParrelSync.ClonesManager.GetCloneProjectsPath, ParrelSync.ClonesManager.GetOriginalProjectPath.
const string ParrelSync.ClonesManager.ProjectName
Referenced by ParrelSync.ParrelSyncAssetModificationProcessor.OnWillSaveAssets.
const int ParrelSync.ClonesManager.MaxCloneProjectCount
The maximum number of clones
Referenced by ParrelSync.ClonesManager.CreateCloneFromPath, ParrelSync.ClonesManager.GetCloneProjectsPath.
const string ParrelSync.ClonesManager.ArgumentFileName
Name of the file for storing clone's argument.
Referenced by ParrelSync.ClonesManager.DeleteClone, ParrelSync.ClonesManager.GetArgument.
const string ParrelSync.ClonesManager.DefaultArgument
Default argument of the new clone
? bool ParrelSync.ClonesManager.isCloneFileExistCache
static Project ParrelSync.ClonesManager.CreateCloneFromCurrent()
Creates clone from the project currently open in Unity Editor.
References ParrelSync.ClonesManager.CreateCloneFromPath, ParrelSync.ClonesManager.GetCurrentProjectPath, ParrelSync.ClonesManager.IsClone.
static Project ParrelSync.ClonesManager.CreateCloneFromPath(string sourceProjectPath)
Creates clone of the project located at the given path.
sourceProjectPath
References ParrelSync.Project.assetPath, ParrelSync.Project.autoBuildPath, ParrelSync.ClonesManager.CloneNameSuffix, ParrelSync.ClonesManager.CopyDirectoryWithProgressBar, ParrelSync.ClonesManager.CreateProjectFolder, ParrelSync.ClonesManager.GetCurrentProject, ParrelSync.Project.libraryPath, ParrelSync.ClonesManager.LinkFolders, ParrelSync.Project.localPackages, ParrelSync.ClonesManager.MaxCloneProjectCount, ParrelSync.Project.name, ParrelSync.Project.packagesPath, ParrelSync.Project.projectPath, ParrelSync.Project.projectSettingsPath.
Referenced by ParrelSync.ClonesManager.CreateCloneFromCurrent.
static void ParrelSync.ClonesManager.OpenProject(string projectPath)
Opens a project located at the given path (if one exists).
projectPath
References ParrelSync.ClonesManager.GetCurrentProjectPath, ParrelSync.ClonesManager.GetOriginalProjectPath, ParrelSync.ValidateCopiedFoldersIntegrity.ValidateFolder.
static bool ParrelSync.ClonesManager.IsCloneProjectRunning(string projectPath)
Is this project being opened by an Unity editor?
projectPath
References ParrelSync.Preferences.AlsoCheckUnityLockFileStaPref, ParrelSync.FileUtilities.IsFileLocked, ParrelSync.BoolPreference.Value.
static void ParrelSync.ClonesManager.DeleteClone(string cloneProjectPath)
Deletes the clone of the currently open project, if such exists.
References ParrelSync.ClonesManager.ArgumentFileName, ParrelSync.ClonesManager.GetOriginalProjectPath, ParrelSync.ClonesManager.IsClone.
static void ParrelSync.ClonesManager.CreateProjectFolder(Project project)
Creates an empty folder using data in the given Project object
project
References ParrelSync.Project.projectPath.
Referenced by ParrelSync.ClonesManager.CreateCloneFromPath.
static void ParrelSync.ClonesManager.CopyLibraryFolder(Project sourceProject, Project destinationProject)
Copies the full contents of the unity library.
We want to do this to avoid the lengthy re-serialization of the whole project when it opens up the clone. sourceProject destinationProject
References ParrelSync.ClonesManager.CopyDirectoryWithProgressBar, ParrelSync.Project.libraryPath, ParrelSync.Project.name.
static void ParrelSync.ClonesManager.LinkFolders(string sourcePath, string destinationPath)
Create a link / junction from the original project to it's clone.
sourcePath destinationPath
Referenced by ParrelSync.ClonesManager.CreateCloneFromPath.
static bool ParrelSync.ClonesManager.IsClone()
Returns true if the project currently open in Unity Editor is a clone.
References ParrelSync.ClonesManager.CloneFileName, ParrelSync.ClonesManager.GetCurrentProjectPath.
Referenced by ParrelSync.ClonesManager.CreateCloneFromCurrent, ParrelSync.ClonesManager.DeleteClone, ParrelSync.ClonesManager.GetArgument, ParrelSync.ClonesManager.GetOriginalProjectPath, ParrelSync.ParrelSyncAssetModificationProcessor.OnWillSaveAssets.
static string ParrelSync.ClonesManager.GetCurrentProjectPath()
Get the path to the current unityEditor project folder's info
Referenced by ParrelSync.ClonesManager.CreateCloneFromCurrent, ParrelSync.ClonesManager.GetArgument, ParrelSync.ClonesManager.GetCurrentProject, ParrelSync.ClonesManager.GetOriginalProjectPath, ParrelSync.ClonesManager.IsClone, ParrelSync.ClonesManager.OpenProject.
static Project ParrelSync.ClonesManager.GetCurrentProject()
Return a project object that describes all the paths we need to clone it.
References ParrelSync.ClonesManager.GetCurrentProjectPath.
Referenced by ParrelSync.ClonesManager.CreateCloneFromPath, ParrelSync.ClonesManager.GetCloneProjectsPath, ParrelSync.ClonesManager.GetOriginalProjectPath.
static string ParrelSync.ClonesManager.GetArgument()
Get the argument of this clone project.
If this is the original project, will return an empty string.
References ParrelSync.ClonesManager.ArgumentFileName, ParrelSync.ClonesManager.GetCurrentProjectPath, ParrelSync.ClonesManager.IsClone.
static string ParrelSync.ClonesManager.GetOriginalProjectPath()
Returns the path to the original project.
If currently open project is the original, returns its own path. If the original project folder cannot be found, retuns an empty string.
References ParrelSync.ClonesManager.CloneNameSuffix, ParrelSync.ClonesManager.GetCurrentProject, ParrelSync.ClonesManager.GetCurrentProjectPath, ParrelSync.ClonesManager.IsClone, ParrelSync.Project.projectPath.
Referenced by ParrelSync.ClonesManager.DeleteClone, ParrelSync.ClonesManager.OpenProject.
static List< string > ParrelSync.ClonesManager.GetCloneProjectsPath()
Returns all clone projects path.
References ParrelSync.ClonesManager.CloneNameSuffix, ParrelSync.ClonesManager.GetCurrentProject, ParrelSync.ClonesManager.MaxCloneProjectCount, ParrelSync.Project.projectPath.
static void ParrelSync.ClonesManager.CopyDirectoryWithProgressBar(string sourcePath, string destinationPath, string progressBarPrefix="")
Copies directory located at sourcePath to destinationPath.
Displays a progress bar. source Directory to be copied. destination Destination directory (created automatically if needed). progressBarPrefix Optional string added to the beginning of the progress bar window header.
Referenced by ParrelSync.ClonesManager.CopyLibraryFolder, ParrelSync.ClonesManager.CreateCloneFromPath.
static void ParrelSync.ClonesManager.OpenProjectInFileExplorer(string path)
static void ParrelSync.ClonesManager.RegisterClone(Project cloneProject)
Registers a clone by placing an identifying ".clone" file in its root directory.
cloneProject
static string ParrelSync.ClonesManager.GetApplicationPath()
static void ParrelSync.ClonesManager.CreateLinkMac(string sourcePath, string destinationPath)
Creates a symlink between destinationPath and sourcePath (Mac version).
sourcePath destinationPath
static void ParrelSync.ClonesManager.CreateLinkLinux(string sourcePath, string destinationPath)
Creates a symlink between destinationPath and sourcePath (Linux version).
sourcePath destinationPath
static void ParrelSync.ClonesManager.CreateLinkWin(string sourcePath, string destinationPath)
Creates a symlink between destinationPath and sourcePath (Windows version).
sourcePath destinationPath
static void ParrelSync.ClonesManager.CopyDirectoryWithProgressBarRecursive(DirectoryInfo source, DirectoryInfo destination, ref long totalBytes, ref long copiedBytes, string progressBarPrefix="")
Copies directory located at sourcePath to destinationPath.
Displays a progress bar. Same as the previous method, but uses recursion to copy all nested folders as well. source Directory to be copied. destination Destination directory (created automatically if needed). totalBytes Total bytes to be copied. Calculated automatically, initialize at 0. copiedBytes To track already copied bytes. Calculated automatically, initialize at 0. progressBarPrefix Optional string added to the beginning of the progress bar window header.
static long ParrelSync.ClonesManager.GetDirectorySize(DirectoryInfo directory, bool includeNested=false, string progressBarPrefix="")
Calculates the size of the given directory.
Displays a progress bar. directory Directory, which size has to be calculated. includeNested If true, size will include all nested directories. progressBarPrefix Optional string added to the beginning of the progress bar window header. Size of the directory in bytes.
static void ParrelSync.ClonesManager.StartHiddenConsoleProcess(string fileName, string args)
Starts process in the system console, taking the given fileName and args.
fileName args
static void ParrelSync.ClonesManager.ExecuteBashCommand(string command)
Thanks to https://github.com/karl-/unity-symlink-utility/blob/master/SymlinkUtility.cs
command