Photon::Pun::UtilityScripts::PunTeams
Team
Dictionary<Team, List<Player> > Photon.Pun.UtilityScripts.PunTeams.PlayersPerTeam
The main list of teams with their player-lists.
Automatically kept up to date. Note that this is static. Can be accessed by PunTeam.PlayersPerTeam. You should not modify this.
Referenced by Photon.Pun.UtilityScripts.PunTeamsInspector.OnInspectorGUI, Photon.Pun.UtilityScripts.PunTeams.Start, Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
const string Photon.Pun.UtilityScripts.PunTeams.TeamPlayerProp
Defines the player custom property name to use for team affinity of "this" player.
Referenced by Photon.Pun.UtilityScripts.TeamExtensions.GetTeam, Photon.Pun.UtilityScripts.TeamExtensions.SetTeam.
void Photon.Pun.UtilityScripts.PunTeams.Start()
References Photon.Pun.UtilityScripts.PunTeams.PlayersPerTeam.
Referenced by Photon.Pun.UtilityScripts.PunTeams.OnDisable, Photon.Pun.UtilityScripts.PunTeams.OnLeftRoom.
override void Photon.Pun.UtilityScripts.PunTeams.OnDisable()
References Photon.Pun.UtilityScripts.PunTeams.Start.
override void Photon.Pun.UtilityScripts.PunTeams.OnJoinedRoom()
Needed to update the team lists when joining a room.
Called by PUN. See enum MonoBehaviourPunCallbacks for an explanation.
References Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
override void Photon.Pun.UtilityScripts.PunTeams.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
References Photon.Pun.UtilityScripts.PunTeams.Start.
override void Photon.Pun.UtilityScripts.PunTeams.OnPlayerPropertiesUpdate(Player targetPlayer, Hashtable changedProps)
Refreshes the team lists.
It could be a non-team related property change, too. Called by PUN. See enum MonoBehaviourPunCallbacks for an explanation.
References Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
override void Photon.Pun.UtilityScripts.PunTeams.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
References Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
override void Photon.Pun.UtilityScripts.PunTeams.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
References Photon.Pun.UtilityScripts.PunTeams.UpdateTeams.
void Photon.Pun.UtilityScripts.PunTeams.UpdateTeams()
References Photon.Pun.PhotonNetwork.PlayerList, Photon.Pun.UtilityScripts.PunTeams.PlayersPerTeam.
Referenced by Photon.Pun.UtilityScripts.PunTeams.OnJoinedRoom, Photon.Pun.UtilityScripts.PunTeams.OnPlayerEnteredRoom, Photon.Pun.UtilityScripts.PunTeams.OnPlayerLeftRoom, Photon.Pun.UtilityScripts.PunTeams.OnPlayerPropertiesUpdate.