Photon::Compression::CompressedMatrix
CompressedElement Photon.Compression.CompressedMatrix.cPos
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.CompressedMatrix.Clear, Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.CompressedMatrix, Photon.Compression.CompressedMatrix.CopyFrom, Photon.Compression.CompressedMatrix.CopyTo, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.CompressedMatrix.Equals, Photon.Compression.CompressedMatrix.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
CompressedElement Photon.Compression.CompressedMatrix.cRot
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.CompressedMatrix.Clear, Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.CompressedMatrix, Photon.Compression.CompressedMatrix.CopyFrom, Photon.Compression.CompressedMatrix.CopyTo, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.CompressedMatrix.Equals, Photon.Compression.CompressedMatrix.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
CompressedElement Photon.Compression.CompressedMatrix.cScl
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Capture, Photon.Compression.CompressedMatrix.Clear, Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.CompressedMatrix, Photon.Compression.CompressedMatrix.CopyFrom, Photon.Compression.CompressedMatrix.CopyTo, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.CompressedMatrix.Equals, Photon.Compression.CompressedMatrix.GetHashCode, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
TransformCrusher Photon.Compression.CompressedMatrix.crusher
Referenced by Photon.Compression.CompressedMatrix.Apply, Photon.Compression.CompressedMatrix.AsArray32, Photon.Compression.CompressedMatrix.AsArray64, Photon.Compression.CompressedMatrix.AsArray8, Photon.Compression.CompressedMatrix.Clear, Photon.Compression.TransformCrusher.Compress, Photon.Compression.CompressedMatrix.CompressedMatrix, Photon.Compression.CompressedMatrix.Decompress, Photon.Compression.CompressedMatrix.GetHashCode, Photon.Compression.CompressedMatrix.Move, Photon.Compression.CompressedMatrix.operator byte, Photon.Compression.CompressedMatrix.operator uint, Photon.Compression.CompressedMatrix.operator ulong, Photon.Compression.CompressedMatrix.operator ushort, Photon.Compression.TransformCrusher.Read, Photon.Compression.CompressedMatrix.Set, Photon.Compression.TransformCrusher.Write.
CompressedMatrix Photon.Compression.CompressedMatrix.reusable
Referenced by Photon.Compression.TransformCrusher.Apply, Photon.Compression.TransformCrusher.Compress, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.TransformCrusher.Move, Photon.Compression.TransformCrusher.Read, Photon.Compression.TransformCrusher.ReadAndApply, Photon.Compression.TransformCrusher.ReadAndDecompress, Photon.Compression.TransformCrusher.Set, Photon.Compression.TransformCrusher.Write.
readonly ulong [] Photon.Compression.CompressedMatrix.reusableArray64
Referenced by Photon.Compression.CompressedMatrix.AsArray64, Photon.Compression.CompressedMatrix.AsArray8.
readonly uint [] Photon.Compression.CompressedMatrix.reusableArray32
Referenced by Photon.Compression.CompressedMatrix.AsArray32.
readonly byte [] Photon.Compression.CompressedMatrix.reusableArray8
Referenced by Photon.Compression.CompressedMatrix.AsArray8.
Photon.Compression.CompressedMatrix.CompressedMatrix()
Photon.Compression.CompressedMatrix.CompressedMatrix(TransformCrusher crusher)
References Photon.Compression.CompressedMatrix.crusher.
Photon.Compression.CompressedMatrix.CompressedMatrix(TransformCrusher crusher, CompressedElement cPos, CompressedElement cRot, CompressedElement cScl)
References Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl.
Photon.Compression.CompressedMatrix.CompressedMatrix(TransformCrusher crusher, ref CompressedElement cPos, ref CompressedElement cRot, ref CompressedElement cScl, int pBits, int rBits, int sBits)
References Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl.
void Photon.Compression.CompressedMatrix.CopyTo(CompressedMatrix copyTarget)
References Photon.Compression.CompressedElement.CopyTo, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl.
void Photon.Compression.CompressedMatrix.CopyFrom(CompressedMatrix copySource)
References Photon.Compression.CompressedElement.CopyFrom, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl.
Referenced by Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState.
void Photon.Compression.CompressedMatrix.Clear()
References Photon.Compression.CompressedElement.Clear, Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl.
ulong[] Photon.Compression.CompressedMatrix.AsArray64(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.reusableArray64, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.CompressedMatrix.AsArray64(ulong[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Write.
uint[] Photon.Compression.CompressedMatrix.AsArray32(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.reusableArray32, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.CompressedMatrix.AsArray32(uint[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Write.
byte[] Photon.Compression.CompressedMatrix.AsArray8(BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into an array.
WARNING: The returned array is recycled - so the values are subject to change. Use contents immediately. If you want to store the returned value, supply a nonalloc array as an argument.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.reusableArray64, Photon.Compression.CompressedMatrix.reusableArray8, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.CompressedMatrix.AsArray8(byte[] nonalloc, BitCullingLevel bcl=BitCullingLevel.NoCulling)
Serializes the CompressedMatrix into supplied nonalloc array.
NOTE: Contents of the nonalloc array will be overwritten.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Write.
void Photon.Compression.CompressedMatrix.Decompress(Matrix nonalloc)
Decompress this CompressedMatrix into the supplied nonalloc Matrix class.
nonalloc The target for the uncompressed TRS.
References Photon.Compression.Matrix.Clear, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Decompress.
Referenced by Photon.Compression.TransformCrusher.Move.
Matrix Photon.Compression.CompressedMatrix.Decompress()
Decompress this CompressedMatrix into a recycled Matrix class.
WARNING: No Matrix is provided in this overload, so a reusable internal Matrix ref is used. Use immediately.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Decompress, Photon.Compression.Matrix.reusable.
void Photon.Compression.CompressedMatrix.Apply()
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.CompressedMatrix.crusher.
void Photon.Compression.CompressedMatrix.Apply(Transform t)
Convenience method.
For the most direct call use crusher.Apply(transform, compressedmatrix) instead.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.CompressedMatrix.crusher.
void Photon.Compression.CompressedMatrix.Apply(Rigidbody rb)
Convenience method.
For the most direct call use crusher.Apply(rigidbody, compressedmatrix) instead.
References Photon.Compression.TransformCrusher.Apply, Photon.Compression.CompressedMatrix.crusher.
void Photon.Compression.CompressedMatrix.Set(Rigidbody rb)
Convenience method.
For the most direct call use crusher.Set(rigidbody, compressedmatrix) instead.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Set.
void Photon.Compression.CompressedMatrix.Move(Rigidbody rb)
Convenience method.
For the most direct call use crusher.Move(rigidbody, compressedmatrix) instead.
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.Move.
override bool Photon.Compression.CompressedMatrix.Equals(object obj)
References Photon.Compression.CompressedMatrix.Equals.
Referenced by Photon.Compression.CompressedMatrix.Equals, Photon.Pun.Simple.SyncTransform.Frame.FastCompareCompressed, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Compression.CompressedMatrix.operator!=, Photon.Compression.CompressedMatrix.operator==.
bool Photon.Compression.CompressedMatrix.Equals(CompressedMatrix other)
Compare the values of this CompressedMatrix with the values of another.
other True if the values match, false if not.
References Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.CompressedElement.Equals.
override int Photon.Compression.CompressedMatrix.GetHashCode()
References Photon.Compression.CompressedMatrix.cPos, Photon.Compression.CompressedMatrix.cRot, Photon.Compression.CompressedMatrix.crusher, Photon.Compression.CompressedMatrix.cScl, Photon.Compression.CompressedElement.GetHashCode.
static Photon.Compression.CompressedMatrix.operator ulong(CompressedMatrix cm)
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
static Photon.Compression.CompressedMatrix.operator uint(CompressedMatrix cm)
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
static Photon.Compression.CompressedMatrix.operator ushort(CompressedMatrix cm)
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
static Photon.Compression.CompressedMatrix.operator byte(CompressedMatrix cm)
References Photon.Compression.CompressedMatrix.crusher, Photon.Compression.TransformCrusher.TallyBits, Photon.Compression.TransformCrusher.Write.
static Photon.Compression.CompressedMatrix.operator ulong[](CompressedMatrix cm)
static Photon.Compression.CompressedMatrix.operator uint[](CompressedMatrix cm)
static Photon.Compression.CompressedMatrix.operator byte[](CompressedMatrix cm)
static bool Photon.Compression.CompressedMatrix.operator==(CompressedMatrix a, CompressedMatrix b)
References Photon.Compression.CompressedMatrix.Equals.
static bool Photon.Compression.CompressedMatrix.operator!=(CompressedMatrix a, CompressedMatrix b)
References Photon.Compression.CompressedMatrix.Equals.