Photon::Pun::Simple::Vitals
List<IOnVitalValueChange> Photon.Pun.Simple.Vitals.OnVitalValueChangeCallbacks
Referenced by Photon.Pun.Simple.SyncVitals.OnAwake, Photon.Pun.Simple.Vitals.OnVitalValueChange.
List<IOnVitalParamChange> Photon.Pun.Simple.Vitals.OnVitalParamChangeCallbacks
Referenced by Photon.Pun.Simple.Vitals.OnVitalParamChange.
List<VitalDefinition> Photon.Pun.Simple.Vitals.vitalDefs
Referenced by Photon.Pun.Simple.Vitals.Deserialize, Photon.Pun.Simple.Vitals.GetVitalIndex, Photon.Pun.Simple.Vitals.Initialize, Photon.Pun.Simple.SyncVitals.OnAwake, Photon.Pun.Simple.Vitals.Serialize.
List<VitalDefinition> Photon.Pun.Simple.Vitals.VitalDefs
Vital [] Photon.Pun.Simple.Vitals.VitalArray
Referenced by Photon.Pun.Simple.SyncVitals.OnAwake, Photon.Pun.Simple.VitalsData.VitalsData.
Vital [] Photon.Pun.Simple.Vitals.vitalArray
Dictionary<int, Vital> Photon.Pun.Simple.Vitals.vitalLookup
int Photon.Pun.Simple.Vitals.vitalCount
bool Photon.Pun.Simple.Vitals.initialized
void Photon.Pun.Simple.Vitals.Initialize()
References Photon.Pun.Simple.Vital.AddIOnVitalChange, Photon.Pun.Simple.VitalNameType.hash, Photon.Pun.Simple.Vital.Initialize, Photon.Pun.Simple.TickEngineSettings.netTickInterval, Photon.Pun.Simple.VitalNameType.type, Photon.Pun.Simple.Vitals.vitalDefs, Photon.Pun.Simple.VitalDefinition.VitalName.
Referenced by Photon.Pun.Simple.Vitals.GetVital.
void Photon.Pun.Simple.Vitals.ResetValues()
References Photon.Pun.Simple.Vital.ResetValues.
Vital Photon.Pun.Simple.Vitals.GetVital(VitalNameType vitalNameType)
Do not use this in a hot path please.
Cache the Vital this returns.
References Photon.Pun.Simple.VitalNameType.hash, Photon.Pun.Simple.Vitals.Initialize.
Referenced by Photon.Pun.Simple.SyncVitals.TryTrigger.
int Photon.Pun.Simple.Vitals.GetVitalIndex(VitalNameType vitalNameType)
References Photon.Pun.Simple.VitalNameType.hash, Photon.Pun.Simple.Vitals.vitalDefs.
Referenced by Photon.Pun.Simple.Vitals.ApplyCharges.
SerializationFlags Photon.Pun.Simple.Vitals.Serialize(VitalsData vdata, VitalsData lastVData, byte[] buffer, ref int bitposition, bool keyframe)
References Photon.Pun.Simple.VitalsData.datas, Photon.Pun.Simple.Vitals.Serialize, Photon.Pun.Simple.Vitals.vitalDefs.
Referenced by Photon.Pun.Simple.SyncVitals.OnNetSerialize, Photon.Pun.Simple.Vitals.Serialize.
SerializationFlags Photon.Pun.Simple.Vitals.Deserialize(VitalsData vdata, byte[] buffer, ref int bitposition, bool keyframe)
References Photon.Pun.Simple.VitalsData.datas, Photon.Pun.Simple.Vitals.vitalDefs.
Referenced by Photon.Pun.Simple.SyncVitals.OnNetDeserialize.
void Photon.Pun.Simple.Vitals.Apply(VitalsData vdata)
References Photon.Pun.Simple.Vitals.Apply, Photon.Pun.Simple.VitalsData.datas.
Referenced by Photon.Pun.Simple.Vitals.Apply, Photon.Pun.Simple.SyncVitals.ApplySnapshot.
double Photon.Pun.Simple.Vitals.ApplyCharges(double discharge, bool allowOverload, bool propagate)
double Photon.Pun.Simple.Vitals.ApplyCharges(VitalNameType vitalNameType, double discharge, bool allowOverload, bool propagate)
References Photon.Pun.Simple.Vitals.CheckForDisrupt, Photon.Pun.Simple.Vitals.GetVitalIndex, Photon.Pun.Simple.VitalNameType.type.
void Photon.Pun.Simple.Vitals.CheckForDisrupt(double consumed)
References Photon.Pun.Simple.Vitals.DisruptDecay, Photon.Pun.Simple.Vitals.DisruptRegen.
Referenced by Photon.Pun.Simple.Vitals.ApplyCharges.
void Photon.Pun.Simple.Vitals.DisruptRegen()
References Photon.Pun.Simple.Vitals.DisruptRegen.
Referenced by Photon.Pun.Simple.Vitals.CheckForDisrupt, Photon.Pun.Simple.Vitals.DisruptRegen.
void Photon.Pun.Simple.Vitals.DisruptDecay()
References Photon.Pun.Simple.Vitals.DisruptDecay.
Referenced by Photon.Pun.Simple.Vitals.CheckForDisrupt, Photon.Pun.Simple.Vitals.DisruptDecay.
void Photon.Pun.Simple.Vitals.OnVitalValueChange(Vital vital)
References Photon.Pun.Simple.Vitals.OnVitalValueChangeCallbacks.
void Photon.Pun.Simple.Vitals.OnVitalParamChange(Vital vital)
References Photon.Pun.Simple.Vitals.OnVitalParamChangeCallbacks.
void Photon.Pun.Simple.Vitals.Simulate()
References Photon.Pun.Simple.Vitals.Simulate.
Referenced by Photon.Pun.Simple.SyncVitals.OnPostSimulate, Photon.Pun.Simple.Vitals.Simulate.
double Photon.Pun.Simple.Vitals.ApplyCharges(int vitalIdx, double discharge, bool allowOverload, bool propagate)