Photon::Pun::ServerSettings
AppSettings Photon.Pun.ServerSettings.AppSettings
Referenced by Photon.Pun.PhotonEditor.Awake, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToRegion, Photon.Pun.PhotonNetwork.ConnectUsingSettings, Photon.Pun.ServerSettingsInspector.OnInspectorGUI, Photon.Pun.Demo.Cockpit.PunCockpit.PingRegions.
string Photon.Pun.ServerSettings.DevRegion
Region that will be used by the Editor and Development Builds. This ensures all users will be in the same region for testing.
PunLogLevel Photon.Pun.ServerSettings.PunLogging
bool Photon.Pun.ServerSettings.EnableSupportLogger
Referenced by Photon.Pun.PhotonHandler.OnEnable.
bool Photon.Pun.ServerSettings.RunInBackground
bool Photon.Pun.ServerSettings.StartInOfflineMode
Referenced by Photon.Pun.Demo.Procedural.IngameControlPanel.Awake, Photon.Pun.PhotonNetwork.ConnectUsingSettings.
List<string> Photon.Pun.ServerSettings.RpcList
Referenced by Photon.Pun.PhotonEditor.ClearRpcList, Photon.Pun.PhotonEditor.UpdateRpcList.
string Photon.Pun.ServerSettings.BestRegionSummaryInPreferences
Gets the "best region summary" from the preferences.
The best region code in preferences.
void Photon.Pun.ServerSettings.UseCloud(string cloudAppid, string code="")
Sets appid and region code in the AppSettings. Used in Editor.
References Photon.Realtime.AppSettings.AppIdRealtime, Photon.Realtime.AppSettings.FixedRegion, Photon.Realtime.AppSettings.Server.
Referenced by Photon.Pun.PhotonEditor.UiSetupApp.
override string Photon.Pun.ServerSettings.ToString()
String summary of the AppSettings.
References Photon.Realtime.AppSettings.ToStringFull.
static bool Photon.Pun.ServerSettings.IsAppId(string val)
Checks if a string is a Guid by attempting to create one.
val The potential guid to check. True if new Guid(val) did not fail.
Referenced by Photon.Pun.PhotonEditor.UiSetupApp.
static void Photon.Pun.ServerSettings.ResetBestRegionCodeInPreferences()
Sets the "best region summary" in the preferences to null. On next start, the client will ping all available.
References Photon.Pun.PhotonNetwork.BestRegionSummaryInPreferences.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.ConnectToBestCloudServer, Photon.Pun.ServerSettingsInspector.OnInspectorGUI.