Photon::Realtime::Room
LoadBalancingClient Photon.Realtime.Room.LoadBalancingClient
A reference to the LoadBalancingClient which is currently keeping the connection and state.
Referenced by Photon.Realtime.Player.SetCustomProperties.
new string Photon.Realtime.Room.Name
The name of a room.
Unique identifier (per region and virtual appid) for a room/match. The name can't be changed once it's set by the server.
Referenced by Launcher.OnJoinedRoom, Launcher_old.OnJoinedRoom.
bool Photon.Realtime.Room.IsOffline
Referenced by Photon.Realtime.Player.SetCustomProperties.
new bool Photon.Realtime.Room.IsOpen
Defines if the room can be joined.
This does not affect listing in a lobby but joining the room will fail if not open. If not open, the room is excluded from random matchmaking. Due to racing conditions, found matches might become closed while users are trying to join. Simply re-connect to master and find another. Use property "IsVisible" to not list the room. As part of RoomInfo this can't be set. As part of a Room (which the player joined), the setter will update the server and all clients.
Referenced by Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnStartGameButtonClicked, Photon.Pun.Demo.Cockpit.CurrentRoomIsOpenToggle.ToggleValue.
new bool Photon.Realtime.Room.IsVisible
Defines if the room is listed in its lobby.
Rooms can be created invisible, or changed to invisible. To change if a room can be joined, use property: open. As part of RoomInfo this can't be set. As part of a Room (which the player joined), the setter will update the server and all clients.
Referenced by Photon.Pun.Demo.Asteroids.LobbyMainPanel.OnStartGameButtonClicked, Photon.Pun.Demo.Cockpit.CurrentRoomIsVisibleToggle.ToggleValue.
new byte Photon.Realtime.Room.MaxPlayers
Sets a limit of players to this room.
This property is synced and shown in lobby, too. If the room is full (players count == maxplayers), joining this room will fail. As part of RoomInfo this can't be set. As part of a Room (which the player joined), the setter will update the server and all clients.
new byte Photon.Realtime.Room.PlayerCount
The count of players in this Room (using this.Players.Count).
Referenced by Launcher.CheckAllPlayersReady, Photon.Pun.PhotonHandler.OnJoinedRoom, Photon.Pun.Demo.PunBasics.Launcher.OnJoinedRoom, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget, Photon.Realtime.Room.ToString, Photon.Realtime.Room.ToStringFull.
Dictionary<int, Player> Photon.Realtime.Room.Players
While inside a Room, this is the list of players who are also in that room.
Referenced by Photon.Realtime.Room.AddPlayer, Photon.Pun.Simple.SyncOwner.DeferredOwnerChange, Photon.Realtime.Player.GetNextFor, Photon.Realtime.Room.GetPlayer, Photon.Pun.Demo.Cockpit.PlayerListView.OnEnable, Photon.Pun.Demo.Cockpit.PlayerListView.OnMasterClientSwitched, Photon.Pun.UtilityScripts.PlayerNumbering.RefreshData, Photon.Realtime.Room.StorePlayer.
string [] Photon.Realtime.Room.ExpectedUsers
List of users who are expected to join this room.
In matchmaking, Photon blocks a slot for each of these UserIDs out of the MaxPlayers. The corresponding feature in Photon is called "Slot Reservation" and can be found in the doc pages. Define expected players in the methods: LoadBalancingClient.OpCreateRoom, LoadBalancingClient.OpJoinRoom and LoadBalancingClient.OpJoinRandomRoom.
Referenced by Photon.Realtime.Room.ClearExpectedUsers, Photon.Realtime.Room.SetExpectedUsers.
int Photon.Realtime.Room.PlayerTtl
Player Time To Live. How long any player can be inactive (due to disconnect or leave) before the user gets removed from the playerlist (freeing a slot).
Referenced by Photon.Pun.PhotonNetwork.LeaveRoom.
int Photon.Realtime.Room.EmptyRoomTtl
Room Time To Live. How long a room stays available (and in server-memory), after the last player becomes inactive. After this time, the room gets persisted or destroyed.
int Photon.Realtime.Room.MasterClientId
The ID (actorNumber, actorNumber) of the player who's the master of this Room.
Note: This changes when the current master leaves the room.
Referenced by Photon.Realtime.Room.GetPlayer, Photon.Realtime.Room.SetMasterClient.
string [] Photon.Realtime.Room.PropertiesListedInLobby
Gets a list of custom properties that are in the RoomInfo of the Lobby.
This list is defined when creating the room and can't be changed afterwards. Compare: LoadBalancingClient.OpCreateRoom() You could name properties that are not set from the beginning. Those will be synced with the lobby when added later on.
bool Photon.Realtime.Room.AutoCleanUp
Gets if this room cleans up the event cache when a player (actor) leaves.
This affects which events joining players get. Set in room creation via RoomOptions.CleanupCacheOnLeave. Within PUN, auto cleanup of events means that cached RPCs and instantiated networked objects are deleted from the room.
Referenced by Photon.Pun.PhotonHandler.OnPlayerLeftRoom.
bool Photon.Realtime.Room.BroadcastPropertiesChangeToAll
Define if the client who calls SetProperties should receive the properties update event or not.
bool Photon.Realtime.Room.SuppressRoomEvents
Define if Join and Leave events should not be sent to clients in the room.
bool Photon.Realtime.Room.SuppressPlayerInfo
Extends SuppressRoomEvents: Define if Join and Leave events but also the actors' list and their respective properties should not be sent to clients.
bool Photon.Realtime.Room.PublishUserId
Define if UserIds of the players are broadcast in the room. Useful for FindFriends and reserving slots for expected users.
bool Photon.Realtime.Room.DeleteNullProperties
Define if actor or room properties with null values are removed on the server or kept.
bool Photon.Realtime.Room.isOffline
Dictionary<int, Player> Photon.Realtime.Room.players
While inside a Room, this is the list of players who are also in that room.
Photon.Realtime.Room.Room(string roomName, RoomOptions options, bool isOffline=false)
Creates a Room (representation) with given name and properties and the "listing options" as provided by parameters.
roomName Name of the room (can be null until it's actually created on server). options Room options.
References Photon.Realtime.RoomOptions.CustomRoomPropertiesForLobby, Photon.Realtime.RoomOptions.IsOpen, Photon.Realtime.RoomInfo.isOpen, Photon.Realtime.RoomOptions.IsVisible, Photon.Realtime.RoomInfo.isVisible, Photon.Realtime.RoomOptions.MaxPlayers, Photon.Realtime.RoomInfo.maxPlayers, Photon.Realtime.RoomInfo.propertiesListedInLobby.
virtual bool Photon.Realtime.Room.SetCustomProperties(Hashtable propertiesToSet, Hashtable expectedProperties=null, WebFlags webFlags=null)
Updates and synchronizes this Room's Custom Properties.
Optionally, expectedProperties can be provided as condition. Custom Properties are a set of string keys and arbitrary values which is synchronized for the players in a Room. They are available when the client enters the room, as they are in the response of OpJoin and OpCreate. Custom Properties either relate to the (current) Room or a Player (in that Room). Both classes locally cache the current key/values and make them available as property: CustomProperties. This is provided only to read them. You must use the method SetCustomProperties to set/modify them. Any client can set any Custom Properties anytime (when in a room). It's up to the game logic to organize how they are best used. You should call SetCustomProperties only with key/values that are new or changed. This reduces traffic and performance. Unless you define some expectedProperties, setting key/values is always permitted. In this case, the property-setting client will not receive the new values from the server but instead update its local cache in SetCustomProperties. If you define expectedProperties, the server will skip updates if the server property-cache does not contain all expectedProperties with the same values. In this case, the property-setting client will get an update from the server and update it's cached key/values at about the same time as everyone else. The benefit of using expectedProperties can be only one client successfully sets a key from one known value to another. As example: Store who owns an item in a Custom Property "ownedBy". It's 0 initally. When multiple players reach the item, they all attempt to change "ownedBy" from 0 to their actorNumber. If you use expectedProperties {"ownedBy", 0} as condition, the first player to take the item will have it (and the others fail to set the ownership). Properties get saved with the game state for Turnbased games (which use IsPersistent = true). propertiesToSet Hashtable of Custom Properties that changes. expectedProperties Provide some keys/values to use as condition for setting the new values. Client must be in room. webFlags Defines if this SetCustomProperties-operation gets forwarded to your WebHooks. Client must be in room. False if propertiesToSet is null or empty or have zero string keys. True in offline mode even if expectedProperties or webFlags are used. Otherwise, returns if this operation could be sent to the server.
References Photon.Realtime.RoomInfo.CustomProperties.
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.ConfirmAndUpdateProperties, Photon.Pun.UtilityScripts.TurnExtensions.SetFinishedTurn, Photon.Pun.Demo.Cockpit.PunCockpit.SetRoomCustomProperty, Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime, Photon.Pun.UtilityScripts.TurnExtensions.SetTurn.
bool Photon.Realtime.Room.SetPropertiesListedInLobby(string[] lobbyProps)
Enables you to define the properties available in the lobby if not all properties are needed to pick a room.
Limit the amount of properties sent to users in the lobby to improve speed and stability. lobbyProps An array of custom room property names to forward to the lobby. If the operation could be sent to the server.
References Photon.Realtime.GamePropertyKey.PropsListedInLobby.
bool Photon.Realtime.Room.SetMasterClient(Player masterClientPlayer)
Asks the server to assign another player as Master Client of your current room.
RaiseEvent has the option to send messages only to the Master Client of a room. SetMasterClient affects which client gets those messages. This method calls an operation on the server to set a new Master Client, which takes a roundtrip. In case of success, this client and the others get the new Master Client from the server. SetMasterClient tells the server which current Master Client should be replaced with the new one. It will fail, if anything switches the Master Client moments earlier. There is no callback for this error. All clients should get the new Master Client assigned by the server anyways. See also: MasterClientId masterClientPlayer The player to become the next Master Client. False when this operation couldn't be done currently. Requires a v4 Photon Server.
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.GamePropertyKey.MasterClientId, Photon.Realtime.Room.MasterClientId.
Referenced by Photon.Pun.PhotonNetwork.SetMasterClient.
virtual bool Photon.Realtime.Room.AddPlayer(Player player)
Checks if the player is in the room's list already and calls StorePlayer() if not.
player The new player - identified by ID. False if the player could not be added (cause it was in the list already).
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.Room.Players, Photon.Realtime.Room.StorePlayer.
virtual Player Photon.Realtime.Room.StorePlayer(Player player)
Updates a player reference in the Players dictionary (no matter if it existed before or not).
player The Player instance to insert into the room.
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.Room.Players.
Referenced by Photon.Realtime.Room.AddPlayer, Photon.Realtime.LoadBalancingClient.ChangeLocalID, Photon.Realtime.LoadBalancingClient.OnEvent.
virtual Player Photon.Realtime.Room.GetPlayer(int id, bool findMaster=false)
Tries to find the player with given actorNumber (a.k.a.
ID). Only useful when in a Room, as IDs are only valid per Room. id ID to look for. findMaster If true, the Master Client is returned for ID == 0. The player with the ID or null.
References Photon.Realtime.Room.MasterClientId, Photon.Realtime.Room.Players.
Referenced by Photon.Realtime.Player.Get, Photon.Realtime.LoadBalancingClient.OnEvent.
bool Photon.Realtime.Room.ClearExpectedUsers()
Attempts to remove all current expected users from the server's Slot Reservation list.
Note that this operation can conflict with new/other users joining. They might be adding users to the list of expected users before or after this client called ClearExpectedUsers. This room's expectedUsers value will update, when the server sends a successful update. Internals: This methods wraps up setting the ExpectedUsers property of a room. If the operation could be sent to the server.
References Photon.Realtime.Room.ExpectedUsers, Photon.Realtime.Room.SetExpectedUsers.
bool Photon.Realtime.Room.SetExpectedUsers(string[] newExpectedUsers)
Attempts to update the expected users from the server's Slot Reservation list.
Note that this operation can conflict with new/other users joining. They might be adding users to the list of expected users before or after this client called SetExpectedUsers. This room's expectedUsers value will update, when the server sends a successful update. Internals: This methods wraps up setting the ExpectedUsers property of a room. newExpectedUsers The new array of UserIDs to be reserved in the room. If the operation could be sent to the server.
References Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.Room.ExpectedUsers, Photon.Realtime.Room.SetExpectedUsers.
Referenced by Photon.Realtime.Room.ClearExpectedUsers, Photon.Realtime.Room.SetExpectedUsers.
override string Photon.Realtime.Room.ToString()
Returns a summary of this Room instance as string.
Summary of this Room instance.
References Photon.Realtime.RoomInfo.isOpen, Photon.Realtime.RoomInfo.isVisible, Photon.Realtime.RoomInfo.maxPlayers, Photon.Realtime.RoomInfo.name, Photon.Realtime.Room.PlayerCount.
new string Photon.Realtime.Room.ToStringFull()
Returns a summary of this Room instance as longer string, including Custom Properties.
Summary of this Room instance.
References Photon.Realtime.RoomInfo.CustomProperties, Photon.Realtime.RoomInfo.isOpen, Photon.Realtime.RoomInfo.isVisible, Photon.Realtime.RoomInfo.maxPlayers, Photon.Realtime.RoomInfo.name, Photon.Realtime.Room.PlayerCount.
void Photon.Realtime.Room.InternalCacheRoomFlags(int roomFlags)
Read (received) room option flags into related bool parameters.
This is for internal use. The operation response for join and create room operations is read this way. roomFlags
override void Photon.Realtime.Room.InternalCacheProperties(Hashtable propertiesToCache)
Copies "well known" properties to fields (IsVisible, etc) and caches the custom properties (string-keys only) in a local hashtable.
propertiesToCache New or updated properties to store in this RoomInfo.
virtual void Photon.Realtime.Room.RemovePlayer(Player player)
Removes a player from this room's Players Dictionary.
This is internally used by the LoadBalancing API. There is usually no need to remove players yourself. This is not a way to "kick" players.
virtual void Photon.Realtime.Room.RemovePlayer(int id)
Removes a player from this room's Players Dictionary.
bool Photon.Realtime.Room.SetExpectedUsers(string[] newExpectedUsers, string[] oldExpectedUsers)