SInt::MissionObjectives::MoManager
List<MoOwner> SInt.MissionObjectives.MoManager.missions
Referenced by SInt.MissionObjectives.MoManager.SearchMoByID, SInt.MissionObjectives.MoManager.TryProgressMoByIDRPC.
PhotonView SInt.MissionObjectives.MoManager.PV
Referenced by SInt.MissionObjectives.MoManager.TryProgressMoByID.
bool SInt.MissionObjectives.MoManager.isAllowDebugInput
MoManager SInt.MissionObjectives.MoManager.instance
Referenced by Chores.CleanToy, Chores.ClearTrash, Chores.PutBack, MoWrapperMethods.SetMoDataProgressionStatusAsActive, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion, MoWrapperMethods.TryProgressMoDataByID.
void SInt.MissionObjectives.MoManager.Awake()
void SInt.MissionObjectives.MoManager.Start()
void SInt.MissionObjectives.MoManager.Update()
IEnumerator SInt.MissionObjectives.MoManager.waitForReadyInGame()
void SInt.MissionObjectives.MoManager.SceneSpecificTweaks()
References SInt.MissionObjectives.MoManager.SetMoDataProgressionStatus.
void SInt.MissionObjectives.MoManager.FactionSpecificTweaks()
References Chores.dustTask, Chores.fridgeTask, Chores.makeBedTask, SInt.MissionObjectives.MoManager.SetMoDataProgressionStatus, Chores.sweepTask, Chores.toyTask, Chores.trashTask, Chores.washDishTask, Chores.waterTask, Chores.wipeTask.
void SInt.MissionObjectives.MoManager.TryProgressMoByID(string targetUniqueID)
References SInt.MissionObjectives.MoManager.PV, Photon.Pun.PhotonView.RPC, SInt.MissionObjectives.MoManager.TryProgressMoByIDRPC.
Referenced by Chores.CleanToy, Chores.ClearTrash, Chores.PutBack, BreakableFurniture.SpawnBrokenVersion, FixDestroyedFurniture.SpawnDefaultVersion, MoWrapperMethods.TryProgressMoDataByID.
void SInt.MissionObjectives.MoManager.TryProgressMoByIDRPC(string targetUniqueID)
References SInt.MissionObjectives.MoManager.missions.
Referenced by SInt.MissionObjectives.MoManager.TryProgressMoByID.
MoData SInt.MissionObjectives.MoManager.SearchMoByID(string targetUniqueID)
References SInt.MissionObjectives.MoManager.missions.
Referenced by SInt.MissionObjectives.MoManager.SetMoDataProgressionStatus.
void SInt.MissionObjectives.MoManager.SetMoDataProgressionStatus(string targetUniqueID, MoStatus newMoStatus)
References SInt.MissionObjectives.MoData.ObjectiveProgress.moStatus, SInt.MissionObjectives.MoData.progress, SInt.MissionObjectives.MoManager.SearchMoByID.
Referenced by SInt.MissionObjectives.MoManager.FactionSpecificTweaks, SInt.MissionObjectives.MoManager.SceneSpecificTweaks, MoWrapperMethods.SetMoDataProgressionStatusAsActive.