Photon::Pun::PhotonTransformViewPositionControl
PhotonTransformViewPositionModel Photon.Pun.PhotonTransformViewPositionControl.m_Model
float Photon.Pun.PhotonTransformViewPositionControl.m_CurrentSpeed
double Photon.Pun.PhotonTransformViewPositionControl.m_LastSerializeTime
Vector3 Photon.Pun.PhotonTransformViewPositionControl.m_SynchronizedSpeed
float Photon.Pun.PhotonTransformViewPositionControl.m_SynchronizedTurnSpeed
Vector3 Photon.Pun.PhotonTransformViewPositionControl.m_NetworkPosition
Queue<Vector3> Photon.Pun.PhotonTransformViewPositionControl.m_OldNetworkPositions
bool Photon.Pun.PhotonTransformViewPositionControl.m_UpdatedPositionAfterOnSerialize
Photon.Pun.PhotonTransformViewPositionControl.PhotonTransformViewPositionControl(PhotonTransformViewPositionModel model)
void Photon.Pun.PhotonTransformViewPositionControl.SetSynchronizedValues(Vector3 speed, float turnSpeed)
These values are synchronized to the remote objects if the interpolation mode or the extrapolation mode SynchronizeValues is used.
Your movement script should pass on the current speed (in units/second) and turning speed (in angles/second) so the remote object can use them to predict the objects movement. speed The current movement vector of the object in units/second. turnSpeed The current turn speed of the object in angles/second.
Referenced by Photon.Pun.PhotonTransformViewClassic.SetSynchronizedValues.
Vector3 Photon.Pun.PhotonTransformViewPositionControl.UpdatePosition(Vector3 currentPosition)
Calculates the new position based on the values setup in the inspector
currentPosition The current position. The new position.
References Photon.Pun.PhotonTransformViewPositionControl.GetExtrapolatedPositionOffset, Photon.Pun.PhotonTransformViewPositionControl.GetNetworkPosition, Photon.Pun.PhotonTransformViewPositionModel.InterpolateLerpSpeed, Photon.Pun.PhotonTransformViewPositionModel.InterpolateMoveTowardsSpeed, Photon.Pun.PhotonTransformViewPositionModel.InterpolateOption, Photon.Pun.PhotonNetwork.SerializationRate, Photon.Pun.PhotonTransformViewPositionModel.TeleportEnabled, Photon.Pun.PhotonTransformViewPositionModel.TeleportIfDistanceGreaterThan.
Vector3 Photon.Pun.PhotonTransformViewPositionControl.GetNetworkPosition()
Gets the last position that was received through the network
Referenced by Photon.Pun.PhotonTransformViewClassic.OnPhotonSerializeView, Photon.Pun.PhotonTransformViewPositionControl.UpdatePosition.
Vector3 Photon.Pun.PhotonTransformViewPositionControl.GetExtrapolatedPositionOffset()
Calculates an estimated position based on the last synchronized position, the time when the last position was received and the movement speed of the object
Estimated position of the remote object
References Photon.Pun.PhotonTransformViewPositionModel.ExtrapolateIncludingRoundTripTime, Photon.Pun.PhotonTransformViewPositionModel.ExtrapolateOption, Photon.Pun.PhotonTransformViewPositionModel.ExtrapolateSpeed, Photon.Pun.PhotonNetwork.GetPing, Photon.Pun.PhotonNetwork.SerializationRate, Photon.Pun.PhotonNetwork.Time.
Referenced by Photon.Pun.PhotonTransformViewPositionControl.UpdatePosition.
void Photon.Pun.PhotonTransformViewPositionControl.OnPhotonSerializeView(Vector3 currentPosition, PhotonStream stream, PhotonMessageInfo info)
References Photon.Pun.PhotonStream.IsWriting, Photon.Pun.PhotonTransformViewPositionModel.SynchronizeEnabled, Photon.Pun.PhotonNetwork.Time.
Referenced by Photon.Pun.PhotonTransformViewClassic.OnPhotonSerializeView.
Vector3 Photon.Pun.PhotonTransformViewPositionControl.GetOldestStoredNetworkPosition()
void Photon.Pun.PhotonTransformViewPositionControl.SerializeData(Vector3 currentPosition, PhotonStream stream, PhotonMessageInfo info)
void Photon.Pun.PhotonTransformViewPositionControl.DeserializeData(PhotonStream stream, PhotonMessageInfo info)