Photon::Pun::Simple::Pooling::Pool
Dictionary<GameObject, Stack<Pool> > Photon.Pun.Simple.Pooling.Pool.pools
The Dict of pools, indexed by the source prefab.
Dictionary<GameObject, PoolItemDef> Photon.Pun.Simple.Pooling.Pool.poolItemDefs
Stores the creation parameters for a pool, for use when expanding it.
GameObject Photon.Pun.Simple.Pooling.Pool.origPrefab
Referenced by Photon.Pun.Simple.Pooling.Pool.Spawn.
Rigidbody Photon.Pun.Simple.Pooling.Pool.rb
Referenced by Photon.Pun.Simple.Pooling.Pool.CacheComponents.
Component Photon.Pun.Simple.Pooling.Pool.extraScript
float Photon.Pun.Simple.Pooling.Pool.deathClock
Referenced by Photon.Pun.Simple.Pooling.Pool.Spawn.
static void Photon.Pun.Simple.Pooling.Pool.AddPrefabToPool(GameObject _prefab, int startingSize=8, int _growBy=8, Type _scriptToAdd=null, bool tidyUp=false)
Add a prefab to the Pool list, and create a pool.
Returns the list index. _prefab _growBy _scriptToAdd Indicate a typeof(Component) that you want added (if not already there) to the root of all instantiated pool items.
Referenced by Photon.Pun.Simple.SyncCannon.OnAwake.
static Pool Photon.Pun.Simple.Pooling.Pool.Spawn(GameObject origPrefab, Transform t, float duration=5f)
References Photon.Pun.Simple.Pooling.Pool.origPrefab, Photon.Pun.Simple.Pooling.Pool.Spawn.
Referenced by Photon.Pun.Simple.Pooling.Pool.Spawn, Photon.Pun.Simple.SyncCannon.Trigger, Photon.Pun.Simple.GenericHitscanExt.VisualizeHitscan.
static Pool Photon.Pun.Simple.Pooling.Pool.Spawn(GameObject origPrefab, Vector3 pos, Quaternion rot, Vector3 scl, float duration=5f)
References Photon.Pun.Simple.Pooling.Pool.origPrefab, Photon.Pun.Simple.Pooling.Pool.Spawn.
static Pool Photon.Pun.Simple.Pooling.Pool.Spawn(GameObject origPrefab, Vector3 pos, Quaternion rot, float duration=5f)
References Photon.Pun.Simple.Pooling.Pool.deathClock, Photon.Pun.Simple.Pooling.Pool.origPrefab.
static void Photon.Pun.Simple.Pooling.Pool.GrowPool(GameObject _prefab, int growAmt=-1)
static void Photon.Pun.Simple.Pooling.Pool.AddItemToPool(GameObject go, GameObject _prefab, PoolItemDef def)
static void Photon.Pun.Simple.Pooling.Pool.ReturnToPool(Pool p, GameObject _prefab)
void Photon.Pun.Simple.Pooling.Pool.CacheComponents()
References Photon.Pun.Simple.Pooling.Pool.rb.
void Photon.Pun.Simple.Pooling.Pool.Update()
void Photon.Pun.Simple.Pooling.Pool.OnDisable()