Photon::Pun::Demo::Procedural::Cluster
string Photon.Pun.Demo.Procedural.Cluster.propertiesKey
Dictionary<int, float> Photon.Pun.Demo.Procedural.Cluster.propertiesValue
int Photon.Pun.Demo.Procedural.Cluster.ClusterId
Dictionary<int, GameObject> Photon.Pun.Demo.Procedural.Cluster.Blocks
Referenced by Photon.Pun.Demo.Procedural.Cluster.AddBlock, Photon.Pun.Demo.Procedural.Cluster.Awake, Photon.Pun.Demo.Procedural.Cluster.DecreaseBlockHeight, Photon.Pun.Demo.Procedural.Cluster.DestroyCluster, Photon.Pun.Demo.Procedural.Cluster.IncreaseBlockHeight, Photon.Pun.Demo.Procedural.Cluster.SetBlockHeightRemote.
void Photon.Pun.Demo.Procedural.Cluster.Awake()
References Photon.Pun.Demo.Procedural.Cluster.Blocks.
void Photon.Pun.Demo.Procedural.Cluster.AddBlock(int blockId, GameObject block)
Adds a Block to the Cluster.
This is called by the WorldGenerator while the generation process is running. In order to modify Blocks directly, we are storing the ID as well as a reference to the certain GameObject.
References Photon.Pun.Demo.Procedural.Cluster.Blocks.
void Photon.Pun.Demo.Procedural.Cluster.DestroyCluster()
Gets called before a new world can be generated.
Destroys each Block from this Cluster and removes the data stored in the Custom Room Properties.
References Photon.Pun.Demo.Procedural.Cluster.Blocks, Photon.Pun.PhotonNetwork.IsMasterClient.
void Photon.Pun.Demo.Procedural.Cluster.DecreaseBlockHeight(int blockId)
Decreases a Block's height locally before applying the modification to the Custom Room Properties.
References Photon.Pun.Demo.Procedural.Cluster.Blocks.
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.DecreaseBlockHeight.
void Photon.Pun.Demo.Procedural.Cluster.IncreaseBlockHeight(int blockId)
Increases a Block's height locally before applying the modification to the Custom Room Properties.
References Photon.Pun.Demo.Procedural.Cluster.Blocks.
Referenced by Photon.Pun.Demo.Procedural.WorldGenerator.IncreaseBlockHeight.
void Photon.Pun.Demo.Procedural.Cluster.SetBlockHeightRemote(int blockId, float height)
Gets called when a remote client has modified a certain Block within this Cluster.
Called by the WorldGenerator or the Cluster itself after the Custom Room Properties have been updated.
References Photon.Pun.Demo.Procedural.Cluster.Blocks.
Referenced by Photon.Pun.Demo.Procedural.Cluster.OnRoomPropertiesUpdate.
override void Photon.Pun.Demo.Procedural.Cluster.OnRoomPropertiesUpdate(Hashtable propertiesThatChanged)
Gets called whenever the Custom Room Properties are updated.
When the changed properties contain the previously set PropertiesKey (basically the Cluster ID), the Cluster and its Blocks will be updated accordingly.
References Photon.Pun.Demo.Procedural.Cluster.SetBlockHeightRemote.
void Photon.Pun.Demo.Procedural.Cluster.Start()
Sets the unique key of this Cluster used for storing modifications within the Custom Room Properties.
void Photon.Pun.Demo.Procedural.Cluster.SetBlockHeightLocal(int blockId, float height)
Gets called whenever the local client modifies any Block within this Cluster.
The modification will be applied to the Block first before it is published to the Custom Room Properties.
void Photon.Pun.Demo.Procedural.Cluster.UpdateRoomProperties(int blockId, float height)
Gets called in order to update the Custom Room Properties with the modification made by the local client.
void Photon.Pun.Demo.Procedural.Cluster.RemoveClusterFromRoomProperties()
Removes the modifications of this Cluster from the Custom Room Properties.