Photon::Pun::PhotonEditor
PhotonSetupStates
Type Photon.Pun.PhotonEditor.WindowType
Referenced by Photon.Pun.PhotonEditor.ShowRegistrationWizard.
string Photon.Pun.PhotonEditor.DocumentationLocation
Referenced by Photon.Pun.PhotonEditor.UiMainWizard.
string Photon.Pun.PhotonEditor.UrlFreeLicense
string Photon.Pun.PhotonEditor.UrlForum
Referenced by Photon.Pun.PhotonEditor.UiMainWizard.
string Photon.Pun.PhotonEditor.UrlCompare
Referenced by Photon.Pun.PhotonEditor.UiMainWizard.
string Photon.Pun.PhotonEditor.UrlHowToSetup
string Photon.Pun.PhotonEditor.UrlAppIDExplained
Vector2 Photon.Pun.PhotonEditor.scrollPos
readonly Vector2 Photon.Pun.PhotonEditor.preferredSize
bool Photon.Pun.PhotonEditor.isSetupWizard
PhotonSetupStates Photon.Pun.PhotonEditor.photonSetupState
bool Photon.Pun.PhotonEditor.minimumInput
bool Photon.Pun.PhotonEditor.useMail
bool Photon.Pun.PhotonEditor.useAppId
bool Photon.Pun.PhotonEditor.useSkip
bool Photon.Pun.PhotonEditor.highlightedSettings
bool Photon.Pun.PhotonEditor.close
string Photon.Pun.PhotonEditor.mailOrAppId
string Photon.Pun.PhotonEditor.emailSentToAccount
bool Photon.Pun.PhotonEditor.emailSentToAccountIsRegistered
AccountService Photon.Pun.PhotonEditor.serviceClient
Texture2D Photon.Pun.PhotonEditor.BackgroundImage
double Photon.Pun.PhotonEditor.lastWarning
bool Photon.Pun.PhotonEditor.postInspectorUpdate
PunWizardText Photon.Pun.PhotonEditor.CurrentLang
Referenced by Photon.Pun.PhotonEditor.ClearRpcList, Photon.Pun.PhotonEditor.MenuItemOpenWizard, Photon.Pun.PhotonEditor.RegisterWithEmail, Photon.Pun.PhotonEditor.ShowRegistrationWizard, Photon.Pun.PhotonEditor.UiMainWizard, Photon.Pun.PhotonEditor.UiSetupApp, Photon.Pun.PhotonEditor.UpdateRpcList.
string Photon.Pun.PhotonEditor.CustomToken
third parties custom token
Referenced by Photon.Pun.PhotonEditor.RegisterWithEmail.
string Photon.Pun.PhotonEditor.CustomContext
third parties custom context
Referenced by Photon.Pun.PhotonEditor.RegisterWithEmail.
const string Photon.Pun.PhotonEditor.UrlDevNet
Referenced by Photon.Pun.PhotonEditor.UiMainWizard.
const string Photon.Pun.PhotonEditor.UrlCloudDashboard
Referenced by Photon.Pun.PhotonEditor.UiMainWizard, Photon.Pun.PhotonEditor.UiSetupApp.
const string Photon.Pun.PhotonEditor.UrlPunSettings
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI.
static void Photon.Pun.PhotonEditor.MenuItemOpenWizard()
References Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PunWizardText.WindowTitle.
static void Photon.Pun.PhotonEditor.MenuItemHighlightSettings()
static void Photon.Pun.PhotonEditor.ShowRegistrationWizard()
Creates an Editor window, showing the cloud-registration wizard for Photon (entry point to setup PUN).
References Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PhotonEditor.PhotonEditor, Photon.Pun.PunWizardText.WindowTitle, Photon.Pun.PhotonEditor.WindowType.
static void Photon.Pun.PhotonEditor.InitializeOnLoadMethod()
static void Photon.Pun.PhotonEditor.UpdateRpcList()
References Photon.Pun.PunWizardText.CancelButton, Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PunWizardText.FullRPCListLabel, Photon.Pun.PunWizardText.FullRPCListTitle, Photon.Pun.PunWizardText.IncorrectRPCListLabel, Photon.Pun.PunWizardText.IncorrectRPCListTitle, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.PunWizardText.RemoveOutdatedRPCsLabel, Photon.Pun.ServerSettings.RpcList, Photon.Pun.PunWizardText.SkipRPCListUpdateLabel.
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI.
static void Photon.Pun.PhotonEditor.ClearRpcList()
References Photon.Pun.PunWizardText.CancelButton, Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.PunWizardText.PUNNameReplaceLabel, Photon.Pun.PunWizardText.PUNNameReplaceTitle, Photon.Pun.ServerSettings.RpcList, Photon.Pun.PunWizardText.RPCListCleared, Photon.Pun.PunWizardText.ServerSettingsCleanedWarning.
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI.
static void Photon.Pun.PhotonEditor.OnDelayCall()
static void Photon.Pun.PhotonEditor.OnProjectChanged()
static void Photon.Pun.PhotonEditor.OnCompileStarted(string obj)
static void Photon.Pun.PhotonEditor.OnDidReloadScripts()
static void Photon.Pun.PhotonEditor.PlayModeStateChanged(PlayModeStateChange state)
static void Photon.Pun.PhotonEditor.HighlightSettings()
static void Photon.Pun.PhotonEditor.SaveSettings()
Photon.Pun.PhotonEditor.PhotonEditor()
Referenced by Photon.Pun.PhotonEditor.ShowRegistrationWizard.
void Photon.Pun.PhotonEditor.Awake()
References Photon.Realtime.AppSettings.AppIdRealtime, Photon.Pun.ServerSettings.AppSettings, Photon.Pun.PhotonNetwork.PhotonServerSettings.
void Photon.Pun.PhotonEditor.Update()
virtual void Photon.Pun.PhotonEditor.OnGUI()
References Photon.Pun.PhotonEditor.UiMainWizard, Photon.Pun.PhotonEditor.UiSetupApp.
virtual void Photon.Pun.PhotonEditor.UiSetupApp()
References Photon.Pun.PunWizardText.AlreadyRegisteredInfo, Photon.Pun.PunWizardText.AppliedToSettingsInfo, Photon.Pun.PunWizardText.CloseWindowButton, Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PunWizardText.EmailOrAppIdLabel, Photon.Pun.ServerSettings.IsAppId, Photon.Pun.PunWizardText.MainMenuButton, Photon.Pun.PunWizardText.OpenCloudDashboardText, Photon.Pun.PunWizardText.OpenCloudDashboardTooltip, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.PunWizardText.RegisteredNewAccountInfo, Photon.Pun.PhotonEditor.RegisterWithEmail, Photon.Pun.PunWizardText.SetupButton, Photon.Pun.PunWizardText.SetupCompleteInfo, Photon.Pun.PunWizardText.SetupWizardInfo, Photon.Pun.PunWizardText.SetupWizardTitle, Photon.Pun.PunWizardText.SkipButton, Photon.Pun.PunWizardText.SkipRegistrationInfo, Photon.Pun.PhotonEditor.UrlCloudDashboard, Photon.Pun.ServerSettings.UseCloud.
Referenced by Photon.Pun.PhotonEditor.OnGUI.
virtual void Photon.Pun.PhotonEditor.UiMainWizard()
References Photon.Pun.PunWizardText.ComparisonPageButton, Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PunWizardText.DocumentationLabel, Photon.Pun.PhotonEditor.DocumentationLocation, Photon.Pun.PunWizardText.LocateSettingsButton, Photon.Pun.PunWizardText.OpenCloudDashboardText, Photon.Pun.PunWizardText.OpenCloudDashboardTooltip, Photon.Pun.PunWizardText.OpenDevNetText, Photon.Pun.PunWizardText.OpenDevNetTooltip, Photon.Pun.PunWizardText.OpenForumText, Photon.Pun.PunWizardText.OpenForumTooltip, Photon.Pun.PunWizardText.OpenPDFText, Photon.Pun.PunWizardText.OpenPDFTooltip, Photon.Pun.PunWizardText.OwnHostCloudCompareLabel, Photon.Pun.PunWizardText.PUNWizardLabel, Photon.Pun.PunWizardText.SettingsButton, Photon.Pun.PunWizardText.SettingsHighlightLabel, Photon.Pun.PunWizardText.SetupButton, Photon.Pun.PunWizardText.SetupServerCloudLabel, Photon.Pun.PhotonEditor.UrlCloudDashboard, Photon.Pun.PhotonEditor.UrlCompare, Photon.Pun.PhotonEditor.UrlDevNet, Photon.Pun.PhotonEditor.UrlForum, Photon.Pun.PunWizardText.WizardMainWindowInfo.
Referenced by Photon.Pun.PhotonEditor.OnGUI.
virtual void Photon.Pun.PhotonEditor.RegisterWithEmail(string email)
References Photon.Pun.PunWizardText.ConnectionInfo, Photon.Pun.PunWizardText.ConnectionTitle, Photon.Pun.PhotonEditor.CurrentLang, Photon.Pun.PhotonEditor.CustomContext, Photon.Pun.PhotonEditor.CustomToken, Photon.Pun.PhotonNetwork.PunVersion.
Referenced by Photon.Pun.PhotonEditor.UiSetupApp.
void Photon.Pun.PhotonEditor.UiTitleBox(string title, Texture2D bgIcon)
void Photon.Pun.PhotonEditor.RegisterWithEmailSuccessCallback(AccountServiceResponse res)
void Photon.Pun.PhotonEditor.RegisterWithEmailErrorCallback(string error)
void Photon.Pun.PhotonEditor.DisplayErrorMessage(string error)