Photon::Pun::Demo::Cockpit::PlayerDetailsController
GameObject Photon.Pun.Demo.Cockpit.PlayerDetailsController.ContentPanel
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnPlayerLeftRoom, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.
PropertyCell Photon.Pun.Demo.Cockpit.PlayerDetailsController.PropertyCellPrototype
Text Photon.Pun.Demo.Cockpit.PlayerDetailsController.UpdateStatusText
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnEnable.
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.BuiltInPropertiesPanel
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.PlayerNumberingExtensionPanel
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.ScoreExtensionPanel
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.TeamExtensionPanel
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.TurnExtensionPanel
Transform Photon.Pun.Demo.Cockpit.PlayerDetailsController.CustomPropertiesPanel
GameObject Photon.Pun.Demo.Cockpit.PlayerDetailsController.MasterClientToolBar
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnMasterClientSwitched, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.
GameObject Photon.Pun.Demo.Cockpit.PlayerDetailsController.NotInRoomLabel
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnEnable, Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnPlayerLeftRoom, Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.
Dictionary<string, PropertyCell> Photon.Pun.Demo.Cockpit.PlayerDetailsController.builtInPropsCellList
Player Photon.Pun.Demo.Cockpit.PlayerDetailsController._player
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.Awake()
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.AddProperty(string property, string value, Transform parent)
string Photon.Pun.Demo.Cockpit.PlayerDetailsController.ParseKey(object key)
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnPlayerNumberingChanged()
IEnumerator Photon.Pun.Demo.Cockpit.PlayerDetailsController.UpdateUIPing()
Hashtable Photon.Pun.Demo.Cockpit.PlayerDetailsController.GetAllPlayerBuiltIntProperties()
override void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnEnable()
References Photon.Pun.Demo.Cockpit.PlayerDetailsController.NotInRoomLabel, Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerNumberingChanged, Photon.Pun.Demo.Cockpit.PlayerDetailsController.UpdateStatusText.
override void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnDisable()
References Photon.Pun.UtilityScripts.PlayerNumbering.OnPlayerNumberingChanged.
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget(Player player)
References Photon.Pun.Demo.Cockpit.PlayerDetailsController.ContentPanel, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Player.CustomProperties, Photon.Realtime.Player.IsMasterClient, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.Demo.Cockpit.PlayerDetailsController.MasterClientToolBar, Photon.Pun.Demo.Cockpit.PlayerDetailsController.NotInRoomLabel, Photon.Realtime.Room.PlayerCount, Photon.Pun.UtilityScripts.PunPlayerScores.PlayerScoreProp, Photon.Pun.Demo.Cockpit.PlayerDetailsController.ResetList.
Referenced by Photon.Pun.Demo.Cockpit.PunCockpit.OnJoinedRoom, Photon.Pun.Demo.Cockpit.PlayerListView.SelectPlayer.
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.KickOutPlayer()
References Photon.Pun.PhotonNetwork.CloseConnection.
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetAsMaster()
References Photon.Pun.PhotonNetwork.SetMasterClient.
override void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
References Photon.Pun.Demo.Cockpit.PlayerDetailsController.ContentPanel, Photon.Pun.Demo.Cockpit.PlayerDetailsController.NotInRoomLabel.
override void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnMasterClientSwitched(Player newMasterClient)
Called after switching to a new MasterClient when the current one leaves.
This is not called when this client enters a room. The former MasterClient is still in the player list when this method get called.
References Photon.Pun.Demo.Cockpit.PlayerDetailsController.MasterClientToolBar.
override void Photon.Pun.Demo.Cockpit.PlayerDetailsController.OnPlayerPropertiesUpdate(Player target, ExitGames.Client.Photon.Hashtable changedProps)
References Photon.Realtime.Player.ActorNumber.
void Photon.Pun.Demo.Cockpit.PlayerDetailsController.ResetList()
Referenced by Photon.Pun.Demo.Cockpit.PlayerDetailsController.SetPlayerTarget.