Photon::Pun::Simple::SyncTransform::Frame
bool Photon.Pun.Simple.SyncTransform.Frame.hasTeleported
Referenced by Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.Frame.Clear, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnNetSerialize.
Matrix Photon.Pun.Simple.SyncTransform.Frame.m
Referenced by Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.FastCompareUncompressed, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Pun.Simple.SyncTransform.Frame.Set, Photon.Pun.Simple.SyncTransform.Frame.ToString.
CompressedMatrix Photon.Pun.Simple.SyncTransform.Frame.cm
Referenced by Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.FastCompareCompressed, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnNetSerialize, Photon.Pun.Simple.SyncTransform.Frame.Set.
SyncTransform Photon.Pun.Simple.SyncTransform.Frame.owner
Matrix Photon.Pun.Simple.SyncTransform.Frame.telem
Referenced by Photon.Pun.Simple.SyncTransform.ApplyFrame, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState.
CompressedMatrix Photon.Pun.Simple.SyncTransform.Frame.telecm
Referenced by Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.OnCaptureCurrentState, Photon.Pun.Simple.SyncTransform.OnNetSerialize.
int Photon.Pun.Simple.SyncTransform.Frame.parentHash
Referenced by Photon.Pun.Simple.SyncTransform.Frame.Clear, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame.
int Photon.Pun.Simple.SyncTransform.Frame.telePparentHash
Photon.Pun.Simple.SyncTransform.Frame.Frame()
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.parentHash, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.Frame.telem.
Referenced by Photon.Pun.Simple.SyncTransform.Frame.CopyFrom.
Photon.Pun.Simple.SyncTransform.Frame.Frame(SyncTransform sst, int frameId)
References Photon.Compression.TransformCrusher.Capture, Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.parentHash, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.Frame.telem, Photon.Pun.Simple.SyncTransform.transformCrusher.
Photon.Pun.Simple.SyncTransform.Frame.Frame(Frame srcFrame, int frameId)
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Pun.Simple.SyncTransform.Frame.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.Frame.telem.
void Photon.Pun.Simple.SyncTransform.Frame.Set(SyncTransform sst, int frameId)
References Photon.Compression.TransformCrusher.Capture, Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.transformCrusher.
override void Photon.Pun.Simple.SyncTransform.Frame.CopyFrom(FrameBase sourceFrame)
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.CompressedMatrix.CopyFrom, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Pun.Simple.SyncTransform.Frame.parentHash, Photon.Pun.Simple.SyncTransform.Frame.telecm, Photon.Pun.Simple.SyncTransform.Frame.telem.
Referenced by Photon.Pun.Simple.SyncTransform.ExtrapolateFrame, Photon.Pun.Simple.SyncTransform.Frame.Frame, Photon.Pun.Simple.SyncTransform.InterpolateFrame.
bool Photon.Pun.Simple.SyncTransform.Frame.FastCompareCompressed(Frame other)
Compares only the compressed values for equality
References Photon.Pun.Simple.SyncTransform.Frame.cm, Photon.Compression.CompressedMatrix.Equals.
bool Photon.Pun.Simple.SyncTransform.Frame.FastCompareUncompressed(Frame other)
Compares only the compressed values for equality
References Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation, Photon.Compression.Matrix.scale.
override void Photon.Pun.Simple.SyncTransform.Frame.Clear()
References Photon.Pun.Simple.SyncTransform.Frame.hasTeleported, Photon.Pun.Simple.SyncTransform.Frame.parentHash.
override string Photon.Pun.Simple.SyncTransform.Frame.ToString()
References Photon.Pun.Simple.FrameBase.frameId, Photon.Pun.Simple.SyncTransform.Frame.m, Photon.Compression.Matrix.position, Photon.Compression.Matrix.rotation.