Photon::Pun::PhotonGUI
GUIStyle Photon.Pun.PhotonGUI.m_DefaultTitleStyle
GUIStyle Photon.Pun.PhotonGUI.m_DefaultContainerStyle
GUIStyle Photon.Pun.PhotonGUI.m_DefaultAddButtonStyle
GUIStyle Photon.Pun.PhotonGUI.m_DefaultRemoveButtonStyle
GUIStyle Photon.Pun.PhotonGUI.m_DefaultContainerRowStyle
GUIStyle Photon.Pun.PhotonGUI.m_FoldoutBold
GUIStyle Photon.Pun.PhotonGUI.m_RichLabel
Texture2D Photon.Pun.PhotonGUI.m_HelpIcon
Texture2D Photon.Pun.PhotonGUI.m_CopyIcon
Texture2D Photon.Pun.PhotonGUI.m_CopyIconPro
GUIStyle? Photon.Pun.PhotonGUI.DefaultTitleStyle
GUIStyle Photon.Pun.PhotonGUI.DefaultContainerStyle
GUIStyle Photon.Pun.PhotonGUI.DefaultAddButtonStyle
Referenced by Photon.Pun.PhotonGUI.AddButton.
GUIStyle Photon.Pun.PhotonGUI.DefaultRemoveButtonStyle
GUIStyle Photon.Pun.PhotonGUI.DefaultContainerRowStyle
GUIStyle Photon.Pun.PhotonGUI.FoldoutBold
GUIStyle Photon.Pun.PhotonGUI.RichLabel
Texture2D Photon.Pun.PhotonGUI.HelpIcon
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI.
Texture2D Photon.Pun.PhotonGUI.CopyIcon
Referenced by Photon.Pun.ServerSettingsInspector.OnInspectorGUI.
static string Photon.Pun.PhotonGUI.GetIconPath(string iconFileName)
static void Photon.Pun.PhotonGUI.ContainerHeader(string headline)
static bool Photon.Pun.PhotonGUI.ContainerHeaderToggle(string headline, bool toggle)
Referenced by Photon.Pun.PhotonRigidbody2DViewEditor.OnInspectorGUI, Photon.Pun.PhotonRigidbodyViewEditor.OnInspectorGUI.
static bool Photon.Pun.PhotonGUI.ContainerHeaderFoldout(string headline, bool foldout, System.Action buttonAction=null, string buttonName=null)
static Rect Photon.Pun.PhotonGUI.ContainerBody(float height)
Referenced by Photon.Pun.PhotonRigidbody2DViewEditor.OnInspectorGUI, Photon.Pun.PhotonRigidbodyViewEditor.OnInspectorGUI.
static bool Photon.Pun.PhotonGUI.AddButton()
References Photon.Pun.PhotonGUI.DefaultAddButtonStyle.
static void Photon.Pun.PhotonGUI.DrawSplitter(Rect position)
static void Photon.Pun.PhotonGUI.DrawGizmoOptions(Rect position, string label, SerializedProperty gizmoEnabledProperty, SerializedProperty gizmoColorProperty, SerializedProperty gizmoTypeProperty, SerializedProperty gizmoSizeProperty)
static Rect Photon.Pun.PhotonGUI.DoContainerBody(float height)
static bool Photon.Pun.PhotonGUI.DoContainerHeaderToggle(string headline, bool toggle)
static bool Photon.Pun.PhotonGUI.DoContainerHeaderFoldout(string headline, bool foldout, System.Action buttonAction=null, string buttonLabel=null, float buttonWidth=48)
static Rect Photon.Pun.PhotonGUI.DoContainerHeader(string headline, float height, float contentOffset)