Photon::Pun::Demo::SlotRacer::Utils::Bezier
static Vector3 Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetPoint(Vector3 p0, Vector3 p1, Vector3 p2, float t)
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierCurve.GetPoint, Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetPoint.
static Vector3 Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetFirstDerivative(Vector3 p0, Vector3 p1, Vector3 p2, float t)
Referenced by Photon.Pun.Demo.SlotRacer.Utils.BezierCurve.GetVelocity, Photon.Pun.Demo.SlotRacer.Utils.BezierSpline.GetVelocity.
static Vector3 Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetPoint(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)
static Vector3 Photon.Pun.Demo.SlotRacer.Utils.Bezier.GetFirstDerivative(Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)