Photon::Realtime::LoadBalancingPeer
Type Photon.Realtime.LoadBalancingPeer.PingImplementation
Obsolete accessor to the RegionHandler.PingImplementation.
readonly Pool<ParameterDictionary> Photon.Realtime.LoadBalancingPeer.paramDictionaryPool
Photon.Realtime.LoadBalancingPeer.LoadBalancingPeer(ConnectionProtocol protocolType)
Creates a Peer with specified connection protocol.
You need to set the Listener before using the peer. Each connection protocol has it's own default networking ports for Photon. protocolType The preferred option is UDP.
Referenced by Photon.Realtime.LoadBalancingClient.DebugReturn, Photon.Realtime.LoadBalancingClient.LoadBalancingClient, Photon.Realtime.ConnectionHandler.RealtimeFallbackThread.
Photon.Realtime.LoadBalancingPeer.LoadBalancingPeer(IPhotonPeerListener listener, ConnectionProtocol protocolType)
Creates a Peer with specified connection protocol and a Listener for callbacks.
virtual bool Photon.Realtime.LoadBalancingPeer.OpGetRegions(string appId)
References Photon.Realtime.ParameterCode.ApplicationId, Photon.Realtime.OperationCode.GetRegions.
virtual bool Photon.Realtime.LoadBalancingPeer.OpJoinLobby(TypedLobby lobby=null)
Joins the lobby on the Master Server, where you get a list of RoomInfos of currently open rooms.
This is an async request which triggers a OnOperationResponse() call. lobby The lobby join to. If the operation could be sent (has to be connected).
References Photon.Realtime.OperationCode.JoinLobby, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType.
Referenced by Photon.Realtime.LoadBalancingClient.OpJoinLobby.
virtual bool Photon.Realtime.LoadBalancingPeer.OpLeaveLobby()
Leaves the lobby on the Master Server.
This is an async request which triggers a OnOperationResponse() call. If the operation could be sent (requires connection).
References Photon.Realtime.OperationCode.LeaveLobby.
Referenced by Photon.Realtime.LoadBalancingClient.OpLeaveLobby.
virtual bool Photon.Realtime.LoadBalancingPeer.OpCreateRoom(EnterRoomParams opParams)
Creates a room (on either Master or Game Server).
The OperationResponse depends on the server the peer is connected to: Master will return a Game Server to connect to. Game Server will return the joined Room's data. This is an async request which triggers a OnOperationResponse() call. If the room is already existing, the OperationResponse will have a returnCode of ErrorCode.GameAlreadyExists.
References Photon.Realtime.ParameterCode.Add, Photon.Realtime.ParameterCode.Broadcast, Photon.Realtime.OperationCode.CreateGame, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.TypedLobby.IsDefault, Photon.Realtime.EnterRoomParams.Lobby, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.TypedLobby.Name, Photon.Realtime.EnterRoomParams.PlayerProperties, Photon.Realtime.ParameterCode.PlayerProperties, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.ParameterCode.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.TypedLobby.Type.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OpCreateRoom.
virtual bool Photon.Realtime.LoadBalancingPeer.OpJoinRoom(EnterRoomParams opParams)
Joins a room by name or creates new room if room with given name not exists.
The OperationResponse depends on the server the peer is connected to: Master will return a Game Server to connect to. Game Server will return the joined Room's data. This is an async request which triggers a OnOperationResponse() call. If the room is not existing (anymore), the OperationResponse will have a returnCode of ErrorCode.GameDoesNotExist. Other possible ErrorCodes are: GameClosed, GameFull. If the operation could be sent (requires connection).
References Photon.Realtime.ParameterCode.Add, Photon.Realtime.ParameterCode.Broadcast, Photon.Realtime.EnterRoomParams.ExpectedUsers, Photon.Realtime.TypedLobby.IsDefault, Photon.Realtime.OperationCode.JoinGame, Photon.Realtime.ParameterCode.JoinMode, Photon.Realtime.EnterRoomParams.Lobby, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.TypedLobby.Name, Photon.Realtime.EnterRoomParams.PlayerProperties, Photon.Realtime.ParameterCode.PlayerProperties, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.ParameterCode.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.TypedLobby.Type.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse, Photon.Realtime.LoadBalancingClient.OpJoinOrCreateRoom, Photon.Realtime.LoadBalancingClient.OpJoinRoom, Photon.Realtime.LoadBalancingClient.OpRejoinRoom.
virtual bool Photon.Realtime.LoadBalancingPeer.OpJoinRandomRoom(OpJoinRandomRoomParams opJoinRandomRoomParams)
Operation to join a random, available room.
Overloads take additional player properties. This is an async request which triggers a OnOperationResponse() call. If all rooms are closed or full, the OperationResponse will have a returnCode of ErrorCode.NoRandomMatchFound. If successful, the OperationResponse contains a gameserver address and the name of some room. If the operation could be sent currently (requires connection).
References Photon.Realtime.ParameterCode.Add, Photon.Realtime.ParameterCode.Data, Photon.Realtime.OpJoinRandomRoomParams.ExpectedCustomRoomProperties, Photon.Realtime.OpJoinRandomRoomParams.ExpectedMaxPlayers, Photon.Realtime.OpJoinRandomRoomParams.ExpectedUsers, Photon.Realtime.ParameterCode.GameProperties, Photon.Realtime.TypedLobby.IsDefault, Photon.Realtime.OperationCode.JoinRandomGame, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.OpJoinRandomRoomParams.MatchingType, Photon.Realtime.ParameterCode.MatchMakingType, Photon.Realtime.GamePropertyKey.MaxPlayers, Photon.Realtime.TypedLobby.Name, Photon.Realtime.OpJoinRandomRoomParams.SqlLobbyFilter, Photon.Realtime.TypedLobby.Type, Photon.Realtime.OpJoinRandomRoomParams.TypedLobby.
Referenced by Photon.Realtime.LoadBalancingClient.OpJoinRandomRoom.
virtual bool Photon.Realtime.LoadBalancingPeer.OpJoinRandomOrCreateRoom(OpJoinRandomRoomParams opJoinRandomRoomParams, EnterRoomParams createRoomParams)
Only used on the Master Server.
It will assign a game server and room to join-or-create. On the Game Server, the OpJoin is used with option "create if not exists".
References Photon.Realtime.ParameterCode.Add, Photon.Realtime.ParameterCode.Data, Photon.Realtime.OpJoinRandomRoomParams.ExpectedCustomRoomProperties, Photon.Realtime.OpJoinRandomRoomParams.ExpectedMaxPlayers, Photon.Realtime.OpJoinRandomRoomParams.ExpectedUsers, Photon.Realtime.ParameterCode.GameProperties, Photon.Realtime.TypedLobby.IsDefault, Photon.Realtime.ParameterCode.JoinMode, Photon.Realtime.OperationCode.JoinRandomGame, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.OpJoinRandomRoomParams.MatchingType, Photon.Realtime.ParameterCode.MatchMakingType, Photon.Realtime.GamePropertyKey.MaxPlayers, Photon.Realtime.TypedLobby.Name, Photon.Realtime.EnterRoomParams.RoomName, Photon.Realtime.ParameterCode.RoomName, Photon.Realtime.EnterRoomParams.RoomOptions, Photon.Realtime.OpJoinRandomRoomParams.SqlLobbyFilter, Photon.Realtime.TypedLobby.Type, Photon.Realtime.OpJoinRandomRoomParams.TypedLobby.
Referenced by Photon.Realtime.LoadBalancingClient.OpJoinRandomOrCreateRoom.
virtual bool Photon.Realtime.LoadBalancingPeer.OpLeaveRoom(bool becomeInactive, bool sendAuthCookie=false)
Leaves a room with option to come back later or "for good".
becomeInactive Async games can be re-joined (loaded) later on. Set to false, if you want to abandon a game entirely. sendAuthCookie WebFlag: Securely transmit the encrypted object AuthCookie to the web service in PathLeave webhook when available If the opteration can be send currently.
References Photon.Realtime.ParameterCode.EventForward, Photon.Realtime.ParameterCode.IsInactive, Photon.Realtime.OperationCode.Leave, Photon.Realtime.WebFlags.SendAuthCookieConst.
Referenced by Photon.Realtime.LoadBalancingClient.OpLeaveRoom.
virtual bool Photon.Realtime.LoadBalancingPeer.OpGetGameList(TypedLobby lobby, string queryData)
Gets a list of games matching a SQL-like where clause.
Operation is only available in lobbies of type SqlLobby. This is an async request which triggers a OnOperationResponse() call. Returned game list is stored in RoomInfoList. https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby::sql_lobby_type lobby The lobby to query. Has to be of type SqlLobby. queryData The sql query statement. If the operation could be sent (has to be connected).
References Photon.Realtime.ParameterCode.Data, Photon.Realtime.OperationCode.GetGameList, Photon.Realtime.TypedLobby.IsDefault, Photon.Realtime.ParameterCode.LobbyName, Photon.Realtime.ParameterCode.LobbyType, Photon.Realtime.TypedLobby.Name, Photon.Realtime.TypedLobby.Type.
Referenced by Photon.Realtime.LoadBalancingClient.OpGetGameList.
virtual bool Photon.Realtime.LoadBalancingPeer.OpFindFriends(string[] friendsToFind, FindFriendsOptions options=null)
Request the rooms and online status for a list of friends (each client must set a unique username via OpAuthenticate).
Used on Master Server to find the rooms played by a selected list of users. Users identify themselves by using OpAuthenticate with a unique user ID. The list of user IDs must be fetched from some other source (not provided by Photon). The server response includes 2 arrays of info (each index matching a friend from the request): ParameterCode.FindFriendsResponseOnlineList = bool[] of online states ParameterCode.FindFriendsResponseRoomIdList = string[] of room names (empty string if not in a room) The options may be used to define which state a room must match to be returned. friendsToFind Array of friend's names (make sure they are unique). options Options that affect the result of the FindFriends operation. If the operation could be sent (requires connection).
References Photon.Realtime.OperationCode.FindFriends, Photon.Realtime.ParameterCode.FindFriendsOptions, Photon.Realtime.ParameterCode.FindFriendsRequestList.
Referenced by Photon.Realtime.LoadBalancingClient.OpFindFriends.
bool Photon.Realtime.LoadBalancingPeer.OpSetCustomPropertiesOfActor(int actorNr, Hashtable actorProperties)
bool Photon.Realtime.LoadBalancingPeer.OpSetCustomPropertiesOfRoom(Hashtable gameProperties)
virtual bool Photon.Realtime.LoadBalancingPeer.OpAuthenticate(string appId, string appVersion, AuthenticationValues authValues, string regionCode, bool getLobbyStatistics)
Sends this app's appId and appVersion to identify this application server side.
This is an async request which triggers a OnOperationResponse() call. This operation makes use of encryption, if that is established before. See: EstablishEncryption(). Check encryption with IsEncryptionAvailable. This operation is allowed only once per connection (multiple calls will have ErrorCode != Ok). appId Your application's name or ID to authenticate. This is assigned by Photon Cloud (webpage). appVersion The client's version (clients with differing client appVersions are separated and players don't meet). authValues Contains all values relevant for authentication. Even without account system (external Custom Auth), the clients are allowed to identify themselves. regionCode Optional region code, if the client should connect to a specific Photon Cloud Region. getLobbyStatistics Set to true on Master Server to receive "Lobby Statistics" events. If the operation could be sent (has to be connected).
References Photon.Realtime.ParameterCode.ApplicationId, Photon.Realtime.ParameterCode.AppVersion, Photon.Realtime.OperationCode.Authenticate, Photon.Realtime.AuthenticationValues.AuthGetParameters, Photon.Realtime.AuthenticationValues.AuthPostData, Photon.Realtime.AuthenticationValues.AuthType, Photon.Realtime.ParameterCode.ClientAuthenticationData, Photon.Realtime.ParameterCode.ClientAuthenticationParams, Photon.Realtime.ParameterCode.ClientAuthenticationType, Photon.Realtime.ParameterCode.LobbyStats, Photon.Realtime.ParameterCode.Region, Photon.Realtime.ParameterCode.Token, Photon.Realtime.AuthenticationValues.Token, Photon.Realtime.ParameterCode.UserId, Photon.Realtime.AuthenticationValues.UserId.
virtual bool Photon.Realtime.LoadBalancingPeer.OpAuthenticateOnce(string appId, string appVersion, AuthenticationValues authValues, string regionCode, EncryptionMode encryptionMode, ConnectionProtocol expectedProtocol)
Sends this app's appId and appVersion to identify this application server side.
This is an async request which triggers a OnOperationResponse() call. This operation makes use of encryption, if that is established before. See: EstablishEncryption(). Check encryption with IsEncryptionAvailable. This operation is allowed only once per connection (multiple calls will have ErrorCode != Ok). appId Your application's name or ID to authenticate. This is assigned by Photon Cloud (webpage). appVersion The client's version (clients with differing client appVersions are separated and players don't meet). authValues Optional authentication values. The client can set no values or a UserId or some parameters for Custom Authentication by a server. regionCode Optional region code, if the client should connect to a specific Photon Cloud Region. encryptionMode expectedProtocol If the operation could be sent (has to be connected).
References Photon.Realtime.ParameterCode.ApplicationId, Photon.Realtime.ParameterCode.AppVersion, Photon.Realtime.OperationCode.AuthenticateOnce, Photon.Realtime.AuthenticationValues.AuthGetParameters, Photon.Realtime.AuthenticationValues.AuthPostData, Photon.Realtime.AuthenticationValues.AuthType, Photon.Realtime.ParameterCode.ClientAuthenticationData, Photon.Realtime.ParameterCode.ClientAuthenticationParams, Photon.Realtime.ParameterCode.ClientAuthenticationType, Photon.Realtime.ParameterCode.EncryptionMode, Photon.Realtime.ParameterCode.ExpectedProtocol, Photon.Realtime.ParameterCode.Region, Photon.Realtime.ParameterCode.Token, Photon.Realtime.AuthenticationValues.Token, Photon.Realtime.ParameterCode.UserId, Photon.Realtime.AuthenticationValues.UserId.
virtual bool Photon.Realtime.LoadBalancingPeer.OpChangeGroups(byte[] groupsToRemove, byte[] groupsToAdd)
Operation to handle this client's interest groups (for events in room).
Note the difference between passing null and byte[0]: null won't add/remove any groups. byte[0] will add/remove all (existing) groups. First, removing groups is executed. This way, you could leave all groups and join only the ones provided. Changes become active not immediately but when the server executes this operation (approximately RTT/2). groupsToRemove Groups to remove from interest. Null will not remove any. A byte[0] will remove all. groupsToAdd Groups to add to interest. Null will not add any. A byte[0] will add all current. If operation could be enqueued for sending. Sent when calling: Service or SendOutgoingCommands.
References Photon.Realtime.ParameterCode.Add, Photon.Realtime.OperationCode.ChangeGroups, Photon.Realtime.ParameterCode.Remove.
Referenced by Photon.Realtime.LoadBalancingClient.OpChangeGroups.
virtual bool Photon.Realtime.LoadBalancingPeer.OpRaiseEvent(byte eventCode, object customEventContent, RaiseEventOptions raiseEventOptions, SendOptions sendOptions)
Send an event with custom code/type and any content to the other players in the same room.
This override explicitly uses another parameter order to not mix it up with the implementation for Hashtable only. eventCode Identifies this type of event (and the content). Your game's event codes can start with 0. customEventContent Any serializable datatype (including Hashtable like the other OpRaiseEvent overloads). raiseEventOptions Contains (slightly) less often used options. If you pass null, the default options will be used. sendOptions Send options for reliable, encryption etc If operation could be enqueued for sending. Sent when calling: Service or SendOutgoingCommands.
References Photon.Realtime.ParameterCode.ActorList, Photon.Realtime.ParameterCode.Cache, Photon.Realtime.RaiseEventOptions.CachingOption, Photon.Realtime.ParameterCode.Code, Photon.Realtime.ParameterCode.Data, Photon.Realtime.ParameterCode.EventForward, Photon.Realtime.RaiseEventOptions.Flags, Photon.Realtime.ParameterCode.Group, Photon.Realtime.WebFlags.HttpForward, Photon.Realtime.RaiseEventOptions.InterestGroup, Photon.Realtime.OperationCode.RaiseEvent, Photon.Realtime.ParameterCode.ReceiverGroup, Photon.Realtime.RaiseEventOptions.Receivers, Photon.Realtime.RaiseEventOptions.TargetActors, Photon.Realtime.WebFlags.WebhookFlags.
Referenced by Photon.Realtime.LoadBalancingClient.OpRaiseEvent, Photon.Pun.Simple.Internal.NetMsgSends.Send.
virtual bool Photon.Realtime.LoadBalancingPeer.OpSettings(bool receiveLobbyStats)
Internally used operation to set some "per server" settings.
This is for the Master Server. receiveLobbyStats Set to true, to get Lobby Statistics (lists of existing lobbies). False if the operation could not be sent.
References Photon.Realtime.OperationCode.ServerSettings.
Referenced by Photon.Realtime.LoadBalancingClient.OnOperationResponse.
void Photon.Realtime.LoadBalancingPeer.ConfigUnitySockets()
void Photon.Realtime.LoadBalancingPeer.RoomOptionsToOpParameters(Dictionary< byte, object > op, RoomOptions roomOptions, bool usePropertiesKey=false)
Used by OpJoinRoom and by OpCreateRoom alike.
bool Photon.Realtime.LoadBalancingPeer.OpSetPropertiesOfActor(int actorNr, Hashtable actorProperties, Hashtable expectedProperties=null, WebFlags webflags=null)
Sets properties of a player / actor.
Internally this uses OpSetProperties, which can be used to either set room or player properties. actorNr The payer ID (a.k.a. actorNumber) of the player to attach these properties to. actorProperties The properties to add or update. expectedProperties If set, these must be in the current properties-set (on the server) to set actorProperties: CAS. webflags Set these to forward the properties to a WebHook as defined for this app (in Dashboard). If the operation could be sent (requires connection).
bool Photon.Realtime.LoadBalancingPeer.OpSetPropertiesOfRoom(Hashtable gameProperties, Hashtable expectedProperties=null, WebFlags webflags=null)
Sets properties of a room.
Internally this uses OpSetProperties, which can be used to either set room or player properties. gameProperties The properties to add or update. expectedProperties The properties expected when update occurs. (CAS : "Check And Swap") webflags WebFlag to indicate if request should be forwarded as "PathProperties" webhook or not. If the operation could be sent (has to be connected).
bool Photon.Realtime.LoadBalancingPeer.OpSetPropertyOfRoom(byte propCode, object value)