Photon::Pun::Simple::OnStateChangeKinematic
int Photon.Pun.Simple.OnStateChangeKinematic.ApplyOrder
bool Photon.Pun.Simple.OnStateChangeKinematic.AutoKinematicEnabled
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onDespawned
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onAnchored
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onMounted
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onTransit
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onDropped
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
KinematicSetting Photon.Pun.Simple.OnStateChangeKinematic.onVisible
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
bool Photon.Pun.Simple.OnStateChangeKinematic.autoDestroy
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.OnAwake.
ObjState Photon.Pun.Simple.OnStateChangeKinematic.currentState
Rigidbody Photon.Pun.Simple.OnStateChangeKinematic.rb
Rigidbody2D Photon.Pun.Simple.OnStateChangeKinematic.rb2d
bool Photon.Pun.Simple.OnStateChangeKinematic.kinematicDefault
int Photon.Pun.Simple.OnStateChangeKinematic.interpolateDefault
override void Photon.Pun.Simple.OnStateChangeKinematic.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
References Photon.Pun.Simple.OnStateChangeKinematic.autoDestroy, Photon.Pun.Simple.NetComponent.netObj, Photon.Pun.Simple.NetObject.Rb, Photon.Pun.Simple.NetObject.Rb2D, Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
override void Photon.Pun.Simple.OnStateChangeKinematic.OnAuthorityChanged(bool isMine, bool controllerChanged)
Owner changes can get dicey, this reapplies the state after an owner change.
References Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics, Photon.Pun.Simple.OnStateChangeKinematic.SetUnownedKinematics.
void Photon.Pun.Simple.OnStateChangeKinematic.OnStateChange(ObjState newState, ObjState previousState, Transform attachmentTransform, Mount attachTo=null, bool isReady=true)
References Photon.Pun.Simple.NetComponent.IsMine, Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics.
virtual void Photon.Pun.Simple.OnStateChangeKinematic.SetUnownedKinematics()
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.OnAuthorityChanged.
virtual void Photon.Pun.Simple.OnStateChangeKinematic.SetOwnedKinematics(ObjState state)
References Photon.Pun.Simple.OnStateChangeKinematic.onAnchored, Photon.Pun.Simple.OnStateChangeKinematic.onDespawned, Photon.Pun.Simple.OnStateChangeKinematic.onDropped, Photon.Pun.Simple.OnStateChangeKinematic.onMounted, Photon.Pun.Simple.OnStateChangeKinematic.onTransit, Photon.Pun.Simple.OnStateChangeKinematic.onVisible.
Referenced by Photon.Pun.Simple.OnStateChangeKinematic.OnAuthorityChanged, Photon.Pun.Simple.OnStateChangeKinematic.OnAwake, Photon.Pun.Simple.OnStateChangeKinematic.OnStateChange.