Photon::Pun::Simple::SyncNodeMover
Movement
float Photon.Pun.Simple.SyncNodeMover.predictWithRTT
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot.
List<Node> Photon.Pun.Simple.SyncNodeMover.nodes
Referenced by Photon.Pun.Simple.SyncNodeMover.InitializeTRS.
Movement Photon.Pun.Simple.SyncNodeMover.movement
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.ConstructMissingFrame, Photon.Pun.Simple.SyncNodeMover.InitializeTRS, Photon.Pun.Simple.SyncNodeMover.OnInterpolate, Photon.Pun.Simple.SyncNodeMover.OnNetDeserialize, Photon.Pun.Simple.SyncNodeMover.OnNetSerialize.
float Photon.Pun.Simple.SyncNodeMover.oscillatePeriod
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.ConstructMissingFrame, Photon.Pun.Simple.SyncNodeMover.TimeToPhase.
AnimationCurve Photon.Pun.Simple.SyncNodeMover.oscillateCurve
Referenced by Photon.Pun.Simple.SyncNodeMover.OscillatePhaseToLerpT, Photon.Pun.Simple.SyncNodeMover.Reset.
LiteFloatCrusher Photon.Pun.Simple.SyncNodeMover.floatCrusher
Referenced by Photon.Pun.Simple.SyncNodeMover.OnCaptureCurrentState, Photon.Pun.Simple.SyncNodeMover.OnNetDeserialize, Photon.Pun.Simple.SyncNodeMover.OnNetSerialize.
Node Photon.Pun.Simple.SyncNodeMover.StartNode
Node Photon.Pun.Simple.SyncNodeMover.EndNode
float Photon.Pun.Simple.SyncNodeMover.currentPhase
Referenced by Photon.Pun.Simple.SyncNodeMover.OnCaptureCurrentState.
int Photon.Pun.Simple.SyncNodeMover.queuedTargetNode
Referenced by Photon.Pun.Simple.SyncNodeMover.Trigger.
int Photon.Pun.Simple.SyncNodeMover.targetNode
Referenced by Photon.Pun.Simple.SyncNodeMover.OnCaptureCurrentState, Photon.Pun.Simple.SyncNodeMover.Trigger.
double Photon.Pun.Simple.SyncNodeMover.timeoffset
float Photon.Pun.Simple.SyncNodeMover.snapPhase
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.OnInterpolate.
float Photon.Pun.Simple.SyncNodeMover.targPhase
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.OnInterpolate.
float Photon.Pun.Simple.SyncNodeMover.accumulatedTime
override void Photon.Pun.Simple.SyncNodeMover.Reset()
References Photon.Pun.Simple.SyncNodeMover.oscillateCurve.
override void Photon.Pun.Simple.SyncNodeMover.InitializeTRS(TRSDefinition def, TRS type)
References Photon.Pun.Simple.SyncNodeMover.movement, Photon.Pun.Simple.SyncNodeMover.nodes, Photon.Pun.Simple.SyncNodeMover.TRSDefinition.relation.
override void Photon.Pun.Simple.SyncNodeMover.ApplySnapshot(Frame snapframe, Frame targframe, bool snapIsVaid, bool targIsValid)
References Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncNodeMover.movement, Photon.Pun.Simple.SyncNodeMover.oscillatePeriod, Photon.Pun.Simple.SyncNodeMover.OscillatePhaseToLerpT, Photon.Pun.Simple.SyncNodeMover.Frame.phase, Photon.Pun.Simple.SyncNodeMover.predictWithRTT, Photon.Pun.Simple.NetMaster.RTT, Photon.Pun.Simple.SyncNodeMover.snapPhase, Photon.Pun.Simple.TickEngineSettings.targetBufferInterval, Photon.Pun.Simple.SyncNodeMover.targPhase, Photon.Pun.Simple.SyncNodeMover.TimeToPhase.
override void Photon.Pun.Simple.SyncNodeMover.ConstructMissingFrame(Frame prevFrame, Frame snapframe, Frame targframe)
References Photon.Pun.Simple.FrameBase.content, Photon.Pun.Simple.SyncNodeMover.movement, Photon.Pun.Simple.TickEngineSettings.netTickInterval, Photon.Pun.Simple.SyncNodeMover.oscillatePeriod, Photon.Pun.Simple.SyncNodeMover.Frame.phase, Photon.Pun.Simple.SyncNodeMover.TimeToPhase.
float Photon.Pun.Simple.SyncNodeMover.OscillatePhaseToLerpT(float phase)
Takes a normalized 0-1 value and returns a T value from the OscillateCurve.
phase
References Photon.Pun.Simple.SyncNodeMover.oscillateCurve.
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.OnInterpolate.
float Photon.Pun.Simple.SyncNodeMover.TimeToPhase(double time)
References Photon.Pun.Simple.SyncNodeMover.oscillatePeriod.
Referenced by Photon.Pun.Simple.SyncNodeMover.ApplySnapshot, Photon.Pun.Simple.SyncNodeMover.ConstructMissingFrame.
override void Photon.Pun.Simple.SyncNodeMover.OnPreSimulate(int frameId, int subFrameId)
override void Photon.Pun.Simple.SyncNodeMover.OnPreUpdate()
void Photon.Pun.Simple.SyncNodeMover.Trigger(int targetNode)
References Photon.Pun.Simple.SyncNodeMover.queuedTargetNode, Photon.Pun.Simple.SyncNodeMover.targetNode.
void Photon.Pun.Simple.SyncNodeMover.TriggerMin()
void Photon.Pun.Simple.SyncNodeMover.TriggerMax()
void Photon.Pun.Simple.SyncNodeMover.OnCaptureCurrentState(int frameId)
References Photon.Pun.Simple.SyncNodeMover.currentPhase, Photon.Compression.LiteFloatCrusher.Encode, Photon.Pun.Simple.SyncNodeMover.floatCrusher, Photon.Pun.Simple.SyncNodeMover.targetNode.
SerializationFlags Photon.Pun.Simple.SyncNodeMover.OnNetSerialize(int frameId, byte[] buffer, ref int bitposition, SerializationFlags writeFlags)
References Photon.Pun.Simple.SyncNodeMover.floatCrusher, Photon.Pun.Simple.SyncNodeMover.movement, Photon.Compression.LiteFloatCrusher.WriteValue.
SerializationFlags Photon.Pun.Simple.SyncNodeMover.OnNetDeserialize(int originFrameId, byte[] buffer, ref int bitposition, FrameArrival arrival)
References Photon.Compression.LiteFloatCrusher.Decode, Photon.Pun.Simple.SyncNodeMover.floatCrusher, Photon.Pun.Simple.SyncNodeMover.movement, Photon.Compression.LiteFloatCrusher.ReadCValue.
override bool Photon.Pun.Simple.SyncNodeMover.OnInterpolate(int snapFrameId, int targFrameId, float t)
References Photon.Pun.Simple.SyncNodeMover.movement, Photon.Pun.Simple.SyncNodeMover.OscillatePhaseToLerpT, Photon.Pun.Simple.SyncNodeMover.snapPhase, Photon.Pun.Simple.SyncNodeMover.targPhase.
void Photon.Pun.Simple.SyncNodeMover.OwnerInterpolate()
void Photon.Pun.Simple.SyncNodeMover.TriggerLerp()
void Photon.Pun.Simple.SyncNodeMover.Oscillate(float lerpT)
Movement based on oscilation
void Photon.Pun.Simple.SyncNodeMover.ApplyOscillate(Vector3 pos, Vector3 rot, Vector3 scl)
Apply a value to the indicated TRS axis, leaving the axes and TRS types not indicated as they are.
pos