Photon::Compression::QuatCrusher
bool Photon.Compression.QuatCrusher.QC_ISPRO
Referenced by Photon.Compression.QuatCrusher.QuatCrusher.
int Photon.Compression.QuatCrusher.bits
bool Photon.Compression.QuatCrusher.enabled
QuatCompress.Cache Photon.Compression.QuatCrusher.cache
bool Photon.Compression.QuatCrusher.initialized
int?? Photon.Compression.QuatCrusher.Bits
Referenced by Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.QuatCrusher.Initialize, Photon.Compression.ElementCrusher.TallyBits.
CompressLevel? Photon.Compression.QuatCrusher.CompressLevel
bool Photon.Compression.QuatCrusher.Enabled
Referenced by Photon.Compression.ElementCrusher.CacheValues, Photon.Compression.ElementCrusher.TallyBits.
CompressLevel Photon.Compression.QuatCrusher._compressLevel
Referenced by Photon.Compression.QuatCrusher.CopyFrom, Photon.Compression.QuatCrusher.Equals, Photon.Compression.QuatCrusher.GetHashCode.
Transform Photon.Compression.QuatCrusher.transform
Referenced by Photon.Compression.QuatCrusher.Compress.
bool Photon.Compression.QuatCrusher.local
Referenced by Photon.Compression.QuatCrusher.Compress, Photon.Compression.QuatCrusher.CopyFrom, Photon.Compression.QuatCrusher.Equals, Photon.Compression.QuatCrusher.GetHashCode.
bool Photon.Compression.QuatCrusher.isStandalone
Referenced by Photon.Compression.QuatCrusher.QuatCrusher.
bool Photon.Compression.QuatCrusher.showEnableToggle
Referenced by Photon.Compression.QuatCrusher.QuatCrusher.
Photon.Compression.QuatCrusher.QuatCrusher()
Photon.Compression.QuatCrusher.QuatCrusher(int bits, bool showEnableToggle=false, bool isStandalone=true)
References Photon.Compression.QuatCrusher.isStandalone, Photon.Compression.QuatCrusher.QC_ISPRO, Photon.Compression.QuatCrusher.RoundBitsToBestPreset, Photon.Compression.QuatCrusher.showEnableToggle.
Photon.Compression.QuatCrusher.QuatCrusher(bool showEnableToggle=false, bool isStandalone=true)
References Photon.Compression.QuatCrusher.isStandalone, Photon.Compression.QuatCrusher.QC_ISPRO, Photon.Compression.QuatCrusher.showEnableToggle.
Photon.Compression.QuatCrusher.QuatCrusher(CompressLevel compressLevel, bool showEnableToggle=false, bool isStandalone=true)
References Photon.Compression.QuatCrusher.isStandalone, Photon.Compression.QuatCrusher.showEnableToggle.
void Photon.Compression.QuatCrusher.Initialize()
References Photon.Compression.QuatCrusher.Bits.
Referenced by Photon.Compression.QuatCrusher.Compress, Photon.Compression.QuatCrusher.Decompress.
override void Photon.Compression.QuatCrusher.OnBeforeSerialize()
override void Photon.Compression.QuatCrusher.OnAfterDeserialize()
ulong Photon.Compression.QuatCrusher.Compress()
References Photon.Compression.QuatCrusher.Initialize, Photon.Compression.QuatCrusher.local, Photon.Compression.QuatCrusher.transform.
Referenced by Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.QuatCrusher.Write.
ulong Photon.Compression.QuatCrusher.Compress(Quaternion quat)
References Photon.Compression.QuatCrusher.Initialize.
Quaternion Photon.Compression.QuatCrusher.Decompress(ulong compressed)
References Photon.Compression.QuatCrusher.Initialize.
Referenced by Photon.Compression.CompressedQuat.Decompress, Photon.Compression.ElementCrusher.Decompress, Photon.Compression.QuatCrusher.Read, Photon.Compression.ElementCrusher.Read.
ulong Photon.Compression.QuatCrusher.Write(Quaternion quat, byte[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Compress.
Referenced by Photon.Compression.ElementCrusher.Write.
ulong Photon.Compression.QuatCrusher.Write(Quaternion quat, uint[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Compress.
ulong Photon.Compression.QuatCrusher.Write(Quaternion quat, ulong[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Compress.
ulong Photon.Compression.QuatCrusher.Write(ulong c, byte[] buffer, ref int bitposition)
ulong Photon.Compression.QuatCrusher.Write(ulong c, uint[] buffer, ref int bitposition)
ulong Photon.Compression.QuatCrusher.Write(ulong c, ulong[] buffer, ref int bitposition)
Quaternion Photon.Compression.QuatCrusher.Read(byte[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Decompress.
Quaternion Photon.Compression.QuatCrusher.Read(uint[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Decompress.
Quaternion Photon.Compression.QuatCrusher.Read(ulong[] buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Decompress.
ulong Photon.Compression.QuatCrusher.Write(Quaternion quat, ref ulong buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Compress.
Quaternion Photon.Compression.QuatCrusher.Read(ref ulong buffer, ref int bitposition)
References Photon.Compression.QuatCrusher.Decompress.
void Photon.Compression.QuatCrusher.CopyFrom(QuatCrusher source)
References Photon.Compression.QuatCrusher._compressLevel, Photon.Compression.QuatCrusher.local.
Referenced by Photon.Compression.ElementCrusher.CopyFrom.
override bool Photon.Compression.QuatCrusher.Equals(object obj)
References Photon.Compression.QuatCrusher.Equals.
Referenced by Photon.Compression.ElementCrusher.Equals, Photon.Compression.QuatCrusher.Equals.
bool Photon.Compression.QuatCrusher.Equals(QuatCrusher other)
References Photon.Compression.QuatCrusher._compressLevel, Photon.Compression.QuatCrusher.local.
override int Photon.Compression.QuatCrusher.GetHashCode()
References Photon.Compression.QuatCrusher._compressLevel, Photon.Compression.QuatCrusher.local.
static int Photon.Compression.QuatCrusher.RoundBitsToBestPreset(int bits)
Referenced by Photon.Compression.QuatCrusher.QuatCrusher.
static bool Photon.Compression.QuatCrusher.operator==(QuatCrusher crusher1, QuatCrusher crusher2)
static bool Photon.Compression.QuatCrusher.operator!=(QuatCrusher crusher1, QuatCrusher crusher2)