Photon::Pun::Simple::Mount
const string Photon.Pun.Simple.Mount.ROOT_MOUNT_NAME
MountSelector Photon.Pun.Simple.Mount.mountType
int Photon.Pun.Simple.Mount.componentIndex
List<IMountable> Photon.Pun.Simple.Mount.mountedObjs
Referenced by Photon.Pun.Simple.Mount.ChangeMounting, Photon.Pun.Simple.Mount.DismountAll, Photon.Pun.Simple.MountThrow.OnPreSimulate.
MountsManager Photon.Pun.Simple.Mount.mountsLookup
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.Mount.OnAwake, Photon.Pun.Simple.MountThrow.OnPreSimulate.
override void Photon.Pun.Simple.Mount.OnAwake()
Be sure to use base.OnAwake() when overriding.
This is called when the NetObject runs Awake(). All code that depends on the NetObj being initialized should use this rather than Awake();
References Photon.Pun.Simple.Mount.mountsLookup, Photon.Pun.Simple.NetComponent.netObj.
void Photon.Pun.Simple.Mount.OnPreQuit()
References Photon.Pun.Simple.Mount.DismountAll.
void Photon.Pun.Simple.Mount.OnPreNetDestroy(NetObject rootNetObj)
References Photon.Pun.Simple.Mount.DismountAll, Photon.Pun.Simple.NetComponent.netObj.
void Photon.Pun.Simple.Mount.DismountAll()
References Photon.Pun.Simple.Component, Photon.Pun.Simple.Mount.mountedObjs.
Referenced by Photon.Pun.Simple.Mount.OnPreNetDestroy, Photon.Pun.Simple.Mount.OnPreQuit.
static void Photon.Pun.Simple.Mount.ChangeMounting(IMountable mountable, Mount prevMount, Mount newMount)
Removes mountable from the list of objects attached to the current mount, and adds to the list of the new mount.
newMount
References Photon.Pun.Simple.Mount.mountedObjs.
Referenced by Photon.Pun.Simple.SyncState.ChangeState.