Photon::Pun::Simple::MountsManager
Dictionary<int, Mount> Photon.Pun.Simple.MountsManager.mountIdLookup
Referenced by Photon.Pun.Simple.SyncState.ChangeMount, Photon.Pun.Simple.MountsManager.CollectMounts, Photon.Pun.Simple.MountsManager.GetMount, Photon.Pun.Simple.SyncState.GetMount.
List<Mount> Photon.Pun.Simple.MountsManager.indexedMounts
Referenced by Photon.Pun.Simple.MountsManager.CollectMounts, Photon.Pun.Simple.MountsManager.OnAwake, Photon.Pun.Simple.MountsManager.UnmountAll.
int Photon.Pun.Simple.MountsManager.bitsForMountId
Referenced by Photon.Pun.Simple.MountsManager.OnAwake.
void Photon.Pun.Simple.MountsManager.OnAwake()
References Photon.Pun.Simple.MountsManager.bitsForMountId, Photon.Pun.Simple.MountsManager.CollectMounts, Photon.Pun.Simple.MountsManager.indexedMounts.
void Photon.Pun.Simple.MountsManager.OnPreQuit()
References Photon.Pun.Simple.MountsManager.UnmountAll.
List< Mount > Photon.Pun.Simple.MountsManager.CollectMounts(bool force=false)
Adds all child mounts to the lookup collections.
References Photon.Pun.Simple.MountsManager.indexedMounts, Photon.Pun.Simple.MountsManager.mountIdLookup.
Referenced by Photon.Pun.Simple.MountsManager.OnAwake.
Mount Photon.Pun.Simple.MountsManager.GetMount(int mountId)
References Photon.Pun.Simple.MountsManager.mountIdLookup.
Referenced by Photon.Pun.Simple.Inventory< T >.OnStart.
void Photon.Pun.Simple.MountsManager.UnmountAll()
Force all mounted objects to dismount.
References Photon.Pun.Simple.MountsManager.indexedMounts.
Referenced by Photon.Pun.Simple.MountsManager.OnPreQuit.