Photon::Pun::UtilityScripts::CountdownTimer
const string Photon.Pun.UtilityScripts.CountdownTimer.CountdownStartTime
Referenced by Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime, Photon.Pun.UtilityScripts.CountdownTimer.TryGetStartTime.
float Photon.Pun.UtilityScripts.CountdownTimer.Countdown
Text Photon.Pun.UtilityScripts.CountdownTimer.Text
bool Photon.Pun.UtilityScripts.CountdownTimer.isTimerRunning
int Photon.Pun.UtilityScripts.CountdownTimer.startTime
CountdownTimerHasExpired Photon.Pun.UtilityScripts.CountdownTimer.OnCountdownTimerHasExpired
Called when the timer has expired.
Referenced by Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnDisable, Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnEnable.
delegate void Photon.Pun.UtilityScripts.CountdownTimer.CountdownTimerHasExpired()
OnCountdownTimerHasExpired delegate.
void Photon.Pun.UtilityScripts.CountdownTimer.Start()
override void Photon.Pun.UtilityScripts.CountdownTimer.OnEnable()
override void Photon.Pun.UtilityScripts.CountdownTimer.OnDisable()
void Photon.Pun.UtilityScripts.CountdownTimer.Update()
override void Photon.Pun.UtilityScripts.CountdownTimer.OnRoomPropertiesUpdate(Hashtable propertiesThatChanged)
Called when a room's custom properties changed.
The propertiesThatChanged contains all that was set via Room.SetCustomProperties. Since v1.25 this method has one parameter: Hashtable propertiesThatChanged. Changing properties must be done by Room.SetCustomProperties, which causes this callback locally, too. propertiesThatChanged
void Photon.Pun.UtilityScripts.CountdownTimer.OnTimerRuns()
void Photon.Pun.UtilityScripts.CountdownTimer.OnTimerEnds()
void Photon.Pun.UtilityScripts.CountdownTimer.Initialize()
float Photon.Pun.UtilityScripts.CountdownTimer.TimeRemaining()
static bool Photon.Pun.UtilityScripts.CountdownTimer.TryGetStartTime(out int startTimestamp)
References Photon.Pun.UtilityScripts.CountdownTimer.CountdownStartTime, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.RoomInfo.CustomProperties, Photon.Pun.PhotonNetwork.ServerTimestamp.
Referenced by Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnPlayerPropertiesUpdate, Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime.
static void Photon.Pun.UtilityScripts.CountdownTimer.SetStartTime()
References Photon.Pun.UtilityScripts.CountdownTimer.CountdownStartTime, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.PhotonNetwork.ServerTimestamp, Photon.Realtime.Room.SetCustomProperties, Photon.Pun.UtilityScripts.CountdownTimer.TryGetStartTime.
Referenced by Photon.Pun.Demo.Asteroids.AsteroidsGameManager.OnPlayerPropertiesUpdate.