Photon::Pun::Simple::Vital
VitalDefinition Photon.Pun.Simple.Vital.vitalDef
VitalData Photon.Pun.Simple.Vital.vitalData
VitalDefinition Photon.Pun.Simple.Vital.VitalDef
Referenced by Photon.Pun.Simple.VitalUI.UpdateGraphics.
VitalData Photon.Pun.Simple.Vital.VitalData
Referenced by Photon.Pun.Simple.SyncVitals.OnVitalValueChange, Photon.Pun.Simple.VitalUI.UpdateGraphics.
double Photon.Pun.Simple.Vital.Value
Referenced by Photon.Pun.Simple.Vital.Apply, Photon.Pun.Simple.Vital.ApplyChange, Photon.Pun.Simple.Vital.ApplyCharges, Photon.Pun.Simple.Vital.IsFull, Photon.Pun.Simple.Vital.Simulate.
int Photon.Pun.Simple.Vital.TicksUntilDecay
int Photon.Pun.Simple.Vital.TicksUntilRegen
List<IOnVitalValueChange> Photon.Pun.Simple.Vital.OnValueChangeCallbacks
Referenced by Photon.Pun.Simple.Vital.AddIOnVitalChange, Photon.Pun.Simple.Vital.RemoveIOnVitalChange, Photon.Pun.Simple.Vital.ResetValues.
List<IOnVitalParamChange> Photon.Pun.Simple.Vital.OnParamChangeCallbacks
Referenced by Photon.Pun.Simple.Vital.AddIOnVitalChange, Photon.Pun.Simple.Vital.RemoveIOnVitalChange.
Photon.Pun.Simple.Vital.Vital(VitalDefinition vitalDef)
void Photon.Pun.Simple.Vital.Initialize(float tickDuration)
References Photon.Pun.Simple.VitalDefinition.Initialize, Photon.Pun.Simple.Vital.ResetValues.
Referenced by Photon.Pun.Simple.Vitals.Initialize.
void Photon.Pun.Simple.Vital.ResetValues()
References Photon.Pun.Simple.VitalDefinition.GetDefaultData, Photon.Pun.Simple.Vital.OnValueChangeCallbacks.
Referenced by Photon.Pun.Simple.Vital.Initialize, Photon.Pun.Simple.Vitals.ResetValues.
void Photon.Pun.Simple.Vital.AddIOnVitalChange(IOnVitalChange cb)
References Photon.Pun.Simple.Vital.OnParamChangeCallbacks, Photon.Pun.Simple.Vital.OnValueChangeCallbacks.
Referenced by Photon.Pun.Simple.Vitals.Initialize.
void Photon.Pun.Simple.Vital.RemoveIOnVitalChange(IOnVitalChange cb)
References Photon.Pun.Simple.Vital.OnParamChangeCallbacks, Photon.Pun.Simple.Vital.OnValueChangeCallbacks.
Referenced by Photon.Pun.Simple.VitalUIBase.OnDestroy.
void Photon.Pun.Simple.Vital.Apply(VitalData vdata)
References Photon.Pun.Simple.VitalData.ticksUntilDecay, Photon.Pun.Simple.VitalData.ticksUntilRegen, Photon.Pun.Simple.VitalData.Value, Photon.Pun.Simple.Vital.Value.
double Photon.Pun.Simple.Vital.ApplyCharges(double amt, bool allowOverload, bool ignoreAbsorbtion)
Apply damage to vital, accounting for absorption.
Returns consumed amount.
References Photon.Pun.Simple.VitalDefinition.Absorbtion, Photon.Pun.Simple.VitalDefinition.FullValue, Photon.Pun.Simple.Vital.Value.
bool Photon.Pun.Simple.Vital.IsFull(bool allowOverload)
Is this vital currently at its max (can its value NOT be increased)
allowOverload Whether to check against Max value or Full value
References Photon.Pun.Simple.VitalDefinition.FullValue, Photon.Pun.Simple.VitalDefinition.MaxValue, Photon.Pun.Simple.Vital.Value.
double Photon.Pun.Simple.Vital.ApplyChange(IVitalsContactReactor iVitalsAffector, ContactEvent contectEvent)
Apply a change to this vital, and return how much was consumed.
References Photon.Pun.Simple.Vital.ApplyChange, Photon.Pun.Simple.ContactEvent.contactType, Photon.Pun.Simple.IVitalsContactReactor.DischargeValue.
Referenced by Photon.Pun.Simple.Vital.ApplyChange.
double Photon.Pun.Simple.Vital.ApplyChange(double amount, IVitalsContactReactor reactor=null)
Apply a change to this vital, and return how much was consumed.
References Photon.Pun.Simple.VitalDefinition.FullValue, Photon.Pun.Simple.VitalDefinition.MaxValue, Photon.Pun.Simple.VitalData.Value, Photon.Pun.Simple.Vital.Value.
void Photon.Pun.Simple.Vital.DisruptRegen()
References Photon.Pun.Simple.VitalDefinition.RegenDelayInTicks, Photon.Pun.Simple.VitalData.ticksUntilRegen.
void Photon.Pun.Simple.Vital.DisruptDecay()
References Photon.Pun.Simple.VitalDefinition.DecayDelayInTicks, Photon.Pun.Simple.VitalData.ticksUntilDecay.
double Photon.Pun.Simple.Vital.TestApplyChange(IVitalsContactReactor iVitalsAffector, ContactEvent contactEvent)
References Photon.Pun.Simple.ContactEvent.contactType, Photon.Pun.Simple.IVitalsContactReactor.DischargeValue, Photon.Pun.Simple.Vital.TestApplyChange.
Referenced by Photon.Pun.Simple.Vital.TestApplyChange, Photon.Pun.Simple.SyncVitals.TryTrigger.
double Photon.Pun.Simple.Vital.TestApplyChange(double charge, IVitalsContactReactor iVitalsAffector)
Get the results of ApplyChange without actually applying them.
References Photon.Pun.Simple.IVitalsContactReactor.AllowOverload, Photon.Pun.Simple.VitalDefinition.MaxValue, Photon.Pun.Simple.VitalData.Value.
void Photon.Pun.Simple.Vital.Simulate()
Apply Regeneration and Decay to current state
References Photon.Pun.Simple.VitalDefinition.DecayPerTick, Photon.Pun.Simple.VitalDefinition.FullValue, Photon.Pun.Simple.VitalDefinition.RegenPerTick, Photon.Pun.Simple.VitalData.ticksUntilDecay, Photon.Pun.Simple.VitalData.ticksUntilRegen, Photon.Pun.Simple.VitalData.Value, Photon.Pun.Simple.Vital.Value.