MenuManager_old
MenuManager_old MenuManager_old.Instance
Referenced by Launcher_old.CreateRoom, Launcher_old.joinRoom, Launcher_old.LeaveRoom, Launcher_old.OnCreateRoomFailed, Launcher_old.OnJoinedLobby, Launcher_old.OnJoinedRoom, Launcher_old.OnLeftRoom.
Menu_old [] MenuManager_old.menus
void MenuManager_old.Awake()
void MenuManager_old.OpenMenu(string menuName)
References CloseMenu, Menu_old.Open.
Referenced by Launcher_old.CreateRoom, Launcher_old.joinRoom, Launcher_old.LeaveRoom, Launcher_old.OnCreateRoomFailed, Launcher_old.OnJoinedLobby, Launcher_old.OnJoinedRoom, Launcher_old.OnLeftRoom.
void MenuManager_old.OpenMenu(Menu_old menu)
References CloseMenu, Menu_old.Open.
void MenuManager_old.CloseMenu(Menu_old menu)
References Menu_old.Close.
Referenced by OpenMenu.