Photon::Pun::Simple::ConnectionTickOffsets
int Photon.Pun.Simple.ConnectionTickOffsets.connId
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConnectionTickOffsets, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
int Photon.Pun.Simple.ConnectionTickOffsets.originToLocalFrame
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameOriginToLocal, Photon.Pun.Simple.Internal.TickManager.LogIncomingFrame, Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot.
int Photon.Pun.Simple.ConnectionTickOffsets.localToOriginFrame
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameLocalToOrigin, Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
int Photon.Pun.Simple.ConnectionTickOffsets.numOfSequentialFramesWithTooSmallBuffer
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
int Photon.Pun.Simple.ConnectionTickOffsets.numOfSequentialFramesWithTooLargeBuffer
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
bool Photon.Pun.Simple.ConnectionTickOffsets.frameArrivedTooLate
Referenced by Photon.Pun.Simple.Internal.TickManager.LogIncomingFrame, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
bool Photon.Pun.Simple.ConnectionTickOffsets.hadInitialSnapshot
Referenced by Photon.Pun.Simple.NetObject.OnInterpolate, Photon.Pun.Simple.NetObject.OnSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
int Photon.Pun.Simple.ConnectionTickOffsets.advanceCount
Referenced by Photon.Pun.Simple.NetObject.OnSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
float [] Photon.Pun.Simple.ConnectionTickOffsets.frameArriveTime
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConnectionTickOffsets, Photon.Pun.Simple.Internal.TickManager.LogIncomingFrame.
float [] Photon.Pun.Simple.ConnectionTickOffsets.frameTimeBeforeConsumption
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConnectionTickOffsets.
FastBitMask128 Photon.Pun.Simple.ConnectionTickOffsets.validFrameMask
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.ConnectionTickOffsets, Photon.Pun.Simple.Internal.TickManager.LogIncomingFrame, Photon.Pun.Simple.NetObject.OnInterpolate, Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
int Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameLocalToOrigin(int localFrameId)
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.ConnectionTickOffsets.localToOriginFrame.
Referenced by Photon.Pun.Simple.Internal.TickManager.LogIncomingFrame, Photon.Pun.Simple.NetObject.OnInterpolate, Photon.Pun.Simple.NetObject.OnSnapshot.
int Photon.Pun.Simple.ConnectionTickOffsets.ConvertFrameOriginToLocal(int originFrameId)
References Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.ConnectionTickOffsets.originToLocalFrame.
Photon.Pun.Simple.ConnectionTickOffsets.ConnectionTickOffsets(int connId, int originToLocal, int localToOrigin)
References Photon.Pun.Simple.ConnectionTickOffsets.connId, Photon.Pun.Simple.ConnectionTickOffsets.frameArriveTime, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.ConnectionTickOffsets.frameTimeBeforeConsumption, Photon.Pun.Simple.ConnectionTickOffsets.validFrameMask.
void Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance()
Checks the state of the buffer, and returns the number of snapshots to advance to keep the buffer happy.
References Photon.Pun.Simple.ConnectionTickOffsets.advanceCount, Photon.Pun.Simple.ConnectionTickOffsets.connId, Photon.Utilities.FastBitMask128.CountValidRange, Photon.Pun.Simple.NetMaster.CurrentFrameId, Photon.Pun.Simple.ConnectionTickOffsets.frameArrivedTooLate, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.ConnectionTickOffsets.hadInitialSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.localToOriginFrame, Photon.Pun.Simple.TickEngineSettings.maxBufferSize, Photon.Pun.Simple.TickEngineSettings.minBufferSize, Photon.Pun.Simple.ConnectionTickOffsets.numOfSequentialFramesWithTooLargeBuffer, Photon.Pun.Simple.ConnectionTickOffsets.numOfSequentialFramesWithTooSmallBuffer, Photon.Pun.Simple.TickEngineSettings.quaterFrameCount, Photon.Pun.Simple.TickEngineSettings.targetBufferSize, Photon.Pun.Simple.TickEngineSettings.ticksBeforeGrow, Photon.Pun.Simple.ConnectionTickOffsets.validFrameMask.
void Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot()
References Photon.Pun.Simple.ConnectionTickOffsets.advanceCount, Photon.Utilities.FastBitMask128.ClearBitsBefore, Photon.Pun.Simple.NetMaster.CurrentFrameId, Photon.Pun.Simple.TickEngineSettings.frameCount, Photon.Pun.Simple.ConnectionTickOffsets.hadInitialSnapshot, Photon.Pun.Simple.ConnectionTickOffsets.localToOriginFrame, Photon.Pun.Simple.ConnectionTickOffsets.originToLocalFrame, Photon.Pun.Simple.TickEngineSettings.quaterFrameCount, Photon.Pun.Simple.ConnectionTickOffsets.validFrameMask.