Photon::Pun::PhotonHandler
PhotonHandler Photon.Pun.PhotonHandler.instance
const int Photon.Pun.PhotonHandler.SerializeRateFrameCorrection
This corrects the "next time to serialize the state" value by some ms.
As LateUpdate typically gets called every 15ms it's better to be early(er) than late to achieve a SerializeRate.
PhotonHandler Photon.Pun.PhotonHandler.Instance
int Photon.Pun.PhotonHandler.MaxDatagrams
Limits the number of datagrams that are created in each LateUpdate.
Helps spreading out sending of messages minimally.
Referenced by Photon.Pun.PhotonHandler.LateUpdate.
bool Photon.Pun.PhotonHandler.SendAsap
Signals that outgoing messages should be sent in the next LateUpdate call.
Up to MaxDatagrams are created to send queued messages.
Referenced by Photon.Pun.PhotonHandler.LateUpdate.
int Photon.Pun.PhotonHandler.UpdateInterval
int Photon.Pun.PhotonHandler.UpdateIntervalOnSerialize
int Photon.Pun.PhotonHandler.nextSendTickCount
int Photon.Pun.PhotonHandler.nextSendTickCountOnSerialize
SupportLogger Photon.Pun.PhotonHandler.supportLoggerComponent
List<int> Photon.Pun.PhotonHandler.reusableIntList
Referenced by Photon.Pun.PhotonHandler.OnJoinedRoom, Photon.Pun.PhotonHandler.OnPlayerEnteredRoom.
override void Photon.Pun.PhotonHandler.Awake()
References Photon.Pun.PhotonHandler.Awake.
Referenced by Photon.Pun.PhotonHandler.Awake.
virtual void Photon.Pun.PhotonHandler.OnEnable()
References Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Realtime.ConnectionHandler.Client, Photon.Realtime.SupportLogger.Client, Photon.Pun.ServerSettings.EnableSupportLogger, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonNetwork.PhotonServerSettings, Photon.Pun.PhotonNetwork.SendRate, Photon.Pun.PhotonNetwork.SerializationRate, Photon.Realtime.ConnectionHandler.StartFallbackSendAckThread.
void Photon.Pun.PhotonHandler.Start()
override void Photon.Pun.PhotonHandler.OnDisable()
References Photon.Pun.PhotonNetwork.RemoveCallbackTarget.
void Photon.Pun.PhotonHandler.FixedUpdate()
Called in intervals by UnityEngine. Affected by Time.timeScale.
References Photon.Pun.PhotonHandler.Dispatch, Photon.Pun.PhotonNetwork.MinimalTimeScaleToDispatchInFixedUpdate.
void Photon.Pun.PhotonHandler.LateUpdate()
Called in intervals by UnityEngine, after running the normal game code and physics.
References Photon.Pun.PhotonHandler.Dispatch, Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonHandler.MaxDatagrams, Photon.Pun.PhotonNetwork.MinimalTimeScaleToDispatchInFixedUpdate, Photon.Pun.PhotonNetwork.NetworkingClient, Photon.Pun.PhotonHandler.SendAsap.
void Photon.Pun.PhotonHandler.Dispatch()
Dispatches incoming network messages for PUN.
Called in FixedUpdate or LateUpdate. It may make sense to dispatch incoming messages, even if the timeScale is near 0. That can be configured with PhotonNetwork.MinimalTimeScaleToDispatchInFixedUpdate. Without dispatching messages, PUN won't change state and does not handle updates.
References Photon.Pun.PhotonNetwork.IsMessageQueueRunning, Photon.Realtime.LoadBalancingClient.LoadBalancingPeer, Photon.Pun.PhotonNetwork.NetworkingClient.
Referenced by Photon.Pun.PhotonHandler.FixedUpdate, Photon.Pun.PhotonHandler.LateUpdate.
void Photon.Pun.PhotonHandler.OnCreatedRoom()
Called when this client created a room and entered it.
OnJoinedRoom() will be called as well. This callback is only called on the client which created a room (see OpCreateRoom). As any client might close (or drop connection) anytime, there is a chance that the creator of a room does not execute OnCreatedRoom. If you need specific room properties or a "start signal", implement OnMasterClientSwitched() and make each new MasterClient check the room's state.
References Photon.Pun.SceneManagerHelper.ActiveSceneName.
void Photon.Pun.PhotonHandler.OnRoomPropertiesUpdate(Hashtable propertiesThatChanged)
Called when a room's custom properties changed.
The propertiesThatChanged contains all that was set via Room.SetCustomProperties. Since v1.25 this method has one parameter: Hashtable propertiesThatChanged. Changing properties must be done by Room.SetCustomProperties, which causes this callback locally, too. propertiesThatChanged
void Photon.Pun.PhotonHandler.OnPlayerPropertiesUpdate(Player targetPlayer, Hashtable changedProps)
Called when custom player-properties are changed.
Player and the changed properties are passed as object[]. Changing properties must be done by Player.SetCustomProperties, which causes this callback locally, too. targetPlayer Contains Player that changed. changedProps Contains the properties that changed.
void Photon.Pun.PhotonHandler.OnMasterClientSwitched(Player newMasterClient)
Called after switching to a new MasterClient when the current one leaves.
This is not called when this client enters a room. The former MasterClient is still in the player list when this method get called.
References Photon.Pun.PhotonNetwork.PhotonViewCollection.
void Photon.Pun.PhotonHandler.OnFriendListUpdate(System.Collections.Generic.List< FriendInfo > friendList)
void Photon.Pun.PhotonHandler.OnCreateRoomFailed(short returnCode, string message)
Called when the server couldn't create a room (OpCreateRoom failed).
Creating a room may fail for various reasons. Most often, the room already exists (roomname in use) or the RoomOptions clash and it's impossible to create the room. When creating a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.PhotonHandler.OnJoinRoomFailed(short returnCode, string message)
Called when a previous OpJoinRoom call failed on the server.
Joining a room may fail for various reasons. Most often, the room is full or does not exist anymore (due to someone else being faster or closing the room). When joining a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback. This way, the client is ready to find/create a room at the moment of the callback. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected. Treat callbacks of OnConnected as pure information that the client could connect. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.PhotonHandler.OnJoinRandomFailed(short returnCode, string message)
Called when a previous OpJoinRandom call failed on the server.
The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room). This operation is only ever sent to the Master Server. Once a room is found by the Master Server, the client will head off to the designated Game Server and use the operation Join on the Game Server. When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms. returnCode Operation ReturnCode from the server. message Debug message for the error.
void Photon.Pun.PhotonHandler.OnJoinedRoom()
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined.
When this is called, you can access the existing players in Room.Players, their custom properties and Room.CustomProperties. In this callback, you could create player objects. For example in Unity, instantiate a prefab for the player. If you want a match to be started "actively", enable the user to signal "ready" (using OpRaiseEvent or a Custom Property).
References Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.PhotonViewCollection, Photon.Realtime.Room.PlayerCount, Photon.Pun.PhotonHandler.reusableIntList, Photon.Pun.PhotonNetwork.ViewCount.
void Photon.Pun.PhotonHandler.OnLeftRoom()
Called when the local user/client left a room, so the game's logic can clean up it's internal state.
When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server. This wraps up multiple internal actions. Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms.
void Photon.Pun.PhotonHandler.OnPlayerEnteredRoom(Player newPlayer)
Called when a remote player entered the room.
This Player is already added to the playerlist. If your game starts with a certain number of players, this callback can be useful to check the Room.playerCount and find out if you can start.
References Photon.Pun.PhotonNetwork.IsMasterClient, Photon.Pun.PhotonNetwork.PhotonViewCollection, Photon.Pun.PhotonHandler.reusableIntList.
void Photon.Pun.PhotonHandler.OnPlayerLeftRoom(Player otherPlayer)
Called when a remote player left the room or became inactive.
Check otherPlayer.IsInactive. If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic. Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room. In such cases, the Player stays in the Room.Players dictionary. If the player is not just inactive, it gets removed from the Room.Players dictionary, before the callback is called.
References Photon.Realtime.Player.ActorNumber, Photon.Realtime.Room.AutoCleanUp, Photon.Pun.PhotonNetwork.CurrentRoom, Photon.Realtime.Player.IsInactive, Photon.Pun.PhotonNetwork.MasterClient, Photon.Pun.PhotonNetwork.PhotonViewCollection.