Photon::Pun::Demo::Cockpit::FriendListView
FriendListCell Photon.Pun.Demo.Cockpit.FriendListView.CellPrototype
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.SetFriendDetails.
Text Photon.Pun.Demo.Cockpit.FriendListView.ContentFeedback
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.FindFriends, Photon.Pun.Demo.Cockpit.FriendListView.OnEnable, Photon.Pun.Demo.Cockpit.FriendListView.OnFriendListUpdate.
Text Photon.Pun.Demo.Cockpit.FriendListView.UpdateStatusText
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.OnEnable.
OnJoinRoomEvent Photon.Pun.Demo.Cockpit.FriendListView.OnJoinRoom
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.JoinFriendRoom.
Dictionary<string, FriendListCell> Photon.Pun.Demo.Cockpit.FriendListView.FriendCellList
string [] Photon.Pun.Demo.Cockpit.FriendListView.FriendsLUT
void Photon.Pun.Demo.Cockpit.FriendListView.Awake()
IEnumerator Photon.Pun.Demo.Cockpit.FriendListView.UpdateUIPing()
override void Photon.Pun.Demo.Cockpit.FriendListView.OnEnable()
References Photon.Pun.Demo.Cockpit.FriendListView.ContentFeedback, Photon.Pun.Demo.Cockpit.FriendListView.UpdateStatusText.
void Photon.Pun.Demo.Cockpit.FriendListView.SetFriendDetails(FriendDetail[] friendList)
References Photon.Pun.Demo.Cockpit.FriendListView.CellPrototype, Photon.Pun.Demo.Cockpit.FriendListView.FindFriends, Photon.Pun.PhotonNetwork.LocalPlayer, Photon.Pun.Demo.Cockpit.FriendListView.ResetList, Photon.Realtime.Player.UserId, Photon.Pun.Demo.Cockpit.FriendListView.FriendDetail.UserId.
void Photon.Pun.Demo.Cockpit.FriendListView.FindFriends()
References Photon.Pun.Demo.Cockpit.FriendListView.ContentFeedback, Photon.Pun.PhotonNetwork.FindFriends.
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.SetFriendDetails.
override void Photon.Pun.Demo.Cockpit.FriendListView.OnFriendListUpdate(List< FriendInfo > friendList)
Called when the server sent the response to a FindFriends request.
After calling OpFindFriends, the Master Server will cache the friend list and send updates to the friend list. The friends includes the name, userId, online state and the room (if any) for each requested user/friend. Use the friendList to update your UI and store it, if the UI should highlight changes.
References Photon.Pun.Demo.Cockpit.FriendListView.ContentFeedback, Photon.Realtime.FriendInfo.UserId.
void Photon.Pun.Demo.Cockpit.FriendListView.OnRoomListUpdateCallBack(List< RoomInfo > roomList)
References Photon.Pun.PhotonNetwork.FindFriends.
void Photon.Pun.Demo.Cockpit.FriendListView.JoinFriendRoom(string RoomName)
References Photon.Pun.Demo.Cockpit.FriendListView.OnJoinRoom.
Referenced by Photon.Pun.Demo.Cockpit.FriendListCell.JoinFriendRoom.
void Photon.Pun.Demo.Cockpit.FriendListView.ResetList()
Referenced by Photon.Pun.Demo.Cockpit.FriendListView.SetFriendDetails.