Photon::Pun::Simple::IUseKeyframes
bool Photon.Pun.Simple.IUseKeyframes.IsKeyframe(int frameId)
Referenced by Photon.Pun.Simple.SyncVitals.OnNetDeserialize, Photon.Pun.Simple.SyncAnimator.OnNetDeserialize, Photon.Pun.Simple.SyncState.OnNetDeserialize, Photon.Pun.Simple.SyncSpawnTimer.OnNetDeserialize, Photon.Pun.Simple.SyncVitals.OnNetSerialize, Photon.Pun.Simple.SyncAnimator.OnNetSerialize, Photon.Pun.Simple.SyncOwner.OnNetSerialize, Photon.Pun.Simple.SyncSpawnTimer.OnNetSerialize, Photon.Pun.Simple.SyncState.OnNetSerialize, Photon.Pun.Simple.SyncTransform.OnNetSerialize.