Photon::Pun::Simple::IVitalsContactReactor
VitalNameType Photon.Pun.Simple.IVitalsContactReactor.VitalNameType
bool Photon.Pun.Simple.IVitalsContactReactor.AllowOverload
Referenced by Photon.Pun.Simple.Vital.TestApplyChange.
bool Photon.Pun.Simple.IVitalsContactReactor.Propagate
double Photon.Pun.Simple.IVitalsContactReactor.DischargeValue(ContactType contactType=ContactType.Undefined)
Referenced by Photon.Pun.Simple.Vital.ApplyChange, Photon.Pun.Simple.Vital.TestApplyChange, Photon.Pun.Simple.SyncVitals.TestConsumption.