Photon::Pun::IPunOwnershipCallbacks
void Photon.Pun.IPunOwnershipCallbacks.OnOwnershipRequest(PhotonView targetView, Player requestingPlayer)
Called when another player requests ownership of a PhotonView.
Called on all clients, so check if (targetView.IsMine) or (targetView.Owner == PhotonNetwork.LocalPlayer) to determine if a targetView.TransferOwnership(requestingPlayer) response should be given. The parameter viewAndPlayer contains: PhotonView view = viewAndPlayer[0] as PhotonView; Player requestingPlayer = viewAndPlayer[1] as Player; targetView PhotonView for which ownership gets requested. requestingPlayer Player who requests ownership.
Referenced by Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Pun.PhotonNetwork.RemoveCallbackTarget.
void Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransfered(PhotonView targetView, Player previousOwner)
Called when ownership of a PhotonView is transfered to another player.
The parameter viewAndPlayers contains: PhotonView view = viewAndPlayers[0] as PhotonView; Player newOwner = viewAndPlayers[1] as Player; Player oldOwner = viewAndPlayers[2] as Player; void OnOwnershipTransfered(object[] viewAndPlayers) {} // targetView PhotonView for which ownership changed. previousOwner Player who was the previous owner (or null, if none).
Referenced by Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Pun.PhotonNetwork.RemoveCallbackTarget.
void Photon.Pun.IPunOwnershipCallbacks.OnOwnershipTransferFailed(PhotonView targetView, Player senderOfFailedRequest)
Called when an Ownership Request fails for objects with "takeover" setting.
Each request asks to take ownership from a specific controlling player. This can fail if anyone else took over ownership briefly before the request arrived. targetView senderOfFailedRequest
Referenced by Photon.Pun.PhotonNetwork.AddCallbackTarget, Photon.Pun.PhotonNetwork.RemoveCallbackTarget.