Photon::Compression::HalfFloat::Half
ushort Photon.Compression.HalfFloat.Half.value
const int Photon.Compression.HalfFloat.Half.PrecisionDigits
Number of decimal digits of precision.
const int Photon.Compression.HalfFloat.Half.MantissaBits
Number of bits in the mantissa.
const int Photon.Compression.HalfFloat.Half.MaximumDecimalExponent
Maximum decimal exponent.
const int Photon.Compression.HalfFloat.Half.MaximumBinaryExponent
Maximum binary exponent.
const int Photon.Compression.HalfFloat.Half.MinimumDecimalExponent
Minimum decimal exponent.
const int Photon.Compression.HalfFloat.Half.MinimumBinaryExponent
Minimum binary exponent.
const int Photon.Compression.HalfFloat.Half.ExponentRadix
Exponent radix.
const int Photon.Compression.HalfFloat.Half.AdditionRounding
Additional rounding.
readonly Half Photon.Compression.HalfFloat.Half.Epsilon
Smallest value such that 1.0 + epsilon != 1.0
readonly Half Photon.Compression.HalfFloat.Half.MaxValue
Maximum value of the number.
readonly Half Photon.Compression.HalfFloat.Half.MinValue
Minimum value of the number.
readonly Half Photon.Compression.HalfFloat.Half.NaN
Represents not a number (NaN).
Referenced by Photon.Compression.HalfFloat.Half.IsNaN.
readonly Half Photon.Compression.HalfFloat.Half.NegativeInfinity
Represents negative infinity.
Referenced by Photon.Compression.HalfFloat.Half.IsInfinity, Photon.Compression.HalfFloat.Half.IsNegativeInfinity.
readonly Half Photon.Compression.HalfFloat.Half.PositiveInfinity
Represents positive infinity.
Referenced by Photon.Compression.HalfFloat.Half.IsInfinity, Photon.Compression.HalfFloat.Half.IsPositiveInfinity.
ushort Photon.Compression.HalfFloat.Half.RawValue
Gets the raw 16 bit value used to back this half-float.
Referenced by Photon.Compression.HalfFloat.Half.ConvertToFloat.
Photon.Compression.HalfFloat.Half.Half(float value)
Initializes a new instance of the T:SlimMath.Half structure.
value The floating point value that should be stored in 16 bit format.
References Photon.Compression.HalfFloat.HalfUtilities.Pack.
Referenced by Photon.Compression.HalfFloat.Half.CompareTo, Photon.Compression.HalfFloat.Half.ConvertToHalf, Photon.Compression.HalfFloat.Half.operator Half.
override string Photon.Compression.HalfFloat.Half.ToString()
Converts the value of the object to its equivalent string representation.
The string representation of the value of this instance.
Referenced by Photon.Compression.HalfFloat.Half.ToString.
string Photon.Compression.HalfFloat.Half.ToString(string format)
Returns a System.String that represents this instance.
format The format. A System.String that represents this instance.
References Photon.Compression.HalfFloat.Half.ToString.
string Photon.Compression.HalfFloat.Half.ToString(IFormatProvider formatProvider)
Returns a System.String that represents this instance.
formatProvider The format provider. A System.String that represents this instance.
References Photon.Compression.HalfFloat.Half.ToString.
string Photon.Compression.HalfFloat.Half.ToString(string format, IFormatProvider formatProvider)
Returns a System.String that represents this instance.
format The format. formatProvider The format provider. A System.String that represents this instance.
References Photon.Compression.HalfFloat.Half.ToString.
override int Photon.Compression.HalfFloat.Half.GetHashCode()
Returns the hash code for this instance.
A 32-bit signed integer hash code.
int Photon.Compression.HalfFloat.Half.CompareTo(Half value)
Compares this instance to another instance of the same type.
value The other value to compare to this instance. A value that specifies if this instance is greater than, less than, or equal to value .
References Photon.Compression.HalfFloat.Half.IsNaN.
int Photon.Compression.HalfFloat.Half.CompareTo(object value)
Compares this instance to another instance of another type.
value The other value to compare to this instance. A value that specifies if this instance is greater than, less than, or equal to value .
References Photon.Compression.HalfFloat.Half.Half, Photon.Compression.HalfFloat.Half.IsNaN.
bool Photon.Compression.HalfFloat.Half.Equals(Half other)
Returns a value that indicates whether the current instance is equal to the specified object.
other Object to make the comparison with. true if the current instance is equal to the specified object; false otherwise.
override bool Photon.Compression.HalfFloat.Half.Equals(object obj)
Returns a value that indicates whether the current instance is equal to a specified object.
obj Object to make the comparison with. true if the current instance is equal to the specified object; false otherwise.
References Photon.Compression.HalfFloat.Half.Equals.
TypeCode Photon.Compression.HalfFloat.Half.GetTypeCode()
Returns the System.TypeCode for value type.
The type code.
bool IConvertible. Photon.Compression.HalfFloat.Half.ToBoolean(IFormatProvider provider)
byte IConvertible. Photon.Compression.HalfFloat.Half.ToByte(IFormatProvider provider)
char IConvertible. Photon.Compression.HalfFloat.Half.ToChar(IFormatProvider provider)
DateTime IConvertible. Photon.Compression.HalfFloat.Half.ToDateTime(IFormatProvider provider)
decimal IConvertible. Photon.Compression.HalfFloat.Half.ToDecimal(IFormatProvider provider)
double IConvertible. Photon.Compression.HalfFloat.Half.ToDouble(IFormatProvider provider)
short IConvertible. Photon.Compression.HalfFloat.Half.ToInt16(IFormatProvider provider)
int IConvertible. Photon.Compression.HalfFloat.Half.ToInt32(IFormatProvider provider)
long IConvertible. Photon.Compression.HalfFloat.Half.ToInt64(IFormatProvider provider)
sbyte IConvertible. Photon.Compression.HalfFloat.Half.ToSByte(IFormatProvider provider)
float IConvertible. Photon.Compression.HalfFloat.Half.ToSingle(IFormatProvider provider)
object IConvertible. Photon.Compression.HalfFloat.Half.ToType(Type type, IFormatProvider provider)
ushort IConvertible. Photon.Compression.HalfFloat.Half.ToUInt16(IFormatProvider provider)
uint IConvertible. Photon.Compression.HalfFloat.Half.ToUInt32(IFormatProvider provider)
ulong IConvertible. Photon.Compression.HalfFloat.Half.ToUInt64(IFormatProvider provider)
static float[] Photon.Compression.HalfFloat.Half.ConvertToFloat(Half[] values)
Converts an array of half precision values into full precision values.
values The values to be converted. An array of converted values.
References Photon.Compression.HalfFloat.Half.RawValue, Photon.Compression.HalfFloat.HalfUtilities.Unpack.
static Half[] Photon.Compression.HalfFloat.Half.ConvertToHalf(float[] values)
Converts an array of full precision values into half precision values.
values The values to be converted. An array of converted values.
References Photon.Compression.HalfFloat.Half.Half.
static bool Photon.Compression.HalfFloat.Half.IsInfinity(Half half)
Returns a value indicating whether the specified number evaluates to negative or positive infinity.
true if half evaluates to positive or negative infinity; otherwise, false.
References Photon.Compression.HalfFloat.Half.NegativeInfinity, Photon.Compression.HalfFloat.Half.PositiveInfinity.
static bool Photon.Compression.HalfFloat.Half.IsNaN(Half half)
Returns a value indicating whether the specified number evaluates to NaN.
true if half evaluates to NaN; otherwise, false.
References Photon.Compression.HalfFloat.Half.NaN.
Referenced by Photon.Compression.HalfFloat.Half.CompareTo.
static bool Photon.Compression.HalfFloat.Half.IsNegativeInfinity(Half half)
Returns a value indicating whether the specified number evaluates to negative infinity.
true if half evaluates to negative infinity; otherwise, false.
References Photon.Compression.HalfFloat.Half.NegativeInfinity.
static bool Photon.Compression.HalfFloat.Half.IsPositiveInfinity(Half half)
Returns a value indicating whether the specified number evaluates to positive infinity.
true if half evaluates to positive infinity; otherwise, false.
References Photon.Compression.HalfFloat.Half.PositiveInfinity.
static bool Photon.Compression.HalfFloat.Half.operator<(Half left, Half right)
Returns a value that indicates whether a specified value is less than another specified value.
left The first value to compare. right The second value to compare. true if left is less than right ; otherwise, false.
static bool Photon.Compression.HalfFloat.Half.operator>(Half left, Half right)
Returns a value that indicates whether a specified value is greater than another specified value.
left The first value to compare. right The second value to compare. true if left is greater than right ; otherwise, false.
static bool Photon.Compression.HalfFloat.Half.operator<=(Half left, Half right)
Returns a value that indicates whether a specified value is less than or equal to another specified value.
left The first value to compare. right The second value to compare. true if left is less than or equal to right ; otherwise, false.
static bool Photon.Compression.HalfFloat.Half.operator>=(Half left, Half right)
Returns a value that indicates whether a specified value is greater than or equal to another specified value.
left The first value to compare. right The second value to compare. true if left is greater than or equal to right; otherwise, false.
static bool Photon.Compression.HalfFloat.Half.operator==(Half left, Half right)
Tests for equality between two objects.
left The first value to compare. right The second value to compare. true if left has the same value as right ; otherwise, false.
References Photon.Compression.HalfFloat.Half.Equals.
static bool Photon.Compression.HalfFloat.Half.operator!=(Half left, Half right)
Tests for inequality between two objects.
left The first value to compare. right The second value to compare. true if left has a different value than right ; otherwise, false.
References Photon.Compression.HalfFloat.Half.Equals.
static Photon.Compression.HalfFloat.Half.operator Half(float value)
Performs an explicit conversion from T:System.Single to T:SlimMath.Half.
value The value to be converted. The converted value.
References Photon.Compression.HalfFloat.Half.Half.
static implicit Photon.Compression.HalfFloat.Half.operator float(Half value)
Performs an implicit conversion from T:SlimMath.Half to T:System.Single.
value The value to be converted. The converted value.
References Photon.Compression.HalfFloat.HalfUtilities.Unpack.
static bool Photon.Compression.HalfFloat.Half.Equals(ref Half value1, ref Half value2)
Determines whether the specified object instances are considered equal.
value1 value2 true if value1 is the same instance as value2 or if both are null references or if value1.Equals(value2) returns true; otherwise, false.
Referenced by Photon.Compression.HalfFloat.Half.Equals, Photon.Compression.HalfFloat.Half.operator!=, Photon.Compression.HalfFloat.Half.operator==.