Photon::Compression::Element
VectorType
VectorType Photon.Compression.Element.vectorType
Referenced by Photon.Compression.Element.Element, Photon.Compression.Element.Equals, Photon.Compression.Element.operator Quaternion, Photon.Compression.Element.operator Vector3, Photon.Compression.Element.operator==, Photon.Compression.Element.Slerp, Photon.Compression.Element.SlerpUnclamped, Photon.Compression.Element.ToString, Photon.Compression.Matrix.ToString.
Vector3 Photon.Compression.Element.v
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.Element.Element, Photon.Compression.Element.Equals, Photon.Compression.ElementCrusher.Move, Photon.Compression.Element.operator Element, Photon.Compression.CompressedElement.operator Quaternion, Photon.Compression.Element.operator Quaternion, Photon.Compression.CompressedElement.operator Vector3, Photon.Compression.Element.operator Vector3, Photon.Compression.Element.operator==, Photon.Compression.ElementCrusher.Set, Photon.Compression.Element.ToString.
Quaternion Photon.Compression.Element.quat
Referenced by Photon.Compression.ElementCrusher.Apply, Photon.Compression.ElementCrusher.Compress, Photon.Compression.ElementCrusher.CompressAndWrite, Photon.Compression.Element.Element, Photon.Compression.Element.Equals, Photon.Compression.ElementCrusher.Move, Photon.Compression.CompressedElement.operator Quaternion, Photon.Compression.Element.operator Quaternion, Photon.Compression.CompressedElement.operator Vector3, Photon.Compression.Element.operator Vector3, Photon.Compression.Element.operator==, Photon.Compression.ElementCrusher.Set, Photon.Compression.Element.ToString.
Photon.Compression.Element.Element(Vector3 v)
References Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
Referenced by Photon.Compression.Element.operator Element.
Photon.Compression.Element.Element(Quaternion quat)
References Photon.Compression.Element.quat, Photon.Compression.Element.vectorType.
override bool Photon.Compression.Element.Equals(object obj)
References Photon.Compression.Element.Equals.
Referenced by Photon.Compression.Element.Equals.
bool Photon.Compression.Element.Equals(Element other)
References Photon.Compression.Element.quat, Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
override string Photon.Compression.Element.ToString()
References Photon.Compression.Element.quat, Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
override int Photon.Compression.Element.GetHashCode()
static Photon.Compression.Element.operator Quaternion(Element e)
References Photon.Compression.Element.quat, Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
static Photon.Compression.Element.operator Vector3(Element e)
References Photon.Compression.Element.quat, Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
static Element Photon.Compression.Element.Slerp(Element a, Element b, float t)
References Photon.Compression.Element.Slerp, Photon.Compression.Element.vectorType.
Referenced by Photon.Compression.Matrix.Lerp, Photon.Compression.Element.Slerp.
static Element Photon.Compression.Element.SlerpUnclamped(Element a, Element b, float t)
References Photon.Compression.Element.SlerpUnclamped, Photon.Compression.Element.vectorType.
Referenced by Photon.Compression.Matrix.CatmullRomLerpUnclamped, Photon.Compression.Matrix.LerpUnclamped, Photon.Compression.Element.SlerpUnclamped.
static bool Photon.Compression.Element.operator==(Element a, Element b)
References Photon.Compression.Element.quat, Photon.Compression.Element.v, Photon.Compression.Element.vectorType.
static bool Photon.Compression.Element.operator!=(Element a, Element b)
static bool Photon.Compression.Element.Equals(Vector3 a, Vector3 b)
static bool Photon.Compression.Element.Equals(Quaternion a, Quaternion b)
static implicit Photon.Compression.Element.operator Element(Quaternion q)
References Photon.Compression.Element.Element.
static implicit Photon.Compression.Element.operator Element(Vector3 v)
References Photon.Compression.Element.Element, Photon.Compression.Element.v.