Photon::Utilities::FastBitMask128
ulong Photon.Utilities.FastBitMask128.seg1
ulong Photon.Utilities.FastBitMask128.seg2
int Photon.Utilities.FastBitMask128.bitcount
int Photon.Utilities.FastBitMask128.seg1bitcount
int Photon.Utilities.FastBitMask128.seg2bitcount
ulong Photon.Utilities.FastBitMask128.alltrue1
ulong Photon.Utilities.FastBitMask128.alltrue2
ulong Photon.Utilities.FastBitMask128.Seg1
ulong Photon.Utilities.FastBitMask128.Seg2
ulong Photon.Utilities.FastBitMask128.AllTrue1
ulong Photon.Utilities.FastBitMask128.AllTrue2
int????? Photon.Utilities.FastBitMask128.BitCount
Changing the bitcount with this property recalculates the masks, and sets any unused bits in the backing fields to 0;
bool Photon.Utilities.FastBitMask128.this[int bit]
bool Photon.Utilities.FastBitMask128.AllAreFalse
All of the backing ulongs == 0
bool Photon.Utilities.FastBitMask128.AllAreTrue
Referenced by Photon.Pun.Simple.NetObject.OnPackObjReadyChange, Photon.Pun.Simple.NetObject.OnSyncObjReadyChange.
Photon.Utilities.FastBitMask128.FastBitMask128(int bitcount)
Referenced by Photon.Utilities.FastBitMask128.NOT, Photon.Utilities.FastBitMask128.operator!, Photon.Utilities.FastBitMask128.operator&, Photon.Utilities.FastBitMask128.operator^, Photon.Utilities.FastBitMask128.operator|.
Photon.Utilities.FastBitMask128.FastBitMask128(FastBitMask128 copyFrom)
bool Photon.Utilities.FastBitMask128.Get(int bit)
void Photon.Utilities.FastBitMask128.Set(int bit, bool value)
void Photon.Utilities.FastBitMask128.SetTrue(int bit)
void Photon.Utilities.FastBitMask128.SetFalse(int bit)
void Photon.Utilities.FastBitMask128.SetAllTrue()
void Photon.Utilities.FastBitMask128.SetAllFalse()
void Photon.Utilities.FastBitMask128.OR(FastBitMask128 other)
void Photon.Utilities.FastBitMask128.OR(FastBitMask128 other, int otherOffset)
void Photon.Utilities.FastBitMask128.AND(FastBitMask128 other)
void Photon.Utilities.FastBitMask128.XOR(FastBitMask128 other)
FastBitMask128 Photon.Utilities.FastBitMask128.NOT()
Returns a FastMask with all bits flipped.
Unused bits remain as zeros.
References Photon.Utilities.FastBitMask128.FastBitMask128.
int Photon.Utilities.FastBitMask128.CountTrue()
int Photon.Utilities.FastBitMask128.CountFalse()
void Photon.Utilities.FastBitMask128.ClearBitsBefore(int start, int count)
Non-inclusive clearning of X bits working back from start.
Max count of 64. start
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.PostSnapshot.
int Photon.Utilities.FastBitMask128.CountValidRange(int start, int lookahead)
Inclusively get relative distance to most future true bit in the range.
Referenced by Photon.Pun.Simple.ConnectionTickOffsets.SnapshotAdvance.
void Photon.Utilities.FastBitMask128.Copy(FastBitMask128 other)
bool Photon.Utilities.FastBitMask128.Compare(FastBitMask128 other)
static FastBitMask128 Photon.Utilities.FastBitMask128.operator|(FastBitMask128 a, FastBitMask128 b)
References Photon.Utilities.FastBitMask128.FastBitMask128.
static FastBitMask128 Photon.Utilities.FastBitMask128.operator&(FastBitMask128 a, FastBitMask128 b)
References Photon.Utilities.FastBitMask128.FastBitMask128.
static FastBitMask128 Photon.Utilities.FastBitMask128.operator^(FastBitMask128 a, FastBitMask128 b)
References Photon.Utilities.FastBitMask128.FastBitMask128.
static FastBitMask128 Photon.Utilities.FastBitMask128.operator!(FastBitMask128 a)
References Photon.Utilities.FastBitMask128.FastBitMask128.