.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncAnimator/Structs/AnimPassThru.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncAnimator/Structs/AnimPassThru.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPhoton\&.Pun\&.Simple\&.AnimPassThru\fP"
.br
.RI "A generic passthrough used to store Play/Crossfade/SetTrigger calls for deferment "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.PassThruType\fP { \fBPhoton\&.Pun\&.Simple\&.SetTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.ResetTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.Play\fP, \fBPhoton\&.Pun\&.Simple\&.PlayFixed\fP, \fBPhoton\&.Pun\&.Simple\&.CrossFade\fP, \fBPhoton\&.Pun\&.Simple\&.CrossFadeFixed\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
