.TH "Bed" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bed
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBTaskComplete\fP"
.br
.ti -1c
.RI "\fBChores\fP \fBhumanChore\fP"
.br
.ti -1c
.RI "GameObject \fBhumanPlayer\fP"
.br
.ti -1c
.RI "bool \fBtaskPending\fP = true"
.br
.ti -1c
.RI "GameObject \fBshirt1\fP"
.br
.ti -1c
.RI "GameObject \fBbook2\fP"
.br
.ti -1c
.RI "GameObject \fBbook3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBBed\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Bed\&.book2"

.PP
Definition at line \fB12\fP of file \fBBed\&.cs\fP\&.
.SS "GameObject Bed\&.book3"

.PP
Definition at line \fB12\fP of file \fBBed\&.cs\fP\&.
.SS "\fBChores\fP Bed\&.humanChore"

.PP
Definition at line \fB9\fP of file \fBBed\&.cs\fP\&.
.SS "GameObject Bed\&.humanPlayer"

.PP
Definition at line \fB10\fP of file \fBBed\&.cs\fP\&.
.SS "GameObject Bed\&.shirt1"

.PP
Definition at line \fB12\fP of file \fBBed\&.cs\fP\&.
.SS "UnityEvent Bed\&.TaskComplete"

.PP
Definition at line \fB8\fP of file \fBBed\&.cs\fP\&.
.SS "bool Bed\&.taskPending = true"

.PP
Definition at line \fB11\fP of file \fBBed\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
