.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/Compression/Bitpackers/BitCounter.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/Compression/Bitpackers/BitCounter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Compression\&.BitCounter\fP"
.br
.RI "Experimental packers, that counts number of used bits for serialization\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Compression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.PackedBitsSize\fP { \fBPhoton\&.Compression\&.UInt8\fP = 4, \fBPhoton\&.Compression\&.UInt16\fP = 5, \fBPhoton\&.Compression\&.UInt32\fP = 6, \fBPhoton\&.Compression\&.UInt64\fP = 7 }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.PackedBytesSize\fP { \fBPhoton\&.Compression\&.UInt8\fP = 1, \fBPhoton\&.Compression\&.UInt16\fP = 2, \fBPhoton\&.Compression\&.UInt32\fP = 3, \fBPhoton\&.Compression\&.UInt64\fP = 4 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
