.TH "BreakableFurniture" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BreakableFurniture
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSpawnBrokenVersion\fP ()"
.br
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.RI "Called by PUN several times per second, so that your script can write and read synchronization data for the PhotonView\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisBroken\fP"
.br
.ti -1c
.RI "GameObject \fBdestroyedObject\fP"
.br
.ti -1c
.RI "float \fBbreakTime\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBBreakableFurniture\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BreakableFurniture\&.OnPhotonSerializeView (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"

.PP
Called by PUN several times per second, so that your script can write and read synchronization data for the PhotonView\&. This method will be called in scripts that are assigned as Observed component of a PhotonView\&.
.br
 PhotonNetwork\&.SerializationRate affects how often this method is called\&.
.br
 PhotonNetwork\&.SendRate affects how often packages are sent by this client\&.
.br
.PP
Implementing this method, you can customize which data a PhotonView regularly synchronizes\&. Your code defines what is being sent (content) and how your data is used by receiving clients\&.
.PP
Unlike other callbacks, \fIOnPhotonSerializeView only gets called when it is assigned to a PhotonView\fP as PhotonView\&.observed script\&.
.PP
To make use of this method, the PhotonStream is essential\&. It will be in 'writing' mode' on the
client that controls a PhotonView (PhotonStream\&.IsWriting == true) and in 'reading mode' on the
remote clients that just receive that the controlling client sends\&.

If you skip writing any value into the stream, PUN will skip the update\&. Used carefully, this can
conserve bandwidth and messages (which have a limit per room/second)\&.

Note that OnPhotonSerializeView is not called on remote clients when the sender does not send
any update\&. This can't be used as 'x-times per second Update()"\&. 
.PP
Implements \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.PP
Definition at line \fB67\fP of file \fBBreakableFurniture\&.cs\fP\&.
.SS "void BreakableFurniture\&.SpawnBrokenVersion ()"

.PP
Definition at line \fB45\fP of file \fBBreakableFurniture\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float BreakableFurniture\&.breakTime"

.PP
Definition at line \fB14\fP of file \fBBreakableFurniture\&.cs\fP\&.
.SS "GameObject BreakableFurniture\&.destroyedObject"

.PP
Definition at line \fB10\fP of file \fBBreakableFurniture\&.cs\fP\&.
.SS "bool BreakableFurniture\&.isBroken"

.PP
Definition at line \fB9\fP of file \fBBreakableFurniture\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
