.TH "ButtonCoolDown" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonCoolDown
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBcoolDownImage\fP"
.br
.ti -1c
.RI "Text \fBcoolDownTimer\fP"
.br
.ti -1c
.RI "bool \fBcooldownStart\fP = false"
.br
.ti -1c
.RI "float \fBcoolDown\fP = 60f"
.br
.ti -1c
.RI "float \fBstartCooldown\fP = 0\&.0f"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBButtonCoolDown\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float ButtonCoolDown\&.coolDown = 60f"

.PP
Definition at line \fB15\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SS "Image ButtonCoolDown\&.coolDownImage"

.PP
Definition at line \fB10\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SS "bool ButtonCoolDown\&.cooldownStart = false"

.PP
Definition at line \fB14\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SS "Text ButtonCoolDown\&.coolDownTimer"

.PP
Definition at line \fB11\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SS "\fBButtonCoolDown\fP ButtonCoolDown\&.instance\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBButtonCoolDown\&.cs\fP\&.
.SS "float ButtonCoolDown\&.startCooldown = 0\&.0f"

.PP
Definition at line \fB16\fP of file \fBButtonCoolDown\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
