.TH "ButtonController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBButtonType\fP \fBbuttonType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBButtonController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonType\fP ButtonController\&.buttonType"

.PP
Definition at line \fB21\fP of file \fBButtonController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
