.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI/ButtonController.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI/ButtonController.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButtonController\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBButtonType\fP { \fBStartGame\fP, \fBOptions\fP, \fBCredit\fP, \fBGameUI\fP, \fBMainMenu\fP, \fBNo\fP, \fBPopUp\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBButtonType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIStartGame \fP\fP
.TP
\fB\fIOptions \fP\fP
.TP
\fB\fICredit \fP\fP
.TP
\fB\fIGameUI \fP\fP
.TP
\fB\fIMainMenu \fP\fP
.TP
\fB\fINo \fP\fP
.TP
\fB\fIPopUp \fP\fP
.PP
Definition at line \fB7\fP of file \fBButtonController\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
