.TH "ButtonHoldDown" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonHoldDown
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerDownHandler, and IPointerUpHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBheldDown\fP"
.br
.ti -1c
.RI "float \fBheldDownTime\fP"
.br
.ti -1c
.RI "float \fBrequiredDownTime\fP"
.br
.ti -1c
.RI "UnityEvent \fBonLongClick\fP"
.br
.ti -1c
.RI "Button \fBuseButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonHoldDown\&.OnPointerDown (PointerEventData eventData)"

.PP
Definition at line \fB23\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SS "void ButtonHoldDown\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB28\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ButtonHoldDown\&.heldDown"

.PP
Definition at line \fB10\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SS "float ButtonHoldDown\&.heldDownTime"

.PP
Definition at line \fB12\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SS "UnityEvent ButtonHoldDown\&.onLongClick"

.PP
Definition at line \fB16\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SS "float ButtonHoldDown\&.requiredDownTime"

.PP
Definition at line \fB14\fP of file \fBButtonHoldDown\&.cs\fP\&.
.SS "Button ButtonHoldDown\&.useButton"

.PP
Definition at line \fB18\fP of file \fBButtonHoldDown\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
