.TH "ButtonSpamScript" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonSpamScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClicking\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBclickMeter\fP"
.br
.ti -1c
.RI "bool \fBbarFull\fP"
.br
.ti -1c
.RI "float \fBcurrentAmt\fP"
.br
.ti -1c
.RI "float \fBmaxAmt\fP"
.br
.ti -1c
.RI "float \fBaddAmt\fP"
.br
.ti -1c
.RI "float \fBminusAmt\fP"
.br
.ti -1c
.RI "float \fBamtReduceTimer\fP"
.br
.ti -1c
.RI "float \fBtimeBetweenClicks\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBButtonSpamScript\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonSpamScript\&.Clicking ()"

.PP
Definition at line \fB35\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float ButtonSpamScript\&.addAmt"

.PP
Definition at line \fB15\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "float ButtonSpamScript\&.amtReduceTimer"

.PP
Definition at line \fB17\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "bool ButtonSpamScript\&.barFull"

.PP
Definition at line \fB10\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "Image ButtonSpamScript\&.clickMeter"

.PP
Definition at line \fB9\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "float ButtonSpamScript\&.currentAmt"

.PP
Definition at line \fB13\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "\fBButtonSpamScript\fP ButtonSpamScript\&.instance\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "float ButtonSpamScript\&.maxAmt"

.PP
Definition at line \fB14\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "float ButtonSpamScript\&.minusAmt"

.PP
Definition at line \fB16\fP of file \fBButtonSpamScript\&.cs\fP\&.
.SS "float ButtonSpamScript\&.timeBetweenClicks"

.PP
Definition at line \fB18\fP of file \fBButtonSpamScript\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
