.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/StarterAssets/Editor Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/StarterAssets/Editor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBPackageChecker\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFirstPersonStarterAssetsDeployMenu\&.cs\fP"
.br
.ti -1c
.RI "file \fBScriptingDefineUtils\&.cs\fP"
.br
.ti -1c
.RI "file \fBStarterAssetsDeployMenu\&.cs\fP"
.br
.ti -1c
.RI "file \fBThirdPersonStarterAssetsDeployMenu\&.cs\fP"
.br
.in -1c
