.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fB_GeneratedPackExtensions\fP"
.br
.ti -1c
.RI "directory \fBAttributes\fP"
.br
.ti -1c
.RI "directory \fBCodeGen\fP"
.br
.ti -1c
.RI "directory \fBEnums\fP"
.br
.ti -1c
.RI "directory \fBInterfaces\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPackObjectDatabase\&.cs\fP"
.br
.ti -1c
.RI "file \fBPackObjectSettings\&.cs\fP"
.br
.in -1c
