.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Actions Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Actions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGameplayCounter\&.cs\fP"
.br
.ti -1c
.RI "file \fBParticleSystemEmit\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayAnimation\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlaySound\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetAnimatorTrigger\&.cs\fP"
.br
.ti -1c
.RI "file \fBSetGameObjectActive\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleRotator\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleTransformer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleTranslator\&.cs\fP"
.br
.ti -1c
.RI "file \fBStartPlayableDirector\&.cs\fP"
.br
.ti -1c
.RI "file \fBSwitchMaterial\&.cs\fP"
.br
.ti -1c
.RI "file \fBToggleGameObjectActive\&.cs\fP"
.br
.ti -1c
.RI "file \fBTriggerUnityEvent\&.cs\fP"
.br
.in -1c
