.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/Prototyping Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/Prototyping Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConnectAndJoinRandom\&.cs\fP"
.br
.ti -1c
.RI "file \fBMoveByKeys\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnClickDestroy\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnClickInstantiate\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnClickRpc\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnEscapeQuit\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnJoinedInstantiate\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnStartDelete\&.cs\fP"
.br
.in -1c
