.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/PhotonPlayer Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/PhotonPlayer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEditor\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPhotonTeamsManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerNumbering\&.cs\fP"
.br
.ti -1c
.RI "file \fBPunPlayerScores\&.cs\fP"
.br
.ti -1c
.RI "file \fBPunTeams\&.cs\fP"
.br
.in -1c
