.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/_Shared/_NetcodePhoton/Scripts/~Samples/SimpleFPSOnline/Scripts Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/_Shared/_NetcodePhoton/Scripts/~Samples/SimpleFPSOnline/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGun\&.cs\fP"
.br
.ti -1c
.RI "file \fBGunInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDamageable\&.cs\fP"
.br
.ti -1c
.RI "file \fBItem\&.cs\fP"
.br
.ti -1c
.RI "file \fBItemInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerController\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerGroundCheck\&.cs\fP"
.br
.ti -1c
.RI "file \fBSingleShotGun\&.cs\fP"
.br
.in -1c
