.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/Structs Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/Structs Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCompressedElement\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompressedMatrix\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompressedMatrixRB\&.cs\fP"
.br
.ti -1c
.RI "file \fBCompressedQuat\&.cs\fP"
.br
.ti -1c
.RI "file \fBElement\&.cs\fP"
.br
.ti -1c
.RI "file \fBIncludedAxisEnum\&.cs\fP"
.br
.ti -1c
.RI "file \fBMatrix\&.cs\fP"
.br
.ti -1c
.RI "file \fBMatrixRB\&.cs\fP"
.br
.in -1c
