.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/CodeGen Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/CodeGen Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBHelpers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGenerateTypeExtension\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeCatalogue\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeInfoDict\&.cs\fP"
.br
.in -1c
