.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncShoot Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncShoot Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAssistants\fP"
.br
.ti -1c
.RI "directory \fBInterfaces\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBProjectile\&.cs\fP"
.br
.ti -1c
.RI "file \fBProjectileHelpers\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncCannon\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncContactScan\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncShootBase\&.cs\fP"
.br
.in -1c
