.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAssistants\fP"
.br
.ti -1c
.RI "directory \fBContactSystems\fP"
.br
.ti -1c
.RI "directory \fBDataMonitor\fP"
.br
.ti -1c
.RI "directory \fBEditor\fP"
.br
.ti -1c
.RI "directory \fBEnums\fP"
.br
.ti -1c
.RI "directory \fBMount\fP"
.br
.ti -1c
.RI "directory \fBSyncAnimator\fP"
.br
.ti -1c
.RI "directory \fBSyncMover\fP"
.br
.ti -1c
.RI "directory \fBSyncOculus\fP"
.br
.ti -1c
.RI "directory \fBSyncState\fP"
.br
.ti -1c
.RI "directory \fBSyncTransform\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoOwnerComponentEnable\&.cs\fP"
.br
.ti -1c
.RI "file \fBAutoOwnerGameObjEnable\&.cs\fP"
.br
.ti -1c
.RI "file \fBEnableOnNetObjReady\&.cs\fP"
.br
.in -1c
