.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAutonomous UI\fP"
.br
.ti -1c
.RI "directory \fBControllers\fP"
.br
.ti -1c
.RI "directory \fBLists\fP"
.br
.ti -1c
.RI "directory \fBPropertyFields\fP"
.br
.ti -1c
.RI "directory \fBReadOnlyProperties\fP"
.br
.ti -1c
.RI "directory \fBThirdParty\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInfosPanelPlaceholder\&.cs\fP"
.br
.ti -1c
.RI "file \fBScoreHelper\&.cs\fP"
.br
.in -1c
