.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/_Shared/_NetcodePhoton/Scripts/CustomUtilities Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/_Shared/_NetcodePhoton/Scripts/CustomUtilities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBEditor\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDevComments\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetcodeIsMineSetup\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetcodeSpawnRoomObjs\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnAllUnityEventCall\&.cs\fP"
.br
.in -1c
