.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/Attributes Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/Attributes Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPackObjectAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncHalfFloatAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncIntAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncListAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncRangedAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncVarAttribute\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncVarBaseAttribute\&.cs\fP"
.br
.in -1c
