.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Chan Kwok Chun/Scripts Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Chan Kwok Chun/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBScreenQuestPointer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSoundCastDynamics\&.cs\fP"
.br
.ti -1c
.RI "file \fBSoundGeneralDynamics\&.cs\fP"
.br
.ti -1c
.RI "file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP"
.br
.ti -1c
.RI "file \fBSoundObjectImpact\&.cs\fP"
.br
.ti -1c
.RI "file \fBSoundTesterKit\&.cs\fP"
.br
.in -1c
