.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBConstants\fP"
.br
.ti -1c
.RI "directory \fBEnums\fP"
.br
.ti -1c
.RI "directory \fBExtensions\fP"
.br
.ti -1c
.RI "directory \fBGenericHitscan\fP"
.br
.ti -1c
.RI "directory \fBInterfaces\fP"
.br
.ti -1c
.RI "directory \fBNetMaster\fP"
.br
.ti -1c
.RI "directory \fBStructs\fP"
.br
.ti -1c
.RI "directory \fBTickManager\fP"
.br
.ti -1c
.RI "directory \fBUtilities\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNetComponent\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncObjectTFrame\&.cs\fP"
.br
.ti -1c
.RI "file \fBTickEngineSettings\&.cs\fP"
.br
.in -1c
