.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonRealtime/Code Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonRealtime/Code Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBUnity\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAppSettings\&.cs\fP"
.br
.ti -1c
.RI "file \fBConnectionHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBCustomTypesUnity\&.cs\fP"
.br
.ti -1c
.RI "file \fBExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBFriendInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBLoadBalancingClient\&.cs\fP"
.br
.ti -1c
.RI "file \fBLoadbalancingPeer\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotonPing\&.cs\fP"
.br
.ti -1c
.RI "file \fBPhotonPingClasses\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayer\&.cs\fP"
.br
.ti -1c
.RI "file \fBRegion\&.cs\fP"
.br
.ti -1c
.RI "file \fBRegionHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBRoom\&.cs\fP"
.br
.ti -1c
.RI "file \fBRoomInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBSupportLogger\&.cs\fP"
.br
.ti -1c
.RI "file \fBWebRpc\&.cs\fP"
.br
.in -1c
