.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Senders Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Senders Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSendOnBecameInvisible\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnBecameVisible\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnCollisionEnter\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnCollisionExit\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnCollisionStay\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnTriggerEnter\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnTriggerExit\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendOnTriggerStay\&.cs\fP"
.br
.ti -1c
.RI "file \fBTriggerCommand\&.cs\fP"
.br
.in -1c
