.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Editor Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Editor Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommandReceiverEditor\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendGameCommandEditor\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleTransformerEditor\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleTranslatorEditor\&.cs\fP"
.br
.ti -1c
.RI "file \fBTeleporterGizmo\&.cs\fP"
.br
.in -1c
