.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts/ReadOnlyProperties Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts/ReadOnlyProperties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAppVersionProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBBestRegionInPrefsProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCloudRegionProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCountOfPlayersInRoomProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCountOfPlayersOnMasterProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCountOfPlayersProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCountOfRoomsProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomAutoCleanupProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomEmptyRoomTtlProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomExpectedUsersProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomIsOfflineProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomIsOpenProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomIsVisibleProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomMasterClientIdProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomMaxPlayersProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomNameProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomPlayerCountProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomPlayerTtlProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBCurrentRoomPropertiesListedInLobbyProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameVersionProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBIsConnectedAndReadyProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBIsConnectedProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBOfflineModeProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBPingProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBPropertyListenerBase\&.cs\fP"
.br
.ti -1c
.RI "file \fBServerAddressProperty\&.cs\fP"
.br
.ti -1c
.RI "file \fBServerProperty\&.cs\fP"
.br
.in -1c
