.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncVitals Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncVitals Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAssistants\fP"
.br
.ti -1c
.RI "directory \fBEnums\fP"
.br
.ti -1c
.RI "directory \fBInterfaces\fP"
.br
.ti -1c
.RI "directory \fBUI\fP"
.br
.ti -1c
.RI "directory \fBVitalsSystem\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOwnedIVitals\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyncVitals\&.cs\fP"
.br
.ti -1c
.RI "file \fBVitalsContactReactor\&.cs\fP"
.br
.in -1c
