.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/ChuYao/Scripts Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/ChuYao/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBChoresRandomizer\&.cs\fP"
.br
.ti -1c
.RI "file \fBDestroyGameObject\&.cs\fP"
.br
.ti -1c
.RI "file \fBDisplayWinner\&.cs\fP"
.br
.ti -1c
.RI "file \fBFridgeDoor\&.cs\fP"
.br
.ti -1c
.RI "file \fBFrozenChicken\&.cs\fP"
.br
.ti -1c
.RI "file \fBReadyCheck\&.cs\fP"
.br
.ti -1c
.RI "file \fBScoreManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBSweepZone\&.cs\fP"
.br
.ti -1c
.RI "file \fBToy\&.cs\fP"
.br
.ti -1c
.RI "file \fBZoneManager\&.cs\fP"
.br
.in -1c
