.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBActions\fP"
.br
.ti -1c
.RI "directory \fBPlatforms\fP"
.br
.ti -1c
.RI "directory \fBSenders\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCollectable\&.cs\fP"
.br
.ti -1c
.RI "file \fBCollector\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameCommandHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameCommandReceiver\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameCommandType\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnTeleportEvent\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendGameCommand\&.cs\fP"
.br
.ti -1c
.RI "file \fBTeleporter\&.cs\fP"
.br
.in -1c
