.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/Human Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/Human Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFirstPersCon\&.cs\fP"
.br
.ti -1c
.RI "file \fBInteractable\&.cs\fP"
.br
.ti -1c
.RI "file \fBPickableObjects\&.cs\fP"
.br
.ti -1c
.RI "file \fBPickUpObjectSystem\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerInteractCon\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerPickUpController\&.cs\fP"
.br
.in -1c
