.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts/Autonomous UI Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/PunCockpit/Scripts/Autonomous UI Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCurrentRoom\fP"
.br
.ti -1c
.RI "directory \fBGeneric\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoSyncSceneToggle\&.cs\fP"
.br
.ti -1c
.RI "file \fBBackgroundTimeOutField\&.cs\fP"
.br
.ti -1c
.RI "file \fBCrcCheckToggle\&.cs\fP"
.br
.ti -1c
.RI "file \fBDocLinkButton\&.cs\fP"
.br
.ti -1c
.RI "file \fBGameVersionField\&.cs\fP"
.br
.ti -1c
.RI "file \fBLayoutElementMatchSize\&.cs\fP"
.br
.ti -1c
.RI "file \fBNickNameField\&.cs\fP"
.br
.ti -1c
.RI "file \fBOnlineDocButton\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendRateField\&.cs\fP"
.br
.ti -1c
.RI "file \fBSendRateOnSerializeField\&.cs\fP"
.br
.in -1c
