.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncOculus Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncOculus Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAssistants\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAutoDisableOculusObjects\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleOculusAutomation\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleOVRDebug\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleOVRGrabbable\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleOVRGrabber\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimpleOVRInputSync\&.cs\fP"
.br
.in -1c
