.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI Directory Reference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBButtonController\&.cs\fP"
.br
.ti -1c
.RI "file \fBCutsceneLoader\&.cs\fP"
.br
.ti -1c
.RI "file \fBImageScroller\&.cs\fP"
.br
.ti -1c
.RI "file \fBJumpAnim\&.cs\fP"
.br
.ti -1c
.RI "file \fBJumpAnim2\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainMenuScroller\&.cs\fP"
.br
.ti -1c
.RI "file \fBSceneTransition\&.cs\fP"
.br
.ti -1c
.RI "file \fBSingletonManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBUIController\&.cs\fP"
.br
.ti -1c
.RI "file \fBUIManager\&.cs\fP"
.br
.in -1c
