.TH "callbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
callbacks \- Callbacks
.PP
 \- Callback Interfaces\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP"
.br
.RI "Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover: Connection and Regions\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP"
.br
.RI "Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover the Lobby\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP"
.br
.RI "Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover Matchmaking\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IInRoomCallbacks\fP"
.br
.RI "Collection of 'in room' callbacks for the \fBRealtime\fP Api to cover: Players entering or leaving, property updates and Master Client switching\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IOnEventCallback\fP"
.br
.RI "Event callback for the \fBRealtime\fP Api\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IWebRpcCallback\fP"
.br
.RI "Interface for 'WebRpc' callbacks for the \fBRealtime\fP Api\&. "
.ti -1c
.RI "interface \fBPhoton\&.Realtime\&.IErrorInfoCallback\fP"
.br
.RI "Interface for \fBEventCode\&.ErrorInfo\fP event callback for the \fBRealtime\fP Api\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunObservable\fP"
.br
.RI "Defines the OnPhotonSerializeView method to make it easy to implement correctly for observable scripts\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunInstantiateMagicCallback\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP"
.br
.RI "This class provides a \&.photonView and all callbacks/events that PUN can call\&. "
.in -1c
.SH "Detailed Description"
.PP 
Callback Interfaces\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
