.TH "Cat_Lite_Demo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cat_Lite_Demo
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCamRotate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBcamRotateCheck\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCat_Lite_Demo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Cat_Lite_Demo\&.CamRotate ()"

.PP
Definition at line \fB21\fP of file \fBCat_Lite_Demo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Cat_Lite_Demo\&.camRotateCheck"

.PP
Definition at line \fB7\fP of file \fBCat_Lite_Demo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
