.TH "CatBreakFurniture" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CatBreakFurniture
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetOutlineVisibility\fP (bool value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFurnitureButton\fP \fBfurniButt\fP"
.br
.ti -1c
.RI "\fBBreakableFurniture\fP \fBtargetFurniture\fP"
.br
.ti -1c
.RI "\fBBreakableFurniture\fP \fBfurni\fP"
.br
.ti -1c
.RI "\fBButtonHoldDown\fP \fBbuttonTiming\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCatBreakFurniture\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CatBreakFurniture\&.SetOutlineVisibility (bool value)"

.PP
Definition at line \fB35\fP of file \fBCatBreakFurniture\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonHoldDown\fP CatBreakFurniture\&.buttonTiming"

.PP
Definition at line \fB14\fP of file \fBCatBreakFurniture\&.cs\fP\&.
.SS "\fBBreakableFurniture\fP CatBreakFurniture\&.furni"

.PP
Definition at line \fB12\fP of file \fBCatBreakFurniture\&.cs\fP\&.
.SS "\fBFurnitureButton\fP CatBreakFurniture\&.furniButt"

.PP
Definition at line \fB9\fP of file \fBCatBreakFurniture\&.cs\fP\&.
.SS "\fBBreakableFurniture\fP CatBreakFurniture\&.targetFurniture"

.PP
Definition at line \fB12\fP of file \fBCatBreakFurniture\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
