.TH "CatTrappedScript" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CatTrappedScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTrapDestroyself\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtrappingCat\fP"
.br
.ti -1c
.RI "float \fBtrappedTime\fP = 3f"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBCatTrappedScript\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCatTrappedScript\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CatTrappedScript\&.TrapDestroyself ()"

.PP
Definition at line \fB40\fP of file \fBCatTrappedScript\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCatTrappedScript\fP CatTrappedScript\&.instance\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCatTrappedScript\&.cs\fP\&.
.SS "float CatTrappedScript\&.trappedTime = 3f"

.PP
Definition at line \fB9\fP of file \fBCatTrappedScript\&.cs\fP\&.
.SS "bool CatTrappedScript\&.trappingCat"

.PP
Definition at line \fB8\fP of file \fBCatTrappedScript\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
