.TH "CatTaskScript" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CatTaskScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetFood\fP ()"
.br
.ti -1c
.RI "void \fBDeliverFood\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBfoodButt\fP"
.br
.ti -1c
.RI "\fBButtonHoldDown\fP \fBbuttonTiming\fP"
.br
.ti -1c
.RI "GameObject \fBdeliveryArea\fP"
.br
.ti -1c
.RI "\fBCatTaskDelivery\fP \fBcatTask\fP"
.br
.ti -1c
.RI "UnityEvent \fBTaskComplete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBCatTaskScript\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CatTaskScript\&.DeliverFood ()"

.PP
Definition at line \fB114\fP of file \fBCatTaskScript\&.cs\fP\&.
.SS "void CatTaskScript\&.GetFood ()"

.PP
Definition at line \fB102\fP of file \fBCatTaskScript\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonHoldDown\fP CatTaskScript\&.buttonTiming"

.PP
Definition at line \fB14\fP of file \fBCatTaskScript\&.cs\fP\&.
.SS "\fBCatTaskDelivery\fP CatTaskScript\&.catTask"

.PP
Definition at line \fB20\fP of file \fBCatTaskScript\&.cs\fP\&.
.SS "GameObject CatTaskScript\&.deliveryArea"

.PP
Definition at line \fB19\fP of file \fBCatTaskScript\&.cs\fP\&.
.SS "Button CatTaskScript\&.foodButt"

.PP
Definition at line \fB13\fP of file \fBCatTaskScript\&.cs\fP\&.
.SS "UnityEvent CatTaskScript\&.TaskComplete"

.PP
Definition at line \fB22\fP of file \fBCatTaskScript\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
