.TH "CatTaskDelivery" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CatTaskDelivery
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasFood\fP = false"
.br
.ti -1c
.RI "GameObject \fBdeliveryZone\fP"
.br
.ti -1c
.RI "GameObject \fBarrow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCatTaskDelivery\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject CatTaskDelivery\&.arrow"

.PP
Definition at line \fB12\fP of file \fBCatTaskDelivery\&.cs\fP\&.
.SS "GameObject CatTaskDelivery\&.deliveryZone"

.PP
Definition at line \fB11\fP of file \fBCatTaskDelivery\&.cs\fP\&.
.SS "bool CatTaskDelivery\&.hasFood = false"

.PP
Definition at line \fB9\fP of file \fBCatTaskDelivery\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
