.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatState.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatState.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Chat\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Chat\&.ChatState\fP { \fBPhoton\&.Chat\&.Uninitialized\fP, \fBPhoton\&.Chat\&.ConnectingToNameServer\fP, \fBPhoton\&.Chat\&.ConnectedToNameServer\fP, \fBPhoton\&.Chat\&.Authenticating\fP, \fBPhoton\&.Chat\&.Authenticated\fP, \fBPhoton\&.Chat\&.DisconnectingFromNameServer\fP, \fBPhoton\&.Chat\&.ConnectingToFrontEnd\fP, \fBPhoton\&.Chat\&.ConnectedToFrontEnd\fP, \fBPhoton\&.Chat\&.DisconnectingFromFrontEnd\fP, \fBPhoton\&.Chat\&.QueuedComingFromFrontEnd\fP, \fBPhoton\&.Chat\&.Disconnecting\fP, \fBPhoton\&.Chat\&.Disconnected\fP, \fBPhoton\&.Chat\&.ConnectWithFallbackProtocol\fP }"
.br
.RI "Possible states for a Chat Client\&."
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
