.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatPeer.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatPeer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Chat\&.ChatPeer\fP"
.br
.RI "Provides basic operations of the \fBPhoton\fP \fBChat\fP server\&. "
.ti -1c
.RI "class \fBPhoton\&.Chat\&.AuthenticationValues\fP"
.br
.RI "Container for user authentication in \fBPhoton\fP\&. "
.ti -1c
.RI "class \fBPhoton\&.Chat\&.ParameterCode\fP"
.br
.RI "Class for constants\&. Codes for parameters of Operations and Events\&."
.ti -1c
.RI "class \fBPhoton\&.Chat\&.ErrorCode\fP"
.br
.RI "\fBErrorCode\fP defines the default codes associated with \fBPhoton\fP client/server communication\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Chat\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Chat\&.CustomAuthenticationType\fP : byte { \fBPhoton\&.Chat\&.Custom\fP = 0, \fBPhoton\&.Chat\&.Steam\fP = 1, \fBPhoton\&.Chat\&.Facebook\fP = 2, \fBPhoton\&.Chat\&.Oculus\fP = 3, \fBPhoton\&.Chat\&.PlayStation4\fP = 4, \fBPhoton\&.Chat\&.PlayStation\fP = 4, \fBPhoton\&.Chat\&.Xbox\fP = 5, \fBPhoton\&.Chat\&.Viveport\fP = 10, \fBPhoton\&.Chat\&.NintendoSwitch\fP = 11, \fBPhoton\&.Chat\&.PlayStation5\fP = 12, \fBPhoton\&.Chat\&.Playstation5\fP = 12, \fBPhoton\&.Chat\&.Epic\fP = 13, \fBPhoton\&.Chat\&.FacebookGaming\fP = 15, \fBPhoton\&.Chat\&.None\fP = byte\&.MaxValue }"
.br
.RI "Options for optional 'Custom Authentication' services used with \fBPhoton\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
