.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatDisconnectCause.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonChat/Code/ChatDisconnectCause.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Chat\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Chat\&.ChatDisconnectCause\fP { \fBPhoton\&.Chat\&.None\fP, \fBPhoton\&.Chat\&.ExceptionOnConnect\fP, \fBPhoton\&.Chat\&.DisconnectByServerLogic\fP, \fBPhoton\&.Chat\&.DisconnectByServerReasonUnknown\fP, \fBPhoton\&.Chat\&.ServerTimeout\fP, \fBPhoton\&.Chat\&.ClientTimeout\fP, \fBPhoton\&.Chat\&.Exception\fP, \fBPhoton\&.Chat\&.InvalidAuthentication\fP, \fBPhoton\&.Chat\&.MaxCcuReached\fP, \fBPhoton\&.Chat\&.InvalidRegion\fP, \fBPhoton\&.Chat\&.OperationNotAllowedInCurrentState\fP, \fBPhoton\&.Chat\&.CustomAuthenticationFailed\fP, \fBPhoton\&.Chat\&.AuthenticationTicketExpired\fP, \fBPhoton\&.Chat\&.DisconnectByClientLogic\fP }"
.br
.RI "Enumeration of causes for Disconnects (used in ChatClient\&.DisconnectedCause)\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
