.TH "Chores" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Chores
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleAnimator\fP ()"
.br
.ti -1c
.RI "void \fBSetOutlineVisibility\fP (GameObject obj, bool isShown)"
.br
.ti -1c
.RI "void \fBGetObject\fP ()"
.br
.ti -1c
.RI "void \fBPutBack\fP ()"
.br
.RI "TASK COMPLETE WHEN PUT THINGS BACK\&. "
.ti -1c
.RI "void \fBWashDishes\fP ()"
.br
.ti -1c
.RI "void \fBPutDishesAway\fP ()"
.br
.ti -1c
.RI "void \fBMakeBed\fP ()"
.br
.ti -1c
.RI "void \fBPickToy\fP ()"
.br
.ti -1c
.RI "void \fBCleanToy\fP ()"
.br
.ti -1c
.RI "void \fBClearTrash\fP ()"
.br
.ti -1c
.RI "void \fBSweepFloor\fP ()"
.br
.ti -1c
.RI "void \fBWipeWindow\fP ()"
.br
.ti -1c
.RI "void \fBWaterPlant\fP ()"
.br
.ti -1c
.RI "void \fBDustCabinet\fP ()"
.br
.ti -1c
.RI "void \fBOpenFridge\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisAtSink\fP = false"
.br
.ti -1c
.RI "bool \fBisAtCabinet\fP = false"
.br
.ti -1c
.RI "bool \fBfinishedDishTask\fP = false"
.br
.ti -1c
.RI "bool \fBisDoneSink\fP = false"
.br
.ti -1c
.RI "bool \fBisAtBed\fP = false"
.br
.ti -1c
.RI "bool \fBfinishedBedTask\fP = false"
.br
.ti -1c
.RI "bool \fBisNearPickableObject\fP = false"
.br
.ti -1c
.RI "LayerMask \fBlayerMask\fP"
.br
.ti -1c
.RI "UnityEvent \fBTaskComplete\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBdoneSweepTask\fP = false"
.br
.ti -1c
.RI "static bool \fBinSweepZone\fP = false"
.br
.ti -1c
.RI "static bool \fBwashDishTask\fP = false"
.br
.ti -1c
.RI "static bool \fBmakeBedTask\fP = false"
.br
.ti -1c
.RI "static bool \fBsweepTask\fP = false"
.br
.ti -1c
.RI "static bool \fBwipeTask\fP = false"
.br
.ti -1c
.RI "static bool \fBwaterTask\fP = false"
.br
.ti -1c
.RI "static bool \fBdustTask\fP = false"
.br
.ti -1c
.RI "static bool \fBtrashTask\fP = false"
.br
.ti -1c
.RI "static bool \fBtoyTask\fP = false"
.br
.ti -1c
.RI "static bool \fBfridgeTask\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneWipeTask\fP = false"
.br
.ti -1c
.RI "static bool \fBinWipeZone\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneWaterTask\fP = false"
.br
.ti -1c
.RI "static bool \fBinWaterZone\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneDustTask\fP = false"
.br
.ti -1c
.RI "static bool \fBinDustZone\fP = false"
.br
.ti -1c
.RI "static bool \fBinTrashZone\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneTrashTask\fP = false"
.br
.ti -1c
.RI "static bool \fBinToyZone\fP = false"
.br
.ti -1c
.RI "static bool \fBinToyboxZone\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneCleanToy\fP = false"
.br
.ti -1c
.RI "static bool \fBinFridgeZone\fP = false"
.br
.ti -1c
.RI "static bool \fBdoneFridgeTask\fP = false"
.br
.ti -1c
.RI "static bool \fBfridgeIsOpen\fP = false"
.br
.ti -1c
.RI "static bool \fBhavePenyapu\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveCloth\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveDuster\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveChicken\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveToy\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveWatercan\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBChores\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Chores\&.CleanToy ()"

.PP
Definition at line \fB740\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.ClearTrash ()"

.PP
Definition at line \fB755\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.DustCabinet ()"

.PP
Definition at line \fB803\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.GetObject ()"

.PP
Definition at line \fB255\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.HandleAnimator ()"

.PP
Definition at line \fB81\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.MakeBed ()"

.PP
Definition at line \fB395\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.OpenFridge ()"

.PP
Definition at line \fB820\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.PickToy ()"

.PP
Definition at line \fB732\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.PutBack ()"

.PP
TASK COMPLETE WHEN PUT THINGS BACK\&. 
.PP
Definition at line \fB301\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.PutDishesAway ()"

.PP
Definition at line \fB380\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.SetOutlineVisibility (GameObject obj, bool isShown)"

.PP
Definition at line \fB102\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.SweepFloor ()"

.PP
Definition at line \fB771\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.WashDishes ()"

.PP
Definition at line \fB370\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.WaterPlant ()"

.PP
Definition at line \fB793\fP of file \fBChores\&.cs\fP\&.
.SS "void Chores\&.WipeWindow ()"

.PP
Definition at line \fB782\fP of file \fBChores\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Chores\&.doneCleanToy = false\fC [static]\fP"

.PP
Definition at line \fB50\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneDustTask = false\fC [static]\fP"

.PP
Definition at line \fB34\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneFridgeTask = false\fC [static]\fP"

.PP
Definition at line \fB53\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneSweepTask = false\fC [static]\fP"

.PP
Definition at line \fB26\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneTrashTask = false\fC [static]\fP"

.PP
Definition at line \fB46\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneWaterTask = false\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.doneWipeTask = false\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.dustTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.finishedBedTask = false"

.PP
Definition at line \fB21\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.finishedDishTask = false"

.PP
Definition at line \fB18\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.fridgeIsOpen = false\fC [static]\fP"

.PP
Definition at line \fB54\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.fridgeTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.haveChicken = false\fC [static]\fP"

.PP
Definition at line \fB65\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.haveCloth = false\fC [static]\fP"

.PP
Definition at line \fB63\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.haveDuster = false\fC [static]\fP"

.PP
Definition at line \fB64\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.havePenyapu = false\fC [static]\fP"

.PP
Definition at line \fB62\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.haveToy = false\fC [static]\fP"

.PP
Definition at line \fB66\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.haveWatercan = false\fC [static]\fP"

.PP
Definition at line \fB67\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inDustZone = false\fC [static]\fP"

.PP
Definition at line \fB34\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inFridgeZone = false\fC [static]\fP"

.PP
Definition at line \fB52\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inSweepZone = false\fC [static]\fP"

.PP
Definition at line \fB26\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inToyboxZone = false\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inToyZone = false\fC [static]\fP"

.PP
Definition at line \fB48\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inTrashZone = false\fC [static]\fP"

.PP
Definition at line \fB45\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inWaterZone = false\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.inWipeZone = false\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.isAtBed = false"

.PP
Definition at line \fB21\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.isAtCabinet = false"

.PP
Definition at line \fB18\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.isAtSink = false"

.PP
Definition at line \fB18\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.isDoneSink = false"

.PP
Definition at line \fB18\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.isNearPickableObject = false"

.PP
Definition at line \fB23\fP of file \fBChores\&.cs\fP\&.
.SS "LayerMask Chores\&.layerMask"

.PP
Definition at line \fB56\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.makeBedTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.sweepTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "UnityEvent Chores\&.TaskComplete"

.PP
Definition at line \fB58\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.toyTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.trashTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.washDishTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.waterTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.
.SS "bool Chores\&.wipeTask = false\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBChores\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
