.TH "ChoreInteractor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChoreInteractor
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayerMask \fBinteractableLayerMask\fP = 12"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBChoreInteractor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayerMask ChoreInteractor\&.interactableLayerMask = 12"

.PP
Definition at line \fB9\fP of file \fBChoreInteractor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
