.TH "CircleIndicator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CircleIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBButtonHoldDown\fP \fBbD\fP"
.br
.ti -1c
.RI "\fBButtonHoldDown\fP \fBbD2\fP"
.br
.ti -1c
.RI "Image \fBcircleOut\fP"
.br
.ti -1c
.RI "Image \fBcircleIn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCircleIndicator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CircleIndicator\&.Update ()"

.PP
Definition at line \fB13\fP of file \fBCircleIndicator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonHoldDown\fP CircleIndicator\&.bD"

.PP
Definition at line \fB8\fP of file \fBCircleIndicator\&.cs\fP\&.
.SS "\fBButtonHoldDown\fP CircleIndicator\&.bD2"

.PP
Definition at line \fB9\fP of file \fBCircleIndicator\&.cs\fP\&.
.SS "Image CircleIndicator\&.circleIn"

.PP
Definition at line \fB11\fP of file \fBCircleIndicator\&.cs\fP\&.
.SS "Image CircleIndicator\&.circleOut"

.PP
Definition at line \fB11\fP of file \fBCircleIndicator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
