.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Utilities/Collider/CollideType.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Utilities/Collider/CollideType.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.ContactType\fP { \fBPhoton\&.Pun\&.Simple\&.Undefined\fP = 0, \fBPhoton\&.Pun\&.Simple\&.Enter\fP = 1, \fBPhoton\&.Pun\&.Simple\&.Stay\fP = 2, \fBPhoton\&.Pun\&.Simple\&.Exit\fP = 4, \fBPhoton\&.Pun\&.Simple\&.Hitscan\fP = 8 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
