.TH "CollectItemQuest" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollectItemQuest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBQuestActive\fP ()"
.br
.ti -1c
.RI "override void \fBQuestCompleted\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB97\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void CollectItemQuest\&.QuestActive ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQuest\fP\&.
.PP
Definition at line \fB105\fP of file \fBQuest\&.cs\fP\&.
.SS "override void CollectItemQuest\&.QuestCompleted ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQuest\fP\&.
.PP
Definition at line \fB117\fP of file \fBQuest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
