.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/Culling/CullArea.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/Culling/CullArea.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.CullArea\fP"
.br
.RI "Represents the cull area used for network culling\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.CellTree\fP"
.br
.RI "Represents the tree accessible from its root node\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.CellTreeNode\fP"
.br
.RI "Represents a single node of the tree\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.ByteComparer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.UtilityScripts\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
