.TH "DefeatEnemiesQuest" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefeatEnemiesQuest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuest\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNumberOfEnemiesToDestroy\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBEnable\fP ()"
.br
.ti -1c
.RI "override void \fBQuestCompleted\fP ()"
.br
.ti -1c
.RI "override void \fBQuestActive\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB137\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void DefeatEnemiesQuest\&.Enable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBQuest\fP\&.
.PP
Definition at line \fB145\fP of file \fBQuest\&.cs\fP\&.
.SS "override void DefeatEnemiesQuest\&.QuestActive ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQuest\fP\&.
.PP
Definition at line \fB157\fP of file \fBQuest\&.cs\fP\&.
.SS "override void DefeatEnemiesQuest\&.QuestCompleted ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBQuest\fP\&.
.PP
Definition at line \fB152\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int DefeatEnemiesQuest\&.NumberOfEnemiesToDestroy"

.PP
Definition at line \fB142\fP of file \fBQuest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
