.TH "DestroyGameObject" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DestroyGameObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelfDestroy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBDestroyGameObject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DestroyGameObject\&.SelfDestroy ()"

.PP
Definition at line \fB27\fP of file \fBDestroyGameObject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
