.TH "DevComments" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevComments \- Adding comments to GameObjects in the Inspector\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtext\fP"
.br
.RI "The comment\&. "
.in -1c
.SH "Detailed Description"
.PP 
Adding comments to GameObjects in the Inspector\&. 


.PP
Definition at line \fB8\fP of file \fBDevComments\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string DevComments\&.text"

.PP
The comment\&. 
.PP
Definition at line \fB14\fP of file \fBDevComments\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
