.TH "DisplayWinner" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisplayWinner
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TextMeshProUGUI \fBplayerName\fP"
.br
.ti -1c
.RI "bool \fBisHuman\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBDisplayWinner\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool DisplayWinner\&.isHuman"

.PP
Definition at line \fB14\fP of file \fBDisplayWinner\&.cs\fP\&.
.SS "TextMeshProUGUI DisplayWinner\&.playerName"

.PP
Definition at line \fB12\fP of file \fBDisplayWinner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
