.TH "Dustyroom.LinearMotion" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dustyroom.LinearMotion
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTranslationMode\fP { \fBOff\fP, \fBXAxis\fP, \fBYAxis\fP, \fBZAxis\fP, \fBVector\fP }"
.br
.ti -1c
.RI "enum \fBRotationMode\fP { \fBOff\fP, \fBXAxis\fP, \fBYAxis\fP, \fBZAxis\fP, \fBVector\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTranslationMode\fP \fBtranslationMode\fP = \fBTranslationMode\&.Off\fP"
.br
.ti -1c
.RI "Vector3 \fBtranslationVector\fP = Vector3\&.forward"
.br
.ti -1c
.RI "float \fBtranslationSpeed\fP = 1\&.0f"
.br
.ti -1c
.RI "\fBRotationMode\fP \fBrotationMode\fP = \fBRotationMode\&.Off\fP"
.br
.ti -1c
.RI "Vector3 \fBrotationAxis\fP = Vector3\&.up"
.br
.ti -1c
.RI "float \fBrotationSpeed\fP = 50\&.0f"
.br
.ti -1c
.RI "bool \fBuseLocalCoordinate\fP = true"
.br
.ti -1c
.RI "float \fBtranslationAcceleration\fP = 0f"
.br
.ti -1c
.RI "float \fBrotationAcceleration\fP = 0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLinearMotion\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBDustyroom\&.LinearMotion\&.RotationMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOff \fP\fP
.TP
\fB\fIXAxis \fP\fP
.TP
\fB\fIYAxis \fP\fP
.TP
\fB\fIZAxis \fP\fP
.TP
\fB\fIVector \fP\fP
.PP
Definition at line \fB15\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "enum \fBDustyroom\&.LinearMotion\&.TranslationMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOff \fP\fP
.TP
\fB\fIXAxis \fP\fP
.TP
\fB\fIYAxis \fP\fP
.TP
\fB\fIZAxis \fP\fP
.TP
\fB\fIVector \fP\fP
.PP
Definition at line \fB7\fP of file \fBLinearMotion\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Dustyroom\&.LinearMotion\&.rotationAcceleration = 0f"

.PP
Definition at line \fB31\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "Vector3 Dustyroom\&.LinearMotion\&.rotationAxis = Vector3\&.up"

.PP
Definition at line \fB27\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "\fBRotationMode\fP Dustyroom\&.LinearMotion\&.rotationMode = \fBRotationMode\&.Off\fP"

.PP
Definition at line \fB26\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "float Dustyroom\&.LinearMotion\&.rotationSpeed = 50\&.0f"

.PP
Definition at line \fB28\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "float Dustyroom\&.LinearMotion\&.translationAcceleration = 0f"

.PP
Definition at line \fB30\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "\fBTranslationMode\fP Dustyroom\&.LinearMotion\&.translationMode = \fBTranslationMode\&.Off\fP"

.PP
Definition at line \fB23\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "float Dustyroom\&.LinearMotion\&.translationSpeed = 1\&.0f"

.PP
Definition at line \fB25\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "Vector3 Dustyroom\&.LinearMotion\&.translationVector = Vector3\&.forward"

.PP
Definition at line \fB24\fP of file \fBLinearMotion\&.cs\fP\&.
.SS "bool Dustyroom\&.LinearMotion\&.useLocalCoordinate = true"

.PP
Definition at line \fB29\fP of file \fBLinearMotion\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
