.TH "Dustyroom.OrbitMotion" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dustyroom.OrbitMotion
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTargetMode\fP { \fBTransform\fP, \fBPosition\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTargetMode\fP \fBtargetMode\fP = \fBTargetMode\&.Position\fP"
.br
.ti -1c
.RI "Transform \fBtargetTransform\fP"
.br
.ti -1c
.RI "bool \fBfollowTargetTransform\fP = true"
.br
.ti -1c
.RI "Vector3 \fBtargetOffset\fP = Vector3\&.zero"
.br
.ti -1c
.RI "Vector3 \fBtargetPosition\fP"
.br
.ti -1c
.RI "float \fBdistanceHorizontal\fP = 60\&.0f"
.br
.ti -1c
.RI "float \fBdistanceVertical\fP = 60\&.0f"
.br
.ti -1c
.RI "float \fBxSpeed\fP = 120\&.0f"
.br
.ti -1c
.RI "float \fBySpeed\fP = 120\&.0f"
.br
.ti -1c
.RI "float \fBdamping\fP = 3f"
.br
.ti -1c
.RI "bool \fBclampAngle\fP = false"
.br
.ti -1c
.RI "float \fByMinLimit\fP = \-20f"
.br
.ti -1c
.RI "float \fByMaxLimit\fP = 80f"
.br
.ti -1c
.RI "bool \fBallowZoom\fP = false"
.br
.ti -1c
.RI "float \fBdistanceMin\fP = \&.5f"
.br
.ti -1c
.RI "float \fBdistanceMax\fP = 15f"
.br
.ti -1c
.RI "bool \fBautoMovement\fP = false"
.br
.ti -1c
.RI "float \fBautoSpeedX\fP = 0\&.2f"
.br
.ti -1c
.RI "float \fBautoSpeedY\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBautoSpeedDistance\fP = \-0\&.1f"
.br
.ti -1c
.RI "bool \fBinteractive\fP = true"
.br
.ti -1c
.RI "float \fBtimeSinceLastMove\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBOrbitMotion\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBDustyroom\&.OrbitMotion\&.TargetMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITransform \fP\fP
.TP
\fB\fIPosition \fP\fP
.PP
Definition at line \fB5\fP of file \fBOrbitMotion\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Dustyroom\&.OrbitMotion\&.allowZoom = false"

.PP
Definition at line \fB26\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "bool Dustyroom\&.OrbitMotion\&.autoMovement = false"

.PP
Definition at line \fB33\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.autoSpeedDistance = \-0\&.1f"

.PP
Definition at line \fB36\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.autoSpeedX = 0\&.2f"

.PP
Definition at line \fB34\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.autoSpeedY = 0\&.1f"

.PP
Definition at line \fB35\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "bool Dustyroom\&.OrbitMotion\&.clampAngle = false"

.PP
Definition at line \fB22\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.damping = 3f"

.PP
Definition at line \fB20\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.distanceHorizontal = 60\&.0f"

.PP
Definition at line \fB16\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.distanceMax = 15f"

.PP
Definition at line \fB28\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.distanceMin = \&.5f"

.PP
Definition at line \fB27\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.distanceVertical = 60\&.0f"

.PP
Definition at line \fB17\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "bool Dustyroom\&.OrbitMotion\&.followTargetTransform = true"

.PP
Definition at line \fB12\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "bool Dustyroom\&.OrbitMotion\&.interactive = true"

.PP
Definition at line \fB38\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "\fBTargetMode\fP Dustyroom\&.OrbitMotion\&.targetMode = \fBTargetMode\&.Position\fP"

.PP
Definition at line \fB10\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "Vector3 Dustyroom\&.OrbitMotion\&.targetOffset = Vector3\&.zero"

.PP
Definition at line \fB13\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "Vector3 Dustyroom\&.OrbitMotion\&.targetPosition"

.PP
Definition at line \fB14\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "Transform Dustyroom\&.OrbitMotion\&.targetTransform"

.PP
Definition at line \fB11\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.timeSinceLastMove"

.PP
Definition at line \fB41\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.xSpeed = 120\&.0f"

.PP
Definition at line \fB18\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.yMaxLimit = 80f"

.PP
Definition at line \fB24\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.yMinLimit = \-20f"

.PP
Definition at line \fB23\fP of file \fBOrbitMotion\&.cs\fP\&.
.SS "float Dustyroom\&.OrbitMotion\&.ySpeed = 120\&.0f"

.PP
Definition at line \fB19\fP of file \fBOrbitMotion\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
