.TH "emotitron.Utilities.GUIUtilities.ValueTypeAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.GUIUtilities.ValueTypeAttribute \- Shortens the field rect, and adds the labeltag to the right\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValueTypeAttribute\fP (string \fBlabeltag\fP, float \fBwidth\fP=48)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlabeltag\fP"
.br
.ti -1c
.RI "float \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shortens the field rect, and adds the labeltag to the right\&. 


.PP
Definition at line \fB19\fP of file \fBValueTypeAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "emotitron\&.Utilities\&.GUIUtilities\&.ValueTypeAttribute\&.ValueTypeAttribute (string labeltag, float width = \fC48\fP)"

.PP
Definition at line \fB24\fP of file \fBValueTypeAttribute\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string emotitron\&.Utilities\&.GUIUtilities\&.ValueTypeAttribute\&.labeltag"

.PP
Definition at line \fB21\fP of file \fBValueTypeAttribute\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.GUIUtilities\&.ValueTypeAttribute\&.width"

.PP
Definition at line \fB22\fP of file \fBValueTypeAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
