.TH "emotitron.Utilities.NameTypeUtils" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.NameTypeUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBGetVitalTypeForName\fP (string name, string[] enumNames)"
.br
.RI "Gets the enum value for the type name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBNameTypeDrawer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int emotitron\&.Utilities\&.NameTypeUtils\&.GetVitalTypeForName (string name, string[] enumNames)\fC [static]\fP"

.PP
Gets the enum value for the type name\&. If none exists returns 1-Custom\&. 
.PP
Definition at line \fB19\fP of file \fBNameTypeDrawer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
