.TH "emotitron.Utilities.GUIColorBoxes" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.GUIColorBoxes
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static GUIStyle \fBGrayBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBBlueBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBCyanBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBGreenBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBYellowBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBOrangeBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBRedBoxStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBPurpleBoxStyle\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.BlueBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB18\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.CyanBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB21\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.GrayBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB15\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.GreenBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB24\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.OrangeBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB31\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.PurpleBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB37\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.RedBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB34\fP of file \fBGUIColorBoxes\&.cs\fP\&.
.SS "GUIStyle emotitron\&.Utilities\&.GUIColorBoxes\&.YellowBoxStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB28\fP of file \fBGUIColorBoxes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
