.TH "emotitron.Utilities.Networking.AutoDestroyWrongNetLib" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.Networking.AutoDestroyWrongNetLib
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBNetLib\fP { \fBUNET\fP = 0, \fBPUN\fP = 1, \fBPUN2\fP = 2, \fBPUNAndPUN2\fP = 3 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNetLib\fP \fBnetLib\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBAutoDestroyWrongNetLib\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBemotitron\&.Utilities\&.Networking\&.AutoDestroyWrongNetLib\&.NetLib\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUNET \fP\fP
.TP
\fB\fIPUN \fP\fP
.TP
\fB\fIPUN2 \fP\fP
.TP
\fB\fIPUNAndPUN2 \fP\fP
.PP
Definition at line \fB16\fP of file \fBAutoDestroyWrongNetLib\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBNetLib\fP emotitron\&.Utilities\&.Networking\&.AutoDestroyWrongNetLib\&.netLib"

.PP
Definition at line \fB19\fP of file \fBAutoDestroyWrongNetLib\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
