.TH "emotitron.Utilities.MarkerNameType" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.MarkerNameType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMarkerNameType\fP (\fBMarkerType\fP vitalType)"
.br
.ti -1c
.RI "\fBMarkerNameType\fP (string \fBname\fP)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMarkerType\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBenumNames\fP = System\&.Enum\&.GetNames(typeof(\fBMarkerType\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBMarkerNameType\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "emotitron\&.Utilities\&.MarkerNameType\&.MarkerNameType (\fBMarkerType\fP vitalType)"

.PP
Definition at line \fB23\fP of file \fBMarkerNameType\&.cs\fP\&.
.SS "emotitron\&.Utilities\&.MarkerNameType\&.MarkerNameType (string name)"

.PP
Definition at line \fB30\fP of file \fBMarkerNameType\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string emotitron\&.Utilities\&.MarkerNameType\&.ToString ()"

.PP
Definition at line \fB39\fP of file \fBMarkerNameType\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] emotitron\&.Utilities\&.MarkerNameType\&.enumNames = System\&.Enum\&.GetNames(typeof(\fBMarkerType\fP))\fC [static]\fP"

.PP
Definition at line \fB37\fP of file \fBMarkerNameType\&.cs\fP\&.
.SS "int emotitron\&.Utilities\&.MarkerNameType\&.hash"

.PP
Definition at line \fB20\fP of file \fBMarkerNameType\&.cs\fP\&.
.SS "string emotitron\&.Utilities\&.MarkerNameType\&.name"

.PP
Definition at line \fB21\fP of file \fBMarkerNameType\&.cs\fP\&.
.SS "\fBMarkerType\fP emotitron\&.Utilities\&.MarkerNameType\&.type"

.PP
Definition at line \fB19\fP of file \fBMarkerNameType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
