.TH "emotitron.TestPackObject" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.TestPackObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnInterpolate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRotationHook\fP (float newrot, float oldrot)"
.br
.ti -1c
.RI "void \fBSnapshotHook\fP (float snap, float targ)"
.br
.ti -1c
.RI "void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "bool \fBOnInterpolate\fP (int snapFrameId, int targFrameId, float t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBrotation\fP"
.br
.ti -1c
.RI "int \fBintoroboto\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBTestPackObject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void emotitron\&.TestPackObject\&.FixedUpdate ()"

.PP
Definition at line \fB114\fP of file \fBTestPackObject\&.cs\fP\&.
.SS "bool emotitron\&.TestPackObject\&.OnInterpolate (int snapFrameId, int targFrameId, float t)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnInterpolate\fP\&.
.PP
Definition at line \fB124\fP of file \fBTestPackObject\&.cs\fP\&.
.SS "void emotitron\&.TestPackObject\&.OnPreSimulate (int frameId, int subFrameId)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Definition at line \fB90\fP of file \fBTestPackObject\&.cs\fP\&.
.SS "void emotitron\&.TestPackObject\&.RotationHook (float newrot, float oldrot)"

.PP
Definition at line \fB75\fP of file \fBTestPackObject\&.cs\fP\&.
.SS "void emotitron\&.TestPackObject\&.SnapshotHook (float snap, float targ)"

.PP
Definition at line \fB85\fP of file \fBTestPackObject\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int emotitron\&.TestPackObject\&.intoroboto"

.PP
Definition at line \fB69\fP of file \fBTestPackObject\&.cs\fP\&.
.SS "float emotitron\&.TestPackObject\&.rotation"

.PP
Definition at line \fB56\fP of file \fBTestPackObject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
