.TH "emotitron.Utilities.Example.BasicController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.Example.BasicController \- A VERY basic player movement and position/rotation sync example using UNET\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTiming\fP { \fBAuto\fP, \fBFixed\fP, \fBUpdate\fP, \fBLateUpdate\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransformCrusher\fP \fBTransformCrusherRef\fP"
.br
.ti -1c
.RI "\fBTiming\fP \fBtiming\fP = \fBTiming\&.Fixed\fP"
.br
.ti -1c
.RI "bool \fBmoveRelative\fP = true"
.br
.ti -1c
.RI "KeyCode \fBmoveLeft\fP = KeyCode\&.A"
.br
.ti -1c
.RI "KeyCode \fBmoveRight\fP = KeyCode\&.D"
.br
.ti -1c
.RI "KeyCode \fBmoveFwd\fP = KeyCode\&.W"
.br
.ti -1c
.RI "KeyCode \fBmoveBwd\fP = KeyCode\&.S"
.br
.ti -1c
.RI "KeyCode \fBmoveUp\fP = KeyCode\&.Space"
.br
.ti -1c
.RI "KeyCode \fBmoveDn\fP = KeyCode\&.Z"
.br
.ti -1c
.RI "KeyCode \fBpitchPos\fP = KeyCode\&.R"
.br
.ti -1c
.RI "KeyCode \fBpitchNeg\fP = KeyCode\&.C"
.br
.ti -1c
.RI "KeyCode \fByawPos\fP = KeyCode\&.E"
.br
.ti -1c
.RI "KeyCode \fByawNeg\fP = KeyCode\&.Q"
.br
.ti -1c
.RI "KeyCode \fBrollPos\fP = KeyCode\&.Alpha4"
.br
.ti -1c
.RI "KeyCode \fBrollNeg\fP = KeyCode\&.Alpha4"
.br
.ti -1c
.RI "bool \fBclampToCrusher\fP = false"
.br
.ti -1c
.RI "float \fBmoveSpeed\fP = 5f"
.br
.ti -1c
.RI "float \fBturnSpeed\fP = 60f"
.br
.ti -1c
.RI "float \fBmoveForce\fP = 12f"
.br
.ti -1c
.RI "float \fBturnForce\fP = 100f"
.br
.ti -1c
.RI "float \fBscaleSpeed\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
A VERY basic player movement and position/rotation sync example using UNET\&. 


.PP
Definition at line \fB23\fP of file \fBBasicController\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBemotitron\&.Utilities\&.Example\&.BasicController\&.Timing\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAuto \fP\fP
.TP
\fB\fIFixed \fP\fP
.TP
\fB\fIUpdate \fP\fP
.TP
\fB\fILateUpdate \fP\fP
.PP
Definition at line \fB41\fP of file \fBBasicController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool emotitron\&.Utilities\&.Example\&.BasicController\&.clampToCrusher = false"

.PP
Definition at line \fB62\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveBwd = KeyCode\&.S"

.PP
Definition at line \fB49\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveDn = KeyCode\&.Z"

.PP
Definition at line \fB51\fP of file \fBBasicController\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.Example\&.BasicController\&.moveForce = 12f"

.PP
Definition at line \fB65\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveFwd = KeyCode\&.W"

.PP
Definition at line \fB48\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveLeft = KeyCode\&.A"

.PP
Definition at line \fB46\fP of file \fBBasicController\&.cs\fP\&.
.SS "bool emotitron\&.Utilities\&.Example\&.BasicController\&.moveRelative = true"

.PP
Definition at line \fB43\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveRight = KeyCode\&.D"

.PP
Definition at line \fB47\fP of file \fBBasicController\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.Example\&.BasicController\&.moveSpeed = 5f"

.PP
Definition at line \fB63\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.moveUp = KeyCode\&.Space"

.PP
Definition at line \fB50\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.pitchNeg = KeyCode\&.C"

.PP
Definition at line \fB55\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.pitchPos = KeyCode\&.R"

.PP
Definition at line \fB54\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.rollNeg = KeyCode\&.Alpha4"

.PP
Definition at line \fB59\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.rollPos = KeyCode\&.Alpha4"

.PP
Definition at line \fB58\fP of file \fBBasicController\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.Example\&.BasicController\&.scaleSpeed = 1f"

.PP
Definition at line \fB67\fP of file \fBBasicController\&.cs\fP\&.
.SS "\fBTiming\fP emotitron\&.Utilities\&.Example\&.BasicController\&.timing = \fBTiming\&.Fixed\fP"

.PP
Definition at line \fB42\fP of file \fBBasicController\&.cs\fP\&.
.SS "\fBTransformCrusher\fP emotitron\&.Utilities\&.Example\&.BasicController\&.TransformCrusherRef"

.PP
Definition at line \fB34\fP of file \fBBasicController\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.Example\&.BasicController\&.turnForce = 100f"

.PP
Definition at line \fB66\fP of file \fBBasicController\&.cs\fP\&.
.SS "float emotitron\&.Utilities\&.Example\&.BasicController\&.turnSpeed = 60f"

.PP
Definition at line \fB64\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.yawNeg = KeyCode\&.Q"

.PP
Definition at line \fB57\fP of file \fBBasicController\&.cs\fP\&.
.SS "KeyCode emotitron\&.Utilities\&.Example\&.BasicController\&.yawPos = KeyCode\&.E"

.PP
Definition at line \fB56\fP of file \fBBasicController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
