.TH "emotitron.Utilities.PrintMaskUtil" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.PrintMaskUtil
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static StringBuilder \fBPrintMask\fP (this BitArray ba, int hiliteBit=\-1)"
.br
.ti -1c
.RI "static int \fBCountTrue\fP (this BitArray ba)"
.br
.ti -1c
.RI "static int \fBCountFalse\fP (this BitArray ba)"
.br
.ti -1c
.RI "static int \fBCountValidRange\fP (this BitArray ba, int start, int lookahead)"
.br
.RI "Inclusively get relative distance to most future true bit in the range\&. "
.ti -1c
.RI "static void \fBClearBitsBefore\fP (this BitArray ba, int start, int count)"
.br
.RI "Non-inclusive clearning of X bits working back from start\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBPrintMaskUtil\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void emotitron\&.Utilities\&.PrintMaskUtil\&.ClearBitsBefore (this BitArray ba, int start, int count)\fC [static]\fP"

.PP
Non-inclusive clearning of X bits working back from start\&. 
.PP
\fBParameters\fP
.RS 4
\fIstart\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB140\fP of file \fBPrintMaskUtil\&.cs\fP\&.
.SS "static int emotitron\&.Utilities\&.PrintMaskUtil\&.CountFalse (this BitArray ba)\fC [static]\fP"

.PP
Definition at line \fB103\fP of file \fBPrintMaskUtil\&.cs\fP\&.
.SS "static int emotitron\&.Utilities\&.PrintMaskUtil\&.CountTrue (this BitArray ba)\fC [static]\fP"

.PP
Definition at line \fB92\fP of file \fBPrintMaskUtil\&.cs\fP\&.
.SS "static int emotitron\&.Utilities\&.PrintMaskUtil\&.CountValidRange (this BitArray ba, int start, int lookahead)\fC [static]\fP"

.PP
Inclusively get relative distance to most future true bit in the range\&. 
.PP
Definition at line \fB117\fP of file \fBPrintMaskUtil\&.cs\fP\&.
.SS "static StringBuilder emotitron\&.Utilities\&.PrintMaskUtil\&.PrintMask (this BitArray ba, int hiliteBit = \fC\-1\fP)\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBPrintMaskUtil\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
