.TH "emotitron" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUtilities\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestPackObject\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTestEnum\fP { \fBNone\fP, \fBSome\fP, \fBSomeMore\fP, \fBAll\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBemotitron\&.TestEnum\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fISome \fP\fP
.TP
\fB\fISomeMore \fP\fP
.TP
\fB\fIAll \fP\fP
.PP
Definition at line \fB10\fP of file \fBTestPackObject\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
