.TH "emotitron.Utilities.GUIUtilities" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.GUIUtilities
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShowIfInterfaceAttribute\fP"
.br
.RI "Attribute that will hide a field if it does not implement the indicated interface\&. "
.ti -1c
.RI "class \fBValueTypeAttribute\fP"
.br
.RI "Shortens the field rect, and adds the labeltag to the right\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
