.TH "emotitron.Utilities.GUIUtilities.ShowIfInterfaceAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities.GUIUtilities.ShowIfInterfaceAttribute \- Attribute that will hide a field if it does not implement the indicated interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShowIfInterfaceAttribute\fP (Type \fBtype\fP, string \fBtooltip\fP)"
.br
.ti -1c
.RI "\fBShowIfInterfaceAttribute\fP (Type \fBtype\fP, string \fBtooltip\fP, float \fBmin\fP, float \fBmax\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Type \fBtype\fP"
.br
.ti -1c
.RI "readonly string \fBtooltip\fP"
.br
.ti -1c
.RI "readonly float \fBmin\fP"
.br
.ti -1c
.RI "readonly float \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute that will hide a field if it does not implement the indicated interface\&. 

NOTE: Cannot be combined with other attributes\&. 
.PP
Definition at line \fB19\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.ShowIfInterfaceAttribute (Type type, string tooltip)"

.PP
Definition at line \fB25\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SS "emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.ShowIfInterfaceAttribute (Type type, string tooltip, float min, float max)"

.PP
Definition at line \fB31\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.max"

.PP
Definition at line \fB23\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SS "readonly float emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.min"

.PP
Definition at line \fB23\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SS "readonly string emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.tooltip"

.PP
Definition at line \fB22\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.
.SS "readonly Type emotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\&.type"

.PP
Definition at line \fB21\fP of file \fBShowIfInterfaceAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
