.TH "emotitron.Utilities" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
emotitron.Utilities
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBExample\fP"
.br
.ti -1c
.RI "namespace \fBGUIUtilities\fP"
.br
.ti -1c
.RI "namespace \fBNetworking\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUIColorBoxes\fP"
.br
.ti -1c
.RI "struct \fBMarkerNameType\fP"
.br
.ti -1c
.RI "class \fBNameTypeUtils\fP"
.br
.ti -1c
.RI "class \fBPrintMaskUtil\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMarkerType\fP { \fBNone\fP, \fBCustom\fP, \fBDefault\fP, \fBPlayer\fP, \fBNPC\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBemotitron\&.Utilities\&.MarkerType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fICustom \fP\fP
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIPlayer \fP\fP
.TP
\fB\fINPC \fP\fP
.PP
Definition at line \fB14\fP of file \fBMarkerNameType\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
