.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/Enums/Enums.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/Enums/Enums.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.TRS\fP { \fBPhoton\&.Pun\&.Simple\&.Position\fP, \fBPhoton\&.Pun\&.Simple\&.Rotation\fP, \fBPhoton\&.Pun\&.Simple\&.Scale\fP }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.AxisMask\fP { \fBPhoton\&.Pun\&.Simple\&.None\fP = 0, \fBPhoton\&.Pun\&.Simple\&.X\fP = 1, \fBPhoton\&.Pun\&.Simple\&.Y\fP = 2, \fBPhoton\&.Pun\&.Simple\&.XY\fP = 3, \fBPhoton\&.Pun\&.Simple\&.Z\fP = 4, \fBPhoton\&.Pun\&.Simple\&.XZ\fP = 5, \fBPhoton\&.Pun\&.Simple\&.YZ\fP = 6, \fBPhoton\&.Pun\&.Simple\&.XYZ\fP = 7 }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.Replication\fP { \fBPhoton\&.Pun\&.Simple\&.OwnerSend\fP = 1, \fBPhoton\&.Pun\&.Simple\&.MasterSend\fP = 2 }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.Interpolation\fP { \fBPhoton\&.Pun\&.Simple\&.None\fP, \fBPhoton\&.Pun\&.Simple\&.Linear\fP, \fBPhoton\&.Pun\&.Simple\&.CatmullRom\fP }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.LocalApplyTiming\fP { \fBPhoton\&.Pun\&.Simple\&.Never\fP, \fBPhoton\&.Pun\&.Simple\&.Immediately\fP, \fBPhoton\&.Pun\&.Simple\&.OnSend\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
