.TH "FlatKit.FlatKitFog" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.FlatKitFog
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableRendererFeature\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCreate\fP ()"
.br
.ti -1c
.RI "override void \fBAddRenderPasses\fP (ScriptableRenderer renderer, ref RenderingData renderingData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFogSettings\fP \fBsettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBFlatKitFog\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void FlatKit\&.FlatKitFog\&.AddRenderPasses (ScriptableRenderer renderer, ref RenderingData renderingData)"

.PP
Definition at line \fB99\fP of file \fBFlatKitFog\&.cs\fP\&.
.SS "override void FlatKit\&.FlatKitFog\&.Create ()"

.PP
Definition at line \fB86\fP of file \fBFlatKitFog\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFogSettings\fP FlatKit\&.FlatKitFog\&.settings"

.PP
Definition at line \fB63\fP of file \fBFlatKitFog\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
