.TH "FlatKit.Water.Tooltips" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.Water.Tooltips
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< String, String > \fBmap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTooltips\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<String, String> FlatKit\&.Water\&.Tooltips\&.map\fC [static]\fP"

.PP
Definition at line \fB6\fP of file \fBTooltips\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
