.TH "FlatKit.FogSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.FogSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuseDistance\fP = true"
.br
.ti -1c
.RI "Gradient \fBdistanceGradient\fP"
.br
.ti -1c
.RI "float \fBnear\fP = 0"
.br
.ti -1c
.RI "float \fBfar\fP = 100"
.br
.ti -1c
.RI "float \fBdistanceFogIntensity\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBuseDistanceFogOnSky\fP = false"
.br
.ti -1c
.RI "bool \fBuseHeight\fP = false"
.br
.ti -1c
.RI "Gradient \fBheightGradient\fP"
.br
.ti -1c
.RI "float \fBlow\fP = 0"
.br
.ti -1c
.RI "float \fBhigh\fP = 10"
.br
.ti -1c
.RI "float \fBheightFogIntensity\fP = 1\&.0f"
.br
.ti -1c
.RI "bool \fBuseHeightFogOnSky\fP = false"
.br
.ti -1c
.RI "float \fBdistanceHeightBlend\fP = 0\&.5f"
.br
.ti -1c
.RI "RenderPassEvent \fBrenderEvent\fP = RenderPassEvent\&.AfterRenderingTransparents"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBFogSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float FlatKit\&.FogSettings\&.distanceFogIntensity = 1\&.0f"

.PP
Definition at line \fB12\fP of file \fBFogSettings\&.cs\fP\&.
.SS "Gradient FlatKit\&.FogSettings\&.distanceGradient"

.PP
Definition at line \fB9\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.distanceHeightBlend = 0\&.5f"

.PP
Definition at line \fB24\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.far = 100"

.PP
Definition at line \fB11\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.heightFogIntensity = 1\&.0f"

.PP
Definition at line \fB20\fP of file \fBFogSettings\&.cs\fP\&.
.SS "Gradient FlatKit\&.FogSettings\&.heightGradient"

.PP
Definition at line \fB17\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.high = 10"

.PP
Definition at line \fB19\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.low = 0"

.PP
Definition at line \fB18\fP of file \fBFogSettings\&.cs\fP\&.
.SS "float FlatKit\&.FogSettings\&.near = 0"

.PP
Definition at line \fB10\fP of file \fBFogSettings\&.cs\fP\&.
.SS "RenderPassEvent FlatKit\&.FogSettings\&.renderEvent = RenderPassEvent\&.AfterRenderingTransparents"

.PP
Definition at line \fB27\fP of file \fBFogSettings\&.cs\fP\&.
.SS "bool FlatKit\&.FogSettings\&.useDistance = true"

.PP
Definition at line \fB8\fP of file \fBFogSettings\&.cs\fP\&.
.SS "bool FlatKit\&.FogSettings\&.useDistanceFogOnSky = false"

.PP
Definition at line \fB13\fP of file \fBFogSettings\&.cs\fP\&.
.SS "bool FlatKit\&.FogSettings\&.useHeight = false"

.PP
Definition at line \fB16\fP of file \fBFogSettings\&.cs\fP\&.
.SS "bool FlatKit\&.FogSettings\&.useHeightFogOnSky = false"

.PP
Definition at line \fB21\fP of file \fBFogSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
