.TH "FlatKit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBStylizedSurface\fP"
.br
.ti -1c
.RI "namespace \fBWater\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuoyancy\fP"
.br
.ti -1c
.RI "class \fBFlatKitFog\fP"
.br
.ti -1c
.RI "class \fBFlatKitOutline\fP"
.br
.ti -1c
.RI "class \fBFlatKitReadme\fP"
.br
.ti -1c
.RI "class \fBFogSettings\fP"
.br
.ti -1c
.RI "class \fBNetworkManager\fP"
.br
.ti -1c
.RI "class \fBOutlineSettings\fP"
.br
.ti -1c
.RI "class \fBReadmeEditor\fP"
.br
.ti -1c
.RI "class \fBUvScroller\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
