.TH "FlatKitWaterEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKitWaterEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits ShaderGUI\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnGUI\fP (MaterialEditor materialEditor, MaterialProperty[] properties)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBWaterEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void FlatKitWaterEditor\&.OnGUI (MaterialEditor materialEditor, MaterialProperty[] properties)"

.PP
Definition at line \fB12\fP of file \fBWaterEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
