.TH "FlatKit.NetworkManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.NetworkManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBGetVersion\fP (Action< string > callback)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBNetworkManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void FlatKit\&.NetworkManager\&.GetVersion (Action< string > callback)\fC [static]\fP"

.PP
Definition at line \fB9\fP of file \fBNetworkManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
