.TH "FlatKit.OutlineSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.OutlineSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBedgeColor\fP = Color\&.white"
.br
.ti -1c
.RI "int \fBthickness\fP = 1"
.br
.ti -1c
.RI "bool \fBresolutionInvariant\fP = false"
.br
.ti -1c
.RI "bool \fBuseDepth\fP = true"
.br
.ti -1c
.RI "bool \fBuseNormals\fP = false"
.br
.ti -1c
.RI "bool \fBuseColor\fP = false"
.br
.ti -1c
.RI "float \fBminDepthThreshold\fP = 0f"
.br
.ti -1c
.RI "float \fBmaxDepthThreshold\fP = 0\&.25f"
.br
.ti -1c
.RI "float \fBminNormalsThreshold\fP = 0f"
.br
.ti -1c
.RI "float \fBmaxNormalsThreshold\fP = 0\&.25f"
.br
.ti -1c
.RI "float \fBminColorThreshold\fP = 0f"
.br
.ti -1c
.RI "float \fBmaxColorThreshold\fP = 0\&.25f"
.br
.ti -1c
.RI "RenderPassEvent \fBrenderEvent\fP = RenderPassEvent\&.AfterRenderingTransparents"
.br
.ti -1c
.RI "bool \fBoutlineOnly\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBOutlineSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color FlatKit\&.OutlineSettings\&.edgeColor = Color\&.white"

.PP
Definition at line \fB9\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.maxColorThreshold = 0\&.25f"

.PP
Definition at line \fB28\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.maxDepthThreshold = 0\&.25f"

.PP
Definition at line \fB24\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.maxNormalsThreshold = 0\&.25f"

.PP
Definition at line \fB26\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.minColorThreshold = 0f"

.PP
Definition at line \fB27\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.minDepthThreshold = 0f"

.PP
Definition at line \fB22\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "float FlatKit\&.OutlineSettings\&.minNormalsThreshold = 0f"

.PP
Definition at line \fB25\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "bool FlatKit\&.OutlineSettings\&.outlineOnly = false"

.PP
Definition at line \fB32\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "RenderPassEvent FlatKit\&.OutlineSettings\&.renderEvent = RenderPassEvent\&.AfterRenderingTransparents"

.PP
Definition at line \fB30\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "bool FlatKit\&.OutlineSettings\&.resolutionInvariant = false"

.PP
Definition at line \fB15\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "int FlatKit\&.OutlineSettings\&.thickness = 1"

.PP
Definition at line \fB11\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "bool FlatKit\&.OutlineSettings\&.useColor = false"

.PP
Definition at line \fB19\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "bool FlatKit\&.OutlineSettings\&.useDepth = true"

.PP
Definition at line \fB17\fP of file \fBOutlineSettings\&.cs\fP\&.
.SS "bool FlatKit\&.OutlineSettings\&.useNormals = false"

.PP
Definition at line \fB18\fP of file \fBOutlineSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
