.TH "FlatKit.UvScroller" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKit.UvScroller
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBtargetMaterial\fP"
.br
.ti -1c
.RI "float \fBspeedX\fP = 0f"
.br
.ti -1c
.RI "float \fBspeedY\fP = 0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBUvScroller\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float FlatKit\&.UvScroller\&.speedX = 0f"

.PP
Definition at line \fB6\fP of file \fBUvScroller\&.cs\fP\&.
.SS "float FlatKit\&.UvScroller\&.speedY = 0f"

.PP
Definition at line \fB7\fP of file \fBUvScroller\&.cs\fP\&.
.SS "Material FlatKit\&.UvScroller\&.targetMaterial"

.PP
Definition at line \fB5\fP of file \fBUvScroller\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
