.TH "FlatKitDepthNormals" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlatKitDepthNormals
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableRendererFeature\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlatKitDepthNormals\fP (RenderTargetHandle depthNormalsTexture)"
.br
.ti -1c
.RI "override void \fBCreate\fP ()"
.br
.ti -1c
.RI "override void \fBAddRenderPasses\fP (ScriptableRenderer renderer, ref RenderingData renderingData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBoverrideRenderEvent\fP"
.br
.ti -1c
.RI "RenderPassEvent \fBrenderEvent\fP = RenderPassEvent\&.AfterRenderingTransparents"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FlatKitDepthNormals\&.FlatKitDepthNormals (RenderTargetHandle depthNormalsTexture)"

.PP
Definition at line \fB83\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void FlatKitDepthNormals\&.AddRenderPasses (ScriptableRenderer renderer, ref RenderingData renderingData)"

.PP
Definition at line \fB95\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.
.SS "override void FlatKitDepthNormals\&.Create ()"

.PP
Definition at line \fB87\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool FlatKitDepthNormals\&.overrideRenderEvent"

.PP
Definition at line \fB10\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.
.SS "RenderPassEvent FlatKitDepthNormals\&.renderEvent = RenderPassEvent\&.AfterRenderingTransparents"

.PP
Definition at line \fB11\fP of file \fBFlatKitDepthNormals\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
