.TH "FoodBehaviourScript" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FoodBehaviourScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPhotonSyncingTaskCompletion\fP ()"
.br
.ti -1c
.RI "void \fBDeliverFood\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisCollected\fP = false"
.br
.ti -1c
.RI "bool \fBisHeld\fP = true"
.br
.ti -1c
.RI "float \fBfloatStrength\fP"
.br
.ti -1c
.RI "UnityEvent \fBTaskComplete\fP"
.br
.ti -1c
.RI "GameObject \fBfoodObject\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FoodBehaviourScript\&.DeliverFood ()"

.PP
Definition at line \fB61\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "void FoodBehaviourScript\&.PhotonSyncingTaskCompletion ()"

.PP
Definition at line \fB52\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float FoodBehaviourScript\&.floatStrength"

.PP
Definition at line \fB13\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "GameObject FoodBehaviourScript\&.foodObject"

.PP
Definition at line \fB16\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "bool FoodBehaviourScript\&.isActive = false"

.PP
Definition at line \fB22\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "bool FoodBehaviourScript\&.isCollected = false"

.PP
Definition at line \fB11\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "bool FoodBehaviourScript\&.isHeld = true"

.PP
Definition at line \fB11\fP of file \fBFoodBehaviourScript\&.cs\fP\&.
.SS "UnityEvent FoodBehaviourScript\&.TaskComplete"

.PP
Definition at line \fB15\fP of file \fBFoodBehaviourScript\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
