.TH "FurnitureButton" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FurnitureButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBInteractable\fP ()"
.br
.ti -1c
.RI "void \fBUninteractable\fP ()"
.br
.ti -1c
.RI "void \fBDestroyFurniture\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Button \fBfurniBreak\fP"
.br
.ti -1c
.RI "\fBCatBreakFurniture\fP \fBgetFurniture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBFurnitureButton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FurnitureButton\&.DestroyFurniture ()"

.PP
Definition at line \fB28\fP of file \fBFurnitureButton\&.cs\fP\&.
.SS "void FurnitureButton\&.Interactable ()"

.PP
Definition at line \fB18\fP of file \fBFurnitureButton\&.cs\fP\&.
.SS "void FurnitureButton\&.Uninteractable ()"

.PP
Definition at line \fB23\fP of file \fBFurnitureButton\&.cs\fP\&.
.SS "void FurnitureButton\&.Update ()"

.PP
Definition at line \fB12\fP of file \fBFurnitureButton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Button FurnitureButton\&.furniBreak"

.PP
Definition at line \fB8\fP of file \fBFurnitureButton\&.cs\fP\&.
.SS "\fBCatBreakFurniture\fP FurnitureButton\&.getFurniture"

.PP
Definition at line \fB10\fP of file \fBFurnitureButton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
