.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/GameCommandType.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/GameCommandType.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSInt\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandType\fP { \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.None\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Activate\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Deactivate\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Open\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Close\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Spawn\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Destroy\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Start\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Stop\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
