.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/GenericHitscan/GenericHitscan.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/GenericHitscan/GenericHitscan.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.Simple\&.HitscanTypeExt\fP"
.br
.RI "Extension of the HitscanType Enum for testing the type of cast/overlap being used\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.Simple\&.GenericHitscanExt\fP"
.br
.RI "Utility class that contains methods to create a unified argument string for calling all of the Raycast/Overlap cast calls\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.HitscanType\fP { \fBPhoton\&.Pun\&.Simple\&.Raycast\fP, \fBPhoton\&.Pun\&.Simple\&.SphereCast\fP, \fBPhoton\&.Pun\&.Simple\&.CapsuleCast\fP, \fBPhoton\&.Pun\&.Simple\&.BoxCast\fP, \fBPhoton\&.Pun\&.Simple\&.OverlapSphere\fP, \fBPhoton\&.Pun\&.Simple\&.OverlapCapsule\fP, \fBPhoton\&.Pun\&.Simple\&.OverlapBox\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
