.TH "GradientSkyboxEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GradientSkyboxEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.MaterialEditor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBGradientSkyboxEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void GradientSkyboxEditor\&.OnInspectorGUI ()"

.PP
Definition at line \fB6\fP of file \fBGradientSkyboxEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
