.TH "HoldButtonTuto" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HoldButtonTuto
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.ti -1c
.RI "void \fBHoldButtonTutorial\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtutoBGPanel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHoldButtonTuto\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HoldButtonTuto\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB12\fP of file \fBHoldButtonTuto\&.cs\fP\&.
.SS "void HoldButtonTuto\&.HoldButtonTutorial ()"

.PP
Definition at line \fB25\fP of file \fBHoldButtonTuto\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject HoldButtonTuto\&.tutoBGPanel"

.PP
Definition at line \fB8\fP of file \fBHoldButtonTuto\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
