.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/Structs/IncludedAxisEnum.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/Structs/IncludedAxisEnum.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Compression\&.IncludeAxisExtensions\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Compression\&.XYZSwitchMaskAttribute\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Compression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.IncludedAxes\fP { \fBPhoton\&.Compression\&.None\fP = 0, \fBPhoton\&.Compression\&.X\fP = 1, \fBPhoton\&.Compression\&.Y\fP = 2, \fBPhoton\&.Compression\&.XY\fP = 3, \fBPhoton\&.Compression\&.Z\fP = 4, \fBPhoton\&.Compression\&.XZ\fP = 5, \fBPhoton\&.Compression\&.YZ\fP = 6, \fBPhoton\&.Compression\&.XYZ\fP = 7, \fBPhoton\&.Compression\&.Uniform\fP = 15 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
