.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/EditorTools/InspectorUtils.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/EditorTools/InspectorUtils.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.MinMaxRangeAttribute\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.BitsPerRangeAttribute\fP"
.br
.RI "Custom drawer attribute that will put bit range slider in the editor\&. "
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.ReadOnlyAttribute\fP"
.br
.RI "Read Only attribute "
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.SingleUnityLayer\fP"
.br
.RI "Single Layer at a time variant of LayerMask "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Utilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
