.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Interfaces/IPhotonViewCallbacks.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Interfaces/IPhotonViewCallbacks.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPhotonViewCallback\fP"
.br
.RI "Empty Base class for all \fBPhotonView\fP callbacks\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IOnPhotonViewPreNetDestroy\fP"
.br
.RI "This interface defines a callback which fires prior to the \fBPhotonNetwork\fP destroying the \fBPhotonView\fP and Gameobject\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IOnPhotonViewOwnerChange\fP"
.br
.RI "This interface defines a callback for changes to the \fBPhotonView\fP's owner\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IOnPhotonViewControllerChange\fP"
.br
.RI "This interface defines a callback for changes to the \fBPhotonView\fP's controller\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
