.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Interfaces/IPunCallbacks.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Interfaces/IPunCallbacks.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunObservable\fP"
.br
.RI "Defines the OnPhotonSerializeView method to make it easy to implement correctly for observable scripts\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunOwnershipCallbacks\fP"
.br
.RI "Global Callback interface for ownership changes\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunInstantiateMagicCallback\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.IPunPrefabPool\fP"
.br
.RI "Defines an interface for object pooling, used in \fBPhotonNetwork\&.Instantiate\fP and \fBPhotonNetwork\&.Destroy\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
