.TH "Launcher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Launcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. "
.ti -1c
.RI "override void \fBOnJoinedLobby\fP ()"
.br
.RI "Called on entering a lobby on the Master Server\&. "
.ti -1c
.RI "void \fBCreateRoom\fP ()"
.br
.ti -1c
.RI "void \fBJoinRoom\fP ()"
.br
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. "
.ti -1c
.RI "override void \fBOnMasterClientSwitched\fP (\fBPlayer\fP newMasterClient)"
.br
.RI "Called after switching to a new MasterClient when the current one leaves\&. "
.ti -1c
.RI "override void \fBOnCreateRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when the server couldn't create a room (OpCreateRoom failed)\&. "
.ti -1c
.RI "override void \fBOnJoinRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRoom call failed on the server\&. "
.ti -1c
.RI "void \fBStartGame\fP ()"
.br
.ti -1c
.RI "void \fBBackToMenu\fP ()"
.br
.ti -1c
.RI "void \fBLeaveRoom\fP ()"
.br
.ti -1c
.RI "void \fBJoinRoom\fP (\fBRoomInfo\fP info)"
.br
.ti -1c
.RI "override void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. "
.ti -1c
.RI "override void \fBOnRoomListUpdate\fP (List< \fBRoomInfo\fP > roomList)"
.br
.RI "Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. "
.ti -1c
.RI "override void \fBOnPlayerEnteredRoom\fP (\fBPlayer\fP newPlayer)"
.br
.RI "Called when a remote player entered the room\&. "
.ti -1c
.RI "void \fBOnClick_Ready\fP ()"
.br
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"
.br
.ti -1c
.RI "IEnumerator \fBCheckAllPlayersReady\fP ()"
.br
.ti -1c
.RI "void \fBAssignRoleRandomly\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLauncher\fP \fBInstance\fP"
.br
.ti -1c
.RI "static readonly string \fBStartGameSceneName\fP = 'MainGame 1'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBLauncher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Launcher\&.AssignRoleRandomly ()"

.PP
Definition at line \fB256\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.BackToMenu ()"

.PP
Definition at line \fB146\fP of file \fBLauncher\&.cs\fP\&.
.SS "IEnumerator Launcher\&.CheckAllPlayersReady ()"

.PP
Definition at line \fB238\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.CreateRoom ()"

.PP
Definition at line \fB70\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.JoinRoom ()"

.PP
Definition at line \fB80\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.JoinRoom (\fBRoomInfo\fP info)"

.PP
Definition at line \fB157\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.LeaveRoom ()"

.PP
Definition at line \fB151\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.OnClick_Ready ()"

.PP
Definition at line \fB190\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnConnectedToMaster ()\fC [virtual]\fP"

.PP
Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. The list of available rooms won't become available unless you join a lobby via LoadBalancingClient\&.OpJoinLobby\&. You can join rooms and create them even without being in a lobby\&. The default lobby is used in that case\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB57\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnCreateRoomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when the server couldn't create a room (OpCreateRoom failed)\&. The most common cause to fail creating a room, is when a title relies on fixed room-names and the room already exists\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB121\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnJoinedLobby ()\fC [virtual]\fP"

.PP
Called on entering a lobby on the Master Server\&. The actual room-list updates will call OnRoomListUpdate\&. 
.PP
While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud)\&. The room list gets available via OnRoomListUpdate\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB64\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. When this is called, you can access the existing players in Room\&.Players, their custom properties and Room\&.CustomProperties\&.
.PP
In this callback, you could create player objects\&. For example in Unity, instantiate a prefab for the player\&.
.PP
If you want a match to be started 'actively', enable the user to signal 'ready' (using OpRaiseEvent or a Custom Property)\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB89\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnJoinRoomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when a previous OpJoinRoom call failed on the server\&. The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room)\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB129\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnLeftRoom ()\fC [virtual]\fP"

.PP
Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server\&. This wraps up multiple internal actions\&.
.PP
Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB164\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnMasterClientSwitched (\fBPlayer\fP newMasterClient)\fC [virtual]\fP"

.PP
Called after switching to a new MasterClient when the current one leaves\&. This is not called when this client enters a room\&. The former MasterClient is still in the player list when this method get called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB113\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnPlayerEnteredRoom (\fBPlayer\fP newPlayer)\fC [virtual]\fP"

.PP
Called when a remote player entered the room\&. This Player is already added to the playerlist\&. 
.PP
If your game starts with a certain number of players, this callback can be useful to check the Room\&.playerCount and find out if you can start\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB185\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"

.PP
Definition at line \fB207\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Launcher\&.OnRoomListUpdate (List< \fBRoomInfo\fP > roomList)\fC [virtual]\fP"

.PP
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. Each item is a RoomInfo which might include custom properties (provided you defined those as lobby-listed when creating a room)\&. Not all types of lobbies provide a listing of rooms to the client\&. Some are silent and specialized for server-side matchmaking\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB169\fP of file \fBLauncher\&.cs\fP\&.
.SS "void Launcher\&.StartGame ()"

.PP
Definition at line \fB139\fP of file \fBLauncher\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLauncher\fP Launcher\&.Instance\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBLauncher\&.cs\fP\&.
.SS "readonly string Launcher\&.StartGameSceneName = 'MainGame 1'\fC [static]\fP"

.PP
Definition at line \fB138\fP of file \fBLauncher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
