.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonRealtime/Code/LoadbalancingPeer.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonRealtime/Code/LoadbalancingPeer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.LoadBalancingPeer\fP"
.br
.RI "A \fBLoadBalancingPeer\fP provides the operations and enum definitions needed to use the LoadBalancing server application which is also used in \fBPhoton\fP Cloud\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.FindFriendsOptions\fP"
.br
.RI "Options for OpFindFriends can be combined to filter which rooms of friends are returned\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.OpJoinRandomRoomParams\fP"
.br
.RI "Parameters for the matchmaking of JoinRandomRoom and JoinRandomOrCreateRoom\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.EnterRoomParams\fP"
.br
.RI "Parameters for creating rooms\&."
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.ErrorCode\fP"
.br
.RI "\fBErrorCode\fP defines the default codes associated with \fBPhoton\fP client/server communication\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.ActorProperties\fP"
.br
.RI "Class for constants\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.GamePropertyKey\fP"
.br
.RI "Class for constants\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.EventCode\fP"
.br
.RI "Class for constants\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.ParameterCode\fP"
.br
.RI "Class for constants\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.OperationCode\fP"
.br
.RI "Class for constants\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.RoomOptions\fP"
.br
.RI "Wraps up common room properties needed when you create rooms\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.RaiseEventOptions\fP"
.br
.RI "Aggregates several less-often used options for operation RaiseEvent\&. See field descriptions for usage details\&."
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.TypedLobby\fP"
.br
.RI "Refers to a specific lobby on the server\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.TypedLobbyInfo\fP"
.br
.RI "Info for a lobby on the server\&. "
.ti -1c
.RI "class \fBPhoton\&.Realtime\&.AuthenticationValues\fP"
.br
.RI "Container for user authentication in \fBPhoton\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Realtime\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.JoinMode\fP : byte { \fBPhoton\&.Realtime\&.Default\fP = 0, \fBPhoton\&.Realtime\&.CreateIfNotExists\fP = 1, \fBPhoton\&.Realtime\&.JoinOrRejoin\fP = 2, \fBPhoton\&.Realtime\&.RejoinOnly\fP = 3 }"
.br
.RI "Defines possible values for OpJoinRoom and OpJoinOrCreate\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.MatchmakingMode\fP : byte { \fBPhoton\&.Realtime\&.FillRoom\fP = 0, \fBPhoton\&.Realtime\&.SerialMatching\fP = 1, \fBPhoton\&.Realtime\&.RandomMatching\fP = 2 }"
.br
.RI "Options for matchmaking rules for OpJoinRandom\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.ReceiverGroup\fP : byte { \fBPhoton\&.Realtime\&.Others\fP = 0, \fBPhoton\&.Realtime\&.All\fP = 1, \fBPhoton\&.Realtime\&.MasterClient\fP = 2 }"
.br
.RI "Lite - OpRaiseEvent lets you chose which actors in the room should receive events\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.EventCaching\fP : byte { \fBPhoton\&.Realtime\&.DoNotCache\fP = 0, \fBPhoton\&.Realtime\&.MergeCache\fP = 1, \fBPhoton\&.Realtime\&.ReplaceCache\fP = 2, \fBPhoton\&.Realtime\&.RemoveCache\fP = 3, \fBPhoton\&.Realtime\&.AddToRoomCache\fP = 4, \fBPhoton\&.Realtime\&.AddToRoomCacheGlobal\fP = 5, \fBPhoton\&.Realtime\&.RemoveFromRoomCache\fP = 6, \fBPhoton\&.Realtime\&.RemoveFromRoomCacheForActorsLeft\fP = 7, \fBPhoton\&.Realtime\&.SliceIncreaseIndex\fP = 10, \fBPhoton\&.Realtime\&.SliceSetIndex\fP = 11, \fBPhoton\&.Realtime\&.SlicePurgeIndex\fP = 12, \fBPhoton\&.Realtime\&.SlicePurgeUpToIndex\fP = 13 }"
.br
.RI "Lite - OpRaiseEvent allows you to cache events and automatically send them to joining players in a room\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.PropertyTypeFlag\fP : byte { \fBPhoton\&.Realtime\&.None\fP = 0x00, \fBPhoton\&.Realtime\&.Game\fP = 0x01, \fBPhoton\&.Realtime\&.Actor\fP = 0x02, \fBPhoton\&.Realtime\&.GameAndActor\fP = Game | Actor }"
.br
.RI "Flags for 'types of properties', being used as filter in OpGetProperties\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.LobbyType\fP : byte { \fBPhoton\&.Realtime\&.Default\fP = 0, \fBPhoton\&.Realtime\&.SqlLobby\fP = 2, \fBPhoton\&.Realtime\&.AsyncRandomLobby\fP = 3 }"
.br
.RI "Types of lobbies define their behaviour and capabilities\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.AuthModeOption\fP { \fBPhoton\&.Realtime\&.Auth\fP, \fBPhoton\&.Realtime\&.AuthOnce\fP, \fBPhoton\&.Realtime\&.AuthOnceWss\fP }"
.br
.RI "Options for authentication modes\&. "
.ti -1c
.RI "enum \fBPhoton\&.Realtime\&.CustomAuthenticationType\fP : byte { \fBPhoton\&.Realtime\&.Custom\fP = 0, \fBPhoton\&.Realtime\&.Steam\fP = 1, \fBPhoton\&.Realtime\&.Facebook\fP = 2, \fBPhoton\&.Realtime\&.Oculus\fP = 3, \fBPhoton\&.Realtime\&.PlayStation4\fP = 4, \fBPhoton\&.Realtime\&.PlayStation\fP = 4, \fBPhoton\&.Realtime\&.Xbox\fP = 5, \fBPhoton\&.Realtime\&.Viveport\fP = 10, \fBPhoton\&.Realtime\&.NintendoSwitch\fP = 11, \fBPhoton\&.Realtime\&.PlayStation5\fP = 12, \fBPhoton\&.Realtime\&.Playstation5\fP = 12, \fBPhoton\&.Realtime\&.Epic\fP = 13, \fBPhoton\&.Realtime\&.FacebookGaming\fP = 15, \fBPhoton\&.Realtime\&.None\fP = byte\&.MaxValue }"
.br
.RI "Options for optional 'Custom Authentication' services used with \fBPhoton\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
