.TH "Menu_old" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu_old
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOpen\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmenuName\fP"
.br
.ti -1c
.RI "bool \fBopen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBMenu_Old\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Menu_old\&.Close ()"

.PP
Definition at line \fB18\fP of file \fBMenu_Old\&.cs\fP\&.
.SS "void Menu_old\&.Open ()"

.PP
Definition at line \fB11\fP of file \fBMenu_Old\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Menu_old\&.menuName"

.PP
Definition at line \fB7\fP of file \fBMenu_Old\&.cs\fP\&.
.SS "bool Menu_old\&.open"

.PP
Definition at line \fB9\fP of file \fBMenu_Old\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
