.TH "MoUIElement" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoUIElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateUIElement\fP (\fBMoData\fP node)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TextMeshProUGUI \fBtitleText\fP"
.br
.ti -1c
.RI "Toggle \fBtoggle\fP"
.br
.ti -1c
.RI "string \fBmoUniqueID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBMoUIElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MoUIElement\&.UpdateUIElement (\fBMoData\fP node)"

.PP
Definition at line \fB25\fP of file \fBMoUIElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string MoUIElement\&.moUniqueID"

.PP
Definition at line \fB13\fP of file \fBMoUIElement\&.cs\fP\&.
.SS "TextMeshProUGUI MoUIElement\&.titleText"

.PP
Definition at line \fB11\fP of file \fBMoUIElement\&.cs\fP\&.
.SS "Toggle MoUIElement\&.toggle"

.PP
Definition at line \fB12\fP of file \fBMoUIElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
