.TH "NetcodeIsMineSetup" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetcodeIsMineSetup
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< GameObject > \fBIsMine_objsToDisable\fP"
.br
.ti -1c
.RI "List< GameObject > \fBIsMine_objsToEnable\fP"
.br
.ti -1c
.RI "List< MonoBehaviour > \fBIsMine_scriptsToEnable\fP"
.br
.ti -1c
.RI "List< MonoBehaviour > \fBIsMine_scriptsToDisable\fP"
.br
.ti -1c
.RI "List< GameObject > \fBIsMineFalse_objsToDisable\fP"
.br
.ti -1c
.RI "List< GameObject > \fBIsMineFalse_objsToEnable\fP"
.br
.ti -1c
.RI "List< MonoBehaviour > \fBIsMineFalse_scriptsToEnable\fP"
.br
.ti -1c
.RI "List< MonoBehaviour > \fBIsMineFalse_scriptsToDisable\fP"
.br
.ti -1c
.RI "\fBPhotonView\fP \fBPV\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<GameObject> NetcodeIsMineSetup\&.IsMine_objsToDisable"

.PP
Definition at line \fB9\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<GameObject> NetcodeIsMineSetup\&.IsMine_objsToEnable"

.PP
Definition at line \fB10\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<MonoBehaviour> NetcodeIsMineSetup\&.IsMine_scriptsToDisable"

.PP
Definition at line \fB12\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<MonoBehaviour> NetcodeIsMineSetup\&.IsMine_scriptsToEnable"

.PP
Definition at line \fB11\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<GameObject> NetcodeIsMineSetup\&.IsMineFalse_objsToDisable"

.PP
Definition at line \fB14\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<GameObject> NetcodeIsMineSetup\&.IsMineFalse_objsToEnable"

.PP
Definition at line \fB15\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<MonoBehaviour> NetcodeIsMineSetup\&.IsMineFalse_scriptsToDisable"

.PP
Definition at line \fB17\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "List<MonoBehaviour> NetcodeIsMineSetup\&.IsMineFalse_scriptsToEnable"

.PP
Definition at line \fB16\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.
.SS "\fBPhotonView\fP NetcodeIsMineSetup\&.PV"

.PP
Definition at line \fB18\fP of file \fBNetcodeIsMineSetup\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
