.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/Compression/NormCompress/NormCompress.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/Compression/NormCompress/NormCompress.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Compression\&.NormCompress\fP"
.br
.RI "Very basic and lightweight compression of floats ranging from 0-1 in value\&. "
.ti -1c
.RI "struct \fBPhoton\&.Compression\&.NormCompress\&.NormCompressCodec\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Compression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.NormalizedFloatCompression\fP { \fBPhoton\&.Compression\&.Bits2\fP = 2, \fBPhoton\&.Compression\&.Bits3\fP, \fBPhoton\&.Compression\&.Bits4\fP, \fBPhoton\&.Compression\&.Bits5\fP, \fBPhoton\&.Compression\&.Bits6\fP, \fBPhoton\&.Compression\&.Bits7\fP, \fBPhoton\&.Compression\&.Bits8\fP, \fBPhoton\&.Compression\&.Bits9\fP, \fBPhoton\&.Compression\&.Bits10\fP, \fBPhoton\&.Compression\&.Bits12\fP = 12, \fBPhoton\&.Compression\&.Bits14\fP = 14, \fBPhoton\&.Compression\&.Half16\fP = 16, \fBPhoton\&.Compression\&.Full32\fP = 32 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
