.TH "ObjectivesDataHolder" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectivesDataHolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBObjectiveData\fP \fBobjectiveData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBObjectivesDataHolder\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBObjectiveData\fP ObjectivesDataHolder\&.objectiveData"

.PP
Definition at line \fB7\fP of file \fBObjectivesDataHolder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
