.TH "ObjectiveData" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectiveData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "\fBGameCommandHandler\fP \fBgameCommandHandler\fP"
.br
.ti -1c
.RI "GameObject \fBassignedOwner\fP"
.br
.ti -1c
.RI "GameObject \fBuiObj\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsCompleted\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB34\fP of file \fBObjectivesManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject ObjectiveData\&.assignedOwner"

.PP
Definition at line \fB38\fP of file \fBObjectivesManager\&.cs\fP\&.
.SS "string ObjectiveData\&.description"

.PP
Definition at line \fB36\fP of file \fBObjectivesManager\&.cs\fP\&.
.SS "\fBGameCommandHandler\fP ObjectiveData\&.gameCommandHandler"

.PP
Definition at line \fB37\fP of file \fBObjectivesManager\&.cs\fP\&.
.SS "GameObject ObjectiveData\&.uiObj"

.PP
Definition at line \fB41\fP of file \fBObjectivesManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ObjectiveData\&.IsCompleted\fC [get]\fP"

.PP
Definition at line \fB40\fP of file \fBObjectivesManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
