.TH "ObjectivesManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectivesManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetupInitialObjectivesUI\fP (\fBObjectiveData\fP od)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBObjectiveData\fP > \fBobjectives\fP"
.br
.ti -1c
.RI "GameObject \fBobjectiveUIPrefab\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutGroup\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBObjectivesManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ObjectivesManager\&.SetupInitialObjectivesUI (\fBObjectiveData\fP od)"

.PP
Definition at line \fB13\fP of file \fBObjectivesManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayoutGroup ObjectivesManager\&.layoutGroup"

.PP
Definition at line \fB12\fP of file \fBObjectivesManager\&.cs\fP\&.
.SS "List<\fBObjectiveData\fP> ObjectivesManager\&.objectives"

.PP
Definition at line \fB10\fP of file \fBObjectivesManager\&.cs\fP\&.
.SS "GameObject ObjectivesManager\&.objectiveUIPrefab"

.PP
Definition at line \fB11\fP of file \fBObjectivesManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
