.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncState/Enums/ObjState.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncState/Enums/ObjState.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.ObjState\fP { \fBPhoton\&.Pun\&.Simple\&.Despawned\fP = 0, \fBPhoton\&.Pun\&.Simple\&.Visible\fP = 1, \fBPhoton\&.Pun\&.Simple\&.Mounted\fP = 2, \fBPhoton\&.Pun\&.Simple\&.AnchoredPosition\fP = 4, \fBPhoton\&.Pun\&.Simple\&.AnchoredRotation\fP = 8, \fBPhoton\&.Pun\&.Simple\&.Anchored\fP = 12, \fBPhoton\&.Pun\&.Simple\&.Dropped\fP = 16, \fBPhoton\&.Pun\&.Simple\&.Transit\fP = 32 }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.ObjStateEditor\fP { \fBPhoton\&.Pun\&.Simple\&.Despawned\fP = 0, \fBPhoton\&.Pun\&.Simple\&.Visible\fP = 1, \fBPhoton\&.Pun\&.Simple\&.Mounted\fP = 2, \fBPhoton\&.Pun\&.Simple\&.AnchoredPosition\fP = 4, \fBPhoton\&.Pun\&.Simple\&.AnchoredRotation\fP = 8, \fBPhoton\&.Pun\&.Simple\&.Dropped\fP = 16, \fBPhoton\&.Pun\&.Simple\&.Transit\fP = 32 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
