.TH "OnAllUnityEventCall" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OnAllUnityEventCall
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlayEventToCall\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBeventToCall\fP"
.br
.ti -1c
.RI "bool \fBisPlayOnEnable\fP = true"
.br
.ti -1c
.RI "bool \fBisPlayOnStart\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnAwake\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnFixedUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnLateUpdate\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnGUI\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnDisable\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnDestroy\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnApplicationPause\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTransformChildrenChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTransformParentChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnBeforeTransformParentChanged\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionEnter\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionExit\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionStay\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerEnter\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerExit\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerStay\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionEnter2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionExit2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnCollisionStay2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerEnter2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerExit2D\fP = false"
.br
.ti -1c
.RI "bool \fBisPlayOnTriggerStay2D\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void OnAllUnityEventCall\&.PlayEventToCall ()"

.PP
Definition at line \fB60\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UnityEvent OnAllUnityEventCall\&.eventToCall"

.PP
Definition at line \fB16\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnApplicationPause = false"

.PP
Definition at line \fB33\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnAwake = false"

.PP
Definition at line \fB21\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnBeforeTransformParentChanged = false"

.PP
Definition at line \fB38\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionEnter = false"

.PP
Definition at line \fB42\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionEnter2D = false"

.PP
Definition at line \fB50\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionExit = false"

.PP
Definition at line \fB43\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionExit2D = false"

.PP
Definition at line \fB51\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionStay = false"

.PP
Definition at line \fB44\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnCollisionStay2D = false"

.PP
Definition at line \fB52\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnDestroy = false"

.PP
Definition at line \fB30\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnDisable = false"

.PP
Definition at line \fB29\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnEnable = true"

.PP
Definition at line \fB19\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnFixedUpdate = false"

.PP
Definition at line \fB23\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnGUI = false"

.PP
Definition at line \fB26\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnLateUpdate = false"

.PP
Definition at line \fB24\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnStart = false"

.PP
Definition at line \fB20\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTransformChildrenChanged = false"

.PP
Definition at line \fB36\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTransformParentChanged = false"

.PP
Definition at line \fB37\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerEnter = false"

.PP
Definition at line \fB45\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerEnter2D = false"

.PP
Definition at line \fB53\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerExit = false"

.PP
Definition at line \fB46\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerExit2D = false"

.PP
Definition at line \fB54\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerStay = false"

.PP
Definition at line \fB47\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnTriggerStay2D = false"

.PP
Definition at line \fB55\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.
.SS "bool OnAllUnityEventCall\&.isPlayOnUpdate = false"

.PP
Definition at line \fB22\fP of file \fBOnAllUnityEventCall\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
