.TH "optionalGui" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
optionalGui \- Optional Gui Elements
.PP
 \- Useful GUI elements for PUN\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\fP"
.br
.RI "This MonoBehaviour is a basic GUI for the \fBPhoton\fP client's network-simulation feature\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.PhotonStatsGui\fP"
.br
.RI "Basic GUI to show traffic and health statistics of the connection to \fBPhoton\fP, toggled by shift+tab\&. "
.in -1c
.SH "Detailed Description"
.PP 
Useful GUI elements for PUN\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
