.TH "OutlinePUN" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutlinePUN
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBOutlineAll\fP, \fBOutlineVisible\fP, \fBOutlineHidden\fP, \fBOutlineAndSilhouette\fP, \fBSilhouetteOnly\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMode\fP \fBOutlineMode\fP\fC [getset]\fP"
.br
.ti -1c
.RI "Color \fBOutlineColor\fP\fC [getset]\fP"
.br
.ti -1c
.RI "float \fBOutlineWidth\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBOutlinePUN\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBOutlinePUN\&.Mode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOutlineAll \fP\fP
.TP
\fB\fIOutlineVisible \fP\fP
.TP
\fB\fIOutlineHidden \fP\fP
.TP
\fB\fIOutlineAndSilhouette \fP\fP
.TP
\fB\fISilhouetteOnly \fP\fP
.PP
Definition at line \fB18\fP of file \fBOutlinePUN\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Color OutlinePUN\&.OutlineColor\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB34\fP of file \fBOutlinePUN\&.cs\fP\&.
.SS "\fBMode\fP OutlinePUN\&.OutlineMode\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB26\fP of file \fBOutlinePUN\&.cs\fP\&.
.SS "float OutlinePUN\&.OutlineWidth\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB42\fP of file \fBOutlinePUN\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
