.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/Enums/PackObjectEnums.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/PackObject/Enums/PackObjectEnums.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Compression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.KeyRate\fP { \fBPhoton\&.Compression\&.UseDefault\fP = -1, \fBPhoton\&.Compression\&.Never\fP, \fBPhoton\&.Compression\&.Every\fP, \fBPhoton\&.Compression\&.Every2nd\fP, \fBPhoton\&.Compression\&.Every3rd\fP, \fBPhoton\&.Compression\&.Every4th\fP, \fBPhoton\&.Compression\&.Every5th\fP, \fBPhoton\&.Compression\&.Every10th\fP = 10 }"
.br
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.SyncAs\fP { \fBPhoton\&.Compression\&.Auto\fP, \fBPhoton\&.Compression\&.State\fP, \fBPhoton\&.Compression\&.Trigger\fP }"
.br
.RI "Indicates how a [Pack] syncvar acts\&. "
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.SetValueTiming\fP { \fBPhoton\&.Compression\&.Never\fP, \fBPhoton\&.Compression\&.AfterCallback\fP, \fBPhoton\&.Compression\&.BeforeCallback\fP }"
.br
.RI "Callbacks assigned to Pack attributes can be called before or after the value is set\&. "
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.IndicatorBit\fP { \fBPhoton\&.Compression\&.None\fP, \fBPhoton\&.Compression\&.IsZero\fP }"
.br
.RI "This enum indicates if an extra bit should be added to indicate cases of Zero value\&. "
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.IndicatorBits\fP { \fBPhoton\&.Compression\&.None\fP, \fBPhoton\&.Compression\&.IsZero\fP, \fBPhoton\&.Compression\&.IsZeroMidMinMax\fP }"
.br
.RI "This enum indicates if an extra bit should be added to indicate cases of Zero value, XXXXX preValue, or two bits should be added to indicate Zero, Min, Max\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
