.TH "ParrelSync.Preferences" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.Preferences
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBBoolPreference\fP \fBAssetModPref\fP = new \fBBoolPreference\fP('ParrelSync_DisableClonesAssetSaving', true)"
.br
.RI "Disable asset saving in clone editors? "
.ti -1c
.RI "static \fBBoolPreference\fP \fBAlsoCheckUnityLockFileStaPref\fP = new \fBBoolPreference\fP('ParrelSync_CheckUnityLockFileOpenStatus', true)"
.br
.RI "In addition of checking the existence of UnityLockFile, also check is the is the UnityLockFile being opened\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB48\fP of file \fBPreferences\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBoolPreference\fP ParrelSync\&.Preferences\&.AlsoCheckUnityLockFileStaPref = new \fBBoolPreference\fP('ParrelSync_CheckUnityLockFileOpenStatus', true)\fC [static]\fP"

.PP
In addition of checking the existence of UnityLockFile, also check is the is the UnityLockFile being opened\&. 
.PP
Definition at line \fB67\fP of file \fBPreferences\&.cs\fP\&.
.SS "\fBBoolPreference\fP ParrelSync\&.Preferences\&.AssetModPref = new \fBBoolPreference\fP('ParrelSync_DisableClonesAssetSaving', true)\fC [static]\fP"

.PP
Disable asset saving in clone editors? 
.PP
Definition at line \fB61\fP of file \fBPreferences\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
