.TH "ParrelSync.ExternalLinks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.ExternalLinks
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBRemoteVersionURL\fP = 'https://raw\&.githubusercontent\&.com/VeriorPies/ParrelSync/master/VERSION\&.txt'"
.br
.ti -1c
.RI "const string \fBReleases\fP = 'https://github\&.com/VeriorPies/ParrelSync/releases'"
.br
.ti -1c
.RI "const string \fBCustomArgumentHelpLink\fP = 'https://github\&.com/VeriorPies/ParrelSync/wiki/Argument'"
.br
.ti -1c
.RI "const string \fBGitHubHome\fP = 'https://github\&.com/VeriorPies/ParrelSync/'"
.br
.ti -1c
.RI "const string \fBGitHubIssue\fP = 'https://github\&.com/VeriorPies/ParrelSync/issues'"
.br
.ti -1c
.RI "const string \fBFAQ\fP = 'https://github\&.com/VeriorPies/ParrelSync/wiki/Troubleshooting\-&\-FAQs'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBExternalLinks\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string ParrelSync\&.ExternalLinks\&.CustomArgumentHelpLink = 'https://github\&.com/VeriorPies/ParrelSync/wiki/Argument'\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBExternalLinks\&.cs\fP\&.
.SS "const string ParrelSync\&.ExternalLinks\&.FAQ = 'https://github\&.com/VeriorPies/ParrelSync/wiki/Troubleshooting\-&\-FAQs'\fC [static]\fP"

.PP
Definition at line \fB11\fP of file \fBExternalLinks\&.cs\fP\&.
.SS "const string ParrelSync\&.ExternalLinks\&.GitHubHome = 'https://github\&.com/VeriorPies/ParrelSync/'\fC [static]\fP"

.PP
Definition at line \fB9\fP of file \fBExternalLinks\&.cs\fP\&.
.SS "const string ParrelSync\&.ExternalLinks\&.GitHubIssue = 'https://github\&.com/VeriorPies/ParrelSync/issues'\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBExternalLinks\&.cs\fP\&.
.SS "const string ParrelSync\&.ExternalLinks\&.Releases = 'https://github\&.com/VeriorPies/ParrelSync/releases'\fC [static]\fP"

.PP
Definition at line \fB6\fP of file \fBExternalLinks\&.cs\fP\&.
.SS "const string ParrelSync\&.ExternalLinks\&.RemoteVersionURL = 'https://raw\&.githubusercontent\&.com/VeriorPies/ParrelSync/master/VERSION\&.txt'\fC [static]\fP"

.PP
Definition at line \fB5\fP of file \fBExternalLinks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
