.TH "ParrelSync.ClonesManagerWindow" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.ClonesManagerWindow \- Clones manager Unity editor window  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisCloneCreated\fP\fC [get]\fP"
.br
.RI "Returns true if project clone exists\&. "
.in -1c
.SH "Detailed Description"
.PP 
Clones manager Unity editor window 
.PP
Definition at line \fB10\fP of file \fBClonesManagerWindow\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ParrelSync\&.ClonesManagerWindow\&.isCloneCreated\fC [get]\fP"

.PP
Returns true if project clone exists\&. 
.PP
Definition at line \fB15\fP of file \fBClonesManagerWindow\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
