.TH "ParrelSync.ClonesManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.ClonesManager \- Contains all required methods for creating a linked clone of the Unity project\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBProject\fP \fBCreateCloneFromCurrent\fP ()"
.br
.RI "Creates clone from the project currently open in Unity Editor\&. "
.ti -1c
.RI "static \fBProject\fP \fBCreateCloneFromPath\fP (string sourceProjectPath)"
.br
.RI "Creates clone of the project located at the given path\&. "
.ti -1c
.RI "static void \fBOpenProject\fP (string projectPath)"
.br
.RI "Opens a project located at the given path (if one exists)\&. "
.ti -1c
.RI "static bool \fBIsCloneProjectRunning\fP (string projectPath)"
.br
.RI "Is this project being opened by an Unity editor? "
.ti -1c
.RI "static void \fBDeleteClone\fP (string cloneProjectPath)"
.br
.RI "Deletes the clone of the currently open project, if such exists\&. "
.ti -1c
.RI "static void \fBCreateProjectFolder\fP (\fBProject\fP project)"
.br
.RI "Creates an empty folder using data in the given \fBProject\fP object "
.ti -1c
.RI "static void \fBCopyLibraryFolder\fP (\fBProject\fP sourceProject, \fBProject\fP destinationProject)"
.br
.RI "Copies the full contents of the unity library\&. "
.ti -1c
.RI "static void \fBLinkFolders\fP (string sourcePath, string destinationPath)"
.br
.RI "Create a link / junction from the original project to it's clone\&. "
.ti -1c
.RI "static bool \fBIsClone\fP ()"
.br
.RI "Returns true if the project currently open in Unity Editor is a clone\&. "
.ti -1c
.RI "static string \fBGetCurrentProjectPath\fP ()"
.br
.RI "Get the path to the current unityEditor project folder's info "
.ti -1c
.RI "static \fBProject\fP \fBGetCurrentProject\fP ()"
.br
.RI "Return a project object that describes all the paths we need to clone it\&. "
.ti -1c
.RI "static string \fBGetArgument\fP ()"
.br
.RI "Get the argument of this clone project\&. "
.ti -1c
.RI "static string \fBGetOriginalProjectPath\fP ()"
.br
.RI "Returns the path to the original project\&. "
.ti -1c
.RI "static List< string > \fBGetCloneProjectsPath\fP ()"
.br
.RI "Returns all clone projects path\&. "
.ti -1c
.RI "static void \fBCopyDirectoryWithProgressBar\fP (string sourcePath, string destinationPath, string progressBarPrefix='')"
.br
.RI "Copies directory located at sourcePath to destinationPath\&. "
.ti -1c
.RI "static void \fBOpenProjectInFileExplorer\fP (string path)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBCloneFileName\fP = '\&.clone'"
.br
.RI "Name used for an identifying file created in the clone project directory\&. "
.ti -1c
.RI "const string \fBCloneNameSuffix\fP = '_clone'"
.br
.RI "Suffix added to the end of the project clone name when it is created\&. "
.ti -1c
.RI "const string \fBProjectName\fP = 'ParrelSync'"
.br
.ti -1c
.RI "const int \fBMaxCloneProjectCount\fP = 10"
.br
.RI "The maximum number of clones "
.ti -1c
.RI "const string \fBArgumentFileName\fP = '\&.parrelsyncarg'"
.br
.RI "Name of the file for storing clone's argument\&. "
.ti -1c
.RI "const string \fBDefaultArgument\fP = 'client'"
.br
.RI "Default argument of the new clone "
.in -1c
.SH "Detailed Description"
.PP 
Contains all required methods for creating a linked clone of the Unity project\&. 


.PP
Definition at line \fB14\fP of file \fBClonesManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ParrelSync\&.ClonesManager\&.CopyDirectoryWithProgressBar (string sourcePath, string destinationPath, string progressBarPrefix = \fC''\fP)\fC [static]\fP"

.PP
Copies directory located at sourcePath to destinationPath\&. Displays a progress bar\&. 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP Directory to be copied\&.
.br
\fIdestination\fP Destination directory (created automatically if needed)\&.
.br
\fIprogressBarPrefix\fP Optional string added to the beginning of the progress bar window header\&.
.RE
.PP

.PP
Definition at line \fB510\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.CopyLibraryFolder (\fBProject\fP sourceProject, \fBProject\fP destinationProject)\fC [static]\fP"

.PP
Copies the full contents of the unity library\&. We want to do this to avoid the lengthy re-serialization of the whole project when it opens up the clone\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourceProject\fP 
.br
\fIdestinationProject\fP 
.RE
.PP

.PP
Definition at line \fB294\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static \fBProject\fP ParrelSync\&.ClonesManager\&.CreateCloneFromCurrent ()\fC [static]\fP"

.PP
Creates clone from the project currently open in Unity Editor\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB55\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static \fBProject\fP ParrelSync\&.ClonesManager\&.CreateCloneFromPath (string sourceProjectPath)\fC [static]\fP"

.PP
Creates clone of the project located at the given path\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourceProjectPath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB72\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.CreateProjectFolder (\fBProject\fP project)\fC [static]\fP"

.PP
Creates an empty folder using data in the given \fBProject\fP object 
.PP
\fBParameters\fP
.RS 4
\fIproject\fP 
.RE
.PP

.PP
Definition at line \fB281\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.DeleteClone (string cloneProjectPath)\fC [static]\fP"

.PP
Deletes the clone of the currently open project, if such exists\&. Clone won't be able to delete itself\&.
.PP
Extra precautions\&.
.PP
Definition at line \fB220\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static string ParrelSync\&.ClonesManager\&.GetArgument ()\fC [static]\fP"

.PP
Get the argument of this clone project\&. If this is the original project, will return an empty string\&. 
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB440\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static List< string > ParrelSync\&.ClonesManager\&.GetCloneProjectsPath ()\fC [static]\fP"

.PP
Returns all clone projects path\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB489\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static \fBProject\fP ParrelSync\&.ClonesManager\&.GetCurrentProject ()\fC [static]\fP"

.PP
Return a project object that describes all the paths we need to clone it\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB429\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static string ParrelSync\&.ClonesManager\&.GetCurrentProjectPath ()\fC [static]\fP"

.PP
Get the path to the current unityEditor project folder's info 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB420\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static string ParrelSync\&.ClonesManager\&.GetOriginalProjectPath ()\fC [static]\fP"

.PP
Returns the path to the original project\&. If currently open project is the original, returns its own path\&. If the original project folder cannot be found, retuns an empty string\&. 
.PP
\fBReturns\fP
.RS 4
.RE
.PP
If this is a clone\&.\&.\&. Original project path can be deduced by removing the suffix from the clone's path\&.
.PP
If this is the original, we return its own path\&.
.PP
Definition at line \fB461\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static bool ParrelSync\&.ClonesManager\&.IsClone ()\fC [static]\fP"

.PP
Returns true if the project currently open in Unity Editor is a clone\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP
The project is a clone if its root directory contains an empty file named '\&.clone'\&.
.PP
Definition at line \fB404\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static bool ParrelSync\&.ClonesManager\&.IsCloneProjectRunning (string projectPath)\fC [static]\fP"

.PP
Is this project being opened by an Unity editor? 
.PP
\fBParameters\fP
.RS 4
\fIprojectPath\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB190\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.LinkFolders (string sourcePath, string destinationPath)\fC [static]\fP"

.PP
Create a link / junction from the original project to it's clone\&. 
.PP
\fBParameters\fP
.RS 4
\fIsourcePath\fP 
.br
\fIdestinationPath\fP 
.RE
.PP

.PP
Definition at line \fB368\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.OpenProject (string projectPath)\fC [static]\fP"

.PP
Opens a project located at the given path (if one exists)\&. 
.PP
\fBParameters\fP
.RS 4
\fIprojectPath\fP 
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBClonesManager\&.cs\fP\&.
.SS "static void ParrelSync\&.ClonesManager\&.OpenProjectInFileExplorer (string path)\fC [static]\fP"

.PP
Definition at line \fB662\fP of file \fBClonesManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string ParrelSync\&.ClonesManager\&.ArgumentFileName = '\&.parrelsyncarg'\fC [static]\fP"

.PP
Name of the file for storing clone's argument\&. 
.PP
Definition at line \fB42\fP of file \fBClonesManager\&.cs\fP\&.
.SS "const string ParrelSync\&.ClonesManager\&.CloneFileName = '\&.clone'\fC [static]\fP"

.PP
Name used for an identifying file created in the clone project directory\&. (!) Do not change this after the clone was created, because then connection will be lost\&. 
.PP
Definition at line \fB22\fP of file \fBClonesManager\&.cs\fP\&.
.SS "const string ParrelSync\&.ClonesManager\&.CloneNameSuffix = '_clone'\fC [static]\fP"

.PP
Suffix added to the end of the project clone name when it is created\&. (!) Do not change this after the clone was created, because then connection will be lost\&. 
.PP
Definition at line \fB30\fP of file \fBClonesManager\&.cs\fP\&.
.SS "const string ParrelSync\&.ClonesManager\&.DefaultArgument = 'client'\fC [static]\fP"

.PP
Default argument of the new clone 
.PP
Definition at line \fB47\fP of file \fBClonesManager\&.cs\fP\&.
.SS "const int ParrelSync\&.ClonesManager\&.MaxCloneProjectCount = 10\fC [static]\fP"

.PP
The maximum number of clones 
.PP
Definition at line \fB37\fP of file \fBClonesManager\&.cs\fP\&.
.SS "const string ParrelSync\&.ClonesManager\&.ProjectName = 'ParrelSync'\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBClonesManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
