.TH "ParrelSync.BoolPreference" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.BoolPreference \- To add value caching for EditorPrefs functions  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoolPreference\fP (string \fBkey\fP, bool \fBdefaultValue\fP)"
.br
.ti -1c
.RI "void \fBClearValue\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBkey\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBdefaultValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBValue\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
To add value caching for EditorPrefs functions 
.PP
Definition at line \fB9\fP of file \fBPreferences\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParrelSync\&.BoolPreference\&.BoolPreference (string key, bool defaultValue)"

.PP
Definition at line \fB13\fP of file \fBPreferences\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ParrelSync\&.BoolPreference\&.ClearValue ()"

.PP
Definition at line \fB41\fP of file \fBPreferences\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ParrelSync\&.BoolPreference\&.defaultValue\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBPreferences\&.cs\fP\&.
.SS "string ParrelSync\&.BoolPreference\&.key\fC [get]\fP"

.PP
Definition at line \fB11\fP of file \fBPreferences\&.cs\fP\&.
.SS "bool ParrelSync\&.BoolPreference\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB21\fP of file \fBPreferences\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
