.TH "ParrelSync.Update.UpdateChecker" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.Update.UpdateChecker \- A simple update checker  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBLocalVersion\fP = '1\&.5\&.1'"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple update checker 
.PP
Definition at line \fB9\fP of file \fBUpdateChecker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string ParrelSync\&.Update\&.UpdateChecker\&.LocalVersion = '1\&.5\&.1'\fC [static]\fP"

.PP
Definition at line \fB12\fP of file \fBUpdateChecker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
