.TH "ParrelSync" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBNonCore\fP"
.br
.ti -1c
.RI "namespace \fBUpdate\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoolPreference\fP"
.br
.RI "To add value caching for EditorPrefs functions "
.ti -1c
.RI "class \fBClonesManager\fP"
.br
.RI "Contains all required methods for creating a linked clone of the Unity project\&. "
.ti -1c
.RI "class \fBClonesManagerWindow\fP"
.br
.RI "Clones manager Unity editor window "
.ti -1c
.RI "class \fBEditorQuit\fP"
.br
.ti -1c
.RI "class \fBExternalLinks\fP"
.br
.ti -1c
.RI "class \fBFileUtilities\fP"
.br
.ti -1c
.RI "class \fBParrelSyncAssetModificationProcessor\fP"
.br
.RI "For preventing assets being modified from the clone instance\&. "
.ti -1c
.RI "class \fBPreferences\fP"
.br
.ti -1c
.RI "class \fBProject\fP"
.br
.ti -1c
.RI "class \fBValidateCopiedFoldersIntegrity\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
