.TH "ParrelSync.EditorQuit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.EditorQuit
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBIsQuiting\fP\fC [get]\fP"
.br
.RI "Is editor being closed "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBEditorQuit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ParrelSync\&.EditorQuit\&.IsQuiting\fC [static]\fP, \fC [get]\fP"

.PP
Is editor being closed 
.PP
Definition at line \fB10\fP of file \fBEditorQuit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
