.TH "ParrelSync.ParrelSyncAssetModificationProcessor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.ParrelSyncAssetModificationProcessor \- For preventing assets being modified from the clone instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.AssetModificationProcessor\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string[] \fBOnWillSaveAssets\fP (string[] paths)"
.br
.in -1c
.SH "Detailed Description"
.PP 
For preventing assets being modified from the clone instance\&. 


.PP
Definition at line \fB8\fP of file \fBParrelSyncAssetModificationProcessor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string[] ParrelSync\&.ParrelSyncAssetModificationProcessor\&.OnWillSaveAssets (string[] paths)\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBParrelSyncAssetModificationProcessor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
