.TH "ParrelSync.ValidateCopiedFoldersIntegrity" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.ValidateCopiedFoldersIntegrity
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBValidateFolder\fP (string targetRoot, string originalRoot, string folderName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBValidateCopiedFoldersIntegrity\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ParrelSync\&.ValidateCopiedFoldersIntegrity\&.ValidateFolder (string targetRoot, string originalRoot, string folderName)\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBValidateCopiedFoldersIntegrity\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
