.TH "ParrelSync.Project" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParrelSync.Project
.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.ICloneable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProject\fP ()"
.br
.RI "Default constructor "
.ti -1c
.RI "\fBProject\fP (string path)"
.br
.RI "Initialize the project object by parsing its full path returned by Unity into a bunch of individual folder names and paths\&. "
.ti -1c
.RI "object \fBClone\fP ()"
.br
.RI "Create a new object with the same settings "
.ti -1c
.RI "void \fBupdateNewName\fP (string newName)"
.br
.RI "\fBUpdate\fP the project object by renaming and reparsing it\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Debug override so we can quickly print out the project info\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBprojectPath\fP"
.br
.ti -1c
.RI "string \fBassetPath\fP"
.br
.ti -1c
.RI "string \fBprojectSettingsPath\fP"
.br
.ti -1c
.RI "string \fBlibraryPath\fP"
.br
.ti -1c
.RI "string \fBpackagesPath\fP"
.br
.ti -1c
.RI "string \fBautoBuildPath\fP"
.br
.ti -1c
.RI "string \fBlocalPackages\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBProject\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParrelSync\&.Project\&.Project ()"

.PP
Default constructor 
.PP
Definition at line \fB24\fP of file \fBProject\&.cs\fP\&.
.SS "ParrelSync\&.Project\&.Project (string path)"

.PP
Initialize the project object by parsing its full path returned by Unity into a bunch of individual folder names and paths\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP 
.RE
.PP

.PP
Definition at line \fB34\fP of file \fBProject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "object ParrelSync\&.Project\&.Clone ()"

.PP
Create a new object with the same settings 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB44\fP of file \fBProject\&.cs\fP\&.
.SS "override string ParrelSync\&.Project\&.ToString ()"

.PP
Debug override so we can quickly print out the project info\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB78\fP of file \fBProject\&.cs\fP\&.
.SS "void ParrelSync\&.Project\&.updateNewName (string newName)"

.PP
\fBUpdate\fP the project object by renaming and reparsing it\&. Pass in the new name of a project, and it'll update the other member variables to match\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP

.PP
Definition at line \fB67\fP of file \fBProject\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ParrelSync\&.Project\&.assetPath"

.PP
Definition at line \fB11\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.autoBuildPath"

.PP
Definition at line \fB15\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.libraryPath"

.PP
Definition at line \fB13\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.localPackages"

.PP
Definition at line \fB16\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.name"

.PP
Definition at line \fB8\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.packagesPath"

.PP
Definition at line \fB14\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.projectPath"

.PP
Definition at line \fB9\fP of file \fBProject\&.cs\fP\&.
.SS "string ParrelSync\&.Project\&.projectSettingsPath"

.PP
Definition at line \fB12\fP of file \fBProject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
