.TH "Photon.Pun.UtilityScripts.PhotonTeamsManagerEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PhotonTeamsManagerEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBRequiresConstantRepaint\fP ()"
.br
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBPhotonTeamsManagerInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManagerEditor\&.OnInspectorGUI ()"

.PP
Definition at line \fB83\fP of file \fBPhotonTeamsManagerInspector\&.cs\fP\&.
.SS "override bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManagerEditor\&.RequiresConstantRepaint ()"

.PP
Definition at line \fB35\fP of file \fBPhotonTeamsManagerInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
