.TH "Photon.Pun.Simple.AutoOwnerComponentEnable.ComponentToggle" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoOwnerComponentEnable.ComponentToggle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Behaviour \fBcomponent\fP"
.br
.ti -1c
.RI "\fBEnableIf\fP \fBenableIfOwned\fP = \fBEnableIf\&.Owner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Behaviour Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.ComponentToggle\&.component"

.PP
Definition at line \fB23\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "\fBEnableIf\fP Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.ComponentToggle\&.enableIfOwned = \fBEnableIf\&.Owner\fP"

.PP
Definition at line \fB24\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
