.TH "Photon.Pun.Simple.IVitalsSystem" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IVitalsSystem \- Object contains a \fBVitals\fP class reference\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IContactSystem\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVitals\fP \fBVitals\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Object contains a \fBVitals\fP class reference\&. 


.PP
Definition at line \fB13\fP of file \fBIVitalsSystem\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBVitals\fP Photon\&.Pun\&.Simple\&.IVitalsSystem\&.Vitals\fC [get]\fP"

.PP
Definition at line \fB15\fP of file \fBIVitalsSystem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
