.TH "Photon.Realtime.PingMono" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.PingMono \- Uses C# Socket class from System\&.Net\&.Sockets (as Unity usually does)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Realtime\&.PhotonPing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBStartPing\fP (string ip)"
.br
.RI "Sends a 'Photon Ping' to a server\&. "
.ti -1c
.RI "override bool \fBDone\fP ()"
.br
.ti -1c
.RI "override void \fBDispose\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Uses C# Socket class from System\&.Net\&.Sockets (as Unity usually does)\&. 

Incompatible with Windows 8 Store/Phone API\&.
.PP
Definition at line \fB86\fP of file \fBPhotonPing\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Realtime\&.PingMono\&.Dispose ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Realtime\&.PhotonPing\fP\&.
.PP
Definition at line \fB171\fP of file \fBPhotonPing\&.cs\fP\&.
.SS "override bool Photon\&.Realtime\&.PingMono\&.Done ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Realtime\&.PhotonPing\fP\&.
.PP
Definition at line \fB131\fP of file \fBPhotonPing\&.cs\fP\&.
.SS "override bool Photon\&.Realtime\&.PingMono\&.StartPing (string ip)\fC [virtual]\fP"

.PP
Sends a 'Photon Ping' to a server\&. 
.PP
\fBParameters\fP
.RS 4
\fIip\fP Address in IPv4 or IPv6 format\&. An address containing a '\&.' will be interpreted as IPv4\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the \fBPhoton\fP Ping could be sent\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Realtime\&.PhotonPing\fP\&.
.PP
Definition at line \fB95\fP of file \fBPhotonPing\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
