.TH "Photon.Compression.WorldBounds" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.WorldBounds \- Put this object on the root of a game map\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCollectMyBounds\fP ()"
.br
.ti -1c
.RI "void \fBFactorInBounds\fP (bool b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBworldBoundsGrp\fP"
.br
.ti -1c
.RI "Bounds \fBmyBounds\fP"
.br
.ti -1c
.RI "int \fBmyBoundsCount\fP"
.br
.ti -1c
.RI "System\&.Action \fBOnWorldBoundsChange\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Bounds \fBManualBounds\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBBoundsTools\&.BoundsType\fP \fBFactorIn\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Put this object on the root of a game map\&. 

It needs to encompass all of the areas the player is capable of moving to\&. The object must contain a MeshRenderer in order to get the bounds\&. 
.PP
Definition at line \fB24\fP of file \fBWorldBounds\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Compression\&.WorldBounds\&.CollectMyBounds ()"

.PP
Definition at line \fB76\fP of file \fBWorldBounds\&.cs\fP\&.
.SS "void Photon\&.Compression\&.WorldBounds\&.FactorInBounds (bool b)"

.PP
Definition at line \fB140\fP of file \fBWorldBounds\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Bounds Photon\&.Compression\&.WorldBounds\&.myBounds"

.PP
Definition at line \fB62\fP of file \fBWorldBounds\&.cs\fP\&.
.SS "int Photon\&.Compression\&.WorldBounds\&.myBoundsCount"

.PP
Definition at line \fB63\fP of file \fBWorldBounds\&.cs\fP\&.
.SS "System\&.Action Photon\&.Compression\&.WorldBounds\&.OnWorldBoundsChange"

.PP
Definition at line \fB67\fP of file \fBWorldBounds\&.cs\fP\&.
.SS "int Photon\&.Compression\&.WorldBounds\&.worldBoundsGrp"

.PP
Definition at line \fB42\fP of file \fBWorldBounds\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBBoundsTools\&.BoundsType\fP Photon\&.Compression\&.WorldBounds\&.FactorIn\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB52\fP of file \fBWorldBounds\&.cs\fP\&.
.SS "Bounds Photon\&.Compression\&.WorldBounds\&.ManualBounds\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB29\fP of file \fBWorldBounds\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
