.TH "Photon.Compression.FloatCrusherExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.FloatCrusherExtensions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, ref uint buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, ref ushort buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, ref byte buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, CompressedFloat c, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Inject() a previously compressed value into the supplied ulong buffer starting at the indicated bitposition\&. "
.ti -1c
.RI "static float \fBReadAndDecompress\fP (this FloatCrusher fc, ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Reads (deserialize) a compressed value from the buffer, decmpress, and return a restored float\&. "
.ti -1c
.RI "static CompressedFloat \fBRead\fP (this FloatCrusher fc, ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Reads (deserialize) a compressed value from the buffer, and returns a CompressedValue\&. "
.ti -1c
.RI "static CompressedFloat \fBRead\fP (this FloatCrusher fc, ref ulong buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Reads (deserialize) a compressed value from the buffer, and returns a CompressedValue\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, CompressedFloat c, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, CompressedFloat c, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, CompressedFloat c, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, uint c, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, uint c, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, uint c, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize a compressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize an uncompressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize an uncompressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBWrite\fP (this FloatCrusher fc, float f, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Serialize an uncompressed value to an array buffer using this FloatCrusher\&. "
.ti -1c
.RI "static CompressedFloat \fBRead\fP (this FloatCrusher fc, byte[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Deserializes a CompressedValue from an array buffer\&. "
.ti -1c
.RI "static CompressedFloat \fBRead\fP (this FloatCrusher fc, uint[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Deserializes a CompressedValue from an array buffer\&. "
.ti -1c
.RI "static CompressedFloat \fBRead\fP (this FloatCrusher fc, ulong[] buffer, ref int bitposition, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.RI "Deserializes a CompressedValue from an array buffer\&. "
.ti -1c
.RI "static float \fBReadAndDecompress\fP (this FloatCrusher fc, byte[] buffer, ref int bitposition)"
.br
.RI "Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. "
.ti -1c
.RI "static float \fBReadAndDecompress\fP (this FloatCrusher fc, uint[] buffer, ref int bitposition)"
.br
.RI "Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. "
.ti -1c
.RI "static float \fBReadAndDecompress\fP (this FloatCrusher fc, ulong[] buffer, ref int bitposition)"
.br
.RI "Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Read (this FloatCrusher fc, byte[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Deserializes a CompressedValue from an array buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP Auto-incremented read position for buffer\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB299\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Read (this FloatCrusher fc, ref ulong buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Reads (deserialize) a compressed value from the buffer, and returns a CompressedValue\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source buffer to read from\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer\&. Will begin reading bits from this position\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB136\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Read (this FloatCrusher fc, uint[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Deserializes a CompressedValue from an array buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP Auto-incremented read position for buffer\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB311\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Read (this FloatCrusher fc, ulong buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Reads (deserialize) a compressed value from the buffer, and returns a CompressedValue\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source buffer to read from\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer\&. Will begin reading bits from this position\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB122\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Read (this FloatCrusher fc, ulong[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Deserializes a CompressedValue from an array buffer\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP Auto-incremented read position for buffer\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB323\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.FloatCrusherExtensions\&.ReadAndDecompress (this FloatCrusher fc, byte[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.RE
.PP
\fBReturns\fP
.RS 4
Restored float value\&.
.RE
.PP

.PP
Definition at line \fB335\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.FloatCrusherExtensions\&.ReadAndDecompress (this FloatCrusher fc, uint[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.RE
.PP
\fBReturns\fP
.RS 4
Restored float value\&.
.RE
.PP

.PP
Definition at line \fB346\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.FloatCrusherExtensions\&.ReadAndDecompress (this FloatCrusher fc, ulong buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Reads (deserialize) a compressed value from the buffer, decmpress, and return a restored float\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source buffer to read from\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer\&. Will begin reading bits from this position\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB106\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.FloatCrusherExtensions\&.ReadAndDecompress (this FloatCrusher fc, ulong[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Deserializes a compressed (encoded) float out of an array from the indicated bitpostion, and Decode() it\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source array buffer\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.RE
.PP
\fBReturns\fP
.RS 4
Restored float value\&.
.RE
.PP

.PP
Definition at line \fB357\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, CompressedFloat c, byte[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB159\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, CompressedFloat c, ref ulong buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Inject() a previously compressed value into the supplied ulong buffer starting at the indicated bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP Compressed value to be written
.br
\fIbuffer\fP Where the bits will be written
.br
\fIbitposition\fP The position in the buffer to start writing at\&. Ref value will be increased by the bits used\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the compressed uint that was serialized\&.
.RE
.PP

.PP
Definition at line \fB88\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, CompressedFloat c, uint[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB175\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, CompressedFloat c, ulong[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB189\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, byte[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize an uncompressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Uncompressed float
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB249\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, ref byte buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to be compressed and serialized
.br
\fIbuffer\fP Target primitive buffer to serialize into\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the compressed uint that was serialized\&.
.RE
.PP

.PP
Definition at line \fB72\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, ref uint buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to be compressed and serialized
.br
\fIbuffer\fP Target primitive buffer to serialize into\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the compressed uint that was serialized\&.
.RE
.PP

.PP
Definition at line \fB40\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, ref ulong buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to be compressed and serialized
.br
\fIbuffer\fP Target primitive buffer to serialize into\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the compressed uint that was serialized\&.
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, ref ushort buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Compress (encode) a float value using this FloatCrusher, then Inject() that compressed value into the supplied buffer starting at the indicated bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to be compressed and serialized
.br
\fIbuffer\fP Target primitive buffer to serialize into\&.
.br
\fIbitposition\fP The auto-incremented position in the array (in bits) where we will begin reading\&.
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Returns the compressed uint that was serialized\&.
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, uint[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize an uncompressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Uncompressed float
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB264\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, float f, ulong[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize an uncompressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Uncompressed float
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB280\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, uint c, byte[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB204\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, uint c, uint[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB219\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.
.SS "static CompressedFloat Photon\&.Compression\&.FloatCrusherExtensions\&.Write (this FloatCrusher fc, uint c, ulong[] buffer, ref int bitposition, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Serialize a compressed value to an array buffer using this FloatCrusher\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP CompressedValue
.br
\fIbuffer\fP 
.br
\fIbitposition\fP 
.br
\fIbcl\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB234\fP of file \fBFloatCrusherExtensions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
