.TH "Photon" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBChat\fP"
.br
.ti -1c
.RI "namespace \fBCompression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.ti -1c
.RI "namespace \fBPun\fP"
.br
.ti -1c
.RI "namespace \fBRealtime\fP"
.br
.ti -1c
.RI "namespace \fBUtilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
