.TH "Photon.Realtime.ILobbyCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.ILobbyCallbacks \- Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover the Lobby\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, Photon\&.Realtime\&.LobbyCallbacksContainer, and \fBPhoton\&.Realtime\&.SupportLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnJoinedLobby\fP ()"
.br
.RI "Called on entering a lobby on the Master Server\&. "
.ti -1c
.RI "void \fBOnLeftLobby\fP ()"
.br
.RI "Called after leaving a lobby\&. "
.ti -1c
.RI "void \fBOnRoomListUpdate\fP (List< \fBRoomInfo\fP > roomList)"
.br
.RI "Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. "
.ti -1c
.RI "void \fBOnLobbyStatisticsUpdate\fP (List< \fBTypedLobbyInfo\fP > lobbyStatistics)"
.br
.RI "Called when the Master Server sent an update for the Lobby Statistics\&. "
.in -1c
.SH "Detailed Description"
.PP 
Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover the Lobby\&. 

Classes that implement this interface must be registered to get callbacks for various situations\&.
.PP
To register for callbacks, call \fBLoadBalancingClient\&.AddCallbackTarget\fP and pass the class implementing this interface To stop getting callbacks, call \fBLoadBalancingClient\&.RemoveCallbackTarget\fP and pass the class implementing this interface
.PP
Definition at line \fB3690\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.ILobbyCallbacks\&.OnJoinedLobby ()"

.PP
Called on entering a lobby on the Master Server\&. The actual room-list updates will call OnRoomListUpdate\&. 
.PP
While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud)\&. The room list gets available via OnRoomListUpdate\&. 
.PP
Implemented in \fBLauncher\fP, \fBLauncher_old\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP, and \fBPhoton\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\fP\&.
.SS "void Photon\&.Realtime\&.ILobbyCallbacks\&.OnLeftLobby ()"

.PP
Called after leaving a lobby\&. When you leave a lobby, \fBOpCreateRoom\fP and \fBOpJoinRandomRoom\fP automatically refer to the default lobby\&. 
.PP
Implemented in \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, and \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP\&.
.SS "void Photon\&.Realtime\&.ILobbyCallbacks\&.OnLobbyStatisticsUpdate (List< \fBTypedLobbyInfo\fP > lobbyStatistics)"

.PP
Called when the Master Server sent an update for the Lobby Statistics\&. This callback has two preconditions: EnableLobbyStatistics must be set to true, before this client connects\&. And the client has to be connected to the Master Server, which is providing the info about lobbies\&. 
.PP
Implemented in \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, and \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "void Photon\&.Realtime\&.ILobbyCallbacks\&.OnRoomListUpdate (List< \fBRoomInfo\fP > roomList)"

.PP
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. Each item is a \fBRoomInfo\fP which might include custom properties (provided you defined those as lobby-listed when creating a room)\&. Not all types of lobbies provide a listing of rooms to the client\&. Some are silent and specialized for server-side matchmaking\&. 
.PP
Implemented in \fBLauncher\fP, \fBLauncher_old\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, and \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.RoomListView\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
