.TH "Photon.Pun.Demo.Cockpit.ToggleExpand" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.ToggleExpand \- UI toggle to activate GameObject\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBContent\fP"
.br
.ti -1c
.RI "Toggle \fBToggle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UI toggle to activate GameObject\&. 


.PP
Definition at line \fB16\fP of file \fBToggleExpand\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.ToggleExpand\&.Content"

.PP
Definition at line \fB18\fP of file \fBToggleExpand\&.cs\fP\&.
.SS "Toggle Photon\&.Pun\&.Demo\&.Cockpit\&.ToggleExpand\&.Toggle"

.PP
Definition at line \fB20\fP of file \fBToggleExpand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
