.TH "Photon.Pun.Simple.IOnJoinedRoom" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnJoinedRoom
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnJoinedRoom\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBNetObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnJoinedRoom\&.OnJoinedRoom ()"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.AutoOwnerComponentEnable\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, and \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
