.TH "Photon.Pun.Simple.ContactGroups" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContactGroupAssign\fP"
.br
.ti -1c
.RI "struct \fBContactGroupMaskSelector\fP"
.br
.ti -1c
.RI "struct \fBContactGroupSelector\fP"
.br
.ti -1c
.RI "class \fBContactGroupSettings\fP"
.br
.ti -1c
.RI "class \fBContactGroupValues\fP"
.br
.ti -1c
.RI "interface \fBIContactGroupMask\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
