.TH "Photon.Pun.Simple.Internal.NetObjColliderExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Internal.NetObjColliderExt \- \fBUtilities\fP for finding/indexing Colliders on a \fBNetObject\fP  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBIndexColliders\fP (this \fBNetObject\fP netObj)"
.br
.RI "Finds all active and inactive colliders on an object "
.ti -1c
.RI "static int \fBGetFirstChildCollider\fP (this Transform transform, ref Component firstFoundCollider, bool countTriggers, bool countNonTriggers)"
.br
.RI "Finds the first child collider or collider 2D\&. "
.ti -1c
.RI "static int \fBCountChildCollider\fP (this Transform transform, bool countTriggers, bool countNonTriggers)"
.br
.RI "Finds the first child collider or collider 2D\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly List< Component > \fBreusableComponents\fP = new List<Component>()"
.br
.ti -1c
.RI "static readonly List< Collider > \fBreusableColliders\fP = new List<Collider>()"
.br
.ti -1c
.RI "static readonly List< Collider2D > \fBreusableColliders2D\fP = new List<Collider2D>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBUtilities\fP for finding/indexing Colliders on a \fBNetObject\fP 
.PP
Definition at line \fB15\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.CountChildCollider (this Transform transform, bool countTriggers, bool countNonTriggers)\fC [static]\fP"

.PP
Finds the first child collider or collider 2D\&. Retuns the count of colliders found\&. First try 3d
.PP
None found, try 2D
.PP
None found, return 0
.PP
Definition at line \fB141\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.GetFirstChildCollider (this Transform transform, ref Component firstFoundCollider, bool countTriggers, bool countNonTriggers)\fC [static]\fP"

.PP
Finds the first child collider or collider 2D\&. Retuns the count of colliders found\&. First try 3d
.PP
None found, try 2D
.PP
None found, return null and 0
.PP
Definition at line \fB65\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.IndexColliders (this \fBNetObject\fP netObj)\fC [static]\fP"

.PP
Finds all active and inactive colliders on an object 
.PP
\fBParameters\fP
.RS 4
\fInetObj\fP 
.RE
.PP
Check each component to see if it is a Collider/Collider2D
.PP
Populate the lookup with the found colliders
.PP
Definition at line \fB25\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly List<Collider> Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.reusableColliders = new List<Collider>()\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SS "readonly List<Collider2D> Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.reusableColliders2D = new List<Collider2D>()\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBNetObjColliderExt\&.cs\fP\&.
.SS "readonly List<Component> Photon\&.Pun\&.Simple\&.Internal\&.NetObjColliderExt\&.reusableComponents = new List<Component>()\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBNetObjColliderExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
