.TH "Photon.Compression.IOnElementCrusherChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.IOnElementCrusherChange
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCrusherChange\fP (\fBElementCrusher\fP ec)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBElementCrusher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Compression\&.IOnElementCrusherChange\&.OnCrusherChange (\fBElementCrusher\fP ec)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
