.TH "Photon.Pun.Demo.Asteroids.RoomListEntry" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids.RoomListEntry
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (string name, byte currentPlayers, byte maxPlayers)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBRoomNameText\fP"
.br
.ti -1c
.RI "Text \fBRoomPlayersText\fP"
.br
.ti -1c
.RI "Button \fBJoinRoomButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBRoomListEntry\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.RoomListEntry\&.Initialize (string name, byte currentPlayers, byte maxPlayers)"

.PP
Definition at line \fB27\fP of file \fBRoomListEntry\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.RoomListEntry\&.Start ()"

.PP
Definition at line \fB14\fP of file \fBRoomListEntry\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Button Photon\&.Pun\&.Demo\&.Asteroids\&.RoomListEntry\&.JoinRoomButton"

.PP
Definition at line \fB10\fP of file \fBRoomListEntry\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Asteroids\&.RoomListEntry\&.RoomNameText"

.PP
Definition at line \fB8\fP of file \fBRoomListEntry\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Asteroids\&.RoomListEntry\&.RoomPlayersText"

.PP
Definition at line \fB9\fP of file \fBRoomListEntry\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
