.TH "Photon.Pun.Simple.MountsManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.MountsManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, \fBPhoton\&.Pun\&.Simple\&.IOnAwake\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreQuit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnPreQuit\fP ()"
.br
.ti -1c
.RI "List< \fBMount\fP > \fBCollectMounts\fP (bool force=false)"
.br
.RI "Adds all child mounts to the lookup collections\&. "
.ti -1c
.RI "\fBMount\fP \fBGetMount\fP (int mountId)"
.br
.ti -1c
.RI "void \fBUnmountAll\fP ()"
.br
.RI "Force all mounted objects to dismount\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBMount\fP > \fBmountIdLookup\fP = new Dictionary<int, \fBMount\fP>()"
.br
.ti -1c
.RI "List< \fBMount\fP > \fBindexedMounts\fP = new List<\fBMount\fP>()"
.br
.ti -1c
.RI "int \fBbitsForMountId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBMountsManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "List< \fBMount\fP > Photon\&.Pun\&.Simple\&.MountsManager\&.CollectMounts (bool force = \fCfalse\fP)"

.PP
Adds all child mounts to the lookup collections\&. 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB103\fP of file \fBMountsManager\&.cs\fP\&.
.SS "\fBMount\fP Photon\&.Pun\&.Simple\&.MountsManager\&.GetMount (int mountId)"

.PP
Definition at line \fB129\fP of file \fBMountsManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountsManager\&.OnAwake ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnAwake\fP\&.
.PP
Definition at line \fB88\fP of file \fBMountsManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountsManager\&.OnPreQuit ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreQuit\fP\&.
.PP
Definition at line \fB94\fP of file \fBMountsManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountsManager\&.UnmountAll ()"

.PP
Force all mounted objects to dismount\&. 
.PP
Definition at line \fB139\fP of file \fBMountsManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.MountsManager\&.bitsForMountId"

.PP
Definition at line \fB26\fP of file \fBMountsManager\&.cs\fP\&.
.SS "List<\fBMount\fP> Photon\&.Pun\&.Simple\&.MountsManager\&.indexedMounts = new List<\fBMount\fP>()"

.PP
Definition at line \fB25\fP of file \fBMountsManager\&.cs\fP\&.
.SS "Dictionary<int, \fBMount\fP> Photon\&.Pun\&.Simple\&.MountsManager\&.mountIdLookup = new Dictionary<int, \fBMount\fP>()"

.PP
Definition at line \fB24\fP of file \fBMountsManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
