.TH "Photon.Compression.ArrayPackBytesExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ArrayPackBytesExt \- Experimental packers, that counts number of used bits for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsafe void \fBWritePackedBytes\fP (ulong *uPtr, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE Write Method\&. "
.ti -1c
.RI "static void \fBWritePackedBytes\fP (this ulong[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static void \fBWritePackedBytes\fP (this uint[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static void \fBWritePackedBytes\fP (this byte[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static unsafe ulong \fBReadPackedBytes\fP (ulong *uPtr, ref int bitposition, int bits)"
.br
.RI "Primary UNSAFE Reader for PackedBytes\&. "
.ti -1c
.RI "static ulong \fBReadPackedBytes\fP (this ulong[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBytes\&. "
.ti -1c
.RI "static ulong \fBReadPackedBytes\fP (this uint[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBytes\&. "
.ti -1c
.RI "static ulong \fBReadPackedBytes\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBytes\&. "
.ti -1c
.RI "static unsafe void \fBWriteSignedPackedBytes\fP (ulong *uPtr, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE Write signed value as PackedByte\&. "
.ti -1c
.RI "static unsafe int \fBReadSignedPackedBytes\fP (ulong *uPtr, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE Read signed value from PackedByte\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBytes\fP (this ulong[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write signed value as PackedByte\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBytes\fP (this ulong[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Read signed value from PackedByte\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBytes\fP (this uint[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write signed value as PackedByte\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBytes\fP (this uint[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Read signed value from PackedByte\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBytes\fP (this byte[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write signed value as PackedByte\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBytes\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Read signed value from PackedByte\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBytes64\fP (this byte[] buffer, long value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write signed value as PackedByte\&. "
.ti -1c
.RI "static long \fBReadSignedPackedBytes64\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Read signed value from PackedByte\&. "
.in -1c
.SH "Detailed Description"
.PP 
Experimental packers, that counts number of used bits for serialization\&. 

Effective for values that hover close to zero\&. 
.PP
Definition at line \fB34\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static ulong Photon\&.Compression\&.ArrayPackBytesExt\&.ReadPackedBytes (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBytes\&. 
.PP
Definition at line \fB158\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArrayPackBytesExt\&.ReadPackedBytes (this uint[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBytes\&. 
.PP
Definition at line \fB145\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArrayPackBytesExt\&.ReadPackedBytes (this ulong[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBytes\&. 
.PP
Definition at line \fB132\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static unsafe ulong Photon\&.Compression\&.ArrayPackBytesExt\&.ReadPackedBytes (ulong * uPtr, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary UNSAFE Reader for PackedBytes\&. 
.PP
Definition at line \fB119\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBytesExt\&.ReadSignedPackedBytes (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Read signed value from PackedByte\&. 
.PP
Definition at line \fB246\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBytesExt\&.ReadSignedPackedBytes (this uint[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Read signed value from PackedByte\&. 
.PP
Definition at line \fB226\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBytesExt\&.ReadSignedPackedBytes (this ulong[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Read signed value from PackedByte\&. 
.PP
Definition at line \fB206\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static unsafe int Photon\&.Compression\&.ArrayPackBytesExt\&.ReadSignedPackedBytes (ulong * uPtr, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE Read signed value from PackedByte\&. 
.PP
Definition at line \fB186\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static long Photon\&.Compression\&.ArrayPackBytesExt\&.ReadSignedPackedBytes64 (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Read signed value from PackedByte\&. 
.PP
Definition at line \fB264\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WritePackedBytes (this byte[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB96\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WritePackedBytes (this uint[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB78\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WritePackedBytes (this ulong[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB60\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static unsafe void Photon\&.Compression\&.ArrayPackBytesExt\&.WritePackedBytes (ulong * uPtr, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE Write Method\&. 
.PP
Definition at line \fB41\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WriteSignedPackedBytes (this byte[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write signed value as PackedByte\&. 
.PP
Definition at line \fB238\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WriteSignedPackedBytes (this uint[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write signed value as PackedByte\&. 
.PP
Definition at line \fB218\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WriteSignedPackedBytes (this ulong[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write signed value as PackedByte\&. 
.PP
Definition at line \fB198\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static unsafe void Photon\&.Compression\&.ArrayPackBytesExt\&.WriteSignedPackedBytes (ulong * uPtr, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE Write signed value as PackedByte\&. 
.PP
Definition at line \fB178\fP of file \fBArrayPackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBytesExt\&.WriteSignedPackedBytes64 (this byte[] buffer, long value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write signed value as PackedByte\&. 
.PP
Definition at line \fB256\fP of file \fBArrayPackBytesExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
