.TH "Photon.Pun.PhotonGUI" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonGUI
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBContainerHeader\fP (string headline)"
.br
.ti -1c
.RI "static bool \fBContainerHeaderToggle\fP (string headline, bool toggle)"
.br
.ti -1c
.RI "static bool \fBContainerHeaderFoldout\fP (string headline, bool foldout, System\&.Action buttonAction=null, string buttonName=null)"
.br
.ti -1c
.RI "static Rect \fBContainerBody\fP (float height)"
.br
.ti -1c
.RI "static bool \fBAddButton\fP ()"
.br
.ti -1c
.RI "static void \fBDrawSplitter\fP (Rect position)"
.br
.ti -1c
.RI "static void \fBDrawGizmoOptions\fP (Rect position, string label, SerializedProperty gizmoEnabledProperty, SerializedProperty gizmoColorProperty, SerializedProperty gizmoTypeProperty, SerializedProperty gizmoSizeProperty)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static GUIStyle? \fBDefaultTitleStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBDefaultContainerStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBDefaultAddButtonStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBDefaultRemoveButtonStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBDefaultContainerRowStyle\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBFoldoutBold\fP\fC [get]\fP"
.br
.ti -1c
.RI "static GUIStyle \fBRichLabel\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Texture2D \fBHelpIcon\fP\fC [get]\fP"
.br
.ti -1c
.RI "static Texture2D \fBCopyIcon\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBPhotonGUI\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Photon\&.Pun\&.PhotonGUI\&.AddButton ()\fC [static]\fP"

.PP
Definition at line \fB239\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static Rect Photon\&.Pun\&.PhotonGUI\&.ContainerBody (float height)\fC [static]\fP"

.PP
Definition at line \fB234\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonGUI\&.ContainerHeader (string headline)\fC [static]\fP"

.PP
Definition at line \fB219\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.PhotonGUI\&.ContainerHeaderFoldout (string headline, bool foldout, System\&.Action buttonAction = \fCnull\fP, string buttonName = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line \fB229\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.PhotonGUI\&.ContainerHeaderToggle (string headline, bool toggle)\fC [static]\fP"

.PP
Definition at line \fB224\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonGUI\&.DrawGizmoOptions (Rect position, string label, SerializedProperty gizmoEnabledProperty, SerializedProperty gizmoColorProperty, SerializedProperty gizmoTypeProperty, SerializedProperty gizmoSizeProperty)\fC [static]\fP"

.PP
Definition at line \fB258\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonGUI\&.DrawSplitter (Rect position)\fC [static]\fP"

.PP
Definition at line \fB253\fP of file \fBPhotonGUI\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Texture2D Photon\&.Pun\&.PhotonGUI\&.CopyIcon\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB194\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.DefaultAddButtonStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB65\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.DefaultContainerRowStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB104\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.DefaultContainerStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB46\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.DefaultRemoveButtonStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB84\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle? Photon\&.Pun\&.PhotonGUI\&.DefaultTitleStyle\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB23\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.FoldoutBold\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB124\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "Texture2D Photon\&.Pun\&.PhotonGUI\&.HelpIcon\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB176\fP of file \fBPhotonGUI\&.cs\fP\&.
.SS "GUIStyle Photon\&.Pun\&.PhotonGUI\&.RichLabel\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB140\fP of file \fBPhotonGUI\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
