.TH "Photon.Pun.Simple.VitalData" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.VitalData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVitalData\fP (double value, int \fBticksUntilDecay\fP, int \fBticksUntilRegen\fP)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBticksUntilRegen\fP"
.br
.ti -1c
.RI "int \fBticksUntilDecay\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBValue\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBVitalData\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.VitalData\&.VitalData (double value, int ticksUntilDecay, int ticksUntilRegen)"

.PP
Definition at line \fB43\fP of file \fBVitalData\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.VitalData\&.ToString ()"

.PP
Definition at line \fB51\fP of file \fBVitalData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.VitalData\&.ticksUntilDecay"

.PP
Definition at line \fB37\fP of file \fBVitalData\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.VitalData\&.ticksUntilRegen"

.PP
Definition at line \fB36\fP of file \fBVitalData\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "double Photon\&.Pun\&.Simple\&.VitalData\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB32\fP of file \fBVitalData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
