.TH "Photon.Pun.Simple.TeleportMarker" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.TeleportMarker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTeleportMarker\fP \fBGetRandomMarker\fP (int hash, float seed)"
.br
.ti -1c
.RI "static \fBTeleportMarker\fP \fBGetNextMarker\fP (int hash)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMarkerNameType\fP \fBmarkerType\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< int, List< \fBTeleportMarker\fP > > \fBlookup\fP = new Dictionary<int, List<\fBTeleportMarker\fP>>()"
.br
.ti -1c
.RI "static Dictionary< int, int > \fBnexts\fP = new Dictionary<int, int>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBTeleportMarker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTeleportMarker\fP Photon\&.Pun\&.Simple\&.TeleportMarker\&.GetNextMarker (int hash)\fC [static]\fP"

.PP
Definition at line \fB59\fP of file \fBTeleportMarker\&.cs\fP\&.
.SS "static \fBTeleportMarker\fP Photon\&.Pun\&.Simple\&.TeleportMarker\&.GetRandomMarker (int hash, float seed)\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBTeleportMarker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, List<\fBTeleportMarker\fP> > Photon\&.Pun\&.Simple\&.TeleportMarker\&.lookup = new Dictionary<int, List<\fBTeleportMarker\fP>>()\fC [static]\fP"

.PP
Definition at line \fB46\fP of file \fBTeleportMarker\&.cs\fP\&.
.SS "\fBMarkerNameType\fP Photon\&.Pun\&.Simple\&.TeleportMarker\&.markerType"

.PP
Definition at line \fB17\fP of file \fBTeleportMarker\&.cs\fP\&.
.SS "Dictionary<int, int> Photon\&.Pun\&.Simple\&.TeleportMarker\&.nexts = new Dictionary<int, int>()\fC [static]\fP"

.PP
Definition at line \fB47\fP of file \fBTeleportMarker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
