.TH "Photon.Pun.Simple.IOnPostUpdate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPostUpdate \- Callback Interface for \fBOnPostUpdate()\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostUpdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPostUpdate()\fP\&. 

Called after all normal Update() calls in MonoBehaviours\&. 
.PP
Definition at line \fB28\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPostUpdate\&.OnPostUpdate ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
