.TH "Photon.Pun.Demo.Asteroids.AsteroidsGameManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids.AsteroidsGameManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "override void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. "
.ti -1c
.RI "override void \fBOnMasterClientSwitched\fP (\fBPlayer\fP newMasterClient)"
.br
.RI "Called after switching to a new MasterClient when the current one leaves\&. "
.ti -1c
.RI "override void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP otherPlayer)"
.br
.RI "Called when a remote player left the room or became inactive\&. "
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"
.br
.RI "Called when custom player-properties are changed\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBInfoText\fP"
.br
.ti -1c
.RI "GameObject[] \fBAsteroidPrefabs\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBAsteroidsGameManager\fP \fBInstance\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.Awake ()"

.PP
Definition at line \fB32\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnDisable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB53\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnDisconnected (\fBDisconnectCause\fP cause)\fC [virtual]\fP"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. It could be a failure or intentional 
.PP
The reason for this disconnect is provided as DisconnectCause\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB116\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB37\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnLeftRoom ()\fC [virtual]\fP"

.PP
Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server\&. This wraps up multiple internal actions\&.
.PP
Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB121\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnMasterClientSwitched (\fBPlayer\fP newMasterClient)\fC [virtual]\fP"

.PP
Called after switching to a new MasterClient when the current one leaves\&. This is not called when this client enters a room\&. The former MasterClient is still in the player list when this method get called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB126\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnPlayerLeftRoom (\fBPlayer\fP otherPlayer)\fC [virtual]\fP"

.PP
Called when a remote player left the room or became inactive\&. Check otherPlayer\&.IsInactive\&. 
.PP
If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic\&.
.PP
Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room\&. In such cases, the Player stays in the \fBRoom\&.Players\fP dictionary\&.
.PP
If the player is not just inactive, it gets removed from the \fBRoom\&.Players\fP dictionary, before the callback is called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB134\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)\fC [virtual]\fP"

.PP
Called when custom player-properties are changed\&. Player and the changed properties are passed as object[]\&. 
.PP
Changing properties must be done by \fBPlayer\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetPlayer\fP Contains Player that changed\&.
.br
\fIchangedProps\fP Contains the properties that changed\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB139\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.Start ()"

.PP
Definition at line \fB44\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject [] Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.AsteroidPrefabs"

.PP
Definition at line \fB28\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.InfoText"

.PP
Definition at line \fB26\fP of file \fBAsteroidsGameManager\&.cs\fP\&.
.SS "\fBAsteroidsGameManager\fP Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\&.Instance = null\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBAsteroidsGameManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
