.TH "Photon.Pun.UtilityScripts.OnClickRpc" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.OnClickRpc \- This component will instantiate a network GameObject when in a room and the user click on that component's GameObject\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClickRpc\fP ()"
.br
.ti -1c
.RI "IEnumerator \fBClickFlash\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PointerEventData\&.InputButton \fBButton\fP"
.br
.ti -1c
.RI "KeyCode \fBModifierKey\fP"
.br
.ti -1c
.RI "\fBRpcTarget\fP \fBTarget\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This component will instantiate a network GameObject when in a room and the user click on that component's GameObject\&. 

Uses PhysicsRaycaster for positioning\&. 
.PP
Definition at line \fB23\fP of file \fBOnClickRpc\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator Photon\&.Pun\&.UtilityScripts\&.OnClickRpc\&.ClickFlash ()"

.PP
Definition at line \fB54\fP of file \fBOnClickRpc\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.OnClickRpc\&.ClickRpc ()"

.PP
Definition at line \fB48\fP of file \fBOnClickRpc\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PointerEventData\&.InputButton Photon\&.Pun\&.UtilityScripts\&.OnClickRpc\&.Button"

.PP
Definition at line \fB25\fP of file \fBOnClickRpc\&.cs\fP\&.
.SS "KeyCode Photon\&.Pun\&.UtilityScripts\&.OnClickRpc\&.ModifierKey"

.PP
Definition at line \fB26\fP of file \fBOnClickRpc\&.cs\fP\&.
.SS "\fBRpcTarget\fP Photon\&.Pun\&.UtilityScripts\&.OnClickRpc\&.Target"

.PP
Definition at line \fB28\fP of file \fBOnClickRpc\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
