.TH "Photon.Utilities.FastBitMaskExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.FastBitMaskExt
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB505\fP of file \fBFastBitMask128\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
