.TH "Photon.Pun.PhotonTransformViewRotationModel" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewRotationModel
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInterpolateOptions\fP { \fBDisabled\fP, \fBRotateTowards\fP, \fBLerp\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBSynchronizeEnabled\fP"
.br
.ti -1c
.RI "\fBInterpolateOptions\fP \fBInterpolateOption\fP = \fBInterpolateOptions\&.RotateTowards\fP"
.br
.ti -1c
.RI "float \fBInterpolateRotateTowardsSpeed\fP = 180"
.br
.ti -1c
.RI "float \fBInterpolateLerpSpeed\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB418\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.PhotonTransformViewRotationModel\&.InterpolateOptions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fIRotateTowards \fP\fP
.TP
\fB\fILerp \fP\fP
.PP
Definition at line \fB420\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.PhotonTransformViewRotationModel\&.InterpolateLerpSpeed = 5"

.PP
Definition at line \fB432\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "\fBInterpolateOptions\fP Photon\&.Pun\&.PhotonTransformViewRotationModel\&.InterpolateOption = \fBInterpolateOptions\&.RotateTowards\fP"

.PP
Definition at line \fB430\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewRotationModel\&.InterpolateRotateTowardsSpeed = 180"

.PP
Definition at line \fB431\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformViewRotationModel\&.SynchronizeEnabled"

.PP
Definition at line \fB428\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
