.TH "Photon.Pun.Demo.Cockpit.Forms" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.Forms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnectToRegionUIForm\fP"
.br
.RI "Manager for ConnectToRegion UI Form "
.ti -1c
.RI "class \fBCreateRoomUiForm\fP"
.br
.RI "Create room user interface form\&. "
.ti -1c
.RI "class \fBLoadLevelUIForm\fP"
.br
.RI "Level Loading UI Form\&. "
.ti -1c
.RI "class \fBSetRoomCustomPropertyUIForm\fP"
.br
.RI "Room custom properties UI Form\&. "
.ti -1c
.RI "class \fBUserIdUiForm\fP"
.br
.RI "User Id UI form\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
