.TH "Photon.Compression.PrimitiveSerializeExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.PrimitiveSerializeExt \- Extension methods for writing bits to primitive buffers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInject\fP (this \fBByteConverter\fP value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this \fBByteConverter\fP value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this \fBByteConverter\fP value, ref ushort buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this \fBByteConverter\fP value, ref byte buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static ulong \fBWriteSigned\fP (this ulong buffer, int value, ref int bitposition, int bits)"
.br
.RI "Write a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this long value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this int value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this short value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this sbyte value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static int \fBReadSigned\fP (this ulong buffer, ref int bitposition, int bits)"
.br
.RI "Read a previously injected signed int back out of a buffer\&. "
.ti -1c
.RI "static uint \fBWriteSigned\fP (this uint buffer, int value, ref int bitposition, int bits)"
.br
.RI "Write a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this long value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this int value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this short value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this sbyte value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static int \fBReadSigned\fP (this uint buffer, ref int bitposition, int bits)"
.br
.RI "Read a previously injected signed int back out of a buffer\&. "
.ti -1c
.RI "static ushort \fBWriteSigned\fP (this ushort buffer, int value, ref int bitposition, int bits)"
.br
.RI "Write a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this long value, ref ushort buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this int value, ref ushort buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this short value, ref ushort buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this sbyte value, ref ushort buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static int \fBReadSigned\fP (this ushort buffer, ref int bitposition, int bits)"
.br
.RI "Read a previously injected signed int back out of a buffer\&. "
.ti -1c
.RI "static byte \fBWriteSigned\fP (this byte buffer, int value, ref int bitposition, int bits)"
.br
.RI "Write a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this long value, ref byte buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this int value, ref byte buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this short value, ref byte buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static void \fBInjectSigned\fP (this sbyte value, ref byte buffer, ref int bitposition, int bits)"
.br
.RI "Inject (write) a signed value into a buffer using zigzag\&. "
.ti -1c
.RI "static int \fBReadSigned\fP (this byte buffer, ref int bitposition, int bits)"
.br
.RI "Read a previously injected signed int back out of a buffer\&. "
.ti -1c
.RI "static ulong \fBWritetBool\fP (this ulong buffer, bool value, ref int bitposition)"
.br
.ti -1c
.RI "static uint \fBWritetBool\fP (this uint buffer, bool value, ref int bitposition)"
.br
.ti -1c
.RI "static ushort \fBWritetBool\fP (this ushort buffer, bool value, ref int bitposition)"
.br
.ti -1c
.RI "static byte \fBWritetBool\fP (this byte buffer, bool value, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBInject\fP (this bool value, ref ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBInject\fP (this bool value, ref uint buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBInject\fP (this bool value, ref ushort buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBInject\fP (this bool value, ref byte buffer, ref int bitposition)"
.br
.ti -1c
.RI "static bool \fBReadBool\fP (this ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "static bool \fBReadtBool\fP (this uint buffer, ref int bitposition)"
.br
.ti -1c
.RI "static bool \fBReadBool\fP (this ushort buffer, ref int bitposition)"
.br
.ti -1c
.RI "static bool \fBReadBool\fP (this byte buffer, ref int bitposition)"
.br
.ti -1c
.RI "static ulong \fBWrite\fP (this ulong buffer, ulong value, ref int bitposition, int bits=64)"
.br
.RI "Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static uint \fBWrite\fP (this uint buffer, ulong value, ref int bitposition, int bits=64)"
.br
.RI "Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static ushort \fBWrite\fP (this ushort buffer, ulong value, ref int bitposition, int bits=64)"
.br
.RI "Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static byte \fBWrite\fP (this byte buffer, ulong value, ref int bitposition, int bits=64)"
.br
.RI "Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref ulong buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref ulong buffer, int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref ulong buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref ulong buffer, int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref ulong buffer, ref int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref ulong buffer, int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref ulong buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref ulong buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this long value, ref ulong buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this int value, ref ulong buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this short value, ref ulong buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this sbyte value, ref ulong buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref uint buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref uint buffer, int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref uint buffer, ref int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref uint buffer, int bitposition, int bits=32)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref uint buffer, ref int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref uint buffer, int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref uint buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref uint buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this long value, ref uint buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this int value, ref uint buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this short value, ref uint buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInjectUnsigned\fP (this sbyte value, ref uint buffer, ref int bitposition, int bits=64)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref ushort buffer, ref int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref ushort buffer, int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref ushort buffer, ref int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref ushort buffer, int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref ushort buffer, ref int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref ushort buffer, int bitposition, int bits=16)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref ushort buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref ushort buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref byte buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref byte buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref byte buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this uint value, ref byte buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref byte buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ushort value, ref byte buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref byte buffer, ref int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this byte value, ref byte buffer, int bitposition, int bits=8)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static ulong \fBExtract\fP (this ulong value, int bits, ref int bitposition)"
.br
.RI "Extract (read/deserialize) a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. "
.ti -1c
.RI "static ulong \fBRead\fP (this ulong value, ref int bitposition, int bits)"
.br
.RI "Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. "
.ti -1c
.RI "static ulong \fBExtract\fP (this ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static ulong \fBExtract\fP (this ulong value, int bits)"
.br
.RI "Extract and return bits from value\&. "
.ti -1c
.RI "static uint \fBRead\fP (this uint value, ref int bitposition, int bits)"
.br
.RI "Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. "
.ti -1c
.RI "static uint \fBExtract\fP (this uint value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static uint \fBExtract\fP (this uint value, int bits)"
.br
.RI "Extract and return bits from value\&. "
.ti -1c
.RI "static uint \fBRead\fP (this ushort value, ref int bitposition, int bits)"
.br
.RI "Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. "
.ti -1c
.RI "static uint \fBExtract\fP (this ushort value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static uint \fBRead\fP (this byte value, ref int bitposition, int bits)"
.br
.RI "Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. "
.ti -1c
.RI "static uint \fBExtract\fP (this byte value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static byte \fBExtract\fP (this byte value, int bits)"
.br
.RI "Extract and return bits from value\&. "
.ti -1c
.RI "static void \fBInject\fP (this float f, ref ulong buffer, ref int bitposition)"
.br
.RI "Inject (serialize/write) a float into a primitive buffer at the bitposition\&. "
.ti -1c
.RI "static float \fBReadFloat\fP (this ulong buffer, ref int bitposition)"
.br
.RI "REad a float from a bitpacked primitive(value) starting at bitposition\&. "
.ti -1c
.RI "static float \fBExtractFloat\fP (this ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "static ushort \fBInjectAsHalfFloat\fP (this float f, ref ulong buffer, ref int bitposition)"
.br
.RI "Inject (serialize/write) a compressed float into a primitive buffer at the bitposition\&. "
.ti -1c
.RI "static ushort \fBInjectAsHalfFloat\fP (this float f, ref uint buffer, ref int bitposition)"
.br
.RI "Inject (serialize/write) a compressed float into a primitive buffer at the bitposition\&. "
.ti -1c
.RI "static float \fBReadHalfFloat\fP (this ulong buffer, ref int bitposition)"
.br
.RI "Read a float from a bitpacked primitive(value) starting at bitposition\&. "
.ti -1c
.RI "static float \fBExtractHalfFloat\fP (this ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "static float \fBReadHalfFloat\fP (this uint buffer, ref int bitposition)"
.br
.RI "Read a float from a bitpacked primitive(value) starting at bitposition\&. "
.ti -1c
.RI "static float \fBExtractHalfFloat\fP (this uint buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref uint buffer, int bits, ref int bitposition)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.ti -1c
.RI "static void \fBInject\fP (this ulong value, ref ulong buffer, int bits, ref int bitposition)"
.br
.RI "Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extension methods for writing bits to primitive buffers\&. 


.PP
Definition at line \fB32\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static byte Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this byte value, int bits)\fC [static]\fP"

.PP
Extract and return bits from value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive\&.
.br
\fIbits\fP How many lower order bits to read\&.
.RE
.PP
\fBReturns\fP
.RS 4
Cast the return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1115\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this byte value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB1100\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this uint value, int bits)\fC [static]\fP"

.PP
Extract and return bits from value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive\&.
.br
\fIbits\fP How many lower order bits to read\&.
.RE
.PP
\fBReturns\fP
.RS 4
Cast the return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1043\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this uint value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB1028\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this ulong value, int bits)\fC [static]\fP"

.PP
Extract and return bits from value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive\&.
.br
\fIbits\fP How many lower order bits to read\&.
.RE
.PP
\fBReturns\fP
.RS 4
Cast the return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1000\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this ulong value, int bits, ref int bitposition)\fC [static]\fP"

.PP
Extract (read/deserialize) a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive buffer to read from\&.
.br
\fIbits\fP Number of lower order bits to copy from source to return value\&.
.br
\fIbitposition\fP Auto-incremented reference to the value read bit pointer\&. Extraction starts at this point in value\&.
.RE
.PP
\fBReturns\fP
.RS 4
Downcast this ulong return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB959\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB984\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Extract (this ushort value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB1071\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ExtractFloat (this ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB1150\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ExtractHalfFloat (this uint buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB1213\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ExtractHalfFloat (this ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB1196\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this bool value, ref byte buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB328\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this bool value, ref uint buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB320\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this bool value, ref ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB316\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this bool value, ref ushort buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB324\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref byte buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB943\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref byte buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB932\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref uint buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB712\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref uint buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB700\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref ulong buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB562\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref ulong buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB551\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref ushort buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB847\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this byte value, ref ushort buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB836\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this \fBByteConverter\fP value, ref byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB78\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this \fBByteConverter\fP value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this \fBByteConverter\fP value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this \fBByteConverter\fP value, ref ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB67\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this float f, ref ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Inject (serialize/write) a float into a primitive buffer at the bitposition\&. No compression occurs, this is a full 32bit write\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to compress and write\&.
.br
\fIbuffer\fP Target buffer for write\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP

.PP
Definition at line \fB1134\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref byte buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB897\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref byte buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB886\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref uint buffer, int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB664\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref uint buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB652\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref ulong buffer, int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB507\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref ulong buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB495\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref ushort buffer, int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB803\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this uint value, ref ushort buffer, ref int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB792\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref byte buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB874\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref byte buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB863\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref uint buffer, int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB639\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref uint buffer, int bits, ref int bitposition)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB1232\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref uint buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB627\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref ulong buffer, int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB475\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref ulong buffer, int bits, ref int bitposition)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB1244\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref ulong buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB463\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref ushort buffer, int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB781\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ulong value, ref ushort buffer, ref int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB770\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref byte buffer, int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB920\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref byte buffer, ref int bitposition, int bits = \fC8\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB909\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref uint buffer, int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB688\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref uint buffer, ref int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB676\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref ulong buffer, int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB539\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref ulong buffer, ref int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB527\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref ushort buffer, int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Write position\&. Writing will begin at this position in the buffer\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB825\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.Inject (this ushort value, ref ushort buffer, ref int bitposition, int bits = \fC16\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB814\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectAsHalfFloat (this float f, ref uint buffer, ref int bitposition)\fC [static]\fP"

.PP
Inject (serialize/write) a compressed float into a primitive buffer at the bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to compress and write\&.
.br
\fIbuffer\fP Target buffer for write\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP

.PP
Definition at line \fB1177\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectAsHalfFloat (this float f, ref ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Inject (serialize/write) a compressed float into a primitive buffer at the bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIf\fP Float to compress and write\&.
.br
\fIbuffer\fP Target buffer for write\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP

.PP
Definition at line \fB1165\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this int value, ref byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB263\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this int value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB159\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this int value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB107\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this int value, ref ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB211\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this long value, ref byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB255\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this long value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB151\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this long value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB99\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this long value, ref ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB203\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this sbyte value, ref byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB279\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this sbyte value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB175\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this sbyte value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB123\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this sbyte value, ref ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB227\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this short value, ref byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB271\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this short value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB167\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this short value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB115\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectSigned (this short value, ref ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Inject (write) a signed value into a buffer using zigzag\&. The buffer reference is modified\&. 
.PP
Definition at line \fB219\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this int value, ref uint buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB734\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this int value, ref ulong buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB587\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this long value, ref uint buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB724\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this long value, ref ulong buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB575\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this sbyte value, ref uint buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB754\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this sbyte value, ref ulong buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB611\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this short value, ref uint buffer, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB744\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitiveSerializeExt\&.InjectUnsigned (this short value, ref ulong buffer, ref int bitposition, int bits = \fC32\fP)\fC [static]\fP"

.PP
Inject (write/serialize) x bits of source value into a target primitive (the buffer) starting at bitposition\&. Negative numbers will not serialize properly\&. Use InjectUnsigned for signed values\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP

.PP
Definition at line \fB599\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Read (this byte value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive buffer to read from\&.
.br
\fIbits\fP Number of lower order bits to copy from source to return value\&.
.br
\fIbitposition\fP Auto-incremented reference to the value read bit pointer\&. Read starts at this point in value\&.
.RE
.PP
\fBReturns\fP
.RS 4
Downcast this uint return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1091\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Read (this uint value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive buffer to read from\&.
.br
\fIbits\fP Number of lower order bits to copy from source to return value\&.
.br
\fIbitposition\fP Auto-incremented reference to the value read bit pointer\&. Read starts at this point in value\&.
.RE
.PP
\fBReturns\fP
.RS 4
Cast this uint return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1019\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.Read (this ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive buffer to read from\&.
.br
\fIbits\fP Number of lower order bits to copy from source to return value\&.
.br
\fIbitposition\fP Auto-incremented reference to the value read bit pointer\&. Read starts at this point in value\&.
.RE
.PP
\fBReturns\fP
.RS 4
Downcast this ulong return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB975\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Read (this ushort value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a value from a source primitive (the buffer) by reading x bits starting at the bitposition, and return the reconstructed value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Source primitive buffer to read from\&.
.br
\fIbits\fP Number of lower order bits to copy from source to return value\&.
.br
\fIbitposition\fP Auto-incremented reference to the value read bit pointer\&. Read starts at this point in value\&.
.RE
.PP
\fBReturns\fP
.RS 4
Cast this ushort return value to the desired type\&.
.RE
.PP

.PP
Definition at line \fB1062\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadBool (this byte buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB345\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadBool (this ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB333\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadBool (this ushort buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB341\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadFloat (this ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
REad a float from a bitpacked primitive(value) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP 
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB1145\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadHalfFloat (this uint buffer, ref int bitposition)\fC [static]\fP"

.PP
Read a float from a bitpacked primitive(value) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source buffer to read from\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB1207\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadHalfFloat (this ulong buffer, ref int bitposition)\fC [static]\fP"

.PP
Read a float from a bitpacked primitive(value) starting at bitposition\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP Source buffer to read from\&.
.br
\fIbitposition\fP Auto-incremented read position for the buffer (in bits)
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB1190\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadSigned (this byte buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a previously injected signed int back out of a buffer\&. 
.PP
\fBReturns\fP
.RS 4
Returns the restored signed value\&.
.RE
.PP

.PP
Definition at line \fB288\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadSigned (this uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a previously injected signed int back out of a buffer\&. 
.PP
\fBReturns\fP
.RS 4
Returns the restored signed value\&.
.RE
.PP

.PP
Definition at line \fB184\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadSigned (this ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a previously injected signed int back out of a buffer\&. 
.PP
\fBReturns\fP
.RS 4
Returns the restored signed value\&.
.RE
.PP

.PP
Definition at line \fB132\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadSigned (this ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Read a previously injected signed int back out of a buffer\&. 
.PP
\fBReturns\fP
.RS 4
Returns the restored signed value\&.
.RE
.PP

.PP
Definition at line \fB236\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.PrimitiveSerializeExt\&.ReadtBool (this uint buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB337\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static byte Photon\&.Compression\&.PrimitiveSerializeExt\&.Write (this byte buffer, ulong value, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer\&.
.RE
.PP

.PP
Definition at line \fB436\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.Write (this uint buffer, ulong value, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer\&.
.RE
.PP

.PP
Definition at line \fB387\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.Write (this ulong buffer, ulong value, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer\&.
.RE
.PP

.PP
Definition at line \fB363\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitiveSerializeExt\&.Write (this ushort buffer, ulong value, ref int bitposition, int bits = \fC64\fP)\fC [static]\fP"

.PP
Primary Write x bits of source value into a target primitive (the buffer) starting at bitposition\&. WARNING: Unlike Inject, Write passes the buffer by reference, so you MUST use the return value as the new buffer value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP Value to write\&.
.br
\fIbuffer\fP Target of write\&.
.br
\fIbitposition\fP Auto-incremented write position\&. Writing will begin at this position in the buffer, and this value will have bits added to it\&.
.br
\fIbits\fP Number of lower order bits to copy from source to target buffer\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer\&.
.RE
.PP

.PP
Definition at line \fB411\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static byte Photon\&.Compression\&.PrimitiveSerializeExt\&.WriteSigned (this byte buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Write a signed value into a buffer using zigzag\&. 
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer with the injected value\&.
.RE
.PP

.PP
Definition at line \fB247\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.WriteSigned (this uint buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Write a signed value into a buffer using zigzag\&. 
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer with the injected value\&.
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.WriteSigned (this ulong buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Write a signed value into a buffer using zigzag\&. 
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer with the injected value\&.
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitiveSerializeExt\&.WriteSigned (this ushort buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Write a signed value into a buffer using zigzag\&. 
.PP
\fBReturns\fP
.RS 4
Returns the modified buffer with the injected value\&.
.RE
.PP

.PP
Definition at line \fB195\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static byte Photon\&.Compression\&.PrimitiveSerializeExt\&.WritetBool (this byte buffer, bool value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB311\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitiveSerializeExt\&.WritetBool (this uint buffer, bool value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB303\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitiveSerializeExt\&.WritetBool (this ulong buffer, bool value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB299\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitiveSerializeExt\&.WritetBool (this ushort buffer, bool value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB307\fP of file \fBPrimitiveSerializeExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
