.TH "Photon.Compression.Internal.PackObjectDatabase.PackObjectInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.PackObjectDatabase.PackObjectInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackObjectInfo\fP (\fBFastBitMask128\fP \fBdefaultReadyMask\fP, \fBPackObjDelegate\fP packObjToBuffer, \fBPackFrameDelegate\fP packFrameToBuffer, \fBUnpackFrameDelegate\fP unpackFrameFromBuffer, int \fBmaxBits\fP, Func< \fBPackFrame\fP > factoryFrame, Func< System\&.Object, int, \fBPackFrame\fP[]> factoryFramesObj, \fBPackCopyFrameToObjectDelegate\fP copyFrameToObj, Action< System\&.Object, \fBPackFrame\fP > captureObj, Action< \fBPackFrame\fP, \fBPackFrame\fP > copyFrameToFrame, \fBPackSnapshotObjectDelegate\fP snapObject, \fBPackInterpFrameToFrameDelegate\fP interpFrameToFrame, \fBPackInterpFrameToObjectDelegate\fP interpFrameToObj, int \fBfieldCount\fP)"
.br
.RI "Class Type Constructor\&. "
.ti -1c
.RI "\fBPackObjectInfo\fP (\fBFastBitMask128\fP \fBdefaultReadyMask\fP, \fBPackStructDelegate\fP packStructToBuffer, \fBPackFrameDelegate\fP packFrameToBuffer, \fBUnpackFrameDelegate\fP unpackFrameFromBuffer, int \fBmaxBits\fP, Func< \fBPackFrame\fP > factoryFrame, Func< IntPtr, int, \fBPackFrame\fP[]> factoryFramesStruct, \fBPackCopyFrameToStructDelegate\fP copyFrameToStruct, Action< IntPtr, \fBPackFrame\fP > captureStruct, Action< \fBPackFrame\fP, \fBPackFrame\fP > copyFrameToFrame, \fBPackSnapshotStructDelegate\fP snapStruct, \fBPackInterpFrameToFrameDelegate\fP interpFrameToFrame, \fBPackInterpFrameToStructDelegate\fP interpFrameToStruct, int \fBfieldCount\fP)"
.br
.RI "Struct Type Constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Type \fBpackFrameType\fP"
.br
.ti -1c
.RI "readonly int \fBmaxBits\fP"
.br
.ti -1c
.RI "readonly int \fBmaxBytes\fP"
.br
.ti -1c
.RI "readonly \fBFastBitMask128\fP \fBdefaultReadyMask\fP"
.br
.ti -1c
.RI "readonly \fBPackObjDelegate\fP \fBPackObjToBuffer\fP"
.br
.ti -1c
.RI "readonly \fBPackStructDelegate\fP \fBPackStructToBuffer\fP"
.br
.ti -1c
.RI "readonly \fBPackFrameDelegate\fP \fBPackFrameToBuffer\fP"
.br
.ti -1c
.RI "readonly \fBUnpackFrameDelegate\fP \fBUnpackFrameFromBuffer\fP"
.br
.ti -1c
.RI "Func< \fBPackFrame\fP > \fBFactoryFrame\fP"
.br
.ti -1c
.RI "Func< System\&.Object, int, \fBPackFrame\fP[]> \fBFactoryFramesObj\fP"
.br
.ti -1c
.RI "Func< IntPtr, int, \fBPackFrame\fP[]> \fBFactoryFramesStruct\fP"
.br
.ti -1c
.RI "\fBPackCopyFrameToObjectDelegate\fP \fBCopyFrameToObj\fP"
.br
.ti -1c
.RI "\fBPackCopyFrameToStructDelegate\fP \fBCopyFrameToStruct\fP"
.br
.ti -1c
.RI "\fBPackSnapshotObjectDelegate\fP \fBSnapObject\fP"
.br
.ti -1c
.RI "\fBPackSnapshotStructDelegate\fP \fBSnapStruct\fP"
.br
.ti -1c
.RI "\fBPackInterpFrameToFrameDelegate\fP \fBInterpFrameToFrame\fP"
.br
.ti -1c
.RI "\fBPackInterpFrameToObjectDelegate\fP \fBInterpFrameToObj\fP"
.br
.ti -1c
.RI "\fBPackInterpFrameToStructDelegate\fP \fBInterpFrameToStruct\fP"
.br
.ti -1c
.RI "Action< System\&.Object, \fBPackFrame\fP > \fBCaptureObj\fP"
.br
.ti -1c
.RI "Action< IntPtr, \fBPackFrame\fP > \fBCaptureStruct\fP"
.br
.ti -1c
.RI "Action< \fBPackFrame\fP, \fBPackFrame\fP > \fBCopyFrameToFrame\fP"
.br
.ti -1c
.RI "readonly int \fBfieldCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.PackObjectInfo (\fBFastBitMask128\fP defaultReadyMask, \fBPackObjDelegate\fP packObjToBuffer, \fBPackFrameDelegate\fP packFrameToBuffer, \fBUnpackFrameDelegate\fP unpackFrameFromBuffer, int maxBits, Func< \fBPackFrame\fP > factoryFrame, Func< System\&.Object, int, \fBPackFrame\fP[]> factoryFramesObj, \fBPackCopyFrameToObjectDelegate\fP copyFrameToObj, Action< System\&.Object, \fBPackFrame\fP > captureObj, Action< \fBPackFrame\fP, \fBPackFrame\fP > copyFrameToFrame, \fBPackSnapshotObjectDelegate\fP snapObject, \fBPackInterpFrameToFrameDelegate\fP interpFrameToFrame, \fBPackInterpFrameToObjectDelegate\fP interpFrameToObj, int fieldCount)"

.PP
Class Type Constructor\&. 
.PP
Definition at line \fB97\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.PackObjectInfo (\fBFastBitMask128\fP defaultReadyMask, \fBPackStructDelegate\fP packStructToBuffer, \fBPackFrameDelegate\fP packFrameToBuffer, \fBUnpackFrameDelegate\fP unpackFrameFromBuffer, int maxBits, Func< \fBPackFrame\fP > factoryFrame, Func< IntPtr, int, \fBPackFrame\fP[]> factoryFramesStruct, \fBPackCopyFrameToStructDelegate\fP copyFrameToStruct, Action< IntPtr, \fBPackFrame\fP > captureStruct, Action< \fBPackFrame\fP, \fBPackFrame\fP > copyFrameToFrame, \fBPackSnapshotStructDelegate\fP snapStruct, \fBPackInterpFrameToFrameDelegate\fP interpFrameToFrame, \fBPackInterpFrameToStructDelegate\fP interpFrameToStruct, int fieldCount)"

.PP
Struct Type Constructor\&. 
.PP
Definition at line \fB134\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action<System\&.Object, \fBPackFrame\fP> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.CaptureObj"

.PP
Definition at line \fB90\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Action<IntPtr, \fBPackFrame\fP> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.CaptureStruct"

.PP
Definition at line \fB91\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Action<\fBPackFrame\fP, \fBPackFrame\fP> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.CopyFrameToFrame"

.PP
Definition at line \fB92\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackCopyFrameToObjectDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.CopyFrameToObj"

.PP
Definition at line \fB83\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackCopyFrameToStructDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.CopyFrameToStruct"

.PP
Definition at line \fB84\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly \fBFastBitMask128\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.defaultReadyMask"

.PP
Definition at line \fB74\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Func<\fBPackFrame\fP> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.FactoryFrame"

.PP
Definition at line \fB80\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Func<System\&.Object, int, \fBPackFrame\fP[]> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.FactoryFramesObj"

.PP
Definition at line \fB81\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "Func<IntPtr, int, \fBPackFrame\fP[]> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.FactoryFramesStruct"

.PP
Definition at line \fB82\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly int Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.fieldCount"

.PP
Definition at line \fB94\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackInterpFrameToFrameDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.InterpFrameToFrame"

.PP
Definition at line \fB87\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackInterpFrameToObjectDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.InterpFrameToObj"

.PP
Definition at line \fB88\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackInterpFrameToStructDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.InterpFrameToStruct"

.PP
Definition at line \fB89\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly int Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.maxBits"

.PP
Definition at line \fB72\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly int Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.maxBytes"

.PP
Definition at line \fB73\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly \fBPackFrameDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.PackFrameToBuffer"

.PP
Definition at line \fB78\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly Type Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.packFrameType"

.PP
Definition at line \fB71\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly \fBPackObjDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.PackObjToBuffer"

.PP
Definition at line \fB76\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly \fBPackStructDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.PackStructToBuffer"

.PP
Definition at line \fB77\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackSnapshotObjectDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.SnapObject"

.PP
Definition at line \fB85\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBPackSnapshotStructDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.SnapStruct"

.PP
Definition at line \fB86\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "readonly \fBUnpackFrameDelegate\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjectInfo\&.UnpackFrameFromBuffer"

.PP
Definition at line \fB79\fP of file \fBPackObjectDatabase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
