.TH "Photon.Pun.Demo.Cockpit.PlayerDetailsController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.PlayerDetailsController \- Controller for the Playerdetails UI view  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBSetPlayerTarget\fP (\fBPlayer\fP player)"
.br
.ti -1c
.RI "void \fBKickOutPlayer\fP ()"
.br
.ti -1c
.RI "void \fBSetAsMaster\fP ()"
.br
.ti -1c
.RI "override void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP otherPlayer)"
.br
.RI "Called when a remote player left the room or became inactive\&. "
.ti -1c
.RI "override void \fBOnMasterClientSwitched\fP (\fBPlayer\fP newMasterClient)"
.br
.RI "Called after switching to a new MasterClient when the current one leaves\&. "
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP target, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"
.br
.ti -1c
.RI "void \fBResetList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBContentPanel\fP"
.br
.ti -1c
.RI "\fBPropertyCell\fP \fBPropertyCellPrototype\fP"
.br
.ti -1c
.RI "Text \fBUpdateStatusText\fP"
.br
.ti -1c
.RI "Transform \fBBuiltInPropertiesPanel\fP"
.br
.ti -1c
.RI "Transform \fBPlayerNumberingExtensionPanel\fP"
.br
.ti -1c
.RI "Transform \fBScoreExtensionPanel\fP"
.br
.ti -1c
.RI "Transform \fBTeamExtensionPanel\fP"
.br
.ti -1c
.RI "Transform \fBTurnExtensionPanel\fP"
.br
.ti -1c
.RI "Transform \fBCustomPropertiesPanel\fP"
.br
.ti -1c
.RI "GameObject \fBMasterClientToolBar\fP"
.br
.ti -1c
.RI "GameObject \fBNotInRoomLabel\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Controller for the Playerdetails UI view 
.PP
Definition at line \fB23\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.KickOutPlayer ()"

.PP
Definition at line \fB133\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.OnDisable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB65\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB55\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.OnMasterClientSwitched (\fBPlayer\fP newMasterClient)\fC [virtual]\fP"

.PP
Called after switching to a new MasterClient when the current one leaves\&. This is not called when this client enters a room\&. The former MasterClient is still in the player list when this method get called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB151\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.OnPlayerLeftRoom (\fBPlayer\fP otherPlayer)\fC [virtual]\fP"

.PP
Called when a remote player left the room or became inactive\&. Check otherPlayer\&.IsInactive\&. 
.PP
If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic\&.
.PP
Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room\&. In such cases, the Player stays in the \fBRoom\&.Players\fP dictionary\&.
.PP
If the player is not just inactive, it gets removed from the \fBRoom\&.Players\fP dictionary, before the callback is called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB145\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.OnPlayerPropertiesUpdate (\fBPlayer\fP target, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"

.PP
Definition at line \fB156\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.ResetList ()"

.PP
Definition at line \fB205\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.SetAsMaster ()"

.PP
Definition at line \fB138\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.SetPlayerTarget (\fBPlayer\fP player)"

.PP
Definition at line \fB72\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.BuiltInPropertiesPanel"

.PP
Definition at line \fB30\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.ContentPanel"

.PP
Definition at line \fB26\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.CustomPropertiesPanel"

.PP
Definition at line \fB35\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.MasterClientToolBar"

.PP
Definition at line \fB37\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.NotInRoomLabel"

.PP
Definition at line \fB41\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.PlayerNumberingExtensionPanel"

.PP
Definition at line \fB31\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "\fBPropertyCell\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.PropertyCellPrototype"

.PP
Definition at line \fB27\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.ScoreExtensionPanel"

.PP
Definition at line \fB32\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.TeamExtensionPanel"

.PP
Definition at line \fB33\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Transform Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.TurnExtensionPanel"

.PP
Definition at line \fB34\fP of file \fBPlayerDetailsController\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\&.UpdateStatusText"

.PP
Definition at line \fB28\fP of file \fBPlayerDetailsController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
