.TH "Photon.Pun.Simple.Internal" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Internal \- Generic handlers for routing incoming network messages as byte[] arrays to registered handlers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCallbackUtilities\fP"
.br
.ti -1c
.RI "class \fBNetMsgCallbacks\fP"
.br
.ti -1c
.RI "class \fBNetMsgSends\fP"
.br
.RI "Unified code for sending network messages across different Network Libraries\&. "
.ti -1c
.RI "class \fBNetObjColliderExt\fP"
.br
.RI "\fBUtilities\fP for finding/indexing Colliders on a \fBNetObject\fP "
.ti -1c
.RI "class \fBParameterDefaults\fP"
.br
.ti -1c
.RI "class \fBParameterSettings\fP"
.br
.RI "Settings for a single Animator parameter\&. "
.ti -1c
.RI "class \fBSimpleDocsURLS\fP"
.br
.ti -1c
.RI "class \fBTickManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBParameterInterpolation\fP { \fBDefault\fP, \fBHold\fP, \fBLerp\fP, \fBAdvance\fP }"
.br
.ti -1c
.RI "enum \fBParameterMissingHold\fP { \fBDefault\fP, \fBHold\fP }"
.br
.ti -1c
.RI "enum \fBParameterExtrapolation\fP { \fBDefault\fP, \fBHold\fP, \fBLerp\fP }"
.br
.ti -1c
.RI "enum \fBReceiveGroup\fP { \fBOthers\fP, \fBAll\fP, \fBMaster\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic handlers for routing incoming network messages as byte[] arrays to registered handlers\&. 

This abstracts the various netlibs into a standard byte[] format\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Simple\&.Internal\&.ParameterExtrapolation\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIHold \fP\fP
.TP
\fB\fILerp \fP\fP
.PP
Definition at line \fB10\fP of file \fBParameterEnums\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Simple\&.Internal\&.ParameterInterpolation\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIHold \fP\fP
.TP
\fB\fILerp \fP\fP
.TP
\fB\fIAdvance \fP\fP
.PP
Definition at line \fB8\fP of file \fBParameterEnums\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Simple\&.Internal\&.ParameterMissingHold\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDefault \fP\fP
.TP
\fB\fIHold \fP\fP
.PP
Definition at line \fB9\fP of file \fBParameterEnums\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Simple\&.Internal\&.ReceiveGroup\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOthers \fP\fP
.TP
\fB\fIAll \fP\fP
.TP
\fB\fIMaster \fP\fP
.PP
Definition at line \fB15\fP of file \fBNetMsgSends\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
