.TH "Photon.Pun.Simple.ConnectionTickOffsets" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ConnectionTickOffsets
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBConvertFrameLocalToOrigin\fP (int localFrameId)"
.br
.ti -1c
.RI "int \fBConvertFrameOriginToLocal\fP (int originFrameId)"
.br
.ti -1c
.RI "\fBConnectionTickOffsets\fP (int \fBconnId\fP, int originToLocal, int localToOrigin)"
.br
.ti -1c
.RI "void \fBSnapshotAdvance\fP ()"
.br
.RI "Checks the state of the buffer, and returns the number of snapshots to advance to keep the buffer happy\&. "
.ti -1c
.RI "void \fBPostSnapshot\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBconnId\fP"
.br
.ti -1c
.RI "int \fBoriginToLocalFrame\fP"
.br
.ti -1c
.RI "int \fBlocalToOriginFrame\fP"
.br
.ti -1c
.RI "int \fBnumOfSequentialFramesWithTooSmallBuffer\fP"
.br
.ti -1c
.RI "int \fBnumOfSequentialFramesWithTooLargeBuffer\fP"
.br
.ti -1c
.RI "bool \fBframeArrivedTooLate\fP"
.br
.ti -1c
.RI "bool \fBhadInitialSnapshot\fP"
.br
.ti -1c
.RI "int \fBadvanceCount\fP"
.br
.ti -1c
.RI "float[] \fBframeArriveTime\fP"
.br
.ti -1c
.RI "float[] \fBframeTimeBeforeConsumption\fP"
.br
.ti -1c
.RI "\fBFastBitMask128\fP \fBvalidFrameMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.ConnectionTickOffsets (int connId, int originToLocal, int localToOrigin)"

.PP
Definition at line \fB45\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.ConvertFrameLocalToOrigin (int localFrameId)"

.PP
Definition at line \fB24\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.ConvertFrameOriginToLocal (int originFrameId)"

.PP
Definition at line \fB33\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.PostSnapshot ()"
This clear could be a bit more intentional Clears valid frames so that lookahead isn't find outdated frames for its buffer adjustments\&.
.PP
Definition at line \fB174\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.SnapshotAdvance ()"

.PP
Checks the state of the buffer, and returns the number of snapshots to advance to keep the buffer happy\&. TODO: May be able to reduce this in the future to a less aggressive look ahead
.PP
Buffer emptied - either means drop/sever connection hang, or way behind\&.
.PP
No valid frames, but we just received one late - buffer needs IMMEDIATE HARD correction
.PP
No frames have arrived late, looks like bad packetloss\&. Don't adjust the buffer in case it corrects\&.
.PP
Buffer is too small
.PP
Buffer is too large
.PP
Limit advance to only one extra snapshot to shrink the buffer, unless this is startup - then we need to burn all backlog\&.
.PP
Buffer is happy\&.
.PP
Definition at line \fB67\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.advanceCount"

.PP
Definition at line \fB20\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.connId"

.PP
Definition at line \fB12\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.frameArrivedTooLate"

.PP
Definition at line \fB18\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "float [] Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.frameArriveTime"

.PP
Definition at line \fB21\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "float [] Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.frameTimeBeforeConsumption"

.PP
Definition at line \fB22\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.hadInitialSnapshot"

.PP
Definition at line \fB19\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.localToOriginFrame"

.PP
Definition at line \fB13\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.numOfSequentialFramesWithTooLargeBuffer"

.PP
Definition at line \fB17\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.numOfSequentialFramesWithTooSmallBuffer"

.PP
Definition at line \fB16\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.originToLocalFrame"

.PP
Definition at line \fB13\fP of file \fBConnectionTickOffsets\&.cs\fP\&.
.SS "\fBFastBitMask128\fP Photon\&.Pun\&.Simple\&.ConnectionTickOffsets\&.validFrameMask"

.PP
Definition at line \fB43\fP of file \fBConnectionTickOffsets\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
