.TH "Photon.Pun.Demo.Cockpit.AutoSyncSceneToggle" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.AutoSyncSceneToggle \- \fBPhotonNetwork\&.AutomaticallySyncScene\fP UI Toggle  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBToggleValue\fP (bool value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPhotonNetwork\&.AutomaticallySyncScene\fP UI Toggle 
.PP
Definition at line \fB17\fP of file \fBAutoSyncSceneToggle\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.AutoSyncSceneToggle\&.ToggleValue (bool value)"

.PP
Definition at line \fB55\fP of file \fBAutoSyncSceneToggle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
