.TH "Photon.Realtime.IErrorInfoCallback" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.IErrorInfoCallback \- Interface for \fBEventCode\&.ErrorInfo\fP event callback for the \fBRealtime\fP Api\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, and Photon\&.Realtime\&.ErrorInfoCallbacksContainer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnErrorInfo\fP (\fBErrorInfo\fP errorInfo)"
.br
.RI "Called when the client receives an event from the server indicating that an error happened there\&. "
.in -1c
.SH "Detailed Description"
.PP 
Interface for \fBEventCode\&.ErrorInfo\fP event callback for the \fBRealtime\fP Api\&. 

Classes that implement this interface must be registered to get callbacks for various situations\&.
.PP
To register for callbacks, call \fBLoadBalancingClient\&.AddCallbackTarget\fP and pass the class implementing this interface To stop getting callbacks, call \fBLoadBalancingClient\&.RemoveCallbackTarget\fP and pass the class implementing this interface
.PP
Definition at line \fB4034\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.IErrorInfoCallback\&.OnErrorInfo (\fBErrorInfo\fP errorInfo)"

.PP
Called when the client receives an event from the server indicating that an error happened there\&. In most cases this could be either:
.IP "1." 4
an error from webhooks plugin (if HasErrorInfo is enabled), read more here: https://doc.photonengine.com/en-us/realtime/current/gameplay/web-extensions/webhooks#options
.IP "2." 4
an error sent from a custom server plugin via PluginHost\&.BroadcastErrorInfoEvent, see example here: https://doc.photonengine.com/en-us/server/current/plugins/manual#handling_http_response
.IP "3." 4
an error sent from the server, for example, when the limit of cached events has been exceeded in the room (all clients will be disconnected and the room will be closed in this case) read more here: https://doc.photonengine.com/en-us/realtime/current/gameplay/cached-events#special_considerations
.PP
.PP
If you implement \fBIOnEventCallback\&.OnEvent\fP or \fBLoadBalancingClient\&.EventReceived\fP you will also get this event\&. 
.PP
\fBParameters\fP
.RS 4
\fIerrorInfo\fP Object containing information about the error
.RE
.PP

.PP
Implemented in \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
