.TH "Photon.Compression.IPackObj" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.IPackObj
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBPackObjectAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
