.TH "Photon.Pun.Simple.AutoMountHitscan" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoMountHitscan \- This component will generate a hitscan based on the transform it is attached to\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.HitscanComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "override void \fBOnAuthorityChanged\fP (bool isMine, bool controllerChanged)"
.br
.RI "Updates authority values on authority changes\&. "
.ti -1c
.RI "override void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.ti -1c
.RI "override bool \fBProcessHit\fP (Collider hit)"
.br
.RI "Handling for processing each hit returned by the hitscan\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSyncState\fP \fBsyncState\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSyncState\fP \fBSyncState\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This component will generate a hitscan based on the transform it is attached to\&. 

For each mount hit, \fBSyncState\&.SoftMount\fP will be called to attempt to reparent to the transform of the \fBMount\fP\&. 
.PP
Definition at line \fB19\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.OnAuthorityChanged (bool isMine, bool controllerChanged)\fC [virtual]\fP"

.PP
Updates authority values on authority changes\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontrollerChanged\fP 
.RE
.PP
Rather than an IsMine test every tick, we are completely removing this object from the OnPreSiulate callback list when !IsMine
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB57\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB49\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.OnPreSimulate (int frameId, int subFrameId)\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.HitscanComponent\fP\&.
.PP
Definition at line \fB78\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SS "override bool Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.ProcessHit (Collider hit)\fC [virtual]\fP"

.PP
Handling for processing each hit returned by the hitscan\&. 
.PP
\fBParameters\fP
.RS 4
\fIhit\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Return true to terminate processing any more hits\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.HitscanComponent\fP\&.
.PP
Definition at line \fB106\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSyncState\fP Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.syncState\fC [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBAutoMountHitscan\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSyncState\fP Photon\&.Pun\&.Simple\&.AutoMountHitscan\&.SyncState\fC [get]\fP"

.PP
Definition at line \fB24\fP of file \fBAutoMountHitscan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
