.TH "Photon.Pun.Demo.Procedural.IngameControlPanel" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Procedural.IngameControlPanel \- The Ingame Control Panel basically controls the \fBWorldGenerator\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.RI "When the object gets created, all necessary references are set up\&. "
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Gets called when the local client has joined the room\&. "
.ti -1c
.RI "override void \fBOnMasterClientSwitched\fP (\fBPlayer\fP newMasterClient)"
.br
.RI "Gets called whenever the current MasterClient has left the room and a new one is selected\&. "
.ti -1c
.RI "override void \fBOnRoomPropertiesUpdate\fP (\fBHashtable\fP propertiesThatChanged)"
.br
.RI "Gets called whenever the Custom Room Properties are updated\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The Ingame Control Panel basically controls the \fBWorldGenerator\fP\&. 

It is only interactable for the current MasterClient in the room\&. 
.PP
Definition at line \fB12\fP of file \fBIngameControlPanel\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\&.Awake ()"

.PP
When the object gets created, all necessary references are set up\&. Also the UI elements get set up properly in order to control the \fBWorldGenerator\fP\&. 
.PP
Definition at line \fB28\fP of file \fBIngameControlPanel\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Gets called when the local client has joined the room\&. Since only the MasterClient can control the \fBWorldGenerator\fP, we are checking if we have to make the UI controls available for the local client\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB157\fP of file \fBIngameControlPanel\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\&.OnMasterClientSwitched (\fBPlayer\fP newMasterClient)\fC [virtual]\fP"

.PP
Gets called whenever the current MasterClient has left the room and a new one is selected\&. If the local client is the new MasterClient, we make the UI controls available for him\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB170\fP of file \fBIngameControlPanel\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\&.OnRoomPropertiesUpdate (\fBHashtable\fP propertiesThatChanged)\fC [virtual]\fP"

.PP
Gets called whenever the Custom Room Properties are updated\&. In this callback we are interested in the settings the MasterClient can apply to the \fBWorldGenerator\fP\&. If all possible settings are updated (and available within the updated properties), these settings are also used to update the Ingame Control Panel as well as the \fBWorldGenerator\fP on all clients\&. Afterwards the \fBWorldGenerator\fP creates a new world with the new settings\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB186\fP of file \fBIngameControlPanel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
