.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Views/PhotonTransformViewClassic.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Views/PhotonTransformViewClassic.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewClassic\fP"
.br
.RI "This class helps you to synchronize position, rotation and scale of a GameObject\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewPositionModel\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewPositionControl\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewRotationModel\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewRotationControl\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewScaleModel\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonTransformViewScaleControl\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
