.TH "Photon.Pun.Simple.AutoOwnerGameObjEnable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoOwnerGameObjEnable
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEnableIf\fP { \fBOwner\fP, \fBOther\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnAuthorityChanged\fP (bool isMine, bool controllerChanged)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnableIf\fP \fBenableIf\fP = \fBEnableIf\&.Owner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBAutoOwnerGameObjEnable\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Simple\&.AutoOwnerGameObjEnable\&.EnableIf\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOwner \fP\fP
.TP
\fB\fIOther \fP\fP
.PP
Definition at line \fB18\fP of file \fBAutoOwnerGameObjEnable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.AutoOwnerGameObjEnable\&.OnAuthorityChanged (bool isMine, bool controllerChanged)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP\&.
.PP
Definition at line \fB32\fP of file \fBAutoOwnerGameObjEnable\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.AutoOwnerGameObjEnable\&.Start ()"

.PP
Definition at line \fB22\fP of file \fBAutoOwnerGameObjEnable\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEnableIf\fP Photon\&.Pun\&.Simple\&.AutoOwnerGameObjEnable\&.enableIf = \fBEnableIf\&.Owner\fP"

.PP
Definition at line \fB20\fP of file \fBAutoOwnerGameObjEnable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
