.TH "Photon.Realtime.PhotonPortDefinition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.PhotonPortDefinition \- Container for port definitions\&. 

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ushort \fBNameServerPort\fP"
.br
.RI "Typical ports: UDP: 5058 or 27000, TCP: 4533, WSS: 19093 or 443\&."
.ti -1c
.RI "ushort \fBMasterServerPort\fP"
.br
.RI "Typical ports: UDP: 5056 or 27002, TCP: 4530, WSS: 19090 or 443\&."
.ti -1c
.RI "ushort \fBGameServerPort\fP"
.br
.RI "Typical ports: UDP: 5055 or 27001, TCP: 4531, WSS: 19091 or 443\&."
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBPhotonPortDefinition\fP \fBAlternativeUdpPorts\fP = new \fBPhotonPortDefinition\fP() { \fBNameServerPort\fP = 27000, \fBMasterServerPort\fP = 27001, \fBGameServerPort\fP = 27002}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Container for port definitions\&.
.PP
Definition at line \fB247\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBPhotonPortDefinition\fP Photon\&.Realtime\&.PhotonPortDefinition\&.AlternativeUdpPorts = new \fBPhotonPortDefinition\fP() { \fBNameServerPort\fP = 27000, \fBMasterServerPort\fP = 27001, \fBGameServerPort\fP = 27002}\fC [static]\fP"

.PP
Definition at line \fB249\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "ushort Photon\&.Realtime\&.PhotonPortDefinition\&.GameServerPort"

.PP
Typical ports: UDP: 5055 or 27001, TCP: 4531, WSS: 19091 or 443\&.
.PP
Definition at line \fB256\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "ushort Photon\&.Realtime\&.PhotonPortDefinition\&.MasterServerPort"

.PP
Typical ports: UDP: 5056 or 27002, TCP: 4530, WSS: 19090 or 443\&.
.PP
Definition at line \fB254\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "ushort Photon\&.Realtime\&.PhotonPortDefinition\&.NameServerPort"

.PP
Typical ports: UDP: 5058 or 27000, TCP: 4533, WSS: 19093 or 443\&.
.PP
Definition at line \fB252\fP of file \fBLoadBalancingClient\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
