.TH "Photon.Pun.Demo.Asteroids.PlayerOverviewPanel" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids.PlayerOverviewPanel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "override void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP otherPlayer)"
.br
.RI "Called when a remote player left the room or became inactive\&. "
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"
.br
.RI "Called when custom player-properties are changed\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBPlayerOverviewEntryPrefab\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBPlayerOverviewPanel\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\&.Awake ()"

.PP
Definition at line \fB30\fP of file \fBPlayerOverviewPanel\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\&.OnPlayerLeftRoom (\fBPlayer\fP otherPlayer)\fC [virtual]\fP"

.PP
Called when a remote player left the room or became inactive\&. Check otherPlayer\&.IsInactive\&. 
.PP
If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic\&.
.PP
Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room\&. In such cases, the Player stays in the \fBRoom\&.Players\fP dictionary\&.
.PP
If the player is not just inactive, it gets removed from the \fBRoom\&.Players\fP dictionary, before the callback is called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB50\fP of file \fBPlayerOverviewPanel\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)\fC [virtual]\fP"

.PP
Called when custom player-properties are changed\&. Player and the changed properties are passed as object[]\&. 
.PP
Changing properties must be done by \fBPlayer\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetPlayer\fP Contains Player that changed\&.
.br
\fIchangedProps\fP Contains the properties that changed\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB60\fP of file \fBPlayerOverviewPanel\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\&.PlayerOverviewEntryPrefab"

.PP
Definition at line \fB24\fP of file \fBPlayerOverviewPanel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
