.TH "Photon.Compression.QuatCrusher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.QuatCrusher \- Wrapper for the QuatCompress codec, giving it editor capabilities and compatibility/interoperability with the entire \fBTransformCrusher\fP library\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Crusher< QuatCrusher >, System\&.IEquatable< QuatCrusher >, and ICrusherCopy< QuatCrusher >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQuatCrusher\fP ()"
.br
.ti -1c
.RI "\fBQuatCrusher\fP (int bits, bool \fBshowEnableToggle\fP=false, bool \fBisStandalone\fP=true)"
.br
.ti -1c
.RI "\fBQuatCrusher\fP (bool \fBshowEnableToggle\fP=false, bool \fBisStandalone\fP=true)"
.br
.ti -1c
.RI "\fBQuatCrusher\fP (\fBCompressLevel\fP compressLevel, bool \fBshowEnableToggle\fP=false, bool \fBisStandalone\fP=true)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.ti -1c
.RI "override void \fBOnBeforeSerialize\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterDeserialize\fP ()"
.br
.ti -1c
.RI "ulong \fBCompress\fP ()"
.br
.ti -1c
.RI "ulong \fBCompress\fP (Quaternion quat)"
.br
.ti -1c
.RI "Quaternion \fBDecompress\fP (ulong compressed)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (Quaternion quat, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (Quaternion quat, uint[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (Quaternion quat, ulong[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (ulong c, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (ulong c, uint[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (ulong c, ulong[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "Quaternion \fBRead\fP (byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "Quaternion \fBRead\fP (uint[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "Quaternion \fBRead\fP (ulong[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "ulong \fBWrite\fP (Quaternion quat, ref ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "Quaternion \fBRead\fP (ref ulong buffer, ref int bitposition)"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (\fBQuatCrusher\fP source)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBQuatCrusher\fP other)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBRoundBitsToBestPreset\fP (int bits)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBQuatCrusher\fP crusher1, \fBQuatCrusher\fP crusher2)"
.br
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBQuatCrusher\fP crusher1, \fBQuatCrusher\fP crusher2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCompressLevel\fP \fB_compressLevel\fP"
.br
.ti -1c
.RI "Transform \fBtransform\fP"
.br
.ti -1c
.RI "bool \fBlocal\fP"
.br
.ti -1c
.RI "bool \fBisStandalone\fP"
.br
.ti -1c
.RI "bool \fBshowEnableToggle\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBQC_ISPRO\fP = QuatCompress\&.ISPRO"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int?? \fBBits\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBCompressLevel\fP? \fBCompressLevel\fP\fC [getset]\fP"
.br
.ti -1c
.RI "bool \fBEnabled\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for the QuatCompress codec, giving it editor capabilities and compatibility/interoperability with the entire \fBTransformCrusher\fP library\&. 


.PP
Definition at line \fB24\fP of file \fBQuatCrusher\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.QuatCrusher\&.QuatCrusher ()"

.PP
Definition at line \fB103\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Photon\&.Compression\&.QuatCrusher\&.QuatCrusher (int bits, bool showEnableToggle = \fCfalse\fP, bool isStandalone = \fCtrue\fP)"

.PP
Definition at line \fB110\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Photon\&.Compression\&.QuatCrusher\&.QuatCrusher (bool showEnableToggle = \fCfalse\fP, bool isStandalone = \fCtrue\fP)"

.PP
Definition at line \fB120\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Photon\&.Compression\&.QuatCrusher\&.QuatCrusher (\fBCompressLevel\fP compressLevel, bool showEnableToggle = \fCfalse\fP, bool isStandalone = \fCtrue\fP)"

.PP
Definition at line \fB129\fP of file \fBQuatCrusher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Compress ()"

.PP
Definition at line \fB163\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Compress (Quaternion quat)"

.PP
Definition at line \fB174\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "void Photon\&.Compression\&.QuatCrusher\&.CopyFrom (\fBQuatCrusher\fP source)"

.PP
Definition at line \fB269\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Quaternion Photon\&.Compression\&.QuatCrusher\&.Decompress (ulong compressed)"

.PP
Definition at line \fB182\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "override bool Photon\&.Compression\&.QuatCrusher\&.Equals (object obj)"

.PP
Definition at line \fB276\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.Equals (\fBQuatCrusher\fP other)"

.PP
Definition at line \fB281\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "override int Photon\&.Compression\&.QuatCrusher\&.GetHashCode ()"

.PP
Definition at line \fB290\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "void Photon\&.Compression\&.QuatCrusher\&.Initialize ()"

.PP
Definition at line \fB137\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "override void Photon\&.Compression\&.QuatCrusher\&.OnAfterDeserialize ()"

.PP
Definition at line \fB146\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "override void Photon\&.Compression\&.QuatCrusher\&.OnBeforeSerialize ()"

.PP
Definition at line \fB143\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.QuatCrusher\&.operator!= (\fBQuatCrusher\fP crusher1, \fBQuatCrusher\fP crusher2)\fC [static]\fP"

.PP
Definition at line \fB305\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.QuatCrusher\&.operator== (\fBQuatCrusher\fP crusher1, \fBQuatCrusher\fP crusher2)\fC [static]\fP"

.PP
Definition at line \fB300\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Quaternion Photon\&.Compression\&.QuatCrusher\&.Read (byte[] buffer, ref int bitposition)"

.PP
Definition at line \fB236\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Quaternion Photon\&.Compression\&.QuatCrusher\&.Read (ref ulong buffer, ref int bitposition)"

.PP
Definition at line \fB263\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Quaternion Photon\&.Compression\&.QuatCrusher\&.Read (uint[] buffer, ref int bitposition)"

.PP
Definition at line \fB242\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Quaternion Photon\&.Compression\&.QuatCrusher\&.Read (ulong[] buffer, ref int bitposition)"

.PP
Definition at line \fB248\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.QuatCrusher\&.RoundBitsToBestPreset (int bits)\fC [static]\fP"

.PP
Definition at line \fB152\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (Quaternion quat, byte[] buffer, ref int bitposition)"

.PP
Definition at line \fB193\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (Quaternion quat, ref ulong buffer, ref int bitposition)"

.PP
Definition at line \fB256\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (Quaternion quat, uint[] buffer, ref int bitposition)"

.PP
Definition at line \fB200\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (Quaternion quat, ulong[] buffer, ref int bitposition)"

.PP
Definition at line \fB207\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (ulong c, byte[] buffer, ref int bitposition)"

.PP
Definition at line \fB214\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (ulong c, uint[] buffer, ref int bitposition)"

.PP
Definition at line \fB220\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "ulong Photon\&.Compression\&.QuatCrusher\&.Write (ulong c, ulong[] buffer, ref int bitposition)"

.PP
Definition at line \fB226\fP of file \fBQuatCrusher\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCompressLevel\fP Photon\&.Compression\&.QuatCrusher\&._compressLevel"

.PP
Definition at line \fB52\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.isStandalone"

.PP
Definition at line \fB81\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.local"

.PP
Definition at line \fB79\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.QC_ISPRO = QuatCompress\&.ISPRO\fC [static]\fP"

.PP
Definition at line \fB26\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.showEnableToggle"

.PP
Definition at line \fB82\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "Transform Photon\&.Compression\&.QuatCrusher\&.transform"

.PP
Definition at line \fB78\fP of file \fBQuatCrusher\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int?? Photon\&.Compression\&.QuatCrusher\&.Bits\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB31\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "\fBCompressLevel\fP? Photon\&.Compression\&.QuatCrusher\&.CompressLevel\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB53\fP of file \fBQuatCrusher\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.QuatCrusher\&.Enabled\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB84\fP of file \fBQuatCrusher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
