.TH "Photon.Pun.NestedComponentUtilities" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.NestedComponentUtilities
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T \fBEnsureRootComponentExists< T, NestedT >\fP (this Transform transform)"
.br
.ti -1c
.RI "static T \fBGetParentComponent< T >\fP (this Transform t)"
.br
.RI "Find T on supplied transform or any parent\&. "
.ti -1c
.RI "static void \fBGetNestedComponentsInParents< T >\fP (this Transform t, List< T > list)"
.br
.RI "Returns all T found between the child transform and its root\&. "
.ti -1c
.RI "static T \fBGetNestedComponentInChildren< T, NestedT >\fP (this Transform t, bool includeInactive)"
.br
.ti -1c
.RI "static T \fBGetNestedComponentInParent< T, NestedT >\fP (this Transform t)"
.br
.RI "Same as GetComponentInParent, but will always include inactive objects in search\&. "
.ti -1c
.RI "static T \fBGetNestedComponentInParents< T, NestedT >\fP (this Transform t)"
.br
.RI "UNTESTED "
.ti -1c
.RI "static void \fBGetNestedComponentsInParents< T, NestedT >\fP (this Transform t, List< T > list)"
.br
.RI "Finds components of type T on supplied transform, and every parent above that node, inclusively stopping on node StopSearchOnT component\&. "
.ti -1c
.RI "static List< T > \fBGetNestedComponentsInChildren< T, NestedT >\fP (this Transform t, List< T > list, bool includeInactive=true)"
.br
.RI "Same as GetComponentsInChildren, but will not recurse into children with component of the DontRecurseOnT type\&. "
.ti -1c
.RI "static List< T > \fBGetNestedComponentsInChildren< T >\fP (this Transform t, List< T > list, bool includeInactive=true, params System\&.Type[] stopOn)"
.br
.RI "Same as GetComponentsInChildren, but will not recurse into children with component of the DontRecurseOnT type\&. "
.ti -1c
.RI "static void \fBGetNestedComponentsInChildren< T, SearchT, NestedT >\fP (this Transform t, bool includeInactive, List< T > list)"
.br
.RI "Same as GetComponentsInChildren, but will not recurse into children with component of the NestedT type\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< System\&.Type, ICollection > \fBsearchLists\fP = new Dictionary<System\&.Type, ICollection>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static T Photon\&.Pun\&.NestedComponentUtilities\&.EnsureRootComponentExists< T, NestedT > (this Transform transform)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.TP
\fINestedT\fP : \fIComponent\fP
.PP
Definition at line \fB11\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static T Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentInChildren< T, NestedT > (this Transform t, bool includeInactive)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fINestedT\fP : \fIclass\fP
.PP
Definition at line \fB79\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static T Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentInParent< T, NestedT > (this Transform t)\fC [static]\fP"

.PP
Same as GetComponentInParent, but will always include inactive objects in search\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.br
\fIDontRecurseOnT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fINestedT\fP : \fIclass\fP
.PP
Definition at line \fB130\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static T Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentInParents< T, NestedT > (this Transform t)\fC [static]\fP"

.PP
UNTESTED 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.br
\fIStopSearchOnT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
Get the reverse list of transforms climbing for start up to netobject
.PP
Stop climbing at the NetObj (this is how we detect nesting
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fINestedT\fP : \fIclass\fP
.PP
Definition at line \fB163\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static List< T > Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentsInChildren< T > (this Transform t, List< T > list, bool includeInactive = \fCtrue\fP, params System\&.Type[] stopOn)\fC [static]\fP"

.PP
Same as GetComponentsInChildren, but will not recurse into children with component of the DontRecurseOnT type\&. This allows nesting of PhotonViews/NetObjects to be respected\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.br
\fIlist\fP Pass null and a reused list will be used\&. Consume immediately\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.PP
Definition at line \fB344\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static List< T > Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentsInChildren< T, NestedT > (this Transform t, List< T > list, bool includeInactive = \fCtrue\fP)\fC [static]\fP"

.PP
Same as GetComponentsInChildren, but will not recurse into children with component of the DontRecurseOnT type\&. This allows nesting of PhotonViews/NetObjects to be respected\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.br
\fIlist\fP Pass null and a reused list will be used\&. Consume immediately\&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fINestedT\fP : \fIclass\fP
.PP
Definition at line \fB272\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentsInChildren< T, SearchT, NestedT > (this Transform t, bool includeInactive, List< T > list)\fC [static]\fP"

.PP
Same as GetComponentsInChildren, but will not recurse into children with component of the NestedT type\&. This allows nesting of PhotonViews/NetObjects to be respected\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP Cast found components to this type\&. Typically Component, but any other class/interface will work as long as they are assignable from SearchT\&.
.br
\fISearchT\fP Find components of this class or interface type\&.
.br
\fIDontRecurseOnT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.br
\fIincludeInactive\fP 
.br
\fIlist\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fISearchT\fP : \fIclass\fP
.PP
Definition at line \fB435\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentsInParents< T > (this Transform t, List< T > list)\fC [static]\fP"

.PP
Returns all T found between the child transform and its root\&. Order in List from child to parent, with the root/parent most being last\&. 
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line \fB64\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.NestedComponentUtilities\&.GetNestedComponentsInParents< T, NestedT > (this Transform t, List< T > list)\fC [static]\fP"

.PP
Finds components of type T on supplied transform, and every parent above that node, inclusively stopping on node StopSearchOnT component\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.br
\fIStopSearchOnT\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIt\fP 
.br
\fIlist\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fINestedT\fP : \fIclass\fP
.PP
Definition at line \fB201\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SS "static T Photon\&.Pun\&.NestedComponentUtilities\&.GetParentComponent< T > (this Transform t)\fC [static]\fP"

.PP
Find T on supplied transform or any parent\&. Unlike GetComponentInParent, GameObjects do not need to be active to be found\&. 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line \fB39\fP of file \fBNestedComponentUtilities\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<System\&.Type, ICollection> Photon\&.Pun\&.NestedComponentUtilities\&.searchLists = new Dictionary<System\&.Type, ICollection>()\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBNestedComponentUtilities\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
