.TH "Photon.Realtime.RegionPinger" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.RegionPinger
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegionPinger\fP (\fBRegion\fP region, Action< \fBRegion\fP > onDoneCallback)"
.br
.ti -1c
.RI "bool \fBStart\fP ()"
.br
.RI "Starts the ping routine for the assigned region\&. "
.ti -1c
.RI "string \fBGetResults\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBResolveHost\fP (string hostName)"
.br
.RI "Attempts to resolve a hostname into an IP string or returns empty string if that fails\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBCurrentAttempt\fP = 0"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBAttempts\fP = 5"
.br
.ti -1c
.RI "static bool \fBIgnoreInitialAttempt\fP = true"
.br
.ti -1c
.RI "static int \fBMaxMilliseconsPerPing\fP = 800"
.br
.ti -1c
.RI "static int \fBPingWhenFailed\fP = \fBAttempts\fP * \fBMaxMilliseconsPerPing\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBDone\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB332\fP of file \fBRegionHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Realtime\&.RegionPinger\&.RegionPinger (\fBRegion\fP region, Action< \fBRegion\fP > onDoneCallback)"

.PP
Definition at line \fB350\fP of file \fBRegionHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Photon\&.Realtime\&.RegionPinger\&.GetResults ()"

.PP
Definition at line \fB598\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "static string Photon\&.Realtime\&.RegionPinger\&.ResolveHost (string hostName)\fC [static]\fP"

.PP
Attempts to resolve a hostname into an IP string or returns empty string if that fails\&. To be compatible with most platforms, the address family is checked like this:
.br
 if (ipAddress\&.AddressFamily\&.ToString()\&.Contains('6')) // ipv6\&.\&.\&. 
.PP
\fBParameters\fP
.RS 4
\fIhostName\fP Hostname to resolve\&.
.RE
.PP
\fBReturns\fP
.RS 4
IP string or empty string if resolution fails
.RE
.PP

.PP
Definition at line \fB612\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.RegionPinger\&.Start ()"

.PP
Starts the ping routine for the assigned region\&. Pinging runs in a ThreadPool worker item or (if needed) in a Thread\&. WebGL runs pinging on the Main Thread as coroutine\&. 
.PP
\fBReturns\fP
.RS 4
Always true\&.
.RE
.PP

.PP
Definition at line \fB408\fP of file \fBRegionHandler\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Realtime\&.RegionPinger\&.Attempts = 5\fC [static]\fP"

.PP
Definition at line \fB334\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.RegionPinger\&.CurrentAttempt = 0"

.PP
Definition at line \fB341\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.RegionPinger\&.IgnoreInitialAttempt = true\fC [static]\fP"

.PP
Definition at line \fB335\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.RegionPinger\&.MaxMilliseconsPerPing = 800\fC [static]\fP"

.PP
Definition at line \fB336\fP of file \fBRegionHandler\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.RegionPinger\&.PingWhenFailed = \fBAttempts\fP * \fBMaxMilliseconsPerPing\fP\fC [static]\fP"

.PP
Definition at line \fB337\fP of file \fBRegionHandler\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Realtime\&.RegionPinger\&.Done\fC [get]\fP"

.PP
Definition at line \fB343\fP of file \fBRegionHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
