.TH "Photon.Chat.ChatEventCode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ChatEventCode \- Wraps up internally used constants in \fBPhoton\fP \fBChat\fP events\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBChatMessages\fP = 0"
.br
.RI "(0) Event code for messages published in public channels\&."
.ti -1c
.RI "const byte \fBUsers\fP = 1"
.br
.RI "(1) Not Used\&. "
.ti -1c
.RI "const byte \fBPrivateMessage\fP = 2"
.br
.RI "(2) Event code for messages published in private channels"
.ti -1c
.RI "const byte \fBFriendsList\fP = 3"
.br
.RI "(3) Not Used\&. "
.ti -1c
.RI "const byte \fBStatusUpdate\fP = 4"
.br
.RI "(4) Event code for status updates\&. "
.ti -1c
.RI "const byte \fBSubscribe\fP = 5"
.br
.RI "(5) Event code for subscription acks\&. "
.ti -1c
.RI "const byte \fBUnsubscribe\fP = 6"
.br
.RI "(6) Event code for unsubscribe acks\&. "
.ti -1c
.RI "const byte \fBPropertiesChanged\fP = 7"
.br
.RI "(7) Event code for properties update\&. "
.ti -1c
.RI "const byte \fBUserSubscribed\fP = 8"
.br
.RI "(8) Event code for new user subscription to a channel where \fBChatChannel\&.PublishSubscribers\fP is enabled\&. "
.ti -1c
.RI "const byte \fBUserUnsubscribed\fP = 9"
.br
.RI "(9) Event code for when user unsubscribes from a channel where \fBChatChannel\&.PublishSubscribers\fP is enabled\&. "
.ti -1c
.RI "const byte \fBErrorInfo\fP = 10"
.br
.RI "(10) Event code for when the server sends an error to the client\&. "
.in -1c
.SH "Detailed Description"
.PP 
Wraps up internally used constants in \fBPhoton\fP \fBChat\fP events\&. 

You don't have to use them directly usually\&. 
.PP
Definition at line \fB12\fP of file \fBChatEventCode\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.ChatMessages = 0\fC [static]\fP"

.PP
(0) Event code for messages published in public channels\&.
.PP
Definition at line \fB15\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.ErrorInfo = 10\fC [static]\fP"

.PP
(10) Event code for when the server sends an error to the client\&. This is currently only used by \fBChat\fP WebHooks\&. 
.PP
Definition at line \fB37\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.FriendsList = 3\fC [static]\fP"

.PP
(3) Not Used\&. 
.PP
Definition at line \fB21\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.PrivateMessage = 2\fC [static]\fP"

.PP
(2) Event code for messages published in private channels
.PP
Definition at line \fB19\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.PropertiesChanged = 7\fC [static]\fP"

.PP
(7) Event code for properties update\&. 
.PP
Definition at line \fB29\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.StatusUpdate = 4\fC [static]\fP"

.PP
(4) Event code for status updates\&. 
.PP
Definition at line \fB23\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.Subscribe = 5\fC [static]\fP"

.PP
(5) Event code for subscription acks\&. 
.PP
Definition at line \fB25\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.Unsubscribe = 6\fC [static]\fP"

.PP
(6) Event code for unsubscribe acks\&. 
.PP
Definition at line \fB27\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.Users = 1\fC [static]\fP"

.PP
(1) Not Used\&. 
.PP
Definition at line \fB17\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.UserSubscribed = 8\fC [static]\fP"

.PP
(8) Event code for new user subscription to a channel where \fBChatChannel\&.PublishSubscribers\fP is enabled\&. 
.PP
Definition at line \fB32\fP of file \fBChatEventCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatEventCode\&.UserUnsubscribed = 9\fC [static]\fP"

.PP
(9) Event code for when user unsubscribes from a channel where \fBChatChannel\&.PublishSubscribers\fP is enabled\&. 
.PP
Definition at line \fB34\fP of file \fBChatEventCode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
