.TH "Photon.Pun.IPunObservable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.IPunObservable \- Defines the OnPhotonSerializeView method to make it easy to implement correctly for observable scripts\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBreakableFurniture\fP, \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.PlayerManager\fP, \fBPhoton\&.Pun\&.Demo\&.SlotRacer\&.PlayerControl\fP, \fBPhoton\&.Pun\&.PhotonAnimatorView\fP, \fBPhoton\&.Pun\&.PhotonRigidbody2DView\fP, \fBPhoton\&.Pun\&.PhotonRigidbodyView\fP, \fBPhoton\&.Pun\&.PhotonTransformView\fP, \fBPhoton\&.Pun\&.PhotonTransformViewClassic\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.CullingHandler\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.SmoothSyncMovement\fP, and \fBTimerScript\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.RI "Called by PUN several times per second, so that your script can write and read synchronization data for the \fBPhotonView\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines the OnPhotonSerializeView method to make it easy to implement correctly for observable scripts\&. 


.PP
Definition at line \fB10\fP of file \fBIPunCallbacks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
