.TH "Photon.Pun.Simple.SyncAnimatorEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncAnimatorEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits SyncObjectEditor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBpassThruTypeNames\fP = System\&.Enum\&.GetNames(typeof(\fBPassThruType\fP))"
.br
.ti -1c
.RI "static string \fBpassThruHelpText\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBInstructions\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBHelpURL\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTexturePath\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.OnEnable ()"
Initialize short term settings memory
.PP
Definition at line \fB110\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.OnInspectorGUI ()"
Passthrus
.PP
States
.PP
Layer Weights
.PP
Parameters
.PP
Definition at line \fB143\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.passThruHelpText\fC [static]\fP"

.PP
Definition at line \fB100\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SS "string [] Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.passThruTypeNames = System\&.Enum\&.GetNames(typeof(\fBPassThruType\fP))\fC [static]\fP"

.PP
Definition at line \fB99\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.HelpURL\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB36\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.Instructions\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncAnimatorEditor\&.TextTexturePath\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBSyncAnimatorEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
