.TH "Photon.Pun.Demo.Cockpit.LayoutElementMatchSize" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.LayoutElementMatchSize \- Force a LayoutElement to march a RectTransform sizeDelta\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayoutElement \fBlayoutElement\fP"
.br
.ti -1c
.RI "RectTransform \fBTarget\fP"
.br
.ti -1c
.RI "bool \fBMatchHeight\fP = true"
.br
.ti -1c
.RI "bool \fBMatchWidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Force a LayoutElement to march a RectTransform sizeDelta\&. 

Useful for complex child content 
.PP
Definition at line \fB16\fP of file \fBLayoutElementMatchSize\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayoutElement Photon\&.Pun\&.Demo\&.Cockpit\&.LayoutElementMatchSize\&.layoutElement"

.PP
Definition at line \fB19\fP of file \fBLayoutElementMatchSize\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.LayoutElementMatchSize\&.MatchHeight = true"

.PP
Definition at line \fB23\fP of file \fBLayoutElementMatchSize\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.LayoutElementMatchSize\&.MatchWidth"

.PP
Definition at line \fB24\fP of file \fBLayoutElementMatchSize\&.cs\fP\&.
.SS "RectTransform Photon\&.Pun\&.Demo\&.Cockpit\&.LayoutElementMatchSize\&.Target"

.PP
Definition at line \fB20\fP of file \fBLayoutElementMatchSize\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
