.TH "Photon.Compression.ArrayPackBitsExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ArrayPackBitsExt \- Experimental packers, that counts number of used bits for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsafe void \fBWritePackedBits\fP (ulong *uPtr, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE WritePacked Method\&. "
.ti -1c
.RI "static void \fBWritePackedBits\fP (this ulong[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static void \fBWritePackedBits\fP (this uint[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static void \fBWritePackedBits\fP (this byte[] buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static unsafe ulong \fBReadPackedBits\fP (ulong *uPtr, ref int bitposition, int bits)"
.br
.RI "Primary UNSAFE Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this ulong[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this uint[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static unsafe void \fBWriteSignedPackedBits\fP (ulong *uPtr, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE Write packed signed value\&. "
.ti -1c
.RI "static unsafe int \fBReadSignedPackedBits\fP (ulong *buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary UNSAFE Read packed signed value\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBits\fP (this ulong[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBits\fP (this ulong[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBits\fP (this uint[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBits\fP (this uint[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBits\fP (this byte[] buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBits\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.ti -1c
.RI "static void \fBWriteSignedPackedBits64\fP (this byte[] buffer, long value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static long \fBReadSignedPackedBits64\fP (this byte[] buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Experimental packers, that counts number of used bits for serialization\&. 

Effective for values that hover close to zero\&. 
.PP
Definition at line \fB34\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static ulong Photon\&.Compression\&.ArrayPackBitsExt\&.ReadPackedBits (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB154\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArrayPackBitsExt\&.ReadPackedBits (this uint[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB137\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArrayPackBitsExt\&.ReadPackedBits (this ulong[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB123\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static unsafe ulong Photon\&.Compression\&.ArrayPackBitsExt\&.ReadPackedBits (ulong * uPtr, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary UNSAFE Reader for PackedBits\&. 
.PP
Definition at line \fB109\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBitsExt\&.ReadSignedPackedBits (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB252\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBitsExt\&.ReadSignedPackedBits (this uint[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB229\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ArrayPackBitsExt\&.ReadSignedPackedBits (this ulong[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB207\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static unsafe int Photon\&.Compression\&.ArrayPackBitsExt\&.ReadSignedPackedBits (ulong * buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB186\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static long Photon\&.Compression\&.ArrayPackBitsExt\&.ReadSignedPackedBits64 (this byte[] buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB273\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WritePackedBits (this byte[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
\fBParameters\fP
.RS 4
\fIcountbits\fP 
.RE
.PP

.PP
Definition at line \fB92\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WritePackedBits (this uint[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
\fBParameters\fP
.RS 4
\fIcountbits\fP 
.RE
.PP

.PP
Definition at line \fB76\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WritePackedBits (this ulong[] buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
\fBParameters\fP
.RS 4
\fIcountbits\fP 
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static unsafe void Photon\&.Compression\&.ArrayPackBitsExt\&.WritePackedBits (ulong * uPtr, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE WritePacked Method\&. 
.PP
\fBParameters\fP
.RS 4
\fIcountbits\fP 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WriteSignedPackedBits (this byte[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB243\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WriteSignedPackedBits (this uint[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB220\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WriteSignedPackedBits (this ulong[] buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB198\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static unsafe void Photon\&.Compression\&.ArrayPackBitsExt\&.WriteSignedPackedBits (ulong * uPtr, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary UNSAFE Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB176\fP of file \fBArrayPackBitsExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArrayPackBitsExt\&.WriteSignedPackedBits64 (this byte[] buffer, long value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB264\fP of file \fBArrayPackBitsExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
