.TH "Photon.Pun.Demo.PunBasics.LoaderAnime" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.LoaderAnime \- \fBSimple\fP behaviour to animate particles around to create a typical 'Ajax Loader'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartLoaderAnimation\fP ()"
.br
.RI "Starts the loader animation\&. "
.ti -1c
.RI "void \fBStopLoaderAnimation\fP ()"
.br
.RI "Stops the loader animation\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP = 180f"
.br
.ti -1c
.RI "float \fBradius\fP = 1f"
.br
.ti -1c
.RI "GameObject \fBparticles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSimple\fP behaviour to animate particles around to create a typical 'Ajax Loader'\&. 

this is actually very important to visual inform the user that something is happening or better say that the application is not frozen, so a animation of some sort helps reassuring the user that the system is idle and well\&.
.PP
TODO: hide when connection failed\&.
.PP
Definition at line \fB22\fP of file \fBLoaderAnime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.LoaderAnime\&.StartLoaderAnimation ()"

.PP
Starts the loader animation\&. Becomes visible 
.PP
Definition at line \fB84\fP of file \fBLoaderAnime\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.LoaderAnime\&.StopLoaderAnimation ()"

.PP
Stops the loader animation\&. Becomes invisible 
.PP
Definition at line \fB94\fP of file \fBLoaderAnime\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.PunBasics\&.LoaderAnime\&.particles"

.PP
Definition at line \fB32\fP of file \fBLoaderAnime\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.PunBasics\&.LoaderAnime\&.radius = 1f"

.PP
Definition at line \fB30\fP of file \fBLoaderAnime\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.PunBasics\&.LoaderAnime\&.speed = 180f"

.PP
Definition at line \fB27\fP of file \fBLoaderAnime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
