.TH "Photon.Pun.Simple.SyncAdditiveMover.TRSDefinition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncAdditiveMover.TRSDefinition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.TRSDefinitionBase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBaddVector\fP = new Vector3(0, 0, 0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.TRSDefinition\&.addVector = new Vector3(0, 0, 0)"

.PP
Definition at line \fB29\fP of file \fBSyncAdditiveMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
