.TH "Photon.Compression.Internal.PackSupportedTypesAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.PackSupportedTypesAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackSupportedTypesAttribute\fP (Type \fBsupportedType\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Type \fBsupportedType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBPackFieldInterfaces\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.Internal\&.PackSupportedTypesAttribute\&.PackSupportedTypesAttribute (Type supportedType)"

.PP
Definition at line \fB20\fP of file \fBPackFieldInterfaces\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Type Photon\&.Compression\&.Internal\&.PackSupportedTypesAttribute\&.supportedType"

.PP
Definition at line \fB18\fP of file \fBPackFieldInterfaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
