.TH "Photon.Compression.PrimitivePackBitsExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.PrimitivePackBitsExt \- Experimental packers, that counts number of used bits for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ulong \fBWritePackedBits\fP (this ulong buffer, uint value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static uint \fBWritePackedBits\fP (this uint buffer, ushort value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static ushort \fBWritePackedBits\fP (this ushort buffer, byte value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary WritePacked Method "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this ulong buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this uint buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBReadPackedBits\fP (this ushort buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBits\&. "
.ti -1c
.RI "static ulong \fBWriteSignedPackedBits\fP (this ulong buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static uint \fBWriteSignedPackedBits\fP (this uint buffer, short value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static ushort \fBWriteSignedPackedBits\fP (this ushort buffer, sbyte value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write packed signed value\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBits\fP (this ulong buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.ti -1c
.RI "static short \fBReadSignedPackedBits\fP (this uint buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.ti -1c
.RI "static sbyte \fBReadSignedPackedBits\fP (this ushort buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Read packed signed value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Experimental packers, that counts number of used bits for serialization\&. 

Effective for values that hover close to zero\&. 
.PP
Definition at line \fB30\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static ulong Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadPackedBits (this uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB93\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadPackedBits (this ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB84\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadPackedBits (this ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBits\&. 
.PP
Definition at line \fB102\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static short Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadSignedPackedBits (this uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB162\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadSignedPackedBits (this ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB151\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static sbyte Photon\&.Compression\&.PrimitivePackBitsExt\&.ReadSignedPackedBits (this ushort buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Read packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB173\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitivePackBitsExt\&.WritePackedBits (this uint buffer, ushort value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
Definition at line \fB51\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBitsExt\&.WritePackedBits (this ulong buffer, uint value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
Definition at line \fB37\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitivePackBitsExt\&.WritePackedBits (this ushort buffer, byte value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary WritePacked Method 
.PP
Definition at line \fB65\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitivePackBitsExt\&.WriteSignedPackedBits (this uint buffer, short value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB128\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBitsExt\&.WriteSignedPackedBits (this ulong buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB118\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.PrimitivePackBitsExt\&.WriteSignedPackedBits (this ushort buffer, sbyte value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write packed signed value\&. ZigZag is employed to move the sign to the rightmost position\&. Packed values work best for serializing fields that have a large possible range, but are mostly hover closer to zero in value\&. 
.PP
Definition at line \fB138\fP of file \fBPrimitivePackBitsExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
