.TH "Photon.Pun.Demo.Cockpit.SendRateOnSerializeField" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.SendRateOnSerializeField \- \fBPhotonNetwork\&.SerializationRate\fP InputField  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEndEdit\fP (string value)"
.br
.ti -1c
.RI "void \fBSubmitForm\fP (string value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBPropertyValueInput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPhotonNetwork\&.SerializationRate\fP InputField 
.PP
Definition at line \fB16\fP of file \fBSendRateOnSerializeField\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.SendRateOnSerializeField\&.OnEndEdit (string value)"

.PP
Definition at line \fB50\fP of file \fBSendRateOnSerializeField\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.SendRateOnSerializeField\&.SubmitForm (string value)"

.PP
Definition at line \fB62\fP of file \fBSendRateOnSerializeField\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.SendRateOnSerializeField\&.PropertyValueInput"

.PP
Definition at line \fB19\fP of file \fBSendRateOnSerializeField\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
