.TH "Photon.Pun.PhotonTransformViewPositionModel" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewPositionModel
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInterpolateOptions\fP { \fBDisabled\fP, \fBFixedSpeed\fP, \fBEstimatedSpeed\fP, \fBSynchronizeValues\fP, \fBLerp\fP }"
.br
.ti -1c
.RI "enum \fBExtrapolateOptions\fP { \fBDisabled\fP, \fBSynchronizeValues\fP, \fBEstimateSpeedAndTurn\fP, \fBFixedSpeed\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBSynchronizeEnabled\fP"
.br
.ti -1c
.RI "bool \fBTeleportEnabled\fP = true"
.br
.ti -1c
.RI "float \fBTeleportIfDistanceGreaterThan\fP = 3f"
.br
.ti -1c
.RI "\fBInterpolateOptions\fP \fBInterpolateOption\fP = \fBInterpolateOptions\&.EstimatedSpeed\fP"
.br
.ti -1c
.RI "float \fBInterpolateMoveTowardsSpeed\fP = 1f"
.br
.ti -1c
.RI "float \fBInterpolateLerpSpeed\fP = 1f"
.br
.ti -1c
.RI "\fBExtrapolateOptions\fP \fBExtrapolateOption\fP = \fBExtrapolateOptions\&.Disabled\fP"
.br
.ti -1c
.RI "float \fBExtrapolateSpeed\fP = 1f"
.br
.ti -1c
.RI "bool \fBExtrapolateIncludingRoundTripTime\fP = true"
.br
.ti -1c
.RI "int \fBExtrapolateNumberOfStoredPositions\fP = 1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB162\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.PhotonTransformViewPositionModel\&.ExtrapolateOptions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fISynchronizeValues \fP\fP
.TP
\fB\fIEstimateSpeedAndTurn \fP\fP
.TP
\fB\fIFixedSpeed \fP\fP
.PP
Definition at line \fB174\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.PhotonTransformViewPositionModel\&.InterpolateOptions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fIFixedSpeed \fP\fP
.TP
\fB\fIEstimatedSpeed \fP\fP
.TP
\fB\fISynchronizeValues \fP\fP
.TP
\fB\fILerp \fP\fP
.PP
Definition at line \fB164\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.PhotonTransformViewPositionModel\&.ExtrapolateIncludingRoundTripTime = true"

.PP
Definition at line \fB195\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "int Photon\&.Pun\&.PhotonTransformViewPositionModel\&.ExtrapolateNumberOfStoredPositions = 1"

.PP
Definition at line \fB196\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "\fBExtrapolateOptions\fP Photon\&.Pun\&.PhotonTransformViewPositionModel\&.ExtrapolateOption = \fBExtrapolateOptions\&.Disabled\fP"

.PP
Definition at line \fB193\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewPositionModel\&.ExtrapolateSpeed = 1f"

.PP
Definition at line \fB194\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewPositionModel\&.InterpolateLerpSpeed = 1f"

.PP
Definition at line \fB191\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewPositionModel\&.InterpolateMoveTowardsSpeed = 1f"

.PP
Definition at line \fB189\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "\fBInterpolateOptions\fP Photon\&.Pun\&.PhotonTransformViewPositionModel\&.InterpolateOption = \fBInterpolateOptions\&.EstimatedSpeed\fP"

.PP
Definition at line \fB188\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformViewPositionModel\&.SynchronizeEnabled"

.PP
Definition at line \fB183\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformViewPositionModel\&.TeleportEnabled = true"

.PP
Definition at line \fB185\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewPositionModel\&.TeleportIfDistanceGreaterThan = 3f"

.PP
Definition at line \fB186\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
