.TH "Photon.Pun.Simple.MountSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.MountSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Utilities\&.SettingsScriptableObject< MountSettings >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBGetIndex\fP (string name)"
.br
.RI "Returns the index of the mount with the indicated name\&. "
.ti -1c
.RI "static string \fBGetName\fP (int index)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBmountTypeCount\fP"
.br
.ti -1c
.RI "static int \fBbitsForMountId\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBAllTrueMask\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBMountSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.Simple\&.MountSettings\&.GetIndex (string name)\fC [static]\fP"

.PP
Returns the index of the mount with the indicated name\&. If not found returns an index of -1\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP

.PP
Definition at line \fB62\fP of file \fBMountSettings\&.cs\fP\&.
.SS "static string Photon\&.Pun\&.Simple\&.MountSettings\&.GetName (int index)\fC [static]\fP"

.PP
Definition at line \fB67\fP of file \fBMountSettings\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.MountSettings\&.Initialize ()"

.PP
Definition at line \fB40\fP of file \fBMountSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.MountSettings\&.bitsForMountId\fC [static]\fP"

.PP
Definition at line \fB38\fP of file \fBMountSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.MountSettings\&.mountTypeCount\fC [static]\fP"

.PP
Definition at line \fB37\fP of file \fBMountSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.MountSettings\&.AllTrueMask\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB75\fP of file \fBMountSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
