.TH "Photon.Pun.Simple.TickEngineSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.TickEngineSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Utilities\&.SettingsScriptableObject< TickEngineSettings >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFrameCountEnum\fP { \fBFrameCount12\fP = 12, \fBFrameCount30\fP = 30, \fBFrameCount60\fP = 60, \fBFrameCount120\fP = 120 }"
.br
.ti -1c
.RI "enum \fBBufferCorrection\fP { \fBManual\fP, \fBAuto\fP }"
.br
.ti -1c
.RI "enum \fBLogInfoLevel\fP { \fBAll\fP, \fBWarningsAndErrors\fP, \fBErrorsOnly\fP, \fBNone\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBBootstrap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenableTickEngine\fP = true"
.br
.ti -1c
.RI "bool \fBsendWhenSolo\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBframeCount\fP"
.br
.ti -1c
.RI "static int \fBtargetBufferSize\fP"
.br
.ti -1c
.RI "static int \fBmaxBufferSize\fP"
.br
.ti -1c
.RI "static int \fBminBufferSize\fP"
.br
.ti -1c
.RI "static int \fBticksBeforeGrow\fP"
.br
.ti -1c
.RI "static int \fBticksBeforeShrink\fP"
.br
.ti -1c
.RI "static int \fBsendEveryXTick\fP = 3"
.br
.ti -1c
.RI "static int \fBhalfFrameCount\fP"
.br
.RI "cached runtime frame count values "
.ti -1c
.RI "static int \fBthirdFrameCount\fP"
.br
.ti -1c
.RI "static int \fBquaterFrameCount\fP"
.br
.ti -1c
.RI "static int \fBframeCountBits\fP"
.br
.ti -1c
.RI "static float \fBnetTickInterval\fP"
.br
.ti -1c
.RI "static float \fBnetTickIntervalInv\fP"
.br
.ti -1c
.RI "static float \fBtargetBufferInterval\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBLogInfoLevel\fP \fBLogLevel\fP\fC [get]\fP"
.br
.ti -1c
.RI "static int \fBMaxKeyframes\fP\fC [get]\fP"
.br
.RI "Get 1/3rd the value of the current frameCount setting\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Simple\&.TickEngineSettings\&.BufferCorrection\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIManual \fP\fP
.TP
\fB\fIAuto \fP\fP
.PP
Definition at line \fB30\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Simple\&.TickEngineSettings\&.FrameCountEnum\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFrameCount12 \fP\fP
.TP
\fB\fIFrameCount30 \fP\fP
.TP
\fB\fIFrameCount60 \fP\fP
.TP
\fB\fIFrameCount120 \fP\fP
.PP
Definition at line \fB29\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Simple\&.TickEngineSettings\&.LogInfoLevel\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAll \fP\fP
.TP
\fB\fIWarningsAndErrors \fP\fP
.TP
\fB\fIErrorsOnly \fP\fP
.TP
\fB\fINone \fP\fP
.PP
Definition at line \fB31\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.TickEngineSettings\&.Bootstrap ()\fC [static]\fP"

.PP
Definition at line \fB123\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.TickEngineSettings\&.enableTickEngine = true"

.PP
Definition at line \fB35\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.frameCount\fC [static]\fP"

.PP
Definition at line \fB51\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.frameCountBits\fC [static]\fP"

.PP
Definition at line \fB104\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.halfFrameCount\fC [static]\fP"

.PP
cached runtime frame count values 
.PP
Definition at line \fB101\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.maxBufferSize\fC [static]\fP"

.PP
Definition at line \fB65\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.minBufferSize\fC [static]\fP"

.PP
Definition at line \fB69\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.TickEngineSettings\&.netTickInterval\fC [static]\fP"

.PP
Definition at line \fB105\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.TickEngineSettings\&.netTickIntervalInv\fC [static]\fP"

.PP
Definition at line \fB105\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.quaterFrameCount\fC [static]\fP"

.PP
Definition at line \fB103\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.sendEveryXTick = 3\fC [static]\fP"

.PP
Definition at line \fB86\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.TickEngineSettings\&.sendWhenSolo = false"

.PP
Definition at line \fB39\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.TickEngineSettings\&.targetBufferInterval\fC [static]\fP"

.PP
Definition at line \fB105\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.targetBufferSize\fC [static]\fP"

.PP
Definition at line \fB61\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.thirdFrameCount\fC [static]\fP"

.PP
Definition at line \fB102\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.ticksBeforeGrow\fC [static]\fP"

.PP
Definition at line \fB74\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.ticksBeforeShrink\fC [static]\fP"

.PP
Definition at line \fB79\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBLogInfoLevel\fP Photon\&.Pun\&.Simple\&.TickEngineSettings\&.LogLevel\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB45\fP of file \fBTickEngineSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.TickEngineSettings\&.MaxKeyframes\fC [static]\fP, \fC [get]\fP"

.PP
Get 1/3rd the value of the current frameCount setting\&. Do not hotpath this method please\&. 
.PP
Definition at line \fB117\fP of file \fBTickEngineSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
