.TH "Photon.Pun.PhotonEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotonEditor\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitializeOnLoadMethod\fP ()"
.br
.ti -1c
.RI "static void \fBUpdateRpcList\fP ()"
.br
.ti -1c
.RI "static void \fBClearRpcList\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPunWizardText\fP \fBCurrentLang\fP = new \fBPunWizardText\fP()"
.br
.ti -1c
.RI "static string \fBCustomToken\fP = null"
.br
.RI "third parties custom token "
.ti -1c
.RI "static string \fBCustomContext\fP = null"
.br
.RI "third parties custom context "
.ti -1c
.RI "const string \fBUrlDevNet\fP = 'https://doc\&.photonengine\&.com/en\-us/pun/v2'"
.br
.ti -1c
.RI "const string \fBUrlCloudDashboard\fP = 'https://dashboard\&.photonengine\&.com/en\-US/account/signin?email='"
.br
.ti -1c
.RI "const string \fBUrlPunSettings\fP = 'https://doc\&.photonengine\&.com/en\-us/pun/v2/getting\-started/initial\-setup'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "virtual void \fBUiSetupApp\fP ()"
.br
.ti -1c
.RI "virtual void \fBUiMainWizard\fP ()"
.br
.ti -1c
.RI "virtual void \fBRegisterWithEmail\fP (string email)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMenuItemOpenWizard\fP ()"
.br
.ti -1c
.RI "static void \fBMenuItemHighlightSettings\fP ()"
.br
.ti -1c
.RI "static void \fBShowRegistrationWizard\fP ()"
.br
.RI "Creates an Editor window, showing the cloud-registration wizard for \fBPhoton\fP (entry point to setup PUN)\&."
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBscrollPos\fP = Vector2\&.zero"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static Type \fBWindowType\fP = typeof(\fBPhotonEditor\fP)"
.br
.ti -1c
.RI "static string \fBDocumentationLocation\fP = 'Assets/Photon/PhotonNetworking\-Documentation\&.pdf'"
.br
.ti -1c
.RI "static string \fBUrlFreeLicense\fP = 'https://dashboard\&.photonengine\&.com/en\-US/SelfHosted'"
.br
.ti -1c
.RI "static string \fBUrlForum\fP = 'https://forum\&.photonengine\&.com'"
.br
.ti -1c
.RI "static string \fBUrlCompare\fP = 'https://doc\&.photonengine\&.com/en\-us/realtime/current/getting\-started/onpremise\-or\-saas'"
.br
.ti -1c
.RI "static string \fBUrlHowToSetup\fP = 'https://doc\&.photonengine\&.com/en\-us/onpremise/current/getting\-started/photon\-server\-in\-5min'"
.br
.ti -1c
.RI "static string \fBUrlAppIDExplained\fP = 'https://doc\&.photonengine\&.com/en\-us/realtime/current/getting\-started/obtain\-your\-app\-id'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBPhotonEditor\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.PhotonEditor\&.PhotonEditor ()"

.PP
Definition at line \fB309\fP of file \fBPhotonEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.PhotonEditor\&.Awake ()\fC [protected]\fP"

.PP
Definition at line \fB314\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.ClearRpcList ()\fC [static]\fP"

.PP
Definition at line \fB837\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.InitializeOnLoadMethod ()\fC [static]\fP"

.PP
Definition at line \fB174\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.MenuItemHighlightSettings ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB166\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.MenuItemOpenWizard ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB154\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.PhotonEditor\&.OnGUI ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB345\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.PhotonEditor\&.RegisterWithEmail (string email)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB618\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.ShowRegistrationWizard ()\fC [static]\fP, \fC [protected]\fP"

.PP
Creates an Editor window, showing the cloud-registration wizard for \fBPhoton\fP (entry point to setup PUN)\&.
.PP
Definition at line \fB324\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.PhotonEditor\&.UiMainWizard ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB551\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.PhotonEditor\&.UiSetupApp ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB386\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonEditor\&.Update ()\fC [protected]\fP"

.PP
Definition at line \fB337\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PhotonEditor\&.UpdateRpcList ()\fC [static]\fP"

.PP
Definition at line \fB746\fP of file \fBPhotonEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPunWizardText\fP Photon\&.Pun\&.PhotonEditor\&.CurrentLang = new \fBPunWizardText\fP()\fC [static]\fP"

.PP
Definition at line \fB91\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.CustomContext = null\fC [static]\fP"

.PP
third parties custom context 
.PP
Definition at line \fB101\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.CustomToken = null\fC [static]\fP"

.PP
third parties custom token 
.PP
Definition at line \fB96\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.DocumentationLocation = 'Assets/Photon/PhotonNetworking\-Documentation\&.pdf'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB103\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "Vector2 Photon\&.Pun\&.PhotonEditor\&.scrollPos = Vector2\&.zero\fC [protected]\fP"

.PP
Definition at line \fB85\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.UrlAppIDExplained = 'https://doc\&.photonengine\&.com/en\-us/realtime/current/getting\-started/obtain\-your\-app\-id'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB115\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.PhotonEditor\&.UrlCloudDashboard = 'https://dashboard\&.photonengine\&.com/en\-US/account/signin?email='\fC [static]\fP"

.PP
Definition at line \fB117\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.UrlCompare = 'https://doc\&.photonengine\&.com/en\-us/realtime/current/getting\-started/onpremise\-or\-saas'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB111\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.PhotonEditor\&.UrlDevNet = 'https://doc\&.photonengine\&.com/en\-us/pun/v2'\fC [static]\fP"

.PP
Definition at line \fB107\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.UrlForum = 'https://forum\&.photonengine\&.com'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB109\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.UrlFreeLicense = 'https://dashboard\&.photonengine\&.com/en\-US/SelfHosted'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB105\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PhotonEditor\&.UrlHowToSetup = 'https://doc\&.photonengine\&.com/en\-us/onpremise/current/getting\-started/photon\-server\-in\-5min'\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB113\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.PhotonEditor\&.UrlPunSettings = 'https://doc\&.photonengine\&.com/en\-us/pun/v2/getting\-started/initial\-setup'\fC [static]\fP"

.PP
Definition at line \fB119\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "Type Photon\&.Pun\&.PhotonEditor\&.WindowType = typeof(\fBPhotonEditor\fP)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB83\fP of file \fBPhotonEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
