.TH "Photon.Realtime.GamePropertyKey" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.GamePropertyKey \- Class for constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBMaxPlayers\fP = 255"
.br
.RI "(255) Max number of players that 'fit' into this room\&. 0 is for 'unlimited'\&."
.ti -1c
.RI "const byte \fBIsVisible\fP = 254"
.br
.RI "(254) Makes this room listed or not in the lobby on master\&."
.ti -1c
.RI "const byte \fBIsOpen\fP = 253"
.br
.RI "(253) Allows more players to join a room (or not)\&."
.ti -1c
.RI "const byte \fBPlayerCount\fP = 252"
.br
.RI "(252) Current count of players in the room\&. Used only in the lobby on master\&."
.ti -1c
.RI "const byte \fBRemoved\fP = 251"
.br
.RI "(251) True if the room is to be removed from room listing (used in update to room list in lobby on master)"
.ti -1c
.RI "const byte \fBPropsListedInLobby\fP = 250"
.br
.RI "(250) A list of the room properties to pass to the \fBRoomInfo\fP list in a lobby\&. This is used in CreateRoom, which defines this list once per room\&."
.ti -1c
.RI "const byte \fBCleanupCacheOnLeave\fP = 249"
.br
.RI "(249) Equivalent of Operation Join parameter CleanupCacheOnLeave\&."
.ti -1c
.RI "const byte \fBMasterClientId\fP = (byte)248"
.br
.RI "(248) Code for MasterClientId, which is synced by server\&. "
.ti -1c
.RI "const byte \fBExpectedUsers\fP = (byte)247"
.br
.RI "(247) Code for ExpectedUsers in a room\&. Matchmaking keeps a slot open for the players with these userIDs\&."
.ti -1c
.RI "const byte \fBPlayerTtl\fP = (byte)246"
.br
.RI "(246) \fBPlayer\fP Time To Live\&. How long any player can be inactive (due to disconnect or leave) before the user gets removed from the playerlist (freeing a slot)\&."
.ti -1c
.RI "const byte \fBEmptyRoomTtl\fP = (byte)245"
.br
.RI "(245) \fBRoom\fP Time To Live\&. How long a room stays available (and in server-memory), after the last player becomes inactive\&. After this time, the room gets persisted or destroyed\&."
.in -1c
.SH "Detailed Description"
.PP 
Class for constants\&. 

These (byte) values are for 'well known' room/game properties used in \fBPhoton\fP LoadBalancing\&. 
.PP
These constants are used internally\&. 'Custom properties' have to use a string-type as key\&. They can be assigned at will\&. 
.PP
Definition at line \fB1288\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.CleanupCacheOnLeave = 249\fC [static]\fP"

.PP
(249) Equivalent of Operation Join parameter CleanupCacheOnLeave\&.
.PP
Definition at line \fB1309\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.EmptyRoomTtl = (byte)245\fC [static]\fP"

.PP
(245) \fBRoom\fP Time To Live\&. How long a room stays available (and in server-memory), after the last player becomes inactive\&. After this time, the room gets persisted or destroyed\&.
.PP
Definition at line \fB1322\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.ExpectedUsers = (byte)247\fC [static]\fP"

.PP
(247) Code for ExpectedUsers in a room\&. Matchmaking keeps a slot open for the players with these userIDs\&.
.PP
Definition at line \fB1316\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.IsOpen = 253\fC [static]\fP"

.PP
(253) Allows more players to join a room (or not)\&.
.PP
Definition at line \fB1297\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.IsVisible = 254\fC [static]\fP"

.PP
(254) Makes this room listed or not in the lobby on master\&.
.PP
Definition at line \fB1294\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.MasterClientId = (byte)248\fC [static]\fP"

.PP
(248) Code for MasterClientId, which is synced by server\&. When sent as op-parameter this is (byte)203\&. As room property this is (byte)248\&.
.PP
Tightly related to \fBParameterCode\&.MasterClientId\fP\&.
.PP
Definition at line \fB1313\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.MaxPlayers = 255\fC [static]\fP"

.PP
(255) Max number of players that 'fit' into this room\&. 0 is for 'unlimited'\&.
.PP
Definition at line \fB1291\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.PlayerCount = 252\fC [static]\fP"

.PP
(252) Current count of players in the room\&. Used only in the lobby on master\&.
.PP
Definition at line \fB1300\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.PlayerTtl = (byte)246\fC [static]\fP"

.PP
(246) \fBPlayer\fP Time To Live\&. How long any player can be inactive (due to disconnect or leave) before the user gets removed from the playerlist (freeing a slot)\&.
.PP
Definition at line \fB1319\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.PropsListedInLobby = 250\fC [static]\fP"

.PP
(250) A list of the room properties to pass to the \fBRoomInfo\fP list in a lobby\&. This is used in CreateRoom, which defines this list once per room\&.
.PP
Definition at line \fB1306\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.GamePropertyKey\&.Removed = 251\fC [static]\fP"

.PP
(251) True if the room is to be removed from room listing (used in update to room list in lobby on master)
.PP
Definition at line \fB1303\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
