.TH "Photon.Utilities.SingleUnityLayer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.SingleUnityLayer \- Single Layer at a time variant of LayerMask  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSet\fP (int _layerIndex)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator int\fP (\fBSingleUnityLayer\fP m)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBLayerIndex\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBMask\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Single Layer at a time variant of LayerMask 
.PP
Definition at line \fB274\fP of file \fBInspectorUtils\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static implicit Photon\&.Utilities\&.SingleUnityLayer\&.operator int (\fBSingleUnityLayer\fP m)\fC [static]\fP"

.PP
Definition at line \fB298\fP of file \fBInspectorUtils\&.cs\fP\&.
.SS "void Photon\&.Utilities\&.SingleUnityLayer\&.Set (int _layerIndex)"

.PP
Definition at line \fB285\fP of file \fBInspectorUtils\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Utilities\&.SingleUnityLayer\&.LayerIndex\fC [get]\fP"

.PP
Definition at line \fB280\fP of file \fBInspectorUtils\&.cs\fP\&.
.SS "int Photon\&.Utilities\&.SingleUnityLayer\&.Mask\fC [get]\fP"

.PP
Definition at line \fB293\fP of file \fBInspectorUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
