.TH "Photon.Realtime.ErrorInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.ErrorInfo \- Class wrapping the received \fBEventCode\&.ErrorInfo\fP event\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorInfo\fP (EventData eventData)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBInfo\fP"
.br
.RI "String containing information about the error\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class wrapping the received \fBEventCode\&.ErrorInfo\fP event\&. 

This is passed inside \fBIErrorInfoCallback\&.OnErrorInfo\fP callback\&. If you implement \fBIOnEventCallback\&.OnEvent\fP or \fBLoadBalancingClient\&.EventReceived\fP you will also get \fBEventCode\&.ErrorInfo\fP but not parsed\&.
.PP
In most cases this could be either:
.IP "1." 4
an error from webhooks plugin (if HasErrorInfo is enabled), read more here: https://doc.photonengine.com/en-us/realtime/current/gameplay/web-extensions/webhooks#options
.IP "2." 4
an error sent from a custom server plugin via PluginHost\&.BroadcastErrorInfoEvent, see example here: https://doc.photonengine.com/en-us/server/current/plugins/manual#handling_http_response
.IP "3." 4
an error sent from the server, for example, when the limit of cached events has been exceeded in the room (all clients will be disconnected and the room will be closed in this case) read more here: https://doc.photonengine.com/en-us/realtime/current/gameplay/cached-events#special_considerations 
.PP

.PP
Definition at line \fB4414\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Realtime\&.ErrorInfo\&.ErrorInfo (EventData eventData)"

.PP
Definition at line \fB4421\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Realtime\&.ErrorInfo\&.ToString ()"

.PP
Definition at line \fB4426\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Photon\&.Realtime\&.ErrorInfo\&.Info"

.PP
String containing information about the error\&. 
.PP
Definition at line \fB4419\fP of file \fBLoadBalancingClient\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
