.TH "Photon.Pun.Simple.IOnRootVitalBecameZero" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnRootVitalBecameZero
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnRootVitalBecameZero\fP (\fBVital\fP vital, \fBIVitalsContactReactor\fP causeOfDeath)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBSyncVitals\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnRootVitalBecameZero\&.OnRootVitalBecameZero (\fBVital\fP vital, \fBIVitalsContactReactor\fP causeOfDeath)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
