.TH "Photon.Pun.SceneSetting" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.SceneSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SceneAsset \fBsceneAsset\fP"
.br
.ti -1c
.RI "string \fBsceneName\fP"
.br
.ti -1c
.RI "int \fBminViewId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.SceneSetting\&.minViewId"

.PP
Definition at line \fB26\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SS "SceneAsset Photon\&.Pun\&.SceneSetting\&.sceneAsset"

.PP
Definition at line \fB24\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SS "string Photon\&.Pun\&.SceneSetting\&.sceneName"

.PP
Definition at line \fB25\fP of file \fBPunSceneSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
