.TH "Photon.Compression.NormCompress.NormCompressCodec" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.NormCompress.NormCompressCodec
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNormCompressCodec\fP (int \fBbits\fP, float \fBencoder\fP, float \fBdecoder\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly int \fBbits\fP"
.br
.ti -1c
.RI "readonly float \fBencoder\fP"
.br
.ti -1c
.RI "readonly float \fBdecoder\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBNormCompress\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.NormCompress\&.NormCompressCodec\&.NormCompressCodec (int bits, float encoder, float decoder)"

.PP
Definition at line \fB37\fP of file \fBNormCompress\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly int Photon\&.Compression\&.NormCompress\&.NormCompressCodec\&.bits"

.PP
Definition at line \fB34\fP of file \fBNormCompress\&.cs\fP\&.
.SS "readonly float Photon\&.Compression\&.NormCompress\&.NormCompressCodec\&.decoder"

.PP
Definition at line \fB35\fP of file \fBNormCompress\&.cs\fP\&.
.SS "readonly float Photon\&.Compression\&.NormCompress\&.NormCompressCodec\&.encoder"

.PP
Definition at line \fB35\fP of file \fBNormCompress\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
