.TH "Photon.Pun.Simple.IContactSystem" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IContactSystem
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.IInventorySystem< T >\fP, and \fBPhoton\&.Pun\&.Simple\&.IVitalsSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsumption\fP \fBTryTrigger\fP (\fBIContactReactor\fP reactor, \fBContactEvent\fP contactEvent, int compatibleMounts)"
.br
.ti -1c
.RI "\fBMount\fP \fBTryPickup\fP (\fBIContactReactor\fP reactor, \fBContactEvent\fP contactEvent)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNetObject\fP \fBNetObj\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBViewID\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsMine\fP\fC [get]\fP"
.br
.ti -1c
.RI "byte \fBSystemIndex\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBMount\fP \fBDefaultMount\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBValidMountsMask\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIContactGroupMask\fP \fBValidContactGroups\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBIContactSystem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMount\fP Photon\&.Pun\&.Simple\&.IContactSystem\&.TryPickup (\fBIContactReactor\fP reactor, \fBContactEvent\fP contactEvent)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.Inventory< T >\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP\&.
.SS "\fBConsumption\fP Photon\&.Pun\&.Simple\&.IContactSystem\&.TryTrigger (\fBIContactReactor\fP reactor, \fBContactEvent\fP contactEvent, int compatibleMounts)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, and \fBPhoton\&.Pun\&.Simple\&.Inventory< T >\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBMount\fP Photon\&.Pun\&.Simple\&.IContactSystem\&.DefaultMount\fC [get]\fP"

.PP
Definition at line \fB21\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.IContactSystem\&.IsMine\fC [get]\fP"

.PP
Definition at line \fB19\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "\fBNetObject\fP Photon\&.Pun\&.Simple\&.IContactSystem\&.NetObj\fC [get]\fP"

.PP
Definition at line \fB17\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.Simple\&.IContactSystem\&.SystemIndex\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB20\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "\fBIContactGroupMask\fP Photon\&.Pun\&.Simple\&.IContactSystem\&.ValidContactGroups\fC [get]\fP"

.PP
Definition at line \fB23\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.IContactSystem\&.ValidMountsMask\fC [get]\fP"

.PP
Definition at line \fB22\fP of file \fBIContactSystem\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.IContactSystem\&.ViewID\fC [get]\fP"

.PP
Definition at line \fB18\fP of file \fBIContactSystem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
