.TH "Photon.Pun.Simple.ContactGroups.ContactGroupSelector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.ContactGroupSelector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.IContactGroupMask\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.RI "Default is an index of 0 and a layermask of 0 "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int? \fBMask\fP\fC [get]\fP"
.br
.RI "Default is an index of 0 and a layermask of 0 "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBContactGroupSelector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSelector\&.index"

.PP
Default is an index of 0 and a layermask of 0 
.PP
Definition at line \fB20\fP of file \fBContactGroupSelector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int? Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSelector\&.Mask\fC [get]\fP"

.PP
Default is an index of 0 and a layermask of 0 
.PP
Definition at line \fB26\fP of file \fBContactGroupSelector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
