.TH "Photon.Chat.ChatPeer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ChatPeer \- Provides basic operations of the \fBPhoton\fP \fBChat\fP server\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits PhotonPeer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBChatPeer\fP (IPhotonPeerListener listener, ConnectionProtocol protocol)"
.br
.RI "\fBChat\fP Peer constructor\&. "
.ti -1c
.RI "bool \fBConnect\fP ()"
.br
.RI "Connects to NameServer\&. "
.ti -1c
.RI "bool \fBAuthenticateOnNameServer\fP (string appId, string appVersion, string region, \fBAuthenticationValues\fP authValues)"
.br
.RI "Authenticates on NameServer\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNameServerHost\fP = 'ns\&.photonengine\&.io'"
.br
.RI "Name Server Host Name for \fBPhoton\fP Cloud\&. Without port and without any prefix\&."
.ti -1c
.RI "ushort \fBNameServerPortOverride\fP"
.br
.RI "If not zero, this is used for the name server port on connect\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNameServerAddress\fP\fC [get]\fP"
.br
.RI "Name Server Address for \fBPhoton\fP Cloud (based on current protocol)\&. You can use the default values and usually won't have to set this value\&."
.in -1c
.SH "Detailed Description"
.PP 
Provides basic operations of the \fBPhoton\fP \fBChat\fP server\&. 

This internal class is used by public \fBChatClient\fP\&. 
.PP
Definition at line \fB27\fP of file \fBChatPeer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Chat\&.ChatPeer\&.ChatPeer (IPhotonPeerListener listener, ConnectionProtocol protocol)"

.PP
\fBChat\fP Peer constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIlistener\fP \fBChat\fP listener implementation\&.
.br
\fIprotocol\fP Protocol to be used by the peer\&.
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBChatPeer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Photon\&.Chat\&.ChatPeer\&.AuthenticateOnNameServer (string appId, string appVersion, string region, \fBAuthenticationValues\fP authValues)"

.PP
Authenticates on NameServer\&. 
.PP
\fBReturns\fP
.RS 4
If the authentication operation request could be sent\&.
.RE
.PP

.PP
Definition at line \fB142\fP of file \fBChatPeer\&.cs\fP\&.
.SS "bool Photon\&.Chat\&.ChatPeer\&.Connect ()"

.PP
Connects to NameServer\&. 
.PP
\fBReturns\fP
.RS 4
If the connection attempt could be sent\&.
.RE
.PP

.PP
Definition at line \fB130\fP of file \fBChatPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Chat\&.ChatPeer\&.NameServerHost = 'ns\&.photonengine\&.io'"

.PP
Name Server Host Name for \fBPhoton\fP Cloud\&. Without port and without any prefix\&.
.PP
Definition at line \fB30\fP of file \fBChatPeer\&.cs\fP\&.
.SS "ushort Photon\&.Chat\&.ChatPeer\&.NameServerPortOverride"

.PP
If not zero, this is used for the name server port on connect\&. Independent of protocol (so this better matches)\&. Set by \fBChatClient\&.ConnectUsingSettings\fP\&.
.PP
This is reset when the protocol fallback is used\&.
.PP
Definition at line \fB97\fP of file \fBChatPeer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Chat\&.ChatPeer\&.NameServerAddress\fC [get]\fP"

.PP
Name Server Address for \fBPhoton\fP Cloud (based on current protocol)\&. You can use the default values and usually won't have to set this value\&.
.PP
Definition at line \fB36\fP of file \fBChatPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
