.TH "Photon.Pun.UtilityScripts.TextButtonTransition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.TextButtonTransition \- Use this on Button texts to have some color transition on the text as well without corrupting button's behaviour\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Selectable \fBSelectable\fP"
.br
.RI "The selectable Component\&. "
.ti -1c
.RI "Color \fBNormalColor\fP = Color\&.white"
.br
.RI "The color of the normal of the transition state\&. "
.ti -1c
.RI "Color \fBHoverColor\fP = Color\&.black"
.br
.RI "The color of the hover of the transition state\&. "
.in -1c
.SH "Detailed Description"
.PP 
Use this on Button texts to have some color transition on the text as well without corrupting button's behaviour\&. 


.PP
Definition at line \fB21\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.Awake ()"

.PP
Definition at line \fB41\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.OnDisable ()"

.PP
Definition at line \fB51\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.OnEnable ()"

.PP
Definition at line \fB46\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.OnPointerEnter (PointerEventData eventData)"

.PP
Definition at line \fB56\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.OnPointerExit (PointerEventData eventData)"

.PP
Definition at line \fB63\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.HoverColor = Color\&.black"

.PP
The color of the hover of the transition state\&. 
.PP
Definition at line \fB39\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "Color Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.NormalColor = Color\&.white"

.PP
The color of the normal of the transition state\&. 
.PP
Definition at line \fB34\fP of file \fBTextButtonTransition\&.cs\fP\&.
.SS "Selectable Photon\&.Pun\&.UtilityScripts\&.TextButtonTransition\&.Selectable"

.PP
The selectable Component\&. 
.PP
Definition at line \fB29\fP of file \fBTextButtonTransition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
