.TH "Photon.Compression.ByteConverter" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ByteConverter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetBytes\fP (byte[] target, int count=4)"
.br
.ti -1c
.RI "void \fBExtractByteArray\fP (byte[] targetArray)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (byte[] bytes)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Byte val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (SByte val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Char val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (UInt32 val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Int32 val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (UInt64 val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Int64 val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Single val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Double val)"
.br
.ti -1c
.RI "static implicit \fBoperator ByteConverter\fP (Boolean val)"
.br
.ti -1c
.RI "static implicit \fBoperator Byte\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator SByte\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Char\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator UInt16\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Int16\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator UInt32\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Int32\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator UInt64\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Int64\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Single\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Double\fP (\fBByteConverter\fP bc)"
.br
.ti -1c
.RI "static implicit \fBoperator Boolean\fP (\fBByteConverter\fP bc)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Single \fBfloat32\fP"
.br
.ti -1c
.RI "Double \fBfloat64\fP"
.br
.ti -1c
.RI "SByte \fBint8\fP"
.br
.ti -1c
.RI "Int16 \fBint16\fP"
.br
.ti -1c
.RI "UInt16 \fBuint16\fP"
.br
.ti -1c
.RI "Char \fBcharacter\fP"
.br
.ti -1c
.RI "Int32 \fBint32\fP"
.br
.ti -1c
.RI "UInt32 \fBuint32\fP"
.br
.ti -1c
.RI "Int64 \fBint64\fP"
.br
.ti -1c
.RI "UInt64 \fBuint64\fP"
.br
.ti -1c
.RI "Byte \fBbyte0\fP"
.br
.ti -1c
.RI "Byte \fBbyte1\fP"
.br
.ti -1c
.RI "Byte \fBbyte2\fP"
.br
.ti -1c
.RI "Byte \fBbyte3\fP"
.br
.ti -1c
.RI "Byte \fBbyte4\fP"
.br
.ti -1c
.RI "Byte \fBbyte5\fP"
.br
.ti -1c
.RI "Byte \fBbyte6\fP"
.br
.ti -1c
.RI "Byte \fBbyte7\fP"
.br
.ti -1c
.RI "uint \fBuint16_B\fP"
.br
.RI "The upper 4 bytes of this 8 byte struct, returned as a uint\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Byte \fBthis[int index]\fP\fC [get]\fP"
.br
.RI "A Byte indexer\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBByteConverter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Compression\&.ByteConverter\&.ExtractByteArray (byte[] targetArray)"

.PP
Definition at line \fB206\fP of file \fBByteConverter\&.cs\fP\&.
.SS "void Photon\&.Compression\&.ByteConverter\&.GetBytes (byte[] target, int count = \fC4\fP)"

.PP
Definition at line \fB84\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Boolean (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB235\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Byte (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB224\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Boolean val)\fC [static]\fP"

.PP
Definition at line \fB199\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Byte val)\fC [static]\fP"

.PP
Definition at line \fB136\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (byte[] bytes)\fC [static]\fP"

.PP
Definition at line \fB118\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Char val)\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Double val)\fC [static]\fP"

.PP
Definition at line \fB192\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Int32 val)\fC [static]\fP"

.PP
Definition at line \fB164\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Int64 val)\fC [static]\fP"

.PP
Definition at line \fB178\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (SByte val)\fC [static]\fP"

.PP
Definition at line \fB143\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (Single val)\fC [static]\fP"

.PP
Definition at line \fB185\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (UInt32 val)\fC [static]\fP"

.PP
Definition at line \fB157\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator \fBByteConverter\fP (UInt64 val)\fC [static]\fP"

.PP
Definition at line \fB171\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Char (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB226\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Double (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB234\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Int16 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB228\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Int32 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB230\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Int64 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB232\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator SByte (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB225\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator Single (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB233\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator UInt16 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB227\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator UInt32 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB229\fP of file \fBByteConverter\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.ByteConverter\&.operator UInt64 (\fBByteConverter\fP bc)\fC [static]\fP"

.PP
Definition at line \fB231\fP of file \fBByteConverter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte0"

.PP
Definition at line \fB62\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte1"

.PP
Definition at line \fB64\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte2"

.PP
Definition at line \fB66\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte3"

.PP
Definition at line \fB68\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte4"

.PP
Definition at line \fB70\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte5"

.PP
Definition at line \fB72\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte6"

.PP
Definition at line \fB74\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Byte Photon\&.Compression\&.ByteConverter\&.byte7"

.PP
Definition at line \fB76\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Char Photon\&.Compression\&.ByteConverter\&.character"

.PP
Definition at line \fB51\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Single Photon\&.Compression\&.ByteConverter\&.float32"

.PP
Definition at line \fB41\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Double Photon\&.Compression\&.ByteConverter\&.float64"

.PP
Definition at line \fB43\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Int16 Photon\&.Compression\&.ByteConverter\&.int16"

.PP
Definition at line \fB47\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Int32 Photon\&.Compression\&.ByteConverter\&.int32"

.PP
Definition at line \fB53\fP of file \fBByteConverter\&.cs\fP\&.
.SS "Int64 Photon\&.Compression\&.ByteConverter\&.int64"

.PP
Definition at line \fB57\fP of file \fBByteConverter\&.cs\fP\&.
.SS "SByte Photon\&.Compression\&.ByteConverter\&.int8"

.PP
Definition at line \fB45\fP of file \fBByteConverter\&.cs\fP\&.
.SS "UInt16 Photon\&.Compression\&.ByteConverter\&.uint16"

.PP
Definition at line \fB49\fP of file \fBByteConverter\&.cs\fP\&.
.SS "uint Photon\&.Compression\&.ByteConverter\&.uint16_B"

.PP
The upper 4 bytes of this 8 byte struct, returned as a uint\&. 
.PP
Definition at line \fB82\fP of file \fBByteConverter\&.cs\fP\&.
.SS "UInt32 Photon\&.Compression\&.ByteConverter\&.uint32"

.PP
Definition at line \fB55\fP of file \fBByteConverter\&.cs\fP\&.
.SS "UInt64 Photon\&.Compression\&.ByteConverter\&.uint64"

.PP
Definition at line \fB59\fP of file \fBByteConverter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Byte Photon\&.Compression\&.ByteConverter\&.this[int index]\fC [get]\fP"

.PP
A Byte indexer\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP Byte index\&.
.RE
.PP
\fBReturns\fP
.RS 4
Value of the byte at given index\&.
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBByteConverter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
