.TH "Photon.Pun.Demo.Cockpit.PunCockpitEmbed" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.PunCockpitEmbed \- Use this in scenes you want to leave Control for connection and pun related commands to \fBCockpit\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBEmbeddCockpit\fP = true"
.br
.ti -1c
.RI "string \fBCockpitGameTitle\fP = ''"
.br
.ti -1c
.RI "GameObject \fBLoadingIndicator\fP"
.br
.ti -1c
.RI "\fBConnectAndJoinRandom\fP \fBAutoConnect\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use this in scenes you want to leave Control for connection and pun related commands to \fBCockpit\fP\&. 

It requires ConnectAndJoinRandom, which it will control for connecting should the \fBCockpit\fP scene not be present or succesfully loaded\&. 
.PP
Definition at line \fB24\fP of file \fBPunCockpitEmbed\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpitEmbed\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. When this is called, you can access the existing players in \fBRoom\&.Players\fP, their custom properties and \fBRoom\&.CustomProperties\fP\&.
.PP
In this callback, you could create player objects\&. For example in Unity, instantiate a prefab for the player\&.
.PP
If you want a match to be started 'actively', enable the user to signal 'ready' (using OpRaiseEvent or a Custom Property)\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB77\fP of file \fBPunCockpitEmbed\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConnectAndJoinRandom\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpitEmbed\&.AutoConnect"

.PP
Definition at line \fB33\fP of file \fBPunCockpitEmbed\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpitEmbed\&.CockpitGameTitle = ''"

.PP
Definition at line \fB30\fP of file \fBPunCockpitEmbed\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpitEmbed\&.EmbeddCockpit = true"

.PP
Definition at line \fB29\fP of file \fBPunCockpitEmbed\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpitEmbed\&.LoadingIndicator"

.PP
Definition at line \fB32\fP of file \fBPunCockpitEmbed\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
