.TH "Photon.Pun.Demo.PunBasics.GameManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.GameManager \- Game manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPlayerEnteredRoom\fP (\fBPlayer\fP other)"
.br
.RI "Called when a \fBPhoton\fP Player got connected\&. "
.ti -1c
.RI "override void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP other)"
.br
.RI "Called when a \fBPhoton\fP Player got disconnected\&. "
.ti -1c
.RI "override void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local player left the room\&. "
.ti -1c
.RI "void \fBLeaveRoom\fP ()"
.br
.ti -1c
.RI "void \fBQuitApplication\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBGameManager\fP \fBInstance\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Game manager\&. 

Connects and watch \fBPhoton\fP Status, Instantiate Player Deals with quiting the room and the game Deals with level loading (outside the in room synchronization) 
.PP
Definition at line \fB26\fP of file \fBGameManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.LeaveRoom ()"

.PP
Definition at line \fB144\fP of file \fBGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.OnLeftRoom ()\fC [virtual]\fP"

.PP
Called when the local player left the room\&. We need to load the launcher scene\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB135\fP of file \fBGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.OnPlayerEnteredRoom (\fBPlayer\fP other)\fC [virtual]\fP"

.PP
Called when a \fBPhoton\fP Player got connected\&. We need to then load a bigger scene\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Other\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB104\fP of file \fBGameManager\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.OnPlayerLeftRoom (\fBPlayer\fP other)\fC [virtual]\fP"

.PP
Called when a \fBPhoton\fP Player got disconnected\&. We need to load a smaller scene\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP Other\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB120\fP of file \fBGameManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.QuitApplication ()"

.PP
Definition at line \fB149\fP of file \fBGameManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameManager\fP Photon\&.Pun\&.Demo\&.PunBasics\&.GameManager\&.Instance\fC [static]\fP"

.PP
Definition at line \fB31\fP of file \fBGameManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
