.TH "Photon.Pun.Simple.MountSelector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.MountSelector
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMountSelector\fP (int index)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator int\fP (\fBMountSelector\fP selector)"
.br
.ti -1c
.RI "static implicit \fBoperator MountSelector\fP (int \fBid\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.RI "Default is an index of 0 and a layermask of 0 "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBMountSelector\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.MountSelector\&.MountSelector (int index)"

.PP
Definition at line \fB25\fP of file \fBMountSelector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static implicit Photon\&.Pun\&.Simple\&.MountSelector\&.operator int (\fBMountSelector\fP selector)\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBMountSelector\&.cs\fP\&.
.SS "static implicit Photon\&.Pun\&.Simple\&.MountSelector\&.operator \fBMountSelector\fP (int id)\fC [static]\fP"

.PP
Definition at line \fB34\fP of file \fBMountSelector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.MountSelector\&.id"

.PP
Default is an index of 0 and a layermask of 0 
.PP
Definition at line \fB21\fP of file \fBMountSelector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
