.TH "Photon.Pun.UtilityScripts.CellTreeNode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.CellTreeNode \- Represents a single node of the tree\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBENodeType\fP : byte { \fBRoot\fP = 0, \fBNode\fP = 1, \fBLeaf\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCellTreeNode\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBCellTreeNode\fP (byte id, \fBENodeType\fP nodeType, \fBCellTreeNode\fP parent)"
.br
.RI "Constructor to define the ID and the node type as well as setting a parent node\&. "
.ti -1c
.RI "void \fBAddChild\fP (\fBCellTreeNode\fP child)"
.br
.RI "Adds the given child to the node\&. "
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.RI "Draws the cell in the editor\&. "
.ti -1c
.RI "void \fBGetActiveCells\fP (List< byte > activeCells, bool yIsUpAxis, Vector3 position)"
.br
.RI "Gathers all cell IDs the player is currently inside or nearby\&. "
.ti -1c
.RI "bool \fBIsPointInsideCell\fP (bool yIsUpAxis, Vector3 point)"
.br
.RI "Checks if the given point is inside the cell\&. "
.ti -1c
.RI "bool \fBIsPointNearCell\fP (bool yIsUpAxis, Vector3 point)"
.br
.RI "Checks if the given point is near the cell\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBId\fP"
.br
.RI "Represents the unique ID of the cell\&. "
.ti -1c
.RI "Vector3 \fBCenter\fP"
.br
.RI "Represents the center, top-left or bottom-right position of the cell or the size of the cell\&. "
.ti -1c
.RI "Vector3 \fBSize\fP"
.br
.ti -1c
.RI "Vector3 \fBTopLeft\fP"
.br
.ti -1c
.RI "Vector3 \fBBottomRight\fP"
.br
.ti -1c
.RI "\fBENodeType\fP \fBNodeType\fP"
.br
.RI "Describes the current node type of the cell tree node\&. "
.ti -1c
.RI "\fBCellTreeNode\fP \fBParent\fP"
.br
.RI "Reference to the parent node\&. "
.ti -1c
.RI "List< \fBCellTreeNode\fP > \fBChilds\fP"
.br
.RI "A list containing all child nodes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a single node of the tree\&. 


.PP
Definition at line \fB304\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.UtilityScripts\&.CellTreeNode\&.ENodeType\fP : byte"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRoot \fP\fP
.TP
\fB\fINode \fP\fP
.TP
\fB\fILeaf \fP\fP
.PP
Definition at line \fB306\fP of file \fBCullArea\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.CellTreeNode ()"

.PP
Default constructor\&. 
.PP
Definition at line \fB348\fP of file \fBCullArea\&.cs\fP\&.
.SS "Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.CellTreeNode (byte id, \fBENodeType\fP nodeType, \fBCellTreeNode\fP parent)"

.PP
Constructor to define the ID and the node type as well as setting a parent node\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID of the cell is used as the interest group\&.
.br
\fInodeType\fP The node type of the cell tree node\&.
.br
\fIparent\fP The parent node of the cell tree node\&.
.RE
.PP

.PP
Definition at line \fB358\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.AddChild (\fBCellTreeNode\fP child)"

.PP
Adds the given child to the node\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP The child which is added to the node\&.
.RE
.PP

.PP
Definition at line \fB371\fP of file \fBCullArea\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Draw ()"

.PP
Draws the cell in the editor\&. 
.PP
Definition at line \fB384\fP of file \fBCullArea\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.GetActiveCells (List< byte > activeCells, bool yIsUpAxis, Vector3 position)"

.PP
Gathers all cell IDs the player is currently inside or nearby\&. 
.PP
\fBParameters\fP
.RS 4
\fIactiveCells\fP The list to add all cell IDs to the player is currently inside or nearby\&.
.br
\fIyIsUpAxis\fP Describes if the y-axis is used as up-axis\&.
.br
\fIposition\fP The current position of the player\&.
.RE
.PP

.PP
Definition at line \fB411\fP of file \fBCullArea\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.IsPointInsideCell (bool yIsUpAxis, Vector3 point)"

.PP
Checks if the given point is inside the cell\&. 
.PP
\fBParameters\fP
.RS 4
\fIyIsUpAxis\fP Describes if the y-axis is used as up-axis\&.
.br
\fIpoint\fP The point to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the point is inside the cell, false if the point is not inside the cell\&.
.RE
.PP

.PP
Definition at line \fB450\fP of file \fBCullArea\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.IsPointNearCell (bool yIsUpAxis, Vector3 point)"

.PP
Checks if the given point is near the cell\&. 
.PP
\fBParameters\fP
.RS 4
\fIyIsUpAxis\fP Describes if the y-axis is used as up-axis\&.
.br
\fIpoint\fP The point to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the point is near the cell, false if the point is too far away\&.
.RE
.PP

.PP
Definition at line \fB481\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.BottomRight"

.PP
Definition at line \fB322\fP of file \fBCullArea\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Center"

.PP
Represents the center, top-left or bottom-right position of the cell or the size of the cell\&. 
.PP
Definition at line \fB322\fP of file \fBCullArea\&.cs\fP\&.
.SS "List<\fBCellTreeNode\fP> Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Childs"

.PP
A list containing all child nodes\&. 
.PP
Definition at line \fB337\fP of file \fBCullArea\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Id"

.PP
Represents the unique ID of the cell\&. 
.PP
Definition at line \fB316\fP of file \fBCullArea\&.cs\fP\&.
.SS "\fBENodeType\fP Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.NodeType"

.PP
Describes the current node type of the cell tree node\&. 
.PP
Definition at line \fB327\fP of file \fBCullArea\&.cs\fP\&.
.SS "\fBCellTreeNode\fP Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Parent"

.PP
Reference to the parent node\&. 
.PP
Definition at line \fB332\fP of file \fBCullArea\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.Size"

.PP
Definition at line \fB322\fP of file \fBCullArea\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.UtilityScripts\&.CellTreeNode\&.TopLeft"

.PP
Definition at line \fB322\fP of file \fBCullArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
