.TH "Photon.Pun.Simple.ContactProjectile" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactProjectile
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, \fBPhoton\&.Pun\&.Simple\&.IProjectile\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBLagCompensate\fP (float timeshift)"
.br
.RI "Override this method to implement more advanced initial lag compensated snap and velocity values\&. "
.ti -1c
.RI "void \fBInitialize\fP (\fBIProjectileCannon\fP \fBowner\fP, int \fBframeId\fP, int \fBsubFrameId\fP, Vector3 localVelocity, \fBRespondTo\fP \fBterminateOn\fP, \fBRespondTo\fP \fBdamageOn\fP, float timeshift=0)"
.br
.ti -1c
.RI "void \fBOnPreSimulate\fP (int \fBframeId\fP, int \fBsubFrameId\fP)"
.br
.RI "Pre-Fixed\&. "
.ti -1c
.RI "virtual void \fBSimulateTime\fP (float t)"
.br
.ti -1c
.RI "virtual void \fBOnPreUpdate\fP ()"
.br
.RI "Interpolation\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBvelocity\fP"
.br
.ti -1c
.RI "int \fBframeId\fP"
.br
.ti -1c
.RI "int \fBsubFrameId\fP"
.br
.ti -1c
.RI "List< \fBIOnNetworkHit\fP > \fBonHit\fP = new List<\fBIOnNetworkHit\fP>()"
.br
.RI "Hit callbacks\&. "
.ti -1c
.RI "List< \fBIOnTerminate\fP > \fBonTerminate\fP = new List<\fBIOnTerminate\fP>()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBInterpolate\fP (float t)"
.br
.ti -1c
.RI "virtual void \fBTerminate\fP ()"
.br
.RI "Override this and extend the base with your own projectile termination code, or place a component on this GameObject with \fBIOnTerminate\fP to define a response\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBIProjectileCannon\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBRespondTo\fP \fBterminateOn\fP = \fBRespondTo\&.IContactTrigger\fP | \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"
.br
.ti -1c
.RI "\fBRespondTo\fP \fBdamageOn\fP = \fBRespondTo\&.IContactTrigger\fP | \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"
.br
.ti -1c
.RI "Rigidbody \fBrb\fP"
.br
.ti -1c
.RI "Rigidbody2D \fBrb2d\fP"
.br
.ti -1c
.RI "bool \fB_hasRigidBody\fP"
.br
.ti -1c
.RI "bool \fBneedsSnapshot\fP"
.br
.ti -1c
.RI "\fBIContactTrigger\fP \fBlocalContactTrigger\fP"
.br
.ti -1c
.RI "bool \fBuseRbForces\fP"
.br
.ti -1c
.RI "bool \fBuseRb2dForces\fP"
.br
.ti -1c
.RI "bool \fBuseRBGravity\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static List< \fBNetObject\fP > \fBreusableNetObjects\fP = new List<\fBNetObject\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIProjectileCannon\fP \fBOwner\fP\fC [getset]\fP"
.br
.ti -1c
.RI "bool \fBHasRigidbody\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBVitalNameType\fP \fBVitalNameType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBContactProjectile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.ContactProjectile\&.Initialize (\fBIProjectileCannon\fP owner, int frameId, int subFrameId, Vector3 localVelocity, \fBRespondTo\fP terminateOn, \fBRespondTo\fP damageOn, float timeshift = \fC0\fP)"
TODO: NOT TESTED
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IProjectile\fP\&.
.PP
Definition at line \fB102\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.ContactProjectile\&.Interpolate (float t)\fC [protected]\fP"

.PP
Definition at line \fB173\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.ContactProjectile\&.LagCompensate (float timeshift)\fC [virtual]\fP"

.PP
Override this method to implement more advanced initial lag compensated snap and velocity values\&. Advance the position/rotation of the projectile here, and set the velocity to a value it should be at AFTER the timeshift is applied, so that it accounts for gravity and drag\&. 
.PP
\fBParameters\fP
.RS 4
\fItimeshift\fP 
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.ContactProjectile\&.OnPreSimulate (int frameId, int subFrameId)"

.PP
Pre-Fixed\&. 
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Definition at line \fB146\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.ContactProjectile\&.OnPreUpdate ()\fC [virtual]\fP"

.PP
Interpolation\&. 
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.PP
Definition at line \fB167\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.ContactProjectile\&.SimulateTime (float t)\fC [virtual]\fP"

.PP
Definition at line \fB152\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.ContactProjectile\&.Terminate ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Override this and extend the base with your own projectile termination code, or place a component on this GameObject with \fBIOnTerminate\fP to define a response\&. 
.PP
Definition at line \fB185\fP of file \fBContactProjectile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&._hasRigidBody\fC [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBRespondTo\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.damageOn = \fBRespondTo\&.IContactTrigger\fP | \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP\fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ContactProjectile\&.frameId"

.PP
Definition at line \fB22\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBIContactTrigger\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.localContactTrigger\fC [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&.needsSnapshot\fC [protected]\fP"

.PP
Definition at line \fB37\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "List<\fBIOnNetworkHit\fP> Photon\&.Pun\&.Simple\&.ContactProjectile\&.onHit = new List<\fBIOnNetworkHit\fP>()"

.PP
Hit callbacks\&. 
.PP
Definition at line \fB45\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "List<\fBIOnTerminate\fP> Photon\&.Pun\&.Simple\&.ContactProjectile\&.onTerminate = new List<\fBIOnTerminate\fP>()"

.PP
Definition at line \fB46\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBIProjectileCannon\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.owner\fC [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "Rigidbody Photon\&.Pun\&.Simple\&.ContactProjectile\&.rb\fC [protected]\fP"

.PP
Definition at line \fB33\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "Rigidbody2D Photon\&.Pun\&.Simple\&.ContactProjectile\&.rb2d\fC [protected]\fP"

.PP
Definition at line \fB34\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "List<\fBNetObject\fP> Photon\&.Pun\&.Simple\&.ContactProjectile\&.reusableNetObjects = new List<\fBNetObject\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB180\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ContactProjectile\&.subFrameId"

.PP
Definition at line \fB23\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBRespondTo\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.terminateOn = \fBRespondTo\&.IContactTrigger\fP | \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP\fC [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&.useRb2dForces\fC [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&.useRbForces\fC [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&.useRBGravity\fC [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.ContactProjectile\&.velocity"

.PP
Definition at line \fB20\fP of file \fBContactProjectile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.ContactProjectile\&.HasRigidbody\fC [get]\fP"

.PP
Definition at line \fB36\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBIProjectileCannon\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.Owner\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB18\fP of file \fBContactProjectile\&.cs\fP\&.
.SS "\fBVitalNameType\fP Photon\&.Pun\&.Simple\&.ContactProjectile\&.VitalNameType\fC [get]\fP"

.PP
Definition at line \fB42\fP of file \fBContactProjectile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
