.TH "Photon.Pun.Simple.AutoOwnerComponentEnable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoOwnerComponentEnable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponentToggle\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBEnableIf\fP { \fBIgnore\fP, \fBOwner\fP, \fBOther\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.ti -1c
.RI "override void \fBOnAuthorityChanged\fP (bool isMine, bool controllerChanged)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBincludeChildren\fP = true"
.br
.ti -1c
.RI "bool \fBincludeUnity\fP = true"
.br
.ti -1c
.RI "bool \fBincludePhoton\fP = false"
.br
.ti -1c
.RI "bool \fBincludeSimple\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.EnableIf\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIgnore \fP\fP
.TP
\fB\fIOwner \fP\fP
.TP
\fB\fIOther \fP\fP
.PP
Definition at line \fB18\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.OnAuthorityChanged (bool isMine, bool controllerChanged)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP\&.
.PP
Definition at line \fB59\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB53\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.OnStart ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB46\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.includeChildren = true"

.PP
Definition at line \fB27\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.includePhoton = false"

.PP
Definition at line \fB29\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.includeSimple = false"

.PP
Definition at line \fB30\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.AutoOwnerComponentEnable\&.includeUnity = true"

.PP
Definition at line \fB28\fP of file \fBAutoOwnerComponentEnable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
