.TH "Photon.Compression.SyncHalfFloatAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.SyncHalfFloatAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP, \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP, and \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyncHalfFloatAttribute\fP (\fBIndicatorBit\fP indicatorBit=\fBIndicatorBit\&.None\fP, \fBKeyRate\fP \fBkeyRate\fP=\fBKeyRate\&.UseDefault\fP)"
.br
.ti -1c
.RI "override int \fBGetMaxBits\fP (Type fieldType)"
.br
.RI "Maximum possible bits that can be used during bitpacking\&. "
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Single value, Single prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Double value, Double prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Double value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.SyncHalfFloatAttribute\&.SyncHalfFloatAttribute (\fBIndicatorBit\fP indicatorBit = \fC\fBIndicatorBit\&.None\fP\fP, \fBKeyRate\fP keyRate = \fC\fBKeyRate\&.UseDefault\fP\fP)"

.PP
Definition at line \fB19\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override int Photon\&.Compression\&.SyncHalfFloatAttribute\&.GetMaxBits (Type fieldType)\fC [virtual]\fP"

.PP
Maximum possible bits that can be used during bitpacking\&. These are used to determine the byte[] size for any PackObjects\&. Override this if the PackableAttribute will always use less than these values\&. Doing so will result in some memory savings\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldType\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP\&.
.PP
Definition at line \fB25\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncHalfFloatAttribute\&.Pack (ref Double value, Double prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.PP
Definition at line \fB75\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncHalfFloatAttribute\&.Pack (ref Single value, Single prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB31\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncHalfFloatAttribute\&.Unpack (ref Double value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.PP
Definition at line \fB81\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncHalfFloatAttribute\&.Unpack (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB55\fP of file \fBSyncHalfFloatAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
