.TH "Photon.Pun.Demo.Procedural.Block" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Procedural.Block \- The \fBBlock\fP component is attach to each instantiated \fBBlock\fP at runtime\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBlockId\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBClusterId\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBBlock\fP component is attach to each instantiated \fBBlock\fP at runtime\&. 

It provides the \fBBlock\fP's ID as well as the parent's \fBCluster\fP ID in order to apply modifications\&. 
.PP
Definition at line \fB9\fP of file \fBBlock\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Demo\&.Procedural\&.Block\&.BlockId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB11\fP of file \fBBlock\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Procedural\&.Block\&.ClusterId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB12\fP of file \fBBlock\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
