.TH "Photon.Pun.SceneManagerHelper" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.SceneManagerHelper
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBActiveSceneName\fP\fC [get]\fP"
.br
.ti -1c
.RI "static int \fBActiveSceneBuildIndex\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB821\fP of file \fBPunClasses\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.SceneManagerHelper\&.ActiveSceneBuildIndex\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB832\fP of file \fBPunClasses\&.cs\fP\&.
.SS "string Photon\&.Pun\&.SceneManagerHelper\&.ActiveSceneName\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB823\fP of file \fBPunClasses\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
