.TH "Photon.Pun.Simple.SyncVitalsEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncVitalsEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits SyncObjectEditor\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUIInjectMiddle\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBHelpURL\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTexturePath\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBInstructions\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBSyncVitalsEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncVitalsEditor\&.OnInspectorGUIInjectMiddle ()\fC [protected]\fP"
SSH is on root of an RB
.PP
SSH is on an RB, but not the root level
.PP
Definition at line \fB41\fP of file \fBSyncVitalsEditor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.SyncVitalsEditor\&.HelpURL\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB18\fP of file \fBSyncVitalsEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncVitalsEditor\&.Instructions\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBSyncVitalsEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncVitalsEditor\&.TextTexturePath\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBSyncVitalsEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
