.TH "Photon.Pun.Simple.IOnNetObjReady" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnNetObjReady \- Callback Interface for when all SyncObjects on a NetObj have indicated Ready and are prepared for the NetObj to become visible\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.EnableOnNetObjReady\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncState\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnNetObjReadyChange\fP (bool ready)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for when all SyncObjects on a NetObj have indicated Ready and are prepared for the NetObj to become visible\&. 


.PP
Definition at line \fB11\fP of file \fBNetObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnNetObjReady\&.OnNetObjReadyChange (bool ready)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.EnableOnNetObjReady\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncState\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
