.TH "Photon.Pun.Demo.Cockpit.CountOfPlayersInRoomProperty" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.CountOfPlayersInRoomProperty \- \fBPhotonNetwork\&.CountOfPlayersInRooms\fP UI property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PropertyListenerBase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBText\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBPhotonNetwork\&.CountOfPlayersInRooms\fP UI property\&. 


.PP
Definition at line \fB17\fP of file \fBCountOfPlayersInRoomProperty\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.CountOfPlayersInRoomProperty\&.Text"

.PP
Definition at line \fB19\fP of file \fBCountOfPlayersInRoomProperty\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
