.TH "Photon.Pun.Demo.Hub.DemoHubManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Hub.DemoHubManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelectDemo\fP (string Reference)"
.br
.ti -1c
.RI "void \fBOpenScene\fP ()"
.br
.ti -1c
.RI "void \fBOpenTutorialLink\fP ()"
.br
.ti -1c
.RI "void \fBOpenDocLink\fP ()"
.br
.ti -1c
.RI "void \fBOpenMainWebLink\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBTitleText\fP"
.br
.ti -1c
.RI "Text \fBDescriptionText\fP"
.br
.ti -1c
.RI "GameObject \fBOpenSceneButton\fP"
.br
.ti -1c
.RI "GameObject \fBOpenTutorialLinkButton\fP"
.br
.ti -1c
.RI "GameObject \fBOpenDocLinkButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBDemoHubManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenDocLink ()"

.PP
Definition at line \fB295\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenMainWebLink ()"

.PP
Definition at line \fB306\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenScene ()"

.PP
Definition at line \fB273\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenTutorialLink ()"

.PP
Definition at line \fB284\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.SelectDemo (string Reference)"

.PP
Definition at line \fB260\fP of file \fBDemoHubManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.DescriptionText"

.PP
Definition at line \fB25\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenDocLinkButton"

.PP
Definition at line \fB28\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenSceneButton"

.PP
Definition at line \fB26\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.OpenTutorialLinkButton"

.PP
Definition at line \fB27\fP of file \fBDemoHubManager\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Hub\&.DemoHubManager\&.TitleText"

.PP
Definition at line \fB24\fP of file \fBDemoHubManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
