.TH "Photon.Pun.Demo.Cockpit.PunCockpit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.PunCockpit \- UI based work in progress to test out api and act as foundation when dealing with room, friends and player list  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBSwitchtoMinimalPanel\fP ()"
.br
.ti -1c
.RI "void \fBSwitchtoMaximalPanel\fP ()"
.br
.ti -1c
.RI "void \fBSwitchToAdvancedConnection\fP ()"
.br
.ti -1c
.RI "void \fBSwitchToSimpleConnection\fP ()"
.br
.ti -1c
.RI "void \fBToggleInfosInMinimalPanel\fP ()"
.br
.ti -1c
.RI "void \fBRequestInfosPanel\fP (GameObject Parent)"
.br
.ti -1c
.RI "void \fBOnUserIdSubmited\fP (string userId)"
.br
.ti -1c
.RI "void \fBSetPlayerTtlRoomOption\fP (int value)"
.br
.ti -1c
.RI "void \fBSetEmptyRoomTtlRoomOption\fP (int value)"
.br
.ti -1c
.RI "void \fBSetMaxPlayersRoomOption\fP (int value)"
.br
.ti -1c
.RI "void \fBSetPluginsRoomOption\fP (string value)"
.br
.ti -1c
.RI "void \fBSetPublishUserId\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetIsVisible\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetIsOpen\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetResetBestRegionCodeInPreferences\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetCleanupCacheOnLeave\fP (bool value)"
.br
.ti -1c
.RI "void \fBSetDeleteNullProperties\fP (bool value)"
.br
.ti -1c
.RI "void \fBPingRegions\fP ()"
.br
.RI "in progress, not fully working "
.ti -1c
.RI "override void \fBOnRegionListReceived\fP (\fBRegionHandler\fP regionHandler)"
.br
.RI "Called when the Name Server provided a list of regions for your title\&. "
.ti -1c
.RI "void \fBCloseRegionListView\fP ()"
.br
.ti -1c
.RI "void \fBLoadLevel\fP (string level)"
.br
.ti -1c
.RI "void \fBSetRoomCustomProperty\fP (string value)"
.br
.ti -1c
.RI "void \fBJoinRoom\fP (string roomName)"
.br
.ti -1c
.RI "void \fBCreateRoom\fP ()"
.br
.ti -1c
.RI "void \fBCreateRoom\fP (string roomName, string lobbyName='MyLobby', LobbyType lobbyType=LobbyType\&.SqlLobby, string[] expectedUsers=null)"
.br
.ti -1c
.RI "void \fBJoinRandomRoom\fP ()"
.br
.ti -1c
.RI "void \fBLeaveRoom\fP ()"
.br
.ti -1c
.RI "void \fBConnect\fP ()"
.br
.ti -1c
.RI "void \fBReConnect\fP ()"
.br
.ti -1c
.RI "void \fBReconnectAndRejoin\fP ()"
.br
.ti -1c
.RI "void \fBConnectToBestCloudServer\fP ()"
.br
.ti -1c
.RI "void \fBConnectToRegion\fP (string region)"
.br
.ti -1c
.RI "void \fBConnectOffline\fP ()"
.br
.ti -1c
.RI "void \fBJoinLobby\fP ()"
.br
.ti -1c
.RI "void \fBDisconnect\fP ()"
.br
.ti -1c
.RI "void \fBOpenDashboard\fP ()"
.br
.ti -1c
.RI "void \fBOnDropdownConnectAs\fP (int dropdownIndex)"
.br
.ti -1c
.RI "void \fBOnLobbyToolsViewTabChanged\fP (string tabId)"
.br
.ti -1c
.RI "void \fBOnSelectPlayer\fP ()"
.br
.ti -1c
.RI "override void \fBOnConnected\fP ()"
.br
.RI "Called to signal that the raw connection got established but before the client can call operation on the server\&. "
.ti -1c
.RI "override void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "override void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. "
.ti -1c
.RI "override void \fBOnJoinedLobby\fP ()"
.br
.RI "Called on entering a lobby on the Master Server\&. "
.ti -1c
.RI "override void \fBOnRoomPropertiesUpdate\fP (\fBHashtable\fP propertiesThatChanged)"
.br
.RI "Called when a room's custom properties changed\&. "
.ti -1c
.RI "override void \fBOnLeftLobby\fP ()"
.br
.RI "Called after leaving a lobby\&. "
.ti -1c
.RI "override void \fBOnCreateRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when the server couldn't create a room (OpCreateRoom failed)\&. "
.ti -1c
.RI "override void \fBOnJoinRandomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRandom call failed on the server\&. "
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. "
.ti -1c
.RI "override void \fBOnJoinRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRoom call failed on the server\&. "
.ti -1c
.RI "override void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdebug\fP = false"
.br
.ti -1c
.RI "Text \fBTitle\fP"
.br
.ti -1c
.RI "Text \fBStateText\fP"
.br
.ti -1c
.RI "Text \fBUserIdText\fP"
.br
.ti -1c
.RI "CanvasGroup \fBMinimalCanvasGroup\fP"
.br
.ti -1c
.RI "CanvasGroup \fBMaximalCanvasGroup\fP"
.br
.ti -1c
.RI "GameObject \fBMinimizeButton\fP"
.br
.ti -1c
.RI "GameObject \fBMinimalUIEmbeddHelp\fP"
.br
.ti -1c
.RI "GameObject \fBConnectingLabel\fP"
.br
.ti -1c
.RI "GameObject \fBConnectionPanel\fP"
.br
.ti -1c
.RI "GameObject \fBAdvancedConnectionPanel\fP"
.br
.ti -1c
.RI "Dropdown \fBConnectAsDropDown\fP"
.br
.ti -1c
.RI "GameObject \fBInfosPanel\fP"
.br
.ti -1c
.RI "GameObject \fBMinimalUiInfosPanel\fP"
.br
.ti -1c
.RI "GameObject \fBLobbyPanel\fP"
.br
.ti -1c
.RI "Selectable \fBJoinLobbyButton\fP"
.br
.ti -1c
.RI "\fBRoomListView\fP \fBRoomListManager\fP"
.br
.ti -1c
.RI "\fBFriendListView\fP \fBFriendListManager\fP"
.br
.ti -1c
.RI "GameObject \fBRoomListMatchMakingForm\fP"
.br
.ti -1c
.RI "GameObject \fBGamePanel\fP"
.br
.ti -1c
.RI "\fBPlayerListView\fP \fBPlayerListManager\fP"
.br
.ti -1c
.RI "\fBPlayerDetailsController\fP \fBPlayerDetailsManager\fP"
.br
.ti -1c
.RI "InputField \fBRoomCustomPropertyInputfield\fP"
.br
.ti -1c
.RI "string \fBGameVersionOverride\fP = String\&.Empty"
.br
.RI "The game version override\&. "
.ti -1c
.RI "bool \fBResetBestRegionCodeInPreferences\fP = false"
.br
.RI "The reset flag for best cloud \fBServerSettings\fP\&. "
.ti -1c
.RI "int \fBMaxPlayers\fP = 4"
.br
.ti -1c
.RI "int \fBPlayerTtl\fP = 0"
.br
.ti -1c
.RI "int \fBEmptyRoomTtl\fP = 0"
.br
.ti -1c
.RI "string \fBPlugins\fP = ''"
.br
.ti -1c
.RI "bool \fBPublishUserId\fP = true"
.br
.ti -1c
.RI "bool \fBIsVisible\fP = true"
.br
.ti -1c
.RI "bool \fBIsOpen\fP = true"
.br
.ti -1c
.RI "bool \fBCleanupCacheOnLeave\fP = true"
.br
.ti -1c
.RI "bool \fBDeleteNullProperties\fP = false"
.br
.ti -1c
.RI "\fBIntInputField\fP \fBPlayerTtlField\fP"
.br
.ti -1c
.RI "\fBIntInputField\fP \fBEmptyRoomTtlField\fP"
.br
.ti -1c
.RI "\fBIntInputField\fP \fBMaxPlayersField\fP"
.br
.ti -1c
.RI "\fBStringInputField\fP \fBPluginsField\fP"
.br
.ti -1c
.RI "\fBBoolInputField\fP \fBPublishUserIdField\fP"
.br
.ti -1c
.RI "\fBBoolInputField\fP \fBIsVisibleField\fP"
.br
.ti -1c
.RI "\fBBoolInputField\fP \fBIsOpenField\fP"
.br
.ti -1c
.RI "\fBBoolInputField\fP \fBCleanupCacheOnLeaveField\fP"
.br
.ti -1c
.RI "\fBBoolInputField\fP \fBDeleteNullPropertiesField\fP"
.br
.ti -1c
.RI "\fBFriendListView\&.FriendDetail\fP[] \fBFriendsList\fP"
.br
.ti -1c
.RI "CanvasGroup \fBModalWindow\fP"
.br
.ti -1c
.RI "\fBRegionListView\fP \fBRegionListView\fP"
.br
.ti -1c
.RI "Text \fBRegionListLoadingFeedback\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBPunCockpit\fP \fBInstance\fP"
.br
.ti -1c
.RI "static bool \fBEmbedded\fP"
.br
.ti -1c
.RI "static string \fBEmbeddedGameTitle\fP = ''"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBUserId\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UI based work in progress to test out api and act as foundation when dealing with room, friends and player list 
.PP
Definition at line \fB26\fP of file \fBPunCockpit\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.CloseRegionListView ()"

.PP
Definition at line \fB408\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Connect ()"

.PP
Definition at line \fB485\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectOffline ()"

.PP
Definition at line \fB577\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectToBestCloudServer ()"

.PP
Definition at line \fB528\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectToRegion (string region)"

.PP
Definition at line \fB551\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.CreateRoom ()"

.PP
Definition at line \fB447\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.CreateRoom (string roomName, string lobbyName = \fC'MyLobby'\fP, \fBLobbyType\fP lobbyType = \fCLobbyType\&.SqlLobby\fP, string[] expectedUsers = \fCnull\fP)"

.PP
Definition at line \fB452\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Disconnect ()"

.PP
Definition at line \fB594\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.JoinLobby ()"

.PP
Definition at line \fB583\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.JoinRandomRoom ()"

.PP
Definition at line \fB470\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.JoinRoom (string roomName)"

.PP
Definition at line \fB438\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.LeaveRoom ()"

.PP
Definition at line \fB475\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.LoadLevel (string level)"

.PP
Definition at line \fB424\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnConnected ()\fC [virtual]\fP"

.PP
Called to signal that the raw connection got established but before the client can call operation on the server\&. After the (low level transport) connection is established, the client will automatically send the Authentication operation, which needs to get a response before the client can call other operations\&.
.PP
Your logic should wait for either: OnRegionListReceived or OnConnectedToMaster\&.
.PP
This callback is useful to detect if the server can be reached at all (technically)\&. Most often, it's enough to implement \fBOnDisconnected()\fP\&.
.PP
This is not called for transitions from the masterserver to game servers\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB648\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnConnectedToMaster ()\fC [virtual]\fP"

.PP
Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. The list of available rooms won't become available unless you join a lobby via \fBLoadBalancingClient\&.OpJoinLobby\fP\&. You can join rooms and create them even without being in a lobby\&. The default lobby is used in that case\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB671\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnCreateRoomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when the server couldn't create a room (OpCreateRoom failed)\&. The most common cause to fail creating a room, is when a title relies on fixed room-names and the room already exists\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB724\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnDisconnected (\fBDisconnectCause\fP cause)\fC [virtual]\fP"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. It could be a failure or intentional 
.PP
The reason for this disconnect is provided as DisconnectCause\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB657\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnDropdownConnectAs (int dropdownIndex)"

.PP
Definition at line \fB608\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnJoinedLobby ()\fC [virtual]\fP"

.PP
Called on entering a lobby on the Master Server\&. The actual room-list updates will call OnRoomListUpdate\&. 
.PP
While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud)\&. The room list gets available via OnRoomListUpdate\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB681\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. When this is called, you can access the existing players in \fBRoom\&.Players\fP, their custom properties and \fBRoom\&.CustomProperties\fP\&.
.PP
In this callback, you could create player objects\&. For example in Unity, instantiate a prefab for the player\&.
.PP
If you want a match to be started 'actively', enable the user to signal 'ready' (using OpRaiseEvent or a Custom Property)\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB734\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnJoinRandomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when a previous OpJoinRandom call failed on the server\&. The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room)\&.
.PP
When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms\&.
.br
 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB729\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnJoinRoomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when a previous OpJoinRoom call failed on the server\&. The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room)\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB752\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnLeftLobby ()\fC [virtual]\fP"

.PP
Called after leaving a lobby\&. When you leave a lobby, \fBOpCreateRoom\fP and \fBOpJoinRandomRoom\fP automatically refer to the default lobby\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB716\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnLeftRoom ()\fC [virtual]\fP"

.PP
Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server\&. This wraps up multiple internal actions\&.
.PP
Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB766\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnLobbyToolsViewTabChanged (string tabId)"

.PP
Definition at line \fB629\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnRegionListReceived (\fBRegionHandler\fP regionHandler)\fC [virtual]\fP"

.PP
Called when the Name Server provided a list of regions for your title\&. Check the RegionHandler class description, to make use of the provided values\&.
.PP
\fBParameters\fP
.RS 4
\fIregionHandler\fP The currently used RegionHandler\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB387\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnRoomPropertiesUpdate (\fBHashtable\fP propertiesThatChanged)\fC [virtual]\fP"

.PP
Called when a room's custom properties changed\&. The propertiesThatChanged contains all that was set via \fBRoom\&.SetCustomProperties\fP\&. 
.PP
Since v1\&.25 this method has one parameter: Hashtable propertiesThatChanged\&.
.br
 Changing properties must be done by \fBRoom\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertiesThatChanged\fP 
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB706\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnSelectPlayer ()"

.PP
Definition at line \fB639\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OnUserIdSubmited (string userId)"

.PP
Definition at line \fB254\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.OpenDashboard ()"

.PP
Definition at line \fB601\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PingRegions ()"

.PP
in progress, not fully working 
.PP
Definition at line \fB333\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ReConnect ()"

.PP
Definition at line \fB501\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ReconnectAndRejoin ()"

.PP
Definition at line \fB514\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RequestInfosPanel (GameObject Parent)"

.PP
Definition at line \fB246\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetCleanupCacheOnLeave (bool value)"

.PP
Definition at line \fB314\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetDeleteNullProperties (bool value)"

.PP
Definition at line \fB320\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetEmptyRoomTtlRoomOption (int value)"

.PP
Definition at line \fB266\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetIsOpen (bool value)"

.PP
Definition at line \fB296\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetIsVisible (bool value)"

.PP
Definition at line \fB290\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetMaxPlayersRoomOption (int value)"

.PP
Definition at line \fB272\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetPlayerTtlRoomOption (int value)"

.PP
Definition at line \fB260\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetPluginsRoomOption (string value)"

.PP
Definition at line \fB278\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetPublishUserId (bool value)"

.PP
Definition at line \fB284\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetResetBestRegionCodeInPreferences (bool value)"

.PP
Definition at line \fB308\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SetRoomCustomProperty (string value)"

.PP
Definition at line \fB430\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Start ()"

.PP
Definition at line \fB122\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SwitchToAdvancedConnection ()"

.PP
Definition at line \fB229\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SwitchtoMaximalPanel ()"

.PP
Definition at line \fB219\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SwitchtoMinimalPanel ()"

.PP
Definition at line \fB211\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.SwitchToSimpleConnection ()"

.PP
Definition at line \fB235\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ToggleInfosInMinimalPanel ()"

.PP
Definition at line \fB241\fP of file \fBPunCockpit\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.AdvancedConnectionPanel"

.PP
Definition at line \fB50\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.CleanupCacheOnLeave = true"

.PP
Definition at line \fB93\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBBoolInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.CleanupCacheOnLeaveField"

.PP
Definition at line \fB104\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Dropdown Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectAsDropDown"

.PP
Definition at line \fB51\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectingLabel"

.PP
Definition at line \fB48\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ConnectionPanel"

.PP
Definition at line \fB49\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.debug = false"

.PP
Definition at line \fB32\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.DeleteNullProperties = false"

.PP
Definition at line \fB94\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBBoolInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.DeleteNullPropertiesField"

.PP
Definition at line \fB106\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Embedded\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.EmbeddedGameTitle = ''\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.EmptyRoomTtl = 0"

.PP
Definition at line \fB87\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBIntInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.EmptyRoomTtlField"

.PP
Definition at line \fB98\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBFriendListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.FriendListManager"

.PP
Definition at line \fB61\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBFriendListView\&.FriendDetail\fP [] Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.FriendsList"
\fBInitial value:\fP
.PP
.nf
=
            new FriendListView\&.FriendDetail[]{
            new FriendListView\&.FriendDetail("Joe","Joe"),
            new FriendListView\&.FriendDetail("Jane","Jane"),
            new FriendListView\&.FriendDetail("Bob","Bob")
            }
.fi
.PP
Definition at line \fB109\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.GamePanel"

.PP
Definition at line \fB65\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.GameVersionOverride = String\&.Empty"

.PP
The game version override\&. This is one way to let the user define the gameversion, and set it properly right after we call connect to override the server settings Check \fBConnectAndJoinRandom\&.cs\fP for another example of gameversion overriding 
.PP
Definition at line \fB76\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.InfosPanel"

.PP
Definition at line \fB54\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBPunCockpit\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Instance\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.IsOpen = true"

.PP
Definition at line \fB91\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBBoolInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.IsOpenField"

.PP
Definition at line \fB103\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.IsVisible = true"

.PP
Definition at line \fB90\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBBoolInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.IsVisibleField"

.PP
Definition at line \fB102\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Selectable Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.JoinLobbyButton"

.PP
Definition at line \fB59\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.LobbyPanel"

.PP
Definition at line \fB58\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "CanvasGroup Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MaximalCanvasGroup"

.PP
Definition at line \fB43\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MaxPlayers = 4"

.PP
Definition at line \fB85\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBIntInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MaxPlayersField"

.PP
Definition at line \fB99\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "CanvasGroup Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MinimalCanvasGroup"

.PP
Definition at line \fB42\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MinimalUIEmbeddHelp"

.PP
Definition at line \fB45\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MinimalUiInfosPanel"

.PP
Definition at line \fB55\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.MinimizeButton"

.PP
Definition at line \fB44\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "CanvasGroup Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ModalWindow"

.PP
Definition at line \fB117\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBPlayerDetailsController\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PlayerDetailsManager"

.PP
Definition at line \fB67\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBPlayerListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PlayerListManager"

.PP
Definition at line \fB66\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PlayerTtl = 0"

.PP
Definition at line \fB86\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBIntInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PlayerTtlField"

.PP
Definition at line \fB97\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Plugins = ''"

.PP
Definition at line \fB88\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBStringInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PluginsField"

.PP
Definition at line \fB100\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PublishUserId = true"

.PP
Definition at line \fB89\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBBoolInputField\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.PublishUserIdField"

.PP
Definition at line \fB101\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RegionListLoadingFeedback"

.PP
Definition at line \fB120\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBRegionListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RegionListView"

.PP
Definition at line \fB119\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.ResetBestRegionCodeInPreferences = false"

.PP
The reset flag for best cloud \fBServerSettings\fP\&. This is one way to let the user define if bestcloud cache should be reseted when connecting\&. 
.PP
Definition at line \fB82\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RoomCustomPropertyInputfield"

.PP
Definition at line \fB69\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "\fBRoomListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RoomListManager"

.PP
Definition at line \fB60\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.RoomListMatchMakingForm"

.PP
Definition at line \fB62\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.StateText"

.PP
Definition at line \fB37\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.Title"

.PP
Definition at line \fB36\fP of file \fBPunCockpit\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.UserIdText"

.PP
Definition at line \fB38\fP of file \fBPunCockpit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\&.UserId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB34\fP of file \fBPunCockpit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
