.TH "Photon.Pun.Demo.PunBasics.Launcher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.Launcher \- Launch manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConnect\fP ()"
.br
.RI "Start the connection process\&. "
.ti -1c
.RI "override void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called after the connection to the master is established and authenticated "
.ti -1c
.RI "override void \fBOnJoinRandomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a JoinRandom() call failed\&. "
.ti -1c
.RI "override void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when entering a room (by creating or joining it)\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Launch manager\&. 

Connect, join a random room or create one if none or all full\&. 
.PP
Definition at line \fB23\fP of file \fBLauncher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.Launcher\&.Connect ()"

.PP
Start the connection process\&. 
.IP "\(bu" 2
If already connected, we attempt joining a random room
.IP "\(bu" 2
if not yet connected, Connect this application instance to \fBPhoton\fP Cloud Network 
.PP

.PP
Definition at line \fB89\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.Launcher\&.OnConnectedToMaster ()\fC [virtual]\fP"

.PP
Called after the connection to the master is established and authenticated 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB148\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.Launcher\&.OnDisconnected (\fBDisconnectCause\fP cause)\fC [virtual]\fP"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB182\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.Launcher\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Called when entering a room (by creating or joining it)\&. Called on all clients (including the Master Client)\&. 
.PP
This method is commonly used to instantiate player characters\&. If a match has to be started 'actively', you can call an \fBPunRPC\fP triggered by a user's button-press or a timer\&.
.PP
When this is called, you can usually already access the existing players in the room via \fBPhotonNetwork\&.PlayerList\fP\&. Also, all custom properties should be already available as Room\&.customProperties\&. Check Room\&.\&.PlayerCount to find out if enough players are in the room to start playing\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB206\fP of file \fBLauncher\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.PunBasics\&.Launcher\&.OnJoinRandomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when a JoinRandom() call failed\&. The parameter provides ErrorCode and message\&. 
.PP
Most likely all rooms are full or no rooms are available\&. 
.br
 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB169\fP of file \fBLauncher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
