.TH "Photon.Pun.Simple.IOnStateChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnStateChange
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.OnStateChangeKinematic\fP, \fBPhoton\&.Pun\&.Simple\&.OnStateChangeToggle\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, and \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnStateChange\fP (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo=null, bool isReady=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBIOnStateChange\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnStateChange\&.OnStateChange (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo = \fCnull\fP, bool isReady = \fCtrue\fP)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP, \fBPhoton\&.Pun\&.Simple\&.OnStateChangeKinematic\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, and \fBPhoton\&.Pun\&.Simple\&.OnStateChangeToggle\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
