.TH "Photon.Compression.HalfFloat" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.HalfFloat
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBHalf\fP"
.br
.RI "A half precision (16 bit) floating point value\&. "
.ti -1c
.RI "class \fBHalfUtilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
