.TH "Photon.Pun.UtilityScripts.TabViewManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.TabViewManager \- \fBTab\fP view manager\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTab\fP"
.br
.ti -1c
.RI "class \fBTabChangeEvent\fP"
.br
.RI "\fBTab\fP change event\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSelectTab\fP (string id)"
.br
.RI "Selects a given tab\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ToggleGroup \fBToggleGroup\fP"
.br
.RI "The toggle group component target\&. "
.ti -1c
.RI "\fBTab\fP[] \fBTabs\fP"
.br
.RI "all the tabs for this group "
.ti -1c
.RI "\fBTabChangeEvent\fP \fBOnTabChanged\fP"
.br
.RI "The on tab changed Event\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTab\fP \fBCurrentTab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTab\fP view manager\&. 

Handles \fBTab\fP views activation and deactivation, and provides a Unity Event Callback when a tab was selected\&. 
.PP
Definition at line \fB25\fP of file \fBTabViewManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.SelectTab (string id)"

.PP
Selects a given tab\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP \fBTab\fP Id
.RE
.PP

.PP
Definition at line \fB94\fP of file \fBTabViewManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTab\fP Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.CurrentTab\fC [protected]\fP"

.PP
Definition at line \fB57\fP of file \fBTabViewManager\&.cs\fP\&.
.SS "\fBTabChangeEvent\fP Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.OnTabChanged"

.PP
The on tab changed Event\&. 
.PP
Definition at line \fB55\fP of file \fBTabViewManager\&.cs\fP\&.
.SS "\fBTab\fP [] Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.Tabs"

.PP
all the tabs for this group 
.PP
Definition at line \fB50\fP of file \fBTabViewManager\&.cs\fP\&.
.SS "ToggleGroup Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.ToggleGroup"

.PP
The toggle group component target\&. 
.PP
Definition at line \fB45\fP of file \fBTabViewManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
