.TH "Photon.Pun.Demo.Cockpit.RoomListView" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.RoomListView \- Room list UI View\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnJoinRoomEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnRoomCellJoinButtonClick\fP (string roomName)"
.br
.ti -1c
.RI "override void \fBOnRoomListUpdate\fP (List< \fBRoomInfo\fP > roomList)"
.br
.RI "Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. "
.ti -1c
.RI "void \fBOnJoinedLobbyCallBack\fP ()"
.br
.ti -1c
.RI "void \fBGetRoomList\fP ()"
.br
.ti -1c
.RI "void \fBResetList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOnJoinRoomEvent\fP \fBOnJoinRoom\fP"
.br
.ti -1c
.RI "\fBRoomListCell\fP \fBCellPrototype\fP"
.br
.ti -1c
.RI "Text \fBUpdateStatusText\fP"
.br
.ti -1c
.RI "Text \fBContentFeedback\fP"
.br
.ti -1c
.RI "InputField \fBLobbyNameInputField\fP"
.br
.ti -1c
.RI "InputField \fBSqlQueryInputField\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Room list UI View\&. 


.PP
Definition at line \fB22\fP of file \fBRoomListView\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.GetRoomList ()"

.PP
Definition at line \fB116\fP of file \fBRoomListView\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB43\fP of file \fBRoomListView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.OnJoinedLobbyCallBack ()"

.PP
Definition at line \fB110\fP of file \fBRoomListView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.OnRoomCellJoinButtonClick (string roomName)"

.PP
Definition at line \fB55\fP of file \fBRoomListView\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.OnRoomListUpdate (List< \fBRoomInfo\fP > roomList)\fC [virtual]\fP"

.PP
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. Each item is a RoomInfo which might include custom properties (provided you defined those as lobby-listed when creating a room)\&. Not all types of lobbies provide a listing of rooms to the client\&. Some are silent and specialized for server-side matchmaking\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB60\fP of file \fBRoomListView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.ResetList ()"

.PP
Definition at line \fB131\fP of file \fBRoomListView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRoomListCell\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.CellPrototype"

.PP
Definition at line \fB29\fP of file \fBRoomListView\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.ContentFeedback"

.PP
Definition at line \fB33\fP of file \fBRoomListView\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.LobbyNameInputField"

.PP
Definition at line \fB35\fP of file \fBRoomListView\&.cs\fP\&.
.SS "\fBOnJoinRoomEvent\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.OnJoinRoom"

.PP
Definition at line \fB27\fP of file \fBRoomListView\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.SqlQueryInputField"

.PP
Definition at line \fB36\fP of file \fBRoomListView\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListView\&.UpdateStatusText"

.PP
Definition at line \fB31\fP of file \fBRoomListView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
