.TH "Photon.Compression.MatrixExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.MatrixExtensions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCopyFrom\fP (this \fBMatrix\fP target, \fBMatrix\fP src)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB368\fP of file \fBMatrix\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.MatrixExtensions\&.CopyFrom (this \fBMatrix\fP target, \fBMatrix\fP src)\fC [static]\fP"

.PP
Definition at line \fB370\fP of file \fBMatrix\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
