.TH "Photon.Pun.PhotonTransformView" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformView
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.RI "Called by PUN several times per second, so that your script can write and read synchronization data for the \fBPhotonView\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBm_SynchronizePosition\fP = true"
.br
.ti -1c
.RI "bool \fBm_SynchronizeRotation\fP = true"
.br
.ti -1c
.RI "bool \fBm_SynchronizeScale\fP = false"
.br
.ti -1c
.RI "bool \fBm_UseLocal\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.PhotonTransformView\&.Awake ()"

.PP
Definition at line \fB38\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonTransformView\&.OnPhotonSerializeView (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"

.PP
Called by PUN several times per second, so that your script can write and read synchronization data for the \fBPhotonView\fP\&. This method will be called in scripts that are assigned as Observed component of a \fBPhotonView\fP\&.
.br
 \fBPhotonNetwork\&.SerializationRate\fP affects how often this method is called\&.
.br
 \fBPhotonNetwork\&.SendRate\fP affects how often packages are sent by this client\&.
.br
.PP
Implementing this method, you can customize which data a \fBPhotonView\fP regularly synchronizes\&. Your code defines what is being sent (content) and how your data is used by receiving clients\&.
.PP
Unlike other callbacks, \fIOnPhotonSerializeView only gets called when it is assigned to a \fBPhotonView\fP\fP as PhotonView\&.observed script\&.
.PP
To make use of this method, the \fBPhotonStream\fP is essential\&. It will be in 'writing' mode' on the
client that controls a PhotonView (PhotonStream\&.IsWriting == true) and in 'reading mode' on the
remote clients that just receive that the controlling client sends\&.

If you skip writing any value into the stream, PUN will skip the update\&. Used carefully, this can
conserve bandwidth and messages (which have a limit per room/second)\&.

Note that OnPhotonSerializeView is not called on remote clients when the sender does not send
any update\&. This can't be used as 'x-times per second \fBUpdate()\fP"\&. 
.PP
Implements \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.PP
Definition at line \fB77\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonTransformView\&.Update ()"

.PP
Definition at line \fB57\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.PhotonTransformView\&.m_SynchronizePosition = true"

.PP
Definition at line \fB29\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformView\&.m_SynchronizeRotation = true"

.PP
Definition at line \fB30\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformView\&.m_SynchronizeScale = false"

.PP
Definition at line \fB31\fP of file \fBPhotonTransformView\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformView\&.m_UseLocal"

.PP
Definition at line \fB34\fP of file \fBPhotonTransformView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
