.TH "Photon.Pun.Simple.AutoZoom" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoZoom
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBwindow\fP = \&.25f"
.br
.ti -1c
.RI "float \fBpanRate\fP = 20f"
.br
.ti -1c
.RI "float \fBzoomRate\fP = 200f"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< Transform > \fBwatched\fP = new List<Transform>()"
.br
.ti -1c
.RI "const float \fBMAX_FOV\fP = 75"
.br
.ti -1c
.RI "const float \fBMIN_FOV\fP = 15"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBAutoZoom\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const float Photon\&.Pun\&.Simple\&.AutoZoom\&.MAX_FOV = 75\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBAutoZoom\&.cs\fP\&.
.SS "const float Photon\&.Pun\&.Simple\&.AutoZoom\&.MIN_FOV = 15\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBAutoZoom\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.AutoZoom\&.panRate = 20f"

.PP
Definition at line \fB25\fP of file \fBAutoZoom\&.cs\fP\&.
.SS "List<Transform> Photon\&.Pun\&.Simple\&.AutoZoom\&.watched = new List<Transform>()\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBAutoZoom\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.AutoZoom\&.window = \&.25f"

.PP
Definition at line \fB23\fP of file \fBAutoZoom\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.AutoZoom\&.zoomRate = 200f"

.PP
Definition at line \fB27\fP of file \fBAutoZoom\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
