.TH "Photon.Pun.Simple.SyncTransform.Frame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncTransform.Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP ()"
.br
.ti -1c
.RI "\fBFrame\fP (\fBSyncTransform\fP sst, int \fBframeId\fP)"
.br
.ti -1c
.RI "\fBFrame\fP (\fBFrame\fP srcFrame, int \fBframeId\fP)"
.br
.ti -1c
.RI "void \fBSet\fP (\fBSyncTransform\fP sst, int \fBframeId\fP)"
.br
.ti -1c
.RI "override void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.ti -1c
.RI "bool \fBFastCompareCompressed\fP (\fBFrame\fP other)"
.br
.RI "Compares only the compressed values for equality "
.ti -1c
.RI "bool \fBFastCompareUncompressed\fP (\fBFrame\fP other)"
.br
.RI "Compares only the compressed values for equality "
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBhasTeleported\fP"
.br
.ti -1c
.RI "\fBMatrix\fP \fBm\fP"
.br
.ti -1c
.RI "\fBCompressedMatrix\fP \fBcm\fP"
.br
.ti -1c
.RI "\fBSyncTransform\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBMatrix\fP \fBtelem\fP"
.br
.ti -1c
.RI "\fBCompressedMatrix\fP \fBtelecm\fP"
.br
.ti -1c
.RI "int \fBparentHash\fP"
.br
.ti -1c
.RI "int \fBtelePparentHash\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB215\fP of file \fBSyncTransform\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.Frame ()"

.PP
Definition at line \fB226\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.Frame (\fBSyncTransform\fP sst, int frameId)"

.PP
Definition at line \fB235\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.Frame (\fBFrame\fP srcFrame, int frameId)"

.PP
Definition at line \fB246\fP of file \fBSyncTransform\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB305\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"
When copying a teleport frame, we use the tele values\&.
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB260\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.FastCompareCompressed (\fBFrame\fP other)"

.PP
Compares only the compressed values for equality 
.PP
Definition at line \fB285\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.FastCompareUncompressed (\fBFrame\fP other)"

.PP
Compares only the compressed values for equality 
.PP
Definition at line \fB297\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.Set (\fBSyncTransform\fP sst, int frameId)"

.PP
Definition at line \fB255\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.ToString ()"

.PP
Definition at line \fB311\fP of file \fBSyncTransform\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCompressedMatrix\fP Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.cm"

.PP
Definition at line \fB219\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.hasTeleported"

.PP
Definition at line \fB217\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "\fBMatrix\fP Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.m"

.PP
Definition at line \fB218\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "\fBSyncTransform\fP Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.owner"

.PP
Definition at line \fB220\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.parentHash"

.PP
Definition at line \fB223\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "\fBCompressedMatrix\fP Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.telecm"

.PP
Definition at line \fB222\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "\fBMatrix\fP Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.telem"

.PP
Definition at line \fB221\fP of file \fBSyncTransform\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncTransform\&.Frame\&.telePparentHash"

.PP
Definition at line \fB224\fP of file \fBSyncTransform\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
