.TH "Photon.Pun.Demo.Cockpit.OnlineDocButton" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.OnlineDocButton \- Open an Url on Pointer Click\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData pointerEventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBUrl\fP = 'https://doc\&.photonengine\&.com/en\-us/pun/v2/getting\-started/pun\-intro'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Open an Url on Pointer Click\&. 


.PP
Definition at line \fB16\fP of file \fBOnlineDocButton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.OnlineDocButton\&.OnPointerClick (PointerEventData pointerEventData)"

.PP
Definition at line \fB21\fP of file \fBOnlineDocButton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.OnlineDocButton\&.Url = 'https://doc\&.photonengine\&.com/en\-us/pun/v2/getting\-started/pun\-intro'"

.PP
Definition at line \fB18\fP of file \fBOnlineDocButton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
