.TH "Photon.Utilities.BoundsTools" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.BoundsTools
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBBoundsType\fP { \fBBoth\fP, \fBMeshRenderer\fP, \fBCollider\fP, \fBManual\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Bounds \fBCollectMyBounds\fP (this GameObject go, \fBBoundsType\fP factorIn, out int numOfBoundsFound, bool includeChildren=true, bool includeInactive=false)"
.br
.RI "Collect the bounds of the indicated types (MeshRenderer and/or Collider) on the object and all of its children, and returns bounds that are a sum of all of those\&. "
.ti -1c
.RI "static Bounds \fBCollectMyBounds\fP (GameObject go, \fBBoundsType\fP factorIn, bool includeChildren=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBCollectBounds\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Utilities\&.BoundsTools\&.BoundsType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBoth \fP\fP
.TP
\fB\fIMeshRenderer \fP\fP
.TP
\fB\fICollider \fP\fP
.TP
\fB\fIManual \fP\fP
.PP
Definition at line \fB13\fP of file \fBCollectBounds\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static Bounds Photon\&.Utilities\&.BoundsTools\&.CollectMyBounds (GameObject go, \fBBoundsType\fP factorIn, bool includeChildren = \fCtrue\fP)\fC [static]\fP"

.PP
Definition at line \fB197\fP of file \fBCollectBounds\&.cs\fP\&.
.SS "static Bounds Photon\&.Utilities\&.BoundsTools\&.CollectMyBounds (this GameObject go, \fBBoundsType\fP factorIn, out int numOfBoundsFound, bool includeChildren = \fCtrue\fP, bool includeInactive = \fCfalse\fP)\fC [static]\fP"

.PP
Collect the bounds of the indicated types (MeshRenderer and/or Collider) on the object and all of its children, and returns bounds that are a sum of all of those\&. 
.PP
\fBParameters\fP
.RS 4
\fIgo\fP GameObject to start search from\&.
.br
\fIfactorIn\fP The types of bounds to factor in\&.
.br
\fIincludeChildren\fP Whether to search all children for bounds\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
nothing found, return an empty bounds
.PP
Definition at line \fB34\fP of file \fBCollectBounds\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
