.TH "Photon.Pun.Demo.SlotRacer.Utils.BezierSplineInspector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.Utils.BezierSplineInspector
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBBezierSplineInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSplineInspector\&.OnInspectorGUI ()"

.PP
Definition at line \fB36\fP of file \fBBezierSplineInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
