.TH "Photon.Realtime.EventCode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.EventCode \- Class for constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBGameList\fP = 230"
.br
.RI "(230) Initial list of RoomInfos (in lobby on Master)"
.ti -1c
.RI "const byte \fBGameListUpdate\fP = 229"
.br
.RI "(229) Update of RoomInfos to be merged into 'initial' list (in lobby on Master)"
.ti -1c
.RI "const byte \fBQueueState\fP = 228"
.br
.RI "(228) Currently not used\&. State of queueing in case of server-full"
.ti -1c
.RI "const byte \fBMatch\fP = 227"
.br
.RI "(227) Currently not used\&. Event for matchmaking"
.ti -1c
.RI "const byte \fBAppStats\fP = 226"
.br
.RI "(226) Event with stats about this application (players, rooms, etc)"
.ti -1c
.RI "const byte \fBLobbyStats\fP = 224"
.br
.RI "(224) This event provides a list of lobbies with their player and game counts\&."
.ti -1c
.RI "const byte \fBAzureNodeInfo\fP = 210"
.br
.RI "(210) Internally used in case of hosting by Azure"
.ti -1c
.RI "const byte \fBJoin\fP = (byte)255"
.br
.RI "(255) Event Join: someone joined the game\&. The new actorNumber is provided as well as the properties of that actor (if set in OpJoin)\&."
.ti -1c
.RI "const byte \fBLeave\fP = (byte)254"
.br
.RI "(254) Event Leave: The player who left the game can be identified by the actorNumber\&."
.ti -1c
.RI "const byte \fBPropertiesChanged\fP = (byte)253"
.br
.RI "(253) When you call OpSetProperties with the broadcast option 'on', this event is fired\&. It contains the properties being set\&."
.ti -1c
.RI "const byte \fBSetProperties\fP = (byte)253"
.br
.RI "(253) When you call OpSetProperties with the broadcast option 'on', this event is fired\&. It contains the properties being set\&."
.ti -1c
.RI "const byte \fBErrorInfo\fP = 251"
.br
.RI "(252) When player left game unexpected and the room has a playerTtl != 0, this event is fired to let everyone know about the timeout\&. "
.ti -1c
.RI "const byte \fBCacheSliceChanged\fP = 250"
.br
.RI "(250) Sent by \fBPhoton\fP whent he event cache slice was changed\&. Done by OpRaiseEvent\&."
.ti -1c
.RI "const byte \fBAuthEvent\fP = 223"
.br
.RI "(223) Sent by \fBPhoton\fP to update a token before it times out\&."
.in -1c
.SH "Detailed Description"
.PP 
Class for constants\&. 

These values are for events defined by \fBPhoton\fP LoadBalancing\&. 
.PP
They start at 255 and go DOWN\&. Your own in-game events can start at 0\&. These constants are used internally\&.
.PP
Definition at line \fB1330\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Realtime\&.EventCode\&.AppStats = 226\fC [static]\fP"

.PP
(226) Event with stats about this application (players, rooms, etc)
.PP
Definition at line \fB1345\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.AuthEvent = 223\fC [static]\fP"

.PP
(223) Sent by \fBPhoton\fP to update a token before it times out\&.
.PP
Definition at line \fB1378\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.AzureNodeInfo = 210\fC [static]\fP"

.PP
(210) Internally used in case of hosting by Azure
.PP
Definition at line \fB1352\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.CacheSliceChanged = 250\fC [static]\fP"

.PP
(250) Sent by \fBPhoton\fP whent he event cache slice was changed\&. Done by OpRaiseEvent\&.
.PP
Definition at line \fB1375\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.ErrorInfo = 251\fC [static]\fP"

.PP
(252) When player left game unexpected and the room has a playerTtl != 0, this event is fired to let everyone know about the timeout\&. Obsolete\&. Replaced by Leave\&. public const byte Disconnect = LiteEventCode\&.Disconnect;
.PP
(251) Sent by \fBPhoton\fP Cloud when a plugin-call or webhook-call failed or events cache limit exceeded\&. Usually, the execution on the server continues, despite the issue\&. Contains: \fBParameterCode\&.Info\fP\&.
.PP
\fBSee also\fP
.RS 4
https://doc\&.photonengine\&.com/en-us/realtime/current/reference/webhooks::options
.PP
.RE
.PP

.PP
Definition at line \fB1372\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.GameList = 230\fC [static]\fP"

.PP
(230) Initial list of RoomInfos (in lobby on Master)
.PP
Definition at line \fB1333\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.GameListUpdate = 229\fC [static]\fP"

.PP
(229) Update of RoomInfos to be merged into 'initial' list (in lobby on Master)
.PP
Definition at line \fB1336\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.Join = (byte)255\fC [static]\fP"

.PP
(255) Event Join: someone joined the game\&. The new actorNumber is provided as well as the properties of that actor (if set in OpJoin)\&.
.PP
Definition at line \fB1355\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.Leave = (byte)254\fC [static]\fP"

.PP
(254) Event Leave: The player who left the game can be identified by the actorNumber\&.
.PP
Definition at line \fB1358\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.LobbyStats = 224\fC [static]\fP"

.PP
(224) This event provides a list of lobbies with their player and game counts\&.
.PP
Definition at line \fB1348\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.Match = 227\fC [static]\fP"

.PP
(227) Currently not used\&. Event for matchmaking
.PP
Definition at line \fB1342\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.PropertiesChanged = (byte)253\fC [static]\fP"

.PP
(253) When you call OpSetProperties with the broadcast option 'on', this event is fired\&. It contains the properties being set\&.
.PP
Definition at line \fB1361\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.QueueState = 228\fC [static]\fP"

.PP
(228) Currently not used\&. State of queueing in case of server-full
.PP
Definition at line \fB1339\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.EventCode\&.SetProperties = (byte)253\fC [static]\fP"

.PP
(253) When you call OpSetProperties with the broadcast option 'on', this event is fired\&. It contains the properties being set\&.
.PP
Definition at line \fB1365\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
