.TH "Photon.Pun.Simple.IConsumable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IConsumable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.IVitalsConsumable\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBCharges\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBConsumption\fP \fBConsumption\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBConsumedDespawn\fP \fBConsumedDespawn\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIConsumable\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "double Photon\&.Pun\&.Simple\&.IConsumable\&.Charges\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB10\fP of file \fBIConsumable\&.cs\fP\&.
.SS "\fBConsumedDespawn\fP Photon\&.Pun\&.Simple\&.IConsumable\&.ConsumedDespawn\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBIConsumable\&.cs\fP\&.
.SS "\fBConsumption\fP Photon\&.Pun\&.Simple\&.IConsumable\&.Consumption\fC [get]\fP"

.PP
Definition at line \fB11\fP of file \fBIConsumable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
