.TH "Photon.Pun.Simple.IVitalsContactReactor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IVitalsContactReactor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IContactReactor\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.IVitalsConsumable\fP, and \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBDischargeValue\fP (\fBContactType\fP contactType=\fBContactType\&.Undefined\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVitalNameType\fP \fBVitalNameType\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBAllowOverload\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBPropagate\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIVitalsContactReactor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "double Photon\&.Pun\&.Simple\&.IVitalsContactReactor\&.DischargeValue (\fBContactType\fP contactType = \fC\fBContactType\&.Undefined\fP\fP)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.IVitalsContactReactor\&.AllowOverload\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBIVitalsContactReactor\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.IVitalsContactReactor\&.Propagate\fC [get]\fP"

.PP
Definition at line \fB13\fP of file \fBIVitalsContactReactor\&.cs\fP\&.
.SS "\fBVitalNameType\fP Photon\&.Pun\&.Simple\&.IVitalsContactReactor\&.VitalNameType\fC [get]\fP"

.PP
Definition at line \fB10\fP of file \fBIVitalsContactReactor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
