.TH "Photon.Pun.Simple.IOnPreLateUpdate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPreLateUpdate \- Callback Interface for \fBOnPreLateUpdate()\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreLateUpdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPreLateUpdate()\fP\&. 

Called prior to all normal LateUpdate() calls in MonoBehaviours\&. 
.PP
Definition at line \fB33\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPreLateUpdate\&.OnPreLateUpdate ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
