.TH "Photon.Pun.Simple.SyncContact" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncContact \- TODO: this class can become non-abstract if I finish it out and see reason for it\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncContact\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.ISyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.IOnSnapshot\fP, \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP, \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP, \fBPhoton\&.Pun\&.Simple\&.IOnCaptureState\fP, and \fBPhoton\&.Pun\&.Simple\&.ISerializationOptional\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBContactRecord\fP"
.br
.ti -1c
.RI "class \fBFrame\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "virtual void \fBSyncContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.ti -1c
.RI "virtual void \fBOnCaptureCurrentState\fP (int frameId)"
.br
.ti -1c
.RI "virtual \fBSerializationFlags\fP \fBOnNetSerialize\fP (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBOnNetDeserialize\fP (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP arrival)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBConvertIndexToMask\fP (int index)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBEnqueueEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.ti -1c
.RI "virtual \fBConsumption\fP \fBContact\fP (\fBContactEvent\fP contactEvent)"
.br
.RI "Attempt a trigger\&. "
.ti -1c
.RI "virtual void \fBConsume\fP (\fBFrame\fP frame, \fBContactEvent\fP contactEvent, \fBConsumption\fP consumed)"
.br
.ti -1c
.RI "override void \fBApplySnapshot\fP (\fBFrame\fP snapframe, \fBFrame\fP targframe, bool snapIsValid, bool targIsValid)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static int \fBConvertMaskToIndex\fP (int mask)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFrame\fP \fBcurrentState\fP = new \fBFrame\fP()"
.br
.ti -1c
.RI "\fBIContactTrigger\fP \fBcontactTrigger\fP"
.br
.ti -1c
.RI "Rigidbody \fBrb\fP"
.br
.ti -1c
.RI "Rigidbody2D \fBrb2d\fP"
.br
.ti -1c
.RI "bool \fB_hasRigidbody\fP"
.br
.ti -1c
.RI "Queue< \fBContactEvent\fP > \fBqueuedContactEvents\fP = new Queue<\fBContactEvent\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHasRigidbody\fP\fC [get]\fP"
.br
.ti -1c
.RI "GameObject \fBVisiblePickupObj\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
TODO: this class can become non-abstract if I finish it out and see reason for it\&. 

The generic base class for any VitalTrigger derived class\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fITFrame\fP 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncContact\&.ApplySnapshot (\fBFrame\fP snapframe, \fBFrame\fP targframe, bool snapIsValid, bool targIsValid)\fC [protected]\fP"

.PP
Definition at line \fB342\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.SyncContact\&.Consume (\fBFrame\fP frame, \fBContactEvent\fP contactEvent, \fBConsumption\fP consumed)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB247\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual \fBConsumption\fP Photon\&.Pun\&.Simple\&.SyncContact\&.Contact (\fBContactEvent\fP contactEvent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Attempt a trigger\&. Returns true if a triggerEvent results in a valid collision\&. 
.PP
Definition at line \fB230\fP of file \fBSyncContact\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.SyncContact\&.ConvertIndexToMask (int index)\fC [static]\fP"

.PP
Definition at line \fB414\fP of file \fBSyncContact\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.SyncContact\&.ConvertMaskToIndex (int mask)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB379\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual bool Photon\&.Pun\&.Simple\&.SyncContact\&.EnqueueEvent (\fBContactEvent\fP contactEvent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB158\fP of file \fBSyncContact\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncContact\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB120\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.SyncContact\&.OnCaptureCurrentState (int frameId)\fC [virtual]\fP"

.PP

.PP
\fBParameters\fP
.RS 4
\fIframeId\fP 
.br
\fIamActingAuthority\fP 
.br
\fIrealm\fP 
.RE
.PP

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnCaptureState\fP\&.
.PP
Definition at line \fB180\fP of file \fBSyncContact\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.SyncContact\&.OnNetDeserialize (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP arrival)"
if pickup event bool
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP\&.
.PP
Definition at line \fB305\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual \fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.SyncContact\&.OnNetSerialize (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)\fC [virtual]\fP"
pickup event
.PP
attached bool
.PP
attached bool
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP\&.
.PP
Definition at line \fB255\fP of file \fBSyncContact\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.SyncContact\&.SyncContactEvent (\fBContactEvent\fP contactEvent)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.ISyncContact\fP\&.
.PP
Definition at line \fB143\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.SyncContact\&._hasRigidbody\fC [protected]\fP"

.PP
Definition at line \fB45\fP of file \fBSyncContact\&.cs\fP\&.
.SS "\fBIContactTrigger\fP Photon\&.Pun\&.Simple\&.SyncContact\&.contactTrigger\fC [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBSyncContact\&.cs\fP\&.
.SS "\fBFrame\fP Photon\&.Pun\&.Simple\&.SyncContact\&.currentState = new \fBFrame\fP()\fC [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBSyncContact\&.cs\fP\&.
.SS "Queue<\fBContactEvent\fP> Photon\&.Pun\&.Simple\&.SyncContact\&.queuedContactEvents = new Queue<\fBContactEvent\fP>()\fC [protected]\fP"

.PP
Definition at line \fB137\fP of file \fBSyncContact\&.cs\fP\&.
.SS "Rigidbody Photon\&.Pun\&.Simple\&.SyncContact\&.rb\fC [protected]\fP"

.PP
Definition at line \fB43\fP of file \fBSyncContact\&.cs\fP\&.
.SS "Rigidbody2D Photon\&.Pun\&.Simple\&.SyncContact\&.rb2d\fC [protected]\fP"

.PP
Definition at line \fB44\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.SyncContact\&.HasRigidbody\fC [get]\fP"

.PP
Definition at line \fB46\fP of file \fBSyncContact\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Simple\&.SyncContact\&.VisiblePickupObj\fC [get]\fP"

.PP
Definition at line \fB48\fP of file \fBSyncContact\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
