.TH "Photon.Compression.Internal.IPackSByte" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.IPackSByte
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Compression\&.SyncRangedIntAttribute\fP, and \fBPhoton\&.Compression\&.SyncVarAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref SByte value, SByte prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref SByte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB68\fP of file \fBPackFieldInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.IPackSByte\&.Pack (ref SByte value, SByte prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implemented in \fBPhoton\&.Compression\&.SyncRangedIntAttribute\fP, and \fBPhoton\&.Compression\&.SyncVarAttribute\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.IPackSByte\&.Unpack (ref SByte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implemented in \fBPhoton\&.Compression\&.SyncRangedIntAttribute\fP, and \fBPhoton\&.Compression\&.SyncVarAttribute\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
