.TH "Photon.Pun.Simple.IOnPreUpdate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPreUpdate \- Callback Interface for \fBOnPreUpdate()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP, \fBPhoton\&.Pun\&.Simple\&.MountSwitcher\fP, \fBPhoton\&.Pun\&.Simple\&.MountThrow\fP, \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAdditiveMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase< TTRSDef, TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreUpdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPreUpdate()\fP\&. 

Called prior to all normal Update() calls in MonoBehaviours\&. 
.PP
Definition at line \fB24\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPreUpdate\&.OnPreUpdate ()"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.MountThrow\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAdditiveMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase< TTRSDef, TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.MountSwitcher\fP, and \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
