.TH "Photon.Pun.Simple.IOnTickPreSerialization" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnTickPreSerialization \- These callbacks are called by \fBNetMaster\fP to serialize data to the tick stream after the FrameId value, and before all \fBNetObject\fP data is written\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationFlags\fP \fBOnPreSerializeTick\fP (int frameId, byte[] buffer, ref int bitposition)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These callbacks are called by \fBNetMaster\fP to serialize data to the tick stream after the FrameId value, and before all \fBNetObject\fP data is written\&. 

The primary use case for this would be serialization of user inputs, but can be used for any other global, non net entity specific serialization, such as scores, timers, global events, etc\&. 
.PP
Definition at line \fB15\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.IOnTickPreSerialization\&.OnPreSerializeTick (int frameId, byte[] buffer, ref int bitposition)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
