.TH "Photon.Pun.Simple.SyncSpawnTimer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncSpawnTimer \- Automatically generates ChangeState events on the \fBSyncState\fP based on timers and triggers\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncSpawnTimer\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.ISpawnController\fP, \fBPhoton\&.Pun\&.Simple\&.ISerializationOptional\fP, \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP, \fBPhoton\&.Pun\&.Simple\&.IUseKeyframes\fP, \fBPhoton\&.Pun\&.Simple\&.IOnSnapshot\fP, \fBPhoton\&.Pun\&.Simple\&.IOnCaptureState\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFrame\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "bool \fBAllowNetObjectReadyCallback\fP (bool ready)"
.br
.RI "Test used by \fBSyncState\fP to see if the OnNetObjReady callback should trigger the default states\&. "
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.ti -1c
.RI "override void \fBOnStart\fP ()"
.br
.ti -1c
.RI "void \fBOnStateChange\fP (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo=null, bool isReady=true)"
.br
.RI "Responds to State change from \fBSyncState\fP "
.ti -1c
.RI "virtual void \fBOnCaptureCurrentState\fP (int frameId)"
.br
.ti -1c
.RI "virtual \fBSerializationFlags\fP \fBOnNetSerialize\fP (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBOnNetDeserialize\fP (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP frameArrival)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBinitialDelay\fP = 0"
.br
.ti -1c
.RI "bool \fBrespawnEnable\fP = true"
.br
.ti -1c
.RI "\fBObjState\fP \fBdespawnOn\fP = \fBObjState\&.Mounted\fP"
.br
.ti -1c
.RI "float \fBdespawnDelay\fP = 5f"
.br
.ti -1c
.RI "bool \fBdespawnEnable\fP = false"
.br
.ti -1c
.RI "\fBObjState\fP \fBrespawnOn\fP = \fBObjState\&.Despawned\fP"
.br
.ti -1c
.RI "float \fBrespawnDelay\fP = 5f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBApplySnapshot\fP (\fBFrame\fP snapframe, \fBFrame\fP targframe, bool snapIsValid, bool targIsValid)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSyncState\fP \fBsyncState\fP"
.br
.ti -1c
.RI "int \fBticksUntilRespawn\fP = \-1"
.br
.ti -1c
.RI "int \fBticksUntilDespawn\fP = \-1"
.br
.ti -1c
.RI "int \fBspawnWaitAsTicks\fP"
.br
.ti -1c
.RI "int \fBrespawnWaitAsTicks\fP"
.br
.ti -1c
.RI "int \fBdespawnWaitAsTicks\fP"
.br
.ti -1c
.RI "bool \fBhadInitialSpawn\fP"
.br
.ti -1c
.RI "int \fBbitsForTicksUntilRespawn\fP"
.br
.ti -1c
.RI "int \fBbitsForTicksUntilDespawn\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBApplyOrder\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Automatically generates ChangeState events on the \fBSyncState\fP based on timers and triggers\&. 


.PP
Definition at line \fB31\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.AllowNetObjectReadyCallback (bool ready)"

.PP
Test used by \fBSyncState\fP to see if the OnNetObjReady callback should trigger the default states\&. Will return false if the spawn timer is still counting down, indicating that \fBSyncState\fP should not fire the default state change for Ready\&. 
.PP
\fBParameters\fP
.RS 4
\fIready\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.ISpawnController\fP\&.
.PP
Definition at line \fB146\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.ApplySnapshot (\fBFrame\fP snapframe, \fBFrame\fP targframe, bool snapIsValid, bool targIsValid)\fC [protected]\fP"
Apply frame, otherwise predict respawn if we didn't get the frame where it would have happened\&.
.PP
Definition at line \fB358\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB121\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnCaptureCurrentState (int frameId)\fC [virtual]\fP"
First check for a respawn - this may belong in post or pre sim, but here for now
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnCaptureState\fP\&.
.PP
Definition at line \fB228\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB155\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnNetDeserialize (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP frameArrival)"
Read ticksToRespawn
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP\&.
.PP
Definition at line \fB316\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "virtual \fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnNetSerialize (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)\fC [virtual]\fP"
TODO: This is ignoring keyframe setting
.PP
Respawn
.PP
non -1 counter bool
.PP
non -1 counter bool
.PP
Despawn
.PP
non -1 counter bool
.PP
non -1 counter bool
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP\&.
.PP
Definition at line \fB262\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnStart ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB170\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.OnStateChange (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo = \fCnull\fP, bool isReady = \fCtrue\fP)"

.PP
Responds to State change from \fBSyncState\fP Check if the flag we are looking for just changed to true
.PP
Check if the flag we are looking for just changed to true
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP\&.
.PP
Definition at line \fB185\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.bitsForTicksUntilDespawn\fC [protected]\fP"

.PP
Definition at line \fB87\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.bitsForTicksUntilRespawn\fC [protected]\fP"

.PP
Definition at line \fB86\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.despawnDelay = 5f"

.PP
Definition at line \fB52\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.despawnEnable = false"

.PP
Definition at line \fB55\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "\fBObjState\fP Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.despawnOn = \fBObjState\&.Mounted\fP"

.PP
Definition at line \fB50\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.despawnWaitAsTicks\fC [protected]\fP"

.PP
Definition at line \fB83\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.hadInitialSpawn\fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.initialDelay = 0"

.PP
Definition at line \fB46\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.respawnDelay = 5f"

.PP
Definition at line \fB59\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.respawnEnable = true"

.PP
Definition at line \fB48\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "\fBObjState\fP Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.respawnOn = \fBObjState\&.Despawned\fP"

.PP
Definition at line \fB57\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.respawnWaitAsTicks\fC [protected]\fP"

.PP
Definition at line \fB82\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.spawnWaitAsTicks\fC [protected]\fP"

.PP
Definition at line \fB81\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "\fBSyncState\fP Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.syncState\fC [protected]\fP"

.PP
Definition at line \fB66\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.ticksUntilDespawn = \-1\fC [protected]\fP"

.PP
Definition at line \fB78\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.ticksUntilRespawn = \-1\fC [protected]\fP"

.PP
Definition at line \fB77\fP of file \fBSyncSpawnTimer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override int Photon\&.Pun\&.Simple\&.SyncSpawnTimer\&.ApplyOrder\fC [get]\fP"

.PP
Definition at line \fB41\fP of file \fBSyncSpawnTimer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
