.TH "Photon.Pun.PhotonTransformViewRotationControl" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewRotationControl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotonTransformViewRotationControl\fP (\fBPhotonTransformViewRotationModel\fP model)"
.br
.ti -1c
.RI "Quaternion \fBGetNetworkRotation\fP ()"
.br
.RI "Gets the last rotation that was received through the network "
.ti -1c
.RI "Quaternion \fBGetRotation\fP (Quaternion currentRotation)"
.br
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (Quaternion currentRotation, \fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB435\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.PhotonTransformViewRotationControl\&.PhotonTransformViewRotationControl (\fBPhotonTransformViewRotationModel\fP model)"

.PP
Definition at line \fB440\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Quaternion Photon\&.Pun\&.PhotonTransformViewRotationControl\&.GetNetworkRotation ()"

.PP
Gets the last rotation that was received through the network 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB449\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "Quaternion Photon\&.Pun\&.PhotonTransformViewRotationControl\&.GetRotation (Quaternion currentRotation)"

.PP
Definition at line \fB454\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonTransformViewRotationControl\&.OnPhotonSerializeView (Quaternion currentRotation, \fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"

.PP
Definition at line \fB468\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
