.TH "Photon.Compression.SyncListAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.SyncListAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP, and \fBPhoton\&.Compression\&.Internal\&.IPackList< Int32 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref List< Int32 > value, List< Int32 > prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref List< Int32 > value, BitArray isCompleteMask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref List< UInt32 > value, List< UInt32 > prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref List< UInt32 > value, BitArray isCompleteMask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCopy< T >\fP (List< T > src, List< T > trg, BitArray mask)"
.br
.RI "Only copies elements when their bit in the associated mask == true\&. "
.ti -1c
.RI "static void \fBCapture< T >\fP (List< T > src, List< T > trg)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.SyncListAttribute\&.Capture< T > (List< T > src, List< T > trg)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.PP
Definition at line \fB185\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.SyncListAttribute\&.Copy< T > (List< T > src, List< T > trg, BitArray mask)\fC [static]\fP"

.PP
Only copies elements when their bit in the associated mask == true\&. 
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.PP
Definition at line \fB176\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncListAttribute\&.Pack (ref List< Int32 > value, List< Int32 > prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Definition at line \fB19\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncListAttribute\&.Pack (ref List< UInt32 > value, List< UInt32 > prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Definition at line \fB97\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncListAttribute\&.Unpack (ref List< Int32 > value, BitArray isCompleteMask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Definition at line \fB56\fP of file \fBSyncListAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncListAttribute\&.Unpack (ref List< UInt32 > value, BitArray isCompleteMask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Definition at line \fB134\fP of file \fBSyncListAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
