.TH "Photon.Pun.Simple.GenericHitscanExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.GenericHitscanExt \- Utility class that contains methods to create a unified argument string for calling all of the Raycast/Overlap cast calls\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBVisualizeHitscan\fP (this \fBHitscanDefinition\fP hd, Transform origin, float duration=\&.5f)"
.br
.ti -1c
.RI "static int \fBGenericHitscanNonAlloc\fP (this \fBHitscanDefinition\fP hd, Transform origin, out RaycastHit[] rayhits, out Collider[] hits, ref int nearestIndex, bool showDebugWidgets=false, bool useSecondaryRealm=false)"
.br
.ti -1c
.RI "static int \fBGenericHitscanNonAlloc\fP (this \fBHitscanDefinition\fP hd, Transform origin, \fBNetObject\fP ownerNetObj, ref List< \fBNetworkHit\fP > hitscanHits, ref int nearestIndex, bool showDebugWidgets=false, bool useSecondaryRealm=false)"
.br
.ti -1c
.RI "static int \fBGenericHitscanNonAlloc\fP (this \fBHitscanDefinition\fP hd, Transform origin, ref Collider[] hits, ref RaycastHit[] rayhits, ref int nearestIndex, bool showDebugWidgets=false, bool useSecondaryRealm=false)"
.br
.RI "Trigger the defined Cast/Overlap\&. "
.ti -1c
.RI "static int \fBGenericCastNonAlloc\fP (this Transform srcT, Collider[] hits, RaycastHit[] rayhits, float distance, float radius, int mask, Quaternion orientation, bool useOffset, Vector3 offset1, Vector3 offset2, \fBHitscanType\fP hitscanType)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Collider[] \fBreusableColliderArray\fP = new Collider[64]"
.br
.ti -1c
.RI "static RaycastHit[] \fBreusableRayHitArray\fP = new RaycastHit[64]"
.br
.ti -1c
.RI "static List< \fBNetworkHit\fP > \fBreusableHitscanHitList\fP = new List<\fBNetworkHit\fP>()"
.br
.ti -1c
.RI "static List< \fBNetObject\fP > \fBreusableNetObjectsList\fP = new List<\fBNetObject\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility class that contains methods to create a unified argument string for calling all of the Raycast/Overlap cast calls\&. 

Used by the Rewind Engine\&. 
.PP
Definition at line \fB49\fP of file \fBGenericHitscan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.GenericCastNonAlloc (this Transform srcT, Collider[] hits, RaycastHit[] rayhits, float distance, float radius, int mask, Quaternion orientation, bool useOffset, Vector3 offset1, Vector3 offset2, \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB508\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.GenericHitscanNonAlloc (this \fBHitscanDefinition\fP hd, Transform origin, \fBNetObject\fP ownerNetObj, ref List< \fBNetworkHit\fP > hitscanHits, ref int nearestIndex, bool showDebugWidgets = \fCfalse\fP, bool useSecondaryRealm = \fCfalse\fP)\fC [static]\fP"
Check each collider hit for its contactGroup and its rootgameobject/viewID - add to our outgoing List<HitscanHit>
.PP
We are only interested in objects with IDs
.PP
Determine if any of the nested NetObjs is the owner\&.
.PP
If we are adding the nearest raycast, log it\&.
.PP
If we are adding the nearest raycast, log it\&.
.PP
Definition at line \fB247\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.GenericHitscanNonAlloc (this \fBHitscanDefinition\fP hd, Transform origin, out RaycastHit[] rayhits, out Collider[] hits, ref int nearestIndex, bool showDebugWidgets = \fCfalse\fP, bool useSecondaryRealm = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line \fB240\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.GenericHitscanNonAlloc (this \fBHitscanDefinition\fP hd, Transform origin, ref Collider[] hits, ref RaycastHit[] rayhits, ref int nearestIndex, bool showDebugWidgets = \fCfalse\fP, bool useSecondaryRealm = \fCfalse\fP)\fC [static]\fP"

.PP
Trigger the defined Cast/Overlap\&. 
.PP
\fBParameters\fP
.RS 4
\fIshowDebugWidgets\fP Show 3d visuals for hitscans\&. Disabled in Release Builds\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP
Overlaps have no rayhit info, so we are done\&.
.PP
Cast Nearest Only
.PP
Get Nearest
.PP
Cast All
.PP
Get Nearest
.PP
Definition at line \fB336\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.VisualizeHitscan (this \fBHitscanDefinition\fP hd, Transform origin, float duration = \fC\&.5f\fP)\fC [static]\fP"

.PP
Definition at line \fB106\fP of file \fBGenericHitscan\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Collider [] Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.reusableColliderArray = new Collider[64]\fC [static]\fP"

.PP
Definition at line \fB51\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "List<\fBNetworkHit\fP> Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.reusableHitscanHitList = new List<\fBNetworkHit\fP>()\fC [static]\fP"

.PP
Definition at line \fB53\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "List<\fBNetObject\fP> Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.reusableNetObjectsList = new List<\fBNetObject\fP>()\fC [static]\fP"

.PP
Definition at line \fB54\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "RaycastHit [] Photon\&.Pun\&.Simple\&.GenericHitscanExt\&.reusableRayHitArray = new RaycastHit[64]\fC [static]\fP"

.PP
Definition at line \fB52\fP of file \fBGenericHitscan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
