.TH "Photon.Pun.Demo.Cockpit.Forms.ConnectToRegionUIForm" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.Forms.ConnectToRegionUIForm \- Manager for ConnectToRegion UI Form  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnSubmitEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBEndEditOnEnter\fP ()"
.br
.ti -1c
.RI "void \fBSetRegionFromDropDown\fP (int index)"
.br
.ti -1c
.RI "void \fBSubmitForm\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBRegionInput\fP"
.br
.ti -1c
.RI "Dropdown \fBRegionListInput\fP"
.br
.ti -1c
.RI "\fBOnSubmitEvent\fP \fBOnSubmit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Manager for ConnectToRegion UI Form 
.PP
Definition at line \fB17\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.EndEditOnEnter ()"

.PP
Definition at line \fB33\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.SetRegionFromDropDown (int index)"

.PP
Definition at line \fB41\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.Start ()"

.PP
Definition at line \fB27\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.SubmitForm ()"

.PP
Definition at line \fB52\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBOnSubmitEvent\fP Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.OnSubmit"

.PP
Definition at line \fB25\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.RegionInput"

.PP
Definition at line \fB19\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.
.SS "Dropdown Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.ConnectToRegionUIForm\&.RegionListInput"

.PP
Definition at line \fB20\fP of file \fBConnectToRegionUIForm\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
