.TH "Photon.Pun.Simple.OnStateChangeToggle" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.OnStateChangeToggle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "void \fBOnStateChange\fP (\fBObjState\fP newState, \fBObjState\fP previousState, Transform pickup, \fBMount\fP attachedTo=null, bool isReady=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDisplayToggle\fP \fBtoggle\fP = \fBDisplayToggle\&.GameObject\fP"
.br
.ti -1c
.RI "Component \fBcomponent\fP"
.br
.ti -1c
.RI "GameObject \fB_gameObject\fP"
.br
.ti -1c
.RI "Renderer \fB_renderer\fP"
.br
.ti -1c
.RI "\fBObjStateLogic\fP \fBstateLogic\fP = new \fBObjStateLogic\fP()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB58\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&.OnStateChange (\fBObjState\fP newState, \fBObjState\fP previousState, Transform pickup, \fBMount\fP attachedTo = \fCnull\fP, bool isReady = \fCtrue\fP)"
If there is no object to attach to yet (due to keyframes) we need to keep this invisible\&.
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP\&.
.PP
Definition at line \fB83\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&._gameObject"

.PP
Definition at line \fB30\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SS "Renderer Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&._renderer"

.PP
Definition at line \fB33\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SS "Component Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&.component"

.PP
Definition at line \fB27\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SS "\fBObjStateLogic\fP Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&.stateLogic = new \fBObjStateLogic\fP()"

.PP
Definition at line \fB36\fP of file \fBOnStateChangeToggle\&.cs\fP\&.
.SS "\fBDisplayToggle\fP Photon\&.Pun\&.Simple\&.OnStateChangeToggle\&.toggle = \fBDisplayToggle\&.GameObject\fP"

.PP
Definition at line \fB23\fP of file \fBOnStateChangeToggle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
