.TH "Photon.Compression.Internal.IPackList< T >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.IPackList< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref List< T > value, List< T > prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref List< T > value, BitArray mask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.PP
Definition at line \fB40\fP of file \fBPackFieldInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSerializationFlags\fP \fBPhoton\&.Compression\&.Internal\&.IPackList\fP< T >\&.Pack (ref List< T > value, List< T > prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.SS "\fBSerializationFlags\fP \fBPhoton\&.Compression\&.Internal\&.IPackList\fP< T >\&.Unpack (ref List< T > value, BitArray mask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
