.TH "Photon.Pun.Demo.PunBasics" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameraWork\fP"
.br
.RI "Camera work\&. "
.ti -1c
.RI "class \fBGameManager\fP"
.br
.RI "Game manager\&. "
.ti -1c
.RI "class \fBLauncher\fP"
.br
.RI "Launch manager\&. "
.ti -1c
.RI "class \fBLoaderAnime\fP"
.br
.RI "\fBSimple\fP behaviour to animate particles around to create a typical 'Ajax Loader'\&. "
.ti -1c
.RI "class \fBPlayerAnimatorManager\fP"
.br
.ti -1c
.RI "class \fBPlayerManager\fP"
.br
.RI "Player manager\&. "
.ti -1c
.RI "class \fBPlayerNameInputField\fP"
.br
.RI "Player name input field\&. "
.ti -1c
.RI "class \fBPlayerUI\fP"
.br
.RI "Player UI\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
