.TH "Photon.Pun.Simple.IOnQuantize" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnQuantize
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnQuantize\fP (int frameId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB77\fP of file \fBSyncObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnQuantize\&.OnQuantize (int frameId)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
