.TH "Photon.Pun.Simple.ObjStateLogic" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ObjStateLogic
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.MaskLogic\fP\&.
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static int[] \fBstateValues\fP = (int[])System\&.Enum\&.GetValues(typeof(\fBObjStateEditor\fP))"
.br
.ti -1c
.RI "static string[] \fBstateNames\fP = System\&.Enum\&.GetNames(typeof(\fBObjStateEditor\fP))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBDefinesZero\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string[] \fBEnumNames\fP\fC [get]\fP"
.br
.ti -1c
.RI "override int[] \fBEnumValues\fP\fC [get]\fP"
.br
.ti -1c
.RI "override int \fBDefaultValue\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBItemStateLogic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] Photon\&.Pun\&.Simple\&.ObjStateLogic\&.stateNames = System\&.Enum\&.GetNames(typeof(\fBObjStateEditor\fP))\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB13\fP of file \fBItemStateLogic\&.cs\fP\&.
.SS "int [] Photon\&.Pun\&.Simple\&.ObjStateLogic\&.stateValues = (int[])System\&.Enum\&.GetValues(typeof(\fBObjStateEditor\fP))\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB12\fP of file \fBItemStateLogic\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override int Photon\&.Pun\&.Simple\&.ObjStateLogic\&.DefaultValue\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB18\fP of file \fBItemStateLogic\&.cs\fP\&.
.SS "override bool Photon\&.Pun\&.Simple\&.ObjStateLogic\&.DefinesZero\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB15\fP of file \fBItemStateLogic\&.cs\fP\&.
.SS "override string [] Photon\&.Pun\&.Simple\&.ObjStateLogic\&.EnumNames\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBItemStateLogic\&.cs\fP\&.
.SS "override int [] Photon\&.Pun\&.Simple\&.ObjStateLogic\&.EnumValues\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBItemStateLogic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
