.TH "Photon.Pun.Demo.Cockpit.FriendListCell" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.FriendListCell \- Friend list cell  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBFriendListView\&.FriendDetail\fP details)"
.br
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBFriendInfo\fP info)"
.br
.ti -1c
.RI "void \fBJoinFriendRoom\fP ()"
.br
.ti -1c
.RI "void \fBRemoveFromList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFriendListView\fP \fBListManager\fP"
.br
.ti -1c
.RI "Text \fBNameText\fP"
.br
.ti -1c
.RI "GameObject \fBOnlineFlag\fP"
.br
.ti -1c
.RI "GameObject \fBinRoomText\fP"
.br
.ti -1c
.RI "GameObject \fBJoinButton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Friend list cell 
.PP
Definition at line \fB18\fP of file \fBFriendListCell\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.JoinFriendRoom ()"

.PP
Definition at line \fB51\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.RefreshInfo (\fBFriendInfo\fP info)"

.PP
Definition at line \fB41\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.RefreshInfo (\fBFriendListView\&.FriendDetail\fP details)"

.PP
Definition at line \fB31\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.RemoveFromList ()"

.PP
Definition at line \fB57\fP of file \fBFriendListCell\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.inRoomText"

.PP
Definition at line \fB25\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.JoinButton"

.PP
Definition at line \fB26\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "\fBFriendListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.ListManager"

.PP
Definition at line \fB20\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.NameText"

.PP
Definition at line \fB22\fP of file \fBFriendListCell\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListCell\&.OnlineFlag"

.PP
Definition at line \fB23\fP of file \fBFriendListCell\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
