.TH "Photon.Pun.UtilityScripts.PunPlayerScores" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PunPlayerScores \- Scoring system for PhotonPlayer  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBPlayerScoreProp\fP = 'score'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Scoring system for PhotonPlayer 
.PP
Definition at line \fB25\fP of file \fBPunPlayerScores\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Photon\&.Pun\&.UtilityScripts\&.PunPlayerScores\&.PlayerScoreProp = 'score'\fC [static]\fP"

.PP
Definition at line \fB27\fP of file \fBPunPlayerScores\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
