.TH "Photon.Chat.Demo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.Demo
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppSettingsExtensions\fP"
.br
.ti -1c
.RI "class \fBChannelSelector\fP"
.br
.ti -1c
.RI "class \fBChatAppIdCheckerUI\fP"
.br
.ti -1c
.RI "class \fBChatGui\fP"
.br
.RI "This simple \fBChat\fP UI demonstrate basics usages of the \fBChat\fP Api "
.ti -1c
.RI "class \fBFriendItem\fP"
.br
.RI "Friend UI item used to represent the friend status as well as message\&. "
.ti -1c
.RI "class \fBIgnoreUiRaycastWhenInactive\fP"
.br
.ti -1c
.RI "class \fBNamePickGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
