.TH "Photon.Realtime.TypedLobbyInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.TypedLobbyInfo \- Info for a lobby on the server\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Realtime\&.TypedLobby\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBPlayerCount\fP"
.br
.RI "Count of players that currently joined this lobby\&."
.ti -1c
.RI "int \fBRoomCount\fP"
.br
.RI "Count of rooms currently associated with this lobby\&."
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Info for a lobby on the server\&. 

Used when \fBLoadBalancingClient\&.EnableLobbyStatistics\fP is true\&. 
.PP
Definition at line \fB2042\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Realtime\&.TypedLobbyInfo\&.ToString ()"

.PP
Definition at line \fB2050\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Realtime\&.TypedLobbyInfo\&.PlayerCount"

.PP
Count of players that currently joined this lobby\&.
.PP
Definition at line \fB2045\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.TypedLobbyInfo\&.RoomCount"

.PP
Count of rooms currently associated with this lobby\&.
.PP
Definition at line \fB2048\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
