.TH "Photon.Utilities.VersaMaskAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.VersaMaskAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersaMaskAttribute\fP (bool \fBdefinesZero\fP=false, Type \fBcastTo\fP=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdefinesZero\fP"
.br
.ti -1c
.RI "Type \fBcastTo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBVersaMaskAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Utilities\&.VersaMaskAttribute\&.VersaMaskAttribute (bool definesZero = \fCfalse\fP, Type castTo = \fCnull\fP)"

.PP
Definition at line \fB21\fP of file \fBVersaMaskAttribute\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Type Photon\&.Utilities\&.VersaMaskAttribute\&.castTo"

.PP
Definition at line \fB19\fP of file \fBVersaMaskAttribute\&.cs\fP\&.
.SS "bool Photon\&.Utilities\&.VersaMaskAttribute\&.definesZero"

.PP
Definition at line \fB18\fP of file \fBVersaMaskAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
