.TH "Photon.Pun.Demo.Cockpit.DocLinkButton" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.DocLinkButton \- Open an Url on Pointer Click\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData pointerEventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDocLinks\&.DocTypes\fP \fBType\fP = DocLinks\&.DocTypes\&.Doc"
.br
.ti -1c
.RI "string \fBReference\fP = 'getting\-started/pun\-intro'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Open an Url on Pointer Click\&. 


.PP
Definition at line \fB17\fP of file \fBDocLinkButton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.DocLinkButton\&.OnPointerClick (PointerEventData pointerEventData)"

.PP
Definition at line \fB28\fP of file \fBDocLinkButton\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.DocLinkButton\&.Start ()"

.PP
Definition at line \fB25\fP of file \fBDocLinkButton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.DocLinkButton\&.Reference = 'getting\-started/pun\-intro'"

.PP
Definition at line \fB21\fP of file \fBDocLinkButton\&.cs\fP\&.
.SS "\fBDocLinks\&.DocTypes\fP Photon\&.Pun\&.Demo\&.Cockpit\&.DocLinkButton\&.Type = DocLinks\&.DocTypes\&.Doc"

.PP
Definition at line \fB19\fP of file \fBDocLinkButton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
