.TH "Photon.Pun.Simple.IOnPostSimulate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPostSimulate \- Callback Interface for \fBOnPostSimulate()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, and \fBTickMover\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostSimulate\fP (int frameId, int subFrameId, bool isNetTick)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPostSimulate()\fP\&. 

Called after all normal FixedUpdate() calls in MonoBehaviours\&. 
.PP
Definition at line \fB46\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPostSimulate\&.OnPostSimulate (int frameId, int subFrameId, bool isNetTick)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, and \fBTickMover\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
