.TH "Photon.Chat.Demo.FriendItem" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.Demo.FriendItem \- Friend UI item used to represent the friend status as well as message\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnFriendStatusUpdate\fP (int status, bool gotMessage, object message)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBNameLabel\fP"
.br
.ti -1c
.RI "Text \fBStatusLabel\fP"
.br
.ti -1c
.RI "Text \fBHealth\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFriendId\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Friend UI item used to represent the friend status as well as message\&. 

It aims at showing how to share health for a friend that plays on a different room than you for example\&. But of course the message can be anything and a lot more complex\&. 
.PP
Definition at line \fB19\fP of file \fBFriendItem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Chat\&.Demo\&.FriendItem\&.Awake ()"

.PP
Definition at line \fB32\fP of file \fBFriendItem\&.cs\fP\&.
.SS "void Photon\&.Chat\&.Demo\&.FriendItem\&.OnFriendStatusUpdate (int status, bool gotMessage, object message)"

.PP
Definition at line \fB37\fP of file \fBFriendItem\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Chat\&.Demo\&.FriendItem\&.Health"

.PP
Definition at line \fB30\fP of file \fBFriendItem\&.cs\fP\&.
.SS "Text Photon\&.Chat\&.Demo\&.FriendItem\&.NameLabel"

.PP
Definition at line \fB28\fP of file \fBFriendItem\&.cs\fP\&.
.SS "Text Photon\&.Chat\&.Demo\&.FriendItem\&.StatusLabel"

.PP
Definition at line \fB29\fP of file \fBFriendItem\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Chat\&.Demo\&.FriendItem\&.FriendId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB22\fP of file \fBFriendItem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
