.TH "Photon.Pun.IOnPhotonViewPreNetDestroy" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.IOnPhotonViewPreNetDestroy \- This interface defines a callback which fires prior to the \fBPhotonNetwork\fP destroying the \fBPhotonView\fP and Gameobject\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.IPhotonViewCallback\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreNetDestroy\fP (\fBPhotonView\fP rootView)"
.br
.RI "This method is called before Destroy() is initiated for a networked object\&. "
.in -1c
.SH "Detailed Description"
.PP 
This interface defines a callback which fires prior to the \fBPhotonNetwork\fP destroying the \fBPhotonView\fP and Gameobject\&. 


.PP
Definition at line \fB16\fP of file \fBIPhotonViewCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.IOnPhotonViewPreNetDestroy\&.OnPreNetDestroy (\fBPhotonView\fP rootView)"

.PP
This method is called before Destroy() is initiated for a networked object\&. 
.PP
\fBParameters\fP
.RS 4
\fIrootView\fP 
.RE
.PP

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
