.TH "Photon.Pun.UtilityScripts.OnEscapeQuit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.OnEscapeQuit \- This component will quit the application when escape key is pressed  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This component will quit the application when escape key is pressed 
.PP
Definition at line \fB20\fP of file \fBOnEscapeQuit\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.OnEscapeQuit\&.Update ()"

.PP
Definition at line \fB23\fP of file \fBOnEscapeQuit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
