.TH "Photon.Pun.Simple.ContactGroups.ContactGroupValues" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.ContactGroupValues
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< float > \fBvalues\fP = new List<float>() { 1 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBContactGroupValues\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<float> Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupValues\&.values = new List<float>() { 1 }"

.PP
Definition at line \fB19\fP of file \fBContactGroupValues\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
