.TH "Photon.Compression.Element" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Element \- A struct that allows Quaternion and Vector types to be treated as the same\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits System\&.IEquatable< Element >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBVectorType\fP { \fBVector3\fP = 1, \fBQuaternion\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElement\fP (Vector3 \fBv\fP)"
.br
.ti -1c
.RI "\fBElement\fP (Quaternion \fBquat\fP)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBElement\fP other)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBoperator Quaternion\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "static \fBoperator Vector3\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "static \fBElement\fP \fBSlerp\fP (\fBElement\fP a, \fBElement\fP b, float t)"
.br
.ti -1c
.RI "static \fBElement\fP \fBSlerpUnclamped\fP (\fBElement\fP a, \fBElement\fP b, float t)"
.br
.ti -1c
.RI "static bool \fBoperator==\fP (\fBElement\fP a, \fBElement\fP b)"
.br
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBElement\fP a, \fBElement\fP b)"
.br
.ti -1c
.RI "static bool \fBEquals\fP (Vector3 a, Vector3 b)"
.br
.ti -1c
.RI "static bool \fBEquals\fP (Quaternion a, Quaternion b)"
.br
.ti -1c
.RI "static implicit \fBoperator Element\fP (Quaternion q)"
.br
.ti -1c
.RI "static implicit \fBoperator Element\fP (Vector3 \fBv\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVectorType\fP \fBvectorType\fP"
.br
.ti -1c
.RI "Vector3 \fBv\fP"
.br
.ti -1c
.RI "Quaternion \fBquat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct that allows Quaternion and Vector types to be treated as the same\&. 


.PP
Definition at line \fB16\fP of file \fBElement\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Compression\&.Element\&.VectorType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVector3 \fP\fP
.TP
\fB\fIQuaternion \fP\fP
.PP
Definition at line \fB18\fP of file \fBElement\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.Element\&.Element (Vector3 v)"

.PP
Definition at line \fB31\fP of file \fBElement\&.cs\fP\&.
.SS "Photon\&.Compression\&.Element\&.Element (Quaternion quat)"

.PP
Definition at line \fB37\fP of file \fBElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Photon\&.Compression\&.Element\&.Equals (\fBElement\fP other)"

.PP
Definition at line \fB120\fP of file \fBElement\&.cs\fP\&.
.SS "override bool Photon\&.Compression\&.Element\&.Equals (object obj)"

.PP
Definition at line \fB115\fP of file \fBElement\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.Element\&.Equals (Quaternion a, Quaternion b)\fC [static]\fP"

.PP
Definition at line \fB146\fP of file \fBElement\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.Element\&.Equals (Vector3 a, Vector3 b)\fC [static]\fP"

.PP
Definition at line \fB136\fP of file \fBElement\&.cs\fP\&.
.SS "override int Photon\&.Compression\&.Element\&.GetHashCode ()"

.PP
Definition at line \fB167\fP of file \fBElement\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.Element\&.operator \fBElement\fP (Quaternion q)\fC [static]\fP"

.PP
Definition at line \fB159\fP of file \fBElement\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.Element\&.operator \fBElement\fP (Vector3 v)\fC [static]\fP"

.PP
Definition at line \fB160\fP of file \fBElement\&.cs\fP\&.
.SS "static Photon\&.Compression\&.Element\&.operator Quaternion (\fBElement\fP e)\fC [explicit]\fP, \fC [static]\fP"

.PP
Definition at line \fB47\fP of file \fBElement\&.cs\fP\&.
.SS "static Photon\&.Compression\&.Element\&.operator Vector3 (\fBElement\fP e)\fC [explicit]\fP, \fC [static]\fP"

.PP
Definition at line \fB60\fP of file \fBElement\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.Element\&.operator!= (\fBElement\fP a, \fBElement\fP b)\fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBElement\&.cs\fP\&.
.SS "static bool Photon\&.Compression\&.Element\&.operator== (\fBElement\fP a, \fBElement\fP b)\fC [static]\fP"

.PP
Definition at line \fB94\fP of file \fBElement\&.cs\fP\&.
.SS "static \fBElement\fP Photon\&.Compression\&.Element\&.Slerp (\fBElement\fP a, \fBElement\fP b, float t)\fC [static]\fP"

.PP
Definition at line \fB76\fP of file \fBElement\&.cs\fP\&.
.SS "static \fBElement\fP Photon\&.Compression\&.Element\&.SlerpUnclamped (\fBElement\fP a, \fBElement\fP b, float t)\fC [static]\fP"

.PP
Definition at line \fB84\fP of file \fBElement\&.cs\fP\&.
.SS "override string Photon\&.Compression\&.Element\&.ToString ()"

.PP
Definition at line \fB162\fP of file \fBElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Quaternion Photon\&.Compression\&.Element\&.quat"

.PP
Definition at line \fB27\fP of file \fBElement\&.cs\fP\&.
.SS "Vector3 Photon\&.Compression\&.Element\&.v"

.PP
Definition at line \fB24\fP of file \fBElement\&.cs\fP\&.
.SS "\fBVectorType\fP Photon\&.Compression\&.Element\&.vectorType"

.PP
Definition at line \fB21\fP of file \fBElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
