.TH "Photon.Pun.Demo.Cockpit.PropertyCell" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.PropertyCell \- Generic string Property Cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateInfo\fP (string value)"
.br
.ti -1c
.RI "void \fBAddToList\fP (string property, string value, bool animate=false)"
.br
.ti -1c
.RI "void \fBRemoveFromList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBPropertyText\fP"
.br
.ti -1c
.RI "Text \fBValueText\fP"
.br
.ti -1c
.RI "Image \fBisUpdatedFlag\fP"
.br
.ti -1c
.RI "LayoutElement \fBLayoutElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic string Property Cell\&. 


.PP
Definition at line \fB18\fP of file \fBPropertyCell\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.AddToList (string property, string value, bool animate = \fCfalse\fP)"

.PP
Definition at line \fB38\fP of file \fBPropertyCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.RemoveFromList ()"

.PP
Definition at line \fB64\fP of file \fBPropertyCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.UpdateInfo (string value)"

.PP
Definition at line \fB27\fP of file \fBPropertyCell\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.isUpdatedFlag"

.PP
Definition at line \fB23\fP of file \fBPropertyCell\&.cs\fP\&.
.SS "LayoutElement Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.LayoutElement"

.PP
Definition at line \fB25\fP of file \fBPropertyCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.PropertyText"

.PP
Definition at line \fB20\fP of file \fBPropertyCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PropertyCell\&.ValueText"

.PP
Definition at line \fB21\fP of file \fBPropertyCell\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
