.TH "Photon.Chat.ChannelCreationOptions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ChannelCreationOptions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBChannelCreationOptions\fP \fBDefault\fP = new \fBChannelCreationOptions\fP()"
.br
.RI "Default values of channel creation options\&."
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBPublishSubscribers\fP\fC [getset]\fP"
.br
.RI "Whether or not the channel to be created will allow client to keep a list of users\&."
.ti -1c
.RI "int \fBMaxSubscribers\fP\fC [getset]\fP"
.br
.RI "Limit of the number of users subscribed to the channel to be created\&."
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBChannelCreationOptions\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChannelCreationOptions\fP Photon\&.Chat\&.ChannelCreationOptions\&.Default = new \fBChannelCreationOptions\fP()\fC [static]\fP"

.PP
Default values of channel creation options\&.
.PP
Definition at line \fB12\fP of file \fBChannelCreationOptions\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Chat\&.ChannelCreationOptions\&.MaxSubscribers\fC [get]\fP, \fC [set]\fP"

.PP
Limit of the number of users subscribed to the channel to be created\&.
.PP
Definition at line \fB16\fP of file \fBChannelCreationOptions\&.cs\fP\&.
.SS "bool Photon\&.Chat\&.ChannelCreationOptions\&.PublishSubscribers\fC [get]\fP, \fC [set]\fP"

.PP
Whether or not the channel to be created will allow client to keep a list of users\&.
.PP
Definition at line \fB14\fP of file \fBChannelCreationOptions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
