.TH "Photon.Pun.Simple.IOnPreQuit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPreQuit \- Callback Interface for \fBOnPreQuit()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.Mount\fP, \fBPhoton\&.Pun\&.Simple\&.MountsManager\fP, and \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreQuit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPreQuit()\fP\&. 

Triggered when \fBNetMaster\fP OnApplicationQuit() is called\&. \fBNetMaster\fP's script execution order is set to fire prior to all other MonoB scripts, so \fBOnPreQuit()\fP will fire prior to OnApplicationQuit() on all scripts\&. 
.PP
Definition at line \fB57\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPreQuit\&.OnPreQuit ()"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.Mount\fP, \fBPhoton\&.Pun\&.Simple\&.MountsManager\fP, and \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
