.TH "Photon.Pun.Demo.Procedural.ProceduralController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Procedural.ProceduralController \- \fBSimple\fP Input Handler to control the camera\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Use horizontal and vertical axes (by default WASD or the arrow keys) for moving for-, back- or sidewards\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSimple\fP Input Handler to control the camera\&. 


.PP
Definition at line \fB8\fP of file \fBProceduralController\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.ProceduralController\&.Awake ()"

.PP
Definition at line \fB14\fP of file \fBProceduralController\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.ProceduralController\&.Update ()"

.PP
Use horizontal and vertical axes (by default WASD or the arrow keys) for moving for-, back- or sidewards\&. Use E or Q for 'zooming' in or out\&. Use the left mouse button to decrease a \fBBlock\fP's height or the right mouse button to increase a \fBBlock\fP's height\&. 
.PP
Definition at line \fB25\fP of file \fBProceduralController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
