.TH "Photon.Pun.UtilityScripts.ScoreExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.ScoreExtensions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetScore\fP (this \fBPlayer\fP player, int newScore)"
.br
.ti -1c
.RI "static void \fBAddScore\fP (this \fBPlayer\fP player, int scoreToAddToCurrent)"
.br
.ti -1c
.RI "static int \fBGetScore\fP (this \fBPlayer\fP player)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBPunPlayerScores\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.UtilityScripts\&.ScoreExtensions\&.AddScore (this \fBPlayer\fP player, int scoreToAddToCurrent)\fC [static]\fP"

.PP
Definition at line \fB40\fP of file \fBPunPlayerScores\&.cs\fP\&.
.SS "static int Photon\&.Pun\&.UtilityScripts\&.ScoreExtensions\&.GetScore (this \fBPlayer\fP player)\fC [static]\fP"

.PP
Definition at line \fB51\fP of file \fBPunPlayerScores\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.UtilityScripts\&.ScoreExtensions\&.SetScore (this \fBPlayer\fP player, int newScore)\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBPunPlayerScores\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
