.TH "Photon.Compression.WorldBoundsSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.WorldBoundsSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Utilities\&.SettingsScriptableObject< WorldBoundsSettings >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRemoveWorldBoundsFromAll\fP (\fBWorldBounds\fP wb)"
.br
.ti -1c
.RI "static int \fBTallyBits\fP (ref int index, BitCullingLevel bcl=BitCullingLevel\&.NoCulling)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBWorldBoundsGroup\fP > \fBworldBoundsGroups\fP = new List<\fBWorldBoundsGroup\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBElementCrusher\fP \fBdefaultWorldBoundsCrusher\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Compression\&.WorldBoundsSettings\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Utilities\&.SettingsScriptableObject< WorldBoundsSettings >\fP\&.
.PP
Definition at line \fB51\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SS "override void Photon\&.Compression\&.WorldBoundsSettings\&.Initialize ()"

.PP
Definition at line \fB59\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.WorldBoundsSettings\&.RemoveWorldBoundsFromAll (\fBWorldBounds\fP wb)\fC [static]\fP"

.PP
Definition at line \fB74\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.WorldBoundsSettings\&.TallyBits (ref int index, BitCullingLevel bcl = \fCBitCullingLevel\&.NoCulling\fP)\fC [static]\fP"

.PP
Definition at line \fB88\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBElementCrusher\fP Photon\&.Compression\&.WorldBoundsSettings\&.defaultWorldBoundsCrusher\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBWorldBoundsSettings\&.cs\fP\&.
.SS "List<\fBWorldBoundsGroup\fP> Photon\&.Compression\&.WorldBoundsSettings\&.worldBoundsGroups = new List<\fBWorldBoundsGroup\fP>()"

.PP
Definition at line \fB48\fP of file \fBWorldBoundsSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
