.TH "Photon.Pun.Simple.NetworkHit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.NetworkHit \- A networkable representation of an object hit, from a collision, trigger or hitscan\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkHit\fP (int objectID, int \fBhitMask\fP, int \fBcolliderId\fP)"
.br
.ti -1c
.RI "void \fBSerialize\fP (byte[] buffer, ref int bitposition, int bitsForHitmask, int bitsForColliderId)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBNetworkHit\fP \fBDeserialize\fP (byte[] buffer, ref int bitposition, int bitsForHitmask, int bitsForColliderId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly int \fBnetObjId\fP"
.br
.ti -1c
.RI "readonly int \fBhitMask\fP"
.br
.ti -1c
.RI "readonly int \fBcolliderId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A networkable representation of an object hit, from a collision, trigger or hitscan\&. 


.PP
Definition at line \fB14\fP of file \fBNetworkHit\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.NetworkHit\&.NetworkHit (int objectID, int hitMask, int colliderId)"

.PP
Definition at line \fB20\fP of file \fBNetworkHit\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBNetworkHit\fP Photon\&.Pun\&.Simple\&.NetworkHit\&.Deserialize (byte[] buffer, ref int bitposition, int bitsForHitmask, int bitsForColliderId)\fC [static]\fP"

.PP
Definition at line \fB34\fP of file \fBNetworkHit\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.NetworkHit\&.Serialize (byte[] buffer, ref int bitposition, int bitsForHitmask, int bitsForColliderId)"

.PP
Definition at line \fB27\fP of file \fBNetworkHit\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly int Photon\&.Pun\&.Simple\&.NetworkHit\&.colliderId"

.PP
Definition at line \fB18\fP of file \fBNetworkHit\&.cs\fP\&.
.SS "readonly int Photon\&.Pun\&.Simple\&.NetworkHit\&.hitMask"

.PP
Definition at line \fB17\fP of file \fBNetworkHit\&.cs\fP\&.
.SS "readonly int Photon\&.Pun\&.Simple\&.NetworkHit\&.netObjId"

.PP
Definition at line \fB16\fP of file \fBNetworkHit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
