.TH "Photon.Pun.Simple.SyncMoverBase< TTRSDef, TFrame >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncMoverBase< TTRSDef, TFrame >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.SyncObject< TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.ITransformController\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwakeInitialize\fP (bool isNetObject)"
.br
.RI "Awake code that will run whether or not a \fBNetObject\fP Exists "
.ti -1c
.RI "override void \fBOnStartInitialize\fP (bool isNetObject)"
.br
.RI "Awake code that will run whether or not a \fBNetObject\fP Exists "
.ti -1c
.RI "virtual void \fBRecalculate\fP ()"
.br
.ti -1c
.RI "abstract void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.ti -1c
.RI "abstract void \fBOnPreUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TTRSDef \fBposDef\fP = new TTRSDef()"
.br
.ti -1c
.RI "TTRSDef \fBrotDef\fP = new TTRSDef()"
.br
.ti -1c
.RI "TTRSDef \fBsclDef\fP = new TTRSDef()"
.br
.ti -1c
.RI "\fBSyncTransform\fP \fBsyncTransform\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBInitializeTRS\fP (TTRSDef def, \fBTRS\fP type)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Rigidbody \fBrb\fP"
.br
.ti -1c
.RI "Rigidbody2D \fBrb2d\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBHandlesInterpolation\fP\fC [get]\fP"
.br
.RI "TODO: This may need a different reply for Trigger - unless I can make that deterministic\&. "
.ti -1c
.RI "virtual bool \fBHandlesExtrapolation\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fITTRSDef\fP : \fI\fBTRSDefinitionBase\fP\fP
.TP
\fITTRSDef\fP : \fInew()\fP
.TP
\fITFrame\fP : \fI\fBFrameBase\fP\fP
.TP
\fITFrame\fP : \fInew()\fP
.PP
Definition at line \fB22\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.InitializeTRS (TTRSDef def, \fBTRS\fP type)\fC [protected]\fP, \fC [pure virtual]\fP"

.SS "override void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.OnAwakeInitialize (bool isNetObject)\fC [virtual]\fP"

.PP
Awake code that will run whether or not a \fBNetObject\fP Exists 
.PP
\fBReturns\fP
.RS 4
Returns true if this is a \fBNetObject\fP
.RE
.PP
If not a \fBNetObject\fP, we need to register our timing callbacks directly with the \fBNetMaster\fP since there is no \fBNetObject\fP to generate these\&.
.PP
Force RBs to be kinematic
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB73\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "abstract void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.OnPreSimulate (int frameId, int subFrameId)\fC [pure virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP\&.
.SS "abstract void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.OnPreUpdate ()\fC [pure virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP\&.
.SS "override void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.OnStartInitialize (bool isNetObject)\fC [virtual]\fP"

.PP
Awake code that will run whether or not a \fBNetObject\fP Exists 
.PP
\fBReturns\fP
.RS 4
Returns true if this is a \fBNetObject\fP
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB101\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "virtual void \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.Recalculate ()\fC [virtual]\fP"

.PP
Definition at line \fB119\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TTRSDef \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.posDef = new TTRSDef()"

.PP
Definition at line \fB35\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "Rigidbody \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.rb\fC [protected]\fP"

.PP
Definition at line \fB66\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "Rigidbody2D \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.rb2d\fC [protected]\fP"

.PP
Definition at line \fB67\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "TTRSDef \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.rotDef = new TTRSDef()"

.PP
Definition at line \fB36\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "TTRSDef \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.sclDef = new TTRSDef()"

.PP
Definition at line \fB37\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "\fBSyncTransform\fP \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.syncTransform"

.PP
Definition at line \fB69\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual bool \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.HandlesExtrapolation\fC [get]\fP"

.PP
Definition at line \fB47\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SS "virtual bool \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase\fP< TTRSDef, TFrame >\&.HandlesInterpolation\fC [get]\fP"

.PP
TODO: This may need a different reply for Trigger - unless I can make that deterministic\&. 
.PP
Definition at line \fB46\fP of file \fBSyncMoverBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
