.TH "Photon.Pun.DefaultPool" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.DefaultPool \- The default implementation of a PrefabPool for PUN, which actually Instantiates and Destroys GameObjects but pools a resource\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.IPunPrefabPool\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GameObject \fBInstantiate\fP (string prefabId, Vector3 position, Quaternion rotation)"
.br
.RI "Returns an inactive instance of a networked GameObject, to be used by PUN\&. "
.ti -1c
.RI "void \fBDestroy\fP (GameObject gameObject)"
.br
.RI "Simply destroys a GameObject\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly Dictionary< string, GameObject > \fBResourceCache\fP = new Dictionary<string, GameObject>()"
.br
.RI "Contains a GameObject per prefabId, to speed up instantiation\&."
.in -1c
.SH "Detailed Description"
.PP 
The default implementation of a PrefabPool for PUN, which actually Instantiates and Destroys GameObjects but pools a resource\&. 

This pool is not actually storing GameObjects for later reuse\&. Instead, it's destroying used GameObjects\&. However, prefabs will be loaded from a Resources folder and cached, which speeds up Instantiation a bit\&.
.PP
The ResourceCache is public, so it can be filled without relying on the Resources folders\&. 
.PP
Definition at line \fB857\fP of file \fBPunClasses\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.DefaultPool\&.Destroy (GameObject gameObject)"

.PP
Simply destroys a GameObject\&. 
.PP
\fBParameters\fP
.RS 4
\fIgameObject\fP The GameObject to get rid of\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Pun\&.IPunPrefabPool\fP\&.
.PP
Definition at line \fB895\fP of file \fBPunClasses\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.DefaultPool\&.Instantiate (string prefabId, Vector3 position, Quaternion rotation)"

.PP
Returns an inactive instance of a networked GameObject, to be used by PUN\&. 
.PP
\fBParameters\fP
.RS 4
\fIprefabId\fP String identifier for the networked object\&.
.br
\fIposition\fP Location of the new object\&.
.br
\fIrotation\fP Rotation of the new object\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBPhoton\&.Pun\&.IPunPrefabPool\fP\&.
.PP
Definition at line \fB867\fP of file \fBPunClasses\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Dictionary<string, GameObject> Photon\&.Pun\&.DefaultPool\&.ResourceCache = new Dictionary<string, GameObject>()"

.PP
Contains a GameObject per prefabId, to speed up instantiation\&.
.PP
Definition at line \fB860\fP of file \fBPunClasses\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
