.TH "Photon.Pun.UtilityScripts.OnClickInstantiate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.OnClickInstantiate \- Instantiates a networked GameObject on click\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInstantiateOption\fP { \fBMine\fP, \fBScene\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PointerEventData\&.InputButton \fBButton\fP"
.br
.ti -1c
.RI "KeyCode \fBModifierKey\fP"
.br
.ti -1c
.RI "GameObject \fBPrefab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instantiates a networked GameObject on click\&. 

Gets OnClick() calls by Unity's IPointerClickHandler\&. Needs a PhysicsRaycaster on the camera\&. See: https://docs.unity3d.com/ScriptReference/EventSystems.IPointerClickHandler.html 
.PP
Definition at line \fB23\fP of file \fBOnClickInstantiate\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.UtilityScripts\&.OnClickInstantiate\&.InstantiateOption\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMine \fP\fP
.TP
\fB\fIScene \fP\fP
.PP
Definition at line \fB25\fP of file \fBOnClickInstantiate\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PointerEventData\&.InputButton Photon\&.Pun\&.UtilityScripts\&.OnClickInstantiate\&.Button"

.PP
Definition at line \fB28\fP of file \fBOnClickInstantiate\&.cs\fP\&.
.SS "KeyCode Photon\&.Pun\&.UtilityScripts\&.OnClickInstantiate\&.ModifierKey"

.PP
Definition at line \fB29\fP of file \fBOnClickInstantiate\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.UtilityScripts\&.OnClickInstantiate\&.Prefab"

.PP
Definition at line \fB31\fP of file \fBOnClickInstantiate\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
