.TH "Photon.Pun.Demo.Asteroids.Asteroid" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids.Asteroid
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnCollisionEnter\fP (Collision collision)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisLargeAsteroid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBAsteroid\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.Asteroid\&.Awake ()"

.PP
Definition at line \fB32\fP of file \fBAsteroid\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.Asteroid\&.OnCollisionEnter (Collision collision)"

.PP
Definition at line \fB61\fP of file \fBAsteroid\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Asteroids\&.Asteroid\&.Update ()"

.PP
Definition at line \fB47\fP of file \fBAsteroid\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Demo\&.Asteroids\&.Asteroid\&.isLargeAsteroid"

.PP
Definition at line \fB20\fP of file \fBAsteroid\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
