.TH "Photon.Pun.Simple.ContactGroups.ContactGroupSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.ContactGroupSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Utilities\&.SettingsScriptableObject< ContactGroupSettings >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBInitialize\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBFindClosestMatch\fP (string n, int id)"
.br
.RI "Supplied a previous index and contactGroup name, and will return the index of the best guess in the current list of layer tags\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< string > \fBcontactGroupTags\fP = new List<string>(2) { \fBDEF_NAME\fP, 'Critical' }"
.br
.ti -1c
.RI "Dictionary< string, int > \fBrewindLayerTagToId\fP = new Dictionary<string, int>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBinitialized\fP"
.br
.ti -1c
.RI "const string \fBDEF_NAME\fP = 'Default'"
.br
.ti -1c
.RI "static int \fBbitsForMask\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.FindClosestMatch (string n, int id)\fC [static]\fP"

.PP
Supplied a previous index and contactGroup name, and will return the index of the best guess in the current list of layer tags\&. First checks for name, then if the previous int still exists, if none of the above returns 0; 
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.Initialize ()"

.PP
Definition at line \fB43\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.bitsForMask\fC [static]\fP"

.PP
Definition at line \fB31\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SS "List<string> Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.contactGroupTags = new List<string>(2) { \fBDEF_NAME\fP, 'Critical' }"

.PP
Definition at line \fB27\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.DEF_NAME = 'Default'\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.initialized\fC [static]\fP"

.PP
Definition at line \fB23\fP of file \fBContactGroupSettings\&.cs\fP\&.
.SS "Dictionary<string, int> Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSettings\&.rewindLayerTagToId = new Dictionary<string, int>()"

.PP
Definition at line \fB28\fP of file \fBContactGroupSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
