.TH "Photon.Pun.Demo.Cockpit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBForms\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppVersionProperty\fP"
.br
.RI "\fBPhotonNetwork\&.AppVersion\fP UI property\&. "
.ti -1c
.RI "class \fBAutoSyncSceneToggle\fP"
.br
.RI "\fBPhotonNetwork\&.AutomaticallySyncScene\fP UI Toggle "
.ti -1c
.RI "class \fBBackgroundTimeOutField\fP"
.br
.RI "PhotonNetwork\&.BackgroundTimeout UI InputField\&. "
.ti -1c
.RI "class \fBBestRegionInPrefsProperty\fP"
.br
.RI "\fBPhotonNetwork\&.BestRegionSummaryInPreferences\fP UI property\&. "
.ti -1c
.RI "class \fBBoolInputField\fP"
.br
.RI "Boolean UI UI Toggle input\&. "
.ti -1c
.RI "class \fBCloudRegionProperty\fP"
.br
.RI "\fBPhotonNetwork\&.CloudRegion\fP UI property\&. "
.ti -1c
.RI "class \fBCountOfPlayersInRoomProperty\fP"
.br
.RI "\fBPhotonNetwork\&.CountOfPlayersInRooms\fP UI property\&. "
.ti -1c
.RI "class \fBCountOfPlayersOnMasterProperty\fP"
.br
.RI "\fBPhotonNetwork\&.CountOfPlayersOnMaster\fP UI property\&. "
.ti -1c
.RI "class \fBCountOfPlayersProperty\fP"
.br
.RI "\fBPhotonNetwork\&.CountOfPlayers\fP UI property\&. "
.ti -1c
.RI "class \fBCountOfRoomsProperty\fP"
.br
.RI "\fBPhotonNetwork\&.CountOfRooms\fP UIs property\&. "
.ti -1c
.RI "class \fBCrcCheckToggle\fP"
.br
.RI "\fBPhotonNetwork\&.CrcCheckEnabled\fP UI Toggle "
.ti -1c
.RI "class \fBCurrentRoomAutoCleanupProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.AutoCleanUp UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomEmptyRoomTtlProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.EmptyRoomTtl UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomExpectedUsersProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.ExpectedUsers UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomIsOfflineProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.IsOffline UI property "
.ti -1c
.RI "class \fBCurrentRoomIsOpenProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.IsOpen UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomIsOpenToggle\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.IsOpen UI Toggle "
.ti -1c
.RI "class \fBCurrentRoomIsVisibleProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.IsVisible UI property "
.ti -1c
.RI "class \fBCurrentRoomIsVisibleToggle\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.IsVisible UI Toggle "
.ti -1c
.RI "class \fBCurrentRoomMasterClientIdProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.MasterClientId UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomMaxPlayersProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.MaxPlayers UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomNameProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.Name UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomPlayerCountProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.PlayerCount UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomPlayerTtlProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.PlayerTtl UI property\&. "
.ti -1c
.RI "class \fBCurrentRoomPropertiesListedInLobbyProperty\fP"
.br
.RI "PhotonNetwork\&.CurrentRoom\&.PropertiesListedInLobby UI property\&. "
.ti -1c
.RI "class \fBDocLinkButton\fP"
.br
.RI "Open an Url on Pointer Click\&. "
.ti -1c
.RI "class \fBFriendListCell\fP"
.br
.RI "Friend list cell "
.ti -1c
.RI "class \fBFriendListView\fP"
.br
.RI "Friend list UI view\&. "
.ti -1c
.RI "class \fBGameVersionField\fP"
.br
.RI "Game version field\&. "
.ti -1c
.RI "class \fBGameVersionProperty\fP"
.br
.RI "\fBPhotonNetwork\&.GameVersion\fP UI property\&. "
.ti -1c
.RI "class \fBInfosPanelPlaceholder\fP"
.br
.RI "Infos panel placeholder\&. "
.ti -1c
.RI "class \fBIntInputField\fP"
.br
.RI "Int UI InputField\&. "
.ti -1c
.RI "class \fBIsConnectedAndReadyProperty\fP"
.br
.RI "\fBPhotonNetwork\&.IsConnectedAndReady\fP UI property "
.ti -1c
.RI "class \fBIsConnectedProperty\fP"
.br
.RI "\fBPhotonNetwork\&.IsConnected\fP UI property "
.ti -1c
.RI "class \fBLayoutElementMatchSize\fP"
.br
.RI "Force a LayoutElement to march a RectTransform sizeDelta\&. "
.ti -1c
.RI "class \fBNickNameField\fP"
.br
.RI "Nickname InputField\&. "
.ti -1c
.RI "class \fBOfflineModeProperty\fP"
.br
.RI "\fBPhotonNetwork\&.OfflineMode\fP UI property "
.ti -1c
.RI "class \fBOnlineDocButton\fP"
.br
.RI "Open an Url on Pointer Click\&. "
.ti -1c
.RI "class \fBPingProperty\fP"
.br
.RI "\fBPhotonNetwork\&.GetPing()\fP UI property\&. "
.ti -1c
.RI "class \fBPlayerDetailsController\fP"
.br
.RI "Controller for the Playerdetails UI view "
.ti -1c
.RI "class \fBPlayerListCell\fP"
.br
.RI "Player list cell representing a given PhotonPlayer "
.ti -1c
.RI "class \fBPlayerListView\fP"
.br
.RI "Player list UI View\&. "
.ti -1c
.RI "class \fBPropertyCell\fP"
.br
.RI "Generic string Property Cell\&. "
.ti -1c
.RI "class \fBPropertyListenerBase\fP"
.br
.RI "Property listener base\&. "
.ti -1c
.RI "class \fBPunCockpit\fP"
.br
.RI "UI based work in progress to test out api and act as foundation when dealing with room, friends and player list "
.ti -1c
.RI "class \fBPunCockpitEmbed\fP"
.br
.RI "Use this in scenes you want to leave Control for connection and pun related commands to \fBCockpit\fP\&. "
.ti -1c
.RI "class \fBRegionListCell\fP"
.br
.RI "Region list cell\&. "
.ti -1c
.RI "class \fBRegionListView\fP"
.br
.RI "Region list UI View\&. "
.ti -1c
.RI "class \fBRoomListCell\fP"
.br
.RI "Roomlist cell\&. "
.ti -1c
.RI "class \fBRoomListView\fP"
.br
.RI "Room list UI View\&. "
.ti -1c
.RI "class \fBScoreHelper\fP"
.br
.ti -1c
.RI "class \fBSendRateField\fP"
.br
.RI "\fBPhotonNetwork\&.SendRate\fP InputField\&. "
.ti -1c
.RI "class \fBSendRateOnSerializeField\fP"
.br
.RI "\fBPhotonNetwork\&.SerializationRate\fP InputField "
.ti -1c
.RI "class \fBServerAddressProperty\fP"
.br
.RI "\fBPhotonNetwork\&.ServerAddress\fP UI property\&. "
.ti -1c
.RI "class \fBServerProperty\fP"
.br
.RI "\fBPhotonNetwork\&.Server\fP UI property "
.ti -1c
.RI "class \fBStringInputField\fP"
.br
.RI "String UI InputField\&. "
.ti -1c
.RI "class \fBToggleExpand\fP"
.br
.RI "UI toggle to activate GameObject\&. "
.ti -1c
.RI "class \fBUserIdField\fP"
.br
.RI "User identifier InputField\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
