.TH "Photon.Compression.Internal.PackObjectDatabase" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.PackObjectDatabase \- Runtime lookup for packing delegates all get associated with Types at runtime and are stored here\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPackObjectInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackStructDelegate\fP (IntPtr obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackObjDelegate\fP (ref System\&.Object obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackFrameDelegate\fP (\fBPackFrame\fP obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBUnpackFrameDelegate\fP (\fBPackFrame\fP obj, ref \fBFastBitMask128\fP hasContentMask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"
.br
.ti -1c
.RI "delegate void \fBPackCopyFrameToObjectDelegate\fP (\fBPackFrame\fP src, System\&.Object trg, ref \fBFastBitMask128\fP mask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackCopyFrameToStructDelegate\fP (\fBPackFrame\fP src, IntPtr trg, ref \fBFastBitMask128\fP mask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackSnapshotObjectDelegate\fP (\fBPackFrame\fP snap, \fBPackFrame\fP targ, System\&.Object trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackSnapshotStructDelegate\fP (\fBPackFrame\fP snap, \fBPackFrame\fP targ, IntPtr trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackInterpFrameToFrameDelegate\fP (\fBPackFrame\fP start, \fBPackFrame\fP end, \fBPackFrame\fP trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackInterpFrameToObjectDelegate\fP (\fBPackFrame\fP start, \fBPackFrame\fP end, System\&.Object trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "delegate void \fBPackInterpFrameToStructDelegate\fP (\fBPackFrame\fP start, \fBPackFrame\fP end, IntPtr trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPackObjectInfo\fP \fBGetPackObjectInfo\fP (Type type)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< Type, \fBPackObjectInfo\fP > \fBpackObjInfoLookup\fP = new Dictionary<Type, \fBPackObjectInfo\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Runtime lookup for packing delegates all get associated with Types at runtime and are stored here\&. 

Generated extensions register themselves with this on startup\&. 
.PP
Definition at line \fB27\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPackObjectInfo\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.GetPackObjectInfo (Type type)\fC [static]\fP"
May have not be initialized in time, brute force reflection initialize\&.
.PP
Definition at line \fB46\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackCopyFrameToObjectDelegate (\fBPackFrame\fP src, System\&.Object trg, ref \fBFastBitMask128\fP mask, ref int maskOffset)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackCopyFrameToStructDelegate (\fBPackFrame\fP src, IntPtr trg, ref \fBFastBitMask128\fP mask, ref int maskOffset)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackFrameDelegate (\fBPackFrame\fP obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackInterpFrameToFrameDelegate (\fBPackFrame\fP start, \fBPackFrame\fP end, \fBPackFrame\fP trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackInterpFrameToObjectDelegate (\fBPackFrame\fP start, \fBPackFrame\fP end, System\&.Object trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackInterpFrameToStructDelegate (\fBPackFrame\fP start, \fBPackFrame\fP end, IntPtr trg, float ntime, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackObjDelegate (ref System\&.Object obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackSnapshotObjectDelegate (\fBPackFrame\fP snap, \fBPackFrame\fP targ, System\&.Object trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"

.SS "delegate void Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackSnapshotStructDelegate (\fBPackFrame\fP snap, \fBPackFrame\fP targ, IntPtr trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.PackStructDelegate (IntPtr obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.UnpackFrameDelegate (\fBPackFrame\fP obj, ref \fBFastBitMask128\fP hasContentMask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP forceKeyframe)"

.SH "Member Data Documentation"
.PP 
.SS "Dictionary<Type, \fBPackObjectInfo\fP> Photon\&.Compression\&.Internal\&.PackObjectDatabase\&.packObjInfoLookup = new Dictionary<Type, \fBPackObjectInfo\fP>()\fC [static]\fP"

.PP
Definition at line \fB44\fP of file \fBPackObjectDatabase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
