.TH "Photon.Chat.ChatOperationCode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ChatOperationCode \- Wraps up codes for operations used internally in \fBPhoton\fP \fBChat\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBAuthenticate\fP = 230"
.br
.RI "(230) Operation Authenticate\&."
.ti -1c
.RI "const byte \fBSubscribe\fP = 0"
.br
.RI "(0) Operation to subscribe to chat channels\&."
.ti -1c
.RI "const byte \fBUnsubscribe\fP = 1"
.br
.RI "(1) Operation to unsubscribe from chat channels\&."
.ti -1c
.RI "const byte \fBPublish\fP = 2"
.br
.RI "(2) Operation to publish a message in a chat channel\&."
.ti -1c
.RI "const byte \fBSendPrivate\fP = 3"
.br
.RI "(3) Operation to send a private message to some other user\&."
.ti -1c
.RI "const byte \fBChannelHistory\fP = 4"
.br
.RI "(4) Not used yet\&."
.ti -1c
.RI "const byte \fBUpdateStatus\fP = 5"
.br
.RI "(5) Set your (client's) status\&."
.ti -1c
.RI "const byte \fBAddFriends\fP = 6"
.br
.RI "(6) Add friends the list of friends that should update you of their status\&."
.ti -1c
.RI "const byte \fBRemoveFriends\fP = 7"
.br
.RI "(7) Remove friends from list of friends that should update you of their status\&."
.ti -1c
.RI "const byte \fBSetProperties\fP = 8"
.br
.RI "(8) Operation to set properties of public chat channel or users in public chat channels\&."
.in -1c
.SH "Detailed Description"
.PP 
Wraps up codes for operations used internally in \fBPhoton\fP \fBChat\fP\&. 

You don't have to use them directly usually\&. 
.PP
Definition at line \fB12\fP of file \fBChatOperationCode\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.AddFriends = 6\fC [static]\fP"

.PP
(6) Add friends the list of friends that should update you of their status\&.
.PP
Definition at line \fB32\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.Authenticate = 230\fC [static]\fP"

.PP
(230) Operation Authenticate\&.
.PP
Definition at line \fB15\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.ChannelHistory = 4\fC [static]\fP"

.PP
(4) Not used yet\&.
.PP
Definition at line \fB27\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.Publish = 2\fC [static]\fP"

.PP
(2) Operation to publish a message in a chat channel\&.
.PP
Definition at line \fB22\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.RemoveFriends = 7\fC [static]\fP"

.PP
(7) Remove friends from list of friends that should update you of their status\&.
.PP
Definition at line \fB34\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.SendPrivate = 3\fC [static]\fP"

.PP
(3) Operation to send a private message to some other user\&.
.PP
Definition at line \fB24\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.SetProperties = 8\fC [static]\fP"

.PP
(8) Operation to set properties of public chat channel or users in public chat channels\&.
.PP
Definition at line \fB36\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.Subscribe = 0\fC [static]\fP"

.PP
(0) Operation to subscribe to chat channels\&.
.PP
Definition at line \fB18\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.Unsubscribe = 1\fC [static]\fP"

.PP
(1) Operation to unsubscribe from chat channels\&.
.PP
Definition at line \fB20\fP of file \fBChatOperationCode\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ChatOperationCode\&.UpdateStatus = 5\fC [static]\fP"

.PP
(5) Set your (client's) status\&.
.PP
Definition at line \fB30\fP of file \fBChatOperationCode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
