.TH "Photon.Pun.Simple.DoubleTime" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.DoubleTime
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSnapFixed\fP ()"
.br
.ti -1c
.RI "static void \fBSnapUpdate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBtime\fP"
.br
.ti -1c
.RI "static double \fBprevUpdateTime\fP"
.br
.ti -1c
.RI "static double \fBprevFixedTime\fP"
.br
.ti -1c
.RI "static double \fBdeltaTime\fP"
.br
.ti -1c
.RI "static double \fBtimeSinceFixed\fP"
.br
.ti -1c
.RI "static double \fBfixedTime\fP"
.br
.ti -1c
.RI "static double \fBfixedDeltaTime\fP"
.br
.ti -1c
.RI "static float \fBnormTimeSinceFixed\fP"
.br
.ti -1c
.RI "static double \fBupdateTime\fP"
.br
.ti -1c
.RI "static float \fBmixedDeltaTime\fP"
.br
.RI "Delta Time that includes Fixed\&. "
.ti -1c
.RI "static bool \fBisInFixed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBDoubleTime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.DoubleTime\&.SnapFixed ()\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.DoubleTime\&.SnapUpdate ()\fC [static]\fP"
TEST - Recreate Fixed() that may not have happened
.PP
Definition at line \fB59\fP of file \fBDoubleTime\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.deltaTime\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.fixedDeltaTime\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.fixedTime\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.DoubleTime\&.isInFixed\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.DoubleTime\&.mixedDeltaTime\fC [static]\fP"

.PP
Delta Time that includes Fixed\&. Useful for operations that apply in both fixed and update\&. 
.PP
Definition at line \fB28\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.DoubleTime\&.normTimeSinceFixed\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.prevFixedTime\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.prevUpdateTime\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.time\fC [static]\fP"

.PP
Definition at line \fB13\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.timeSinceFixed\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBDoubleTime\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.DoubleTime\&.updateTime\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBDoubleTime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
