.TH "Photon.Pun.Simple.ContactReactorBase< T >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactReactorBase< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IContactReactor\fP, ContactReactorBase, and \fBPhoton\&.Pun\&.Simple\&.IOnContactEvent\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwakeInitialize\fP (bool isNetObject)"
.br
.RI "Awake code that will run whether or not a \fBNetObject\fP Exists "
.ti -1c
.RI "virtual \fBConsumption\fP \fBOnContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBContactType\fP \fBtriggerOn\fP = \fBContactType\&.Enter\fP | \fBContactType\&.Stay\fP | \fBContactType\&.Exit\fP | \fBContactType\&.Hitscan\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "abstract \fBConsumption\fP \fBProcessContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBSyncState\fP \fBsyncState\fP"
.br
.ti -1c
.RI "int \fBsyncStateMountMask\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContactType\fP \fBTriggerOn\fP\fC [get]\fP"
.br
.ti -1c
.RI "abstract bool \fBIsPickup\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.TP
\fIT\fP : \fI\fBIContactSystem\fP\fP
.PP
Definition at line \fB86\fP of file \fBContactReactorBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.OnAwakeInitialize (bool isNetObject)\fC [virtual]\fP"

.PP
Awake code that will run whether or not a \fBNetObject\fP Exists 
.PP
\fBReturns\fP
.RS 4
Returns true if this is a \fBNetObject\fP
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Reimplemented in \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.PP
Definition at line \fB38\fP of file \fBContactReactorBase\&.cs\fP\&.
.SS "virtual \fBConsumption\fP \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.OnContactEvent (\fBContactEvent\fP contactEvent)\fC [virtual]\fP"
Pickup requires mount compatibility to be valid
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnContactEvent\fP\&.
.PP
Definition at line \fB49\fP of file \fBContactReactorBase\&.cs\fP\&.
.SS "abstract \fBConsumption\fP \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.ProcessContactEvent (\fBContactEvent\fP contactEvent)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors< T >\fP, and \fBPhoton\&.Pun\&.Simple\&.VitalsContactReactor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSyncState\fP \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.syncState\fC [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBContactReactorBase\&.cs\fP\&.
.SS "int \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.syncStateMountMask\fC [protected]\fP"

.PP
Definition at line \fB36\fP of file \fBContactReactorBase\&.cs\fP\&.
.SS "\fBContactType\fP \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.triggerOn = \fBContactType\&.Enter\fP | \fBContactType\&.Stay\fP | \fBContactType\&.Exit\fP | \fBContactType\&.Hitscan\fP"

.PP
Definition at line \fB24\fP of file \fBContactReactorBase\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "abstract bool \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.IsPickup\fC [get]\fP"

.PP
Definition at line \fB32\fP of file \fBContactReactorBase\&.cs\fP\&.
.SS "\fBContactType\fP \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase\fP< T >\&.TriggerOn\fC [get]\fP"

.PP
Definition at line \fB25\fP of file \fBContactReactorBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
