.TH "Photon.Realtime.Extensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.Extensions \- This static class defines some useful extension methods for several existing classes (e\&.g\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMerge\fP (this IDictionary target, IDictionary addHash)"
.br
.RI "Merges all keys from addHash into the target\&. "
.ti -1c
.RI "static void \fBMergeStringKeys\fP (this IDictionary target, IDictionary addHash)"
.br
.RI "Merges keys of type string to target Hashtable\&. "
.ti -1c
.RI "static string \fBToStringFull\fP (this IDictionary origin)"
.br
.RI "Helper method for debugging of IDictionary content, including type-information\&. "
.ti -1c
.RI "static string \fBToStringFull< T >\fP (this List< T > data)"
.br
.RI "Helper method for debugging of List<T> content\&. "
.ti -1c
.RI "static string \fBToStringFull\fP (this object[] data)"
.br
.RI "Helper method for debugging of object[] content\&. "
.ti -1c
.RI "static \fBHashtable\fP \fBStripToStringKeys\fP (this IDictionary original)"
.br
.RI "This method copies all string-typed keys of the original into a new Hashtable\&. "
.ti -1c
.RI "static \fBHashtable\fP \fBStripToStringKeys\fP (this \fBHashtable\fP original)"
.br
.RI "This method copies all string-typed keys of the original into a new Hashtable\&. "
.ti -1c
.RI "static void \fBStripKeysWithNullValues\fP (this IDictionary original)"
.br
.RI "Removes all keys with null values\&. "
.ti -1c
.RI "static void \fBStripKeysWithNullValues\fP (this \fBHashtable\fP original)"
.br
.RI "Removes all keys with null values\&. "
.ti -1c
.RI "static bool \fBContains\fP (this int[] target, int nr)"
.br
.RI "Checks if a particular integer value is in an int-array\&. "
.in -1c
.SH "Detailed Description"
.PP 
This static class defines some useful extension methods for several existing classes (e\&.g\&. 

Vector3, float and others)\&. 
.PP
Definition at line \fB35\fP of file \fBExtensions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Photon\&.Realtime\&.Extensions\&.Contains (this int[] target, int nr)\fC [static]\fP"

.PP
Checks if a particular integer value is in an int-array\&. This might be useful to look up if a particular actorNumber is in the list of players of a room\&.
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The array of ints to check\&.
.br
\fInr\fP The number to lookup in target\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if nr was found in target\&.
.RE
.PP

.PP
Definition at line \fB250\fP of file \fBExtensions\&.cs\fP\&.
.SS "static void Photon\&.Realtime\&.Extensions\&.Merge (this IDictionary target, IDictionary addHash)\fC [static]\fP"

.PP
Merges all keys from addHash into the target\&. Adds new keys and updates the values of existing keys in target\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The IDictionary to update\&.
.br
\fIaddHash\fP The IDictionary containing data to merge into target\&.
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBExtensions\&.cs\fP\&.
.SS "static void Photon\&.Realtime\&.Extensions\&.MergeStringKeys (this IDictionary target, IDictionary addHash)\fC [static]\fP"

.PP
Merges keys of type string to target Hashtable\&. Does not remove keys from target (so non-string keys CAN be in target if they were before)\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The target IDictionary passed in plus all string-typed keys from the addHash\&.
.br
\fIaddHash\fP A IDictionary that should be merged partly into target to update it\&.
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBExtensions\&.cs\fP\&.
.SS "static void Photon\&.Realtime\&.Extensions\&.StripKeysWithNullValues (this \fBHashtable\fP original)\fC [static]\fP"

.PP
Removes all keys with null values\&. \fBPhoton\fP properties are removed by setting their value to null\&. Changes the original IDictionary! Uses lock(keysWithNullValue), which should be no problem in expected use cases\&. 
.PP
\fBParameters\fP
.RS 4
\fIoriginal\fP The IDictionary to strip of keys with null value\&.
.RE
.PP

.PP
Definition at line \fB220\fP of file \fBExtensions\&.cs\fP\&.
.SS "static void Photon\&.Realtime\&.Extensions\&.StripKeysWithNullValues (this IDictionary original)\fC [static]\fP"

.PP
Removes all keys with null values\&. \fBPhoton\fP properties are removed by setting their value to null\&. Changes the original IDictionary! Uses lock(keysWithNullValue), which should be no problem in expected use cases\&. 
.PP
\fBParameters\fP
.RS 4
\fIoriginal\fP The IDictionary to strip of keys with null value\&.
.RE
.PP

.PP
Definition at line \fB192\fP of file \fBExtensions\&.cs\fP\&.
.SS "static \fBHashtable\fP Photon\&.Realtime\&.Extensions\&.StripToStringKeys (this \fBHashtable\fP original)\fC [static]\fP"

.PP
This method copies all string-typed keys of the original into a new Hashtable\&. Does not recurse (!) into hashes that might be values in the root-hash\&. This does not modify the original\&. 
.PP
\fBParameters\fP
.RS 4
\fIoriginal\fP The original IDictonary to get string-typed keys from\&.
.RE
.PP
\fBReturns\fP
.RS 4
New Hashtable containing only string-typed keys of the original\&.
.RE
.PP

.PP
Definition at line \fB161\fP of file \fBExtensions\&.cs\fP\&.
.SS "static \fBHashtable\fP Photon\&.Realtime\&.Extensions\&.StripToStringKeys (this IDictionary original)\fC [static]\fP"

.PP
This method copies all string-typed keys of the original into a new Hashtable\&. Does not recurse (!) into hashes that might be values in the root-hash\&. This does not modify the original\&. 
.PP
\fBParameters\fP
.RS 4
\fIoriginal\fP The original IDictonary to get string-typed keys from\&.
.RE
.PP
\fBReturns\fP
.RS 4
New Hashtable containing only string-typed keys of the original\&.
.RE
.PP

.PP
Definition at line \fB135\fP of file \fBExtensions\&.cs\fP\&.
.SS "static string Photon\&.Realtime\&.Extensions\&.ToStringFull (this IDictionary origin)\fC [static]\fP"

.PP
Helper method for debugging of IDictionary content, including type-information\&. Using this is not performant\&.
.PP
Should only be used for debugging as necessary\&.
.PP
\fBParameters\fP
.RS 4
\fIorigin\fP Some Dictionary or Hashtable\&.
.RE
.PP
\fBReturns\fP
.RS 4
String of the content of the IDictionary\&.
.RE
.PP

.PP
Definition at line \fB84\fP of file \fBExtensions\&.cs\fP\&.
.SS "static string Photon\&.Realtime\&.Extensions\&.ToStringFull (this object[] data)\fC [static]\fP"

.PP
Helper method for debugging of object[] content\&. Using this is not performant\&.
.PP
Should only be used for debugging as necessary\&.
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Any object[]\&.
.RE
.PP
\fBReturns\fP
.RS 4
A comma-separated string containing each value's ToString()\&.
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBExtensions\&.cs\fP\&.
.SS "static string \fBPhoton\&.Realtime\&.Extensions\&.ToStringFull\fP< T > (this List< T > data)\fC [static]\fP"

.PP
Helper method for debugging of List<T> content\&. Using this is not performant\&.
.PP
Should only be used for debugging as necessary\&.
.PP
\fBParameters\fP
.RS 4
\fIdata\fP Any List<T> where T implements \&.ToString()\&.
.RE
.PP
\fBReturns\fP
.RS 4
A comma-separated string containing each value's ToString()\&.
.RE
.PP

.PP
Definition at line \fB93\fP of file \fBExtensions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
