.TH "Photon.Pun.Simple.IOnVitalValueChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnVitalValueChange
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IOnVitalChange\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.VitalUIBase\fP, and \fBPhoton\&.Pun\&.Simple\&.Vitals\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnVitalValueChange\fP (\fBVital\fP vital)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBIOnVitalChange\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnVitalValueChange\&.OnVitalValueChange (\fBVital\fP vital)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.VitalUIBase\fP, and \fBPhoton\&.Pun\&.Simple\&.Vitals\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
