.TH "Photon.Pun.UtilityScripts.ConnectAndJoinRandom" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.ConnectAndJoinRandom \- \fBSimple\fP component to call ConnectUsingSettings and to get into a PUN room easily\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBConnectNow\fP ()"
.br
.ti -1c
.RI "override void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. "
.ti -1c
.RI "override void \fBOnJoinedLobby\fP ()"
.br
.RI "Called on entering a lobby on the Master Server\&. "
.ti -1c
.RI "override void \fBOnJoinRandomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRandom call failed on the server\&. "
.ti -1c
.RI "override void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBAutoConnect\fP = true"
.br
.RI "Connect automatically? If false you can set this to true later on or call ConnectUsingSettings in your own scripts\&."
.ti -1c
.RI "byte \fBVersion\fP = 1"
.br
.RI "Used as \fBPhotonNetwork\&.GameVersion\fP\&."
.ti -1c
.RI "byte \fBMaxPlayers\fP = 4"
.br
.RI "Max number of players allowed in room\&. Once full, a new room will be created by the next connection attemping to join\&."
.ti -1c
.RI "int \fBplayerTTL\fP = \-1"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSimple\fP component to call ConnectUsingSettings and to get into a PUN room easily\&. 

A custom inspector provides a button to connect in PlayMode, should AutoConnect be false\&.
.PP
Definition at line \fB27\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.ConnectNow ()"

.PP
Definition at line \fB49\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.OnConnectedToMaster ()\fC [virtual]\fP"

.PP
Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. The list of available rooms won't become available unless you join a lobby via \fBLoadBalancingClient\&.OpJoinLobby\fP\&. You can join rooms and create them even without being in a lobby\&. The default lobby is used in that case\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB64\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.OnDisconnected (\fBDisconnectCause\fP cause)\fC [virtual]\fP"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. It could be a failure or intentional 
.PP
The reason for this disconnect is provided as DisconnectCause\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB89\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.OnJoinedLobby ()\fC [virtual]\fP"

.PP
Called on entering a lobby on the Master Server\&. The actual room-list updates will call OnRoomListUpdate\&. 
.PP
While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud)\&. The room list gets available via OnRoomListUpdate\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB71\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Called when the LoadBalancingClient entered a room, no matter if this client created it or simply joined\&. When this is called, you can access the existing players in \fBRoom\&.Players\fP, their custom properties and \fBRoom\&.CustomProperties\fP\&.
.PP
In this callback, you could create player objects\&. For example in Unity, instantiate a prefab for the player\&.
.PP
If you want a match to be started 'actively', enable the user to signal 'ready' (using OpRaiseEvent or a Custom Property)\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB94\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.OnJoinRandomFailed (short returnCode, string message)\fC [virtual]\fP"

.PP
Called when a previous OpJoinRandom call failed on the server\&. The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room)\&.
.PP
When using multiple lobbies (via OpJoinLobby or a TypedLobby parameter), another lobby might have more/fitting rooms\&.
.br
 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB77\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.Start ()"

.PP
Definition at line \fB41\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.AutoConnect = true"

.PP
Connect automatically? If false you can set this to true later on or call ConnectUsingSettings in your own scripts\&.
.PP
Definition at line \fB30\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.MaxPlayers = 4"

.PP
Max number of players allowed in room\&. Once full, a new room will be created by the next connection attemping to join\&.
.PP
Definition at line \fB37\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.playerTTL = \-1"

.PP
Definition at line \fB39\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\&.Version = 1"

.PP
Used as \fBPhotonNetwork\&.GameVersion\fP\&.
.PP
Definition at line \fB33\fP of file \fBConnectAndJoinRandom\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
