.TH "Photon.Pun.Simple.TRSDefinitionBase" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.TRSDefinitionBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncAdditiveMover\&.TRSDefinition\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\&.TRSDefinition\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBSyncMoverBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.TRSDefinitionBase\&.bool = true"

.PP
Definition at line \fB18\fP of file \fBSyncMoverBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
