.TH "Photon.Pun.Demo.Cockpit.CurrentRoomIsVisibleToggle" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.CurrentRoomIsVisibleToggle \- PhotonNetwork\&.CurrentRoom\&.IsVisible UI Toggle  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBToggleValue\fP (bool value)"
.br
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
PhotonNetwork\&.CurrentRoom\&.IsVisible UI Toggle 
.PP
Definition at line \fB18\fP of file \fBCurrentRoomIsVisibleToggle\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.CurrentRoomIsVisibleToggle\&.OnPointerClick (PointerEventData eventData)"

.PP
Definition at line \fB60\fP of file \fBCurrentRoomIsVisibleToggle\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.CurrentRoomIsVisibleToggle\&.ToggleValue (bool value)"

.PP
Definition at line \fB49\fP of file \fBCurrentRoomIsVisibleToggle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
