.TH "Photon.Pun.Simple.SyncAnimator.Frame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncAnimator.Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP ()"
.br
.ti -1c
.RI "\fBFrame\fP (\fBSyncAnimator\fP \fBsyncAnimator\fP, int \fBframeId\fP)"
.br
.ti -1c
.RI "override void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSyncAnimator\fP \fBsyncAnimator\fP"
.br
.ti -1c
.RI "\fBSmartVar\fP[] \fBparameters\fP"
.br
.ti -1c
.RI "int?[] \fBstateHashes\fP"
.br
.ti -1c
.RI "bool[] \fBlayerIsInTransition\fP"
.br
.ti -1c
.RI "float[] \fBnormalizedTime\fP"
.br
.ti -1c
.RI "float?[] \fBlayerWeights\fP"
.br
.ti -1c
.RI "Queue< \fBAnimPassThru\fP > \fBpassThrus\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB131\fP of file \fBSyncAnimator\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.Frame ()"

.PP
Definition at line \fB145\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.Frame (\fBSyncAnimator\fP syncAnimator, int frameId)"

.PP
Definition at line \fB147\fP of file \fBSyncAnimator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB228\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"
Don't copy triggers - unless I decide otherwise\&. They are fire once and should not be repeated\&.
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB183\fP of file \fBSyncAnimator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool [] Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.layerIsInTransition"

.PP
Definition at line \fB136\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "float? [] Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.layerWeights"

.PP
Definition at line \fB138\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "float [] Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.normalizedTime"

.PP
Definition at line \fB137\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "\fBSmartVar\fP [] Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.parameters"

.PP
Definition at line \fB134\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "Queue<\fBAnimPassThru\fP> Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.passThrus"

.PP
Definition at line \fB139\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "int? [] Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.stateHashes"

.PP
Definition at line \fB135\fP of file \fBSyncAnimator\&.cs\fP\&.
.SS "\fBSyncAnimator\fP Photon\&.Pun\&.Simple\&.SyncAnimator\&.Frame\&.syncAnimator"

.PP
Definition at line \fB133\fP of file \fBSyncAnimator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
