.TH "Photon.Chat.Demo.ChannelSelector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.Demo.ChannelSelector
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChannel\fP (string channel)"
.br
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBChannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBChannelSelector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Chat\&.Demo\&.ChannelSelector\&.OnPointerClick (PointerEventData eventData)"

.PP
Definition at line \fB26\fP of file \fBChannelSelector\&.cs\fP\&.
.SS "void Photon\&.Chat\&.Demo\&.ChannelSelector\&.SetChannel (string channel)"

.PP
Definition at line \fB19\fP of file \fBChannelSelector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Chat\&.Demo\&.ChannelSelector\&.Channel"

.PP
Definition at line \fB17\fP of file \fBChannelSelector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
