.TH "Photon.Pun.PunSceneSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PunSceneSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBMinViewIdForScene\fP (string sceneName)"
.br
.ti -1c
.RI "static void \fBSanitizeSceneSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSceneSetting\fP > \fBMinViewIdPerScene\fP = new List<\fBSceneSetting\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBPunSceneSettingsCsPath\fP\fC [get]\fP"
.br
.ti -1c
.RI "static \fBPunSceneSettings\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.PunSceneSettings\&.MinViewIdForScene (string sceneName)\fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.PunSceneSettings\&.SanitizeSceneSettings ()\fC [static]\fP"

.PP
Definition at line \fB134\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSceneSetting\fP> Photon\&.Pun\&.PunSceneSettings\&.MinViewIdPerScene = new List<\fBSceneSetting\fP>()"

.PP
Definition at line \fB42\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBPunSceneSettings\fP Photon\&.Pun\&.PunSceneSettings\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB78\fP of file \fBPunSceneSettings\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunSceneSettings\&.PunSceneSettingsCsPath\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB50\fP of file \fBPunSceneSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
