.TH "Photon.Compression.Internal.SyncRangedAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.SyncRangedAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP, and \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyncRangedAttribute\fP (\fBLiteFloatCompressType\fP compression, Single min, Single max, bool accurateCenter)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Single value, Single preValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBSyncRangedAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.Internal\&.SyncRangedAttribute\&.SyncRangedAttribute (\fBLiteFloatCompressType\fP compression, Single min, Single max, bool accurateCenter)"

.PP
Definition at line \fB16\fP of file \fBSyncRangedAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.SyncRangedAttribute\&.Pack (ref Single value, Single preValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB20\fP of file \fBSyncRangedAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.SyncRangedAttribute\&.Unpack (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB31\fP of file \fBSyncRangedAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
