.TH "Photon.Pun.Simple.IContactReactor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IContactReactor
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase< IInventorySystem< T > >\fP, \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase< T >\fP, and \fBPhoton\&.Pun\&.Simple\&.IVitalsContactReactor\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIContactReactor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
