.TH "Photon.Pun.PhotonAnimatorView.SynchronizedLayer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonAnimatorView.SynchronizedLayer
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSynchronizeType\fP \fBSynchronizeType\fP"
.br
.ti -1c
.RI "int \fBLayerIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.PhotonAnimatorView\&.SynchronizedLayer\&.LayerIndex"

.PP
Definition at line \fB62\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "\fBSynchronizeType\fP Photon\&.Pun\&.PhotonAnimatorView\&.SynchronizedLayer\&.SynchronizeType"

.PP
Definition at line \fB61\fP of file \fBPhotonAnimatorView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
