.TH "Photon.Pun.UtilityScripts.OnPointerOverTooltip" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.OnPointerOverTooltip \- Set focus to a given photonView when pointed is over  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SH "Detailed Description"
.PP 
Set focus to a given photonView when pointed is over 
.PP
Definition at line \fB17\fP of file \fBOnPointerOverTooltip\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
