.TH "Photon.Pun.UtilityScripts.PhotonLagSimulationGui" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PhotonLagSimulationGui \- This MonoBehaviour is a basic GUI for the \fBPhoton\fP client's network-simulation feature\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Rect \fBWindowRect\fP = new Rect(0, 100, 120, 100)"
.br
.RI "Positioning rect for window\&."
.ti -1c
.RI "int \fBWindowId\fP = 101"
.br
.RI "Unity GUI Window ID (must be unique or will cause issues)\&."
.ti -1c
.RI "bool \fBVisible\fP = true"
.br
.RI "Shows or hides GUI (does not affect settings)\&."
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "PhotonPeer \fBPeer\fP\fC [getset]\fP"
.br
.RI "The peer currently in use (to set the network simulation)\&."
.in -1c
.SH "Detailed Description"
.PP 
This MonoBehaviour is a basic GUI for the \fBPhoton\fP client's network-simulation feature\&. 

It can modify lag (fixed delay), jitter (random lag) and packet loss\&. 
.PP
Definition at line \fB27\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.OnGUI ()"

.PP
Definition at line \fB46\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.Start ()"

.PP
Definition at line \fB41\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.Visible = true"

.PP
Shows or hides GUI (does not affect settings)\&.
.PP
Definition at line \fB36\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.WindowId = 101"

.PP
Unity GUI Window ID (must be unique or will cause issues)\&.
.PP
Definition at line \fB33\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SS "Rect Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.WindowRect = new Rect(0, 100, 120, 100)"

.PP
Positioning rect for window\&.
.PP
Definition at line \fB30\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "PhotonPeer Photon\&.Pun\&.UtilityScripts\&.PhotonLagSimulationGui\&.Peer\fC [get]\fP, \fC [set]\fP"

.PP
The peer currently in use (to set the network simulation)\&.
.PP
Definition at line \fB39\fP of file \fBPhotonLagSimulationGui\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
