.TH "Photon.Pun.MonoBehaviourPun" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.MonoBehaviourPun \- This class adds the property photonView, while logging a warning when your game still uses the networkView\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBBreakableFurniture\fP, \fBFoodBehaviourScript\fP, \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.PlayerAnimatorManager\fP, \fBPhoton\&.Pun\&.Demo\&.SlotRacer\&.PlayerControl\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.PhotonAnimatorView\fP, \fBPhoton\&.Pun\&.PhotonRigidbody2DView\fP, \fBPhoton\&.Pun\&.PhotonRigidbodyView\fP, \fBPhoton\&.Pun\&.PhotonTransformView\fP, \fBPhoton\&.Pun\&.PhotonTransformViewClassic\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.MoveByKeys\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.OnClickDestroy\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.OnClickRpc\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.SmoothSyncMovement\fP, \fBPushOverIndicator\fP, and \fBTimerScript\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPhotonView\fP \fBphotonView\fP\fC [get]\fP"
.br
.RI "A cached reference to a \fBPhotonView\fP on this GameObject\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class adds the property photonView, while logging a warning when your game still uses the networkView\&. 


.PP
Definition at line \fB44\fP of file \fBPunClasses\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBPhotonView\fP Photon\&.Pun\&.MonoBehaviourPun\&.photonView\fC [get]\fP"

.PP
A cached reference to a \fBPhotonView\fP on this GameObject\&. If you intend to work with a \fBPhotonView\fP in a script, it's usually easier to write this\&.photonView\&.
.PP
If you intend to remove the \fBPhotonView\fP component from the GameObject but keep this Photon\&.MonoBehaviour, avoid this reference or modify this code to use PhotonView\&.Get(obj) instead\&. 
.PP
Definition at line \fB56\fP of file \fBPunClasses\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
