.TH "Photon.Compression.CompressedQuat" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.CompressedQuat
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompressedQuat\fP (\fBQuatCrusher\fP \fBcrusher\fP, ulong \fBcvalue\fP)"
.br
.ti -1c
.RI "\fBCompressedQuat\fP (\fBQuatCrusher\fP \fBcrusher\fP, uint \fBcvalue\fP)"
.br
.ti -1c
.RI "\fBCompressedQuat\fP (\fBQuatCrusher\fP \fBcrusher\fP, ushort \fBcvalue\fP)"
.br
.ti -1c
.RI "\fBCompressedQuat\fP (\fBQuatCrusher\fP \fBcrusher\fP, byte \fBcvalue\fP)"
.br
.ti -1c
.RI "Quaternion \fBDecompress\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator ulong\fP (\fBCompressedQuat\fP cv)"
.br
.ti -1c
.RI "static \fBoperator uint\fP (\fBCompressedQuat\fP cv)"
.br
.ti -1c
.RI "static \fBoperator ushort\fP (\fBCompressedQuat\fP cv)"
.br
.ti -1c
.RI "static \fBoperator byte\fP (\fBCompressedQuat\fP cv)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBQuatCrusher\fP \fBcrusher\fP"
.br
.ti -1c
.RI "readonly ulong \fBcvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBCompressedQuat\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.CompressedQuat\&.CompressedQuat (\fBQuatCrusher\fP crusher, ulong cvalue)"

.PP
Definition at line \fB16\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "Photon\&.Compression\&.CompressedQuat\&.CompressedQuat (\fBQuatCrusher\fP crusher, uint cvalue)"

.PP
Definition at line \fB22\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "Photon\&.Compression\&.CompressedQuat\&.CompressedQuat (\fBQuatCrusher\fP crusher, ushort cvalue)"

.PP
Definition at line \fB28\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "Photon\&.Compression\&.CompressedQuat\&.CompressedQuat (\fBQuatCrusher\fP crusher, byte cvalue)"

.PP
Definition at line \fB34\fP of file \fBCompressedQuat\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Quaternion Photon\&.Compression\&.CompressedQuat\&.Decompress ()"

.PP
Definition at line \fB48\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "static Photon\&.Compression\&.CompressedQuat\&.operator byte (\fBCompressedQuat\fP cv)\fC [explicit]\fP, \fC [static]\fP"

.PP
Definition at line \fB43\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "static Photon\&.Compression\&.CompressedQuat\&.operator uint (\fBCompressedQuat\fP cv)\fC [explicit]\fP, \fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "static implicit Photon\&.Compression\&.CompressedQuat\&.operator ulong (\fBCompressedQuat\fP cv)\fC [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "static Photon\&.Compression\&.CompressedQuat\&.operator ushort (\fBCompressedQuat\fP cv)\fC [explicit]\fP, \fC [static]\fP"

.PP
Definition at line \fB42\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "override string Photon\&.Compression\&.CompressedQuat\&.ToString ()"

.PP
Definition at line \fB54\fP of file \fBCompressedQuat\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBQuatCrusher\fP Photon\&.Compression\&.CompressedQuat\&.crusher"

.PP
Definition at line \fB13\fP of file \fBCompressedQuat\&.cs\fP\&.
.SS "readonly ulong Photon\&.Compression\&.CompressedQuat\&.cvalue"

.PP
Definition at line \fB14\fP of file \fBCompressedQuat\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
