.TH "Photon.Pun.Simple.VitalsData" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.VitalsData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVitalsData\fP (\fBVitals\fP \fBvitals\fP)"
.br
.ti -1c
.RI "void \fBCopyFrom\fP (\fBVitalsData\fP source)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVitals\fP \fBvitals\fP"
.br
.ti -1c
.RI "\fBVitalData\fP[] \fBdatas\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBVitalData\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.VitalsData\&.VitalsData (\fBVitals\fP vitals)"

.PP
Definition at line \fB14\fP of file \fBVitalData\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.VitalsData\&.CopyFrom (\fBVitalsData\fP source)"

.PP
Definition at line \fB20\fP of file \fBVitalData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBVitalData\fP [] Photon\&.Pun\&.Simple\&.VitalsData\&.datas"

.PP
Definition at line \fB12\fP of file \fBVitalData\&.cs\fP\&.
.SS "\fBVitals\fP Photon\&.Pun\&.Simple\&.VitalsData\&.vitals"

.PP
Definition at line \fB11\fP of file \fBVitalData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
