.TH "Photon.Compression.Internal" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIPackBoolean\fP"
.br
.ti -1c
.RI "interface \fBIPackByte\fP"
.br
.ti -1c
.RI "interface \fBIPackChar\fP"
.br
.ti -1c
.RI "interface \fBIPackDouble\fP"
.br
.ti -1c
.RI "interface \fBIPackInt16\fP"
.br
.ti -1c
.RI "interface \fBIPackInt32\fP"
.br
.ti -1c
.RI "interface \fBIPackInt64\fP"
.br
.ti -1c
.RI "interface \fBIPackList\fP"
.br
.ti -1c
.RI "interface \fBIPackSByte\fP"
.br
.ti -1c
.RI "interface \fBIPackSingle\fP"
.br
.ti -1c
.RI "interface \fBIPackString\fP"
.br
.ti -1c
.RI "interface \fBIPackStringBuilder\fP"
.br
.ti -1c
.RI "interface \fBIPackUInt16\fP"
.br
.ti -1c
.RI "interface \fBIPackUInt32\fP"
.br
.ti -1c
.RI "interface \fBIPackUInt64\fP"
.br
.ti -1c
.RI "interface \fBIPackVector2\fP"
.br
.ti -1c
.RI "interface \fBIPackVector2Int\fP"
.br
.ti -1c
.RI "interface \fBIPackVector3\fP"
.br
.ti -1c
.RI "interface \fBIPackVector3Int\fP"
.br
.ti -1c
.RI "class \fBPack_TestPackObject\fP"
.br
.ti -1c
.RI "class \fBPackFrame\fP"
.br
.ti -1c
.RI "class \fBPackFrame_TestPackObject\fP"
.br
.ti -1c
.RI "class \fBPackObjectDatabase\fP"
.br
.RI "Runtime lookup for packing delegates all get associated with Types at runtime and are stored here\&. "
.ti -1c
.RI "class \fBPackSupportedTypesAttribute\fP"
.br
.ti -1c
.RI "class \fBSyncRangedAttribute\fP"
.br
.ti -1c
.RI "class \fBSyncVarBaseAttribute\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackDelegate< T >\fP (ref T value, T prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBUnpackDelegate< T >\fP (ref T value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackListDelegate< T >\fP (ref List< T > value, List< T > prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBUnpackListDelegate< T >\fP (ref List< T > value, BitArray mask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "delegate \fBSerializationFlags\fP \fBPackSingleDelegate\fP (ref Single value, Single preValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackDelegate< T > (ref T value, T prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackListDelegate< T > (ref List< T > value, List< T > prevvalue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.PackSingleDelegate (ref Single value, Single preValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.UnpackDelegate< T > (ref T value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.SS "delegate \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.UnpackListDelegate< T > (ref List< T > value, BitArray mask, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
