.TH "Photon.Pun.Simple.IContactGroupsAssign" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IContactGroupsAssign
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMask\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBApplyToChildren\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBNetworkHitInerfaces\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.IContactGroupsAssign\&.ApplyToChildren\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBNetworkHitInerfaces\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.IContactGroupsAssign\&.Mask\fC [get]\fP"

.PP
Definition at line \fB11\fP of file \fBNetworkHitInerfaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
