.TH "Photon.Pun.Demo.SlotRacer.Utils.SplineWalker" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.Utils.SplineWalker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPositionOnSpline\fP (float position)"
.br
.ti -1c
.RI "void \fBExecutePositioning\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBezierSpline\fP \fBspline\fP"
.br
.ti -1c
.RI "float \fBSpeed\fP = 0f"
.br
.ti -1c
.RI "bool \fBlookForward\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "float \fBcurrentDistance\fP =0f"
.br
.ti -1c
.RI "float \fBcurrentClampedDistance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBSplineWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.ExecutePositioning ()"

.PP
Definition at line \fB46\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.SetPositionOnSpline (float position)"

.PP
Definition at line \fB33\fP of file \fBSplineWalker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.currentClampedDistance"

.PP
Definition at line \fB31\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.currentDistance =0f"

.PP
Definition at line \fB29\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.lookForward"

.PP
Definition at line \fB23\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.reverse"

.PP
Definition at line \fB25\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.Speed = 0f"

.PP
Definition at line \fB21\fP of file \fBSplineWalker\&.cs\fP\&.
.SS "\fBBezierSpline\fP Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.SplineWalker\&.spline"

.PP
Definition at line \fB19\fP of file \fBSplineWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
