.TH "Photon.Pun.Simple.HitscanTypeExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.HitscanTypeExt \- Extension of the HitscanType Enum for testing the type of cast/overlap being used\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsCast\fP (this \fBHitscanType\fP hitscanType)"
.br
.ti -1c
.RI "static bool \fBIsOverlap\fP (this \fBHitscanType\fP hitscanType)"
.br
.ti -1c
.RI "static bool \fBUsesRadius\fP (this \fBHitscanType\fP hitscanType)"
.br
.ti -1c
.RI "static bool \fBIsBox\fP (this \fBHitscanType\fP hitscanType)"
.br
.ti -1c
.RI "static bool \fBIsCapsule\fP (this \fBHitscanType\fP hitscanType)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extension of the HitscanType Enum for testing the type of cast/overlap being used\&. 


.PP
Definition at line \fB22\fP of file \fBGenericHitscan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Photon\&.Pun\&.Simple\&.HitscanTypeExt\&.IsBox (this \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.Simple\&.HitscanTypeExt\&.IsCapsule (this \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB40\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.Simple\&.HitscanTypeExt\&.IsCast (this \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.Simple\&.HitscanTypeExt\&.IsOverlap (this \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBGenericHitscan\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.Simple\&.HitscanTypeExt\&.UsesRadius (this \fBHitscanType\fP hitscanType)\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBGenericHitscan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
