.TH "Photon.Compression.Internal.PackFrame_TestPackObject" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.PackFrame_TestPackObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.Internal\&.PackFrame\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInterpolate\fP (\fBPackFrame\fP start, \fBPackFrame\fP end, \fBPackFrame\fP trg, float time, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "static void \fBInterpolate\fP (\fBPackFrame\fP start, \fBPackFrame\fP end, System\&.Object trg, float time, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "static void \fBSnapshotCallback\fP (\fBPackFrame\fP snapframe, \fBPackFrame\fP targframe, System\&.Object trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)"
.br
.ti -1c
.RI "static void \fBCapture\fP (System\&.Object src, \fBPackFrame\fP trg)"
.br
.ti -1c
.RI "static void \fBApply\fP (\fBPackFrame\fP src, System\&.Object trg, ref \fBFastBitMask128\fP \fBmask\fP, ref int maskOffset)"
.br
.ti -1c
.RI "static void \fBCopy\fP (\fBPackFrame\fP src, \fBPackFrame\fP trg)"
.br
.ti -1c
.RI "static \fBPackFrame\fP \fBFactory\fP ()"
.br
.ti -1c
.RI "static \fBPackFrame\fP[] \fBFactory\fP (System\&.Object trg, int count)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "System\&.Single \fBrotation\fP"
.br
.ti -1c
.RI "System\&.Int32 \fBintoroboto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Apply (\fBPackFrame\fP src, System\&.Object trg, ref \fBFastBitMask128\fP mask, ref int maskOffset)\fC [static]\fP"

.PP
Definition at line \fB50\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Capture (System\&.Object src, \fBPackFrame\fP trg)\fC [static]\fP"

.PP
Definition at line \fB43\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Copy (\fBPackFrame\fP src, \fBPackFrame\fP trg)\fC [static]\fP"

.PP
Definition at line \fB57\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBPackFrame\fP Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Factory ()\fC [static]\fP"

.PP
Definition at line \fB65\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBPackFrame\fP[] Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Factory (System\&.Object trg, int count)\fC [static]\fP"

.PP
Definition at line \fB66\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Interpolate (\fBPackFrame\fP start, \fBPackFrame\fP end, \fBPackFrame\fP trg, float time, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.Interpolate (\fBPackFrame\fP start, \fBPackFrame\fP end, System\&.Object trg, float time, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.SnapshotCallback (\fBPackFrame\fP snapframe, \fBPackFrame\fP targframe, System\&.Object trg, ref \fBFastBitMask128\fP readyMask, ref int maskOffset)\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "System\&.Int32 Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.intoroboto"

.PP
Definition at line \fB13\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "System\&.Single Photon\&.Compression\&.Internal\&.PackFrame_TestPackObject\&.rotation"

.PP
Definition at line \fB12\fP of file \fBPack_TestPackObject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
