.TH "Photon.Compression.LiteFloatCrusher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.LiteFloatCrusher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.LiteCrusher< ulong, float >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBNormalization\fP { \fBNone\fP, \fBPositive\fP, \fBNegative\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLiteFloatCrusher\fP ()"
.br
.ti -1c
.RI "\fBLiteFloatCrusher\fP (\fBLiteFloatCompressType\fP \fBcompressType\fP, float \fBmin\fP, float \fBmax\fP, bool accurateCenter, \fBLiteOutOfBoundsHandling\fP \fBoutOfBoundsHandling\fP=\fBLiteOutOfBoundsHandling\&.Clamp\fP)"
.br
.ti -1c
.RI "\fBLiteFloatCrusher\fP (\fBLiteFloatCompressType\fP \fBcompressType\fP, \fBNormalization\fP \fBnormalization\fP=\fBNormalization\&.None\fP, \fBLiteOutOfBoundsHandling\fP \fBoutOfBoundsHandling\fP=\fBLiteOutOfBoundsHandling\&.Clamp\fP)"
.br
.ti -1c
.RI "override ulong \fBEncode\fP (float val)"
.br
.ti -1c
.RI "override float \fBDecode\fP (uint cval)"
.br
.ti -1c
.RI "override ulong \fBWriteValue\fP (float val, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "override void \fBWriteCValue\fP (uint cval, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "override float \fBReadValue\fP (byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "override ulong \fBReadCValue\fP (byte[] buffer, ref int bitposition)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRecalculate\fP (\fBLiteFloatCompressType\fP \fBcompressType\fP, float \fBmin\fP, float \fBmax\fP, bool accurateCenter, \fBLiteFloatCrusher\fP crusher)"
.br
.ti -1c
.RI "static void \fBRecalculate\fP (\fBLiteFloatCompressType\fP \fBcompressType\fP, float \fBmin\fP, float \fBmax\fP, bool accurateCenter, ref int \fBbits\fP, ref float encoder, ref float decoder, ref ulong maxCVal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNormalization\fP \fBnormalization\fP"
.br
.ti -1c
.RI "\fBLiteFloatCompressType\fP \fBcompressType\fP = \fBLiteFloatCompressType\&.Half16\fP"
.br
.ti -1c
.RI "\fBLiteOutOfBoundsHandling\fP \fBoutOfBoundsHandling\fP = \fBLiteOutOfBoundsHandling\&.Clamp\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBmin\fP"
.br
.ti -1c
.RI "float \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Compression\&.LiteFloatCrusher\&.Normalization\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIPositive \fP\fP
.TP
\fB\fINegative \fP\fP
.PP
Definition at line \fB21\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.LiteFloatCrusher\&.LiteFloatCrusher ()"

.PP
Definition at line \fB35\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "Photon\&.Compression\&.LiteFloatCrusher\&.LiteFloatCrusher (\fBLiteFloatCompressType\fP compressType, float min, float max, bool accurateCenter, \fBLiteOutOfBoundsHandling\fP outOfBoundsHandling = \fC\fBLiteOutOfBoundsHandling\&.Clamp\fP\fP)"
Don't allow min and max to equal\&.
.PP
Definition at line \fB46\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "Photon\&.Compression\&.LiteFloatCrusher\&.LiteFloatCrusher (\fBLiteFloatCompressType\fP compressType, \fBNormalization\fP normalization = \fC\fBNormalization\&.None\fP\fP, \fBLiteOutOfBoundsHandling\fP outOfBoundsHandling = \fC\fBLiteOutOfBoundsHandling\&.Clamp\fP\fP)"

.PP
Definition at line \fB77\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override float Photon\&.Compression\&.LiteFloatCrusher\&.Decode (uint cval)\fC [virtual]\fP"
For the min and max cvals, just return the min max\&. Less work, and no sensless float errors\&.
.PP
Implements \fBPhoton\&.Compression\&.LiteCrusher< ulong, float >\fP\&.
.PP
Definition at line \fB176\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "override ulong Photon\&.Compression\&.LiteFloatCrusher\&.Encode (float val)"
Before casting check that the encoded float isn't negative\&. If negative, clamp to zero\&.
.PP
If positive, cast to int, and clamp to our max compresssed value\&.
.PP
Definition at line \fB144\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "override ulong Photon\&.Compression\&.LiteFloatCrusher\&.ReadCValue (byte[] buffer, ref int bitposition)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Compression\&.LiteCrusher< ulong, float >\fP\&.
.PP
Definition at line \fB258\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "override float Photon\&.Compression\&.LiteFloatCrusher\&.ReadValue (byte[] buffer, ref int bitposition)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Compression\&.LiteCrusher< ulong, float >\fP\&.
.PP
Definition at line \fB236\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.LiteFloatCrusher\&.Recalculate (\fBLiteFloatCompressType\fP compressType, float min, float max, bool accurateCenter, \fBLiteFloatCrusher\fP crusher)\fC [static]\fP"

.PP
Definition at line \fB109\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.LiteFloatCrusher\&.Recalculate (\fBLiteFloatCompressType\fP compressType, float min, float max, bool accurateCenter, ref int bits, ref float encoder, ref float decoder, ref ulong maxCVal)\fC [static]\fP"

.PP
Definition at line \fB126\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "override void Photon\&.Compression\&.LiteFloatCrusher\&.WriteCValue (uint cval, byte[] buffer, ref int bitposition)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Compression\&.LiteCrusher< ulong, float >\fP\&.
.PP
Definition at line \fB219\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "override ulong Photon\&.Compression\&.LiteFloatCrusher\&.WriteValue (float val, byte[] buffer, ref int bitposition)"

.PP
Definition at line \fB195\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBLiteFloatCompressType\fP Photon\&.Compression\&.LiteFloatCrusher\&.compressType = \fBLiteFloatCompressType\&.Half16\fP"

.PP
Definition at line \fB27\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "float Photon\&.Compression\&.LiteFloatCrusher\&.max\fC [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "float Photon\&.Compression\&.LiteFloatCrusher\&.min\fC [protected]\fP"

.PP
Definition at line \fB24\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "\fBNormalization\fP Photon\&.Compression\&.LiteFloatCrusher\&.normalization"

.PP
Definition at line \fB23\fP of file \fBLiteFloatCrusher\&.cs\fP\&.
.SS "\fBLiteOutOfBoundsHandling\fP Photon\&.Compression\&.LiteFloatCrusher\&.outOfBoundsHandling = \fBLiteOutOfBoundsHandling\&.Clamp\fP"

.PP
Definition at line \fB28\fP of file \fBLiteFloatCrusher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
