.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Views/PhotonAnimatorView.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Code/Views/PhotonAnimatorView.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonAnimatorView\fP"
.br
.RI "This class helps you to synchronize Mecanim animations Simply add the component to your GameObject and make sure that the \fBPhotonAnimatorView\fP is added to the list of observed components "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonAnimatorView\&.SynchronizedParameter\fP"
.br
.ti -1c
.RI "class \fBPhoton\&.Pun\&.PhotonAnimatorView\&.SynchronizedLayer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
