.TH "Photon.Pun.Simple.ContactGroups.ContactGroupAssign" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.ContactGroupAssign
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, \fBPhoton\&.Pun\&.Simple\&.IContactGroupsAssign\fP, and \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.IContactGroupMask\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBContactGroupMaskSelector\fP \fBcontactGroups\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBapplyToChildren\fP = true"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBApplyToChildren\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBMask\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBContactGroupAssign\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\&.applyToChildren = true\fC [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBContactGroupAssign\&.cs\fP\&.
.SS "\fBContactGroupMaskSelector\fP Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\&.contactGroups"

.PP
Definition at line \fB26\fP of file \fBContactGroupAssign\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\&.ApplyToChildren\fC [get]\fP"

.PP
Definition at line \fB31\fP of file \fBContactGroupAssign\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\&.Mask\fC [get]\fP"

.PP
Definition at line \fB34\fP of file \fBContactGroupAssign\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
