.TH "Photon.Utilities.MinMaxRangeAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.MinMaxRangeAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMinMaxRangeAttribute\fP (float \fBmin\fP, float \fBmax\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly float \fBmax\fP"
.br
.ti -1c
.RI "readonly float \fBmin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB114\fP of file \fBInspectorUtils\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Utilities\&.MinMaxRangeAttribute\&.MinMaxRangeAttribute (float min, float max)"

.PP
Definition at line \fB119\fP of file \fBInspectorUtils\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly float Photon\&.Utilities\&.MinMaxRangeAttribute\&.max"

.PP
Definition at line \fB116\fP of file \fBInspectorUtils\&.cs\fP\&.
.SS "readonly float Photon\&.Utilities\&.MinMaxRangeAttribute\&.min"

.PP
Definition at line \fB117\fP of file \fBInspectorUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
