.TH "Photon.Pun.Simple.AutoDestroyUnspawned" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AutoDestroyUnspawned \- Destroys they exist in the scene during startup\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDestroyUnspawned\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBonlyIfPrefab\fP = true"
.br
.ti -1c
.RI "bool \fBhasPrefabParent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Destroys they exist in the scene during startup\&. 

This allows prefab copies to exist in the scene while editing, without having to delete them every time you build out\&. 
.PP
Definition at line \fB29\fP of file \fBAutoDestroyUnspawned\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.AutoDestroyUnspawned\&.DestroyUnspawned ()\fC [static]\fP"

.PP
Definition at line \fB68\fP of file \fBAutoDestroyUnspawned\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.AutoDestroyUnspawned\&.hasPrefabParent"

.PP
Definition at line \fB39\fP of file \fBAutoDestroyUnspawned\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.AutoDestroyUnspawned\&.onlyIfPrefab = true"

.PP
Definition at line \fB34\fP of file \fBAutoDestroyUnspawned\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
