.TH "Photon.Pun.Demo.SlotRacer.SlotLanes" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.SlotLanes \- Define Slot lanes and grid positions placeholders\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSplinePosition\fP[] \fBGridPositions\fP"
.br
.RI "The grid positions\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSlotLanes\fP \fBInstance\fP"
.br
.RI "Instance Pointer to access GridPositions "
.in -1c
.SH "Detailed Description"
.PP 
Define Slot lanes and grid positions placeholders\&. 

This is a convenient approach to visually define the lanes and their grid positions without any complicated editors and setup framework\&. 
.PP
Definition at line \fB21\fP of file \fBSlotLanes\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSplinePosition\fP [] Photon\&.Pun\&.Demo\&.SlotRacer\&.SlotLanes\&.GridPositions"

.PP
The grid positions\&. 
.PP
Definition at line \fB31\fP of file \fBSlotLanes\&.cs\fP\&.
.SS "\fBSlotLanes\fP Photon\&.Pun\&.Demo\&.SlotRacer\&.SlotLanes\&.Instance\fC [static]\fP"

.PP
Instance Pointer to access GridPositions 
.PP
Definition at line \fB26\fP of file \fBSlotLanes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
