.TH "Photon.Utilities.SettingsScriptableObjectBase" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.SettingsScriptableObjectBase \- Non-generic base class for \fBSettingsScriptableObject\fP to make non-generic elements more easily accessible\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBPhoton\&.Utilities\&.SettingsScriptableObject< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBInitialize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Non-generic base class for \fBSettingsScriptableObject\fP to make non-generic elements more easily accessible\&. 


.PP
Definition at line \fB20\fP of file \fBSettingsScriptableObject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void Photon\&.Utilities\&.SettingsScriptableObjectBase\&.Initialize ()\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Utilities\&.SettingsScriptableObject< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
