.TH "Photon.Compression.PackObjectAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.PackObjectAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPackObjectAttribute\fP (\fBDefaultKeyRate\fP \fBdefaultKeyRate\fP=\fBDefaultKeyRate\&.Every\fP)"
.br
.RI "BufferSize is the number of bytes that will be allocated for each frame\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDefaultKeyRate\fP \fBdefaultKeyRate\fP"
.br
.ti -1c
.RI "\fBDefaultPackInclusion\fP \fBdefaultInclusion\fP = \fBDefaultPackInclusion\&.Explicit\fP"
.br
.ti -1c
.RI "\fBSyncAs\fP \fBsyncAs\fP = \fBSyncAs\&.State\fP"
.br
.ti -1c
.RI "string \fBpostSnapCallback\fP"
.br
.ti -1c
.RI "string \fBpostApplyCallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.PackObjectAttribute\&.PackObjectAttribute (\fBDefaultKeyRate\fP defaultKeyRate = \fC\fBDefaultKeyRate\&.Every\fP\fP)"

.PP
BufferSize is the number of bytes that will be allocated for each frame\&. 
.PP
\fBParameters\fP
.RS 4
\fIbufferSize\fP 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDefaultPackInclusion\fP Photon\&.Compression\&.PackObjectAttribute\&.defaultInclusion = \fBDefaultPackInclusion\&.Explicit\fP"

.PP
Definition at line \fB33\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SS "\fBDefaultKeyRate\fP Photon\&.Compression\&.PackObjectAttribute\&.defaultKeyRate"

.PP
Definition at line \fB32\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SS "string Photon\&.Compression\&.PackObjectAttribute\&.postApplyCallback"

.PP
Definition at line \fB37\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SS "string Photon\&.Compression\&.PackObjectAttribute\&.postSnapCallback"

.PP
Definition at line \fB36\fP of file \fBPackObjectAttribute\&.cs\fP\&.
.SS "\fBSyncAs\fP Photon\&.Compression\&.PackObjectAttribute\&.syncAs = \fBSyncAs\&.State\fP"

.PP
Definition at line \fB34\fP of file \fBPackObjectAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
