.TH "Photon.Utilities.SmartVar" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.SmartVar
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSmartVar\fP \fBCopy\fP ()"
.br
.ti -1c
.RI "string \fBToStringVerbose\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (Int32 v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (UInt32 v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (Single v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (Boolean v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (Byte v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (Int16 v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (UInt16 v)"
.br
.ti -1c
.RI "static implicit \fBoperator SmartVar\fP (\fBChar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Int32\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator UInt32\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Single\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Boolean\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Byte\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Int16\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator UInt16\fP (\fBSmartVar\fP v)"
.br
.ti -1c
.RI "static implicit \fBoperator Char\fP (\fBSmartVar\fP v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSmartVarTypeCode\fP \fBTypeCode\fP"
.br
.ti -1c
.RI "Int32 \fBInt\fP"
.br
.ti -1c
.RI "UInt32 \fBUInt\fP"
.br
.ti -1c
.RI "Boolean \fBBool\fP"
.br
.ti -1c
.RI "Single \fBFloat\fP"
.br
.ti -1c
.RI "Byte \fBByte8\fP"
.br
.ti -1c
.RI "Int16 \fBShort\fP"
.br
.ti -1c
.RI "UInt16 \fBUShort\fP"
.br
.ti -1c
.RI "Char \fBChar\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBSmartVar\fP \fBNone\fP = new \fBSmartVar\fP() { \fBTypeCode\fP = SmartVarTypeCode\&.None }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBSmartVars\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSmartVar\fP Photon\&.Utilities\&.SmartVar\&.Copy ()"

.PP
Definition at line \fB177\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator Boolean (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB126\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator Byte (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB136\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBChar\fP (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB166\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator Int16 (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB146\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator Int32 (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB91\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator Single (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB112\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (Boolean v)\fC [static]\fP"

.PP
Definition at line \fB66\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (Byte v)\fC [static]\fP"

.PP
Definition at line \fB71\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (\fBChar\fP v)\fC [static]\fP"

.PP
Definition at line \fB86\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (Int16 v)\fC [static]\fP"

.PP
Definition at line \fB76\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (Int32 v)\fC [static]\fP"

.PP
Definition at line \fB51\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (Single v)\fC [static]\fP"

.PP
Definition at line \fB61\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (UInt16 v)\fC [static]\fP"

.PP
Definition at line \fB81\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator \fBSmartVar\fP (UInt32 v)\fC [static]\fP"

.PP
Definition at line \fB56\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator UInt16 (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB156\fP of file \fBSmartVars\&.cs\fP\&.
.SS "static implicit Photon\&.Utilities\&.SmartVar\&.operator UInt32 (\fBSmartVar\fP v)\fC [static]\fP"

.PP
Definition at line \fB102\fP of file \fBSmartVars\&.cs\fP\&.
.SS "override string Photon\&.Utilities\&.SmartVar\&.ToString ()"

.PP
Definition at line \fB206\fP of file \fBSmartVars\&.cs\fP\&.
.SS "string Photon\&.Utilities\&.SmartVar\&.ToStringVerbose ()"

.PP
Definition at line \fB182\fP of file \fBSmartVars\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Boolean Photon\&.Utilities\&.SmartVar\&.Bool"

.PP
Definition at line \fB32\fP of file \fBSmartVars\&.cs\fP\&.
.SS "Byte Photon\&.Utilities\&.SmartVar\&.Byte8"

.PP
Definition at line \fB38\fP of file \fBSmartVars\&.cs\fP\&.
.SS "Char Photon\&.Utilities\&.SmartVar\&.Char"

.PP
Definition at line \fB47\fP of file \fBSmartVars\&.cs\fP\&.
.SS "Single Photon\&.Utilities\&.SmartVar\&.Float"

.PP
Definition at line \fB35\fP of file \fBSmartVars\&.cs\fP\&.
.SS "Int32 Photon\&.Utilities\&.SmartVar\&.Int"

.PP
Definition at line \fB26\fP of file \fBSmartVars\&.cs\fP\&.
.SS "readonly \fBSmartVar\fP Photon\&.Utilities\&.SmartVar\&.None = new \fBSmartVar\fP() { \fBTypeCode\fP = SmartVarTypeCode\&.None }\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBSmartVars\&.cs\fP\&.
.SS "Int16 Photon\&.Utilities\&.SmartVar\&.Short"

.PP
Definition at line \fB41\fP of file \fBSmartVars\&.cs\fP\&.
.SS "\fBSmartVarTypeCode\fP Photon\&.Utilities\&.SmartVar\&.TypeCode"

.PP
Definition at line \fB23\fP of file \fBSmartVars\&.cs\fP\&.
.SS "UInt32 Photon\&.Utilities\&.SmartVar\&.UInt"

.PP
Definition at line \fB29\fP of file \fBSmartVars\&.cs\fP\&.
.SS "UInt16 Photon\&.Utilities\&.SmartVar\&.UShort"

.PP
Definition at line \fB44\fP of file \fBSmartVars\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
