.TH "Photon.Realtime.PhotonPing" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.PhotonPing \- Abstract implementation of \fBPhotonPing\fP, ase for pinging servers to find the 'Best Region'\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.PP
Inherited by \fBPhoton\&.Realtime\&.PingMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBStartPing\fP (string ip)"
.br
.ti -1c
.RI "virtual bool \fBDone\fP ()"
.br
.ti -1c
.RI "virtual void \fBDispose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBDebugString\fP = ''"
.br
.ti -1c
.RI "bool \fBSuccessful\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract implementation of \fBPhotonPing\fP, ase for pinging servers to find the 'Best Region'\&. 


.PP
Definition at line \fB43\fP of file \fBPhotonPing\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Photon\&.Realtime\&.PhotonPing\&.Dispose ()\fC [virtual]\fP"

.PP
Reimplemented in \fBPhoton\&.Realtime\&.PingMono\fP\&.
.PP
Definition at line \fB69\fP of file \fBPhotonPing\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.PhotonPing\&.Done ()\fC [virtual]\fP"

.PP
Reimplemented in \fBPhoton\&.Realtime\&.PingMono\fP\&.
.PP
Definition at line \fB64\fP of file \fBPhotonPing\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.PhotonPing\&.StartPing (string ip)\fC [virtual]\fP"

.PP
Reimplemented in \fBPhoton\&.Realtime\&.PingMono\fP\&.
.PP
Definition at line \fB59\fP of file \fBPhotonPing\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Realtime\&.PhotonPing\&.DebugString = ''"

.PP
Definition at line \fB45\fP of file \fBPhotonPing\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.PhotonPing\&.Successful"

.PP
Definition at line \fB47\fP of file \fBPhotonPing\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
