.TH "Photon.Pun.UtilityScripts.GraphicToggleIsOnTransition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.GraphicToggleIsOnTransition \- Use this on toggles texts to have some color transition on the text depending on the isOn State\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerEnterHandler, and IPointerExitHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerEnter\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerExit\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnValueChanged\fP (bool isOn)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Toggle \fBtoggle\fP"
.br
.ti -1c
.RI "Color \fBNormalOnColor\fP = Color\&.white"
.br
.ti -1c
.RI "Color \fBNormalOffColor\fP = Color\&.black"
.br
.ti -1c
.RI "Color \fBHoverOnColor\fP = Color\&.black"
.br
.ti -1c
.RI "Color \fBHoverOffColor\fP = Color\&.black"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use this on toggles texts to have some color transition on the text depending on the isOn State\&. 


.PP
Definition at line \fB20\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.OnDisable ()"

.PP
Definition at line \fB54\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.OnEnable ()"

.PP
Definition at line \fB45\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.OnPointerEnter (PointerEventData eventData)"

.PP
Definition at line \fB33\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.OnPointerExit (PointerEventData eventData)"

.PP
Definition at line \fB39\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.OnValueChanged (bool isOn)"

.PP
Definition at line \fB59\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.HoverOffColor = Color\&.black"

.PP
Definition at line \fB29\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "Color Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.HoverOnColor = Color\&.black"

.PP
Definition at line \fB28\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "Color Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.NormalOffColor = Color\&.black"

.PP
Definition at line \fB27\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "Color Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.NormalOnColor = Color\&.white"

.PP
Definition at line \fB26\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.
.SS "Toggle Photon\&.Pun\&.UtilityScripts\&.GraphicToggleIsOnTransition\&.toggle"

.PP
Definition at line \fB22\fP of file \fBGraphicToggleIsOnTransition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
