.TH "Photon.Compression.IncludeAxisExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.IncludeAxisExtensions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBSqrMagnitude\fP (this Vector3 v, \fBIncludedAxes\fP ia)"
.br
.RI "Only factors in used axes "
.ti -1c
.RI "static float \fBMagnitude\fP (this Vector3 v, \fBIncludedAxes\fP ia)"
.br
.RI "Only factors in used axes "
.ti -1c
.RI "static Vector3 \fBLerp\fP (this GameObject go, Vector3 start, Vector3 end, \fBIncludedAxes\fP ia, float t, bool localPosition=false)"
.br
.RI "Lerp extension that only applies the lerp to axis indicated by the XYZ\&. "
.ti -1c
.RI "static void \fBSetPosition\fP (this GameObject go, Vector3 pos, \fBIncludedAxes\fP ia, bool localPosition=false)"
.br
.RI "Set position applying ONLY the values indicated as included, non-included axis use the current axis of the gameobject\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBIncludedAxisEnum\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static Vector3 Photon\&.Compression\&.IncludeAxisExtensions\&.Lerp (this GameObject go, Vector3 start, Vector3 end, \fBIncludedAxes\fP ia, float t, bool localPosition = \fCfalse\fP)\fC [static]\fP"

.PP
Lerp extension that only applies the lerp to axis indicated by the XYZ\&. Other axis return the same axis value as start\&. 
.PP
Definition at line \fB53\fP of file \fBIncludedAxisEnum\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.IncludeAxisExtensions\&.Magnitude (this Vector3 v, \fBIncludedAxes\fP ia)\fC [static]\fP"

.PP
Only factors in used axes 
.PP
Definition at line \fB41\fP of file \fBIncludedAxisEnum\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.IncludeAxisExtensions\&.SetPosition (this GameObject go, Vector3 pos, \fBIncludedAxes\fP ia, bool localPosition = \fCfalse\fP)\fC [static]\fP"

.PP
Set position applying ONLY the values indicated as included, non-included axis use the current axis of the gameobject\&. 
.PP
Definition at line \fB68\fP of file \fBIncludedAxisEnum\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.IncludeAxisExtensions\&.SqrMagnitude (this Vector3 v, \fBIncludedAxes\fP ia)\fC [static]\fP"

.PP
Only factors in used axes 
.PP
Definition at line \fB30\fP of file \fBIncludedAxisEnum\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
