.TH "Photon.Pun.Demo.Cockpit.ServerProperty" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.ServerProperty \- \fBPhotonNetwork\&.Server\fP UI property  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PropertyListenerBase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBText\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBPhotonNetwork\&.Server\fP UI property 
.PP
Definition at line \fB16\fP of file \fBServerProperty\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.ServerProperty\&.Text"

.PP
Definition at line \fB19\fP of file \fBServerProperty\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
