.TH "Photon.Pun.Simple.SyncCannon" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncCannon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, and \fBPhoton\&.Pun\&.Simple\&.IProjectileCannon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBprojPrefab\fP"
.br
.ti -1c
.RI "Vector3 \fBvelocity\fP = new Vector3(0, 0, 10f)"
.br
.ti -1c
.RI "\fBRespondTo\fP \fBterminateOn\fP = \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"
.br
.ti -1c
.RI "\fBRespondTo\fP \fBdamageOn\fP = \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"
.br
.ti -1c
.RI "float \fBlagCompensate\fP = 1f"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBReset\fP ()"
.br
.ti -1c
.RI "override bool \fBTrigger\fP (\fBFrame\fP frame, int subFrameId, float timeshift=0)"
.br
.RI "Create the projectile instance "
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static List< \fBNetObject\fP > \fBreusableNetObjects\fP = new List<\fBNetObject\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBApplyOrder\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBSyncCannon\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncCannon\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; If no prefab was designated, we need a dummy
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB59\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncCannon\&.Reset ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB54\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "override bool Photon\&.Pun\&.Simple\&.SyncCannon\&.Trigger (\fBFrame\fP frame, int subFrameId, float timeshift = \fC0\fP)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Create the projectile instance 
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP\&.
.PP
Definition at line \fB150\fP of file \fBSyncCannon\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRespondTo\fP Photon\&.Pun\&.Simple\&.SyncCannon\&.damageOn = \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"

.PP
Definition at line \fB30\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.SyncCannon\&.lagCompensate = 1f"

.PP
Definition at line \fB35\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Simple\&.SyncCannon\&.projPrefab"

.PP
Definition at line \fB26\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "List<\fBNetObject\fP> Photon\&.Pun\&.Simple\&.SyncCannon\&.reusableNetObjects = new List<\fBNetObject\fP>()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line \fB75\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "\fBRespondTo\fP Photon\&.Pun\&.Simple\&.SyncCannon\&.terminateOn = \fBRespondTo\&.HitNetObj\fP | \fBRespondTo\&.HitNonNetObj\fP"

.PP
Definition at line \fB29\fP of file \fBSyncCannon\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.SyncCannon\&.velocity = new Vector3(0, 0, 10f)"

.PP
Definition at line \fB27\fP of file \fBSyncCannon\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override int Photon\&.Pun\&.Simple\&.SyncCannon\&.ApplyOrder\fC [get]\fP"

.PP
Definition at line \fB22\fP of file \fBSyncCannon\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
