.TH "Photon.Realtime.PhotonAppSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.PhotonAppSettings \- Collection of connection-relevant settings, used internally by PhotonNetwork\&.ConnectUsingSettings\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLoadOrCreateSettings\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAppSettings\fP \fBAppSettings\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPhotonAppSettings\fP \fBInstance\fP\fC [get]\fP"
.br
.RI "Serialized server settings, written by the Setup Wizard for use in ConnectUsingSettings\&."
.in -1c
.SH "Detailed Description"
.PP 
Collection of connection-relevant settings, used internally by PhotonNetwork\&.ConnectUsingSettings\&. 

Includes the \fBAppSettings\fP class from the \fBRealtime\fP APIs plus some other, PUN-relevant, settings\&.
.PP
Definition at line \fB27\fP of file \fBPhotonAppSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Realtime\&.PhotonAppSettings\&.LoadOrCreateSettings ()\fC [static]\fP"

.PP
Definition at line \fB59\fP of file \fBPhotonAppSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAppSettings\fP Photon\&.Realtime\&.PhotonAppSettings\&.AppSettings"

.PP
Definition at line \fB30\fP of file \fBPhotonAppSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBPhotonAppSettings\fP Photon\&.Realtime\&.PhotonAppSettings\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Serialized server settings, written by the Setup Wizard for use in ConnectUsingSettings\&.
.PP
Definition at line \fB42\fP of file \fBPhotonAppSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
