.TH "Photon.Compression.Internal.PackFrame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.PackFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Compression\&.Internal\&.PackFrame_TestPackObject\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFastBitMask128\fP \fBmask\fP"
.br
.ti -1c
.RI "\fBFastBitMask128\fP \fBisCompleteMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFastBitMask128\fP Photon\&.Compression\&.Internal\&.PackFrame\&.isCompleteMask"

.PP
Definition at line \fB16\fP of file \fBPackObjectDatabase\&.cs\fP\&.
.SS "\fBFastBitMask128\fP Photon\&.Compression\&.Internal\&.PackFrame\&.mask"

.PP
Definition at line \fB15\fP of file \fBPackObjectDatabase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
