.TH "Photon.Pun.Demo.Cockpit.RegionListView" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.RegionListView \- Region list UI View\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "void \fBOnRegionListUpdate\fP (List< \fBRegion\fP > regionList)"
.br
.ti -1c
.RI "void \fBResetList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRegionListCell\fP \fBCellPrototype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Region list UI View\&. 


.PP
Definition at line \fB19\fP of file \fBRegionListView\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListView\&.OnEnable ()"

.PP
Definition at line \fB27\fP of file \fBRegionListView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListView\&.OnRegionListUpdate (List< \fBRegion\fP > regionList)"

.PP
Definition at line \fB34\fP of file \fBRegionListView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListView\&.ResetList ()"

.PP
Definition at line \fB50\fP of file \fBRegionListView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRegionListCell\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListView\&.CellPrototype"

.PP
Definition at line \fB22\fP of file \fBRegionListView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
