.TH "Photon.Pun.Simple.IContactable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IContactable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP, and \fBPhoton\&.Pun\&.Simple\&.IInventoryable< T >\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBIContactSystem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
