.TH "Photon.Pun.Demo.Procedural.WorldGenerator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Procedural.WorldGenerator \- The World Generator creates a world based on four options the current MasterClient can set\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBCreateWorld\fP ()"
.br
.RI "Called whenever a client receives a Custom Room Properties update containing all necessary information for creating a world\&. "
.ti -1c
.RI "void \fBConfirmAndUpdateProperties\fP ()"
.br
.RI "Whenever the 'Confirm' button on the Control Panel is clicked by the MasterClient, the Room Properties will be updated with the settings he defined\&. "
.ti -1c
.RI "void \fBDecreaseBlockHeight\fP (int clusterId, int blockId)"
.br
.RI "Decreases the height of a certain \fBBlock\fP from a certain \fBCluster\fP\&. "
.ti -1c
.RI "void \fBIncreaseBlockHeight\fP (int clusterId, int blockId)"
.br
.RI "Increases the height of a certain \fBBlock\fP from a certain \fBCluster\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBSeedPropertiesKey\fP = 'Seed'"
.br
.ti -1c
.RI "readonly string \fBWorldSizePropertiesKey\fP = 'WorldSize'"
.br
.ti -1c
.RI "readonly string \fBClusterSizePropertiesKey\fP = 'ClusterSize'"
.br
.ti -1c
.RI "readonly string \fBWorldTypePropertiesKey\fP = 'WorldType'"
.br
.ti -1c
.RI "Material[] \fBWorldMaterials\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBWorldGenerator\fP \fBInstance\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBSeed\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBWorldSize\fP \fBWorldSize\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBClusterSize\fP \fBClusterSize\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBWorldType\fP \fBWorldType\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The World Generator creates a world based on four options the current MasterClient can set\&. 

These options are available on the Ingame Control Panel\&. If those options are confirmed by the current MasterClient, they will be stored in the Custom Room Properties to make them available on all clients\&. These options are: 1) a numerical Seed to make sure that each client generates the same world and to avoid Random functions and 'network-instantiate' everything 2) the World Size to describe how large the generated world should be 3) the \fBCluster\fP Size to describe how many Blocks are inside each \fBCluster\fP 4) the World Type to make the generated world appear in different 'looks'\&. 
.PP
Definition at line \fB53\fP of file \fBWorldGenerator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.Awake ()"

.PP
Definition at line \fB89\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.ConfirmAndUpdateProperties ()"

.PP
Whenever the 'Confirm' button on the Control Panel is clicked by the MasterClient, the Room Properties will be updated with the settings he defined\&. 
.PP
Definition at line \fB134\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.CreateWorld ()"

.PP
Called whenever a client receives a Custom Room Properties update containing all necessary information for creating a world\&. If there is currently a world generation process running, it will be stopped automatically\&. Also if there is a world already existing, it will be destroyed before the new one gets created\&. 
.PP
Definition at line \fB107\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.DecreaseBlockHeight (int clusterId, int blockId)"

.PP
Decreases the height of a certain \fBBlock\fP from a certain \fBCluster\fP\&. 
.PP
Definition at line \fB155\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.IncreaseBlockHeight (int clusterId, int blockId)"

.PP
Increases the height of a certain \fBBlock\fP from a certain \fBCluster\fP\&. 
.PP
Definition at line \fB168\fP of file \fBWorldGenerator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.ClusterSizePropertiesKey = 'ClusterSize'"

.PP
Definition at line \fB57\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "readonly string Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.SeedPropertiesKey = 'Seed'"

.PP
Definition at line \fB55\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "Material [] Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.WorldMaterials"

.PP
Definition at line \fB85\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "readonly string Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.WorldSizePropertiesKey = 'WorldSize'"

.PP
Definition at line \fB56\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "readonly string Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.WorldTypePropertiesKey = 'WorldType'"

.PP
Definition at line \fB58\fP of file \fBWorldGenerator\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBClusterSize\fP Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.ClusterSize\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB79\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "\fBWorldGenerator\fP Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB62\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.Seed\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB75\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "\fBWorldSize\fP Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.WorldSize\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB77\fP of file \fBWorldGenerator\&.cs\fP\&.
.SS "\fBWorldType\fP Photon\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\&.WorldType\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB81\fP of file \fBWorldGenerator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
