.TH "Photon.Utilities.CatmulRom" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.CatmulRom
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float \fBCatmullRomLerp\fP (float pre, float start, float end, float post, float t)"
.br
.ti -1c
.RI "static float \fBCatmullRomLerp\fP (float pre, float start, float end, float t)"
.br
.ti -1c
.RI "static Vector3 \fBCatmullRomLerp\fP (Vector2 pre, Vector2 start, Vector2 end, Vector2 post, float t)"
.br
.ti -1c
.RI "static Vector3 \fBCatmullRomLerp\fP (Vector2 pre, Vector2 start, Vector2 end, float t)"
.br
.ti -1c
.RI "static Vector3 \fBCatmullRomLerp\fP (Vector3 pre, Vector3 start, Vector3 end, Vector3 post, float t)"
.br
.ti -1c
.RI "static Vector3 \fBCatmullRomLerp\fP (Vector3 pre, Vector3 start, Vector3 end, float t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static float Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (float pre, float start, float end, float post, float t)\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SS "static float Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (float pre, float start, float end, float t)\fC [static]\fP"

.PP
Definition at line \fB42\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SS "static Vector3 Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (Vector2 pre, Vector2 start, Vector2 end, float t)\fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SS "static Vector3 Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (Vector2 pre, Vector2 start, Vector2 end, Vector2 post, float t)\fC [static]\fP"

.PP
Definition at line \fB78\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SS "static Vector3 Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (Vector3 pre, Vector3 start, Vector3 end, float t)\fC [static]\fP"

.PP
Definition at line \fB178\fP of file \fBCatmullRomLerp\&.cs\fP\&.
.SS "static Vector3 Photon\&.Utilities\&.CatmulRom\&.CatmullRomLerp (Vector3 pre, Vector3 start, Vector3 end, Vector3 post, float t)\fC [static]\fP"

.PP
Definition at line \fB146\fP of file \fBCatmullRomLerp\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
