.TH "Photon.Pun.Simple.ContactGroups.ContactGroupMaskSelector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.ContactGroupMaskSelector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.IContactGroupMask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContactGroupMaskSelector\fP (int mask)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static implicit \fBoperator int\fP (\fBContactGroupMaskSelector\fP selector)"
.br
.ti -1c
.RI "static implicit \fBoperator ContactGroupMaskSelector\fP (int mask)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMask\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBContactGroupMaskSelector\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupMaskSelector\&.ContactGroupMaskSelector (int mask)"

.PP
Definition at line \fB28\fP of file \fBContactGroupMaskSelector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static implicit Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupMaskSelector\&.operator \fBContactGroupMaskSelector\fP (int mask)\fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBContactGroupMaskSelector\&.cs\fP\&.
.SS "static implicit Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupMaskSelector\&.operator int (\fBContactGroupMaskSelector\fP selector)\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBContactGroupMaskSelector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupMaskSelector\&.Mask\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB22\fP of file \fBContactGroupMaskSelector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
