.TH "Photon.Pun.Simple.Pooling.Pool" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Pooling.Pool \- A VERY basic pooling system, because not using pooling is a bad for things like projectiles\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCacheComponents\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBAddPrefabToPool\fP (GameObject _prefab, int startingSize=8, int _growBy=8, Type _scriptToAdd=null, bool tidyUp=false)"
.br
.RI "Add a prefab to the \fBPool\fP list, and create a pool\&. "
.ti -1c
.RI "static \fBPool\fP \fBSpawn\fP (GameObject \fBorigPrefab\fP, Transform t, float duration=5f)"
.br
.ti -1c
.RI "static \fBPool\fP \fBSpawn\fP (GameObject \fBorigPrefab\fP, Vector3 pos, Quaternion rot, Vector3 scl, float duration=5f)"
.br
.ti -1c
.RI "static \fBPool\fP \fBSpawn\fP (GameObject \fBorigPrefab\fP, Vector3 pos, Quaternion rot, float duration=5f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBorigPrefab\fP"
.br
.ti -1c
.RI "Rigidbody \fBrb\fP"
.br
.ti -1c
.RI "Component \fBextraScript\fP"
.br
.ti -1c
.RI "float \fBdeathClock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A VERY basic pooling system, because not using pooling is a bad for things like projectiles\&. 

The statics are the pool manager\&. The non-static fields and methods are for pool members this is attached to\&. Objects are returned to the pool when they are SetActive(false)\&. 
.PP
Definition at line \fB17\fP of file \fBPool\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.AddPrefabToPool (GameObject _prefab, int startingSize = \fC8\fP, int _growBy = \fC8\fP, Type _scriptToAdd = \fCnull\fP, bool tidyUp = \fCfalse\fP)\fC [static]\fP"

.PP
Add a prefab to the \fBPool\fP list, and create a pool\&. Returns the list index\&. 
.PP
\fBParameters\fP
.RS 4
\fI_prefab\fP 
.br
\fI_growBy\fP 
.br
\fI_scriptToAdd\fP Indicate a typeof(Component) that you want added (if not already there) to the root of all instantiated pool items\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB60\fP of file \fBPool\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.CacheComponents ()"

.PP
Definition at line \fB188\fP of file \fBPool\&.cs\fP\&.
.SS "static \fBPool\fP Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.Spawn (GameObject origPrefab, Transform t, float duration = \fC5f\fP)\fC [static]\fP"

.PP
Definition at line \fB88\fP of file \fBPool\&.cs\fP\&.
.SS "static \fBPool\fP Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.Spawn (GameObject origPrefab, Vector3 pos, Quaternion rot, float duration = \fC5f\fP)\fC [static]\fP"
Check to see if the pool has been destroyed somehow, and reuild it if so\&.
.PP
Definition at line \fB100\fP of file \fBPool\&.cs\fP\&.
.SS "static \fBPool\fP Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.Spawn (GameObject origPrefab, Vector3 pos, Quaternion rot, Vector3 scl, float duration = \fC5f\fP)\fC [static]\fP"

.PP
Definition at line \fB93\fP of file \fBPool\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.deathClock"

.PP
Definition at line \fB186\fP of file \fBPool\&.cs\fP\&.
.SS "Component Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.extraScript"

.PP
Definition at line \fB184\fP of file \fBPool\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.origPrefab"

.PP
Definition at line \fB182\fP of file \fBPool\&.cs\fP\&.
.SS "Rigidbody Photon\&.Pun\&.Simple\&.Pooling\&.Pool\&.rb"

.PP
Definition at line \fB183\fP of file \fBPool\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
