.TH "Photon.Pun.UtilityScripts.PhotonTeamExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PhotonTeamExtensions \- Extension methods for the Player class that make use of \fBPhotonTeamsManager\fP\&. 

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPhotonTeam\fP \fBGetPhotonTeam\fP (this \fBPlayer\fP player)"
.br
.RI "Gets the team the player is currently joined to\&. "
.ti -1c
.RI "static bool \fBJoinTeam\fP (this \fBPlayer\fP player, \fBPhotonTeam\fP team)"
.br
.RI "Join a team\&. "
.ti -1c
.RI "static bool \fBJoinTeam\fP (this \fBPlayer\fP player, byte teamCode)"
.br
.RI "Join a team using team code\&. "
.ti -1c
.RI "static bool \fBJoinTeam\fP (this \fBPlayer\fP player, string teamName)"
.br
.RI "Join a team using team name\&. "
.ti -1c
.RI "static bool \fBSwitchTeam\fP (this \fBPlayer\fP player, \fBPhotonTeam\fP team)"
.br
.RI "Switch that player's team to the one you assign\&. "
.ti -1c
.RI "static bool \fBSwitchTeam\fP (this \fBPlayer\fP player, byte teamCode)"
.br
.RI "Switch the player's team using a team code\&. "
.ti -1c
.RI "static bool \fBSwitchTeam\fP (this \fBPlayer\fP player, string teamName)"
.br
.RI "Switch the player's team using a team name\&. "
.ti -1c
.RI "static bool \fBLeaveCurrentTeam\fP (this \fBPlayer\fP player)"
.br
.RI "Leave the current team if any\&. "
.ti -1c
.RI "static bool \fBTryGetTeamMates\fP (this \fBPlayer\fP player, out \fBPlayer\fP[] teamMates)"
.br
.RI "Try to get the team mates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extension methods for the Player class that make use of \fBPhotonTeamsManager\fP\&.
.PP
Definition at line \fB492\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPhotonTeam\fP Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.GetPhotonTeam (this \fBPlayer\fP player)\fC [static]\fP"

.PP
Gets the team the player is currently joined to\&. Null if none\&.
.PP
\fBReturns\fP
.RS 4
The team the player is currently joined to\&. Null if none\&.
.RE
.PP

.PP
Definition at line \fB496\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.JoinTeam (this \fBPlayer\fP player, byte teamCode)\fC [static]\fP"

.PP
Join a team using team code\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player who will join the team\&.
.br
\fIteamCode\fP The code fo the team to be joined\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB535\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.JoinTeam (this \fBPlayer\fP player, \fBPhotonTeam\fP team)\fC [static]\fP"

.PP
Join a team\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player who will join a team\&.
.br
\fIteam\fP The team to be joined\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB513\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.JoinTeam (this \fBPlayer\fP player, string teamName)\fC [static]\fP"

.PP
Join a team using team name\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player who will join the team\&.
.br
\fIteamName\fP The name of the team to be joined\&.
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB547\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.LeaveCurrentTeam (this \fBPlayer\fP player)\fC [static]\fP"

.PP
Leave the current team if any\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP 
.RE
.PP
\fBReturns\fP
.RS 4
If the leaving team request is queued to be sent to the server or done in case offline or not joined to a room yet\&.
.RE
.PP

.PP
Definition at line \fB606\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.SwitchTeam (this \fBPlayer\fP player, byte teamCode)\fC [static]\fP"

.PP
Switch the player's team using a team code\&. Internally checks if this player is in that team already or not\&.
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player that will switch teams\&.
.br
\fIteamCode\fP The code of the team to switch to\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the team switch request is queued to be sent to the server or done in case offline or not joined to a room yet\&.
.RE
.PP

.PP
Definition at line \fB584\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.SwitchTeam (this \fBPlayer\fP player, \fBPhotonTeam\fP team)\fC [static]\fP"

.PP
Switch that player's team to the one you assign\&. Internally checks if this player is in that team already or not\&. Only team switches are actually sent\&.
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP 
.br
\fIteam\fP 
.RE
.PP

.PP
Definition at line \fB557\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.SwitchTeam (this \fBPlayer\fP player, string teamName)\fC [static]\fP"

.PP
Switch the player's team using a team name\&. Internally checks if this player is in that team already or not\&.
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player that will switch teams\&.
.br
\fIteamName\fP The name of the team to switch to\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the team switch request is queued to be sent to the server or done in case offline or not joined to a room yet\&.
.RE
.PP

.PP
Definition at line \fB595\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamExtensions\&.TryGetTeamMates (this \fBPlayer\fP player, out \fBPlayer\fP[] teamMates)\fC [static]\fP"

.PP
Try to get the team mates\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player to get the team mates of\&.
.br
\fIteamMates\fP The team mates array to fill\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB623\fP of file \fBPhotonTeamsManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
