.TH "Photon.Pun.Demo.Cockpit.InfosPanelPlaceholder" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.InfosPanelPlaceholder \- Infos panel placeholder\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPunCockpit\fP \fBManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Infos panel placeholder\&. 

Defines the place where the infos panel should go\&. It will request InfoPanel when Component is enabled\&. 
.PP
Definition at line \fB14\fP of file \fBInfosPanelPlaceholder\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPunCockpit\fP Photon\&.Pun\&.Demo\&.Cockpit\&.InfosPanelPlaceholder\&.Manager"

.PP
Definition at line \fB16\fP of file \fBInfosPanelPlaceholder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
