.TH "Photon.Pun.Simple.EnableOnNetObjReady" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.EnableOnNetObjReady
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and \fBPhoton\&.Pun\&.Simple\&.IOnNetObjReady\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBOnNetObjReadyChange\fP (bool ready)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBvisibilityObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBEnableOnNetObjReady\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.EnableOnNetObjReady\&.Awake ()"

.PP
Definition at line \fB25\fP of file \fBEnableOnNetObjReady\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.EnableOnNetObjReady\&.OnNetObjReadyChange (bool ready)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnNetObjReady\fP\&.
.PP
Definition at line \fB38\fP of file \fBEnableOnNetObjReady\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.EnableOnNetObjReady\&.Reset ()"

.PP
Definition at line \fB20\fP of file \fBEnableOnNetObjReady\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Simple\&.EnableOnNetObjReady\&.visibilityObject"

.PP
Definition at line \fB18\fP of file \fBEnableOnNetObjReady\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
