.TH "Photon.Compression.ArraySegmentExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ArraySegmentExt
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ArraySegment< byte > \fBExtractArraySegment\fP (byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static ArraySegment< ushort > \fBExtractArraySegment\fP (ushort[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static ArraySegment< uint > \fBExtractArraySegment\fP (uint[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static ArraySegment< ulong > \fBExtractArraySegment\fP (ulong[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBAppend\fP (this ArraySegment< byte > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBAppend\fP (this ArraySegment< uint > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBAppend\fP (this ArraySegment< ulong > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBWrite\fP (this ArraySegment< byte > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBWrite\fP (this ArraySegment< uint > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBWrite\fP (this ArraySegment< ulong > buffer, ulong value, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static ulong \fBRead\fP (this ArraySegment< byte > buffer, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static ulong \fBRead\fP (this ArraySegment< uint > buffer, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static ulong \fBRead\fP (this ArraySegment< ulong > buffer, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBReadOutSafe\fP (this ArraySegment< byte > source, int srcStartPos, byte[] target, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBReadOutSafe\fP (this ArraySegment< byte > source, int srcStartPos, ulong[] target, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBReadOutSafe\fP (this ArraySegment< ulong > source, int srcStartPos, byte[] target, ref int bitposition, int bits)"
.br
.ti -1c
.RI "static void \fBReadOutSafe\fP (this ArraySegment< ulong > source, int srcStartPos, ulong[] target, ref int bitposition, int bits)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Append (this ArraySegment< byte > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB27\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Append (this ArraySegment< uint > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB34\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Append (this ArraySegment< ulong > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ArraySegment< byte > Photon\&.Compression\&.ArraySegmentExt\&.ExtractArraySegment (byte[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ArraySegment< uint > Photon\&.Compression\&.ArraySegmentExt\&.ExtractArraySegment (uint[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ArraySegment< ulong > Photon\&.Compression\&.ArraySegmentExt\&.ExtractArraySegment (ulong[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ArraySegment< ushort > Photon\&.Compression\&.ArraySegmentExt\&.ExtractArraySegment (ushort[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB12\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArraySegmentExt\&.Read (this ArraySegment< byte > buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB72\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArraySegmentExt\&.Read (this ArraySegment< uint > buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB80\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ArraySegmentExt\&.Read (this ArraySegment< ulong > buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB88\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.ReadOutSafe (this ArraySegment< byte > source, int srcStartPos, byte[] target, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB97\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.ReadOutSafe (this ArraySegment< byte > source, int srcStartPos, ulong[] target, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB103\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.ReadOutSafe (this ArraySegment< ulong > source, int srcStartPos, byte[] target, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB109\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.ReadOutSafe (this ArraySegment< ulong > source, int srcStartPos, ulong[] target, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB115\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Write (this ArraySegment< byte > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB49\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Write (this ArraySegment< uint > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB56\fP of file \fBArraySegmentExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySegmentExt\&.Write (this ArraySegment< ulong > buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
Definition at line \fB63\fP of file \fBArraySegmentExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
