.TH "Photon.Pun.UtilityScripts.CountdownTimer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.CountdownTimer \- This is a basic, network-synced \fBCountdownTimer\fP based on properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBCountdownTimerHasExpired\fP ()"
.br
.RI "OnCountdownTimerHasExpired delegate\&. "
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "override void \fBOnRoomPropertiesUpdate\fP (\fBHashtable\fP propertiesThatChanged)"
.br
.RI "Called when a room's custom properties changed\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBTryGetStartTime\fP (out int startTimestamp)"
.br
.ti -1c
.RI "static void \fBSetStartTime\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBCountdown\fP = 5\&.0f"
.br
.ti -1c
.RI "Text \fBText\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBCountdownStartTime\fP = 'StartTime'"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static \fBCountdownTimerHasExpired\fP \fBOnCountdownTimerHasExpired\fP"
.br
.RI "Called when the timer has expired\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is a basic, network-synced \fBCountdownTimer\fP based on properties\&. 

In order to start the timer, the MasterClient can call \fBSetStartTime()\fP to set the timestamp for the start\&. The property 'StartTime' then contains the server timestamp when the timer has been started\&.
.PP
In order to subscribe to the CountdownTimerHasExpired event you can call \fBCountdownTimer\&.OnCountdownTimerHasExpired\fP += OnCountdownTimerIsExpired; from Unity's OnEnable function for example\&. For unsubscribing simply call \fBCountdownTimer\&.OnCountdownTimerHasExpired\fP -= OnCountdownTimerIsExpired;\&.
.PP
You can do this from Unity's OnEnable and OnDisable functions\&. 
.PP
Definition at line \fB35\fP of file \fBCountdownTimer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "delegate void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.CountdownTimerHasExpired ()"

.PP
OnCountdownTimerHasExpired delegate\&. 
.SS "override void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.OnDisable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB75\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB66\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.OnRoomPropertiesUpdate (\fBHashtable\fP propertiesThatChanged)\fC [virtual]\fP"

.PP
Called when a room's custom properties changed\&. The propertiesThatChanged contains all that was set via \fBRoom\&.SetCustomProperties\fP\&. 
.PP
Since v1\&.25 this method has one parameter: Hashtable propertiesThatChanged\&.
.br
 Changing properties must be done by \fBRoom\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertiesThatChanged\fP 
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB113\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.SetStartTime ()\fC [static]\fP"

.PP
Definition at line \fB161\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.Start ()"

.PP
Definition at line \fB61\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "static bool Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.TryGetStartTime (out int startTimestamp)\fC [static]\fP"

.PP
Definition at line \fB146\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.Update ()"

.PP
Definition at line \fB82\fP of file \fBCountdownTimer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.Countdown = 5\&.0f"

.PP
Definition at line \fB45\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.CountdownStartTime = 'StartTime'\fC [static]\fP"

.PP
Definition at line \fB42\fP of file \fBCountdownTimer\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.Text"

.PP
Definition at line \fB52\fP of file \fBCountdownTimer\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "\fBCountdownTimerHasExpired\fP Photon\&.Pun\&.UtilityScripts\&.CountdownTimer\&.OnCountdownTimerHasExpired\fC [static]\fP"

.PP
Called when the timer has expired\&. 
.PP
Definition at line \fB58\fP of file \fBCountdownTimer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
