.TH "Photon.Pun.Simple.IOnPreNetDestroy" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPreNetDestroy \- Callback Interface for \fBOnPreNetDestroy()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.Mount\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreNetDestroy\fP (\fBNetObject\fP roothNetObj)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPreNetDestroy()\fP\&. 

Triggered when \fBNetObject\fP Destroy() is called\&. 
.PP
Definition at line \fB46\fP of file \fBNetObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPreNetDestroy\&.OnPreNetDestroy (\fBNetObject\fP roothNetObj)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.Mount\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
