.TH "Photon.Compression.SyncRangedIntAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.SyncRangedIntAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP, \fBPhoton\&.Compression\&.Internal\&.IPackByte\fP, \fBPhoton\&.Compression\&.Internal\&.IPackSByte\fP, \fBPhoton\&.Compression\&.Internal\&.IPackUInt16\fP, \fBPhoton\&.Compression\&.Internal\&.IPackInt16\fP, \fBPhoton\&.Compression\&.Internal\&.IPackUInt32\fP, \fBPhoton\&.Compression\&.Internal\&.IPackInt32\fP, \fBPhoton\&.Compression\&.Internal\&.IPackUInt64\fP, \fBPhoton\&.Compression\&.Internal\&.IPackInt64\fP, \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP, and \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyncRangedIntAttribute\fP (int min, int max, \fBIndicatorBits\fP indicatorBits=\fBIndicatorBits\&.None\fP, \fBKeyRate\fP \fBkeyRate\fP=\fBKeyRate\&.UseDefault\fP)"
.br
.RI "Network this field as an Integer type that will remain between the range values\&. "
.ti -1c
.RI "override int \fBGetMaxBits\fP (Type fieldType)"
.br
.RI "Maximum possible bits that can be used during bitpacking\&. "
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Byte value, Byte prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Byte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref SByte value, SByte prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref SByte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref UInt16 value, UInt16 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref UInt16 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Int16 value, Int16 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Int16 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref UInt32 value, UInt32 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref UInt32 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Int32 value, Int32 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Int32 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref UInt64 value, UInt64 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref UInt64 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Int64 value, Int64 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Int64 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Single value, Single prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBPack\fP (ref Double value, Double prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBUnpack\fP (ref Double value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.SyncRangedIntAttribute\&.SyncRangedIntAttribute (int min, int max, \fBIndicatorBits\fP indicatorBits = \fC\fBIndicatorBits\&.None\fP\fP, \fBKeyRate\fP keyRate = \fC\fBKeyRate\&.UseDefault\fP\fP)"

.PP
Network this field as an Integer type that will remain between the range values\&. Any values outside of these will be clamped\&. By knowing this range, values can automatically be bitpacked to the smallest possible value\&. 
.PP
\fBParameters\fP
.RS 4
\fImin\fP 
.br
\fImax\fP 
.RE
.PP

.PP
Definition at line \fB31\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override int Photon\&.Compression\&.SyncRangedIntAttribute\&.GetMaxBits (Type fieldType)\fC [virtual]\fP"

.PP
Maximum possible bits that can be used during bitpacking\&. These are used to determine the byte[] size for any PackObjects\&. Override this if the PackableAttribute will always use less than these values\&. Doing so will result in some memory savings\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldType\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Compression\&.Internal\&.SyncVarBaseAttribute\fP\&.
.PP
Definition at line \fB52\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Byte value, Byte prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackByte\fP\&.
.PP
Definition at line \fB148\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Double value, Double prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.PP
Definition at line \fB276\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Int16 value, Int16 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt16\fP\&.
.PP
Definition at line \fB189\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Int32 value, Int32 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt32\fP\&.
.PP
Definition at line \fB217\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Int64 value, Int64 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt64\fP\&.
.PP
Definition at line \fB245\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref SByte value, SByte prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSByte\fP\&.
.PP
Definition at line \fB161\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref Single value, Single prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB260\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref UInt16 value, UInt16 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt16\fP\&.
.PP
Definition at line \fB176\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref UInt32 value, UInt32 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt32\fP\&.
.PP
Definition at line \fB204\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Pack (ref UInt64 value, UInt64 prevValue, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt64\fP\&.
.PP
Definition at line \fB232\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Byte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackByte\fP\&.
.PP
Definition at line \fB155\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Double value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackDouble\fP\&.
.PP
Definition at line \fB286\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Int16 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt16\fP\&.
.PP
Definition at line \fB196\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Int32 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt32\fP\&.
.PP
Definition at line \fB224\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Int64 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackInt64\fP\&.
.PP
Definition at line \fB252\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref SByte value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSByte\fP\&.
.PP
Definition at line \fB168\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref Single value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackSingle\fP\&.
.PP
Definition at line \fB270\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref UInt16 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt16\fP\&.
.PP
Definition at line \fB183\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref UInt32 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt32\fP\&.
.PP
Definition at line \fB211\fP of file \fBSyncIntAttribute\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Compression\&.SyncRangedIntAttribute\&.Unpack (ref UInt64 value, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"

.PP
Implements \fBPhoton\&.Compression\&.Internal\&.IPackUInt64\fP\&.
.PP
Definition at line \fB239\fP of file \fBSyncIntAttribute\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
