.TH "Photon.Pun.Simple.MountSwitcher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.MountSwitcher
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "void \fBOnPreUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "KeyCode \fBkeycode\fP = KeyCode\&.M"
.br
.ti -1c
.RI "\fBMountSelector\fP \fBmount\fP = new \fBMountSelector\fP(1)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBtriggered\fP"
.br
.ti -1c
.RI "\fBSyncState\fP \fBsyncState\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBMountSwitcher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.MountSwitcher\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB21\fP of file \fBMountSwitcher\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountSwitcher\&.OnPreSimulate (int frameId, int subFrameId)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Definition at line \fB41\fP of file \fBMountSwitcher\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountSwitcher\&.OnPreUpdate ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.PP
Definition at line \fB35\fP of file \fBMountSwitcher\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "KeyCode Photon\&.Pun\&.Simple\&.MountSwitcher\&.keycode = KeyCode\&.M"

.PP
Definition at line \fB14\fP of file \fBMountSwitcher\&.cs\fP\&.
.SS "\fBMountSelector\fP Photon\&.Pun\&.Simple\&.MountSwitcher\&.mount = new \fBMountSelector\fP(1)"

.PP
Definition at line \fB15\fP of file \fBMountSwitcher\&.cs\fP\&.
.SS "\fBSyncState\fP Photon\&.Pun\&.Simple\&.MountSwitcher\&.syncState\fC [protected]\fP"

.PP
Definition at line \fB19\fP of file \fBMountSwitcher\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.MountSwitcher\&.triggered\fC [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBMountSwitcher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
