.TH "Photon.Pun.Simple.ISyncContact" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ISyncContact
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSyncContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBISyncContact\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.ISyncContact\&.SyncContactEvent (\fBContactEvent\fP contactEvent)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
