.TH "Photon.Pun.Demo.Asteroids" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAsteroid\fP"
.br
.ti -1c
.RI "class \fBAsteroidsGame\fP"
.br
.ti -1c
.RI "class \fBAsteroidsGameManager\fP"
.br
.ti -1c
.RI "class \fBBullet\fP"
.br
.ti -1c
.RI "class \fBLobbyMainPanel\fP"
.br
.ti -1c
.RI "class \fBLobbyTopPanel\fP"
.br
.ti -1c
.RI "class \fBPlayerListEntry\fP"
.br
.ti -1c
.RI "class \fBPlayerOverviewPanel\fP"
.br
.ti -1c
.RI "class \fBRoomListEntry\fP"
.br
.ti -1c
.RI "class \fBSpaceship\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
