.TH "Photon.Pun.Demo.Cockpit.PlayerListCell" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.PlayerListCell \- Player list cell representing a given PhotonPlayer  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"
.br
.ti -1c
.RI "void \fBAddToList\fP (\fBPlayer\fP info, bool animate=false)"
.br
.ti -1c
.RI "void \fBRemoveFromList\fP ()"
.br
.ti -1c
.RI "void \fBOnClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPlayerListView\fP \fBListManager\fP"
.br
.ti -1c
.RI "Text \fBNumberText\fP"
.br
.ti -1c
.RI "Text \fBNameText\fP"
.br
.ti -1c
.RI "Image \fBActiveFlag\fP"
.br
.ti -1c
.RI "Color \fBInactiveColor\fP"
.br
.ti -1c
.RI "Color \fBActiveColor\fP"
.br
.ti -1c
.RI "Text \fBisLocalText\fP"
.br
.ti -1c
.RI "Image \fBisMasterFlag\fP"
.br
.ti -1c
.RI "LayoutElement \fBLayoutElement\fP"
.br
.ti -1c
.RI "bool \fBisInactiveCache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Player list cell representing a given PhotonPlayer 
.PP
Definition at line \fB24\fP of file \fBPlayerListCell\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.AddToList (\fBPlayer\fP info, bool animate = \fCfalse\fP)"

.PP
Definition at line \fB51\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.OnClick ()"

.PP
Definition at line \fB76\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.RefreshInfo (\fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"

.PP
Definition at line \fB46\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.RemoveFromList ()"

.PP
Definition at line \fB70\fP of file \fBPlayerListCell\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.ActiveColor"

.PP
Definition at line \fB33\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Image Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.ActiveFlag"

.PP
Definition at line \fB31\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Color Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.InactiveColor"

.PP
Definition at line \fB32\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.isInactiveCache"

.PP
Definition at line \fB42\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.isLocalText"

.PP
Definition at line \fB35\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Image Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.isMasterFlag"

.PP
Definition at line \fB36\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "LayoutElement Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.LayoutElement"

.PP
Definition at line \fB38\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "\fBPlayerListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.ListManager"

.PP
Definition at line \fB27\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.NameText"

.PP
Definition at line \fB30\fP of file \fBPlayerListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.PlayerListCell\&.NumberText"

.PP
Definition at line \fB29\fP of file \fBPlayerListCell\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
