.TH "Photon.Realtime.FindFriendsOptions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.FindFriendsOptions \- Options for OpFindFriends can be combined to filter which rooms of friends are returned\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBCreatedOnGs\fP = false"
.br
.RI "Include a friend's room only if it is created and confirmed by the game server\&."
.ti -1c
.RI "bool \fBVisible\fP = false"
.br
.RI "Include a friend's room only if it is visible (using \fBRoom\&.IsVisible\fP)\&."
.ti -1c
.RI "bool \fBOpen\fP = false"
.br
.RI "Include a friend's room only if it is open (using \fBRoom\&.IsOpen\fP)\&."
.in -1c
.SH "Detailed Description"
.PP 
Options for OpFindFriends can be combined to filter which rooms of friends are returned\&. 


.PP
Definition at line \fB1019\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Realtime\&.FindFriendsOptions\&.CreatedOnGs = false"

.PP
Include a friend's room only if it is created and confirmed by the game server\&.
.PP
Definition at line \fB1022\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.FindFriendsOptions\&.Open = false"

.PP
Include a friend's room only if it is open (using \fBRoom\&.IsOpen\fP)\&.
.PP
Definition at line \fB1026\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.FindFriendsOptions\&.Visible = false"

.PP
Include a friend's room only if it is visible (using \fBRoom\&.IsVisible\fP)\&.
.PP
Definition at line \fB1024\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
