.TH "Photon.Pun.Simple.IProjectile" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IProjectile
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBIProjectileCannon\fP owner, int frameId, int subFrameId, Vector3 velocity, \fBRespondTo\fP terminateOn, \fBRespondTo\fP damageOn, float timeshift)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIProjectileCannon\fP \fBOwner\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBIProjectile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IProjectile\&.Initialize (\fBIProjectileCannon\fP owner, int frameId, int subFrameId, Vector3 velocity, \fBRespondTo\fP terminateOn, \fBRespondTo\fP damageOn, float timeshift)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIProjectileCannon\fP Photon\&.Pun\&.Simple\&.IProjectile\&.Owner\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB15\fP of file \fBIProjectile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
