.TH "Photon.Pun.Simple.SyncNodeMover.Node" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncNodeMover.Node
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3[] \fBtrs\fP = new Vector3[3] { new Vector3(0, 0, 0), new Vector3(0, 0, 0), new Vector3(1, 1, 1) }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Vector3 \fBPos\fP\fC [getset]\fP"
.br
.ti -1c
.RI "Vector3 \fBRot\fP\fC [getset]\fP"
.br
.ti -1c
.RI "Vector3 \fBScl\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB36\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 [] Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Node\&.trs = new Vector3[3] { new Vector3(0, 0, 0), new Vector3(0, 0, 0), new Vector3(1, 1, 1) }"

.PP
Definition at line \fB38\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Node\&.Pos\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB39\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Node\&.Rot\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB40\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Node\&.Scl\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB41\fP of file \fBSyncNodeMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
