.TH "Photon.Pun.Simple.SyncContact.Frame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncContact.Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP ()"
.br
.ti -1c
.RI "\fBFrame\fP (int \fBframeId\fP)"
.br
.ti -1c
.RI "override void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFrame\fP \fBConstruct\fP (int \fBframeId\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBContactRecord\fP > \fBcontactRecords\fP = new List<\fBContactRecord\fP>(1)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB85\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.Frame ()"

.PP
Definition at line \fB89\fP of file \fBSyncContact\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.Frame (int frameId)"

.PP
Definition at line \fB91\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB109\fP of file \fBSyncContact\&.cs\fP\&.
.SS "static \fBFrame\fP Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.Construct (int frameId)\fC [static]\fP"

.PP
Definition at line \fB104\fP of file \fBSyncContact\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB97\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBContactRecord\fP> Photon\&.Pun\&.Simple\&.SyncContact\&.Frame\&.contactRecords = new List<\fBContactRecord\fP>(1)"

.PP
Definition at line \fB87\fP of file \fBSyncContact\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
