.TH "Photon.Pun.Demo.Cockpit.StringInputField" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.StringInputField \- String UI InputField\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnSubmitEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetValue\fP (string value)"
.br
.ti -1c
.RI "void \fBEndEditOnEnter\fP (string value)"
.br
.ti -1c
.RI "void \fBSubmitForm\fP (string value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBPropertyValueInput\fP"
.br
.ti -1c
.RI "\fBOnSubmitEvent\fP \fBOnSubmit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
String UI InputField\&. 


.PP
Definition at line \fB17\fP of file \fBStringInputField\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.StringInputField\&.EndEditOnEnter (string value)"

.PP
Definition at line \fB48\fP of file \fBStringInputField\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.StringInputField\&.SetValue (string value)"

.PP
Definition at line \fB43\fP of file \fBStringInputField\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.StringInputField\&.SubmitForm (string value)"

.PP
Definition at line \fB60\fP of file \fBStringInputField\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBOnSubmitEvent\fP Photon\&.Pun\&.Demo\&.Cockpit\&.StringInputField\&.OnSubmit"

.PP
Definition at line \fB24\fP of file \fBStringInputField\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.StringInputField\&.PropertyValueInput"

.PP
Definition at line \fB19\fP of file \fBStringInputField\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
