.TH "Photon.Compression.IHasTransformCrusher" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.IHasTransformCrusher \- VERY basic interface, just to make it easy to find transform crusher in another example component\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTransformCrusher\fP \fBTC\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VERY basic interface, just to make it easy to find transform crusher in another example component\&. 


.PP
Definition at line \fB17\fP of file \fBTransformCrusher\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTransformCrusher\fP Photon\&.Compression\&.IHasTransformCrusher\&.TC\fC [get]\fP"

.PP
Definition at line \fB19\fP of file \fBTransformCrusher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
