.TH "Photon.Pun.InstantiateParameters" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.InstantiateParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstantiateParameters\fP (string \fBprefabName\fP, Vector3 \fBposition\fP, Quaternion \fBrotation\fP, byte @\fBgroup\fP, object[] \fBdata\fP, byte \fBobjLevelPrefix\fP, int[] \fBviewIDs\fP, \fBPlayer\fP \fBcreator\fP, int \fBtimestamp\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBviewIDs\fP"
.br
.ti -1c
.RI "byte \fBobjLevelPrefix\fP"
.br
.ti -1c
.RI "object[] \fBdata\fP"
.br
.ti -1c
.RI "byte \fBgroup\fP"
.br
.ti -1c
.RI "Quaternion \fBrotation\fP"
.br
.ti -1c
.RI "Vector3 \fBposition\fP"
.br
.ti -1c
.RI "string \fBprefabName\fP"
.br
.ti -1c
.RI "\fBPlayer\fP \fBcreator\fP"
.br
.ti -1c
.RI "int \fBtimestamp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.InstantiateParameters\&.InstantiateParameters (string prefabName, Vector3 position, Quaternion rotation, byte @ group, object[] data, byte objLevelPrefix, int[] viewIDs, \fBPlayer\fP creator, int timestamp)"

.PP
Definition at line \fB44\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPlayer\fP Photon\&.Pun\&.InstantiateParameters\&.creator"

.PP
Definition at line \fB41\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "object [] Photon\&.Pun\&.InstantiateParameters\&.data"

.PP
Definition at line \fB36\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.InstantiateParameters\&.group"

.PP
Definition at line \fB37\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.InstantiateParameters\&.objLevelPrefix"

.PP
Definition at line \fB35\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.InstantiateParameters\&.position"

.PP
Definition at line \fB39\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "string Photon\&.Pun\&.InstantiateParameters\&.prefabName"

.PP
Definition at line \fB40\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "Quaternion Photon\&.Pun\&.InstantiateParameters\&.rotation"

.PP
Definition at line \fB38\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "int Photon\&.Pun\&.InstantiateParameters\&.timestamp"

.PP
Definition at line \fB42\fP of file \fBPhotonNetwork\&.cs\fP\&.
.SS "int [] Photon\&.Pun\&.InstantiateParameters\&.viewIDs"

.PP
Definition at line \fB34\fP of file \fBPhotonNetwork\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
