.TH "Photon.Pun.Demo.PunBasics.PlayerNameInputField" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.PlayerNameInputField \- Player name input field\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPlayerName\fP (string value)"
.br
.RI "Sets the name of the player, and save it in the PlayerPrefs for future sessions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Player name input field\&. 

Let the user input his name, will appear above the player in the game\&. 
.PP
Definition at line \fB20\fP of file \fBPlayerNameInputField\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.PlayerNameInputField\&.SetPlayerName (string value)"

.PP
Sets the name of the player, and save it in the PlayerPrefs for future sessions\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The name of the Player
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBPlayerNameInputField\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
