.TH "Photon.Pun.IPunOwnershipCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.IPunOwnershipCallbacks \- Global Callback interface for ownership changes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnOwnershipRequest\fP (\fBPhotonView\fP targetView, \fBPlayer\fP requestingPlayer)"
.br
.RI "Called when another player requests ownership of a \fBPhotonView\fP\&. "
.ti -1c
.RI "void \fBOnOwnershipTransfered\fP (\fBPhotonView\fP targetView, \fBPlayer\fP previousOwner)"
.br
.RI "Called when ownership of a \fBPhotonView\fP is transfered to another player\&. "
.ti -1c
.RI "void \fBOnOwnershipTransferFailed\fP (\fBPhotonView\fP targetView, \fBPlayer\fP senderOfFailedRequest)"
.br
.RI "Called when an Ownership Request fails for objects with 'takeover' setting\&. "
.in -1c
.SH "Detailed Description"
.PP 
Global Callback interface for ownership changes\&. 

These callbacks will fire for changes to ANY \fBPhotonView\fP that changes\&. Consider using \fBIOnPhotonViewControllerChange\fP for callbacks from a specific \fBPhotonView\fP\&. 
.PP
Definition at line \fB45\fP of file \fBIPunCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.IPunOwnershipCallbacks\&.OnOwnershipRequest (\fBPhotonView\fP targetView, \fBPlayer\fP requestingPlayer)"

.PP
Called when another player requests ownership of a \fBPhotonView\fP\&. Called on all clients, so check if (targetView\&.IsMine) or (targetView\&.Owner == \fBPhotonNetwork\&.LocalPlayer\fP) to determine if a targetView\&.TransferOwnership(requestingPlayer) response should be given\&. 
.PP
The parameter viewAndPlayer contains:
.PP
\fBPhotonView\fP view = viewAndPlayer[0] as \fBPhotonView\fP;
.PP
Player requestingPlayer = viewAndPlayer[1] as Player; 
.PP
\fBParameters\fP
.RS 4
\fItargetView\fP \fBPhotonView\fP for which ownership gets requested\&.
.br
\fIrequestingPlayer\fP Player who requests ownership\&.
.RE
.PP

.SS "void Photon\&.Pun\&.IPunOwnershipCallbacks\&.OnOwnershipTransfered (\fBPhotonView\fP targetView, \fBPlayer\fP previousOwner)"

.PP
Called when ownership of a \fBPhotonView\fP is transfered to another player\&. The parameter viewAndPlayers contains:
.PP
\fBPhotonView\fP view = viewAndPlayers[0] as \fBPhotonView\fP;
.PP
Player newOwner = viewAndPlayers[1] as Player;
.PP
Player oldOwner = viewAndPlayers[2] as Player; 
.PP
void OnOwnershipTransfered(object[] viewAndPlayers) {} //
.PP
\fBParameters\fP
.RS 4
\fItargetView\fP \fBPhotonView\fP for which ownership changed\&.
.br
\fIpreviousOwner\fP Player who was the previous owner (or null, if none)\&.
.RE
.PP

.SS "void Photon\&.Pun\&.IPunOwnershipCallbacks\&.OnOwnershipTransferFailed (\fBPhotonView\fP targetView, \fBPlayer\fP senderOfFailedRequest)"

.PP
Called when an Ownership Request fails for objects with 'takeover' setting\&. Each request asks to take ownership from a specific controlling player\&. This can fail if anyone else took over ownership briefly before the request arrived\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetView\fP 
.br
\fIsenderOfFailedRequest\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
