.TH "Photon.Pun.Demo.SlotRacer.Utils.BezierSpline" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.Utils.BezierSpline
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector3 \fBGetControlPoint\fP (int index)"
.br
.ti -1c
.RI "void \fBSetControlPoint\fP (int index, Vector3 point)"
.br
.ti -1c
.RI "\fBBezierControlPointMode\fP \fBGetControlPointMode\fP (int index)"
.br
.ti -1c
.RI "void \fBSetControlPointMode\fP (int index, \fBBezierControlPointMode\fP mode)"
.br
.ti -1c
.RI "Vector3 \fBGetPoint\fP (float t)"
.br
.ti -1c
.RI "Vector3 \fBGetVelocity\fP (float t)"
.br
.ti -1c
.RI "Vector3 \fBGetDirection\fP (float t)"
.br
.ti -1c
.RI "void \fBAddCurve\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBComputeLengths\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetPositionAtDistance\fP (float distance, bool reverse=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBTotalLength\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBLoop\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBControlPointCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCurveCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBBezierSpline\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.AddCurve ()"

.PP
Definition at line \fB225\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.ComputeLengths ()"

.PP
Definition at line \fB262\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetControlPoint (int index)"

.PP
Definition at line \fB64\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "\fBBezierControlPointMode\fP Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetControlPointMode (int index)"

.PP
Definition at line \fB110\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetDirection (float t)"

.PP
Definition at line \fB220\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetPoint (float t)"

.PP
Definition at line \fB184\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetPositionAtDistance (float distance, bool reverse = \fCfalse\fP)"

.PP
Definition at line \fB296\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.GetVelocity (float t)"

.PP
Definition at line \fB202\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.Reset ()"

.PP
Definition at line \fB248\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.SetControlPoint (int index, Vector3 point)"

.PP
Definition at line \fB69\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.SetControlPointMode (int index, \fBBezierControlPointMode\fP mode)"

.PP
Definition at line \fB115\fP of file \fBBezierSpline\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.TotalLength"

.PP
Definition at line \fB29\fP of file \fBBezierSpline\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.ControlPointCount\fC [get]\fP"

.PP
Definition at line \fB51\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.CurveCount\fC [get]\fP"

.PP
Definition at line \fB177\fP of file \fBBezierSpline\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierSpline\&.Loop\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB37\fP of file \fBBezierSpline\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
