.TH "Photon.Chat.UtilityScripts" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.UtilityScripts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventSystemSpawner\fP"
.br
.RI "Event system spawner\&. "
.ti -1c
.RI "class \fBOnStartDelete\fP"
.br
.RI "This component will destroy the GameObject it is attached to (in Start())\&."
.ti -1c
.RI "class \fBTextButtonTransition\fP"
.br
.RI "Use this on Button texts to have some color transition on the text as well without corrupting button's behaviour\&. "
.ti -1c
.RI "class \fBTextToggleIsOnTransition\fP"
.br
.RI "Use this on toggles texts to have some color transition on the text depending on the isOn State\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
