.TH "Photon.Compression.ZigZagExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ZigZagExt
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ulong \fBZigZag\fP (this long s)"
.br
.ti -1c
.RI "static long \fBUnZigZag\fP (this ulong u)"
.br
.ti -1c
.RI "static uint \fBZigZag\fP (this int s)"
.br
.ti -1c
.RI "static int \fBUnZigZag\fP (this uint u)"
.br
.ti -1c
.RI "static ushort \fBZigZag\fP (this short s)"
.br
.ti -1c
.RI "static short \fBUnZigZag\fP (this ushort u)"
.br
.ti -1c
.RI "static byte \fBZigZag\fP (this sbyte s)"
.br
.ti -1c
.RI "static sbyte \fBUnZigZag\fP (this byte u)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBZigZagExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static sbyte Photon\&.Compression\&.ZigZagExt\&.UnZigZag (this byte u)\fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.ZigZagExt\&.UnZigZag (this uint u)\fC [static]\fP"

.PP
Definition at line \fB23\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static long Photon\&.Compression\&.ZigZagExt\&.UnZigZag (this ulong u)\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static short Photon\&.Compression\&.ZigZagExt\&.UnZigZag (this ushort u)\fC [static]\fP"

.PP
Definition at line \fB32\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.ZigZagExt\&.ZigZag (this int s)\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.ZigZagExt\&.ZigZag (this long s)\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static byte Photon\&.Compression\&.ZigZagExt\&.ZigZag (this sbyte s)\fC [static]\fP"

.PP
Definition at line \fB37\fP of file \fBZigZagExt\&.cs\fP\&.
.SS "static ushort Photon\&.Compression\&.ZigZagExt\&.ZigZag (this short s)\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBZigZagExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
