.TH "Photon.Pun.Simple.ContactGroups.IContactGroupMask" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactGroups.IContactGroupMask
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupAssign\fP, \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupMaskSelector\fP, and \fBPhoton\&.Pun\&.Simple\&.ContactGroups\&.ContactGroupSelector\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMask\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIContactGroupMask\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.ContactGroups\&.IContactGroupMask\&.Mask\fC [get]\fP"

.PP
Definition at line \fB10\fP of file \fBIContactGroupMask\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
