.TH "Photon.Pun.Simple.IOnEnable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnEnable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncAnimator\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncContact\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncOwner\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncShootBase\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncSpawnTimer\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncState\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncTransform\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncVitals\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncObject< TFrame >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPostEnable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBNetObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnEnable\&.OnPostEnable ()"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncAnimator\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncContact\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncOwner\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncShootBase\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncSpawnTimer\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncState\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncTransform\&.Frame >\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncVitals\&.Frame >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
