.TH "Photon.Pun.PunWizardText" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PunWizardText
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBWindowTitle\fP = 'PUN Wizard'"
.br
.ti -1c
.RI "string \fBSetupWizardWarningTitle\fP = 'Warning'"
.br
.ti -1c
.RI "string \fBSetupWizardWarningMessage\fP = 'You have not yet run the Photon setup wizard! Your game won't be able to connect\&. See Windows \-> Photon Unity Networking\&.'"
.br
.ti -1c
.RI "string \fBMainMenuButton\fP = 'Main Menu'"
.br
.ti -1c
.RI "string \fBSetupWizardTitle\fP = 'PUN Setup'"
.br
.ti -1c
.RI "string \fBSetupWizardInfo\fP = 'Thanks for importing Photon Unity Networking\&.\\nThis window should set you up\&.\\n\\n<b>\-</b> To use an existing Photon Cloud App, enter your AppId\&.\\n<b>\-</b> To register an account or access an existing one, enter the account's mail address\&.\\n<b>\-</b> To use Photon OnPremise, skip this step\&.'"
.br
.ti -1c
.RI "string \fBEmailOrAppIdLabel\fP = 'AppId or Email'"
.br
.ti -1c
.RI "string \fBAlreadyRegisteredInfo\fP = 'The email is registered so we can't fetch your AppId (without password)\&.\\n\\nPlease login online to get your AppId and paste it above\&.'"
.br
.ti -1c
.RI "string \fBSkipRegistrationInfo\fP = 'Skipping? No problem:\\nEdit your server settings in the PhotonServerSettings file\&.'"
.br
.ti -1c
.RI "string \fBRegisteredNewAccountInfo\fP = 'We created a (free) account and fetched you an AppId\&.\\nWelcome\&. Your PUN project is setup\&.'"
.br
.ti -1c
.RI "string \fBAppliedToSettingsInfo\fP = 'Your AppId is now applied to this project\&.'"
.br
.ti -1c
.RI "string \fBSetupCompleteInfo\fP = '<b>Done!</b>\\nAll connection settings can be edited in the <b>PhotonServerSettings</b> now\&.\\nHave a look\&.'"
.br
.ti -1c
.RI "string \fBCloseWindowButton\fP = 'Close'"
.br
.ti -1c
.RI "string \fBSkipButton\fP = 'Skip'"
.br
.ti -1c
.RI "string \fBSetupButton\fP = 'Setup Project'"
.br
.ti -1c
.RI "string \fBCancelButton\fP = 'Cancel'"
.br
.ti -1c
.RI "string \fBPUNWizardLabel\fP = 'PUN Wizard'"
.br
.ti -1c
.RI "string \fBSettingsButton\fP = 'Settings:'"
.br
.ti -1c
.RI "string \fBSetupServerCloudLabel\fP = 'Setup wizard for setting up your own server or the cloud\&.'"
.br
.ti -1c
.RI "string \fBWarningPhotonDisconnect\fP = 'Disconnecting PUN due to recompile\&. Exit PlayMode\&.'"
.br
.ti -1c
.RI "string \fBStartButton\fP = 'Start'"
.br
.ti -1c
.RI "string \fBLocateSettingsButton\fP = 'Locate PhotonServerSettings'"
.br
.ti -1c
.RI "string \fBSettingsHighlightLabel\fP = 'Highlights the used photon settings file in the project\&.'"
.br
.ti -1c
.RI "string \fBDocumentationLabel\fP = 'Documentation:'"
.br
.ti -1c
.RI "string \fBOpenPDFText\fP = 'Reference PDF'"
.br
.ti -1c
.RI "string \fBOpenPDFTooltip\fP = 'Opens the local documentation pdf\&.'"
.br
.ti -1c
.RI "string \fBOpenDevNetText\fP = 'Doc Pages / Manual'"
.br
.ti -1c
.RI "string \fBOpenDevNetTooltip\fP = 'Online documentation for Photon\&.'"
.br
.ti -1c
.RI "string \fBOpenCloudDashboardText\fP = 'Cloud Dashboard Login'"
.br
.ti -1c
.RI "string \fBOpenCloudDashboardTooltip\fP = 'Review Cloud App information and statistics\&.'"
.br
.ti -1c
.RI "string \fBOpenForumText\fP = 'Open Forum'"
.br
.ti -1c
.RI "string \fBOpenForumTooltip\fP = 'Online support for Photon\&.'"
.br
.ti -1c
.RI "string \fBOkButton\fP = 'Ok'"
.br
.ti -1c
.RI "string \fBOwnHostCloudCompareLabel\fP = 'How 'my own host' compares to 'cloud'\&.'"
.br
.ti -1c
.RI "string \fBComparisonPageButton\fP = 'Cloud versus OnPremise'"
.br
.ti -1c
.RI "string \fBConnectionTitle\fP = 'Connecting'"
.br
.ti -1c
.RI "string \fBConnectionInfo\fP = 'Connecting to the account service\&.\&.\&.'"
.br
.ti -1c
.RI "string \fBErrorTextTitle\fP = 'Error'"
.br
.ti -1c
.RI "string \fBIncorrectRPCListTitle\fP = 'Warning: RPC\-list becoming incompatible!'"
.br
.ti -1c
.RI "string \fBIncorrectRPCListLabel\fP = 'Your project's RPC\-list is full, so we can't add some RPCs just compiled\&.\\n\\nBy removing outdated RPCs, the list will be long enough but incompatible with older client builds!\\n\\nMake sure you change the game version where you use \fBPhotonNetwork\&.ConnectUsingSettings\fP()\&.'"
.br
.ti -1c
.RI "string \fBRemoveOutdatedRPCsLabel\fP = 'Remove outdated RPCs'"
.br
.ti -1c
.RI "string \fBFullRPCListTitle\fP = 'Warning: RPC\-list is full!'"
.br
.ti -1c
.RI "string \fBFullRPCListLabel\fP = 'Your project's RPC\-list is too long for PUN\&.\\n\\nYou can change PUN's source to use short\-typed RPC index\&. Look for comments 'LIMITS RPC COUNT'\\n\\nAlternatively, remove some RPC methods (use more parameters per RPC maybe)\&.\\n\\nAfter a RPC\-list refresh, make sure you change the game version where you use \fBPhotonNetwork\&.ConnectUsingSettings\fP()\&.'"
.br
.ti -1c
.RI "string \fBSkipRPCListUpdateLabel\fP = 'Skip RPC\-list update'"
.br
.ti -1c
.RI "string \fBPUNNameReplaceTitle\fP = 'Warning: RPC\-list Compatibility'"
.br
.ti -1c
.RI "string \fBPUNNameReplaceLabel\fP = 'PUN replaces RPC names with numbers by using the RPC\-list\&. All clients must use the same list for that\&.\\n\\nClearing it most likely makes your client incompatible with previous versions! Change your game version or make sure the RPC\-list matches other clients\&.'"
.br
.ti -1c
.RI "string \fBRPCListCleared\fP = 'Clear RPC\-list'"
.br
.ti -1c
.RI "string \fBServerSettingsCleanedWarning\fP = 'Cleared the PhotonServerSettings\&.RpcList, which breaks compatibility with older builds\&. You should update the \\'App Version\\' in the PhotonServerSettings to avoid issues\&.'"
.br
.ti -1c
.RI "string \fBWizardMainWindowInfo\fP = 'This window should help you find important settings for PUN, as well as documentation\&.'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBPhotonEditor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.PunWizardText\&.AlreadyRegisteredInfo = 'The email is registered so we can't fetch your AppId (without password)\&.\\n\\nPlease login online to get your AppId and paste it above\&.'"

.PP
Definition at line \fB36\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.AppliedToSettingsInfo = 'Your AppId is now applied to this project\&.'"

.PP
Definition at line \fB39\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.CancelButton = 'Cancel'"

.PP
Definition at line \fB44\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.CloseWindowButton = 'Close'"

.PP
Definition at line \fB41\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.ComparisonPageButton = 'Cloud versus OnPremise'"

.PP
Definition at line \fB63\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.ConnectionInfo = 'Connecting to the account service\&.\&.\&.'"

.PP
Definition at line \fB65\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.ConnectionTitle = 'Connecting'"

.PP
Definition at line \fB64\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.DocumentationLabel = 'Documentation:'"

.PP
Definition at line \fB52\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.EmailOrAppIdLabel = 'AppId or Email'"

.PP
Definition at line \fB35\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.ErrorTextTitle = 'Error'"

.PP
Definition at line \fB66\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.FullRPCListLabel = 'Your project's RPC\-list is too long for PUN\&.\\n\\nYou can change PUN's source to use short\-typed RPC index\&. Look for comments 'LIMITS RPC COUNT'\\n\\nAlternatively, remove some RPC methods (use more parameters per RPC maybe)\&.\\n\\nAfter a RPC\-list refresh, make sure you change the game version where you use \fBPhotonNetwork\&.ConnectUsingSettings\fP()\&.'"

.PP
Definition at line \fB71\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.FullRPCListTitle = 'Warning: RPC\-list is full!'"

.PP
Definition at line \fB70\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.IncorrectRPCListLabel = 'Your project's RPC\-list is full, so we can't add some RPCs just compiled\&.\\n\\nBy removing outdated RPCs, the list will be long enough but incompatible with older client builds!\\n\\nMake sure you change the game version where you use \fBPhotonNetwork\&.ConnectUsingSettings\fP()\&.'"

.PP
Definition at line \fB68\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.IncorrectRPCListTitle = 'Warning: RPC\-list becoming incompatible!'"

.PP
Definition at line \fB67\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.LocateSettingsButton = 'Locate PhotonServerSettings'"

.PP
Definition at line \fB50\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.MainMenuButton = 'Main Menu'"

.PP
Definition at line \fB32\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OkButton = 'Ok'"

.PP
Definition at line \fB61\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenCloudDashboardText = 'Cloud Dashboard Login'"

.PP
Definition at line \fB57\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenCloudDashboardTooltip = 'Review Cloud App information and statistics\&.'"

.PP
Definition at line \fB58\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenDevNetText = 'Doc Pages / Manual'"

.PP
Definition at line \fB55\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenDevNetTooltip = 'Online documentation for Photon\&.'"

.PP
Definition at line \fB56\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenForumText = 'Open Forum'"

.PP
Definition at line \fB59\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenForumTooltip = 'Online support for Photon\&.'"

.PP
Definition at line \fB60\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenPDFText = 'Reference PDF'"

.PP
Definition at line \fB53\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OpenPDFTooltip = 'Opens the local documentation pdf\&.'"

.PP
Definition at line \fB54\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.OwnHostCloudCompareLabel = 'How 'my own host' compares to 'cloud'\&.'"

.PP
Definition at line \fB62\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.PUNNameReplaceLabel = 'PUN replaces RPC names with numbers by using the RPC\-list\&. All clients must use the same list for that\&.\\n\\nClearing it most likely makes your client incompatible with previous versions! Change your game version or make sure the RPC\-list matches other clients\&.'"

.PP
Definition at line \fB74\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.PUNNameReplaceTitle = 'Warning: RPC\-list Compatibility'"

.PP
Definition at line \fB73\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.PUNWizardLabel = 'PUN Wizard'"

.PP
Definition at line \fB45\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.RegisteredNewAccountInfo = 'We created a (free) account and fetched you an AppId\&.\\nWelcome\&. Your PUN project is setup\&.'"

.PP
Definition at line \fB38\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.RemoveOutdatedRPCsLabel = 'Remove outdated RPCs'"

.PP
Definition at line \fB69\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.RPCListCleared = 'Clear RPC\-list'"

.PP
Definition at line \fB75\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.ServerSettingsCleanedWarning = 'Cleared the PhotonServerSettings\&.RpcList, which breaks compatibility with older builds\&. You should update the \\'App Version\\' in the PhotonServerSettings to avoid issues\&.'"

.PP
Definition at line \fB76\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SettingsButton = 'Settings:'"

.PP
Definition at line \fB46\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SettingsHighlightLabel = 'Highlights the used photon settings file in the project\&.'"

.PP
Definition at line \fB51\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupButton = 'Setup Project'"

.PP
Definition at line \fB43\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupCompleteInfo = '<b>Done!</b>\\nAll connection settings can be edited in the <b>PhotonServerSettings</b> now\&.\\nHave a look\&.'"

.PP
Definition at line \fB40\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupServerCloudLabel = 'Setup wizard for setting up your own server or the cloud\&.'"

.PP
Definition at line \fB47\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupWizardInfo = 'Thanks for importing Photon Unity Networking\&.\\nThis window should set you up\&.\\n\\n<b>\-</b> To use an existing Photon Cloud App, enter your AppId\&.\\n<b>\-</b> To register an account or access an existing one, enter the account's mail address\&.\\n<b>\-</b> To use Photon OnPremise, skip this step\&.'"

.PP
Definition at line \fB34\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupWizardTitle = 'PUN Setup'"

.PP
Definition at line \fB33\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupWizardWarningMessage = 'You have not yet run the Photon setup wizard! Your game won't be able to connect\&. See Windows \-> Photon Unity Networking\&.'"

.PP
Definition at line \fB31\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SetupWizardWarningTitle = 'Warning'"

.PP
Definition at line \fB30\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SkipButton = 'Skip'"

.PP
Definition at line \fB42\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SkipRegistrationInfo = 'Skipping? No problem:\\nEdit your server settings in the PhotonServerSettings file\&.'"

.PP
Definition at line \fB37\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.SkipRPCListUpdateLabel = 'Skip RPC\-list update'"

.PP
Definition at line \fB72\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.StartButton = 'Start'"

.PP
Definition at line \fB49\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.WarningPhotonDisconnect = 'Disconnecting PUN due to recompile\&. Exit PlayMode\&.'"

.PP
Definition at line \fB48\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.WindowTitle = 'PUN Wizard'"

.PP
Definition at line \fB29\fP of file \fBPhotonEditor\&.cs\fP\&.
.SS "string Photon\&.Pun\&.PunWizardText\&.WizardMainWindowInfo = 'This window should help you find important settings for PUN, as well as documentation\&.'"

.PP
Definition at line \fB77\fP of file \fBPhotonEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
