.TH "Photon.Pun.Demo.Hub" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Hub
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDemoHubManager\fP"
.br
.ti -1c
.RI "class \fBPunStartup\fP"
.br
.ti -1c
.RI "class \fBToDemoHubButton\fP"
.br
.RI "Present a button on all launched demos from hub to allow getting back to the demo hub\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
