.TH "Photon.Pun.Simple.OwnedIVitals" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.OwnedIVitals
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOnChangeAuthority\fP (\fBIVitalsSystem\fP ivc, bool isMine, bool asServer)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBIVitalsSystem\fP > \fBownedVitalComponents\fP = new List<\fBIVitalsSystem\fP>()"
.br
.RI "List of all VitalsComponents that belong to this connection\&. "
.ti -1c
.RI "static List< \fBIOnChangeOwnedVitals\fP > \fBiOnChangeOwnedVitals\fP = new List<\fBIOnChangeOwnedVitals\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBIVitalsSystem\fP? \fBLastItem\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBOwnedIVitals\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.OwnedIVitals\&.OnChangeAuthority (\fBIVitalsSystem\fP ivc, bool isMine, bool asServer)\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBOwnedIVitals\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBIOnChangeOwnedVitals\fP> Photon\&.Pun\&.Simple\&.OwnedIVitals\&.iOnChangeOwnedVitals = new List<\fBIOnChangeOwnedVitals\fP>()\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBOwnedIVitals\&.cs\fP\&.
.SS "List<\fBIVitalsSystem\fP> Photon\&.Pun\&.Simple\&.OwnedIVitals\&.ownedVitalComponents = new List<\fBIVitalsSystem\fP>()\fC [static]\fP"

.PP
List of all VitalsComponents that belong to this connection\&. Used for connecting \fBVitalUI\fP elements to \fBVitals\fP at runtime\&. 
.PP
Definition at line \fB16\fP of file \fBOwnedIVitals\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIVitalsSystem\fP? Photon\&.Pun\&.Simple\&.OwnedIVitals\&.LastItem\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB19\fP of file \fBOwnedIVitals\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
