.TH "Photon.Pun.Simple.IOnIncrementFrame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnIncrementFrame \- Callback Interface for \fBOnIncrementFrame()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnIncrementFrame\fP (int newFrameId, int newSubFrameId, int previousFrameId, int prevSubFrameId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnIncrementFrame()\fP\&. 

Called when \fBNetMaster\fP increments the current FrameId and SubFrameId\&. 
.PP
Definition at line \fB51\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnIncrementFrame\&.OnIncrementFrame (int newFrameId, int newSubFrameId, int previousFrameId, int prevSubFrameId)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, and \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
