.TH "Photon.Pun.Demo.SlotRacer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUtils\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPlayerControl\fP"
.br
.RI "Player control\&. "
.ti -1c
.RI "class \fBSlotLanes\fP"
.br
.RI "Define Slot lanes and grid positions placeholders\&. "
.ti -1c
.RI "class \fBSlotRacerSplashScreen\fP"
.br
.RI "Slot racer splash screen\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
