.TH "Photon.Pun.Simple.InventoryContactReactors< T >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.InventoryContactReactors< T > \- An implementation of InventoryContactReactors<> that can be used as an inv  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase< IInventorySystem< T > >\fP, and \fBPhoton\&.Pun\&.Simple\&.IInventoryable< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwakeInitialize\fP (bool isNetObject)"
.br
.RI "Awake code that will run whether or not a \fBNetObject\fP Exists "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override \fBConsumption\fP \fBProcessContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Vector3Int \fBsize\fP = new Vector3Int(1, 1, 1)"
.br
.ti -1c
.RI "int \fBvolume\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override Vector3Int \fBSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "abstract T \fBSize\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBVolume\fP\fC [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsPickup\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An implementation of InventoryContactReactors<> that can be used as an inv 
.PP
Definition at line \fB14\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.OnAwakeInitialize (bool isNetObject)\fC [virtual]\fP"

.PP
Awake code that will run whether or not a \fBNetObject\fP Exists 
.PP
\fBReturns\fP
.RS 4
Returns true if this is a \fBNetObject\fP
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB20\fP of file \fBInventoryContactReactors\&.cs\fP\&.
.SS "override \fBConsumption\fP \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.ProcessContactEvent (\fBContactEvent\fP contactEvent)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.ContactReactorBase< IInventorySystem< T > >\fP\&.
.PP
Definition at line \fB25\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3Int \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.size = new Vector3Int(1, 1, 1)\fC [protected]\fP"

.PP
Definition at line \fB17\fP of file \fBInventoryContactReactors\&.cs\fP\&.
.SS "int \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.volume\fC [protected]\fP"

.PP
Definition at line \fB20\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.IsPickup\fC [get]\fP"

.PP
Definition at line \fB23\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.
.SS "override Vector3Int \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.Size\fC [get]\fP"

.PP
Definition at line \fB18\fP of file \fBInventoryContactReactors\&.cs\fP\&.
.SS "abstract T \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.Size\fC [get]\fP"

.PP
Definition at line \fB17\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.
.SS "int \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors\fP< T >\&.Volume\fC [get]\fP"

.PP
Definition at line \fB21\fP of file \fBInventoryContactReactorsT\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
