.TH "Photon.Pun.UtilityScripts.CellTree" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.CellTree \- Represents the tree accessible from its root node\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCellTree\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBCellTree\fP (\fBCellTreeNode\fP root)"
.br
.RI "Constructor to define the root node\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCellTreeNode\fP \fBRootNode\fP\fC [get]\fP"
.br
.RI "Represents the root node of the cell tree\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the tree accessible from its root node\&. 


.PP
Definition at line \fB277\fP of file \fBCullArea\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.UtilityScripts\&.CellTree\&.CellTree ()"

.PP
Default constructor\&. 
.PP
Definition at line \fB287\fP of file \fBCullArea\&.cs\fP\&.
.SS "Photon\&.Pun\&.UtilityScripts\&.CellTree\&.CellTree (\fBCellTreeNode\fP root)"

.PP
Constructor to define the root node\&. 
.PP
\fBParameters\fP
.RS 4
\fIroot\fP The root node of the tree\&.
.RE
.PP

.PP
Definition at line \fB295\fP of file \fBCullArea\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCellTreeNode\fP Photon\&.Pun\&.UtilityScripts\&.CellTree\&.RootNode\fC [get]\fP"

.PP
Represents the root node of the cell tree\&. 
.PP
Definition at line \fB282\fP of file \fBCullArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
