.TH "Photon.Pun.Simple.SyncNodeMover.Frame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncNodeMover.Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrame\fP ()"
.br
.ti -1c
.RI "\fBFrame\fP (int \fBframeId\fP)"
.br
.ti -1c
.RI "override void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.ti -1c
.RI "bool \fBCompare\fP (\fBFrame\fP otherFrame)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtargetNode\fP"
.br
.ti -1c
.RI "float \fBphase\fP"
.br
.ti -1c
.RI "uint \fBcphase\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB77\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.Frame ()"

.PP
Definition at line \fB83\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.Frame (int frameId)"

.PP
Definition at line \fB85\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB97\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.Compare (\fBFrame\fP otherFrame)"

.PP
Definition at line \fB106\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB87\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.cphase"

.PP
Definition at line \fB81\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.phase"

.PP
Definition at line \fB80\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\&.targetNode"

.PP
Definition at line \fB79\fP of file \fBSyncNodeMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
