.TH "Photon.Realtime.IInRoomCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.IInRoomCallbacks \- Collection of 'in room' callbacks for the \fBRealtime\fP Api to cover: Players entering or leaving, property updates and Master Client switching\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.Simple\&.Internal\&.TickManager\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\fP, Photon\&.Realtime\&.InRoomCallbacksContainer, and \fBPhoton\&.Realtime\&.SupportLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPlayerEnteredRoom\fP (\fBPlayer\fP newPlayer)"
.br
.RI "Called when a remote player entered the room\&. "
.ti -1c
.RI "void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP otherPlayer)"
.br
.RI "Called when a remote player left the room or became inactive\&. "
.ti -1c
.RI "void \fBOnRoomPropertiesUpdate\fP (\fBHashtable\fP propertiesThatChanged)"
.br
.RI "Called when a room's custom properties changed\&. "
.ti -1c
.RI "void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"
.br
.RI "Called when custom player-properties are changed\&. "
.ti -1c
.RI "void \fBOnMasterClientSwitched\fP (\fBPlayer\fP newMasterClient)"
.br
.RI "Called after switching to a new MasterClient when the current one leaves\&. "
.in -1c
.SH "Detailed Description"
.PP 
Collection of 'in room' callbacks for the \fBRealtime\fP Api to cover: Players entering or leaving, property updates and Master Client switching\&. 

Classes that implement this interface must be registered to get callbacks for various situations\&.
.PP
To register for callbacks, call \fBLoadBalancingClient\&.AddCallbackTarget\fP and pass the class implementing this interface To stop getting callbacks, call \fBLoadBalancingClient\&.RemoveCallbackTarget\fP and pass the class implementing this interface
.PP
Definition at line \fB3855\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.IInRoomCallbacks\&.OnMasterClientSwitched (\fBPlayer\fP newMasterClient)"

.PP
Called after switching to a new MasterClient when the current one leaves\&. This is not called when this client enters a room\&. The former MasterClient is still in the player list when this method get called\&. 
.PP
Implemented in \fBLauncher\fP, \fBLauncher_old\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\fP, and \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PlayerListView\fP\&.
.SS "void Photon\&.Realtime\&.IInRoomCallbacks\&.OnPlayerEnteredRoom (\fBPlayer\fP newPlayer)"

.PP
Called when a remote player entered the room\&. This \fBPlayer\fP is already added to the playerlist\&. 
.PP
If your game starts with a certain number of players, this callback can be useful to check the Room\&.playerCount and find out if you can start\&. 
.PP
Implemented in \fBLauncher\fP, \fBLauncher_old\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PlayerListView\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PlayerNumbering\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PunTeams\fP, and \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.GameManager\fP\&.
.SS "void Photon\&.Realtime\&.IInRoomCallbacks\&.OnPlayerLeftRoom (\fBPlayer\fP otherPlayer)"

.PP
Called when a remote player left the room or became inactive\&. Check otherPlayer\&.IsInactive\&. 
.PP
If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic\&.
.PP
Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room\&. In such cases, the \fBPlayer\fP stays in the \fBRoom\&.Players\fP dictionary\&.
.PP
If the player is not just inactive, it gets removed from the \fBRoom\&.Players\fP dictionary, before the callback is called\&. 
.PP
Implemented in \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.GameManager\fP, \fBSInt\&.Netcode\&.PhotonPUN\&.PlayerListItem\fP, \fBPlayerListItem_Old\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PlayerDetailsController\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PlayerListView\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PlayerNumbering\fP, and \fBPhoton\&.Pun\&.UtilityScripts\&.PunTeams\fP\&.
.SS "void Photon\&.Realtime\&.IInRoomCallbacks\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"

.PP
Called when custom player-properties are changed\&. \fBPlayer\fP and the changed properties are passed as object[]\&. 
.PP
Changing properties must be done by \fBPlayer\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetPlayer\fP Contains \fBPlayer\fP that changed\&.
.br
\fIchangedProps\fP Contains the properties that changed\&.
.RE
.PP

.PP
Implemented in \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.PlayerController\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.PlayerOverviewPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PlayerNumbering\fP, and \fBPhoton\&.Pun\&.UtilityScripts\&.PunTeams\fP\&.
.SS "void Photon\&.Realtime\&.IInRoomCallbacks\&.OnRoomPropertiesUpdate (\fBHashtable\fP propertiesThatChanged)"

.PP
Called when a room's custom properties changed\&. The propertiesThatChanged contains all that was set via \fBRoom\&.SetCustomProperties\fP\&. 
.PP
Since v1\&.25 this method has one parameter: Hashtable propertiesThatChanged\&.
.br
 Changing properties must be done by \fBRoom\&.SetCustomProperties\fP, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertiesThatChanged\fP 
.RE
.PP

.PP
Implemented in \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Pun\&.PhotonHandler\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Cluster\fP, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.IngameControlPanel\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.CountdownTimer\fP, \fBPhoton\&.Pun\&.UtilityScripts\&.PunTurnManager\fP, and \fBPhoton\&.Pun\&.Simple\&.Internal\&.TickManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
