.TH "Photon.Pun.Simple.AnimPassThru" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.AnimPassThru \- A generic passthrough used to store Play/Crossfade/SetTrigger calls for deferment  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimPassThru\fP (\fBPassThruType\fP triggerType, int \fBhash\fP, int \fBlayer\fP, float normTime, float otherTime, float \fBduration\fP, \fBLocalApplyTiming\fP \fBlocalApplyTiming\fP=\fBLocalApplyTiming\&.OnSend\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPassThruType\fP \fBpassThruType\fP"
.br
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "float \fBnormlTime\fP"
.br
.ti -1c
.RI "float \fBfixedTime\fP"
.br
.ti -1c
.RI "float \fBduration\fP"
.br
.ti -1c
.RI "int \fBlayer\fP"
.br
.ti -1c
.RI "\fBLocalApplyTiming\fP \fBlocalApplyTiming\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A generic passthrough used to store Play/Crossfade/SetTrigger calls for deferment 
.PP
Definition at line \fB13\fP of file \fBAnimPassThru\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.AnimPassThru\&.AnimPassThru (\fBPassThruType\fP triggerType, int hash, int layer, float normTime, float otherTime, float duration, \fBLocalApplyTiming\fP localApplyTiming = \fC\fBLocalApplyTiming\&.OnSend\fP\fP)"

.PP
Definition at line \fB23\fP of file \fBAnimPassThru\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.Simple\&.AnimPassThru\&.duration"

.PP
Definition at line \fB19\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.AnimPassThru\&.fixedTime"

.PP
Definition at line \fB18\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.AnimPassThru\&.hash"

.PP
Definition at line \fB16\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.AnimPassThru\&.layer"

.PP
Definition at line \fB20\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "\fBLocalApplyTiming\fP Photon\&.Pun\&.Simple\&.AnimPassThru\&.localApplyTiming"

.PP
Definition at line \fB21\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.AnimPassThru\&.normlTime"

.PP
Definition at line \fB17\fP of file \fBAnimPassThru\&.cs\fP\&.
.SS "\fBPassThruType\fP Photon\&.Pun\&.Simple\&.AnimPassThru\&.passThruType"

.PP
Definition at line \fB15\fP of file \fBAnimPassThru\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
