.TH "Photon.Pun.UtilityScripts.EventSystemSpawner" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.EventSystemSpawner \- Event system spawner\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Event system spawner\&. 

Will add an EventSystem GameObject with an EventSystem component and a StandaloneInputModule component\&. Use this in additive scene loading context where you would otherwise get a 'Multiple EventSystem in scene\&.\&.\&. this is not supported' error from Unity\&. 
.PP
Definition at line \fB20\fP of file \fBEventSystemSpawner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
