.TH "Photon.Realtime.EnterRoomParams" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.EnterRoomParams \- Parameters for creating rooms\&. 

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBRoomName\fP"
.br
.RI "The name of the room to create\&. If null, the server generates a unique name\&. If not null, it must be unique and new or will cause an error\&."
.ti -1c
.RI "\fBRoomOptions\fP \fBRoomOptions\fP"
.br
.RI "The \fBRoomOptions\fP define the optional behaviour of rooms\&."
.ti -1c
.RI "\fBTypedLobby\fP \fBLobby\fP"
.br
.RI "A lobby to attach the new room to\&. If set, this overrides a joined lobby (if any)\&."
.ti -1c
.RI "\fBHashtable\fP \fBPlayerProperties\fP"
.br
.RI "The custom player properties that describe this client / user\&. Keys must be strings\&."
.ti -1c
.RI "string[] \fBExpectedUsers\fP"
.br
.RI "A list of users who are expected to join the room along with this client\&. Reserves slots for rooms with MaxPlayers value\&."
.in -1c
.SH "Detailed Description"
.PP 
Parameters for creating rooms\&.
.PP
Definition at line \fB1074\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] Photon\&.Realtime\&.EnterRoomParams\&.ExpectedUsers"

.PP
A list of users who are expected to join the room along with this client\&. Reserves slots for rooms with MaxPlayers value\&.
.PP
Definition at line \fB1089\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBTypedLobby\fP Photon\&.Realtime\&.EnterRoomParams\&.Lobby"

.PP
A lobby to attach the new room to\&. If set, this overrides a joined lobby (if any)\&.
.PP
Definition at line \fB1081\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBHashtable\fP Photon\&.Realtime\&.EnterRoomParams\&.PlayerProperties"

.PP
The custom player properties that describe this client / user\&. Keys must be strings\&.
.PP
Definition at line \fB1083\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.EnterRoomParams\&.RoomName"

.PP
The name of the room to create\&. If null, the server generates a unique name\&. If not null, it must be unique and new or will cause an error\&.
.PP
Definition at line \fB1077\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBRoomOptions\fP Photon\&.Realtime\&.EnterRoomParams\&.RoomOptions"

.PP
The \fBRoomOptions\fP define the optional behaviour of rooms\&.
.PP
Definition at line \fB1079\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
