.TH "Photon.Compression.CompressedElementExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.CompressedElementExt
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static StringBuilder \fBAppendSB\fP (this StringBuilder strb, \fBCompressedElement\fP ce)"
.br
.ti -1c
.RI "static void \fBGetChangeAmount\fP (uint[] results, \fBCompressedElement\fP a, \fBCompressedElement\fP b)"
.br
.ti -1c
.RI "static uint[] \fBGetChangeAmount\fP (\fBCompressedElement\fP a, \fBCompressedElement\fP b)"
.br
.ti -1c
.RI "static void \fBGuessUpperBits\fP (this \fBCompressedElement\fP newcpos, \fBElementCrusher\fP ec, \fBCompressedElement\fP oldcpos, BitCullingLevel bcl)"
.br
.RI "Alternative to OverwriteUpperBits that attempts to guess the upperbits by seeing if each axis of the new position would be closer to the old one if the upper bit is incremented by one, two, three etc\&. "
.ti -1c
.RI "static \fBCompressedElement\fP \fBGuessUpperBits\fP (this \fBCompressedElement\fP newcpos, \fBCompressedElement\fP oldcpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)"
.br
.ti -1c
.RI "static void \fBOverwriteUpperBits\fP (this \fBCompressedElement\fP low, \fBCompressedElement\fP uppers, BitCullingLevel bcl)"
.br
.RI "Replace the upperbits of the first compressed element with the upper bits of the second, using BitCullingLevel as the separation point\&. "
.ti -1c
.RI "static \fBCompressedElement\fP \fBOverwriteUpperBits\fP (this \fBCompressedElement\fP low, \fBCompressedElement\fP up, \fBElementCrusher\fP ec, BitCullingLevel bcl)"
.br
.ti -1c
.RI "static void \fBZeroLowerBits\fP (this \fBCompressedElement\fP fullpos, \fBCompressedElement\fP target, BitCullingLevel bcl)"
.br
.ti -1c
.RI "static \fBCompressedElement\fP \fBZeroLowerBits\fP (this \fBCompressedElement\fP fullpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)"
.br
.ti -1c
.RI "static void \fBZeroUpperBits\fP (this \fBCompressedElement\fP fullpos, \fBCompressedElement\fP target, BitCullingLevel bcl)"
.br
.ti -1c
.RI "static \fBCompressedElement\fP \fBZeroUpperBits\fP (this \fBCompressedElement\fP fullpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static System\&.UInt32[] \fBreusableInts\fP = new System\&.UInt32[3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB758\fP of file \fBCompressedElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static StringBuilder Photon\&.Compression\&.CompressedElementExt\&.AppendSB (this StringBuilder strb, \fBCompressedElement\fP ce)\fC [static]\fP"

.PP
Definition at line \fB762\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static uint[] Photon\&.Compression\&.CompressedElementExt\&.GetChangeAmount (\fBCompressedElement\fP a, \fBCompressedElement\fP b)\fC [static]\fP"

.PP
Definition at line \fB799\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.CompressedElementExt\&.GetChangeAmount (uint[] results, \fBCompressedElement\fP a, \fBCompressedElement\fP b)\fC [static]\fP"

.PP
Definition at line \fB793\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static \fBCompressedElement\fP Photon\&.Compression\&.CompressedElementExt\&.GuessUpperBits (this \fBCompressedElement\fP newcpos, \fBCompressedElement\fP oldcpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB824\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.CompressedElementExt\&.GuessUpperBits (this \fBCompressedElement\fP newcpos, \fBElementCrusher\fP ec, \fBCompressedElement\fP oldcpos, BitCullingLevel bcl)\fC [static]\fP"

.PP
Alternative to OverwriteUpperBits that attempts to guess the upperbits by seeing if each axis of the new position would be closer to the old one if the upper bit is incremented by one, two, three etc\&. Stops trying when it fails to get a better result\&. 
.PP
\fBParameters\fP
.RS 4
\fIoldcpos\fP Last best position test against\&.
.RE
.PP
\fBReturns\fP
.RS 4
Returns a corrected CompressPos
.RE
.PP

.PP
Definition at line \fB813\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static \fBCompressedElement\fP Photon\&.Compression\&.CompressedElementExt\&.OverwriteUpperBits (this \fBCompressedElement\fP low, \fBCompressedElement\fP up, \fBElementCrusher\fP ec, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB859\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.CompressedElementExt\&.OverwriteUpperBits (this \fBCompressedElement\fP low, \fBCompressedElement\fP uppers, BitCullingLevel bcl)\fC [static]\fP"

.PP
Replace the upperbits of the first compressed element with the upper bits of the second, using BitCullingLevel as the separation point\&. 
.PP
Definition at line \fB848\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.CompressedElementExt\&.ZeroLowerBits (this \fBCompressedElement\fP fullpos, \fBCompressedElement\fP target, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB878\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static \fBCompressedElement\fP Photon\&.Compression\&.CompressedElementExt\&.ZeroLowerBits (this \fBCompressedElement\fP fullpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB889\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.CompressedElementExt\&.ZeroUpperBits (this \fBCompressedElement\fP fullpos, \fBCompressedElement\fP target, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB907\fP of file \fBCompressedElement\&.cs\fP\&.
.SS "static \fBCompressedElement\fP Photon\&.Compression\&.CompressedElementExt\&.ZeroUpperBits (this \fBCompressedElement\fP fullpos, \fBElementCrusher\fP ec, BitCullingLevel bcl)\fC [static]\fP"

.PP
Definition at line \fB918\fP of file \fBCompressedElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "System\&.UInt32 [] Photon\&.Compression\&.CompressedElementExt\&.reusableInts = new System\&.UInt32[3]\fC [static]\fP"

.PP
Definition at line \fB760\fP of file \fBCompressedElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
