.TH "Photon.Pun.Simple.Mount" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Mount
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreQuit\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreNetDestroy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "void \fBOnPreQuit\fP ()"
.br
.ti -1c
.RI "void \fBOnPreNetDestroy\fP (\fBNetObject\fP rootNetObj)"
.br
.ti -1c
.RI "void \fBDismountAll\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBChangeMounting\fP (\fBIMountable\fP mountable, \fBMount\fP prevMount, \fBMount\fP newMount)"
.br
.RI "Removes mountable from the list of objects attached to the current mount, and adds to the list of the new mount\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMountSelector\fP \fBmountType\fP = new \fBMountSelector\fP(1)"
.br
.ti -1c
.RI "int \fBcomponentIndex\fP"
.br
.ti -1c
.RI "List< \fBIMountable\fP > \fBmountedObjs\fP = new List<\fBIMountable\fP>()"
.br
.ti -1c
.RI "\fBMountsManager\fP \fBmountsLookup\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBROOT_MOUNT_NAME\fP = 'Root'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBMount\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.Mount\&.ChangeMounting (\fBIMountable\fP mountable, \fBMount\fP prevMount, \fBMount\fP newMount)\fC [static]\fP"

.PP
Removes mountable from the list of objects attached to the current mount, and adds to the list of the new mount\&. 
.PP
\fBParameters\fP
.RS 4
\fInewMount\fP 
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBMount\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Mount\&.DismountAll ()"

.PP
Definition at line \fB62\fP of file \fBMount\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.Mount\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB40\fP of file \fBMount\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Mount\&.OnPreNetDestroy (\fBNetObject\fP rootNetObj)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreNetDestroy\fP\&.
.PP
Definition at line \fB51\fP of file \fBMount\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Mount\&.OnPreQuit ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreQuit\fP\&.
.PP
Definition at line \fB46\fP of file \fBMount\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.Mount\&.componentIndex"

.PP
Definition at line \fB24\fP of file \fBMount\&.cs\fP\&.
.SS "List<\fBIMountable\fP> Photon\&.Pun\&.Simple\&.Mount\&.mountedObjs = new List<\fBIMountable\fP>()"

.PP
Definition at line \fB27\fP of file \fBMount\&.cs\fP\&.
.SS "\fBMountsManager\fP Photon\&.Pun\&.Simple\&.Mount\&.mountsLookup"

.PP
Definition at line \fB30\fP of file \fBMount\&.cs\fP\&.
.SS "\fBMountSelector\fP Photon\&.Pun\&.Simple\&.Mount\&.mountType = new \fBMountSelector\fP(1)"

.PP
Definition at line \fB22\fP of file \fBMount\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Simple\&.Mount\&.ROOT_MOUNT_NAME = 'Root'\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBMount\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
