.TH "Photon.Pun.UtilityScripts.PhotonTeamsManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PhotonTeamsManager \- Implements teams in a room/game with help of player properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP, and \fBPhoton\&.Realtime\&.IInRoomCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBTryGetTeamByCode\fP (byte code, out \fBPhotonTeam\fP team)"
.br
.RI "Find a \fBPhotonTeam\fP using a team code\&. "
.ti -1c
.RI "bool \fBTryGetTeamByName\fP (string teamName, out \fBPhotonTeam\fP team)"
.br
.RI "Find a \fBPhotonTeam\fP using a team name\&. "
.ti -1c
.RI "\fBPhotonTeam\fP[] \fBGetAvailableTeams\fP ()"
.br
.RI "Gets all teams available\&. "
.ti -1c
.RI "bool \fBTryGetTeamMembers\fP (byte code, out \fBPlayer\fP[] members)"
.br
.RI "Gets all players joined to a team using a team code\&. "
.ti -1c
.RI "bool \fBTryGetTeamMembers\fP (string teamName, out \fBPlayer\fP[] members)"
.br
.RI "Gets all players joined to a team using a team name\&. "
.ti -1c
.RI "bool \fBTryGetTeamMembers\fP (\fBPhotonTeam\fP team, out \fBPlayer\fP[] members)"
.br
.RI "Gets all players joined to a team\&. "
.ti -1c
.RI "bool \fBTryGetTeamMatesOfPlayer\fP (\fBPlayer\fP player, out \fBPlayer\fP[] teamMates)"
.br
.RI "Gets all team mates of a player\&. "
.ti -1c
.RI "int \fBGetTeamMembersCount\fP (byte code)"
.br
.RI "Gets the number of players in a team by team code\&. "
.ti -1c
.RI "int \fBGetTeamMembersCount\fP (string name)"
.br
.RI "Gets the number of players in a team by team name\&. "
.ti -1c
.RI "int \fBGetTeamMembersCount\fP (\fBPhotonTeam\fP team)"
.br
.RI "Gets the number of players in a team\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBTeamPlayerProp\fP = '_pt'"
.br
.RI "Defines the player custom property name to use for team affinity of 'this' player\&."
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPhotonTeamsManager\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "static Action< \fBPlayer\fP, \fBPhotonTeam\fP > \fBPlayerJoinedTeam\fP"
.br
.ti -1c
.RI "static Action< \fBPlayer\fP, \fBPhotonTeam\fP > \fBPlayerLeftTeam\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implements teams in a room/game with help of player properties\&. 

Access them by Player\&.GetTeam extension\&. 
.PP
Teams are defined by enum Team\&. Change this to get more / different teams\&. There are no rules when / if you can join a team\&. You could add this in JoinTeam or something\&. 
.PP
Definition at line \fB44\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPhotonTeam\fP[] Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.GetAvailableTeams ()"

.PP
Gets all teams available\&. 
.PP
\fBReturns\fP
.RS 4
Returns all teams available\&.
.RE
.PP

.PP
Definition at line \fB302\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.GetTeamMembersCount (byte code)"

.PP
Gets the number of players in a team by team code\&. 
.PP
\fBParameters\fP
.RS 4
\fIcode\fP Unique code of the team
.RE
.PP
\fBReturns\fP
.RS 4
Number of players joined to the team\&.
.RE
.PP

.PP
Definition at line \fB416\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.GetTeamMembersCount (\fBPhotonTeam\fP team)"

.PP
Gets the number of players in a team\&. 
.PP
\fBParameters\fP
.RS 4
\fIteam\fP The team you want to know the size of
.RE
.PP
\fBReturns\fP
.RS 4
Number of players joined to the team\&.
.RE
.PP

.PP
Definition at line \fB446\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.GetTeamMembersCount (string name)"

.PP
Gets the number of players in a team by team name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP Unique name of the team
.RE
.PP
\fBReturns\fP
.RS 4
Number of players joined to the team\&.
.RE
.PP

.PP
Definition at line \fB431\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamByCode (byte code, out \fBPhotonTeam\fP team)"

.PP
Find a \fBPhotonTeam\fP using a team code\&. 
.PP
\fBParameters\fP
.RS 4
\fIcode\fP The team code\&.
.br
\fIteam\fP The team to be assigned if found\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB282\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamByName (string teamName, out \fBPhotonTeam\fP team)"

.PP
Find a \fBPhotonTeam\fP using a team name\&. 
.PP
\fBParameters\fP
.RS 4
\fIteamName\fP The team name\&.
.br
\fIteam\fP The team to be assigned if found\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB293\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamMatesOfPlayer (\fBPlayer\fP player, out \fBPlayer\fP[] teamMates)"

.PP
Gets all team mates of a player\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player whose team mates will be searched\&.
.br
\fIteamMates\fP The array of players to be filled\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB374\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamMembers (byte code, out \fBPlayer\fP[] members)"

.PP
Gets all players joined to a team using a team code\&. 
.PP
\fBParameters\fP
.RS 4
\fIcode\fP The code of the team\&.
.br
\fImembers\fP The array of players to be filled\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB317\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamMembers (\fBPhotonTeam\fP team, out \fBPlayer\fP[] members)"

.PP
Gets all players joined to a team\&. 
.PP
\fBParameters\fP
.RS 4
\fIteam\fP The team which will be used to find players\&.
.br
\fImembers\fP The array of players to be filled\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB358\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TryGetTeamMembers (string teamName, out \fBPlayer\fP[] members)"

.PP
Gets all players joined to a team using a team name\&. 
.PP
\fBParameters\fP
.RS 4
\fIteamName\fP The name of the team\&.
.br
\fImembers\fP The array of players to be filled\&.
.RE
.PP
\fBReturns\fP
.RS 4
If successful or not\&.
.RE
.PP

.PP
Definition at line \fB341\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.TeamPlayerProp = '_pt'\fC [static]\fP"

.PP
Defines the player custom property name to use for team affinity of 'this' player\&.
.PP
Definition at line \fB67\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBPhotonTeamsManager\fP Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB73\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<\fBPlayer\fP, \fBPhotonTeam\fP> Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.PlayerJoinedTeam\fC [static]\fP"

.PP
Definition at line \fB69\fP of file \fBPhotonTeamsManager\&.cs\fP\&.
.SS "Action<\fBPlayer\fP, \fBPhotonTeam\fP> Photon\&.Pun\&.UtilityScripts\&.PhotonTeamsManager\&.PlayerLeftTeam\fC [static]\fP"

.PP
Definition at line \fB70\fP of file \fBPhotonTeamsManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
