.TH "Photon.Pun.Demo.SlotRacer.Utils.Bezier" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.Utils.Bezier
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Vector3 \fBGetPoint\fP (Vector3 p0, Vector3 p1, Vector3 p2, float t)"
.br
.ti -1c
.RI "static Vector3 \fBGetFirstDerivative\fP (Vector3 p0, Vector3 p1, Vector3 p2, float t)"
.br
.ti -1c
.RI "static Vector3 \fBGetPoint\fP (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)"
.br
.ti -1c
.RI "static Vector3 \fBGetFirstDerivative\fP (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBBezier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.Bezier\&.GetFirstDerivative (Vector3 p0, Vector3 p1, Vector3 p2, float t)\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBBezier\&.cs\fP\&.
.SS "static Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.Bezier\&.GetFirstDerivative (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)\fC [static]\fP"

.PP
Definition at line \fB46\fP of file \fBBezier\&.cs\fP\&.
.SS "static Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.Bezier\&.GetPoint (Vector3 p0, Vector3 p1, Vector3 p2, float t)\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBBezier\&.cs\fP\&.
.SS "static Vector3 Photon\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.Bezier\&.GetPoint (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 p3, float t)\fC [static]\fP"

.PP
Definition at line \fB35\fP of file \fBBezier\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
