.TH "Photon.Pun.Simple.Internal.CallbackUtilities" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Internal.CallbackUtilities
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBRegisterInterface< T >\fP (List< T > callbackList, object c, bool register)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBCallbackUtilities\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Pun\&.Simple\&.Internal\&.CallbackUtilities\&.RegisterInterface< T > (List< T > callbackList, object c, bool register)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIclass\fP
.PP
Definition at line \fB12\fP of file \fBCallbackUtilities\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
