.TH "Photon.Pun.Demo.SlotRacer.PlayerControl" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.PlayerControl \- Player control\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject[] \fBCarPrefabs\fP"
.br
.RI "The car prefabs to pick depending on the grid position\&. "
.ti -1c
.RI "float \fBMaximumSpeed\fP = 20"
.br
.RI "The maximum speed\&. "
.ti -1c
.RI "float \fBDrag\fP = 5"
.br
.RI "The drag when user is not accelerating "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Player control\&. 

Interface the User Inputs and PUN Handle the Car instance 
.PP
Definition at line \fB26\fP of file \fBPlayerControl\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject [] Photon\&.Pun\&.Demo\&.SlotRacer\&.PlayerControl\&.CarPrefabs"

.PP
The car prefabs to pick depending on the grid position\&. 
.PP
Definition at line \fB31\fP of file \fBPlayerControl\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.PlayerControl\&.Drag = 5"

.PP
The drag when user is not accelerating 
.PP
Definition at line \fB41\fP of file \fBPlayerControl\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Demo\&.SlotRacer\&.PlayerControl\&.MaximumSpeed = 20"

.PP
The maximum speed\&. Maximum speed is reached with a 1 unit per seconds acceleration 
.PP
Definition at line \fB36\fP of file \fBPlayerControl\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
