.TH "Photon.Pun.Simple.VitalDefinition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.VitalDefinition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddIOnVitalChange\fP (\fBIOnVitalValueChange\fP cb)"
.br
.ti -1c
.RI "void \fBRemoveIOnVitalChange\fP (\fBIOnVitalValueChange\fP cb)"
.br
.ti -1c
.RI "\fBVitalDefinition\fP (double fullValue, uint maxValue, double \fBstartValue\fP, double absorbtion, float regenDelay, double regenRate, float decayDelay, double decayRate, string name)"
.br
.ti -1c
.RI "void \fBInitialize\fP (float tickDuration)"
.br
.ti -1c
.RI "void \fBSetTickInterval\fP (float tickInterval)"
.br
.ti -1c
.RI "\fBVitalData\fP \fBGetDefaultData\fP ()"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBSerialize\fP (\fBVitalData\fP vitalData, \fBVitalData\fP prevVitalData, byte[] buffer, ref int bitposition, bool keyframe=true)"
.br
.ti -1c
.RI "\fBVitalData\fP \fBDeserialize\fP (byte[] buffer, ref int bitposition, bool keyframe=true)"
.br
.ti -1c
.RI "\fBVitalData\fP \fBExtrapolate\fP (\fBVitalData\fP prev)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBIOnVitalValueChange\fP > \fBiOnVitalChange\fP = new List<\fBIOnVitalValueChange\fP>()"
.br
.ti -1c
.RI "double \fBstartValue\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVitalNameType\fP \fBVitalName\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBFullValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBMaxValue\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBAbsorbtion\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBDecayDelayInTicks\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBRegenDelayInTicks\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBDecayPerTick\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBRegenPerTick\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBVitalDefinition\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.VitalDefinition\&.VitalDefinition (double fullValue, uint maxValue, double startValue, double absorbtion, float regenDelay, double regenRate, float decayDelay, double decayRate, string name)"

.PP
Definition at line \fB102\fP of file \fBVitalDefinition\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.VitalDefinition\&.AddIOnVitalChange (\fBIOnVitalValueChange\fP cb)"

.PP
Definition at line \fB26\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "\fBVitalData\fP Photon\&.Pun\&.Simple\&.VitalDefinition\&.Deserialize (byte[] buffer, ref int bitposition, bool keyframe = \fCtrue\fP)"

.PP
Definition at line \fB186\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "\fBVitalData\fP Photon\&.Pun\&.Simple\&.VitalDefinition\&.Extrapolate (\fBVitalData\fP prev)"

.PP
Definition at line \fB198\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "\fBVitalData\fP Photon\&.Pun\&.Simple\&.VitalDefinition\&.GetDefaultData ()"

.PP
Definition at line \fB133\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.VitalDefinition\&.Initialize (float tickDuration)"

.PP
Definition at line \fB115\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.VitalDefinition\&.RemoveIOnVitalChange (\fBIOnVitalValueChange\fP cb)"

.PP
Definition at line \fB30\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.VitalDefinition\&.Serialize (\fBVitalData\fP vitalData, \fBVitalData\fP prevVitalData, byte[] buffer, ref int bitposition, bool keyframe = \fCtrue\fP)"
We always write the ticks until, even if we are marking this as having no content\&.
.PP
Definition at line \fB138\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.VitalDefinition\&.SetTickInterval (float tickInterval)"

.PP
Definition at line \fB120\fP of file \fBVitalDefinition\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBIOnVitalValueChange\fP> Photon\&.Pun\&.Simple\&.VitalDefinition\&.iOnVitalChange = new List<\fBIOnVitalValueChange\fP>()"

.PP
Definition at line \fB25\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.startValue"

.PP
Definition at line \fB52\fP of file \fBVitalDefinition\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.Absorbtion\fC [get]\fP"

.PP
Definition at line \fB70\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.VitalDefinition\&.DecayDelayInTicks\fC [get]\fP"

.PP
Definition at line \fB75\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.DecayPerTick\fC [get]\fP"

.PP
Definition at line \fB80\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.FullValue\fC [get]\fP"

.PP
Definition at line \fB46\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.MaxValue\fC [get]\fP"

.PP
Definition at line \fB50\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.VitalDefinition\&.RegenDelayInTicks\fC [get]\fP"

.PP
Definition at line \fB77\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.VitalDefinition\&.RegenPerTick\fC [get]\fP"

.PP
Definition at line \fB82\fP of file \fBVitalDefinition\&.cs\fP\&.
.SS "\fBVitalNameType\fP Photon\&.Pun\&.Simple\&.VitalDefinition\&.VitalName\fC [get]\fP"

.PP
Definition at line \fB40\fP of file \fBVitalDefinition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
