.TH "Photon.Compression.XYZSwitchMaskAttribute" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.XYZSwitchMaskAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits PropertyAttribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXYZSwitchMaskAttribute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBIncludedAxisEnum\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Compression\&.XYZSwitchMaskAttribute\&.XYZSwitchMaskAttribute ()"

.PP
Definition at line \fB85\fP of file \fBIncludedAxisEnum\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
