.TH "Photon.Pun.Demo.Asteroids.AsteroidsGame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Asteroids.AsteroidsGame
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Color \fBGetColor\fP (int colorChoice)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const float \fBASTEROIDS_MIN_SPAWN_TIME\fP = 5\&.0f"
.br
.ti -1c
.RI "const float \fBASTEROIDS_MAX_SPAWN_TIME\fP = 10\&.0f"
.br
.ti -1c
.RI "const float \fBPLAYER_RESPAWN_TIME\fP = 4\&.0f"
.br
.ti -1c
.RI "const int \fBPLAYER_MAX_LIVES\fP = 3"
.br
.ti -1c
.RI "const string \fBPLAYER_LIVES\fP = 'PlayerLives'"
.br
.ti -1c
.RI "const string \fBPLAYER_READY\fP = 'IsPlayerReady'"
.br
.ti -1c
.RI "const string \fBPLAYER_LOADED_LEVEL\fP = 'PlayerLoadedLevel'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static Color Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.GetColor (int colorChoice)\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const float Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.ASTEROIDS_MAX_SPAWN_TIME = 10\&.0f\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const float Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.ASTEROIDS_MIN_SPAWN_TIME = 5\&.0f\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.PLAYER_LIVES = 'PlayerLives'\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.PLAYER_LOADED_LEVEL = 'PlayerLoadedLevel'\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const int Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.PLAYER_MAX_LIVES = 3\fC [static]\fP"

.PP
Definition at line \fB12\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.PLAYER_READY = 'IsPlayerReady'\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBAsteroidsGame\&.cs\fP\&.
.SS "const float Photon\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGame\&.PLAYER_RESPAWN_TIME = 4\&.0f\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBAsteroidsGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
