.TH "Photon.Pun.Simple.IOnPreSimulate" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnPreSimulate \- Callback Interface for \fBOnPreSimulate()\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP, \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.HitscanComponent\fP, \fBPhoton\&.Pun\&.Simple\&.MountSwitcher\fP, \fBPhoton\&.Pun\&.Simple\&.MountThrow\fP, \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAdditiveMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase< TTRSDef, TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, and \fBemotitron\&.TestPackObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Callback Interface for \fBOnPreSimulate()\fP\&. 

Called prior to all normal FixedUpdate() calls in MonoBehaviours\&. 
.PP
Definition at line \fB42\fP of file \fBNetMasterInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnPreSimulate\&.OnPreSimulate (int frameId, int subFrameId)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.NetObject\fP, \fBPhoton\&.Pun\&.Simple\&.ContactProjectile\fP, \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP, \fBPhoton\&.Pun\&.Simple\&.MountThrow\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAdditiveMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncMoverBase< TTRSDef, TFrame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.AutoMountHitscan\fP, \fBPhoton\&.Pun\&.Simple\&.MountSwitcher\fP, \fBPhoton\&.Pun\&.Simple\&.HitscanComponent\fP, and \fBemotitron\&.TestPackObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
