.TH "Photon.Pun.Demo.Cockpit.Forms.UserIdUiForm" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.Forms.UserIdUiForm \- User Id UI form\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnSubmitEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBEndEditOnEnter\fP ()"
.br
.ti -1c
.RI "void \fBSubmitForm\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBidInput\fP"
.br
.ti -1c
.RI "\fBOnSubmitEvent\fP \fBOnSubmit\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBUserIdPlayerPref\fP = 'PunUserId'"
.br
.in -1c
.SH "Detailed Description"
.PP 
User Id UI form\&. 


.PP
Definition at line \fB17\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.EndEditOnEnter ()"

.PP
Definition at line \fB40\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.Start ()"

.PP
Definition at line \fB28\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.SubmitForm ()"

.PP
Definition at line \fB48\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.idInput"

.PP
Definition at line \fB21\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SS "\fBOnSubmitEvent\fP Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.OnSubmit"

.PP
Definition at line \fB26\fP of file \fBUserIdUiForm\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.UserIdUiForm\&.UserIdPlayerPref = 'PunUserId'\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBUserIdUiForm\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
