.TH "Photon.Pun.Simple.Internal.ParameterSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Internal.ParameterSettings \- Settings for a single Animator parameter\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameterSettings\fP (int \fBhash\fP, \fBParameterDefaults\fP defs, ref int paramCount, AnimatorControllerParameterType \fBparamType\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< string > \fBRebuildParamSettings\fP (Animator a, ref \fBParameterSettings\fP[] paraSettings, ref int paramCount, \fBParameterDefaults\fP defs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "AnimatorControllerParameterType \fBparamType\fP"
.br
.ti -1c
.RI "bool \fBinclude\fP"
.br
.ti -1c
.RI "\fBParameterInterpolation\fP \fBinterpolate\fP"
.br
.ti -1c
.RI "\fBParameterExtrapolation\fP \fBextrapolate\fP"
.br
.ti -1c
.RI "\fBSmartVar\fP \fBdefaultValue\fP"
.br
.ti -1c
.RI "\fBLiteFloatCrusher\fP \fBfcrusher\fP"
.br
.RI "TODO: FieldOffset these\&. "
.ti -1c
.RI "\fBLiteIntCrusher\fP \fBicrusher\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Settings for a single Animator parameter\&. 


.PP
Definition at line \fB19\fP of file \fBParameterSettings\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.ParameterSettings (int hash, \fBParameterDefaults\fP defs, ref int paramCount, AnimatorControllerParameterType paramType)"

.PP
Definition at line \fB34\fP of file \fBParameterSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static List< string > Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.RebuildParamSettings (Animator a, ref \fBParameterSettings\fP[] paraSettings, ref int paramCount, \fBParameterDefaults\fP defs)\fC [static]\fP"
remap existing switches for this hash, or if not found make a new one
.PP
Definition at line \fB81\fP of file \fBParameterSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSmartVar\fP Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.defaultValue"

.PP
Definition at line \fB27\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "\fBParameterExtrapolation\fP Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.extrapolate"

.PP
Definition at line \fB26\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "\fBLiteFloatCrusher\fP Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.fcrusher"

.PP
TODO: FieldOffset these\&. 
.PP
Definition at line \fB30\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.hash"

.PP
Definition at line \fB22\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "\fBLiteIntCrusher\fP Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.icrusher"

.PP
Definition at line \fB31\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.include"

.PP
Definition at line \fB24\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "\fBParameterInterpolation\fP Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.interpolate"

.PP
Definition at line \fB25\fP of file \fBParameterSettings\&.cs\fP\&.
.SS "AnimatorControllerParameterType Photon\&.Pun\&.Simple\&.Internal\&.ParameterSettings\&.paramType"

.PP
Definition at line \fB23\fP of file \fBParameterSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
