.TH "Photon.Pun.Simple.IApplyOrder" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IApplyOrder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncAnimator\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncContact\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncOwner\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncShootBase\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncSpawnTimer\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncState\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncTransform\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.SyncObject< SyncVitals\&.Frame >\fP, \fBPhoton\&.Pun\&.Simple\&.IAdjustableApplyOrder\fP, \fBPhoton\&.Pun\&.Simple\&.OnStateChangeKinematic\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncObject< TFrame >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBApplyOrder\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBSyncObjInterfaces\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.IApplyOrder\&.ApplyOrder\fC [get]\fP"

.PP
Definition at line \fB21\fP of file \fBSyncObjInterfaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
