.TH "Photon.Pun.Demo.PunBasics.CameraWork" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.CameraWork \- Camera work\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnStartFollowing\fP ()"
.br
.RI "Raises the start following event\&. "
.in -1c
.SH "Detailed Description"
.PP 
Camera work\&. 

Follow a target 
.PP
Definition at line \fB18\fP of file \fBCameraWork\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.PunBasics\&.CameraWork\&.OnStartFollowing ()"

.PP
Raises the start following event\&. Use this when you don't know at the time of editing what to follow, typically instances managed by the photon network\&. 
.PP
Definition at line \fB92\fP of file \fBCameraWork\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
