.TH "Photon.Pun.Simple.IOnCaptureState" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnCaptureState
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCaptureCurrentState\fP (int frameId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB80\fP of file \fBSyncObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnCaptureState\&.OnCaptureCurrentState (int frameId)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
