.TH "Photon.Pun.Demo.PunBasics.PlayerAnimatorManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.PunBasics.PlayerAnimatorManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBPlayerAnimatorManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
