.TH "Photon.Realtime.IConnectionCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.IConnectionCallbacks \- Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover: Connection and Regions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, and \fBPhoton\&.Realtime\&.SupportLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnConnected\fP ()"
.br
.RI "Called to signal that the 'low level connection' got established but before the client can call operation on the server\&. "
.ti -1c
.RI "void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. "
.ti -1c
.RI "void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "void \fBOnRegionListReceived\fP (\fBRegionHandler\fP regionHandler)"
.br
.RI "Called when the Name Server provided a list of regions for your title\&. "
.ti -1c
.RI "void \fBOnCustomAuthenticationResponse\fP (Dictionary< string, object > data)"
.br
.RI "Called when your Custom Authentication service responds with additional data\&. "
.ti -1c
.RI "void \fBOnCustomAuthenticationFailed\fP (string debugMessage)"
.br
.RI "Called when the custom authentication failed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Collection of 'organizational' callbacks for the \fBRealtime\fP Api to cover: Connection and Regions\&. 

Classes that implement this interface must be registered to get callbacks for various situations\&.
.PP
To register for callbacks, call \fBLoadBalancingClient\&.AddCallbackTarget\fP and pass the class implementing this interface To stop getting callbacks, call \fBLoadBalancingClient\&.RemoveCallbackTarget\fP and pass the class implementing this interface
.PP
Definition at line \fB3603\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnConnected ()"

.PP
Called to signal that the 'low level connection' got established but before the client can call operation on the server\&. After the (low level transport) connection is established, the client will automatically send the Authentication operation, which needs to get a response before the client can call other operations\&.
.PP
Your logic should wait for either: OnRegionListReceived or OnConnectedToMaster\&.
.PP
This callback is useful to detect if the server can be reached at all (technically)\&. Most often, it's enough to implement \fBOnDisconnected(DisconnectCause cause)\fP and check for the cause\&.
.PP
This is not called for transitions from the masterserver to game servers\&. 
.PP
Implemented in \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, and \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP\&.
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnConnectedToMaster ()"

.PP
Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. The list of available rooms won't become available unless you join a lobby via \fBLoadBalancingClient\&.OpJoinLobby\fP\&. You can join rooms and create them even without being in a lobby\&. The default lobby is used in that case\&. 
.PP
Implemented in \fBLauncher\fP, \fBLauncher_old\fP, \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.LobbyMainPanel\fP, \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.Launcher\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP, and \fBPhoton\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\fP\&.
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnCustomAuthenticationFailed (string debugMessage)"

.PP
Called when the custom authentication failed\&. Followed by disconnect! 
.PP
Custom Authentication can fail due to user-input, bad tokens/secrets\&. If authentication is successful, this method is not called\&. Implement OnJoinedLobby() or \fBOnConnectedToMaster()\fP (as usual)\&.
.PP
During development of a game, it might also fail due to wrong configuration on the server side\&. In those cases, logging the debugMessage is very important\&.
.PP
Unless you setup a custom authentication service for your app (in the \fCDashboard\fP), this won't be called! 
.PP
\fBParameters\fP
.RS 4
\fIdebugMessage\fP Contains a debug message why authentication failed\&. This has to be fixed during development\&.
.RE
.PP

.PP
Implemented in \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, and \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnCustomAuthenticationResponse (Dictionary< string, object > data)"

.PP
Called when your Custom Authentication service responds with additional data\&. Custom Authentication services can include some custom data in their response\&. When present, that data is made available in this callback as Dictionary\&. While the keys of your data have to be strings, the values can be either string or a number (in Json)\&. You need to make extra sure, that the value type is the one you expect\&. Numbers become (currently) int64\&.
.PP
Example: void OnCustomAuthenticationResponse(Dictionary<string, object> data) { \&.\&.\&. } 
.PP
https://doc\&.photonengine\&.com/en-us/realtime/current/reference/custom-authentication 
.PP
Implemented in \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, and \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnDisconnected (\fBDisconnectCause\fP cause)"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. It could be a failure or an explicit disconnect call 
.PP
The reason for this disconnect is provided as DisconnectCause\&. 
.PP
Implemented in \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, \fBPhoton\&.Pun\&.Demo\&.Asteroids\&.AsteroidsGameManager\fP, \fBPhoton\&.Pun\&.Demo\&.PunBasics\&.Launcher\fP, \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP, and \fBPhoton\&.Pun\&.UtilityScripts\&.ConnectAndJoinRandom\fP\&.
.SS "void Photon\&.Realtime\&.IConnectionCallbacks\&.OnRegionListReceived (\fBRegionHandler\fP regionHandler)"

.PP
Called when the Name Server provided a list of regions for your title\&. Check the \fBRegionHandler\fP class description, to make use of the provided values\&.
.PP
\fBParameters\fP
.RS 4
\fIregionHandler\fP The currently used \fBRegionHandler\fP\&.
.RE
.PP

.PP
Implemented in \fBPhoton\&.Realtime\&.ConnectionCallbacksContainer\fP, \fBPhoton\&.Realtime\&.SupportLogger\fP, \fBPhoton\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\fP, \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, and \fBPhoton\&.Pun\&.Demo\&.Cockpit\&.PunCockpit\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
