.TH "Photon.Pun.Demo.Cockpit.GameVersionProperty" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.GameVersionProperty \- \fBPhotonNetwork\&.GameVersion\fP UI property\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPhotonNetwork\&.GameVersion\fP UI property\&. 


.PP
Definition at line \fB16\fP of file \fBGameVersionProperty\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.GameVersionProperty\&.Text"

.PP
Definition at line \fB18\fP of file \fBGameVersionProperty\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
