.TH "Photon.Pun.Simple.ContactManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactManager \- Companion component to \fBIContactSystem\fP components\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "\fBIContactSystem\fP \fBGetContacting\fP (int index)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBIContactSystem\fP > \fBcontactSystems\fP = new List<\fBIContactSystem\fP>(0)"
.br
.ti -1c
.RI "List< \fBIContactTrigger\fP > \fBcontactTriggers\fP = new List<\fBIContactTrigger\fP>(0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Companion component to \fBIContactSystem\fP components\&. 

This component indexes all \fBIContactSystem\fP components so their references can be serialized efficiently\&. 
.PP
Definition at line \fB15\fP of file \fBContactManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.ContactManager\&.Awake ()"

.PP
Definition at line \fB21\fP of file \fBContactManager\&.cs\fP\&.
.SS "\fBIContactSystem\fP Photon\&.Pun\&.Simple\&.ContactManager\&.GetContacting (int index)"

.PP
Definition at line \fB35\fP of file \fBContactManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBIContactSystem\fP> Photon\&.Pun\&.Simple\&.ContactManager\&.contactSystems = new List<\fBIContactSystem\fP>(0)"

.PP
Definition at line \fB17\fP of file \fBContactManager\&.cs\fP\&.
.SS "List<\fBIContactTrigger\fP> Photon\&.Pun\&.Simple\&.ContactManager\&.contactTriggers = new List<\fBIContactTrigger\fP>(0)"

.PP
Definition at line \fB18\fP of file \fBContactManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
