.TH "Photon.Pun.Simple.IFlagTeleport" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IFlagTeleport
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFlagTeleport\fP ()"
.br
.RI "Call this BEFORE changing the parent and/or applying position and rotation changes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIOnTeleport\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IFlagTeleport\&.FlagTeleport ()"

.PP
Call this BEFORE changing the parent and/or applying position and rotation changes\&. This will notify the \fBSyncTransform\fP that a teleport will be happening, and \fBSyncTransform\fP will record the pre-teleport state and send both the pre and post teleport state in the next send\&. 
.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
