.TH "Photon.Pun.Simple.IVitalsConsumable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IVitalsConsumable
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IVitalsContactReactor\fP, and \fBPhoton\&.Pun\&.Simple\&.IConsumable\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBIVitalsContactReactor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
