.TH "Photon.Pun.UtilityScripts.PunTeams" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PunTeams \- Implements teams in a room/game with help of player properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTeam\fP : byte { \fBnone\fP, \fBred\fP, \fBblue\fP }"
.br
.RI "Enum defining the teams available\&. First team should be neutral (it's the default value any field of this enum gets)\&."
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "override void \fBOnJoinedRoom\fP ()"
.br
.RI "Needed to update the team lists when joining a room\&. "
.ti -1c
.RI "override void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. "
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"
.br
.RI "Refreshes the team lists\&. "
.ti -1c
.RI "override void \fBOnPlayerLeftRoom\fP (\fBPlayer\fP otherPlayer)"
.br
.RI "Called when a remote player left the room or became inactive\&. "
.ti -1c
.RI "override void \fBOnPlayerEnteredRoom\fP (\fBPlayer\fP newPlayer)"
.br
.RI "Called when a remote player entered the room\&. "
.ti -1c
.RI "void \fBUpdateTeams\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< \fBTeam\fP, List< \fBPlayer\fP > > \fBPlayersPerTeam\fP"
.br
.RI "The main list of teams with their player-lists\&. "
.ti -1c
.RI "const string \fBTeamPlayerProp\fP = 'team'"
.br
.RI "Defines the player custom property name to use for team affinity of 'this' player\&."
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implements teams in a room/game with help of player properties\&. 

Access them by Player\&.GetTeam extension\&. 
.PP
Teams are defined by enum Team\&. Change this to get more / different teams\&. There are no rules when / if you can join a team\&. You could add this in JoinTeam or something\&. 
.PP
Definition at line \fB35\fP of file \fBPunTeams\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.UtilityScripts\&.PunTeams\&.Team\fP : byte"

.PP
Enum defining the teams available\&. First team should be neutral (it's the default value any field of this enum gets)\&.
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInone \fP\fP
.TP
\fB\fIred \fP\fP
.TP
\fB\fIblue \fP\fP
.PP
Definition at line \fB39\fP of file \fBPunTeams\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnDisable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB63\fP of file \fBPunTeams\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnJoinedRoom ()\fC [virtual]\fP"

.PP
Needed to update the team lists when joining a room\&. Called by PUN\&. See enum \fBMonoBehaviourPunCallbacks\fP for an explanation\&.
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB71\fP of file \fBPunTeams\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnLeftRoom ()\fC [virtual]\fP"

.PP
Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. When leaving a room, the LoadBalancingClient will disconnect the Game Server and connect to the Master Server\&. This wraps up multiple internal actions\&.
.PP
Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB77\fP of file \fBPunTeams\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnPlayerEnteredRoom (\fBPlayer\fP newPlayer)\fC [virtual]\fP"

.PP
Called when a remote player entered the room\&. This Player is already added to the playerlist\&. 
.PP
If your game starts with a certain number of players, this callback can be useful to check the Room\&.playerCount and find out if you can start\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB94\fP of file \fBPunTeams\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnPlayerLeftRoom (\fBPlayer\fP otherPlayer)\fC [virtual]\fP"

.PP
Called when a remote player left the room or became inactive\&. Check otherPlayer\&.IsInactive\&. 
.PP
If another player leaves the room or if the server detects a lost connection, this callback will be used to notify your game logic\&.
.PP
Depending on the room's setup, players may become inactive, which means they may return and retake their spot in the room\&. In such cases, the Player stays in the \fBRoom\&.Players\fP dictionary\&.
.PP
If the player is not just inactive, it gets removed from the \fBRoom\&.Players\fP dictionary, before the callback is called\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB89\fP of file \fBPunTeams\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)\fC [virtual]\fP"

.PP
Refreshes the team lists\&. It could be a non-team related property change, too\&.
.PP
Called by PUN\&. See enum \fBMonoBehaviourPunCallbacks\fP for an explanation\&.
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB84\fP of file \fBPunTeams\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.Start ()"

.PP
Definition at line \fB53\fP of file \fBPunTeams\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.UpdateTeams ()"

.PP
Definition at line \fB102\fP of file \fBPunTeams\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<\fBTeam\fP, List<\fBPlayer\fP> > Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.PlayersPerTeam\fC [static]\fP"

.PP
The main list of teams with their player-lists\&. Automatically kept up to date\&.
.PP
Note that this is static\&. Can be accessed by PunTeam\&.PlayersPerTeam\&. You should not modify this\&.
.PP
Definition at line \fB44\fP of file \fBPunTeams\&.cs\fP\&.
.SS "const string Photon\&.Pun\&.UtilityScripts\&.PunTeams\&.TeamPlayerProp = 'team'\fC [static]\fP"

.PP
Defines the player custom property name to use for team affinity of 'this' player\&.
.PP
Definition at line \fB48\fP of file \fBPunTeams\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
