.TH "Photon.Pun.UtilityScripts" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBButtonInsideScrollList\fP"
.br
.RI "Button inside scroll list will stop scrolling ability of scrollRect container, so that when pressing down on a button and draggin up and down will not affect scrolling\&. "
.ti -1c
.RI "class \fBByteComparer\fP"
.br
.ti -1c
.RI "class \fBCellTree\fP"
.br
.RI "Represents the tree accessible from its root node\&. "
.ti -1c
.RI "class \fBCellTreeNode\fP"
.br
.RI "Represents a single node of the tree\&. "
.ti -1c
.RI "class \fBConnectAndJoinRandom\fP"
.br
.RI "\fBSimple\fP component to call ConnectUsingSettings and to get into a PUN room easily\&. "
.ti -1c
.RI "class \fBCopyComponent\fP"
.br
.ti -1c
.RI "class \fBCountdownTimer\fP"
.br
.RI "This is a basic, network-synced \fBCountdownTimer\fP based on properties\&. "
.ti -1c
.RI "class \fBCullArea\fP"
.br
.RI "Represents the cull area used for network culling\&. "
.ti -1c
.RI "class \fBCullAreaEditor\fP"
.br
.ti -1c
.RI "class \fBCullingHandler\fP"
.br
.RI "Handles the network culling\&. "
.ti -1c
.RI "class \fBEventSystemSpawner\fP"
.br
.RI "Event system spawner\&. "
.ti -1c
.RI "class \fBGraphicToggleIsOnTransition\fP"
.br
.RI "Use this on toggles texts to have some color transition on the text depending on the isOn State\&. "
.ti -1c
.RI "interface \fBIPunTurnManagerCallbacks\fP"
.br
.ti -1c
.RI "class \fBMoveByKeys\fP"
.br
.RI "Very basic component to move a GameObject by WASD and Space\&. "
.ti -1c
.RI "class \fBOnClickDestroy\fP"
.br
.RI "Destroys the networked GameObject either by \fBPhotonNetwork\&.Destroy\fP or by sending an RPC which calls Object\&.Destroy()\&. "
.ti -1c
.RI "class \fBOnClickInstantiate\fP"
.br
.RI "Instantiates a networked GameObject on click\&. "
.ti -1c
.RI "class \fBOnClickRpc\fP"
.br
.RI "This component will instantiate a network GameObject when in a room and the user click on that component's GameObject\&. "
.ti -1c
.RI "class \fBOnEscapeQuit\fP"
.br
.RI "This component will quit the application when escape key is pressed "
.ti -1c
.RI "class \fBOnJoinedInstantiate\fP"
.br
.RI "This component will instantiate a network GameObject when a room is joined "
.ti -1c
.RI "class \fBOnPointerOverTooltip\fP"
.br
.RI "Set focus to a given photonView when pointed is over "
.ti -1c
.RI "class \fBOnStartDelete\fP"
.br
.RI "This component will destroy the GameObject it is attached to (in Start())\&."
.ti -1c
.RI "class \fBPhotonLagSimulationGui\fP"
.br
.RI "This MonoBehaviour is a basic GUI for the \fBPhoton\fP client's network-simulation feature\&. "
.ti -1c
.RI "class \fBPhotonStatsGui\fP"
.br
.RI "Basic GUI to show traffic and health statistics of the connection to \fBPhoton\fP, toggled by shift+tab\&. "
.ti -1c
.RI "class \fBPhotonTeam\fP"
.br
.ti -1c
.RI "class \fBPhotonTeamExtensions\fP"
.br
.RI "Extension methods for the Player class that make use of \fBPhotonTeamsManager\fP\&."
.ti -1c
.RI "class \fBPhotonTeamsManager\fP"
.br
.RI "Implements teams in a room/game with help of player properties\&. "
.ti -1c
.RI "class \fBPhotonTeamsManagerEditor\fP"
.br
.ti -1c
.RI "class \fBPlayerNumbering\fP"
.br
.RI "Implements consistent numbering in a room/game with help of room properties\&. "
.ti -1c
.RI "class \fBPlayerNumberingExtensions\fP"
.br
.RI "Extension used for PlayerRoomIndexing and Player class\&."
.ti -1c
.RI "class \fBPlayerNumberingInspector\fP"
.br
.ti -1c
.RI "class \fBPointedAtGameObjectInfo\fP"
.br
.RI "Display ViewId, OwnerActorNr, IsCeneView and IsMine when clicked\&. "
.ti -1c
.RI "class \fBPunPlayerScores\fP"
.br
.RI "Scoring system for PhotonPlayer "
.ti -1c
.RI "class \fBPunTeams\fP"
.br
.RI "Implements teams in a room/game with help of player properties\&. "
.ti -1c
.RI "class \fBPunTeamsInspector\fP"
.br
.ti -1c
.RI "class \fBPunTurnManager\fP"
.br
.RI "\fBPun\fP turnBased Game manager\&. "
.ti -1c
.RI "class \fBScoreExtensions\fP"
.br
.ti -1c
.RI "class \fBSmoothSyncMovement\fP"
.br
.RI "Smoothed out movement for network gameobjects "
.ti -1c
.RI "class \fBStatesGui\fP"
.br
.RI "Output detailed information about \fBPun\fP Current states, using the old Unity UI framework\&. "
.ti -1c
.RI "class \fBTabViewManager\fP"
.br
.RI "\fBTab\fP view manager\&. "
.ti -1c
.RI "class \fBTeamExtensions\fP"
.br
.RI "Extension used for \fBPunTeams\fP and Player class\&. Wraps access to the player's custom property\&."
.ti -1c
.RI "class \fBTextButtonTransition\fP"
.br
.RI "Use this on Button texts to have some color transition on the text as well without corrupting button's behaviour\&. "
.ti -1c
.RI "class \fBTextToggleIsOnTransition\fP"
.br
.RI "Use this on toggles texts to have some color transition on the text depending on the isOn State\&. "
.ti -1c
.RI "class \fBTurnExtensions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
