.TH "Photon.Realtime.Demo.ConnectAndJoinRandomLb" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.Demo.ConnectAndJoinRandomLb
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP, \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP, and \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnConnected\fP ()"
.br
.RI "Called to signal that the 'low level connection' got established but before the client can call operation on the server\&. "
.ti -1c
.RI "void \fBOnConnectedToMaster\fP ()"
.br
.RI "Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. "
.ti -1c
.RI "void \fBOnDisconnected\fP (\fBDisconnectCause\fP cause)"
.br
.RI "Called after disconnecting from the \fBPhoton\fP server\&. "
.ti -1c
.RI "void \fBOnCustomAuthenticationResponse\fP (Dictionary< string, object > data)"
.br
.RI "Called when your Custom Authentication service responds with additional data\&. "
.ti -1c
.RI "void \fBOnCustomAuthenticationFailed\fP (string debugMessage)"
.br
.RI "Called when the custom authentication failed\&. "
.ti -1c
.RI "void \fBOnRegionListReceived\fP (\fBRegionHandler\fP regionHandler)"
.br
.RI "Called when the Name Server provided a list of regions for your title\&. "
.ti -1c
.RI "void \fBOnRoomListUpdate\fP (List< \fBRoomInfo\fP > roomList)"
.br
.RI "Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. "
.ti -1c
.RI "void \fBOnLobbyStatisticsUpdate\fP (List< \fBTypedLobbyInfo\fP > lobbyStatistics)"
.br
.RI "Called when the Master Server sent an update for the Lobby Statistics\&. "
.ti -1c
.RI "void \fBOnJoinedLobby\fP ()"
.br
.RI "Called on entering a lobby on the Master Server\&. "
.ti -1c
.RI "void \fBOnLeftLobby\fP ()"
.br
.RI "Called after leaving a lobby\&. "
.ti -1c
.RI "void \fBOnFriendListUpdate\fP (List< \fBFriendInfo\fP > friendList)"
.br
.RI "Called when the server sent the response to a FindFriends request\&. "
.ti -1c
.RI "void \fBOnCreatedRoom\fP ()"
.br
.RI "Called when this client created a room and entered it\&. "
.ti -1c
.RI "void \fBOnCreateRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when the server couldn't create a room (OpCreateRoom failed)\&. "
.ti -1c
.RI "void \fBOnJoinedRoom\fP ()"
.br
.RI "Called when the \fBLoadBalancingClient\fP entered a room, no matter if this client created it or simply joined\&. "
.ti -1c
.RI "void \fBOnJoinRoomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRoom call failed on the server\&. "
.ti -1c
.RI "void \fBOnJoinRandomFailed\fP (short returnCode, string message)"
.br
.RI "Called when a previous OpJoinRandom call failed on the server\&. "
.ti -1c
.RI "void \fBOnLeftRoom\fP ()"
.br
.RI "Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBStateUiText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnConnected ()"

.PP
Called to signal that the 'low level connection' got established but before the client can call operation on the server\&. After the (low level transport) connection is established, the client will automatically send the Authentication operation, which needs to get a response before the client can call other operations\&.
.PP
Your logic should wait for either: OnRegionListReceived or OnConnectedToMaster\&.
.PP
This callback is useful to detect if the server can be reached at all (technically)\&. Most often, it's enough to implement \fBOnDisconnected(DisconnectCause cause)\fP and check for the cause\&.
.PP
This is not called for transitions from the masterserver to game servers\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB59\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnConnectedToMaster ()"

.PP
Called when the client is connected to the Master Server and ready for matchmaking and other tasks\&. The list of available rooms won't become available unless you join a lobby via \fBLoadBalancingClient\&.OpJoinLobby\fP\&. You can join rooms and create them even without being in a lobby\&. The default lobby is used in that case\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB63\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnCreatedRoom ()"

.PP
Called when this client created a room and entered it\&. \fBOnJoinedRoom()\fP will be called as well\&. 
.PP
This callback is only called on the client which created a room (see OpCreateRoom)\&.
.PP
As any client might close (or drop connection) anytime, there is a chance that the creator of a room does not execute OnCreatedRoom\&.
.PP
If you need specific room properties or a 'start signal', implement OnMasterClientSwitched() and make each new MasterClient check the room's state\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB108\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnCreateRoomFailed (short returnCode, string message)"

.PP
Called when the server couldn't create a room (OpCreateRoom failed)\&. Creating a room may fail for various reasons\&. Most often, the room already exists (roomname in use) or the \fBRoomOptions\fP clash and it's impossible to create the room\&.
.PP
When creating a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback\&. This way, the client is ready to find/create a room at the moment of the callback\&. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected\&. Treat callbacks of OnConnected as pure information that the client could connect\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB112\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnCustomAuthenticationFailed (string debugMessage)"

.PP
Called when the custom authentication failed\&. Followed by disconnect! 
.PP
Custom Authentication can fail due to user-input, bad tokens/secrets\&. If authentication is successful, this method is not called\&. Implement \fBOnJoinedLobby()\fP or \fBOnConnectedToMaster()\fP (as usual)\&.
.PP
During development of a game, it might also fail due to wrong configuration on the server side\&. In those cases, logging the debugMessage is very important\&.
.PP
Unless you setup a custom authentication service for your app (in the \fCDashboard\fP), this won't be called! 
.PP
\fBParameters\fP
.RS 4
\fIdebugMessage\fP Contains a debug message why authentication failed\&. This has to be fixed during development\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB78\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnCustomAuthenticationResponse (Dictionary< string, object > data)"

.PP
Called when your Custom Authentication service responds with additional data\&. Custom Authentication services can include some custom data in their response\&. When present, that data is made available in this callback as Dictionary\&. While the keys of your data have to be strings, the values can be either string or a number (in Json)\&. You need to make extra sure, that the value type is the one you expect\&. Numbers become (currently) int64\&.
.PP
Example: void OnCustomAuthenticationResponse(Dictionary<string, object> data) { \&.\&.\&. } 
.PP
https://doc\&.photonengine\&.com/en-us/realtime/current/reference/custom-authentication 
.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB74\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnDisconnected (\fBDisconnectCause\fP cause)"

.PP
Called after disconnecting from the \fBPhoton\fP server\&. It could be a failure or an explicit disconnect call 
.PP
The reason for this disconnect is provided as DisconnectCause\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB69\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnFriendListUpdate (List< \fBFriendInfo\fP > friendList)"

.PP
Called when the server sent the response to a FindFriends request\&. After calling OpFindFriends, the Master Server will cache the friend list and send updates to the friend list\&. The friends includes the name, userId, online state and the room (if any) for each requested user/friend\&.
.PP
Use the friendList to update your UI and store it, if the UI should highlight changes\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB104\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnJoinedLobby ()"

.PP
Called on entering a lobby on the Master Server\&. The actual room-list updates will call OnRoomListUpdate\&. 
.PP
While in the lobby, the roomlist is automatically updated in fixed intervals (which you can't modify in the public cloud)\&. The room list gets available via OnRoomListUpdate\&. 
.PP
Implements \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP\&.
.PP
Definition at line \fB96\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnJoinedRoom ()"

.PP
Called when the \fBLoadBalancingClient\fP entered a room, no matter if this client created it or simply joined\&. When this is called, you can access the existing players in \fBRoom\&.Players\fP, their custom properties and \fBRoom\&.CustomProperties\fP\&.
.PP
In this callback, you could create player objects\&. For example in Unity, instantiate a prefab for the player\&.
.PP
If you want a match to be started 'actively', enable the user to signal 'ready' (using OpRaiseEvent or a Custom Property)\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB116\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnJoinRandomFailed (short returnCode, string message)"

.PP
Called when a previous OpJoinRandom call failed on the server\&. The most common causes are that a room is full or does not exist (due to someone else being faster or closing the room)\&.
.PP
This operation is only ever sent to the Master Server\&. Once a room is found by the Master Server, the client will head off to the designated Game Server and use the operation Join on the Game Server\&.
.PP
When using multiple lobbies (via OpJoinLobby or a \fBTypedLobby\fP parameter), another lobby might have more/fitting rooms\&.
.br
 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB125\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnJoinRoomFailed (short returnCode, string message)"

.PP
Called when a previous OpJoinRoom call failed on the server\&. Joining a room may fail for various reasons\&. Most often, the room is full or does not exist anymore (due to someone else being faster or closing the room)\&.
.PP
When joining a room fails on a Game Server: The client will cache the failure internally and returns to the Master Server before it calls the fail-callback\&. This way, the client is ready to find/create a room at the moment of the callback\&. In this case, the client skips calling OnConnectedToMaster but returning to the Master Server will still call OnConnected\&. Treat callbacks of OnConnected as pure information that the client could connect\&. 
.PP
\fBParameters\fP
.RS 4
\fIreturnCode\fP Operation ReturnCode from the server\&.
.br
\fImessage\fP Debug message for the error\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB121\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnLeftLobby ()"

.PP
Called after leaving a lobby\&. When you leave a lobby, \fBOpCreateRoom\fP and \fBOpJoinRandomRoom\fP automatically refer to the default lobby\&. 
.PP
Implements \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP\&.
.PP
Definition at line \fB100\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnLeftRoom ()"

.PP
Called when the local user/client left a room, so the game's logic can clean up it's internal state\&. When leaving a room, the \fBLoadBalancingClient\fP will disconnect the Game Server and connect to the Master Server\&. This wraps up multiple internal actions\&.
.PP
Wait for the callback OnConnectedToMaster, before you use lobbies and join or create rooms\&. 
.PP
Implements \fBPhoton\&.Realtime\&.IMatchmakingCallbacks\fP\&.
.PP
Definition at line \fB131\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnLobbyStatisticsUpdate (List< \fBTypedLobbyInfo\fP > lobbyStatistics)"

.PP
Called when the Master Server sent an update for the Lobby Statistics\&. This callback has two preconditions: EnableLobbyStatistics must be set to true, before this client connects\&. And the client has to be connected to the Master Server, which is providing the info about lobbies\&. 
.PP
Implements \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP\&.
.PP
Definition at line \fB92\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnRegionListReceived (\fBRegionHandler\fP regionHandler)"

.PP
Called when the Name Server provided a list of regions for your title\&. Check the \fBRegionHandler\fP class description, to make use of the provided values\&.
.PP
\fBParameters\fP
.RS 4
\fIregionHandler\fP The currently used \fBRegionHandler\fP\&.
.RE
.PP

.PP
Implements \fBPhoton\&.Realtime\&.IConnectionCallbacks\fP\&.
.PP
Definition at line \fB82\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.OnRoomListUpdate (List< \fBRoomInfo\fP > roomList)"

.PP
Called for any update of the room-listing while in a lobby (InLobby) on the Master Server\&. Each item is a \fBRoomInfo\fP which might include custom properties (provided you defined those as lobby-listed when creating a room)\&. Not all types of lobbies provide a listing of rooms to the client\&. Some are silent and specialized for server-side matchmaking\&. 
.PP
Implements \fBPhoton\&.Realtime\&.ILobbyCallbacks\fP\&.
.PP
Definition at line \fB88\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.Start ()"

.PP
Definition at line \fB23\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.Update ()"

.PP
Definition at line \fB41\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Realtime\&.Demo\&.ConnectAndJoinRandomLb\&.StateUiText"

.PP
Definition at line \fB21\fP of file \fBConnectAndJoinRandomLb\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
