.TH "Photon.Pun.IOnPhotonViewOwnerChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.IOnPhotonViewOwnerChange \- This interface defines a callback for changes to the \fBPhotonView\fP's owner\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.IPhotonViewCallback\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.NetObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnOwnerChange\fP (\fBPlayer\fP newOwner, \fBPlayer\fP previousOwner)"
.br
.RI "This method will be called when the \fBPhotonView\fP's owner changes\&. "
.in -1c
.SH "Detailed Description"
.PP 
This interface defines a callback for changes to the \fBPhotonView\fP's owner\&. 


.PP
Definition at line \fB28\fP of file \fBIPhotonViewCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.IOnPhotonViewOwnerChange\&.OnOwnerChange (\fBPlayer\fP newOwner, \fBPlayer\fP previousOwner)"

.PP
This method will be called when the \fBPhotonView\fP's owner changes\&. 
.PP
\fBParameters\fP
.RS 4
\fInewOwner\fP 
.br
\fIpreviousOwner\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
