.TH "Photon.Pun.Simple.IOnVitalsParamChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnVitalsParamChange
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IOnVitalsChange\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnVitalParamChange\fP (\fBVital\fP vital)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB29\fP of file \fBIOnVitalChange\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnVitalsParamChange\&.OnVitalParamChange (\fBVital\fP vital)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
