.TH "Photon.Chat.ParameterCode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ParameterCode \- Class for constants\&. Codes for parameters of Operations and Events\&. 

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBApplicationId\fP = 224"
.br
.RI "(224) Your application's ID: a name on your own \fBPhoton\fP or a GUID on the \fBPhoton\fP Cloud"
.ti -1c
.RI "const byte \fBSecret\fP = 221"
.br
.RI "(221) Internally used to establish encryption"
.ti -1c
.RI "const byte \fBAppVersion\fP = 220"
.br
.RI "(220) Version of your application"
.ti -1c
.RI "const byte \fBClientAuthenticationType\fP = 217"
.br
.RI "(217) This key's (byte) value defines the target custom authentication type/service the client connects with\&. Used in OpAuthenticate"
.ti -1c
.RI "const byte \fBClientAuthenticationParams\fP = 216"
.br
.RI "(216) This key's (string) value provides parameters sent to the custom authentication type/service the client connects with\&. Used in OpAuthenticate"
.ti -1c
.RI "const byte \fBClientAuthenticationData\fP = 214"
.br
.RI "(214) This key's (string or byte[]) value provides parameters sent to the custom authentication service setup in \fBPhoton\fP Dashboard\&. Used in OpAuthenticate"
.ti -1c
.RI "const byte \fBRegion\fP = 210"
.br
.RI "(210) Used for region values in OpAuth and OpGetRegions\&."
.ti -1c
.RI "const byte \fBAddress\fP = 230"
.br
.RI "(230) Address of a (game) server to use\&."
.ti -1c
.RI "const byte \fBUserId\fP = 225"
.br
.RI "(225) User's ID"
.in -1c
.SH "Detailed Description"
.PP 
Class for constants\&. Codes for parameters of Operations and Events\&.
.PP
Definition at line \fB358\fP of file \fBChatPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Chat\&.ParameterCode\&.Address = 230\fC [static]\fP"

.PP
(230) Address of a (game) server to use\&.
.PP
Definition at line \fB375\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.ApplicationId = 224\fC [static]\fP"

.PP
(224) Your application's ID: a name on your own \fBPhoton\fP or a GUID on the \fBPhoton\fP Cloud
.PP
Definition at line \fB361\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.AppVersion = 220\fC [static]\fP"

.PP
(220) Version of your application
.PP
Definition at line \fB365\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.ClientAuthenticationData = 214\fC [static]\fP"

.PP
(214) This key's (string or byte[]) value provides parameters sent to the custom authentication service setup in \fBPhoton\fP Dashboard\&. Used in OpAuthenticate
.PP
Definition at line \fB371\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.ClientAuthenticationParams = 216\fC [static]\fP"

.PP
(216) This key's (string) value provides parameters sent to the custom authentication type/service the client connects with\&. Used in OpAuthenticate
.PP
Definition at line \fB369\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.ClientAuthenticationType = 217\fC [static]\fP"

.PP
(217) This key's (byte) value defines the target custom authentication type/service the client connects with\&. Used in OpAuthenticate
.PP
Definition at line \fB367\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.Region = 210\fC [static]\fP"

.PP
(210) Used for region values in OpAuth and OpGetRegions\&.
.PP
Definition at line \fB373\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.Secret = 221\fC [static]\fP"

.PP
(221) Internally used to establish encryption
.PP
Definition at line \fB363\fP of file \fBChatPeer\&.cs\fP\&.
.SS "const byte Photon\&.Chat\&.ParameterCode\&.UserId = 225\fC [static]\fP"

.PP
(225) User's ID
.PP
Definition at line \fB377\fP of file \fBChatPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
