.TH "Photon.Realtime.FriendInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.FriendInfo \- Used to store info about a friend's online state and in which room he/she is\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBUserId\fP\fC [getprotected set]\fP"
.br
.ti -1c
.RI "bool \fBIsOnline\fP\fC [getprotected set]\fP"
.br
.ti -1c
.RI "string \fBRoom\fP\fC [getprotected set]\fP"
.br
.ti -1c
.RI "bool \fBIsInRoom\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to store info about a friend's online state and in which room he/she is\&. 


.PP
Definition at line \fB29\fP of file \fBFriendInfo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Realtime\&.FriendInfo\&.ToString ()"

.PP
Definition at line \fB43\fP of file \fBFriendInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Realtime\&.FriendInfo\&.IsInRoom\fC [get]\fP"

.PP
Definition at line \fB38\fP of file \fBFriendInfo\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.FriendInfo\&.IsOnline\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line \fB35\fP of file \fBFriendInfo\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.FriendInfo\&.Name\fC [get]\fP"

.PP
Definition at line \fB32\fP of file \fBFriendInfo\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.FriendInfo\&.Room\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line \fB36\fP of file \fBFriendInfo\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.FriendInfo\&.UserId\fC [get]\fP, \fC [protected set]\fP"

.PP
Definition at line \fB33\fP of file \fBFriendInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
