.TH "Photon.Pun.Simple.ISyncAnimator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ISyncAnimator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBSyncObjInterfaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
