.TH "Photon.Chat.ChatUserStatus" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.ChatUserStatus \- Contains commonly used status values for SetOnlineStatus\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBOffline\fP = 0"
.br
.RI "(0) Offline\&."
.ti -1c
.RI "const int \fBInvisible\fP = 1"
.br
.RI "(1) Be invisible to everyone\&. Sends no message\&."
.ti -1c
.RI "const int \fBOnline\fP = 2"
.br
.RI "(2) Online and available\&."
.ti -1c
.RI "const int \fBAway\fP = 3"
.br
.RI "(3) Online but not available\&."
.ti -1c
.RI "const int \fBDND\fP = 4"
.br
.RI "(4) Do not disturb\&."
.ti -1c
.RI "const int \fBLFG\fP = 5"
.br
.RI "(5) Looking For Game/Group\&. Could be used when you want to be invited or do matchmaking\&."
.ti -1c
.RI "const int \fBPlaying\fP = 6"
.br
.RI "(6) Could be used when in a room, playing\&."
.in -1c
.SH "Detailed Description"
.PP 
Contains commonly used status values for SetOnlineStatus\&. 

You can define your own\&.
.PP
While 'online' (value 2 and up), the status message will be sent to anyone who has you on his friend list\&.
.PP
Define custom online status values as you like with these rules: 0: Means 'offline'\&. It will be used when you are not connected\&. In this status, there is no status message\&. 1: Means 'invisible' and is sent to friends as 'offline'\&. They see status 0, no message but you can chat\&. 2: And any higher value will be treated as 'online'\&. Status can be set\&. 
.PP
Definition at line \fB18\fP of file \fBChatUserStatus\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.Away = 3\fC [static]\fP"

.PP
(3) Online but not available\&.
.PP
Definition at line \fB27\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.DND = 4\fC [static]\fP"

.PP
(4) Do not disturb\&.
.PP
Definition at line \fB29\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.Invisible = 1\fC [static]\fP"

.PP
(1) Be invisible to everyone\&. Sends no message\&.
.PP
Definition at line \fB23\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.LFG = 5\fC [static]\fP"

.PP
(5) Looking For Game/Group\&. Could be used when you want to be invited or do matchmaking\&.
.PP
Definition at line \fB31\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.Offline = 0\fC [static]\fP"

.PP
(0) Offline\&.
.PP
Definition at line \fB21\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.Online = 2\fC [static]\fP"

.PP
(2) Online and available\&.
.PP
Definition at line \fB25\fP of file \fBChatUserStatus\&.cs\fP\&.
.SS "const int Photon\&.Chat\&.ChatUserStatus\&.Playing = 6\fC [static]\fP"

.PP
(6) Could be used when in a room, playing\&.
.PP
Definition at line \fB33\fP of file \fBChatUserStatus\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
