.TH "Photon.Pun.PhotonTransformViewScaleControl" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewScaleControl
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhotonTransformViewScaleControl\fP (\fBPhotonTransformViewScaleModel\fP model)"
.br
.ti -1c
.RI "Vector3 \fBGetNetworkScale\fP ()"
.br
.RI "Gets the last scale that was received through the network "
.ti -1c
.RI "Vector3 \fBGetScale\fP (Vector3 currentScale)"
.br
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (Vector3 currentScale, \fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB506\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.PhotonTransformViewScaleControl\&.PhotonTransformViewScaleControl (\fBPhotonTransformViewScaleModel\fP model)"

.PP
Definition at line \fB511\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Vector3 Photon\&.Pun\&.PhotonTransformViewScaleControl\&.GetNetworkScale ()"

.PP
Gets the last scale that was received through the network 
.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line \fB520\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.PhotonTransformViewScaleControl\&.GetScale (Vector3 currentScale)"

.PP
Definition at line \fB525\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonTransformViewScaleControl\&.OnPhotonSerializeView (Vector3 currentScale, \fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"

.PP
Definition at line \fB539\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
