.TH "Photon.Realtime.WebRpcResponse" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.WebRpcResponse \- Reads an operation response of a WebRpc and provides convenient access to most common values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWebRpcResponse\fP (OperationResponse response)"
.br
.RI "An OperationResponse for a WebRpc is needed to read it's values\&."
.ti -1c
.RI "string \fBToStringFull\fP ()"
.br
.RI "Turns the response into an easier to read string\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "Name of the WebRpc that was called\&."
.ti -1c
.RI "int \fBResultCode\fP\fC [get]\fP"
.br
.RI "ResultCode of the WebService that answered the WebRpc\&. "
.ti -1c
.RI "int \fBReturnCode\fP\fC [get]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fC [get]\fP"
.br
.RI "Might be empty or null\&."
.ti -1c
.RI "string \fBDebugMessage\fP\fC [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object > \fBParameters\fP\fC [get]\fP"
.br
.RI "Other key/values returned by the webservice that answered the WebRpc\&."
.in -1c
.SH "Detailed Description"
.PP 
Reads an operation response of a WebRpc and provides convenient access to most common values\&. 

See \fBLoadBalancingClient\&.OpWebRpc\fP\&.
.br
 Create a \fBWebRpcResponse\fP to access common result values\&.
.br
 The operationResponse\&.OperationCode should be: \fBOperationCode\&.WebRpc\fP\&.
.br
 
.PP
Definition at line \fB34\fP of file \fBWebRpc\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Realtime\&.WebRpcResponse\&.WebRpcResponse (OperationResponse response)"

.PP
An OperationResponse for a WebRpc is needed to read it's values\&.
.PP
Definition at line \fB65\fP of file \fBWebRpc\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Photon\&.Realtime\&.WebRpcResponse\&.ToStringFull ()"

.PP
Turns the response into an easier to read string\&. 
.PP
\fBReturns\fP
.RS 4
String resembling the result\&.
.RE
.PP

.PP
Definition at line \fB92\fP of file \fBWebRpc\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Realtime\&.WebRpcResponse\&.DebugMessage\fC [get]\fP"

.PP
Definition at line \fB55\fP of file \fBWebRpc\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.WebRpcResponse\&.Message\fC [get]\fP"

.PP
Might be empty or null\&.
.PP
Definition at line \fB53\fP of file \fBWebRpc\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.WebRpcResponse\&.Name\fC [get]\fP"

.PP
Name of the WebRpc that was called\&.
.PP
Definition at line \fB37\fP of file \fBWebRpc\&.cs\fP\&.
.SS "Dictionary<string, object> Photon\&.Realtime\&.WebRpcResponse\&.Parameters\fC [get]\fP"

.PP
Other key/values returned by the webservice that answered the WebRpc\&.
.PP
Definition at line \fB62\fP of file \fBWebRpc\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.WebRpcResponse\&.ResultCode\fC [get]\fP"

.PP
ResultCode of the WebService that answered the WebRpc\&. 0 is: 'OK' for WebRPCs\&.
.br
 -1 is: No ResultCode by WebRpc service (check OperationResponse\&.ReturnCode)\&.
.br
 Other ResultCode are defined by the individual WebRpc and service\&. 
.PP
Definition at line \fB45\fP of file \fBWebRpc\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.WebRpcResponse\&.ReturnCode\fC [get]\fP"

.PP
Definition at line \fB47\fP of file \fBWebRpc\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
