.TH "Photon.Pun.Demo.Procedural.Cluster" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Procedural.Cluster \- The \fBCluster\fP component has references to all Blocks that are part of this \fBCluster\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBAddBlock\fP (int blockId, GameObject block)"
.br
.RI "Adds a \fBBlock\fP to the \fBCluster\fP\&. "
.ti -1c
.RI "void \fBDestroyCluster\fP ()"
.br
.RI "Gets called before a new world can be generated\&. "
.ti -1c
.RI "void \fBDecreaseBlockHeight\fP (int blockId)"
.br
.RI "Decreases a \fBBlock\fP's height locally before applying the modification to the Custom Room Properties\&. "
.ti -1c
.RI "void \fBIncreaseBlockHeight\fP (int blockId)"
.br
.RI "Increases a \fBBlock\fP's height locally before applying the modification to the Custom Room Properties\&. "
.ti -1c
.RI "void \fBSetBlockHeightRemote\fP (int blockId, float height)"
.br
.RI "Gets called when a remote client has modified a certain \fBBlock\fP within this \fBCluster\fP\&. "
.ti -1c
.RI "override void \fBOnRoomPropertiesUpdate\fP (\fBHashtable\fP propertiesThatChanged)"
.br
.RI "Gets called whenever the Custom Room Properties are updated\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBClusterId\fP\fC [getset]\fP"
.br
.ti -1c
.RI "Dictionary< int, GameObject > \fBBlocks\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCluster\fP component has references to all Blocks that are part of this \fBCluster\fP\&. 

It provides functions for modifying single Blocks inside this \fBCluster\fP\&. It also handles modifications made to the world by other clients\&. 
.PP
Definition at line \fB14\fP of file \fBCluster\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.AddBlock (int blockId, GameObject block)"

.PP
Adds a \fBBlock\fP to the \fBCluster\fP\&. This is called by the \fBWorldGenerator\fP while the generation process is running\&. In order to modify Blocks directly, we are storing the ID as well as a reference to the certain GameObject\&. 
.PP
Definition at line \fB50\fP of file \fBCluster\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.Awake ()"

.PP
Definition at line \fB26\fP of file \fBCluster\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.DecreaseBlockHeight (int blockId)"

.PP
Decreases a \fBBlock\fP's height locally before applying the modification to the Custom Room Properties\&. 
.PP
Definition at line \fB77\fP of file \fBCluster\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.DestroyCluster ()"

.PP
Gets called before a new world can be generated\&. Destroys each \fBBlock\fP from this \fBCluster\fP and removes the data stored in the Custom Room Properties\&. 
.PP
Definition at line \fB59\fP of file \fBCluster\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.IncreaseBlockHeight (int blockId)"

.PP
Increases a \fBBlock\fP's height locally before applying the modification to the Custom Room Properties\&. 
.PP
Definition at line \fB88\fP of file \fBCluster\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.OnRoomPropertiesUpdate (\fBHashtable\fP propertiesThatChanged)\fC [virtual]\fP"

.PP
Gets called whenever the Custom Room Properties are updated\&. When the changed properties contain the previously set PropertiesKey (basically the \fBCluster\fP ID), the \fBCluster\fP and its Blocks will be updated accordingly\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB157\fP of file \fBCluster\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.SetBlockHeightRemote (int blockId, float height)"

.PP
Gets called when a remote client has modified a certain \fBBlock\fP within this \fBCluster\fP\&. Called by the \fBWorldGenerator\fP or the \fBCluster\fP itself after the Custom Room Properties have been updated\&. 
.PP
Definition at line \fB100\fP of file \fBCluster\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<int, GameObject> Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.Blocks\fC [get]\fP"

.PP
Definition at line \fB22\fP of file \fBCluster\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Demo\&.Procedural\&.Cluster\&.ClusterId\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB20\fP of file \fBCluster\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
