.TH "Photon.Utilities.BitUtilities" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Utilities.BitUtilities
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBGetBitsForMaxValue\fP (this int maxvalue)"
.br
.RI "Returns the min number of bits required to describe any value between 0 and int maxvalue "
.ti -1c
.RI "static int \fBGetBitsForMaxValue\fP (this uint maxvalue)"
.br
.RI "Returns the min number of bits required to describe any value between 0 and uint maxvalue "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBBitUtilities\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int Photon\&.Utilities\&.BitUtilities\&.GetBitsForMaxValue (this int maxvalue)\fC [static]\fP"

.PP
Returns the min number of bits required to describe any value between 0 and int maxvalue 
.PP
Definition at line \fB13\fP of file \fBBitUtilities\&.cs\fP\&.
.SS "static int Photon\&.Utilities\&.BitUtilities\&.GetBitsForMaxValue (this uint maxvalue)\fC [static]\fP"

.PP
Returns the min number of bits required to describe any value between 0 and uint maxvalue 
.PP
Definition at line \fB24\fP of file \fBBitUtilities\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
