.TH "Photon.Pun.Simple.SyncOwner.Frame" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncOwner.Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBClear\fP ()"
.br
.ti -1c
.RI "override void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBownerActorId\fP"
.br
.ti -1c
.RI "bool \fBownerHasChanged\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBSyncOwner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncOwner\&.Frame\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB35\fP of file \fBSyncOwner\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.SyncOwner\&.Frame\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.FrameBase\fP\&.
.PP
Definition at line \fB42\fP of file \fBSyncOwner\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.SyncOwner\&.Frame\&.ownerActorId"

.PP
Definition at line \fB32\fP of file \fBSyncOwner\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncOwner\&.Frame\&.ownerHasChanged"

.PP
Definition at line \fB33\fP of file \fBSyncOwner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
