.TH "Photon.Pun.PhotonAnimatorView.SynchronizedParameter" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonAnimatorView.SynchronizedParameter
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBParameterType\fP \fBType\fP"
.br
.ti -1c
.RI "\fBSynchronizeType\fP \fBSynchronizeType\fP"
.br
.ti -1c
.RI "string \fBName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.PhotonAnimatorView\&.SynchronizedParameter\&.Name"

.PP
Definition at line \fB54\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "\fBSynchronizeType\fP Photon\&.Pun\&.PhotonAnimatorView\&.SynchronizedParameter\&.SynchronizeType"

.PP
Definition at line \fB53\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "\fBParameterType\fP Photon\&.Pun\&.PhotonAnimatorView\&.SynchronizedParameter\&.Type"

.PP
Definition at line \fB52\fP of file \fBPhotonAnimatorView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
