.TH "Photon.Pun.Simple.SyncAdditiveMover" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncAdditiveMover \- Basic automatic transform mover for objects for network testing\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.ITransformController\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTRSDefinition\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.ti -1c
.RI "void \fBOnPreUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTRSDefinition\fP \fBposDef\fP = new \fBTRSDefinition\fP()"
.br
.ti -1c
.RI "\fBTRSDefinition\fP \fBrotDef\fP = new \fBTRSDefinition\fP()"
.br
.ti -1c
.RI "\fBTRSDefinition\fP \fBsclDef\fP = new \fBTRSDefinition\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHandlesInterpolation\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBHandlesExtrapolation\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Basic automatic transform mover for objects for network testing\&. 

Will only run if object has local authority\&. 
.PP
Definition at line \fB20\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.OnPreSimulate (int frameId, int subFrameId)"
Make sure previous lerp is fully applied to scene so our transform capture is based on the fixed time and not the last update time
.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Definition at line \fB63\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.OnPreUpdate ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.PP
Definition at line \fB72\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTRSDefinition\fP Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.posDef = new \fBTRSDefinition\fP()"

.PP
Definition at line \fB34\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SS "\fBTRSDefinition\fP Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.rotDef = new \fBTRSDefinition\fP()"

.PP
Definition at line \fB35\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SS "\fBTRSDefinition\fP Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.sclDef = new \fBTRSDefinition\fP()"

.PP
Definition at line \fB36\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.HandlesExtrapolation\fC [get]\fP"

.PP
Definition at line \fB53\fP of file \fBSyncAdditiveMover\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.SyncAdditiveMover\&.HandlesInterpolation\fC [get]\fP"

.PP
Definition at line \fB52\fP of file \fBSyncAdditiveMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
