.TH "Photon.Pun.Simple.IOnNetSerialize" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnNetSerialize
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ISerializationOptional\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationFlags\fP \fBOnNetSerialize\fP (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBOnNetDeserialize\fP (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP frameArrival)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBSkipWhenEmpty\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB58\fP of file \fBSyncObjInterfaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.IOnNetSerialize\&.OnNetDeserialize (int originFrameId, byte[] buffer, ref int bitposition, \fBFrameArrival\fP frameArrival)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.IOnNetSerialize\&.OnNetSerialize (int frameId, byte[] buffer, ref int bitposition, \fBSerializationFlags\fP writeFlags)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncTransform\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.IOnNetSerialize\&.SkipWhenEmpty\fC [get]\fP"

.PP
Definition at line \fB62\fP of file \fBSyncObjInterfaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
