.TH "Photon.Pun.UtilityScripts.CopyComponent" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.CopyComponent
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Component \fBComponentCopy\fP (this Component original, GameObject destination)"
.br
.ti -1c
.RI "static T \fBGetCopyOf< T >\fP (this T comp, T other)"
.br
.ti -1c
.RI "static T \fBAddColliderCopy< T >\fP (this GameObject go, T toAdd)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBCopyComponent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static T Photon\&.Pun\&.UtilityScripts\&.CopyComponent\&.AddColliderCopy< T > (this GameObject go, T toAdd)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fICollider\fP
.PP
Definition at line \fB59\fP of file \fBCopyComponent\&.cs\fP\&.
.SS "static Component Photon\&.Pun\&.UtilityScripts\&.CopyComponent\&.ComponentCopy (this Component original, GameObject destination)\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBCopyComponent\&.cs\fP\&.
.SS "static T Photon\&.Pun\&.UtilityScripts\&.CopyComponent\&.GetCopyOf< T > (this T comp, T other)\fC [static]\fP"
Only set value if we are not dealing with an obsolete method (otherwise\&.\&.\&. enjoy log warnings)
.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line \fB28\fP of file \fBCopyComponent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
