.TH "Photon.Pun.PhotonTransformViewEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBPhotonTransformViewEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.PhotonTransformViewEditor\&.OnEnable ()"

.PP
Definition at line \fB25\fP of file \fBPhotonTransformViewEditor\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.PhotonTransformViewEditor\&.OnInspectorGUI ()"

.PP
Definition at line \fB33\fP of file \fBPhotonTransformViewEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
