.TH "Photon.Compression.PrimitivePackBytesExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.PrimitivePackBytesExt \- Experimental packers, that counts number of used bits for serialization\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ulong \fBWritePackedBytes\fP (this ulong buffer, ulong value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static uint \fBWritePackedBytes\fP (this uint buffer, uint value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static void \fBInjectPackedBytes\fP (this ulong value, ref ulong buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static void \fBInjectPackedBytes\fP (this uint value, ref uint buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write Method\&. "
.ti -1c
.RI "static ulong \fBReadPackedBytes\fP (this ulong buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBytes\&. "
.ti -1c
.RI "static uint \fBReadPackedBytes\fP (this uint buffer, ref int bitposition, int bits)"
.br
.RI "Primary Reader for PackedBytes\&. "
.ti -1c
.RI "static ulong \fBWriteSignedPackedBytes\fP (this ulong buffer, int value, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Primary Write signed value as PackedByte\&. "
.ti -1c
.RI "static int \fBReadSignedPackedBytes\fP (this ulong buffer, ref int bitposition, int bits)"
.br
.RI "EXPERIMENTAL: Read signed value from PackedByte\&. "
.in -1c
.SH "Detailed Description"
.PP 
Experimental packers, that counts number of used bits for serialization\&. 

Effective for values that hover close to zero\&. 
.PP
Definition at line \fB31\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.PrimitivePackBytesExt\&.InjectPackedBytes (this uint value, ref uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB89\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.PrimitivePackBytesExt\&.InjectPackedBytes (this ulong value, ref ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB74\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitivePackBytesExt\&.ReadPackedBytes (this uint buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBytes\&. 
.PP
Definition at line \fB119\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBytesExt\&.ReadPackedBytes (this ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
Primary Reader for PackedBytes\&. 
.PP
Definition at line \fB109\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static int Photon\&.Compression\&.PrimitivePackBytesExt\&.ReadSignedPackedBytes (this ulong buffer, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Read signed value from PackedByte\&. 
.PP
Definition at line \fB142\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static uint Photon\&.Compression\&.PrimitivePackBytesExt\&.WritePackedBytes (this uint buffer, uint value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB56\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBytesExt\&.WritePackedBytes (this ulong buffer, ulong value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write Method\&. 
.PP
Definition at line \fB39\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.
.SS "static ulong Photon\&.Compression\&.PrimitivePackBytesExt\&.WriteSignedPackedBytes (this ulong buffer, int value, ref int bitposition, int bits)\fC [static]\fP"

.PP
EXPERIMENTAL: Primary Write signed value as PackedByte\&. 
.PP
Definition at line \fB134\fP of file \fBPrimitivePackBytesExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
