.TH "Photon.Pun.Simple.NetMasterCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.NetMasterCallbacks
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDelayedRegistrationItem\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterCallbackInterfaces\fP (object comp, bool register=true, bool delay=false)"
.br
.RI "Find callback interfaces used by \fBNetMaster\fP in this class, and add/remove them from the callback lists\&. "
.ti -1c
.RI "static void \fBOnPreQuitCallbacks\fP ()"
.br
.ti -1c
.RI "static void \fBOnPreUpdateCallbacks\fP ()"
.br
.ti -1c
.RI "static void \fBOnInterpolateCallbacks\fP (int _prevFrameId, int _currFrameId, float t)"
.br
.ti -1c
.RI "static void \fBOnPreLateUpdateCallbacks\fP ()"
.br
.ti -1c
.RI "static void \fBOnPostSimulateCallbacks\fP (int _currFrameId, int _currSubFrameId, bool isNetTick)"
.br
.ti -1c
.RI "static void \fBOnIncrementFrameCallbacks\fP (int _currFrameId, int _currSubFrameId, int _prevFrameId, int _prevSubFrameId)"
.br
.ti -1c
.RI "static void \fBOnSnapshotCallbacks\fP (int _currFrameId)"
.br
.ti -1c
.RI "static void \fBOnPreSerializeTickCallbacks\fP (int _currFrameId, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBOnPreSimulateCallbacks\fP (int currentFrameId, int currentSubFrameId)"
.br
.ti -1c
.RI "static void \fBOnPostUpdateCallbacks\fP ()"
.br
.ti -1c
.RI "static void \fBOnPostLateUpdateCallbacks\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBIOnTickPreSerialization\fP > \fBonTickPreSerializations\fP = new List<\fBIOnTickPreSerialization\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPreUpdate\fP > \fBonPreUpdates\fP = new List<\fBIOnPreUpdate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPostUpdate\fP > \fBonPostUpdates\fP = new List<\fBIOnPostUpdate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPreLateUpdate\fP > \fBonPreLateUpdates\fP = new List<\fBIOnPreLateUpdate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPostLateUpdate\fP > \fBonPostLateUpdates\fP = new List<\fBIOnPostLateUpdate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnIncrementFrame\fP > \fBonIncrementFrames\fP = new List<\fBIOnIncrementFrame\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPreSimulate\fP > \fBonPreSimulates\fP = new List<\fBIOnPreSimulate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPostSimulate\fP > \fBonPostSimulates\fP = new List<\fBIOnPostSimulate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnTickSnapshot\fP > \fBonSnapshots\fP = new List<\fBIOnTickSnapshot\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnInterpolate\fP > \fBonInterpolates\fP = new List<\fBIOnInterpolate\fP>()"
.br
.ti -1c
.RI "static List< \fBIOnPreQuit\fP > \fBonPreQuits\fP = new List<\fBIOnPreQuit\fP>()"
.br
.ti -1c
.RI "static Queue< System\&.Action > \fBpostCallbackActions\fP = new Queue<System\&.Action>()"
.br
.RI "Add delegates here that should be executed after the current callback timing segment has run\&. "
.ti -1c
.RI "static Queue< System\&.Action > \fBpostSimulateActions\fP = new Queue<System\&.Action>()"
.br
.RI "Add delegates here that should be executed after the PostSimulation timing has run\&. "
.ti -1c
.RI "static Queue< System\&.Action > \fBpostSerializationActions\fP = new Queue<System\&.Action>()"
.br
.ti -1c
.RI "static Queue< \fBDelayedRegistrationItem\fP > \fBpendingRegistrations\fP = new Queue<\fBDelayedRegistrationItem\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBCallbacksLocked\fP\fC [set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnIncrementFrameCallbacks (int _currFrameId, int _currSubFrameId, int _prevFrameId, int _prevSubFrameId)\fC [static]\fP"

.PP
Definition at line \fB151\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnInterpolateCallbacks (int _prevFrameId, int _currFrameId, float t)\fC [static]\fP"

.PP
Definition at line \fB126\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPostLateUpdateCallbacks ()\fC [static]\fP"

.PP
Definition at line \fB218\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPostSimulateCallbacks (int _currFrameId, int _currSubFrameId, bool isNetTick)\fC [static]\fP"

.PP
Definition at line \fB143\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPostUpdateCallbacks ()\fC [static]\fP"

.PP
Definition at line \fB205\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPreLateUpdateCallbacks ()\fC [static]\fP"

.PP
Definition at line \fB134\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPreQuitCallbacks ()\fC [static]\fP"

.PP
Definition at line \fB110\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPreSerializeTickCallbacks (int _currFrameId, byte[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB174\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPreSimulateCallbacks (int currentFrameId, int currentSubFrameId)\fC [static]\fP"

.PP
Definition at line \fB192\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnPreUpdateCallbacks ()\fC [static]\fP"

.PP
Definition at line \fB118\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.OnSnapshotCallbacks (int _currFrameId)\fC [static]\fP"

.PP
Definition at line \fB159\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.RegisterCallbackInterfaces (object comp, bool register = \fCtrue\fP, bool delay = \fCfalse\fP)\fC [static]\fP"

.PP
Find callback interfaces used by \fBNetMaster\fP in this class, and add/remove them from the callback lists\&. 
.PP
Definition at line \fB56\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBIOnIncrementFrame\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onIncrementFrames = new List<\fBIOnIncrementFrame\fP>()\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnInterpolate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onInterpolates = new List<\fBIOnInterpolate\fP>()\fC [static]\fP"

.PP
Definition at line \fB31\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPostLateUpdate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPostLateUpdates = new List<\fBIOnPostLateUpdate\fP>()\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPostSimulate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPostSimulates = new List<\fBIOnPostSimulate\fP>()\fC [static]\fP"

.PP
Definition at line \fB28\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPostUpdate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPostUpdates = new List<\fBIOnPostUpdate\fP>()\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPreLateUpdate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPreLateUpdates = new List<\fBIOnPreLateUpdate\fP>()\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPreQuit\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPreQuits = new List<\fBIOnPreQuit\fP>()\fC [static]\fP"

.PP
Definition at line \fB33\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPreSimulate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPreSimulates = new List<\fBIOnPreSimulate\fP>()\fC [static]\fP"

.PP
Definition at line \fB27\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnPreUpdate\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onPreUpdates = new List<\fBIOnPreUpdate\fP>()\fC [static]\fP"

.PP
Definition at line \fB18\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnTickSnapshot\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onSnapshots = new List<\fBIOnTickSnapshot\fP>()\fC [static]\fP"

.PP
Definition at line \fB30\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "List<\fBIOnTickPreSerialization\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.onTickPreSerializations = new List<\fBIOnTickPreSerialization\fP>()\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "Queue<\fBDelayedRegistrationItem\fP> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.pendingRegistrations = new Queue<\fBDelayedRegistrationItem\fP>()\fC [static]\fP"

.PP
Definition at line \fB52\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "Queue<System\&.Action> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.postCallbackActions = new Queue<System\&.Action>()\fC [static]\fP"

.PP
Add delegates here that should be executed after the current callback timing segment has run\&. This is for deferring actions that would change the callback list\&. 
.PP
Definition at line \fB38\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "Queue<System\&.Action> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.postSerializationActions = new Queue<System\&.Action>()\fC [static]\fP"

.PP
Definition at line \fB44\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SS "Queue<System\&.Action> Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.postSimulateActions = new Queue<System\&.Action>()\fC [static]\fP"

.PP
Add delegates here that should be executed after the PostSimulation timing has run\&. 
.PP
Definition at line \fB42\fP of file \fBNetMasterCallbacks\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.NetMasterCallbacks\&.CallbacksLocked\fC [static]\fP, \fC [set]\fP"

.PP
Definition at line \fB87\fP of file \fBNetMasterCallbacks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
