.TH "Photon.Realtime.RaiseEventOptions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.RaiseEventOptions \- Aggregates several less-often used options for operation RaiseEvent\&. See field descriptions for usage details\&. 

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEventCaching\fP \fBCachingOption\fP"
.br
.RI "Defines if the server should simply send the event, put it in the cache or remove events that are like this one\&. "
.ti -1c
.RI "byte \fBInterestGroup\fP"
.br
.RI "The number of the Interest Group to send this to\&. 0 goes to all users but to get 1 and up, clients must subscribe to the group first\&."
.ti -1c
.RI "int[] \fBTargetActors\fP"
.br
.RI "A list of Player\&.ActorNumbers to send this event to\&. You can implement events that just go to specific users this way\&."
.ti -1c
.RI "\fBReceiverGroup\fP \fBReceivers\fP"
.br
.RI "Sends the event to All, MasterClient or Others (default)\&. Be careful with MasterClient, as the client might disconnect before it got the event and it gets lost\&."
.ti -1c
.RI "byte \fBSequenceChannel\fP"
.br
.RI "Events are ordered per 'channel'\&. If you have events that are independent of others, they can go into another sequence or channel\&."
.ti -1c
.RI "\fBWebFlags\fP \fBFlags\fP = \fBWebFlags\&.Default\fP"
.br
.RI "Optional flags to be used in \fBPhoton\fP client SDKs with Op RaiseEvent and Op SetProperties\&. "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBRaiseEventOptions\fP \fBDefault\fP = new \fBRaiseEventOptions\fP()"
.br
.RI "Default options: CachingOption: DoNotCache, InterestGroup: 0, targetActors: null, receivers: Others, sequenceChannel: 0\&."
.in -1c
.SH "Detailed Description"
.PP 
Aggregates several less-often used options for operation RaiseEvent\&. See field descriptions for usage details\&.
.PP
Definition at line \fB1926\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEventCaching\fP Photon\&.Realtime\&.RaiseEventOptions\&.CachingOption"

.PP
Defines if the server should simply send the event, put it in the cache or remove events that are like this one\&. When using option: SliceSetIndex, SlicePurgeIndex or SlicePurgeUpToIndex, set a CacheSliceIndex\&. All other options except SequenceChannel get ignored\&. 
.PP
Definition at line \fB1935\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "readonly \fBRaiseEventOptions\fP Photon\&.Realtime\&.RaiseEventOptions\&.Default = new \fBRaiseEventOptions\fP()\fC [static]\fP"

.PP
Default options: CachingOption: DoNotCache, InterestGroup: 0, targetActors: null, receivers: Others, sequenceChannel: 0\&.
.PP
Definition at line \fB1929\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBWebFlags\fP Photon\&.Realtime\&.RaiseEventOptions\&.Flags = \fBWebFlags\&.Default\fP"

.PP
Optional flags to be used in \fBPhoton\fP client SDKs with Op RaiseEvent and Op SetProperties\&. Introduced mainly for webhooks 1\&.2 to control behavior of forwarded HTTP requests\&.
.PP
Definition at line \fB1952\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "byte Photon\&.Realtime\&.RaiseEventOptions\&.InterestGroup"

.PP
The number of the Interest Group to send this to\&. 0 goes to all users but to get 1 and up, clients must subscribe to the group first\&.
.PP
Definition at line \fB1938\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBReceiverGroup\fP Photon\&.Realtime\&.RaiseEventOptions\&.Receivers"

.PP
Sends the event to All, MasterClient or Others (default)\&. Be careful with MasterClient, as the client might disconnect before it got the event and it gets lost\&.
.PP
Definition at line \fB1944\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "byte Photon\&.Realtime\&.RaiseEventOptions\&.SequenceChannel"

.PP
Events are ordered per 'channel'\&. If you have events that are independent of others, they can go into another sequence or channel\&.
.PP
Definition at line \fB1948\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "int [] Photon\&.Realtime\&.RaiseEventOptions\&.TargetActors"

.PP
A list of Player\&.ActorNumbers to send this event to\&. You can implement events that just go to specific users this way\&.
.PP
Definition at line \fB1941\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
