.TH "Photon.Pun.Simple.FrameBase" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.FrameBase \- Extend this base class for derived SyncObjectTFrame to include networked variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncContact\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncTransform\&.Frame\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncVitals\&.Frame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFrameBase\fP ()"
.br
.ti -1c
.RI "\fBFrameBase\fP (int \fBframeId\fP)"
.br
.ti -1c
.RI "virtual void \fBCopyFrom\fP (\fBFrameBase\fP sourceFrame)"
.br
.ti -1c
.RI "virtual void \fBClear\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TFrame \fBInstantiate< TFrame >\fP (int \fBframeId\fP)"
.br
.ti -1c
.RI "static void \fBPopulateFrames< TFrame >\fP (ref TFrame[] frames)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBframeId\fP"
.br
.ti -1c
.RI "\fBFrameContents\fP \fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extend this base class for derived SyncObjectTFrame to include networked variables\&. 


.PP
Definition at line \fB13\fP of file \fBFrameBase\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.FrameBase\&.FrameBase ()"

.PP
Definition at line \fB19\fP of file \fBFrameBase\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.FrameBase\&.FrameBase (int frameId)"

.PP
Definition at line \fB23\fP of file \fBFrameBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Photon\&.Pun\&.Simple\&.FrameBase\&.Clear ()\fC [virtual]\fP"

.PP
Reimplemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\&.Frame\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncTransform\&.Frame\fP\&.
.PP
Definition at line \fB41\fP of file \fBFrameBase\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.FrameBase\&.CopyFrom (\fBFrameBase\fP sourceFrame)\fC [virtual]\fP"

.PP
Reimplemented in \fBPhoton\&.Pun\&.Simple\&.SyncContact\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncShootBase\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncVitals\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncAnimator\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncNodeMover\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncOwner\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\&.Frame\fP, \fBPhoton\&.Pun\&.Simple\&.SyncState\&.Frame\fP, and \fBPhoton\&.Pun\&.Simple\&.SyncTransform\&.Frame\fP\&.
.PP
Definition at line \fB35\fP of file \fBFrameBase\&.cs\fP\&.
.SS "static TFrame Photon\&.Pun\&.Simple\&.FrameBase\&.Instantiate< TFrame > (int frameId)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fITFrame\fP : \fIFrameBase\fP
.PP
Definition at line \fB28\fP of file \fBFrameBase\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.FrameBase\&.PopulateFrames< TFrame > (ref TFrame[] frames)\fC [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fITFrame\fP : \fIFrameBase\fP
.PP
Definition at line \fB46\fP of file \fBFrameBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFrameContents\fP Photon\&.Pun\&.Simple\&.FrameBase\&.content"

.PP
Definition at line \fB16\fP of file \fBFrameBase\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.FrameBase\&.frameId"

.PP
Definition at line \fB15\fP of file \fBFrameBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
