.TH "Photon.Pun.UtilityScripts.OnClickDestroy" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.OnClickDestroy \- Destroys the networked GameObject either by \fBPhotonNetwork\&.Destroy\fP or by sending an RPC which calls Object\&.Destroy()\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IEnumerator \fBDestroyRpc\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PointerEventData\&.InputButton \fBButton\fP"
.br
.ti -1c
.RI "KeyCode \fBModifierKey\fP"
.br
.ti -1c
.RI "bool \fBDestroyByRpc\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Destroys the networked GameObject either by \fBPhotonNetwork\&.Destroy\fP or by sending an RPC which calls Object\&.Destroy()\&. 

Using an RPC to Destroy a GameObject is typically a bad idea\&. It allows any player to Destroy a GameObject and may cause errors\&.
.PP
A client has to clean up the server's event-cache, which contains events for Instantiate and buffered RPCs related to the GO\&.
.PP
A buffered RPC gets cleaned up when the sending player leaves the room, so players joining later won't get those buffered RPCs\&. This in turn, may mean they don't destroy the GO due to coming later\&.
.PP
Vice versa, a GameObject Instantiate might get cleaned up when the creating player leaves a room\&. This way, the GameObject that a RPC targets might become lost\&.
.PP
It makes sense to test those cases\&. Many are not breaking errors and you just have to be aware of them\&.
.PP
Gets OnClick() calls by Unity's IPointerClickHandler\&. Needs a PhysicsRaycaster on the camera\&. See: https://docs.unity3d.com/ScriptReference/EventSystems.IPointerClickHandler.html 
.PP
Definition at line \fB38\fP of file \fBOnClickDestroy\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "IEnumerator Photon\&.Pun\&.UtilityScripts\&.OnClickDestroy\&.DestroyRpc ()"

.PP
Definition at line \fB66\fP of file \fBOnClickDestroy\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PointerEventData\&.InputButton Photon\&.Pun\&.UtilityScripts\&.OnClickDestroy\&.Button"

.PP
Definition at line \fB40\fP of file \fBOnClickDestroy\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.OnClickDestroy\&.DestroyByRpc"

.PP
Definition at line \fB43\fP of file \fBOnClickDestroy\&.cs\fP\&.
.SS "KeyCode Photon\&.Pun\&.UtilityScripts\&.OnClickDestroy\&.ModifierKey"

.PP
Definition at line \fB41\fP of file \fBOnClickDestroy\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
