.TH "Photon.Pun.Simple.HitscanComponent" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.HitscanComponent \- Starting class for Generic Hitscan component implementation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.AutoMountHitscan\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "virtual void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.ti -1c
.RI "virtual void \fBProcessHits\fP (Collider[] hits, int hitcount)"
.br
.ti -1c
.RI "abstract bool \fBProcessHit\fP (Collider hit)"
.br
.RI "Handling for processing each hit returned by the hitscan\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBorigin\fP"
.br
.ti -1c
.RI "\fBHitscanDefinition\fP \fBhitscanDefinition\fP = new \fBHitscanDefinition\fP()"
.br
.ti -1c
.RI "bool \fBignoreSelf\fP = true"
.br
.ti -1c
.RI "bool \fBvisualize\fP = false"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBtriggerQueued\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Starting class for Generic Hitscan component implementation\&. 


.PP
Definition at line \fB13\fP of file \fBHitscanComponent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.HitscanComponent\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB44\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.HitscanComponent\&.OnPreSimulate (int frameId, int subFrameId)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Reimplemented in \fBPhoton\&.Pun\&.Simple\&.AutoMountHitscan\fP\&.
.PP
Definition at line \fB52\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "abstract bool Photon\&.Pun\&.Simple\&.HitscanComponent\&.ProcessHit (Collider hit)\fC [pure virtual]\fP"

.PP
Handling for processing each hit returned by the hitscan\&. 
.PP
\fBParameters\fP
.RS 4
\fIhit\fP 
.RE
.PP
\fBReturns\fP
.RS 4
Return true to terminate processing any more hits\&.
.RE
.PP

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.AutoMountHitscan\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.HitscanComponent\&.ProcessHits (Collider[] hits, int hitcount)\fC [virtual]\fP"

.PP
Definition at line \fB73\fP of file \fBHitscanComponent\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHitscanDefinition\fP Photon\&.Pun\&.Simple\&.HitscanComponent\&.hitscanDefinition = new \fBHitscanDefinition\fP()"

.PP
Definition at line \fB20\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.HitscanComponent\&.ignoreSelf = true"

.PP
Definition at line \fB23\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "GameObject Photon\&.Pun\&.Simple\&.HitscanComponent\&.origin"

.PP
Definition at line \fB18\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.HitscanComponent\&.triggerQueued\fC [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBHitscanComponent\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.HitscanComponent\&.visualize = false"

.PP
Definition at line \fB26\fP of file \fBHitscanComponent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
