.TH "Photon.Compression.WorldBoundsGroup" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.WorldBoundsGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResetActiveBounds\fP ()"
.br
.ti -1c
.RI "void \fBRecalculateWorldCombinedBounds\fP ()"
.br
.RI "Whenever an instance of WorldBoundss gets removed, the combinedWorldBounds needs to be rebuilt with this\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBElementCrusher\fP \fBGetUncompressedCrusher\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP = \fBdefaultName\fP"
.br
.ti -1c
.RI "System\&.Action \fBOnWorldBoundChanged\fP"
.br
.ti -1c
.RI "\fBElementCrusher\fP \fBcrusher\fP = \fBGetUncompressedCrusher\fP()"
.br
.ti -1c
.RI "readonly List< \fBWorldBounds\fP > \fBactiveWorldBounds\fP = new List<\fBWorldBounds\fP>()"
.br
.ti -1c
.RI "Bounds \fB_combinedWorldBounds\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBdefaultName\fP = 'Default'"
.br
.ti -1c
.RI "const string \fBnewAddName\fP = 'Unnamed'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBActiveBoundsObjCount\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBElementCrusher\fP Photon\&.Compression\&.WorldBoundsGroup\&.GetUncompressedCrusher ()\fC [static]\fP"

.PP
Definition at line \fB43\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "void Photon\&.Compression\&.WorldBoundsGroup\&.RecalculateWorldCombinedBounds ()"

.PP
Whenever an instance of WorldBoundss gets removed, the combinedWorldBounds needs to be rebuilt with this\&. When we have bounds for a group, switch back to Resolution mode if we are in a mode hostile to trying to set things
.PP
Definition at line \fB63\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "void Photon\&.Compression\&.WorldBoundsGroup\&.ResetActiveBounds ()"

.PP
Definition at line \fB55\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Bounds Photon\&.Compression\&.WorldBoundsGroup\&._combinedWorldBounds"

.PP
Definition at line \fB41\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "readonly List<\fBWorldBounds\fP> Photon\&.Compression\&.WorldBoundsGroup\&.activeWorldBounds = new List<\fBWorldBounds\fP>()"

.PP
Definition at line \fB34\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "\fBElementCrusher\fP Photon\&.Compression\&.WorldBoundsGroup\&.crusher = \fBGetUncompressedCrusher\fP()"

.PP
Definition at line \fB29\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "const string Photon\&.Compression\&.WorldBoundsGroup\&.defaultName = 'Default'\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "string Photon\&.Compression\&.WorldBoundsGroup\&.name = \fBdefaultName\fP"

.PP
Definition at line \fB23\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "const string Photon\&.Compression\&.WorldBoundsGroup\&.newAddName = 'Unnamed'\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SS "System\&.Action Photon\&.Compression\&.WorldBoundsGroup\&.OnWorldBoundChanged"

.PP
Definition at line \fB26\fP of file \fBWorldBoundsGroup\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Compression\&.WorldBoundsGroup\&.ActiveBoundsObjCount\fC [get]\fP"

.PP
Definition at line \fB38\fP of file \fBWorldBoundsGroup\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
