.TH "Photon.Compression.PackObjectSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.PackObjectSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Utilities\&.SettingsScriptableObject< PackObjectSettings >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBBootstrap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBautoGenerate\fP = true"
.br
.ti -1c
.RI "bool \fBdeleteBadCode\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBPackObjectSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.PackObjectSettings\&.Bootstrap ()\fC [static]\fP"

.PP
Definition at line \fB46\fP of file \fBPackObjectSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Compression\&.PackObjectSettings\&.autoGenerate = true"

.PP
Definition at line \fB40\fP of file \fBPackObjectSettings\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.PackObjectSettings\&.deleteBadCode = true"

.PP
Definition at line \fB43\fP of file \fBPackObjectSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
