.TH "Photon.Pun.Simple.IOnVitalChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnVitalChange
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.IOnVitalParamChange\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnVitalValueChange\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBIOnVitalChange\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
