.TH "Photon.Pun.Demo.SlotRacer.Utils" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.Utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBezier\fP"
.br
.ti -1c
.RI "class \fBBezierCurve\fP"
.br
.ti -1c
.RI "class \fBBezierCurveInspector\fP"
.br
.ti -1c
.RI "class \fBBezierSpline\fP"
.br
.ti -1c
.RI "class \fBBezierSplineInspector\fP"
.br
.ti -1c
.RI "class \fBLine\fP"
.br
.ti -1c
.RI "class \fBLineInspector\fP"
.br
.ti -1c
.RI "class \fBSplinePosition\fP"
.br
.ti -1c
.RI "class \fBSplineWalker\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBezierControlPointMode\fP { \fBFree\fP, \fBAligned\fP, \fBMirrored\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Demo\&.SlotRacer\&.Utils\&.BezierControlPointMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFree \fP\fP
.TP
\fB\fIAligned \fP\fP
.TP
\fB\fIMirrored \fP\fP
.PP
Definition at line \fB14\fP of file \fBBezierControlPointMode\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
