.TH "Photon.Pun.Simple.Internal.NetMsgCallbacks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Internal.NetMsgCallbacks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBByteBufferCallback\fP (object conn, int connId, byte[] buffer)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOnEvent\fP (EventData photonEvent)"
.br
.RI "Capture incoming \fBPhoton\fP messages here\&. "
.ti -1c
.RI "static void \fBRegisterCallback\fP (byte msgid, \fBByteBufferCallback\fP callback, bool asServer)"
.br
.ti -1c
.RI "static void \fBRegisterCallback\fP (\fBByteBufferCallback\fP callback)"
.br
.ti -1c
.RI "static void \fBRegisterCallback\fP (byte msgid, \fBByteBufferCallback\fP callback)"
.br
.ti -1c
.RI "static void \fBUnregisterCallback\fP (byte msgid, \fBByteBufferCallback\fP callback, bool asServer)"
.br
.ti -1c
.RI "static void \fBUnregisterCallback\fP (\fBByteBufferCallback\fP callback)"
.br
.ti -1c
.RI "static void \fBUnregisterCallback\fP (byte msgid, \fBByteBufferCallback\fP callback)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBDEF_MSG_ID\fP = 215"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "delegate void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.ByteBufferCallback (object conn, int connId, byte[] buffer)"

.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.OnEvent (EventData photonEvent)\fC [static]\fP"

.PP
Capture incoming \fBPhoton\fP messages here\&. 
.PP
Definition at line \fB40\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.RegisterCallback (byte msgid, \fBByteBufferCallback\fP callback)\fC [static]\fP"

.PP
Definition at line \fB103\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.RegisterCallback (byte msgid, \fBByteBufferCallback\fP callback, bool asServer)\fC [static]\fP"

.PP
Definition at line \fB85\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.RegisterCallback (\fBByteBufferCallback\fP callback)\fC [static]\fP"

.PP
Definition at line \fB99\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.UnregisterCallback (byte msgid, \fBByteBufferCallback\fP callback)\fC [static]\fP"

.PP
Definition at line \fB134\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.UnregisterCallback (byte msgid, \fBByteBufferCallback\fP callback, bool asServer)\fC [static]\fP"

.PP
Definition at line \fB118\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.UnregisterCallback (\fBByteBufferCallback\fP callback)\fC [static]\fP"

.PP
Definition at line \fB130\fP of file \fBNetMsgCallbacks\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Pun\&.Simple\&.Internal\&.NetMsgCallbacks\&.DEF_MSG_ID = 215\fC [static]\fP"

.PP
Definition at line \fB29\fP of file \fBNetMsgCallbacks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
