.TH "Photon.Pun.Demo.SlotRacer.SlotRacerSplashScreen" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.SlotRacer.SlotRacerSplashScreen \- Slot racer splash screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBWarningText\fP"
.br
.ti -1c
.RI "GameObject \fBSplashScreen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Slot racer splash screen\&. 

Inform about the slotRacer demo and the \fBCockpit\fP control setup Gets deleted as soon as the scene plays 
.PP
Definition at line \fB27\fP of file \fBSlotRacerSplashScreen\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.SlotRacer\&.SlotRacerSplashScreen\&.Update ()"

.PP
Definition at line \fB45\fP of file \fBSlotRacerSplashScreen\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Photon\&.Pun\&.Demo\&.SlotRacer\&.SlotRacerSplashScreen\&.SplashScreen"

.PP
Definition at line \fB34\fP of file \fBSlotRacerSplashScreen\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.SlotRacer\&.SlotRacerSplashScreen\&.WarningText"

.PP
Definition at line \fB33\fP of file \fBSlotRacerSplashScreen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
