.TH "Photon.Pun.Simple.MountThrow" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.MountThrow
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "void \fBOnPreUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnPreSimulate\fP (int frameId, int subFrameId)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "KeyCode \fBthrowKey\fP"
.br
.ti -1c
.RI "\fBMount\fP \fBmount\fP"
.br
.ti -1c
.RI "bool \fBfromRoot\fP = true"
.br
.ti -1c
.RI "bool \fBinheritRBVelocity\fP = true"
.br
.ti -1c
.RI "Vector3 \fBoffset\fP = new Vector3(0, 3f, 0)"
.br
.ti -1c
.RI "Vector3 \fBvelocity\fP = new Vector3(0, 1f, 5f)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBMountThrow\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.MountThrow\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB37\fP of file \fBMountThrow\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountThrow\&.OnPreSimulate (int frameId, int subFrameId)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreSimulate\fP\&.
.PP
Definition at line \fB56\fP of file \fBMountThrow\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.MountThrow\&.OnPreUpdate ()"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnPreUpdate\fP\&.
.PP
Definition at line \fB45\fP of file \fBMountThrow\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.MountThrow\&.fromRoot = true"

.PP
Definition at line \fB24\fP of file \fBMountThrow\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.MountThrow\&.inheritRBVelocity = true"

.PP
Definition at line \fB25\fP of file \fBMountThrow\&.cs\fP\&.
.SS "\fBMount\fP Photon\&.Pun\&.Simple\&.MountThrow\&.mount"

.PP
Definition at line \fB22\fP of file \fBMountThrow\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.MountThrow\&.offset = new Vector3(0, 3f, 0)"

.PP
Definition at line \fB26\fP of file \fBMountThrow\&.cs\fP\&.
.SS "KeyCode Photon\&.Pun\&.Simple\&.MountThrow\&.throwKey"

.PP
Definition at line \fB21\fP of file \fBMountThrow\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.MountThrow\&.velocity = new Vector3(0, 1f, 5f)"

.PP
Definition at line \fB27\fP of file \fBMountThrow\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
