.TH "Photon.Pun.UtilityScripts.TabViewManager.Tab" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.TabViewManager.Tab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBID\fP = ''"
.br
.ti -1c
.RI "Toggle \fBToggle\fP"
.br
.ti -1c
.RI "RectTransform \fBView\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBTabViewManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.Tab\&.ID = ''"

.PP
Definition at line \fB37\fP of file \fBTabViewManager\&.cs\fP\&.
.SS "Toggle Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.Tab\&.Toggle"

.PP
Definition at line \fB38\fP of file \fBTabViewManager\&.cs\fP\&.
.SS "RectTransform Photon\&.Pun\&.UtilityScripts\&.TabViewManager\&.Tab\&.View"

.PP
Definition at line \fB39\fP of file \fBTabViewManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
