.TH "Photon.Pun.Demo.Cockpit.RegionListCell" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.RegionListCell \- Region list cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBRegion\fP info)"
.br
.ti -1c
.RI "void \fBAddToList\fP (\fBRegion\fP info, int index)"
.br
.ti -1c
.RI "void \fBRemoveFromList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRegionListView\fP \fBListManager\fP"
.br
.ti -1c
.RI "Text \fBCodeText\fP"
.br
.ti -1c
.RI "Text \fBIpText\fP"
.br
.ti -1c
.RI "Text \fBPingText\fP"
.br
.ti -1c
.RI "LayoutElement \fBLayoutElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Region list cell\&. 


.PP
Definition at line \fB20\fP of file \fBRegionListCell\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.AddToList (\fBRegion\fP info, int index)"

.PP
Definition at line \fB42\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.RefreshInfo (\fBRegion\fP info)"

.PP
Definition at line \fB34\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.RemoveFromList ()"

.PP
Definition at line \fB51\fP of file \fBRegionListCell\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.CodeText"

.PP
Definition at line \fB24\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.IpText"

.PP
Definition at line \fB25\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "LayoutElement Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.LayoutElement"

.PP
Definition at line \fB28\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "\fBRegionListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.ListManager"

.PP
Definition at line \fB22\fP of file \fBRegionListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RegionListCell\&.PingText"

.PP
Definition at line \fB26\fP of file \fBRegionListCell\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
