.TH "Photon.Pun.Demo.Cockpit.RoomListCell" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.RoomListCell \- Roomlist cell\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBRoomInfo\fP \fBinfo\fP)"
.br
.ti -1c
.RI "void \fBOnJoinRoomButtonClick\fP ()"
.br
.ti -1c
.RI "void \fBAddToList\fP (\fBRoomInfo\fP \fBinfo\fP, bool animate=false)"
.br
.ti -1c
.RI "void \fBRemoveFromList\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRoomListView\fP \fBListManager\fP"
.br
.ti -1c
.RI "Text \fBRoomNameText\fP"
.br
.ti -1c
.RI "Text \fBPlayerCountText\fP"
.br
.ti -1c
.RI "Text \fBOpenText\fP"
.br
.ti -1c
.RI "CanvasGroup \fBJoinButtonCanvasGroup\fP"
.br
.ti -1c
.RI "LayoutElement \fBLayoutElement\fP"
.br
.ti -1c
.RI "\fBRoomInfo\fP \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Roomlist cell\&. 


.PP
Definition at line \fB20\fP of file \fBRoomListCell\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.AddToList (\fBRoomInfo\fP info, bool animate = \fCfalse\fP)"

.PP
Definition at line \fB60\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.OnJoinRoomButtonClick ()"

.PP
Definition at line \fB54\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.RefreshInfo (\fBRoomInfo\fP info)"

.PP
Definition at line \fB32\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.RemoveFromList ()"

.PP
Definition at line \fB74\fP of file \fBRoomListCell\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRoomInfo\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.info"

.PP
Definition at line \fB30\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "CanvasGroup Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.JoinButtonCanvasGroup"

.PP
Definition at line \fB27\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "LayoutElement Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.LayoutElement"

.PP
Definition at line \fB28\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "\fBRoomListView\fP Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.ListManager"

.PP
Definition at line \fB22\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.OpenText"

.PP
Definition at line \fB26\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.PlayerCountText"

.PP
Definition at line \fB25\fP of file \fBRoomListCell\&.cs\fP\&.
.SS "Text Photon\&.Pun\&.Demo\&.Cockpit\&.RoomListCell\&.RoomNameText"

.PP
Definition at line \fB24\fP of file \fBRoomListCell\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
