.TH "Photon.Realtime.LoadBalancingClient" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.LoadBalancingClient \- This class implements the \fBPhoton\fP LoadBalancing workflow by using a \fBLoadBalancingPeer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IPhotonPeerListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadBalancingClient\fP (ConnectionProtocol protocol=ConnectionProtocol\&.Udp)"
.br
.RI "Creates a \fBLoadBalancingClient\fP with UDP protocol or the one specified\&. "
.ti -1c
.RI "\fBLoadBalancingClient\fP (string masterAddress, string appId, string gameVersion, ConnectionProtocol protocol=ConnectionProtocol\&.Udp)"
.br
.RI "Creates a \fBLoadBalancingClient\fP, setting various values needed before connecting\&. "
.ti -1c
.RI "virtual bool \fBConnectUsingSettings\fP (\fBAppSettings\fP appSettings)"
.br
.ti -1c
.RI "bool \fBConnect\fP ()"
.br
.ti -1c
.RI "virtual bool \fBConnectToMasterServer\fP ()"
.br
.RI "Starts the 'process' to connect to a Master Server, using MasterServerAddress and AppId properties\&. "
.ti -1c
.RI "bool \fBConnectToNameServer\fP ()"
.br
.RI "Connects to the NameServer for \fBPhoton\fP Cloud, where a region and server list can be obtained\&. "
.ti -1c
.RI "bool \fBConnectToRegionMaster\fP (string region)"
.br
.RI "Connects you to a specific region's Master Server, using the Name Server to find the IP\&. "
.ti -1c
.RI "bool \fBReconnectToMaster\fP ()"
.br
.RI "Can be used to reconnect to the master server after a disconnect\&. "
.ti -1c
.RI "bool \fBReconnectAndRejoin\fP ()"
.br
.RI "Can be used to return to a room quickly by directly reconnecting to a game server to rejoin a room\&. "
.ti -1c
.RI "void \fBDisconnect\fP (\fBDisconnectCause\fP cause=\fBDisconnectCause\&.DisconnectByClientLogic\fP)"
.br
.RI "Disconnects the peer from a server or stays disconnected\&. "
.ti -1c
.RI "void \fBSimulateConnectionLoss\fP (bool simulateTimeout)"
.br
.RI "Useful to test loss of connection which will end in a client timeout\&. "
.ti -1c
.RI "void \fBService\fP ()"
.br
.RI "This method dispatches all available incoming commands and then sends this client's outgoing commands\&. "
.ti -1c
.RI "bool \fBOpFindFriends\fP (string[] friendsToFind, \fBFindFriendsOptions\fP options=null)"
.br
.RI "Request the rooms and online status for a list of friends\&. "
.ti -1c
.RI "bool \fBOpJoinLobby\fP (\fBTypedLobby\fP lobby)"
.br
.RI "If already connected to a Master Server, this joins the specified lobby\&. "
.ti -1c
.RI "bool \fBOpLeaveLobby\fP ()"
.br
.RI "Opposite of joining a lobby\&. "
.ti -1c
.RI "bool \fBOpJoinRandomRoom\fP (\fBOpJoinRandomRoomParams\fP opJoinRandomRoomParams=null)"
.br
.RI "Joins a random room that matches the filter\&. "
.ti -1c
.RI "bool \fBOpJoinRandomOrCreateRoom\fP (\fBOpJoinRandomRoomParams\fP opJoinRandomRoomParams, \fBEnterRoomParams\fP createRoomParams)"
.br
.RI "Attempts to join a room that matches the specified filter and creates a room if none found\&. "
.ti -1c
.RI "bool \fBOpCreateRoom\fP (\fBEnterRoomParams\fP enterRoomParams)"
.br
.RI "Creates a new room\&. "
.ti -1c
.RI "bool \fBOpJoinOrCreateRoom\fP (\fBEnterRoomParams\fP enterRoomParams)"
.br
.RI "Joins a specific room by name and creates it on demand\&. "
.ti -1c
.RI "bool \fBOpJoinRoom\fP (\fBEnterRoomParams\fP enterRoomParams)"
.br
.RI "Joins a room by name\&. "
.ti -1c
.RI "bool \fBOpRejoinRoom\fP (string roomName)"
.br
.RI "Rejoins a room by roomName (using the userID internally to return)\&. "
.ti -1c
.RI "bool \fBOpLeaveRoom\fP (bool becomeInactive, bool sendAuthCookie=false)"
.br
.RI "Leaves the current room, optionally telling the server that the user is just becoming inactive\&. "
.ti -1c
.RI "bool \fBOpGetGameList\fP (\fBTypedLobby\fP typedLobby, string sqlLobbyFilter)"
.br
.RI "Gets a list of rooms matching the (non empty) SQL filter for the given SQL-typed lobby\&. "
.ti -1c
.RI "bool \fBOpSetCustomPropertiesOfActor\fP (int actorNr, \fBHashtable\fP propertiesToSet, \fBHashtable\fP expectedProperties=null, \fBWebFlags\fP webFlags=null)"
.br
.RI "Updates and synchronizes a \fBPlayer\fP's Custom Properties\&. "
.ti -1c
.RI "bool \fBOpSetCustomPropertiesOfRoom\fP (\fBHashtable\fP propertiesToSet, \fBHashtable\fP expectedProperties=null, \fBWebFlags\fP webFlags=null)"
.br
.RI "Updates and synchronizes this \fBRoom\fP's Custom Properties\&. "
.ti -1c
.RI "virtual bool \fBOpRaiseEvent\fP (byte eventCode, object customEventContent, \fBRaiseEventOptions\fP raiseEventOptions, SendOptions sendOptions)"
.br
.RI "Send an event with custom code/type and any content to the other players in the same room\&. "
.ti -1c
.RI "virtual bool \fBOpChangeGroups\fP (byte[] groupsToRemove, byte[] groupsToAdd)"
.br
.RI "Operation to handle this client's interest groups (for events in room)\&. "
.ti -1c
.RI "void \fBChangeLocalID\fP (int newID)"
.br
.RI "Internally used to set the LocalPlayer's ID (from -1 to the actual in-room ID)\&. "
.ti -1c
.RI "virtual void \fBDebugReturn\fP (DebugLevel level, string message)"
.br
.RI "Debug output of low level api (and this client)\&. "
.ti -1c
.RI "virtual void \fBOnOperationResponse\fP (OperationResponse operationResponse)"
.br
.RI "Uses the OperationResponses provided by the server to advance the internal state and call ops as needed\&. "
.ti -1c
.RI "virtual void \fBOnStatusChanged\fP (StatusCode statusCode)"
.br
.RI "Uses the connection's statusCodes to advance the internal state and call operations as needed\&. "
.ti -1c
.RI "virtual void \fBOnEvent\fP (EventData photonEvent)"
.br
.RI "Uses the photonEvent's provided by the server to advance the internal state and call ops as needed\&. "
.ti -1c
.RI "virtual void \fBOnMessage\fP (object message)"
.br
.RI "In \fBPhoton\fP 4, 'raw messages' will get their own callback method in the interface\&. Not used yet\&."
.ti -1c
.RI "bool \fBOpWebRpc\fP (string uriPath, object parameters, bool sendAuthCookie=false)"
.br
.RI "This operation makes \fBPhoton\fP call your custom web-service by path/name with the given parameters (converted into Json)\&. "
.ti -1c
.RI "void \fBAddCallbackTarget\fP (object target)"
.br
.RI "Registers an object for callbacks for the implemented callback-interfaces\&. "
.ti -1c
.RI "void \fBRemoveCallbackTarget\fP (object target)"
.br
.RI "Unregisters an object from callbacks for the implemented callback-interfaces\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAuthModeOption\fP \fBAuthMode\fP = \fBAuthModeOption\&.Auth\fP"
.br
.RI "Enables the new Authentication workflow\&."
.ti -1c
.RI "\fBEncryptionMode\fP \fBEncryptionMode\fP = \fBEncryptionMode\&.PayloadEncryption\fP"
.br
.RI "Defines how the communication gets encrypted\&."
.ti -1c
.RI "string \fBNameServerHost\fP = 'ns\&.photonengine\&.io'"
.br
.RI "Name Server Host Name for \fBPhoton\fP Cloud\&. Without port and without any prefix\&."
.ti -1c
.RI "\fBPhotonPortDefinition\fP \fBServerPortOverrides\fP"
.br
.RI "Defines overrides for server ports\&. "
.ti -1c
.RI "string \fBProxyServerAddress\fP"
.br
.RI "Defines a proxy URL for WebSocket connections\&. "
.ti -1c
.RI "\fBConnectionCallbacksContainer\fP \fBConnectionCallbackTargets\fP"
.br
.RI "Wraps up the target objects for a group of callbacks, so they can be called conveniently\&. "
.ti -1c
.RI "\fBMatchMakingCallbacksContainer\fP \fBMatchMakingCallbackTargets\fP"
.br
.RI "Wraps up the target objects for a group of callbacks, so they can be called conveniently\&. "
.ti -1c
.RI "bool \fBEnableLobbyStatistics\fP"
.br
.RI "If enabled, the client will get a list of available lobbies from the Master Server\&. "
.ti -1c
.RI "\fBRegionHandler\fP \fBRegionHandler\fP"
.br
.RI "Contains the list if enabled regions this client may use\&. Null, unless the client got a response to OpGetRegions\&."
.ti -1c
.RI "string \fBSummaryToCache\fP"
.br
.RI "Set when the best region pinging is done\&."
.ti -1c
.RI "int \fBNameServerPortInAppSettings\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLoadBalancingPeer\fP \fBLoadBalancingPeer\fP\fC [get]\fP"
.br
.RI "The client uses a \fBLoadBalancingPeer\fP as API to communicate with the server\&. "
.ti -1c
.RI "SerializationProtocol \fBSerializationProtocol\fP\fC [getset]\fP"
.br
.RI "Gets or sets the binary protocol version used by this client "
.ti -1c
.RI "string \fBAppVersion\fP\fC [getset]\fP"
.br
.RI "The version of your client\&. A new version also creates a new 'virtual app' to separate players from older client versions\&."
.ti -1c
.RI "string \fBAppId\fP\fC [getset]\fP"
.br
.RI "The AppID as assigned from the \fBPhoton\fP Cloud\&. If you host yourself, this is the 'regular' \fBPhoton\fP Server Application Name (most likely: 'LoadBalancing')\&."
.ti -1c
.RI "\fBClientAppType\fP \fBClientType\fP\fC [getset]\fP"
.br
.RI "The ClientAppType defines which sort of AppId should be expected\&. The \fBLoadBalancingClient\fP supports \fBRealtime\fP and Voice app types\&. Default: \fBRealtime\fP\&."
.ti -1c
.RI "\fBAuthenticationValues\fP \fBAuthValues\fP\fC [getset]\fP"
.br
.RI "User authentication values to be sent to the \fBPhoton\fP server right after connecting\&. "
.ti -1c
.RI "ConnectionProtocol? \fBExpectedProtocol\fP\fC [getset]\fP"
.br
.RI "Optionally contains a protocol which will be used on Master- and GameServer\&. "
.ti -1c
.RI "bool \fBIsUsingNameServer\fP\fC [getset]\fP"
.br
.RI "True if this client uses a NameServer to get the Master Server address\&. "
.ti -1c
.RI "string \fBNameServerAddress\fP\fC [get]\fP"
.br
.RI "Name Server Address for \fBPhoton\fP Cloud (based on current protocol)\&. You can use the default values and usually won't have to set this value\&."
.ti -1c
.RI "bool \fBUseAlternativeUdpPorts\fP\fC [getset]\fP"
.br
.RI "Replaced by ServerPortOverrides\&."
.ti -1c
.RI "bool \fBEnableProtocolFallback\fP\fC [getset]\fP"
.br
.RI "Enables a fallback to another protocol in case a connect to the Name Server fails\&. "
.ti -1c
.RI "string \fBCurrentServerAddress\fP\fC [get]\fP"
.br
.RI "The currently used server address (if any)\&. The type of server is define by Server property\&."
.ti -1c
.RI "string \fBMasterServerAddress\fP\fC [getset]\fP"
.br
.RI "Your Master Server address\&. "
.ti -1c
.RI "string \fBGameServerAddress\fP\fC [getset]\fP"
.br
.RI "The game server's address for a particular room\&. In use temporarily, as assigned by master\&."
.ti -1c
.RI "\fBServerConnection\fP \fBServer\fP\fC [get]\fP"
.br
.RI "The server this client is currently connected or connecting to\&. "
.ti -1c
.RI "\fBClientState\fP \fBState\fP\fC [getset]\fP"
.br
.RI "Current state this client is in\&. Careful: several states are 'transitions' that lead to other states\&."
.ti -1c
.RI "bool \fBIsConnected\fP\fC [get]\fP"
.br
.RI "Returns if this client is currently connected or connecting to some type of server\&. "
.ti -1c
.RI "bool \fBIsConnectedAndReady\fP\fC [get]\fP"
.br
.RI "A refined version of IsConnected which is true only if your connection is ready to send operations\&. "
.ti -1c
.RI "\fBDisconnectCause\fP \fBDisconnectedCause\fP\fC [getprotected set]\fP"
.br
.RI "Summarizes (aggregates) the different causes for disconnects of a client\&. "
.ti -1c
.RI "bool \fBInLobby\fP\fC [get]\fP"
.br
.RI "Internal value if the client is in a lobby\&. "
.ti -1c
.RI "\fBTypedLobby\fP \fBCurrentLobby\fP\fC [getset]\fP"
.br
.RI "The lobby this client currently uses\&. Defined when joining a lobby or creating rooms"
.ti -1c
.RI "\fBPlayer\fP \fBLocalPlayer\fP\fC [getset]\fP"
.br
.RI "The local player is never null but not valid unless the client is in a room, too\&. The ID will be -1 outside of rooms\&."
.ti -1c
.RI "string \fBNickName\fP\fC [getset]\fP"
.br
.RI "The nickname of the player (synced with others)\&. "
.ti -1c
.RI "string \fBUserId\fP\fC [getset]\fP"
.br
.RI "An ID for this user\&. "
.ti -1c
.RI "\fBRoom\fP \fBCurrentRoom\fP\fC [getset]\fP"
.br
.RI "The current room this client is connected to (null if none available)\&."
.ti -1c
.RI "bool \fBInRoom\fP\fC [get]\fP"
.br
.RI "Is true while being in a room (this\&.state == \fBClientState\&.Joined\fP)\&. "
.ti -1c
.RI "int \fBPlayersOnMasterCount\fP\fC [getset]\fP"
.br
.RI "Statistic value available on master server: Players on master (looking for games)\&."
.ti -1c
.RI "int \fBPlayersInRoomsCount\fP\fC [getset]\fP"
.br
.RI "Statistic value available on master server: Players in rooms (playing)\&."
.ti -1c
.RI "int \fBRoomsCount\fP\fC [getset]\fP"
.br
.RI "Statistic value available on master server: Rooms currently created\&."
.ti -1c
.RI "bool \fBIsFetchingFriendList\fP\fC [get]\fP"
.br
.RI "Internal flag to know if the client currently fetches a friend list\&."
.ti -1c
.RI "string \fBCloudRegion\fP\fC [get]\fP"
.br
.RI "The cloud region this client connects to\&. Set by \fBConnectToRegionMaster()\fP\&. Not set if you don't use a NameServer!"
.ti -1c
.RI "string \fBCurrentCluster\fP\fC [get]\fP"
.br
.RI "The cluster name provided by the Name Server\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action< \fBClientState\fP, \fBClientState\fP > \fBStateChanged\fP"
.br
.RI "Register a method to be called when this client's ClientState gets set\&. "
.ti -1c
.RI "Action< EventData > \fBEventReceived\fP"
.br
.RI "Register a method to be called when an event got dispatched\&. "
.ti -1c
.RI "Action< OperationResponse > \fBOpResponseReceived\fP"
.br
.RI "Register a method to be called when an operation response is received\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class implements the \fBPhoton\fP LoadBalancing workflow by using a \fBLoadBalancingPeer\fP\&. 

It keeps a state and will automatically execute transitions between the Master and Game Servers\&. 
.PP
This class (and the \fBPlayer\fP class) should be extended to implement your own game logic\&. You can override CreatePlayer as 'factory' method for Players and return your own \fBPlayer\fP instances\&. The State of this class is essential to know when a client is in a lobby (or just on the master) and when in a game where the actual gameplay should take place\&. Extension notes: An extension of this class should override the methods of the IPhotonPeerListener, as they are called when the state changes\&. Call base\&.method first, then pick the operation or state you want to react to and put it in a switch-case\&. We try to provide demo to each platform where this api can be used, so lookout for those\&. 
.PP
Definition at line \fB278\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Realtime\&.LoadBalancingClient\&.LoadBalancingClient (ConnectionProtocol protocol = \fCConnectionProtocol\&.Udp\fP)"

.PP
Creates a \fBLoadBalancingClient\fP with UDP protocol or the one specified\&. 
.PP
\fBParameters\fP
.RS 4
\fIprotocol\fP Specifies the network protocol to use for connections\&.
.RE
.PP

.PP
Definition at line \fB765\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "Photon\&.Realtime\&.LoadBalancingClient\&.LoadBalancingClient (string masterAddress, string appId, string gameVersion, ConnectionProtocol protocol = \fCConnectionProtocol\&.Udp\fP)"

.PP
Creates a \fBLoadBalancingClient\fP, setting various values needed before connecting\&. 
.PP
\fBParameters\fP
.RS 4
\fImasterAddress\fP The Master Server's address to connect to\&. Used in Connect\&.
.br
\fIappId\fP The AppId of this title\&. Needed for the \fBPhoton\fP Cloud\&. Find it in the Dashboard\&.
.br
\fIgameVersion\fP A version for this client/build\&. In the \fBPhoton\fP Cloud, players are separated by AppId, GameVersion and \fBRegion\fP\&.
.br
\fIprotocol\fP Specifies the network protocol to use for connections\&.
.RE
.PP

.PP
Definition at line \fB801\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.AddCallbackTarget (object target)"

.PP
Registers an object for callbacks for the implemented callback-interfaces\&. Adding and removing callback targets is queued to not mess with callbacks in execution\&. Internally, this means that the addition/removal is done before the \fBLoadBalancingClient\fP calls the next callbacks\&. This detail should not affect a game's workflow\&.
.PP
The covered callback interfaces are: \fBIConnectionCallbacks\fP, \fBIMatchmakingCallbacks\fP, \fBILobbyCallbacks\fP, \fBIInRoomCallbacks\fP, \fBIOnEventCallback\fP and \fBIWebRpcCallback\fP\&.
.PP
See: \fCThe object that registers to get callbacks from this client\&. \fP
.PP
Definition at line \fB3490\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.ChangeLocalID (int newID)"

.PP
Internally used to set the LocalPlayer's ID (from -1 to the actual in-room ID)\&. 
.PP
\fBParameters\fP
.RS 4
\fInewID\fP New actor ID (a\&.k\&.a actorNr) assigned when joining a room\&.
.RE
.PP

.PP
Definition at line \fB2289\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.Connect ()"

.PP
Definition at line \fB947\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.LoadBalancingClient\&.ConnectToMasterServer ()\fC [virtual]\fP"

.PP
Starts the 'process' to connect to a Master Server, using MasterServerAddress and AppId properties\&. To connect to the \fBPhoton\fP Cloud, use \fBConnectUsingSettings()\fP or \fBConnectToRegionMaster()\fP\&.
.PP
The process to connect includes several steps: the actual connecting, establishing encryption, authentification (of app and optionally the user) and connecting to the MasterServer
.PP
Users can connect either anonymously or use 'Custom Authentication' to verify each individual player's login\&. Custom Authentication in \fBPhoton\fP uses external services and communities to verify users\&. While the client provides a user's info, the service setup is done in the \fBPhoton\fP Cloud Dashboard\&. The parameter authValues will set this\&.AuthValues and use them in the connect process\&.
.PP
Connecting to the \fBPhoton\fP Cloud might fail due to:
.IP "\(bu" 2
Network issues (\fBOnStatusChanged()\fP StatusCode\&.ExceptionOnConnect)
.IP "\(bu" 2
\fBRegion\fP not available (\fBOnOperationResponse()\fP for OpAuthenticate with ReturnCode == \fBErrorCode\&.InvalidRegion\fP)
.IP "\(bu" 2
Subscription CCU limit reached (\fBOnOperationResponse()\fP for OpAuthenticate with ReturnCode == \fBErrorCode\&.MaxCcuReached\fP) 
.PP

.PP
Definition at line \fB971\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.ConnectToNameServer ()"

.PP
Connects to the NameServer for \fBPhoton\fP Cloud, where a region and server list can be obtained\&. OpGetRegions 
.PP
\fBReturns\fP
.RS 4
If the workflow was started or failed right away\&.
.RE
.PP

.PP
Definition at line \fB1006\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.ConnectToRegionMaster (string region)"

.PP
Connects you to a specific region's Master Server, using the Name Server to find the IP\&. If the region is null or empty, no connection will be made\&. If the region (code) provided is not available, the connection process will fail on the Name Server\&. This method connects only to the region defined\&. No 'Best Region' pinging will be done\&.
.PP
If the region string does not contain a '/', this means no specific cluster is requested\&. To support 'Sharding', the region gets a '/*' postfix in this case, to select a random cluster\&. 
.PP
\fBReturns\fP
.RS 4
If the operation could be sent\&. If false, no operation was sent\&.
.RE
.PP

.PP
Definition at line \fB1054\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.LoadBalancingClient\&.ConnectUsingSettings (\fBAppSettings\fP appSettings)\fC [virtual]\fP"

.PP
Definition at line \fB854\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual void Photon\&.Realtime\&.LoadBalancingClient\&.DebugReturn (DebugLevel level, string message)\fC [virtual]\fP"

.PP
Debug output of low level api (and this client)\&. This method is not responsible to keep up the state of a \fBLoadBalancingClient\fP\&. Calling base\&.DebugReturn on overrides is optional\&.
.PP
Definition at line \fB2553\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.Disconnect (\fBDisconnectCause\fP cause = \fC\fBDisconnectCause\&.DisconnectByClientLogic\fP\fP)"

.PP
Disconnects the peer from a server or stays disconnected\&. If the client / peer was connected, a callback will be triggered\&.
.PP
Disconnect will attempt to notify the server of the client closing the connection\&.
.PP
Clients that are in a room, will leave the room\&. If the room's playerTTL > 0, the player will just become inactive (and may rejoin)\&.
.PP
This method will not change the current State, if this client State is PeerCreated, Disconnecting or Disconnected\&. In those cases, there is also no callback for the disconnect\&. The DisconnectedCause will only change if the client was connected\&. 
.PP
Definition at line \fB1270\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual void Photon\&.Realtime\&.LoadBalancingClient\&.OnEvent (EventData photonEvent)\fC [virtual]\fP"

.PP
Uses the photonEvent's provided by the server to advance the internal state and call ops as needed\&. This method is essential to update the internal state of a \fBLoadBalancingClient\fP\&. Overriding methods must call base\&.OnEvent\&.
.PP
Definition at line \fB3173\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual void Photon\&.Realtime\&.LoadBalancingClient\&.OnMessage (object message)\fC [virtual]\fP"

.PP
In \fBPhoton\fP 4, 'raw messages' will get their own callback method in the interface\&. Not used yet\&.
.PP
Definition at line \fB3357\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual void Photon\&.Realtime\&.LoadBalancingClient\&.OnOperationResponse (OperationResponse operationResponse)\fC [virtual]\fP"

.PP
Uses the OperationResponses provided by the server to advance the internal state and call ops as needed\&. When this method finishes, it will call your OnOpResponseAction (if any)\&. This way, you can get any operation response without overriding this class\&.
.PP
To implement a more complex game/app logic, you should implement your own class that inherits the \fBLoadBalancingClient\fP\&. Override this method to use your own operation-responses easily\&.
.PP
This method is essential to update the internal state of a \fBLoadBalancingClient\fP, so overriding methods must call base\&.OnOperationResponse()\&. 
.PP
\fBParameters\fP
.RS 4
\fIoperationResponse\fP Contains the server's response for an operation called by this peer\&.
.RE
.PP

.PP
Definition at line \fB2614\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual void Photon\&.Realtime\&.LoadBalancingClient\&.OnStatusChanged (StatusCode statusCode)\fC [virtual]\fP"

.PP
Uses the connection's statusCodes to advance the internal state and call operations as needed\&. This method is essential to update the internal state of a \fBLoadBalancingClient\fP\&. Overriding methods must call base\&.OnStatusChanged\&.
.PP
Definition at line \fB2943\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.LoadBalancingClient\&.OpChangeGroups (byte[] groupsToRemove, byte[] groupsToAdd)\fC [virtual]\fP"

.PP
Operation to handle this client's interest groups (for events in room)\&. Note the difference between passing null and byte[0]: null won't add/remove any groups\&. byte[0] will add/remove all (existing) groups\&. First, removing groups is executed\&. This way, you could leave all groups and join only the ones provided\&.
.PP
Changes become active not immediately but when the server executes this operation (approximately RTT/2)\&. 
.PP
\fBParameters\fP
.RS 4
\fIgroupsToRemove\fP Groups to remove from interest\&. Null will not remove any\&. A byte[0] will remove all\&.
.br
\fIgroupsToAdd\fP Groups to add to interest\&. Null will not add any\&. A byte[0] will add all current\&.
.RE
.PP
\fBReturns\fP
.RS 4
If operation could be enqueued for sending\&. Sent when calling: Service or SendOutgoingCommands\&.
.RE
.PP

.PP
Definition at line \fB2195\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpCreateRoom (\fBEnterRoomParams\fP enterRoomParams)"

.PP
Creates a new room\&. Will callback: OnCreatedRoom and OnJoinedRoom or OnCreateRoomFailed\&. 
.PP
When successful, the client will enter the specified room and callback both OnCreatedRoom and OnJoinedRoom\&. In all error cases, OnCreateRoomFailed gets called\&.
.PP
Creating a room will fail if the room name is already in use or when the \fBRoomOptions\fP clashing with one another\&. Check the \fBEnterRoomParams\fP reference for the various room creation options\&.
.PP
This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster\&. Check the return value to make sure the operation will be called on the server\&. Note: There will be no callbacks if this method returned false\&.
.PP
When you're in the room, this client's State will become \fBClientState\&.Joined\fP\&.
.PP
When entering a room, this client's \fBPlayer\fP Custom Properties will be sent to the room\&. Use LocalPlayer\&.SetCustomProperties to set them, even while not yet in the room\&. Note that the player properties will be cached locally and are not wiped when leaving a room\&.
.PP
You can define an array of expectedUsers, to block player slots in the room for these users\&. The corresponding feature in \fBPhoton\fP is called 'Slot Reservation' and can be found in the doc pages\&. 
.PP
\fBParameters\fP
.RS 4
\fIenterRoomParams\fP Definition of properties for the room to create\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent currently (requires connection to Master Server)\&.
.RE
.PP

.PP
Definition at line \fB1702\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpFindFriends (string[] friendsToFind, \fBFindFriendsOptions\fP options = \fCnull\fP)"

.PP
Request the rooms and online status for a list of friends\&. All clients should set a unique UserId before connecting\&. The result is available in this\&.FriendList\&. 
.PP
Used on Master Server to find the rooms played by a selected list of users\&. The result will be stored in LoadBalancingClient\&.FriendList, which is null before the first server response\&.
.PP
Users identify themselves by setting a UserId in the \fBLoadBalancingClient\fP instance\&. This will send the ID in OpAuthenticate during connect (to master and game servers)\&. Note: Changing a player's name doesn't make sense when using a friend list\&.
.PP
The list of usernames must be fetched from some other source (not provided by \fBPhoton\fP)\&.
.PP
Internal:
.br
 The server response includes 2 arrays of info (each index matching a friend from the request):
.br
 \fBParameterCode\&.FindFriendsResponseOnlineList\fP = bool[] of online states
.br
 \fBParameterCode\&.FindFriendsResponseRoomIdList\fP = string[] of room names (empty string if not in a room)
.br
 
.br
 The options may be used to define which state a room must match to be returned\&. 
.PP
\fBParameters\fP
.RS 4
\fIfriendsToFind\fP Array of friend's names (make sure they are unique)\&.
.br
\fIoptions\fP Options that affect the result of the FindFriends operation\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent (requires connection)\&.
.RE
.PP

.PP
Definition at line \fB1444\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpGetGameList (\fBTypedLobby\fP typedLobby, string sqlLobbyFilter)"

.PP
Gets a list of rooms matching the (non empty) SQL filter for the given SQL-typed lobby\&. Operation is only available for lobbies of type SqlLobby and the filter can not be empty\&. It will check those conditions and fail locally, returning false\&.
.PP
This is an async request which triggers a \fBOnOperationResponse()\fP call\&. 
.PP
https://doc\&.photonengine\&.com/en-us/realtime/current/reference/matchmaking-and-lobby::sql_lobby_type 
.PP
\fBParameters\fP
.RS 4
\fItypedLobby\fP The lobby to query\&. Has to be of type SqlLobby\&.
.br
\fIsqlLobbyFilter\fP The sql query statement\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent (has to be connected)\&.
.RE
.PP

.PP
Definition at line \fB1935\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpJoinLobby (\fBTypedLobby\fP lobby)"

.PP
If already connected to a Master Server, this joins the specified lobby\&. This request triggers an \fBOnOperationResponse()\fP call and the callback OnJoinedLobby()\&.
.PP
\fBParameters\fP
.RS 4
\fIlobby\fP The lobby to join\&. Use null for default lobby\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent\&. False, if the client is not IsConnectedAndReady or when it's not connected to a Master Server\&.
.RE
.PP

.PP
Definition at line \fB1518\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpJoinOrCreateRoom (\fBEnterRoomParams\fP enterRoomParams)"

.PP
Joins a specific room by name and creates it on demand\&. Will callback: OnJoinedRoom or OnJoinRoomFailed\&. 
.PP
Useful when players make up a room name to meet in: All involved clients call the same method and whoever is first, also creates the room\&.
.PP
When successful, the client will enter the specified room\&. The client which creates the room, will callback both OnCreatedRoom and OnJoinedRoom\&. Clients that join an existing room will only callback OnJoinedRoom\&. In all error cases, OnJoinRoomFailed gets called\&.
.PP
Joining a room will fail, if the room is full, closed or when the user already is present in the room (checked by userId)\&.
.PP
To return to a room, use OpRejoinRoom\&.
.PP
This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster\&. Check the return value to make sure the operation will be called on the server\&. Note: There will be no callbacks if this method returned false\&.
.PP
This client's State is set to \fBClientState\&.Joining\fP immediately, when the operation could be called\&. In the background, the client will switch servers and call various related operations\&.
.PP
When you're in the room, this client's State will become \fBClientState\&.Joined\fP\&.
.PP
If you set room properties in roomOptions, they get ignored when the room is existing already\&. This avoids changing the room properties by late joining players\&.
.PP
When entering a room, this client's \fBPlayer\fP Custom Properties will be sent to the room\&. Use LocalPlayer\&.SetCustomProperties to set them, even while not yet in the room\&. Note that the player properties will be cached locally and are not wiped when leaving a room\&.
.PP
You can define an array of expectedUsers, to block player slots in the room for these users\&. The corresponding feature in \fBPhoton\fP is called 'Slot Reservation' and can be found in the doc pages\&. 
.PP
\fBParameters\fP
.RS 4
\fIenterRoomParams\fP Definition of properties for the room to create or join\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent currently (requires connection to Master Server)\&.
.RE
.PP

.PP
Definition at line \fB1765\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpJoinRandomOrCreateRoom (\fBOpJoinRandomRoomParams\fP opJoinRandomRoomParams, \fBEnterRoomParams\fP createRoomParams)"

.PP
Attempts to join a room that matches the specified filter and creates a room if none found\&. This operation is a combination of filter-based random matchmaking with the option to create a new room, if no fitting room exists\&. The benefit of that is that the room creation is done by the same operation and the room can be found by the very next client, looking for similar rooms\&.
.PP
There are separate parameters for joining and creating a room\&.
.PP
This method can only be called while connected to a Master Server\&. This client's State is set to \fBClientState\&.Joining\fP immediately\&.
.PP
Either \fBIMatchmakingCallbacks\&.OnJoinedRoom\fP or \fBIMatchmakingCallbacks\&.OnCreatedRoom\fP get called\&.
.PP
More about matchmaking: https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby
.PP
Check the return value to make sure the operation will be called on the server\&. Note: There will be no callbacks if this method returned false\&. 
.PP
\fBReturns\fP
.RS 4
If the operation will be sent (requires connection to Master Server)\&.
.RE
.PP

.PP
Definition at line \fB1640\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpJoinRandomRoom (\fBOpJoinRandomRoomParams\fP opJoinRandomRoomParams = \fCnull\fP)"

.PP
Joins a random room that matches the filter\&. Will callback: OnJoinedRoom or OnJoinRandomFailed\&. 
.PP
Used for random matchmaking\&. You can join any room or one with specific properties defined in opJoinRandomRoomParams\&.
.PP
You can use expectedCustomRoomProperties and expectedMaxPlayers as filters for accepting rooms\&. If you set expectedCustomRoomProperties, a room must have the exact same key values set at Custom Properties\&. You need to define which Custom \fBRoom\fP Properties will be available for matchmaking when you create a room\&. See: OpCreateRoom(string roomName, RoomOptions roomOptions, TypedLobby lobby)
.PP
This operation fails if no rooms are fitting or available (all full, closed or not visible)\&. It may also fail when actually joining the room which was found\&. Rooms may close, become full or empty anytime\&.
.PP
This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster\&. Check the return value to make sure the operation will be called on the server\&. Note: There will be no callbacks if this method returned false\&.
.PP
This client's State is set to \fBClientState\&.Joining\fP immediately, when the operation could be called\&. In the background, the client will switch servers and call various related operations\&.
.PP
When you're in the room, this client's State will become \fBClientState\&.Joined\fP\&.
.PP
When entering a room, this client's \fBPlayer\fP Custom Properties will be sent to the room\&. Use LocalPlayer\&.SetCustomProperties to set them, even while not yet in the room\&. Note that the player properties will be cached locally and are not wiped when leaving a room\&.
.PP
More about matchmaking: https://doc.photonengine.com/en-us/realtime/current/reference/matchmaking-and-lobby
.PP
You can define an array of expectedUsers, to block player slots in the room for these users\&. The corresponding feature in \fBPhoton\fP is called 'Slot Reservation' and can be found in the doc pages\&. 
.PP
\fBParameters\fP
.RS 4
\fIopJoinRandomRoomParams\fP Optional definition of properties to filter rooms in random matchmaking\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent currently (requires connection to Master Server)\&.
.RE
.PP

.PP
Definition at line \fB1590\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpJoinRoom (\fBEnterRoomParams\fP enterRoomParams)"

.PP
Joins a room by name\&. Will callback: OnJoinedRoom or OnJoinRoomFailed\&. 
.PP
Useful when using lobbies or when players follow friends or invite each other\&.
.PP
When successful, the client will enter the specified room and callback via OnJoinedRoom\&. In all error cases, OnJoinRoomFailed gets called\&.
.PP
Joining a room will fail if the room is full, closed, not existing or when the user already is present in the room (checked by userId)\&.
.PP
To return to a room, use OpRejoinRoom\&. When players invite each other and it's unclear who's first to respond, use OpJoinOrCreateRoom instead\&.
.PP
This method can only be called while the client is connected to a Master Server so you should implement the callback OnConnectedToMaster\&. Check the return value to make sure the operation will be called on the server\&. Note: There will be no callbacks if this method returned false\&.
.PP
A room's name has to be unique (per region, appid and gameversion)\&. When your title uses a global matchmaking or invitations (e\&.g\&. an external solution), keep regions and the game versions in mind to join a room\&.
.PP
This client's State is set to \fBClientState\&.Joining\fP immediately, when the operation could be called\&. In the background, the client will switch servers and call various related operations\&.
.PP
When you're in the room, this client's State will become \fBClientState\&.Joined\fP\&.
.PP
When entering a room, this client's \fBPlayer\fP Custom Properties will be sent to the room\&. Use LocalPlayer\&.SetCustomProperties to set them, even while not yet in the room\&. Note that the player properties will be cached locally and are not wiped when leaving a room\&.
.PP
You can define an array of expectedUsers, to reserve player slots in the room for friends or party members\&. The corresponding feature in \fBPhoton\fP is called 'Slot Reservation' and can be found in the doc pages\&. 
.PP
\fBParameters\fP
.RS 4
\fIenterRoomParams\fP Definition of properties for the room to join\&.
.RE
.PP
\fBReturns\fP
.RS 4
If the operation could be sent currently (requires connection to Master Server)\&.
.RE
.PP

.PP
Definition at line \fB1830\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpLeaveLobby ()"

.PP
Opposite of joining a lobby\&. You don't have to explicitly leave a lobby to join another (client can be in one max, at any time)\&.
.PP
\fBReturns\fP
.RS 4
If the operation could be sent (has to be connected)\&.
.RE
.PP

.PP
Definition at line \fB1542\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpLeaveRoom (bool becomeInactive, bool sendAuthCookie = \fCfalse\fP)"

.PP
Leaves the current room, optionally telling the server that the user is just becoming inactive\&. Will callback: OnLeftRoom\&. 
.PP
OpLeaveRoom skips execution when the room is null or the server is not GameServer or the client is disconnecting from GS already\&. OpLeaveRoom returns false in those cases and won't change the state, so check return of this method\&.
.PP
In some cases, this method will skip the OpLeave call and just call \fBDisconnect()\fP, which not only leaves the room but also the server\&. Disconnect also triggers a leave and so that workflow is is quicker\&. 
.PP
\fBParameters\fP
.RS 4
\fIbecomeInactive\fP If true, this player becomes inactive in the game and can return later (if PlayerTTL of the room is != 0)\&.
.br
\fIsendAuthCookie\fP WebFlag: Securely transmit the encrypted object AuthCookie to the web service in PathLeave webhook when available
.RE
.PP
\fBReturns\fP
.RS 4
If the current room could be left (impossible while not in a room)\&.
.RE
.PP

.PP
Definition at line \fB1910\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "virtual bool Photon\&.Realtime\&.LoadBalancingClient\&.OpRaiseEvent (byte eventCode, object customEventContent, \fBRaiseEventOptions\fP raiseEventOptions, SendOptions sendOptions)\fC [virtual]\fP"

.PP
Send an event with custom code/type and any content to the other players in the same room\&. 
.PP
\fBParameters\fP
.RS 4
\fIeventCode\fP Identifies this type of event (and the content)\&. Your game's event codes can start with 0\&.
.br
\fIcustomEventContent\fP Any serializable datatype (including Hashtable like the other OpRaiseEvent overloads)\&.
.br
\fIraiseEventOptions\fP Contains used send options\&. If you pass null, the default options will be used\&.
.br
\fIsendOptions\fP Send options for reliable, encryption etc
.RE
.PP
\fBReturns\fP
.RS 4
If operation could be enqueued for sending\&. Sent when calling: Service or SendOutgoingCommands\&.
.RE
.PP

.PP
Definition at line \fB2169\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpRejoinRoom (string roomName)"

.PP
Rejoins a room by roomName (using the userID internally to return)\&. Will callback: OnJoinedRoom or OnJoinRoomFailed\&. 
.PP
Used to return to a room, before this user was removed from the players list\&. Internally, the userID will be checked by the server, to make sure this user is in the room (active or inactice)\&.
.PP
In contrast to join, this operation never adds a players to a room\&. It will attempt to retake an existing spot in the playerlist or fail\&. This makes sure the client doean't accidentally join a room when the game logic meant to re-activate an existing actor in an existing room\&.
.PP
This method will fail on the server, when the room does not exist, can't be loaded (persistent rooms) or when the userId is not in the player list of this room\&. This will lead to a callback OnJoinRoomFailed\&.
.PP
Rejoining room will not send any player properties\&. Instead client will receive up-to-date ones from server\&. If you want to set new player properties, do it once rejoined\&. 
.PP
Definition at line \fB1871\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpSetCustomPropertiesOfActor (int actorNr, \fBHashtable\fP propertiesToSet, \fBHashtable\fP expectedProperties = \fCnull\fP, \fBWebFlags\fP webFlags = \fCnull\fP)"

.PP
Updates and synchronizes a \fBPlayer\fP's Custom Properties\&. Optionally, expectedProperties can be provided as condition\&. 
.PP
Custom Properties are a set of string keys and arbitrary values which is synchronized for the players in a \fBRoom\fP\&. They are available when the client enters the room, as they are in the response of OpJoin and OpCreate\&.
.PP
Custom Properties either relate to the (current) \fBRoom\fP or a \fBPlayer\fP (in that \fBRoom\fP)\&.
.PP
Both classes locally cache the current key/values and make them available as property: CustomProperties\&. This is provided only to read them\&. You must use the method SetCustomProperties to set/modify them\&.
.PP
Any client can set any Custom Properties anytime (when in a room)\&. It's up to the game logic to organize how they are best used\&.
.PP
You should call SetCustomProperties only with key/values that are new or changed\&. This reduces traffic and performance\&.
.PP
Unless you define some expectedProperties, setting key/values is always permitted\&. In this case, the property-setting client will not receive the new values from the server but instead update its local cache in SetCustomProperties\&.
.PP
If you define expectedProperties, the server will skip updates if the server property-cache does not contain all expectedProperties with the same values\&. In this case, the property-setting client will get an update from the server and update it's cached key/values at about the same time as everyone else\&.
.PP
The benefit of using expectedProperties can be only one client successfully sets a key from one known value to another\&. As example: Store who owns an item in a Custom Property 'ownedBy'\&. It's 0 initally\&. When multiple players reach the item, they all attempt to change 'ownedBy' from 0 to their actorNumber\&. If you use expectedProperties {'ownedBy', 0} as condition, the first player to take the item will have it (and the others fail to set the ownership)\&.
.PP
Properties get saved with the game state for Turnbased games (which use IsPersistent = true)\&. 
.PP
\fBParameters\fP
.RS 4
\fIactorNr\fP Defines which player the Custom Properties belong to\&. ActorID of a player\&.
.br
\fIpropertiesToSet\fP Hashtable of Custom Properties that changes\&.
.br
\fIexpectedProperties\fP Provide some keys/values to use as condition for setting the new values\&. Client must be in room\&.
.br
\fIwebFlags\fP Defines if the set properties should be forwarded to a WebHook\&. Client must be in room\&.
.RE
.PP
\fBReturns\fP
.RS 4
False if propertiesToSet is null or empty or have zero string keys\&. If not in a room, returns true if local player and expectedProperties and webFlags are null\&. False if actorNr is lower than or equal to zero\&. Otherwise, returns if the operation could be sent to the server\&. 
.RE
.PP

.PP
Definition at line \fB2005\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpSetCustomPropertiesOfRoom (\fBHashtable\fP propertiesToSet, \fBHashtable\fP expectedProperties = \fCnull\fP, \fBWebFlags\fP webFlags = \fCnull\fP)"

.PP
Updates and synchronizes this \fBRoom\fP's Custom Properties\&. Optionally, expectedProperties can be provided as condition\&. 
.PP
Custom Properties are a set of string keys and arbitrary values which is synchronized for the players in a \fBRoom\fP\&. They are available when the client enters the room, as they are in the response of OpJoin and OpCreate\&.
.PP
Custom Properties either relate to the (current) \fBRoom\fP or a \fBPlayer\fP (in that \fBRoom\fP)\&.
.PP
Both classes locally cache the current key/values and make them available as property: CustomProperties\&. This is provided only to read them\&. You must use the method SetCustomProperties to set/modify them\&.
.PP
Any client can set any Custom Properties anytime (when in a room)\&. It's up to the game logic to organize how they are best used\&.
.PP
You should call SetCustomProperties only with key/values that are new or changed\&. This reduces traffic and performance\&.
.PP
Unless you define some expectedProperties, setting key/values is always permitted\&. In this case, the property-setting client will not receive the new values from the server but instead update its local cache in SetCustomProperties\&.
.PP
If you define expectedProperties, the server will skip updates if the server property-cache does not contain all expectedProperties with the same values\&. In this case, the property-setting client will get an update from the server and update it's cached key/values at about the same time as everyone else\&.
.PP
The benefit of using expectedProperties can be only one client successfully sets a key from one known value to another\&. As example: Store who owns an item in a Custom Property 'ownedBy'\&. It's 0 initally\&. When multiple players reach the item, they all attempt to change 'ownedBy' from 0 to their actorNumber\&. If you use expectedProperties {'ownedBy', 0} as condition, the first player to take the item will have it (and the others fail to set the ownership)\&.
.PP
Properties get saved with the game state for Turnbased games (which use IsPersistent = true)\&. 
.PP
\fBParameters\fP
.RS 4
\fIpropertiesToSet\fP Hashtable of Custom Properties that changes\&.
.br
\fIexpectedProperties\fP Provide some keys/values to use as condition for setting the new values\&.
.br
\fIwebFlags\fP Defines web flags for an optional PathProperties webhook\&.
.RE
.PP
\fBReturns\fP
.RS 4
False if propertiesToSet is null or empty or have zero string keys\&. Otherwise, returns if the operation could be sent to the server\&. 
.RE
.PP

.PP
Definition at line \fB2112\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.OpWebRpc (string uriPath, object parameters, bool sendAuthCookie = \fCfalse\fP)"

.PP
This operation makes \fBPhoton\fP call your custom web-service by path/name with the given parameters (converted into Json)\&. Use \fBIWebRpcCallback\&.OnWebRpcResponse\fP as a callback\&. 
.PP
A WebRPC calls a custom, http-based function on a server you provide\&. The uriPath is relative to a 'base path' which is configured server-side\&. The sent parameters get converted from C# types to Json\&. Vice versa, the response of the web-service will be converted to C# types and sent back as normal operation response\&.
.PP
To use this feature, you have to setup your server:
.PP
For a \fBPhoton\fP Cloud application, \fCvisit the Dashboard \fP and setup 'WebHooks'\&. The BaseUrl is used for WebRPCs as well\&.
.PP
The class \fBWebRpcResponse\fP is a helper-class that extracts the most valuable content from the WebRPC response\&. 
.PP
\fBParameters\fP
.RS 4
\fIuriPath\fP The url path to call, relative to the baseUrl configured on \fBPhoton\fP's server-side\&.
.br
\fIparameters\fP The parameters to send to the web-service method\&.
.br
\fIsendAuthCookie\fP Defines if the authentication cookie gets sent to a WebHook (if setup)\&.
.RE
.PP

.PP
Definition at line \fB3449\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.ReconnectAndRejoin ()"

.PP
Can be used to return to a room quickly by directly reconnecting to a game server to rejoin a room\&. Rejoining room will not send any player properties\&. Instead client will receive up-to-date ones from server\&. If you want to set new player properties, do it once rejoined\&. 
.PP
\fBReturns\fP
.RS 4
False, if the conditions are not met\&. Then, this client does not attempt the ReconnectAndRejoin\&.
.RE
.PP

.PP
Definition at line \fB1219\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.ReconnectToMaster ()"

.PP
Can be used to reconnect to the master server after a disconnect\&. Common use case: Press the Lock Button on a iOS device and you get disconnected immediately\&.
.PP
Definition at line \fB1182\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.RemoveCallbackTarget (object target)"

.PP
Unregisters an object from callbacks for the implemented callback-interfaces\&. Adding and removing callback targets is queued to not mess with callbacks in execution\&. Internally, this means that the addition/removal is done before the \fBLoadBalancingClient\fP calls the next callbacks\&. This detail should not affect a game's workflow\&.
.PP
The covered callback interfaces are: \fBIConnectionCallbacks\fP, \fBIMatchmakingCallbacks\fP, \fBILobbyCallbacks\fP, \fBIInRoomCallbacks\fP, \fBIOnEventCallback\fP and \fBIWebRpcCallback\fP\&.
.PP
See: \fC\fP 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The object that unregisters from getting callbacks\&.
.RE
.PP

.PP
Definition at line \fB3509\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.Service ()"

.PP
This method dispatches all available incoming commands and then sends this client's outgoing commands\&. It uses DispatchIncomingCommands and SendOutgoingCommands to do that\&. 
.PP
The \fBPhoton\fP client libraries are designed to fit easily into a game or application\&. The application is in control of the context (thread) in which incoming events and responses are executed and has full control of the creation of UDP/TCP packages\&.
.PP
Sending packages and dispatching received messages are two separate tasks\&. Service combines them into one method at the cost of control\&. It calls DispatchIncomingCommands and SendOutgoingCommands\&.
.PP
Call this method regularly (10\&.\&.50 times a second)\&.
.PP
This will Dispatch ANY received commands (unless a reliable command in-order is still missing) and events AND will send queued outgoing commands\&. Fewer calls might be more effective if a device cannot send many packets per second, as multiple operations might be combined into one package\&. 
.PP
You could replace Service by: 
.PP
.nf
while (DispatchIncomingCommands()); //Dispatch until everything is Dispatched...
SendOutgoingCommands(); //Send a UDP/TCP package with outgoing messages

.fi
.PP
 
.PP
\fBSee also\fP
.RS 4
PhotonPeer\&.DispatchIncomingCommands, PhotonPeer\&.SendOutgoingCommands
.PP
.RE
.PP

.PP
Definition at line \fB1395\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "void Photon\&.Realtime\&.LoadBalancingClient\&.SimulateConnectionLoss (bool simulateTimeout)"

.PP
Useful to test loss of connection which will end in a client timeout\&. This modifies LoadBalancingPeer\&.NetworkSimulationSettings\&. Read remarks\&. 
.PP
Use with care as this sets LoadBalancingPeer\&.IsSimulationEnabled\&.
.br
 Read LoadBalancingPeer\&.IsSimulationEnabled to check if this is on or off, if needed\&.
.br
.PP
If simulateTimeout is true, LoadBalancingPeer\&.NetworkSimulationSettings\&.IncomingLossPercentage and LoadBalancingPeer\&.NetworkSimulationSettings\&.OutgoingLossPercentage will be set to 100\&.
.br
 Obviously, this overrides any network simulation settings done before\&.
.br
.PP
If you want fine-grained network simulation control, use the NetworkSimulationSettings\&.
.br
.PP
The timeout will lead to a call to \fBIConnectionCallbacks\&.OnDisconnected\fP, as usual in a client timeout\&.
.PP
You could modify this method (or use NetworkSimulationSettings) to deliberately run into a server timeout by just setting the OutgoingLossPercentage = 100 and the IncomingLossPercentage = 0\&. 
.PP
\fBParameters\fP
.RS 4
\fIsimulateTimeout\fP If true, a connection loss is simulated\&. If false, the simulation ends\&.
.RE
.PP

.PP
Definition at line \fB1327\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAuthModeOption\fP Photon\&.Realtime\&.LoadBalancingClient\&.AuthMode = \fBAuthModeOption\&.Auth\fP"

.PP
Enables the new Authentication workflow\&.
.PP
Definition at line \fB319\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBConnectionCallbacksContainer\fP Photon\&.Realtime\&.LoadBalancingClient\&.ConnectionCallbackTargets"

.PP
Wraps up the target objects for a group of callbacks, so they can be called conveniently\&. By using Add or Remove, objects can 'subscribe' or 'unsubscribe' for this group of callbacks\&.
.PP
Definition at line \fB531\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.EnableLobbyStatistics"

.PP
If enabled, the client will get a list of available lobbies from the Master Server\&. Set this value before the client connects to the Master Server\&. While connected to the Master Server, a change has no effect\&.
.PP
Implement OptionalInfoCallbacks\&.OnLobbyStatisticsUpdate, to get the list of used lobbies\&.
.PP
The lobby statistics can be useful if your title dynamically uses lobbies, depending (e\&.g\&.) on current player activity or such\&. In this case, getting a list of available lobbies, their room-count and player-count can be useful info\&.
.PP
ConnectUsingSettings sets this to the PhotonServerSettings value\&. 
.PP
Definition at line \fB591\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBEncryptionMode\fP Photon\&.Realtime\&.LoadBalancingClient\&.EncryptionMode = \fBEncryptionMode\&.PayloadEncryption\fP"

.PP
Defines how the communication gets encrypted\&.
.PP
Definition at line \fB322\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBMatchMakingCallbacksContainer\fP Photon\&.Realtime\&.LoadBalancingClient\&.MatchMakingCallbackTargets"

.PP
Wraps up the target objects for a group of callbacks, so they can be called conveniently\&. By using Add or Remove, objects can 'subscribe' or 'unsubscribe' for this group of callbacks\&.
.PP
Definition at line \fB535\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.NameServerHost = 'ns\&.photonengine\&.io'"

.PP
Name Server Host Name for \fBPhoton\fP Cloud\&. Without port and without any prefix\&.
.PP
Definition at line \fB357\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.LoadBalancingClient\&.NameServerPortInAppSettings"

.PP
Definition at line \fB808\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.ProxyServerAddress"

.PP
Defines a proxy URL for WebSocket connections\&. Can be the proxy or point to a \&.pac file\&. 
.PP
This URL supports various definitions:
.PP
'user:pass@proxyaddress:port'
.br
 'proxyaddress:port'
.br
 'system:'
.br
 'pac:'
.br
 'pac:http://host/path/pacfile\&.pac'
.br
.PP
Important: Don't define a protocol, except to point to a pac file\&. the proxy address should not begin with http:// or https://\&. 
.PP
Definition at line \fB431\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBRegionHandler\fP Photon\&.Realtime\&.LoadBalancingClient\&.RegionHandler"

.PP
Contains the list if enabled regions this client may use\&. Null, unless the client got a response to OpGetRegions\&.
.PP
Definition at line \fB711\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBPhotonPortDefinition\fP Photon\&.Realtime\&.LoadBalancingClient\&.ServerPortOverrides"

.PP
Defines overrides for server ports\&. Used per server-type if > 0\&. Important: You must change these when the protocol changes!
.PP
Typical ports are listed in \fBPhotonPortDefinition\fP\&.
.PP
Instead of using the port provided from the servers, the specified port is used (independent of the protocol)\&. If a value is 0 (default), the port is not being replaced\&.
.PP
Different protocols have different typical ports per server-type\&. https://doc.photonengine.com/en-us/pun/current/reference/tcp-and-udp-port-numbers
.PP
In case of using the AuthMode AutOnceWss, the name server's protocol is wss, while udp or tcp will be used on the master server and game server\&. Set the ports accordingly per protocol and server\&. 
.PP
Definition at line \fB384\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.SummaryToCache"

.PP
Set when the best region pinging is done\&.
.PP
Definition at line \fB717\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.AppId\fC [get]\fP, \fC [set]\fP"

.PP
The AppID as assigned from the \fBPhoton\fP Cloud\&. If you host yourself, this is the 'regular' \fBPhoton\fP Server Application Name (most likely: 'LoadBalancing')\&.
.PP
Definition at line \fB309\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.AppVersion\fC [get]\fP, \fC [set]\fP"

.PP
The version of your client\&. A new version also creates a new 'virtual app' to separate players from older client versions\&.
.PP
Definition at line \fB306\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBAuthenticationValues\fP Photon\&.Realtime\&.LoadBalancingClient\&.AuthValues\fC [get]\fP, \fC [set]\fP"

.PP
User authentication values to be sent to the \fBPhoton\fP server right after connecting\&. Set this property or pass \fBAuthenticationValues\fP by Connect(\&.\&.\&., authValues)\&.
.PP
Definition at line \fB316\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBClientAppType\fP Photon\&.Realtime\&.LoadBalancingClient\&.ClientType\fC [get]\fP, \fC [set]\fP"

.PP
The ClientAppType defines which sort of AppId should be expected\&. The \fBLoadBalancingClient\fP supports \fBRealtime\fP and Voice app types\&. Default: \fBRealtime\fP\&.
.PP
Definition at line \fB312\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.CloudRegion\fC [get]\fP"

.PP
The cloud region this client connects to\&. Set by \fBConnectToRegionMaster()\fP\&. Not set if you don't use a NameServer!
.PP
Definition at line \fB701\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.CurrentCluster\fC [get]\fP"

.PP
The cluster name provided by the Name Server\&. The value is provided by the OpResponse for OpAuthenticate/OpAuthenticateOnce\&. Default: null\&. This value only ever updates from the Name Server authenticate response\&. 
.PP
Definition at line \fB708\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBTypedLobby\fP Photon\&.Realtime\&.LoadBalancingClient\&.CurrentLobby\fC [get]\fP, \fC [set]\fP"

.PP
The lobby this client currently uses\&. Defined when joining a lobby or creating rooms
.PP
Definition at line \fB573\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBRoom\fP Photon\&.Realtime\&.LoadBalancingClient\&.CurrentRoom\fC [get]\fP, \fC [set]\fP"

.PP
The current room this client is connected to (null if none available)\&.
.PP
Definition at line \fB653\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.CurrentServerAddress\fC [get]\fP"

.PP
The currently used server address (if any)\&. The type of server is define by Server property\&.
.PP
Definition at line \fB399\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBDisconnectCause\fP Photon\&.Realtime\&.LoadBalancingClient\&.DisconnectedCause\fC [get]\fP, \fC [protected set]\fP"

.PP
Summarizes (aggregates) the different causes for disconnects of a client\&. A disconnect can be caused by: errors in the network connection or some vital operation failing (which is considered 'high level')\&. While operations always trigger a call to OnOperationResponse, connection related changes are treated in OnStatusChanged\&. The DisconnectCause is set in either case and summarizes the causes for any disconnect in a single state value which can be used to display (or debug) the cause for disconnection\&. 
.PP
Definition at line \fB562\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.EnableProtocolFallback\fC [get]\fP, \fC [set]\fP"

.PP
Enables a fallback to another protocol in case a connect to the Name Server fails\&. When connecting to the Name Server fails for a first time, the client will select an alternative network protocol and re-try to connect\&.
.PP
The fallback will use the default Name Server port as defined by ProtocolToNameServerPort\&.
.PP
The fallback for TCP is UDP\&. All other protocols fallback to TCP\&. 
.PP
Definition at line \fB396\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "ConnectionProtocol? Photon\&.Realtime\&.LoadBalancingClient\&.ExpectedProtocol\fC [get]\fP, \fC [set]\fP"

.PP
Optionally contains a protocol which will be used on Master- and GameServer\&. When using AuthMode = \fBAuthModeOption\&.AuthOnceWss\fP, the client uses a wss-connection on the NameServer but another protocol on the other servers\&. As the NameServer sends an address, which is different per protocol, it needs to know the expected protocol\&.
.PP
This is nullable by design\&. In many cases, the protocol on the NameServer is not different from the other servers\&. If set, the operation AuthOnce will contain this value and the OpAuth response on the NameServer will execute a protocol switch\&. 
.PP
summary>Simplifies getting the token for connect/init requests, if this feature is enabled\&.
.PP
Definition at line \fB332\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.GameServerAddress\fC [get]\fP, \fC [set]\fP"

.PP
The game server's address for a particular room\&. In use temporarily, as assigned by master\&.
.PP
Definition at line \fB409\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.InLobby\fC [get]\fP"

.PP
Internal value if the client is in a lobby\&. This is used to re-set this\&.State, when joining/creating a room fails\&.
.PP
Definition at line \fB567\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.InRoom\fC [get]\fP"

.PP
Is true while being in a room (this\&.state == \fBClientState\&.Joined\fP)\&. Aside from polling this value, game logic should implement \fBIMatchmakingCallbacks\fP in some class and react when that gets called\&.
.br
 OpRaiseEvent, OpLeave and some other operations can only be used (successfully) when the client is in a room\&.\&. 
.PP
Definition at line \fB662\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.IsConnected\fC [get]\fP"

.PP
Returns if this client is currently connected or connecting to some type of server\&. This is even true while switching servers\&. Use IsConnectedAndReady to check only for those states that enable you to send Operations\&.
.PP
Definition at line \fB458\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.IsConnectedAndReady\fC [get]\fP"

.PP
A refined version of IsConnected which is true only if your connection is ready to send operations\&. Not all operations can be called on all types of servers\&. If an operation is unavailable on the currently connected server, this will result in a OperationResponse with \fBErrorCode\fP != 0\&.
.PP
Examples: The NameServer allows OpGetRegions which is not available anywhere else\&. The MasterServer does not allow you to send events (OpRaiseEvent) and on the GameServer you are unable to join a lobby (OpJoinLobby)\&.
.PP
To check which server you are on, use: \fBServer\fP\&. 
.PP
Definition at line \fB473\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.IsFetchingFriendList\fC [get]\fP"

.PP
Internal flag to know if the client currently fetches a friend list\&.
.PP
Definition at line \fB697\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.IsUsingNameServer\fC [get]\fP, \fC [set]\fP"

.PP
True if this client uses a NameServer to get the Master Server address\&. This value is public, despite being an internal value, which should only be set by this client\&.
.PP
Definition at line \fB354\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBLoadBalancingPeer\fP Photon\&.Realtime\&.LoadBalancingClient\&.LoadBalancingPeer\fC [get]\fP"

.PP
The client uses a \fBLoadBalancingPeer\fP as API to communicate with the server\&. This is public for ease-of-use: Some methods like OpRaiseEvent are not relevant for the connection state and don't need a override\&. 
.PP
Definition at line \fB284\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBPlayer\fP Photon\&.Realtime\&.LoadBalancingClient\&.LocalPlayer\fC [get]\fP, \fC [set]\fP"

.PP
The local player is never null but not valid unless the client is in a room, too\&. The ID will be -1 outside of rooms\&.
.PP
Definition at line \fB598\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.MasterServerAddress\fC [get]\fP, \fC [set]\fP"

.PP
Your Master Server address\&. In PhotonCloud, call \fBConnectToRegionMaster()\fP to find your Master Server\&.
.PP
In the \fBPhoton\fP Cloud, explicit definition of a Master Server Address is not best practice\&. The \fBPhoton\fP Cloud has a 'Name Server' which redirects clients to a specific Master Server (per \fBRegion\fP and AppId)\&. 
.PP
Definition at line \fB406\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.NameServerAddress\fC [get]\fP"

.PP
Name Server Address for \fBPhoton\fP Cloud (based on current protocol)\&. You can use the default values and usually won't have to set this value\&.
.PP
Definition at line \fB360\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.NickName\fC [get]\fP, \fC [set]\fP"

.PP
The nickname of the player (synced with others)\&. Same as client\&.LocalPlayer\&.NickName\&. 
.PP
Definition at line \fB603\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.LoadBalancingClient\&.PlayersInRoomsCount\fC [get]\fP, \fC [set]\fP"

.PP
Statistic value available on master server: Players in rooms (playing)\&.
.PP
Definition at line \fB674\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.LoadBalancingClient\&.PlayersOnMasterCount\fC [get]\fP, \fC [set]\fP"

.PP
Statistic value available on master server: Players on master (looking for games)\&.
.PP
Definition at line \fB671\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.LoadBalancingClient\&.RoomsCount\fC [get]\fP, \fC [set]\fP"

.PP
Statistic value available on master server: Rooms currently created\&.
.PP
Definition at line \fB677\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "SerializationProtocol Photon\&.Realtime\&.LoadBalancingClient\&.SerializationProtocol\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the binary protocol version used by this client Use this always instead of setting it via \fBLoadBalancingClient\&.LoadBalancingPeer\fP (PhotonPeer\&.SerializationProtocolType) directly, especially when WSS protocol is used\&. 
.PP
Definition at line \fB293\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBServerConnection\fP Photon\&.Realtime\&.LoadBalancingClient\&.Server\fC [get]\fP"

.PP
The server this client is currently connected or connecting to\&. Each server (NameServer, MasterServer, GameServer) allow some operations and reject others\&. 
.PP
Definition at line \fB415\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "\fBClientState\fP Photon\&.Realtime\&.LoadBalancingClient\&.State\fC [get]\fP, \fC [set]\fP"

.PP
Current state this client is in\&. Careful: several states are 'transitions' that lead to other states\&.
.PP
Definition at line \fB437\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.LoadBalancingClient\&.UseAlternativeUdpPorts\fC [get]\fP, \fC [set]\fP"

.PP
Replaced by ServerPortOverrides\&.
.PP
Definition at line \fB368\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.LoadBalancingClient\&.UserId\fC [get]\fP, \fC [set]\fP"

.PP
An ID for this user\&. Sent in OpAuthenticate when you connect\&. If not set, the PlayerName is applied during connect\&.
.PP
On connect, if the UserId is null or empty, the client will copy the PlayName to UserId\&. If PlayerName is not set either (before connect), the server applies a temporary ID which stays unknown to this client and other clients\&.
.PP
The UserId is what's used in FindFriends and for fetching data for your account (with WebHooks e\&.g\&.)\&.
.PP
By convention, set this ID before you connect, not while being connected\&. There is no error but the ID won't change while being connected\&. 
.PP
Definition at line \fB632\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action<EventData> Photon\&.Realtime\&.LoadBalancingClient\&.EventReceived"

.PP
Register a method to be called when an event got dispatched\&. Gets called after the \fBLoadBalancingClient\fP handled the internal events first\&.
.PP
This is an alternative to extending \fBLoadBalancingClient\fP to override \fBOnEvent()\fP\&.
.PP
Note that OnEvent is calling EventReceived after it handled internal events first\&. That means for example: Joining players will already be in the player list but leaving players will already be removed from the room\&. 
.PP
Definition at line \fB516\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "Action<OperationResponse> Photon\&.Realtime\&.LoadBalancingClient\&.OpResponseReceived"

.PP
Register a method to be called when an operation response is received\&. This is an alternative to extending \fBLoadBalancingClient\fP to override \fBOnOperationResponse()\fP\&.
.PP
Note that OnOperationResponse gets executed before your Action is called\&. That means for example: The OpJoinLobby response already set the state to 'JoinedLobby' and the response to OpLeave already triggered the Disconnect before this is called\&. 
.PP
Definition at line \fB526\fP of file \fBLoadBalancingClient\&.cs\fP\&.
.SS "Action<\fBClientState\fP, \fBClientState\fP> Photon\&.Realtime\&.LoadBalancingClient\&.StateChanged"

.PP
Register a method to be called when this client's ClientState gets set\&. This can be useful to react to being connected, joined into a room, etc\&.
.PP
Definition at line \fB506\fP of file \fBLoadBalancingClient\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
