.TH "Photon.Pun.Simple.IAutoKinematic" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IAutoKinematic
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.OnStateChangeKinematic\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBAutoKinematicEnabled\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.IAutoKinematic\&.AutoKinematicEnabled\fC [get]\fP"

.PP
Definition at line \fB16\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
