.TH "Photon.Chat.Demo.IgnoreUiRaycastWhenInactive" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Chat.Demo.IgnoreUiRaycastWhenInactive
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, and ICanvasRaycastFilter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsRaycastLocationValid\fP (Vector2 screenPoint, Camera eventCamera)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBIgnoreUiRaycastWhenInactive\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Photon\&.Chat\&.Demo\&.IgnoreUiRaycastWhenInactive\&.IsRaycastLocationValid (Vector2 screenPoint, Camera eventCamera)"

.PP
Definition at line \fB15\fP of file \fBIgnoreUiRaycastWhenInactive\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
