.TH "Photon.Pun.UtilityScripts.TeamExtensions" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.TeamExtensions \- Extension used for \fBPunTeams\fP and Player class\&. Wraps access to the player's custom property\&. 

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPunTeams\&.Team\fP \fBGetTeam\fP (this \fBPlayer\fP player)"
.br
.RI "Extension for Player class to wrap up access to the player's custom property\&. "
.ti -1c
.RI "static void \fBSetTeam\fP (this \fBPlayer\fP player, \fBPunTeams\&.Team\fP team)"
.br
.RI "Switch that player's team to the one you assign\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extension used for \fBPunTeams\fP and Player class\&. Wraps access to the player's custom property\&.
.PP
Definition at line \fB120\fP of file \fBPunTeams\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBPunTeams\&.Team\fP Photon\&.Pun\&.UtilityScripts\&.TeamExtensions\&.GetTeam (this \fBPlayer\fP player)\fC [static]\fP"

.PP
Extension for Player class to wrap up access to the player's custom property\&. 
.PP
\fBReturns\fP
.RS 4
PunTeam\&.Team\&.none if no team was found (yet)\&.
.RE
.PP

.PP
Definition at line \fB125\fP of file \fBPunTeams\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.UtilityScripts\&.TeamExtensions\&.SetTeam (this \fBPlayer\fP player, \fBPunTeams\&.Team\fP team)\fC [static]\fP"

.PP
Switch that player's team to the one you assign\&. Internally checks if this player is in that team already or not\&. Only team switches are actually sent\&.
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP 
.br
\fIteam\fP 
.RE
.PP

.PP
Definition at line \fB141\fP of file \fBPunTeams\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
