.TH "Photon.Pun.PhotonTransformViewScaleModel" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonTransformViewScaleModel
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBInterpolateOptions\fP { \fBDisabled\fP, \fBMoveTowards\fP, \fBLerp\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBSynchronizeEnabled\fP"
.br
.ti -1c
.RI "\fBInterpolateOptions\fP \fBInterpolateOption\fP = \fBInterpolateOptions\&.Disabled\fP"
.br
.ti -1c
.RI "float \fBInterpolateMoveTowardsSpeed\fP = 1f"
.br
.ti -1c
.RI "float \fBInterpolateLerpSpeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB489\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.PhotonTransformViewScaleModel\&.InterpolateOptions\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fIMoveTowards \fP\fP
.TP
\fB\fILerp \fP\fP
.PP
Definition at line \fB491\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Photon\&.Pun\&.PhotonTransformViewScaleModel\&.InterpolateLerpSpeed"

.PP
Definition at line \fB503\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "float Photon\&.Pun\&.PhotonTransformViewScaleModel\&.InterpolateMoveTowardsSpeed = 1f"

.PP
Definition at line \fB502\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "\fBInterpolateOptions\fP Photon\&.Pun\&.PhotonTransformViewScaleModel\&.InterpolateOption = \fBInterpolateOptions\&.Disabled\fP"

.PP
Definition at line \fB501\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonTransformViewScaleModel\&.SynchronizeEnabled"

.PP
Definition at line \fB499\fP of file \fBPhotonTransformViewClassic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
