.TH "Photon.Pun.UtilityScripts.CullArea" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.CullArea \- Represents the cull area used for network culling\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnDrawGizmos\fP ()"
.br
.RI "Creates the cell hierarchy in editor and draws the cell view\&. "
.ti -1c
.RI "List< byte > \fBGetActiveCells\fP (Vector3 position)"
.br
.RI "Gets a list of all cell IDs the player is currently inside or nearby\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly byte \fBFIRST_GROUP_ID\fP = 1"
.br
.RI "This represents the first ID which is assigned to the first created cell\&. "
.ti -1c
.RI "readonly int[] \fBSUBDIVISION_FIRST_LEVEL_ORDER\fP = new int[4] { 0, 1, 1, 1 }"
.br
.RI "This represents the order in which updates are sent\&. "
.ti -1c
.RI "readonly int[] \fBSUBDIVISION_SECOND_LEVEL_ORDER\fP = new int[8] { 0, 2, 1, 2, 0, 2, 1, 2 }"
.br
.RI "This represents the order in which updates are sent\&. "
.ti -1c
.RI "readonly int[] \fBSUBDIVISION_THIRD_LEVEL_ORDER\fP = new int[12] { 0, 3, 2, 3, 1, 3, 2, 3, 1, 3, 2, 3 }"
.br
.RI "This represents the order in which updates are sent\&. "
.ti -1c
.RI "Vector2 \fBCenter\fP"
.br
.ti -1c
.RI "Vector2 \fBSize\fP = new Vector2(25\&.0f, 25\&.0f)"
.br
.ti -1c
.RI "Vector2[] \fBSubdivisions\fP = new Vector2[\fBMAX_NUMBER_OF_SUBDIVISIONS\fP]"
.br
.ti -1c
.RI "int \fBNumberOfSubdivisions\fP"
.br
.ti -1c
.RI "bool \fBYIsUpAxis\fP = false"
.br
.ti -1c
.RI "bool \fBRecreateCellHierarchy\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBMAX_NUMBER_OF_SUBDIVISIONS\fP = 3"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCellCount\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBCellTree\fP \fBCellTree\fP\fC [get]\fP"
.br
.ti -1c
.RI "Dictionary< int, GameObject > \fBMap\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the cull area used for network culling\&. 


.PP
Definition at line \fB22\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "List< byte > Photon\&.Pun\&.UtilityScripts\&.CullArea\&.GetActiveCells (Vector3 position)"

.PP
Gets a list of all cell IDs the player is currently inside or nearby\&. 
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The current position of the player\&.
.RE
.PP
\fBReturns\fP
.RS 4
A list containing all cell IDs the player is currently inside or nearby\&.
.RE
.PP

.PP
Definition at line \fB258\fP of file \fBCullArea\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.CullArea\&.OnDrawGizmos ()"

.PP
Creates the cell hierarchy in editor and draws the cell view\&. 
.PP
Definition at line \fB101\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector2 Photon\&.Pun\&.UtilityScripts\&.CullArea\&.Center"

.PP
Definition at line \fB70\fP of file \fBCullArea\&.cs\fP\&.
.SS "readonly byte Photon\&.Pun\&.UtilityScripts\&.CullArea\&.FIRST_GROUP_ID = 1"

.PP
This represents the first ID which is assigned to the first created cell\&. If you already have some interest groups blocking this first ID, fell free to change it\&. However increasing the first group ID decreases the maximum amount of allowed cells\&. Allowed values are in range from 1 to 250\&. 
.PP
Definition at line \fB34\fP of file \fBCullArea\&.cs\fP\&.
.SS "const int Photon\&.Pun\&.UtilityScripts\&.CullArea\&.MAX_NUMBER_OF_SUBDIVISIONS = 3\fC [static]\fP"

.PP
Definition at line \fB26\fP of file \fBCullArea\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.CullArea\&.NumberOfSubdivisions"

.PP
Definition at line \fB75\fP of file \fBCullArea\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.CullArea\&.RecreateCellHierarchy = false"

.PP
Definition at line \fB84\fP of file \fBCullArea\&.cs\fP\&.
.SS "Vector2 Photon\&.Pun\&.UtilityScripts\&.CullArea\&.Size = new Vector2(25\&.0f, 25\&.0f)"

.PP
Definition at line \fB71\fP of file \fBCullArea\&.cs\fP\&.
.SS "readonly int [] Photon\&.Pun\&.UtilityScripts\&.CullArea\&.SUBDIVISION_FIRST_LEVEL_ORDER = new int[4] { 0, 1, 1, 1 }"

.PP
This represents the order in which updates are sent\&. The number represents the subdivision of the cell hierarchy:
.IP "\(bu" 2
0: message is sent to all players
.IP "\(bu" 2
1: message is sent to players who are interested in the matching cell of the first subdivision If there is only one subdivision we are sending one update to all players before sending three consequent updates only to players who are in the same cell or interested in updates of the current cell\&. 
.PP

.PP
Definition at line \fB45\fP of file \fBCullArea\&.cs\fP\&.
.SS "readonly int [] Photon\&.Pun\&.UtilityScripts\&.CullArea\&.SUBDIVISION_SECOND_LEVEL_ORDER = new int[8] { 0, 2, 1, 2, 0, 2, 1, 2 }"

.PP
This represents the order in which updates are sent\&. The number represents the subdivision of the cell hierarchy:
.IP "\(bu" 2
0: message is sent to all players
.IP "\(bu" 2
1: message is sent to players who are interested in the matching cell of the first subdivision
.IP "\(bu" 2
2: message is sent to players who are interested in the matching cell of the second subdivision If there are two subdivisions we are sending every second update only to players who are in the same cell or interested in updates of the current cell\&. 
.PP

.PP
Definition at line \fB56\fP of file \fBCullArea\&.cs\fP\&.
.SS "readonly int [] Photon\&.Pun\&.UtilityScripts\&.CullArea\&.SUBDIVISION_THIRD_LEVEL_ORDER = new int[12] { 0, 3, 2, 3, 1, 3, 2, 3, 1, 3, 2, 3 }"

.PP
This represents the order in which updates are sent\&. The number represents the subdivision of the cell hierarchy:
.IP "\(bu" 2
0: message is sent to all players
.IP "\(bu" 2
1: message is sent to players who are interested in the matching cell of the first subdivision
.IP "\(bu" 2
2: message is sent to players who are interested in the matching cell of the second subdivision
.IP "\(bu" 2
3: message is sent to players who are interested in the matching cell of the third subdivision If there are two subdivisions we are sending every second update only to players who are in the same cell or interested in updates of the current cell\&. 
.PP

.PP
Definition at line \fB68\fP of file \fBCullArea\&.cs\fP\&.
.SS "Vector2 [] Photon\&.Pun\&.UtilityScripts\&.CullArea\&.Subdivisions = new Vector2[\fBMAX_NUMBER_OF_SUBDIVISIONS\fP]"

.PP
Definition at line \fB73\fP of file \fBCullArea\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.CullArea\&.YIsUpAxis = false"

.PP
Definition at line \fB83\fP of file \fBCullArea\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.UtilityScripts\&.CullArea\&.CellCount\fC [get]\fP"

.PP
Definition at line \fB77\fP of file \fBCullArea\&.cs\fP\&.
.SS "\fBCellTree\fP Photon\&.Pun\&.UtilityScripts\&.CullArea\&.CellTree\fC [get]\fP"

.PP
Definition at line \fB79\fP of file \fBCullArea\&.cs\fP\&.
.SS "Dictionary<int, GameObject> Photon\&.Pun\&.UtilityScripts\&.CullArea\&.Map\fC [get]\fP"

.PP
Definition at line \fB81\fP of file \fBCullArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
