.TH "Photon.Pun.Simple.IContactTrigger" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IContactTrigger
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsumption\fP \fBContactCallbacks\fP (\fBContactEvent\fP contactEvent)"
.br
.ti -1c
.RI "void \fBOnContact\fP (\fBIContactTrigger\fP otherCT, \fBContactType\fP contactType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNetObject\fP \fBNetObj\fP\fC [get]\fP"
.br
.ti -1c
.RI "byte \fBIndex\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBIContactTrigger\fP \fBProxy\fP\fC [getset]\fP"
.br
.ti -1c
.RI "bool \fBPreventRepeats\fP\fC [getset]\fP"
.br
.ti -1c
.RI "List< \fBIContactSystem\fP > \fBContactSystems\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBISyncContact\fP \fBSyncContact\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBIContactGroupsAssign\fP \fBContactGroupsAssign\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBIContactTrigger\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBConsumption\fP Photon\&.Pun\&.Simple\&.IContactTrigger\&.ContactCallbacks (\fBContactEvent\fP contactEvent)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.IContactTrigger\&.OnContact (\fBIContactTrigger\fP otherCT, \fBContactType\fP contactType)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.ContactTrigger\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIContactGroupsAssign\fP Photon\&.Pun\&.Simple\&.IContactTrigger\&.ContactGroupsAssign\fC [get]\fP"

.PP
Definition at line \fB20\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "List<\fBIContactSystem\fP> Photon\&.Pun\&.Simple\&.IContactTrigger\&.ContactSystems\fC [get]\fP"

.PP
Definition at line \fB18\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "byte Photon\&.Pun\&.Simple\&.IContactTrigger\&.Index\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB13\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "\fBNetObject\fP Photon\&.Pun\&.Simple\&.IContactTrigger\&.NetObj\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.IContactTrigger\&.PreventRepeats\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB17\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "\fBIContactTrigger\fP Photon\&.Pun\&.Simple\&.IContactTrigger\&.Proxy\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB16\fP of file \fBIContactTrigger\&.cs\fP\&.
.SS "\fBISyncContact\fP Photon\&.Pun\&.Simple\&.IContactTrigger\&.SyncContact\fC [get]\fP"

.PP
Definition at line \fB19\fP of file \fBIContactTrigger\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
