.TH "Photon.Pun.Simple.Vital" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Vital
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVital\fP (\fBVitalDefinition\fP vitalDef)"
.br
.ti -1c
.RI "void \fBInitialize\fP (float tickDuration)"
.br
.ti -1c
.RI "void \fBResetValues\fP ()"
.br
.ti -1c
.RI "void \fBAddIOnVitalChange\fP (\fBIOnVitalChange\fP cb)"
.br
.ti -1c
.RI "void \fBRemoveIOnVitalChange\fP (\fBIOnVitalChange\fP cb)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBVitalData\fP vdata)"
.br
.ti -1c
.RI "double \fBApplyCharges\fP (double amt, bool allowOverload, bool ignoreAbsorbtion)"
.br
.RI "Apply damage to vital, accounting for absorption\&. "
.ti -1c
.RI "bool \fBIsFull\fP (bool allowOverload)"
.br
.RI "Is this vital currently at its max (can its value NOT be increased) "
.ti -1c
.RI "double \fBApplyChange\fP (\fBIVitalsContactReactor\fP iVitalsAffector, \fBContactEvent\fP contectEvent)"
.br
.RI "Apply a change to this vital, and return how much was consumed\&. "
.ti -1c
.RI "double \fBApplyChange\fP (double amount, \fBIVitalsContactReactor\fP reactor=null)"
.br
.RI "Apply a change to this vital, and return how much was consumed\&. "
.ti -1c
.RI "void \fBDisruptRegen\fP ()"
.br
.ti -1c
.RI "void \fBDisruptDecay\fP ()"
.br
.ti -1c
.RI "double \fBTestApplyChange\fP (\fBIVitalsContactReactor\fP iVitalsAffector, \fBContactEvent\fP contactEvent)"
.br
.ti -1c
.RI "double \fBTestApplyChange\fP (double charge, \fBIVitalsContactReactor\fP iVitalsAffector)"
.br
.RI "Get the results of ApplyChange without actually applying them\&. "
.ti -1c
.RI "void \fBSimulate\fP ()"
.br
.RI "Apply Regeneration and Decay to current state "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBIOnVitalValueChange\fP > \fBOnValueChangeCallbacks\fP = new List<\fBIOnVitalValueChange\fP>(0)"
.br
.ti -1c
.RI "List< \fBIOnVitalParamChange\fP > \fBOnParamChangeCallbacks\fP = new List<\fBIOnVitalParamChange\fP>(0)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVitalDefinition\fP \fBVitalDef\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBVitalData\fP \fBVitalData\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBValue\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBTicksUntilDecay\fP\fC [getset]\fP"
.br
.ti -1c
.RI "int \fBTicksUntilRegen\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBVital\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.Vital\&.Vital (\fBVitalDefinition\fP vitalDef)"

.PP
Definition at line \fB46\fP of file \fBVital\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.AddIOnVitalChange (\fBIOnVitalChange\fP cb)"

.PP
Definition at line \fB72\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.Apply (\fBVitalData\fP vdata)"

.PP
Definition at line \fB96\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.ApplyChange (double amount, \fBIVitalsContactReactor\fP reactor = \fCnull\fP)"

.PP
Apply a change to this vital, and return how much was consumed\&. 
.PP
Definition at line \fB143\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.ApplyChange (\fBIVitalsContactReactor\fP iVitalsAffector, \fBContactEvent\fP contectEvent)"

.PP
Apply a change to this vital, and return how much was consumed\&. 
.PP
Definition at line \fB134\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.ApplyCharges (double amt, bool allowOverload, bool ignoreAbsorbtion)"

.PP
Apply damage to vital, accounting for absorption\&. Returns consumed amount\&. 
.PP
Definition at line \fB106\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.DisruptDecay ()"

.PP
Definition at line \fB187\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.DisruptRegen ()"

.PP
Definition at line \fB182\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.Initialize (float tickDuration)"

.PP
Definition at line \fB51\fP of file \fBVital\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.Vital\&.IsFull (bool allowOverload)"

.PP
Is this vital currently at its max (can its value NOT be increased) 
.PP
\fBParameters\fP
.RS 4
\fIallowOverload\fP Whether to check against Max value or Full value
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB126\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.RemoveIOnVitalChange (\fBIOnVitalChange\fP cb)"

.PP
Definition at line \fB83\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.ResetValues ()"
Notify UI and other subscribed components of change
.PP
Definition at line \fB57\fP of file \fBVital\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.Vital\&.Simulate ()"

.PP
Apply Regeneration and Decay to current state Regeneration
.PP
Overload decay
.PP
Definition at line \fB235\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.TestApplyChange (double charge, \fBIVitalsContactReactor\fP iVitalsAffector)"

.PP
Get the results of ApplyChange without actually applying them\&. 
.PP
Definition at line \fB200\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.TestApplyChange (\fBIVitalsContactReactor\fP iVitalsAffector, \fBContactEvent\fP contactEvent)"

.PP
Definition at line \fB192\fP of file \fBVital\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBIOnVitalParamChange\fP> Photon\&.Pun\&.Simple\&.Vital\&.OnParamChangeCallbacks = new List<\fBIOnVitalParamChange\fP>(0)"

.PP
Definition at line \fB70\fP of file \fBVital\&.cs\fP\&.
.SS "List<\fBIOnVitalValueChange\fP> Photon\&.Pun\&.Simple\&.Vital\&.OnValueChangeCallbacks = new List<\fBIOnVitalValueChange\fP>(0)"

.PP
Definition at line \fB69\fP of file \fBVital\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.Vital\&.TicksUntilDecay\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB43\fP of file \fBVital\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.Vital\&.TicksUntilRegen\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB44\fP of file \fBVital\&.cs\fP\&.
.SS "double Photon\&.Pun\&.Simple\&.Vital\&.Value\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB22\fP of file \fBVital\&.cs\fP\&.
.SS "\fBVitalData\fP Photon\&.Pun\&.Simple\&.Vital\&.VitalData\fC [get]\fP"

.PP
Definition at line \fB20\fP of file \fBVital\&.cs\fP\&.
.SS "\fBVitalDefinition\fP Photon\&.Pun\&.Simple\&.Vital\&.VitalDef\fC [get]\fP"

.PP
Definition at line \fB16\fP of file \fBVital\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
