.TH "Photon.Compression.ArraySerializeHalfExt" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.ArraySerializeHalfExt
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBWriteHalf\fP (this byte[] buffer, float value, ref int bitposition)"
.br
.ti -1c
.RI "static float \fBReadHalf\fP (this byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "static void \fBAppendHalf\fP (this byte[] buffer, float value, ref int bitposition)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBArrayPackHalfExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.ArraySerializeHalfExt\&.AppendHalf (this byte[] buffer, float value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB41\fP of file \fBArrayPackHalfExt\&.cs\fP\&.
.SS "static float Photon\&.Compression\&.ArraySerializeHalfExt\&.ReadHalf (this byte[] buffer, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB36\fP of file \fBArrayPackHalfExt\&.cs\fP\&.
.SS "static void Photon\&.Compression\&.ArraySerializeHalfExt\&.WriteHalf (this byte[] buffer, float value, ref int bitposition)\fC [static]\fP"

.PP
Definition at line \fB31\fP of file \fBArrayPackHalfExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
