.TH "Photon.Pun.Simple.BasicInventory" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.BasicInventory \- A simple usable example of an IInventory system\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.Inventory< Vector3Int >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBTestCapacity\fP (\fBIInventoryable\fP< Vector3Int > inventoryable)"
.br
.RI "Return if the object being picked up exceeds remaining inventory\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3Int \fBcapacity\fP = new Vector3Int(16, 1, 1)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVolume\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBUsed\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBRemaining\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A simple usable example of an IInventory system\&. 

Either create your own by deriving from the \fBInventory\fP base class or by creating your own class using IInventory\&. You can also derive from this class to extend \fBBasicInventory\fP if you only want to make a minor adjustment to it for your needs\&. 
.PP
Definition at line \fB18\fP of file \fBBasicInventory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Photon\&.Pun\&.Simple\&.BasicInventory\&.TestCapacity (\fBIInventoryable\fP< Vector3Int > inventoryable)"

.PP
Return if the object being picked up exceeds remaining inventory\&. 
.PP
\fBParameters\fP
.RS 4
\fIinventoryable\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB53\fP of file \fBBasicInventory\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3Int Photon\&.Pun\&.Simple\&.BasicInventory\&.capacity = new Vector3Int(16, 1, 1)"

.PP
Definition at line \fB22\fP of file \fBBasicInventory\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.BasicInventory\&.Remaining\fC [get]\fP"

.PP
Definition at line \fB46\fP of file \fBBasicInventory\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.BasicInventory\&.Used\fC [get]\fP"

.PP
Definition at line \fB25\fP of file \fBBasicInventory\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.BasicInventory\&.Volume\fC [get]\fP"

.PP
Definition at line \fB23\fP of file \fBBasicInventory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
