.TH "Photon.Pun.Demo.Cockpit.Forms.SetRoomCustomPropertyUIForm" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.Forms.SetRoomCustomPropertyUIForm \- Room custom properties UI Form\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOnSubmitEvent\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBEndEditOnEnter\fP ()"
.br
.ti -1c
.RI "void \fBSubmitForm\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "InputField \fBPropertyValueInput\fP"
.br
.ti -1c
.RI "\fBOnSubmitEvent\fP \fBOnSubmit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Room custom properties UI Form\&. 


.PP
Definition at line \fB19\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.SetRoomCustomPropertyUIForm\&.EndEditOnEnter ()"

.PP
Definition at line \fB34\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.SetRoomCustomPropertyUIForm\&.Start ()"

.PP
Definition at line \fB28\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.SetRoomCustomPropertyUIForm\&.SubmitForm ()"

.PP
Definition at line \fB42\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBOnSubmitEvent\fP Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.SetRoomCustomPropertyUIForm\&.OnSubmit"

.PP
Definition at line \fB26\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.Forms\&.SetRoomCustomPropertyUIForm\&.PropertyValueInput"

.PP
Definition at line \fB21\fP of file \fBSetRoomCustomPropertyUIForm\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
