.TH "Photon.Pun.Simple.Debugging.UIConsole" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.Debugging.UIConsole
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (object str)"
.br
.RI "Shortcut for Append to the strb StringBuilder\&. "
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (string str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (int str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (uint str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (byte str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (sbyte str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (short str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (ushort str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (long str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (ulong str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (float str)"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB_\fP (double str)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBLog\fP (string str)"
.br
.ti -1c
.RI "static void \fBRefresh\fP ()"
.br
.RI "Update the UI element with the current StringBuilder strb value\&. "
.ti -1c
.RI "static void \fBClear\fP ()"
.br
.ti -1c
.RI "static \fBUIConsole\fP \fBCreateGUI\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmaxSize\fP = 3000"
.br
.ti -1c
.RI "bool \fBlogToDebug\fP = true"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly StringBuilder \fBstrb\fP = new StringBuilder()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBUIConsole\fP \fBSingle\fP\fC [get]\fP"
.br
.ti -1c
.RI "\fBUIConsole\fP \fB__\fP\fC [get]\fP"
.br
.RI "Shortcut for Append(Space)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBUIConsole\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (byte str)"

.PP
Definition at line \fB70\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (double str)"

.PP
Definition at line \fB77\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (float str)"

.PP
Definition at line \fB76\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (int str)"

.PP
Definition at line \fB68\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (long str)"

.PP
Definition at line \fB74\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (object str)"

.PP
Shortcut for Append to the strb StringBuilder\&. Be sure to \fBRefresh()\fP to apply to UI\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP 
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (sbyte str)"

.PP
Definition at line \fB71\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (short str)"

.PP
Definition at line \fB72\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (string str)"

.PP
Definition at line \fB67\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (uint str)"

.PP
Definition at line \fB69\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (ulong str)"

.PP
Definition at line \fB75\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&._ (ushort str)"

.PP
Definition at line \fB73\fP of file \fBUIConsole\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.Clear ()\fC [static]\fP"

.PP
Definition at line \fB98\fP of file \fBUIConsole\&.cs\fP\&.
.SS "static \fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.CreateGUI ()\fC [static]\fP"

.PP
Definition at line \fB106\fP of file \fBUIConsole\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.Log (string str)\fC [static]\fP"

.PP
Definition at line \fB44\fP of file \fBUIConsole\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.Refresh ()\fC [static]\fP"

.PP
Update the UI element with the current StringBuilder strb value\&. 
.PP
Definition at line \fB87\fP of file \fBUIConsole\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.logToDebug = true"

.PP
Definition at line \fB17\fP of file \fBUIConsole\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.maxSize = 3000"

.PP
Definition at line \fB15\fP of file \fBUIConsole\&.cs\fP\&.
.SS "readonly StringBuilder Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.strb = new StringBuilder()\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBUIConsole\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.__\fC [get]\fP"

.PP
Shortcut for Append(Space)\&. 
.PP
Definition at line \fB82\fP of file \fBUIConsole\&.cs\fP\&.
.SS "\fBUIConsole\fP Photon\&.Pun\&.Simple\&.Debugging\&.UIConsole\&.Single\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB22\fP of file \fBUIConsole\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
