.TH "Photon.Pun.Demo.Cockpit.FriendListView.FriendDetail" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.FriendListView.FriendDetail \- Friend detail class This info comes from your social network and is meant to be matched against the friendInfo from \fBPhoton\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFriendDetail\fP (string \fBNickName\fP, string \fBUserId\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNickName\fP"
.br
.ti -1c
.RI "string \fBUserId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Friend detail class This info comes from your social network and is meant to be matched against the friendInfo from \fBPhoton\fP 
.PP
Definition at line \fB32\fP of file \fBFriendListView\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListView\&.FriendDetail\&.FriendDetail (string NickName, string UserId)"

.PP
Definition at line \fB34\fP of file \fBFriendListView\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListView\&.FriendDetail\&.NickName"

.PP
Definition at line \fB40\fP of file \fBFriendListView\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Cockpit\&.FriendListView\&.FriendDetail\&.UserId"

.PP
Definition at line \fB41\fP of file \fBFriendListView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
