.TH "Photon.Pun.ServerSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.ServerSettings \- Collection of connection-relevant settings, used internally by \fBPhotonNetwork\&.ConnectUsingSettings\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUseCloud\fP (string cloudAppid, string code='')"
.br
.RI "Sets appid and region code in the AppSettings\&. Used in Editor\&."
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "String summary of the AppSettings\&."
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsAppId\fP (string val)"
.br
.RI "Checks if a string is a Guid by attempting to create one\&. "
.ti -1c
.RI "static void \fBResetBestRegionCodeInPreferences\fP ()"
.br
.RI "Sets the 'best region summary' in the preferences to null\&. On next start, the client will ping all available\&."
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAppSettings\fP \fBAppSettings\fP"
.br
.ti -1c
.RI "string \fBDevRegion\fP"
.br
.RI "Region that will be used by the Editor and Development Builds\&. This ensures all users will be in the same region for testing\&."
.ti -1c
.RI "\fBPunLogLevel\fP \fBPunLogging\fP = \fBPunLogLevel\&.ErrorsOnly\fP"
.br
.ti -1c
.RI "bool \fBEnableSupportLogger\fP"
.br
.ti -1c
.RI "bool \fBRunInBackground\fP = true"
.br
.ti -1c
.RI "bool \fBStartInOfflineMode\fP"
.br
.ti -1c
.RI "List< string > \fBRpcList\fP = new List<string>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBBestRegionSummaryInPreferences\fP\fC [get]\fP"
.br
.RI "Gets the 'best region summary' from the preferences\&. "
.in -1c
.SH "Detailed Description"
.PP 
Collection of connection-relevant settings, used internally by \fBPhotonNetwork\&.ConnectUsingSettings\fP\&. 

Includes the AppSettings class from the \fBRealtime\fP APIs plus some other, PUN-relevant, settings\&.
.PP
Definition at line \fB27\fP of file \fBServerSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Photon\&.Pun\&.ServerSettings\&.IsAppId (string val)\fC [static]\fP"

.PP
Checks if a string is a Guid by attempting to create one\&. 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The potential guid to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if new Guid(val) did not fail\&.
.RE
.PP

.PP
Definition at line \fB68\fP of file \fBServerSettings\&.cs\fP\&.
.SS "static void Photon\&.Pun\&.ServerSettings\&.ResetBestRegionCodeInPreferences ()\fC [static]\fP"

.PP
Sets the 'best region summary' in the preferences to null\&. On next start, the client will ping all available\&.
.PP
Definition at line \fB89\fP of file \fBServerSettings\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.ServerSettings\&.ToString ()"

.PP
String summary of the AppSettings\&.
.PP
Definition at line \fB95\fP of file \fBServerSettings\&.cs\fP\&.
.SS "void Photon\&.Pun\&.ServerSettings\&.UseCloud (string cloudAppid, string code = \fC''\fP)"

.PP
Sets appid and region code in the AppSettings\&. Used in Editor\&.
.PP
Definition at line \fB58\fP of file \fBServerSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAppSettings\fP Photon\&.Pun\&.ServerSettings\&.AppSettings"

.PP
Definition at line \fB30\fP of file \fBServerSettings\&.cs\fP\&.
.SS "string Photon\&.Pun\&.ServerSettings\&.DevRegion"

.PP
Region that will be used by the Editor and Development Builds\&. This ensures all users will be in the same region for testing\&.
.PP
Definition at line \fB34\fP of file \fBServerSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.ServerSettings\&.EnableSupportLogger"

.PP
Definition at line \fB40\fP of file \fBServerSettings\&.cs\fP\&.
.SS "\fBPunLogLevel\fP Photon\&.Pun\&.ServerSettings\&.PunLogging = \fBPunLogLevel\&.ErrorsOnly\fP"

.PP
Definition at line \fB37\fP of file \fBServerSettings\&.cs\fP\&.
.SS "List<string> Photon\&.Pun\&.ServerSettings\&.RpcList = new List<string>()"

.PP
Definition at line \fB49\fP of file \fBServerSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.ServerSettings\&.RunInBackground = true"

.PP
Definition at line \fB43\fP of file \fBServerSettings\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.ServerSettings\&.StartInOfflineMode"

.PP
Definition at line \fB46\fP of file \fBServerSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Photon\&.Pun\&.ServerSettings\&.BestRegionSummaryInPreferences\fC [static]\fP, \fC [get]\fP"

.PP
Gets the 'best region summary' from the preferences\&. The best region code in preferences\&.
.PP
Definition at line \fB83\fP of file \fBServerSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
