.TH "Photon.Pun.IPunInstantiateMagicCallback" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.IPunInstantiateMagicCallback
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPhotonInstantiate\fP (\fBPhotonMessageInfo\fP info)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB93\fP of file \fBIPunCallbacks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.IPunInstantiateMagicCallback\&.OnPhotonInstantiate (\fBPhotonMessageInfo\fP info)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
