.TH "Photon.Pun.Simple.VitalNameType" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.VitalNameType \- TODO: Make this a generic when working on \&.net versions that supports enum generic constraint\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVitalNameType\fP (\fBVitalType\fP vitalType)"
.br
.ti -1c
.RI "\fBVitalNameType\fP (string \fBname\fP)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVitalType\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBenumNames\fP = System\&.Enum\&.GetNames(typeof(\fBVitalType\fP))"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string[] \fBEnumNames\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: Make this a generic when working on \&.net versions that supports enum generic constraint\&. 

Enum type and name pair\&. Name will be the same text as the enum, unless the enum is Custom\&. Name value is converted to hash in editor and can be used as dict key\&. 
.PP
Definition at line \fB25\fP of file \fBVitalNameType\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.VitalNameType\&.VitalNameType (\fBVitalType\fP vitalType)"

.PP
Definition at line \fB31\fP of file \fBVitalNameType\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.VitalNameType\&.VitalNameType (string name)"

.PP
Definition at line \fB38\fP of file \fBVitalNameType\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.VitalNameType\&.ToString ()"

.PP
Definition at line \fB48\fP of file \fBVitalNameType\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] Photon\&.Pun\&.Simple\&.VitalNameType\&.enumNames = System\&.Enum\&.GetNames(typeof(\fBVitalType\fP))\fC [static]\fP"

.PP
Definition at line \fB45\fP of file \fBVitalNameType\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.VitalNameType\&.hash"

.PP
Definition at line \fB28\fP of file \fBVitalNameType\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Simple\&.VitalNameType\&.name"

.PP
Definition at line \fB29\fP of file \fBVitalNameType\&.cs\fP\&.
.SS "\fBVitalType\fP Photon\&.Pun\&.Simple\&.VitalNameType\&.type"

.PP
Definition at line \fB27\fP of file \fBVitalNameType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string [] Photon\&.Pun\&.Simple\&.VitalNameType\&.EnumNames\fC [get]\fP"

.PP
Definition at line \fB46\fP of file \fBVitalNameType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
