.TH "Photon.Pun.Simple.GhostWorlds.IHasNetworkID" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.GhostWorlds.IHasNetworkID
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "uint \fBViewID\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBIHasNetworkID\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "uint Photon\&.Pun\&.Simple\&.GhostWorlds\&.IHasNetworkID\&.ViewID\fC [get]\fP"

.PP
Definition at line \fB12\fP of file \fBIHasNetworkID\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
