.TH "Photon.Compression.LiteCrusher< TComp, T >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.LiteCrusher< TComp, T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits LiteCrusher\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract TComp \fBEncode\fP (T val)"
.br
.ti -1c
.RI "abstract T \fBDecode\fP (uint val)"
.br
.ti -1c
.RI "abstract TComp \fBWriteValue\fP (T val, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "abstract void \fBWriteCValue\fP (uint val, byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "abstract T \fBReadValue\fP (byte[] buffer, ref int bitposition)"
.br
.ti -1c
.RI "abstract TComp \fBReadCValue\fP (byte[] buffer, ref int bitposition)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBGetBitsForMaxValue\fP (uint maxvalue)"
.br
.RI "Returns the min number of bits required to describe any value between 0 and uint maxvalue "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fIstruct\fP
.TP
\fITComp\fP : \fIstruct\fP
.PP
Definition at line \fB24\fP of file \fBLiteCrusher\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract T \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.Decode (uint val)\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Compression\&.LiteFloatCrusher\fP, and \fBPhoton\&.Compression\&.LiteIntCrusher\fP\&.
.SS "abstract TComp \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.Encode (T val)\fC [pure virtual]\fP"

.SS "static int \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.GetBitsForMaxValue (uint maxvalue)\fC [static]\fP"

.PP
Returns the min number of bits required to describe any value between 0 and uint maxvalue 
.PP
Definition at line \fB14\fP of file \fBLiteCrusher\&.cs\fP\&.
.SS "abstract TComp \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.ReadCValue (byte[] buffer, ref int bitposition)\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Compression\&.LiteFloatCrusher\fP, and \fBPhoton\&.Compression\&.LiteIntCrusher\fP\&.
.SS "abstract T \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.ReadValue (byte[] buffer, ref int bitposition)\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Compression\&.LiteFloatCrusher\fP, and \fBPhoton\&.Compression\&.LiteIntCrusher\fP\&.
.SS "abstract void \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.WriteCValue (uint val, byte[] buffer, ref int bitposition)\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Compression\&.LiteFloatCrusher\fP, and \fBPhoton\&.Compression\&.LiteIntCrusher\fP\&.
.SS "abstract TComp \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.WriteValue (T val, byte[] buffer, ref int bitposition)\fC [pure virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int \fBPhoton\&.Compression\&.LiteCrusher\fP< TComp, T >\&.bits\fC [protected]\fP"

.PP
Definition at line \fB9\fP of file \fBLiteCrusher\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
