.TH "Photon.Pun.Simple.SyncNodeMover.TRSDefinition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncNodeMover.TRSDefinition
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.TRSDefinitionBase\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAxisMask\fP \fBincludeAxes\fP = \fBAxisMask\&.XYZ\fP"
.br
.ti -1c
.RI "\fBMovementRelation\fP \fBrelation\fP = MovementRelation\&.Relative"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB45\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAxisMask\fP Photon\&.Pun\&.Simple\&.SyncNodeMover\&.TRSDefinition\&.includeAxes = \fBAxisMask\&.XYZ\fP"

.PP
Definition at line \fB47\fP of file \fBSyncNodeMover\&.cs\fP\&.
.SS "\fBMovementRelation\fP Photon\&.Pun\&.Simple\&.SyncNodeMover\&.TRSDefinition\&.relation = MovementRelation\&.Relative"

.PP
Definition at line \fB48\fP of file \fBSyncNodeMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
