.TH "Photon.Pun.Simple.HitscanDefinition" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.HitscanDefinition \- This is the inspector element for \fBHitscanDefinition\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReplicate\fP \fBownerToAuthority\fP = \fBReplicate\&.Hits\fP"
.br
.ti -1c
.RI "\fBReplicate\fP \fBauthorityToAll\fP = \fBReplicate\&.Hits\fP"
.br
.ti -1c
.RI "LayerMask \fBlayerMask\fP = \-1"
.br
.ti -1c
.RI "bool \fBuseOffset\fP"
.br
.ti -1c
.RI "Vector3 \fBoffset1\fP = new Vector3(0, 0, 0)"
.br
.ti -1c
.RI "Vector3 \fBoffset2\fP = new Vector3(0, 1, 0)"
.br
.ti -1c
.RI "Vector3 \fBhalfExtents\fP = new Vector3(1, 1, 1)"
.br
.ti -1c
.RI "Vector3 \fBorientation\fP = new Vector3(0, 0, 0)"
.br
.ti -1c
.RI "\fBHitscanType\fP \fBhitscanType\fP = \fBHitscanType\&.Raycast\fP"
.br
.ti -1c
.RI "float \fBdistance\fP = 100f"
.br
.ti -1c
.RI "float \fBradius\fP = 1"
.br
.ti -1c
.RI "bool \fBnearestOnly\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the inspector element for \fBHitscanDefinition\fP\&. 


.PP
Definition at line \fB20\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBReplicate\fP Photon\&.Pun\&.Simple\&.HitscanDefinition\&.authorityToAll = \fBReplicate\&.Hits\fP"

.PP
Definition at line \fB24\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.HitscanDefinition\&.distance = 100f"

.PP
Definition at line \fB35\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.HitscanDefinition\&.halfExtents = new Vector3(1, 1, 1)"

.PP
Definition at line \fB32\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "\fBHitscanType\fP Photon\&.Pun\&.Simple\&.HitscanDefinition\&.hitscanType = \fBHitscanType\&.Raycast\fP"

.PP
Definition at line \fB34\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "LayerMask Photon\&.Pun\&.Simple\&.HitscanDefinition\&.layerMask = \-1"

.PP
Definition at line \fB28\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.HitscanDefinition\&.nearestOnly = true"

.PP
Definition at line \fB37\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.HitscanDefinition\&.offset1 = new Vector3(0, 0, 0)"

.PP
Definition at line \fB30\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.HitscanDefinition\&.offset2 = new Vector3(0, 1, 0)"

.PP
Definition at line \fB31\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "Vector3 Photon\&.Pun\&.Simple\&.HitscanDefinition\&.orientation = new Vector3(0, 0, 0)"

.PP
Definition at line \fB33\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "\fBReplicate\fP Photon\&.Pun\&.Simple\&.HitscanDefinition\&.ownerToAuthority = \fBReplicate\&.Hits\fP"

.PP
Definition at line \fB23\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "float Photon\&.Pun\&.Simple\&.HitscanDefinition\&.radius = 1"

.PP
Definition at line \fB36\fP of file \fBHitscanDefinition\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.HitscanDefinition\&.useOffset"

.PP
Definition at line \fB29\fP of file \fBHitscanDefinition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
