.TH "Photon.Pun.PhotonAnimatorView" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PhotonAnimatorView \- This class helps you to synchronize Mecanim animations Simply add the component to your GameObject and make sure that the \fBPhotonAnimatorView\fP is added to the list of observed components  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP, and \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSynchronizedLayer\fP"
.br
.ti -1c
.RI "class \fBSynchronizedParameter\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBParameterType\fP { \fBFloat\fP = 1, \fBInt\fP = 3, \fBBool\fP = 4, \fBTrigger\fP = 9 }"
.br
.ti -1c
.RI "enum \fBSynchronizeType\fP { \fBDisabled\fP = 0, \fBDiscrete\fP = 1, \fBContinuous\fP = 2 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCacheDiscreteTriggers\fP ()"
.br
.RI "Caches the discrete triggers values for keeping track of raised triggers, and will be reseted after the sync routine got performed "
.ti -1c
.RI "bool \fBDoesLayerSynchronizeTypeExist\fP (int layerIndex)"
.br
.RI "Check if a specific layer is configured to be synchronize "
.ti -1c
.RI "bool \fBDoesParameterSynchronizeTypeExist\fP (string name)"
.br
.RI "Check if the specified parameter is configured to be synchronized "
.ti -1c
.RI "List< \fBSynchronizedLayer\fP > \fBGetSynchronizedLayers\fP ()"
.br
.RI "Get a list of all synchronized layers "
.ti -1c
.RI "List< \fBSynchronizedParameter\fP > \fBGetSynchronizedParameters\fP ()"
.br
.RI "Get a list of all synchronized parameters "
.ti -1c
.RI "\fBSynchronizeType\fP \fBGetLayerSynchronizeType\fP (int layerIndex)"
.br
.RI "Gets the type how the layer is synchronized "
.ti -1c
.RI "\fBSynchronizeType\fP \fBGetParameterSynchronizeType\fP (string name)"
.br
.RI "Gets the type how the parameter is synchronized "
.ti -1c
.RI "void \fBSetLayerSynchronized\fP (int layerIndex, \fBSynchronizeType\fP synchronizeType)"
.br
.RI "Sets the how a layer should be synchronized "
.ti -1c
.RI "void \fBSetParameterSynchronized\fP (string name, \fBParameterType\fP type, \fBSynchronizeType\fP synchronizeType)"
.br
.RI "Sets the how a parameter should be synchronized "
.ti -1c
.RI "void \fBOnPhotonSerializeView\fP (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"
.br
.RI "Called by PUN several times per second, so that your script can write and read synchronization data for the \fBPhotonView\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class helps you to synchronize Mecanim animations Simply add the component to your GameObject and make sure that the \fBPhotonAnimatorView\fP is added to the list of observed components 

When Using Trigger Parameters, make sure the component that sets the trigger is higher in the stack of Components on the GameObject than '\fBPhotonAnimatorView\fP' Triggers are raised true during one frame only\&. 
.PP
Definition at line \fB28\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.PhotonAnimatorView\&.ParameterType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFloat \fP\fP
.TP
\fB\fIInt \fP\fP
.TP
\fB\fIBool \fP\fP
.TP
\fB\fITrigger \fP\fP
.PP
Definition at line \fB32\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.PhotonAnimatorView\&.SynchronizeType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisabled \fP\fP
.TP
\fB\fIDiscrete \fP\fP
.TP
\fB\fIContinuous \fP\fP
.PP
Definition at line \fB41\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.PhotonAnimatorView\&.CacheDiscreteTriggers ()"

.PP
Caches the discrete triggers values for keeping track of raised triggers, and will be reseted after the sync routine got performed 
.PP
Definition at line \fB160\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonAnimatorView\&.DoesLayerSynchronizeTypeExist (int layerIndex)"

.PP
Check if a specific layer is configured to be synchronize 
.PP
\fBParameters\fP
.RS 4
\fIlayerIndex\fP Index of the layer\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the layer is synchronized
.RE
.PP

.PP
Definition at line \fB182\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.PhotonAnimatorView\&.DoesParameterSynchronizeTypeExist (string name)"

.PP
Check if the specified parameter is configured to be synchronized 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the parameter\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if the parameter is synchronized
.RE
.PP

.PP
Definition at line \fB192\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "\fBSynchronizeType\fP Photon\&.Pun\&.PhotonAnimatorView\&.GetLayerSynchronizeType (int layerIndex)"

.PP
Gets the type how the layer is synchronized 
.PP
\fBParameters\fP
.RS 4
\fIlayerIndex\fP Index of the layer\&.
.RE
.PP
\fBReturns\fP
.RS 4
Disabled/Discrete/Continuous
.RE
.PP

.PP
Definition at line \fB220\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "\fBSynchronizeType\fP Photon\&.Pun\&.PhotonAnimatorView\&.GetParameterSynchronizeType (string name)"

.PP
Gets the type how the parameter is synchronized 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the parameter\&.
.RE
.PP
\fBReturns\fP
.RS 4
Disabled/Discrete/Continuous
.RE
.PP

.PP
Definition at line \fB237\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "List< \fBSynchronizedLayer\fP > Photon\&.Pun\&.PhotonAnimatorView\&.GetSynchronizedLayers ()"

.PP
Get a list of all synchronized layers 
.PP
\fBReturns\fP
.RS 4
List of \fBSynchronizedLayer\fP objects
.RE
.PP

.PP
Definition at line \fB201\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "List< \fBSynchronizedParameter\fP > Photon\&.Pun\&.PhotonAnimatorView\&.GetSynchronizedParameters ()"

.PP
Get a list of all synchronized parameters 
.PP
\fBReturns\fP
.RS 4
List of \fBSynchronizedParameter\fP objects
.RE
.PP

.PP
Definition at line \fB210\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonAnimatorView\&.OnPhotonSerializeView (\fBPhotonStream\fP stream, \fBPhotonMessageInfo\fP info)"

.PP
Called by PUN several times per second, so that your script can write and read synchronization data for the \fBPhotonView\fP\&. This method will be called in scripts that are assigned as Observed component of a \fBPhotonView\fP\&.
.br
 \fBPhotonNetwork\&.SerializationRate\fP affects how often this method is called\&.
.br
 \fBPhotonNetwork\&.SendRate\fP affects how often packages are sent by this client\&.
.br
.PP
Implementing this method, you can customize which data a \fBPhotonView\fP regularly synchronizes\&. Your code defines what is being sent (content) and how your data is used by receiving clients\&.
.PP
Unlike other callbacks, \fIOnPhotonSerializeView only gets called when it is assigned to a \fBPhotonView\fP\fP as PhotonView\&.observed script\&.
.PP
To make use of this method, the \fBPhotonStream\fP is essential\&. It will be in 'writing' mode' on the
client that controls a PhotonView (PhotonStream\&.IsWriting == true) and in 'reading mode' on the
remote clients that just receive that the controlling client sends\&.

If you skip writing any value into the stream, PUN will skip the update\&. Used carefully, this can
conserve bandwidth and messages (which have a limit per room/second)\&.

Note that OnPhotonSerializeView is not called on remote clients when the sender does not send
any update\&. This can't be used as 'x-times per second Update()"\&. 
.PP
Implements \fBPhoton\&.Pun\&.IPunObservable\fP\&.
.PP
Definition at line \fB529\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonAnimatorView\&.SetLayerSynchronized (int layerIndex, \fBSynchronizeType\fP synchronizeType)"

.PP
Sets the how a layer should be synchronized 
.PP
\fBParameters\fP
.RS 4
\fIlayerIndex\fP Index of the layer\&.
.br
\fIsynchronizeType\fP Disabled/Discrete/Continuous
.RE
.PP

.PP
Definition at line \fB254\fP of file \fBPhotonAnimatorView\&.cs\fP\&.
.SS "void Photon\&.Pun\&.PhotonAnimatorView\&.SetParameterSynchronized (string name, \fBParameterType\fP type, \fBSynchronizeType\fP synchronizeType)"

.PP
Sets the how a parameter should be synchronized 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the parameter\&.
.br
\fItype\fP The type of the parameter\&.
.br
\fIsynchronizeType\fP Disabled/Discrete/Continuous
.RE
.PP

.PP
Definition at line \fB279\fP of file \fBPhotonAnimatorView\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
