.TH "Photon.Pun.PunSceneViews" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.PunSceneViews \- Stores a \fBPhotonView\fP instances per viewId (key)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBPhotonView\fP > \fBViews\fP = new Dictionary<int, \fBPhotonView\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBPunSceneViews\fP \fBInstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores a \fBPhotonView\fP instances per viewId (key)\&. 

Instance is used as cache storage in-Editor\&. 
.PP
Definition at line \fB166\fP of file \fBPhotonViewHandler\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, \fBPhotonView\fP> Photon\&.Pun\&.PunSceneViews\&.Views = new Dictionary<int, \fBPhotonView\fP>()"

.PP
Definition at line \fB169\fP of file \fBPhotonViewHandler\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBPunSceneViews\fP Photon\&.Pun\&.PunSceneViews\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB172\fP of file \fBPhotonViewHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
