.TH "Photon.Pun.Simple.OnStateChangeKinematic" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.OnStateChangeKinematic
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP, \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP, \fBPhoton\&.Pun\&.Simple\&.IApplyOrder\fP, and \fBPhoton\&.Pun\&.Simple\&.IAutoKinematic\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAwake\fP ()"
.br
.RI "Be sure to use base\&.OnAwake() when overriding\&. "
.ti -1c
.RI "override void \fBOnAuthorityChanged\fP (bool isMine, bool controllerChanged)"
.br
.RI "Owner changes can get dicey, this reapplies the state after an owner change\&. "
.ti -1c
.RI "void \fBOnStateChange\fP (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo=null, bool isReady=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKinematicSetting\fP \fBonDespawned\fP = \fBKinematicSetting\&.Kinematic\fP"
.br
.ti -1c
.RI "\fBKinematicSetting\fP \fBonAnchored\fP = \fBKinematicSetting\&.Kinematic\fP"
.br
.ti -1c
.RI "\fBKinematicSetting\fP \fBonMounted\fP = \fBKinematicSetting\&.NonKinematic\fP"
.br
.ti -1c
.RI "\fBKinematicSetting\fP \fBonTransit\fP = \fBKinematicSetting\&.NonKinematic\fP"
.br
.ti -1c
.RI "\fBKinematicSetting\fP \fBonDropped\fP = \fBKinematicSetting\&.NonKinematic\fP"
.br
.ti -1c
.RI "\fBKinematicSetting\fP \fBonVisible\fP = \fBKinematicSetting\&.Default\fP"
.br
.ti -1c
.RI "bool \fBautoDestroy\fP = true"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSetUnownedKinematics\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetOwnedKinematics\fP (\fBObjState\fP state)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBApplyOrder\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBAutoKinematicEnabled\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.OnAuthorityChanged (bool isMine, bool controllerChanged)\fC [virtual]\fP"

.PP
Owner changes can get dicey, this reapplies the state after an owner change\&. 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB76\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.OnAwake ()\fC [virtual]\fP"

.PP
Be sure to use base\&.OnAwake() when overriding\&. This is called when the \fBNetObject\fP runs \fBAwake()\fP\&. All code that depends on the NetObj being initialized should use this rather than \fBAwake()\fP; 
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.PP
Definition at line \fB50\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.OnStateChange (\fBObjState\fP newState, \fBObjState\fP previousState, Transform attachmentTransform, \fBMount\fP attachTo = \fCnull\fP, bool isReady = \fCtrue\fP)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnStateChange\fP\&.
.PP
Definition at line \fB86\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.SetOwnedKinematics (\fBObjState\fP state)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB109\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.SetUnownedKinematics ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB92\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.autoDestroy = true"

.PP
Definition at line \fB41\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onAnchored = \fBKinematicSetting\&.Kinematic\fP"

.PP
Definition at line \fB34\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onDespawned = \fBKinematicSetting\&.Kinematic\fP"

.PP
Definition at line \fB33\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onDropped = \fBKinematicSetting\&.NonKinematic\fP"

.PP
Definition at line \fB37\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onMounted = \fBKinematicSetting\&.NonKinematic\fP"

.PP
Definition at line \fB35\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onTransit = \fBKinematicSetting\&.NonKinematic\fP"

.PP
Definition at line \fB36\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "\fBKinematicSetting\fP Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.onVisible = \fBKinematicSetting\&.Default\fP"

.PP
Definition at line \fB38\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.ApplyOrder\fC [get]\fP"

.PP
Definition at line \fB27\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.OnStateChangeKinematic\&.AutoKinematicEnabled\fC [get]\fP"

.PP
Definition at line \fB30\fP of file \fBOnStateChangeKinematic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
