.TH "Photon.Realtime.OperationCode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.OperationCode \- Class for constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBExchangeKeysForEncryption\fP = 250"
.br
.ti -1c
.RI "const byte \fBJoin\fP = 255"
.br
.RI "(255) Code for OpJoin, to get into a room\&."
.ti -1c
.RI "const byte \fBAuthenticateOnce\fP = 231"
.br
.RI "(231) Authenticates this peer and connects to a virtual application"
.ti -1c
.RI "const byte \fBAuthenticate\fP = 230"
.br
.RI "(230) Authenticates this peer and connects to a virtual application"
.ti -1c
.RI "const byte \fBJoinLobby\fP = 229"
.br
.RI "(229) Joins lobby (on master)"
.ti -1c
.RI "const byte \fBLeaveLobby\fP = 228"
.br
.RI "(228) Leaves lobby (on master)"
.ti -1c
.RI "const byte \fBCreateGame\fP = 227"
.br
.RI "(227) Creates a game (or fails if name exists)"
.ti -1c
.RI "const byte \fBJoinGame\fP = 226"
.br
.RI "(226) Join game (by name)"
.ti -1c
.RI "const byte \fBJoinRandomGame\fP = 225"
.br
.RI "(225) Joins random game (on master)"
.ti -1c
.RI "const byte \fBLeave\fP = (byte)254"
.br
.RI "(254) Code for OpLeave, to get out of a room\&."
.ti -1c
.RI "const byte \fBRaiseEvent\fP = (byte)253"
.br
.RI "(253) Raise event (in a room, for other actors/players)"
.ti -1c
.RI "const byte \fBSetProperties\fP = (byte)252"
.br
.RI "(252) Set Properties (of room or actor/player)"
.ti -1c
.RI "const byte \fBGetProperties\fP = (byte)251"
.br
.RI "(251) Get Properties"
.ti -1c
.RI "const byte \fBChangeGroups\fP = (byte)248"
.br
.RI "(248) Operation code to change interest groups in Rooms (Lite application and extending ones)\&."
.ti -1c
.RI "const byte \fBFindFriends\fP = 222"
.br
.RI "(222) Request the rooms and online status for a list of friends (by name, which should be unique)\&."
.ti -1c
.RI "const byte \fBGetLobbyStats\fP = 221"
.br
.RI "(221) Request statistics about a specific list of lobbies (their user and game count)\&."
.ti -1c
.RI "const byte \fBGetRegions\fP = 220"
.br
.RI "(220) Get list of regional servers from a NameServer\&."
.ti -1c
.RI "const byte \fBWebRpc\fP = 219"
.br
.RI "(219) WebRpc Operation\&."
.ti -1c
.RI "const byte \fBServerSettings\fP = 218"
.br
.RI "(218) Operation to set some server settings\&. Used with different parameters on various servers\&."
.ti -1c
.RI "const byte \fBGetGameList\fP = 217"
.br
.RI "(217) Get the game list matching a supplied sql filter (SqlListLobby only) "
.in -1c
.SH "Detailed Description"
.PP 
Class for constants\&. 

Contains operation codes\&. 
.PP
These constants are used internally\&.
.PP
Definition at line \fB1617\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Realtime\&.OperationCode\&.Authenticate = 230\fC [static]\fP"

.PP
(230) Authenticates this peer and connects to a virtual application
.PP
Definition at line \fB1630\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.AuthenticateOnce = 231\fC [static]\fP"

.PP
(231) Authenticates this peer and connects to a virtual application
.PP
Definition at line \fB1627\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.ChangeGroups = (byte)248\fC [static]\fP"

.PP
(248) Operation code to change interest groups in Rooms (Lite application and extending ones)\&.
.PP
Definition at line \fB1662\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.CreateGame = 227\fC [static]\fP"

.PP
(227) Creates a game (or fails if name exists)
.PP
Definition at line \fB1639\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.ExchangeKeysForEncryption = 250\fC [static]\fP"

.PP
Definition at line \fB1620\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.FindFriends = 222\fC [static]\fP"

.PP
(222) Request the rooms and online status for a list of friends (by name, which should be unique)\&.
.PP
Definition at line \fB1665\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.GetGameList = 217\fC [static]\fP"

.PP
(217) Get the game list matching a supplied sql filter (SqlListLobby only) 
.PP
Definition at line \fB1680\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.GetLobbyStats = 221\fC [static]\fP"

.PP
(221) Request statistics about a specific list of lobbies (their user and game count)\&.
.PP
Definition at line \fB1668\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.GetProperties = (byte)251\fC [static]\fP"

.PP
(251) Get Properties
.PP
Definition at line \fB1659\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.GetRegions = 220\fC [static]\fP"

.PP
(220) Get list of regional servers from a NameServer\&.
.PP
Definition at line \fB1671\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.Join = 255\fC [static]\fP"

.PP
(255) Code for OpJoin, to get into a room\&.
.PP
Definition at line \fB1624\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.JoinGame = 226\fC [static]\fP"

.PP
(226) Join game (by name)
.PP
Definition at line \fB1642\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.JoinLobby = 229\fC [static]\fP"

.PP
(229) Joins lobby (on master)
.PP
Definition at line \fB1633\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.JoinRandomGame = 225\fC [static]\fP"

.PP
(225) Joins random game (on master)
.PP
Definition at line \fB1645\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.Leave = (byte)254\fC [static]\fP"

.PP
(254) Code for OpLeave, to get out of a room\&.
.PP
Definition at line \fB1650\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.LeaveLobby = 228\fC [static]\fP"

.PP
(228) Leaves lobby (on master)
.PP
Definition at line \fB1636\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.RaiseEvent = (byte)253\fC [static]\fP"

.PP
(253) Raise event (in a room, for other actors/players)
.PP
Definition at line \fB1653\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.ServerSettings = 218\fC [static]\fP"

.PP
(218) Operation to set some server settings\&. Used with different parameters on various servers\&.
.PP
Definition at line \fB1677\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.SetProperties = (byte)252\fC [static]\fP"

.PP
(252) Set Properties (of room or actor/player)
.PP
Definition at line \fB1656\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.OperationCode\&.WebRpc = 219\fC [static]\fP"

.PP
(219) WebRpc Operation\&.
.PP
Definition at line \fB1674\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
