.TH "Photon.Compression.Internal.Pack_TestPackObject" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Compression.Internal.Pack_TestPackObject
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitialize\fP ()"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBPack\fP (ref System\&.Object obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBPack\fP (ref \fBemotitron\&.TestPackObject\fP packable, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBPack\fP (\fBPackFrame\fP obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBUnpack\fP (\fBPackFrame\fP obj, ref \fBFastBitMask128\fP mask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBPack\fP (ref \fBPackFrame_TestPackObject\fP packable, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.ti -1c
.RI "static \fBSerializationFlags\fP \fBUnpack\fP (ref \fBPackFrame_TestPackObject\fP packable, ref \fBFastBitMask128\fP mask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBLOCAL_FIELDS\fP = 2"
.br
.ti -1c
.RI "const int \fBTOTAL_FIELDS\fP = 2"
.br
.ti -1c
.RI "static \fBPackObjectDatabase\&.PackObjectInfo\fP \fBpackObjInfo\fP"
.br
.ti -1c
.RI "static bool \fBinitialized\fP"
.br
.ti -1c
.RI "static bool \fBisInitializing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB69\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Initialize ()\fC [static]\fP"

.PP
Definition at line \fB86\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Pack (\fBPackFrame\fP obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB150\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Pack (ref \fBemotitron\&.TestPackObject\fP packable, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB136\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Pack (ref \fBPackFrame_TestPackObject\fP packable, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB183\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Pack (ref System\&.Object obj, \fBPackFrame\fP prevFrame, ref \fBFastBitMask128\fP mask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB121\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Unpack (\fBPackFrame\fP obj, ref \fBFastBitMask128\fP mask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB165\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "static \fBSerializationFlags\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.Unpack (ref \fBPackFrame_TestPackObject\fP packable, ref \fBFastBitMask128\fP mask, ref \fBFastBitMask128\fP isCompleteMask, ref int maskOffset, byte[] buffer, ref int bitposition, int frameId, \fBSerializationFlags\fP writeFlags)\fC [static]\fP"

.PP
Definition at line \fB197\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.initialized\fC [static]\fP"

.PP
Definition at line \fB82\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "bool Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.isInitializing\fC [static]\fP"

.PP
Definition at line \fB83\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "const int Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.LOCAL_FIELDS = 2\fC [static]\fP"

.PP
Definition at line \fB71\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "\fBPackObjectDatabase\&.PackObjectInfo\fP Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.packObjInfo\fC [static]\fP"

.PP
Definition at line \fB75\fP of file \fBPack_TestPackObject\&.cs\fP\&.
.SS "const int Photon\&.Compression\&.Internal\&.Pack_TestPackObject\&.TOTAL_FIELDS = 2\fC [static]\fP"

.PP
Definition at line \fB73\fP of file \fBPack_TestPackObject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
