.TH "Photon.Pun.Simple.ContactEvent" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.ContactEvent
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContactEvent\fP (\fBIContactSystem\fP \fBcontactSystem\fP, \fBIContactTrigger\fP contacter, \fBContactType\fP \fBcontactType\fP)"
.br
.ti -1c
.RI "\fBContactEvent\fP (\fBContactEvent\fP contactEvent)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBIContactSystem\fP \fBcontactSystem\fP"
.br
.ti -1c
.RI "readonly \fBIContactTrigger\fP \fBcontactTrigger\fP"
.br
.ti -1c
.RI "readonly \fBContactType\fP \fBcontactType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBContactEvent\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.ContactEvent\&.ContactEvent (\fBIContactSystem\fP contactSystem, \fBIContactTrigger\fP contacter, \fBContactType\fP contactType)"

.PP
Definition at line \fB19\fP of file \fBContactEvent\&.cs\fP\&.
.SS "Photon\&.Pun\&.Simple\&.ContactEvent\&.ContactEvent (\fBContactEvent\fP contactEvent)"

.PP
Definition at line \fB26\fP of file \fBContactEvent\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBIContactSystem\fP Photon\&.Pun\&.Simple\&.ContactEvent\&.contactSystem"

.PP
Definition at line \fB15\fP of file \fBContactEvent\&.cs\fP\&.
.SS "readonly \fBIContactTrigger\fP Photon\&.Pun\&.Simple\&.ContactEvent\&.contactTrigger"

.PP
Definition at line \fB16\fP of file \fBContactEvent\&.cs\fP\&.
.SS "readonly \fBContactType\fP Photon\&.Pun\&.Simple\&.ContactEvent\&.contactType"

.PP
Definition at line \fB17\fP of file \fBContactEvent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
