.TH "Photon.Pun.UtilityScripts.PhotonStatsGui" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.PhotonStatsGui \- Basic GUI to show traffic and health statistics of the connection to \fBPhoton\fP, toggled by shift+tab\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.RI "Checks for shift+tab input combination (to toggle statsOn)\&."
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.ti -1c
.RI "void \fBTrafficStatsWindow\fP (int windowID)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBstatsWindowOn\fP = true"
.br
.RI "Shows or hides GUI (does not affect if stats are collected)\&."
.ti -1c
.RI "bool \fBstatsOn\fP = true"
.br
.RI "Option to turn collecting stats on or off (used in \fBUpdate()\fP)\&."
.ti -1c
.RI "bool \fBhealthStatsVisible\fP"
.br
.RI "Shows additional 'health' values of connection\&."
.ti -1c
.RI "bool \fBtrafficStatsOn\fP"
.br
.RI "Shows additional 'lower level' traffic stats\&."
.ti -1c
.RI "bool \fBbuttonsOn\fP"
.br
.RI "Show buttons to control stats and reset them\&."
.ti -1c
.RI "Rect \fBstatsRect\fP = new Rect(0, 100, 200, 50)"
.br
.RI "Positioning rect for window\&."
.ti -1c
.RI "int \fBWindowId\fP = 100"
.br
.RI "Unity GUI Window ID (must be unique or will cause issues)\&."
.in -1c
.SH "Detailed Description"
.PP 
Basic GUI to show traffic and health statistics of the connection to \fBPhoton\fP, toggled by shift+tab\&. 

The shown health values can help identify problems with connection losses or performance\&. \fBExample\fP: If the time delta between two consecutive SendOutgoingCommands calls is a second or more, chances rise for a disconnect being caused by this (because acknowledgements to the server need to be sent in due time)\&. 
.PP
Definition at line \fB33\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.OnGUI ()"

.PP
Definition at line \fB75\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.Start ()"

.PP
Definition at line \fB57\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.TrafficStatsWindow (int windowID)"

.PP
Definition at line \fB90\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "void Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.Update ()"

.PP
Checks for shift+tab input combination (to toggle statsOn)\&.
.PP
Definition at line \fB66\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.buttonsOn"

.PP
Show buttons to control stats and reset them\&.
.PP
Definition at line \fB48\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.healthStatsVisible"

.PP
Shows additional 'health' values of connection\&.
.PP
Definition at line \fB42\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.statsOn = true"

.PP
Option to turn collecting stats on or off (used in \fBUpdate()\fP)\&.
.PP
Definition at line \fB39\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "Rect Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.statsRect = new Rect(0, 100, 200, 50)"

.PP
Positioning rect for window\&.
.PP
Definition at line \fB51\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.statsWindowOn = true"

.PP
Shows or hides GUI (does not affect if stats are collected)\&.
.PP
Definition at line \fB36\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.trafficStatsOn"

.PP
Shows additional 'lower level' traffic stats\&.
.PP
Definition at line \fB45\fP of file \fBPhotonStatsGui\&.cs\fP\&.
.SS "int Photon\&.Pun\&.UtilityScripts\&.PhotonStatsGui\&.WindowId = 100"

.PP
Unity GUI Window ID (must be unique or will cause issues)\&.
.PP
Definition at line \fB54\fP of file \fBPhotonStatsGui\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
