.TH "Photon.Pun.UtilityScripts.ByteComparer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.UtilityScripts.ByteComparer
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparer< byte >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCompare\fP (byte x, byte y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB493\fP of file \fBCullArea\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Photon\&.Pun\&.UtilityScripts\&.ByteComparer\&.Compare (byte x, byte y)"

.PP

.PP
Definition at line \fB496\fP of file \fBCullArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
