.TH "Photon.Pun.Simple.VitalUIBase" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.VitalUIBase
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.VitalsUISrcBase\fP, \fBPhoton\&.Pun\&.Simple\&.IOnVitalValueChange\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnChangeOwnedVitals\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.VitalUI\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTargetField\fP { \fBValue\fP, \fBMax\fP, \fBMaxOverload\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBIVitalsSystem\fP \fBApplyVitalsSource\fP (Object vs)"
.br
.ti -1c
.RI "abstract void \fBRecalculate\fP ()"
.br
.ti -1c
.RI "override void \fBOnChangeOwnedVitals\fP (\fBIVitalsSystem\fP added, \fBIVitalsSystem\fP removed)"
.br
.ti -1c
.RI "void \fBOnVitalParamChange\fP (\fBVital\fP \fBvital\fP)"
.br
.ti -1c
.RI "virtual void \fBOnVitalValueChange\fP (\fBVital\fP \fBvital\fP)"
.br
.ti -1c
.RI "abstract void \fBUpdateGraphics\fP (\fBVital\fP \fBvital\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVitalNameType\fP \fBtargetVital\fP = new \fBVitalNameType\fP(\fBVitalType\&.Health\fP)"
.br
.ti -1c
.RI "\fBTargetField\fP \fBtargetField\fP = \fBTargetField\&.Value\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDestroy\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBvitalIndex\fP = \-1"
.br
.ti -1c
.RI "\fBVital\fP \fBvital\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBVitals\fP \fBVitals\fP\fC [getset]\fP"
.br
.ti -1c
.RI "\fBVital\fP \fBVital\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBVitalUIBase\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Simple\&.VitalUIBase\&.TargetField\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIValue \fP\fP
.TP
\fB\fIMax \fP\fP
.TP
\fB\fIMaxOverload \fP\fP
.PP
Definition at line \fB21\fP of file \fBVitalUIBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBIVitalsSystem\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.ApplyVitalsSource (Object vs)\fC [virtual]\fP"
Apply this to \fBVitals\fP to trigger its properties for dealing with changing \fBVitals\fP
.PP
Reimplemented from \fBPhoton\&.Pun\&.Simple\&.VitalsUISrcBase\fP\&.
.PP
Definition at line \fB56\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.VitalUIBase\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"
Force a rebuild of the vitals\&.\&.\&. need to really make this more clear\&.
.PP
Reimplemented in \fBPhoton\&.Pun\&.Simple\&.VitalUI\fP\&.
.PP
Definition at line \fB102\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "override void Photon\&.Pun\&.Simple\&.VitalUIBase\&.OnChangeOwnedVitals (\fBIVitalsSystem\fP added, \fBIVitalsSystem\fP removed)"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnChangeOwnedVitals\fP\&.
.PP
Definition at line \fB128\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.VitalUIBase\&.OnDestroy ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB118\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.VitalUIBase\&.OnVitalParamChange (\fBVital\fP vital)"
TODO: different update graphics for max/full value changes
.PP
Definition at line \fB144\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.VitalUIBase\&.OnVitalValueChange (\fBVital\fP vital)\fC [virtual]\fP"

.PP
Implements \fBPhoton\&.Pun\&.Simple\&.IOnVitalValueChange\fP\&.
.PP
Definition at line \fB149\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "abstract void Photon\&.Pun\&.Simple\&.VitalUIBase\&.Recalculate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.VitalUI\fP\&.
.SS "virtual void Photon\&.Pun\&.Simple\&.VitalUIBase\&.Start ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB112\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "abstract void Photon\&.Pun\&.Simple\&.VitalUIBase\&.UpdateGraphics (\fBVital\fP vital)\fC [pure virtual]\fP"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.VitalUI\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTargetField\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.targetField = \fBTargetField\&.Value\fP"

.PP
Definition at line \fB30\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "\fBVitalNameType\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.targetVital = new \fBVitalNameType\fP(\fBVitalType\&.Health\fP)"

.PP
Definition at line \fB26\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "\fBVital\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.vital\fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.VitalUIBase\&.vitalIndex = \-1\fC [protected]\fP"

.PP
Definition at line \fB49\fP of file \fBVitalUIBase\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBVital\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.Vital\fC [get]\fP"

.PP
Definition at line \fB86\fP of file \fBVitalUIBase\&.cs\fP\&.
.SS "\fBVitals\fP Photon\&.Pun\&.Simple\&.VitalUIBase\&.Vitals\fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB34\fP of file \fBVitalUIBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
