.TH "Photon.Pun.Simple.IInventoryable< T >" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IInventoryable< T > \- Indicates a class that can be added to an IInventory\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.IContactable\fP\&.
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.InventoryContactReactors< T >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "T \fBSize\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Indicates a class that can be added to an IInventory\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP 
.RE
.PP

.PP
Definition at line \fB12\fP of file \fBIInventoryable\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "T \fBPhoton\&.Pun\&.Simple\&.IInventoryable\fP< T >\&.Size\fC [get]\fP"

.PP
Definition at line \fB14\fP of file \fBIInventoryable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
