.TH "Photon.Pun.Demo.Shared.DocLinks" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Shared.DocLinks \- Document links\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDocTypes\fP { \fBDoc\fP, \fBApi\fP }"
.br
.RI "Document types "
.ti -1c
.RI "enum \fBProducts\fP { \fBOnPremise\fP, \fBRealtime\fP, \fBPun\fP, \fBChat\fP, \fBVoice\fP, \fBBolt\fP, \fBQuantum\fP }"
.br
.RI "The various supported languages "
.ti -1c
.RI "enum \fBVersions\fP { \fBCurrent\fP, \fBV1\fP, \fBV2\fP }"
.br
.RI "The various version of the documentation that exists\&. "
.ti -1c
.RI "enum \fBLanguages\fP { \fBEnglish\fP, \fBJapanese\fP, \fBKorean\fP, \fBChinese\fP }"
.br
.RI "The various supported languages "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetLink\fP (\fBDocTypes\fP type, string reference)"
.br
.RI "Gets a documentation link given a reference "
.ti -1c
.RI "static string \fBGetApiLink\fP (string reference)"
.br
.RI "Gets the API link given a reference "
.ti -1c
.RI "static string \fBGetDocLink\fP (string reference)"
.br
.RI "Gets the Doc link given a reference "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBVersions\fP \fBVersion\fP = \fBVersions\&.Current\fP"
.br
.RI "The version to generate links for "
.ti -1c
.RI "static \fBLanguages\fP \fBLanguage\fP = \fBLanguages\&.English\fP"
.br
.RI "The language to generate links with "
.ti -1c
.RI "static \fBProducts\fP \fBProduct\fP = \fBProducts\&.Pun\fP"
.br
.RI "The product to generate links for "
.ti -1c
.RI "static string \fBApiUrlRoot\fP = 'https://doc\-api\&.photonengine\&.com/{0}/{1}/{2}/{3}'"
.br
.RI "The API URL format\&. "
.ti -1c
.RI "static string \fBDocUrlFormat\fP = 'https://doc\&.photonengine\&.com/{0}/{1}/{2}/{3}'"
.br
.RI "The Doc URL format\&. "
.in -1c
.SH "Detailed Description"
.PP 
Document links\&. 


.PP
Definition at line \fB15\fP of file \fBDocLinks\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPhoton\&.Pun\&.Demo\&.Shared\&.DocLinks\&.DocTypes\fP"

.PP
Document types 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDoc \fP\fP
.TP
\fB\fIApi \fP\fP
.PP
Definition at line \fB20\fP of file \fBDocLinks\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Languages\fP"

.PP
The various supported languages 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIEnglish \fP\fP
.TP
\fB\fIJapanese \fP\fP
.TP
\fB\fIKorean \fP\fP
.TP
\fB\fIChinese \fP\fP
.PP
Definition at line \fB35\fP of file \fBDocLinks\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Products\fP"

.PP
The various supported languages 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOnPremise \fP\fP
.TP
\fB\fIRealtime \fP\fP
.TP
\fB\fIPun \fP\fP
.TP
\fB\fIChat \fP\fP
.TP
\fB\fIVoice \fP\fP
.TP
\fB\fIBolt \fP\fP
.TP
\fB\fIQuantum \fP\fP
.PP
Definition at line \fB25\fP of file \fBDocLinks\&.cs\fP\&.
.SS "enum \fBPhoton\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Versions\fP"

.PP
The various version of the documentation that exists\&. Current will be either V1 or V2 or possibly a beta version or branched version\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICurrent \fP\fP
.TP
\fB\fIV1 \fP\fP
.TP
\fB\fIV2 \fP\fP
.PP
Definition at line \fB30\fP of file \fBDocLinks\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.GetApiLink (string reference)\fC [static]\fP"

.PP
Gets the API link given a reference 
.PP
\fBReturns\fP
.RS 4
The API link\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIreference\fP Reference\&.
.RE
.PP

.PP
Definition at line \fB143\fP of file \fBDocLinks\&.cs\fP\&.
.SS "static string Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.GetDocLink (string reference)\fC [static]\fP"

.PP
Gets the Doc link given a reference 
.PP
\fBReturns\fP
.RS 4
The document link\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIreference\fP Reference\&.
.RE
.PP

.PP
Definition at line \fB153\fP of file \fBDocLinks\&.cs\fP\&.
.SS "static string Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.GetLink (\fBDocTypes\fP type, string reference)\fC [static]\fP"

.PP
Gets a documentation link given a reference 
.PP
\fBReturns\fP
.RS 4
The link\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fItype\fP Type\&.
.br
\fIreference\fP Reference\&.
.RE
.PP

.PP
Definition at line \fB125\fP of file \fBDocLinks\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.ApiUrlRoot = 'https://doc\-api\&.photonengine\&.com/{0}/{1}/{2}/{3}'\fC [static]\fP"

.PP
The API URL format\&. 0 is the Language 1 is the Product 2 is the Version 3 is the custom part passed to generate the link with 
.PP
Definition at line \fB60\fP of file \fBDocLinks\&.cs\fP\&.
.SS "string Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.DocUrlFormat = 'https://doc\&.photonengine\&.com/{0}/{1}/{2}/{3}'\fC [static]\fP"

.PP
The Doc URL format\&. 0 is the Language 1 is the Product 2 is the Version 3 is the custom part passed to generate the link with 
.PP
Definition at line \fB69\fP of file \fBDocLinks\&.cs\fP\&.
.SS "\fBLanguages\fP Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Language = \fBLanguages\&.English\fP\fC [static]\fP"

.PP
The language to generate links with 
.PP
Definition at line \fB46\fP of file \fBDocLinks\&.cs\fP\&.
.SS "\fBProducts\fP Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Product = \fBProducts\&.Pun\fP\fC [static]\fP"

.PP
The product to generate links for 
.PP
Definition at line \fB51\fP of file \fBDocLinks\&.cs\fP\&.
.SS "\fBVersions\fP Photon\&.Pun\&.Demo\&.Shared\&.DocLinks\&.Version = \fBVersions\&.Current\fP\fC [static]\fP"

.PP
The version to generate links for 
.PP
Definition at line \fB40\fP of file \fBDocLinks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
