.TH "Photon.Pun.Simple.SyncTransformEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncTransformEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits SyncObjectEditor\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUIInjectMiddle\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBInstructions\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBHelpURL\fP\fC [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTexturePath\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBSyncTransformEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Photon\&.Pun\&.Simple\&.SyncTransformEditor\&.OnInspectorGUIInjectMiddle ()\fC [protected]\fP"
Warn that a component may be playing with settings
.PP
Definition at line \fB48\fP of file \fBSyncTransformEditor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.SyncTransformEditor\&.HelpURL\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBSyncTransformEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncTransformEditor\&.Instructions\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB18\fP of file \fBSyncTransformEditor\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.SyncTransformEditor\&.TextTexturePath\fC [get]\fP, \fC [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBSyncTransformEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
