.TH "Photon.Pun.Simple.IOnVitalsChange" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnVitalsChange
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.IOnVitalsParamChange\fP, and \fBPhoton\&.Pun\&.Simple\&.IOnVitalsValueChange\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBIOnVitalChange\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
