.TH "Photon.Pun.Simple.NetworkHits" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.NetworkHits \- A reusable collection of \fBNetworkHit\fP that can be serialized\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkHits\fP (bool \fBnearestOnly\fP, int \fBbitsForContactGroupMask\fP)"
.br
.ti -1c
.RI "void \fBReset\fP (bool \fBnearestOnly\fP, int \fBbitsForContactGroupMask\fP)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBSerialize\fP (byte[] buffer, ref int bitposition, int bitsForColliderId)"
.br
.ti -1c
.RI "\fBSerializationFlags\fP \fBDeserialize\fP (byte[] buffer, ref int bitposition, int bitsForColliderId)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly List< \fBNetworkHit\fP > \fBhits\fP = new List<\fBNetworkHit\fP>()"
.br
.ti -1c
.RI "bool \fBnearestOnly\fP"
.br
.ti -1c
.RI "int \fBnearestIndex\fP = \-1"
.br
.ti -1c
.RI "int \fBbitsForContactGroupMask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A reusable collection of \fBNetworkHit\fP that can be serialized\&. 


.PP
Definition at line \fB14\fP of file \fBNetworkHits\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.NetworkHits\&.NetworkHits (bool nearestOnly, int bitsForContactGroupMask)"

.PP
Definition at line \fB21\fP of file \fBNetworkHits\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.NetworkHits\&.Clear ()"

.PP
Definition at line \fB35\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.NetworkHits\&.Deserialize (byte[] buffer, ref int bitposition, int bitsForColliderId)"

.PP
Definition at line \fB71\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Simple\&.NetworkHits\&.Reset (bool nearestOnly, int bitsForContactGroupMask)"

.PP
Definition at line \fB27\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "\fBSerializationFlags\fP Photon\&.Pun\&.Simple\&.NetworkHits\&.Serialize (byte[] buffer, ref int bitposition, int bitsForColliderId)"

.PP
Definition at line \fB41\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "override string Photon\&.Pun\&.Simple\&.NetworkHits\&.ToString ()"

.PP
Definition at line \fB100\fP of file \fBNetworkHits\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Photon\&.Pun\&.Simple\&.NetworkHits\&.bitsForContactGroupMask"

.PP
Definition at line \fB19\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "readonly List<\fBNetworkHit\fP> Photon\&.Pun\&.Simple\&.NetworkHits\&.hits = new List<\fBNetworkHit\fP>()"

.PP
Definition at line \fB16\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.NetworkHits\&.nearestIndex = \-1"

.PP
Definition at line \fB18\fP of file \fBNetworkHits\&.cs\fP\&.
.SS "bool Photon\&.Pun\&.Simple\&.NetworkHits\&.nearestOnly"

.PP
Definition at line \fB17\fP of file \fBNetworkHits\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
