.TH "Photon.Pun.Simple.IOnChangeOwnedVitals" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.IOnChangeOwnedVitals \- Interface indicates interest in knowing when there has been a change in which \fBVitals\fP are owned by this connection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPhoton\&.Pun\&.Simple\&.VitalUIBase\fP, and \fBPhoton\&.Pun\&.Simple\&.VitalsUISrcBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnChangeOwnedVitals\fP (\fBIVitalsSystem\fP added, \fBIVitalsSystem\fP removed)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface indicates interest in knowing when there has been a change in which \fBVitals\fP are owned by this connection\&. 

Used for things like health bars, that need to determine which netobj's vitals they should be monitoring at runtime\&. 
.PP
Definition at line \fB22\fP of file \fBIVitalsSystem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Simple\&.IOnChangeOwnedVitals\&.OnChangeOwnedVitals (\fBIVitalsSystem\fP added, \fBIVitalsSystem\fP removed)"

.PP
Implemented in \fBPhoton\&.Pun\&.Simple\&.VitalsUISrcBase\fP, and \fBPhoton\&.Pun\&.Simple\&.VitalUIBase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
