.TH "Photon.Realtime.AppSettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.AppSettings \- Settings for \fBPhoton\fP application(s) and the server to connect to\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBToStringFull\fP ()"
.br
.RI "ToString but with more details\&."
.ti -1c
.RI "\fBAppSettings\fP \fBCopyTo\fP (\fBAppSettings\fP d)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsAppId\fP (string val)"
.br
.RI "Checks if a string is a Guid by attempting to create one\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBAppIdRealtime\fP"
.br
.RI "AppId for \fBRealtime\fP or PUN\&."
.ti -1c
.RI "string \fBAppIdFusion\fP"
.br
.RI "AppId for \fBPhoton\fP Fusion\&."
.ti -1c
.RI "string \fBAppIdChat\fP"
.br
.RI "AppId for \fBPhoton\fP \fBChat\fP\&."
.ti -1c
.RI "string \fBAppIdVoice\fP"
.br
.RI "AppId for \fBPhoton\fP Voice\&."
.ti -1c
.RI "string \fBAppVersion\fP"
.br
.RI "The AppVersion can be used to identify builds and will split the AppId distinct 'Virtual AppIds' (important for matchmaking)\&."
.ti -1c
.RI "bool \fBUseNameServer\fP = true"
.br
.RI "If false, the app will attempt to connect to a Master Server (which is obsolete but sometimes still necessary)\&. "
.ti -1c
.RI "string \fBFixedRegion\fP"
.br
.RI "Can be set to any of the \fBPhoton\fP Cloud's region names to directly connect to that region\&. "
.ti -1c
.RI "string \fBBestRegionSummaryFromStorage\fP"
.br
.RI "Set to a previous BestRegionSummary value before connecting\&. "
.ti -1c
.RI "string \fBServer\fP"
.br
.RI "The address (hostname or IP) of the server to connect to\&."
.ti -1c
.RI "int \fBPort\fP"
.br
.RI "If not null, this sets the port of the first \fBPhoton\fP server to connect to (that will 'forward' the client as needed)\&."
.ti -1c
.RI "string \fBProxyServer\fP"
.br
.RI "The address (hostname or IP and port) of the proxy server\&."
.ti -1c
.RI "ConnectionProtocol \fBProtocol\fP = ConnectionProtocol\&.Udp"
.br
.RI "The network level protocol to use\&."
.ti -1c
.RI "bool \fBEnableProtocolFallback\fP = true"
.br
.RI "Enables a fallback to another protocol in case a connect to the Name Server fails\&. "
.ti -1c
.RI "\fBAuthModeOption\fP \fBAuthMode\fP = \fBAuthModeOption\&.Auth\fP"
.br
.RI "Defines how authentication is done\&. On each system, once or once via a WSS connection (safe)\&."
.ti -1c
.RI "bool \fBEnableLobbyStatistics\fP"
.br
.RI "If true, the client will request the list of currently available lobbies\&."
.ti -1c
.RI "DebugLevel \fBNetworkLogging\fP = DebugLevel\&.ERROR"
.br
.RI "Log level for the network lib\&."
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsMasterServerAddress\fP\fC [get]\fP"
.br
.RI "If true, the Server field contains a Master Server address (if any address at all)\&."
.ti -1c
.RI "bool \fBIsBestRegion\fP\fC [get]\fP"
.br
.RI "If true, the client should fetch the region list from the Name Server and find the one with best ping\&. "
.ti -1c
.RI "bool \fBIsDefaultNameServer\fP\fC [get]\fP"
.br
.RI "If true, the default nameserver address for the \fBPhoton\fP Cloud should be used\&."
.ti -1c
.RI "bool \fBIsDefaultPort\fP\fC [get]\fP"
.br
.RI "If true, the default ports for a protocol will be used\&."
.in -1c
.SH "Detailed Description"
.PP 
Settings for \fBPhoton\fP application(s) and the server to connect to\&. 

This is Serializable for Unity, so it can be included in ScriptableObject instances\&. 
.PP
Definition at line \fB33\fP of file \fBAppSettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAppSettings\fP Photon\&.Realtime\&.AppSettings\&.CopyTo (\fBAppSettings\fP d)"

.PP
Definition at line \fB177\fP of file \fBAppSettings\&.cs\fP\&.
.SS "static bool Photon\&.Realtime\&.AppSettings\&.IsAppId (string val)\fC [static]\fP"

.PP
Checks if a string is a Guid by attempting to create one\&. 
.PP
\fBParameters\fP
.RS 4
\fIval\fP The potential guid to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
True if new Guid(val) did not fail\&.
.RE
.PP

.PP
Definition at line \fB155\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.ToStringFull ()"

.PP
ToString but with more details\&.
.PP
Definition at line \fB126\fP of file \fBAppSettings\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Photon\&.Realtime\&.AppSettings\&.AppIdChat"

.PP
AppId for \fBPhoton\fP \fBChat\fP\&.
.PP
Definition at line \fB42\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.AppIdFusion"

.PP
AppId for \fBPhoton\fP Fusion\&.
.PP
Definition at line \fB39\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.AppIdRealtime"

.PP
AppId for \fBRealtime\fP or PUN\&.
.PP
Definition at line \fB36\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.AppIdVoice"

.PP
AppId for \fBPhoton\fP Voice\&.
.PP
Definition at line \fB45\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.AppVersion"

.PP
The AppVersion can be used to identify builds and will split the AppId distinct 'Virtual AppIds' (important for matchmaking)\&.
.PP
Definition at line \fB48\fP of file \fBAppSettings\&.cs\fP\&.
.SS "\fBAuthModeOption\fP Photon\&.Realtime\&.AppSettings\&.AuthMode = \fBAuthModeOption\&.Auth\fP"

.PP
Defines how authentication is done\&. On each system, once or once via a WSS connection (safe)\&.
.PP
Definition at line \fB92\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.BestRegionSummaryFromStorage"

.PP
Set to a previous BestRegionSummary value before connecting\&. This is a value used when the client connects to the 'Best Region'\&. If this is null or empty, all regions gets pinged\&. Providing a previous summary on connect, speeds up best region selection and makes the previously selected region 'sticky'\&.
.PP
Unity clients should store the BestRegionSummary in the PlayerPrefs\&. You can store the new result by implementing \fBIConnectionCallbacks\&.OnConnectedToMaster\fP\&. If \fBLoadBalancingClient\&.SummaryToCache\fP is not null, store this string\&. To avoid storing the value multiple times, you could set SummaryToCache to null\&. 
.PP
Definition at line \fB73\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.EnableLobbyStatistics"

.PP
If true, the client will request the list of currently available lobbies\&.
.PP
Definition at line \fB95\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.EnableProtocolFallback = true"

.PP
Enables a fallback to another protocol in case a connect to the Name Server fails\&. See: \fBLoadBalancingClient\&.EnableProtocolFallback\fP\&.
.PP
Definition at line \fB89\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.FixedRegion"

.PP
Can be set to any of the \fBPhoton\fP Cloud's region names to directly connect to that region\&. if this IsNullOrEmpty() AND UseNameServer == true, use BestRegion\&. else, use a server
.PP
Definition at line \fB57\fP of file \fBAppSettings\&.cs\fP\&.
.SS "DebugLevel Photon\&.Realtime\&.AppSettings\&.NetworkLogging = DebugLevel\&.ERROR"

.PP
Log level for the network lib\&.
.PP
Definition at line \fB98\fP of file \fBAppSettings\&.cs\fP\&.
.SS "int Photon\&.Realtime\&.AppSettings\&.Port"

.PP
If not null, this sets the port of the first \fBPhoton\fP server to connect to (that will 'forward' the client as needed)\&.
.PP
Definition at line \fB79\fP of file \fBAppSettings\&.cs\fP\&.
.SS "ConnectionProtocol Photon\&.Realtime\&.AppSettings\&.Protocol = ConnectionProtocol\&.Udp"

.PP
The network level protocol to use\&.
.PP
Definition at line \fB85\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.ProxyServer"

.PP
The address (hostname or IP and port) of the proxy server\&.
.PP
Definition at line \fB82\fP of file \fBAppSettings\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.AppSettings\&.Server"

.PP
The address (hostname or IP) of the server to connect to\&.
.PP
Definition at line \fB76\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.UseNameServer = true"

.PP
If false, the app will attempt to connect to a Master Server (which is obsolete but sometimes still necessary)\&. if true, Server points to a NameServer (or is null, using the default), else it points to a MasterServer\&.
.PP
Definition at line \fB53\fP of file \fBAppSettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Photon\&.Realtime\&.AppSettings\&.IsBestRegion\fC [get]\fP"

.PP
If true, the client should fetch the region list from the Name Server and find the one with best ping\&. See 'Best Region' in the online docs\&.
.PP
Definition at line \fB108\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.IsDefaultNameServer\fC [get]\fP"

.PP
If true, the default nameserver address for the \fBPhoton\fP Cloud should be used\&.
.PP
Definition at line \fB114\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.IsDefaultPort\fC [get]\fP"

.PP
If true, the default ports for a protocol will be used\&.
.PP
Definition at line \fB120\fP of file \fBAppSettings\&.cs\fP\&.
.SS "bool Photon\&.Realtime\&.AppSettings\&.IsMasterServerAddress\fC [get]\fP"

.PP
If true, the Server field contains a Master Server address (if any address at all)\&.
.PP
Definition at line \fB101\fP of file \fBAppSettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
