.TH "Photon.Pun.Demo.Cockpit.UserIdField" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Demo.Cockpit.UserIdField \- User identifier InputField\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEndEdit\fP (string value)"
.br
.ti -1c
.RI "void \fBSubmitForm\fP (string value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPunCockpit\fP \fBManager\fP"
.br
.ti -1c
.RI "InputField \fBPropertyValueInput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
User identifier InputField\&. 


.PP
Definition at line \fB16\fP of file \fBUserIdField\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.UserIdField\&.OnEndEdit (string value)"

.PP
Definition at line \fB52\fP of file \fBUserIdField\&.cs\fP\&.
.SS "void Photon\&.Pun\&.Demo\&.Cockpit\&.UserIdField\&.SubmitForm (string value)"

.PP
Definition at line \fB64\fP of file \fBUserIdField\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPunCockpit\fP Photon\&.Pun\&.Demo\&.Cockpit\&.UserIdField\&.Manager"

.PP
Definition at line \fB19\fP of file \fBUserIdField\&.cs\fP\&.
.SS "InputField Photon\&.Pun\&.Demo\&.Cockpit\&.UserIdField\&.PropertyValueInput"

.PP
Definition at line \fB21\fP of file \fBUserIdField\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
