.TH "Photon.Realtime.OpJoinRandomRoomParams" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.OpJoinRandomRoomParams \- Parameters for the matchmaking of JoinRandomRoom and JoinRandomOrCreateRoom\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHashtable\fP \fBExpectedCustomRoomProperties\fP"
.br
.RI "The custom room properties a room must have to fit\&. All key-values must be present to match\&. In SQL Lobby, use SqlLobbyFilter instead\&."
.ti -1c
.RI "byte \fBExpectedMaxPlayers\fP"
.br
.RI "Filters by the MaxPlayers value of rooms\&."
.ti -1c
.RI "\fBMatchmakingMode\fP \fBMatchingType\fP"
.br
.RI "The MatchmakingMode affects how rooms get filled\&. By default, the server fills rooms\&."
.ti -1c
.RI "\fBTypedLobby\fP \fBTypedLobby\fP"
.br
.RI "The lobby in which to match\&. The type affects how filters are applied\&."
.ti -1c
.RI "string \fBSqlLobbyFilter\fP"
.br
.RI "SQL query to filter room matches\&. For default-typed lobbies, use ExpectedCustomRoomProperties instead\&."
.ti -1c
.RI "string[] \fBExpectedUsers\fP"
.br
.RI "The expected users list blocks player slots for your friends or team mates to join the room, too\&. "
.in -1c
.SH "Detailed Description"
.PP 
Parameters for the matchmaking of JoinRandomRoom and JoinRandomOrCreateRoom\&. 

More about matchmaking: https://doc\&.photonengine\&.com/en-us/pun/current/manuals-and-demos/matchmaking-and-lobby\&. 
.PP
Definition at line \fB1056\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHashtable\fP Photon\&.Realtime\&.OpJoinRandomRoomParams\&.ExpectedCustomRoomProperties"

.PP
The custom room properties a room must have to fit\&. All key-values must be present to match\&. In SQL Lobby, use SqlLobbyFilter instead\&.
.PP
Definition at line \fB1059\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "byte Photon\&.Realtime\&.OpJoinRandomRoomParams\&.ExpectedMaxPlayers"

.PP
Filters by the MaxPlayers value of rooms\&.
.PP
Definition at line \fB1061\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "string [] Photon\&.Realtime\&.OpJoinRandomRoomParams\&.ExpectedUsers"

.PP
The expected users list blocks player slots for your friends or team mates to join the room, too\&. See: https://doc.photonengine.com/en-us/pun/v2/lobby-and-matchmaking/matchmaking-and-lobby#matchmaking_slot_reservation 
.PP
Definition at line \fB1070\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBMatchmakingMode\fP Photon\&.Realtime\&.OpJoinRandomRoomParams\&.MatchingType"

.PP
The MatchmakingMode affects how rooms get filled\&. By default, the server fills rooms\&.
.PP
Definition at line \fB1063\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "string Photon\&.Realtime\&.OpJoinRandomRoomParams\&.SqlLobbyFilter"

.PP
SQL query to filter room matches\&. For default-typed lobbies, use ExpectedCustomRoomProperties instead\&.
.PP
Definition at line \fB1067\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "\fBTypedLobby\fP Photon\&.Realtime\&.OpJoinRandomRoomParams\&.TypedLobby"

.PP
The lobby in which to match\&. The type affects how filters are applied\&.
.PP
Definition at line \fB1065\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
