.TH "Photon.Realtime.ActorProperties" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Realtime.ActorProperties \- Class for constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBPlayerName\fP = 255"
.br
.RI "(255) Name of a player/actor\&."
.ti -1c
.RI "const byte \fBIsInactive\fP = 254"
.br
.RI "(254) Tells you if the player is currently in this game (getting events live)\&. "
.ti -1c
.RI "const byte \fBUserId\fP = 253"
.br
.RI "(253) UserId of the player\&. Sent when room gets created with \fBRoomOptions\&.PublishUserId\fP = true\&."
.in -1c
.SH "Detailed Description"
.PP 
Class for constants\&. 

These (byte) values define 'well known' properties for an Actor / \fBPlayer\fP\&. 
.PP
These constants are used internally\&. 'Custom properties' have to use a string-type as key\&. They can be assigned at will\&. 
.PP
Definition at line \fB1267\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte Photon\&.Realtime\&.ActorProperties\&.IsInactive = 254\fC [static]\fP"

.PP
(254) Tells you if the player is currently in this game (getting events live)\&. A server-set value for async games, where players can leave the game and return later\&.
.PP
Definition at line \fB1274\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.ActorProperties\&.PlayerName = 255\fC [static]\fP"

.PP
(255) Name of a player/actor\&.
.PP
Definition at line \fB1270\fP of file \fBLoadbalancingPeer\&.cs\fP\&.
.SS "const byte Photon\&.Realtime\&.ActorProperties\&.UserId = 253\fC [static]\fP"

.PP
(253) UserId of the player\&. Sent when room gets created with \fBRoomOptions\&.PublishUserId\fP = true\&.
.PP
Definition at line \fB1277\fP of file \fBLoadbalancingPeer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
