.TH "Photon.Pun.Simple.SyncContact.ContactRecord" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Photon.Pun.Simple.SyncContact.ContactRecord
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContactRecord\fP (int \fBcontactSystemViewID\fP, byte \fBcontactSystemIndex\fP, \fBContactType\fP \fBcontactType\fP)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBContactType\fP \fBcontactType\fP"
.br
.ti -1c
.RI "int \fBcontactSystemViewID\fP"
.br
.ti -1c
.RI "byte \fBcontactSystemIndex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB66\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Photon\&.Pun\&.Simple\&.SyncContact\&.ContactRecord\&.ContactRecord (int contactSystemViewID, byte contactSystemIndex, \fBContactType\fP contactType)"

.PP
Definition at line \fB72\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Photon\&.Pun\&.Simple\&.SyncContact\&.ContactRecord\&.ToString ()"

.PP
Definition at line \fB79\fP of file \fBSyncContact\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "byte Photon\&.Pun\&.Simple\&.SyncContact\&.ContactRecord\&.contactSystemIndex"

.PP
Definition at line \fB70\fP of file \fBSyncContact\&.cs\fP\&.
.SS "int Photon\&.Pun\&.Simple\&.SyncContact\&.ContactRecord\&.contactSystemViewID"

.PP
Definition at line \fB69\fP of file \fBSyncContact\&.cs\fP\&.
.SS "\fBContactType\fP Photon\&.Pun\&.Simple\&.SyncContact\&.ContactRecord\&.contactType"

.PP
Definition at line \fB68\fP of file \fBSyncContact\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
