.TH "PickUpObjectSystem" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PickUpObjectSystem
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBPickUpCheck\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisInTaskRange\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBhavePenyapu\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveCloth\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveDuster\fP = false"
.br
.ti -1c
.RI "static bool \fBhaveChicken\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PickUpObjectSystem\&.PickUpCheck ()"

.PP
Definition at line \fB158\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SS "void PickUpObjectSystem\&.Update ()"

.PP
Definition at line \fB32\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool PickUpObjectSystem\&.haveChicken = false\fC [static]\fP"

.PP
Definition at line \fB25\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SS "bool PickUpObjectSystem\&.haveCloth = false\fC [static]\fP"

.PP
Definition at line \fB23\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SS "bool PickUpObjectSystem\&.haveDuster = false\fC [static]\fP"

.PP
Definition at line \fB24\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SS "bool PickUpObjectSystem\&.havePenyapu = false\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBPickUpObjectSystem\&.cs\fP\&.
.SS "bool PickUpObjectSystem\&.isInTaskRange"

.PP
Definition at line \fB30\fP of file \fBPickUpObjectSystem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
