.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/PhotonPlayer/PlayerNumbering.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/UtilityScripts/PhotonPlayer/PlayerNumbering.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.PlayerNumbering\fP"
.br
.RI "Implements consistent numbering in a room/game with help of room properties\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.UtilityScripts\&.PlayerNumberingExtensions\fP"
.br
.RI "Extension used for PlayerRoomIndexing and Player class\&."
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.UtilityScripts\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBHashtable\fP = ExitGames\&.Client\&.Photon\&.Hashtable"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBHashtable\fP =  ExitGames\&.Client\&.Photon\&.Hashtable"

.PP
Definition at line \fB18\fP of file \fBPlayerNumbering\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
