.TH "PlayerStats" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerStats
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnabled\fP ()"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action< int > \fBPlayerReceivedExperience\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB74\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PlayerStats\&.Disable ()"

.PP
Definition at line \fB85\fP of file \fBQuest\&.cs\fP\&.
.SS "void PlayerStats\&.Enabled ()"

.PP
Definition at line \fB80\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action<int> PlayerStats\&.PlayerReceivedExperience"

.PP
Definition at line \fB78\fP of file \fBQuest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
