.TH "ProjectNull.DocTools.DoxyWindow" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectNull.DocTools.DoxyWindow \- The doxygen window in the editor to access doxygen and the documentation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SH "Detailed Description"
.PP 
The doxygen window in the editor to access doxygen and the documentation\&. 
.PP
Definition at line \fB10\fP of file \fBDoxyWindow\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
