.TH "ProjectNull.DocTools.DoxyFile" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectNull.DocTools.DoxyFile \- The base doxy file class used to make new doxyfiles form a base doxyfile\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBMakeTheDoxyFiles\fP (\fBDoxySettings\fP doxySettings)"
.br
.RI "Make the doxyfiles in the new folder\&. "
.ti -1c
.RI "static bool \fBDoxygenFileExist\fP (\fBDoxyType\fP doxyType, \fBDoxySettings\fP doxySettings)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The base doxy file class used to make new doxyfiles form a base doxyfile\&. 
.PP
Definition at line \fB15\fP of file \fBDoxyFile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool ProjectNull\&.DocTools\&.DoxyFile\&.DoxygenFileExist (\fBDoxyType\fP doxyType, \fBDoxySettings\fP doxySettings)\fC [static]\fP"
\\breif Test if dxygen file exist 
.PP
Definition at line \fB47\fP of file \fBDoxyFile\&.cs\fP\&.
.SS "static int ProjectNull\&.DocTools\&.DoxyFile\&.MakeTheDoxyFiles (\fBDoxySettings\fP doxySettings)\fC [static]\fP"

.PP
Make the doxyfiles in the new folder\&. 
.PP
Definition at line \fB20\fP of file \fBDoxyFile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
