.TH "ProjectNull.DocTools.DoxySettings" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectNull.DocTools.DoxySettings \- This is the settings of the\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSave\fP ()"
.br
.RI "Save the data to the EditorPrefs using SetString\&. "
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.RI "Used to load the settings from EditorPrefs\&. "
.ti -1c
.RI "void \fBLoadFromEditorPrefs\fP ()"
.br
.RI "Used to load the settings from EditorPrefs\&. "
.ti -1c
.RI "void \fBLoadSettingsFromUserDoxyFile\fP ()"
.br
.RI "Loading settings from the doxygen using the user doxygen file\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBfullDoxygenPath\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBactiveDocumentationFolder\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBprojecSourceFolder\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBprojectName\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBprojectBrief\fP\fC [getset]\fP"
.br
.ti -1c
.RI "string \fBprojectVersionNumber\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the settings of the\&. 
.PP
Definition at line \fB10\fP of file \fBDoxySettings\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ProjectNull\&.DocTools\&.DoxySettings\&.Load ()"

.PP
Used to load the settings from EditorPrefs\&. 
.PP
Definition at line \fB72\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "void ProjectNull\&.DocTools\&.DoxySettings\&.LoadFromEditorPrefs ()"

.PP
Used to load the settings from EditorPrefs\&. 
.PP
Definition at line \fB82\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "void ProjectNull\&.DocTools\&.DoxySettings\&.LoadSettingsFromUserDoxyFile ()"

.PP
Loading settings from the doxygen using the user doxygen file\&. 
.PP
Definition at line \fB132\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "void ProjectNull\&.DocTools\&.DoxySettings\&.Save ()"

.PP
Save the data to the EditorPrefs using SetString\&. 
.PP
Definition at line \fB59\fP of file \fBDoxySettings\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.activeDocumentationFolder\fC [get]\fP, \fC [set]\fP"
\\breif The path to the active documentation folder
.PP
It's here the doxy files and PDFs are 
.PP
Definition at line \fB24\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.fullDoxygenPath\fC [get]\fP, \fC [set]\fP"
\\breif The path to the doxygen\&.exe file 
.PP
Definition at line \fB15\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.projecSourceFolder\fC [get]\fP, \fC [set]\fP"
\\breif The path to the source folder when generating new doxy files\&. 
.PP
Definition at line \fB31\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.projectBrief\fC [get]\fP, \fC [set]\fP"
\\breif The project brief description to insert in the doxyfile\&. 
.PP
Definition at line \fB45\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.projectName\fC [get]\fP, \fC [set]\fP"
\\breif The project name to insert in the doxyfile\&. 
.PP
Definition at line \fB38\fP of file \fBDoxySettings\&.cs\fP\&.
.SS "string ProjectNull\&.DocTools\&.DoxySettings\&.projectVersionNumber\fC [get]\fP, \fC [set]\fP"
\\breif The project number (version number) to insert in the doxyfile\&. 
.PP
Definition at line \fB52\fP of file \fBDoxySettings\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
