.TH "ProjectNull.DocTools" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectNull.DocTools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDoxyFile\fP"
.br
.RI "The base doxy file class used to make new doxyfiles form a base doxyfile\&. "
.ti -1c
.RI "struct \fBDoxySettings\fP"
.br
.RI "This is the settings of the\&. "
.ti -1c
.RI "class \fBDoxyWindow\fP"
.br
.RI "The doxygen window in the editor to access doxygen and the documentation\&. "
.ti -1c
.RI "class \fBProcessRunner\fP"
.br
.RI "Contains a process and this is the interface point\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDoxyType\fP { \fBUser\fP, \fBDeveloper\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBProjectNull\&.DocTools\&.DoxyType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUser \fP\fP
.TP
\fB\fIDeveloper \fP\fP
.PP
Definition at line \fB7\fP of file \fBDoxyFile\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
