.TH "ProjectNull.DocTools.ProcessRunner" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProjectNull.DocTools.ProcessRunner \- Contains a process and this is the interface point\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBProcessIsActive\fP ()"
.br
.ti -1c
.RI "void \fBStartInWorkingFolder\fP (string runFile, string[] arguments)"
.br
.RI "Creat a temp working folder and start a process in it\&. "
.ti -1c
.RI "void \fBStartWitoutWorkingFolder\fP (string runFile, string[] arguments)"
.br
.RI "Start a process without creating a temp working folder\&. "
.ti -1c
.RI "System\&.IO\&.StreamReader \fBGetOutStream\fP ()"
.br
.RI "Get the stream out from the process\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains a process and this is the interface point\&. 
.PP
Definition at line \fB8\fP of file \fBProcessRunner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "System\&.IO\&.StreamReader ProjectNull\&.DocTools\&.ProcessRunner\&.GetOutStream ()"

.PP
Get the stream out from the process\&. 
.PP
Definition at line \fB70\fP of file \fBProcessRunner\&.cs\fP\&.
.SS "bool ProjectNull\&.DocTools\&.ProcessRunner\&.ProcessIsActive ()"

.PP
Definition at line \fB11\fP of file \fBProcessRunner\&.cs\fP\&.
.SS "void ProjectNull\&.DocTools\&.ProcessRunner\&.StartInWorkingFolder (string runFile, string[] arguments)"

.PP
Creat a temp working folder and start a process in it\&. 
.PP
Definition at line \fB22\fP of file \fBProcessRunner\&.cs\fP\&.
.SS "void ProjectNull\&.DocTools\&.ProcessRunner\&.StartWitoutWorkingFolder (string runFile, string[] arguments)"

.PP
Start a process without creating a temp working folder\&. 
.PP
Definition at line \fB40\fP of file \fBProcessRunner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
