.TH "PUNEnterOfflineMode" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PUNEnterOfflineMode
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPUNEnterOfflineMode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
