.TH "PushOverIndicator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PushOverIndicator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPun\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRPCOnHitbox\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material[] \fBmaterial\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPushOverIndicator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PushOverIndicator\&.RPCOnHitbox ()"

.PP
Definition at line \fB48\fP of file \fBPushOverIndicator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Material [] PushOverIndicator\&.material"

.PP
Definition at line \fB8\fP of file \fBPushOverIndicator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
