.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/QuatCrusher.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/TransformCrusher/QuatCrusher.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Compression\&.QuatCrusher\fP"
.br
.RI "Wrapper for the QuatCompress codec, giving it editor capabilities and compatibility/interoperability with the entire \fBTransformCrusher\fP library\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Compression\fP"
.br
.RI "Temporariliy using the \fBUtilities\fP namespace to avoid collisions with the DLL still in use by NST "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Compression\&.CompressLevel\fP { \fBPhoton\&.Compression\&.SetBits\fP = -1, \fBPhoton\&.Compression\&.Disabled\fP = 0, \fBPhoton\&.Compression\&.uint16Low\fP = 16, \fBPhoton\&.Compression\&.uint32Med\fP = 32, \fBPhoton\&.Compression\&.uint64Hi\fP = 64 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
