.TH "Quest" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Quest
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCollectItemQuest\fP, and \fBDefeatEnemiesQuest\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBUniqueId\fP"
.br
.ti -1c
.RI "string \fBName\fP"
.br
.ti -1c
.RI "\fBQuestState\fP \fBState\fP"
.br
.ti -1c
.RI "int \fBLevelRequirement\fP"
.br
.ti -1c
.RI "int \fBExperienceReward\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBEnable\fP ()"
.br
.ti -1c
.RI "virtual void \fBDisable\fP ()"
.br
.ti -1c
.RI "abstract void \fBQuestActive\fP ()"
.br
.ti -1c
.RI "abstract void \fBQuestCompleted\fP ()"
.br
.ti -1c
.RI "void \fBComplete\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBQuestChannel\fP \fB_questsChannel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBQuest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Quest\&.Complete ()\fC [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBQuest\&.cs\fP\&.
.SS "virtual void Quest\&.Disable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB42\fP of file \fBQuest\&.cs\fP\&.
.SS "virtual void Quest\&.Enable ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBDefeatEnemiesQuest\fP\&.
.PP
Definition at line \fB31\fP of file \fBQuest\&.cs\fP\&.
.SS "abstract void Quest\&.QuestActive ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCollectItemQuest\fP, and \fBDefeatEnemiesQuest\fP\&.
.SS "abstract void Quest\&.QuestCompleted ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCollectItemQuest\fP, and \fBDefeatEnemiesQuest\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBQuestChannel\fP Quest\&._questsChannel\fC [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBQuest\&.cs\fP\&.
.SS "int Quest\&.ExperienceReward"

.PP
Definition at line \fB29\fP of file \fBQuest\&.cs\fP\&.
.SS "int Quest\&.LevelRequirement"

.PP
Definition at line \fB28\fP of file \fBQuest\&.cs\fP\&.
.SS "string Quest\&.Name"

.PP
Definition at line \fB26\fP of file \fBQuest\&.cs\fP\&.
.SS "\fBQuestState\fP Quest\&.State"

.PP
Definition at line \fB27\fP of file \fBQuest\&.cs\fP\&.
.SS "string Quest\&.UniqueId"

.PP
Definition at line \fB25\fP of file \fBQuest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
