.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/MissionObjectives/Quest.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/MissionObjectives/Quest.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQuestChannel\fP"
.br
.ti -1c
.RI "class \fBQuest\fP"
.br
.ti -1c
.RI "class \fBPlayerStats\fP"
.br
.ti -1c
.RI "class \fBCollectItemQuest\fP"
.br
.ti -1c
.RI "class \fBDefeatEnemiesQuest\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBQuestState\fP { \fBPending\fP, \fBActive\fP, \fBCompleted\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBQuestState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPending \fP\fP
.TP
\fB\fIActive \fP\fP
.TP
\fB\fICompleted \fP\fP
.PP
Definition at line \fB176\fP of file \fBQuest\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
