.TH "QuickApplicationQuit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuickApplicationQuit
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBQuitApp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBQuickApplicationQuit\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void QuickApplicationQuit\&.QuitApp ()"

.PP
Definition at line \fB7\fP of file \fBQuickApplicationQuit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
