.TH "Readme" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Readme
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSection\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Texture2D \fBicon\fP"
.br
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "\fBSection\fP[] \fBsections\fP"
.br
.ti -1c
.RI "bool \fBloadedLayout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBReadme\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Texture2D Readme\&.icon"

.PP
Definition at line \fB5\fP of file \fBReadme\&.cs\fP\&.
.SS "bool Readme\&.loadedLayout"

.PP
Definition at line \fB8\fP of file \fBReadme\&.cs\fP\&.
.SS "\fBSection\fP [] Readme\&.sections"

.PP
Definition at line \fB7\fP of file \fBReadme\&.cs\fP\&.
.SS "string Readme\&.title"

.PP
Definition at line \fB6\fP of file \fBReadme\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
