.TH "Readme.Section" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Readme.Section
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBheading\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "string \fBlinkText\fP"
.br
.ti -1c
.RI "string \fBurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBReadme\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Readme\&.Section\&.heading"

.PP
Definition at line \fB12\fP of file \fBReadme\&.cs\fP\&.
.SS "string Readme\&.Section\&.linkText"

.PP
Definition at line \fB12\fP of file \fBReadme\&.cs\fP\&.
.SS "string Readme\&.Section\&.text"

.PP
Definition at line \fB12\fP of file \fBReadme\&.cs\fP\&.
.SS "string Readme\&.Section\&.url"

.PP
Definition at line \fB12\fP of file \fBReadme\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
