.TH "RemoveBGIntro" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoveBGIntro
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBintroBG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBRemoveBGIntro\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RemoveBGIntro\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB11\fP of file \fBRemoveBGIntro\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject RemoveBGIntro\&.introBG"

.PP
Definition at line \fB9\fP of file \fBRemoveBGIntro\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
