.TH "RemoveRestrict" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RemoveRestrict
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtutoBGPanel\fP"
.br
.ti -1c
.RI "float \fBtimer\fP = 0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBRemoveRestrict\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void RemoveRestrict\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB14\fP of file \fBRemoveRestrict\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float RemoveRestrict\&.timer = 0f"

.PP
Definition at line \fB11\fP of file \fBRemoveRestrict\&.cs\fP\&.
.SS "GameObject RemoveRestrict\&.tutoBGPanel"

.PP
Definition at line \fB8\fP of file \fBRemoveRestrict\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
