.TH "RoomListItem_Old" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoomListItem_Old
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetUp\fP (\fBRoomInfo\fP _info)"
.br
.ti -1c
.RI "void \fBOnClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRoomInfo\fP \fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBRoomListItem_Old\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RoomListItem_Old\&.OnClick ()"

.PP
Definition at line \fB19\fP of file \fBRoomListItem_Old\&.cs\fP\&.
.SS "void RoomListItem_Old\&.SetUp (\fBRoomInfo\fP _info)"

.PP
Definition at line \fB13\fP of file \fBRoomListItem_Old\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRoomInfo\fP RoomListItem_Old\&.info"

.PP
Definition at line \fB11\fP of file \fBRoomListItem_Old\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
