.TH "ScoreManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoreManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetMainScore\fP (int score)"
.br
.ti -1c
.RI "void \fBSetBrokenFurnitureScore\fP (int score)"
.br
.ti -1c
.RI "void \fBSetFixFurnitureScore\fP (int score)"
.br
.ti -1c
.RI "void \fBSetTrapScore\fP ()"
.br
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBBackToMenu\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmainScore\fP = 1000"
.br
.ti -1c
.RI "int \fBtrapScore\fP = 100"
.br
.ti -1c
.RI "int \fBfurniture1\fP = 100"
.br
.ti -1c
.RI "int \fBfurniture2\fP = 250"
.br
.ti -1c
.RI "int \fBfurniture3\fP = 500"
.br
.ti -1c
.RI "int \fBtotalFurnitureScore\fP = 2400"
.br
.ti -1c
.RI "TextMeshProUGUI \fBnameP1\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBnameP2\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBmainScoreP1\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBmainScoreP2\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBextraScoreP1\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBextraScoreP2\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBtotalP1\fP"
.br
.ti -1c
.RI "TextMeshProUGUI \fBtotalP2\fP"
.br
.ti -1c
.RI "\fBTimerScript\fP \fBtimerScript\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBScoreManager\fP \fBinstance\fP"
.br
.ti -1c
.RI "const string \fBMainScore\fP = 'MainScore'"
.br
.ti -1c
.RI "const string \fBBrokenFurnitureScore\fP = 'BrokenFurnitureScore'"
.br
.ti -1c
.RI "const string \fBTotalTrapScore\fP = 'TotalTrapScore'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBScoreManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ScoreManager\&.BackToMenu ()"

.PP
Definition at line \fB224\fP of file \fBScoreManager\&.cs\fP\&.
.SS "override void ScoreManager\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBExitGames\&.Client\&.Photon\&.Hashtable\fP changedProps)"

.PP
Definition at line \fB120\fP of file \fBScoreManager\&.cs\fP\&.
.SS "void ScoreManager\&.SetBrokenFurnitureScore (int score)"

.PP
Definition at line \fB61\fP of file \fBScoreManager\&.cs\fP\&.
.SS "void ScoreManager\&.SetFixFurnitureScore (int score)"

.PP
Definition at line \fB79\fP of file \fBScoreManager\&.cs\fP\&.
.SS "void ScoreManager\&.SetMainScore (int score)"

.PP
Definition at line \fB38\fP of file \fBScoreManager\&.cs\fP\&.
.SS "void ScoreManager\&.SetTrapScore ()"

.PP
Definition at line \fB96\fP of file \fBScoreManager\&.cs\fP\&.
.SS "void ScoreManager\&.Start ()"

.PP
Definition at line \fB179\fP of file \fBScoreManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string ScoreManager\&.BrokenFurnitureScore = 'BrokenFurnitureScore'\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.extraScoreP1"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.extraScoreP2"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.furniture1 = 100"

.PP
Definition at line \fB21\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.furniture2 = 250"

.PP
Definition at line \fB22\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.furniture3 = 500"

.PP
Definition at line \fB23\fP of file \fBScoreManager\&.cs\fP\&.
.SS "\fBScoreManager\fP ScoreManager\&.instance\fC [static]\fP"

.PP
Definition at line \fB13\fP of file \fBScoreManager\&.cs\fP\&.
.SS "const string ScoreManager\&.MainScore = 'MainScore'\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.mainScore = 1000"

.PP
Definition at line \fB19\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.mainScoreP1"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.mainScoreP2"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.nameP1"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.nameP2"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "\fBTimerScript\fP ScoreManager\&.timerScript"

.PP
Definition at line \fB177\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.totalFurnitureScore = 2400"

.PP
Definition at line \fB24\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.totalP1"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "TextMeshProUGUI ScoreManager\&.totalP2"

.PP
Definition at line \fB28\fP of file \fBScoreManager\&.cs\fP\&.
.SS "const string ScoreManager\&.TotalTrapScore = 'TotalTrapScore'\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBScoreManager\&.cs\fP\&.
.SS "int ScoreManager\&.trapScore = 100"

.PP
Definition at line \fB20\fP of file \fBScoreManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
