.TH "ScreenQuestAssets" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScreenQuestAssets
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBVisualSprite\fP"
.br
.ti -1c
.RI "float \fBXVisualDistanceFromCenter\fP"
.br
.ti -1c
.RI "float \fBYVisualDistanceFromCenter\fP"
.br
.ti -1c
.RI "float \fBXSize\fP"
.br
.ti -1c
.RI "float \fBYSize\fP"
.br
.ti -1c
.RI "float \fBVisualAngle\fP"
.br
.ti -1c
.RI "float \fBVisualAngleBuffer\fP"
.br
.ti -1c
.RI "GameObject \fBObjectImage\fP"
.br
.ti -1c
.RI "RectTransform \fBRectImage\fP"
.br
.ti -1c
.RI "Image \fBComponentImage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB147\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image ScreenQuestAssets\&.ComponentImage"

.PP
Definition at line \fB166\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "GameObject ScreenQuestAssets\&.ObjectImage"

.PP
Definition at line \fB164\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "RectTransform ScreenQuestAssets\&.RectImage"

.PP
Definition at line \fB165\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.VisualAngle"

.PP
Definition at line \fB160\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.VisualAngleBuffer"

.PP
Definition at line \fB162\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "Sprite ScreenQuestAssets\&.VisualSprite"

.PP
Definition at line \fB150\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.XSize"

.PP
Definition at line \fB156\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.XVisualDistanceFromCenter"

.PP
Definition at line \fB152\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.YSize"

.PP
Definition at line \fB158\fP of file \fBScreenQuestPointer\&.cs\fP\&.
.SS "float ScreenQuestAssets\&.YVisualDistanceFromCenter"

.PP
Definition at line \fB154\fP of file \fBScreenQuestPointer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
