.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/SettingsScriptableObject/SettingsScriptableObject.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUtilities/SettingsScriptableObject/SettingsScriptableObject.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.SettingsScriptableObjectBase\fP"
.br
.RI "Non-generic base class for \fBSettingsScriptableObject\fP to make non-generic elements more easily accessible\&. "
.ti -1c
.RI "class \fBPhoton\&.Utilities\&.SettingsScriptableObject< T >\fP"
.br
.RI "Base class for all of the settings scriptable objects\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Utilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
