.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Utilities/GUITools/ShowIfInterfaceAttribute.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Utilities/GUITools/ShowIfInterfaceAttribute.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBemotitron\&.Utilities\&.GUIUtilities\&.ShowIfInterfaceAttribute\fP"
.br
.RI "Attribute that will hide a field if it does not implement the indicated interface\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBemotitron\fP"
.br
.ti -1c
.RI "namespace \fBemotitron\&.Utilities\fP"
.br
.ti -1c
.RI "namespace \fBemotitron\&.Utilities\&.GUIUtilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
