.TH "Simplex.Noise" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Simplex.Noise \- Implementation of the Perlin simplex noise, an improved Perlin noise algorithm\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static float[] \fBCalc1D\fP (int width, float scale)"
.br
.ti -1c
.RI "static float[,] \fBCalc2D\fP (int width, int height, float scale)"
.br
.ti -1c
.RI "static float[,,] \fBCalc3D\fP (int width, int height, int length, float scale)"
.br
.ti -1c
.RI "static float \fBCalcPixel1D\fP (int x, float scale)"
.br
.ti -1c
.RI "static float \fBCalcPixel2D\fP (int x, int y, float scale)"
.br
.ti -1c
.RI "static float \fBCalcPixel3D\fP (int x, int y, int z, float scale)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static int \fBSeed\fP\fC [getset]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the Perlin simplex noise, an improved Perlin noise algorithm\&. 

Based loosely on SimplexNoise1234 by Stefan Gustavson http://staffwww.itn.liu.se/~stegu/aqsis/aqsis-newnoise/ 
.PP
Definition at line \fB42\fP of file \fBNoise\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static float[] Simplex\&.Noise\&.Calc1D (int width, float scale)\fC [static]\fP"

.PP
Definition at line \fB44\fP of file \fBNoise\&.cs\fP\&.
.SS "static float[,] Simplex\&.Noise\&.Calc2D (int width, int height, float scale)\fC [static]\fP"

.PP
Definition at line \fB52\fP of file \fBNoise\&.cs\fP\&.
.SS "static float[,,] Simplex\&.Noise\&.Calc3D (int width, int height, int length, float scale)\fC [static]\fP"

.PP
Definition at line \fB61\fP of file \fBNoise\&.cs\fP\&.
.SS "static float Simplex\&.Noise\&.CalcPixel1D (int x, float scale)\fC [static]\fP"

.PP
Definition at line \fB71\fP of file \fBNoise\&.cs\fP\&.
.SS "static float Simplex\&.Noise\&.CalcPixel2D (int x, int y, float scale)\fC [static]\fP"

.PP
Definition at line \fB76\fP of file \fBNoise\&.cs\fP\&.
.SS "static float Simplex\&.Noise\&.CalcPixel3D (int x, int y, int z, float scale)\fC [static]\fP"

.PP
Definition at line \fB81\fP of file \fBNoise\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Simplex\&.Noise\&.Seed\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Definition at line \fB92\fP of file \fBNoise\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
