.TH "Simplex" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Simplex
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNoise\fP"
.br
.RI "Implementation of the Perlin simplex noise, an improved Perlin noise algorithm\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
