.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendGameCommandEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendGameCommandEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits UnityEditor\&.Editor\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDrawInteraction\fP (\fBSendGameCommand\fP si)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBSendGameCommandEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommandEditor\&.DrawInteraction (\fBSendGameCommand\fP si)\fC [static]\fP"

.PP
Definition at line \fB39\fP of file \fBSendGameCommandEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
