.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.OnTeleportEvent" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.OnTeleportEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnTeleport\fP (\fBTeleporter\fP teleporter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBOnTeleportEvent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.OnTeleportEvent\&.OnTeleport (\fBTeleporter\fP teleporter)\fC [virtual]\fP"

.PP
Definition at line \fB8\fP of file \fBOnTeleportEvent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
