.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Teleporter" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Teleporter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "new Collider \fBcollider\fP"
.br
.ti -1c
.RI "LayerMask \fBlayers\fP"
.br
.ti -1c
.RI "GameObject \fBenterEffect\fP"
.br
.ti -1c
.RI "GameObject \fBexitEffect\fP"
.br
.ti -1c
.RI "Transform \fBdestinationTransform\fP"
.br
.ti -1c
.RI "float \fBdelayTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTeleporter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "new Collider SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.collider"

.PP
Definition at line \fB11\fP of file \fBTeleporter\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.delayTime"

.PP
Definition at line \fB17\fP of file \fBTeleporter\&.cs\fP\&.
.SS "Transform SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.destinationTransform"

.PP
Definition at line \fB16\fP of file \fBTeleporter\&.cs\fP\&.
.SS "GameObject SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.enterEffect"

.PP
Definition at line \fB14\fP of file \fBTeleporter\&.cs\fP\&.
.SS "GameObject SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.exitEffect"

.PP
Definition at line \fB15\fP of file \fBTeleporter\&.cs\fP\&.
.SS "LayerMask SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Teleporter\&.layers"

.PP
Definition at line \fB12\fP of file \fBTeleporter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
