.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.TriggerUnityEvent" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.TriggerUnityEvent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformInteraction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBunityEvent\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTriggerUnityEvent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerUnityEvent\&.PerformInteraction ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB10\fP of file \fBTriggerUnityEvent\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UnityEvent SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerUnityEvent\&.unityEvent"

.PP
Definition at line \fB8\fP of file \fBTriggerUnityEvent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
