.TH "SInt.Netcode.PhotonPUN.Menu" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Menu
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOpen\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBQuitGame\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmenuName\fP"
.br
.ti -1c
.RI "bool \fBopen\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnOpen_Event\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnExit_Event\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBMenu\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.Netcode\&.PhotonPUN\&.Menu\&.Close ()"

.PP
Definition at line \fB22\fP of file \fBMenu\&.cs\fP\&.
.SS "void SInt\&.Netcode\&.PhotonPUN\&.Menu\&.Open ()"

.PP
Definition at line \fB15\fP of file \fBMenu\&.cs\fP\&.
.SS "void SInt\&.Netcode\&.PhotonPUN\&.Menu\&.QuitGame ()"

.PP
Definition at line \fB29\fP of file \fBMenu\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SInt\&.Netcode\&.PhotonPUN\&.Menu\&.menuName"

.PP
Definition at line \fB10\fP of file \fBMenu\&.cs\fP\&.
.SS "UnityEvent SInt\&.Netcode\&.PhotonPUN\&.Menu\&.OnExit_Event"

.PP
Definition at line \fB13\fP of file \fBMenu\&.cs\fP\&.
.SS "UnityEvent SInt\&.Netcode\&.PhotonPUN\&.Menu\&.OnOpen_Event"

.PP
Definition at line \fB12\fP of file \fBMenu\&.cs\fP\&.
.SS "bool SInt\&.Netcode\&.PhotonPUN\&.Menu\&.open"

.PP
Definition at line \fB11\fP of file \fBMenu\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
