.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGun\fP"
.br
.ti -1c
.RI "class \fBGunInfo\fP"
.br
.ti -1c
.RI "interface \fBIDamageable\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItemInfo\fP"
.br
.ti -1c
.RI "class \fBPlayerController\fP"
.br
.ti -1c
.RI "class \fBPlayerGroundCheck\fP"
.br
.ti -1c
.RI "class \fBSingleShotGun\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
