.TH "SInt.MissionObjectives.MoOwner" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.MissionObjectives.MoOwner \- 3 set tasks  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoData\fP \fBFindMoDataByID\fP (string targetUniqueID)"
.br
.ti -1c
.RI "void \fBInit\fP (\fBMoData\fP curNode)"
.br
.ti -1c
.RI "\fBMoData\fP \fBSetupNode\fP (\fBMoData\fP childNode)"
.br
.ti -1c
.RI "void \fBOnRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFaction\fP \fBfaction\fP"
.br
.ti -1c
.RI "\fBMoData\fP \fBrootNode\fP"
.br
.ti -1c
.RI "GameObject \fBuiElementPrefab\fP"
.br
.ti -1c
.RI "List< LayoutGroup > \fBuiLayoutGroups\fP"
.br
.ti -1c
.RI "List< \fBMoUIElement\fP > \fBmoUIElements\fP"
.br
.ti -1c
.RI "List< \fBMoData\fP > \fBallMoDatasFound\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBMoData\fP > \fBmoDataDictionary\fP = new()"
.br
.in -1c
.SH "Detailed Description"
.PP 
3 set tasks 
.PP
Definition at line \fB256\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMoData\fP SInt\&.MissionObjectives\&.MoOwner\&.FindMoDataByID (string targetUniqueID)"

.PP
Definition at line \fB275\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoOwner\&.Init (\fBMoData\fP curNode)"

.PP
Definition at line \fB285\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoOwner\&.OnRefresh ()"

.PP
Definition at line \fB338\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBMoData\fP SInt\&.MissionObjectives\&.MoOwner\&.SetupNode (\fBMoData\fP childNode)"

.PP
Definition at line \fB310\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBMoData\fP> SInt\&.MissionObjectives\&.MoOwner\&.allMoDatasFound"

.PP
Definition at line \fB271\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBFaction\fP SInt\&.MissionObjectives\&.MoOwner\&.faction"

.PP
Definition at line \fB259\fP of file \fBMoManager\&.cs\fP\&.
.SS "Dictionary<string, \fBMoData\fP> SInt\&.MissionObjectives\&.MoOwner\&.moDataDictionary = new()"

.PP
Definition at line \fB272\fP of file \fBMoManager\&.cs\fP\&.
.SS "List<\fBMoUIElement\fP> SInt\&.MissionObjectives\&.MoOwner\&.moUIElements"

.PP
Definition at line \fB270\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBMoData\fP SInt\&.MissionObjectives\&.MoOwner\&.rootNode"

.PP
Definition at line \fB262\fP of file \fBMoManager\&.cs\fP\&.
.SS "GameObject SInt\&.MissionObjectives\&.MoOwner\&.uiElementPrefab"

.PP
Definition at line \fB264\fP of file \fBMoManager\&.cs\fP\&.
.SS "List<LayoutGroup> SInt\&.MissionObjectives\&.MoOwner\&.uiLayoutGroups"

.PP
Definition at line \fB265\fP of file \fBMoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
