.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.Gun" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.Gun
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Item\fP\&.
.PP
Inherited by \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.SingleShotGun\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract override void \fBUse\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBbulletImpactPrefab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBGun\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract override void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\&.Use ()\fC [pure virtual]\fP"

.PP
Implements \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Item\fP\&.
.PP
Implemented in \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.SingleShotGun\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\&.bulletImpactPrefab"

.PP
Definition at line \fB12\fP of file \fBGun\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
