.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.PlayerController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.PlayerController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP, and \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.IDamageable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnPlayerPropertiesUpdate\fP (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)"
.br
.RI "Called when custom player-properties are changed\&. "
.ti -1c
.RI "void \fBSetGroundedState\fP (bool _grounded)"
.br
.ti -1c
.RI "void \fBTakeDamage\fP (float damage)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBPlayerController\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.PlayerController\&.OnPlayerPropertiesUpdate (\fBPlayer\fP targetPlayer, \fBHashtable\fP changedProps)\fC [virtual]\fP"

.PP
Called when custom player-properties are changed\&. Player and the changed properties are passed as object[]\&. 
.PP
Changing properties must be done by Player\&.SetCustomProperties, which causes this callback locally, too\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetPlayer\fP Contains Player that changed\&.
.br
\fIchangedProps\fP Contains the properties that changed\&.
.RE
.PP

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB162\fP of file \fBPlayerController\&.cs\fP\&.
.SS "void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.PlayerController\&.SetGroundedState (bool _grounded)"

.PP
Definition at line \fB170\fP of file \fBPlayerController\&.cs\fP\&.
.SS "void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.PlayerController\&.TakeDamage (float damage)"

.PP
Implements \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.IDamageable\fP\&.
.PP
Definition at line \fB183\fP of file \fBPlayerController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
