.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Platform" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Platform
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMoveCharacterController\fP (Vector3 deltaPosition)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayerMask \fBlayers\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "CharacterController \fBm_CharacterController\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBPlatform\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Platform\&.MoveCharacterController (Vector3 deltaPosition)"

.PP
Definition at line \fB38\fP of file \fBPlatform\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayerMask SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Platform\&.layers"

.PP
Definition at line \fB12\fP of file \fBPlatform\&.cs\fP\&.
.SS "CharacterController SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Platform\&.m_CharacterController\fC [protected]\fP"

.PP
Definition at line \fB14\fP of file \fBPlatform\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
