.TH "SInt.ReCC.Utilities.ReCCFixedUpdateFollow" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.ReCC.Utilities.ReCCFixedUpdateFollow
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleFollow\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBtoFollow_Equipped\fP"
.br
.ti -1c
.RI "bool \fBisAlsoUseUpdate\fP = true"
.br
.ti -1c
.RI "bool \fBisAlsoUseFixedUpdate\fP = true"
.br
.ti -1c
.RI "bool \fBisAlsoUseLateUpdate\fP = true"
.br
.ti -1c
.RI "bool \fBisFindToFollowBySocketName\fP"
.br
.ti -1c
.RI "bool \fBisSearchByCustomRootTransform\fP = false"
.br
.ti -1c
.RI "HumanBodyBones \fBhumanBodyBones\fP"
.br
.ti -1c
.RI "string \fBtoFollow_socketName\fP"
.br
.ti -1c
.RI "Transform \fBcustomRootTransform\fP"
.br
.ti -1c
.RI "bool \fBignoreFollowRotation\fP"
.br
.ti -1c
.RI "bool \fBisUseRotationOverride\fP"
.br
.ti -1c
.RI "Quaternion \fBrotationOverride\fP"
.br
.ti -1c
.RI "bool \fBisUseMoveTowardsInsteadOfFollow\fP"
.br
.ti -1c
.RI "float \fBmoveTowardsSpeed\fP = 1f"
.br
.ti -1c
.RI "bool \fBIsUseOnValidateFind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.HandleFollow ()"

.PP
Definition at line \fB108\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Transform SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.customRootTransform"

.PP
Definition at line \fB25\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "HumanBodyBones SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.humanBodyBones"

.PP
Definition at line \fB22\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.ignoreFollowRotation"

.PP
Definition at line \fB28\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isAlsoUseFixedUpdate = true"

.PP
Definition at line \fB15\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isAlsoUseLateUpdate = true"

.PP
Definition at line \fB16\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isAlsoUseUpdate = true"

.PP
Definition at line \fB14\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isFindToFollowBySocketName"

.PP
Definition at line \fB19\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isSearchByCustomRootTransform = false"

.PP
Definition at line \fB20\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isUseMoveTowardsInsteadOfFollow"

.PP
Definition at line \fB31\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.IsUseOnValidateFind"

.PP
Definition at line \fB37\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "bool SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.isUseRotationOverride"

.PP
Definition at line \fB29\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "float SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.moveTowardsSpeed = 1f"

.PP
Definition at line \fB32\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "Quaternion SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.rotationOverride"

.PP
Definition at line \fB30\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "Transform SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.toFollow_Equipped"

.PP
Definition at line \fB11\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.
.SS "string SInt\&.ReCC\&.Utilities\&.ReCCFixedUpdateFollow\&.toFollow_socketName"

.PP
Definition at line \fB23\fP of file \fBReCCFixedUpdateFollow\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
