.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.GunInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.GunInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.ItemInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBdamage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBGunInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.GunInfo\&.damage"

.PP
Definition at line \fB10\fP of file \fBGunInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
