.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleRotator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleRotator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformTransform\fP (float position)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBaxis\fP = Vector3\&.forward"
.br
.ti -1c
.RI "float \fBstart\fP = 0"
.br
.ti -1c
.RI "float \fBend\fP = 90"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSimpleRotator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\&.PerformTransform (float position)\fC [virtual]\fP"

.PP
Reimplemented from \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP\&.
.PP
Definition at line \fB14\fP of file \fBSimpleRotator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\&.axis = Vector3\&.forward"

.PP
Definition at line \fB9\fP of file \fBSimpleRotator\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\&.end = 90"

.PP
Definition at line \fB11\fP of file \fBSimpleRotator\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\&.start = 0"

.PP
Definition at line \fB10\fP of file \fBSimpleRotator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
