.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Collectable" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Collectable
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "new Collider \fBcollider\fP"
.br
.ti -1c
.RI "LayerMask \fBlayers\fP"
.br
.ti -1c
.RI "GameObject \fBcollectEffect\fP"
.br
.ti -1c
.RI "AudioClip \fBonCollectAudio\fP"
.br
.ti -1c
.RI "bool \fBdisableOnCollect\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBCollect\fP (Collider other)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCollectable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.Collect (Collider other)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line \fB26\fP of file \fBCollectable\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.collectEffect"

.PP
Definition at line \fB10\fP of file \fBCollectable\&.cs\fP\&.
.SS "new Collider SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.collider"

.PP
Definition at line \fB8\fP of file \fBCollectable\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.disableOnCollect = false"

.PP
Definition at line \fB12\fP of file \fBCollectable\&.cs\fP\&.
.SS "LayerMask SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.layers"

.PP
Definition at line \fB9\fP of file \fBCollectable\&.cs\fP\&.
.SS "AudioClip SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collectable\&.onCollectAudio"

.PP
Definition at line \fB11\fP of file \fBCollectable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
