.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.SingleShotGun" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.SingleShotGun
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBUse\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSingleShotGun\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.SingleShotGun\&.Use ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\fP\&.
.PP
Definition at line \fB19\fP of file \fBSingleShotGun\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
