.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameplayCounter" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameplayCounter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformInteraction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurrentCount\fP = 0"
.br
.ti -1c
.RI "int \fBtargetCount\fP = 3"
.br
.ti -1c
.RI "\fBSendGameCommand\fP \fBonIncrementSendCommand\fP"
.br
.ti -1c
.RI "\fBGameCommandHandler\fP \fBonIncrementPerformAction\fP"
.br
.ti -1c
.RI "\fBSendGameCommand\fP \fBonTargetReachedSendCommand\fP"
.br
.ti -1c
.RI "\fBGameCommandHandler\fP \fBonTargetReachedPerformAction\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBGameplayCounter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.PerformInteraction ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB23\fP of file \fBGameplayCounter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.currentCount = 0"

.PP
Definition at line \fB8\fP of file \fBGameplayCounter\&.cs\fP\&.
.SS "\fBGameCommandHandler\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.onIncrementPerformAction"

.PP
Definition at line \fB15\fP of file \fBGameplayCounter\&.cs\fP\&.
.SS "\fBSendGameCommand\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.onIncrementSendCommand"

.PP
Definition at line \fB13\fP of file \fBGameplayCounter\&.cs\fP\&.
.SS "\fBGameCommandHandler\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.onTargetReachedPerformAction"

.PP
Definition at line \fB20\fP of file \fBGameplayCounter\&.cs\fP\&.
.SS "\fBSendGameCommand\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.onTargetReachedSendCommand"

.PP
Definition at line \fB18\fP of file \fBGameplayCounter\&.cs\fP\&.
.SS "int SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\&.targetCount = 3"

.PP
Definition at line \fB9\fP of file \fBGameplayCounter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
