.TH "SInt.MissionObjectives.MoData" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.MissionObjectives.MoData
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObjectiveProgress\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTryComplete\fP ()"
.br
.ti -1c
.RI "void \fBTryProgress\fP ()"
.br
.ti -1c
.RI "void \fBTryProgress\fP (int progressIncrement)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBuniqueId\fP"
.br
.ti -1c
.RI "string \fBvisualDescription\fP"
.br
.ti -1c
.RI "\fBObjectiveProgress\fP \fBprogress\fP"
.br
.ti -1c
.RI "bool \fBisHideCheckMark\fP"
.br
.ti -1c
.RI "bool \fBisHideUIElement\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnProgression\fP"
.br
.ti -1c
.RI "UnityEvent \fBOnCompletion\fP"
.br
.ti -1c
.RI "List< \fBMoData\fP > \fBchildMoData\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsAllChildObjectivesComplete\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB348\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.MissionObjectives\&.MoData\&.TryComplete ()"

.PP
Definition at line \fB412\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoData\&.TryProgress ()"

.PP
Definition at line \fB420\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoData\&.TryProgress (int progressIncrement)"

.PP
Definition at line \fB432\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBMoData\fP> SInt\&.MissionObjectives\&.MoData\&.childMoData"

.PP
Definition at line \fB394\fP of file \fBMoManager\&.cs\fP\&.
.SS "bool SInt\&.MissionObjectives\&.MoData\&.isHideCheckMark"

.PP
Definition at line \fB359\fP of file \fBMoManager\&.cs\fP\&.
.SS "bool SInt\&.MissionObjectives\&.MoData\&.isHideUIElement"

.PP
Definition at line \fB360\fP of file \fBMoManager\&.cs\fP\&.
.SS "UnityEvent SInt\&.MissionObjectives\&.MoData\&.OnCompletion"

.PP
Definition at line \fB364\fP of file \fBMoManager\&.cs\fP\&.
.SS "UnityEvent SInt\&.MissionObjectives\&.MoData\&.OnProgression"

.PP
Definition at line \fB363\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBObjectiveProgress\fP SInt\&.MissionObjectives\&.MoData\&.progress"

.PP
Definition at line \fB357\fP of file \fBMoManager\&.cs\fP\&.
.SS "string SInt\&.MissionObjectives\&.MoData\&.title"

.PP
Definition at line \fB352\fP of file \fBMoManager\&.cs\fP\&.
.SS "string SInt\&.MissionObjectives\&.MoData\&.uniqueId"

.PP
Definition at line \fB353\fP of file \fBMoManager\&.cs\fP\&.
.SS "string SInt\&.MissionObjectives\&.MoData\&.visualDescription"

.PP
Definition at line \fB355\fP of file \fBMoManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool SInt\&.MissionObjectives\&.MoData\&.IsAllChildObjectivesComplete\fC [get]\fP"

.PP
Definition at line \fB396\fP of file \fBMoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
