.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.ItemInfo" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.ItemInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.GunInfo\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBitemName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBItemInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.ItemInfo\&.itemName"

.PP
Definition at line \fB9\fP of file \fBItemInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
