.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendGameCommand" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendGameCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnBecameInvisible\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnBecameVisible\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnCollisionEnter\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnCollisionExit\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnCollisionStay\fP, and \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSend\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameCommandType\fP \fBinteractionType\fP"
.br
.ti -1c
.RI "\fBGameCommandReceiver\fP \fBinteractiveObject\fP"
.br
.ti -1c
.RI "bool \fBoneShot\fP = false"
.br
.ti -1c
.RI "float \fBcoolDown\fP = 1"
.br
.ti -1c
.RI "AudioSource \fBonSendAudio\fP"
.br
.ti -1c
.RI "float \fBaudioDelay\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBReset\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBTemperature\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBSendGameCommand\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.Reset ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerCommand\fP\&.
.PP
Definition at line \fB50\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.Send ()"

.PP
Definition at line \fB40\fP of file \fBSendGameCommand\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.audioDelay"

.PP
Definition at line \fB26\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.coolDown = 1"

.PP
Definition at line \fB20\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "\fBGameCommandType\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.interactionType"

.PP
Definition at line \fB14\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "\fBGameCommandReceiver\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.interactiveObject"

.PP
Definition at line \fB16\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.oneShot = false"

.PP
Definition at line \fB18\fP of file \fBSendGameCommand\&.cs\fP\&.
.SS "AudioSource SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.onSendAudio"

.PP
Definition at line \fB24\fP of file \fBSendGameCommand\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\&.Temperature\fC [get]\fP"

.PP
Definition at line \fB31\fP of file \fBSendGameCommand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
