.TH "SInt.Netcode.PhotonPUN.RoomManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.RoomManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnEnable\fP ()"
.br
.ti -1c
.RI "override void \fBOnDisable\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBRoomManager\fP \fBInstance\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBRoomManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.Netcode\&.PhotonPUN\&.RoomManager\&.OnDisable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB29\fP of file \fBRoomManager\&.cs\fP\&.
.SS "override void SInt\&.Netcode\&.PhotonPUN\&.RoomManager\&.OnEnable ()\fC [virtual]\fP"

.PP
Reimplemented from \fBPhoton\&.Pun\&.MonoBehaviourPunCallbacks\fP\&.
.PP
Definition at line \fB23\fP of file \fBRoomManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRoomManager\fP SInt\&.Netcode\&.PhotonPUN\&.RoomManager\&.Instance\fC [static]\fP"

.PP
Definition at line \fB11\fP of file \fBRoomManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
