.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Collector" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.Collector
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnCollect\fP (\fBCollectable\fP collectable)"
.br
.ti -1c
.RI "bool \fBHasCollectable\fP (string name)"
.br
.ti -1c
.RI "bool \fBHasCollectableQuantity\fP (string name, int requiredCount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBattachCollectables\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCollector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collector\&.HasCollectable (string name)"

.PP
Definition at line \fB22\fP of file \fBCollector\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collector\&.HasCollectableQuantity (string name, int requiredCount)"

.PP
Definition at line \fB27\fP of file \fBCollector\&.cs\fP\&.
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collector\&.OnCollect (\fBCollectable\fP collectable)\fC [virtual]\fP"

.PP
Definition at line \fB11\fP of file \fBCollector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.Collector\&.attachCollectables = false"

.PP
Definition at line \fB8\fP of file \fBCollector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
