.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.ParticleSystemEmit\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.PlayAnimation\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.PlaySound\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetAnimatorTrigger\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetGameObjectActive\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.StartPlayableDirector\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SwitchMaterial\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.ToggleGameObjectActive\fP, and \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerUnityEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBPerformInteraction\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInteraction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameCommandType\fP \fBinteractionType\fP"
.br
.ti -1c
.RI "bool \fBisOneShot\fP = false"
.br
.ti -1c
.RI "float \fBcoolDown\fP = 0"
.br
.ti -1c
.RI "float \fBstartDelay\fP = 0"
.br
.ti -1c
.RI "bool \fBisTriggered\fP = false"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP\&.
.PP
Definition at line \fB52\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.OnInteraction ()\fC [virtual]\fP"

.PP
Definition at line \fB28\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "abstract void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.PerformInteraction ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameplayCounter\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.ParticleSystemEmit\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.PlayAnimation\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.PlaySound\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetAnimatorTrigger\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetGameObjectActive\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.StartPlayableDirector\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SwitchMaterial\fP, \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.ToggleGameObjectActive\fP, and \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.TriggerUnityEvent\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.coolDown = 0"

.PP
Definition at line \fB18\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "\fBGameCommandType\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.interactionType"

.PP
Definition at line \fB14\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.isOneShot = false"

.PP
Definition at line \fB16\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.isTriggered = false"

.PP
Definition at line \fB22\fP of file \fBGameCommandHandler\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\&.startDelay = 0"

.PP
Definition at line \fB20\fP of file \fBGameCommandHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
