.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleTranslator" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleTranslator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformTransform\fP (float position)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "new Rigidbody \fBrigidbody\fP"
.br
.ti -1c
.RI "Vector3 \fBstart\fP = \-Vector3\&.forward"
.br
.ti -1c
.RI "Vector3 \fBend\fP = Vector3\&.forward"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSimpleTranslator\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\&.PerformTransform (float position)\fC [virtual]\fP"

.PP
Reimplemented from \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\fP\&.
.PP
Definition at line \fB12\fP of file \fBSimpleTranslator\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\&.end = Vector3\&.forward"

.PP
Definition at line \fB10\fP of file \fBSimpleTranslator\&.cs\fP\&.
.SS "new Rigidbody SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\&.rigidbody"

.PP
Definition at line \fB8\fP of file \fBSimpleTranslator\&.cs\fP\&.
.SS "Vector3 SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\&.start = \-Vector3\&.forward"

.PP
Definition at line \fB9\fP of file \fBSimpleTranslator\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
