.TH "SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.Item" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN.Samples.SimpleFPSOnline.Item
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBUse\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBItemInfo\fP \fBitemInfo\fP"
.br
.ti -1c
.RI "GameObject \fBitemGameObject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBItem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Item\&.Use ()\fC [pure virtual]\fP"

.PP
Implemented in \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Gun\fP, and \fBSInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.SingleShotGun\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Item\&.itemGameObject"

.PP
Definition at line \fB9\fP of file \fBItem\&.cs\fP\&.
.SS "\fBItemInfo\fP SInt\&.Netcode\&.PhotonPUN\&.Samples\&.SimpleFPSOnline\&.Item\&.itemInfo"

.PP
Definition at line \fB8\fP of file \fBItem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
