.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SetGameObjectActive" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SetGameObjectActive
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformInteraction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject[] \fBtargets\fP"
.br
.ti -1c
.RI "bool \fBisEnabled\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSetGameObjectActive\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetGameObjectActive\&.PerformInteraction ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB12\fP of file \fBSetGameObjectActive\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetGameObjectActive\&.isEnabled = true"

.PP
Definition at line \fB10\fP of file \fBSetGameObjectActive\&.cs\fP\&.
.SS "GameObject [] SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SetGameObjectActive\&.targets"

.PP
Definition at line \fB9\fP of file \fBSetGameObjectActive\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
