.TH "SInt.MissionObjectives" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.MissionObjectives
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoData\fP"
.br
.ti -1c
.RI "class \fBMoManager\fP"
.br
.ti -1c
.RI "class \fBMoOwner\fP"
.br
.RI "3 set tasks "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMoStatus\fP { \fBInactive\fP, \fBActive\fP, \fBComplete\fP, \fBFailed\fP, \fBAbandoned\fP, \fBUnavailable\fP }"
.br
.ti -1c
.RI "enum \fBFaction\fP { \fBNone\fP, \fBHuman\fP, \fBCat\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSInt\&.MissionObjectives\&.Faction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIHuman \fP\fP
.TP
\fB\fICat \fP\fP
.PP
Definition at line \fB470\fP of file \fBMoManager\&.cs\fP\&.
.SS "enum \fBSInt\&.MissionObjectives\&.MoStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInactive \fP\fP
.TP
\fB\fIActive \fP\fP
.TP
\fB\fIComplete \fP\fP
.TP
\fB\fIFailed \fP\fP
.TP
\fB\fIAbandoned \fP\fP
.TP
\fB\fIUnavailable \fP\fP
.PP
Definition at line \fB460\fP of file \fBMoManager\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
