.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SwitchMaterial" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SwitchMaterial
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformInteraction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Renderer \fBtarget\fP"
.br
.ti -1c
.RI "Material[] \fBmaterials\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSwitchMaterial\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SwitchMaterial\&.PerformInteraction ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB12\fP of file \fBSwitchMaterial\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Material [] SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SwitchMaterial\&.materials"

.PP
Definition at line \fB9\fP of file \fBSwitchMaterial\&.cs\fP\&.
.SS "Renderer SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SwitchMaterial\&.target"

.PP
Definition at line \fB8\fP of file \fBSwitchMaterial\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
