.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleTransformer" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SimpleTransformer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Inherited by \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\fP, and \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLoopType\fP { \fBOnce\fP, \fBPingPong\fP, \fBRepeat\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBPerformInteraction\fP ()"
.br
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBPerformTransform\fP (float position)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLoopType\fP \fBloopType\fP"
.br
.ti -1c
.RI "float \fBduration\fP = 1"
.br
.ti -1c
.RI "AnimationCurve \fBaccelCurve\fP"
.br
.ti -1c
.RI "bool \fBactivate\fP = false"
.br
.ti -1c
.RI "\fBSendGameCommand\fP \fBOnStartCommand\fP"
.br
.ti -1c
.RI "\fBSendGameCommand\fP \fBOnStopCommand\fP"
.br
.ti -1c
.RI "AudioSource \fBonStartAudio\fP"
.br
.ti -1c
.RI "AudioSource \fBonEndAudio\fP"
.br
.ti -1c
.RI "float \fBpreviewPosition\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBPlatform\fP \fBm_Platform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.LoopType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOnce \fP\fP
.TP
\fB\fIPingPong \fP\fP
.TP
\fB\fIRepeat \fP\fP
.PP
Definition at line \fB7\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB38\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.FixedUpdate ()"

.PP
Definition at line \fB52\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "override void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.PerformInteraction ()\fC [virtual]\fP"

.PP
Implements \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandHandler\fP\&.
.PP
Definition at line \fB45\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "virtual void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.PerformTransform (float position)\fC [virtual]\fP"

.PP
Reimplemented in \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleRotator\fP, and \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTranslator\fP\&.
.PP
Definition at line \fB73\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AnimationCurve SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.accelCurve"

.PP
Definition at line \fB17\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "bool SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.activate = false"

.PP
Definition at line \fB19\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.duration = 1"

.PP
Definition at line \fB16\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "\fBLoopType\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.loopType"

.PP
Definition at line \fB14\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "\fBPlatform\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.m_Platform\fC [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "AudioSource SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.onEndAudio"

.PP
Definition at line \fB22\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "AudioSource SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.onStartAudio"

.PP
Definition at line \fB22\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "\fBSendGameCommand\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.OnStartCommand"

.PP
Definition at line \fB20\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "\fBSendGameCommand\fP SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.OnStopCommand"

.PP
Definition at line \fB20\fP of file \fBSimpleTransformer\&.cs\fP\&.
.SS "float SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SimpleTransformer\&.previewPosition"

.PP
Definition at line \fB25\fP of file \fBSimpleTransformer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
