.TH "SInt.MissionObjectives.MoManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.MissionObjectives.MoManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSceneSpecificTweaks\fP ()"
.br
.ti -1c
.RI "void \fBFactionSpecificTweaks\fP ()"
.br
.ti -1c
.RI "void \fBTryProgressMoByID\fP (string targetUniqueID)"
.br
.ti -1c
.RI "void \fBTryProgressMoByIDRPC\fP (string targetUniqueID)"
.br
.ti -1c
.RI "\fBMoData\fP \fBSearchMoByID\fP (string targetUniqueID)"
.br
.ti -1c
.RI "void \fBSetMoDataProgressionStatus\fP (string targetUniqueID, \fBMoStatus\fP newMoStatus)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBMoOwner\fP > \fBmissions\fP"
.br
.ti -1c
.RI "\fBPhotonView\fP \fBPV\fP"
.br
.ti -1c
.RI "bool \fBisAllowDebugInput\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMoManager\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.MissionObjectives\&.MoManager\&.FactionSpecificTweaks ()"

.PP
Definition at line \fB49\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoManager\&.SceneSpecificTweaks ()"

.PP
Definition at line \fB41\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBMoData\fP SInt\&.MissionObjectives\&.MoManager\&.SearchMoByID (string targetUniqueID)"

.PP
Definition at line \fB189\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoManager\&.SetMoDataProgressionStatus (string targetUniqueID, \fBMoStatus\fP newMoStatus)"

.PP
Definition at line \fB200\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoManager\&.TryProgressMoByID (string targetUniqueID)"

.PP
Definition at line \fB171\fP of file \fBMoManager\&.cs\fP\&.
.SS "void SInt\&.MissionObjectives\&.MoManager\&.TryProgressMoByIDRPC (string targetUniqueID)"

.PP
Definition at line \fB177\fP of file \fBMoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMoManager\fP SInt\&.MissionObjectives\&.MoManager\&.instance\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBMoManager\&.cs\fP\&.
.SS "bool SInt\&.MissionObjectives\&.MoManager\&.isAllowDebugInput"

.PP
Definition at line \fB22\fP of file \fBMoManager\&.cs\fP\&.
.SS "List<\fBMoOwner\fP> SInt\&.MissionObjectives\&.MoManager\&.missions"

.PP
Definition at line \fB17\fP of file \fBMoManager\&.cs\fP\&.
.SS "\fBPhotonView\fP SInt\&.MissionObjectives\&.MoManager\&.PV"

.PP
Definition at line \fB18\fP of file \fBMoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
