.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollectable\fP"
.br
.ti -1c
.RI "class \fBCollector\fP"
.br
.ti -1c
.RI "class \fBCommandGizmos\fP"
.br
.ti -1c
.RI "class \fBCommandReceiverEditor\fP"
.br
.ti -1c
.RI "class \fBGameCommandHandler\fP"
.br
.ti -1c
.RI "class \fBGameCommandReceiver\fP"
.br
.ti -1c
.RI "class \fBGameplayCounter\fP"
.br
.ti -1c
.RI "class \fBOnTeleportEvent\fP"
.br
.ti -1c
.RI "class \fBParticleSystemEmit\fP"
.br
.ti -1c
.RI "class \fBPlatform\fP"
.br
.ti -1c
.RI "class \fBPlayAnimation\fP"
.br
.ti -1c
.RI "class \fBPlaySound\fP"
.br
.ti -1c
.RI "class \fBSendGameCommand\fP"
.br
.ti -1c
.RI "class \fBSendGameCommandEditor\fP"
.br
.ti -1c
.RI "class \fBSendOnBecameInvisible\fP"
.br
.ti -1c
.RI "class \fBSendOnBecameVisible\fP"
.br
.ti -1c
.RI "class \fBSendOnCollisionEnter\fP"
.br
.ti -1c
.RI "class \fBSendOnCollisionExit\fP"
.br
.ti -1c
.RI "class \fBSendOnCollisionStay\fP"
.br
.ti -1c
.RI "class \fBSendOnTriggerEnter\fP"
.br
.ti -1c
.RI "class \fBSendOnTriggerExit\fP"
.br
.ti -1c
.RI "class \fBSendOnTriggerStay\fP"
.br
.ti -1c
.RI "class \fBSetAnimatorTrigger\fP"
.br
.ti -1c
.RI "class \fBSetGameObjectActive\fP"
.br
.ti -1c
.RI "class \fBSimpleRotator\fP"
.br
.ti -1c
.RI "class \fBSimpleTransformer\fP"
.br
.ti -1c
.RI "class \fBSimpleTransformerEditor\fP"
.br
.ti -1c
.RI "class \fBSimpleTranslator\fP"
.br
.ti -1c
.RI "class \fBSimpleTranslatorEditor\fP"
.br
.ti -1c
.RI "class \fBStartPlayableDirector\fP"
.br
.ti -1c
.RI "class \fBSwitchMaterial\fP"
.br
.ti -1c
.RI "class \fBTeleporter\fP"
.br
.ti -1c
.RI "class \fBToggleGameObjectActive\fP"
.br
.ti -1c
.RI "class \fBTriggerCommand\fP"
.br
.ti -1c
.RI "class \fBTriggerUnityEvent\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGameCommandType\fP { \fBNone\fP, \fBActivate\fP, \fBDeactivate\fP, \fBOpen\fP, \fBClose\fP, \fBSpawn\fP, \fBDestroy\fP, \fBStart\fP, \fBStop\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINone \fP\fP
.TP
\fB\fIActivate \fP\fP
.TP
\fB\fIDeactivate \fP\fP
.TP
\fB\fIOpen \fP\fP
.TP
\fB\fIClose \fP\fP
.TP
\fB\fISpawn \fP\fP
.TP
\fB\fIDestroy \fP\fP
.TP
\fB\fIStart \fP\fP
.TP
\fB\fIStop \fP\fP
.PP
Definition at line \fB9\fP of file \fBGameCommandType\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
