.TH "SInt.Netcode.PhotonPUN" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.Netcode.PhotonPUN
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSamples\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenu\fP"
.br
.ti -1c
.RI "class \fBMenuManager\fP"
.br
.ti -1c
.RI "class \fBPhotonPlayer\fP"
.br
.ti -1c
.RI "class \fBPlayerListItem\fP"
.br
.ti -1c
.RI "class \fBPlayerManager\fP"
.br
.ti -1c
.RI "class \fBRoomListItem\fP"
.br
.ti -1c
.RI "class \fBRoomManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
