.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendOnCollisionExit" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.SendOnCollisionExit
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendGameCommand\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayerMask \fBlayers\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSendOnCollisionExit\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayerMask SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.SendOnCollisionExit\&.layers"

.PP
Definition at line \fB10\fP of file \fBSendOnCollisionExit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
