.TH "SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandReceiver" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SInt.QuickTask.Gamekit3D.KitHelpers.GameCommands.GameCommandReceiver
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReceive\fP (\fBGameCommandType\fP e)"
.br
.ti -1c
.RI "void \fBRegister\fP (\fBGameCommandType\fP type, \fBGameCommandHandler\fP handler)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBGameCommandType\fP type, \fBGameCommandHandler\fP handler)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBGameCommandReceiver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandReceiver\&.Receive (\fBGameCommandType\fP e)"

.PP
Definition at line \fB12\fP of file \fBGameCommandReceiver\&.cs\fP\&.
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandReceiver\&.Register (\fBGameCommandType\fP type, \fBGameCommandHandler\fP handler)"

.PP
Definition at line \fB21\fP of file \fBGameCommandReceiver\&.cs\fP\&.
.SS "void SInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.GameCommandReceiver\&.Remove (\fBGameCommandType\fP type, \fBGameCommandHandler\fP handler)"

.PP
Definition at line \fB31\fP of file \fBGameCommandReceiver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
