.TH "SoundGeneralDynamicsMultiplayerPhoton.SoundPiece" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamicsMultiplayerPhoton.SoundPiece
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBActivateTime\fP ()"
.br
.ti -1c
.RI "void \fBActivateSpecificTime\fP (float time)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpieceName\fP"
.br
.ti -1c
.RI "AudioClip \fBAudio\fP"
.br
.ti -1c
.RI "AudioMixerGroup \fBAudioMixer\fP"
.br
.ti -1c
.RI "string \fBsoundCastName\fP"
.br
.ti -1c
.RI "string \fBsoundVisualizerName\fP"
.br
.ti -1c
.RI "bool \fBplayOnStart\fP"
.br
.ti -1c
.RI "int \fBloopNum\fP"
.br
.ti -1c
.RI "float \fBdelayBefore\fP = 0f"
.br
.ti -1c
.RI "bool \fBwaitForSoundFinish\fP"
.br
.ti -1c
.RI "float \fBdelayAfter\fP = 0f"
.br
.ti -1c
.RI "float \fBVolume\fP = 1f"
.br
.ti -1c
.RI "float \fBPitch\fP = 1f"
.br
.ti -1c
.RI "float \fBoriginalMaxVolume\fP"
.br
.ti -1c
.RI "float \fBoriginalPitch\fP"
.br
.ti -1c
.RI "AudioSource \fBsource\fP"
.br
.ti -1c
.RI "\fBSoundCast\fP[] \fBsoundCastSource\fP"
.br
.ti -1c
.RI "\fBSoundVisualizer\fP[] \fBsoundVisualSource\fP"
.br
.ti -1c
.RI "WaitForSeconds \fBdelayBeforeWait\fP"
.br
.ti -1c
.RI "WaitWhile \fBdelayDuringWait\fP"
.br
.ti -1c
.RI "WaitForSeconds \fBdelayAfterWait\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB722\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.ActivateSpecificTime (float time)"

.PP
Definition at line \fB770\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.ActivateTime ()"

.PP
Definition at line \fB763\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AudioClip SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.Audio"

.PP
Definition at line \fB726\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "AudioMixerGroup SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.AudioMixer"

.PP
Definition at line \fB727\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.delayAfter = 0f"

.PP
Definition at line \fB747\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "WaitForSeconds SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.delayAfterWait"

.PP
Definition at line \fB761\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.delayBefore = 0f"

.PP
Definition at line \fB743\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "WaitForSeconds SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.delayBeforeWait"

.PP
Definition at line \fB759\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "WaitWhile SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.delayDuringWait"

.PP
Definition at line \fB760\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "int SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.loopNum"

.PP
Definition at line \fB741\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.originalMaxVolume"

.PP
Definition at line \fB753\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.originalPitch"

.PP
Definition at line \fB754\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "string SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.pieceName"

.PP
Definition at line \fB725\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.Pitch = 1f"

.PP
Definition at line \fB751\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "bool SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.playOnStart"

.PP
Definition at line \fB739\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "string SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.soundCastName"

.PP
Definition at line \fB731\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "\fBSoundCast\fP [] SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.soundCastSource"

.PP
Definition at line \fB756\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "string SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.soundVisualizerName"

.PP
Definition at line \fB735\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "\fBSoundVisualizer\fP [] SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.soundVisualSource"

.PP
Definition at line \fB757\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "AudioSource SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.source"

.PP
Definition at line \fB755\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.Volume = 1f"

.PP
Definition at line \fB749\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "bool SoundGeneralDynamicsMultiplayerPhoton\&.SoundPiece\&.waitForSoundFinish"

.PP
Definition at line \fB745\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
