.TH "SoundGeneralDynamics.SoundPiece" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamics.SoundPiece
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpieceName\fP"
.br
.ti -1c
.RI "AudioClip \fBAudio\fP"
.br
.ti -1c
.RI "AudioMixerGroup \fBAudioMixer\fP"
.br
.ti -1c
.RI "string \fBsoundCastName\fP"
.br
.ti -1c
.RI "int \fBloopNum\fP"
.br
.ti -1c
.RI "float \fBdelayBefore\fP = 0f"
.br
.ti -1c
.RI "bool \fBwaitForSoundFinish\fP"
.br
.ti -1c
.RI "float \fBdelayAfter\fP = 0f"
.br
.ti -1c
.RI "float \fBVolume\fP = 1f"
.br
.ti -1c
.RI "float \fBPitch\fP = 1f"
.br
.ti -1c
.RI "float \fBoriginalMaxVolume\fP"
.br
.ti -1c
.RI "float \fBoriginalPitch\fP"
.br
.ti -1c
.RI "AudioSource \fBsource\fP"
.br
.ti -1c
.RI "\fBSoundCast\fP[] \fBsoundCastSource\fP"
.br
.ti -1c
.RI "WaitForSeconds \fBdelayBeforeWait\fP"
.br
.ti -1c
.RI "WaitWhile \fBdelayDuringWait\fP"
.br
.ti -1c
.RI "WaitForSeconds \fBdelayAfterWait\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB432\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AudioClip SoundGeneralDynamics\&.SoundPiece\&.Audio"

.PP
Definition at line \fB436\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "AudioMixerGroup SoundGeneralDynamics\&.SoundPiece\&.AudioMixer"

.PP
Definition at line \fB437\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.delayAfter = 0f"

.PP
Definition at line \fB448\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "WaitForSeconds SoundGeneralDynamics\&.SoundPiece\&.delayAfterWait"

.PP
Definition at line \fB461\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.delayBefore = 0f"

.PP
Definition at line \fB444\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "WaitForSeconds SoundGeneralDynamics\&.SoundPiece\&.delayBeforeWait"

.PP
Definition at line \fB459\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "WaitWhile SoundGeneralDynamics\&.SoundPiece\&.delayDuringWait"

.PP
Definition at line \fB460\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "int SoundGeneralDynamics\&.SoundPiece\&.loopNum"

.PP
Definition at line \fB442\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.originalMaxVolume"

.PP
Definition at line \fB454\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.originalPitch"

.PP
Definition at line \fB455\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "string SoundGeneralDynamics\&.SoundPiece\&.pieceName"

.PP
Definition at line \fB435\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.Pitch = 1f"

.PP
Definition at line \fB452\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "string SoundGeneralDynamics\&.SoundPiece\&.soundCastName"

.PP
Definition at line \fB438\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "\fBSoundCast\fP [] SoundGeneralDynamics\&.SoundPiece\&.soundCastSource"

.PP
Definition at line \fB457\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "AudioSource SoundGeneralDynamics\&.SoundPiece\&.source"

.PP
Definition at line \fB456\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundPiece\&.Volume = 1f"

.PP
Definition at line \fB450\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "bool SoundGeneralDynamics\&.SoundPiece\&.waitForSoundFinish"

.PP
Definition at line \fB446\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
