.TH "SoundGeneralDynamicsMultiplayerPhoton" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamicsMultiplayerPhoton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSoundChain\fP"
.br
.ti -1c
.RI "class \fBSoundChunk\fP"
.br
.ti -1c
.RI "class \fBSoundPiece\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialization\fP ()"
.br
.ti -1c
.RI "void \fBmultiplayerSoundChain\fP (int soundChainID)"
.br
.ti -1c
.RI "void \fBmultiplayerSoundChunk\fP (int soundChunkID)"
.br
.ti -1c
.RI "void \fBmultiplayerSoundPiece\fP (int soundPieceID)"
.br
.ti -1c
.RI "void \fBmultiplayerSoundChain\fP (string soundChainName)"
.br
.ti -1c
.RI "void \fBmultiplayerSoundChunk\fP (string soundChunkName)"
.br
.ti -1c
.RI "void \fBmultiplayerSoundPiece\fP (string soundPieceName)"
.br
.ti -1c
.RI "void \fBPlayChain\fP (int soundChainID)"
.br
.ti -1c
.RI "void \fBPlayChunk\fP (int soundChunkID)"
.br
.ti -1c
.RI "void \fBPlayPiece\fP (int soundPieceID)"
.br
.ti -1c
.RI "void \fBPlayChain\fP (string soundChainName)"
.br
.ti -1c
.RI "void \fBPlayChunk\fP (string soundChunkName)"
.br
.ti -1c
.RI "void \fBPlayPiece\fP (string soundPieceName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
!!Notes: Script Version (2\&.0V) By Chan Kwok Chun (Gul) Will be reused in future projects because its perfect for copy and pasting Will be upgraded to include 3D casts
.PP
Update Log: 1\&.0V - : - Basic Introduction with library and its components\&. 1\&.1V - : - Chunks and chains sounds (Doesn't actually work) 1\&.2V - : - StartCoroutine style code allows for more action\&. 1\&.3V - : - Includes sound volume and pitch adjustments\&. 1\&.4V - : - Basic inclusion of delay for more possible adjustments\&. 1\&.5V - : - Optimization 1\&.6V - : - Sound Cast introduction\&. 1\&.7V - : - Sound Cast optimization as well as including an updating integral\&. 1\&.8V - : - Info statements and code cleanup\&. 1\&.9V - : - Actually make the chunks and chains work\&. (Teehee) 2\&.0V 05/02/2022: - Included looping for chunks within the chains, and the pieces within the chunks\&. (Ehe, it actually didn't work before this)
.IP "\(bu" 2
Sound cast discovery optimization (Include this version into 2D when the time comes!!!) 2\&.1V 13/02/2022: - Renamed to \fBSoundGeneralDynamics\fP, Seperated Sound Cast from Sound General Dynamics, added sound lumping (Sounds in the same zone doesn't just cause itself to be louder) 2\&.2V 22/02/2022: - Synced multiplayer sound play, doing surround sound\&. 2\&.3V 08/03/2022: - Surround Sound based on y rotation, as long as the ears doesn't tilt\&. 2\&.4V 15/03/2022: - Added Play On Start, made tilt included in calculation\&. 2\&.5V 04/04/2022: - Progress on sound visual indicator\&. 2\&.6V 09/04/2022: - Finished Sound Visualizer, not tested\&. 2\&.7V 17/04/2022: - Fixed some bugs, optimized, seperated visual indicator with a last known location director, removed continuous checker(Hated this to bits) 
.PP

.PP
Definition at line \fB35\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.Initialization ()"

.PP
Definition at line \fB113\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundChain (int soundChainID)"

.PP
Definition at line \fB505\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundChain (string soundChainName)"

.PP
Definition at line \fB519\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundChunk (int soundChunkID)"

.PP
Definition at line \fB509\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundChunk (string soundChunkName)"

.PP
Definition at line \fB523\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundPiece (int soundPieceID)"

.PP
Definition at line \fB513\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.multiplayerSoundPiece (string soundPieceName)"

.PP
Definition at line \fB527\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayChain (int soundChainID)"

.PP
Definition at line \fB534\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayChain (string soundChainName)"

.PP
Definition at line \fB555\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayChunk (int soundChunkID)"

.PP
Definition at line \fB540\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayChunk (string soundChunkName)"

.PP
Definition at line \fB575\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayPiece (int soundPieceID)"

.PP
Definition at line \fB546\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "void SoundGeneralDynamicsMultiplayerPhoton\&.PlayPiece (string soundPieceName)"

.PP
Definition at line \fB592\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
