.TH "SoundGeneralDynamicsMultiplayerPhoton.SoundChunk" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamicsMultiplayerPhoton.SoundChunk
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBchunkName\fP"
.br
.ti -1c
.RI "\fBSoundPiece\fP[] \fBsoundPieces\fP"
.br
.ti -1c
.RI "bool \fBplayOnStart\fP"
.br
.ti -1c
.RI "int \fBloopNum\fP"
.br
.ti -1c
.RI "float \fBVolume\fP = 1f"
.br
.ti -1c
.RI "float \fBPitch\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB704\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.chunkName"

.PP
Definition at line \fB706\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "int SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.loopNum"

.PP
Definition at line \fB713\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.Pitch = 1f"

.PP
Definition at line \fB717\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "bool SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.playOnStart"

.PP
Definition at line \fB711\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "\fBSoundPiece\fP [] SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.soundPieces"

.PP
Definition at line \fB707\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundChunk\&.Volume = 1f"

.PP
Definition at line \fB715\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
