.TH "SoundObjectImpact" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundObjectImpact
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBcalculateResistance\fP (float soundPower, float thickness)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBdensity\fP"
.br
.ti -1c
.RI "float \fBrebound\fP"
.br
.ti -1c
.RI "float \fBabsorption\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSoundObjectImpact\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "float SoundObjectImpact\&.calculateResistance (float soundPower, float thickness)"

.PP
Definition at line \fB11\fP of file \fBSoundObjectImpact\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SoundObjectImpact\&.absorption"

.PP
Definition at line \fB9\fP of file \fBSoundObjectImpact\&.cs\fP\&.
.SS "float SoundObjectImpact\&.density"

.PP
Definition at line \fB7\fP of file \fBSoundObjectImpact\&.cs\fP\&.
.SS "float SoundObjectImpact\&.rebound"

.PP
Definition at line \fB8\fP of file \fBSoundObjectImpact\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
