.TH "SoundGeneralDynamics.SoundChunk" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamics.SoundChunk
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBchunkName\fP"
.br
.ti -1c
.RI "\fBSoundPiece\fP[] \fBsoundPieces\fP"
.br
.ti -1c
.RI "int \fBloopNum\fP"
.br
.ti -1c
.RI "float \fBVolume\fP = 1f"
.br
.ti -1c
.RI "float \fBPitch\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB416\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SoundGeneralDynamics\&.SoundChunk\&.chunkName"

.PP
Definition at line \fB418\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "int SoundGeneralDynamics\&.SoundChunk\&.loopNum"

.PP
Definition at line \fB423\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundChunk\&.Pitch = 1f"

.PP
Definition at line \fB427\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "\fBSoundPiece\fP [] SoundGeneralDynamics\&.SoundChunk\&.soundPieces"

.PP
Definition at line \fB419\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.
.SS "float SoundGeneralDynamics\&.SoundChunk\&.Volume = 1f"

.PP
Definition at line \fB425\fP of file \fBSoundGeneralDynamics\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
