.TH "SoundVisualAssets" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundVisualAssets
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBVisualSprite\fP"
.br
.ti -1c
.RI "float \fBXVisualDistanceFromCenter\fP"
.br
.ti -1c
.RI "float \fBYVisualDistanceFromCenter\fP"
.br
.ti -1c
.RI "float \fBXSize\fP"
.br
.ti -1c
.RI "float \fBYSize\fP"
.br
.ti -1c
.RI "float \fBVisualAngle\fP"
.br
.ti -1c
.RI "float \fBVisualAngleBuffer\fP"
.br
.ti -1c
.RI "float \fBActiveTime\fP"
.br
.ti -1c
.RI "float \fBBufferTime\fP"
.br
.ti -1c
.RI "GameObject \fBObjectImage\fP"
.br
.ti -1c
.RI "RectTransform \fBRectImage\fP"
.br
.ti -1c
.RI "Image \fBComponentImage\fP"
.br
.ti -1c
.RI "float \fBcurrentTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB824\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SoundVisualAssets\&.ActiveTime"

.PP
Definition at line \fB841\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.BufferTime"

.PP
Definition at line \fB843\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "Image SoundVisualAssets\&.ComponentImage"

.PP
Definition at line \fB847\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.currentTime"

.PP
Definition at line \fB848\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "GameObject SoundVisualAssets\&.ObjectImage"

.PP
Definition at line \fB845\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "RectTransform SoundVisualAssets\&.RectImage"

.PP
Definition at line \fB846\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.VisualAngle"

.PP
Definition at line \fB837\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.VisualAngleBuffer"

.PP
Definition at line \fB839\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "Sprite SoundVisualAssets\&.VisualSprite"

.PP
Definition at line \fB827\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.XSize"

.PP
Definition at line \fB833\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.XVisualDistanceFromCenter"

.PP
Definition at line \fB829\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.YSize"

.PP
Definition at line \fB835\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundVisualAssets\&.YVisualDistanceFromCenter"

.PP
Definition at line \fB831\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
