.TH "SoundGeneralDynamicsMultiplayerPhoton.SoundChain" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoundGeneralDynamicsMultiplayerPhoton.SoundChain
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBchainName\fP"
.br
.ti -1c
.RI "\fBSoundChunk\fP[] \fBsoundChunks\fP"
.br
.ti -1c
.RI "bool \fBplayOnStart\fP"
.br
.ti -1c
.RI "int \fBloopNum\fP"
.br
.ti -1c
.RI "float \fBVolume\fP = 1f"
.br
.ti -1c
.RI "float \fBPitch\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB686\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.chainName"

.PP
Definition at line \fB688\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "int SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.loopNum"

.PP
Definition at line \fB695\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.Pitch = 1f"

.PP
Definition at line \fB699\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "bool SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.playOnStart"

.PP
Definition at line \fB693\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "\fBSoundChunk\fP [] SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.soundChunks"

.PP
Definition at line \fB689\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.
.SS "float SoundGeneralDynamicsMultiplayerPhoton\&.SoundChain\&.Volume = 1f"

.PP
Definition at line \fB697\fP of file \fBSoundGeneralDynamicsMultiplayerPhoton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
