.TH "SpawnManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpawnManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Transform \fBGetSpawnpoint\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSpawnManager\fP \fBInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSpawnManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Transform SpawnManager\&.GetSpawnpoint ()"

.PP
Definition at line \fB17\fP of file \fBSpawnManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSpawnManager\fP SpawnManager\&.Instance\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBSpawnManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
