.TH "StarterAssets.ThirdPersonController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.ThirdPersonController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBMoveSpeed\fP = 2\&.0f"
.br
.ti -1c
.RI "float \fBSprintSpeed\fP = 5\&.335f"
.br
.ti -1c
.RI "float \fBRotationSmoothTime\fP = 0\&.12f"
.br
.ti -1c
.RI "float \fBSpeedChangeRate\fP = 10\&.0f"
.br
.ti -1c
.RI "float \fBJumpHeight\fP = 1\&.2f"
.br
.ti -1c
.RI "float \fBGravity\fP = \-15\&.0f"
.br
.ti -1c
.RI "float \fBJumpTimeout\fP = 0\&.50f"
.br
.ti -1c
.RI "float \fBFallTimeout\fP = 0\&.15f"
.br
.ti -1c
.RI "bool \fBGrounded\fP = true"
.br
.ti -1c
.RI "float \fBGroundedOffset\fP = \-0\&.14f"
.br
.ti -1c
.RI "float \fBGroundedRadius\fP = 0\&.28f"
.br
.ti -1c
.RI "LayerMask \fBGroundLayers\fP"
.br
.ti -1c
.RI "GameObject \fBCinemachineCameraTarget\fP"
.br
.ti -1c
.RI "float \fBTopClamp\fP = 70\&.0f"
.br
.ti -1c
.RI "float \fBBottomClamp\fP = \-30\&.0f"
.br
.ti -1c
.RI "float \fBCameraAngleOverride\fP = 0\&.0f"
.br
.ti -1c
.RI "bool \fBLockCameraPosition\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBThirdPersonController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float StarterAssets\&.ThirdPersonController\&.BottomClamp = \-30\&.0f"

.PP
Definition at line \fB56\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.CameraAngleOverride = 0\&.0f"

.PP
Definition at line \fB58\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "GameObject StarterAssets\&.ThirdPersonController\&.CinemachineCameraTarget"

.PP
Definition at line \fB52\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.FallTimeout = 0\&.15f"

.PP
Definition at line \fB38\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.Gravity = \-15\&.0f"

.PP
Definition at line \fB32\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "bool StarterAssets\&.ThirdPersonController\&.Grounded = true"

.PP
Definition at line \fB42\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.GroundedOffset = \-0\&.14f"

.PP
Definition at line \fB44\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.GroundedRadius = 0\&.28f"

.PP
Definition at line \fB46\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "LayerMask StarterAssets\&.ThirdPersonController\&.GroundLayers"

.PP
Definition at line \fB48\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.JumpHeight = 1\&.2f"

.PP
Definition at line \fB30\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.JumpTimeout = 0\&.50f"

.PP
Definition at line \fB36\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "bool StarterAssets\&.ThirdPersonController\&.LockCameraPosition = false"

.PP
Definition at line \fB60\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.MoveSpeed = 2\&.0f"

.PP
Definition at line \fB19\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.RotationSmoothTime = 0\&.12f"

.PP
Definition at line \fB24\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.SpeedChangeRate = 10\&.0f"

.PP
Definition at line \fB26\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.SprintSpeed = 5\&.335f"

.PP
Definition at line \fB21\fP of file \fBThirdPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.ThirdPersonController\&.TopClamp = 70\&.0f"

.PP
Definition at line \fB54\fP of file \fBThirdPersonController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
