.TH "StarterAssets.FirstPersonController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.FirstPersonController
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBMoveSpeed\fP = 4\&.0f"
.br
.ti -1c
.RI "float \fBSprintSpeed\fP = 6\&.0f"
.br
.ti -1c
.RI "float \fBRotationSpeed\fP = 1\&.0f"
.br
.ti -1c
.RI "float \fBSpeedChangeRate\fP = 10\&.0f"
.br
.ti -1c
.RI "float \fBJumpHeight\fP = 1\&.2f"
.br
.ti -1c
.RI "float \fBGravity\fP = \-15\&.0f"
.br
.ti -1c
.RI "float \fBJumpTimeout\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBFallTimeout\fP = 0\&.15f"
.br
.ti -1c
.RI "bool \fBGrounded\fP = true"
.br
.ti -1c
.RI "float \fBGroundedOffset\fP = \-0\&.14f"
.br
.ti -1c
.RI "float \fBGroundedRadius\fP = 0\&.5f"
.br
.ti -1c
.RI "LayerMask \fBGroundLayers\fP"
.br
.ti -1c
.RI "GameObject \fBCinemachineCameraTarget\fP"
.br
.ti -1c
.RI "float \fBTopClamp\fP = 90\&.0f"
.br
.ti -1c
.RI "float \fBBottomClamp\fP = \-90\&.0f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBFirstPersonController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float StarterAssets\&.FirstPersonController\&.BottomClamp = \-90\&.0f"

.PP
Definition at line \fB55\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "GameObject StarterAssets\&.FirstPersonController\&.CinemachineCameraTarget"

.PP
Definition at line \fB51\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.FallTimeout = 0\&.15f"

.PP
Definition at line \fB37\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.Gravity = \-15\&.0f"

.PP
Definition at line \fB31\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "bool StarterAssets\&.FirstPersonController\&.Grounded = true"

.PP
Definition at line \fB41\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.GroundedOffset = \-0\&.14f"

.PP
Definition at line \fB43\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.GroundedRadius = 0\&.5f"

.PP
Definition at line \fB45\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "LayerMask StarterAssets\&.FirstPersonController\&.GroundLayers"

.PP
Definition at line \fB47\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.JumpHeight = 1\&.2f"

.PP
Definition at line \fB29\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.JumpTimeout = 0\&.1f"

.PP
Definition at line \fB35\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.MoveSpeed = 4\&.0f"

.PP
Definition at line \fB19\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.RotationSpeed = 1\&.0f"

.PP
Definition at line \fB23\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.SpeedChangeRate = 10\&.0f"

.PP
Definition at line \fB25\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.SprintSpeed = 6\&.0f"

.PP
Definition at line \fB21\fP of file \fBFirstPersonController\&.cs\fP\&.
.SS "float StarterAssets\&.FirstPersonController\&.TopClamp = 90\&.0f"

.PP
Definition at line \fB53\fP of file \fBFirstPersonController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
