.TH "StarterAssets.ScriptingDefineUtils" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.ScriptingDefineUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCheckScriptingDefine\fP (string scriptingDefine)"
.br
.ti -1c
.RI "static void \fBSetScriptingDefine\fP (string scriptingDefine)"
.br
.ti -1c
.RI "static void \fBRemoveScriptingDefine\fP (string scriptingDefine)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBScriptingDefineUtils\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool StarterAssets\&.ScriptingDefineUtils\&.CheckScriptingDefine (string scriptingDefine)\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBScriptingDefineUtils\&.cs\fP\&.
.SS "static void StarterAssets\&.ScriptingDefineUtils\&.RemoveScriptingDefine (string scriptingDefine)\fC [static]\fP"

.PP
Definition at line \fB25\fP of file \fBScriptingDefineUtils\&.cs\fP\&.
.SS "static void StarterAssets\&.ScriptingDefineUtils\&.SetScriptingDefine (string scriptingDefine)\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBScriptingDefineUtils\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
