.TH "StarterAssets" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFirstPersonController\fP"
.br
.ti -1c
.RI "class \fBPackageChecker\fP"
.br
.ti -1c
.RI "class \fBPurrFPSHumanCharacterController\fP"
.br
.ti -1c
.RI "class \fBScriptingDefineUtils\fP"
.br
.ti -1c
.RI "class \fBStarterAssetsDeployMenu\fP"
.br
.ti -1c
.RI "class \fBStarterAssetsInputs\fP"
.br
.ti -1c
.RI "class \fBThirdPersonController\fP"
.br
.ti -1c
.RI "class \fBUICanvasControllerInput\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
