.TH "StarterAssets.UICanvasControllerInput" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.UICanvasControllerInput
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVirtualMoveInput\fP (Vector2 virtualMoveDirection)"
.br
.ti -1c
.RI "void \fBVirtualLookInput\fP (Vector2 virtualLookDirection)"
.br
.ti -1c
.RI "void \fBVirtualJumpInput\fP (bool virtualJumpState)"
.br
.ti -1c
.RI "void \fBVirtualSprintInput\fP (bool virtualSprintState)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStarterAssetsInputs\fP \fBstarterAssetsInputs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUICanvasControllerInput\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void StarterAssets\&.UICanvasControllerInput\&.VirtualJumpInput (bool virtualJumpState)"

.PP
Definition at line \fB21\fP of file \fBUICanvasControllerInput\&.cs\fP\&.
.SS "void StarterAssets\&.UICanvasControllerInput\&.VirtualLookInput (Vector2 virtualLookDirection)"

.PP
Definition at line \fB16\fP of file \fBUICanvasControllerInput\&.cs\fP\&.
.SS "void StarterAssets\&.UICanvasControllerInput\&.VirtualMoveInput (Vector2 virtualMoveDirection)"

.PP
Definition at line \fB11\fP of file \fBUICanvasControllerInput\&.cs\fP\&.
.SS "void StarterAssets\&.UICanvasControllerInput\&.VirtualSprintInput (bool virtualSprintState)"

.PP
Definition at line \fB26\fP of file \fBUICanvasControllerInput\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStarterAssetsInputs\fP StarterAssets\&.UICanvasControllerInput\&.starterAssetsInputs"

.PP
Definition at line \fB9\fP of file \fBUICanvasControllerInput\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
