.TH "StarterAssets.PackageChecker.PackageEntry" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.PackageChecker.PackageEntry
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBversion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB263\fP of file \fBPackageChecker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string StarterAssets\&.PackageChecker\&.PackageEntry\&.name"

.PP
Definition at line \fB265\fP of file \fBPackageChecker\&.cs\fP\&.
.SS "string StarterAssets\&.PackageChecker\&.PackageEntry\&.version"

.PP
Definition at line \fB266\fP of file \fBPackageChecker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
