.TH "StarterAssets.StarterAssetsDeployMenu" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarterAssets.StarterAssetsDeployMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject, ScriptableObject, and ScriptableObject\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBMenuRoot\fP = 'Tools/Starter Assets'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBStarterAssetsInstallPath\fP\fC [get]\fP"
.br
.RI "Get the relative root path of the \fBStarterAssets\fP install - works even if user has moved it within Assets, so long as user does not mess with the internal hierarchy of the \fBStarterAssets\fP folder "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBFirstPersonStarterAssetsDeployMenu\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string StarterAssets\&.StarterAssetsDeployMenu\&.MenuRoot = 'Tools/Starter Assets'\fC [static]\fP"

.PP
Definition at line \fB13\fP of file \fBStarterAssetsDeployMenu\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string StarterAssets\&.StarterAssetsDeployMenu\&.StarterAssetsInstallPath\fC [static]\fP, \fC [get]\fP"

.PP
Get the relative root path of the \fBStarterAssets\fP install - works even if user has moved it within Assets, so long as user does not mess with the internal hierarchy of the \fBStarterAssets\fP folder 
.PP
Definition at line \fB37\fP of file \fBStarterAssetsDeployMenu\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
