.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Actions/StartPlayableDirector.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/WeiYuen/Scripts/_Bin/Kit/Interactive/Runtime/Actions/StartPlayableDirector.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\&.StartPlayableDirector\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSInt\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\fP"
.br
.ti -1c
.RI "namespace \fBSInt\&.QuickTask\&.Gamekit3D\&.KitHelpers\&.GameCommands\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
