.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/FlatKit/Shaders/Editor/StylizedSurfaceEditor.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/FlatKit/Shaders/Editor/StylizedSurfaceEditor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStylizedSurfaceEditor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSurfaceType\fP { \fBOpaque\fP, \fBTransparent\fP }"
.br
.ti -1c
.RI "enum \fBBlendMode\fP { \fBAlpha\fP, \fBPremultiply\fP, \fBAdditive\fP, \fBMultiply\fP }"
.br
.ti -1c
.RI "enum \fBRenderFace\fP { \fBFront\fP = 2, \fBBack\fP = 1, \fBBoth\fP = 0 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlendMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAlpha \fP\fP
.TP
\fB\fIPremultiply \fP\fP
.TP
\fB\fIAdditive \fP\fP
.TP
\fB\fIMultiply \fP\fP
.PP
Definition at line \fB15\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.
.SS "enum \fBRenderFace\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFront \fP\fP
.TP
\fB\fIBack \fP\fP
.TP
\fB\fIBoth \fP\fP
.PP
Definition at line \fB22\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.
.SS "enum \fBSurfaceType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOpaque \fP\fP
.TP
\fB\fITransparent \fP\fP
.PP
Definition at line \fB10\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
