.TH "StylizedSurfaceEditor" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StylizedSurfaceEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseShaderGUI\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBMaterialChanged\fP (Material material)"
.br
.ti -1c
.RI "override void \fBOnGUI\fP (MaterialEditor materialEditor, MaterialProperty[] properties)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void StylizedSurfaceEditor\&.MaterialChanged (Material material)"

.PP
Definition at line \fB70\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.
.SS "override void StylizedSurfaceEditor\&.OnGUI (MaterialEditor materialEditor, MaterialProperty[] properties)"

.PP
Definition at line \fB72\fP of file \fBStylizedSurfaceEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
