.TH "SuperBasicController" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuperBasicController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPhoton\&.Pun\&.Simple\&.NetComponent\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBis2D\fP = false"
.br
.ti -1c
.RI "float \fBturnSpeed\fP = 150f"
.br
.ti -1c
.RI "float \fBmoveSpeed\fP = 4f"
.br
.ti -1c
.RI "bool \fBautoMove\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBSuperBasicController\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SuperBasicController\&.autoMove = true"

.PP
Definition at line \fB25\fP of file \fBSuperBasicController\&.cs\fP\&.
.SS "bool SuperBasicController\&.is2D = false"

.PP
Definition at line \fB18\fP of file \fBSuperBasicController\&.cs\fP\&.
.SS "float SuperBasicController\&.moveSpeed = 4f"

.PP
Definition at line \fB23\fP of file \fBSuperBasicController\&.cs\fP\&.
.SS "float SuperBasicController\&.turnSpeed = 150f"

.PP
Definition at line \fB21\fP of file \fBSuperBasicController\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
