.TH "SweepZone" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SweepZone
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleAnimator\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBonTrigger\fP"
.br
.ti -1c
.RI "Button \fBsweepButton\fP"
.br
.ti -1c
.RI "bool \fBinSweepZone\fP = false"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSweepZone\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSweepZone\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SweepZone\&.HandleAnimator ()"

.PP
Definition at line \fB30\fP of file \fBSweepZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSweepZone\fP SweepZone\&.instance\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBSweepZone\&.cs\fP\&.
.SS "bool SweepZone\&.inSweepZone = false"

.PP
Definition at line \fB18\fP of file \fBSweepZone\&.cs\fP\&.
.SS "UnityEvent SweepZone\&.onTrigger"

.PP
Definition at line \fB11\fP of file \fBSweepZone\&.cs\fP\&.
.SS "Button SweepZone\&.sweepButton"

.PP
Definition at line \fB14\fP of file \fBSweepZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
