.TH "SwitchingPlayers" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SwitchingPlayers
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBcatUiScreen\fP"
.br
.ti -1c
.RI "GameObject \fBcatCamera\fP"
.br
.ti -1c
.RI "GameObject \fBcatTasklist\fP"
.br
.ti -1c
.RI "GameObject \fBhumanUiScreen\fP"
.br
.ti -1c
.RI "GameObject \fBhumanCamera\fP"
.br
.ti -1c
.RI "GameObject \fBhumanThirdPov\fP"
.br
.ti -1c
.RI "GameObject \fBhumanTasklist\fP"
.br
.ti -1c
.RI "GameObject \fBcatIcon\fP"
.br
.ti -1c
.RI "GameObject \fBhumanIcon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SwitchingPlayers\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB22\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject SwitchingPlayers\&.catCamera"

.PP
Definition at line \fB9\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.catIcon"

.PP
Definition at line \fB19\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.catTasklist"

.PP
Definition at line \fB10\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.catUiScreen"

.PP
Definition at line \fB8\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.humanCamera"

.PP
Definition at line \fB14\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.humanIcon"

.PP
Definition at line \fB20\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.humanTasklist"

.PP
Definition at line \fB16\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.humanThirdPov"

.PP
Definition at line \fB15\fP of file \fBSwitchingPlayers\&.cs\fP\&.
.SS "GameObject SwitchingPlayers\&.humanUiScreen"

.PP
Definition at line \fB13\fP of file \fBSwitchingPlayers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
