.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/Interfaces/SyncObjInterfaces.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Core/Interfaces/SyncObjInterfaces.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.ISyncAnimator\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IApplyOrder\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IAdjustableApplyOrder\fP"
.br
.RI "Flags a ApplyOrder as adjustable in the inspector\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IReadyable\fP"
.br
.RI "Flags a \fBSyncObject\fP as needing to recieve a complete frame or manually call netObj\&.SyncObjSetReady() before the netObj is flagged as ready\&. "
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IUseKeyframes\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IDeltaFrameChangeDetect\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.ISerializationOptional\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnNetSerialize\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnCriticallyLateFrame\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnSnapshot\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnInterpolate\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnQuantize\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnCaptureState\fP"
.br
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.IOnAuthorityChanged\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
