.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncState/SyncSpawnTimer.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/SyncState/SyncSpawnTimer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBPhoton\&.Pun\&.Simple\&.ISpawnController\fP"
.br
.RI "Indicates component controls the spawning and despawning of an object\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\fP"
.br
.RI "Automatically generates ChangeState events on the \fBSyncState\fP based on timers and triggers\&. "
.ti -1c
.RI "class \fBPhoton\&.Pun\&.Simple\&.SyncSpawnTimer\&.Frame\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
