.TH "TextAnimation" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextAnimation
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtext\fP"
.br
.ti -1c
.RI "float \fBtextDelay\fP = 0\&.1f"
.br
.ti -1c
.RI "string \fBfullText\fP"
.br
.ti -1c
.RI "bool \fBfinishText\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTextAnimation\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TextAnimation\&.finishText"

.PP
Definition at line \fB11\fP of file \fBTextAnimation\&.cs\fP\&.
.SS "string TextAnimation\&.fullText"

.PP
Definition at line \fB10\fP of file \fBTextAnimation\&.cs\fP\&.
.SS "GameObject TextAnimation\&.text"

.PP
Definition at line \fB8\fP of file \fBTextAnimation\&.cs\fP\&.
.SS "float TextAnimation\&.textDelay = 0\&.1f"

.PP
Definition at line \fB9\fP of file \fBTextAnimation\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
