.TH "Toy" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Toy
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtoyboxFull\fP"
.br
.ti -1c
.RI "GameObject \fBtoys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBToy\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject Toy\&.toyboxFull"

.PP
Definition at line \fB7\fP of file \fBToy\&.cs\fP\&.
.SS "GameObject Toy\&.toys"

.PP
Definition at line \fB8\fP of file \fBToy\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
