.TH "TransitionToLobby" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransitionToLobby
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlobbySceneName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTransitionToLobby\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TransitionToLobby\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB12\fP of file \fBTransitionToLobby\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string TransitionToLobby\&.lobbySceneName"

.PP
Definition at line \fB10\fP of file \fBTransitionToLobby\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
