.TH "TrapMechanicButtonScript" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrapMechanicButtonScript
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCaptureCat\fP ()"
.br
.ti -1c
.RI "void \fBTrapInstantiate\fP ()"
.br
.ti -1c
.RI "void \fBEnableCatCanvas\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBcatPlayer\fP"
.br
.ti -1c
.RI "GameObject \fBtrapPrefab\fP"
.br
.ti -1c
.RI "bool \fBtrapNow\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBTrapMechanicButtonScript\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TrapMechanicButtonScript\&.CaptureCat ()"

.PP
Definition at line \fB34\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SS "void TrapMechanicButtonScript\&.EnableCatCanvas ()"

.PP
Definition at line \fB78\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SS "void TrapMechanicButtonScript\&.TrapInstantiate ()"

.PP
Definition at line \fB55\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject TrapMechanicButtonScript\&.catPlayer"

.PP
Definition at line \fB11\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SS "\fBTrapMechanicButtonScript\fP TrapMechanicButtonScript\&.instance\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SS "bool TrapMechanicButtonScript\&.trapNow"

.PP
Definition at line \fB15\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.
.SS "GameObject TrapMechanicButtonScript\&.trapPrefab"

.PP
Definition at line \fB12\fP of file \fBTrapMechanicButtonScript\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
