.TH "TriggerAreaTuto" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggerAreaTuto
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTutorial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBCheckIfHappening\fP ()"
.br
.ti -1c
.RI "void \fBOnTriggerEnter\fP (Collider collision)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBwhoIsWalkingToTrigger\fP"
.br
.ti -1c
.RI "GameObject \fBtutoBGPanel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTriggerAreaTuto\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void TriggerAreaTuto\&.CheckIfHappening ()\fC [virtual]\fP"

.PP
Reimplemented from \fBTutorial\fP\&.
.PP
Definition at line \fB16\fP of file \fBTriggerAreaTuto\&.cs\fP\&.
.SS "void TriggerAreaTuto\&.OnTriggerEnter (Collider collision)"

.PP
Definition at line \fB30\fP of file \fBTriggerAreaTuto\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject TriggerAreaTuto\&.tutoBGPanel"

.PP
Definition at line \fB12\fP of file \fBTriggerAreaTuto\&.cs\fP\&.
.SS "Transform TriggerAreaTuto\&.whoIsWalkingToTrigger"

.PP
Definition at line \fB9\fP of file \fBTriggerAreaTuto\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
