.TH "TriggeringZone" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TriggeringZone
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleAnimator\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent \fBonTrigger\fP"
.br
.ti -1c
.RI "Button \fBtrapButton\fP"
.br
.ti -1c
.RI "Button \fBfixButton\fP"
.br
.ti -1c
.RI "Button \fBinteractButton\fP"
.br
.ti -1c
.RI "\fBBreakableFurniture\fP \fBfurniture\fP"
.br
.ti -1c
.RI "\fBFixDestroyedFurniture\fP[] \fBbrokenFurn\fP"
.br
.ti -1c
.RI "bool \fBcatInRange\fP = false"
.br
.ti -1c
.RI "bool \fBbrokenProp\fP = false"
.br
.ti -1c
.RI "bool \fBreadyTrap\fP = false"
.br
.ti -1c
.RI "Animator \fBanimator\fP"
.br
.ti -1c
.RI "\fBPhotonView\fP \fBPV\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBTriggeringZone\fP \fBinstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTriggeringZone\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TriggeringZone\&.HandleAnimator ()"

.PP
Definition at line \fB36\fP of file \fBTriggeringZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Animator TriggeringZone\&.animator"

.PP
Definition at line \fB29\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "\fBFixDestroyedFurniture\fP [] TriggeringZone\&.brokenFurn"

.PP
Definition at line \fB21\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "bool TriggeringZone\&.brokenProp = false"

.PP
Definition at line \fB25\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "bool TriggeringZone\&.catInRange = false"

.PP
Definition at line \fB24\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "Button TriggeringZone\&.fixButton"

.PP
Definition at line \fB15\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "\fBBreakableFurniture\fP TriggeringZone\&.furniture"

.PP
Definition at line \fB20\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "\fBTriggeringZone\fP TriggeringZone\&.instance\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "Button TriggeringZone\&.interactButton"

.PP
Definition at line \fB17\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "UnityEvent TriggeringZone\&.onTrigger"

.PP
Definition at line \fB11\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "\fBPhotonView\fP TriggeringZone\&.PV"

.PP
Definition at line \fB30\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "bool TriggeringZone\&.readyTrap = false"

.PP
Definition at line \fB26\fP of file \fBTriggeringZone\&.cs\fP\&.
.SS "Button TriggeringZone\&.trapButton"

.PP
Definition at line \fB14\fP of file \fBTriggeringZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
