.TH "TutoManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TutoManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTutorial\fP \fBTutoSequence\fP (int order)"
.br
.ti -1c
.RI "void \fBNextTutorial\fP (int onSequence)"
.br
.ti -1c
.RI "void \fBTutoComplete\fP ()"
.br
.ti -1c
.RI "void \fBEndTuto\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBTutorial\fP > \fBtutorials\fP = new List<\fBTutorial\fP>()"
.br
.ti -1c
.RI "Text \fBdialogue\fP"
.br
.ti -1c
.RI "string \fBendTutorialMessage\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBTutoManager\fP \fBinstance\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTutoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TutoManager\&.EndTuto ()"

.PP
Definition at line \fB77\fP of file \fBTutoManager\&.cs\fP\&.
.SS "void TutoManager\&.NextTutorial (int onSequence)"

.PP
Definition at line \fB59\fP of file \fBTutoManager\&.cs\fP\&.
.SS "void TutoManager\&.TutoComplete ()"

.PP
Definition at line \fB72\fP of file \fBTutoManager\&.cs\fP\&.
.SS "\fBTutorial\fP TutoManager\&.TutoSequence (int order)"

.PP
Definition at line \fB45\fP of file \fBTutoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Text TutoManager\&.dialogue"

.PP
Definition at line \fB12\fP of file \fBTutoManager\&.cs\fP\&.
.SS "string TutoManager\&.endTutorialMessage"

.PP
Definition at line \fB13\fP of file \fBTutoManager\&.cs\fP\&.
.SS "List<\fBTutorial\fP> TutoManager\&.tutorials = new List<\fBTutorial\fP>()"

.PP
Definition at line \fB9\fP of file \fBTutoManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTutoManager\fP TutoManager\&.instance\fC [static]\fP, \fC [get]\fP"

.PP
Definition at line \fB18\fP of file \fBTutoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
