.TH "UIManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSingleton< UIManager >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSwitchMenu\fP (\fBUIType\fP _uiType)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBUIManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UIManager\&.Awake ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSingleton< UIManager >\fP\&.
.PP
Definition at line \fB19\fP of file \fBUIManager\&.cs\fP\&.
.SS "void UIManager\&.SwitchMenu (\fBUIType\fP _uiType)"

.PP
Definition at line \fB30\fP of file \fBUIManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
