.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI/UIManager.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/_Developers/Adriana/Scripts/UI/UIManager.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUIManager\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBUIType\fP { \fBMainMenu\fP, \fBOptions\fP, \fBCredit\fP, \fBPopUp\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBUIType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMainMenu \fP\fP
.TP
\fB\fIOptions \fP\fP
.TP
\fB\fICredit \fP\fP
.TP
\fB\fIPopUp \fP\fP
.PP
Definition at line \fB6\fP of file \fBUIManager\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
