.TH "UIVirtualJoystick" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIVirtualJoystick
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerDownHandler, IDragHandler, and IPointerUpHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBcontainerRect\fP"
.br
.ti -1c
.RI "RectTransform \fBhandleRect\fP"
.br
.ti -1c
.RI "float \fBjoystickRange\fP = 50f"
.br
.ti -1c
.RI "float \fBmagnitudeMultiplier\fP = 1f"
.br
.ti -1c
.RI "bool \fBinvertXOutputValue\fP"
.br
.ti -1c
.RI "bool \fBinvertYOutputValue\fP"
.br
.ti -1c
.RI "UnityEvent< Vector2 > \fBjoystickOutputEvent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UIVirtualJoystick\&.OnDrag (PointerEventData eventData)"

.PP
Definition at line \fB42\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "void UIVirtualJoystick\&.OnPointerDown (PointerEventData eventData)"

.PP
Definition at line \fB37\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "void UIVirtualJoystick\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB62\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "RectTransform UIVirtualJoystick\&.containerRect"

.PP
Definition at line \fB12\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "RectTransform UIVirtualJoystick\&.handleRect"

.PP
Definition at line \fB13\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "bool UIVirtualJoystick\&.invertXOutputValue"

.PP
Definition at line \fB18\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "bool UIVirtualJoystick\&.invertYOutputValue"

.PP
Definition at line \fB19\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "UnityEvent<Vector2> UIVirtualJoystick\&.joystickOutputEvent"

.PP
Definition at line \fB22\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "float UIVirtualJoystick\&.joystickRange = 50f"

.PP
Definition at line \fB16\fP of file \fBUIVirtualJoystick\&.cs\fP\&.
.SS "float UIVirtualJoystick\&.magnitudeMultiplier = 1f"

.PP
Definition at line \fB17\fP of file \fBUIVirtualJoystick\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
