.TH "UIVirtualTouchZone" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIVirtualTouchZone
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerDownHandler, IDragHandler, and IPointerUpHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectTransform \fBcontainerRect\fP"
.br
.ti -1c
.RI "RectTransform \fBhandleRect\fP"
.br
.ti -1c
.RI "bool \fBclampToMagnitude\fP"
.br
.ti -1c
.RI "float \fBmagnitudeMultiplier\fP = 1f"
.br
.ti -1c
.RI "bool \fBinvertXOutputValue\fP"
.br
.ti -1c
.RI "bool \fBinvertYOutputValue\fP"
.br
.ti -1c
.RI "UnityEvent< Vector2 > \fBtouchZoneOutputEvent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UIVirtualTouchZone\&.OnDrag (PointerEventData eventData)"

.PP
Definition at line \fB52\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "void UIVirtualTouchZone\&.OnPointerDown (PointerEventData eventData)"

.PP
Definition at line \fB40\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "void UIVirtualTouchZone\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB66\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UIVirtualTouchZone\&.clampToMagnitude"

.PP
Definition at line \fB15\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "RectTransform UIVirtualTouchZone\&.containerRect"

.PP
Definition at line \fB11\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "RectTransform UIVirtualTouchZone\&.handleRect"

.PP
Definition at line \fB12\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "bool UIVirtualTouchZone\&.invertXOutputValue"

.PP
Definition at line \fB17\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "bool UIVirtualTouchZone\&.invertYOutputValue"

.PP
Definition at line \fB18\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "float UIVirtualTouchZone\&.magnitudeMultiplier = 1f"

.PP
Definition at line \fB16\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.
.SS "UnityEvent<Vector2> UIVirtualTouchZone\&.touchZoneOutputEvent"

.PP
Definition at line \fB25\fP of file \fBUIVirtualTouchZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
