.TH "UIVirtualButton" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIVirtualButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour, IPointerDownHandler, IPointerUpHandler, and IPointerClickHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnPointerDown\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBOnPointerClick\fP (PointerEventData eventData)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UnityEvent< bool > \fBbuttonStateOutputEvent\fP"
.br
.ti -1c
.RI "UnityEvent \fBbuttonClickOutputEvent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUIVirtualButton\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UIVirtualButton\&.OnPointerClick (PointerEventData eventData)"

.PP
Definition at line \fB24\fP of file \fBUIVirtualButton\&.cs\fP\&.
.SS "void UIVirtualButton\&.OnPointerDown (PointerEventData eventData)"

.PP
Definition at line \fB14\fP of file \fBUIVirtualButton\&.cs\fP\&.
.SS "void UIVirtualButton\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB19\fP of file \fBUIVirtualButton\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UnityEvent UIVirtualButton\&.buttonClickOutputEvent"

.PP
Definition at line \fB12\fP of file \fBUIVirtualButton\&.cs\fP\&.
.SS "UnityEvent<bool> UIVirtualButton\&.buttonStateOutputEvent"

.PP
Definition at line \fB11\fP of file \fBUIVirtualButton\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
