.TH "UnityStandardAssets.Characters.ThirdPerson.PunDemos" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnityStandardAssets.Characters.ThirdPerson.PunDemos
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThirdPersonCharacter\fP"
.br
.ti -1c
.RI "class \fBThirdPersonUserControl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
