.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncVitals/VitalsSystem/DataTypes/VitalNameType.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/Simple/Components/ContactSystems/SyncVitals/VitalsSystem/DataTypes/VitalNameType.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPhoton\&.Pun\&.Simple\&.VitalNameType\fP"
.br
.RI "TODO: Make this a generic when working on \&.net versions that supports enum generic constraint\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Simple\fP"
.br
.RI "A collection of interfaces SyncObjects can implement\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Simple\&.VitalType\fP { \fBPhoton\&.Pun\&.Simple\&.None\fP, \fBPhoton\&.Pun\&.Simple\&.Custom\fP, \fBPhoton\&.Pun\&.Simple\&.Health\fP, \fBPhoton\&.Pun\&.Simple\&.Armor\fP, \fBPhoton\&.Pun\&.Simple\&.Shield\fP, \fBPhoton\&.Pun\&.Simple\&.Energy\fP, \fBPhoton\&.Pun\&.Simple\&.Mana\fP, \fBPhoton\&.Pun\&.Simple\&.Rage\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
