.TH "C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/DemoProcedural/Scripts/WorldGenerator.cs" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_SSDSPEEDUP/2021/GPS/gps2_purrpatrator/GPS2_Purrpatrator/Assets/Photon/PhotonUnityNetworking/Demos/DemoProcedural/Scripts/WorldGenerator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhoton\&.Pun\&.Demo\&.Procedural\&.WorldGenerator\fP"
.br
.RI "The World Generator creates a world based on four options the current MasterClient can set\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPhoton\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Demo\fP"
.br
.ti -1c
.RI "namespace \fBPhoton\&.Pun\&.Demo\&.Procedural\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBHashtable\fP = ExitGames\&.Client\&.Photon\&.Hashtable"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Demo\&.Procedural\&.WorldSize\fP { \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Tiny\fP = 16, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Small\fP = 32, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Medium\fP = 64, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Large\fP = 128 }"
.br
.RI "Describes the Size of the World\&. "
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Demo\&.Procedural\&.WorldType\fP { \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Flat\fP = 4, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Standard\fP = 8, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Mountain\fP = 16 }"
.br
.RI "Describes the type of the generated world\&. "
.ti -1c
.RI "enum \fBPhoton\&.Pun\&.Demo\&.Procedural\&.ClusterSize\fP { \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Small\fP = 4, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Medium\fP = 16, \fBPhoton\&.Pun\&.Demo\&.Procedural\&.Large\fP = 64 }"
.br
.RI "Describes how many Blocks are part of one CLuster\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBHashtable\fP =  ExitGames\&.Client\&.Photon\&.Hashtable"

.PP
Definition at line \fB4\fP of file \fBWorldGenerator\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
