.TH "ZoneManager" 3 "Mon Apr 18 2022" "Purrpatrator User manual" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBsweep\fP"
.br
.ti -1c
.RI "GameObject \fBwipe\fP"
.br
.ti -1c
.RI "GameObject \fBwater\fP"
.br
.ti -1c
.RI "GameObject \fBdust\fP"
.br
.ti -1c
.RI "GameObject \fBtrash\fP"
.br
.ti -1c
.RI "GameObject \fBtoybox\fP"
.br
.ti -1c
.RI "GameObject \fBfridge\fP"
.br
.ti -1c
.RI "GameObject \fBdefrost\fP"
.br
.ti -1c
.RI "GameObject \fBbroom\fP"
.br
.ti -1c
.RI "GameObject \fBduster\fP"
.br
.ti -1c
.RI "GameObject \fBcloth\fP"
.br
.ti -1c
.RI "GameObject \fBtoy\fP"
.br
.ti -1c
.RI "GameObject \fBwatercan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBZoneManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject ZoneManager\&.broom"

.PP
Definition at line \fB18\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.cloth"

.PP
Definition at line \fB20\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.defrost"

.PP
Definition at line \fB15\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.dust"

.PP
Definition at line \fB11\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.duster"

.PP
Definition at line \fB19\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.fridge"

.PP
Definition at line \fB14\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.sweep"

.PP
Definition at line \fB8\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.toy"

.PP
Definition at line \fB21\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.toybox"

.PP
Definition at line \fB13\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.trash"

.PP
Definition at line \fB12\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.water"

.PP
Definition at line \fB10\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.watercan"

.PP
Definition at line \fB22\fP of file \fBZoneManager\&.cs\fP\&.
.SS "GameObject ZoneManager\&.wipe"

.PP
Definition at line \fB9\fP of file \fBZoneManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Purrpatrator User manual from the source code\&.
